### ISSUE TITLE
[Display news. Gallery view ]  There is no user's added picture  in the news.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1021]
**Environment:**  **Firefox Version 78.0.2 (64-bit)** / Windows 10 Home 1903
OS: Windows 10 Pro, Version 2004
Browser: Mozilla Firefox, Version: 82.0.3

**Reproducable:**  always
**Build found:**  commit 19.11.2020

**Steps to reproduce**
1. Open  **Firefox Version 78.0.2 (64-bit)**
2. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
3. Click on 'Eco news' link in the header.

**Actual result**

There are no added images in the news.

![Disappear picture](https://user-images.githubusercontent.com/64972476/88712641-b5f44800-d122-11ea-8138-0b50ce8889cc.jpg)

**Expected result**

The added image of the user is displayed in the News items

![Appear picture](https://user-images.githubusercontent.com/64972476/88712852-0b305980-d123-11ea-9f28-a8c8b8921463.jpg)

**User story and test case links**
User story  [#459](https://github.com/ita-social-projects/GreenCity/issues/459)
Test case [GC-674](https://jira.softserve.academy/browse/GC-674)

[Verify that created news with max parametrs (no spaces) are displayed correctly in different views and resolutions] (https://jira.softserve.academy/browse/GC-679)

**P.S. Bug is reproduce in Browser Firefox**

**Comment by Gusvarov** [comment]
Duplicate of #880

**Comment by natalinapr** [comment]
Not fixed

**Comment by natalinapr** [comment]
Not fixed

**Comment by JimHolman1199** [comment]
problem saving images -> BE part
