### ISSUE TITLE
[Header] Incorrect alignment of header on screen resolution 1440px. 1024px, 768px, 576px, 320px.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1022]
**Environment:** Firefox Version 78.0.2 (64-bit) / Windows 10 Home 1903
**Reproducable:** always
**Build found:** commit  e1be472

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click F12;
5. Change screen resolution on 1440px, 1024px, 768px, 576px, 320px.

**Actual result**
**1440**
Location of logo on the  header doesn't meet to mock up. Header should be a static and doesn't change due-to scrolling.
![768 header](https://user-images.githubusercontent.com/64972476/88727042-826fe880-d137-11ea-9831-56f0bed82407.jpg)
**1024**
![1024](https://user-images.githubusercontent.com/64972476/89191031-01877580-d5ab-11ea-851f-9523adc4e861.jpg)
**768**
![768](https://user-images.githubusercontent.com/64972476/89191061-0cdaa100-d5ab-11ea-9d90-1d66ae93a8be.jpg)
**576**
![576](https://user-images.githubusercontent.com/64972476/89191083-182dcc80-d5ab-11ea-9c0d-aa91f8580077.jpg)
**320**
![320](https://user-images.githubusercontent.com/64972476/89191107-22e86180-d5ab-11ea-98bb-99bd850939cc.jpg)

**Expected result**
The position of the logo on the header must be in sync with the main page.

![768 header correct](https://user-images.githubusercontent.com/64972476/88727552-82241d00-d138-11ea-834f-f0208d1d28be.jpg)

**User story and test case links**
User story [#354](https://github.com/ita-social-projects/GreenCity/issues/354)

**Comment by JustinCooper43** [comment]
The error has not been fixed. At **1440px** and **1024px** resolution. The exact distance cannot be measured, because there is no logo image.

![12](https://user-images.githubusercontent.com/64972476/90692673-30296f80-e27e-11ea-9462-b1b7d66dcb65.jpg)

**Comment by JustinCooper43** [comment]
Bug was not fixed. 

**Actual result**
Logo image has incorrect size (**94px x 24px**)  when resolution **576px**. 

![Incirrect logo](https://user-images.githubusercontent.com/64972476/91643682-1df9bf00-ea3e-11ea-8fd0-654b01371439.jpg)

**Expected result**
Logo image has to size (**136px x 36px**) when resolution **576px**
![Incirrect logo 136 36](https://user-images.githubusercontent.com/64972476/91643738-9496bc80-ea3e-11ea-8532-d630c38eb07e.jpg)

**Comment by tatiana404** [comment]
The size of the logo does not coincide with the mock up. The logo in application consists of one part and has the size 136x36 in all resolutions. Logo in mock up is divided into two parts and has size : 36x36 and 94x12 on 1440px,1024px, 768px, 576px  resolutions
![320 logo](https://user-images.githubusercontent.com/65060199/100939370-d84a0800-34fe-11eb-9a76-e1ed1f7dd365.jpg)
![1440 logo](https://user-images.githubusercontent.com/65060199/100939381-db44f880-34fe-11eb-80d1-aba0efe03b39.jpg)
![logo 1 1024 mock](https://user-images.githubusercontent.com/65060199/100939419-eac44180-34fe-11eb-8e64-f0a068704c55.jpg)
![logo 2 1024 mock](https://user-images.githubusercontent.com/65060199/100939442-f31c7c80-34fe-11eb-8118-ea73b46d0052.jpg)
![logo 1 320 mock](https://user-images.githubusercontent.com/65060199/100939475-fdd71180-34fe-11eb-8c14-bebe9d653cbf.jpg)
![logo 2 320 mock](https://user-images.githubusercontent.com/65060199/100939489-029bc580-34ff-11eb-89e2-6d2512f948b7.jpg)





 and 24x24 and 66x8 on 320px  resolution
