### ISSUE TITLE
[Comment] There is no 'reply' button to 'my comment' block on the News single page 

### ISSUE THREAD

**Issue by YuliyaTimosh** [ita-social-projects/GreenCity#1025]
Environment: Windows 10 Pro (64-bit), Google Chrome 81.0.4044.138 (64-bit)
Reproducible: Always
Build: commit 0140903

**Spets po reproduce:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome and sign in with valid data (e.g. Email <koton86272@example.com>, Password <Qw@rt111>)
2. Click on the 'Eco News' link on the header of the page.
3. Choose any news and add the comment to it.

**Actual result:**
There is no 'Reply' button to the comment.
![2020-07-29 12_18_15-Eco news](https://user-images.githubusercontent.com/46763919/88782001-bf6ac800-d195-11ea-8875-b6de6e70b488.png)

**Expected result:**
The 'Reply' button is presented in the bottom of the comment.
![2020-07-29 12_21_53-ITA Greencity – Figma](https://user-images.githubusercontent.com/46763919/88782327-1ffa0500-d196-11ea-9614-fb86853c2fd0.png)

Mockups: https://www.figma.com/file/K5qc43VjSkWVz8mobuovxs/ITA-Greencity?node-id=101%3A2508

User story: #763 
[Testcase](https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je%3Azephyr-tests-page#test-cycles-tab)

**Comment by Gusvarov** [comment]
Reply button visible only, if comment isn't yours
