### ISSUE TITLE
[Comment] Wrong magrin of the comments block on the News Single Page at 768, 576 and 320 screen resolutions.

### ISSUE THREAD

**Issue by YuliyaTimosh** [ita-social-projects/GreenCity#1030]
Environment: Windows 10 Pro (64-bit), Google Chrome 81.0.4044.138 (64-bit)
Reproducible: Always
Build: commit 0140903

**Spets po reproduce:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome and sign in with valid data (e.g. Email koton86272@example.com, Password Qw@rt111)
2. Click on the 'Eco News' link on the header of the page.
3. Choose any news and add the comment to it.
4. Change the screen resolution to 768.
 4.1. Change the screen resolution to 576.
 4.2. Change the screen resolution to 320.

**Actual result:**

![position](https://user-images.githubusercontent.com/46763919/88789463-70299500-d19f-11ea-815f-e63c8ce871f8.png)

**Expected result:**

![position 2](https://user-images.githubusercontent.com/46763919/88789179-14f7a280-d19f-11ea-8073-3fda3d5533b5.png)

Mockups: https://www.figma.com/file/K5qc43VjSkWVz8mobuovxs/ITA-Greencity?node-id=101%3A2508

User story: #763

**Comment by Volodymyr-Danyliv** [comment]
At 320px resolution done, but other two screen need to fix:
![image](https://user-images.githubusercontent.com/29017153/90153096-3658b100-dd91-11ea-971c-5572e36a43bb.png)
