### ISSUE TITLE
[Comment] Wrong possition of 'Comment' button on the News Single Page at 576 and 320 screen resolutions.

### ISSUE THREAD

**Issue by YuliyaTimosh** [ita-social-projects/GreenCity#1031]
Environment: Windows 10 Pro (64-bit), Google Chrome 81.0.4044.138 (64-bit)
Reproducible: Always
Build: commit 0140903

**Spets po reproduce:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome and sign in with valid data (e.g. Email koton86272@example.com, Password Qw@rt111)
2. Click on the 'Eco News' link on the header of the page.
3. Choose any news and add the comment to it.
4. Change the screen resolution to 576..
4.1. Change the screen resolution to 320.

**Actual result:**

576 screen resolution
![576 resolution actual](https://user-images.githubusercontent.com/46763919/88795430-ad465500-d1a8-11ea-8896-8314722c6ee2.png)

320 screen resolution
![320 resolution actual](https://user-images.githubusercontent.com/46763919/88795429-acadbe80-d1a8-11ea-8e81-cb5b66c061b5.png)

**Expected result:**

576 screen resolution
![576 resolution expected](https://user-images.githubusercontent.com/46763919/88795533-dcf55d00-d1a8-11ea-9df4-9a183293ac16.png)

320 screen resolution
![320 resolution expected](https://user-images.githubusercontent.com/46763919/88795530-dc5cc680-d1a8-11ea-8e3a-7a43ac9ca00c.png)

Mockups: https://www.figma.com/file/K5qc43VjSkWVz8mobuovxs/ITA-Greencity?node-id=101%3A2508

User story: #763

**Comment by Volodymyr-Danyliv** [comment]
At 320px resolution need more space between textbox and button:
![image](https://user-images.githubusercontent.com/29017153/90147260-ae6fa880-dd8a-11ea-95c4-a02b0dd21290.png)
At 576 px need to fix.
