### ISSUE TITLE
[API] Incorrect Response body when the system doesn't allow to add the file of inappropriate format when creating new Tips & Tricks

### ISSUE THREAD

**Issue by Volodymyr-Danyliv** [ita-social-projects/GreenCity#1042]
**Environment:** Windows 8.1 Pro, Google Chrome Version 84.0.4147.89 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** commit [a08a11d]((https://github.com/ita-social-projects/GreenCityClient/commit/a08a11d80e76e1c8b9bb9dff7843222b752e8bdd)).

**Preconditions**

1. Go to Swagger: https://greencity.azurewebsites.net/swagger-ui.html#/ ;
2. Sign in with controller Post /ownSecurity/signIn;
3. Use token to authorize in Swagger
4. Download test data: [.docx](https://github.com/ita-social-projects/GreenCity/files/4852578/471.Test.Design.docx), [.pdf](https://github.com/ita-social-projects/GreenCity/files/4852602/ITA.atomic.tets.design.1.pdf)

**Steps to reproduce**

1. Open tips-and-tricks-controller request via /tipsandtricks
2. Add new tips & tricks
3. Add file .pdf or .docx format in "Image" field (see attachments)
4. Add request
{
"image":	"471.Test.Design.docx",
"source":	"http://www.greeneducationfoundation.org/nationalgreenweeksub/waste-reduction-tips/tips-to-use-less-plastic.html",
"tags":		["lifehacks", "green thinking"],
"text":		"Stop using plastic straws, even in restaurants. If a straw is a must, purchase a reusable stainless steel or glass straw Use a reusable produce bag. A single plastic bag can take 1,000 years to degrade. Purchase or make your own reusable produce bag and be sure to wash them often!",
"title":	"Tips to Use Less Plastic"
}
5. Click on the "Execute" button

**Actual result**
Responce code == 400.
{
  "message": "save.image: Download PNG or JPEG only."
}

**Expected result**
Responce code == 400.
{
"message": "Download PNG or JPEG only."
}

**User story and test case links**
User story [#537](https://github.com/ita-social-projects/GreenCity/issues/537)
Test case [GC-1205](https://jira.softserve.academy/browse/GC-120)

**Comment by MarDatsko** [comment]
@Volodymyr-Danyliv Sorry, but I think you are using the wrong model for the test, for this controller should use "TipsAndTricksDtoRequest" model.

**Comment by Volodymyr-Danyliv** [comment]
Thank you for your attention. I corrected the test condition. Look again now, please.
