### ISSUE TITLE
[Display news. Single view] Incorrect alignment for date and author fields.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1043]
**Environment:** Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducable:** always
**Build found:** commit  e1be472

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Ckick on any  created news item 

**Actual result**
Alignment for date and author don't meet mock up. They are not centered.

![Wrong date and name](https://user-images.githubusercontent.com/64972476/88859546-97fe1480-d202-11ea-9ab6-b9d9d01cfe4d.jpg)

**Expected result**
Alignment for date and author should meet mock up

![Correct date and name](https://user-images.githubusercontent.com/64972476/88913854-66b92f00-d26a-11ea-8e7d-bfe69aa046da.jpg)

**User story and test case links**
User story [#498 ](https://github.com/ita-social-projects/GreenCity/issues/498)
[GC-679](https://jira.softserve.academy/browse/GC-679)

**Comment by RomanDeveloperAcc** [comment]
Not relevant. According to BA's decision, author's name is priority and this alignment is correct
