### ISSUE TITLE
[Display news: Single view] Text in 'Source' field is not located in borders of field  

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1044]
**Environment:**  Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducable:** always
**Build found:** commit  e1be472

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Ckick on any created news item

**Actual result**
Text in 'Source' field is not located in borders of field 
![Wrong source](https://user-images.githubusercontent.com/64972476/88860789-312e2a80-d205-11ea-9b50-3cc97f66d4ac.jpg)

**Expected result**
The text in the "Source" field should  located within the borders of the field and aligned with the main text

**User story and test case links**
User story [#498](https://github.com/ita-social-projects/GreenCity/issues/498)
[GC-679](https://jira.softserve.academy/browse/GC-679)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
