### ISSUE TITLE
[Header] The buttons are slightly overlapping with each other (IE11)

### ISSUE THREAD

**Issue by Volodymyr-Danyliv** [ita-social-projects/GreenCity#1050]
**Environment:** Windows 8.1 Pro, Internet Explorer 11 (Version: 11.0.9600.19155).
**Reproducible:** always.
**Build found:** commit [874f344](https://github.com/ita-social-projects/GreenCityClient/commit/874f344b7089ff1a598c3a1c4c3a8182eec28d6f)

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient'

**Actual result**
The logo and "Eco news" buttons intersect. And also the cell of the drop-down list of the language switch is too narrow at the 1366x768 screen resolution.
![image](https://user-images.githubusercontent.com/29017153/88923608-a8ea6c80-d27a-11ea-8dab-62f298da2d4d.png)

**Expected result**
The Header should be like in the mockup

**User story and test case links**
User story [#354](https://github.com/ita-social-projects/GreenCity/issues/354).

**Comment by RomanDeveloperAcc** [comment]
Not relevant
