### ISSUE TITLE
[Eco news: single view] News recommendations are displayed in one column

### ISSUE THREAD

**Issue by Volodymyr-Danyliv** [ita-social-projects/GreenCity#1053]
**Environment:** Windows 8.1 Pro, Internet Explorer 11 (Version: 11.0.9600.19155).
**Reproducible:** always.
**Build found:** commit [e80ed98](https://github.com/ita-social-projects/GreenCityClient/commit/e80ed98f2ea4ad441872bcc643d805123ef9f971)

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/news'
2. Click on some news item
3. Scroll down to news recommendations widget

**Actual result**
The news recommendations are displayed in one column at 1366x768 screen resolution:
![image](https://user-images.githubusercontent.com/29017153/88938621-3daa9580-d28e-11ea-95c9-359d64a92286.png)

**Expected result**
The three columns display three news recommendations (according to mockup).

**User story and test case links**
User story [#500](https://github.com/ita-social-projects/GreenCity/issues/500).

**Comment by RomanDeveloperAcc** [comment]
Not relevant
