### ISSUE TITLE
[Edit news] Button 'Edit news' is not active.

### ISSUE THREAD

**Issue by BohdanPrysiazhnyi** [ita-social-projects/GreenCity#1060]
Windows 10 home 64bit. 
Google Chrome 84.0.4147.105
Reproducable: always.
Build found: commit 61a3545

Preconditions
1. Log in to the https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Create Eco news.

Steps to reproduce
1. Go to (https://ita-social-projects.github.io/GreenCityClient/#/welcome)
2. Click on 'Eco news'
3. Find eco news created by you.
4. Open this eco news.
5. Click on 'Edit news'

Actual result
Editing eco news is impossible. Button 'Edit news' is not active
![edit bug](https://user-images.githubusercontent.com/68583636/89046610-dfe18080-d355-11ea-9bd0-584c11f89953.jpg)

Expected result
You should be able to edit your news

Postconditions
You might be delete your news

User story [#660 ](url)

**Comment by JustinCooper43** [comment]
Bug was not fixed 

[Video](https://drive.google.com/file/d/1aAxw3DwOTWp_k7M1SRulPyaflZfwUwS7/view?usp=sharing)
