### ISSUE TITLE
[Header] Font of text  in 'Language'  drop-down menu incorrect. Looks of drop down menu doesn't meet mock up.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1074]
**Environment:**  Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducable:** always
**Build found:** commit  9c376b1

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click  'Language'  drop-down menu on Header

**Actual result**
Font of text doesn't meet a mock up.
1. Font incorrect
2. Location (drop-down menu  stays under button)
3. Size one item (41px*22px)
4. Menu doesn't have  shadow

![Mozilla](https://user-images.githubusercontent.com/64972476/89185496-fdeff080-d5a2-11ea-9b48-5e634d0373b2.jpg)

**Expected result**
 Looks of drop down menu should meet mock up.
1. Font correct
2. Location (drop-down menu  doesn't stay under button)
3. Size one item (61px*44px)
4. Menu has shadow

![FIGMA](https://user-images.githubusercontent.com/64972476/89192852-ccc8ed80-d5ad-11ea-9290-a3898289c49f.jpg)

**User story and test case links**
User story ##558

**Comment by RomanDeveloperAcc** [comment]
Not relevant
