### ISSUE TITLE
[Common] Only the last 20 comments are displayed (The page pagination is not work). 

### ISSUE THREAD

**Issue by YuliyaTimosh** [ita-social-projects/GreenCity#1085]
Environment: Windows 10 Pro (64-bit), Google Chrome 81.0.4044.138 (64-bit)
Reproducible: Always
Build: commit 0140903

**Spets to reproduce:**

1. Go to DataBase and use  this file (https://drive.google.com/file/d/1FonV39b4yk9WSfuCOtqKRuR3J74cupbu/view?usp=sharing) to insert comments to the news. 
2. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome ( login: koton86272@rm2rf.com password: Qw@rt111 )
3. Found the news with title 'Very simple test like previous. verify contentType filed with more than 20 characters' **or go throuhg the** link https://ita-social-projects.github.io/GreenCityClient/#/news/1660
4. Go to the comment block.

**Actual result:**

The pagination with only 2 number of pages.

**Expected result:**

The pagination shoud be with 4 number of pages.

![2020-08-04 12_56_19-Eco news](https://user-images.githubusercontent.com/46763919/89280920-fb000900-d651-11ea-9f93-899055c366dd.png)

User Story #767

**Comment by Volodymyr-Danyliv** [comment]
Only the last 20 comments are displayed (10 per page), although a total of 50 comments have been written:
![image](https://user-images.githubusercontent.com/29017153/91236807-a415bd00-e741-11ea-8299-e5349fcf474a.png)

**Comment by RomanDeveloperAcc** [comment]
Please, check one more time. Not relevant
