### ISSUE TITLE
BL for user info about my profile

### ISSUE THREAD

**Issue by Gusvarov** [ita-social-projects/GreenCity#1102]
### Summary
As a user, i want to see info about my profile

### Acceptance Criteria
We must display:
1. Profile avatar if it exists, if not, display default picture
2. Username
3. User City if it exists, if not, display nothing
4. User status
5. User credo if it exists,  if not, display nothing
6. User Rate if it more than 0, if not, display 0
Edit profile icon isn't a part of a story
Social networks isn't a part of a story

### Tasks 
1. [x] Profile avatar 
2. [x] Username
3. [x] City
4. [x] Status
5. [x] Rate
6. [x] User credo
7. [x] Pull Request
8. [x] Merge

### API
https://greencity.azurewebsites.net/user/userId/profile/

{
  "city": "string",
  "firstName": "string",
  "profilePicturePath": "string",
  "rating": 0,
  "showEcoPlace": true,
  "showLocation": true,
  "showShoppingList": true,
  "socialNetworks": [
    "string"
  ],
  "userCredo": "string"
}

### Mockups
![image](https://user-images.githubusercontent.com/54152415/89557190-1d914e00-d81b-11ea-9021-d7bb222e96e7.png)

**Comment by iskoryk** [comment]
The US #1102 edited, added “The 'City' field containing the city and country name”.
