### ISSUE TITLE
Deletion of existent place in the list as Admin

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#112]
As an admin I want to delete existent place so that the list with places will not increase with unactual places.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/64131825-eed15300-cdd3-11e9-9edb-bba3d64ec95e.png)

![image](https://user-images.githubusercontent.com/53810790/64131955-ceee5f00-cdd4-11e9-892b-818fc5e971ca.png)

Acceptance criteria:

1. "Delete" icon button is available on the "Places" tab near each row on the right side. It is shown as icon of recycle bin.

2. WHEN an admin see "Places" tab, THEN he can click on one of "Delete" icon button near each row.

3. WHEN an admin clicks "Delete" icon button THEN he/she see popup with the next information appears:
a. Text - "Are you sure you want to delete this item?"
b. "Cancel" button
c. "Delete" button

4. WHEN an admin clicks "Cancel" button THEN Admin see active row in the list with the same status as it was.

5. WHEN an admin clicks "Delete" button THEN status for mentioned row changes to "Deleted".

**Comment by rsyvulko** [comment]
Not relevant.
