### ISSUE TITLE
Bulk deletion of places by Admin

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#113]
**As an Admin I want to delete existent places in the list so that it will be easier to clear data with places quicker.**

Mockup:

**Acceptance criteria:**

1. System shall display a "Delete" button and checkboxes near each of the row in the list of places in the Admin page.

2. **Deletion:**
    a. WHEN an admin checks more that one row, THEN "Delete" button become enabled.

    b. WHEN an admin clicks "Delete" button, THEN popup with the next information appears:
      1. Text - "Are you sure you want to delete these items?"
      2. "Yes" button
      3. "Cancel" button

    c. WHEN an admin clicks "Yes" button, THEN status of checked rows should be changed to "deleted".

    d. WHEN an admin clicks "Cancel" button, THEN checked rows should be visible in list of places as they were.

**Comment by rsyvulko** [comment]
Not relevant.
