### ISSUE TITLE
[Header] Logo image and magnifier image are absent on the header

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1186]
**Environment:** Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducible:** always
**Build found:** c6df48b

**Steps to reproduce**
1.Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome

**Actual result**
Logo image and magnifier image are absent on the header
![Logo and search](https://user-images.githubusercontent.com/64972476/90693775-11c47380-e280-11ea-81a7-de5840374016.jpg)

**Expected result**
Header has to containe logo and magnifier images
![Logo and search correct](https://user-images.githubusercontent.com/64972476/90693892-505a2e00-e280-11ea-92ae-56c328dfdadc.jpg)

**P.S.**
Related bug  [#1022](https://github.com/ita-social-projects/GreenCity/issues/1022)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
