### ISSUE TITLE
[Header] 'Magnifier' image has got incorrect size.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1192]
**Environment:** Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducible:** always
**Build found:** 4a2d9d1

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome

**Actual result**
'Magnifier' image has got **26px x 26px** size

![Magnifier image](https://user-images.githubusercontent.com/64972476/90957670-cbe1f800-e497-11ea-85dc-b9b60415fa8e.jpg)

**Expected result**
'Magnifier' image has to **11px x 11px** size

![Magnifier image correct](https://user-images.githubusercontent.com/64972476/90957679-e87e3000-e497-11ea-8734-e02e2dec3e86.jpg)

**Comment by skrebetsnataliia** [comment]
According to mockup search icon has 16px 16px  in header component 
![image](https://user-images.githubusercontent.com/50843868/98026471-d6aff600-1e13-11eb-88b9-94ef6630ee69.png)
In search pop-up it has 24px 24px 
![image](https://user-images.githubusercontent.com/50843868/98026738-43c38b80-1e14-11eb-94da-0d03d7eadcbb.png)

**Comment by tatiana404** [comment]
The search pop-up has 16x16 size
![0-02-05-fb0fb0b6143d24960517425c6cbd1e09b2374a68fd01634873a63265c19374cc_8db7df28](https://user-images.githubusercontent.com/65060199/98929877-7f311a80-24e4-11eb-93c3-32ab21d135c7.jpg)

**Comment by skrebetsnataliia** [comment]
according to mockup search icon in header shoul be 16px 16px
in the mockup
![image](https://user-images.githubusercontent.com/50843868/99085737-3dca6900-25d1-11eb-986f-0cd93f4f45f9.png)
in the projects 
![image](https://user-images.githubusercontent.com/50843868/99086076-b29da300-25d1-11eb-8d61-ac782d412b77.png)

https://www.figma.com/file/K5qc43VjSkWVz8mobuovxs/ITA-Greencity?node-id=2213%3A399
https://ita-social-projects.github.io/GreenCityClient/#/welcome

**Comment by tatiana404** [comment]
Thank you for your letter, sorry for mistake...
