### ISSUE TITLE
[Sign in - forgot password] Incorrect error message is displayed when user enters valid not registered e-mail

### ISSUE THREAD

**Issue by stasgoodman** [ita-social-projects/GreenCity#1201]
**Environment:** Google Chrome, version 84.0.4147.135, Linux Mint 19.3 Tricia, 
**Reproducible:** always
**Build found:** commit 4a2d9d1

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign in'
3. Click on 'Forgot password'
4. Set valid not registered e-mail (e.g: "Anymail@gmail.com")
5. Click on 'Submit a login link' button

**Actual result**
There is error message is displayed 'Bad email or password: Anymail@gmail.com' 
![image](https://user-images.githubusercontent.com/69276462/90986261-193e9200-e58a-11ea-91ad-0cdf55e55ace.png)

**Expected result**
There is error message is displayed 'The user does not exist by this email: Anymail@gmail.com'
![image](https://user-images.githubusercontent.com/69276462/90986675-45a7dd80-e58d-11ea-90a4-dca1729edf90.png)

**Postconditions**
- Change to Ukrainian language 
- Repeat steps to reproduce
- There is a wrong error message displayed 

**User story and test case links**
User story #472
See Clarifications 06.05.2020

**Comment by JimHolman1199** [comment]
not sure it's still relevant
Can you check this again?

![Screenshot 2020-10-24 at 20 34 23](https://user-images.githubusercontent.com/46226026/97088263-60074180-1638-11eb-9f74-fe5b0074dbc8.png)

**Comment by ProstoLeleka** [comment]
@JimHolman1199 I think it's ok now.
