### ISSUE TITLE
[News page loading] Message text has got wrong size and wrong location (When resolution 576px, 320px)

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1202]
**Environment:** Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducible:** always
**Build found:** 4a2d9d1

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click 'Create news'
5. Input valid values to all mandatory fields
6. Click 'Publish'

**Actual result**
**1.**
Text "Please wait while loading..." has got **441,683px x 48px** size.
Text "Your news is loading to the website. Please wait until the page refreshes" has got **511,417px x 24px** size.

![Save news 1 incorrect](https://user-images.githubusercontent.com/64972476/90978020-06f53180-e553-11ea-822f-fe6dc909506b.jpg)
![Save news incorrect](https://user-images.githubusercontent.com/64972476/90978027-12485d00-e553-11ea-8eb0-f68cfa332d8d.jpg)

**2.**
**Resolution 576px**
"Your news is loading to the website. Please wait until the page refreshes" located on the two line.
![Save news 1 incorrect 576px](https://user-images.githubusercontent.com/64972476/90978059-5a677f80-e553-11ea-8a44-5db2a4579ab6.jpg)

**3.**
**Resolution 320px**
"Please wait while loading..."  and "Your news is loading to the website. Please wait until the page refreshes" have got the same located
![Save news 1 incorrect 320px](https://user-images.githubusercontent.com/64972476/90978062-5fc4ca00-e553-11ea-8ef0-c70321cd6417.jpg)

**Expected result**
**1.**
Text "Please wait while loading..." has to **435px x 48px** size.
Text "Your news is loading to the website. Please wait until the page refreshes" has to **526px x 32px** size.
![Save news 1 correct](https://user-images.githubusercontent.com/64972476/90978065-6c492280-e553-11ea-93b1-479b1ceb7f7b.jpg)
![Save news correct](https://user-images.githubusercontent.com/64972476/90978068-73703080-e553-11ea-8dea-7c5dfbfe61cf.jpg)
**2.**
"Your news is loading to the website. Please wait until the page refreshes" should be located on the **one** line when resolution **576px**
![Save news correct 576px](https://user-images.githubusercontent.com/64972476/90978117-dfeb2f80-e553-11ea-891f-6877cb862ea2.jpg)
**3.**
"Please wait while loading..."  and "Your news is loading to the website. Please wait until the page refreshes" have to the different located and meet mockup
![Save news correct 320px](https://user-images.githubusercontent.com/64972476/90978127-fee9c180-e553-11ea-8f37-f2121775c3b0.jpg)

**Comment by natalinapr** [comment]
**Actual result:**
1. **1440px:** Text "Please wait while loading..." and text "Your news is loading to the website. Please wait until the page refreshes" have got the same location. Text "Please wait while loading..." is located on the two lines.
![image](https://user-images.githubusercontent.com/62031226/98943319-f91ecf00-24f7-11eb-9f81-e66abe7e59de.png)
2. **1024px:** Text "Please wait while loading..." and text "Your news is loading to the website. Please wait until the page refreshes" have got the same location. Text "Please wait while loading..." is located on the two lines.
![image](https://user-images.githubusercontent.com/62031226/98943319-f91ecf00-24f7-11eb-9f81-e66abe7e59de.png)
3. **768px:** Text "Please wait while loading..." and text "Your news is loading to the website. Please wait until the page refreshes" have got the same location. Text "Please wait while loading..." is located on the two lines.
![image](https://user-images.githubusercontent.com/62031226/98943319-f91ecf00-24f7-11eb-9f81-e66abe7e59de.png)
4. **576px:** Text "Please wait while loading..." is located on the two lines. Text "Your news is loading to the website. Please wait until the page refreshes" is located on the two lines.
![image](https://user-images.githubusercontent.com/62031226/98944312-83b3fe00-24f9-11eb-8b98-c07fddc7a4fe.png)



**Expected result:**
1. **1440px:** Text "Please wait while loading..." and text "Your news is loading to the website. Please wait until the page refreshes" have got different locations(one under the other). Text "Please wait while loading..." is located on one line.
![image](https://user-images.githubusercontent.com/62031226/98944832-587dde80-24fa-11eb-9131-305d310594cd.png)
2. **1024px:** Text "Please wait while loading..." and text "Your news is loading to the website. Please wait until the page refreshes" have got different locations(one under the other). Text "Please wait while loading..." is located on one line.
![image](https://user-images.githubusercontent.com/62031226/98945019-9b3fb680-24fa-11eb-9e83-40e15c2bb05a.png)
3. **768px:** Text "Please wait while loading..." and text "Your news is loading to the website. Please wait until the page refreshes" have got different locations(one under the other). Text "Please wait while loading..." is located on one line.
![image](https://user-images.githubusercontent.com/62031226/98945160-cc1feb80-24fa-11eb-94ab-48091d13bae3.png)
4. **576px:** Text "Please wait while loading..." is located on one line. Text "Your news is loading to the website. Please wait until the page refreshes" is located on one line.
![image](https://user-images.githubusercontent.com/62031226/98945313-04bfc500-24fb-11eb-8832-e795fffa5aa7.png)

**Comment by oprotyniak** [comment]
Bug is not fixed.

**Comment by IrynaShlyakhetko** [comment]
defect is fixed
