### ISSUE TITLE
[News page loading] Page doesn't refresh after creating news.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1203]
**Environment:** Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducible:** always
**Build found:** 4a2d9d1

**Steps to reproduce**

1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click 'Create news'
5. Input valid values to all mandatory fields
6. Click 'Publish'

**Actual result**
Page doesn't automate refresh after creating news.
![Save news stop](https://user-images.githubusercontent.com/64972476/90979193-2cd30400-e55c-11ea-9674-7ea4874476e5.jpg)

**Expected result**
Page have to automate refresh after creating news

**Comment by JimHolman1199** [comment]
well...it works for me...
soooo, can you check this again? pleease)
