### ISSUE TITLE
[News page loading] Imposible create two news with same title.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1206]
**Environment:** Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducible:** sometimes
**Build found:** 4a2d9d1

**Steps to reproduce**
1. **Open Firefox**
2. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
3. Log into the system.
4. Click on 'Eco news' link in the header.
5. Click 'Create news'
6. Input valid values to all mandatory fields
7. Click 'Publish'
8. Reapete 4 and 5 steps
9. In 'Title' field input same value from 6 step
10. Click 'Publish'

**Actual result**
Imposible create news with exist title in DB  

![Error](https://user-images.githubusercontent.com/64972476/90987456-cf5aa980-e593-11ea-85ce-72216ea3d97d.jpg)

**Expected result**
Title field is not uniqe. Create two news with same title is possible.

**Comment by bohdana1** [comment]
User cannot create news after entering valid values to all mandatory fields and Click 'Publish'. Verification of creating news with exist title in DB is impossible.

**Comment by luchward** [comment]
It is impossible to reproduce this bug.

**Comment by bohdana1** [comment]
Hello!
User cannot create any news after entering valid values to all mandatory
fields and Click 'Publish'. That's why verification of creating news with
exist title in DB is impossible because I as an user cannot create any
news((( and I cannot create two news with the same title((((

чт, 26 лист. 2020 о 22:19 Eduard Luchuk <notifications@github.com> пише:

**Comment by oprotyniak** [comment]
I can't create news. I tried different browsers and users, waited for some time after clicking on 'Publish' button.
![image](https://user-images.githubusercontent.com/73852063/100931687-88197880-34f3-11eb-9c53-fcf737b4dff5.png)
