### ISSUE TITLE
[Sign in - forgot password] Wrong marrgin between elements ('Email', 'Error message', 'back to Sign In')

### ISSUE THREAD

**Issue by stasgoodman** [ita-social-projects/GreenCity#1207]
**Environment:** Google Chrome, version 84.0.4147.135, Linux Mint 19.3 Tricia,
**Reproducible:** always
**Build found:** commit 4a2d9d1

**Steps to reproduce**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign in'
3. Click on 'Forgot password'
4. Set valid not registered e-mail (e.g: "Anymail@gmail.com")
5. Click on 'Submit a login link' button

**Actual result**
There is a margin between 
- 'Email' input field and error message (21px)
- in div.mentioned-password  (200px 121px 40px 56px;)
![image](https://user-images.githubusercontent.com/69276462/90987284-70e0fb80-e592-11ea-83e8-d6e7f65ed96f.png)

**Expected result**
There is a margin between 
- 'Email' input field and error message (0px)
- in div.mentioned-password  (200px 107px 40px 56px;)
![image](https://user-images.githubusercontent.com/69276462/90987241-18116300-e592-11ea-8b8c-a160ef7ba96a.png)

**User story and test case links**
User story #472

**Comment by Plilia** [comment]
The bug didn't fix
![1207](https://user-images.githubusercontent.com/12970841/92130729-c082bb00-ee0d-11ea-89bb-1b1981ab11ea.jpg)
