### ISSUE TITLE
[Home page] Wrong question in the ‘Cups section’

### ISSUE THREAD

**Issue by SolkaNik** [ita-social-projects/GreenCity#1220]
**Environment:** Windows 10 Home x64; browsers: Google Chrome v. 84.0.4147.135; Firefox v. 79.0; Microsoft Edge 44.19041.423.0.
**Reproducible:** always.
**Build found:** commit 4e8d686.

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/welcome'.
2. Scroll down and check the question in the ‘Cups section’ (En version).
3. Change the localization to 'Uk' and check the question in the ‘Cups section’.
4. Change the localization to 'Ru' and check the question in the ‘Cups section’.

**Actual result**
There is the following question in the ‘Cups section’:
- And how many packages you did not take today? (En)
- А скільки пакетів ти не взяв сьогодні? (Uk)
- А сколько пакетов ты не взял сегодня? (Ru)

![Cups_En](https://user-images.githubusercontent.com/69673163/91172008-2f606580-e6e4-11ea-9218-484525724c2f.png)
![Cups_Uk](https://user-images.githubusercontent.com/69673163/91172015-32f3ec80-e6e4-11ea-91ce-3945dce05bb5.png)
![Cups_Ru](https://user-images.githubusercontent.com/69673163/91172033-3a1afa80-e6e4-11ea-824b-309c6a688535.png)

**Expected result**
There should be the following question in the ‘Cups section’:
- And how many cups did you not throw away today? (En)
- А скільки склянок не викинув сьогодні ти? (Uk)
- А сколько стаканчиков не выбросил сегодня ты? (Ru)

![Cups section mock-up](https://user-images.githubusercontent.com/69673163/91172095-4d2dca80-e6e4-11ea-8d25-a810d8f8ecd2.png)

**User story and test case links**
User story #356

**Comment by JustinCooper43** [comment]
Bug was not fixed

![2020-09-01_010816](https://user-images.githubusercontent.com/64972476/91773617-cd29c800-ebef-11ea-8c2d-5eedf577c4d5.png)
