### ISSUE TITLE
[Sign up] The background image of Popup is different.

### ISSUE THREAD

**Issue by Plilia** [ita-social-projects/GreenCity#1237]
**Environment:** Windows 10 Home, Version 80.0 (64-bit) 
**Reproducible:** always
**Build found:** "commit 147fa44"

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/welcome.'
2. Click on 'Sign-up button'

**Actual result**
Missing items of the background image
![222](https://user-images.githubusercontent.com/12970841/91496960-bc164980-e8c5-11ea-8cc9-5d16c1d88a38.jpg)

**Expected result**
The background image has to be the same as in the mockup
![33333](https://user-images.githubusercontent.com/12970841/91497103-00a1e500-e8c6-11ea-89d1-953e13dbb2a7.jpg)

**User story and test case links**
E.g.: "User story #385 
[Test case]https://jira.softserve.academy/browse/GC-216

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: trivial"), Type ("UI").

**Comment by krivondulia** [comment]
Not fixed
