### ISSUE TITLE
[Edit Profile] Improvement to 'City' field validation

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1254]
Criteria to validate a 'City' field on the 'Edit profile' page should be the following:

1.	Be a maximum of eighty-five (**85**) characters.
2.	Alphanumeric characters and  '()-! ’,'.
3.	Name of the city can’t start with '()-! ’,'.

**Enhancement related to**

Epic [#938](https://github.com/ita-social-projects/GreenCity/issues/938)
Story  [#1010 ]( https://github.com/ita-social-projects/GreenCity/issues/1010)

**Comment by stasgoodman** [comment]
- [ ] 
- [ ]
