### ISSUE TITLE
[Header] 'Logo' image, 'Magnifying glass' image lose quality when zoom page.

### ISSUE THREAD

**Issue by JustinCooper43** [ita-social-projects/GreenCity#1257]
**Environment:** Firefox Version 78.0.2 (64-bit)/Windows 10 Home 1903
**Reproducible:** always
**Build found:** 0ee1777

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Zoom page on 200%. ( Ctrl + '+')

**Actual result**
'Logo' image, 'Magnifying glass' image and some items of header lose quality.

![Zoom](https://user-images.githubusercontent.com/64972476/91766495-538bdd00-ebe3-11ea-86e8-ff7201c95f6e.jpg)

**Expected result**
All items of page have not to lose quality when zoom.

![Zoom 1](https://user-images.githubusercontent.com/64972476/91766797-d01ebb80-ebe3-11ea-86af-a310a79e6f54.jpg)

**Comment by tatiana404** [comment]
The bug was not fixed. When user sets 200 % resolution the logo sign  is not visible on a page.
![logo 200%](https://user-images.githubusercontent.com/65060199/100932251-4210e480-34f4-11eb-85a9-9d2f9f57b0e4.PNG)
