### ISSUE TITLE
unnecessary box-shadow on buttons

### ISSUE THREAD

**Issue by HryshkoAnton** [ita-social-projects/GreenCity#1274]
As a user I want to see **focused** change view buttons without any borders

Actual result:
![image](https://user-images.githubusercontent.com/45083515/91995624-b777e800-ed40-11ea-84e5-b7270740ec44.png)

Expected result:
![image](https://user-images.githubusercontent.com/45083515/91995699-cced1200-ed40-11ea-8823-8cf4e682d35f.png)

**Comment by Volodymyr-Danyliv** [comment]
@HryshkoAnton could you specify the environment?
