### ISSUE TITLE
[Edit profile] Improvement to ‘Add social network’ functionality

### ISSUE THREAD

**Issue by SolkaNik** [ita-social-projects/GreenCity#1298]
1. User can delete social network links which were added earlier. When user clicks on ‘Delete’ icon the confirmation message appears with the following text and two buttons:
- En: ‘Are you sure that you want to remove this social network link from your profile?’ -  ‘Cancel’ / ‘Yes’
- Ua: ‘Ви впевнені, що хочете видалити це посилання на соцмережу зі свого профілю?’ – ‘Скасувати’ / ‘Так’
If user clicks on ‘Yes’ button the link is removed and the system comes back to ‘Edit profile’.
If user clicks on ‘Cancel’ button the link is not removed and the system comes back to ‘Edit profile’.

2. If user tries to add two similar links (e.g., adds twice the same account from Facebook), the ‘Social network’ field should be highlighted in red and the error message should appear below the field: ‘This link has been already added’/ ‘Це посилання вже додано’/ ‘Эта ссылка уже добавлена’.
3. User cannot add more than 5 social networks. When user has already added 5 social networks the 'Add social network' button should be disabled.
4. When user does not add any social networks the icons of social networks don’t display on the profile page.
5. When user hover over the social network icon on the profile page, the infotip with full account link should appear.
6. When user adds an unknown social network the default icon should display on the profile page for this link.

Related to:
User Story #1007 
Epic #938

[UPDATE]
Everything is done except for point 1, but I created a separate issue for it 
https://github.com/ita-social-projects/GreenCity/issues/1931

**Comment by ViktoriyaRyazhska** [comment]
Cannot save user personal data with added social network
