### ISSUE TITLE
[Edit Profile] User can change his 'Name' when error message is shown and 'Save' button is disabled after pressing enter

### ISSUE THREAD

**Issue by stasgoodman** [ita-social-projects/GreenCity#1308]
**Environment:** Google Chrome, version 84.0.4147.135, Linux Mint 19.3 Tricia
**Reproducible:** always.
**Build found:** commit f63855f

**Preconditions**
- User should be logged in (e.g : login:green.city.test2@gmail.com   password: Green.city#500);

**Steps to reproduce**
1. Go to 'My habits' > Edit Profile (https://ita-social-projects.github.io/GreenCityClient/#/profile/302/edit\)
2. Click on 'Name' field 
3. Delete data from 'Name' field  (leave a pointer in 'Name' field)
4. Check that button 'Save' is disabled and error message 'Should contain maximum 30 symbols' is shown in red color
5. Press 'Enter'

**Actual result**
- 'My Habits' page is shown
- The changed 'Name' field is saved despite the error message
[video](https://www.awesomescreenshot.com/video/879595?key=1061276913ec81a4ae6b6e48eebf36e4)

**Expected result**
- 'Edit profille' page is shown
- User should not be able to save changes in the 'Name' field using 'Enter' when button 'Save' is disabled and error message is shown

**User story and test case links**

"User story #1010 
[Test case](https://jira.softserve.academy/browse/GC-1549)"

**Comment by bohdana1** [comment]
The button 'Save' is enabled.
The error message 'Should contain maximum 30 symbols' is not shown in red color.
User can save changes in the 'Name' field using 'Enter'
