### ISSUE TITLE
[Edit profile] Wrong buttons alignment on Cancel pop-up when screen resolution is 390 - 575 px (Ua)

### ISSUE THREAD

**Issue by SolkaNik** [ita-social-projects/GreenCity#1334]
**Environment:** Windows 10 Home x64; browsers: Google Chrome v. 84.0.4147.135; Firefox v. 79.0; Microsoft Edge 44.19041.423.0.
**Reproducible:** always.
**Build found:** commit c40865d.

**Preconditions**
User should be logged in https://ita-social-projects.github.io/GreenCityClient/#/profile/4325 with credentials (e.g., email: sunnyraintest@ukr.net, password: Mysunnytest#1).

**Steps to reproduce**
1. Select ‘Uk’ in the language dropdown at the top right side of page.
2. Go to 'My habits' and click on 'Edit icon' at the top left side of the profile section.
3. Click the ‘Cancel’ button at the bottom of page.
4. Press F12 and set resolution 390 px.
5. Set resolution 575 px.
5. Check the alignment of controls on Cancel pop-up.

**Actual result**
The buttons are not aligned regarding mockup. This bug is reproducible on resolutions in the range of 390 - 575 px.

![390 Uk Chrome](https://user-images.githubusercontent.com/69673163/92693401-4773ee00-f34e-11ea-9f50-adc83c90a511.png)

![575 Uk Chrome](https://user-images.githubusercontent.com/69673163/92693416-4a6ede80-f34e-11ea-9f71-77538819c1de.png)

**Expected result**
The buttons alignment on all screen resolutions < 576 px should be the same as on the mock-up ‘Cancel popup 320’.

![Cancel popup 320](https://user-images.githubusercontent.com/69673163/92693735-ac2f4880-f34e-11ea-8f3f-1e05ac3fc164.png)

**User story and test case links**
User story #1009 
Test case https://jira.softserve.academy/browse/GC-1538

**Comment by oprotyniak** [comment]
Alignment is correct. The buttons have different height.
