### ISSUE TITLE
Verification url format for social network link - change request

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1340]
Url for social network link on 'Edit profile' page should have the hext format:
"protocol"://"address"
where protocol is https or http.

**Related to**:
Epic #938 
User story #1007

**Comment by JimHolman1199** [comment]
Like this?
p.s. just a test, not yet on the live site)  
<img width="365" alt="Screenshot 2020-12-09 at 21 40 13" src="https://user-images.githubusercontent.com/46226026/101678823-2adb7500-3a67-11eb-9847-6ae748d93b9b.png">

**Comment by JimHolman1199** [comment]
I talked to Viktoria and we agreed that this is no longer relevant.
