### ISSUE TITLE
Filtering places by Discount rate

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#135]
As an unregistered user I want to filter places in the sidebar list by discount rate so that I can find the place with cheapest drink to buy.

Mockups:
![image](https://user-images.githubusercontent.com/53810790/64415268-9fbe4300-d09d-11e9-9b68-851e7206d611.png)
![image](https://user-images.githubusercontent.com/53810790/64407999-6205ee00-d08e-11e9-9fa0-df3e44da04fb.png)
![image](https://user-images.githubusercontent.com/53810790/64706373-0be3e100-d4ba-11e9-925a-91b861e05933.png)

Acceptance criteria:

1. "Filter by" button in available above the sidebar list with places for Unregistered user.

2. WHEN an unregistered user clicks "Filter by" button, panel with filtering options is opened.

3. Panel with filtering options contains the next information:
a. Discount rate;
b. Text "Choose a discount range to search in:"
b. Low rate (first value is the smallest discount among all places)
c. High rate (the last value is the biggest discount among all places) 
d. "Apply" button;
e. "Cancel" button;

4. An unregistered user can drag a filter between the smallest and the biggest values.

5. WHEN un unregistered user choose filtering options AND clicks "Apply" button, THEN system shall display places, where discount rate value fits in the filtered range.

6. WHEN an unregistered user choose one filtering option of Discount rate and clicks "Cancel" button, THEN he/she can see default places in the list.

**Comment by rsyvulko** [comment]
Not relevant.
