### ISSUE TITLE
[Calendar] Default month and year views of Calendar

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1429]
**As a** user, **I want to** see a default month view of the calendar on ‘My habits page’, **so that** I could review the calendar for the current month. 

**Preconditions:**
• Registered User is logged in
• My habits page is open
• User doesn’t have any habits in progress

**Acceptance criteria:**

1. The default ‘Month view’ is represented by the current month in the format ‘month year’ on ‘My habits’ page.

2. The current day on the ‘Month view’ layout is colored in green color. 

3. User can navigate from the previous month to next month by pressing the '<', '>' buttons. 

4. By clicking on the ‘Month’ label at the top of the Calendar user can see the default current year view. The current month is colored in green color, other months are colored in grey color. 

5. On the ‘Year view’ layout, User can navigate from the previous year to the next year by pressing the '<', '>' buttons.

6. On the ‘Year view’ layout, when User selects the month, the system displays the selected month view layout.

![image](https://user-images.githubusercontent.com/73845584/99250271-0ef00500-2814-11eb-9674-9d01a21c9931.png)

**Out of scope:**
Mark/unmark habits ‘in progress’ on a Calendar at My habits page (#1431)

**Comment by SWalaszek** [comment]
Retested successfully. 
Test case: [WR50QC-579](https://jira.softserve.academy/browse/WR50QC-579)
