### ISSUE TITLE
Update username in header after editing name in profile

### ISSUE THREAD

**Issue by yulkats** [ita-social-projects/GreenCity#1451]

**Comment by ViktorRachynskyi** [comment]
Duplicate - https://github.com/ita-social-projects/GreenCity/issues/2677#issue-867745993

**Comment by Nazik94** [comment]
[](https://github.com/ita-social-projects/GreenCity/issues/2677)

**Comment by Nazik94** [comment]
[https://github.com/ita-social-projects/GreenCity/issues/2677](url)

**Comment by Nazik94** [comment]
[dd](https://github.com/ita-social-projects/GreenCity/issues/2677)

**Comment by Nazik94** [comment]
dd - https://github.com/ita-social-projects/GreenCity/issues/2677
