### ISSUE TITLE
Add autocomplete for City on the 'Edit Profile' page

### ISSUE THREAD

**Issue by yulkats** [ita-social-projects/GreenCity#1452]
Intgrate google API to this field
<img width="804" alt="Screenshot 2021-04-29 at 19 34 46" src="https://user-images.githubusercontent.com/46226026/116586328-030b8180-a922-11eb-93c9-951d0190465b.png">

**Comment by LiliiaPalii** [comment]
Doesn't work autocomplete for 'City' field
