### ISSUE TITLE
Navigation to the place

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#147]
As an unregistered user I want to know direction from my location to the place, where café is situated so that I will get this place with the best way.

Mockups:
![image](https://user-images.githubusercontent.com/53810790/64696861-2d3bd180-d4a8-11e9-840b-ab7d12d61b91.png)

Acceptance criteria:

1. System displays place on the map with marker icon.

2. WHEN an unregister user access the application, THEN popup with next information:
    a. www.greencity.com want to: Know your location. (example in mockup)
    b. "Allow" button
    c. "Block" button

3. WHEN an unregistered user clicks "Allow" button, THEN system shall define user's coordinate and display un unregistered user's location on the map. 
     
4. WHEN an unregistered user click "Block" button, THEN popup with the information appears: "Please put a marker on the map, which distance to the places will be calculated from".

5. WHEN an unregistered user moves cursor to place's marker, THEN popup button "Navigate to the place" appears.

6. WHEN an unregistered user clicks "Navigate" button, THEN system shall display direction from:
a. user location (in case unregistered user allowed an access to his location)
b. marker that user set on the map (in case unregistered user blocked an access to his location and set a marker on the map)
c. default location marker on the map (in case unregistered user blocked an access to his location and did not set a marker on the map)
… to mentioned place with highlighted blue line. (TBD What should be the next actions)

**Comment by rsyvulko** [comment]
Not relevant.
