### ISSUE TITLE
Filtering places by Opening times

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#150]
As an unregistered user I want to filter places in the sidebar list by opening times so that I can find the place which is opened in time when unregistered use is serching.

Acceptance criteria:

1. "Filter by" button in available above the sidebar list with places for Unregistered user.

2. WHEN an unregistered user clicks "Filter by" button, panel with filtering options is opened.

3. Panel with filtering contains second option "Is opened now".

4. WHEN un unregistered user chooses option "Is opened now" AND click "Apply" button, THEN system shall fixes current day and time and display in the sidebar list all places, which are opened from current moment and during the next hour. (For ex. user filters data at 8:34, then system shall display all places, which is opened during 8:34-9:34 current day).

This user story is related to #135

**Comment by rsyvulko** [comment]
Not relevant.
