### ISSUE TITLE
[Own security] Updating current password returns status 401.

### ISSUE THREAD

**Issue by iraflorens** [ita-social-projects/GreenCity#1509]
**Environment:** swagger
**Reproducible:** always
**Build found:** commit 0e9ce75

**Preconditions**
- https://greencity.azurewebsites.net/swagger-ui.html# should be opened.
- user should be signed in and authorized.

**Steps to reproduce**
1. Click on own-security-controller, PUT ownSecurity/Updating current password
2. Set up valid current password, password and confirm password
3. Execute request.

**Actual result**
{
  "timestamp": "2020-09-27T17:55:43.605+0000",
  "status": 401,
  "error": "Unauthorized",
  "message": "Authorize first.",
  "path": "/ownSecurity"
}

**Expected result**
Json with 'status': 200 should be displayed

https://github.com/ita-social-projects/GreenCity/pull/2146

**Comment by TarasDovganyuk** [comment]
Checked. When user is Signed in, authorized by token, **PUT ownSecurity/** returns 200 response.

**Comment by krivondulia** [comment]
The same problem. Response 401. {
  "timestamp": "2020-10-04T16:34:38.972+0000",
  "status": 401,
  "error": "Unauthorized",
  "message": "Authorize first.",
  "path": "/ownSecurity"
}

**Comment by TarasDovganyuk** [comment]
Preconditions

https://greencity.azurewebsites.net/swagger-ui.html# should be opened.
user should be signed in and authorized.

**Comment by krivondulia** [comment]
@TarasDovganyuk I've logged and authorized and still get response 401.

**Comment by ProstoLeleka** [comment]
Bug is still active. 401 response. Authorization work for EcoNews (CreateNews etc.), but in UpdatePassword 401.

**Comment by irynamykhailevych** [comment]
Got response - 401, after logging and authorizing. 
{
  "timestamp": "2021-04-28T14:00:25.217+0000",
  "status": 401,
  "error": "Unauthorized",
  "message": "Authorize first.",
  "path": "/ownSecurity/changePassword"
}
