### ISSUE TITLE
[Edit profile, edit photo] Incorrect text alignment on 'Upload new photo' in Uk

### ISSUE THREAD

**Issue by iraflorens** [ita-social-projects/GreenCity#1521]
**Environment:** Google Chrome version 85.0.4183.121 (64-bit)
**Reproducible:** always
**Build found:** commit 0e9ce75

**Preconditions**
- User should be signed in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
(e.g : login: green.city.test2@gmail.com password: Green.city#500)
- Edit profile page should be opened

**Steps to reproduce**
1. Select Uk localization
2. Click on Edit photo's icon

**Actual result**
The text is located at the bottom of the 'Upload new photo' button.
![image](https://user-images.githubusercontent.com/69673012/94545172-de004480-0254-11eb-9bce-5aa309ed59fb.png)

**Expected result**
The text should be located in the middle of the 'Upload new photo' button.
![image](https://user-images.githubusercontent.com/69673012/94546132-25d39b80-0256-11eb-8292-632d496a474b.png)

**User story and test case links**
User story #1006

**Comment by krivondulia** [comment]
Not fixed

**Comment by JimHolman1199** [comment]
![Screenshot 2020-10-19 at 19 30 04](https://user-images.githubusercontent.com/46226026/96479369-87799b00-1241-11eb-9c60-cdaf3e2c9856.png)
@krivondulia Can you check this again?

**Comment by krivondulia** [comment]
@JimHolman1199 Checked, Firefox 81.0.2, Windows 10 Home and Pro 
![mozilla photo](https://user-images.githubusercontent.com/69672600/96491548-af1d3300-1242-11eb-9409-45d3577eb59c.jpg)

**Comment by JimHolman1199** [comment]
looks fine on my end
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
![Screenshot 2020-10-20 at 18 52 34](https://user-images.githubusercontent.com/46226026/96611578-7befa800-1305-11eb-82c9-860780a3aadf.png)

**Comment by krivondulia** [comment]
@JimHolman1199 Good, fixed)
