### ISSUE TITLE
[Edit profile] Button 'Edit photo' has wrong alignment

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1525]
**Environment:** Google Chrome 85.0.4183.121
**Reproducible:** always
**Build found:** commit 0e9ce75

**Preconditions**
User should be logged in https://ita-social-projects.github.io/GreenCityClient/#/profile/4325 
with credentials (e.g., email: sunnyraintest@ukr.net, password: Mysunnytest#1).

**Steps to reproduce**
1. Go to 'My habits' and click on 'Edit icon' at the top left side of the profile section.

**Actual result**
'Edit photo' icon has wrong position.
![кнопка сьехала](https://user-images.githubusercontent.com/69672600/94593940-af509100-0289-11eb-921d-010c51c48a12.jpg)

**Expected result**
'Edit photo' icon has correct position.

**User story and test case links**
 User story #1006

**Comment by JimHolman1199** [comment]
The problem was that the link to the photo coming from the server was broken
It was fixed on the server so it is no longer relevant
