### ISSUE TITLE
[Sing up] Tab is disabled for 'Sign in' link

### ISSUE THREAD

**Issue by SolkaNik** [ita-social-projects/GreenCity#1538]
**Environment:** Windows 10 Home x64; Google Chrome 85.0.4183.121.
**Reproducible:** always.
**Build found:** commit 0e9ce75.

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign up' button at the top right corner.
3. Go to the 'Sign in' link at the bottom by pressing the 'Tab' button.

**Actual result**
'Sign in' link is disabled and not focusable. 
See the video https://drive.google.com/file/d/1gaEN4UqTZilG8y-H5S9bOuQsPixqmMl0/view?usp=sharing 

**Expected result**
'Sign in' link should be focusable while pressing 'Tab' on it. When user press 'Enter' the 'Sign in' popup should open.

**NB!**
The same result reproduces on the 'Sign in' popup while pressing 'Tab' on the 'Sign up' link.

**User story and test case links**
Epic #908 
Test case [216](https://jira.softserve.academy/browse/GC-216)

**Comment by krivondulia** [comment]
Visual accompaniment is present, but after pressing 'Enter' user doesn't redirect to 'Sign In' form.
