### ISSUE TITLE
Add feedback to a place

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#154]
As registered user I want to add a feedback on a place, so that there will be more information about a place in order to choose one.

Mockup (for example):
![image](https://user-images.githubusercontent.com/53810790/64941250-c5ea9c80-d86e-11e9-90a9-71860a9d45e0.png)

Acceptance criteria:

1. "Submit feedback" button shall be displayed on the site and shall be available only for registered user.

2. A registered user can click "Submit feedback" button.

3. WHEN a registered user clicks "Submit feedback" button, THEN popup, which contains the next information:
a. Rate (is shown as five empty stars from 1 to 5)
b. Input text filed (with placeholder "Please write a comment", min length - 5 symb, max - 300 symb with gaps).
c. "Attach file" button (max size 20 MB and is optional to submit a feedback)
d. Field for attached file name (with placeholder jpg, png, gif)
e. "Submit" , "Cancel" buttons

4. System shall display submitted feedback under the place in the sidebar list for unregistered and registered users. 

5. Feedback shall be visible WHEN an user (registered/unregistered) clicks on the place in the sidebar list.

6. Registered user can leave only one feedback for one place.

5. Admin shall receive a notification about each submitted feedback to his email address.

**Comment by rsyvulko** [comment]
Not relevant.
