### ISSUE TITLE
[Sign in] Own-Security-Controller returns status 500 for incorrect password

### ISSUE THREAD

**Issue by SolkaNik** [ita-social-projects/GreenCity#1545]
**Environment:** Swagger.
**Reproducible:** always.
**Build found:** commit 0e9ce75.

**Steps to reproduce**
1. Go to https://greencity.azurewebsites.net/swagger-ui.html#/own-security-controller/singInUsingPOST
2. Set up incorrect password into JSON (invalid format or password that does not match to email):
{
"email": "sunnyraintest@ukr.net",
"password": "Mysunnytest#12"
}
3. Execute request.

**Actual result**
Response 500:
{
  "timestamp": "2020-10-01T12:00:46.762+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Bad password",
  "path": "/ownSecurity/signIn"
}

**Expected result**
Response 400 with the error message: "Bad password" should return.

**User story and test case links**
User story #66 
Test cases [495](https://jira.softserve.academy/browse/GC-495), [496](https://jira.softserve.academy/browse/GC-496).

**Comment by ProstoLeleka** [comment]
Bug is still active.
