### ISSUE TITLE
[Comment, Econews] No icons present at 'Like' and 'Reply' buttons at Ru and Uk l10n

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1552]
**Environment:**  Windows 10 Home, Mozilla Firefox 80.0.1
**Reproducible:** always
**Build found:** commit 0e9ce75

**Preconditions**
User should be logged in https://ita-social-projects.github.io/GreenCityClient/#/welcome
with credentials (e.g., email: sunnyraintest@ukr.net, password: Mysunnytest#1)

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/news/3096
2.Click on 'Uk' localization dropdown

**Actual result**
No icons near the buttons
![no icon comments](https://user-images.githubusercontent.com/69672600/94846361-50258480-0421-11eb-86af-10846367bb55.jpg)

**Expected result**
The icons are present near the buttons
![photo_2020-10-01_14-10-39](https://user-images.githubusercontent.com/69672600/94846504-8d8a1200-0421-11eb-955b-918e485cc486.jpg)

**User story and test case links**
User story #937 #1179

**Comment by Benerous** [comment]
**Actual result**
Icons near all the buttons in comment on every available localization
![result_3](https://user-images.githubusercontent.com/59996447/97007041-74204580-1549-11eb-8ac9-01b4c7108060.PNG)
![result_2](https://user-images.githubusercontent.com/59996447/97007045-75517280-1549-11eb-9e5b-904ddf236480.PNG)
![result_1](https://user-images.githubusercontent.com/59996447/97007047-76829f80-1549-11eb-936d-71b08628cb80.PNG)

**Comment by krivondulia** [comment]
@Benerous not fixed
Windows 10 Home/Pro, Mozilla Firefox 82.0
![нет иконок мозилла](https://user-images.githubusercontent.com/69672600/97079631-f0706280-15f5-11eb-983f-2ae278024bc0.jpg)
