### ISSUE TITLE
[Comment/Reply, Econews] The system doesn't display notification wher user want to delete its comment/reply

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1631]
**Environment:** Windows 10 Home, Google Chrome 85.0.4183.121, Mozilla Firefox 80.0.1
**Reproducible:** always
**Build found:** commit 818b49c

**Preconditions**
User should be logged in (e.g., email: sunnyraintest@ukr.net, password: Mysunnytest#1)
User should post at least one comment and reply for 'Eco news'.

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/news/3096
2. Click on 'Delete' icon near this user comment.
3. Click on 'Delete' icon near this user reply.

**Actual result**
Comment and reply are deleted without any notification form.

**Expected result**
the system display notification ‘ Are you sure you want to delete the comment?’ - if user wants to delete its comment,
the system display notification ‘ Are you sure you want to delete the reply?’ - if user wants to delete its reply,

**Postconditions**
Check the changes in DB
use query:
"select * from econews_comment
where user_id = 4325;"

**User story and test case links**
User story #846
[Test case] https://jira.softserve.academy/browse/GC-822
https://jira.softserve.academy/browse/GC-819

**Comment by vandrusenko** [comment]
The bug is fixed.
