### ISSUE TITLE
Sorting in Admin page

### ISSUE THREAD

**Issue by yartymys** [ita-social-projects/GreenCity#164]
As an admin I want to be able to sort data within columns, so I can easily view required information.

**Mockup:**
!! for visual reference only (functionality has to be as described in acceptance criteria)
1
![image](https://user-images.githubusercontent.com/53868652/65055527-008c2c00-d978-11e9-9b6e-41846fffa308.png)

2 
![image](https://user-images.githubusercontent.com/53868652/65055590-21548180-d978-11e9-8c42-82d2826c4861.png)

3 sorted by descending 
![image](https://user-images.githubusercontent.com/53868652/65055665-4517c780-d978-11e9-8aaa-cf0325849285.png)

4
![image](https://user-images.githubusercontent.com/53868652/65055739-65e01d00-d978-11e9-8b82-e653c9ccf6b3.png)

**Acceptance Criteria:**

1. In admin page columns shall be sortable.
2. WHEN admin hovers the cursor over the column name of the column which is sortable, THEN the 'point' cursor shall change to 'hand' cursor.
3. WHEN admin clicks on the sortable column name, THEN system shall display Sorting menu.
4. In Sorting menu, system shall display the following:
a. "Sort Ascending"
b. "Sort Descending"
c. "Cancel Sorting"
5. WHEN admin clicks on "Sort Ascending" or "Sort Descending", THEN system shall
a. sort the column items correspondingly to the selected sorting option
b. display an upward or downward arrow next to the column header, correspondingly to the selected sorting option
c. highlight the whole column with color. (possibly light gray)
d. close the Sorting menu
6. Provided a column is sorted in ascending order, then "Sort Ascending" shall be disabled.
7. Provided a column is sorted in descending order, then "Sort Descending" shall be disabled.
8. Provided no column is sorted on, then "Cancel Sorting" shall be disabled in Sorting menu.
9. If admin clicks "Cancel Sorting," system shall restore the default sorting of screen (table/grid) and close Sorting menu.
10. System shall allow only one column sorted at a time.
11. GIVEN admin  manually sorted items, WHEN he navigates away from the screen and comes back, THEN system shall save the defined sorting. If admin logs out of the system, system shall not save the defined sorting.

**Assumptions and Constraints:**
1. arrows may be different from ones on mockups

US related to #24 #27 
**TBD:**

**Comment by rsyvulko** [comment]
Not relevant.
