### ISSUE TITLE
[Calendar] On screen 768px displaying wrong date

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1640]
**Environment:** Windows 10 Home, Google Chrome 85.0.4183.121, Mozilla Firefox 80.0.1
**Reproducible:** always
**Build found:** commit 818b49c

**Preconditions**
User should be logged in ( e.g. email: "userok2@xxx.com", pass: "GtDTkmm#1aAF3hQXN")

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/profile/6093
2. Click on 'F12' and set screen resolution 768px
3. Check the date

**Actual result**
Wrong date displaying.
![wrong date calendsr](https://user-images.githubusercontent.com/69672600/95975628-b1345b80-0e16-11eb-9237-5a021afefc48.jpg)

**Expected result**
Current date should be displaying. 14.10.2020 Wednesday.

**User story and test case links**
User story #1178 #749

**Comment by MykytaT** [comment]
There is a wrong date displaying with the screen resolution 768px.
**Actual result**
![image](https://user-images.githubusercontent.com/71656989/99071261-6dba4200-25ba-11eb-8288-7adfd51bf1e1.png)
**Expected result**
Current date should be displaying. 13.11.2020 Friday.
