### ISSUE TITLE
[Create news]Сan not POST new eco news when source is empty field

### ISSUE THREAD

**Issue by ViktoriyaRyazhska** [ita-social-projects/GreenCity#1655]
**Environment:** Windows 10, Chrome 86.0.4240.75
**Reproducible:** always
**Build found:** 17.10.2020, 18:53

**Steps to reproduce**
1. Go to 'https://greencity.azurewebsites.net/swagger-ui.html'
2. Click on 'Eco News Controller'
3. Run 'Add new eco news' with data:

{   "image": "string", 
"source": "",   
"tags": [     "news"   ],  
 "text": "testtest1testtest1testtest1testtest1testtest1testtest1",  
 "title": "WowWOW" }

**Actual result**
{
  "timestamp": "2020-10-17T15:49:27.818+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "image == null!",
  "path": "/econews"
}

**Expected result**
200 ok
json with new news is received

**User story and test case links**
User story #505

**Comment by Yura09** [comment]
pass image as base64 or upload image

**Comment by krivondulia** [comment]
Works only with image as base 64.
Upload image returns 500.
