### ISSUE TITLE
Display favorite places on map (registered user)

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#167]
As a registered user I want to see my favorite places displayed on the map with a different marker, so I can see them separately from all other places.

**Acceptance criteria:**
1. GIVEN user has a list of saved favorite places, WHEN user logs in to the system, THEN system shall display his favorites places on a map by different marker of a different color (instead of default marker).
2. Provided user clicks on a favorite place marker, system shall open the detail view of the place, where 'Favorite' icon (star) shall be selected (yellow).

related to #49

**Comment by rsyvulko** [comment]
Not relevant.
