### ISSUE TITLE
[Restore password] BorderColor of EmailField is not red when user  not exist

### ISSUE THREAD

**Issue by ProstoLeleka** [ita-social-projects/GreenCity#1714]
Environment: Windows 7, Google Chrome 86.0.4240.111
Reproducible: always
Build found: d03df76

Steps to reproduce
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign in'
3. Click on 'Forgot password'
4. Set valid not registered e-mail (e.g: "MyEmail@gmail.com")
5. Click on 'Submit a login link' button

Actual result
BorderColor of EmailField has not changed.
![Screenshot_8](https://user-images.githubusercontent.com/34520370/97094222-9d30fb00-165b-11eb-91cb-a9d0d45f7bbc.png)

Expected result
BorderColor of EmailField has changed to red.
![Screenshot_7](https://user-images.githubusercontent.com/34520370/97094240-cce00300-165b-11eb-8aed-e0bac9f90ea5.png)

User story and test case links
User story #472
See Clarifications 06.05.2020

**Comment by JimHolman1199** [comment]
@ProstoLeleka hi, not sure it's still relevant, can you check again?
![Screenshot 2020-11-12 at 00 16 38](https://user-images.githubusercontent.com/46226026/98870694-570dd100-247c-11eb-8266-d54c45011a5e.png)

**Comment by ProstoLeleka** [comment]
@JimHolman1199 Yes, now it's ok. Everything fine.

**Comment by marinasmarsa** [comment]
shouldn't be black frame
![6fa427f25a](https://user-images.githubusercontent.com/69673592/99716083-5692bd00-2ab0-11eb-8df4-8b8a3d1897d3.jpg)
![7a9f0b0100](https://user-images.githubusercontent.com/69673592/99716087-572b5380-2ab0-11eb-9dd9-1c4a5919082a.jpg)
