### ISSUE TITLE
[Create news] Source field is always equal to content after creation

### ISSUE THREAD

**Issue by Meownjik** [ita-social-projects/GreenCity#1718]
**Environment:** Chrome 86.0.4240.111
**Reproducible:** always
**Build found:** commit 39df7c7 and earlier

**Preconditions**
You are logged in

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/news
2. Click on Create News
3. Fill Title with `Test news source field` and Content with `This post tests whether the source specified is displayed.`

4-a. Fill Source field with `https://www.google.com.ua/`
4-b. Leave Source field empty

5. Select any Tag
6. Click Publish
7. Go to https://ita-social-projects.github.io/GreenCityClient/#/news
8. Click on the just-published news

**Actual result**
The news has the Source equal to the Content: `This post tests whether the source specified is displayed.`

![image](https://user-images.githubusercontent.com/43137377/97179368-69f88400-17a1-11eb-9539-f4d13302ad9c.png)

**Expected result**
In case of step 4-a: The news has the Source specified on creation: `https://www.google.com.ua/`

In case of step 4-b: The news has empty Source field

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: low"), Type ("Functional")

**Comment by Dnagor** [comment]
In source field Attribute 'href' always equals to Content field, even if source filed is empty.
`<div _ngcontent-lvy-c10="" class="news-text-content word-wrap"> **Мережа магазинів спеціалізованих на реалізації натуральної та екологічно чистої продукції, яка вирощується і виробляється на фермерських господарствах.** </div>
<div _ngcontent-lvy-c10="" class="source-field ng-star-inserted"><div _ngcontent-lvy-c10="" class="source-title"> Source: </div><a _ngcontent-lvy-c10="" class="source-text word-wrap" href="**Мережа магазинів спеціалізованих на реалізації натуральної та екологічно чистої продукції, яка вирощується і виробляється на фермерських господарствах.**"> https://news.com </a></div>`
