### ISSUE TITLE
[News page loading] Incorrect message for user

### ISSUE THREAD

**Issue by romanovskyroma** [ita-social-projects/GreenCity#1739]
Environment: Chrome Version 86.0.4240.111 (64-bit)/Windows 10 Home 1903
Reproducible: always

Steps to reproduce

1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click 'Create news'
5. Input valid values to all mandatory fields
6. Click 'Publish'

Actual result

![bug_econews_add_2](https://user-images.githubusercontent.com/58560068/97346246-e075ae80-1893-11eb-8af2-0725bdf5e8aa.png)

Expected result
delete 'the'.
![bug_econews_add](https://user-images.githubusercontent.com/58560068/97346304-f2efe800-1893-11eb-9b32-01945a57871b.png)

**Comment by SashkoMolodec** [comment]
Not a bug.
