### ISSUE TITLE
[Sign Up] Error message shown in wrong language in Ru, Ukr l10n

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1752]
**Environment:** Windows 10 Home, Mozilla Firefox 82.0
**Reproducible:** always
**Build found:** commit 8b208c6

**Preconditions**
The user with this email is already registered e.g. "adminok@xxx.com"

**Steps to reproduce** 
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Choose the Ukr l10n
3. Click on 'Зарєєструватись' button
 4.  Use the "adminok@xxx.com" email
 5. Fill other fields with valid data.

**Actual result**
Error message is shown in English language.
![button enabled](https://user-images.githubusercontent.com/69672600/97585082-08caed80-19f9-11eb-8f65-ada60d5a204b.jpg)

**Expected result**
Error message is shown in Russian and Ukrainian language.

**User story and test case links**
E.g.: "User story #455

**Comment by Yuliia-Rutetska** [comment]
fixed
