### ISSUE TITLE
Notification about approved/declined proposed place

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#176]
As a registered user I want to receive email notifications when my proposed place(s) is approved or declined.

**Acceptance Criteria:**

1. Provided a proposed place was approved by admin, system shall send an email notification to the user who proposed the place with the following text:
"Your proposed place "[XXX]" has been approved. You can now view it in GreenCity."
where [XXX] is the name of proposed place.

2. Provided a proposed place was declined by admin, system shall send an email notification to the user who proposed the place with the following text:
"Your proposed place "[XXX]" has been declined."
where [XXX] is the name of proposed place.

**Assumptions and Constraints:**
out of scope of this story - add ability for admin to leave comments when declining a proposed place, so that user can understand why his place was declined - **create a story for this**

TBD:

**Comment by rsyvulko** [comment]
Not relevant.
