### ISSUE TITLE
[Sign Up] Wrong font used for labels

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1764]
**Environment:** Windows 10Home, Mozilla Firefox 82.0
**Reproducible:** always
**Build found:** commit 8b208c6

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign Up' button

**Actual result**
Label 'Пожалуйста, внеси свои данные, чтобы зарегистрироваться ' has a wrong font - Roboto.
![шрифт не правильній](https://user-images.githubusercontent.com/69672600/97626744-9541d400-1a2a-11eb-8e54-93c8ec84939c.jpg)

**Expected result**
It should be 'OpenSans' font.

**User story and test case links**
User story #455

**Comment by Yuliia-Rutetska** [comment]
fixed
