### ISSUE TITLE
[Sign Up] User is redirected to 'Sign in' page after registration

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1766]
**Environment:** Windows 10Home, Mozilla Firefox 82.0
**Reproducible:** always.
**Build found:** commit 8b208c6

**Steps to reproduce**
1. Go to Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign Up' button
3. Fill all fields with valid data.
4. Click 'Sign Up' button.

**Actual result**
Pop-up 'Congrats! Your profile is created. Please check the email sent with a link to confirm your email address. ' is appear and user is redirected to the 'Sign in' page.

**Expected result**
User should stay on the 'Main' page.

**User story and test case links**
User story #455

**Comment by tatiana404** [comment]
The user can not sign up. After entering valid data and pressing 'Sign up' button  server does not
<img width="912" alt="log in bug" src="https://user-images.githubusercontent.com/65060199/98919817-f4e2b980-24d7-11eb-86ce-1c62c45b3889.PNG">
 respond
