### ISSUE TITLE
[Restore password] After user changed Name in the resstore password email Name don't changed.

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1768]
**Environment:** Windows 10 Home, Mozilla Firefox 82.0
**Reproducible:** always
**Build found:** commit 8b208c6

**Preconditions**
User should be registered in the system by email.
User should change his name on the 'My habits' page.

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign in'
3. Click on 'Forgot password' link
4. Fill the textbox with valid data
5. Click on 'Submit a login link'

**Actual result**
User gets the email with the old user Name.

**Expected result**
User gets the email with actual user Name.

**User story and test case links**
User story #136

**Comment by natalinapr** [comment]
Not fixed
In email the user name is null instead of name of registered user.
![tempsnip](https://user-images.githubusercontent.com/62031226/100391521-5f4d3b00-303c-11eb-9d14-35216e81066b.png)
