### ISSUE TITLE
[Restore password] incorrect l10n 

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1770]
**Environment:** Windows 10 Home, Mozilla Firefox 82.0
**Reproducible:** always
**Build found:** commit 8b208c6

**Preconditions**
User should be registered in the system by email.

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Choose the Ukrainian language in the dropdown 
3. Click on 'Увійти' button
3. Click on 'Забули пароль?' link
4. Fill the textbox with valid data
5. Click on 'Надіслати посилання для входу'

**Actual result**
The email sent in English language.

**Expected result**
The email sent in Ukrainian language.

**User story and test case links**
User story #136

**Comment by tatiana404** [comment]
The system does not send email due to error message 'must be a well-formed email address ' 
![non well-formed email address](https://user-images.githubusercontent.com/65060199/100934007-cebca200-34f6-11eb-9b5d-1deb565ca68e.PNG)

**Comment by vandrusenko** [comment]
![restore_email_ukr](https://user-images.githubusercontent.com/75262612/102715863-c5964800-42e0-11eb-83e1-435cb5055056.jpg)
The bug was fixed.

**Comment by vandrusenko** [comment]
![restore_email_ukr_title](https://user-images.githubusercontent.com/75262612/102715998-98966500-42e1-11eb-8cb2-4292ace9b420.jpg)
The subject of the email is still in English.
