### ISSUE TITLE
[Restore password] Pop-up  "Your password has just been reset." doesn't appear

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1773]
**Environment:** Windows 10 Home, Mozilla Firefox 82.0
**Reproducible:** always
**Build found:** commit 8b208c6

**Preconditions**
User should be registered in the system by email.
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign in'
3. Click on 'Forgot password' link
4. Fill the textbox with valid data
5. Click on 'Submit a login link'

**Steps to reproduce**
1. check your mailbox and click on 'Restore' button.
2. Change your password. 

**Actual result**
Pop-up  "Your password has just been reset." doesn't appear

**Expected result**
Pop-up  "Your password has just been reset."  appears

**User story and test case links**
User story #136

**Comment by oprotyniak** [comment]
The bug wasn't fixed
Pop-up "Your password has just been reset." doesn't appear. And also no email with message "Your password has just been reset."is sent to user.

**Comment by oprotyniak** [comment]
After clicking on 'Restore' button user is redirected to 'Home' page
![image](https://user-images.githubusercontent.com/73852063/102653453-9fa16400-4177-11eb-99b7-a4362cadc6f0.png)
