### ISSUE TITLE
[Restore password] User doesn't receive email with message "Your password has just been reset."

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1774]
**Environment:** Windows 10 Home, Mozilla Firefox 82.0
**Reproducible:** always
**Build found:** commit 8b208c6

**Preconditions**
User should be registered in the system by email.
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign in'
3. Click on 'Forgot password' link
4. Fill the textbox with valid data
5. Click on 'Submit a login link'

**Steps to reproduce**
1. check your mailbox and click on 'Restore' button.
2. Change your password. 

**Actual result**
User doesn't get the email with message "Your password has just been reset."

**Expected result**
User gets the email with message "Your password has just been reset."

**User story and test case links**
User story #136

**Comment by oprotyniak** [comment]
After clicking on 'Restore' button user is redirected to Home page
![image](https://user-images.githubusercontent.com/73852063/102653161-42a5ae00-4177-11eb-8048-9b64593331e1.png)

**Comment by JimHolman1199** [comment]
please check this again! 
<img width="598" alt="Screenshot 2021-01-02 at 19 24 51" src="https://user-images.githubusercontent.com/46226026/103462786-4b2de500-4d30-11eb-82eb-1e0fa2ee44f4.png">

**Comment by oprotyniak** [comment]
User shouldn't receive E-mail after changing and confirming changed password.  In a meeting on 04.01.2021 it was agreed that 8c acceptance criteria in user story #136 should be deleted.
