### ISSUE TITLE
[Restore password] after user used the 'Restore password' link and change password token/link still work

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1776]
**Environment:** Windows 10 Home, Mozilla Firefox 82.0
**Reproducible:** always
**Build found:** commit 8b208c6

**Preconditions**
User should be registered in the system by email.
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign in'
3. Click on 'Forgot password' link
4. Fill the textbox with valid data
5. Click on 'Submit a login link'

**Steps to reproduce**
1. check your mailbox and click on 'Restore' button.
2. Change your password. 
3. Click on the 'Restore password' link.

**Actual result**
This link with 'Restore password' token still works.

**Expected result**
This link with 'Restore password' token doesn't available.

**User story and test case links**
User story #136

**Comment by marinasmarsa** [comment]
Bug has not been fixed - The link with 'Restore password' token still works.

**Comment by forestik** [comment]
The link with "Recover Password" still works, but the password doesn't change after 24 hours.

**Comment by IgorBoykov** [comment]
After receiving error from back, user should get message "your token is invalid"
https://i.imgur.com/f6sBlAt.png
