### ISSUE TITLE
[API] [Habits]  Get habit assign controller returns 500

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1777]
**Environment:** Swagger
**Reproducible:** always
**Build found:** commit 8b208c6

**Steps to reproduce**
1. Go to https://greencity.azurewebsites.net/swagger-ui.html#/habit-controller/getHabitAssignUsingGET
2. Click on 'Try it on'
3. Use habitAssignId e.g. "4325"

**Actual result**
Response 500. {
  "timestamp": "2020-10-31T18:04:59.690+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Habit assign does not exist by this id : 4325",
  "path": "/habit/assign/4325"
}

**Expected result**
Response 401 user should be authorized.

**User story and test case links**
User story #988

**Comment by oprotyniak** [comment]
Expected result in this case should have been:
![image](https://user-images.githubusercontent.com/73852063/100599613-e9c9bf00-3308-11eb-8ad1-88377474bb6e.png)
