### ISSUE TITLE
[API][Habits] PATCH/habit/assign/{habitAssignId} controller returns 500

### ISSUE THREAD

**Issue by krivondulia** [ita-social-projects/GreenCity#1778]
**Environment:** Swagger
**Reproducible:** always
**Build found:** commit 8b208c6

**Preconditions**
User should be authorized (e.g., email: sunnyraintest@ukr.net, password: Mysunnytest#1)

**Steps to reproduce**
1. Go to https://greencity.azurewebsites.net/swagger-ui.html#/habit-controller/updateAssignUsingPATCH
2. Click on 'Try it on'
3. Use habitAssignId e.g. "4325" and habitAssignStatDto "{
  "acquired": true,
  "suspended": true
}"

**Actual result**
Response 500.  {
  "timestamp": "2020-10-31T19:16:15.167+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Habit assign does not exist by this id : ",
  "path": "/habit/assign/4325"
}

**Expected result**
Response 201.

**User story and test case links**
User story #994

**Comment by SashkoMolodec** [comment]
Method has changed.
