### ISSUE TITLE
[Gallery view] [List view] Gallery and List view buttons dissappear when width of window is less than 529

### ISSUE THREAD

**Issue by BohdanDziubailo** [ita-social-projects/GreenCity#1782]
**Environment:** Windows 10, Google Chrome  v86.0.4240.111
**Reproducible:** Always
**Build found:** GreenCityClient dev: 8b208c6

**Preconditions**
1) Navigate to https://ita-social-projects.github.io/GreenCityClient/#/news
2) Press F12 and select "Toggle device toolbar"
![_1](https://user-images.githubusercontent.com/68228941/97857536-9282ff80-1d06-11eb-8fd0-f80d83036a3c.png)

**Steps to reproduce**
1. Set width of device to 530 - you still see Gallery/List view buttons
2. Set width of device to 529 - you still see Gallery/List view buttons
3. Set width of defice to 528

**Actual result**
Buttons of switching List-Gallery views disappeared
![_2](https://user-images.githubusercontent.com/68228941/97858064-46848a80-1d07-11eb-80e0-68e579d333a0.png)

**Expected result**
[Advice] When width of screen becomes less then 529, than display news in List-view mode.

[Notice, also bug] Even if we select List view before shrinking the width, after described actions buttons will disappear and news will display in Gallery view mode. https://jira.softserve.academy/browse/GC-707

**User story and test case links**
[Test case] https://jira.softserve.academy/browse/GC-669
[Test case] https://jira.softserve.academy/browse/GC-704

**Comment by JimHolman1199** [comment]
@BohdanDziubailo hi, if i understood correctly they should disappear when the screen is less than 576px ?
![Screenshot 2020-11-04 at 23 39 03](https://user-images.githubusercontent.com/46226026/98171180-fae50300-1ef7-11eb-8f24-bce8dcf5d63f.png)
n

**Comment by BohdanDziubailo** [comment]
Yes, they disappear when width of body is less then 576px(or less then 529px when you do this like i described in report).
I don't know, is it really a bug or just a "feature", but when i showed this behavior to Victoria and she said that i should report it as a bug. Also this behavior is not described in Figma mock-ups.

**Comment by JimHolman1199** [comment]
@BohdanDziubailo  hello, you can check it again, because from where I stand, I see that everything is correct.
According to the design, we should remove the buttons if the width is less than 576px, and display the news in the gallery view.
thanks

**Comment by bohdana1** [comment]
not fixed

**Comment by VasylynaYaremkiv** [comment]
https://jira.softserve.academy/browse/GC-1321 User Story

**Comment by VasylynaYaremkiv** [comment]
size 576 and more-there are buttons,
size 575 and less-there are no buttons
![570 size no buttons](https://user-images.githubusercontent.com/77506104/105386165-bf1b2900-5c1c-11eb-831f-c2edd0cb3b12.png)
![575 size no buttons](https://user-images.githubusercontent.com/77506104/105386172-c04c5600-5c1c-11eb-82c2-5f0bacd1d723.png)
![580 size -there are buttons](https://user-images.githubusercontent.com/77506104/105386175-c04c5600-5c1c-11eb-983f-c0f809432e82.png)
