### ISSUE TITLE
Like and unlike don`t work 

### ISSUE THREAD

**Issue by forestik** [ita-social-projects/GreenCity#1789]
**Environment:**  Windows 10 Home, Google Chrome
**Reproducible:** always, 

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/news/4708'
2. Click on 'like'
Execute request.

**Actual result**
![Screenshot 2020-11-02 204350](https://user-images.githubusercontent.com/68025190/97906622-a8b3ae80-1d4c-11eb-91cb-a3032916f295.png)

**Expected result**
The number of likes has not changed

**Comment by bohdana1** [comment]
not fixed
