### ISSUE TITLE
[Sign Up] An improper message on leaving email-field empty.

### ISSUE THREAD

**Issue by ProstoLeleka** [ita-social-projects/GreenCity#1844]
**Environment**: Windows 7, Chrome 86.0.4240.111
**Reproducible**: always
**Build found**: commit cc99c87

**Steps to reproduce**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on Sign up
3. Leave email-field empty
4. Click on any element except email-field

**Actual result**
A message appears:
This field is required
![Screenshot_29](https://user-images.githubusercontent.com/34520370/98995154-99e1ae80-2539-11eb-9cf7-d4b9c8a3e98e.png)

**Expected result**
A message appears: 
Email is required

User story #455

**Comment by JimHolman1199** [comment]
Please check this again 
<img width="1234" alt="Screenshot 2020-12-01 at 01 26 33" src="https://user-images.githubusercontent.com/46226026/100677716-4910e900-3374-11eb-843d-a23ade073960.png">
