### ISSUE TITLE
[ІSign in\sign up] Registered User can not receive email to restore password via  'Forgot password?' link

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1849]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041 
Mozilla Firefox Browser 82.0.3 (64-bit)
Microsoft Windows 7 Home
Chrome Browser Версія 86.0.4240.198 (Розробка) (32-розрядна версія)

Reproducible: always
Build found:14.11.2020

Preconditions
The user should be registered in the 'GreenCity' application

Steps to reproduce
1. Go to the 'https://ita-social-projects.github.io/GreenCityClient/#/welcome'
2. Click on the 'Sign in' button in the top right part of the window.
3. Click on the 'Forgot password?' link.
4. Enter email address in the 'Email' field, which is registered in the system. (tatiana.peutina@gmail.com)
5. Click on the 'Submit a login link' button.
6. Pay attention to the result

Actual result
'Email' field is highlighted in red color and error message : 'java.net.SocketTimeoutException: connect timed out ' is emerged under the 'Email' field.
![forgot pass bug](https://user-images.githubusercontent.com/65060199/99148792-72522980-2692-11eb-89bd-ca0fb9ceabe3.PNG)

Expected result
'Forgot password' popup has disappeared.

User story and test case links
E.g.: "User story  #472 
[Test case](https://jira.softserve.academy/browse/GC-521)
[Test case] (https://jira.softserve.academy/browse/GC-504)

**Comment by vandrusenko** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/75262612/102715344-74d12000-42dd-11eb-83e5-30447c167af2.png">
The bug was fixed.
