### ISSUE TITLE
[Search] Redundant item 'see all results' under topic 'News'

### ISSUE THREAD

**Issue by bohdana1** [ita-social-projects/GreenCity#1851]
Environment: Microsoft Windows 7 Home
Chrome Browser Версія 86.0.4240.198 (Розробка) (32-розрядна версія)
Reproducible: always.
Build found: 14.11.2020

Steps to reproduce
1. Log into 'https://ita-social-projects.github.io/GreenCityClient/#/welcome'
2. Click on 'Search' item
3. Type velues into field (e.g. 'as')

Actual result
'See all news' links are shown under 'News' and 'Tip & Triks' items.
Attachment added

Expected result
'See all news' link is shown at the bottom of the page under the last found item. 

User story and test case links
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/545
[Test case](https://jira.softserve.academy/browse/GC-760)"

Labels to be added
"Bug", Priority ("medium"), Severity ("minor"), Type ("UI").
![see all results](https://user-images.githubusercontent.com/73852733/99154949-6da26b00-26bc-11eb-9c83-45f009d0a811.png)
![see all](https://user-images.githubusercontent.com/73852733/99154950-6ed39800-26bc-11eb-911a-dd615bb09841.png)

**Comment by JimHolman1199** [comment]
Should be See all news and See all tips & tricks

**Comment by IrynaShlyakhetko** [comment]
'See all news' link is shown only 'News'  items
Actual Result:
<img width="1231" alt="Screen Shot 2021-01-21 at 15 40 52" src="https://user-images.githubusercontent.com/77668307/105359220-dbf53380-5bff-11eb-8a6c-909886b0d29f.png">
