### ISSUE TITLE
[Display news: List view]  Invalid number of content items are displayed by default

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1854]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Mozilla Firefox Browser 82.0.3 (64-bit)
Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Environment: Microsoft Windows 7 Home
Chrome Browser Версія 86.0.4240.198 (Розробка) (32-розрядна версія)
Reproducible: always.
Build found: 15.11.2020

Steps to reproduce
1. Go to the link https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on  the 'Eco news' button
3. Click on the 'List view' icon
4. Pay attention to the result.

Actual result
First twelve content items are displayed by default

Expected result
First six content items are displayed by default

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-710)
[Test case](https://jira.softserve.academy/browse/GC-332)

**Comment by vandrusenko** [comment]
The bug is fixed.
