### ISSUE TITLE
[Sign up] "Будь ласка, внеси свої дані для реєстрації" label is misspelled

### ISSUE THREAD

**Issue by natalinapr** [ita-social-projects/GreenCity#1856]
**Environment:** OS Windows 10 Pro, Version 2004
Mozilla Firefox, Version 82.0.3
**Reproducible:** always
**Build found:** 16.11.2020 from https://github.com/ita-social-projects/GreenCityClient/tree/dev

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Change the application language to Ukrainian
3. Click on Sign-up button

**Actual result**
"Будь ласка, внеси свої дані для реєстрації" label is displayed.
![Sign up UI MISSPELLING](https://user-images.githubusercontent.com/62031226/99240105-b06f5a80-2804-11eb-8ed0-c951959adcf9.png)

**Expected result**
"Будь ласка, внесіть свої дані для реєстрації." label should be displayed.
![Sign up UI](https://user-images.githubusercontent.com/62031226/99240060-9f264e00-2804-11eb-9ba6-1faae96ea3b3.png)

**User story and test case links**
User story #455
[Verify 'Sign up' page UI](https://jira.softserve.academy/browse/GC-216)

**Comment by Benerous** [comment]
Which statement is correct: "Внеси" or "Внесіть"?
There is another bug report which is opposite to this [#1786](https://github.com/ita-social-projects/GreenCity/issues/1786)

**Comment by chelkis** [comment]
Correct statement according to mock-up is "Внесіть".

**Comment by chelkis** [comment]
> Which statement is correct: "Внеси" or "Внесіть"?
> There is another bug report which is opposite to this [#1786](https://github.com/ita-social-projects/GreenCity/issues/1786)

Correct statement according to mock-up is "Внесіть".

**Comment by Benerous** [comment]
> > Which statement is correct: "Внеси" or "Внесіть"?
> > There is another bug report which is opposite to this [#1786](https://github.com/ita-social-projects/GreenCity/issues/1786)
> 
> Correct statement according to mock-up is "Внесіть".

This question was recently discussed that should be used informal style of communication with a User. The mock-up is out-of-date.
