### ISSUE TITLE
['Sign-up'] The wrong error-message displayes when user leaves all fields empty on the ‘Registration’ page

### ISSUE THREAD

**Issue by Yuliia-Rutetska** [ita-social-projects/GreenCity#1872]
Environment: Mozilla Firefox, Version 83.03 (64- bit)
Reproducible: always
Build found: 18.11.2020

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/welcome'
2. Click on the ''Sign-up' button'
3. Leave all fields empty
4. Click on 'Sing-up' button

**Actual result**
For the 'Email' field displayes error-message 'This field is required'
For 'User Name' field displayes error-message 'The name must contain 6-30 characters and can contain letters(a-z), numbers(0-9) and a dot(.)'
For the 'Password' field displayes error-message 'Password has contain at least one character of Uppercase letter (A-Z), Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.)'
For the 'Confirm Password' field error-message does not display.
![Screenshot 2020-11-22 172503](https://user-images.githubusercontent.com/73403555/99907820-c474f980-2ce7-11eb-9dd3-f4200e893e5b.jpg)

**Expected result**
For the 'Email' field displayes error-message 'Email is required'
For User Name' field displayes error-message 'User Name is required'
For the 'Password' field displayes error-message 'Password is required'
For the 'Confirm Password' field displayes error-message 'Password is required'

E.g.: "User story #455 #617

**Comment by vandrusenko** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/75262612/102715190-5f0f2b00-42dc-11eb-8d4b-5faeab003fff.png">
The bug is fixed.
