### ISSUE TITLE
[Display news, Gallery view] Wrong alignment of news cards when resolution 1440px, 1024px, 768px, 576px.

### ISSUE THREAD

**Issue by natalinapr** [ita-social-projects/GreenCity#1878]
**Environment:** OS: Windows 10 Pro, Version 2004
Browser: Mozilla Firefox, Version: 82.0.3
**Reproducible:** always
**Build found:** last commit from 19.11.2020

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in application
3. Open 'Eco news' page
4. Open devtool

**Actual result**

1. 1440px: 
News cards are not aligned on the right side. There is space between news cards of the third column and alignment line.
![1440 674](https://user-images.githubusercontent.com/62031226/99709312-b173e680-2aa7-11eb-97e1-ced50b9e6201.png)

2. 1024px:
News cards in third columns are beyond the alignment field.
![1024 674](https://user-images.githubusercontent.com/62031226/99710385-28f64580-2aa9-11eb-855a-223c9853e4f7.png)

3. 768px:
News cards in second columns are beyond the alignment field.
![768](https://user-images.githubusercontent.com/62031226/99713789-678dff00-2aad-11eb-8db9-3c95787e4a27.png)

4. 576px:
News cards in second columns are beyond the alignment field.
![576 0](https://user-images.githubusercontent.com/62031226/99715431-88575400-2aaf-11eb-97bf-087cc4e0037f.png)

**Expected result**

1. 1440px:
News cards are aligned according to mockup.
![image](https://user-images.githubusercontent.com/62031226/99708819-fc412e80-2aa6-11eb-824b-a45f4dc0b23d.png)

2. 1024px:
News cards in third columns are in the alignment field according to mockup.
![image](https://user-images.githubusercontent.com/62031226/99713401-ed5d7a80-2aac-11eb-9dab-adf8e39014a5.png)

3. 768px:
News cards in second columns are in the alignment field according to mockup.
![image](https://user-images.githubusercontent.com/62031226/99714207-fe5abb80-2aad-11eb-9518-548ba56425ac.png)

4. 576px:
News cards in second columns are in the alignment field according to mockup.
![image](https://user-images.githubusercontent.com/62031226/99715610-c6547800-2aaf-11eb-98ea-77fc52638627.png)

**User story and test case links**
User story #971
[[Display news, Gallery view] Verify that Gallery view has 3 columns on 1140-1024, 2 columns on 768-576 and 1 column on 320 screen resolutions] (https://jira.softserve.academy/browse/GC-668)

**Comment by romanovskyroma** [comment]
this bug was fixed in [#664](https://github.com/ita-social-projects/GreenCityClient/pull/664) pull request.
