### ISSUE TITLE
[Display news: List view] Incorrect size and alignment of UI elements of news item on 'List view' page (1024 resolution Mozilla)

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1879]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Mozilla Firefox Browser 82.0.3 (64-bit)
Reproducible: always
Build found: 2020-11-19

Preconditions
1. Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. User should be authorized
3. There should be at least one news created by current user

Steps to reproduce
1. Click on the 'Eco news' button
2. Click on the 'List view' icon
3. Verify  UI elements' size and alignments of the news item  on 1199-992 resolution (ex. 1024 as we have mock - up with resolution 1024)with dev tool help.
4. Pay attention to the result.

Actual result
1. The size of the image is 299x166
![image size](https://user-images.githubusercontent.com/65060199/99701509-39a0be80-2a9d-11eb-803d-5cd3338da2cf.jpg)
2. The size of the 'News' label is 40x14
![news label](https://user-images.githubusercontent.com/65060199/99707815-a3bd6180-2aa5-11eb-9e14-1a670a0f03f2.jpg)
3. The height of the 'Date' label is 24
![data size](https://user-images.githubusercontent.com/65060199/99718302-5811b480-2ab3-11eb-9ae0-a3a240019a4d.jpg)

4. The height of the 'Author' label is 24
![author](https://user-images.githubusercontent.com/65060199/99712748-2812e300-2aac-11eb-8d2d-77a3e8f6e524.jpg)
5. The size of the 'Title' label is 322x26
![title](https://user-images.githubusercontent.com/65060199/99714129-dec39300-2aad-11eb-8361-f3fec22678f0.jpg)
6. Incorrect alignment of the news item
![alignment](https://user-images.githubusercontent.com/65060199/99717503-264c1e00-2ab2-11eb-8798-7cd9c5a075fe.PNG)

Expected result
1. The size of the image is 299x171
![image mock](https://user-images.githubusercontent.com/65060199/99701662-66ed6c80-2a9d-11eb-8fa6-77121b067530.jpg)
2. The size of the 'News' label is 42x16
![news label mock](https://user-images.githubusercontent.com/65060199/99707830-aa4bd900-2aa5-11eb-9200-3af1315af84f.jpg)
3. The height of the 'Date' label is 21
![data size mock](https://user-images.githubusercontent.com/65060199/99718487-9b6c2300-2ab3-11eb-99cf-9d100372ba02.jpg)
4. The height of the 'Author' label is 21
![author mock](https://user-images.githubusercontent.com/65060199/99712981-7b853100-2aac-11eb-8782-2283335bb089.jpg)
5. The size of the 'Title' label is 613x53
![title mock](https://user-images.githubusercontent.com/65060199/99713803-6d83e000-2aad-11eb-8315-689cbb023f2f.jpg)
6. Correct alignment of the news item
![alignment mock](https://user-images.githubusercontent.com/65060199/99717540-349a3a00-2ab2-11eb-805f-89c11849e646.PNG)

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-720)"

**Comment by YulianaQC** [comment]
1. 299x171
2. 42.9x19
4. ?
5. 612x26

**Comment by OksanaRom** [comment]
**Actual result:** 
1.The size of the 'News' label is 44x16 
2.The size of the 'Title' label is 733x26
**Expected result:**
1.The size of the 'News' label is 35x16 
2.The size of the 'Title' label is 733x28
![size news lable](https://user-images.githubusercontent.com/80678953/113508528-2e849180-9559-11eb-8592-21e7a5744162.jpg)
![size of news name field](https://user-images.githubusercontent.com/80678953/113508529-2fb5be80-9559-11eb-8149-9eb841abf8c6.jpg)
