### ISSUE TITLE
[Gallery view] News is misaligned and do not match the mock-up

### ISSUE THREAD

**Issue by Yuliia-Rutetska** [ita-social-projects/GreenCity#1880]
Environment: Explorer, Version 86.0.622.69 (64-bit); Mozilla Firefox, Version 83.03 (64- bit)
Reproducible: always
Build found: 19.11.2020

Pre-conditions:
Go to https://ita-social-projects.github.io/GreenCityClient/

Steps to reproduce:
1. Sign in application
2. Open 'Eco news' page
3. Open devtool
4. Verify UI of news alignment on 1024, 768, 576 px resolution

**Actual result**
News alignment is not carried out in accordance with the mock-up

1024px:
![1024_LI](https://user-images.githubusercontent.com/73403555/99717827-9b1f5800-2ab2-11eb-9fb9-02d80724beb4.jpg)
768px:
![Inked768  до 674_LI](https://user-images.githubusercontent.com/73403555/99717834-9d81b200-2ab2-11eb-9032-d5a07d3b3be9.jpg)
576px:
![Inked576_LI](https://user-images.githubusercontent.com/73403555/99717841-9f4b7580-2ab2-11eb-9d02-862f54600896.jpg)

**Expected result**
News alignment is carried out in accordance with the mock-up
![mock-up](https://user-images.githubusercontent.com/73403555/99717923-bc804400-2ab2-11eb-852c-4dac733f812f.jpg)

"User story #971

**Comment by JimHolman1199** [comment]
@Yuliia-Rutetska hi, can you check this again, please?
