### ISSUE TITLE
[Gallery view] On the 'Eco News' page the content item has an inappropriate names and number of tags

### ISSUE THREAD

**Issue by Yuliia-Rutetska** [ita-social-projects/GreenCity#1882]
Environment: Mozilla Firefox, Version 83.03 (64- bit);  Explorer, Version 86.0.622.69 (64-bit)
Reproducible: always
Build found: 19.11.2020

Pre-condition:
1. Go to https://ita-social-projects.github.io/GreenCityClient/
2. User should be registered on the Green City page.
3. Publish news in such tags as 'News', 'Events', 'Courses', 'Initiatives', and 'Ads' without attaching pictures

Steps to reproduce:
1. Go to 'Eco News' page 
2. Verify that Content item has relevant tags

**Actual result**
On the 'Eco News' page Content item has the following tags:
- 'Ads'
- 'Events'
- 'News'
- 'Education'
- 'Initiatives'
- 'Lifehacks'
![tag incorrect](https://user-images.githubusercontent.com/73403555/99724470-51d40600-2abc-11eb-910e-a73376568f08.jpg)

**Expected result**
On the 'Eco News' page Content item has the following tags: 
- 'News'
- 'Events'
- 'Courses'
- 'Initiatives'
-  'Ads'
![tag](https://user-images.githubusercontent.com/73403555/99724366-32d57400-2abc-11eb-811b-0c334339fc2d.jpg)

Post-condition:
The person, who verifies this test case has access to 'Green City' project DataBase
Delete created news from the database by using SQL queries:
DELETE FROM eco_news_tags
WHERE eco_news_id=<news id>;
DELETE FROM eco_news
WHERE id=<news id>;

E.g.: "User story #971 ,#459

**Comment by JimHolman1199** [comment]
already fixed.
related to database and BE
