### ISSUE TITLE
[List view] Incorrect size and alignment of UI elements of news item on 'List view' page (768 resolution Mozilla)

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1883]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Mozilla Firefox Browser 82.0.3 (64-bit)
Reproducible: always
Build found: 2020-11-19

Preconditions
1. Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. User should be authorized
3. There should be at least one news created by current user

Steps to reproduce
1. Click on the 'Eco news' button
2. Click on the 'List view' icon
3. Verify UI elements size and alignments of the news item on 991-768 resolution (ex. 768 as we have mock - up with resolution 768) with dev tool help.
4. Pay attention to the result.

Actual result
1. The size of the image is 359x204
![image](https://user-images.githubusercontent.com/80644037/113913129-a0bcd680-97e4-11eb-87cb-924c6ddc30a8.png)

2. The size of the 'News' label is 44x16
![image](https://user-images.githubusercontent.com/80644037/113913215-bb8f4b00-97e4-11eb-8c5b-d2b3807389a6.png)

3. The width of the 'Date' label is 88
![image](https://user-images.githubusercontent.com/80644037/113913551-25a7f000-97e5-11eb-9401-2b05ccfa4132.png)

5. The size of the 'Title' label is 733x100
![image](https://user-images.githubusercontent.com/80644037/113913805-6d2e7c00-97e5-11eb-8099-ad77c64d7055.png)

6. Incorrect alignment of the news item
![alignment 768](https://user-images.githubusercontent.com/65060199/99721956-9e1d4700-2ab8-11eb-975f-770a6613b86a.PNG)

Expected result
1. The size of the image is 204x204
![image](https://user-images.githubusercontent.com/80644037/113913912-918a5880-97e5-11eb-9b35-299fa8ef81d0.png)

2. The size of the 'News' label is 35x16
![image](https://user-images.githubusercontent.com/80644037/113913987-a6ff8280-97e5-11eb-941e-934179588582.png)

3. The height of the 'Date' label is 21
![data mock 768](https://user-images.githubusercontent.com/65060199/99723998-a3c85c00-2abb-11eb-9dc3-bca528c6cb9b.jpg)

4. The height of the 'Author' label is 20
![image](https://user-images.githubusercontent.com/80644037/113914017-b54d9e80-97e5-11eb-8542-5d23caa80d2e.png)

5. The size of the 'Title' label is 468x56
![image](https://user-images.githubusercontent.com/80644037/113914086-cac2c880-97e5-11eb-8608-8ecb5c5556c6.png)

6. Correct alignment of the news item
![alignment mock 768](https://user-images.githubusercontent.com/65060199/99722038-b9885200-2ab8-11eb-9eb5-1449e2d878d4.PNG)

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-720)"

**Comment by YulianaQC** [comment]
Actual result:
1. The size of the image is 190x190
![Image1](https://user-images.githubusercontent.com/77490082/105363962-452b7580-5c05-11eb-85a3-84e6ed2a06bd.png)
2. The size of the 'News' label is 42.9833x19
![зображення](https://user-images.githubusercontent.com/77490082/105364308-b10dde00-5c05-11eb-8650-6161cf011794.png)
3.  Done
4. The width of the 'Author' label is 110.567
![зображення](https://user-images.githubusercontent.com/77490082/105365000-7a849300-5c06-11eb-91ab-073f4024d804.png)
5.The size of the 'Title' label is 482x24
![зображення](https://user-images.githubusercontent.com/77490082/105365616-1b734e00-5c07-11eb-92c6-01d49dbfbfe9.png)
6.  Done.

**Comment by VitalyBorysenko** [comment]
New mockup https://www.figma.com/file/yFVSRLVAA1umR2nSj6B7ba/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12671%3A6429

Expected result:
1. The size of the image is 334x191. - 
  Result: 204x204 by new mockup.
![image](https://user-images.githubusercontent.com/24696596/109803678-04724380-7c2a-11eb-80a6-aaa14a76bf2f.png)

2. The size of the 'News' label is 42x16. - Fixed in task https://github.com/ita-social-projects/GreenCity/issues/1879.
3. The height of the 'Date' label is 21. - 20 height of this block (browser automatically calculated).
4. The height of the 'Author' label is 21. - 20 height of this block (browser automatically calculated).
5. The size of the 'Title' label is 501x78. -  Changed dynamically. Depending on the amount of text. MAX height is really 72.
6. Correct alignment of the news item. - Can't see the bug. Maybe fixed in previous tasks

**Comment by SerhiiStarshoi** [comment]
Actual result

1. The size of the image is 204x204 (meets expected result)
2. The size of the 'News' label is 46x16 (expected result 35x16) 
![photo_2021-06-08 17 35 05](https://user-images.githubusercontent.com/32453285/121204900-e860ec80-c87f-11eb-93df-f9533e762b81.jpeg)
3. The height of the 'Date' label is 20 (meets expected result)
4.  The size of the 'Title' label is 468x52 (expected result 468x56)
![photo_2021-06-08 17 46 33](https://user-images.githubusercontent.com/32453285/121206867-7a1d2980-c881-11eb-9cb0-a254666ebad0.jpeg)

**Comment by Ol98** [comment]
Actual result:
1. The size of the 'Title' label is 485x28 (expected result 468x56)
![image](https://user-images.githubusercontent.com/91474733/135711313-0af2785d-5ab1-420b-9879-e25e9af40d4a.png)

2. The size of the 'Subtitle' label is 485x21
![image](https://user-images.githubusercontent.com/91474733/135711417-d0e2c370-6ad6-49be-861e-76d5d5b39fed.png)

Expected result:
1. The size of the 'Title' label is  468x56
2. The size of the 'Subtitle' label is 468x40
