### ISSUE TITLE
[Display news, Gallery view] News cards are of different sizes when resolution is 768px.

### ISSUE THREAD

**Issue by natalinapr** [ita-social-projects/GreenCity#1884]
**Environment:** OS: Windows 10 Pro, Version 2004
Browser: Mozilla Firefox, Version: 82.0.3
**Reproducible:** always
**Build found:** commit 19.11.2020

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in application
3. Open 'Eco news' page
4. Open devtool
5. Establish resolution 768px

**Actual result**
There are news card of 350x503 size and news card of 350x500 size.
![768 1](https://user-images.githubusercontent.com/62031226/99724963-184fca80-2abd-11eb-8db3-5e63a98d4ab8.png)
![768 2](https://user-images.githubusercontent.com/62031226/99724976-1c7be800-2abd-11eb-848a-83c3099e0aa7.png)

**Expected result**
All news cards are 350x500 in size.
![mockup2](https://user-images.githubusercontent.com/62031226/99725256-81cfd900-2abd-11eb-9c25-c9c6a841f26b.png)

**User story and test case links**
User story #971
[Verify that news are aligned according to the news title and content length](https://jira.softserve.academy/browse/GC-674)

**Comment by Benerous** [comment]
Are these **Steps to reproduce** correct? I haven't noticed any differences in the size of cards
![image](https://user-images.githubusercontent.com/59996447/101172183-8366d880-3649-11eb-9a5b-7fb83d7b7cce.png)
![image](https://user-images.githubusercontent.com/59996447/101172201-895cb980-3649-11eb-92d9-46082c587be1.png)
