### ISSUE TITLE
List view] Incorrect size and alignment of UI elements of news item on 'List view' page (576 resolution Mozilla, Chrome)

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1887]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Mozilla Firefox Browser 82.0.3 (64-bit)
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Reproducible: always
Build found: 2020-11-19

Preconditions
1. Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. User should be authorized
3. There should be at least one news created by current user

Steps to reproduce
1. Click on the 'Eco news' button
2. Click on the 'List view' icon
3. Verify UI elements size and alignments of the news item on 767-576 resolution (ex. 576 as we have mock - up with resolution 576) with dev tool help.
4. Pay attention to the result.

Actual result
1. The size of the 'News' label is 40x14 (Mozilla, Chrome)
![news 576](https://user-images.githubusercontent.com/65060199/99731185-340b9e80-2ac6-11eb-93e3-d3eece5ef475.jpg)
2. The height of the 'Date' label is 24 (Mozilla, Chrome)
![date 576](https://user-images.githubusercontent.com/65060199/99730978-e000ba00-2ac5-11eb-8151-8045f13cce7f.jpg)
3. The height of the 'Author' label is 24 (Mozilla, Chrome)
![author 576](https://user-images.githubusercontent.com/65060199/99730675-88fae500-2ac5-11eb-9b5a-7a65226761a8.jpg)
4. The size of the 'Title' label is 322x26 (Mozilla, Chrome)
![title 576](https://user-images.githubusercontent.com/65060199/99730511-3d483b80-2ac5-11eb-939a-0d8c61d835a9.jpg)
5. Incorrect alignment of the news item (Mozilla)
![alignment 576](https://user-images.githubusercontent.com/65060199/99729933-543a5e00-2ac4-11eb-8f99-cd2c04230c94.PNG)
6. Incorrect alignment of the news item (Chrome)
![alignment 576](https://user-images.githubusercontent.com/65060199/99883199-849e0b80-2c2e-11eb-85b4-9118b316c017.PNG)

Expected result
1. The size of the 'News' label is 36x16
![image](https://user-images.githubusercontent.com/80644037/113693475-50a41e00-96d7-11eb-9826-042c7898d3b7.png)

2. The height of the 'Date' label is 20
![image](https://user-images.githubusercontent.com/80644037/113693371-34a07c80-96d7-11eb-8b00-dcfb04540dc6.png)

3. The height of the 'Author' label is 20
![image](https://user-images.githubusercontent.com/80644037/113693422-41bd6b80-96d7-11eb-8f80-32913bfd9cc5.png)

4. The size of the 'Title' label is 492x28
![image](https://user-images.githubusercontent.com/80644037/113693516-5a2d8600-96d7-11eb-8fdc-789feb7b8c42.png)

5. Correct alignment of the news item
![alignment mock 576](https://user-images.githubusercontent.com/65060199/99729920-4dabe680-2ac4-11eb-8847-d7bcfe3f09a4.PNG)

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-720)

**Comment by VasylynaYaremkiv** [comment]
Actual result
1.The size of the 'News' label is 42.99*19.2 on Mozilla, Chrome (expected 42*16)
2.The height of the 'Date' label is Mozilla-21, Chrome-20, but 95*20 on Chrome and 109*21 on Morzilla (expected 95*21)
3.The height of the 'Author' label is Mozilla 21 and  Chrome-20 (expected-21)
4.The size of the 'Title' label is 492*72 on Chrome  210*147 on Morzilla (expected 492x72)
5.Incorrect alignment of the news item (edd attachmens)
![5 Chrome](https://user-images.githubusercontent.com/77506104/105383430-c856c680-5c19-11eb-90ee-7b6a1d6521eb.png)
![5  Morzilla](https://user-images.githubusercontent.com/77506104/105383433-c8ef5d00-5c19-11eb-8a00-9f56334ba394.png)

**Comment by VitalyBorysenko** [comment]
new mockup https://www.figma.com/file/yFVSRLVAA1umR2nSj6B7ba/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12201%3A1

**Comment by VitalyBorysenko** [comment]
Expected result
1. The height of the 'News' label is 16px - fixed with bug https://github.com/ita-social-projects/GreenCity/issues/1879
2. The height of the 'Date' label is 21. - 20 height of this block (browser automatically calculated).
3. The height of the 'Author' label is 21. - 20 height of this block (browser automatically calculated).
4. The size of the 'Title' label is 500x72. - Changed dynamically. Depending on the amount of text. MAX height is really 72.
5. Incorrect alignment of the news item. - If you mean news filter, it has the horizontal scroll (by new mockup).
![image](https://user-images.githubusercontent.com/24696596/109669769-1d6feb80-7b7b-11eb-9fbf-323b85f66dc4.png)

**Comment by SerhiiStarshoi** [comment]
alignment of the news item<img width="594" alt="image" src="https://user-images.githubusercontent.com/32453285/121079912-720eac80-c7e3-11eb-91e9-6fe58fd1721b.png">

**Comment by DarynaPashkevych** [comment]
Actual result
1.The size of the 'News' label is 46x16
![image](https://user-images.githubusercontent.com/46245318/121667604-22fe9b00-cab3-11eb-9745-5bc0d342755e.png)

2.The size of the 'Title' label is 492x26
![image](https://user-images.githubusercontent.com/46245318/121667993-825cab00-cab3-11eb-98da-78e07464ca60.png)


Expected Result
1.The size of the 'News' label is 35x16
![image](https://user-images.githubusercontent.com/46245318/121667727-41649680-cab3-11eb-9593-bca3b6061f56.png)

2.The size of the 'Title' label is 492x28
![image](https://user-images.githubusercontent.com/46245318/121668048-91435d80-cab3-11eb-91c8-2b86cf9e83a6.png)

User story #460
https://jira.softserve.academy/browse/GC-720

**Comment by Ol98** [comment]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Mozilla Firefox Browser 82.0.3 (64-bit)
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Reproducible: always

Actual result:
1. The size of the main header "Eco News" is 256x48
![image](https://user-images.githubusercontent.com/91474733/135135006-e6568594-e690-4ff0-b78f-8c506dcc086b.png)

2. The size of the 'Title' label is 504,95x28
![image](https://user-images.githubusercontent.com/91474733/135131584-83885f5e-058a-46e8-baea-3c4a0d46a6cd.png)

3. The size of the list card is 452,4x192
![image](https://user-images.githubusercontent.com/91474733/135135459-64df34c1-4c30-4cf1-9f9c-6c36364b697c.png)

4. The size of the 'Date' label is 99,25x20
![image](https://user-images.githubusercontent.com/91474733/135132616-3b28aefc-b8bb-489f-b80d-a58f2452f02b.png)

5.Incorrect alignment of the news item . Width is 23,05
![image](https://user-images.githubusercontent.com/91474733/135138702-87b4cb3a-2461-42c0-9769-ecfb5a5798a3.png)

Expected result:
1. The size of the main header "Eco News" is 201x56
2. The size of the 'Title' label is 492x28
3. The size of the list card is 540x192
4. The size of the 'Date' label is 95x20
5. Alignment of the news item: Width is 18.

**Comment by MyroslavaVynokur** [comment]
Please have a look to the step 2 and 3
Actual result:
2. 
 <img width="657" alt="Screenshot 2021-11-30 at 21 52 40" src="https://user-images.githubusercontent.com/34717146/144119122-947b4e56-0910-4438-9ea6-406a3d9f5f95.png">

 3. 
<img width="595" alt="Screenshot 2021-11-30 at 21 55 24" src="https://user-images.githubusercontent.com/34717146/144119152-a1b5d04e-dbd1-48db-9d83-6c312a55827d.png">
