### ISSUE TITLE
[Display News, List View] Incorrect display of Title with 4 rows

### ISSUE THREAD

**Issue by oprotyniak** [ita-social-projects/GreenCity#1889]
**Environment:** Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
   Microsoft Windows 10 Home, Version 10.0.19041 
   Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 20.11.2020

**Preconditions**
1. https://ita-social-projects.github.io/GreenCityClient/ is opened.
2. News items are created in the DB and are displayed as first news item in the list view. Use queries:
INSERT INTO eco_news
(ID, title, text, author_id, creation_date)
VALUES (708, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim ven',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure d',
857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (708, 1), (708, 3);

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Eco news' link in the header.
3. Set browser window width to 1024px.
4. Click on the View as a List option on the right side of the page.
5. Pay attention to created news Title and Description display.

**Actual result**
- Title is displayed and consists of 4 rows and has 104px in height In Mozilla, Title is displayed and consists of 4 rows and has 102px in height in Chrome, No description is shown.
- Title content is placed out of the frame. 
![image](https://user-images.githubusercontent.com/73852063/99734161-0412ca00-2acb-11eb-9110-a598ae50960d.png)
![bd chrome](https://user-images.githubusercontent.com/65060199/99738944-586e7780-2ad4-11eb-95ca-90a17469c689.jpg)

**Expected result**
- Title is displayed and consists of 4 rows and has 128px in height. No description is shown.
- Title content is placed inside of the frame. 

**Postconditions**
Created news are deleted from DB using queries:
DELETE FROM eco_news_tags
WHERE eco_news_id = 708;

DELETE FROM eco_news
WHERE id = 708;

**User story and test case links**
User story #460
[Test case](https://jira.softserve.academy/browse/GC-708)

**Comment by JimHolman1199** [comment]
hiiiii
can you check this again? please )

**Comment by oprotyniak** [comment]
Hi, the title now is placed within the frame, but problem with the size still exists. In addition the row with author and date now overlaid with 'Title' field.
![image](https://user-images.githubusercontent.com/73852063/101682524-66c50900-3a6c-11eb-9573-6691eb28b327.png)

**Comment by oprotyniak** [comment]
The test data given above is designed to test 4 row title. Now the results show 2 row title. 
![image](https://user-images.githubusercontent.com/73852063/103320416-ecb9eb80-4a3d-11eb-9e46-21b2079545d9.png)

**Comment by JimHolman1199** [comment]
how can i put a 4 line header there?
see design for 1024px
<img width="781" alt="Screenshot 2020-12-31 at 12 17 46" src="https://user-images.githubusercontent.com/46226026/103406113-3bf93c80-4b62-11eb-9e3a-f38401151783.png">

**Comment by oprotyniak** [comment]
Hello! I am not sure what do you mean by this image and "4 line header". We have user story #460 with the guidelines that are shown on mock-up for different title heights (including 4 row title). If 4 row  title is not possible to implement we should discuss this at the meeting.

**Comment by oprotyniak** [comment]
I might have used a confusing image for you, because there is some data highlighted with DevTool. The point was that the title has 2 rows, althought with such test data 4 rows should have been shown.
![image](https://user-images.githubusercontent.com/73852063/103489851-1ef19180-4e20-11eb-9af2-9ce015aa99cf.png)

**Comment by IrynaShlyakhetko** [comment]
defect is  fixed partly
Not fixed is the next disparity:
1. size of tittle is 612*52 (Chrome), 612*78 (Mozila) (See attachments) - expected result is 613*53 

2. Title is displayed and consists of 4 rows and has 104px in height In Mozilla, and "eco news date text"  is placed out of the frame. (see attachment)
<img width="757" alt="Screen Shot 2021-01-22 at 16 04 15" src="https://user-images.githubusercontent.com/77668307/105505244-648fd480-5cd1-11eb-8a9a-b111dbf6605b.png">
<img width="746" alt="Screen Shot 2021-01-22 at 16 03 51" src="https://user-images.githubusercontent.com/77668307/105505272-6e193c80-5cd1-11eb-8482-6e904016189e.png">
<img width="431" alt="Screen Shot 2021-01-22 at 16 16 48" src="https://user-images.githubusercontent.com/77668307/105505293-770a0e00-5cd1-11eb-8314-218a65c734a7.png">
<img width="713" alt="Screen Shot 2021-01-22 at 16 28 51" src="https://user-images.githubusercontent.com/77668307/105505323-7f624900-5cd1-11eb-9690-a3d345812f6d.png">

**Comment by TetianaD** [comment]
**Actual result:**
Title is displayed and consists of 4 rows and is 104px in height.
![photo_2021-04-28_15-57-19](https://user-images.githubusercontent.com/10379945/116407472-7934b900-a83a-11eb-9b42-fb911f5d3154.jpg)

**Expected result:**
Expected result:
Title is displayed and consists of 4 rows and is 128px in height.
<img width="735" alt="Screenshot 2021-04-28 at 15 31 36" src="https://user-images.githubusercontent.com/10379945/116407617-9d909580-a83a-11eb-930c-f054f91d9cd0.png">

User story #460

**Comment by TetianaD** [comment]
Fixed in accordance with the new mockup design.
