### ISSUE TITLE
[Display News, List View] Incorrect display of the text of Title with 2 rows and Description with 2 row

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1892]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit);
Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
Reproducible: always
Build found: 20.11.2020

Preconditions

1. https://ita-social-projects.github.io/GreenCityClient/ is opened.
2. News items are created in the DB and are displayed as first news item in the list view. Use queries:
INSERT INTO eco_news
(ID, title, text, author_id, creation_date)
VALUES (722, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod ti ',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure d',
857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (722, 1), (722, 3);

Steps to reproduce

1. Click on 'Eco news' link in the header. 
2. Set browser window width to 1440px.
3. Click on the View as a List option on the right side of the page.
4. Pay attention to created news' Title and Description display.

Actual result
Title is displayed and consist of 2 rows and is 51px in heights.
![title 2 row](https://user-images.githubusercontent.com/65060199/99742842-0b42d380-2add-11eb-9764-f4f31187826e.jpg)
Description is displayed and consist of 2 rows and is 46px in heights.
![description 2 row](https://user-images.githubusercontent.com/65060199/99742854-11d14b00-2add-11eb-852b-1622131d3cf6.jpg)

Expected result
Title is displayed and consist of 2 rows and is 64px in heights.
Description is displayed and consist of 2 rows and is 64px in heights.

Postconditions
1. Created news are deleted from DB using queries:
DELETE FROM eco_news_tags
WHERE eco_news_id = 722;
DELETE FROM eco_news
WHERE id = 722;

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-722)

**Comment by JimHolman1199** [comment]
it does not match the design
