### ISSUE TITLE
[Display news, Gallery view] Incorrect display of text in the news card.

### ISSUE THREAD

**Issue by natalinapr** [ita-social-projects/GreenCity#1898]
**Environment:**  OS: Windows 10 Pro, Version 2004
Browser: Mozilla Firefox, Version: 82.0.3
**Reproducible:** always
**Build found:** commit 21.11.2020

**Preconditions**
Create an item in the database using SQL query:
INSERT INTO eco_news
 (ID, title, text, source, image_path, author_id, creation_date)
 VALUES (340, 'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
 'https://google.com/WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
 'https://storage.cloud.google.com/staging.greencity-c5a3a.appspot.com/f76c91cf-830c-465f-a080-ebb02b1f4f13', 
 857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">'),
 (341, 'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
 'https://google.com/WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
 'https://storage.cloud.google.com/staging.greencity-c5a3a.appspot.com/f76c91cf-830c-465f-a080-ebb02b1f4f13',
 857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
 (eco_news_id, tags_id)
 VALUES (340, 4), (340, 3), (340, 2), (341, 4), (341, 3), (341, 2);

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Eco news' link in the header.
3. Pay attention to the first eco news item in the Gallery

**Actual result**
Text in the news card is displayed incorrectly.
![1440 679 3](https://user-images.githubusercontent.com/62031226/99876613-89e46180-2c00-11eb-95d8-36d79a4a2f88.png)

**Expected result**
Text in the news card is displayed =according to mockup.
![image](https://user-images.githubusercontent.com/62031226/99876737-4807eb00-2c01-11eb-93b9-9099f61552ae.png)

**Postconditions**
Delete created item from database using SQL query:

DELETE FROM eco_news_tags
 WHERE eco_news_id IN (340, 341);

DELETE FROM eco_news
 WHERE id IN (340, 341);

**User story and test case links**
User story #971
[Verify that created news with max parameters are displayed correctly in different views and resolutions](https://jira.softserve.academy/browse/GC-679)

**Comment by JimHolman1199** [comment]
BE part.. issue with storing images
