### ISSUE TITLE
[Display news: List view] Incorrect size and alignment of UI elements of news item on 'List view' page (1024 resolution Chrome)

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1903]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Reproducible: always
Build found: 2020-11-21

Preconditions

1. Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. User should be authorized
3. There should be at least one news created by current user

Steps to reproduce
1. Click on the 'Eco news' button
2. Click on the 'List view' icon
3. Verify UI elements' size and alignments of the news item on 1199-992 resolution (ex. 1024 as we have mock - up with resolution 1024)with dev tool help.
4. Pay attention to the result.

Actual result
The size of the image is 299x166
![image 1024](https://user-images.githubusercontent.com/65060199/99880089-edc75400-2c19-11eb-87ec-c4d9ac919d22.jpg)

The size of the 'News' label is 40x14
![news 1024](https://user-images.githubusercontent.com/65060199/99880147-50205480-2c1a-11eb-8fac-9e1049047929.jpg)

The height of the 'Date' label is 24
![date 1024](https://user-images.githubusercontent.com/65060199/99880250-ff5d2b80-2c1a-11eb-8b8a-fdabd90aa450.jpg)

The height of the 'Author' label is 24
author
![author 1024](https://user-images.githubusercontent.com/65060199/99880433-eef98080-2c1b-11eb-96d2-f40287155edb.jpg)

The size of the 'Title' label is 322x26
title
![title 1024](https://user-images.githubusercontent.com/65060199/99880438-f751bb80-2c1b-11eb-8df4-16bb35cdfde4.jpg)

Incorrect alignment of the news item
![alignment 1024](https://user-images.githubusercontent.com/65060199/99880525-8363e300-2c1c-11eb-8020-2de0cd804c4b.PNG)

Expected result
The size of the image is 299x171
![image mock](https://user-images.githubusercontent.com/65060199/99880958-6da3ed00-2c1f-11eb-8ab0-53553520d915.jpg)

The size of the 'News' label is 42x16
![news label mock](https://user-images.githubusercontent.com/65060199/99880950-595ff000-2c1f-11eb-9e5a-1e86e9ee965c.jpg)

The height of the 'Date' label is 21
![data size mock](https://user-images.githubusercontent.com/65060199/99880839-8d86e100-2c1e-11eb-9b73-9176e6fbdd72.jpg)

The height of the 'Author' label is 21
![author mock](https://user-images.githubusercontent.com/65060199/99880847-98417600-2c1e-11eb-9f1a-65d57eedd522.jpg)

The size of the 'Title' label is 613x53
![title mock](https://user-images.githubusercontent.com/65060199/99880851-9ecfed80-2c1e-11eb-85b0-6cc57ea4db9b.jpg)

Correct alignment of the news item
![alignment 1024](https://user-images.githubusercontent.com/65060199/99880906-f8381c80-2c1e-11eb-9c3f-189522aac3b7.jpg)

User story and test case links
E.g.: "User story #460
Test case"

**Comment by OleksiiDziubenko** [comment]
Environment:
Windows 10 Pro, Version 20H2, Build 19042.746
Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
Reproducible: Always
Build found: 2021-01-21

Some UI elements are not sized correctly:
1. The height of the background is 167 (expected result: 166)
![Untitled-01](https://user-images.githubusercontent.com/77582518/105381620-df94b480-5c17-11eb-8748-b8d547b034cf.png)

2. The size of the image is 300x167 (expected result: 299x166)
![Untitled-02](https://user-images.githubusercontent.com/77582518/105381632-e3283b80-5c17-11eb-92f5-53eac532651a.png)

3. The size of the 'News' label is 43x19 (expected result: 42x16)
![Untitled-03](https://user-images.githubusercontent.com/77582518/105381639-e58a9580-5c17-11eb-8f4c-465eeddcbe34.png)

4. The height of the 'Date' label is 20 (expected result: 21px)
![Untitled-04](https://user-images.githubusercontent.com/77582518/105381651-e7ecef80-5c17-11eb-89c5-29af6fc6c4dc.png)

5. The height of the 'Author' label is 20 (expected result: 21px)
![Untitled-05](https://user-images.githubusercontent.com/77582518/105381656-eae7e000-5c17-11eb-9fa5-8d7e8741df6b.png)

6. The size of the 'Title' label is 612x63 (expected result: 613x53)
![Untitled-06](https://user-images.githubusercontent.com/77582518/105381673-ed4a3a00-5c17-11eb-86c7-4e36606ca7dc.png)

7. The row gap between 'Title' and 'Date & Author' labels is 8 (expected result: 16)
![Untitled-07](https://user-images.githubusercontent.com/77582518/105381681-f0452a80-5c17-11eb-908a-07e43aa42ae8.png)

**Comment by AlekOK** [comment]
This task is equel that https://github.com/ita-social-projects/GreenCity/issues/1879 and it was fixed.

**Comment by SerhiiStarshoi** [comment]
Environment: Safari 14.1, macOS Big Sur 11.3
Reproducible: always
Build found: 08.06.2021

Some UI elements are not sized correctly:

1. The size of the image is 299х204 (expected result: 359х204)
Actual Result
![photo_2021-06-08 17 07 59](https://user-images.githubusercontent.com/32453285/121200135-2cea8900-c87c-11eb-87a4-6b2ca724793f.jpeg)
Expected Result
![photo_2021-06-08 17 08 05](https://user-images.githubusercontent.com/32453285/121200165-33790080-c87c-11eb-8a1b-e859b8fb7778.jpeg)

2. The size of the 'News' label is 31.8x16 (expected result: 35x16)

Actual Result
![photo_2021-06-08 17 10 03](https://user-images.githubusercontent.com/32453285/121200451-6b804380-c87c-11eb-9f8b-d9752e0a0aec.jpeg)
Expected Result
![photo_2021-06-08 17 10 08](https://user-images.githubusercontent.com/32453285/121200487-74711500-c87c-11eb-80c2-02c477b52b0c.jpeg)

**Comment by MyroslavaVynokur** [comment]
Size and alignment of UI elements meet requirements in figma:
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12671%3A6400

Please focus on the expected results in figma
Verified - move to done
