### ISSUE TITLE
[Display News, List View] Title and Content text are higher than 136px.

### ISSUE THREAD

**Issue by oprotyniak** [ita-social-projects/GreenCity#1906]
**Environment:** Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
**Reproducible:** always
**Build found:** 22.11.2020

**Preconditions**
1. https://ita-social-projects.github.io/GreenCityClient/ is opened.
2. News items are created in the DB and are displayed as first news item in the list view. Use queries:
INSERT INTO eco_news
(ID, title, text, source, image_path, author_id, creation_date)
VALUES (703, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim ven',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure d',
'https://google.com/Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim ven',
'https://storage.cloud.google.com/staging.greencity-c5a3a.appspot.com/7a68b28d-224a-42f7-94c7-55b1fa59297e',
857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');
INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (703, 4), (703, 3), (703, 2);

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Eco news' link in the header.
3. Click on the View as a List option on the right side of the page.
4. Set browser window width to 1440px and measure height of title and content text fields.
5. Set browser window width to 1024px and measure height of title and content text fields.
6. Set browser window width to 768px and measure height of title and content text fields.
7. Set browser window width to 576px and measure height of title and content text fields.

**Actual result**
The title and content text field are higher than 136px
![1440](https://user-images.githubusercontent.com/73852063/99908213-fd15d280-2ce9-11eb-9088-4d8eb30b9b74.JPG)
![1024](https://user-images.githubusercontent.com/73852063/99908215-01da8680-2cea-11eb-87d6-959f4faa5130.JPG)
![768](https://user-images.githubusercontent.com/73852063/99908234-220a4580-2cea-11eb-8b16-812b2601b51a.JPG)
![576](https://user-images.githubusercontent.com/73852063/99908242-26cef980-2cea-11eb-9272-bc3ff284532e.JPG)

**Expected result**
The title and content text field are not higher than 136px as is shown on mockup
![Card Guideline List view](https://user-images.githubusercontent.com/73852063/99907942-4e24c700-2ce8-11eb-9191-547c970379dc.jpg)

**Postconditions**
Delete created item from database using SQL query:
DELETE FROM eco_news_tags
WHERE eco_news_id = 703;

DELETE FROM eco_news
WHERE id = 703;

**User story and test case links**
User story #460
[Test case](https://jira.softserve.academy/browse/GC-703)"

**Comment by ProstoLeleka** [comment]
If I understand correctly - 4 rows (Title and Content) + 8px (space between them) = 136px (4*32+8). There aren't enough space for Author and Data, so height is higher than 136px. Might be design mistake or misunderstanding.

**Comment by oprotyniak** [comment]
Mockup should be updated. 96px includes only content text field, without 'Author and date' row. With such condition test has passed.
