### ISSUE TITLE
[News display: list view] The 'Greencity' application url can not be opened in Internet Explorer 

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1911]
Environment: 
Microsoft Windows 10 Home, Version 10.0.19041
Internet Explorer Version 11.630.19041.0 
Reproducible: always
Build found: 2020-11-22

Preconditions
Internet Explorer browser should be opened

Steps to reproduce
1. Go to https://ita-social-projects.github.io/GreenCityClient/ 
2. Pay attention to the result

Actual result
The site is not displayed
![explorer](https://user-images.githubusercontent.com/65060199/99919520-a5e22300-2d26-11eb-9069-64946458b11e.jpg)

Expected result
The site is displayed

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-703), (https://jira.softserve.academy/browse/GC-704)
(https://jira.softserve.academy/browse/GC-706)
(https://jira.softserve.academy/browse/GC-707)
(https://jira.softserve.academy/browse/GC-708)
(https://jira.softserve.academy/browse/GC-710)
(https://jira.softserve.academy/browse/GC-720)
(https://jira.softserve.academy/browse/GC-722)
(https://jira.softserve.academy/browse/GC-723)
(https://jira.softserve.academy/browse/GC-724)
(https://jira.softserve.academy/browse/GC-725)
(https://jira.softserve.academy/browse/GC-332)
(https://jira.softserve.academy/browse/GC-352)

**Comment by JimHolman1199** [comment]
we are not supporting IE
