### ISSUE TITLE
[Display News, List View] The display of order and labels of tabs do not coincide with the mock-up

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1912]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit);
 Mozilla Firefox 82.0.3 (64-біт)
Reproducible: always
Build found: 2020-11-22

Preconditions
1.https://ita-social-projects.github.io/GreenCityClient/ is opened.

Steps to reproduce
1. Click on 'Eco news' link in the header.
2. Pay attention to the tabs order and labels display

Actual result
The display order and labels of tabs do not coincide with the mock-up, there is extra tab 'Lifehacks', tab 'Education' instead of tab 'Courses'
![tabs](https://user-images.githubusercontent.com/65060199/99919881-c3b08780-2d28-11eb-8379-e28f9fcbe6a2.jpg)

Expected result
The display order and labels of tabs coincide with the mock-up, there is no extra tab 'Lifehacks'
![tabs mock](https://user-images.githubusercontent.com/65060199/99919986-62d57f00-2d29-11eb-83fb-a394352cc99b.jpg)

User story and test case links
E.g.: "User story #460
[Test case](https://jira.softserve.academy/browse/GC-720)

****

**Comment by JimHolman1199** [comment]
Lifehacks - deleted
also the order does not matter because it is test data and they can change

**Comment by IrynaShlyakhetko** [comment]
Defect is not fixed
Actual Result:
1. Buttons near "Filter by" field is posted in incorrect order
2. Button "Education" is extra
3. There is not button "Courses" near "Filter by" field
<img width="715" alt="Screen Shot 2021-01-22 at 13 34 53" src="https://user-images.githubusercontent.com/77668307/105493119-a0bb3900-5cc1-11eb-8e0d-74cd5fc13387.png">

**Comment by VitalyBorysenko** [comment]
The filters list comes from BE. FrontEnd only displaying it. And I think it can dynamically be changed by App Admin. So it no matters the order of locations.

**Comment by OksanaKukalets** [comment]
The actual result:
Tabs after the 'FIlter by' label are not located in the order corresponding to the mockup. There is a tab 'Education' rather than 'Courses'.
![2021-04-02_09h01_17](https://user-images.githubusercontent.com/80641785/113386154-4a8a0680-9392-11eb-8f3a-25ac977e49fd.png)

**Comment by ViktoriyaRyazhska** [comment]
It's not a bug
Filters are depended from data in DB
