### ISSUE TITLE
[Display news: List view] Incorrect size and alignment of UI elements  on 'List view' page (1440 resolution)

### ISSUE THREAD

**Issue by tatiana404** [ita-social-projects/GreenCity#1915]
Environment:
Microsoft Windows 10 Home, Version 10.0.19041
Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Reproducible: always
Build found: 2020-11-21

Preconditions

1. Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome

Steps to reproduce
1. Click on the 'Eco news' button
2. Click on the 'List view' icon
3. Verify UI elements size and alignments of the news item on 1440  resolution with dev tool help.
4. Pay attention to the result.

Actual result
The size of the 'Greencity' logo is 136x36
![greencity 1440](https://user-images.githubusercontent.com/65060199/100013783-1304bf80-2dde-11eb-8b1f-c15f08956659.jpg)

The size of the 'Search' control is 16x16
![search button 1440](https://user-images.githubusercontent.com/65060199/100014140-a76f2200-2dde-11eb-94f1-ca873be7efdf.jpg)

The seize of the 'language' dropdown list is 16x44
![lang 1440](https://user-images.githubusercontent.com/65060199/100014645-56136280-2ddf-11eb-80dc-73cbf14d7218.jpg)

The heights of the user name field is 16px 
![name 1440](https://user-images.githubusercontent.com/65060199/100014865-b2768200-2ddf-11eb-8acb-8df41e2e85e4.jpg)

The size of the 'Create news' button is 185x40
![create news button1440](https://user-images.githubusercontent.com/65060199/100015181-37619b80-2de0-11eb-9e51-65ea97b6fdb4.jpg)

The size of the 'Create news' button label is 99x16
![create news button's label 1440](https://user-images.githubusercontent.com/65060199/100015314-7394fc00-2de0-11eb-84c6-f02898e98c36.jpg)

The size of the 'Eco news' title is 227x30
![eco news title1440](https://user-images.githubusercontent.com/65060199/100015587-e69e7280-2de0-11eb-8bde-190283370c9d.jpg)

The size of the 'Filter by' label is 97x42
![filter by 1440](https://user-images.githubusercontent.com/65060199/100015811-2feec200-2de1-11eb-8fe2-0ebea2654642.jpg)

The size of the 'Greencity' logo in the footer is 206x48
![greencity footer 1440](https://user-images.githubusercontent.com/65060199/100016071-8bb94b00-2de1-11eb-9413-7e4111a9cfbe.jpg)

The size of the 'Copyright' label in the footer is 1440x16
![copyright 1440](https://user-images.githubusercontent.com/65060199/100016299-ddfa6c00-2de1-11eb-8608-33e285e4089f.jpg)

The size of the 'Follow us' link in the footer is 61x16
![follow us 1440](https://user-images.githubusercontent.com/65060199/100016640-67aa3980-2de2-11eb-8322-41b8c4a1f979.jpg)

Expected result

The size of the 'Greencity' logo is divided into two parts  36x36, 94x12
![greencity  mock 1440](https://user-images.githubusercontent.com/65060199/100013829-27e15300-2dde-11eb-939d-3e960972c1a5.jpg)
![greencity mock1 1400](https://user-images.githubusercontent.com/65060199/100013885-3af42300-2dde-11eb-967d-a18a5ea19365.jpg)

The size of the 'Search' control is 11x11
![search control mock 1440](https://user-images.githubusercontent.com/65060199/100014197-b9e95b80-2dde-11eb-96a5-a768ad5619d3.jpg)

The seize of the language dropdown list is 17x19
![lang mock 1440](https://user-images.githubusercontent.com/65060199/100014747-81964d00-2ddf-11eb-8efb-e372c89c59eb.jpg)

The heights of the user name field is 12px 
![name mock 1440](https://user-images.githubusercontent.com/65060199/100014934-cf12ba00-2ddf-11eb-81c5-87b43459dd6c.jpg)

The size of the 'Create news' button is 183x40
![button create news mock 1440](https://user-images.githubusercontent.com/65060199/100015256-5a8c4b00-2de0-11eb-848a-fbcc648f6ff5.jpg)

The size of the 'Create news' button label is 96x16
![create news label mock 1440](https://user-images.githubusercontent.com/65060199/100015426-9f17e680-2de0-11eb-88dd-24c5979059b2.jpg)

The size of the 'Eco news' title is 256x48
![eco news title mock](https://user-images.githubusercontent.com/65060199/100015654-fe75f680-2de0-11eb-91ad-acd3f303341f.jpg)

The size of the 'Filter by' label is 99x24
![filter by mock 1440](https://user-images.githubusercontent.com/65060199/100015874-49900980-2de1-11eb-952e-0332217e0652.jpg)

The size of the 'Greencity' logo is divided into two parts  48x48, 141x18
![greencity footer1 1440](https://user-images.githubusercontent.com/65060199/100016184-b2778180-2de1-11eb-99fd-ae7acccbd5c4.jpg)
![greencity footer mock 1440](https://user-images.githubusercontent.com/65060199/100016220-bb685300-2de1-11eb-8a63-91d55fbafa65.jpg)

The size of the 'Copyright' label in the footer is 194x16
![copyright mock 1440](https://user-images.githubusercontent.com/65060199/100016430-139f5500-2de2-11eb-8ed9-084ec2979062.jpg)

The size of the 'Follow us' link in the footer is 62x19
![follow us mock 1440](https://user-images.githubusercontent.com/65060199/100016551-45182080-2de2-11eb-8725-58f2c29d8ef6.jpg)

User story and test case links
E.g.: "User story #460
Test case https://jira.softserve.academy/browse/GC-720

**Comment by JimHolman1199** [comment]
please check this again, and divide the test cases into different areas (header, footer, eco-news) because it is impossible to work with it

**Comment by IrynaShlyakhetko** [comment]
Defect is not fixed 
Is fixed only size of the 'Create news' button (see attachment with result)
<img width="366" alt="Screen Shot 2021-01-22 at 15 07 24" src="https://user-images.githubusercontent.com/77668307/105495641-15dc3d80-5cc5-11eb-9d61-3cdcef12f066.png">
