### ISSUE TITLE
[API] [Reply] Logged user does not see the replies to the comment on the Eco News page.

### ISSUE THREAD

**Issue by natalinapr** [ita-social-projects/GreenCity#1937]
**Environment:** OS Windows 10 Pro, Version 2004
DataGrip, Swagger
**Reproducible:** always
**Build found:** 27/11/2020
**Preconditions**
1. Open Swagger: https://greencity.azurewebsites.net/swagger-ui.html#/ ;
2. Sign in with controller Post /ownSecurity/signIn (e.g. green.city.test2@gmail.com, Green.city#500);
3. Use token to authorize in Swagger;
4. Get any parent_comment_id which have a comments in DataBase using query:
select * from econews_comment where parent_comment_id is not null;
(e.g. 224)

**Steps to reproduce**
1. Open eco-news-comment-controller
2. Click on controller /econews/comments/count/replies 'Get count of replies to comment.'
3. Click on "Try it out" button
4. Set parameters parentCommentId (e.g. 344)
5. Click on 'Execute' button.
6. Count parent_comment_id in DataBase using query:
select count(parent_comment_id) from econews_comment where parent_comment_id = 224;
7. Pay attention to responses in Database and Swagger

**Actual result**
1. The Database response is 6.
The Swagger response is 4.
2. The replies to the comment are not displayed.

![image](https://user-images.githubusercontent.com/62031226/100396819-4a2dd780-304f-11eb-8b9b-533076b078a5.png)

![image](https://user-images.githubusercontent.com/62031226/100396840-69c50000-304f-11eb-82d0-0ed131448a1a.png)

**Expected result**
The Database response is 6. The Swagger response is 6.

**User story and test case links**
User story #843
[[API][Reply] Verify that logged user can see the replies to the comment on the Eco News page.](https://jira.softserve.academy/browse/GC-1195)

**Comment by forestik** [comment]
In the swagger parent_comment_id is 344, but for search in databese you used 224 for parent_comment_id.
