### ISSUE TITLE
[API] Unlogged user cannot review comments on the News page

### ISSUE THREAD

**Issue by bohdana1** [ita-social-projects/GreenCity#1940]
Environment: Microsoft Windows 7 Home
Chrome Browser Версія 86.0.4240.198 (Розробка) (32-розрядна версія)
Reproducible: always.
Build found: 27.11.2020

Preconditions
User is not logged.

Steps to reproduce
1. Go to 'https://greencity.azurewebsites.net/swagger-ui.html#/eco-news-comment-controller'
2. Click on ''GET/econews/comments controller'
3. Set valid data to: ecoNewsId (e.g. 6029) field,page (e.g. 1) field, size(e.g. 5) field
4. Click on the 'Execute' button

Actual result
Response code 401. 
{
  "timestamp": "2020-11-27T10:40:11.062+0000",
  "status": 401,
  "error": "Unauthorized",
  "message": "Authorize first.",
  "path": "/econews/comments"
}

Expected result
Response code 200
{
"currentPage": 0,
"page": [
{
"author":

{ "id": 0, "name": "string", "userProfilePicturePath": "string" }

User story and test case links
E.g.: "User story #763
[Test case](https://jira.softserve.academy/browse/GC-1192)"

Labels to be added
"Bug", Priority ("medium"), Severity ("major"), Type ("Functional"), "API" (for back-end bugs).
![get comment](https://user-images.githubusercontent.com/73852733/100441012-6f056780-30ae-11eb-86bb-2ac8604cd539.png)

**Comment by forestik** [comment]
/econews/comments/ this method used only admin

**Comment by forestik** [comment]
/econews/comments/active This method used all users

**Comment by bohdana1** [comment]
This method should be used for all users)

пт, 27 лист. 2020 о 13:56 forestik <notifications@github.com> пише:
