### ISSUE TITLE
[Restore password] Can't restore password with valid registered email.

### ISSUE THREAD

**Issue by ProstoLeleka** [ita-social-projects/GreenCity#1975]
Environment: Windows 7, Google Chrome 86.0.4240.111
Reproducible: always
Build found: 13e140a

Steps to reproduce

Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
Click on 'Sign in'
Click on 'Forgot password'
Set valid registered e-mail (e.g: "lelekatestacc@gmail.com")
Click on 'Submit a login link' button

Actual result
Text alert: "must be a well-formed email address".
![Screenshot_9](https://user-images.githubusercontent.com/34520370/101082119-a2b32680-35b3-11eb-9d1c-04b8c94740f0.png)

Expected result
Email to restore password was sent to entered email,

User story #472

**Comment by oprotyniak** [comment]
duplicate of https://github.com/ita-social-projects/GreenCity/issues/1966
