### ISSUE TITLE
BUG (#_) [ADMIN] No error message when enter an invalid data 'id' in /user/role Update role of user

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#199]
**Steps to reproduce:**

1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#...
2. Choose User Controller
3. Choose PATCH /user/role Update role of user
4. Click 'Try it out' button
5. Enter invalid data 'id' and valid data "role" (e.g. { "id": t&C, "role": "ROLE_USER""})
6. Click 'Execute' button

**Actual result:**
There is '400 Error'
**Expected result:**
There is ' 400 Error "message": "You enter invalid data. The 'id' contains only numeric data"

**Comment by Bogdan-Kuzenko** [comment]
Right now it is not possible to create a custom message for each field (like "id" etc...). We've added a full error message from HttpMessageNotReadable Exception
