### ISSUE TITLE
[Change request] View, edit and save additional details for a habit

### ISSUE THREAD

**Issue by Oksana-Voitovych** [ita-social-projects/GreenCity#1991]
**As a** registered user **I want to** be able to view, edit and save additional details for a habit from a list of standard habits, **so that** I was able to modify a habit according to my needs if needed.

**Acceptance Criteria:**
To add:
5. When the habit is added, the counters of habits in progress on My Habits page increase by 1. 

Related to user story #1785
Epic: My habits #938

**Comment by atsa21** [comment]
Done
