### ISSUE TITLE
[Econews, comment] Confirmation is not displayed after clicking on 'Delete' comment button

### ISSUE THREAD

**Issue by chelkis** [ita-social-projects/GreenCity#1999]
**Environment:**  
1) Windows 8.1     Microsoft Edge v. 87.0.664.55
2) Windows 10 Pro version 2004 (OS Build 19041.630), Firefox 83.0 (x64)
3) MacOS Catalina 10.15.7 (19H2), Safari 14.0 (15610.1.28.1.9, 15610)
4) macOS Catalina 10.15.6, Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)

**Reproducible:** always.
**Build found:** 08.12.2020

**Preconditions**
1. https://ita-social-projects.github.io/GreenCityClient/#/welcome is opened.
2. Log into GreenCity (e.g. 'Email'="green.city.test2@gmail.com", 'Password'="Green.city#500")
3. Click on 'Eco news' link in the Header.
4. Click on Single News.

**Steps to reproduce**
1. Go down to the end of page.
2. Add a comment on the window and click on 'Comment' button (e.g. "Thank you for interesting news.")
3. Click on your comment and click on 'delete' button

**Actual result**
Confirmation is not displayed after clicking on 'delete' button when user want to delete his comment
**Expected result**
The system should display confirmation: " Are you sure you want to delete the comment? And give option 'Yes' or 'No' "

**User story and test case links**
User story [#846](https://github.com/ita-social-projects/GreenCity/issues/846)
[Test case](https://jira.softserve.academy/browse/GC-794)

**Attachment**
[Video_attachment](https://www.loom.com/share/3b2522f461e144cfa83548c13b883bb6)

**Comment by JimHolman1199** [comment]
seems to be working now, please check it again!

**Comment by JimHolman1199** [comment]
Uploading Screen Recording 2021-01-03 at 00.45.59.mov…
