### ISSUE TITLE
Access application with a map and sidebar list

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#20]
As an unregistered user I want to access the application, so that I can see a map with places on the right side and a list with places on the left side of the window.

Mockups:
![image](https://user-images.githubusercontent.com/53810790/62903445-56fbbe80-bd6b-11e9-8b4f-bdec9a83e337.png)

Acceptance Criteria:
1. WHEN Unregistered user access the site, THEN system should navigate him/her to the main page of website with:
a. Map zoomed out to area of Lviv
b. List of places (Names)

2. Test places are on the map

3. System allows to zoom in/out a map.

4. Sidebar list of cafes include names of test cafes and their address.

5. List of places should be sorted by name.

6. Test cafes, which are in the list of sidebar should be visible on the map in parallel.

TBD:
- Research best map to integrate with a website??

**Comment by yartymys** [comment]
As an unregistered user I want to access the application, so that I can see a map with cafes (TBD including maps integration) 

Mockups:
 
Acceptance Criteria:
1.	
 




Assumptions and Constraints:
 
TBD:

**Comment by rsyvulko** [comment]
Not relevant.
