### ISSUE TITLE
[Eco news, comment] comment container is wider than specified on the mockup for 1440p resolution.

### ISSUE THREAD

**Issue by tkoretska47** [ita-social-projects/GreenCity#2004]
**Environment:** Windows 10 Pro version 2004 (OS Build 19041.630), Firefox 83.0 (x64)
**Reproducible:** always
**Build found:** 08.12.2020

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome and sign in with valid data. 
2. Click on the 'Eco News' link on the header of the page. There are at least two comments on "Eco news" Single page.
3. There should be at least one comment by currently logged in user. If there's no one - leave a comment with any content.

**Steps to reproduce**
1. Change the screen resolution to 1440p.
2. Scroll down to any comment left by currently logged in user.
3. Check the comment container width.

**Actual result**
The width is 806.4px
![container_width1](https://user-images.githubusercontent.com/75268511/101548638-dc6d9e00-39b4-11eb-9ae1-df2e06c85e0d.png)

**Expected result**
The width is 750px as it is on the [mockup](https://www.figma.com/file/K5qc43VjSkWVz8mobuovxs/ITA-Greencity?node-id=5323%3A3288).
![container_width_mockup](https://user-images.githubusercontent.com/75268511/101548665-edb6aa80-39b4-11eb-974f-d02ae6a47f2e.png)

**User story and test case links**
User story #763
[Test case](https://jira.softserve.academy/browse/GC-868)

**Comment by yuriiLisunov** [comment]
**To be disscussed;**
need to review the mokup for an error

**Comment by AlekOK** [comment]
Hi! This isn't a bug, because the width of the container is the sum of the avatar image and other details. If you subtract 800 - 50 (img) we get the desired 750.

**Comment by Nazik94** [comment]
Actual result:
The width is 798px
![image](https://user-images.githubusercontent.com/33220864/116418575-f533fe80-a844-11eb-97fa-efa3bcc39342.png)
Expected result:
The width is 750 px
![image](https://user-images.githubusercontent.com/33220864/116420129-5f996e80-a846-11eb-9005-55dc598ba6e3.png)

**Comment by DarynaPashkevych** [comment]
Actual result: 
The width is 798px
![image](https://user-images.githubusercontent.com/46245318/121655615-69e69380-caa7-11eb-9e38-335e278d816d.png)

Expected result:
The width is 750 px
![image](https://user-images.githubusercontent.com/46245318/121655713-7c60cd00-caa7-11eb-9e1c-7adf156f2413.png)

User story #763

**Comment by Ol98** [comment]
Actual result: 
The width is 752.4
![image](https://user-images.githubusercontent.com/91474733/135080812-c9203d5a-240b-4dad-887d-62c3eeda674f.png)

Expected result:
The width is 750 px
![image](https://user-images.githubusercontent.com/91474733/135080882-18acaf93-bb11-4a90-a532-9123ed8e3e4f.png)

**Comment by Ol98** [comment]
Done!
