### ISSUE TITLE
[Change request] 'Hide replies' button to collapse replies

### ISSUE THREAD

**Issue by vandrusenko** [ita-social-projects/GreenCity#2009]
As a registered user, I want to be able to collapse expanded replies by clicking 'Hide replies' button. 

**Acceptance Criteria:**
To hide the replies to the comment user should click on the link 'Hide replies'.

![View_reply_Hide_reply](https://user-images.githubusercontent.com/75262612/101655901-cd392f80-3a4a-11eb-86fb-7aa77d117b44.jpg)

**User story and test case links:**
Related to User Story #843
Epic: Comment #937
JIRA [Test case](https://jira.softserve.academy/browse/GC-971)

**Comment by kbqe** [comment]
Looks like a reasonable improvement.
