### ISSUE TITLE
[Comments/Replies] When posting reply, it does not show up under the comment

### ISSUE THREAD

**Issue by vandrusenko** [ita-social-projects/GreenCity#2013]
**Environment:** macOS Catalina 10.15.7 (19H2), Safari 14.0 (15610.1.28.1.9, 15610)
**Reproducible:** always
**Build found:** 09.12.2020

**Preconditions**
1) Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2) Sign in as user with valid data (e.g. Email "koton86272@example.com", Password "Qw@rt111").
3) Go to 'Eco news' page.
4) Go to any news.
5) There is at least one comment on the news page.
 
**Steps to reproduce**
1. Сlick the Reply button under any comment.
2. Post any valid reply under a comment (e.g. "hallo").

**Actual result**
The reply is published and hidden under the 'View reply' button.
(See attachment)

**Expected result**
The reply should be published and displayed to user.

**Attachments**
![post_reply_1](https://user-images.githubusercontent.com/75262612/101680513-7db62c00-3a69-11eb-9fc6-bde618ecee0e.jpg)

![post_reply_2_AR](https://user-images.githubusercontent.com/75262612/101680520-7f7fef80-3a69-11eb-8dc8-53a749dac1e6.jpg)

**Comment by dmytro-kryvyi** [comment]
Already fixed #6875
