### ISSUE TITLE
 [Eco news, Reply] Confirmation is not displayed after clicking on 'Delete' reply button

### ISSUE THREAD

**Issue by chelkis** [ita-social-projects/GreenCity#2016]
**Environment:** 
1) Windows 8.1  Microsoft Edge v. 87.0.664.55
2) MacOS Catalina 10.15.7 (19H2), Safari 14.0 (15610.1.28.1.9, 15610)
3) macOS Catalina 10.15.6, Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)

**Reproducible:** always
**Build found:** 09.12.2020
**Preconditions**
1. https://ita-social-projects.github.io/GreenCityClient/#/welcome is opened.
2. Log into GreenCity (e.g. 'Email'="green.city.test2@gmail.com", 'Password'="Green.city#500")
3. Click on 'Eco news' link in the Header.
4. Click Single News

**Steps to reproduce**
1. Moved to the comments
2. Click on 'Reply' button and add a reply for a comment. (e.g. "Agree")
3. Click on 'View reply' button and delete your reply by clicking on 'delete' button

**Actual result**
The system does not display confirmation: ' Are you sure you want to delete the reply? And give option 'Yes' or 'No'

**Expected result**
The system should display confirmation: ' Are you sure you want to delete the reply? And give option 'Yes' or 'No'

**User story and test case links**
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/846
[Test case](https://jira.softserve.academy/browse/GC-822)"

**Comment by JimHolman1199** [comment]
seems to be working now, please check it out!

https://user-images.githubusercontent.com/46226026/103467981-47fd1e00-4d5d-11eb-958e-0371ccd79e7d.mov
