### ISSUE TITLE
[UI, Editing comment] 'Save' button is shown instead of 'Save changes' button during editing comment

### ISSUE THREAD

**Issue by NSkolozdra** [ita-social-projects/GreenCity#2018]
**Environment:**
macOS Catalina 10.15.6, Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
MacOS Catalina 10.15.7 (19H2), Safari 14.0.1 (15610.2.11.51.10, 15610)
Windows 10 Pro version 2004 (OS Build 19041.630), Firefox 83.0 (x64)
Windows 8.1, Microsoft Edge v. 87.0.664.55

**Reproducible:** always
**Build found:** 10/12/20

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in as user with valid data 
3. Go to 'Eco news' page.
4. Create at least one comment on the 'Eco News' page.

**Steps to reproduce**
1. Click 'Edit' link at the bottom of your created comment.
2. Edit text of the comment.

**Actual result**
‘Save’ button is displayed near the comment field.
(See screenshot)
![Screenshot 2020-12-10 at 10 44 17](https://user-images.githubusercontent.com/75263280/101748550-5dbc5200-3ad5-11eb-855a-c6c986c538f9.png)

**Expected result**
‘Save changes’ button should be displayed near the comment field (according to Acceptance criteria User story #845)
See mock-up
https://www.figma.com/file/K5qc43VjSkWVz8mobuovxs/ITA-Greencity?node-id=6947%3A9

**User story and test case links**
E.g.: "User story #845
[Test case](https://jira.softserve.academy/browse/GC-861)"

**Labels to be added**

**Comment by AleksandrMDC** [comment]
Button name is still incorrect.
‘Save’ instead 'Save changes'
[](url)
![Save_changes](https://user-images.githubusercontent.com/77486695/106917653-23f07c00-6711-11eb-962e-ff144435e2cb.png)
