### ISSUE TITLE
BUG (#_) [ADMIN] No error message when enter a negative numbers in fields in /user Get users by page

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#203]
**Steps to reproduce:**
1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#...
2. Choose User Controller
3. Choose GET /user Get users by page
4. Click 'Try it out' button
5. Enter negative numbers in 'page' and negative numbers in 'size' field (e.g. 'page': -1, 'size': -5)
6. Click 'Execute' button

**Actual result:**
There isn't error message

**Expected result:**
There is ' 400 Error "message": "You enter invalid data. The 'page', 'size' contain only numeric data"

**Comment by RostyslavKhasanov** [comment]
Mappting GET /user getAllUsers in User Controller was removed.

**Comment by yuriikoval1997** [comment]
This is the default Spring behaviour. When entered invalid page index (less than 0) or size (less than 1), Spring uses its default Pageable object with page equals to 0 and size equals to 20.
