### ISSUE TITLE
BUG (#_) [ADMIN] Not all users are displayed in /user Get users by page

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#204]
`Description:`
`Steps to reproduce:`
1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#...
2. Choose User Controller
3. Choose GET /user Get users by page
4. Click 'Try it out' button
5. Click 'Execute' button
`Actual result:`
22 users (id) are displayed 
`Expected result:`
The number of users (id) displayed  is equal "totalElements"

**Comment by RostyslavKhasanov** [comment]
Mappting GET /user getAllUsers in User Controller was removed.
