### ISSUE TITLE
[Eco news, Comment] "Reply" button location doesn't meet the mockup for 576p screen resolution.

### ISSUE THREAD

**Issue by tkoretska47** [ita-social-projects/GreenCity#2040]
**Environment:** Windows 10 Pro version 2004 (OS Build 19041.630), Firefox 83.0 (x64)
Windows 8.1, Microsoft Edge v. 87.0.664.55
**Reproducible:** always
**Build found:** 15.12.2020

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome and sign in with valid data.
2. Click on the 'Eco News' link on the header of the page. There are at least two comments on "Eco news" Single page.
3. There should be at least one comment by currently logged in user. If there's no one - leave a comment with any content.

**Steps to reproduce**
1. Change the screen resolution to 576p.
2. Click on "Reply" link.
3. Look at "Reply" button location.

**Actual result**
"Reply" button is located on the right sight of "Add a reply" field.
![Untitled](https://user-images.githubusercontent.com/75268511/102210806-5634e880-3edb-11eb-86bb-d538486c4218.png)

**Expected result**
"Reply" button is located below the "Add a reply" field.
![Untitled](https://user-images.githubusercontent.com/75268511/102210920-7c5a8880-3edb-11eb-9f40-369d1f09bd9c.png)

**User story and test case links**
User story #765 
[Test case](https://jira.softserve.academy/browse/GC-1029)

**Comment by IrynaShlyakhetko** [comment]
defect is not fixed

**Comment by paslavskyi9roman** [comment]
![bug](https://user-images.githubusercontent.com/46484914/110013491-5bf7d880-7d2a-11eb-9092-0dbb29379c89.jpg)
On a 576px or less width screen, the Reply button is displaying as expected
