### ISSUE TITLE
BUG (#_) [ADMIN] Input and output data do not match in /user getAllUsers

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#205]
`Description:`
`Steps to reproduce:`
1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#...
2. Choose User Controller
3. Choose GET /user getAllUsers
4. Click 'Try it out' button
5. Enter valid data in 'pageNumber' field and valid data in 'pageSize' field (e.g. 'pageNumber': 4, 'pageSize': 20)
6. Click 'Execute' button
`Actual result:`
22 users (id) are displayed
`Expected result:`
The page and the number of users are the same as the data entered into 'pageNumber', 'pageSize' fields

**Comment by RostyslavKhasanov** [comment]
Mappting GET /user getAllUsers in User Controller was removed.
