### ISSUE TITLE
[Functional, Like a Comment] System doesn't recalculate total likes number in real time

### ISSUE THREAD

**Issue by NSkolozdra** [ita-social-projects/GreenCity#2072]
**Environment:** 
1) macOS Catalina 10.15.6
Google Chrome Version 87.0.4280.88 (Official Build) (x86_64) + Safari Version 13.1.2 (15609.3.5.1.3)
2) Windows 10 Pro version 2004 (OS Build 19041.630), Firefox 83.0 (x64) + Opera (v. 72.0.3815.400) 

**Reproducible:** always
**Build found:** 17/12/20

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome in one browser (e.g. Google Chrome)
2. Sign in with valid data as User.
3. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome in another browser (e.g. Safari)
4. Sign in with valid data as another User.
5. Open to browsers to observe actions in real time on both.

**Steps to reproduce**
1. Click on 'Eco News' tab in one browser. There is at least one News with comment.
2. Like not your comment.

**Actual result**
System doesn't recalculate total likes number in real time in another browser 
(See video: https://drive.google.com/file/d/1A3A4hv6kgzLq1qthtr2ZxjtSImggIF6I/view?usp=sharing)

**Expected result**
System should recalculate total likes number in real time on both browsers.

**User story and test case links**
User story #766 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional")

**Comment by irynamykhailevych** [comment]
The bug is still reproduce on environments:
Windows 10 x64 
Chrome 90.0.4430.212
Mozilla Firefox 88.0.1 (64-біт)

**Comment by SerhiiStarshoi** [comment]
The bug is still reproduce on environments:
macOS Big Sur 11.4
Chrome 91.0.4472.77
Safari 14.1.1 (16611.2.7.1.4)
