### ISSUE TITLE
Propose new cafe

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#21]
As a registered user I want to propose a new café to be added to the map/list, so that information about cafes is up-to-date and full. 

**Mockups:**

**Acceptance Criteria:**
1. GIVEN a registered user is successfully logged in to the system, WHEN he clicks on "Add place" button at top right corner of the screen, THEN system shall open a modal window with the following:
a. input field "Type"
b. input field "Name"
c. input field "Address"
d. input field "Working times"
e. Buttons "Add" and "Cancel"

2. Provided user clicks on field "Type", system shall open a drop-down with the following elements:
a. Cafe
b. Restaurant
c. Add new

3. Provided user selects "Add new" option in the Type field, system shall let him enter a new type of place.

3. Fields "Name" and "Address" shall be char + digit fields. User can input max number of 30 chars into each field.

4. Provided user clicks on "Working times" field, system shall open a pop-up, where user has to choose opening and closure times. There shall be buttons "OK" and "Cancel".

5. All fields are mandatory to be populated. Provided at least one field is not populated, then "Add" button shall be disabled.

6. Provided user clicks on "Add" button, system shall close the modal window, add the proposed place to the system and display it in the "Proposed places" tab of the Admin page.

7. Provided user clicks on "Cancel" button, system shall close the modal window and not save data entered in the fields (if any).

**Assumptions and Constraints:**

**TBD:**

**Comment by rsyvulko** [comment]
Not relevant.
