### ISSUE TITLE
BUG(#_) [ADMIN]: Input and output data do not match in 'place-controller / getPlacesByStatus '

### ISSUE THREAD

**Issue by AnatoliyKazymyrchuk** [ita-social-projects/GreenCity#210]
**Pre-conditions:**

- Go to https://greencitysoftserve.herokuapp.com
- Click own-security-controller
- Choose POST/ownSecurity/signIn
- Insert 'email': 'greencity.adm@gmail.com',
- 'password': 'greencityadm123' in 'json'
- Execute query
- Get a token
- Click 'Authorize'
- In 'Value' field insert 'Bearer token' and authorize.

**Steps to reproduce**
1. Click place-controller
2. Choose GET/place/{status}
3. Click 'Try it out' button
4. Enter valid data in 'pageNumber' field and valid data in 'pageSize' field (e.g. 'pageNumber': 1, 'pageSize': 5)
5. Enter valid data in 'status' field (e.g. "APPROVED")
6. Click 'Execute' button

**Actual Result**

- 9  place are displayed

**Expected Result**

- The page and the number of places are the same as the data entered into 'pageNumber', 'pageSize' fields

![Actual 2](https://user-images.githubusercontent.com/54502867/65585724-9b45c580-df8b-11e9-82c2-94df51774093.png)
![Actual](https://user-images.githubusercontent.com/54502867/65585725-9b45c580-df8b-11e9-8de9-eb39e5019eda.png)

**Comment by tivanych** [comment]
Confirmation test Fail
displayed 6 element (all) not 5 per page
"totalElements": 6,
  "currentPage": 1
![Знімок екрана 2019-10-08 22 09 04](https://user-images.githubusercontent.com/54436799/66425447-5fddd900-ea18-11e9-8fb0-3bcaf8b3638f.png)

**Comment by RomanZahorui** [comment]
Don't understend you. For this paramenters where 5 elements per page and page is 1 (means second page) :
![image](https://user-images.githubusercontent.com/7768829/66430061-011d5d00-ea22-11e9-9fc7-10549bd86c03.png)

I'm getting the next response:

{
  "page": [
    {
      "id": 2,
      "name": "Victoria Gardens",
      "location": {
        "id": 11,
        "lat": 49.807129,
        "lng": 23.977985,
        "address": "Вулиця Кульпарківська, 226а, Львів, Львівська область, 79000"
      },
      "category": {
        "name": "Food"
      },
      "openingHoursList": [
        {
          "id": 23,
          "openTime": "06:00",
          "closeTime": "20:00",
          "weekDay": "MONDAY"
        },
        {
          "id": 25,
          "openTime": "06:00",
          "closeTime": "20:00",
          "weekDay": "WEDNESDAY"
        },
        {
          "id": 27,
          "openTime": "06:00",
          "closeTime": "20:00",
          "weekDay": "FRIDAY"
        },
        {
          "id": 26,
          "openTime": "06:00",
          "closeTime": "20:00",
          "weekDay": "THURSDAY"
        },
        {
          "id": 24,
          "openTime": "06:00",
          "closeTime": "20:00",
          "weekDay": "TUESDAY"
        }
      ],
      "author": {
        "id": 1,
        "firstName": "Rostyslav",
        "lastName": "Khasanov",
        "email": "rostuk.khasanov@gmail.com"
      },
      "status": "APPROVED",
      "modifiedDate": "23.05.2005 14:25"
    }
  ],
  "totalElements": 6,
  "currentPage": 1
}

WHERE "totalElements": 6 - amount of all elements in our database
AND      "currentPage": 1 - second page. 

RESPONSE contains only one place with "id": 2 (the last item from 6 elements)
