### ISSUE TITLE
BUG (#50) automatic redirection from http to https is not connected. Button "Sign in with Google"  is not active on protocol http://

### ISSUE THREAD

**Issue by AnatoliyKazymyrchuk** [ita-social-projects/GreenCity#213]
related to #50 

**Steps to reproduce**

1. Go to http://greencityclient.herokuapp.com/auth
2. Click on "Sign-in with Google" button

**Actual Result**

- button "Sign-in with Google"  is not active on protocol http://

**Expected Result**

- Automatic redirection from http to https
- Button "Sign-in with Google"  is active
![Actual](https://user-images.githubusercontent.com/54502867/65594201-f16e3500-df9a-11e9-8167-7258f8156aea.png)

**Comment by lenadgit** [comment]
Ready
