### ISSUE TITLE
[Display news]  On the "Eco News" page  user sees only 6 news before scrolling

### ISSUE THREAD

**Issue by HannaVasiunyk** [ita-social-projects/GreenCity#2137]
**Environment:** Windows 10 Pro, Chrome 87.0.4280.88 (Розробка) (64-біт).
**Reproducible:** always
**Build found:** 29.12.2020

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/
2. Click on 'Eco News' button
3. Scroll down to first loading

**Actual result**
User sees only 6 first content item(news) by default.
![image](https://user-images.githubusercontent.com/47008446/103314982-f424c900-4a2c-11eb-812c-2eb88a969aa5.png)

**Expected result**
User should see first 12 content item(news) by default.

**User story and test case links**
   User story [#459](https://github.com/ita-social-projects/GreenCity/issues/459)
**Labels to be added**
"Bug"

**Comment by IrynaShlyakhetko** [comment]
Defect is fixed
