### ISSUE TITLE
[Header] Old 'User Name' is shown when user signs for the second time after editing 'Name' field

### ISSUE THREAD

**Issue by oprotyniak** [ita-social-projects/GreenCity#2138]
**Environment:** Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
Chrome 86.0.4240.198 (Розробка) (64-біт)
**Reproducible:** always
**Build found:** 30.12.2020

**Preconditions**
User is signed in.

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in
3. Click on 'Edit profile'
4. Change 'Name' field and save
5. Pay attention to User Name in Header
6. Sign out and sign in again
7. Pay attention to User Name in Header

**Actual result**
The Name is changed after profile editing in 'Header'. After sign out-sign the 'User Name' in 'Header' is changed to the name with which account was created for the first time. 'Name' in Profile is new.
![image](https://user-images.githubusercontent.com/73852063/103318751-153ee700-4a38-11eb-8602-323a65bb6f6d.png)

**Expected result**
The Name is changed after profile editing in 'Header'. After sign out-sign the 'User Name' in 'Header'corresponds to the 'Name' in Profile.
![image](https://user-images.githubusercontent.com/73852063/103318684-df99fe00-4a37-11eb-8a6f-a91646b69b2b.png)

**User story and test case links**
User story #225

**Comment by idzhersh** [comment]
**I checked, all works correct. even if you change your name in profile it also chages in header. Also I tried to sign-out and sign in again and names in header and profile were the same too**

![Screenshot (514) (1)](https://user-images.githubusercontent.com/50026335/115573411-6285e380-a2c9-11eb-99bc-6daadf9f02de.png)

**Comment by Halchysko** [comment]
This issue is closed, a new one is created. #2708
