### ISSUE TITLE
[Admin: Eco News] When Admin creates a News item, another News item is created

### ISSUE THREAD

**Issue by olesyasenyk** [ita-social-projects/GreenCity#2142]
#**Steps to reproduce:**
1. Go to Admin section > Eco News.
2. Click Add Eco News.
3. In the Add Eco News pop-up window, fill in all the fields and select Add.
A new News item is created.
4. Next to the newly created News item, select the Edit button.
![image](https://user-images.githubusercontent.com/54891146/103405804-0bfd6980-4b61-11eb-82dc-b23cb9cf6de8.png)
5. In the Edit pop-up window, edit the Text field, select Save.

**Actual result**
The same news item is duplicated under different IDs.
![image](https://user-images.githubusercontent.com/54891146/103406004-cb522000-4b61-11eb-887b-a6b00c88ea52.png)

**Expected result**
There is only one News item in which latest changes are saved.

**User story and test case links**
"User story #1116

**Comment by forestik** [comment]
Can`t reproduce
