### ISSUE TITLE
[Create news, preview] After "preview news"  tags list are invisible

### ISSUE THREAD

**Issue by HannaVasiunyk** [ita-social-projects/GreenCity#2156]
**Environment:** Windows 10 Pro, Chrome 87.0.4280.88 (Розробка) (64-біт).
**Reproducible:** always
**Build found:** 05.01.2021

**Preconditions**
1. Go to [Green City](https://ita-social-projects.github.io/GreenCityClient/#/news)
2. Sign in

**Steps to reproduce**
1. Go to 'create news' page.
2. Fill Title, content and select tags.
3. Click on "preview".
4. Click on "Back to editing".

**Actual result**
Tags are invisible.
![image](https://user-images.githubusercontent.com/47008446/103696174-98b38780-4fa6-11eb-9adc-46dd46af7e21.png)

**Expected result**
Tags list are displayed and you can select or deselect tags.
![image](https://user-images.githubusercontent.com/47008446/103696323-d3b5bb00-4fa6-11eb-9d16-e62f54a133a4.png)

**Labels to be added**
"Bug",

**Comment by OKalynivska** [comment]
Environment: Windows 10 Pro, Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by Ol98** [comment]
not reproducible
