### ISSUE TITLE
[Display News, List View] No content should be shown at resolution less than 1024px

### ISSUE THREAD

**Issue by AndriiTurianskyi** [ita-social-projects/GreenCity#2162]
**Environment:** Windows 10 Pro, Google Chrome 87.0.4280.141(64-bit).
**Reproducible:** always.
**Build found:** 09.01.21

**Preconditions**

1. Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. User should be authorized
3. There should be at least one news created by the current user

**Steps to reproduce**
1.Click on 'Eco news' button.
2. Click on'List view' icon.
3. resize the window width to less than 1024. 
4. Pay attention to the result.

**Actual result**
Content is shown.

**Expected result**
No content should be shown.

![Без імені](https://user-images.githubusercontent.com/74553656/104108139-f4de1a80-52ca-11eb-973c-e736c5ff634a.png)

**Test case links**
[GC-720](https://jira.softserve.academy/browse/720)"

**Comment by dmytro-kryvyi** [comment]
According to mocups content should be shown
![image](https://github.com/ita-social-projects/GreenCity/assets/94367438/3bda0bb9-77cb-43a6-abd3-4e513b77e45a)

**Comment by dmytro-kryvyi** [comment]
Not a bug
