### ISSUE TITLE
BUG (#_)As ADMIN I can't choose 'parentCategory', 'categories', 'places' when I create a category in 'category-controller/saveCategoryUsingPOST'

### ISSUE THREAD

**Issue by NataliiaVerkhola** [ita-social-projects/GreenCity#218]
**Pre-conditions:**
Go to https://greencity-lv448.herokuapp.com/swagger-ui.html#/
Click own-security-controller
Choose POST/ownSecurity/signIn
Insert 'email': 'firiw69955@tmail1.com',
'password': 'Qwer1234$' in 'json'
Execute query
Get a token
Click 'Authorize'
In 'Value' field insert 'Bearer token' and authorize

**Steps to reproduce**
Click category-controller
Choose POST/category saveCategory
Click 'Try it out'
Enter valid data in 'json'
Execute query.

**Expected Result**
Category is created. 'ParentCategory', 'Categories', 'Places' are chosen
**Actual Result**
Category is created. 'ParentCategory', 'Categories', 'Places' aren't chosen
![SubCategory ](https://user-images.githubusercontent.com/54468505/65599966-bde5d780-dfa7-11e9-8563-057faab1f7bd.png)

**Comment by nomadness** [comment]
This feature is not yet implemented. parentCategory, categories, places are set to null by default.
