### ISSUE TITLE
BUG (#20) Not Localization's in Map

### ISSUE THREAD

**Issue by AnatoliyKazymyrchuk** [ita-social-projects/GreenCity#219]
related to #20 

**Steps to reproduce**
1. Go to https://greencityclient.herokuapp.com
2. Click on some places which are tied with Google Maps (e.g. "Готель Львів")

**Actual Result**
- Appears tooltip in Russian Languages

**Expected Result**
- All elements in Map must be translated according to mock up 

To display in English you need to use https://www.google.com/maps/place/ **%**/**=en**
To display in Ukrainian you need to use https://www.google.com/maps/place/ **%**/**=uk**

![Actual](https://user-images.githubusercontent.com/54502867/65605846-787ad780-dfb2-11e9-854c-407cf2190623.png)

**Comment by MarianMilian** [comment]
Please check localization your browser or laptop, somewhere  you use russian localization

**Comment by AnatoliyKazymyrchuk** [comment]
> Please check localization your browser or laptop, somewhere you use russian localization

I check localization browser and  laptop:
 - my comp:  browser - English , Win - Russian  https://prnt.sc/paw15o
-  RD comp:  browser - English , win - Eng  https://prnt.sc/paw2fo

Errors are identical on different computers and different settings.
Accordingly, it does not extend from Environment

BUG in RD comp:  https://prnt.sc/paw5f6
BUG  in  my comp: https://prnt.sc/paw4vc

**Comment by lenadgit** [comment]
It depends of custom setups in Google Maps (not in OS)
Go to the settings in your browser. Scroll down to the link Advanced. Choose Language and add Ukrainian to the list (if it was not added). And choose the option View Google Chrom in Ukrainian 
https://i.piccy.info/i9/4e8b54a2cdd8bc121de18ec22c7898b1/1580722188/112998/1358686/language.jpg
