### ISSUE TITLE
Access admin page for moderation

### ISSUE THREAD

**Issue by yartymys** [ita-social-projects/GreenCity#22]
As an admin I want to access admin page, so that I can moderate the cafes on the map/list. 

**Mockups:**  
![image](https://user-images.githubusercontent.com/53810790/63801130-4412ed80-c918-11e9-941e-9547781147c0.png)
![image](https://user-images.githubusercontent.com/53810790/63801295-a0760d00-c918-11e9-9c4d-157eb700c9c3.png)

**Acceptance Criteria:**
1. GIVEN admin user is successfully logged in to the system, WHEN he clicks on "Admin" button, THEN system shall navigate him to the admin page.

2. The admin page shall contain the following tabs at the top of the screen:
a. Users
b. Places

3. When admin clicks on a tab, system shall navigate him to it.

**Out of scope:**
list of places and users are out of scope of this story

**Comment by rsyvulko** [comment]
Not relevant.
