### ISSUE TITLE
[UBS] Review order summary and submit order

### ISSUE THREAD

**Issue by Oksana-Voitovych** [ita-social-projects/GreenCity#2200]
**As a** user I want to review information about my order so that I could manage it if needed before I proceed to the payment. 

**Preconditions:**
The registered user is logged in
User has filled the “Деталі замовлення” and “Особисті дані” tabs

**Acceptance criteria:**
1. User is able to review the information about his/her order at the “Оплата” tab of the Order form.

2. Information about the order is divided into 2 sections:
    a. Ваше замовлення
    b. Деталі замовника.

3. In the section “Ваше замовлення” user can see the list of chosen packages and the total amount of the order.

4. In the section “Деталі замовника” his/her:
    a. personal information in the format: Surname and name, email address and phone number;
    b. address details in the format: City, district, street, building #, entrance #, comment (if any)

5. User is able to see the payment method in the drop-down “Спосіб оплати”:
    a. system displays "Карткою через LiqPay" by default.

6. By clicking on the button “Назад”, user is redirected to the previous tab where he/she can edit the information if needed:
    a. system should update and display the edited information at the “Оплата” tab.

7. By clicking on the button “Замовити” user is redirected to the page of the payment system.

![image](https://user-images.githubusercontent.com/73845584/105024905-4a49c280-5a55-11eb-9e17-670d712a1b55.png)

Epic #2195

**Comment by MyroslavaVynokur** [comment]
LiqPay payment works, but we have a problem on LiqPay servers (payment is not set as successful as we need Private Entrepreneur account opened in Privat Bank,  so we can't test it) - move to status blocked

**Comment by IrusiaVI** [comment]
Superseded #2541
