### ISSUE TITLE
[API] [Habit-assign-controller] [Documentation] there is not Example value for code 200 on get/habit/assign controller

### ISSUE THREAD

**Issue by IrynaShlyakhetko** [ita-social-projects/GreenCity#2230]
**Environment:** Windows, MacOS (Chrome, Mozilla).
**Reproducible:** always.
**Build found:** 28.01.2021

**Preconditions**
Preconditions:

Swagger https://greencity.azurewebsites.net/swagger-ui.html#/ is opened.
User have to be logged
User has to have some habits in progress
Get token
Authorize

**Steps to reproduce**
1. Open habit-assign-controller
2. Choose GET Habit/assign 
3. Click "Try it out" button
4. Leave field for test data empty
5. Click "Execute" button

**Actual result**
There is not Example value for code 200 on get/habit/assign controller

**Expected result**
There is  Example value for code 200 on get/habit/assign controller

**Postconditions**

**User story and test case links**
E.g.: "User story #988 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by IrynaShlyakhetko** [comment]
<img width="1207" alt="Screen Shot 2021-01-27 at 11 10 38" src="https://user-images.githubusercontent.com/77668307/106106598-73054280-614e-11eb-851a-32ef0c8d5308.png">

**Comment by IrynaShlyakhetko** [comment]
Defect is not fixed

**Comment by MarianDiakiv** [comment]
Can you look again. 
![image](https://user-images.githubusercontent.com/36082474/107020350-70889580-67ab-11eb-9666-439d4c96e523.png)

**Comment by IrynaShlyakhetko** [comment]
orders of Dates in response body and example value are different. 
<img width="1193" alt="Screen Shot 2021-02-08 at 16 24 15" src="https://user-images.githubusercontent.com/77668307/107233203-fcf4bb80-6a2a-11eb-9005-cf3ecd17107a.png">
<img width="672" alt="Screen Shot 2021-02-08 at 16 24 35" src="https://user-images.githubusercontent.com/77668307/107233219-01b96f80-6a2b-11eb-974f-ffcd5496abaa.png">

**Comment by Nazar-Blashchak** [comment]
Not valid yet
