### ISSUE TITLE
[API] [eco-news-controller] Logged user can`t delete not his own comment on the 'News' page

### ISSUE THREAD

**Issue by AndriiTurianskyi** [ita-social-projects/GreenCity#2231]
**Environment:** Windows 10 Pro, Chrome 87.0.4280.88 (Розробка) (64-біт).
**Reproducible:** always.
**Build found:** 28.01.21

**Preconditions**

1. Open Swagger: https://greencity.azurewebsites.net/swagger-ui.html#/ ;
2. Sign in with controller Post /ownSecurity/signIn (e.g. green.city.test2@gmail.com, Green.city#500);
3. Use a token to authorize in Swagger
4. The system should have comments and replay not logger users.

**Steps to reproduce**
1. Open eco-news-comment-controller
2. Click DELETE /econews/comments Delete comment.
3. Click "Try out" button
4. Set not ID users comment
5. 5. Click on the 'Execute' button. 

**Actual result**
error 400 
![statusCode](https://user-images.githubusercontent.com/74553656/106146185-0d7d7a00-617f-11eb-8306-aa6fc5d272e2.png)

**Expected result**
Should be error 403
![expected](https://user-images.githubusercontent.com/74553656/106146426-52a1ac00-617f-11eb-86d4-b161b5822523.png)

** Test case links**
[Test case GC-1158](https://jira.softserve.academy/browse/GC-1158)"

**Comment by adamos98** [comment]
![image](https://user-images.githubusercontent.com/75321714/118644490-25d0dd80-b7de-11eb-9f79-1f7f4fa6bd73.png)
I checked it and everything works correctly.

**Comment by SerhiiStarshoi** [comment]
Current user has no permission for this action![photo_2021-06-04 13 05 59](https://user-images.githubusercontent.com/32453285/120785226-9e9d9c80-c535-11eb-8cdc-d6191a98c4c8.jpeg)
