### ISSUE TITLE
User Settings

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#225]
As a registered user I want to be able to view and edit my user information/settings.

**Mockup:**
![image](https://user-images.githubusercontent.com/53868652/65838321-c07b6080-e30a-11e9-87dd-1e181bbe4149.png)

**Acceptance Criteria:**

1. Provided user is logged in to the application, system shall display "User Settings" button (at top right of the screen).

2. Provided user clicked on 'User Settings' button, system shall open a modal window.

3. User Settings modal window shall contain
a. header "User Settings"
b. 'X' icon in header to close the modal
c. main body elements:
c.1 "Email" with user's email address
c.2 "Change password" button next to user's email   - [out of scope of this story]
c.3 "First name" with user's first name as per registration
c.4 "Last name" with user's last name as per registration
d. buttons in footer: "Cancel", "Save"
3.1. Each element from the main body is required (cannot be left blank).

4. User's email in the "Email" element shall be not editable and static.

5. "First name" and "Last name" elements shall have 'Edit' buttons next to them.
5.1. Provided user clicks on edit button next to first or last name, system shall display an input field with the entered name, which shall be editable.

6. Button "Save" in the footer shall be disabled by default.
6.1. Provided there is a change to at least 1 element of the modal window, "Save" button shall get enabled.
6.2. Provided user clicks on "Save" button, system shall 
a. save the changes
b. close the modal window
7. Button "Cancel" in the footer shall be always enabled.
7.1. Provided user clicks on "Cancel" button, system shall 
a. not save any changes 
b. close the modal window
8. 'X' icon in the header shall work the same as 'Cancel' button.

**Assumptions and Constraints:**
relates to #226
relates to #227

**TBD:**

**Comment by rsyvulko** [comment]
Not relevant.
