### ISSUE TITLE
[API] [UBS] After entering not existing code of certificate, the output code is 200, not 404

### ISSUE THREAD

**Issue by YulianaQC** [ita-social-projects/GreenCity#2258]
**Environment:** Windows, MacOS.
**Reproducible:** always.
**Build found:** 03.02.2021

**Preconditions**
1. Registered User logged in.
2. Swagger is opened and authorized (https://greencity-ubs.azurewebsites.net/swagger-ui.html)
3. Dabase is opened

**Steps to reproduce**
1. Click 'order-controller'
2. Click 'GET /ubs/first/certificate/{code} Check if certificate is active'
3. Click 'Try it out' button
4. Enter the code in 'code' field that does not exist in table 'certificate', column 'code' (e.g. 'fgh').
5. Click 'Execute' button

**Actual result**
Code 200

**Expected result**
Code 404

**User story and test case links**
E.g.: "User story #2195 
[Test case]()"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by LiliiaPalii** [comment]
Swagger doesn't contain  'order-controller'  for  checking

**Comment by ZaharVeremchuk** [comment]
We have 3 different swagger. Its on ubs swagger.
https://greencity-ubs.azurewebsites.net/swagger-ui.html

**Comment by ZaharVeremchuk** [comment]
@LiliiaPalii
