### ISSUE TITLE
Email notifications about new places (User settings)

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#226]
As a registered user I want to receive email notifications about newly added places to the map, so that I have the up-to-date information.

**Mockups:**
1
![image](https://user-images.githubusercontent.com/53868652/65837712-5e6b2d00-e303-11e9-9cf3-ff5a6fab6aae.png)

2
![image](https://user-images.githubusercontent.com/53868652/65837825-8f982d00-e304-11e9-9e38-ad9d74ab71e3.png)

**Acceptance Criteria:**
1. In User settings system shall display "Email Notifications" element, which shall have radio buttons
 a. Yes
 b. No
2. "No" shall be selected by default.
3. Provided "Yes" is selected in "Email Notifications", system shall display element "Frequency" below the "Email Notifications".
4. "Frequency" element shall have radio buttons
 a. Immediately
 b. Daily - shall be selected by default
 c. Weekly
 d. Monthly
5. Provided user selected "Yes" in the email notifications, system shall send and email to user, with notification that a new place has been added to the map (i.e. approved places by admin).
6. Email notification for Immediate notifications shall be of the following pattern:
"Dear [user_first_name],
a new [category] place **[NAME_OF_PLACE]** has just been added to Green City."
(e.g. "Dear Yurii, 
a new Food place "**Delikateka**" has just been added to Green City.")
7. Email notification for Daily, Weekly, Monthly notifications shall be of the following pattern:
"Dear [user_first_name],
new [category] place(s) have been added to Green City [yesterday/last week/last month]:
**[list_of_all added places_within_the_period]**"
(e.g. "Dear Yurii,
new Food place(s) have been added to Green City yesterday:
**Sily Z'ily
Chelentano
Puzata Khata**")
8. Email notifications shall be sent per following pattern
a. Immediately - an email shall be sent to user(s) as soon as a new place is added to the map (approved by admin)
b. Daily - a daily summary email, which shall include all places added within the previous day, shall be sent to user(s) every day at 12:00 (PM). 
(e.g. on Tuesday at 12:00 (PM) an email shall be sent to user(s), which shall include all places added to the map (approved by admin) from 12:00 PM Monday till 12:00 PM Tuesday)
c. Weekly - a weekly summary email, which shall include all places added within the previous week, shall be sent to user(s) every Monday at 12:00 (PM)
d. Monthly - a monthly summary email, which shall include all places added within the previous month, shall be sent to user(s) every 1st day of the month at 12:00 (PM)

9. Provided "No" is selected in "Email Notifications", system shall not display element "Frequency" below the "Email Notifications" AND shall not send notifications to user.

to ADD - no added places - no email (for daily/monthly/weekly

**Assumptions and Constraints:**
relates to #225

**Comment by rsyvulko** [comment]
Not relevant.
