### ISSUE TITLE
Change password for registered user (User settings)

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#227]
As a registered user I want to be able to change my password.

**Mockup:**
![image](https://user-images.githubusercontent.com/53868652/65837859-ff0e1c80-e304-11e9-97ae-d69debcb112e.png)

**Acceptance Criteria:**
1. Provided user clicks on "Change password" button in User settings, system shall display the following input fields below the button:
a. "Current password"
b. "New password"
c. "Confirm password"

2. Criteria for a new password shall be the same as in #29.

3. GIVEN user entered incorrect current password, WHEN he presses "Save" button, THEN system shall 
a. highlight the input field red 
b. display a textual error message "Incorrect password" above the input field
4. GIVEN new password does not match security criteria, WHEN user presses "Save" button, THEN system shall display
a. highlight the input field red 
b. display a textual error message "Password does not match security criteria" above the input field
5. GIVEN confirm password does not match new password, WHEN user presses "Save" button, THEN system shall 
a. highlight the input field red 
b. display a textual error message "Password does not match" above the input field

**Assumptions and Constraints:**
relates to #225 
relates to #29

**Comment by rsyvulko** [comment]
Not relevant.
