### ISSUE TITLE
[API] [tips-and-tricks-controller] Logged user can`t add new tips & tricks.

### ISSUE THREAD

**Issue by AndriiTurianskyi** [ita-social-projects/GreenCity#2289]
**Environment:** Windows 10 Pro, Chrome 87.0.4280.88 (Розробка) (64-біт).
**Reproducible:** always.
**Build found:** 10.02.21

**Preconditions**

1. Open Swagger: https://greencity.azurewebsites.net/swagger-ui.html#/ ;
2. Sign in with controller Post /ownSecurity/signIn (e.g. green.city.test2@gmail.com, Green.city#500);
3. Use a token to authorize in Swagger

**Steps to reproduce**
1. Open tips-and-tricks-controller
2. Click POST /tipsandtricks Add new tips & tricks.
3. Click "Try out" button
4. Enter new tips & tricks data
5. Click on 'Execute'.

**Actual result** 
Code 500
![d](https://user-images.githubusercontent.com/74553656/107534105-44fd1500-6bc8-11eb-980e-95e2488a8552.png)

**Expected result**
Status code 200

**Comment by darzinch** [comment]
при перевірці видає помилку
![image](https://user-images.githubusercontent.com/91462440/135323609-38fc36bd-649c-4441-963e-c03ab5b23020.png)

**Comment by ViktoriyaRyazhska** [comment]
not relevant
