### ISSUE TITLE
Approve/decline proposed cafes

### ISSUE THREAD

**Issue by yartymys** [ita-social-projects/GreenCity#23]
As an admin I want to be able to approve or decline proposed cafés.
**Mockups:**

**Acceptance Criteria:**

1. Provided there is at least one unapproved cafe in the list of proposed cafes, system shall display 2 buttons "Approve" (green) and "Decline" (red) to the right of the respective cafe description.

2. Provided admin approved a proposed cafe, by clicking on the "Approve" button AND it was successfully approved, then system shall:
a. remove the item from the list of proposed places
b. add the item to the list of approved places
c. add the place to the map
d. display a notification flash message "Approved" (green color) at the top of the screen (it shall disappear in 3 seconds)

3. Provided admin approved a proposed place AND it was not successfully approved due to a system or other error, then system shall display a notification flash message "Error. Item was not approved. Please try again" (red color) at the top of the screen. (the item shall not disappear from the proposed list.

4. Provided admin declined a proposed place, by clicking on the "Decline" button, then system shall:
a. remove the item from the list of proposed places
b. add the item to the list of declined places
c. display a notification flash message "Declined" (green color) at the top of the screen (it shall disappear in 3 seconds)

5. Provided admin declined a proposed place AND it was not successfully declined due to a system or other error, then system shall display a notification flash message "Error. Item was not declined. Please try again" (red color) at the top of the screen. (the item shall not disappear from the proposed list.

**Assumptions and Constraints:**

this user story is related to user story #24

**TBD:**

**Comment by yartymys** [comment]
As an admin I want to be able to approve or decline proposed cafés.  
Mockups:

Acceptance Criteria:

1. Provided there is at least one unapproved cafe in the list of proposed cafes, system shall display 2 buttons "Approve" (green) and "Decline" (red) to the right of the respective cafe description.
2. Provided admin approves a proposed cafe, system shall:
a. remove the item from the list of proposed places
b. add the item to the list of approved places
c. add the place to the map



Assumptions and Constraints:

this user story is related to user story #24 

TBD:

**Comment by rsyvulko** [comment]
Not relevant.
