### ISSUE TITLE
Detail information of a place - Working times enhancement

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#232]
As a user I want to see working times for the current day by default, and be able to see working times for the whole week.

**Mockups:**
current state: 
![image](https://user-images.githubusercontent.com/53868652/65873914-0da01680-e38d-11e9-945b-18e20c790ba2.png)

to be state collapsed: 
![image](https://user-images.githubusercontent.com/53868652/65873938-214b7d00-e38d-11e9-87a3-4ead90ac6a86.png)
to be state expanded: 
![image](https://user-images.githubusercontent.com/53868652/65873964-2f999900-e38d-11e9-8fda-b9d8ba55a7cc.png)

**Acceptance Criteria:**
1. In the details view popup, system shall display working times for the current day only. (e.g. if today is Monday - system shall display working times for Monday only)
2. In the details view popup, system shall display a collapse/expand icon next to the current day working times.
3. Provided user clicks on the expander, system shall 
a. expand the working times area 
b. display working times for all available days
c. display working times of the current day in bold font
4. Provided user clicks on the collapser, system shall collapse the working times area and display working times for the current day only. 
5. All available days with working times shall be sorted in order Monday to Sunday.

**Assumptions and Constraints:**
relates to #26

**Comment by rsyvulko** [comment]
Not relevant.
