### ISSUE TITLE
Payment with certificate 

### ISSUE THREAD

**Issue by AnnaMix** [ita-social-projects/GreenCity#2329]
As a user, I want to be able to use the certificate so that I can receive a discount for a partial or full order amount. 

**Preconditions:**
- The registered user is logged in.
- The user chooses services in the tab “Деталі замовлення”.
- The user has at least one valid certificate.
- The user’s valid certificate is in the database. 

**Assumptions and constraints:**
- All certificates should exist in the database before they are issued for the user.

**Business rules:**
1. The certificate serial number format is restricted with 9 characters “4 numeric characters_dash_4 numeric characters” (for example 1234-1234), according to which:
   - the first four characters before the dash correspond to the number of the service assigned by an accountant via 1C system and it cannot be “0000”;
   - the last four characters after the dash are the sequence number of the certificate and the numbering starts from “0001”.
3. The certificate is activated and valid as of the issue date. The administrator sets up the expiration date per each certificate. The expiration date should be shown in the message when the certificate is applied (AC-6).
3. The certificate’s minimum amount is 500 UAH and no maximum amount limit.

**Acceptance criteria:**
1. Under the order list, the logged-in user sees a certificate section with the sub-title “Чи бажаєте Ви скористатися сертифікатом?”. 
2. The input field for the certificate is shown with the text “Введіть номер сертифіката” above it. 
3. The field contains a placeholder with a grey-colored text: “XXXX-XXXX”. The placeholder shall disappear once the user starts typing.
4. When the user enters the first 4 numeric characters of the certificate, the system shall automatically enter a dash according to the certificate format.
5. The button “Активувати” is disabled until the user enters all 8 numeric characters according to the certificate format.
The mockup for the certificate field in the default state under the order list:
![image](https://user-images.githubusercontent.com/78092432/112617689-f4671180-8e2d-11eb-81db-1d94e15367ff.png)

6. The user can’t type more than 8 numeric characters in the certificate input field. 
7. When the user clicks on the button “Активувати”, the system shall verify the certificate number by checking it in the database. The system shall show the following messages under the certificate input field and make relevant changes in the order amount field in the following cases:

  | Entered characters | Expected results | Expected message | Changes in the order amount field
-- | -- | -- | -- | --
  1. | Eight numeric characters 0-9 of the certificate with a discount that is lower or equals the order amount. | The certificate matches with the database and the certificate is valid. The system accepts the certificate. The order amount is recalculated. | *Сертифiкат на cуму XXX грн активовано. Строк дії сертифікату - до YY.YY.YYYY* | The additional row “Сертифiкат” appears under the row “Сума замовлення”, its discount is shown and the system deducts it from the order amount.
 | 2. | Eight numeric characters 0-9 of the certificate with a discount that is greater than the order amount. | The certificate matches with the database and the certificate is valid. The system accepts the certificate.The order amount is recalculated. | *Сертифікат на суму XXX грн активовано, що перевищує суму Вашого замовлення. Залишок у розмірі YYY грн буде нараховано на Ваш бонусний рахунок для наступного замовлення. Строк дії сертифікату - до YY.YY.YYYY* | The additional row “Сертифiкат” appears under the row “Сума замовлення”, its discount is shown and the system deducts it from the order amount so the total amount equals 0.
| 3. | Eight numeric characters 0-9 but they altogether do not match with the database, including 0000-0000. | The certificate does not match with the database and the certificate is invalid. The system rejects it. The order amount is not changed. | *Сертифiкат не прийнято. Спробуйте ще раз.* | The additional row with the certificate does not appear.
| 4. | Special characters that are not allowed *(%$#@&*?!+=:”></) | When at least one special character is entered, the certificate is not valid and the system rejects it. The order amount is not changed. | *Номер сертифікату введено некоректно. Спробуйте ще раз.* | The additional row with the certificate does not appear.
| 5. | Eight numeric characters 0-9 of the certificate that has been already used. | The certificate matches with the database but it was already applied before, so the certificate is invalid. The system rejects it. The order amount is not changed. | *Сертифiкат вже використано. Строк дії сертифікату - до YY.YY.YYYY* | The additional row with the certificate does not appear.
| 6. | Eight numeric characters 0-9 of the certificate that is expired. | The certificate matches with the database but it is expired, so the certificate is invalid. The system rejects it. The order amount is not changed. | *Сертифікат не є дійсним. Строк дії сертифікату - до YY.YY.YYYY* | The additional row with the certificate does not appear.

The mockup with the example of the message for the applied valid certificate with its discount that is also shown in the order amount field (case 1 in the table above):
![image](https://user-images.githubusercontent.com/78092432/110180537-a6ed1b00-7e12-11eb-8318-69205d9227cb.png)
8. When the certificate is accepted, the button “Активувати” shall switch to button “Відмінити”.
9. When the user clicks on “Відмінити” button, the system shall clear the input field and return it to the default state. The system shall remove the additional row “Сертифiкат” under the row “Сума замовлення” together with the certificate’s discount and recalculate the order amount back to the order amount without the discount. 
10. The system shall add the link “Додати ще сертифікат” under the field with the first accepted certificate. When the user clicks on the link, the system shall show another input field and the system shall behave in the same way as it does with the previous input field.
The mockup with the example of the link for the second input field:
![image](https://user-images.githubusercontent.com/78092432/110180713-f92e3c00-7e12-11eb-85c5-1d869c2d8da7.png)
11. When the first certificate equals or exceeds the order amount, the system shall not show the link “Додати ще сертифікат” for another certificate. 
12. The user must be able to add a new certificate until the amount of the order is fully covered.
13.  When the user applies two or more certificates, the system shall add up all discounts to one total discount, dynamically display it in the additional row “Сертифiкат” under the row “Сума замовлення” and deduct the total discount from the order amount.

**Out of scope:**
N/A

**Related Epic** - #2195

**Comment by kulaira** [comment]
[Certificates.postman_collection (2).json](https://github.com/ita-social-projects/GreenCity/files/15351622/Certificates.postman_collection.2.json)
