### ISSUE TITLE
Admin can view and delete created feedback on a place

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#236]
As an Admin I want to view and delete created feedback on a place so that feedbacks with no sense will be not visible on the site.

Acceptance criteria:

1. Admin can review created feedback on all available places.

2. Admin can see created feedbacks on all places on Admin page as a table with two columns:
a. Name of place to what feedback is related
b. Text of feedback
c. Name of attachment with hyperlink. If there is no attachments, then placeholder "No attachments".

3. Near each row of the table delete icon is available.

4. WHEN Admin clicks on any delete icon, THEN popup with the next option:
a. " Are you sure you want to delete this feedback?" as text
b. "Yes" button
c. "Cancel" button

5. WHEN Admin clicks "Yes" button, THEN appropriate row should be removed from the table on Admin page and from info panel of the place in the side bar list to what feedback is related.

6. WHEN Admin clicks "Cancel" button, THEN Admin see table of feedbacks on current page.

**Comment by rsyvulko** [comment]
Not relevant.
