### ISSUE TITLE
[Calendar] [My Habits] The empty pop-up appears after user clicks on the date without habits

### ISSUE THREAD

**Issue by IrynaMarkovych** [ita-social-projects/GreenCity#2364]
**Environment:** MacOS, Google Chrome, Version 88.0.4324.192
**Reproducible:** always
**Build found:** 10.03.2021
**Preconditions**

- Registered User is logged in (e.g.,email: testgreencity121@gmail.com, password: Testgrencity45/)
- My habits page is open
- User has at least one habit in progress

**Steps to reproduce**
1. Click on the date without habits in the top right corner of the 'Calendar'
2. Pay attention to the next action

**Actual result**
The empty pop-up appears (see attachments)
<img width="504" alt="Screen Shot 2021-03-07 at 10 15 02 PM" src="https://user-images.githubusercontent.com/79633583/110681860-f51f6700-81e2-11eb-8e0b-7db7d130e488.png">

**Expected result**
The pop-up does not appear for days without habits

**User story and test case links**
E.g.: "User story #1431 
[Test case](https://jira.softserve.academy/browse/GC-1864)"

**Labels to be added**
"Bug"

**Comment by kovalsofiia1** [comment]
A pop-up appears on days without habits, showing a habit that is marked as not done, but the pop-up is not empty.

![Image](https://github.com/user-attachments/assets/8960c13f-ba29-413c-a886-bb652a946868)
