### ISSUE TITLE
List of Places

### ISSUE THREAD

**Issue by yartymys** [ita-social-projects/GreenCity#24]
As an admin I want to see the list of Places, so that I can approve/decline them later. 
**Mockups:** 
![image](https://user-images.githubusercontent.com/53810790/63801067-26458880-c918-11e9-9f06-30db0c5626a9.png)
 
**Acceptance Criteria:**
1. WHEN an admin user navigates to the tab "Places" in the admin page, THEN an admin shall see them in a table list;

2. The list of Places shall contain the following columns:
a. "Category"
b. "Name"
c. "Address" 
d. "Working times"
e. "Added by" (login of user who proposed a place)
f. "Added on" (date of proposed place)
e. "Status" (Proposed/Approved/Declined)

3. System sorts records in the list of places by date added (newest at the top) and status by default.

4. System shall display data in the columns as follows:
a. category (dropdown list with data)
a. name - free text (max # of chars = 30)
b. address - free text (max # of chars = 30)
c. working times - time range in format "HH:MM-HH:MM"
d. added by - user login (email)
e. added on - in format "DD.MM.YY HH:MM"
f. Status - dropdown list (Proposed/Approved/Declined)

5. The table can have a maximum number of record rows that can fit on a page. There shall not be a scroll.
6. Provided there are more record rows that can fit the page, system shall display a page counter and buttons "Previous", "Next" at the bottom of the page.
7. GIVEN user is on a page AND there is a page counter and button "Previous" or "Next" respectively, WHEN 
- user clicks on "Next" button, THEN system shall navigate him to the next page
- user clicks on "Previous" button, THEN system shall navigate him to the previous page.
 

**Assumptions and Constraints:**
1. this user story is related to user story #23 
2. page selector is currently out of scope of this user story

 
**TBD:**

**Comment by rsyvulko** [comment]
Not relevant.
