### ISSUE TITLE
Check performance of an application

### ISSUE THREAD

**Issue by ViktoriyaRyazhska** [ita-social-projects/GreenCity#2440]
Ivestigate responce time of the next features:

N | Feature | DB, time | API, time | Web, time
-- | -- | -- | -- | --
1 | 'Home' page | 1.27s, 5.76s | 9.10 s, 3.84 s |  5,40s
2 | 'Eco news' page | 1.38s, 6.89s  | 3.53s |  8.51s
3 | 'Single news' page | 1.16s, 5.79s  | 2.83s |  13.32s
4 | Create   news (after clicking 'Create' button) |0.86s, 5.23s   | 4.53s  |  5.14s
5 | 'My   habits' page     - all habits     - use filter |  0.95s, 6.65s | 2.84s  |  8.15s
6 | 'Add new habits' page | 1.02s, 5.99s  | 2.00s  |  6.37s
7 | 'About us' page |-   |-   |  4.07s
8 | Calendar |  - | -  |  3.09s

**Comment by ZaharVeremchuk** [comment]
Exel results : https://1drv.ms/x/s!AoWUW8YEg0ovgXx12xH-Ocgjfc1w?e=MsZe0v
