### ISSUE TITLE
[Search] Search does not work when we enter two words

### ISSUE THREAD

**Issue by SerhiiNesterov** [ita-social-projects/GreenCity#2455]
Environment: Windows 10 browser: all
Reproducible: always
Build found: 23.03.2021

Preconditions
The GreenCity application is opened

Steps to reproduce

1. Choose two words that are exactly in the content (e.g. '20' and 'day')
2. Input into 'search' field '20 day'
3. Pay attention to the result

Actual result:
Message '0 items found' appears

Expected result:
First results where those two words appear together, but not necessarily one near another, the later results will contain at least one of those words

User story and test case links
User story #[545](https://github.com/ita-social-projects/GreenCity/issues/545)

**Comment by JimHolman1199** [comment]
hi, i can see it works, could you check it again?

**Comment by SerhiiNesterov** [comment]
Hi there. it still doesn't work.

1 квітня 2021, 19:49:00, від "Yurii Pryshliak" ***@***.***>:


hi, i can see it works, could you check it again?

**Comment by SerhiiNesterov** [comment]
If you want I can explain by phone why I say it doesn't work

1 квітня 2021, 19:49:00, від "Yurii Pryshliak" ***@***.***>:


hi, i can see it works, could you check it again?

**Comment by SerhiiNesterov** [comment]
0975395988

2 квітня 2021, 15:35:43, від "Sergiy Nesterov" ***@***.***>:

If you want I can explain by phone why I say it doesn't work

1 квітня 2021, 19:49:00, від "Yurii Pryshliak" ***@***.***>:


hi, i can see it works, could you check it again?

**Comment by SerhiiNesterov** [comment]
When you enter '20' it gives 14 results. When you enter 'day' it gives 100 results. When you enter '20 day 'it should give 114 results, but gives 0.

2 квітня 2021, 15:36:27, від "Sergiy Nesterov" ***@***.***>:

0975395988

2 квітня 2021, 15:35:43, від "Sergiy Nesterov" ***@***.***>:

If you want I can explain by phone why I say it doesn't work

1 квітня 2021, 19:49:00, від "Yurii Pryshliak" ***@***.***>:


hi, i can see it works, could you check it again?

**Comment by yuriiLisunov** [comment]
hi. it works correctly according to chosen search algorithm.

**Comment by OksanaRom** [comment]
Still doesn`t work
**Steps to reproduce:**
1.Type word 'title' into search field
2. Pay attention to search results (55 items found)
3.  Type word 'just' into search field
4.  Pay attention to search results (15 items found)
5. Type words just title' into the search field
6. Pay attention to search results ( no items found)

![searching two words](https://user-images.githubusercontent.com/80678953/115006030-1265e600-9eb1-11eb-9a34-76cef570b9a2.jpg)

**Comment by yuriiLisunov** [comment]
OksanaRom, this functionality works correctly !!! You can get detailed information about search algorithm from the project manager!

**Comment by LiliiaPalii** [comment]
Search field logic does not work
![Search field](https://user-images.githubusercontent.com/55461895/121092721-ad65a700-c7f4-11eb-8fd6-0be44b7e4fd6.png)

**Comment by KaterynaKhorosh** [comment]
Search  works when we enter two words
