### ISSUE TITLE
Online payment by card via Fondy

### ISSUE THREAD

**Issue by AnnaMix** [ita-social-projects/GreenCity#2477]
As a user, I want to use an online payment service, so that I am able to pay the order using my credit/debit card.

**Assumptions & Constraints**
N/A

**Preconditions**

- The registered user is logged in.
- The user chooses services in the tab “Деталі замовлення” and applies certificate(s) or/and bonuses.
- The user fills in his/her personal information for the order in the tab “Особисті дані”.
- The user has at least one valid debit or credit card.
- The user has available money in the card account in UAH and this amount equals to or greater than the order amount.

**Business rules**
N/A

### Acceptance Criteria
1. When the user places the order, in the tab “Пiдтвердження” the user sees the order summary with the final order amount to be paid.
The mockup of the tab “Пiдтвердження”:
![image](https://user-images.githubusercontent.com/78092432/112618733-20cf5d80-8e2f-11eb-8673-fe3d2d8d52ed.png)

2. When the user clicks on “Назад” button at the bottom of the page to change any order data, the system shall save user input data in the order form and let the user go back to the previous order tabs.

3. In the field “Оплата”, the user sees a drop-down list to choose a payment method.

4. The drop-down list is shown with the text above “Оберіть спосіб оплати” and the pre-selected method “Kарткою через Fondy”. The second option from the drop-down list is LiqPay. 

5. When the user clicks on “Замовити” button, the system shall redirect the user to the new page with Fondy payment form and the order amount in the payment field shall equal to amount in  “Сума до оплати” field. 

6. When the user is redirected to the new page with Fondy payment form, the user should input valid debit or credit card number, valid thru date MM/PP and CVV/CVC of the card. 

7. When the user submits the payment, the system shall return the user to the confirmation page and show one of the following messages:

Payment status | Expected result | Expected message
-- | -- | --
The payment is successful | The order is fully paid and the user’s bank account is charged with the order amount. | _Ваше замовлення прийнято (№ХХХХ)_
The payment failed | The bank rejects the payment and the order is not paid. The system saves the order in the user’s cabinet and changes the order status on Unpaid. | _Упс, щось пішло не так..._

The mockup of the confirmation page in the case of successful payment:
![image](https://user-images.githubusercontent.com/78092432/112530565-4157d300-8daf-11eb-8e4f-ef289c2b17f6.png)

The mockup of the failed payment screen:
![image](https://user-images.githubusercontent.com/78092432/112765260-022abb80-9015-11eb-8339-d01164c7ca61.png)

8. When the order amount equals 0 UAH (in the case when applied certificates or/and bonuses cover the full order amount), the system shall not show the whole block “Оплата”, so the user clicks on “Замовити” button and gets a confirmation screen from the system about the successful order placement. It should be depicted in admin table order in the order payment confirmation as “Оплачено”.

9. When the payment is successful, Fondy should send the order payment confirmation as “Оплачено”, the date of payment “Дата оплати” and the payment ID “ID платежу”, which should be depicted in the corresponding columns in the admin table-order (see mockup of the table below) and be related to the corresponding order number “№ замовлення”.
![table-order](https://user-images.githubusercontent.com/83393282/117943729-1e5c9080-b315-11eb-994e-39e0a7405039.png)

10. When the user clicks on “Вiдмiнити” button at the bottom of the page, the system shall save user input order data and show a pop-up window with the warning message:
![image](https://user-images.githubusercontent.com/78092432/112530866-9a276b80-8daf-11eb-8b69-d74c72913bfa.png)

- If the user chooses to click on “Ні, не потрібно” button, the system shall erase all entered user data and redirect the user to the Home Page.
- If the user chooses to click on “Так, зберегти” button, the system shall save the order as a draft in the user’s cabinet and redirect the user to the confirmation page with the message on the banner: “Тепер ви можете знайти своє замовлення № 12345 у Вашому особистому кабінеті та продовжити його оформлення в будь-який час”.

The mockup for the page with the confirmation of the saved order:
![image](https://user-images.githubusercontent.com/78092432/112530988-b925fd80-8daf-11eb-8605-4db4e63fbd92.png)

11. When the user wants to close the window or the current tab in the browser to interrupt the order flow, the system shall show an alert message with the warning:
![image](https://user-images.githubusercontent.com/78092432/112531096-d9ee5300-8daf-11eb-89de-2d420d9848cc.png)

- If the user clicks on “Ні, видалити замовлення” button, the system shall erase all entered user data and close the window.
- If the user clicks on “Окей” button, the system shall save the order as a draft in the user’s cabinet and close the window. 

**Out of scope**
- Confirmation screen with related links (to user cabinet, to FAQ or useful info, etc), details why the payment is rejected or fails;
- Other payment methods.

**Epic**
UBS courier #2195

**Comment by alinant87** [comment]
Hi

**Comment by alinant87** [comment]
Hi

**Comment by alinant87** [comment]
Hi

**Comment by alinant87** [comment]
- [ ] Hi
