### ISSUE TITLE
[Change request to #2329] Certificate functionality

### ISSUE THREAD

**Issue by AnnaMix** [ita-social-projects/GreenCity#2481]
**Description of a Change request:**
Changed business logic for the certificate after the last customer review.  

**Reason for Change:**
The business logic on the processing of the certificate needs to be changed: if the certificate amount is greater than the amount of the selected service, the remaining certificate amount should not be converted into bonuses and it should be burned out. 
Examples of certificates - https://shop.nowaste.com.ua/sertificat 

**Acceptance Criteria**
1. When the user wants to use the certificate, the user shall enter eight numeric characters 0-9 of the certificate and click on the button “Активувати” and the system shall verify the certificate number by checking it in the database.
2. The system shall display the following messages under the certificate input field and make relevant changes in the order amount field in the following cases:

Certificate status in DB | Expected result | Expected message
-- | -- | --
**New** - the certificate is issued, is not expired, and was not applied yet  | The certificate matches with the database and the certificate is valid. The system accepts the certificate. The order amount is recalculated according to the discount. If the certificate discount is greater than the order amount,  the remaining certificate amount should be burned. | _Сертифiкат на cуму XXX грн активовано. Строк дії сертифікату - до YY.YY.YYYY_
**Used** - the certificate is issued and was already applied | The certificate matches with the database but it was already applied before, so the certificate is invalid. The system rejects it. The order amount is not changed. | _Сертифiкат вже було використано YY.YY.YYYY_
**Expired** - the certificate is issued, was not applied, but has an expired date | The certificate matches with the database but it has the expired date, so this certificate is invalid. The system rejects it. The order amount is not changed. | _Сертифікат не є дійсним. Строк дії сертифікату - до YY.YY.YYYY_ 

Here is the example when the certificate discount is greater than the order amount:
![image](https://user-images.githubusercontent.com/78092432/112623046-870aaf00-8e34-11eb-913d-1ff01fad8f45.png)

**Impact of Change** 
[US - Choose services and see total amount (Order form) #2196, US - Payment with certificate #2329] – certificate is no longer connected with bonuses and the remaining certificate amount should not be converted into bonuses.

**Epic**: UBS courier #2195

**Comment by kulaira** [comment]
[Certificates.postman_collection (2).json](https://github.com/ita-social-projects/GreenCity/files/15351613/Certificates.postman_collection.2.json)
