### ISSUE TITLE
Order confirmation page

### ISSUE THREAD

**Issue by AnnaMix** [ita-social-projects/GreenCity#2514]
As a user, I want to receive order confirmation, so that I can get the payment status of my order.

**Assumptions & Constraints**
N/A

**Preconditions**
- The registered user is logged in.
- The user chooses services and fulfills all required user data.
- The user makes the order payment via a selected method. 

**Business rules**
- The bank that receives the payment shall verify the payment status and redirect the user back to the UBS website with a confirmation of successful or failing payment.
- The bank that issued the debit/credit card is the only authority that can provide the user with any details about transactions.

### Acceptance Criteria
1. When the user completes the order payment via a selected method, the system shall redirect the user to the confirmation page of the USB website. 
2. The system shall automatically sequentially assign the order number. These numbers ascend incrementally and start from 1 (for example, №123, №124, №125, and so on). 
3. Regardless of the payment status, the structure of the page is the following: 
- the message to the user about the transaction (details in the AC - 04);
- additional information on the left side of the screen:

the first block **УБС сервіси**

Displayed text | Link attached 
--|--
“УБС сервіси”. Bold text, disabled. | No link attached
“Зробити інше замовлення”. Regular text, linked, disabled. | The link to the default order form. 
“Пластик Поштою”. Regular text, linked, disabled. | https://forms.gle/1JHwRFhKkovJwQ6z8
“Сайт Україна Без Сміття”. Regular text, linked, disabled. | https://nowaste.com.ua/
“Еко магазин”. Regular text, linked, disabled. | https://shop.nowaste.com.ua/

   the second block **Корисна інформація**

Displayed text | Link attached 
--|--
“Корисна інформація”. Bold text, disabled. | No link attached
“Інструкція з переробки сміття”. Regular text, linked, disabled. | https://nowaste.com.ua/sort-station/
“Відео про сортування і переробку ”. Regular text, linked, disabled. | https://www.youtube.com/channel/UChFVBZ_HcaQYiF-GcMHiCNA/videos

- the illustration for each status on the right side of the screen (please refer to the mockups); 
- in the bottom of the screen, the disabled text is displayed: _“Якщо у Вас виникнуть запитання, Ви можете зв’язатись з нами”_, where “зв’язатись з нами” is linked to the contact email address hello@nowaste.org.ua

4. Depending on the payment status of the order, the system shall display one of two possible confirmation messages: 

Confirmation screen type | Expected message for the user 
--|--
Successful payment | Disabled text: “Ваше замовлення прийнято (№XXX) Щиро дякуємо, що здійснюють контроль за відходами!”
Payment failed | Disabled text: “Упс, щось пішло не так… На жаль, Ваше замовлення №12345 не було оплачено. Спробуйте ще раз”

5. In case of the failed payment screen, the system shall additionally display the button “Повернутись до оплати”. When the user clicks on it, the system shall bring the user back to the tab “Підтвердження”, so the user is able to try to pay the order one more time. 
6. The mockups:
**successful payment**
![image](https://user-images.githubusercontent.com/78092432/113061687-20322080-91bb-11eb-9169-91f68da0d821.png)

**failed payment**
![image](https://user-images.githubusercontent.com/78092432/113061754-37710e00-91bb-11eb-9167-c4cd2d6bf668.png)

7. When the user wants to save the order without payment as a draft for the future, on the previous step “Підтвердження” the user shall click on the button “Відмінити” and select to save the order on the pop-up message. The system shall redirect the user to the order confirmation page. On that page the system shall display the banner with the text “Тепер ви можете знайти своє замовлення № XXX у Вашому особистому кабінеті та продовжити його оформлення в будь-який час”. Instead of the message about the payment, the system shall display the button “До особистого кабінету”. When the user clicks on it, the system shall redirect the user to the User's personal cabinet where the user shall be able to find the saved order. 
The mockup of the **saved unpaid order**:
![image](https://user-images.githubusercontent.com/78092432/113061825-54a5dc80-91bb-11eb-86f3-8ddc9c30cbed.png)

**Out of scope**
- The text “зв’язатись з нами” shall redirect to the Contact Us page with all the means of communication (email, Telegram, Vider, chat with UBS admin) 
- How the 3rd party payment system (Fondy, Liqpay, etc.) behaves when the payment is completed - should it redirect the user automatically back to UBS web-site or should the user click on any button on Liqpay/Fondy page to get back to UBS web-site to see the confirmation page? 

**Epic link**
UBS courier #2195

**Comment by YanaTarasiuk** [comment]
PAY ATTENTION, 
1. the text in AC4 should be changed. In case of successful payment the user should see the following message: "Дякуємо, що піклуєтеся про довкілля разом з нами!" instead of "Щиро дякуємо, що залишаєте контроль за відходами!" (Underlined in the attached screenshot)
2. AC3. the text “Якщо у Вас виникнуть запитання, Ви можете зв’язатись з нами” should be changed in to "Залишились питання? Наш чат підтримки — швидке і зручне рішення" (Underlined in the attached screenshot)
3. AC3. The text "Залишились питання? Наш чат підтримки — швидке і зручне рішення"  should not be linked.
<img width="837" alt="Image" src="https://github.com/user-attachments/assets/b2aad2f5-99fb-4d98-802f-e6b3651b1085" />
