### ISSUE TITLE
[UBS Admin Cabinet] Current orders view

### ISSUE THREAD

**Issue by Mariana-Khishchenko** [ita-social-projects/GreenCity#2536]
As an administrator, I want to be able to see a list of orders with their relative info in the admin cabinet so that I can track and manage orders.

**Preconditions:**

1. User is logged in as administrator. 
2. User navigated to the Orders tab

**Assumptions and constraints:**

1. Different Administrator types might have different rights sets in future
2. Each Administrator may change current orders view to fit their organization purpose
3. Some fields are interlinked with the order form, all rules based on form data are subjects to change

**Business rules:**
Only administrators with access should be able to view Admin Cabinet

### Acceptance criteria:
 Current orders view should contain table:

Name of the Column | Requirements | Comments
-- | -- | --
Checkbox | Each order record has a checkbox. By selecting a checkbox - a record is highlighted. Several records may be selected to be edited. By clicking on the checkbox in the column legend - all records are selected\deselected |  
Номер замовлення | 10 digit integer | could be updates from the customer as they’ve started to assign some order ID’s recently and will provide us updates regarding the logic of ID creation a bit later
Статус замовлення | Supported statuses: Сформовано; Оплачено; Узгодження; Підтверджено; На маршруті; Не вивезли; Виконано; Скасовано; Виконано/Не оплачено |
Дата замовлення | DD/MM/YYYY Date Received from order form |  The date when the order was created and status Сформовано was assigned
Дата оплати | DD/MM/YYYY Date Received from payment system |  The date when the order was paid and status Оплачено was assigned; If the payment confirmation was received in a form of a screen from the customer, the admin should add this date manually
Ім'я замовника | <Name> - 1-30 char <Lastname> - 1-30 char Special characters supported. Received from order form |  
Телефон замовника | 9 digits starting with:+380 Received from order form |  
Email замовника | Received from order form. |  
Ім’я отримувача | <Name> - 1-30 char<Lastname> - 1-30 char. Special characters supported. Received from order form in case ‘Отримувач інша людина’ option is chosen |  
Телефон отримувача | 9 digits starting with:+380 Received from order form in case ‘Отримувач інша людина’ option is chosen |  
Email отримувача | Received from the order form. |  
Кількість порушень клієнта | Quantity of users rule violations. | Violations should be displayed for a user who created an order, not the receiver; each number should be highlighted with a color marking (green, yellow, red) depending on customer status (separate story on violations)
Район | Automatically generated by the system based on user address and house number |  
Адреса (вулиця/дім/під'їзд) | Received from order form. |  
Коментар до адреси від клієнта | Max 170 characters (all types of characters) Received from order form. By default column width is set to show the first 15 characters; Admin may narrow column width below default value (it may be changed to hold less than 15 chars). When the full comment is more than 15 characters - 3 dots at the end of the comment appear. By clicking on 3 dots or Comment string - a popup window with the full comment is shown |  
Кіл-ть вторсировини (120л) | Values from 0-999 only. Received from order form. |  
Кіл-ть пакетів БО (120л) | Values from 0-999 only. Received from the order form. |  
Кіл-ть пакетів БО (20л) | Values from 0-999 only. Received from the order form. |  
Загальна сума замовлення | Order sum without discount. Float number with 2 digits. e.g (255.00 UAH). It can't be less than 0. No upper limit is set |  
Номер сертифікату (4 цифри тире 4 цифри) | Certificate number 8 digit number.e.g. 1234-1234. In case several certificates were used those are written in one line and are separated by ‘;’e.g: 2222-2222; 2222-2221 |  
Загальна знижка | Total sum of certificate and  bonuses (discount) used in UAH; Integer; Cannot be higher than ‘Загальна сума замовлення’ field |  
Сума до оплати | Order total - Certificate and bonuses. May not be less than 0. May be equal to 0. Float number with 2 digits.e.g (150.00 UAH) No upper limit |  
Коментар до замовлення від клієнта | max 170 characters (all types of characters) Received from order form. By default column width is set to show the first 15 characters; Admin may narrow column width below default value (it may be changed to hold less than 15 chars). When the full comment is more than 15 characters - 3 dots at the end of the comment appear. By clicking on 3 dots or Comment string - a popup window with the full comment is shown |  
Оплата | payment ID | this item should be extracted from the payment system response or in case the payment was added manually from the payment form (separate story)
Дата вивезення | No value until status is changed to: Узгодження; Підтверджено; На маршруті; Виконано; Виконано/Не оплачено | When Changing to any of aforementioned statuses - pop-up window is shown to select date
Час вивезення | No value until status is changed to: Оплачено; Узгодження; Підтверджено; На маршруті; Не вивезли; Виконано, Виконано/Не оплачено Receives value-range.e.g: 10:30 - 12:00; 13:20 - 19:00 |  
Номер замовлення з магазину | 10- digit number from Eco-StoreIn case several orders from Eco-Store is used those are written in one line and are separated by ‘;’e.g: 1234567890; 0123456789 |  
Станція приймання | Drop-down list of possible receiver stations | Станція - Саперно-Слобідська
Відповідальний менеджер | Pulls data from ‘Receiving station’ staff. Shows Last + First Name | Drop-down list of managers
Відповідальний логіст | Drop-down list of logists. Pulls data from ‘Receiving station’ staff |  
Відповідальний водій | Drop-down list of drivers. Pulls data from ‘Receiving station’ staff |  
Відповідальний штурман | Drop-down list of pilots. Pulls data from ‘Receiving station’ staff |  
Коментарі до замовлення | Empty by default. A comment may be added by clicking on a field near order. Max NONE characters (all types of characters) |  
</div></b>

1. Table should support width change of every column
2. Height of rows is constant and cannot be changed

**Mockup:**
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=14147%3A72013 

**Out of scope:**
Filter\Sorting functionality
Export to Excel
Auto-assignment of several roles
Violation rules
Manual payment confirmation

**Epic link**
E.g.: Epic #2195 [Epic](https://github.com/ita-social-projects/GreenCity/issues/2195)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by YanaTarasiuk** [comment]
<img width="383" alt="Screenshot 2025-01-06 at 17 19 25" src="https://github.com/user-attachments/assets/1a92f8a7-db0a-45c7-9d79-fddf5a604a3d" />

1. The text in the titles of the columns should be transferred into the next line, so admins can see the full title of the column.
2. The word "Number (Номер)" in the title should be substituted with the sign "№"

**NOT RELEVANT. Already done**
