### ISSUE TITLE
[Change request to #2200] Order form – Order summary

### ISSUE THREAD

**Issue by AnnaMix** [ita-social-projects/GreenCity#2541]
**Description of a Change request:**
UI improvements in the tab “Підтвердження”.

**Reason for Change:**
As a result of change requests for both previous tabs of the Order Form (change requests #2379, #2531 and #2533).

**Acceptance Criteria**
1. The user shall see the title of the service “УБС Кур’єр” in the top of the page. 
2. The user shall see the following tabs of the order steps: 
“1. Деталі замовлення – 2. Особисті дані – 3. Підтвердження”
The third tab “Підтвердження” is active. The previous tabs “Деталі замовлення” and “Особисті дані” are marked as done . 
![image](https://user-images.githubusercontent.com/78092432/113402094-2851b200-93ad-11eb-8d9e-7328947bf776.png)

3. Under the tabs, the user shall see the following blocks:
- “**Ваше замовлення**” with the summary of the selected services and cost per each service, order amount, certificate discount if any, bonus discount if any, and the total order amount to be paid; 
- “**Доставка з Еко магазину**” with the text “Номер вашого замовлення:  ХХХХХХХХХХ” (if only one shop order was mentioned) OR “Номери ваших замовлень:  12344445, 58001234” (if two or more shop orders were mentioned);
- “**Отримувач**” with the recipient personal data; 
- “**Адреса вивезення замовлених послуг**” with the recipient’s address and comments on the address if any; 
- “**Оплата**” which is described is the feature Payment (US #2477, US #2478).

4. All the fields are disabled and cannot be edited on this tab. 
![image](https://user-images.githubusercontent.com/78092432/113402298-7666b580-93ad-11eb-9174-71668bdcf6cd.png)

5. All the fields shall be displayed dynamically according to the entered data on both previous tabs of the Order Form.  
6. When the user clicks on the button “Назад” at the bottom of the page to change any order or personal data, the system shall save previously entered data in the order form and let the user go back to the previous tabs.
7. When the order amount equals 0 UAH, the system shall not display the block “Оплата”, so the user is able to click on the button “Замовити” and immediately gets a confirmation screen from the system about the successful order placement (please refer to US #2514 - Order confirmation page). 
8. When the user clicks on the button “Вiдмiнити” at the bottom of the page, the system shall save the order data and show a pop-up window with the warning message:
![image](https://user-images.githubusercontent.com/78092432/113402449-af068f00-93ad-11eb-8b7e-95b3ce43d641.png)
- If the user clicks on the button “Ні, видалити замовлення”, the system shall erase all entered user data and close the window;
- If the user clicks on the button“Окей”, the system shall save the order as a draft in the User Cabinet and redirect the user to the order confirmation page (please refer to the AC-07 in US-#2514).

**Impact of Change**
US #2200 - Review order summary and submit order.

**Epic:**
UBS courier #2195

**Comment by MyroslavaVynokur** [comment]
LiqPay payment works, but we have a problem on LiqPay servers (payment is not set as successful as we need Private Entrepreneur account opened in Privat Bank,  so we can't test it) - move to status blocked
