### ISSUE TITLE
Fix bug /favorite_place/{placeId}

### ISSUE THREAD

**Issue by ZaharVeremchuk** [ita-social-projects/GreenCity#2545]
Description: When you delete id  which is not in database, application send you 500 error ;
Decision: It should send you 404 error message;
![image](https://user-images.githubusercontent.com/45737995/114191654-527b1500-9955-11eb-9f17-6ba57ebc9e49.png)
![image](https://user-images.githubusercontent.com/45737995/114191963-a2f27280-9955-11eb-8535-f65f59b2226e.png)

**Comment by irynamykhailevych** [comment]
404 response is shown
