### ISSUE TITLE
Fix bug file-service-controller

### ISSUE THREAD

**Issue by ZaharVeremchuk** [ita-social-projects/GreenCity#2547]
When you send image in string (like link). It send 500.
![image](https://user-images.githubusercontent.com/45737995/113425341-5c8f9780-93da-11eb-99e2-063f622fbea0.png).
![image](https://user-images.githubusercontent.com/45737995/113425367-64e7d280-93da-11eb-9f36-1e4836d5a51d.png).
Also mapping  on controller methods should change.

**Comment by LiliiaPalii** [comment]
When you send image in string (link), you get response 400.
![Image1](https://user-images.githubusercontent.com/55461895/121143179-710e6700-c845-11eb-85ad-e112429031a1.png)
![Image2](https://user-images.githubusercontent.com/55461895/121143182-71a6fd80-c845-11eb-8a8d-3244752f54b0.png)
