### ISSUE TITLE
[Habit]  hebits are added to the list of templates in reverse order

### ISSUE THREAD

**Issue by idzhersh** [ita-social-projects/GreenCity#2550]
**Environment:** Windows 10 Pro 64bit, Версія 89.0.4389.90 (Official Build) (64-bit).
Reproducible: always.
Build found: 18.03.21

**Steps to reproduce**
1 Sign in with User on-page https://ita-social-projects.github.io/GreenCityClient/
2. Click on My habits tab
3. Click on Add new habit button 
4. Next, when you scroll through the list of habits, they are added in reverse order

**Expected result:**Habit cards should be added in the correct order

**Comment by mocharna** [comment]
Habit cards are displayed in the wrong order (first are displayed cards, which were added earlier).
