### ISSUE TITLE
[UBS courier] The 'Далі' button on the 'Деталі замовлення' page does not work when the user enters valid data

### ISSUE THREAD

**Issue by OksanaKukalets** [ita-social-projects/GreenCity#2598]
**Environment:** Windows 10, Google Chrome 89.0.4389.114.
**Reproducible:** always
**Build found:** 12.04.2021

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in to GreenCity as a User
3. Click on the 'UBS' tab

**Steps to reproduce**
1. Put values into 'Безнадійний одяг 120л' or 'Безадійний одяг 20л' or 'Вторсировина' fields ('Сума замовлення' is >= 500грн)
2. Click on the 'Далі' button.

**Actual result**
The 'Далі' button does not work.

**Expected result**
User shall be redirected to the next page of the order form “Особисті дані”. The system shall save the entered data so the user is able to edit any data by clicking on “Назад” button from the page “Особисті дані”.

**User story and test case links**
E.g.: "User story #2196 
[Test case](https://jira.softserve.academy/browse/GC-1942)"

**Comment by nazarhlyvka** [comment]
All works properly.
