### ISSUE TITLE
Access to cafe detail information

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#26]
As an unregistered user I want to be able to access to the detail information about a place on the map so that I can choose the place to go.

**Mockups:**
![image](https://user-images.githubusercontent.com/53810790/62904792-63cee100-bd70-11e9-990d-f7e0b2df3f8a.png)

**Acceptance criteria:**
1. WHEN Unregistered or Registered user clicks on the one of test places, THEN he/she should be able to see small pop-up with detailed info about place (test data):
a. Name
b. Address (City, Street, Number of building)
c. Working times (day; hh:mm-hh:mm)
d. Discount
e. Feedback
f. Unactive star-icon in order to add this place to Favorites (as Registered user)

**Assumptions and Constraints:**
This User story is related to user story #20

**Comment by rsyvulko** [comment]
Not relevant.
