### ISSUE TITLE
[UBS Admin Cabinet] Filtering

### ISSUE THREAD

**Issue by Mariana-Khishchenko** [ita-social-projects/GreenCity#2600]
As an administrator, I want to be able to filter orders by different criteria in the admin cabinet so that I can narrow down the search of required order items.

**Assumptions & Constraints**
1.  

**Preconditions**
1. User is logged in as administrator. 
2. User navigates to the Orders tab
3. At least 2 different orders are added

**Business rules**
1. n/a

### Acceptance Criteria
1.
  | Requirements | Comments
-- | -- | --
Search bar | Search provides filtering of all entities from the table e.g: When typing ‘10.10’ it searches through all columns of the table and filters orders that fall under this criteria, not showing orders that have no search overlaps. There is no search term confirmation - a table is filtered in real-time | Mockup to be used as a reference on placement

![image](https://user-images.githubusercontent.com/73824853/114440601-0210eb00-9bd3-11eb-8a2a-2ae063fa8de6.png)

Table filters  | Requirements | Comments
-- | -- | --
2 **<Статус замовлення>** | Filter icon is shown to the right of the column:  Clicking on the icon - Pop-up with checkboxes near supported statuses are shown. Checkboxes are selected by default. Deselecting checkbox - hides all orders with <status> type from table | |
 3 **<Кількість порушень клієнта>** |Filtering is not supported for this field | |
4 **<Оплата>** | Clicking on the icon - Pop-up with checkboxes <Не оплачені> and <Оплачені> is shown. Checkboxes are selected by default. Deselecting checkbox - hides all orders with payment ID or <No Receipt> from the table.||
 5 **<Станція приймання>**| Clicking on the icon - Pop-up with checkboxes near each receiving station is shown. Checkboxes are selected by default. Deselecting checkbox - hides all orders from deselected receiving station from the table. | |
6 **<Дата замовлення>** | In range - when this option is chosen the user should be able to select 2 dates(from, to). | |
7 **<Дата Оплати>** | Clicking on the icon a user must have a possibility to choose next options: Equals - when this option is chosen the user should be able to select a specific date on which filtering will be performed. In range - when this option is chosen the user should be able to select 2 dates(from, to) | |
8 **<Район>**|Filter icon is shown to the right of the column:  Clicking on the icon - Pop-up with checkboxes near supported districts are shown. Checkboxes are selected by default. Deselecting checkbox - hides all orders with the district from table | |
9. **‘Вид таблиці’ button**  
Pop-up with checkboxes near each <column name> is shown. Checkboxes are selected by default. Deselecting checkbox - hides deselected column from the table 

![image](https://user-images.githubusercontent.com/73824853/114440736-28cf2180-9bd3-11eb-852b-6dc2a4f603be.png)

**Out of scope**
Edit filters pop-up

**Epic link**
E.g.: Epic #2195 
**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by ViktoriyaRyazhska** [comment]
Filter will be implemented in #3300
