### ISSUE TITLE
BUG (#_) [ADMIN] Filter doesn't work  by date of registration in /user/filter Filter all user by search criteria

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#261]
**Description:**

**Steps to reproduce:**
1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#...
2. Choose User Controller
3. Choose /user/filter Filter all user by search criteria
4. Click 'Try it out' button
5. Enter valid data into 'searchReg' (e.g. { 'searchReg': '2019-08-30 09:30'}. A user with such a registration date is present)
6. Click 'Execute' button
**Actual result:**
{
  "page": [],
  "totalElements": 0,
  "currentPage": 0
}
**Expected result:**
There is ' 200 Code" and all users with the login date entered

**Comment by erikgajdos1997** [comment]
Hello, can I work on this? Could you assign me to this?

**Comment by RostyslavKhasanov** [comment]
Solved, and was updated date format, example "2019-09-17 10:15".

**Comment by Bastarn78** [comment]
> Solved, and was updated date format, example

Doesn't work. example "2019-08-30 09:30"
