### ISSUE TITLE
Fix bug on user controller

### ISSUE THREAD

**Issue by ZaharVeremchuk** [ita-social-projects/GreenCity#2627]
Description: When user update him profile and press update ,it send 500 error.
![image](https://user-images.githubusercontent.com/45737995/115020646-8e692980-9ec3-11eb-891e-bab019e390e8.png)

**Comment by SerhiiStarshoi** [comment]
![photo_2021-06-04 23 53 57](https://user-images.githubusercontent.com/32453285/120861609-3def7d80-c590-11eb-9825-49d29e38fd3b.jpeg)
sends 200 code error
