### ISSUE TITLE
[EDIT ECO NEWS] Fix the number of tags

### ISSUE THREAD

**Issue by JimHolman1199** [ita-social-projects/GreenCity#2631]
There is something wrong with the number of tags when trying to edit created News

<img width="847" alt="Screenshot 2021-04-15 at 19 15 52" src="https://user-images.githubusercontent.com/46226026/115053343-b5395700-9ee7-11eb-8751-44fe06c2df25.png">

**Comment by KirillAbramo** [comment]
We need to recieve from back-end active tags in news that is going to be edited (get econews by id) in a way of array with english, ukrainian, russian language options, to be able to mach it on front-end. Like this:  ["events", "події", "cобытия"]. Not like now: ["events"].
![image](https://user-images.githubusercontent.com/58560218/116111704-93965780-a6bf-11eb-8e61-9d0957906e8e.png)
