### ISSUE TITLE
[Edit profile] The error message is not shown after uploading oversize or incorrect type of picture

### ISSUE THREAD

**Issue by irynamykhailevych** [ita-social-projects/GreenCity#2633]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 16.04.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome         
Edit profile page is opened.

**Steps to reproduce**
1. Click on the 'Edit a photo' icon.
2. Click on the 'Upload new photo' button.
3. Select **PNG or JPEG file** with size **more 10Mb** and select any type of file **except PNG or JPEG** with **less than 10Mb**.
4. Click on the 'Save photo' button.

**Actual result**
The error message is not shown after uploading oversize or incorrect type of picture

**Expected result**
The error messages are shown:
EN “Download PNG or JPEG only. File size should be less than 10Mb"
UA "Завантажуйте лише PNG або JPEG. Розмір файлу не повинен перевищувати 10Mb"
RU "Загружайте только PNG или JPEG. Размер файла не должен привышать 10Mb”

**User story and test case links**
User story #1010 
[Test case] https://jira.softserve.academy/browse/GC-1548

![photo bug](https://user-images.githubusercontent.com/82223583/115079176-761bfd80-9f09-11eb-86f1-64b16e39313e.jpg)

**Comment by MyroslavaVynokur** [comment]
Verified - done
