### ISSUE TITLE
[Edit profile, upload new photo]  The photo with an invalid size is accepted  

### ISSUE THREAD

**Issue by ViktorRachynskyi** [ita-social-projects/GreenCity#2635]
Environment: OS Windows 10 x64, Google Chrome 89.0.4389.128
Reproducible: always
Build found: 16.04.2021

Preconditions:

- The photo with a size of more than 10 Mb in PNG or JPEG format
- User should be logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome                                                          (e.g : login: green.city.test2@gmail.com password: Green.city#500)
- Edit photo popup should be opened

Steps to reproduce:

1. Click on the 'Upload new photo' button
2. Select an image with an invalid size from the computer file system and load it
3. Click on the 'Save photo' button
4. Pay attention to the actual photo in the profile

Actual result:

1) The photo is uploaded after selecting the photo with an invalid size of more than 10 Mb
![image](https://user-images.githubusercontent.com/79053863/115108060-047a9880-9f77-11eb-988b-090764b49d9a.png)
![2](https://user-images.githubusercontent.com/79053863/115108259-1f99d800-9f78-11eb-9c92-f162218e9d96.png)

2) The error message 'Download PNG or JPG only. File size should be less than 10 Mb' is not displayed in red under the image
![image](https://user-images.githubusercontent.com/79053863/115108039-f3318c00-9f76-11eb-9e71-7bdd43826f82.png)

Expected result:

1) The old photo is displayed after uploading a photo with an invalid size of more than 10 Mb                                                        ![image](https://user-images.githubusercontent.com/79053863/115108105-515e6f00-9f77-11eb-8073-2208062acafe.png)

2) The error message 'Download PNG or JPG only. File size should be less than 10 Mb' is displayed in red under the image
![image](https://user-images.githubusercontent.com/79053863/115108077-31c74680-9f77-11eb-8373-17974d6e55d8.png)

User story #1006 
[Test case] https://jira.softserve.academy/browse/GC-1569
                 https://jira.softserve.academy/browse/GC-1572 
                 https://jira.softserve.academy/browse/GC-1573

**Comment by Bishko86** [comment]
The same bag already exists **[Edit profile] The error message is not shown after uploading oversize or incorrect type of picture #2633**

**Comment by MyroslavaVynokur** [comment]
Verified - done
