### ISSUE TITLE
[Edit profile] Upload picture pop-up is cropped

### ISSUE THREAD

**Issue by AlexaEskina** [ita-social-projects/GreenCity#2642]
**Environment:** Windows 10, Google Chrome v.89.0.4389.114
**Reproducible:** always
**Build found:** 8f348b1 (18.04.2021)

**Preconditions**
The User is Logged with actual credential  at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**
1. Open  'UBS' page
2.  Click  on 'User name' (on the top right side of the page) -> on settings 
2. 'Edit profile' page is opened
3. Click on profile avatar 'edit' icon

**Actual result**
Pop-up "Do you want to change your profile picture?" is cropped

**Expected result**
Pop-up "Do you want to change your profile picture?" is not cropped

![Screenshot 2021-04-17 232116](https://user-images.githubusercontent.com/75045081/115153313-f499ac00-a07d-11eb-89db-cd075d44aba2.png)

**Comment by andkuzma** [comment]
Pop-up "Do you want to change your profile picture?" is not cropped 
![image](https://user-images.githubusercontent.com/51418233/129194694-7edf59c2-92fc-43af-a048-da47bcb71b57.png)

**Comment by JimHolman1199** [comment]
please check it again !

**Comment by Ol98** [comment]
Done!
