### ISSUE TITLE
[Edit profile, edit photo] The uploading page isn't displayed after clicking on the 'Upload new photo' button

### ISSUE THREAD

**Issue by ViktorRachynskyi** [ita-social-projects/GreenCity#2645]
Environment: OS Windows 10 x64, Google Chrome 89.0.4389.128
Reproducible: always
Build found: 16.04.2021

Description:

The uploading page isn't implemented                                                                                                                           
Requirements describe in User Story's Change request which is linked to this bug report

Preconditions:

1. The User should be logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome

Steps to reproduce:

1. Click on the 'My habits' tab
2. Click on the 'Edit' button on the Profile section
3. Click on the 'Edit photo' button
4. Click on the 'Upload new photo' button
5. Pay attention to that file system of the user's computer opens instead of the uploading page

Actual result:
The file system of the user's computer is opened 
![image](https://user-images.githubusercontent.com/79053863/115225157-69b8c000-a116-11eb-995c-587dcd9fac13.png)

Expected result:
The uploading page is opened
![image](https://user-images.githubusercontent.com/79053863/115225352-a7b5e400-a116-11eb-8373-15c44f3f81df.png)

User story #1006 
[Test case] 
https://jira.softserve.academy/browse/GC-1566
https://jira.softserve.academy/browse/GC-1567
https://jira.softserve.academy/browse/GC-1580
https://jira.softserve.academy/browse/GC-1581
https://jira.softserve.academy/browse/GC-1591
https://jira.softserve.academy/browse/GC-1593

**Comment by Ol98** [comment]
The bug is not fixed. The same problem appears.
