### ISSUE TITLE
[Edit profile] 'Save' button should be disabled by default if user doesn't change any info

### ISSUE THREAD

**Issue by AlexaEskina** [ita-social-projects/GreenCity#2649]
**Environment:** Windows 10, Google Chrome v.89.0.4389.114
**Reproducible:** always
**Build found:** 19.04.2021

**Preconditions**
The User is Logged with actual credential at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**
1. Go to 'Edit profile'
2. Verify 'Save' button

**Actual result**
'Save' button is enabled 

**Expected result**
 'Save' button should be disabled while the user doesn't make any changes on the page

**Comment by Halchysko** [comment]
Fixing of this defect caused the re-opening of defect #2629
