### ISSUE TITLE
[Controller] For work with order adresses

### ISSUE THREAD

**Issue by ZaharVeremchuk** [ita-social-projects/GreenCity#2652]
Description: User should have possibility add, update, delete him address and get all him address.

Functional Requirements:

[1] When user add him new address, address should be save into database and it should have column actual equal true, but another him addreses should have  column actual false. Controller should return all him addresses. In database this address should be with the status NEW.

Example of use controller for check this requirment :
[1.1] Id should be 0 ;
![image](https://user-images.githubusercontent.com/45737995/117814316-d124e400-b26c-11eb-92d4-cd4f2f206c81.png)

[2] When user update him address. 
[Check] Address should have column actual equal true, but another user addreses should have column actual false. Controller should return all him addresses. In database this address should be with the status NEW into address column.

[2.1] Id should id of created user address ;

![image](https://user-images.githubusercontent.com/45737995/117814866-88b9f600-b26d-11eb-8bbb-1f17aa49b6f0.png)

[3] User should delete address by using id of user address.
[Check]: If address have status DELETED into database (greeencity ubs) in address column.

[3.1] Input id of exist user address ;

![image](https://user-images.githubusercontent.com/45737995/117815110-cc146480-b26d-11eb-8d71-d2742929a598.png)

[4] When user make order and want to update him address.
[Check]: After make order address should have status IN_ORDER (into address column). 
[Check] When user updated address that have status IN_ORDER , address should change status on NEW.

[4.1] Create certidicate

![image](https://user-images.githubusercontent.com/45737995/117817069-e5b6ab80-b26f-11eb-9e74-9b048d886b83.png)

[4.2] Add address

![image](https://user-images.githubusercontent.com/45737995/117817180-0252e380-b270-11eb-8ff5-9a343e7dc376.png)

[4.3] Make order, input inside json with certificate id and created address id.

![image](https://user-images.githubusercontent.com/45737995/117817511-58278b80-b270-11eb-9537-4ad1e061d77f.png)

[4.4]Try to updated this address

![image](https://user-images.githubusercontent.com/45737995/117817735-915ffb80-b270-11eb-8eeb-d1d7579399a9.png)

**Comment by MyroslavaVynokur** [comment]
Controllers 'Save order address', 'Delete order address', 'Process user order' work as expected
<img width="887" alt="Screenshot 2021-12-01 at 22 17 22" src="https://user-images.githubusercontent.com/34717146/144307428-16cd4ff3-fa0f-4caf-bf14-e7a90e46bf25.png">

<img width="865" alt="Screenshot 2021-12-01 at 22 17 35" src="https://user-images.githubusercontent.com/34717146/144307456-728edb89-d630-4fe2-8091-b4183cfaaa68.png">

<img width="885" alt="Screenshot 2021-12-01 at 22 17 58" src="https://user-images.githubusercontent.com/34717146/144307498-b7fb99ec-14df-4a8f-bc77-8a1e131d8b4b.png">

<img width="894" alt="Screenshot 2021-12-01 at 22 18 08" src="https://user-images.githubusercontent.com/34717146/144307524-d633e0cd-f8ff-4740-aa8d-59efddea6352.png">
