### ISSUE TITLE
[Edit Profile] The view of the pictogram 'Edit Picture' button is incorrect 

### ISSUE THREAD

**Issue by Uliana-Bigun** [ita-social-projects/GreenCity#2655]
**Environment:** OS Windows 10 Pro, browser - Google Chrome 89.0.4389.114 (64-bit) 

**Reproducible:** always

**Build found:** last commit from https://ita-social-projects.github.io/GreenCityClient/#/profile/302/edit

**Steps to reproduce**
1. Log in 
2. 'Edit Profile' is opened 
3. Go to 'My habits' > Edit Profile (https://ita-social-projects.github.io/GreenCityClient/#/profile/302/edit\))
4. Click on 'Edit Picture' button

**Actual result**
1. The view of the pictogram 'Edit Picture' button is incorrect (see the attachment )  
![Screenshot_7](https://user-images.githubusercontent.com/82227122/115116902-c1371e80-9fa4-11eb-8f4a-93266c34d276.png)

**Expected result**
1.The view of the 'Edit Picture' button is correct according to the mock-up (see the attachment )  
![Screenshot_8](https://user-images.githubusercontent.com/82227122/115116940-e6c42800-9fa4-11eb-970a-562ecbdbf5dd.png)

**User story and test case links**
User story #1011
[Test case GC-1501] https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je%3Azephyr-tests-page#test-cycles-tab

**Comment by Uliana-Bigun** [comment]
CHANGE REQUEST
The mock-up is updated. 

Actual result
1.  The view of the pictogram 'Edit Picture' button is incorrect (see the attachment 1)

Expected result
1. The view of the 'Edit Picture' button is correct according to the mock-up (see the attachment )(see the attachment 2)

![Screenshot_2](https://user-images.githubusercontent.com/82227122/116360256-6903e600-a808-11eb-9db7-bc1031eaab96.png)

![Screenshot_1](https://user-images.githubusercontent.com/82227122/116360293-715c2100-a808-11eb-9481-f1f9277e8c0a.png)

**Comment by Edw1x** [comment]
Can you add a link to the Figma mockup?
