### ISSUE TITLE
[Create news] After changing the language, the tags aren't translated correctly or the process of translating takes too long

### ISSUE THREAD

**Issue by bilobramv** [ita-social-projects/GreenCity#2658]
**Environment:** Windows 10 x64, Google Chrome 89.0.4389.128 (64-bit)
**Reproducible:** rarely

**Steps to reproduce**

1. Go to "https://ita-social-projects.github.io/GreenCityClient/#/"
2. Log in 
3. Go to 'Eco news' page
4. Click on 'Create news' button
5. Click on 'Language Dropdown' button
6. Choose a language different from default 

**Actual result**
Tags aren't translated correctly or the process of translating takes too long
![error](https://user-images.githubusercontent.com/80643382/115581532-c069f980-a2d0-11eb-9c34-3c73c282e62e.png)

**Expected result**
After changing the language, the tags are translated correctly and immediately

**User story and test case links**
Create News functionality #525

**Comment by dmytro-kryvyi** [comment]
Not reproduce
