### ISSUE TITLE
[Edit News] Tags are duplicated and the elect "Education" tag is displayed with an error

### ISSUE THREAD

**Issue by TimeKenosh** [ita-social-projects/GreenCity#2662]
Environment: Windows 10, browser: Google Chrome, version 89.0.4389.128.
Reproducible: always.

**Preconditions**
Create the news:
Go to "https://ita-social-projects.github.io/GreenCityClient/#/"
Log in
Go to 'Eco news' page
Click on 'Create news' button
Set valid title
Set valid content
Click "Education" tag
Click "Publish" button

**Steps to reproduce**
1. Click on the news you created
2. Click "Edit news" button

**Actual result**
![image](https://user-images.githubusercontent.com/79340430/115687845-3fa80d80-a363-11eb-8138-3d6b847d3580.png)

**Expected result**
![image](https://user-images.githubusercontent.com/79340430/115687902-4df62980-a363-11eb-88c8-d460e6fb484b.png)

**User story and test case links**
Edit News | #660

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("medium:"), Type ("UI, "Functional").

**Comment by dmytro-kryvyi** [comment]
Not reproduce

**Comment by snezhanapravdyuk** [comment]
News created with "Education" tag.
When editing "Education" tag does not show as selected.

![news](https://github.com/ita-social-projects/GreenCity/assets/165433958/8f3c1729-6dad-4b77-a1de-2d9b3c53c205)
