### ISSUE TITLE
[Edit Profile] The alignment of the controls is not the same as on the mock-up 'Cancel' pop-up on different screen resolutions.

### ISSUE THREAD

**Issue by TetianaD** [ita-social-projects/GreenCity#2673]
**Environment:** macOS Big Sur 11.2.3, Google Chrome Version 90.0.4430.85 (x86_64)
**Reproducible:** always
**Build found:** 23.04.2021

**Preconditions**
The User is Logged in with the actual credential at the https://ita-social-projects.github.io/GreenCityClient/.
The URL 'https://ita-social-projects.github.io/GreenCityClient/#/profile/' is opened.

**Steps to reproduce**
1. Select the localization at the top right side of the page (e.g. En/Ua/Ru)
2. Click on the 'Edit' icon at the top right side of the profile section.
3. Click on the 'Cancel' button at the bottom of the page.
4. Press F12 and change the resolution for:
- <576 (e.g. 320 px/390 px/575 px)
- >= 576 px (e.g. 576 px/600 px/767 px)
- >= 768 px (e.g. 768 px/800 px/991 px)
- >= 992 px (e.g. 992 px/1024 px/1199 px)
- >=1200 рх (e.g. 1200 px/1366 px)

**Actual result**
The alignment of the controls is not the same as on the mock-up 'Cancel' pop-up on different screen resolutions.

**Expected result**
The alignment of the controls is the same as on the mock-up 'Cancel' pop-up on different screen resolutions.

**User story and test case links**
User story Edit Profile: Cancel functionality #1009
[Test case GC-1538](https://jira.softserve.academy/browse/GC-1538)

**Comment by Flash5482** [comment]
Checked again this bug because I can't reproduce it
