### ISSUE TITLE
[Edit profile] Incorrect name displayed in top panel after changing user name

### ISSUE THREAD

**Issue by AlexaEskina** [ita-social-projects/GreenCity#2677]
**Environment:** Windows 10, Google Chrome v.90.0.4430.85
**Reproducible:** always
**Build found:**26.04.2021

**Preconditions**
The User is Logged with actual credential at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**

1. Go to 'Edit profile' page
2. Change name in 'Name' field
3. Click on 'Save' button
4. Go to 'My habits' page
5. Verify user name

**Actual result**
Incorrect user name displays in the top panel

**Expected result**
User name should be same as user name in top panel 

![Screenshot 2021-04-26 153615](https://user-images.githubusercontent.com/75045081/116083486-50c78600-a6a5-11eb-870f-c3a55cb832e8.png)

**Comment by Anastasiia-Hevchuk** [comment]
No bugs found. After editing, the name changes successfully.
