### ISSUE TITLE
[Forgot password] The 'or sign in with' text is shown insted of the 'or' text

### ISSUE THREAD

**Issue by ViktorRachynskyi** [ita-social-projects/GreenCity#2685]
Environment: OS Windows 10 x64, Google Chrome 89.0.4389.128
Reproducible: always
Build found: 27.04.2021

Description:
The 'sign in with' text item is repeated. It looks ridiculous. 

Steps to reproduce: 

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Click on the 'Sign in' button
3. Click on the 'Forgot password?' button
4. Pay attention to text that duplicate

Actual result:
The 'or sign in with' text is shown between two buttons
![bug1](https://user-images.githubusercontent.com/79053863/116275342-374d3980-a78c-11eb-9653-99212483d487.png)

Expected result:
The 'or' text is shown between two buttons
![bug1](https://user-images.githubusercontent.com/79053863/116275518-6499e780-a78c-11eb-8239-65e46208b2f9.png)

[Test case] https://jira.softserve.academy/browse/GC-518

**Comment by SerhiiStarshoi** [comment]
The 'or' text is shown between two buttons

<img width="952" alt="image" src="https://user-images.githubusercontent.com/32453285/120886367-3d89cd80-c5f6-11eb-905d-85c557ba6e54.png">
