### ISSUE TITLE
[Restore password] The wrong text message is shown on the 'Restore password' link in the received email message when En/Ua/Ru language is set on the site

### ISSUE THREAD

**Issue by ViktorRachynskyi** [ita-social-projects/GreenCity#2694]
Environment: OS Windows 10 x64, Google Chrome 89.0.4389.128
Reproducible: always
Build found: 29.04.2021

Pre-conditions:

1) The User is created on the GreenCity
2) Go to https://ita-social-projects.github.io/GreenCityClient/#/ without Log in

Steps to reproduce:

1) Select En/Ua/Ru language in the header
2) Click on the 'Sign in' button in the header
3) Click on the 'Forgot password?' button
4) Enter the email of the created user
5) Click on the 'Submit a login link' button
6) Open the email box of the user and open received mail 
7) Pay attention to the text of the link

Actual result:

The 'Restore'/'Відновлення'/'Востановление' text message is shown on the link in the received email message when En/Ua/Ru language is set on the site
![bug4](https://user-images.githubusercontent.com/79053863/116473398-cab36700-a87f-11eb-9660-c07a8552a168.png)

Expected result:

The 'Change password'/'Змінити пароль'/'Сменить пароль' text message is shown on the link in the received email message when En/Ua/Ru language is set on the site

**Comment by Ol98** [comment]
Done!
