### ISSUE TITLE
[Edit profile, Edit picture] The elements have different sizes than on mockups

### ISSUE THREAD

**Issue by ViktorRachynskyi** [ita-social-projects/GreenCity#2698]
Environment: OS Windows 10 x64, Google Chrome 89.0.4389.128
Reproducible: always
Build found: 29.04.2021

Pre-conditions:

1) The User should be logged using Google Account with a photo in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome

Steps to reproduce:

1) Click on the 'My habits' tab
2) Click on the 'Edit' icon at the top right side of the profile section
3) Click on the 'Edit photo' button
4) Pay attention to the alignment of controls

Actual result:
The elements have different sizes than on mockups (headline - 418.92x28 , 'Cancel' button - 100.47x40 , 'Delete photo' button - 146.89x42 , 'Upload new photo' button - 188.66x42 )
![ui_1](https://user-images.githubusercontent.com/79053863/116538305-084fd880-a8f0-11eb-87e4-390adc1cad39.png)
![ui_2](https://user-images.githubusercontent.com/79053863/116538335-10a81380-a8f0-11eb-8658-0d1f8f315300.png)
![ui_3](https://user-images.githubusercontent.com/79053863/116538346-1271d700-a8f0-11eb-8011-c153f84e16ea.png)
![ui_4](https://user-images.githubusercontent.com/79053863/116538356-14d43100-a8f0-11eb-8116-7701516843c1.png)

Expected result:
The elements have the same sizes as on mockups (headline - 519x28 , 'Cancel' button - 98x40 , 'Delete photo' button - 143x42 , 'Upload new photo' button - 181x40 )
![ui_1_1](https://user-images.githubusercontent.com/79053863/116538427-2fa6a580-a8f0-11eb-8b87-50771bf00cf3.png)
![ui_2_2](https://user-images.githubusercontent.com/79053863/116538434-30d7d280-a8f0-11eb-9622-802e0b927349.png)
![ui_3_3](https://user-images.githubusercontent.com/79053863/116538444-3503f000-a8f0-11eb-8382-f326f30c4209.png)
![ui_4_4](https://user-images.githubusercontent.com/79053863/116538449-36cdb380-a8f0-11eb-8cd9-30e680fe811d.png)

User story #1006 
[Test case] https://jira.softserve.academy/browse/GC-1561

**Comment by SerhiiStarshoi** [comment]
![Uploading image.png…]()
