### ISSUE TITLE
[My habits] Wrong presentation of the button 'Edit profile'. 

### ISSUE THREAD

**Issue by mocharna** [ita-social-projects/GreenCity#2699]
**Environment**: OS: Windows 10, Browser: Google Chrome 89.0.4389.114
**Reproducible**: Always
**Build found**: 29.04.2021

**Steps to reproduce**
1. User should be logged in Green City 'https://ita-social-projects.github.io/GreenCityClient/#/welcome';
2. Go to 'My habits' page;

**Actual result**
![1](https://user-images.githubusercontent.com/82234978/116541388-130c6c80-a8f4-11eb-9fbc-4742a26a81eb.png)

**Expected result**
![2](https://user-images.githubusercontent.com/82234978/116541553-40f1b100-a8f4-11eb-91c5-2abf45a20621.png)

**Comment by paslavskyi9roman** [comment]
https://www.figma.com/file/K5qc43VjSkWVz8mobuovxs/ITA-Greencity?node-id=101%3A2508 
Due to the Figma mock-up, the icon is correct

**Comment by TetianaD** [comment]
Still wrong presentation of the button 'Edit profile'.
<img width="246" alt="Screenshot 2021-05-19 at 17 34 47" src="https://user-images.githubusercontent.com/10379945/118832187-15e1f800-b8c9-11eb-9803-27ac65ef1d52.png">
