### ISSUE TITLE
Moderate registered users 

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#27]
As an admin I want to be able to moderate registered users.

**Mockups:**

**Acceptance Criteria:**
1. Provided admin navigates to "Users" tab in the admin page, system shall display the list of all registered users.

2. The list shall be in a form of a table and shall contain the following columns:
a. E-mail address
b. First name
c. Last name
d. Date of registration
e. Actions

3. Actions column shall contain the following buttons:
a. "Block"
b. "Make Admin"
c. "Deactivate"
d. "Unblock"
e. "Activate"

4. Records in the list shall bu automatically sorted in alphabetical order (A-Z) by the E-mail address column.

*5. The table can have a maximum number of ??TBD?? record rows on a page. There shall not be a scroll.
6. Provided there are more record rows that can fit the page, system shall display a page counter and buttons "Previous", "Next" at the bottom of the page.

**Assumptions and Constraints:**

**TBD:**

**Comment by rsyvulko** [comment]
Not relevant.
