### ISSUE TITLE
[Footer] Wrong size of 'Eco news' link, Twitter icon and 'Follow us' label with icons of social networks on the footer

### ISSUE THREAD

**Issue by Halchysko** [ita-social-projects/GreenCity#2707]
**Environment:** Windows 8.1, Google Chrome 90.0.4430.85
**Reproducible:** always
**Build found:** 27.04.2021

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in as an existing user
3. Scroll down to the footer of the page

**Actual result**
1. The size of the link 'Eco news' is 97.05x17
2. The size of the Twitter icon is 16x14
3. The size of the "Follow us" label and icons is 160.36x16

**Expected result**
According to mockups
1. The size of the link 'Eco news' is 60x20
2. The size of the Twitter icon is 15x12.19
3. The size of the "Follow us" label and icons of social networks is 154x20

**Attachments**
1. 'Eco news' actual result
![Actual Eco news](https://user-images.githubusercontent.com/82100741/116678436-f9c9f580-a9b1-11eb-94d5-47c86a4105fa.jpg)

'Eco news' expected
![Econews](https://user-images.githubusercontent.com/82100741/116678345-de5eea80-a9b1-11eb-83e2-4ef10ae36684.jpg)

2. Twitter icon actual result
![Actual Twitter ](https://user-images.githubusercontent.com/82100741/116678534-19f9b480-a9b2-11eb-9348-c76343118359.jpg)

Twitter icon expected result
![Twitter](https://user-images.githubusercontent.com/82100741/116678561-2251ef80-a9b2-11eb-9710-7353dc27b36c.jpg)

3. 'Follow us' label and icons of the social networks actual result
![Actual Follow us](https://user-images.githubusercontent.com/82100741/116678613-2ed64800-a9b2-11eb-9ef2-f1fac2b3c8ed.jpg)

'Follow us' label and icons of social networks expected result
![Follow us](https://user-images.githubusercontent.com/82100741/116678749-5fb67d00-a9b2-11eb-8c2f-ec0fbb440eb5.jpg)

**Comment by Halchysko** [comment]
This issue is created and renewed based on the old one #877

**Comment by SerhiiStarshoi** [comment]
Eco new actual result
<img width="486" alt="image" src="https://user-images.githubusercontent.com/32453285/120884823-1f1fd400-c5ee-11eb-9ada-48b0a3c671d5.png">



Twitter icon actual result
<img width="301" alt="image" src="https://user-images.githubusercontent.com/32453285/120884776-e4b63700-c5ed-11eb-82ce-35576c2cd47a.png">

'Follow us' label actual result
<img width="275" alt="image" src="https://user-images.githubusercontent.com/32453285/120884845-470f3780-c5ee-11eb-9e93-2dba30914795.png">
