### ISSUE TITLE
[My habits] The "You don't have authorities" error is shown after clicking 'Mark as done' checkbox

### ISSUE THREAD

**Issue by irynamykhailevych** [ita-social-projects/GreenCity#2709]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 01.05.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
My habits page is opened.

**Steps to reproduce**
1. Click on the 'Add new habit' button.
2. Click on the 'Add habit' button of any habits. 
3. Click on the 'Mark as done' checkbox.
4. Pay attention to the error message on the top of the page. 

**Actual result**
The "You don't have authorities" error is shown after clicking 'Mark as done' checkbox.

**Expected result**
The habit is transferred to the section of 'Acquired habits' from 'Habits in progress' section.

**User story and test case links**
User story #993
Test case GC-1816

![Screenshot_3](https://user-images.githubusercontent.com/82223583/116793200-f4fa6400-aacd-11eb-98d6-a69da6e8091d.jpg)

**Comment by nazarhlyvka** [comment]
It works properly.

**Comment by darzinch** [comment]
This case not reproduceble. See issue  #3296
