### ISSUE TITLE
BUG [ADMIN]There is an additional status in the 'Status' drop-down

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#271]
**Steps to reproduce:**
1. Go to http://greencityclient.herokuapp.com/
2. Login as Admin (e.g. 'User'='greencity.adm@gmail.com', 'Password'='Greencityadm123_')
3. Click on the drop-down list in the upper right corner above the map
4. Choose 'Admin'
5. Click 'Status' drop-down

**Actual result:**
Drop-down contains the following statuses:
- Proposed
- Approved
- Declined
- Deleted

**Expected result:**
Drop-down should have the following statuses:
- Proposed
- Approved
- Declined

[https://github.com/SoftServe-Social-Projects/GreenCity/issues/24](url)
[http://jira.softserve.academy/browse/GC-59](url)

**Comment by nhrab** [comment]
I approve to remain as it is now.
