### ISSUE TITLE
[Edit profile] Possible to save less than 6 characters in the 'Name' field

### ISSUE THREAD

**Issue by irynamykhailevych** [ita-social-projects/GreenCity#2710]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 01.05.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
Edit profile page is opened.

**Steps to reproduce**
1. Enter less than 6 characters in the 'Name' field.
2. Click on the 'Save' button.

**Actual result**
Possible to save less than 6 characters in the 'Name' field.

**Expected result**
The error message is shown after entering less than 6 characters:
ENG - The name must contain 6-30 characters and can contain letters(a-z), numbers(0-9) and a dot(.), dot at the start, at the end and consecutive dot is forbidden
UA - Ім'я повинно містити 6-30 символів і може складатись з літер(a-z), цифр(0-9) та крапки(.), крапка на початку імені, в кінці та послідовність крапок заборонена
RU - Имя должно содержать 6-30 символов и может состоять из букв(a-z), цифр(0-9) и точки(.), точка в начале имени, в конце, а также последовательность точек запрещена

**User story and test case links**
User story #1010 
Improvement: #2615, #2693 

![Screenshot_4](https://user-images.githubusercontent.com/82223583/116794037-f8dcb500-aad2-11eb-9617-815455bccf03.jpg)

**Comment by nazarhlyvka** [comment]
![image](https://user-images.githubusercontent.com/77922339/129071076-6194f29e-d20b-4c60-a961-fdb942028711.png)
![image](https://user-images.githubusercontent.com/77922339/129071247-fafa694a-3318-435b-9d3e-295024b2912c.png)
It works correct.
