### ISSUE TITLE
[Edit profile] Possible to save name with a dot in the 'Name' field

### ISSUE THREAD

**Issue by irynamykhailevych** [ita-social-projects/GreenCity#2711]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 01.05.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
Edit profile page is opened.

**Steps to reproduce**
1. Enter the dot at the beginning of the name in the 'Name' field.
2. Enter the dot at the end of the name in the 'Name' field.
3. Click on the 'Save' button.

**Actual result**
Possible to save name with a dot at the beginning or at the end of the name in the 'Name' field.

**Expected result**
The error message is shown after entering a dot at the beginning or at the end of the name in the 'Name' field: 
ENG - The name must contain 6-30 characters and can contain letters(a-z), numbers(0-9) and a dot(.), dot at the start, at the end and consecutive dot is forbidden
UA - Ім'я повинно містити 6-30 символів і може складатись з літер(a-z), цифр(0-9) та крапки(.), крапка на початку імені, в кінці та послідовність крапок заборонена
RU - Имя должно содержать 6-30 символов и может состоять из букв(a-z), цифр(0-9) и точки(.), точка в начале имени, в конце, а также последовательность точек запрещена

**User story and test case links**
User story #1010
Improvement: #2615, #2693

![Screenshot_5](https://user-images.githubusercontent.com/82223583/116794368-2cb8da00-aad5-11eb-8b7a-d8001e355902.jpg)

**Comment by SerhiiStarshoi** [comment]
User can not save dots in the 'Name' field

<img width="396" alt="image" src="https://user-images.githubusercontent.com/32453285/120884538-64db9d00-c5ec-11eb-9b7e-5621557f1e9f.png">
