### ISSUE TITLE
[Search] Wrong quantity of news are displayed for screen resolution 1024

### ISSUE THREAD

**Issue by Halchysko** [ita-social-projects/GreenCity#2714]
**Environment:** Windows 8.1, Google Chrome 90.0.4430.93
**Reproducible:** always
**Build found:** 04.05.2021

**Preconditions**
The user should be signed in GreenCity

**Steps to reproduce**
1. Click on the 'Search' icon
2. Type text in the search field (e.g. "news")
3. Click on the 'See all news' button

**Actual result**
The user sees unstoppable scrolled news in column and 2 news in a row
![not9items](https://user-images.githubusercontent.com/82100741/116972785-381e2800-acc4-11eb-84d5-2913cf1e4694.png)

**Expected result**
The User sees first 9 of them: 3 items per 1 column, 3 items in a row.
![Should be](https://user-images.githubusercontent.com/82100741/116972815-453b1700-acc4-11eb-8654-45eac272bb6c.png)

**User story and test case links**
User story #572 , 
[User story](https://jira.softserve.academy/browse/GC-2023)
[Test case](https://jira.softserve.academy/browse/GC-1763)

**Comment by SerhiiStarshoi** [comment]
The User sees first 9 of them: 3 items per 1 column, 3 items in a row.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/32453285/120886190-61004880-c5f5-11eb-82bd-252c4728c75c.png">
