### ISSUE TITLE
[Search] The search window is closed after user clicks in any page place

### ISSUE THREAD

**Issue by AlexaEskina** [ita-social-projects/GreenCity#2716]
**Environment:** Windows 10, Google Chrome v.90.0.4430.93
**Reproducible:** always
**Build found:** 04.05.2021

**Preconditions**
The User is Logged with actual credential at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**
1. Click on the 'Search' icon in the header
2. Type any data in the search field (e.g News)
3. Click on the place above the card with news
![Screenshot 2021-05-04 142317](https://user-images.githubusercontent.com/75045081/116996763-96f39980-ace4-11eb-9d8a-294a43b97004.png)

**Actual result**
After clicking on the place above the card with news, the search window is closed 

**Expected result**
The search window should be closed when the user clicks on "X"

"User story #545

**Comment by Edw1x** [comment]
Not reproducible now
