### ISSUE TITLE
[Search] User can see only first 9 items (instead 12 items) of the search results, if the list has more than 9 items

### ISSUE THREAD

**Issue by Uliana-Bigun** [ita-social-projects/GreenCity#2718]
Environment: OS Windows 10 Pro, browser - Google Chrome 89.0.4389.114 (64-bit)

Reproducible: always

Build found: last commit from https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. The user should be logged in;
2. Click on the 'Search' icon at the top right side of the screen
3. Type the text in the 'Search' field (e.g. 'news')
4. Click on the ‘See all News’ button on the left side at the bottom of the screen

**Actual result**
The new page with all items found is displayed. The User sees first 9 of them.

**Expected result**
The new page with all items found is displayed. The User sees first 12 of them.

**User story and test case links**
E.g.: "User story #572
[Test case - GC-2028] (https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)"

**Comment by paslavskyi9roman** [comment]
![search](https://user-images.githubusercontent.com/46484914/117654575-994f6b00-b19e-11eb-85ec-1d92132528d7.jpg)

https://github.com/ita-social-projects/GreenCity/issues/572
