### ISSUE TITLE
[Search] The 18 items are shown instead of 9 after infinite scrolling

### ISSUE THREAD

**Issue by irynamykhailevych** [ita-social-projects/GreenCity#2720]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 04.05.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome

**Steps to reproduce**
1. Click on the 'Search' icon at the header of the site.
2. Type the text in the 'Search' field (e.g. 'news')
3. Click on the ‘See all News’ button on the left side at the bottom of the screen.
4. Scroll down the search results.

**Actual result**
The 18 items are shown instead of 9 after infinite scrolling.

**Expected result**
The 9 items are shown after infinite scrolling.

**User story and test case links**
E.g.: "User story #572
[Test case](https://jira.softserve.academy/browse/GC-1764)"

https://user-images.githubusercontent.com/82223583/117043738-4dbc3d80-ad16-11eb-8ded-c38126773580.mp4

**Comment by darzinch** [comment]
This bug is not reproduceble
