### ISSUE TITLE
[Search] Long search result doesn't move on the next line when user types long value

### ISSUE THREAD

**Issue by AlexaEskina** [ita-social-projects/GreenCity#2721]
**Environment:**Windows 10, Google Chrome v.90.0.4430.93
**Reproducible:** always
**Build found:**04.05.2021

**Preconditions**
The User is Logged with actual credential at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**
1. Click on the 'Search' icon in the header
2. Type in the search field letter '**j**' 100 times ( or any numeric 100 times)

**Actual result**
When a user types too long value in the search field, the search result displays behind a card with news

**Expected result**
When a user types too long value in search field, the search result should be moved on the next line
![Screenshot 2021-05-04 200257](https://user-images.githubusercontent.com/75045081/117045574-5281f100-ad18-11eb-9da3-daf1dd89c4c7.png)

"User story #545

**Comment by SerhiiStarshoi** [comment]
Search result moves on the next line when user types long value

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/32453285/120885551-555f5280-c5f2-11eb-849c-38ded0035a60.png">
