### ISSUE TITLE
[My habits] Background colors do not match.

### ISSUE THREAD

**Issue by mocharna** [ita-social-projects/GreenCity#2722]
Environment: OS: Windows 10, Browser: Google Chrome 89.0.4389.114
Reproducible: Always
Build found: 04.05.2021

**Steps to reproduce**
1. User should be logged in Green City 'https://ita-social-projects.github.io/GreenCityClient/#/welcome';
2. Go to 'My habits' page.

**Actual result**
Background - White #FFFFFF
Icons - #F5F6F6

<img width="437" alt="1" src="https://user-images.githubusercontent.com/82234978/117048075-43e90900-ad1b-11eb-8272-9ba1306e6858.PNG">

**Expected result**
Background - Grey #F7F7F7
Icons - White #FFFFFF

<img width="334" alt="2" src="https://user-images.githubusercontent.com/82234978/117048045-3c296480-ad1b-11eb-95ff-70b2799ebd27.PNG">

**Comment by JohnSteck9** [comment]
already done
