### ISSUE TITLE
[Eco news] Extra page in pagination.

### ISSUE THREAD

**Issue by mocharna** [ita-social-projects/GreenCity#2723]
**Environment**: OS: Windows 10, Browser: Google Chrome 89.0.4389.114.
**Reproducible**: Always
**Build found**: 04.05.2021

**Steps to reproduce**
1. Click on 'Eco News' tab
2. Click on news with 7 pages of comments/replies ('https://ita-social-projects.github.io/GreenCityClient/#/news/11252')

**Actual result**
 Page numbers are placed in order: '1', '2', '3', '4', '...', '7'

**Expected result**
 Page numbers are placed in order: '1', '2', '3', '...', '7'

<img width="119" alt="1" src="https://user-images.githubusercontent.com/82234978/117052650-abee1e00-ad20-11eb-8c3b-e962fa10f8fc.PNG">

**User story and test case links**
User story: #767
Test case: https://jira.softserve.academy/browse/GC-902

**Comment by darzinch** [comment]
The issue is still not resolved
![image](https://user-images.githubusercontent.com/91462440/136054757-662531cd-34af-439f-9e3e-f61a9746dd5e.png)
