### ISSUE TITLE
[Eco news] Extra page in pagination.

### ISSUE THREAD

**Issue by mocharna** [ita-social-projects/GreenCity#2724]
**Environment**: OS: Windows 10, Browser: Google Chrome 89.0.4389.114.
**Reproducible**: Always
**Build found**: 04.05.2021

1. **Steps to reproduce**
1. Click on 'Eco News' tab
2. Click on news with '7' pages of comments ('https://ita-social-projects.github.io/GreenCityClient/#/news/11252')
3. Click on comment page number '4'.

**Actual result**
Page numbers are placed in order: '1', '2', '3', '4', '5', '6', '7'

**Expected result**
Page numbers are placed in order: '1', '...', '3', '4', '5', '...', '7'

2. **Steps to reproduce**
1. Click on 'Eco News' tab
2. Click on news with '7' pages of comments ('https://ita-social-projects.github.io/GreenCityClient/#/news/11252')
3. Click on page number '7' (last page).

**Actual result**
Page numbers are placed in order: '1', '2', '3', '4', '5', '6', '7'.

**Expected result**
Page numbers are placed in order: '1', '...', '4', '5', '6', '7'.

**User story and test case links**
User story: #767
Test case: https://jira.softserve.academy/browse/GC-902

**Comment by s1auka** [comment]
Note: We show '...' only if we hide 2 or more pages. So
we have '1', '2', '3', '4', '5', '6', '7' instead of '1', '...', '3', '4', '5', '...', '7'
