### ISSUE TITLE
[Eco news] Wrong placement of pictures on different screen resolutions.

### ISSUE THREAD

**Issue by mocharna** [ita-social-projects/GreenCity#2725]
**Environment**: OS: Windows 10, Browser: Google Chrome 89.0.4389.114.
**Reproducible**: Always
**Build found**: 04.05.2021

**Steps to reproduce**
1. Click on 'Eco News' tab
2. Click on news with 7 pages of comments/replies ('https://ita-social-projects.github.io/GreenCityClient/#/news/11252')

**Actual result**
Pictures are displayed wrong while screen resolutions '992/991' and '768/767'.

**Expected result**
Pictures are displayed in a row while screen resolutions '992/991' and '768/767'.

**User story and test case links**
User story: #767
Test case: https://jira.softserve.academy/browse/GC-903

**Comment by MyroslavaVynokur** [comment]
Pictures are displayed in a row while screen resolutions '992/991' and '768/767' - verified
