### ISSUE TITLE
[Search] The dot is missed at the end of the sentence after searching text which couldn't be found

### ISSUE THREAD

**Issue by irynamykhailevych** [ita-social-projects/GreenCity#2734]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 05.05.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
The **Eng** localization is turned on. 

**Steps to reproduce**
1. Click on the 'Search' icon at the header of the site.
2. Type the text in the 'Search' field which couldn't be found (e.g. 'bAasnashj12123(%&#$746hgh')
3. Pay attention to the "We couldn't find results for <User's search query>. Please change the search." label.

**Actual result**
The dot is missed at the end of the sentence after searching text which couldn't be found.

**Expected result**
The dot is displayed at the end of the sentence "We couldn't find results for <User's search query>**.**" after searching text which couldn't be found.

**User story and test case links**
E.g.: "User story #572
[Test case](https://jira.softserve.academy/browse/GC-773)"

![2021-05-05_22-32-07](https://user-images.githubusercontent.com/82223583/117199597-0bb4f980-adf3-11eb-926e-77cf1d17ef49.png)

Mock-up:
![2021-05-05_22-42-24](https://user-images.githubusercontent.com/82223583/117199761-41f27900-adf3-11eb-9f98-278b48864163.png)

**Comment by YulianaNadorozhniak** [comment]
This bug is still reproducible
Environment: Windows 10, Chrome Version 91.0.4472.124
![edde3ca3-ade9-468f-a434-3d28921acce2](https://user-images.githubusercontent.com/88138210/128035307-9aa1bef1-9538-49c5-80d6-8a078e0e2b79.jpg)
