### ISSUE TITLE
[Search] The date labels are not translated to Ukrainian/Russian with UA/RU localization after searching 

### ISSUE THREAD

**Issue by irynamykhailevych** [ita-social-projects/GreenCity#2735]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 05.05.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
The **UA/RU** localization is turned on.

**Steps to reproduce**
1. Click on the 'Search' icon at the header of the site.
2. Type the text in the 'Search' field (e.g. 'в')
3. Pay attention to the date labels.

**Actual result**
The date labels are not translated to Ukrainian/Russian with UA/RU localization after searching.

**Expected result**
The date labels are translated to Ukrainian/Russian with UA/RU localization after searching.

![2021-05-05_22-53-33](https://user-images.githubusercontent.com/82223583/117202493-8b909300-adf6-11eb-93b7-7f8e1d377679.png)

**User story and test case links**
E.g.: "User story #572 
[Test case](https://jira.softserve.academy/browse/GC-773)"

**Comment by NewArtMask** [comment]
- It is no longer relevant because of the change in design

![image](https://user-images.githubusercontent.com/34275837/132245872-5146c25e-c4c3-4576-a1e4-69ad8639ce94.png)
