### ISSUE TITLE
[Eco news] Number of comments are displayed in the wrong place. 

### ISSUE THREAD

**Issue by mocharna** [ita-social-projects/GreenCity#2736]
**Environment**: OS: Windows 10, Browser: Google Chrome 89.0.4389.114.
**Reproducible**: Always
**Build found**: 05.05.2021

**Steps to reproduce**
1. Click on 'Eco News' tab
2. Click on news with 7 pages of comments/replies ('https://ita-social-projects.github.io/GreenCityClient/#/news/11252')

**Actual result**
![2](https://user-images.githubusercontent.com/82234978/117202288-53895000-adf6-11eb-855e-c7ea0a22fc8d.PNG)

**Expected result**
![1](https://user-images.githubusercontent.com/82234978/117202314-57b56d80-adf6-11eb-855e-1965a2c5d81e.PNG)

**User story and test case links**
User story: #767
Test case: https://jira.softserve.academy/browse/GC-903

**Comment by TetianaD** [comment]
Number of comments are displayed in the wrong place again.
![Uploading Screenshot 2021-05-19 at 22.59.17.png…]()

**Comment by eclipseidea** [comment]
![image](https://user-images.githubusercontent.com/25909791/129599024-b88c579a-a2d1-4923-96a8-2b9f287f2c6d.png)

The amount of comments is displayed in the correct format on all screen sizes, I removed only the colon (:)
