### ISSUE TITLE
[UBS, Management] AddViolationToUser responses 500 Internal Server Error

### ISSUE THREAD

**Issue by ViktorRachynskyi** [ita-social-projects/GreenCity#2744]
Reproducible: always
Build found: 09.05..2021

Pre-conditions:
- any order is already created (remember it's id)
 
Steps to reproduce:
1. Open Swagger https://greencity-ubs.azurewebsites.net/swagger-ui.html
2. Authorize as admin
3. Open the 'management-order-controller' list
4. Click on the 'POST /ubs/management/addViolationToUser' button 
5. Click on the 'Try it out'
6. Enter a correct order ID (from pre-conditions)
7. Add any violation description to your user
Example:
"The user didn't take his order"
8. Enter the 'en' text in the 'language' field
9. Click on the 'Execute' button 

Actual result: 
- 500 Internal Server Error appears
![image](https://user-images.githubusercontent.com/79053863/117553893-bbd96b00-b05c-11eb-8fe8-d6cebb2adf6e.png)

Expected result:
- 201 'created' code is got
- Violation Description should be successfully added to the appropriate user

**Comment by adamos98** [comment]
![image](https://user-images.githubusercontent.com/75321714/118645049-bc9d9a00-b7de-11eb-8583-4a4c85384aed.png)

That was not a bug. The problem was that the fields in the users table do not yet have data in "recipient_name", "recipient_email". After manually adding the data, the response is correct.

**Comment by LiliiaPalii** [comment]
![201](https://user-images.githubusercontent.com/55461895/121083565-43470500-c7e8-11eb-9568-9c180b0b4559.png)
