### ISSUE TITLE
[Edit Profile] "Save" button is disabled when social network link is added, edited or deleted.

### ISSUE THREAD

**Issue by ElizbethNovakova** [ita-social-projects/GreenCity#2746]
**Environment:** Windows 10  x64,  Google Chrome Version 90.0.4430.93
**Reproducible:** always.
**Build found:** 09.05.2021

**Preconditions**
The User is Logged with actual credential at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**
1. Go to 'My habits'
2. Click on 'Edit profile'
3. Scroll down to 'Linked social networks'
4. Add social network / edit social network / delete social network

**Actual result**
Button 'Save' is disabled.

**Expected result**
Button 'Save' is enabled, the user has the ability to save changes.

![bug1](https://user-images.githubusercontent.com/30701821/117571185-1531b080-b0d6-11eb-8659-4351a9bcc914.PNG)

![bug2](https://user-images.githubusercontent.com/30701821/117571186-18c53780-b0d6-11eb-9036-823a24c1a008.PNG)

**Comment by SerhiiStarshoi** [comment]
new defect https://github.com/ita-social-projects/GreenCity/issues/2869
