### ISSUE TITLE
[Edit Profile] Pop up isn't shown when the 'Cancel' button clicked when social network link is added, edited or deleted.

### ISSUE THREAD

**Issue by ElizbethNovakova** [ita-social-projects/GreenCity#2748]
**Environment:** Windows 10 x64, Google Chrome Version 90.0.4430.93
**Reproducible:** always
**Build found:** 09.05.2021

**Preconditions**
The User is Logged with actual credential at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**
1. Go to 'My habits'
2. Click on 'Edit profile'
3. Scroll down to 'Linked social networks'
4. Add social network / edit social network / delete social network
5. Click the 'Cancel' button.

**Actual result**
Pop up isn't shown after click 'Cancel' button

**Expected result**
Pop up is shown after click 'Cancel' button

**Comment by SerhiiStarshoi** [comment]
Pop up is shown after click 'Cancel' button

<img width="976" alt="image" src="https://user-images.githubusercontent.com/32453285/120886474-cacd2200-c5f6-11eb-939d-3fcdb09fc36b.png">
