### ISSUE TITLE
Personal Cabinet of registered user

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#277]
As a registered user I want to get into my personal cabinet, so that I can see my personal information.

Mockups:
![image](https://user-images.githubusercontent.com/53868652/67082350-a6ae9a00-f1a1-11e9-98dd-cf3f6c1bf512.png)

Acceptance Criteria:
1. Personal cabinet shall contain sections:
a. header
b. "My Eco Stats"
c. "Goals"
d. "Tracker"
e. "User settings" - _think of better name_ #279 
2. Header shall contain
a. logo
b. welcome message
c. sign out button

Assumptions and Constraints:
1. given user is logged in, when he closes the page AND opens it again, then system shall navigate him to personal cabinet
2. think about user session expiration time - **not needed?** 

TBD:
1. need a button to navigate to main page from cabinet
2. on main page - when signed in - header text to disappear and maybe user avatar appears (when clicked on - takes to cabinet)

**Comment by rsyvulko** [comment]
Not relevant.
