### ISSUE TITLE
My Achievements in User settings

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#278]
As a registered user I want to see all achievements so that I can track them in my settings.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/68378537-f3f4aa80-0154-11ea-8826-2552409ebe28.png)

Acceptance criteria:

1. Set of all available achievements are displayed in user settings panel in personal cabinet.

2. Available achievements contain the next:
a. Achievement 1 - "Acquaintance"
b. Achievement 2 - " Eco friend"
c. Achievement 3 - " Conscious"
…

3. A registered and logged in user can hover cursor on each of achievements and see popup with text how to achieve appropriate achievement. 

4. Conditions, when *Achievement 1 - "Acquaintance"* become enabled for registered and logged in user is described in # story 

5. Conditions, when *Achievement 2 -  " Eco friend"* become enabled for registered and logged in user is described in # story 

6. Conditions, when *Achievement 3 - " Conscious"* become enabled for registered and logged in user is described in # story 

Assumption and Constraints:
1.  At the beginning all available achievements are inactive for register and logged in user.

**Comment by rsyvulko** [comment]
Not relevant.
