### ISSUE TITLE
CRUD employees

### ISSUE THREAD

**Issue by YanaTarasiuk** [ita-social-projects/GreenCity#2780]
As an admin, I want to be able to add data on the role page, so that I could add the employees. 

**Business rules:**
1. An employee with a particular role is responsible only for his/her orders and a new employee with the same role is responsible for orders, which he/she manages.

**Precondition:** the Admin is on the role page
 
**Acceptance criteria**

1. When the “Додати працівника” button is tapped, the new employee form is opened (see mockup) and it has: 
a) the attributes: “Ім’я”, “Прізвище”, “Посада”, “Телефон”, "Email", “Тарифи”, "Фото"  should have the following input fields and a dwopdown menu described in the table below:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-8d32216c-7fff-9dec-ec0e-a20ee0fa0211"><div dir="ltr" style="margin-left:0pt;" align="left">

Field title | Field type | Prefilled text | Condition | Validation
-- | -- | -- | -- | --
Ім’я | Input field | n/a | Mandatory | Letters should be whether from Cyrillic or Latin alphabets, Capital or lower-case, one special symbol "-" between letters, space are allowed, size should be from 1 to 30 characters. 
Прізвище | Input field | n/a | Mandatory | Letters should be whether from Cyrillic or Latin alphabets, Capital or lower-case, one special symbol "-" between letters, space are allowed, size should be from 1 to 30 characters. 
Номер телефону | Input field | Autofill +380. It shall be editable.| Mandatory| Only numeric characters are allowed. When the user starts typing, the placeholder “+380” stays in the field, so the user needs to type the rest of the telephone number (for example, the user shall type only 96 123 45 67) and only type the numbers starts with "39","50","63","66","67","68","91", "92","93","94","95","96","97","98" as Ukrainian mobile operators have.
Email| input field| n/a| Non-Mandatory| Email text field(see https://github.com/ita-social-projects/GreenCity/issues/4277 )
Роль / Посада | Checkboxes| n/a | Non-Mandatory | One/a few of the checkboxes are selected.
Тарифи| Checkboxes | n/a | Non-Mandatory | One/a few of the checkboxes are selected.
Фото| Upload image| Перетягніть зображення, або завантажте з пристрою | Non-Mandatory| The limit is 25 MB with .jpg/.png /.jpeg format,only one image should be uploaded. 

</div><br /></b>
</body>
</html>
b) “Скасувати” button. When tapped, the role page is opened and the changes are not saved.

c) “Додати” button. When tapped, the changes are saved when all the mandatory fields are populated. When at least one mandatory field is not populated and “Додати” is tapped,  the system shall display the warning message under the field: “Це поле є обов'язковим для заповнення”. Then the button “Додати” in the bottom of the page remains disabled until the user fulfils every mandatory field. When changes are saved, the new employee data is saved and depicted on the role page.

2. About the function Deactivate, we can follow this link: https://github.com/ita-social-projects/GreenCity/issues/4615
3. About the function Edit, we can follow this link: https://github.com/ita-social-projects/GreenCity/issues/4616

Mockup: 

**Epic**
UBS courier #2195

**Comment by Dana0104** [comment]
[Test.design.2780add.docx](https://github.com/user-attachments/files/21203625/Test.design.2780add.docx)
