### ISSUE TITLE
[UBS Admin Cabinet ] Order details

### ISSUE THREAD

**Issue by YuliyaTymkiv** [ita-social-projects/GreenCity#2787]
**As an** administrator, **I want  to** see and edit the details of the order in the admin cabinet **so that** I can plan the waste disposal.  

**Assumptions & Constraints**

1. Different Administrator types might have different rights sets
2. Some fields are interlinked with the current orders view table. If any field was changed in the current order view table, it should be changed in the related current order details and vice versa. 

**Preconditions**

1. User is logged in as administrator.
2. An administrator navigates to the Orders tab.
3. An administrator has opened an order from current orders view table

**Business rules**

1. Only administrators with access should be able to view Admin Cabinet

### Acceptance Criteria

1.  Current order details view should contain:

Field title | Field type | Requirements | Comments
-- | -- | -- | --
Замовлення | Disabled | Received from order form | &nbsp;
Дата оформлення | Disabled | Received from order form | &nbsp;
Статус замовлення | Enabled | &nbsp; | Described in user story #2538
Статус оплати | Disabled | &nbsp; | Described in another story.
Коментар адміністратора | Input field | Empty by default. Max 255 characters (all types of characters). Don't truncate | &nbsp;
Client information “Клієнт”
Ім'я | Disabled | Received from order form | Name and Surname
Телефон | Disabled | Received from order form | &nbsp;
E-mail | Disabled | Received from order form | &nbsp;
Information about the receiver “Отримувач”
Ім'я | Enabled, Input field, Mandatory. | Received from order formName and surname 1-30 char - 1-30 char. Special characters supported.&nbsp;When the field is empty, the placeholder in gray color should be depicted : “Ім’я та прізвище” | Described in Activity diagram: Add/change receiveIf a client chooses option “Отримувач інша людина” in order form, the receiver’s data should be depicted in these fields.If a client doesn’t choose option “Отримувач інша людина” in order form, then the client’s data should be depicted in these fields.
Телефон | Enabled, Input field, Mandatory. | Received from order form9 digits starting with:+380.When the field is empty, the placeholder in gray color should be depicted : “+380 00 000 00 00”
E-mail | Enabled, Input field, Optional | Received from order formWhen the field is empty, the placeholder in gray color should be depicted: “mail@mail.com”
Порушення клієнта | &nbsp; | &nbsp; | Described in user story #2861 - #2864 .
The information in section “Адреса вивезення відходів”| &nbsp; | &nbsp; | Described in user story #5101 
Район | Enabled&nbsp;Drop down list | Received from order form.The list of all 10 Kyiv districts shall be displayed in the drop-down: Голосіївський, Дарницький, Деснянський, Дніпровський, Оболонський, Печерський, Подільський, Святошинський, Солом'янський, Шевченківський | &nbsp;
Вулиця | Enabled, Input field, Mandatory | Received from order form.Only alphabetic and numeric characters,  special characters “-” (space) and " ' " (apostrophe) are allowed. From minimum 3 to maximum 40 characters are allowed. After typing 3 characters, the system shall show the street suggestions based on the Places API (Place Autocomplete). Suggestions are displayed by a drop-down list. When there are no suggestions the user should be able to type the full name of the street. | &nbsp;
Будинок | Enabled, Input field, Mandatory | Received from order form.Only numeric, alphabetic characters and "-,/"are allowed. | &nbsp;
Корпус | Enabled, Input field, Optionally | Received from order form.Only alphabetic and numeric characters are allowed. From minimum 1 to maximum 4 characters are allowed. | &nbsp;
Під’їзд | Enabled, Input field, Optionally | Received from order form.Only numeric characters are allowed. From minimum 1 to maximum 2 characters are allowed. | &nbsp;
Коментар до адреси від клієнта | Disabled | Received from order form | If the user has not added any comment, this field is empty. Don't truncate
Section “Деталі замовлення” | table with total quantity of packages, order, certificate and bonuses sums, order total is described in  user story #2865 
Номер сертифікату | Enabled | Received from order form.&nbsp;Certificate number 8 digit number.e.g. 1234-1234. In case several certificates were used, those are written in one line and are separated by ‘;’e.g: 2222-2222; 2222-2221 | Certificate verification is described in another story
Номер замовлення з магазину | Enabled | Received from order form. From 4 to 10- digit number from Eco-Store. In case several orders from Eco-Store are used those are written in one line and are separated by ‘;’e.g: 1234567890; 0123456789. | &nbsp;
Коментар до замовлення від клієнта | Disabled | Received from order form. Don't truncate | &nbsp;
Section “Оплата замовлення” | &nbsp; | &nbsp; | Described in another story
Section “Деталі вивезення”
Дата вивезення | DD/MM/YYYYEnabled | No value until status is changed to: Узгодження; Підтверджено; На маршруті; Виконано. | The administrator chooses dates from the calendar, that is shown when clicking on the field
Час вивезення | value-range.e.g: 10:30 - 12:00; 13:20 - 19:00enabled | No value until status is changed to: Узгодження; Підтверджено; На маршруті;  Виконано | The administrator chooses time from the time-picker, that is shown when clicking on the field  | &nbsp;
Станція приймання | Drop-down list of possible receiver stations. | &nbsp; | Станція - Саперно-Слобідська
Section “Відповідальні особи”
Менеджер послуги | Drop-down list of service managers | Pulls data from ‘Receiving station’ staff. | Shows Last + First Name
Менеджер обдзвону | Drop-down list of call-center managers | Pulls data from ‘Receiving station’ staff. | Shows Last + First Name
Логіст | Drop-down list of logists | Pulls data from ‘Receiving station’ staff. | Shows Last + First Name
Штурман | Drop-down list of pilots | Pulls data from ‘Receiving station’ staff. | Shows Last + First Name
Водій | Drop-down list of drivers | Pulls data from ‘Receiving station’ staff. | Shows Last + First Name

</div></b>

2. If the administrator inputs data in incorrect format, the system should highlight appropriate field.

![image](https://user-images.githubusercontent.com/82950010/119331422-00394d80-bc90-11eb-9009-aa5ea6e153cb.png)

**Mockup**
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=17561%3A749

**Out of scope**

1. Order statuses
2. Payment statuses
3. Add user rule violations to the current order
4. Change packages quantity in the current order
5. Certificate verification
6. Payment details
7. Save/cancel changes in the current order
8. Order sum validation
10. Adding and storage comments in the current order
11. View and manage users' violations
12. Send notifications to user
13. Order workflow log (history)
14. Manage orders for different stations
15. Edit, add and delete recipient
16. Edit address of waste disposal
17. Displaying payment with bonuses for additional packages
18. Responsible persons validation for different order statuses

**Epic link**
E.g.: Epic #2195 

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by YanaTarasiuk** [comment]
The text in the titles of the columns should be transferred into the next line, so admins can see the full title of the column
