### ISSUE TITLE
[UBS client cabinet] Send notifications to user

### ISSUE THREAD

**Issue by Adjichka13** [ita-social-projects/GreenCity#2796]
As a registered client I want to receive notifications so that I have informed of changes related to my order 

Mockup: https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-Greencity-%D0%A3%D0%91%D0%A1-(Copy)?node-id=15486%3A78034

**Assumptions & Constraints**
n\a

**Preconditions**
1. User is logged in as client 
2. User navigates to Client cabinet 

**Business rules**
n\a

### Acceptance Criteria
1. The notification tab should be located on the side navigation panel. 
![1](https://user-images.githubusercontent.com/82903691/120783496-c7bd2d80-c533-11eb-89a8-24748ecf15c7.jpg)
2. Title of the menu item should be “Повідомлення” 
3. Notification item has a counter and mark of unread messages.
![2](https://user-images.githubusercontent.com/82903691/120783823-166ac780-c534-11eb-879d-bb0600528b3f.jpg)
4. The notification tab contains tabl with raws of the message and 3 columns (order number, Title of the message, Time-Date) 
5. The message line must have the opportunity to expand\ collapse to show message content 
6. New messages (unread) are in bold 
7. Messages are sorted from newest to oldest 
8. Pagination and scrolling must be implemented
![4](https://user-images.githubusercontent.com/82903691/120784778-20d99100-c535-11eb-983d-731cb49fe7a7.jpg)
9. Autonotifications should be sent to additional communication channels (Viber or/and Telegram) in case the client has chosen additional channels in Client settings (It should be described in separate US)
10. If the user has selected English, then the notifications should be shown in English. Translations in doc https://docs.google.com/document/d/1lfNpxCbXY5qQOMzmZCEblL_NnlsX5K5J6f5Dv9A3hlI/edit

**Scenario 1** – Notification tab is empty 

_Given_ I’m logged client 
_When_ I open the “Повідомлення” tab of the navigation menu 
_Then_ the system shows me empty notifications’ page with Title “Ваші повідомлення” and text “У Вас ще немає повідомлень.” 
 
![3](https://user-images.githubusercontent.com/82903691/120784608-eec82f00-c534-11eb-8287-6995b16498c0.jpg)

**Scenario 2** – Notification tab with messages 

_Given_ I’m logged client 
_When_ I open the “Повідомлення” tab of the navigation menu 
_Then_ the system shows me list of notifications with Title “Ваші повідомлення” and notification table with 3 columns (order number, Title of the message, Date) 
_And_ client can expand notification 
_And_ client can collapse notification 

![5](https://user-images.githubusercontent.com/82903691/120785694-0bb13200-c536-11eb-8fd6-c2d72a437a43.jpg)

![6](https://user-images.githubusercontent.com/82903691/120785874-40bd8480-c536-11eb-8e22-abd374263566.jpg)

![7](https://user-images.githubusercontent.com/82903691/120786008-65b1f780-c536-11eb-87bd-8a32fc5c13b8.jpg)

Auto notification - sent by the system automatically in response to some event
1) Reminder that there is an unpaid application (at the end of 3 days)
2) Message that the application has been paid
3) Message about the formed route
4) Message that you need to pay for the package
5) Message about the accrual of bonuses
6) Reporting a violation

| Message | Requirements | Content| Comment |
| ------------- |:------------------|:-----------|:------------|
| Unpaid order     | <p>1. Trigger - 3 days after order was formed. <p>2. System checks BD at 18.00 daily and sends messages  in case the order was formed 3 days ago and wasn’t paid by client. <p>3. Chat and e-mail links are clickable. <p>4. **Resend Message** - The system must resend a message every 7 days (once a week) for a month.  | **Title**: Неоплачене замовлення **Body:**  Вітання! Ви нещодавно залишили заявку для замовлення нашої послуги «УБС Кур’єр», але ми не отримали підтвердження оплати.  Можливо, у вас виникли якісь труднощі? Якщо у вас залишилися будь-які питання — з радістю відповім!  Чат з менеджеркою   [t.me/nowaste_service_bot](url) чи e-mail   [hello@nowaste.org.ua](url) |  |
|   Order is paid   |  <p>1. Trigger - the system get an answer from the payment system. <p>2. The UBS system sends a message. <p>3. Chat and e-mail links are clickable.  | **Title:** Оплата пройшла успішно **Body:** Вітаємо! Ви успішно замовили й оплатили послугу «УБС Кур'єр»!  УБС Кур'єр приїде по ваші пакети впродовж 2–9 днів від дати оплати послуги. Коли маршрут буде сформовано, ми обов’язково зв'яжемося з вами для узгодження деталей. Якщо у вас залишилися будь-які питання — з радістю відповім!  Чат з менеджеркою  [ t.me/nowaste_service_bot](url) чи  e-mail   [hello@nowaste.org.ua](url)   |   |
|  Courier itinerary formed  | <p> 1. Trigger - the manager includes the order in the itinerary and changes order status to “Підтвердженно”.<p> 2. The system sends message immediately after a status change.<p> 3. Chat and e-mail links are clicable. <p>4. _Date format_: Day Month (23 April) - Received from order form <p>5. _Time format:_ Hours:Minutes (8:30) - Received from order form  | **Title:** Маршрут сформовано  **Body:** Вітання! Ми сформували маршрут УБС Кур’єра. Наш Кур’єр буде у вас завтра, _XX Mісяць_.  Робочий час Кур'єра: з _XX:XX_ до _XX:XX_.  Будь ласка, залишайтеся в цей час на зв’язку й увімкніть телефон на гучний режим. Кур'єр зателефонує вам заздалегідь та коли приїде. Якщо вам не вдасться бути на місці в домовлений час, ви можете залишити ваші пакети в консьєржа, але обов'язково попередьте про це Кур'єра або менеджерів! Номер Кур'єра — +380638175035 або +380931038987.  Якщо у вас залишилися будь-які питання — з радістю відповім! Чат з менеджеркою   [t.me/nowaste_service_bot](url) чи  e-mail   [hello@nowaste.org.ua](url)  |  _Assumption:_ For now, the courier number is static, but in the future it should be getting from the employee system  |
|  Unpaid package  | <p>1. Trigger - payment status changes to “Частково оплачено”. <p> 2.The System sends message after changing the payment status to “Частково оплачено”. <p>3. Button “Оплатити” inside notification redirects to page 3 of the order 4. Float number with 2 digits.e.g (150.00 UAH) No upper limit. <p> 4. Payment sum received from the order form<p> 5. Order number received from the order form <p>6. Resend Message - The system must resend a message every 7 days (once a week) for a month.| **Title:**  Оплатіть зміну у замовлені **Body:** Вітання! Ви внесли зміни у замовлення №ХХХХ Просимо вас, будь ласка, доплатити  ХХХ грн. Оплатити: (кнопка “Оплатити”). Якщо у вас залишилися будь-які питання — з радістю відповім! Чат з менеджеркою   t.me/nowaste_service_bot чи  e-mail   hello@nowaste.org.ua. |   |
|  Accrued bonuses to account   | <p>1. Trigger - If the order has overpayment after changing order status to "Виконано". <p>2. The System sends message after the system formed bonuses. <p>3. Packages number received from order form. <p>4. Payment sum received from the order form| **Title:** Нараховано бонуси **Body:** Вітання! Сьогодні УБС Кур’єр забрав у вас пакетів: XXX. А оплачували ви: XXX. Тож фіксуємо для вас депозит для наступного вивозу на суму XXX грн. Гарного дня!    |   |
|  Violation the rules   | <p>1. Trigger – manager adds violation to order. <p>2. The System sends message after the manager added  violation to order “Виявлено порушення”. <p>3. Link with rules is clickable and redirects to page [https://bit.ly/2Q2esLB](https://bit.ly/2Q2esLB) <p>4. List of the violations received from order form <p> 5. Photos of the violations received from order form   | **Title:** Недотримання правил УБС **Body:** Вітання! На жаль, у ваших пакетах було виявлено: xxxxxx. Це відходи, які ми не приймаємо.  Будь ласка, ознайомтеся ще раз із нашими правилами сортування: [https://bit.ly/2Q2esLB](url) **НЕ приймаємо взагалі:** - батарейки, акумулятори, ртутьвмісні (люмінесцентні) лампи й термометри; - ліки та фармацевтичні відходи (маски, рукавички, шприци), а також усе, що контактувало з рідинами тіла (кров’ю, сечею, слиною, виділеннями); - використані засоби особистої гігієни та контрацепції (підгузки, прокладки, тампони, презервативи тощо); - картриджі принтера; - будівельні відходи, лаки, фарби, пластилін; - недопалки/стіки від електронних аксесуарів для куріння; - газові балони, запальнички, вибухонебезпечні предмети (гільзи, снаряди тощо); - кераміку; - гострі та ріжучі предмети. Дякуємо за розуміння!    |  |
|  Let's stay connected  | <p> 1. Trigger - 2 months after last order. <p>2. System checks BD daily and sends messages in case the order was made 2 months ago. <p> 3. **Re-sending a message** - The system must re-send a message every 2 months, throughout the year. The letter should have a built-in counter that will indicate how long ago the last order was 2 months, 4 months, 6 months, etc. up to 1 year. | **Title:** Давайте залишатися на зв'язку **Body:** Привіт! Ми помітили, що ви не користувалися послугою «УБС Кур‘єр» уже [month amount] місяці. Можливо, ви вирушили в тривалу подорож, а можливо, щось пішло не так зі збиранням пластиків. Поділіться, будь ласка, цим із нами, щоб ми зрозуміли, чи можемо допомогти і як саме.  |  |
|   |    |    |  |

**Out of scope**
1. Search of the notification
2. Sorting and filtering of the notifications
3. Removing the notifications

**Epic link**
E.g.: Epic #2195 [Epic]

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by YanaTarasiuk** [comment]
Attention: the **Body** of the UNPAID ORDER should be the following in UA version: 

Вітання! Ви нещодавно залишили заявку для замовлення нашої послуги «УБС Кур’єр», але ми не отримали підтвердження оплати. Можливо, у вас виникли якісь труднощі? Сума до сплати XXX.00 грн. Оплатити: (HERE should be actual link for payment. https://secure.wayforpay.com/invoice/). Якщо у вас залишилися будь-які питання — з радістю відповімо! Чат з менеджером https://t.me/nowaste_service_bot чи e-mail hello@nowaste.org.ua
