### ISSUE TITLE
See a sidebar list of cafes near the map

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#28]
As an unregistered user I want to see a sidebar list of cafes near the map, so that I can view them outside of the map.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/62836061-fdf73200-bc67-11e9-9437-df5eb946b57b.png)

Acceptance Criteria:
1. WHEN Unregistered user accesses the website, THEN on the left side of the window he/she can see the list of test cafes.

2. Sidebar list of cafes include names of test cafes and their address.

3. List cafes should be sorted by name of cafe.

4. Test cafes, which are on the list in sidebar should be visible on the map in parallel.

Assumptions and Constraints:
This user story is related to user story #20

**Comment by nhrab** [comment]
This story was joined with user story #20

**Comment by rsyvulko** [comment]
Not relevant.
