### ISSUE TITLE
Marking of Home page

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#280]
As a user I want to enter that application so that I can see home page.

Mockups:
![image](https://user-images.githubusercontent.com/53810790/70897264-f0c5c780-1ffa-11ea-8f7d-163c59b7768b.png)
![image](https://user-images.githubusercontent.com/53810790/70897290-fb805c80-1ffa-11ea-987e-93843bdd2acb.png)
![image](https://user-images.githubusercontent.com/53810790/70897314-06d38800-1ffb-11ea-979b-191219969cbd.png)

1. Home page consists of the next sections:
   1.1. Header #352 
   1.2. Navigation panel #354 
   1.3. Advertising info of application #355 
   1.4. Stat info based on habits #356 
   1.5. Eco news #351 
   1.6. Eco advices #376 
   1.7. Receiving eco news #353 
   1.8. Footer #384

Assumptions and constraints:
1. User can scroll up and down home page.
2. Home page should be responsive

#668 #669

**Comment by yuraolkhovskyi** [comment]
This story is still in progress because we need to add functionality for QR-code and create an ability to add a photo for every eco-news.
