### ISSUE TITLE
Change icons on habit page

### ISSUE THREAD

**Issue by hutei** [ita-social-projects/GreenCity#2801]
how it's now:
![image](https://user-images.githubusercontent.com/36189445/119549896-61e8dd00-bda0-11eb-95a8-aa3317577b3c.png)

how should it be:
![image](https://user-images.githubusercontent.com/36189445/119549739-3665f280-bda0-11eb-9118-65a23a84eecf.png)

**Comment by KaterynaKhorosh** [comment]
![2022-01-24_10-49-21](https://user-images.githubusercontent.com/95848159/150750809-648a431b-1c5a-4ecc-a4ce-f6dcced5279a.png)

Icons are changed on habits page
