### ISSUE TITLE
[UBS Controller] Return order detail

### ISSUE THREAD

**Issue by ZaharVeremchuk** [ita-social-projects/GreenCity#2821]
**Description** :
1. Create contollers that will return data for this part of page.
2.  Look on figma https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=17561%3A749
3. It should return json with information about bags 
4. Should be controller for saving order with changed bags 
5. Should be controller that count the new sum of order
6. Should be controller that return information about Number of certificate  and number of orderId and comment
7. Should be implement controller that save all data of this part of page.

![image](https://user-images.githubusercontent.com/45737995/119932164-6f15ef80-bf8b-11eb-83ac-13b87891bc46.png)

8. Work with this tables in database

![image](https://user-images.githubusercontent.com/45737995/119933565-06c80d80-bf8d-11eb-8a6c-f279e53cdcca.png)

**Epick link**
Epic #2787 

Controllers:{
/read-order-info/{id}
/set-order-detail
/get-order-sum-detail/{id}
}

**Comment by MyroslavaVynokur** [comment]
Get bags info controller
<img width="894" alt="Screenshot 2021-12-16 at 23 25 38" src="https://user-images.githubusercontent.com/34717146/146451223-7e03455f-658f-4dc7-b946-52e86c13871a.png">

Get order sum details
<img width="1025" alt="Screenshot 2021-12-16 at 23 33 46" src="https://user-images.githubusercontent.com/34717146/146452236-7fe7d9bc-da82-4508-b613-57c560b82836.png">
