### ISSUE TITLE
My Eco Stats (Статистика за місяць) in Personal Cabinet

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#283]
As a registered, logged in user I can see my statistics for month based on information from tracker so that I can analyze my consumption of chosen item.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/68341419-1523af80-00f1-11ea-8e93-115133077bad.png)

![image](https://user-images.githubusercontent.com/53810790/68341388-050bd000-00f1-11ea-8052-e56152ef3a50.png)

Acceptance criteria:

1. My Eco Stat block contains:
      a. tooltip with current date and number of day of habit
      b. title "Calendar of eco habits"
      c. Tooltip text or statistics

2. WHEN registered logged in user just registers, he can see tooltip text: "In this month you have not saved any paper cup or plastic bag, but you have a chance to make the world clearer! Let's start it now! Add a habit to the tracker and enjoy of tracking saved items every day."

3. WHEN registered logged in user already tracks saved items, in this block he can see quantity of items (separately paper or/and plastic bags) that were saved in current month. This data based on data from tracker.

4. Analysis of statistics displays as comparison of saved items between current and previous day.

Assumption and Constraints:
1. Statistics counts items only for calendar month. For example if user start to track a habit 25th of month, statistics for current month shall show saved items from 25th till 30/31st of current month. It means that statistics will show data of 5 days of habit in current month.
2. Firstly as user just registers and logged in to personal cabinet he can see tooltip text without statistics.

**Comment by rsyvulko** [comment]
Not relevant.
