### ISSUE TITLE
[Personal data] Multiple addresses are automatically selected at the same time after the creation of a new addressd

### ISSUE THREAD

**Issue by LiliiaPalii** [ita-social-projects/GreenCity#2839]
**Environment:**  OS: Windows 10 Pro, Browser: Google Chrome, Version 90.0.4430.212
**Reproducible:** Always
**Build found:**   27.05.2021

**Preconditions**
The registered user is logged in
User chose services from the list on 'Деталі замовлення' tab and switch to 'Особисті дані' tab
Several different addresses created

**Steps to reproduce**
1. Scroll down to 'Адреса вивозу сміття'
2. Click on 'Додати адресу'
3. Click on 'Відмінити'

**Actual result**
Multiple addresses are automatically selected at the same time after the creation of a new address is canceled.
https://user-images.githubusercontent.com/55461895/120077965-b8625e00-c0b5-11eb-9c48-f9ad336b9bad.mp4

![Bug8](https://user-images.githubusercontent.com/55461895/120122376-19229100-c1b1-11eb-82d5-1c36d449722f.png)

**Expected result**
After clicking on the “Відмінити” button user is redirected to the “Особисті дані” tab.

**User story and test case links**
User story #2533

**Comment by Ol98** [comment]
not reproducible
