### ISSUE TITLE
Goals (Мої цілі) in Personal Cabinet

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#284]
As a registered logged in user I want to see my goals in personal cabinet so that I can track my tasks to be done.

Mockups:
![image](https://user-images.githubusercontent.com/53810790/68338618-8c564500-00eb-11ea-922c-8051991b6912.png)
![image](https://user-images.githubusercontent.com/53810790/68338630-98da9d80-00eb-11ea-9c54-048cf84c2165.png)

Acceptance criteria:

1. My goals section contain:
    a. title "My goals"
    b. tooltip with text "Here you can set your goals and complete them!" or list of chosen/added goals" and checkboxes near each goal.
    c. Text "Review all my goals" with hyperlink
    d. "Manage goals" button

2. WHEN registered logged in user just registered and logged in the personal cabinet under title "My goals" he can see tooltip with text "Here you can set your goals and complete them!" and "Manage goals" button.

3. WHEN registered logged in user clicks on "Manage goals" button, he can see popup. This feature is described in user story #334 #347  

4. WHEN registered logged in user clicks "Review all my goals", list of my goals expands with all my goals (already done and not done) and "Show less" button is available. 
WHEN registered logged in user clicks "Show less" button, list roll up to 3 goals.

Assumption and constraints:

**Comment by rsyvulko** [comment]
Not relevant.
