### ISSUE TITLE
[UBS courier] Improvement to 'Phone number' field validation

### ISSUE THREAD

**Issue by LiliiaPalii** [ita-social-projects/GreenCity#2840]
**Environment:** OS: Windows 10 Pro, Browser: Google Chrome, Version 90.0.4430.212
**Reproducible:** Always
**Build found:** 27.05.2021

**Actual result**
Validation 'Phone number' field on 'Personal data' tab, UBS courier page is carried out by the country code and the number of characters allowed for the field only. 
![зображення_2021-05-25](https://user-images.githubusercontent.com/55461895/120080858-56a8f080-c0c3-11eb-8362-17a5dfee6ded.png)

**Expected result**
Validating the 'Phone number' field is the connection of the library **google-libphonenumber**, which allows you to validate the phone number by country code, city, etc.

Related to:
User Story #2531

**Comment by ViktoriyaRyazhska** [comment]
Code phone number is duplicated
![image](https://user-images.githubusercontent.com/22353523/143489980-41d9e6f1-c7ab-46aa-b12a-1e474643cd96.png)

**Comment by KaterynaKhorosh** [comment]
![2022-01-28_13-41-25](https://user-images.githubusercontent.com/95848159/151541055-e604601a-5245-4f8b-8a75-fce101578c72.png)

Telephone number is displayed correctly with country and operator code
