### ISSUE TITLE
[Edit Profile] [API] If we changing "firstName" to incorrect values it returns us 200

### ISSUE THREAD

**Issue by TarasAmelianovych** [ita-social-projects/GreenCity#2849]
**Environment:** Swagger.
**Reproducible:** always.
**Build found:** commit 69ec25b

Preconditions

https://greencity-user.azurewebsites.net/swagger-ui.html#/ should be opened.
user should be signed in and authorized.

**Steps to reproduce**
1. Click on "user-controller", 
2. Click on **PUT** "/user/profile" and "Try it out"
3. Change "firstName" to incorrect values (I've tried less than 6 and more than 30 and special symbols)

**Actual result**
Code 200 User successfully updated.
If we will go to the GreenCity  profile we will see that the name was successfully changed

**Expected result**
Should return one of 400th code
And the name should not be changed on a GreenCity website

![EditProfileSwagger](https://user-images.githubusercontent.com/75034355/120505244-785ced00-c3cd-11eb-9548-d7f335ec13dd.PNG)
![EditProfileGreenCity](https://user-images.githubusercontent.com/75034355/120505356-90347100-c3cd-11eb-81be-6abb14dc99af.PNG)

**Comment by Ol98** [comment]
Done!
