### ISSUE TITLE
Tracker (Щоденний еко трекер) in Personal Cabinet

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#285]
As a registered user I want to see a tracker of habits so that I can logged how many items I did not use.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/68659192-7c04f680-053f-11ea-9e72-f3169d9092be.png)
![image](https://user-images.githubusercontent.com/53810790/68659225-8d4e0300-053f-11ea-9f34-9fa387e53b89.png)

*Acceptance criteria:*

1. This section is displayed with one default habit (plastic bags) if registered logged in see personal cabinet page.

2. Daily tracker consist:
    a. circle diagram with chosen habit to used to
    b. text "How many packages haven't you taken today?" for habit packages
    c. 8 icons of item for appropriate habit (with possibility by "+" to open 8 more in the next row)
    d. "more", "less" options
    e. text - "How can you evaluate your result today?"
    f. evaluation section with 3 blocks/buttons
    g. icon with advice on eco theme that relates to the habit

3. WHEN registered logged in user clicks on "Add new habit" button, popup with information displays. This feature is described in user story #330

4. WHEN registered logged in user hovers on each icon of item (under text "How many items you saved today"), it displays as active and he can see tooltip with quantity of chosen items.

5. WHEN registered logged in user click on icon of item, as a result quantity of chosen items displays in circle diagram in a cell of current day and this quantity of items remains active till the end of current day.

6. If registered logged in user wants to add more items as saved, he can choose them among the rest items that were inactive and chosen quantity shall be added to the number in cell for current day.

7. For each next day of habit icons of items become inactive.

8. Max quantity in each cell is not bigger than quantity of icons of items that are near the tracker.

10. WHEN registered logged in user clicks on evaluation buttons (super, normal, bad), cell of current day becomes in chosen color.

*Assumptions and Constraints:*

1. Registered and logged in user can track min one habit.
2. Registered logged in user can track items by clicking on each icon of items or click on the last that he chose and all before icons will be also counted without clicking on them.
3. For one day there are available up to 16 items for each habit that can be tracked.
4. Registered logged in user can evaluate current day and previous day many times.
5. Registered logged in user can log quantity of saved items only for current day and for previous day. All rest days for tracking are blocked.

**Comment by rsyvulko** [comment]
Not relevant.
