### ISSUE TITLE
BUG [ADMIN] "Create new place" button isn't available on the "Places" tab

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#286]
**Steps to reproduce:**
1. Go to http://greencityclient.herokuapp.com/
2. Login as Admin (e.g. 'User'='greencity.adm@gmail.com', 'Password'='Greencityadm123_')
3. Click on the dropdown list in the upper right corner above the map.
4. Choose 'Admin' 

**Actual result:**
"Create new cafe" button is available  in the upper right corner above the Places tab

**Expected result:**
"Create new place" button is available on the "Places" tab

[https://github.com/SoftServe-Social-Projects/GreenCity/issues/57](url)
[http://jira.softserve.academy/browse/GC-42](url)

**Comment by nhrab** [comment]
I approve to remain as it is now.
