### ISSUE TITLE
[UBS Admin Cabinet ] View violation of the current order

### ISSUE THREAD

**Issue by YuliyaTymkiv** [ita-social-projects/GreenCity#2862]
**As an** administrator, **I want** to see the details of user rule violation added to the current order **so that** I will be aware of the issue 

**Assumptions & Constraints**
1. Different Administrator types might have different rights sets

**Preconditions**

1. User is logged in as administrator.
2. Administrator has opened an order from current orders view table
3. Administrator has already added violation for current order

**Business rules**

1. Only administrators with access should be able to view Admin Cabinet
2. Violations should be displayed for a user who created an order, not the receiver.

### Acceptance Criteria

1. In the field “Поточне замовлення” of the section “Порушення клієнта” numeric character “1” should be linked to the related user rule violation record made in the current order.

2. When administrator clicks on “1” in the field “Поточне замовлення”, the pop-up with details of related violation record should be opened.

3. The pop-up shall include the following fields:

Field title | Condition | Requirements
-- | -- | --
“Порушення. Замовлення №&lt;12345&gt;” | Disabled | Order ID (e.g.12345) is received from order details form [admin cabinet]
“Ступінь порушення” | Disabled | Received from violation form.The administrator sees 2 radio buttons of violation levels: “Легке” and “Серйозне”. Only one is chosen.
“Опис порушення” | Disabled | Received from violation form.
“Фотографії порушення” | Disabled&nbsp; (view only) | Received from violation form.Files are displayed in a 3X2 photo matrix
“Дата” | Disabled | Received from violation form.
“Додано” | Disabled | Received from violation form.

</div></b>

4. When the administrator clicks on the photo, it should be opened and enlarged in a separate pop-up window.  The administrator should be able to scroll photo gallery using left/right arrows. If the administrator clicks outside the pop-up, it should be closed.

5. Buttons "Зберегти" and "Скасувати" should be disabled by default.

6. Edit icon and Delete icon should be enabled by default (described in stories #2863 and #2864 )

7. Administrator can close the pop-up with violation details by clicking on “X” (close icon)

**Mockup:**

https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=18992%3A96252

**Out of scope**

1. Edit violation in the current order
2. Delete violation from  the current order

**Epic link**
E.g.: Epic #2195 

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by yulianagoncharenko** [comment]
[Zero Violations.postman_collection_upd.json](https://github.com/ita-social-projects/GreenCity/files/15348138/Zero.Violations.postman_collection_upd.json)
Postman collection for Zero Violations case API testing

**Comment by yulianagoncharenko** [comment]
[Zero Violations.postman_collection.json](https://github.com/ita-social-projects/GreenCity/files/15357764/Zero.Violations.postman_collection.json)
API testing for order with no violations
