### ISSUE TITLE
[Edit Profile] The 'Save' button is disabled when the user signs in using Google mail and wants to edit his Profile

### ISSUE THREAD

**Issue by SerhiiStarshoi** [ita-social-projects/GreenCity#2869]
**Environment:** Safari 14.1, macOS Big Sur 11.3
**Reproducible:** always
**Build found:** 08.06.2021

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in to the GreenCity as a User using Google mail
3. Click on the 'Edit Profile' tab
4. Pay attention to the 'Name' input field, which consists with Name and Surname.
5. Pay attention to the 'Save' button

**Actual result**
The 'Save' button is disabled when the user signs in using Google mail and wants to edit his Profile

**Expected result**
The 'Save' button is enabled when the user signs in using Google mail and wants to edit his Profile

![photo_2021-06-08 12 09 02](https://user-images.githubusercontent.com/32453285/121157571-5a224180-c852-11eb-8e6f-349e7fd95120.jpeg)

**Comment by MyroslavaVynokur** [comment]
Bug is still reproduced
<img width="519" alt="Screenshot 2021-11-15 at 22 15 27" src="https://user-images.githubusercontent.com/34717146/141847813-543020d4-53c9-43da-a95b-122c1f5e003c.png">
