### ISSUE TITLE
BUG [ADMIN] The name, number of fields, and buttons in the "Create a new place" popup do not meet the requirements

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#287]
**Steps to reproduce:**
1. Go to http://greencityclient.herokuapp.com/
2. Login as Admin (e.g. 'User'='greencity.adm@gmail.com', 'Password'='Greencityadm123_')
3. Click on the dropdown list in the upper right corner above the map.
4. Choose 'Admin'
5. Click on 'Create new cafe' button

**Actual result:**
Admin sees popup with next fields:
1. input field 'Name'
2. input field 'Enter address'
3. drop-down 'Select category'
4. drop-down 'Select specification'
5. drop-down 'Discount'
6. 'Add discount' button
7. drop-down 'Select day', spinner fields 'from:', 'to:'
8. 'Add day' button
9. 'Add photo' button
10. 'Submit' button
11. 'Close' button

**Expected result:**
Admin sees popup with next fields:
1. input field 'Type/Category'
2. input field 'Name'
3. input field 'Address'
4. input field 'Working times'
5. "Save" button

[https://github.com/SoftServe-Social-Projects/GreenCity/issues/57](url)
[http://jira.softserve.academy/browse/GC-42](url)

**Comment by rinagoroh** [comment]
User story have to be changed.

**Comment by nhrab** [comment]
I approve to remain as it is now.
