### ISSUE TITLE
[UBS Controller] Return bonus details (date, amount, reason)

### ISSUE THREAD

**Issue by Liubchik26** [ita-social-projects/GreenCity#2889]
**Description :**
1) Create a new controller that will return information about the user's bonuses.
2) Create two Dto's wich return information about user's points_to_use
3) look on figma https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=14622%3A75418
4) It should return json with information about all user's bonuses. 
5) If pointsToUse = 0 for ubsUser we don't display anything. 
6) write tests for controller, methods and dto.
7) Work with tables in database: 
![image](https://user-images.githubusercontent.com/42591139/122418428-dd4e4080-cf92-11eb-89cb-ce5dee16ab72.png)

**Comment by MyroslavaVynokur** [comment]
Client controller 'Get user's bonuses' returns info about bonuses which user had used (amount, date and order)

<img width="980" alt="Screenshot 2021-12-01 at 22 49 56" src="https://user-images.githubusercontent.com/34717146/144311813-adc2535d-e615-4d39-b375-c753e4397c87.png">
