### ISSUE TITLE
[UBS courier] Inconsistent title of the service on the order page

### ISSUE THREAD

**Issue by LiliiaPalii** [ita-social-projects/GreenCity#2890]
**Environment:** OS: Windows 10 Pro, Browser: Google Chrome, Version 90.0.4430.212
**Reproducible:** Always
**Build found:** 10.06.2021

**Preconditions**
Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. Go to order creation
2. Pay attention to the title of the service

**Actual result**
![заголовок](https://user-images.githubusercontent.com/55461895/121666496-fe55f380-cab1-11eb-9d32-f53fe1a50a42.png)

**Expected result**
![Заголовок мокап](https://user-images.githubusercontent.com/55461895/121666801-51c84180-cab2-11eb-85c7-a451e1d3348b.png)

**User story and test case links**
 User story #2198 
Test case GC-2039

**Comment by SofiiaBaziv** [comment]
fixed in https://github.com/ita-social-projects/GreenCity/issues/2930
