### ISSUE TITLE
[UBS Courier] The Headers 'Послуги', 'Еко Магазин', 'Коментар' have different fonts and font sizes than on mockups

### ISSUE THREAD

**Issue by SerhiiStarshoi** [ita-social-projects/GreenCity#2895]
**Environment:** Safari 14.1, macOS Big Sur 11.3
**Reproducible:** always
**Build found:** 15.06.2021

**Steps to reproduce**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in to the GreenCity as a User
3. Click on the 'UBS' tab
4. Pay attention to the headers 'Послуги', 'Еко Магазин', 'Коментар' 

**Actual result**
The headers have different fonts and font sizes than on mockups
(https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=13717%3A524)

1. Header 'Послуги' has font size 28 px and font-family Roboto
![photo_2021-06-15 17 53 34](https://user-images.githubusercontent.com/32453285/122075319-a8ab7f00-ce02-11eb-956f-6bbb1e29f4a0.jpeg)

2. Header 'Еко Магазин' has font size 28 px and font-family Roboto
![photo_2021-06-15 17 53 29](https://user-images.githubusercontent.com/32453285/122075353-aea16000-ce02-11eb-9c2a-3be0b36bf5fd.jpeg)

3. Header 'Комент' has font size 28 px and font-family Roboto
![photo_2021-06-15 17 48 42](https://user-images.githubusercontent.com/32453285/122075382-b3feaa80-ce02-11eb-8fad-e4e74a061868.jpeg)

**Expected result**
1. Header 'Послуги' has font size 24 px and font-family Lato
![photo_2021-06-15 17 56 16](https://user-images.githubusercontent.com/32453285/122075789-0213ae00-ce03-11eb-8dd0-a33e56317319.jpeg)

2. Header 'Еко Магазин' has font size 24 px and font-family Lato
![photo_2021-06-15 17 56 01](https://user-images.githubusercontent.com/32453285/122075826-06d86200-ce03-11eb-894a-9bbdc00a8e1e.jpeg)

3. Header 'Комент' has font size 24 px and font-family Lato
![photo_2021-06-15 17 55 40](https://user-images.githubusercontent.com/32453285/122075861-0dff7000-ce03-11eb-863b-b76277f09199.jpeg)

**User story and test case links**
E.g.: "User story #2379 
[Test case](https://jira.softserve.academy/browse/GC-1935)"

**Comment by MyroslavaVynokur** [comment]
Verified - done
