### ISSUE TITLE
[UBS Admin Cabinet ] Order payment details

### ISSUE THREAD

**Issue by YuliyaTymkiv** [ita-social-projects/GreenCity#2898]
**As an** administrator, **I want** to  see order payment details **so that** I check what amount and when was paid or returned.

**Assumptions & Constraints**
1. Different Administrator types might have different rights sets
2. The field of total payment “Замовлення оплачено в розмірі” is interlinked with the field “Оплата” of the current orders view table. 

**Preconditions**
1. User is logged in as administrator.
2. The administrator has navigated to the Orders tab and has opened an order from current orders view table

**Business rules**
1. Only administrators with access should be able to view Admin Cabinet

### Acceptance Criteria

1. Section title is “Оплата замовлення” 

2. The field of total payment “Замовлення оплачено в розмірі”  contains float number with 2 digits.e.g (150.00 грн) No upper limit. May be equal to or greater than 0. 

3. The total payment “Замовлення оплачено в розмірі” is calculated by formula : 
total payment = payment amount 1 + payment amount 2  - payment amount 3 with comment “зарахування на бонусний рахунок” -  payment amount 4 with comment “повернення коштів” (e.g.: 200 + 300 -100 - 50 = 350.00 грн) 

4. The system should count all payment amounts that are recorded in the table with payment details

5. Each time when a new payment amount is added, the system should dynamically recalculate the total payment “Замовлення оплачено в розмірі”

6. Table with payment details and its attributes:

Дата оплати | ID платежу | Сума | Коментар/Чек
-- | -- | -- | --
Payment date: DD/MM/YYYY Mandatory | Payment ID. Integers in format: &nbsp;&nbsp;№&lt;payment ID&gt;,&nbsp;  (e.g.№12345 ). No upper limit.  Optional for “зарахування на бонусний рахунок” and “повернення коштів” | Payment amount. Float number with 2 digits.e.g (150.00 грн). No upper limit.  May be greater than 0 only. Mandatory | Possible options: link;  зарахування на бонусний рахунок; повернення коштів. Optional for&nbsp; payment system response

</div></b>

7. All fields of the table are disabled and the data is received from the payment system response or from the payment form in case the payment was added manually (separate story)

**Mockup**

![Payment details](https://user-images.githubusercontent.com/82950010/122193607-4eabc780-ce9d-11eb-907b-658bf5833605.JPG)

**Out of scope**
1. Adding payment manually

**Epic link**
E.g.: Epic #2195 

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by SofiiaHavsot7** [comment]
Postman collection for API testing
[Overpayment Copy.postman_collection.json](https://github.com/ita-social-projects/GreenCity/files/15375489/Overpayment.Copy.postman_collection.json)
