### ISSUE TITLE
[UBS Admin Cabinet] Overpayment and underpayment messages

### ISSUE THREAD

**Issue by YuliyaTymkiv** [ita-social-projects/GreenCity#2899]
**As an** administrator, **I want** to see if there is overpayment or underpayment in the current order, **so that** I know whether to return the unused amount to the client or ask for additional payment.

**Assumptions & Constraints**
N/A

**Preconditions**
1. User is logged in as administrator.
2. Administrator  has opened an separate order from current orders view table 

**Business rules**
1. Only administrators with access should be able to view Admin Cabinet

### Acceptance Criteria

1. The system should compare the following values each time, when they are changed:
          **a.** **confirmed order total “Сума до оплати” (column “Підтверджена к-сть”)** with total payment “Замовлення оплачено в розмірі” on the order statuses Сформовано; Узгодження; Підтверджено; Не виконано.
          **b.** **actual order total “Сума до оплати” (column “Вивезена к-сть”)** with total payment “Замовлення оплачено в розмірі” on the order statuses На маршруті; Виконано; Привезе сам; Скасовано.
 
2. If the confirmed or actual order total "Сума до оплати" (depends on the order status) is greater than total payment "Замовлення оплачено в розмірі", the system shows the following message under the table with packages quantity and order total details:  **“Потрібно доплатити <underpayment грн>”,**  where underpayment is float number with 2 digits (250.00), greater than 0 and  calculated by formula: 
          **a.** on the order statuses Сформовано; Узгодження; Підтверджено; Не виконано: confirmed order total "Сума до оплати" - total payment "Замовлення оплачено в розмірі" = underpayment
          **b.** on the order statuses На маршруті; Виконано; Привезе сам; Скасовано: actual order total "Сума до оплати" - total payment "Замовлення оплачено в розмірі" = underpayment
 
3. If the confirmed or actual order total "Сума до оплати" (depends on the order status) is less than total payment "Замовлення оплачено в розмірі", the system shows the following message under the table with packages quantity and order total details: **“Переплата <overpayment грн>”,** where overpayment is float number with 2 digits (250.00), greater than 0 and calculated by formula: 
          **a.** on the order statuses Сформовано; Узгодження; Підтверджено; Не виконано: total payment "Замовлення оплачено в розмірі" - confirmed order total "Сума до оплати" = overpayment
          **b.** on the order statuses На маршруті; Виконано; Привезе сам; Скасовано: total payment "Замовлення оплачено в розмірі" - actual order total "Сума до оплати" = overpayment

**Mockup**

![over_underpayment notifications](https://user-images.githubusercontent.com/82950010/122220275-d9e68680-ceb8-11eb-8e44-752410f0d6ce.JPG)

**Out of scope**

**Epic link**
E.g.: Epic #2195 

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] sample task.

**Comment by SofiiaHavsot7** [comment]
[Overpayment Copy.postman_collection.json](https://github.com/ita-social-projects/GreenCity/files/15375448/Overpayment.Copy.postman_collection.json)
Postman collection for API testing
