### ISSUE TITLE
Register in application with credentials

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#29]
As unregistered user I want to be able to register so that I can have wide access to the application (save favorite places in a profile, leave a feedback for a place).
(new version #385 )
Mockups:
![image](https://user-images.githubusercontent.com/53810790/62836242-ed47bb80-bc69-11e9-9117-b39d21e26ef7.png)
![image](https://user-images.githubusercontent.com/53810790/63437956-37802800-c434-11e9-8977-506239194c7e.png)

Acceptance Criteria:
1. WHEN Unregistered user accesses the main page of application, THEN on the upper right side of the window he/she can see "Sign Up" button.

2. WHEN Unregistered user clicks on the "Sign Up" button, THEN he/she can see popup with the next fields to fill in:
a. First Name (max chars 20)
b. Last Name (max chars 20)  
c. Email Address (with check of existence @....com in filled in text)
d. Password
All fields, mentioned above, should be obligatory to enter.  

3. Criteria to create a password for Unregistered user should be the next:
a. Be a minimum of eight (8) characters in length
b. Contain at least one (1) character from three (3) of the following categories:
c. Uppercase letter (A-Z)
d. Lowercase letter (a-z)
e. Digit (0-9)
f. Special character (~`!@#$%^&*()+=_-{}[]\|:;”’?/<>,.)

4. WHEN Unregistered user fills in all necessary fields AND clicks "Sign Up" button, THEN he/she see popup with text "You successfully registered on this site. Please verify your email address in mailbox". And at once unregistered user should receive a verification email about registration in the application to his/her email address, mentioned in form.

5. Verification email is active during 24 h after registration.

6. Verification email should contain:
a. subject" Verify your email address"
b. text in email:
" *Verify your email address to complete registration* (in bold)
Hi /User name/,
Thanks for your interest in joining /Name of application/! To complete your registration, we need you to verify your email address.
c.  "Verify Email" button

7. When Unregistered user clicks "Verify Email" button, THEN system should navigate him/her to the initial application's page with "Sign in" button available.

**Comment by GuN41K** [comment]
d. Password (max 8 digits long)? I think that bad pattern for password, because it is so simple.

**Comment by Marieye** [comment]
BUG (#253) [Sign Up page] Mistake in error message when entering registered email address

**Comment by Marieye** [comment]
BUG (#253 )

**Comment by Marieye** [comment]
BUG (#253) [Sign Up page] Mistake in error message when entering registered email address
