### ISSUE TITLE
Bug [Admin]: 'Save' button is absent on 'Place' tab

### ISSUE THREAD

**Issue by Mari1ana** [ita-social-projects/GreenCity#290]
Steps to reproduce:
1. Go to http://greencityclient.herokuapp.com/.
2. Login as Admin.
3. Click on dropdown list of 'Admin' button on the top right corner of the window.
4. Select 'Admin'.
5. Select 'Place' tab.
6. Pay attention to the right down corner.

Actual result:
'Save' button is not present there.

Expected result;
'Save' button is present there.

![Admin 'Save' button](https://user-images.githubusercontent.com/57095740/67795477-fb49f300-fa86-11e9-9b99-3f7210c9ed70.png)
![Admin 'Save' button-2](https://user-images.githubusercontent.com/57095740/67795721-5aa80300-fa87-11e9-95a0-0ba616344795.png)

https://ssu-jira.softserveinc.com/browse/GCS-44

**Comment by Bastarn78** [comment]
This bug has already been created. Please check previous bugs. thank you
