### ISSUE TITLE
[Controller UBS] Order detail, display user rule violations for the current order made by the user

### ISSUE THREAD

**Issue by rusanovscaia** [ita-social-projects/GreenCity#2902]
Return information about user rule violations for the current order made by user.
field “Поточне замовлення” - violation from current order. Only one numeric character - 0 or 1 - is allowed.
If there is no violation from the current order, the system should display 0. Disabled

![image](https://user-images.githubusercontent.com/82950010/121037884-812c3500-c7b8-11eb-97e3-263b06bd9445.JPG)

**Comment by MyroslavaVynokur** [comment]
Management controller - Get details of user violation
Verified - works as expected

<img width="1010" alt="Screenshot 2021-12-03 at 14 05 57" src="https://user-images.githubusercontent.com/34717146/144599860-b00c167c-6614-4396-8b9a-10bdfea4b502.png">
