### ISSUE TITLE
Bug [Admin]: Extra option 'Search' is present on 'Place' tab

### ISSUE THREAD

**Issue by Mari1ana** [ita-social-projects/GreenCity#291]
Steps to reproduce:

1. Go to http://greencityclient.herokuapp.com/.
2. Login as Admin.
3. Click on dropdown list of 'Admin' button on the top right corner of the window.
4. Select 'Admin'.
5. Select 'Place' tab.
6. Pay attention to the controls located above the grid.

Actual result:
'Search' text field and 'Search' button are displayed above the grid.

Expected result:
Nothing is located above the grid.

![Admin 'Search' option](https://user-images.githubusercontent.com/57095740/67796815-5977d580-fa89-11e9-88cc-898fa2c14ddf.png)
![Admin 'Search' option-2](https://user-images.githubusercontent.com/57095740/67796816-5977d580-fa89-11e9-8df1-3719467aa740.png)

https://ssu-jira.softserveinc.com/browse/GCS-44

**Comment by RostyslavKhasanov** [comment]
Hi, this search field must be above the table in user and place tab on the admin page. It was created by this user story [Search for entry by name](https://github.com/SoftServe-Social-Projects/GreenCity/issues/59)
