### ISSUE TITLE
Bug [Admin]: No data represented in places grid on 'Place' tab when new place was created

### ISSUE THREAD

**Issue by Mari1ana** [ita-social-projects/GreenCity#292]
Steps to reproduce:

1.  Go to http://greencityclient.herokuapp.com/
2. Login as Admin
3. Click on dropdown list of 'Admin' button on the top right corner of the window
4. Select 'Admin'
5. Select 'Place' tab
6. Click 'Create new place' button.
7. Enter valid name (e.g. 'CoffeeLab')
8. Enter valid address (e.g. Lviv, Naykova 7d)
9. Select category (e.g. 'Food')
10. Select specification (e.g. 'Own cup')
11. Enter schedule (e.g. Monday 08:00 - 19:00)
12. Click 'Submit' button
13. Pay attention to the places grid

Actual result:
No data appeared in the grid

Expected result:
Information about created place appeared in on the top of the grid

![Admin 'Place' grid](https://user-images.githubusercontent.com/57095740/67807533-a6fe3d80-fa9d-11e9-88e1-873b1967f1ba.png)

https://ssu-jira.softserveinc.com/browse/GCS-47

**Comment by nazarvladyka** [comment]
This is happens because when admin adds a place it's automatically becomes - approved, and appears on tab with approved places.
