### ISSUE TITLE
The pop-up window about defining location doesn't appear when unregistered user accesses the application

### ISSUE THREAD

**Issue by Olena22** [ita-social-projects/GreenCity#293]
Steps to reproduce:

1.Go to http://greencityclient.herokuapp.com/.
2.Sign in (e.g. email:'oshkapiak@gmail.com', password:'Ichwill1*')

Actual result:
The pop-up window about defining location doesn't appear when unregistered/registered user accesses the application

Expected result: 
The pop-up window about defining location doesn't appear when unregistered/registered user accesses the application (see attachment)
![loc](https://user-images.githubusercontent.com/57154115/67807737-13793c80-fa9e-11e9-8e9b-6d81ebc54173.png)

User Story#235
https://ssu-jira.softserveinc.com/browse/GCS-48
https://ssu-jira.softserveinc.com/browse/GCS-49
https://ssu-jira.softserveinc.com/browse/GCS-41

**Comment by lenadgit** [comment]
ready
