### ISSUE TITLE
[Order form] The dropdown with address details doesn't display correctly.

### ISSUE THREAD

**Issue by karynashvets** [ita-social-projects/GreenCity#2936]
Environment: Microsoft Windows 10 Home, Version 2004
Google Chrome version 91.0.4472.114 (Official Build) (64-bit)
Reproducible: always
Build found: 2021-06-30

Steps to reproduce:

1. Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in as a registered user 
3. Click on the 'UBS courier' tab
4. Add any service (e.g 'Old clothes' = 'Number of packages 11')
5. Click the 'Next' button
6. Fill out personal data 
7. Click on 'Add address'
8. Fill out any address 

Actual result:
The dropdown with address doesn't correspond to the mock-up (see attachments below).
<img width="454" alt="gc mockup" src="https://user-images.githubusercontent.com/85613711/123948650-534aa280-d9aa-11eb-93db-ab608667e545.png">
<img width="939" alt="greencity ui" src="https://user-images.githubusercontent.com/85613711/123948665-580f5680-d9aa-11eb-94e9-875d00093ed9.png">

Expected result:
UI element corresponds to the mock-up.

User story and test case links
User story #2199

**Comment by Ol98** [comment]
not reproducible
