### ISSUE TITLE
[UBS Courier tab] The system does not save user's unfinished order in 'Мій кабінет', when user clicks on 'Відмінити' and selects to save the order

### ISSUE THREAD

**Issue by oksanasmetanyuk** [ita-social-projects/GreenCity#2946]
**Environment:** macOS High Sierra 10.13.6, Google Chrome, version 91.0.4472.114 (Official Build) (x86_64).
**Reproducible:** always.
**Build found:** July 1, 2021.

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Click on 'Увійти'
3. Log in as a registered user (e.g. Login:   '**oksana.smet@yahoo.com**'   Password: '**Motherload1!**')
4. Click on 'UBS кур'єр' tab
5. Enter a number of bags into any 'Кількість пакетів' field so that the total price is more than 500 hrn
6. Click on 'Далі' button on bottom of 'Деталі замовлення' page
7. Click on 'Відмінити' button on bottom of 'Особисті дані' page
8. From the pop up menu, click on 'Так, вийти' button (see screenshot attached)
9. On the homepage menu, select 'Мій кабінет'

**Actual result**
No saved orders are present in 'Мій кабінет'.

**Expected result**
The last unfinished order should be saved in 'Мій кабінет'.

**User story and test case links**
#2196 #2379 
[Test case GC-2052](https://jira.softserve.academy/browse/GC-2052)

**Labels to be added**
"Bug", "UBS Courier", "UBS", "Order Form", "GreenCityUBS", Priority ("pri: High"), Severity ("severity: minor"), Type ("Functional").

![Screen Shot 2021-07-01 at 21 59 21](https://user-images.githubusercontent.com/85681218/124178598-546af500-daba-11eb-8241-66d555be97de.png)

**Comment by Edw1x** [comment]
No logic made for this function

**Comment by oksanasmetanyuk** [comment]
The requirement for this function is included in the Change request #2379 to User Story #2196. A new updated Defect has been logged: https://github.com/ita-social-projects/GreenCity/issues/2959
