### ISSUE TITLE
[List view] View list is not displayed correctly according to the selected template 

### ISSUE THREAD

**Issue by AlonaLutsenko** [ita-social-projects/GreenCity#2971]
Environment: Microsoft Windows 10 Enterprise
Google Chrome version 91.0.4472.124 (Official Build) (64-bit)
Reproducible: always
Build found: 2021-07-05

**Preconditions**

1. Go to https://ita-social-projects.github.io/GreenCityClient/
2. Open 'Eco news' page
3. Content items are displayed as a Gallery by default

**Steps to reproduce**
1. Maximize  browser window width to 1440px. 
2. Set browser window width to 1020px.

**Actual result**
All labels are displayed and aligned according to the list.

![tempsnip1](https://user-images.githubusercontent.com/71566280/124581170-87fea400-de59-11eb-8272-f6c4adfd0a5e.png)

**Expected result**
All labels should be displayed and aligned according to the grid.

![tempsnip2](https://user-images.githubusercontent.com/71566280/124581187-8c2ac180-de59-11eb-903e-ec0a7b35411a.png)

**User story and test case links**
Test case [#669](https://jira.softserve.academy/browse/GC-669)
Test case [#339](https://jira.softserve.academy/browse/GC-339)
Test case [#674](https://jira.softserve.academy/browse/GC-674)

**Comment by Ol98** [comment]
not reproducible
