### ISSUE TITLE
The dashboard for the selected place does not appear after clicking the place name in the sidebar

### ISSUE THREAD

**Issue by Markezo** [ita-social-projects/GreenCity#299]
**Steps to reproduce:** 

1. Open the site http://greencityclient.herokuapp.com/
2. Verify that names of places are displayed in the sidebar list
3. Move a cursor on the name of place in the sidebar list

**Actual result:**
Location information is not displayed

**Expected result:**
Name of place become active (for example, bigger text and in bold)

![67834362-e6557a00-faef-11e9-86ea-b3e5bdbf1ff0 1](https://user-images.githubusercontent.com/42619313/67834384-f2d9d280-faef-11e9-8b0a-43e0b422d6be.png)

#147

**Comment by lenadgit** [comment]
Each selected location contains information. Popup with details appears after clicking on the pointer on the map http://joxi.ru/YmE9VQzHwz0n3m
