### ISSUE TITLE
[UBS courier] Field "Your order numbers"  is displayed incorrectly

### ISSUE THREAD

**Issue by OKalynivska** [ita-social-projects/GreenCity#2990]
**Environment:** Windows 10 Pro, Browser: Google Chrome 91.0.4472.124 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** July 13 2021

**Preconditions**
1.Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/
2.Click on 'Увійти'
3.Log in as a registered user .
4.Click on 'UBS кур'єр' tab

**Steps to reproduce**
1.On "Деталі замовлення" step choose the order amount (Minimal amount is 500 UAH)
2.In "Еко магазин" block type first order number and second order number(e.g., 1111111111,2222222222)
3.Click on "Далі" button
4.Fill in the fields with correct data
5.Click on "Далі" button
6.Check the "Доставка з Еко магазину" block

**Actual result**
Numbers are displayed  with comma after second number
[![Screenshot-6.png](https://i.postimg.cc/mkW4cXWm/Screenshot-6.png)](https://postimg.cc/HczRRtxM)

**Expected result**
The text "Номери ваших замовлень:  
1111111111, 2222222222  " is displayed.
[![Screenshot-9.png](https://i.postimg.cc/BvfRB8Vv/Screenshot-9.png)](https://postimg.cc/hXMCSGgF)

**User story and test case links**

[Test case]https://jira.softserve.academy/browse/GC-2060
                https://jira.softserve.academy/browse/GC-2059

**Labels to be added**
"Bug"

**Comment by s1auka** [comment]
The same bug as https://github.com/ita-social-projects/GreenCity/issues/2949
