### ISSUE TITLE
The message in the "Delete" popup in Places tab doesn't meet the requirements

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#300]
**Steps to reproduce:**
1. Go to http://greencityclient.herokuapp.com/
2. Login as Admin (e.g. 'User'='greencity.adm@gmail.com', 'Password'='Greencityadm123_')
3. Click on the dropdown list in the upper right corner above the map.
4. Choose 'Admin'
5. Click on 'Delete' button next to one of the places

**Actual result:**
Popup with the information appears:
Message: "Are you sure you want to delete this item?"
"Cancel" button
"Delete" button

**Expected result:**
Popup with the information appears:
Message: "Do you really want to delete "_place name_"?"
"Cancel" button
"Delete" button"

[https://github.com/SoftServe-Social-Projects/GreenCity/issues/112](url)
[http://jira.softserve.academy/browse/GC-57](url)

**Comment by nhrab** [comment]
I approve to remain as it is now.
