### ISSUE TITLE
[UBS Certificate] Incorrect discount after canceling certificates.

### ISSUE THREAD

**Issue by Dnagor** [ita-social-projects/GreenCity#3018]
Environment: Windows 10, Chrome 92.0.4515.107.
Reproducible: always.

Steps to reproduce

Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
Fill in the service fields so that the amount of the order exceeds UAH 500. 
Add three or more active certificates.For Example:
Add certificate "5553-3247".
![Screenshot_54](https://user-images.githubusercontent.com/82941886/126863985-36f05ef1-c938-42f3-84de-b25ec93bd3a6.png)
Add certificate "3999-0001".
![Screenshot_55](https://user-images.githubusercontent.com/82941886/126863986-faba470c-ab0f-4cf0-90a9-b9f701e18450.png)
Add certificate "5553-3248".
![Screenshot_56](https://user-images.githubusercontent.com/82941886/126863987-ca0d0db2-a528-4a2e-8136-b3b7cb07d94b.png)
Quicly cancel two last certificates.

**Actual result**
![Screenshot_57](https://user-images.githubusercontent.com/82941886/126863984-cce8a8bb-66ba-4278-a008-474a39b4679b.png)
![CertificateError](https://user-images.githubusercontent.com/82941886/126864112-68cdc84f-6287-4880-86f3-475324663453.png)

**Expected result**
Correct discount of only one certificate which is left.
This situation is reproducable with certificates and order amounts.

**User story and test case links**
"User story #2329

**Comment by KaterynaKhorosh** [comment]
added 3 ceritifcates, canceled 2 of them, total amount is correct
![2022-01-17_11-55-19](https://user-images.githubusercontent.com/95848159/149747845-433bac3c-e0c5-4f6e-9516-24b5362c3f02.png)
