### ISSUE TITLE
[UBS Courier] The format of the phone number isn't displayed correctly and there is an error in the word 'certificate' on the "Confirmation" page

### ISSUE THREAD

**Issue by VictoriaBadenko** [ita-social-projects/GreenCity#3023]
Environment: Windows 10 Pro, Browser: Google Chrome 91.0.4472.124 (Official Build) (64-bit)
Reproducible: always
Build found: July 28, 2021

Preconditions:
Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/
Click on 'Увійти'
Log in as a registered user .
Click on 'UBS кур'єр' tab.

Steps to reproduce
1.Fill in the fields with the correct data to the last step
2.Check the "Отримувач" block

Actual result
The format of the phone number in the "Отримувач" block is not displayed correctly.
![001](https://user-images.githubusercontent.com/81874906/127323383-6fe5bfa3-8fa9-435c-863f-6687006a03cf.png)
There is an error in the word 'certificate'.
![IMG_20210728_144358_061](https://user-images.githubusercontent.com/81874906/127323569-c7aa02dd-31d5-438f-92a0-d4182c43e253.jpg)

Expected result
The phone number is displayed in this format:
![IMG_20210728_141750_630](https://user-images.githubusercontent.com/81874906/127323693-69e130a6-7c96-4b7d-bd30-9c2a00c59f65.jpg)
The word 'certificate' is such as:
![002](https://user-images.githubusercontent.com/81874906/127325821-335bfe84-cc2d-4962-9b64-1bbc24181d00.png)

User story and test case links
[Test case]https://jira.softserve.academy/browse/GC-2062

Labels to be added
"Bug"

**Comment by MyroslavaVynokur** [comment]
**Actual result:**

The format of the phone number in the "Отримувач" block is not displayed correctly
<img width="238" alt="Screenshot 2021-12-01 at 20 26 01" src="https://user-images.githubusercontent.com/34717146/144292016-4817a36a-5ad8-4237-9c71-fc8a760e7cf7.png">

**Comment by BobNazar** [comment]
![image](https://user-images.githubusercontent.com/76586511/161018558-267f9544-4d0b-4b50-8353-f471d7e8f2a3.png)
displayed correctly
