### ISSUE TITLE
Step 0.1. (choose location)

### ISSUE THREAD

**Issue by AndriyHoroschko** [ita-social-projects/GreenCity#3033]
**As a** user, **I want to** be able to select the location where the service will be provided **so that** I could place an order.

**Preconditions:**
The registered user is logged in

**Business rule:**
Only Kyiv and Kyiv region citizens are able to submit the Order form.

**Acceptance Criteria:**
1. The user must be able to select a location after he put button “Замовити Кур’єра” on the home page.
2. The user shall see the title on the top of pop-up: “Вітаємо в УБС! Спочатку оберіть свою локацію:”. Under the title the user shall see a drop-down with 2 variants: “м. Київ” and “Київська обл.” 

![Pop-up1](https://user-images.githubusercontent.com/82659440/127987087-66993073-02a4-474e-8101-9056bef5d451.png)

3. The background for this pop-up should be the page, from which the popup was entered.
4. In pop-up the user should see the list of locations:
“м. Київ”
“Київська обл.”
At the first visit, the first shown location option by default is “м. Київ”.

![Pop-up1](https://user-images.githubusercontent.com/82659440/127987125-856234dd-d79e-4163-97c1-b259afd010f0.png)

5. After the user has selected the location, he can confirm his choice by clicking the button “Продовжити”. The button “Продовжити” is always active. If the user does not perform the action with the selection of the location and clicks the button “Продовжити”, so then will be chosen “м. Київ” by default. 
6. By clicking on the button “Продовжити”, the user shall be redirected to the first page of the order form.
If the user has selected “м. Київ”, must be used rules for Variant 1 (Kyiv). If the user has selected “Київська обл.”, must be used rules for Variant 2 (Kyiv region).  Rules are described in Change request #3032.
7. The system should remember the chosen location so the user will see his previously chosen location in the first place by default during the next login into the system.
8. By clicking on the button “Назад”,  on “X” (close), or outside of the pop-up, the pop-up should close, and the user shall be redirected to the page, from which the popup was entered. The button “Назад” is always active. 
 
 

**EPIC:** UBS courier #2195

**Comment by rostikdoroshenko** [comment]
@AndriyHoroschko, please, check this url  https://nowaste.com.ua/  
Maybe it should be https://ita-social-projects.github.io/GreenCityClient/#/ubs/order

**Comment by AndriyHoroschko** [comment]
> @AndriyHoroschko, please, check this url https://nowaste.com.ua/ in step 1, 3 and 8
> Maybe it should be https://ita-social-projects.github.io/GreenCityClient/#/ubs/order ?

It should be https://nowaste.com.ua
This is the customer's website (УкраїнаБезСміття)

**Comment by rostikdoroshenko** [comment]
@ViktoriyaRyazhska

**Comment by AndriyHoroschko** [comment]
> @AndriyHoroschko, please, check this url https://nowaste.com.ua/ in step 1, 3 and 8
> Maybe it should be https://ita-social-projects.github.io/GreenCityClient/#/ubs/order ?

changes have been made, please check

**Comment by YanaTarasiuk** [comment]
Acceptance criteria 2. The text in the pop-up title should be changed to: "Вітаємо в УБС! Оберіть локацію вивезення відходів. Наразі ми працюємо тільки в м. Києві та передмістті столиці в радіусі 20 км." in UA and "Welcome to UBS! First, choose the location of waste disposal. Currently, we work in Kyiv and the suburbs." in EN.
