### ISSUE TITLE
[Edit Profile] Error message is displayed after entering one 'space' in the "Name" field

### ISSUE THREAD

**Issue by LimeGrey** [ita-social-projects/GreenCity#3034]
**Environment:** Windows 10 Pro , Chrome 92.0.4515.107 
**Reproducible:** always
**Build found:** 03.08.2021

**Preconditions**
The User is Logged with actual credential at the https://ita-social-projects.github.io/GreenCityClient/

**Steps to reproduce**
1. Go to 'Edit  Profile' page 
2. Change the  'Name' field , by using one 'space' special character (e.g. Stanislav Maslenkov)

**Actual result**
Error message "The name must contain 6-30 characters and can contain letters(a-z), numbers(0-9) and a dot(.), dot at the start, at the end and consecutive dot is forbidden" is appeared
![photo_2021-08-03_17-04-33](https://user-images.githubusercontent.com/78852678/128029307-79341ec1-e207-4cb6-9120-90c74f405bb7.jpg)

**Expected result**
Name is changed and displayed in the header

**Labels to be added**
"Bug", Priority ("Medium: "), Severity ("Major:"), Type ("Functional")

**Comment by MyroslavaVynokur** [comment]
Verified - done
