### ISSUE TITLE
[User tab] missed the saved draft of the order in the user's cabinet.

### ISSUE THREAD

**Issue by HalynaLanova** [ita-social-projects/GreenCity#3042]
**Environment:** Windows 10, Google Chrome.
**Reproducible:** always.
**Build found:** last commit from " https://ita-social-projects.github.io/GreenCityClient/#/ "

**Preconditions**
1. Log in to GreenCity as a User
2. Click on the 'UBS' tab

**Steps to reproduce**
1. Fill in the 'Кількість пакетів' field with valid data
2. Click on 'Далі' button below of 'Деталі замовлення' page.
3. Click on 'Відмінити' button on 'Особисті дані' page.
4. Click on 'Так, вийти' button
5. Verify that the system saves the order as a draft in the user's cabinet and opens the GreenCity homepage.
**Actual result**
The system does not save the order as a draft in the user's cabinet.
![Screenshot_16](https://user-images.githubusercontent.com/88144901/128507447-65da1dec-d2a4-40a3-aee2-738f5189e7b8.png)

**Expected result**
The system saves the order as a draft in the user's cabinet and opens the GreenCity homepage.

**Comment by olena-shpakovska** [comment]
Is not relevant.
