### ISSUE TITLE
'Address' field accepts 31 and more values instead of 30 or less values when a registered user creates a new place

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#305]
**Steps to reproduce:**
1. Go to http://greencityclient.herokuapp.com
2. Log in as User (e.g. 'User'='greencity.user@gmail.com', 'Password'='greencityuser123')
3. Click on the 'Add place' button
4.Enter 31 and more values into the 'Address' field
Use following letters A-z, А-я, digits 0-9, special characters (e.g. 'ghf.siebrandsstraat meteren nederl')

**Actual result:**
System shows list of addresses and user can select it and add into the field

**Expected result:**
Address can not be added into the field

[http://jira.softserve.academy/browse/GC-25](url)

**Comment by rinagoroh** [comment]
We can add address with more than 30 symbols. User story have to be changed. It's question to BA.

**Comment by Bastarn78** [comment]
> We can add address with more than 30 symbols. User story have to be changed. It's question to BA.

I have no connection with BA
