### ISSUE TITLE
[UBS Courier] Error message in 'House' field

### ISSUE THREAD

**Issue by robbi22** [ita-social-projects/GreenCity#3052]
**Environment:** macOS Big Sur 11.4, Chrome Version 92.0.4515.131.
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
Log In as a client

**Steps to reproduce**
1) Put values into 'Безнадійний одяг 120л' or 'Безадійний одяг 20л' or 'Вторсировина' fields 

2) Click on 'Next' button

3) Click on 'Add Address' button

4) Choose 'Kyiv' in the dropdown 'City'

5) Input 5 characters in the 'House' field

6) Input special characters in 'House' field

**Actual result**
Error message not shown below 'House' field.

**Expected result**
The error message below the 'House' field appears in red color.

**User story and test case links**
E.g.: "User story #2199 
[Test case](https://jira.softserve.academy/browse/GC-2080)"

<img width="825" alt="Screenshot 2021-08-09 at 11 44 55" src="https://user-images.githubusercontent.com/40024792/128685375-daa0f0ea-105b-4b2e-81fc-0e1a67a817d5.png">
<img width="822" alt="Screenshot 2021-08-09 at 11 46 16" src="https://user-images.githubusercontent.com/40024792/128685379-825d83be-e86d-4f7a-86c8-028fe28e0d51.png">

**Comment by Ol98** [comment]
not reproducible
