### ISSUE TITLE
[UBS] POST Client controler make order again

### ISSUE THREAD

**Issue by MyloslavaM** [ita-social-projects/GreenCity#3061]
**Environment:** mac OS Big Sur 11,2 , browser Firefox 91.0b9
**Reproducible:** always

**Preconditions**
user should be logged
user should have more than one done order

**Steps to reproduce**
1. Go to ' greencity-ubs.azurewebsites.net/ubs/client/{id}/make-order-again' 
2. Select POST method
3. submit the action

**Actual result**
{
    "timestamp": "2021-08-12T20:25:43.197+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No enum constant greencity.entity.enums.OrderStatus.PAID; nested exception is java.lang.IllegalArgumentException: No enum constant greencity.entity.enums.OrderStatus.PAID",
    "path": "/ubs/client/601/make-order-again"
}

**Expected result**
{
  "bagOrderDtoList": [
    {
      "bagAmount": 0,
      "bagId": 0,
      "capacity": 0,
      "name": "string",
      "price": 0
    }
  ],
  "orderAmount": 0,
  "orderId": 0
}

**User story and test case links**
E.g.: "User story #2196 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:critical"), Type ("Functional"), "API" (for back-end bugs).

**Comment by VadymMakitra** [comment]
We don't have orders in our db with status PAID, and status PAID cannot be applied to order, so i don't have an idea, how you can get this error message; P.S. Controller works fine.
![image](https://user-images.githubusercontent.com/84317209/134786450-fe7393fd-9eae-45ee-a759-281cd59a20e5.png)
