### ISSUE TITLE
[UBS] Management Employee Controller DELETE  responce 500

### ISSUE THREAD

**Issue by MyloslavaM** [ita-social-projects/GreenCity#3068]
Environment: mac OS Big Sur 11,2 , browser Firefox 91.0b9
Reproducible: always

**Preconditions**
User should be logged as admin
an employee with an image should be created
**Data ** https://greencity-ubs.azurewebsites.net/swagger-ui.html#/

**Steps to reproduce**
1. Go to 'https://greencity-ubs.azurewebsites.net/admin/ubs-employee/delete-employee-image/{id}'
2. Click submit

**Actual result**
{
    "timestamp": "2021-08-18T09:36:02.840+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Could not initialize class com.azure.storage.blob.implementation.util.ModelHelper",
   

**Expected result**
Responce 200 OK

**User story and test case links**
E.g.: "User story #2780 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:critical"), Type ( "Functional"), "API" (for back-end bugs).

**Comment by Ol98** [comment]
Done!
