### ISSUE TITLE
Working times for the whole week aren't displayed

### ISSUE THREAD

**Issue by Kh-coder5** [ita-social-projects/GreenCity#307]
**Steps to reproduce:**
1. Go to http://greencityclient.herokuapp.com/
2. Navigate cursor on the one of existing places on the map (e.g. "Forum")
3. Click on the navigated icon on the map
4. Click on the expander next to the displayed working time 

**Actual result**
Working times for Monday and Thursday are displayed (see attachment)
![image](https://user-images.githubusercontent.com/56940690/68089180-e3031b00-fe6e-11e9-82ee-0675682d5cec.png)

**Expected result**
Working times for the whole week should be displayed 

Relates to user story #232

**Comment by Bastarn78** [comment]
It's not a bug. In the Forum Working times only Sun 10:00 - 23:00. You should add more Working times.

**Comment by lenadgit** [comment]
Short breaks in Forum Lviv don't exist. http://i.piccy.info/i9/d75d2c8919bf515c98a17979302ec9d1/1580499445/102810/1358686/forum.jpg
Information about breaks can be displayed automatically in the case while it fullfilled in Google Map Servise for created object in the appropriate field.
