### ISSUE TITLE
[UBS Courier tab UI] 'Деталі замовлення' tab do not correcpont to the mock up

### ISSUE THREAD

**Issue by HalynaLanova** [ita-social-projects/GreenCity#3078]
**Environment:** Windows 10
**Reproducible:** always

**Preconditions**
1. Log into Figma as an existing user.
2. Go to https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=12201%3A2.
3. Log into GreenCity as an existing user.

**Steps to reproduce**
1.  Click on 'UBS кур'єр' tab
2.  Click on 'Замовити Курєра'
3. Verify 'Деталі замовлення' tab to Final Version mockups on Figma

**Actual result**
'Деталі замовлення' tab doesn't correspond to the mockup
![Screenshot_30](https://user-images.githubusercontent.com/88144901/130061286-29e1001a-7634-41e1-bd3e-3a118c325a0a.png)

**Expected result**
'Деталі замовлення' tab correspond to the mockup
![Screenshot_31](https://user-images.githubusercontent.com/88144901/130061437-6805ec61-cdbf-4f28-8d60-ede110272813.png)
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=12201%3A2

**User story and test case links**
E.g.: "User story #2196 
[Test case](https://jira.softserve.academy/browse/GC-1935)"

**Labels to be added**
"Bug", "UBS Courier", "UBS", "Order Form", "GreenCityUBS", Priority ("pri: med"), Severity ("severity: trivial"), Type ("UI").

**Comment by dmytro-kryvyi** [comment]
Not a bug. These fields are configured on the admin page
