### ISSUE TITLE
[UBS] Management Order Controller POST  Add Violation to User responce 500

### ISSUE THREAD

**Issue by MyloslavaM** [ita-social-projects/GreenCity#3086]
Environment: mac OS Big Sur 11,2 , browser Firefox 91.0b9
Reproducible: always

**Preconditions**

1. User is logged as admin
2. order has been created

**Steps to reproduce**
1. Go to 'https://greencity-ubs.azurewebsites.net/ubs/management/addViolationToUser'
2. add Json (ex  {
  "orderID": 895,
  "violationDescription": "good luck"
} )
2. Click submit

**Actual result**
{
    "timestamp": "2021-08-20T06:34:43.975+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "415 null",
    "path": "/ubs/management/addViolationToUser"
}
the value vas added into DB violations_description_mapping tab 

**Expected result**
the system should send message 201 created. 

**User story and test case links**
E.g.: "User story #2863 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
<img width="1505" alt="Screenshot 2021-08-20 at 09 59 44" src="https://user-images.githubusercontent.com/88142576/130193795-bf0d4e5a-6e51-416e-8d03-90e173233a2b.png">

**Comment by darzinch** [comment]
this bug is done
