### ISSUE TITLE
[UBS] Management Order Controller PUT  Update employee position by order

### ISSUE THREAD

**Issue by MyloslavaM** [ita-social-projects/GreenCity#3096]
**Environment:** mac OS Big Sur 11,2 , browser Firefox 91.0b9
**Reproducible:** always

**Preconditions**
1.    User is logged in as administrator
2.     Order has been already created

**Steps to reproduce**
1. Go to 'https://greencity-ubs.azurewebsites.net/ubs/management/update-position-by-order'
2. Click submit
**Actual result**
{
  "timestamp": "2021-08-21T07:03:56.761+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Index 1 out of bounds for length 1",
  "path": "/ubs/management/update-position-by-order"
}

**Expected result**
The administrator has the opportunity to manipulate data of employee position 

**User story and test case links**
E.g.: "User story #2780 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by MyroslavaVynokur** [comment]
Verified - controller works as expected
