### ISSUE TITLE
[Login page] Registration is not successfu while entering valid Password in a concrete sequence

### ISSUE THREAD

**Issue by HalynaLanova** [ita-social-projects/GreenCity#3099]
**Environment:** Windows 10, Google Chrome
**Reproducible:** always

**Preconditions**

1.  Open https://ita-social-projects.github.io/GreenCityClient/#/
2. Click on 'Sign up' button
3. Registration page is open

**Steps to reproduce**
1. Enter valid Email address
2. Enter valid values in 'User name' field
3. Enter valid values in 'Password' field "Ivavaav12345#"
4. Enter  equal to Password field values in 'Confirm password' field "Ivavaav12345#"
5. Click on 'Sign up' button
6. Verify is the registration successful.

**Actual result**
Registration is not successful. Error message 'Password has contain at least one character of Uppercase letter (A-Z), Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.)' is shown.
![Screenshot_40](https://user-images.githubusercontent.com/88144901/130354659-b692e885-e04b-47d7-b68b-8675c602db74.png)

**Expected result**
Registration should be successful 'Congratulations! You have successfully registered on the site. Please confirm your email address in the email box' message appears

**User story and test case links**
E.g.: "User story #https://jira.softserve.academy/browse/GC-184
[Test case](https://jira.softserve.academy/browse/GC-199)"

**Labels to be added**
"Bug", Priority ("medium"), Type ("Functional"),

**Comment by Bishko86** [comment]
character sequence "qwerty" and "12345" is allowed now
