### ISSUE TITLE
View of the pricing page for an admin

### ISSUE THREAD

**Issue by YanaTarasiuk** [ita-social-projects/GreenCity#3146]
As an Admin, I want to be able to view the page with tariffs for different locations, so that actual prices for a location are collected in one place.

**User Flow**
Main UBS menu -> Choose "Документи" -> Open "Тарифи" -> Tap location "Локація"

**Preconditions**
1. The user should be logged in as an Admin

### Acceptance Criteria
1. The page of tariffs will contain the following information: 
- dropdown menu with selected locations,
- the name of the transportation courier,
- the table "Сервіси",
- the table "Тарифи на Послуги",
- previously set order limits for the current transportation courier:
* radio button with two options: the Sum of the order "Сума замовлення" (від __ до__) and the Quantity of bags "Кількість пакетів" (від __ до__),
* minimum set of bags "Мінімальний набір пакетів" - list of service names from the table "Тарифи на послуги" and corresponding volumes with selected checkboxes. Not editable,
* the order limits information with a populated text field. Not editable. The message populated in this field will be depicted in the client order form,

2. The table "Сервіси", which contains the following columns:
- Найменування послуги 
- Об’єм
- Базова вартість
- Комісія перевізника
- Повна вартість
- Опиc послуги

3. The table "Тарифи на Послуги", which contains the following columns:
- Найменування послуги 
- Об’єм
- Базова вартість
- Комісія перевізника
- Повна вартість
- Опиc послуги

4. When in the dropdown another location is selected, the pricing page for that location will be depicted on the page.

**Epic link**
Epic #2195 

**Labels to be added**
"User story", "UBS courier
![photo_2021-09-27_15-05-02](https://user-images.githubusercontent.com/83393282/134909347-b823291d-c7ab-4656-a426-b3d18a1ace91.jpg)
"

**Comment by NewArtMask** [comment]
Not relevant
