### ISSUE TITLE
[Header] Doesn`t correspondent to mock up

### ISSUE THREAD

**Issue by JohnSteck9** [ita-social-projects/GreenCity#3188]
**Environment:** Windows 10 Pro 21H1 19043.1165, Opera 78.0.4093.184
**Reproducible:** screen extension 574px and less
**Build found:** 07.09.2021

**Actual result**
![image](https://user-images.githubusercontent.com/63707307/133044459-f924a290-280a-4afc-b140-54ccf341ff93.png)

**Expected result**
![image](https://user-images.githubusercontent.com/63707307/132992194-981abcf2-8e30-49ef-a647-59fc2af7ad91.png)
![image](https://user-images.githubusercontent.com/63707307/133001877-c85af73b-ab55-4528-9870-ec96413fadbc.png)

**Comment by JohnSteck9** [comment]
![image](https://user-images.githubusercontent.com/63707307/133001902-89e7c975-d0ec-4090-99f4-b8e28181f50b.png)

**Comment by Ol98** [comment]
Done!
