### ISSUE TITLE
Epic: Green City Events

### ISSUE THREAD

**Issue by AsyaKerechan** [ita-social-projects/GreenCity#3194]
***Status:***
**B** - in progress, back  
**BD** - done, back     
**F** - in progress, front  
**FD** - done, front  
**T** - in progress, testing  
**Done**  - US is done

- **RELEVANT user story list:**

### 1. Feature: Events
№ | User story | Link | Status | MVP |
-- | -- | -- | -- | -- |
1 | Create event | #3193 #4231 #4232 #5123 [#6359](https://github.com/ita-social-projects/GreenCity/issues/6359) [#6361](https://github.com/ita-social-projects/GreenCity/issues/6361)
2 | Edit event | #3195 #5146 
3 | Delete event | #3196 #6181
4 | Event dashboard | #3197 #4907
5 | Add event comment | #3208 #4665 #5490 
6 | Delete comment | #3209 #5147 
7 | Edit comment | #3210 #5153
8 | Reply on comment | #3211 #5145 
9 | Events filter | #3266 #5007 
10 | Search event | #3267 #5005 
11 | Event organizer rating | #3268 #4696 #5066
12 | Event attendance | #3270 #6157 #6222
13 | Manage event location | #3373 #5394 
14 | View event preview card | #3374 #5006
15 | View my events | #3375
16 | Tagging in reply on comment | #4701

- **NOT RELEVANT user story list: -**

Epic list: #3194

**Comment by VlasenkoYuliia** [comment]
> _**Status:**_ **B** - in progress, back **BD** - done, back **F** - in progress, front **FD** - done, front **T** - in progress, testing **Done** - US is done
> 
> * **RELEVANT user story list:**
> 
> ### 1. Feature: Events
> №	User story	Link	Status	MVP
> 1	Create event	#3193 #4231 #4232 #5123 [#6359](https://github.com/ita-social-projects/GreenCity/issues/6359) [#6361](https://github.com/ita-social-projects/GreenCity/issues/6361)		
> 2	Edit event	#3195 #5146		
> 3	Delete event	#3196 #6181		
> 4	Event dashboard	#3197 #4907		
> 5	Add event comment	#3208 #4665 #5490		
> 6	Delete comment	#3209 #5147		
> 7	Edit comment	#3210 #5153		
> 8	Reply on comment	#3211 #5145		
> 9	Events filter	#3266 #5007		
> 10	Search event	#3267 #5005		
> 11	Event organizer rating	#3268 #4696 #5066		
> 12	Event attendance	#3270 #6157 #6222		
> 13	Manage event location	#3373 #5394		
> 14	View event preview card	#3374 #5006		
> 15	View my events	#3375		
> 16	Tagging in reply on comment	#4701		
> * **NOT RELEVANT user story list: -**
> 
> Epic list: #3194
