### ISSUE TITLE
The message in the "Delete" popup in Feedbacks tab doesn't meet the requirements

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#320]
**Steps to reproduce:**
1. Go to http://greencityclient.herokuapp.com/
2. Login as Admin (e.g. 'User'='greencity.adm@gmail.com', 'Password'='Greencityadm123_')
3. Click on the dropdown list in the upper right corner above the map.
4. Choose 'Admin'
5. Choose 'Feedbacks' tab
6. Click on 'Delete' button next to one of the Feedbacks

**Actual result:**
Popup with the information appears:
a. "Do you really want to delete comment of "_place name_" ?" as text
b. "Cancel" button
c. "Delete" button
d. "X" button

**Expected result:**
Popup with the information appears:
a. " Are you sure you want to delete this feedback?" as text
b. "Yes" button
c. "Cancel" button

[https://github.com/SoftServe-Social-Projects/GreenCity/issues/236](url)

**Comment by nhrab** [comment]
I approve to remain this message as it is.
