### ISSUE TITLE
[UBS courier] Input field is not disabled by default  in the 'Ні' radio button when using the 'tab' button instead mouse

### ISSUE THREAD

**Issue by olena-shpakovska** [ita-social-projects/GreenCity#3201]
**Environment:** Windows10 X64, Opera 78.0.4093.147.
**Reproducible:** always.
**Build found:** 08.09.2021

**Preconditions**
- Log into GreenCity https://ita-social-projects.github.io/GreenCityClient/#/ as an existing user.
- User goes to the next sections via **'tab' button instead mouse**

**Steps to reproduce**
1. Go to 'UBS кур'єр' tab
2. Click on 'Замовити кур'єра' button
3. Scroll to 'Еко магазин' section 
4. Pay attention to the two radio buttons “Так” and “Ні” 
5. Choose 'Ні' radio button and enter any numbers into input field

**Actual result**
By default the system displayed “Ні” answer and the input field for the shop order number is **enabled** in the 'Еко магазин'section on the 'Деталі замовлення' tab.

**Expected result**
By default the system displayed “Ні” answer and the input field for the shop order number is **disabled** in the 'Еко магазин'section on the 'Деталі замовлення' tab.

**User story and test case links**
User stories : #2196 , #2379
Test case GC-2050

![Actual result_eco store](https://user-images.githubusercontent.com/88791464/132666231-7d06167c-85e8-4496-9d04-51e8e5bca17c.png)

**Comment by Ol98** [comment]
Done!
