### ISSUE TITLE
[UBS_Order Form] Error message is shown when entering special characters (-, /) in 'Будинок' field

### ISSUE THREAD

**Issue by msmorodinnikova** [ita-social-projects/GreenCity#3206]
**Environment:** Windows 7, Google Chrome 93.0.4577.63
**Reproducible**: always
**Build found**: 10.09.2021

**Preconditions**
The user is logged in at https://ita-social-projects.github.io/GreenCityClient/#/ubs/order

**Steps to reproduce**

1. Go to 'UBS кур'єр' tab
2. Click on the 'Замовити кур'єра' button
3. Choose services minimum for 500 UAH
4. Click on the 'Далі' button
5. Click on the 'Додати адресу' button
6. Choose 'Kiev' in 'Місто' dropdown
7. Enter valid data in 'Вулиця' field (e.g. Шевченка)
8. Enter special characters (-,/) in 'Будинок' field

Actual result
The 'Поле містить заборонені символи.' message is shown after entering special characters (-,/) in 'Будинок' field.

Expected result
Special characters (-,/) are displayed in the 'Будинок' field.

User story #2199 https://jira.softserve.academy/browse/GC-1925
#2533 
[Test case 2079] https://jira.softserve.academy/browse/GC-2079

![image](https://user-images.githubusercontent.com/88488747/132723863-2bae6331-8000-44ab-8b9e-b378c38bc444.png)

**Comment by darzinch** [comment]
The issue is not solved (env: Windows 10, Google Chrome)
![Bug](https://user-images.githubusercontent.com/91462440/135282600-8352e31e-8a73-484a-82e2-c028ee300aef.PNG)

**Comment by MyroslavaVynokur** [comment]
Verified - done
