### ISSUE TITLE
Delete comment

### ISSUE THREAD

**Issue by AsyaKerechan** [ita-social-projects/GreenCity#3209]
As an Authorized User, I shall be able to delete my comment, in order to remove it from the system.

**Assumptions & Constraints**
1. Comment may have an answer. An authorized user who has left a comment will be able to respond to his own comment too. It will allow users to answer each other within one branch of communication.

**Preconditions**
1. The user should be logged in as a Authorized User.
2. User can delete only his own comment.

**Business rules**
An authorized user can delete a comment that is left without a time limit.

### Acceptance Criteria
1. Authorized User shall be able to delete comment by clicking on the "Delete" bttn.
2. After clicking on the "Delete" button system shows alert message: "Your comment will be deleted. Do you want to continue? " Buttons "YES, delete" and "Cancel" should be displayed.
3. If the user clicks “Cancel” button, alert message, buttons " YES, delete " and " Cancel " should be disapeared.
4. If the user clicks “YES, delete” button, the system clears all comment data from the database. Alert message, buttons " YES, delete " and " Cancel " should be disapeared.
5. The administrator can delete user comments.

**Out of scope**
Edit comment
Add comment
Reply on comment

**Epic link**
E.g.: Epic #3194 

**Labels to be added**
"User story"

### Tasks 
1. - [ ] sample task.

**Comment by ospodaryk** [comment]
Bug Retesting needed.
I can successfully delete my comments
<img width="768" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/82940222/6b57f2e5-9c72-46cb-9637-5225790bb3ed">
