### ISSUE TITLE
Edit comment

### ISSUE THREAD

**Issue by AsyaKerechan** [ita-social-projects/GreenCity#3210]
As an authorized User, I shall be able to edit my comment, in order to update its content.

**Assumptions & Constraints**
1.

**Preconditions**
1.	The User should be authorized.
2.	The User should be logged in.
3.	The User can edit only his comments.

**Business rules**
1.	Authorized User can edit comments which he has left with no time limits.

### Acceptance Criteria
1.	Authorized User shall be able to edit his comment by clicking on the 'Edit' button.
2.	When ‘Edit’ button is clicked on, all text symbols from the current comment become editable.
3.	Under the box with text are two buttons ‘save’ and ‘cancel’.
4.	When ‘Cancel’ button is clicked on, changes aren’t saved. The User can see his original, unedited comment.
5.	When 'Save' button is clicked on, the changes are saved and depicted in the current comment list.
6.	Show 'Edited' label after this action in the list of comments.

**Out of scope**
Add comment
Delete comment
Reply on comment

**Epic link**
E.g.: Epic #3194  

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. [ ] back-end
2. [ ] front UI
3. [ ] - front logic

**Comment by Priadkohrystyna** [comment]
Authorized User , when ‘Edit’ button is tapped,  can't see all (any) text symbols from the current comment, so user can't edit his comment.
