### ISSUE TITLE
[UBS courier] Error message is not displayed when 'Ні' radio button is chosen and the user entered less than 10 characters in the 'Введіть номер замовлення' text field

### ISSUE THREAD

**Issue by olena-shpakovska** [ita-social-projects/GreenCity#3216]
**Environment:** Windows10 X64, Opera 78.0.4093.147.
**Reproducible:** always.
**Build found:** 10.09.2021

**Preconditions**
- Log into GreenCity https://ita-social-projects.github.io/GreenCityClient/#/ as an existing user.
- User goes to the next sections via 'tab' button instead mouse

**Steps to reproduce**
1. Go to 'UBS кур'єр' tab
2. Click on 'Замовити кур'єра'
3. Scroll to 'Еко магазин' section
4. Pay attention to the two radio buttons “Так” and “Ні”
5. Choose 'Ні' radio button
6. Enter less than 10 numeric characters 

**Actual result**
'Номер введено не вірно. Спробуйте ще раз.' error message **is not displayed** when the user enters less than 10 numeric characteristics.
![Actual result_eco store,'Ні'](https://user-images.githubusercontent.com/88791464/132906727-bc684669-19e4-483b-909b-4f77c21cd1ff.png)

**Expected result**
'Номер введено не вірно. Спробуйте ще раз.' error message **is displayed** when the user enters less than 10 numeric characteristics.

**User story and test case links**
User stories : #2196 , #2379
Test case GC-2108

Is related with  Bug #3201

**Comment by Ol98** [comment]
Done!
