### ISSUE TITLE
[UBS admin] Admin can't find an order that is not loaded in table of orders.

### ISSUE THREAD

**Issue by IvannaVeselovska** [ita-social-projects/GreenCity#3218]
**Environment:** Windows 10 Home version 21H1; Google Chrome version 93.0.4577.63 (64-bit).
**Reproducible:** always.
**Build found:** 12/09/2021 

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in as administator.

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/orders
2. Set "1582" in the 'Search' field
3. Pay attention to the table

**Actual result**
The order with 'id' equals "1582" did not appear.

**Expected result**
The order with 'id' equals "1582" appeared.

**User story and test case links**
E.g.: "User story #2536 
[Test case](https://jira.softserve.academy/browse/TQ-244)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

![image](https://user-images.githubusercontent.com/48368073/132987206-a69d6990-f3be-4471-b8ce-17d4ce7b65fc.png)
![image](https://user-images.githubusercontent.com/48368073/132987267-8ca9b449-b500-4d8d-8c42-0f845a20158e.png)

**Comment by Flash5482** [comment]
This order id (1582) isn't in DB

**Comment by IvannaVeselovska** [comment]
You can try any other id, that isn't included in first 10/15/20 orders.
that isaccording to choosen table view mode.

**Comment by MyroslavaVynokur** [comment]
The search works fine - move this issue to done

<img width="1124" alt="Screenshot 2021-11-26 at 16 56 54" src="https://user-images.githubusercontent.com/34717146/143599122-cfdac373-f4dc-4424-8e6b-095d38dbf939.png">
