### ISSUE TITLE
[UBS admin orders] Several certificates are are not separated by ‘;’

### ISSUE THREAD

**Issue by msemochko** [ita-social-projects/GreenCity#3222]
Environment: Windows 10 Home version 21H1; Google Chrome version 93.0.4577.63 (64-bit).
Reproducible: always.
Build found: 12/09/2021

Preconditions

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in as administrator
3. An order with 1 or more certificates is created

Steps to reproduce

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/orders
2. Find an order with 1 or more certificates
3. Pay attention to the 'order_certificate_code' column

Actual result
Several certificates are separated by ',' sign

Expected result
Several certificates are separated by ‘;’

User story and test case links

User story #2536

**Comment by MyroslavaVynokur** [comment]
Fixed
<img width="210" alt="Screenshot 2021-11-30 at 20 46 09" src="https://user-images.githubusercontent.com/34717146/144108672-4a1d9e25-4b0b-46f1-9abb-2d6fe10bf1ca.png">
