### ISSUE TITLE
[UBS admin] 'amount_due' displays negative value instead of zero when 'total_order_sum' is less than 'order_certificate_points' 

### ISSUE THREAD

**Issue by IvannaVeselovska** [ita-social-projects/GreenCity#3223]
**Environment:** Windows 10 Home version 21H1; Google Chrome version 93.0.4577.63 (64-bit).
**Reproducible:** always.
**Build found:** 12/09/2021

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in as administrator
3. An order with 'total_order_sum' less than 'order_cretificate_points' is created

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/orders
2. Find an order with 'total_order_sum' less than 'order_cretificate_points'(e.g. order with 'id' = "1605")
3. Pay attention to 'amount_due' column

**Actual result**
'amount_due' column displays negative value.

**Expected result**
'amount_due' column is zero.

**User story and test case links**
E.g.: "User story #2536 
[Test case](https://jira.softserve.academy/browse/TQ-241)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional").

![image](https://user-images.githubusercontent.com/48368073/133047469-f50a7752-18a1-4b2c-949f-6c07ef909adb.png)
![image](https://user-images.githubusercontent.com/48368073/133047737-89b346c0-70a3-4651-8840-9deff783f5f3.png)

**Comment by Flash5482** [comment]
I can't reproduce it cuz in DB there isn't an order id(1605). Mb you can create new one...
