### ISSUE TITLE
[UBS_Order Form] Error message is shown when entering uppercase letters 'І', 'Є' in Ukrainian in 'Ім'я', 'Прізвище','Вулиця' fields

### ISSUE THREAD

**Issue by msmorodinnikova** [ita-social-projects/GreenCity#3229]
**Environment:** Windows 7, Google Chrome 93.0.4577.63
**Reproducible:** always
**Build found:** 13.09.21

**Preconditions**
The user is logged in at https://ita-social-projects.github.io/GreenCityClient/#/ubs/order

**Steps to reproduce**

1. Go to 'UBS кур'єр' tab
2. Click on the 'Замовити кур'єра' button
3. Choose services minimum for 500 UAH
4. Click on the 'Далі' button
5. Click on the 'Додати адресу' button
6. Choose 'Kiev' in 'Місто' dropdown
7. Enter uppercase letters 'І', 'Є' in Ukrainian in 'Ім'я', 'Прізвище','Вулиця' fields

**Actual result**
The 'Поле містить заборонені символи' is shown near the 'Ім'я', 'Прізвище', 'Вулиця' fields after entering uppercase letters 'І', 'Є'.

**Expected result**
The value is entered and displayed in 'Ім'я', 'Прізвище', 'Вулиця' fields.

**User story and test case links**
User story #2198 
User story #2531  https://jira.softserve.academy/browse/GC-1852
[Test case 2109] (https://jira.softserve.academy/browse/GC-2109)

![image](https://user-images.githubusercontent.com/88488747/133081390-538245c8-ce9f-42a9-8ffc-f0e1d2995939.png)

![image](https://user-images.githubusercontent.com/88488747/133081572-5df4ada1-9dbb-4e6a-a857-47148ca5abe6.png)

**Comment by Ol98** [comment]
Done!
