### ISSUE TITLE
[Green City] Eco News Controller 500 Internal Server Error

### ISSUE THREAD

**Issue by VadymMakitra** [ita-social-projects/GreenCity#3234]
1. Open https://greencity.azurewebsites.net/swagger-ui.html#/eco-news-controller/getEcoNewsUsingGET;
2. If user entered not supported Sorting criteria controller returned 500 Internal Server Error;
![image](https://user-images.githubusercontent.com/84317209/133221279-b3ed701e-c159-4e4b-bdc8-f8bea259cd60.png)

**Comment by MyroslavaVynokur** [comment]
Get eco news by tags controller works fine - verified
