### ISSUE TITLE
[UBS admin] scroll doesnt work properly

### ISSUE THREAD

**Issue by nazarf1** [ita-social-projects/GreenCity#3250]
**Environment**: Windows 10 Home version 21H1; Google Chrome version 93.0.4577.63 (64-bit).
**Reproducible**: always.
**Build found**: 12/09/2021

**Preconditions**

Go to https://ita-social-projects.github.io/GreenCityClient/#/
Log in as administrator
go to user data page 
pay attention to scroll
**Actual result**
scroll does not occupy the entire height
![image](https://user-images.githubusercontent.com/88323205/133820019-0aadadf1-d330-4368-ab2c-6e1d4ba39faf.png)

**Expected result**
![image](https://user-images.githubusercontent.com/88323205/133820161-29949802-ed94-4257-8333-c6b05b1c024e.png)

**Comment by Ol98** [comment]
Done!
