### ISSUE TITLE
Edit the pricing page, tapping "Редагувати сторінку"

### ISSUE THREAD

**Issue by YanaTarasiuk** [ita-social-projects/GreenCity#3263]
As a Super Admin I want to be able to edit the pricing page, so that information is visible for admins and on client's order page it is up-to-date.

**User Flow**
Main UBS menu -> Choose "Документи" -> Open "Тарифи" -> Tap a selected location -> Tap "Редагувати сторінку" on the pricing page 

**Preconditions**
1. The user should be logged in as a Super Admin

### Acceptance Criteria
1. At the top of the page there is the name of the current city.
2. Below the city name, there is a dropdown which enlists all the transportation couriers that were add to the general list. See #3157.
3. The Delete button "Видалити перевізника". See #3264 
4. In the table "Сервіси" each row has "Edit" button. See #3144 
5. In the table "Тарифи на послуги" each row has "Edit" and "Delete" buttons. See #3144 
6. The table "Тарифи на послуги" has a button "Додати послугу". See #3145 
7. The block "Ліміти замовлення" with a radio button with two options: the Sum of the order "Сума замовлення" (від __ до__) and the Quantity of bags "Кількість пакетів" (від __ до__)
8. The block "Мінімальний набір пакетів" - list of service names from the table "Тарифи на послуги" and corresponding volumes with selected checkboxes.
9. The order limits information with a text field "Інформація про ліміти замовлення". The message populated in this field will be depicted in the client order form. The hint message inside it says "Інформація про ліміти замовлення, яка буде відображатись у формі замовлення клієнта".
10. The button "Додати превізника". When tapped, appear the identic information block, as before with non-populated fields. The couriers, which are already described above for the current location can't be selected from the dropdown and are highlighted in grey. 
11. The button "Зберегти зміни". See point 4 #3143.   
12. When the changes are made, it will affect ONLY future documentation and calculations.

**Epic link**
Epic #2195 

**Labels to be added**
"User story", "UBS courier"

**Mockups*
![photo_2021-09-27_15-04-56](https://user-images.githubusercontent.com/83393282/134908974-e0010493-1861-436f-a5d5-e36a576d424c.jpg)
![photo_2021-09-27_15-05-06](https://user-images.githubusercontent.com/83393282/134909005-5c9fde33-f56d-44ba-a9ca-6b9bfc28cbae.jpg)

*

**Comment by NewArtMask** [comment]
Not relevant
