### ISSUE TITLE
Delete the courier from the pricing page of a particular location

### ISSUE THREAD

**Issue by YanaTarasiuk** [ita-social-projects/GreenCity#3264]
As a Super Admin I want to be able to delete a courier from the pricing page of a particular city, so that when the courier does not cooperate with UBS it is not depicted here.  

**User Flow**
Main UBS menu -> Choose "Документи" -> Open "Тарифи" -> Tap a selected location -> Tap "Редагувати сторінку" on the pricing page 

**Preconditions**
1. The user should be logged in as a Super Admin

### Acceptance Criteria
1. When the Delete button "Видалити перевізника" is tapped, the pop-up with a confirmation question and two buttons will appear: "Видалити перевізника?" and buttons "Так" and "Ні". 
2. When "Так" is tapped, the courier and pricing parameters for this courier are deleted. 
3. When "Ні" is tapped, no changes are made.
4. When the changes are made, it will affect ONLY future documentation.

**Epic link**
Epic #2195 

**Labels to be added**
"User story", "UBS courier"
![photo_2021-09-27_15-05-06](https://user-images.githubusercontent.com/83393282/134908838-5ba9b230-718d-488b-9145-e6ca1419aeb6.jpg)

**Comment by NewArtMask** [comment]
Not relevant
