### ISSUE TITLE
Duplicate the pricing page, creating a new location

### ISSUE THREAD

**Issue by YanaTarasiuk** [ita-social-projects/GreenCity#3272]
As a Super Admin I want to be able to duplicate the pricing page, so that creating new location takes less time.

**User Flow**
Main UBS menu -> Choose "Документи" -> Open "Тарифи" -> Tap a selected location -> Tap "Дублювати сторінку" on the pricing page 

**Preconditions**
1. The user should be logged in as a Super Admin

### Acceptance Criteria

1. When "Дублювати сторінку" is tapped the new page of a new location is created and it reflects the view and all the functionality of edit page (2-10, 12 points) #3263 
2. At the top of the page there is a dropdown with the full list of possible locations. 
3. When the location is selected and "Зберегти зміни" is tapped, this new location is added to the list of selected locations with already populated information on the pricing page. See #3140 
4. When the location selected from the dropdown is already in the selected location list, the information message will appear: "Це місто вже додано, оберіть інше місто" and the button "Зберегти зміни" will be inactive.

**Epic link**
Epic #2195 

**Labels to be added**
"User story", "UBS courier"

**Mockups
![photo_2021-09-27_15-04-56](https://user-images.githubusercontent.com/83393282/134908462-6596c172-73b3-4a66-acd3-c9b9358c3053.jpg)
**

**Comment by NewArtMask** [comment]
Not relevant
