### ISSUE TITLE
[My habits] The "Add habit" buttons are disabled, when scroling page "All habits" 

### ISSUE THREAD

**Issue by darzinch** [ita-social-projects/GreenCity#3296]
**Environment:** Windows10 x64, Chrome 89.0.4389.128
**Reproducible:** always
**Build found:** 27.09.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
My habits page is opened.

**Steps to reproduce**
1. Click on 'Add new habit' button
2. Scroll down to the list of habits
3. Pay attention to the "Add habit" buttons  

**Actual result**
All butons "Add habit" are disabled  when start scrolling down (see attachment). 

**Expected result**
The buttons "Add habit" stays active. 

**User story and test case links**
User story #993 
related bug: [My habits] The "You don't have authorities" error is shown after clicking 'Mark as done' checkbox #2709"
![Снимок](https://user-images.githubusercontent.com/91462440/135092854-11cb465b-08f5-4aa1-98c4-c402b8d56e92.PNG)

**Labels to be added**
 "Pri: high", "Bug", "Sev: major", "Functional", "Habit item"

**Comment by ILyaDyakun** [comment]
bug isn't reproduced

**Comment by slavafisher** [comment]
Disabled only habbits that alredy added to user account. Back to user habbits and see habbits that added.
