### ISSUE TITLE
[Search] The displayed amount of results are different after clickin on the "See all results" option 

### ISSUE THREAD

**Issue by darzinch** [ita-social-projects/GreenCity#3298]
Environment: Windows10 x64, Chrome 89.0.4389.128
Reproducible: always
Build found: 27.09.2021

**Preconditions**
User is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome

**Steps to reproduce**
1. Click on the 'Search' icon at the header of the site.
2. Type the text in the 'Search' field (e.g. 'news')
3. Click on the ‘See all News’ button on the left side at the bottom of the screen.
4. Scroll down the search results.

**Actual result**
On the step 2 there is information about how many items have been found (see attachment "search result"), but after clicking on the button "see all results" there is only 6 items (see attachement "see all results").

**Expected result**

After the User clicks on the 'See All News' button on the Search page, the User should be redirected to the page with All found content items.

**User story and test case links**
[Search] Search results displaying and filtering #572
[Search] The 18 items are shown instead of 9 after infinite scrolling #2720

**Attachments**

![search result](https://user-images.githubusercontent.com/91462440/135215644-0f7f95ed-3678-4d2d-b803-2ee9d59f45e3.jpg)
![see all results](https://user-images.githubusercontent.com/91462440/135215611-5a91a6e2-43fa-4991-b9bf-805f3c3dbc4d.jpg)

**Comment by MyroslavaVynokur** [comment]
Bug is fixed - verified
