### ISSUE TITLE
Add new eco habit to track

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#330]
As a registered logged in user I want to add new eco habit so that I can track one more habit in my personal cabinet.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/69504553-86a29100-0f2c-11ea-8694-0deb614bc907.png)
![image](https://user-images.githubusercontent.com/53810790/69504588-dc773900-0f2c-11ea-90b9-2f23c318f891.png)
![image](https://user-images.githubusercontent.com/53810790/69504561-96ba7080-0f2c-11ea-8c9a-29293c9028fe.png)

Acceptance criteria:

1. "Add new habit" button is available in personal cabinet. 

2. WHEN Registered logged in user clicks on "Add new habit" button popup appears.

3. Popup contains the next information:
    a. Section with already chosen eco habits
    b. Section with available/"can be added" eco habits
    c. "Save changes" button
    d. "Cancel" button
    e. "x" button

4. Registered logged in user can drag blocks with eco habits to section of chosen habits or to all available and back only till clicking "Save changes" button.

5. One eco habit is chosen by default and date of first logging in is the first day for tracking "habit by default" for user.

6. When registered logged in user hovers on eco habit he want to choose in section "Habits that can be added" it becomes active and has possibility to drag it.

7. WHEN Registered logged in user chooses eco habits/drag eco habit to "already chosen" section and clicks "Save changes" eco habits in "already chosen" section appears in user personal cabinet. 

Assumptions and constraints:
1. Chosen eco habit highlights with green when it's dragged to section "already chosen" in popup.
2. New chosen eco habit should be added as the last one of habit's section in personal cabinet.

**Comment by rsyvulko** [comment]
Not relevant.
