### ISSUE TITLE
[Personal data] The address duplication validation does not work in the 'Garbage collection address' field

### ISSUE THREAD

**Issue by NadiiaMudryk** [ita-social-projects/GreenCity#3305]
**Environment:** OS, Windows 10 Pro, Browser: Google Chrome Version 93.0.4577.82.
**Reproducible:** Always
**Build found:** 30.09.2021

**Preconditions**
The registered user is logged in
'UBS кур'єр'/'Замовити кур'єра'/'Продовжити'/created order and press 'Далі'/

**Steps to reproduce**
1. Go to 'Адреса вивозу сміття'
2. Click on 'Додати адресу'
3. Set a valid value into all fields (вул. Саксаганського, б.12, к.1, п.1) 
4. Set a valid value into all fields (вул. Антоновича, б.1, к.1, п.1)
5. Set a valid value into all fields (вул. Саксаганського, б.12, к.1, п.1)

**Actual result**
The address duplication validation does not work

![image](https://user-images.githubusercontent.com/91464855/135460736-b4f95af5-f3ed-4992-b4b6-e74857a61806.png)

**Expected result**
The address duplication validation has to work

**User story and test case links**
E.g.: "User story  #2533

**Labels to be added**
"Bug", Priority ("Pri: High "), Severity ("Severity :Major "), Type ("Functional"), UBS, UBS courier.

**Comment by ViktoriyaRyazhska** [comment]
One customer cannot have two equivalent addresses
