### ISSUE TITLE
Change request to user story #283

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#331]
As a user I want to see date of tracking to each of habits near title of appropriate habit, so that it will show actual date for each habit separately.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/69505072-7096cf80-0f30-11ea-8914-42370426530e.png)

Acceptance criteria:

1. Date of tracking should be moved from my statistic section to each of chosen eco habits.

2. Date of tracking is available for each of chosen eco habits in personal cabinet.

3. First day of tracking eco habit "by default" is day of first logging the application.

4. Date of tracking is situated near title of appropriate habit in right upper corner of eco habit section.

**Comment by rsyvulko** [comment]
Not relevant.
