### ISSUE TITLE
Delete chosen eco habit

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#332]
As a registered logged in user I want to delete chosen eco habit so that I can track only actual for me habits.

Mockups:
![image](https://user-images.githubusercontent.com/53810790/69505377-4cd48900-0f32-11ea-965b-b96034b37733.png)

Acceptance criteria:

1. Registered logged in user can delete habit in popup of "Add new habit" button only from "Already chosen" section, when it is already saved as chosen.

2. WHEN registered logged in user hovers on each habit from "Already chosen" section, it become active to delete, appears red "x" button in upper corner.

3. Registered logged in user cannot delete the last habit in "Already chosen" section.

4. WHEN Registered logged in user clicks red "x" button popup with the next options appears:
    a. Text of popup "Are you sure you want to delete this eco habit?"
    b. "Yes" button
    c. "Cancel" button

5. WHEN Registered logged in user clicks "Yes" button, appropriate section with eco habit is removed from personal cabinet.

6. WHEN Registered logged in user clicks "Cancel" button, user see popup "New habit".

**Comment by rsyvulko** [comment]
Not relevant.
