### ISSUE TITLE
[UBS Certificate] The expiry date of previously used certificate is shown instead of the date when we used it 

### ISSUE THREAD

**Issue by Ol98** [ita-social-projects/GreenCity#3328]
**Environment:** Windows,  Google Chrome 94.0.4606.71 
**Reproducible:** always
**Build found:** 04.10.2021

**Preconditions**
Log into Green City as an existing user https://ita-social-projects.github.io/GreenCityClient/#/
Choose 'UBS кур'єр' tab

**Steps to reproduce**
1. Click on 'Замовити кур'єра' button
2. Choose your order amount (e.g. 'Безнадійний одяг 120 л'  - 10)
3. Scroll down to the 'Certificate' field
4. Enter a number of previously used certificate 

**Actual result**
The error message with the expiry date of the previously used certificate is shown.
![image](https://user-images.githubusercontent.com/91474733/135846792-c3988743-3b65-44d5-afc0-df86c92dbdc0.png)

**Expected result**
The error message with the date when we used the certificate is shown.

E.g.: "User story #2481 

**Labels to be added**
"Bug", Priority ("low: "), "UI"

**Comment by MyroslavaVynokur** [comment]
Actual result:

Error message does not appear (certificate 3007-1993 is used):


<img width="516" alt="Screenshot 2021-12-01 at 20 22 39" src="https://user-images.githubusercontent.com/34717146/144291467-57933e98-c991-4a1c-a5ee-f9eba9116490.png">
