### ISSUE TITLE
Enchancement to user story #285_Title to eco habit

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#333]
As a user I want to see titles to eco habits so that it will be easier to navigate among eco habit's trackers.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/69506016-57445200-0f35-11ea-9f52-580751a4e224.png)

Acceptance criteria:

1. Title of habit is available to each of chosen eco habits in personal cabinet.

2. Title consists of:
   a. Sequence number of habit in personal cabinet
   b. Name of habit 

3. Text of interest facts that belongs to appropriate habit is available under the title of habit.

**Comment by rsyvulko** [comment]
Not relevant.
