### ISSUE TITLE
[Sign up] After signing up the new user is not logged and redirected to main page istead of 'My Space' page

### ISSUE THREAD

**Issue by Ol98** [ita-social-projects/GreenCity#3331]
**Environment:** Windows, Google Chrome 94.0.4606.71 
**Reproducible:** always
**Build found:** 04.10.2021

**Preconditions**
Go to Green City https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. Click on 'Sign-up' button
2. Set correct values in 'Email' field in the following format: @domain.com
3. Set correct value in 'User name' field - up to 20 characters
4. Set correct value in the 'Password' field 
5. Set correct value in 'Confirm password' field
6. Click 'Sign-up' button
7. Open the email box you entered in step 2 
8. Open the email with the verification of your email address
9. Click on 'Підтвердьте свою електронну адресу' button
**Actual result**
The user is redirected to the main page and not logged in. 
https://user-images.githubusercontent.com/91474733/135894360-fbb45c6b-f009-49f9-8423-b3a01dc6ae01.mp4

**Expected result**
User is successfully redirected to 'My habits' page.

**User story and test case links**
E.g.: "User story #29, #386, #455"

**Labels to be added**
"Bug", Priority ("high: "), Severity ("severity: high"), Type ( "Functional")

**Comment by MyroslavaVynokur** [comment]
Verified - done
