### ISSUE TITLE
To add new goal

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#334]
As a user I want to add a new goal from the list so that I can see my new goals in my personal cabinet.
![image](https://user-images.githubusercontent.com/58074253/69540503-648e2a80-0f8f-11ea-8c8f-1622ad95509d.png)

Acceptance criteria
 
1.	Button “add new goal” is active without any default goals if registered logged in user see personal cabinet page.
2.	Registered logged in user clicks on "Add new goal" button, popup with information displays. 
3.	Popup window consists of 
a.check box list of new goals
c. 8 new goals that are proposed in the list
d. possibility by "+" to create own goal
e. Button “add” at the bottom of popup window 
f. Button “x” in the corner of popup window

4.	WHEN registered logged in user clicks on "+" button, new checkbox with active text field appears at the end of goal list in popup window.  
5.	WHEN registered logged in user is in the English interface, he can write only Latin letters  
6.	WHEN registered logged-in user clicks on the button “add” popup window disappears and all checked goals will be saved and display in personal cabinet.
7.	New chosen goals appear on the top of goals list in the personal cabinet.  
8.	WHEN registered logged in user clicks on button "x" popup window disappears without saving data
Assumptions and Constraints:
1.	Registered and logged in user can add from 0 to all goals.
2.	Registered logged in user can check and uncheck every goal
3.	New created goal should be checked on the checkbox to be displayed on the list of goals in the personal cabinet
4.	New created goal can be edited in the text field in popup window

**Comment by rsyvulko** [comment]
Not relevant.
