### ISSUE TITLE
To see achievements in personal cabinet

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#335]
As a registered logged in user I want to see section with achievements so that I will enjoy of ways to receive them. 

Mockup:
![image](https://user-images.githubusercontent.com/53810790/69506662-4812d380-0f38-11ea-85b5-d4ec58b0caf5.png)

Acceptance criteria:

1. Achievements section is available in personal cabinet of user.

2. This section contains:
     a. title "My achievements"
     b. Tooltip text "Enjoy to receive an achievements of using the application. It is funny!"
     c. Icons of achievements - 9 items

3. WHEN an user registers and log in for first time all achievements are inactive. 

4. WHEN registered logged in user hovers on each of icons of achievement, tooltip with text how to receive it appears.

**Comment by rsyvulko** [comment]
Not relevant.
