### ISSUE TITLE
[bugFix] Incorrect display of elements in the tablet and mobile versions

### ISSUE THREAD

**Issue by SvitlanaVorobets** [ita-social-projects/GreenCity#3350]
At page https://ita-social-projects.github.io/GreenCityClient/#/ the ''Eco news'' section is incorrectly displayed in the tablet and mobile versions.

Expected result:
- Arrange the elements of the ''Eco news'' section in one column, filling the width of the screen

**Comment by KaterynaKhorosh** [comment]
the elements of the ''Eco news'' section are not arranged in the portrait view

![Screenshot_2022-01-20-09-41-44-329_com android chrome](https://user-images.githubusercontent.com/95848159/150295034-14fdf838-3e44-4449-ba4b-6a1264534457.jpg)
![Screenshot_2022-01-20-09-42-11-256_com android chrome](https://user-images.githubusercontent.com/95848159/150295037-ceddb7c8-7646-4443-bc68-a35eef9bd4ff.jpg)

**Comment by KaterynaKhorosh** [comment]
https://user-images.githubusercontent.com/95848159/154942994-82663913-52bd-4f40-82ef-86fef43fe2c0.mp4

the elements of the ''Eco news'' section are  arranged
