### ISSUE TITLE
To receive an achievement

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#336]
As a registered logged in user I want to receive an achievement so that I will enjoy using and explore the application.

Acceptance criteria:

1. There is available 9 achievements in personal cabinet are inactive.

2. WHEN registered logged in user hovers on each achievement tooltips appears:
     2.1. Achievement#1 "Acquaintanceship" - "Register and pass onboarding"
     2.2. Achievement#2 "Eco friend" - Start to track a habit"
     2.3. Achievement#3 "Сonscious" - "Made first habit"
     2.4. Achievement#4 "Wow!" - "Add second habit"
     2.5. Achievement#5 "Well done" - "Complete 3 goals"

Ways how achievements become active:

3. Achievement#1 "Acquaintanceship"
   3.1. WHEN user registers, logs in, passes onboarding successfully, icon for Achievement#1 "Acquaintanceship" become active and popup appears. Popup consist:
          3.1.1. Icon-picture of achievement#1 "Acquaintanceship"
          3.1.2. Text "Welcome you in Green City application!"
          3.1.3. "Ok" button
   3.2. WHEN registered logged in user clicks "Ok" button he can see personal cabinet. And "Acquaintanceship" achievement displays active.

4. Achievement#2 "Eco friend"
    4.1. WHEN registered logged in user starts to track default habit (checks saved items for first day and they appear in circle diagram) popup appears. Popup consist:
           4.1.1. Icon-picture of achievement#2 "Eco friend"
           4.1.2. Text "Good start for you and do not give up! Achievement "Eco friend" is yours."
           4.1.3. "Ok" button
    4.2. WHEN registered logged in user clicks "Ok" button he can see personal cabinet. And "Eco friend" achievement displays active.

5. Achievement#3 "Сonscious"
   5.1. WHEN registered logged in user tracks saved items for last day (21st) of first habit and quantity of saved items appear in the last cell popup appears. Popup consist:
          5.1.1. Icon-picture of achievement#3 "Сonscious"
          5.1.2. Text "Congratulation! You made your first eco habit and you deserve achievement "Сonscious"
          5.1.3. "Ok" button
    5.2. WHEN registered logged in user clicks "Ok" button he can see personal cabinet. And "Сonscious" achievement displays active.

6. Achievement#4 "Wow!"
   6.1. WHEN registered logged in user add second habit and it appears in personal cabinet popup appears. Popup consist:
          6.1.1. Icon-picture of achievement#4 "Wow!"
          6.1.2. Text "It looks you want to track one more habit. It is brilliant idea!"
          6.1.3. "Ok" button
    6.2. WHEN registered logged in user clicks "Ok" button he can see personal cabinet. And "Wow!" achievement displays active.

7. Achievement#5 "Well done"
   7.1. WHEN registered logged in user checked his 3 goals in the list in personal cabinet and they move down the list popup appears. Popup consist:
          7.1.1. Icon-picture of achievement#5 "Well done"
          7.1.2. Text "Well done. Keep doing your goals with the same enthusiasm"
          7.1.3. "Ok" button
    7.2. WHEN registered logged in user clicks "Ok" button he can see personal cabinet. And "Well done" achievement displays active.

8. The rest 4 achievements displays as icons-pictures without functionality and tooltips.

**Comment by rsyvulko** [comment]
Not relevant.
