### ISSUE TITLE
[bugFix] Incorrect display of elements in the mobile versions

### ISSUE THREAD

**Issue by SvitlanaVorobets** [ita-social-projects/GreenCity#3380]
At page https://ita-social-projects.github.io/GreenCityClient/#/ the ''There are 3625 of us and today we'' and at page https://ita-social-projects.github.io/GreenCityClient/#/about in section "About us" are incorrectly displayed in the mobile versions.

Expected result:

Arrange the elements of the ''There are 3625 of us and today we'' section in one column, filling the width of the screen. At section "About us" I need to add padding.

**Comment by KaterynaKhorosh** [comment]
![2022-01-20_14-22-52](https://user-images.githubusercontent.com/95848159/150338425-4147da79-c06f-4bb9-b909-e117eb764f79.png)

All elements are arranged in the mobile versions
