### ISSUE TITLE
[UBS Admin. Orders] Three selected columns are frozen instead of the first three columns chosen by user.

### ISSUE THREAD

**Issue by Ol98** [ita-social-projects/GreenCity#3384]
**Environment:** All browsers
**Reproducible:** always
**Build found:**  14.10.2021

**Preconditions**
Log into Green City as an admin.

**Steps to reproduce**
1. Go to UBS-Admin page
2. Click on Orders tab
3. Shuffle the first three columns
4. Scroll the table to the right
5. Pay your attention to the first three columns

**Actual result**
The first three columns by default are frozen.

**Expected result**
The first three columns chosen by a user are frozen. 

**User story and test case links**
E.g.: "User story #3289
[Test case](https://jira.softserve.academy/browse/GC-2159)

**Comment by KaterynaKhorosh** [comment]
The first three columns chosen by a user are frozen.
