### ISSUE TITLE
[bugFix] Display of elements at mobile is incorrect at page "UBS courier" and "My space"

### ISSUE THREAD

**Issue by SvitlanaVorobets** [ita-social-projects/GreenCity#3389]
At page https://ita-social-projects.github.io/GreenCityClient/#/ubsare and https://ita-social-projects.github.io/GreenCityClient/#/profile/7602 incorrectly displayed in the mobile versions.

Preconditions:
Sign in 
Email: howiv47374@nenekbet.com
Password: Test-User123

Expected result:
Page elements should be displayed according to the mockup.

**Comment by KaterynaKhorosh** [comment]
elements are displayed correclty in the mobile version
![2022-02-21_12-38-58](https://user-images.githubusercontent.com/95848159/154939280-14383e30-254b-43fe-be61-4600abf57ba7.png)
