### ISSUE TITLE
[Change request to #3143] <Fill in the pricing page for a particular location>

### ISSUE THREAD

**Issue by YanaTarasiuk** [ita-social-projects/GreenCity#3390]
**Description of a Change request:**

1. In the table "Сервіси" the rows should have the button "Edit" and "Translation"
2. In the table "Тарифи на Послуги" each row should have the buttons "Edit", "Delete" and "Translation".
3. The block "Ліміти замовлення", should contain "Translation" button.

**Reason for Change:**
The customer foresees the English version of the site in the future

**Acceptance Criteria**
1. "Translation" button is active only after the row is populated.
2. When "Translation" is tapped, the pop-up with the attributes from the table/block and two text fields for each attribute will appear. One text field will be populated with the original (ukr) information and not editable. Another text field of the same attribute will be editable and have hint message "Введіть переклад". The non-editable info will be grey. There will be two buttons "Зберегти" and "Скасувати".
4. When translation pop-up is populated and the original (ukr) information in the row is deleted, the translation is not saved and not depicted. TBD.
4. When "Зберегти" is tapped, the changes are saved and depicted in English version of the site for the corresponding attribute.
5. When "Скасувати" is tapped, the changes are not saves and the pop-up disappears.  
6. The translation won't be depicted to other admins in a View mode. TBD.

**Impact of Change**
#3143

**Comment by NewArtMask** [comment]
Not relevant
