### ISSUE TITLE
[GreencityUbs] to do tests

### ISSUE THREAD

**Issue by PavloFedyk** [ita-social-projects/GreenCity#3436]
GreenCityUbs\service\src\main\java\greencity\service\ubs\UBSClientServiceImpl\markUserAsDeactivated(Long id)

 GreenCityUbs\core\src\main\java\greencity\controller\SuperAdminController\createServices,getService,deleteService

**Comment by dessdee** [comment]
pull request - https://github.com/ita-social-projects/GreenCityUBS/pull/430
