### ISSUE TITLE
'My goals' block in 'My habits' covers the hyperlink 'more'

### ISSUE THREAD

**Issue by blekhtc** [ita-social-projects/GreenCity#345]
**Steps to reproduce:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/ 
2. Log in as User (e.g. 'User'='ritokod399@4tmail.net', 'Password'='Qwer1234$')
3. Go to 'My habits' page

**Actual result:**
'My goals' block covers the hyperlink 'more'

**Expected result:**
'My goals' block in 'My habits' shoud not cover

**Environment**
Opera Версія:65.0.3467.48

https://jira.softserve.academy/browse/GC-105

![Без імені](https://user-images.githubusercontent.com/58074230/69899451-d9d27480-136e-11ea-9c62-b340bcd00cd8.jpg)
 the hyperlink 'more'

**Comment by lenadgit** [comment]
This bug was fixed 
http://i.piccy.info/i9/4e47d334333e9d0108139753562ef7ac/1581349026/176296/1358686/opera_screen.jpg
