### ISSUE TITLE
[UBS Admin. Orders] Invalid orders view and some properties of orders table

### ISSUE THREAD

**Issue by MyroslavaVynokur** [ita-social-projects/GreenCity#3454]
**Environment:** MacOS 11.4, Google Chrome Version 94.0.4606.71 (Official Build) (arm64)
**Reproducible:** always
**Build found:** 31.10.2021

**Preconditions**
1. Log into Green City as an admin

**Steps to reproduce**
1. Go to UBS-Admin page
2. Click on Orders tab
3. Try to change columns width 
4. Mark checkbox of any record
5. Pay attention to columns headers where client's personal data is stored ("Ім'я клієнта", "Телефон клієнта", "Email клієнта")
6. Check "Адреса" column and pay attention how data is displayed
7. Have a look at "Загальна знижка" column
8. Have a look at "Оплата" column
9. Have a look at "Номер замовлення з магазину" column

**Actual result**

1. Administrator can NOT change the column width
2. Record is selected with marked checkbox

<img width="467" alt="Screenshot 2021-10-31 at 17 04 40" src="https://user-images.githubusercontent.com/34717146/139589850-1628846a-18ce-4595-846e-95dfde8e403a.png">

3. Next headers are displayed: "Ім'я замовника", "Телефон замовника", "Email замовника"

<img width="608" alt="Screenshot 2021-10-31 at 17 15 37" src="https://user-images.githubusercontent.com/34717146/139590272-7eea2849-e97b-4f5b-b840-460788ec01aa.png">

4. Address is displayed in format: [street name], [house number], [block number]

<img width="221" alt="Screenshot 2021-10-31 at 17 23 24" src="https://user-images.githubusercontent.com/34717146/139590601-4c57a416-66f9-4bcc-813b-21d7d4668a5b.png">

5. The value in "Загальна знижка" field is displayed with integer. If there is no discount, fields are blank.

<img width="199" alt="Screenshot 2021-10-31 at 17 27 35" src="https://user-images.githubusercontent.com/34717146/139590723-4e1b98a5-2ccb-4ac7-8e42-10cdc6df792e.png">

6. The value in "Оплата" field is displayed with integer.

<img width="198" alt="Screenshot 2021-10-31 at 17 31 05" src="https://user-images.githubusercontent.com/34717146/139590867-f4c5ee9c-cbdf-4e98-94d4-7af6f2258f92.png">

7. Column is filled in with 4-digit number from Eco-Store

<img width="197" alt="Screenshot 2021-10-31 at 17 36 16" src="https://user-images.githubusercontent.com/34717146/139591145-206f9f28-db46-4fdb-a41e-abe90f42cf65.png">

**Expected result**

1. Administrator can change the column width. It cannot be narrowed less than the default width (12 characters). Columns width set by administrator should be saved and applied in his next session.
2. By selecting a checkbox - a record is highlighted. Several records may be selected to be edited.
3.  "замовник" should be renamed to "клієнт" ("Ім'я клієнта", "Телефон клієнта", "Email клієнта")
4. The address should be displayed in format: [street name] [house number], корп. [block number], п. [entrance]. If there is no block or entrance number, the system should display “-” (hyphen). E.g. Личаківська 5, корп. 3, п.2 or Зелена 127, корп.-, п.-
5. Should be displayed in format   “-100.00 грн” (float number with 2 digits). If there is no discount, 0.00 грн should be displayed.
6. Should be float number with 2 digits.e.g (150.00 грн)
7. Should be 10-digit number from Eco-Store; In case several orders from Eco-Store is used those are written in one line and are separated by ‘;’e.g: 1234567890; 0123456789

**User story and test case links**
User story #2536 #3184 #3289 
[Test case](https://jira.softserve.academy/browse/GC-2161)
[Test case](https://jira.softserve.academy/browse/GC-2103)
[Test case](https://jira.softserve.academy/browse/GC-2165)
[Test case](https://jira.softserve.academy/browse/GC-2104)

**Comment by YelyzavetaSheptytska** [comment]
Everything is fixed except "Columns width set by administrator should be saved and applied in his next session."
