### ISSUE TITLE
repeat achieving the goal multiple times

### ISSUE THREAD

**Issue by sofiya-kozak** [ita-social-projects/GreenCity#346]
As a registered logged in user I want to add again to my goals list in my personal cabinet already achieved goal so that I can repeat to achieve the same goal  

Acceptance criteria
1.	When registered logged in user checks goal in my goals list in the personal cabinet, this goal becomes unchecked in the popup window again 

Assumption and constraints:
The same goal can be in the list of checked and unchecked goals in the personal cabinet.
The same goal can be added to the goals list in the personal cabinet multiply times only if this goal was checked

**Comment by rsyvulko** [comment]
Not relevant.
