### ISSUE TITLE
[UBS. Profile] Users gets 405 error when he/she tries to edit his/her profile

### ISSUE THREAD

**Issue by ViktoriyaRyazhska** [ita-social-projects/GreenCity#3464]
**Environment:** Win10, Chrome 91.
**Reproducible:** always.
**Build found:** 2.11.2021

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Log in as a user
3. Go to client cabinet via profile
4. Click on 'User data' tab
5. Click on 'Edit data' button
6. Fill all mandatory fields
7. Click on 'Save changes' button

**Actual result**
All entered data are saved

**Expected result**
405 error (update) is displayed in browser dev tool 

**User story and test case links**
E.g.: "User story #3051

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by MyroslavaVynokur** [comment]
The bug is still reproduced, please have a look

<img width="1431" alt="Screenshot 2021-11-26 at 16 06 00" src="https://user-images.githubusercontent.com/34717146/143592842-6edf9ceb-901a-4a08-b88e-c4206ca36cac.png">

**Comment by KaterynaKhorosh** [comment]
![2022-01-20_14-15-48](https://user-images.githubusercontent.com/95848159/150337043-f8002c9f-ba22-4da9-bf77-fb9880bb9d6a.png

Pls check, changes are not saved each time while editing, error 500

**Comment by KaterynaKhorosh** [comment]
no error in dev tools
