### ISSUE TITLE
add a new goal to the existing list of goals in the personal cabinet

### ISSUE THREAD

**Issue by sofiya-kozak** [ita-social-projects/GreenCity#347]
As a registered logged in user I want to add to already existing list of goals in my personal cabinet new goals so that I can track them.
Acceptance criteria
1.	WHEN registered logged in user clicks on "Add new goal" button, popup window with information displays.
2.	Popup window consists of
a. checkbox list of  8 goals
b. checkbox list of own goals, if such were created
c. possibility by "+" to create own goal
d. Button “add” at the bottom of popup window
e. Button “x” in the corner of popup window
f. scroll button on the right side of popup window
3.	Already chosen goals are marked as checked in the popup window
4.	Registered logged in user can uncheck already checked goal in the popup window
5.	When registered logged in user click button “add”, unchecked goals in popup window will disappear from my goals list in the personal cabinet and checked goals will be added to my goals list.  
6.	Already achieved goals in the personal cabinet are marked as unchecked in the popup window.
7.	Registered logged in user can edit own created goals by clicking on the button “edit” on the right side of own created goal

Related to #334

**Comment by rsyvulko** [comment]
Not relevant.
