### ISSUE TITLE
[Sign in/Sign up] User signed in with Google is NOT able to do any actions on UBS side 

### ISSUE THREAD

**Issue by MyroslavaVynokur** [ita-social-projects/GreenCity#3505]
**Environment:** MacOS 11.4, Google Chrome Version 94.0.4606.71 (Official Build) (arm64)
**Reproducible:** always
**Build found:** 10.11.2021

**Preconditions**
1. User is NOT registered

**Steps to reproduce**
1.  Go to main page and click on "Sing in" button in the menu bar
https://ita-social-projects.github.io/GreenCityClient/#/
2. Click on "Sign in with Google" button
3. Fill in email address, password fields (important that user shouldn't have account for this address)
3. Go to UBS Courier
4. Click on "Call up the courier" button 
5. Click on user name at the right side of menu bar and select UBS-user from a drop down list
6. Click on User data tab
7. Click on "Change password" button

**Actual result**

1. User is not able to choose the location from pop up window

<img width="1419" alt="Screenshot 2021-11-11 at 00 01 47" src="https://user-images.githubusercontent.com/34717146/141200849-9c2a5305-a33f-475c-ae94-c0a7a59a0bcd.png">

2. Eror message appears "Something went wrong... Please, reload the page" OR "ubs-client-profile.error-message" (6 step)

<img width="1419" alt="Screenshot 2021-11-11 at 00 02 32" src="https://user-images.githubusercontent.com/34717146/141200926-7b02cb62-a410-46af-bfdb-6fdcf1d15349.png">

3. Pop up window with blank fields appears

<img width="574" alt="Screenshot 2021-11-11 at 00 03 13" src="https://user-images.githubusercontent.com/34717146/141200989-b711af02-3b16-47b9-b6b2-c1950e102b73.png">

**Expected result**

1.  User should be able to choose location from pop up window and user should be navigated to order form
2. User should be navigated to his personal data
3. Warning message should appear "In order to change your password please go to your email settings" etc.

**User story and test case links**
E.g.: "User story #50

**Comment by KaterynaKhorosh** [comment]
User signed in with Google is  able to do any actions on UBS side and on Green city My space:
user data are edited
possible to make an order on UBS courrier
possible to add news
possible to change password
