### ISSUE TITLE
See Eco news section on home page

### ISSUE THREAD

**Issue by sofiya-kozak** [ita-social-projects/GreenCity#351]
As an unregistered user, I want to see informational section on the main page, so I can read eco-news.  
Mockup:
![image](https://user-images.githubusercontent.com/58074253/70866857-7011b780-1f77-11ea-9939-08e35f29623a.png)
Acceptance criteria
1.	WHEN unregistered user scrolls down the page, he can see section#4 eco-news 
2.	It consists of:
-	Name of the section “Eco-news” in the middle of landing page in section#4
-	Table with 2 columns
a. 1st column shows the name of the earliest eco-article with picture
b. 2nd column shows the name of 2 next articles, one below the other. 
c. above every article, there is a date of publishing on our website (day month year)
 d. under every article name, there is a button “read more” 
-	Button “read all news”, in the middle of landing page in section#4

3.	When unregistered user clicks on the bottom “read more”, the new page with the article appears.
4. When unregistered user clicks on the bottom “read all news”, the new page with the list of articles appears.
5.	 When the new article is added, it appears in the 1st column with the photo, the next article is moved to 2nd column

Assumption and constraints:
1.	The articles posted by date

Related to #461
Defects #790 #799  #803 #809

**Comment by yuraolkhovskyi** [comment]
In this story we need to add an ability that every eco-news has its own photo.
