### ISSUE TITLE
[UBS Order Form Step 1] Alignment of order sum section on 'Деталі замовлення' tab doesn't correspond to the mockup 

### ISSUE THREAD

**Issue by MyroslavaVynokur** [ita-social-projects/GreenCity#3515]
**Environment:** MacOS 11.4, Google Chrome Version 94.0.4606.71 (Official Build) (arm64)
**Reproducible:** always
**Build found:** 14.11.2021

**Preconditions**
1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
2. User should have some points on his/her balance 

**Steps to reproduce**
1. Go to 'UBS кур'єр'
2. Click on the "Замовити кур'єра" button
3. Enter valid data into 'Деталі замовлення' tab (min order sum is 500 uah for Kyiv location)
4. Mark check box to the 'Так' in the section 'Чи бажаєте Ви скористатися бонусами?'
5. Fill in the field 'Чи бажаєте Ви скористатись сертифікатом?' with valid certificate (e.g. 0987-6543)
6. Pay attention to the section above where order sum is calculated 

**Actual result**

1. Alignment of order sum section on 'Деталі замовлення' tab doesn't correspond to the mockup 

<img width="343" alt="Screenshot 2021-11-14 at 15 21 00" src="https://user-images.githubusercontent.com/34717146/141689938-9235817d-666b-492f-aff3-a41c62e64dab.png">

**Expected result**

1. Alignment of order sum section on 'Деталі замовлення' tab should correspond to the mockup 

<img width="313" alt="Screenshot 2021-11-14 at 18 46 11" src="https://user-images.githubusercontent.com/34717146/141690161-4561ea9e-ac0f-4e2f-8824-70ba71b1c3fd.png">

**User story and test case links**
E.g.: "User story #2379 
[Test case](https://jira.softserve.academy/browse/GC-1935)"

**Comment by TarasKuzma1999** [comment]
In new figma 'Деталі замовлення' tab  correspond to the mockup
