### ISSUE TITLE
[UBS-user page. 'Замовлення' tab]  When user clicks on expanding icon of order remaining orders are not shifted 

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3528]
**Environment:** for all browsers 
**Reproducible:** always
**Build found:**  17.11.2021

**Preconditions**
1. the registered user has a few made orders

**Steps to reproduce**
1. The registered user is logged in https://ita-social-projects.github.io/GreenCityClient/#/
2. The user navigated to the tab "Замовлення" in the personal cabinet
3. Click on expanding icon of order 
4. Click on expanding icon of another order 

**Actual result**
Two orders have an expanded view at a time.
**Expected result**
Only one order from the list can have an expanded view at time. Remaining orders are shifted

**User story and test case links**
E.g.: "User story #3478

**Comment by KaterynaKhorosh** [comment]
Only one order from the list can have an expanded view at time. Remaining orders are shifted

https://user-images.githubusercontent.com/95848159/151353595-a654d86d-f669-4c50-8378-ec607eb52885.mp4
