### ISSUE TITLE
[UBS-user page. 'Замовлення' tab] the order displays services in 'Послуга' column that the user didn't do

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3531]
**Environment:** all browsers 
**Reproducible:** always
**Build found:** 17.11.2021

**Preconditions**
1. the registered user has made order with only one ordered service in 'Послуга' column

**Steps to reproduce**
1. Go to: https://ita-social-projects.github.io/GreenCityClient/#/
2. Go to "Замовлення" tab in the personal UBS-user cabinet
3. Click on expanding icon of the order from preconditions 
4. Verify "Послуга" column 

**Actual result**
the order displays three services, two of which the user did not do in the order, with the following names: "Безнадійний одягВторсировина", "Безнадійний одягВторсировина", "ВторсировинаВторсировина".

**Expected result**
the order displays one service which user did in order, with one of the following names: "Безпечні відходи", "Текстильні відходи", "Текстильні відходи". 

**User story and test case links**
E.g.: "User story #3478

**Comment by BobNazar** [comment]
![image](https://user-images.githubusercontent.com/76586511/144590679-2741b825-1527-45ae-8f03-d90942d21deb.png)
Works correctly.

**Comment by MyroslavaVynokur** [comment]
Bug is still reproduced
I've created the order 3267 and only added service "Текстильні відходи" (120 л), please pay attention to the list of services:

<img width="1007" alt="Screenshot 2021-12-05 at 15 06 06" src="https://user-images.githubusercontent.com/34717146/144747745-29fac4bb-57de-4d16-a969-83cb60cc407c.png">
