### ISSUE TITLE
[UBS-user page. 'Замовлення' tab] 'Коментар до замовлення' field is not displayed in order 

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3533]
**Environment:** all browsers 
**Reproducible:** always
**Build found:** 17.11.2021

**Preconditions**
1. The user should have order with made comment in field "Коментар" from order form 

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Open "Замовлення" tab in the personal UBS-user cabinet
3. Click on expanding icon of the order (order from precondition )
4. Verify if there is  'Коментар до замовлення' field is present 

**Actual result**
'Коментар до замовлення' field is not displayed in order 

**Expected result**
'Коментар до замовлення' field is dsaplayed in the order and received from order form from field “Коментар”

**User story and test case links**
E.g.: "User story #3478

**Comment by KaterynaKhorosh** [comment]
Коментар до адреси is displayed but Коментар до замовлення no
![2022-01-28_18-48-21](https://user-images.githubusercontent.com/95848159/151587983-089f0eb0-b139-4c91-bf1e-73c33ca6c5f2.png)
![2022-01-28_18-49-27](https://user-images.githubusercontent.com/95848159/151587985-895b51fa-b2a8-459b-befe-264e951cb08d.png)
