### ISSUE TITLE
[UBS-user page. 'Замовлення' tab] 'Отримувач' is displayed in the order instead of 'Відправник'

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3534]
**Environment:** all browsers
**Reproducible:** always
**Build found:** 17.11.2021

**Preconditions**
1. The user should have made order

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Open "Замовлення" tab in the personal UBS-user cabinet
3. Click on expanding icon of the order (order from precondition )
4. Verify 'Відправник' field 

**Actual result**
Title is 'Отримувач' 

**Expected result**
Title is 'Відправник' 

**User story and test case links**
E.g.: "User story #3478

**Comment by MyroslavaVynokur** [comment]
Verified - done

<img width="1018" alt="Screenshot 2021-12-05 at 14 51 34" src="https://user-images.githubusercontent.com/34717146/144747291-b2a0ae49-f75d-41c1-81e2-657cf48aac99.png">
