### ISSUE TITLE
[UBS-user page. 'Замовлення' tab] 'Адреса вивезення відходів' field is displayed without numbers in address

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3535]
**Environment:** all browsers
**Reproducible:** always
**Build found:** 17.11.2021

**Preconditions**
The user should have made the order with the specified address in order

**Steps to reproduce**
1. Go to:  https://ita-social-projects.github.io/GreenCityClient/#/
2. Open "Замовлення" tab in the personal UBS-user cabinet
3. Click on expanding icon of the order (order from precondition )
4. Verify  'Адреса вивезення відходів' field

**Actual result**
'Адреса вивезення відходів' field is displayed without numbers in the address

**Expected result**
City, Street, District, Region, Street should be displayed in format: [street name] [house number], корп. [block number], п. [entrance]. ( E.g. Личаківська 5, корп. 3, п.2 or Зелена 127, корп.-, п.- ) 

**User story and test case links**
E.g.: "User story #3478

**Comment by KaterynaKhorosh** [comment]
![2022-01-17_11-21-52](https://user-images.githubusercontent.com/95848159/149742358-54e32895-7357-459b-834c-6034b973df03.png)

adress is displayed as expected
