### ISSUE TITLE
[UBS User] Delete order from orders list in user orders page

### ISSUE THREAD

**Issue by NazarDobriy** [ita-social-projects/GreenCity#3536]
**Preconditions**

1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**

1. Click on logged in user in the right top corner of the screen
2. Select 'UBS-user' from drop down list
3. Click on "Замовлення" tab
4. Click on "Скасувати" order

**Actual result**

1. The order is not deleted

**Expected result**

1. the order must be deleted

**Comment by MyroslavaVynokur** [comment]
When the user cancels order from the orders list data in DB is erased. Also canceled orders should be displayed in "Історія замовлень" tab.
