### ISSUE TITLE
[UBS-user page. 'Замовлення' tab] ‘Вартість’, 'Сума', columns, ‘Сума замовлення’, ‘Сертифікат’, ‘Бонуси’, ‘Сума до оплати’, 'Часткова оплата' fields are not float number with 2 digits

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3537]
**Environment:** all browsers
**Reproducible:** always
**Build found:** 18.11.2021

**Preconditions**
1. the user must have a partially paid order with ordered services (Послуга), use the certificate and bonuses in order . 

**Steps to reproduce**
1. Go to: https://ita-social-projects.github.io/GreenCityClient/#/
2. Open "Замовлення" tab in the personal UBS-user cabinet
3. Click on expanding icon of the order (order from precondition )
4. Verify ‘Вартість’, 'Сума', columns, ‘Сума замовлення’, ‘Сертифікат’, ‘Бонуси’, ‘Сума до оплати’, 'Часткова оплата' fields

**Actual result**
 ‘Вартість’, 'Сума', columns, ‘Сума замовлення’, ‘Сертифікат’, ‘Бонуси’, ‘Сума до оплати’, 'Часткова оплата' fields  are integer number

**Expected result**
‘Вартість’, 'Сума', columns, ‘Сума замовлення’, ‘Сертифікат’, ‘Бонуси’, ‘Сума до оплати’, 'Часткова оплата' fields  are float number with 2 digits in format : XXX.XX грн

**User story and test case links**
E.g.: "User story #3478

**Comment by MyroslavaVynokur** [comment]
Verified - done

<img width="831" alt="Screenshot 2021-12-05 at 14 52 59" src="https://user-images.githubusercontent.com/34717146/144747348-87447dba-6cd4-462c-af78-22daaaeaf22f.png">
