### ISSUE TITLE
[UBS-user page. 'Замовлення' tab] 'Часткова оплата' field is not displayed in order details when order is partially paid

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3539]
**Environment:** all browsers 
**Reproducible:** always
**Build found:** 18.11.2021

**Preconditions**
1. The user must have partially paid order

**Steps to reproduce**
1. Go to: https://ita-social-projects.github.io/GreenCityClient/#/
2. Open "Замовлення" tab in the personal UBS-user cabinet
3. Click on expanding icon of the order (order from precondition )
4. Verify 'Часткова оплата' field in the order

**Actual result**
'Часткова оплата' field is not displayed in order details

**Expected result**
'Часткова оплата' field is displayed in order details like total amount that client has paid in the order

**User story and test case links**
E.g.: "User story #3478

**Comment by NewArtMask** [comment]
No longer up to date
