### ISSUE TITLE
[UBS User] Create pop-up for order payment

### ISSUE THREAD

**Issue by NazarDobriy** [ita-social-projects/GreenCity#3549]
**Preconditions**

1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**

1. Click on logged in user in the right top corner of the screen
2. Select 'UBS-user' from drop down list
3. Click on "Замовлення" tab
4. Click on "Оплатити" order

**Expected result**
A pop-up window “Оплата” to pay for specific order is opened
![image](https://user-images.githubusercontent.com/51053478/142651887-6ca3f6a4-6d16-4847-b499-4ca7283b0370.png)
The amount “Сума” is equal to 0 (fully covered by certificate or bonuses)
![image](https://user-images.githubusercontent.com/51053478/142652324-4f4df9a3-f4e0-4041-ace2-9542475a4339.png)

**User story and test case links**
Epic link
E.g.: Epic #3491

**Comment by SWalaszek** [comment]
The pop-up is not implemented.
