### ISSUE TITLE
See an advertising info of application

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#355]
As a user I want to see short information about application, so that I can understand what the app is about and whether I want to track a habit.

Mockups:
![image](https://user-images.githubusercontent.com/53810790/70898634-b0b41400-1ffd-11ea-8ab4-6956809d2d10.png)

Acceptance criteria:

1. User can see Advertising info of application on the Home page.

2. Advertising info section contain:
         2.1. Title
         2.2. Text
         2.3. Picture 
         2.4. Button "Start to track eco habit"

3. WHEN user clicks on "Start to track eco habit" button, system shall: 
         3.1. navigate logged in user to Personal cabinet
         3.2. display log in form for unlogged user.

**Comment by ViktoriyaRyazhska** [comment]
resolved
particulary mockup was changed
