### ISSUE TITLE
[UBS Admin Cabinet] Modified amount of packages doesnt changed to previous values after reset order changes

### ISSUE THREAD

**Issue by s1auka** [ita-social-projects/GreenCity#3551]
Go to UBS admin cabinet.
Choose orders tab.
Click on any order to open order details.
modify any amount of packages.
At the bottom of the page click "Cancel" to reset all changes.
Modified amount of packages doesnt reseted.

**Comment by MyroslavaVynokur** [comment]
Verified - done
