### ISSUE TITLE
[UBS order] Incorrect confirmation page after the Fondy payment

### ISSUE THREAD

**Issue by NewArtMask** [ita-social-projects/GreenCity#3558]
**Preconditions**
- The registered user is logged in.
- The user goes to the UBS-order page.
- The user chooses services and fulfills all required user data.
- The user chooses the 'Fondy' payment.
- The user clicks on the 'Order' button.

**When the payment is successful:**

**Actual result:**
![image](https://user-images.githubusercontent.com/34275837/143040993-220edcc0-0880-49c2-9034-38c3720948bb.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/34275837/143041291-cb955ea8-42c1-4a61-a700-be7eda83f472.png)

**Comment by MyroslavaVynokur** [comment]
Done - verified
