### ISSUE TITLE
[UBS] Fix 500 Internal Server Error Management order controller's group

### ISSUE THREAD

**Issue by VadymMakitra** [ita-social-projects/GreenCity#3561]
Fixeissue with internal server error in ManagementOrderController :
- /ubs/management/read-address-order/id
- /ubs/management/getAdditionalOrderBagsInfo/id
- /ubs/management/read-order-info/id
Remove outdated controller and all dependency logic for it:
- /ubs/management/order/

**Comment by MyroslavaVynokur** [comment]
Verified - done
