### ISSUE TITLE
[UBS Order] Bug/Fix If user use certificate after bonus and certificate biggest then the final sum the sum will be negative.

### ISSUE THREAD

**Issue by Flash5482** [ita-social-projects/GreenCity#3564]
**Steps to reproduce:** 

1. Go to "https://ita-social-projects.github.io/GreenCityClient/#/".
2. Log in
3. Go to "UBS courier" page
4. Click on button 'call-up the courier
5. Chose some service
6. Use bonus 
7. Use certificate (certificate should be biggest then final price)

**Before fix:**
![image](https://user-images.githubusercontent.com/48418496/143293113-cbc9a2e6-70d7-4f3c-8bcf-ab5aadecf3c1.png)
**After fix:**
![image](https://user-images.githubusercontent.com/48418496/143293201-d35dbfb0-1ad0-49cb-9f2e-0101acab9f48.png)

**Comment by MyroslavaVynokur** [comment]
Verified - done
