### ISSUE TITLE
[UBS Order] Bug/Fix After user used a bonus and try to change the number of packages the final sum is not correct calculated

### ISSUE THREAD

**Issue by Flash5482** [ita-social-projects/GreenCity#3565]
**Steps to reproduce:**

1. Go to "https://ita-social-projects.github.io/GreenCityClient/#/".
2. Log in
3. Go to "UBS courier" page
4. Click on button 'call-up the courier
5. Chose some service
6. Use bonus
7. Try to change number of packages

**Before fix:**

https://user-images.githubusercontent.com/48418496/143294866-318d8b19-7b14-4c2d-b44f-350d5285a851.mp4

**After fix:**

https://user-images.githubusercontent.com/48418496/143295041-acfaba49-e8bd-45f1-ac33-6503e20e5b1c.mp4

**Comment by MyroslavaVynokur** [comment]
Verified - done
