### ISSUE TITLE
[UBS Order] Bug/Fix If user use certificate biggest then price or equal to price user can set bonus and after this input for certificate will be broke

### ISSUE THREAD

**Issue by Flash5482** [ita-social-projects/GreenCity#3566]
Steps to reproduce:

1. Go to "https://ita-social-projects.github.io/GreenCityClient/#/".
2. Log in
3. Go to "UBS courier" page
4. Click on button 'call-up the courier
5. Chose some service
6. Use certificate (certificate should be biggest or equal  to price)
7. Try to use bonus and delete bonus

**Before fix:**

1. Final price didn't calculate
2. Input for Certificate broke

**After fix:**

1. Final price calculate
2. Input for Certificate is normal

**Comment by MyroslavaVynokur** [comment]
Verified - done
