### ISSUE TITLE
[UBS Order] Bug/Fix If user click on add bonus a couple times the price and bonus will be destroyed

### ISSUE THREAD

**Issue by Flash5482** [ita-social-projects/GreenCity#3567]
**Steps to reproduce:**

1. Go to "https://ita-social-projects.github.io/GreenCityClient/#/".
2. Log in
3. Go to "UBS courier" page
4. Click on button 'call-up the courier
5. Chose some service
6. Use bonus and try to click on bonus couple times

**Comment by MyroslavaVynokur** [comment]
Verified - done
