### ISSUE TITLE
[UBS User] Create redirection to Fondy from order

### ISSUE THREAD

**Issue by NazarDobriy** [ita-social-projects/GreenCity#3568]
**Preconditions**

1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**

1. Click on logged in user in the right top corner of the screen
2. Select 'UBS-user' from drop down list
3. Click on "Замовлення" tab
4. Сhoose Fondy payment system
5. Click on "Оплатити" order

**Expected result**
1. Redirect to Fondy payment system with sum which specified in the order
![image](https://user-images.githubusercontent.com/51053478/143297987-06eef0cd-9e04-4169-af8f-4b542f9c0942.png)
**User story and test case links**
Epic link
E.g.: Epic #3491

**Comment by KaterynaKhorosh** [comment]
![2022-01-17_10-15-38](https://user-images.githubusercontent.com/95848159/149732355-5d63dc44-4387-4728-af77-164233389a9c.png)

payment not possible, error message appeared
