### ISSUE TITLE
bugFix/UBS/Personal-Cabinet/order-details-data

### ISSUE THREAD

**Issue by BobNazar** [ita-social-projects/GreenCity#3582]
Fix order details data.

**Comment by MyroslavaVynokur** [comment]
Client-controller (- returns all user orders for logged user) works as expected

<img width="1009" alt="Screenshot 2021-12-03 at 13 11 57" src="https://user-images.githubusercontent.com/34717146/144593180-85302276-a608-48e8-bb16-39285f13b3b6.png">
