### ISSUE TITLE
[Change request to #3274] <Remove duplicate save place check box>

### ISSUE THREAD

**Issue by ILyaDyakun** [ita-social-projects/GreenCity#3591]
**Description of a Change request:**
Remove duplicate save place check box from more options filter component

**Reason for Change:**
We don't need more than one saved places checkbox 
**Acceptance Criteria**
![image](https://user-images.githubusercontent.com/58696858/143720663-584d58f9-4757-4981-afef-e9bd582b865c.png)

**Comment by KaterynaKhorosh** [comment]
duplicate save place check box is removed
