### ISSUE TITLE
[Change request to Change request to #2198 (fields rename)] <#2533 Order form>

### ISSUE THREAD

**Issue by schIRIS** [ita-social-projects/GreenCity#3592]
**Description of a Change request:**
User interface adjustments, change field “naming” of another recipient

**Reason for Change:**
UI improvements in the tab “Деталі замовлення”, add the right naming of another recipient.

**Acceptance Criteria**

1. Rename fields “Отримувач інша людина” to “Відправник інша людина” on mockups (tabs) “Особисті дані”.
2. Rename fields “Адреса вивозу сміття” to “Адреса вивезення відходів”  

![image](https://user-images.githubusercontent.com/48557003/143784985-ac796ebb-e7a8-4bc4-8aaa-e269d85bb59c.png)

3. Rename fields on the mockups of the step “Підтвердження”. 
3.1. Rename the field “Отримувач” to “Відправник”
3.2. Rename  “Адреса вивезення замовлених послуг” to “Адреса вивезення відходів”
![image](https://user-images.githubusercontent.com/48557003/143785028-d7f42b02-f72a-48a5-b327-1ca0f7045efd.png)

**Impact of Change**
This change request affects 2 existing user stories:
#2198 - Fill in personal information
#2541 [Change request to #2200] Order form – Order summary

**Labels to be added**
[change request: UI improvement]
[change request: rename fields]

Epic: #2195

**Comment by YanaTarasiuk** [comment]
Pay attention, the text “Відправник інша людина” should be changed into "Пакети передає інша людина" in UA and "The recipient is another person" in EN


(**NOT RELEVANT. Already done**)
