### ISSUE TITLE
[UBS User] User doesn't add certificates to pop-up for order payment

### ISSUE THREAD

**Issue by NazarDobriy** [ita-social-projects/GreenCity#3597]
Preconditions

1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/

Steps to reproduce

1. Click on logged in user in the right top corner of the screen
2. Select 'UBS-user' from drop down list
3. Click on "Замовлення" tab
4. Click on "Оплатити" order
5. Enter certificate in field
6. Click on "Активувати"
7. Click on "Додати сертифікат"

**Expected result**
Appear new field and we can write another certificate
![image](https://user-images.githubusercontent.com/51053478/144058516-55e03136-78b4-4145-b8eb-311df49bc618.png)
**User story and test case links**
Epic link
E.g.: Epic #3491

**Comment by KaterynaKhorosh** [comment]
![2022-01-20_10-15-13](https://user-images.githubusercontent.com/95848159/150299320-49dd64f9-104d-4b09-9f63-57c4bc73ad12.png)

new field is appeared and we can activate certificate
