### ISSUE TITLE
[List view] Incorrect order of filter buttons on Eco News page and missing icon on buttons 

### ISSUE THREAD

**Issue by MyroslavaVynokur** [ita-social-projects/GreenCity#3602]
**Environment:** MacOS 11.4, Google Chrome Version 94.0.4606.71 (Official Build) (arm64)
**Reproducible:** always
**Build found:** 01.12.21

**Preconditions**
1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
2. Go to Eco news page

**Steps to reproduce**
1. Pay attention to Filter by section
2. Click on the button "News"

**Actual result**

1. Order of filter buttons on Eco News page is next:

<img width="544" alt="Screenshot 2021-12-01 at 14 28 31" src="https://user-images.githubusercontent.com/34717146/144234460-7af38fb0-62ca-4120-8fae-abdf35db9045.png">

2. Button "News" is highlighted in green color 

<img width="585" alt="Screenshot 2021-12-01 at 14 36 03" src="https://user-images.githubusercontent.com/34717146/144235492-779e65e2-e603-4c22-8f3e-91bb0fa8ab35.png">

**Expected result**
1. Order of filter buttons on Eco News page should correspond to the mockup in figma:

<img width="684" alt="Screenshot 2021-12-01 at 14 29 49" src="https://user-images.githubusercontent.com/34717146/144234653-47eb3955-f941-43ff-9ade-e567fbbfed9b.png">

2. Button should be highlighted in green color and closing icon should appear; according to figma:

<img width="673" alt="Screenshot 2021-12-01 at 14 37 24" src="https://user-images.githubusercontent.com/34717146/144235643-23da8cd0-a76f-46fb-b576-339e90152dd8.png">

**User story and test case links**
User story #538

**Comment by KaterynaKhorosh** [comment]
Only 3 sections dispayed: News, Events, Courses

Sections Initiatives, Ads are missing

**Comment by KaterynaKhorosh** [comment]
Order of filter buttons on Eco News page corresponds to the mockup in figma, Button is highlighted in green color and closing icon is appearred:
![2022-01-27_11-43-52](https://user-images.githubusercontent.com/95848159/151333708-bb3236dc-38bd-492b-8951-254f6f169740.png)
