### ISSUE TITLE
[UBS Order] Order data are not saved when leave the page

### ISSUE THREAD

**Issue by NewArtMask** [ita-social-projects/GreenCity#3604]
**Preconditions**
- The registered user is logged in.
- The user goes to the UBS-order page.
- The user chooses services and fulfills some data.
- The user closes the browser or exits the page.

**Actual result:**
The data is not saved when the user returns to the order page.

**Expected result:**
All entered data, with the exception of certificates and points, will be saved when the user returns to the order page.

**Comment by KaterynaKhorosh** [comment]
All entered data, with the exception of certificates and points, are saved when the user returns to the order page.
