### ISSUE TITLE
[UBS-User. Order tab] 'Нове замовлення' button is not shown on the page.

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3614]
**Environment:** All browsers.
**Reproducible:** always.
**Build found:** 03.12.2021

**Preconditions**
1.  The User has some orders.
2.  Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click "Замовлення" tab.
2. Take a look at the Order page.

**Actual result**
 'Нове замовлення' button is not shown on the page.

**Expected result**
'Нове замовлення' button is shown in the top right corner of the page.

**User story and test case links**
E.g.: "User story #3477

**Comment by KaterynaKhorosh** [comment]
![2022-01-17_11-17-34](https://user-images.githubusercontent.com/95848159/149741745-215993f5-591b-46f1-83dc-b5ab68f0d6d9.png)
'Нове замовлення' button is shown
