### ISSUE TITLE
[UBS-User. Order tab] Incorrect column names are shown in the orders table on the 'Історія замовлень' tab

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3615]
**Environment:** All browsers.
**Reproducible:** always.
**Build found:** 03.12.2021.

**Preconditions**
1. The User has some orders with 'Виконано' and/or 'Скасовано' order statuses.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click 'Замовлення' tab.
2. Click 'Історія замовлень' tab.
3. Take a look at the column names in the orders table.

**Actual result**
One can see 'Дата', 'Сума до оплати' column names.

**Expected result**
'Дата замовлення', 'Сума замовлення' column names should be used according to the mock-up.
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17780%3A37828

**User story and test case links**
E.g.: "User story#3477

**Comment by KaterynaKhorosh** [comment]
'Дата замовлення', 'Сума замовлення' column names are present
