### ISSUE TITLE
[UBS-User. Order tab] Column 'Дата оплати' is absent in the orders table on the 'Історія замовлень' tab.

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3616]
**Environment:** All browsers
**Reproducible:** always.
**Build found:** 03.12.2021.

**Preconditions**
1. The User has some orders with 'Виконано' and/or 'Скасовано' order statuses.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click 'Замовлення' tab.
2. Click 'Історія замовлень' tab.
3. Take a look at the column names in the orders table.

**Actual result**
Column 'Дата оплати' is absent in the orders table on the 'Історія замовлень' tab.

**Expected result**
Column 'Дата оплати' should be shown in the orders table on the 'Історія замовлень' tab according to the mock-up.
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17780%3A37828

**User story and test case links**
E.g.: "User story #3477

**Comment by KaterynaKhorosh** [comment]
Column 'Дата оплати' is still 
![2022-02-21_11-34-34](https://user-images.githubusercontent.com/95848159/154927948-724cc38b-260e-441c-b1e7-abd444aef087.png)
absent in the orders table on the 'Історія замовлень' tab

**Comment by TaniaIvashkiv** [comment]
Column 'Дата оплати' is still absent in the orders table on the 'Історія замовлень' tab.
![history_orders](https://user-images.githubusercontent.com/105448699/168446505-de54cc47-04bb-408f-9804-279652e28917.png)
