### ISSUE TITLE
[UBS-User. Order tab] The orders are not sorted from newest to oldest in the table on the “Історія замовлень” tab 

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3618]
![1 2](https://user-images.githubusercontent.com/92379802/144631403-b1b643d0-3989-4f3e-959a-5b9a82ef65e5.jpg)
**Environment:** All browsers.
**Reproducible:** always.
**Build found:** 03.12.2021.

**Preconditions**
1. The User has 5 or more orders with the "Виконано", "Скасовано" order statuses.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click 'Замовлення' tab.
2. Click 'Історія замовлень' tab.
3. Take a look at the 'Дата замовлення'column in the orders table.

**Actual result**
The orders are sorted in ascending order (from the oldest orders to the newest).

**Expected result**
The orders are sorted in descending order (from the oldest orders to the newest).

**User story and test case links**
E.g.: "User story#3477

**Comment by voronkooleksandr** [comment]
Everything is OK
The orders are sorted in descending order

**Comment by IvannaYarynovska** [comment]
Привіт, успіхів! )))

пн, 16 трав. 2022, 15:39 користувач Voronko Oleksandr <
***@***.***> пише:

**Comment by voronkooleksandr** [comment]
![image](https://user-images.githubusercontent.com/61209463/168640681-2f96e122-def0-42ea-aff8-7f8b0df71503.png)

Is it OK or not ? :)

**Comment by AntonHusiev** [comment]
**25.07.2022**

Orders are not sorted from the oldest orders to the newest.
[screen](http://joxi.ru/Y2Lz1xJHx0Y91r)
