### ISSUE TITLE
[UBS-User. Order tab] The orders information is shifted relative to the columns of the table on the “Історія замовлень” tab.

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3619]
**Environment:** All browsers.
**Reproducible:** always.
**Build found:** 03.12.2021.

**Preconditions**
1. The User has more than 4 orders with 'Виконано' and/or 'Скасовано' order statuses.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click 'Замовлення' tab.
2. Click 'Історія замовлень' tab.
3. Take a look at the orders table.

**Actual result**
The orders information in the 'Статус оплати', 'Сума до оплати' fields is shifted relative to the columns of the table.

**Expected result**
The order information is displayed in the form of a table and there is an alignment on columns as you can see on the mock-up. 
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17780%3A37828

**User story and test case links**
E.g.: "User story#3477
![1 3 1](https://user-images.githubusercontent.com/92379802/144654870-a3d35aac-e69c-40a2-8fb5-1b719eb87584.jpg)

**Comment by KaterynaKhorosh** [comment]
![2022-02-21_12-00-55](https://user-images.githubusercontent.com/95848159/154932536-d244dd89-d105-44cc-8891-64614200ecb7.png)

Information in the all columns is shifted

**Comment by Petryulya** [comment]
Steps to reproduce:
1. Click 'Orders' tab.
2. Click 'Current orders' tab.
3. Take a look at the orders table.

Actual result
The column names:
_'Order date', 'Order status', 'Payment status', ,Payment amount'_ 
are shifted relative to the columns of the table.

![21](https://user-images.githubusercontent.com/102656931/163677197-72acbb4f-5f69-45c3-a3bc-84b966a24be7.jpg)
