### ISSUE TITLE
BUG [USER] "My Eco Stat" block isn't available on the User page

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#362]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/
2. Login as User 

 **Actual result:**
"My cabinet" block is available on the User page

**Expected result:**
"My Eco Stat" block is available on the User page

[https://github.com/ita-social-projects/GreenCity/issues/283](url)

**Comment by nomadness** [comment]
Can't reproduce
