### ISSUE TITLE
[UBS-User. Order tab] An extra button is used in the orders table on the “Історія замовлень” tab.

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3621]
**Environment:** All browsers.
**Reproducible:** always.
**Build found:** 03.12.2021.

**Preconditions**
1. The User has some orders with 'Виконано' order status.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click 'Замовлення' tab.
2. Click 'Історія замовлень' tab.
3. Take a look at the orders table.

**Actual result**
'Замовити ще раз' button is shown for the orders with the 'Виконано' status.

**Expected result**
The usage of 'Замовити ще раз' button for the orders with the 'Виконано' status is not provided by the requirements or mock-ups.
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17780%3A37828

**User story and test case links**
E.g.: "User story#3477
![1 4](https://user-images.githubusercontent.com/92379802/144657443-64477d98-8b45-4af9-bdbf-d77c004836fe.jpg)

**Comment by krayevska** [comment]
has been fixed before
