### ISSUE TITLE
[Change request to #2481] Certificate functionality 

### ISSUE THREAD

**Issue by YuliyaTymkiv** [ita-social-projects/GreenCity#3626]
**Description of a Change request:**
Notification improvements

**Reason for Change:**
If the certificate amount is greater than the amount to be paid for selected service, the client should be notified that remaining certificate amount will not be converted into bonuses and will be burned out. Business logic described in user story #2481 is without changes

**Acceptance Criteria**
1. Client activated certificate. The certificate  is valid and the system accepts the certificate. The order amount is recalculated according to the discount and the following message is shown:

<html>
<body>

Certificate status in DB | Requirements | Expected message
-- | -- | --
New | Certificate amount is lower than the amount to be paid | Сертифiкат на cуму XXX.XX грн активовано. Строк дії сертифікату - до YY.YY.YYYY
New | Certificate amount is greater than the amount to be paid | Сертифікат на суму XXX.XX грн активовано, що перевищує суму Вашого замовлення. Залишок у розмірі ZZZ.ZZ грн не повертається. Строк дії сертифікату - до YY.YY.YYYY

</div></b>

**Impact of Change**
User story #2481 - new message if certificate amount is greater than the amount to be paid

Epic: #2195

**Comment by kulaira** [comment]
[Certificates.postman_collection (2).json](https://github.com/ita-social-projects/GreenCity/files/15351627/Certificates.postman_collection.2.json)
