### ISSUE TITLE
[ubs user] when user click "UBS user" button orders page should open by default

### ISSUE THREAD

**Issue by TarasKuzma1999** [ita-social-projects/GreenCity#3627]
Actual result
![image](https://user-images.githubusercontent.com/56336985/144818295-ddd7a625-32ef-4bd7-b580-7f41cce80d92.png)

Expected result
![image](https://user-images.githubusercontent.com/56336985/144818619-2b4f7e2e-a1d3-43c0-a39e-7c277f45ab58.png)

**Comment by MyroslavaVynokur** [comment]
Verified - done
