### ISSUE TITLE
BUG [USER] The new registered user doesn't see tooltip text in the "My Eco Stat" block

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#364]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/
2. Login as User
3. Choosse "My cabinet" 

**Actual result:**
The new registered user doesn't see tooltip text: "In this month you have not saved any paper cup or plastic bag, but you have a chance to make the world clearer! Let's start it now! Add a habit to the tracker and enjoy of tracking saved items every day." in the "My Eco Stat" block

**Expected result**:
The new registered user can see tooltip text: "In this month you have not saved any paper cup or plastic bag, but you have a chance to make the world clearer! Let's start it now! Add a habit to the tracker and enjoy of tracking saved items every day." in the "My Eco Stat" block

[https://jira.softserve.academy/browse/GC-106](url)
#283

**Comment by greatpanda1603** [comment]
Lost relevance due to My Cabinet / Profile page redesign #674

**Comment by rsyvulko** [comment]
Not relevant.
