### ISSUE TITLE
[API UBS / Management Order] POST 'Return overpayment to user' controller does not add bonuses to user account

### ISSUE THREAD

**Issue by MyroslavaVynokur** [ita-social-projects/GreenCity#3649]
**Environment:** MacOS 11.4, Google Chrome Version 94.0.4606.71 (Official Build) (arm64)
**Reproducible:** always
**Build found:** 09.12.21

**Preconditions**
1. Login as an admin (admin token is valid) in Postman
POST https://greencity-user.azurewebsites.net/ownSecurity/signIn
body
{
"email": "string",
"password": "string"
}

**Steps to reproduce**
1. Add query 
POST  https://greencity-ubs.azurewebsites.net/ubs/management/return-overpayment
body {
  "bonuses": 200,
  "comment": "extra bonuses",
  "overpayment": 200
}
+ params. orderId
2. Check admin account for bonuses 

**Actual result**
1. Bonuses are not added to account, status 200

<img width="1001" alt="Screenshot 2021-12-10 at 17 52 38" src="https://user-images.githubusercontent.com/34717146/145602456-7572ed78-b01f-4f0c-b658-f88d0fab2aac.png">

**Expected result**
1. Bonuses should be added to user account

**User story and test case links**
User story #2900

**Comment by Petryulya** [comment]
Bonuses are not added to user account

**Comment by NataliaHlazova** [comment]
POST https://greencity-ubs.azurewebsites.net/ubs/management/return-overpayment
body {
"bonuses": 0,
"comment": "string",         // The parameter must be equal to "Зарахування на бонусний рахунок" or "Повернення коштів"
"overpayment": 0
}

**Comment by TaniaQC** [comment]
Bonuses are not added to the user
![image](https://user-images.githubusercontent.com/105351490/180969428-91e20b36-207c-4de7-be56-59b68d51f32a.png)
![image](https://user-images.githubusercontent.com/105351490/180969627-b4f092d3-7b17-4c30-a403-c24afade6b74.png)

**Comment by NataliaHlazova** [comment]
POST https://greencity-ubs.azurewebsites.net/ubs/management/return-overpayment
* Order's status must be "Done" or "Canceled".
* The parameter "comment" must be equal to "Зарахування на бонусний рахунок" or "Повернення коштів".
