### ISSUE TITLE
BUG [USER] Tooltip with the text "Here you can set your goals and meet them!" isn't available in 'My goals' section

### ISSUE THREAD

**Issue by Bastarn78** [ita-social-projects/GreenCity#365]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/
2. Login as User
3. Choosse 'My cabinet' item

**Actual result:**
Tooltip with the text "Here you can set goals and fulfill them!" is available in 'My goals' section above the 'Manage goals' button

**Expected result:**
Tooltip with the text "Here you can set your goals and complete them!" is available in 'My goals' section above the 'Manage goals' button

[https://github.com/ita-social-projects/GreenCity/issues/284](url)
[https://jira.softserve.academy/browse/GC-109](url)

**Comment by lenadgit** [comment]
This tooltip user can see while there are no chosen goals
http://joxi.ru/DrlbaYgSVOyJB2
If one or more goals were added to the list, this tooltip disappears
http://joxi.ru/l2ZlvJ4uzW7a9r
