### ISSUE TITLE
[USB-User. Confirmation page] 'Ваше замовлення прийнято (№ [[Order ID]])' title - is desplayed, instead of 'Ваше замовлення оплачено (№ [[Order ID]])' when the user made order payment

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3650]
**Environment:**  all browsers
**Reproducible:** always
**Build found:** 10.12.2021

**Preconditions**
1. User is logged in as a client and navigated to a personal cabinet, tab “Замовлення”.
2. User made successful paid for the order and 'Ваше замовлення оплачено' сonfirmation page is opened 

**Steps to reproduce**
1. Verify title of сonfirmation page

**Actual result**
 'Ваше замовлення прийнято (№ [[Order ID]])' - is displayed

**Expected result**
'Ваше замовлення оплачено (№ [[Order ID]])' - is displayed

**User story and test case links**
E.g.: "User story #3491

**Comment by KaterynaKhorosh** [comment]
![2022-01-28_13-47-57](https://user-images.githubusercontent.com/95848159/151542133-bffd8e29-16fe-4b7f-b3e9-40c725a7206e.png)

the same message, Прийнято instaed of Оплачено

**Comment by Petryulya** [comment]
The word 'прийнято' in the Ukrainian version of the page has not been changed to 'оплачено'

![34](https://user-images.githubusercontent.com/102656931/164892905-22c9b223-0c85-47ea-b552-d2d9945c0d2d.jpg)

**Comment by voronkooleksandr** [comment]
All is Ok!
![image](https://user-images.githubusercontent.com/61209463/169502223-6b28d3b7-7212-48f8-bbc1-678e3722c099.png)
