### ISSUE TITLE
[UBS-User. Order tab] A warning message is not displayed after the 'Cancel' button is clicked

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3651]
**Environment:** All browsers.
**Reproducible:** always.
**Build found:** 10.12.2021.

**Preconditions**
1. The User has the order with “Сформовано” order status and “Не оплачено” payment status.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click the 'Cancel' button in the row of the order.
2. Take a look at the system behavior.

**Actual result**
The order is deleted from the order list after clicking the 'Cancel' button.
https://user-images.githubusercontent.com/92379802/145608210-751676ec-ca4e-4929-9b21-1b6e2e7afcc1.mp4

**Expected result**
A warning message 'У разі скасування дане замовлення буде видалено. Чи дійсно Ви бажаєте скасувати замовлення?' is displayed after the 'Cancel' button is clicked.
![2 1](https://user-images.githubusercontent.com/92379802/145608192-cbb04a4e-d7ad-41e0-91d7-99704f824072.jpg)

**User story and test case links**
E.g.: "User story #3488.

**Comment by KaterynaKhorosh** [comment]
Bug fixed

https://user-images.githubusercontent.com/95848159/149490484-e37156fc-f8a4-4f9c-bf80-cb324b58d975.mp4
