### ISSUE TITLE
[USB-User.'Замовлення' tab ] User can't pay for order by certificate when user use bonuses and certificate simultaneously for order payment 

### ISSUE THREAD

**Issue by OstapHapyak** [ita-social-projects/GreenCity#3652]
**Environment:** all browsers
**Reproducible:** always
**Build found:** 10.12.2021

**Preconditions**
1. User is logged in as a client and navigated to a personal cabinet, tab “Замовлення”.
2. User has made paid order and used bonuses and certificate simultaneously for order payment in the 'Order form' (step 1) 

**Steps to reproduce**
1. Go to 'Замовлення' Tab 
2. Verify the appropriate order from precondition 2
3. Verify 'Сертифікат' field 

**Actual result**
'Сертифікат' field is not displayed in the order, and the order is partially paid, only by bonuses 

**Expected result**
'Сертифікат' field is displayed in the order like total amount of certificate used to pay for the order, and the order is fully paid by bonuses  and certificate 

**User story and test case links**
E.g.: "User story #3478 #2379

**Comment by KaterynaKhorosh** [comment]
Possible to add certificate and use bonuses simultaneously but can not finish order, error message appeared: Упс, щось пішло не так...
На жаль, Ваше замовлення не було оплачено. 
![2](https://user-images.githubusercontent.com/95848159/149487410-f6e4781a-23e2-4bcc-9e4a-5d9965e90652.png)

**Comment by NazarDobriy** [comment]
> Possible to add certificate and use bonuses simultaneously but can not finish order, error message appeared: Упс, щось пішло не так... На жаль, Ваше замовлення не було оплачено. ![2](https://user-images.githubusercontent.com/95848159/149487410-f6e4781a-23e2-4bcc-9e4a-5d9965e90652.png)

Add certificates in user orders page, read

**Comment by NazarDobriy** [comment]
> > Possible to add certificate and use bonuses simultaneously but can not finish order, error message appeared: Упс, щось пішло не так... На жаль, Ваше замовлення не було оплачено. ![2](https://user-images.githubusercontent.com/95848159/149487410-f6e4781a-23e2-4bcc-9e4a-5d9965e90652.png)
> 
> Add certificates in user orders page, read

Read the "Preconditions", you must go to personal cabinet -> tab orders -> after that use certificates and bonuses

**Comment by NazarDobriy** [comment]
![image](https://user-images.githubusercontent.com/51053478/149760152-452e34fa-53bb-48fa-8c5d-2ce2591bec38.png)

**Comment by NazarDobriy** [comment]
![image](https://user-images.githubusercontent.com/51053478/149760222-9b102baf-cbfe-49d7-8272-f45bb6bd2f93.png)

**Comment by OliaFed** [comment]
Cannot use the certificate
