### ISSUE TITLE
[UBS-User. Order tab]  User's bonuses are not shown in the pop-up 

### ISSUE THREAD

**Issue by IvannaYarynovska** [ita-social-projects/GreenCity#3654]
**Environment:** All browsers.
**Reproducible:** always.
**Build found:** 10.12.2021.

**Preconditions**
1. The user has the order with 'Частково оплачено' payment status and the amount in 'Сума до оплати' field is greater than zero.
2. The user has some points on the bonus account.
3. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
4. Go to the user's personal cabinet (UBS-user).4. 

**Steps to reproduce**
1. Click the 'Оплатити' button in the row of the order.
2. Take a look at the popup that arises.

**Actual result**
User's bonuses are not shown in the pop-up under the question 'Чи бажаєте Ви скористатися бонусами?'.
![4 2](https://user-images.githubusercontent.com/92379802/145651647-392d8d6f-7134-4458-8cf3-8e39e86b8374.jpg)

**Expected result**
User's bonuses are shown in the pop-up under the question 'Чи бажаєте Ви скористатися бонусами?'. as it's shown on the mock-up.
![4 1](https://user-images.githubusercontent.com/92379802/145652017-3cb836f3-afa6-4ff2-9e74-88cf25e6470b.jpg)

**User story and test case links**
E.g.: "User story #3489.

**Comment by KaterynaKhorosh** [comment]
User's bonuses are shown in the pop-up under the question 'Чи бажаєте Ви скористатися бонусами?'.
![2022-01-17_11-23-53](https://user-images.githubusercontent.com/95848159/149742766-e9943c71-f131-4cbc-96fa-3118cee68526.png)

**Comment by KaterynaKhorosh** [comment]
![2022-01-28_14-25-59](https://user-images.githubusercontent.com/95848159/151546758-334a0f69-4764-40cf-9c00-1f1e7d686d5d.png)
User's bonuses are shown in the pop-up under the question 'Чи бажаєте Ви скористатися бонусами?'. as it's shown on the mock-up.
