### ISSUE TITLE
[UBS User] Create redirection to LiqPay from order

### ISSUE THREAD

**Issue by NazarDobriy** [ita-social-projects/GreenCity#3659]
**Preconditions**

1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**

1. Click on logged in user in the right top corner of the screen
2. Select 'UBS-user' from drop down list
3. Click on "Замовлення" tab
4. Сhoose LiqPay payment system
5. Click on "Оплатити" order

**Expected result**
![image](https://user-images.githubusercontent.com/51053478/145889150-08afaa8c-be46-4647-b43e-6c67e4b74aa9.png)

**Comment by KaterynaKhorosh** [comment]
payment not poss

https://user-images.githubusercontent.com/95848159/149743167-dd18db6a-f4f8-481e-88cf-f9f39f8063c4.mp4

**Comment by NazarDobriy** [comment]
> payment not poss
> 
>  2022-01-17_11-26-01.jkt.mp4

Do payment in user cabinet, read "Steps to reproduce".

**Comment by KaterynaKhorosh** [comment]
![2022-01-17_13-30-22](https://user-images.githubusercontent.com/95848159/149762060-c5eb3d9d-1086-4820-83f4-f5766e5171c5.png)

redirection is working
