### ISSUE TITLE
[API UBS Controller/ management order] PUT 'Update order detail info' controller does not work

### ISSUE THREAD

**Issue by MyroslavaVynokur** [ita-social-projects/GreenCity#3675]
**Environment:** MacOS 12.1, Google Chrome Version 94.0.4606.71 (Official Build) (arm64)
**Reproducible:** always
**Build found:** 18.12.21

**Preconditions**
1. Login as an admin (admin token is valid) in Postman
POST https://greencity-user.azurewebsites.net/ownSecurity/signIn
body
{
"email": "adminubs@starmaker.email",
"password": "Test-User123"
}

**Steps to reproduce**

1. Add query
PUT https://greencity-ubs.azurewebsites.net/ubs/management/set-order-detail
body
-  dto [
{
    "amount": 1,
    "bagId": 1,
    "confirmedQuantity": 1,
    "exportedQuantity": 1,
    "orderId": 3308
  }
]
- language UA
<img width="674" alt="Screenshot 2021-12-18 at 17 43 15" src="https://user-images.githubusercontent.com/34717146/146646876-21cafd44-683f-46cd-8489-2a7ff3328ffc.png">

**Actual result**

Status code 415

<img width="984" alt="Screenshot 2021-12-18 at 17 43 31" src="https://user-images.githubusercontent.com/34717146/146646881-78fac813-bc34-43d6-8f83-941603eca4f5.png">

**Expected result**

1. Order 3308 (mentioned in dto) should be updated

**User story and test case links**
User story #2821

**Comment by RossSihovsk** [comment]
This controller will be removed soon because this functional is part of one big update controller
