### ISSUE TITLE
[UBS.Admin cabinet]  The column widths cannot be changed in the 'Orders' tab

### ISSUE THREAD

**Issue by RuslanaVech** [ita-social-projects/GreenCity#3681]
**Environment:** Windows 10 Pro, Browser: Google Chrome 94.0.4606.71 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** December 21, 2021

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Log in as an admin

**Steps to reproduce**
1. Go to UBS-admin cabinet via profile
4. Click on the "Orders" tab
3. Hover over the column border (e.g. "Order number") 
4. Change the column width

**Actual result**
The column widths cannot be changed

**Expected result**
The column widths changes in the direction of increase or decrease

**User story and test case links**
US #2536 , Jira tc [GC-2104](https://jira.softserve.academy/browse/GC-2104)

**Labels to be added**
"Bug"

**Comment by Yura935** [comment]
This task is already done. We can change the width of columns. But we can choose the column not on the column name but on its body. But now we can't change the first three elements width. Try to change the width of the column "Payment date" and columns after it.

**Comment by KaterynaKhorosh** [comment]
closed as bug fixed
