### ISSUE TITLE
[Admin. Замовлення] Close icon 'Х' is not displayed on the 'Вид таблиці' button

### ISSUE THREAD

**Issue by Larysa28** [ita-social-projects/GreenCity#3712]
**Environment:** OS Linux, Ubuntu 20.04.3 LTS.
   browser Google Chrome Version 96.0.4664.110 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** 29.12.2021

**Preconditions**
Log in to the app as Admin user.

**Steps to reproduce**
1. Go to 'Замовлення'
2. Click on 'Вид таблиці'

**Actual result**
Close 'X' icon is not present on pop-up.

**Expected result**
Close 'X' icon is displayed on pop-up.

**User story and test case links**
E.g.: "User story #3334 
[Test case](https://jira.softserve.academy/browse/GC-2313)

**Comment by KaterynaKhorosh** [comment]
Close 'X' icon is displayed on pop-up.
![2022-01-20_09-35-45](https://user-images.githubusercontent.com/95848159/150293888-1b05f8fa-06e8-415d-beb9-900aeb0d20a4.png)
