### ISSUE TITLE
[UBS Admin.Orders] Current status in not displayed in the DB after status change "Узгодження"-"Сформовано"

### ISSUE THREAD

**Issue by KaterynaKhorosh** [ita-social-projects/GreenCity#3716]
**Environment:** Windows 10 Google Chrome 96.0.4664.110
**Reproducible:** always
**Build found:** 

**Preconditions**
Go to UBS-Admin=>Order
Choose any order with status "Узгодження"

**Steps to reproduce**
1. Click the Edit icon in the "Статус замовлення" column
2. Change current status to "Сформовано" in the opened dropdown list
3. Check status of the current order in DB: SELECT*FROM ORDERS WHERE ID=orders_id

**Actual result**
Status of current order is "Узгодження" in the DB

**Expected result**
Status of current order is "Сформовано" in the DB

**User story and test case links**
 "User story #2538  (https://jira.softserve.academy/browse/GC-2269)
#2901 https://jira.softserve.academy/browse/GC-2270
[Test case] (https://jira.softserve.academy/browse/100)](https://jira.softserve.academy/browse/GC-2300)
![Без імені](https://user-images.githubusercontent.com/95848159/147731642-c3a289d8-8a09-4bbc-a72c-b74e90bf6c37.png)

**Comment by TaniaQC** [comment]
Done
