### ISSUE TITLE
Chat bot service abstraction

### ISSUE THREAD

**Issue by Max877866** [ita-social-projects/GreenCity#3732]
with 2 implementations: Viber and telegram

**Comment by Max877866** [comment]
Or together with email notifications, introduce NotificationProvider

void send(UserNotification)
boolean enabled();

**Comment by dessdee** [comment]
done [card-77084671](https://github.com/ita-social-projects/GreenCity/projects/3#card-77084671)
03.01.2022

**Comment by dessdee** [comment]
done [card-77206137](https://github.com/ita-social-projects/GreenCity/projects/3#card-77206137)

**Comment by dessdee** [comment]
done [card-77688786](https://github.com/ita-social-projects/GreenCity/projects/3#card-77688786)

**Comment by dessdee** [comment]
done [card-77754995](https://github.com/ita-social-projects/GreenCity/projects/3#card-77754995)
15.02.22

**Comment by dessdee** [comment]
done [card-77820109](https://github.com/ita-social-projects/GreenCity/projects/3#card-77820109)
