### ISSUE TITLE
[UBS Admin | Order form] The field of total payment "Замовлення оплачено в розмірі" must be "0.00 grn" after full payment of the order with bonuses

### ISSUE THREAD

**Issue by RuslanaVech** [ita-social-projects/GreenCity#3741]
**Environment:** Windows 10 Pro, Browser: Google Chrome 94.0.4606.71 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** January 10, 2022 

**Preconditions**
1. Log in to the GreenCity page https://ita-social-projects.github.io/GreenCityClient/#/ as Admin user.
2. Open the 'Замовлення' page.
3. Prepare an order paid for with bonuses (e.g. 3685)

**Steps to reproduce**
1. Click on the prepared order's number in the "Номер замовлення" column 
2. Scroll down to the "Деталі замовлення" section
3. Check if the payment is made with bonuses in the "Бонуси" row
4.  Click on the "Оплата замовлення" section 

**Actual result**
The field of total payment "Замовлення оплачено в розмірі" isn't "0.00 грн" but is displayed the number of bonuses used.

**Expected result**
The field of total payment "Замовлення оплачено в розмірі" is "0.00 грн" 

**User story and test case links**
E.g.: "User story #2898 
[Test case GC-2331](https://jira.softserve.academy/browse/GC-2331)"

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:"), Type ("Functional")

![3 3_pay_by_bonuses(2)](https://user-images.githubusercontent.com/95848332/148751766-9cf6ed39-eb4d-4357-96ed-922291a1c1d2.png)

**Comment by yarkokuzyk** [comment]
The field of total payment still shows the number of bonuses that were used.

**Comment by voronkooleksandr** [comment]
@Horokh How did you add payment of bonuses more than the sum of the order?
