### ISSUE TITLE
[UBS Admin | Order form] The invalid field name is displayed in the "Оплата замовлення" section

### ISSUE THREAD

**Issue by RuslanaVech** [ita-social-projects/GreenCity#3742]
**Environment:** Windows 10 Pro, Browser: Google Chrome 94.0.4606.71 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** January 10, 2022

**Preconditions:**

1. Log in to the GreenCity page https://ita-social-projects.github.io/GreenCityClient/#/ as Admin user.
2. Open the 'Замовлення' page.

**Steps to reproduce:**

1. Click on some order's number in the "Номер замовлення" column
2. Scroll down to the "Оплата замовлення" section

**Actual result:**
The "Замовлення **виконано** в розмірі" field name is displayed.

**Expected result:**
The "Замовлення **оплачено** в розмірі" field name is displayed.

**User story and test case links**
User story #2898 
[GC-2331](https://jira.softserve.academy/browse/GC-2331)
[GC-2348](https://jira.softserve.academy/browse/GC-2348)

**Labels to be added**
"Bug", Priority ("pri: low
![4_order_payment(label)](https://user-images.githubusercontent.com/95848332/148754503-082a42a0-a8d3-4e3e-b0e9-f2976ce38a00.png)
"), Type ("UI).

**Comment by KaterynaKhorosh** [comment]
![2022-01-28_13-54-33](https://user-images.githubusercontent.com/95848159/151542862-40a6ed39-846d-41f0-9996-a55990da7727.png)

 "Замовлення оплачено в розмірі" field name is displayed.
