### ISSUE TITLE
[UBS User] After payment confirm page redirection on user orders

### ISSUE THREAD

**Issue by NazarDobriy** [ita-social-projects/GreenCity#3754]
**Preconditions**

1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**

1. Click on logged in user in the right top corner of the screen
2. Select 'UBS-user' from drop down list
3. Click on "Замовлення" tab
4. Click on "Оплатити" order
5. Pay the order
6. In confirm page click on "Повернутися до оплати"
7. Go to user orders page

**Actual result**
https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Expected result**
https://ita-social-projects.github.io/GreenCityClient/#/ubs-user/orders

**User story and test case links**
E.g.: "User story #3491

**Comment by Petryulya** [comment]
After successful order payment, the system redirects the user to the order payment confirmation page (see attachment). The button "Повернутися до оплати" is not provided on this page. The requirements (User story #3491) indicate that it is present only if the payment for the order failed.

![33](https://user-images.githubusercontent.com/102656931/164890553-8ed37078-964b-4b9e-8778-52e6d7c3660f.jpg)
