### ISSUE TITLE
See eco advises  

### ISSUE THREAD

**Issue by sofiya-kozak** [ita-social-projects/GreenCity#376]
As a unregistered user I want to see eco-advice on Greencity website so that I can read interesting information.
Mockup
 
![image](https://user-images.githubusercontent.com/58074253/71668572-16303080-2d72-11ea-9691-78e5332ac53c.png)

Acceptance criteria
1.	WHEN unregistered user scrolls down the page, he can see section#6 
2.	It consists of:
-	Name of the section “Eco-advice” in the middle of landing page in section#6
-	List of advices 
-	Buttons with left and right arrows, in the left side of landing page in section#6
3.	Every advice has an icon with the picture related to the advice and a text of advice
4.	When unregistered user clicks on the button with left arrow, the eco-advices scrolls from the left to right.
5.	When unregistered user clicks on the button with the right arrow, the eco-advices scrolls from the right to left.

Assumption and constraints:
1.	The eco-advice should have not more than 6 lines

**Comment by nomadness** [comment]
The current progress state includes UI placeholders and doesn't include logic for retrieval of advices and pictures from the server-side.

**Comment by rsyvulko** [comment]
Not relevant.
