### ISSUE TITLE
Localization for back-end

### ISSUE THREAD

**Issue by VitaliyDzen** [ita-social-projects/GreenCity#378]
As a user i want to see localized back-end data on every page.

Acceptance criteria:
1. User should see localized news on home page
2. User should see localized tracker header on personal cabinet
3. User should see localized predefined goals on personal cabinet
4. User should see localized advices under every tracker
5. User should see localized facts above every tracker
6. User should see localized habit description on Add new habit popup

**Comment by 0lezhka** [comment]
As a user i want to see localized back-end data on every page.

Acceptance criteria:
     1. User should see localized news on home page
     2. User should see localized tracker header on personal cabinet
     3. User should see localized predefined goals on personal cabinet
     4. User should see localized advices under every tracker
     5. User should see localized facts above every tracker
     6. User should see localized habit description on `Add new habit` popup
