### ISSUE TITLE
[Translate] Incorrect display after loading the page in incognito mode

### ISSUE THREAD

**Issue by NewArtMask** [ita-social-projects/GreenCity#3800]
Incorrect display of the website after loading in incognito mode in a browser

**Current result:**
![image](https://user-images.githubusercontent.com/34275837/151251485-0ce40b77-8002-458a-9f5b-d92a49b1bbb7.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/34275837/151251543-5a7c2904-9672-4eca-8926-7254e4ea8120.png)

**Comment by KaterynaKhorosh** [comment]
![2022-01-28_13-44-16](https://user-images.githubusercontent.com/95848159/151541581-865713ba-0453-417c-8b69-5a6adddeae04.png)

page is loaded correctly in incognito mode in  UA and EN version
