### ISSUE TITLE
[UBS Admin. Orders] Order is not displayed after inserting its number into the "Search" field

### ISSUE THREAD

**Issue by KaterynaKhorosh** [ita-social-projects/GreenCity#3812]
**Environment:** Windows 10 Google Chrome 96.0.4664.110
**Reproducible:** always
**Build found:**28.01.2022

**Preconditions**
1. Sign in  as Admin

**Steps to reproduce**
1. Go to UBS-Admin Orders (https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/orders)'
2. Write any orders number in the "Search" field (ex. 35, 41, 50 etc)

**Actual result**
Orders inserted into  the "Search" field is not displayed 

**Expected result**
Orders inserted into  the "Search" field is displayed in the table

https://user-images.githubusercontent.com/95848159/151590609-a3b2cbd1-1a62-4b91-b0e9-9910c2672f4f.mp4

**Comment by NewArtMask** [comment]
Search works for all cells of table.
