### ISSUE TITLE
[UBS Admin.Orders] not possible to change Orders Status

### ISSUE THREAD

**Issue by KaterynaKhorosh** [ita-social-projects/GreenCity#3813]
**Environment:** Windows 10 Google Chrome 96.0.4664.110
**Reproducible:** always
**Build found:** l28.01.2022

**Preconditions**
1. Sign in as Admin

**Steps to reproduce**
1. Go to UBSadmin Orders https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/orders
2. Click on Редагувати pointer

**Actual result**
Search circle is spun

https://user-images.githubusercontent.com/95848159/151593911-aa296c1d-48f9-4d8e-a7f0-d5cdac318d1b.mp4

**Expected result**
A pop-up is opened with list of statuses to choose

**Comment by NewArtMask** [comment]
No longer up to date
