### ISSUE TITLE
[Text error] error in the text [UBS courier] missing quotes in the text

### ISSUE THREAD

**Issue by KylynYuriy** [ita-social-projects/GreenCity#3819]
**Environment:** IOS, Firefox, Chrome.
**Reproducible:** always.

**Preconditions**

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'

<img width="1203" alt="Знімок екрана  о 00 01 13" src="https://user-images.githubusercontent.com/95444492/151679268-a1be4ae1-985d-4cc1-bbc3-1fce44965c22.png">

**Comment by KaterynaKhorosh** [comment]
![2022-02-21_13-36-07](https://user-images.githubusercontent.com/95848159/154947770-f31aad21-4adf-4a6f-8b03-cafaf87ba30b.png)
