### ISSUE TITLE
[Text error] There is no dot at the end of the test. 

### ISSUE THREAD

**Issue by KylynYuriy** [ita-social-projects/GreenCity#3820]
**Environment:** IOS, Firefox, Chrome.
**Reproducible:** always.

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'

<img width="1073" alt="Знімок екрана  о 00 17 57" src="https://user-images.githubusercontent.com/95444492/151679408-65fe9b54-68b5-469e-8466-167f6b1057ca.png">

**Comment by KaterynaKhorosh** [comment]
Dot is added

![2022-02-21_13-37-26](https://user-images.githubusercontent.com/95848159/154948090-8643f794-0409-40b3-b95f-cee3954f4a59.png)
