### ISSUE TITLE
[Green City] Overlapping elements in the header "UBS courier" button and "Search" when to reduce window change by 25%

### ISSUE THREAD

**Issue by KylynYuriy** [ita-social-projects/GreenCity#3826]
**Environment:** IOS Chrome.
**Reproducible:** always.

https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Steps to reproduce**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'
2. Click on 'Green City' button

[https://ita-social-projects.github.io/GreenCityClient/#/](u
<img width="1271" alt="Знімок екрана  о 09 28 07" src="https://user-images.githubusercontent.com/95444492/151928925-c20e0705-bdf4-4469-a28d-cc7be3aa1976.png">
rl)

**Comment by KaterynaKhorosh** [comment]
no overlapped elements when reduce window change by 25%

**Comment by OliaFed** [comment]
20.04.2022 The defect was not fixed
While resizing the page 'UBS courier' label overlaped with the 'Search' icon

**Comment by voronkooleksandr** [comment]
I delete Tips*Tricks from Header (another task) and everything started to work!

**Comment by TaniaQC** [comment]
The bug has been fixed.
