### ISSUE TITLE
[BurgerMenu] Еhe first menu item "About-us" or "Про нас" is not displayed" when the code validation menu is open

### ISSUE THREAD

**Issue by KylynYuriy** [ita-social-projects/GreenCity#3827]
**Environment:** IOS mac Firefox.
**Reproducible:** always.

**Steps to reproduce**
1. Go to (https://ita-social-projects.github.io/GreenCityClient/#/ubs)
2. Click on 'resize windows to get burger menu'
3. 2. Click on burger menu

**Actual result**
<img width="1271" alt="Знімок екрана  о 10 15 44" src="https://user-images.githubusercontent.com/95444492/151935244-438f84a2-579d-4bee-8c9e-3d7ad19b19f4.png">

**Expected result**
Attached screenshots or mock-ups if available.
<img width="1271" alt="Знімок екрана  о 10 23 08" src="https://user-images.githubusercontent.com/95444492/151935229-5fb016f9-622a-41a0-8d07-f770212a1ec0.png">

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by NewArtMask** [comment]
Not reproducible
