### ISSUE TITLE
[UBS | Courier] Incorrect calculating of points

### ISSUE THREAD

**Issue by NewArtMask** [ita-social-projects/GreenCity#3834]
**Preconditions**
- Log into GreenCity https://ita-social-projects.github.io/GreenCityClient/#/ as an existing user.

**Steps to reproduce**
1. Go to 'UBS кур'єр' tab
2. Click on 'Замовити кур'єра'
3. Fullfill required data
5. Add points (the points amount must be less then order amount)
6. Add the certificate
7. Remove the certificate
6. Pay attention to the amount section and the points section

**Actual result:**
![image](https://user-images.githubusercontent.com/34275837/152180176-11fd9d5a-e230-4480-af12-1ec075dbe863.png)
![image](https://user-images.githubusercontent.com/34275837/152179231-501f3e58-3851-456b-a0a5-05ca67d9c531.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/34275837/152180286-0f9a55d7-5cf8-4005-9377-75d6e7139407.png)
![image](https://user-images.githubusercontent.com/34275837/152180311-d7bcb3a2-0207-440c-b350-61330fcf887d.png)

**Comment by OliaFed** [comment]
Certificates dont work. BLOCKED
