### ISSUE TITLE
See footer on landingpage

### ISSUE THREAD

**Issue by sofiya-kozak** [ita-social-projects/GreenCity#384]
User story: 
As a user I want to see footer so that I can go to appropriate page or link 
 
Mockup
![image](https://user-images.githubusercontent.com/58074253/71689717-7099b300-2dab-11ea-853b-4fca77efd68c.png)

Acceptance criteria:
1.	User scrolls down the application and sees footer at the bottom of the page. 
2.	Footer contains three sections:
- First section consists of
2.1. logo and name of the application
2.1.1. WHEN user clicks on logo or name of application, system shall navigate to Home page.
2.2. Button "Start to track eco habit"
2.2.1.WHEN user clicks on "Start to track eco habit" button, system shall:
2.2.2. Navigate logged in user to Personal cabinet
2.2.3. display login form for unlogged user.
2.3. Button "App Store"
2.3.1. WHEN user clicks on "App Store", system navigate to AppStore page where user can download Greencity App (as we don`t have such app, the button is not active)
2.4. Button "Get it on Google Play"
2.4.1. WHEN user clicks on "Get it on Google Play", system navigate to Google Play page where user can download Greencity App
- Second section consists of
2.5. Text “Main page” (with hidden hyperlink)
2.5.1. WHEN user clicks on "Main page", system shall navigate to Home page.
2.6. Text “Eco-news” (with hidden hyperlink)
2.6.1. WHEN user clicks on "Eco-news", system shall navigate to Eco-news page in landing page. 
2.7. Eco-advice (with hidden hyperlink)
2.7.1. WHEN user clicks on "Eco-advice", system shall navigate to Eco-advice page in landing page.
2.8. Text “Map” (with hidden hyperlink)
2.8.1. WHEN user clicks on "Map", system shall navigate to Map page.
2.9. “My cabinet” (with hidden hyperlink)
2.9.1. WHEN user clicks on "My cabinet", system shall :
2.9.1.1. navigate to "My cabinet"(Eco-habits/Personal cabinet) page, if user is logged in.
2.9.1.2. display login form if user is registered, but not logged in.
2.9.1.3. display registration form if user is not registered the application.
2.10. Text “About us” (with hidden hyperlink)
2.10.1. WHEN user clicks on "About us", system shall navigate to About us page in landing page.
- Third section consists of
2.11. Twitter icon
2.11.1 WHEN user clicks on Twitter icon, system shall navigate to Greencity Twitter page 
2.12. Facebook icon
2.12.1. WHEN user clicks on Facebook icon, system shall navigate to Greencity Facebook page
2.13. LinkedIn icon
2.13.1 WHEN user clicks on LinkedIn icon, system shall navigate to Greencity LinkedIn page
2.14. Text "Copyright 2019. Green City"

Assumption and constraints:

1.	As we don`t have apps in Google Play and AppStore, the buttons are not active till they will be created.
2.	As we don`t have pages in social media, the buttons are not active till they will be created.

#560

**Comment by nomadness** [comment]
2.9.1.2. display login form if user is registered, but not logged in.
2.9.1.3. display registration form if user is not registered the application.
It is impossible to find out if the user is registered when he is not logged in, especially if the user uses an anonymous tab.

2.10.1. WHEN user clicks on "About us", system shall navigate to About us page in landing page.
"About us" page is not yet implemented

**Comment by Nataliia2903** [comment]
Related to User Story #559

**Comment by Nataliia2903** [comment]
Related to story #560
