### ISSUE TITLE
[Personal Cabinet] Message is not received after successful payment for order

### ISSUE THREAD

**Issue by MyroslavStryzhevskyi** [ita-social-projects/GreenCity#3858]
**Environment:** Windows 10x64, Google Chrome 97.0.4692.99
**Reproducible:** always
**Build found:** 09.02.2022

**Preconditions**
1. The user is logged in.
2. Create order (step 1) page is opened: https://ita-social-projects.github.io/GreenCityClient/#/ubs/order

**Steps to reproduce**
1. Choose any service (e.g. 3 packages of 'Текстильні відходи').
2. Scroll down to 'Далі' button and click on it.
3. Fill in 'Особисті дані' and 'Адреса вивозу сміття' sections
4. Scroll down to 'Далі' button and click on it.
5. At step 3 scroll down to 'Замовити' button and click on it.
6. Make payment
7. Open the 'Повідомлення' tab at Personal Cabinet

**Actual result**
The user did not receive a message about successful payment for order. The "У вас ще немає повідомлень" lable is displayed in the 'Повідомлення' tab. Notification item has not a counter and mark of unread messages.
![image](https://user-images.githubusercontent.com/97730221/153090411-fa49aab4-76a8-4a71-93e6-04ddbd58de10.png)

**Expected result**
The user received a message about successful payment for order with title "Оплата пройшла успішно" in the 'Повідомлення' tab. Notification item has a counter and mark of unread messages.
The message body is "Вітаємо! Ви успішно замовили й оплатили послугу «УБС Кур'єр»! УБС Кур'єр приїде по ваші пакети впродовж 2–9 днів від дати оплати послуги. Коли маршрут буде сформовано, ми обов’язково зв'яжемося з вами для узгодження деталей. Якщо у вас залишилися будь-які питання — з радістю відповім! Чат з менеджеркою t.me/nowaste_service_bot чи e-mail hello@nowaste.org.ua"
![120783823-166ac780-c534-11eb-879d-bb0600528b3f](https://user-images.githubusercontent.com/97730221/153090676-f6b838ee-8a21-4e63-9ac2-6cbe785b7331.jpg)
![120785694-0bb13200-c536-11eb-8fd6-c2d72a437a43](https://user-images.githubusercontent.com/97730221/153090699-c2684452-f75f-41b3-9117-9746547d32ee.jpg)

E.g.: "User story #2796
[Test case] https://jira.softserve.academy/browse/GC-2378

**Comment by danylohlynsky** [comment]
It works correctly if do as described
