### ISSUE TITLE
[Ubs courier. Confirmation page] Problems with localization: after language change some elements are not translated into appropriate language

### ISSUE THREAD

**Issue by tetiana-ustymenko** [ita-social-projects/GreenCity#3868]
**Environment:**  All environments
**Reproducible:** always
**Build found:** 12.02.2022

**Preconditions**
1. User is logged into the UBS service
2. Order Details and Personal Data steps are marked as done

**Steps to reproduce**
1. Go to Confirmation page

**Actual result**
-Service items are not translated into English. However, all other elements at the column are translated correctly.
![image](https://user-images.githubusercontent.com/92719887/153721238-bd03bd58-10b1-4b73-a49f-c67f6a00a47c.png)

-Data about the address of export are also translated incorrectly both in English and Ukrainian variants.
![image](https://user-images.githubusercontent.com/92719887/153721306-555cca1c-751c-4c23-a9e8-bbf55a3a9e25.png)

![image](https://user-images.githubusercontent.com/92719887/153721315-dc04c0a2-9247-4e81-97f1-439cb6131dca.png)

**Expected result**
All elements on the Confirmation page are translated in accordance with the chosen language and are appropriately changed after language change.

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by TaniaQC** [comment]
Data about the address of export of the ordered services are still translated incorrectly; there is a mix of English and Ukrainian variants.
![image  png](https://user-images.githubusercontent.com/105351490/168424097-4af150be-981d-4031-a95c-bc85b97e98b1.png)

**Comment by Horokh** [comment]
![image](https://user-images.githubusercontent.com/102593506/180766068-4ef9dd3f-263a-48b1-ad29-7b8ab061f299.png)
