### ISSUE TITLE
[UBS-Admin. Orders] The user does not get bonuses after the order status is changed from 'Сформовано' to 'Скасовано' 

### ISSUE THREAD

**Issue by hsushko** [ita-social-projects/GreenCity#3884]
**Environment:** OS Windows 11 PRO Version 21H2, Browser Google Chrome Version 98.0.4758.102.
**Reproducible:** always.
**Build:** 16.02.2022.

**Preconditions**
1. Create a user and make an order that is paid for money (e.g. 'Безпечні відходи' in quantity of 4 packages (each package is per 250UAH), total amount - 1000UAH).
2. User is Logged in to GreenCity as an Administrator: https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Steps to reproduce**
1. Open 'Замовлення' tab and find order mentioned in preconditions
2. Open the order found in step 1, change the order status on the "Скасовано" and click on the "Зберегти" button
3. Log in to GreenCity as a User
4. Open 'Замовлення' tab and find order mentioned in preconditions
5. Open the order found in step 4
6. Open the 'Рахунок' tab

**Actual result**
The User does not get any bonuses after the order status ischanged to 'Скасовано'

**Expected result**
The amount of bonuses in value of 1000 UAH is displayed on the page.

**User story and test case links**
User story #3633 
Test case (https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)

**Comment by Pavl0-Gural** [comment]
Not a bug
User story #2900
