### ISSUE TITLE
[UBS-Admin. Orders] The statuses 'Підтверджено', 'На маршруті', 'Виконано' are not reproducible due to unworking 'Скасувати' and 'Зберегти' buttons

### ISSUE THREAD

**Issue by hsushko** [ita-social-projects/GreenCity#3886]
**Environment:** OS Windows 11 PRO Version 21H2, Browser Google Chrome Version 98.0.4758.102.
**Reproducible:** always.
**Build found:** 16. 02. 2022.

**Preconditions**
1. Create a user and make an order that is paid for money (e.g. 'Безпечні відходи' in quantity of 4 packages, each package is per 250UAH), total amount - 1000UAH.
2. User is Logged in to GreenCity as an Administrator: https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Steps to reproduce**
1. Open 'Замовлення' tab and find order mentioned in preconditions
2. Open the order found in step 1, change the order status on the 'Узгодження', change the quantity of packages from 4 to 3 at the 'Деталі замовлення' section, then click on the 'Зберегти' button
3. Сhange the order status on the 'Підтверджено', then click on the 'Зберегти' button
4. Сhange the order status on the 'На маршруті', then click on the 'Зберегти' button
5. Сhange the order status on the 'Виконано', then click on the 'Зберегти' button

**Actual result**
No status changes are available because the buttons 'Скасувати' and 'Зберегти' do not work.

**Expected result**
The administrator can change the order status to  'Підтверджено', 'На маршруті', 'Виконано' and the buttons 'Скасувати' and 'Зберегти' properly work.

**User story and test case links**
User story #3633, #2796
Test case (https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)
https://jira.softserve.academy/browse/GC-2386

**Comment by voronkooleksandr** [comment]
Everything works!
Tested
