### ISSUE TITLE
[UBS-User. Bonus notification] The notification about recieved bonuses differs from the required

### ISSUE THREAD

**Issue by hsushko** [ita-social-projects/GreenCity#3891]
**Environment:** OS Windows 11 PRO Version 21H2, Browser Google Chrome Version 98.0.4758.102
**Reproducible:** always
**Build found:** 16.02.2022

**Preconditions**
1. Create a user and make an order that is paid for bonuses (e.g. 'Безпечні відходи' in quantity of 4 packages (each package is per 250UAH), total amount - 1000UAH).
2. User is Logged in to GreenCity as an Administrator: https://ita-social-projects.github.io/GreenCityClient/#/ubs 

**Steps to reproduce**
1. Open 'Замовлення' tab and find order mentioned in preconditions
2. Open the order found in step 1, change the order status on the "Скасовано" and click on the "Зберегти" button
3. Log in to GreenCity as a User (https://ita-social-projects.github.io/GreenCityClient/#/ubs Use credentials as for Client mentioned in preconditions)
4. Open 'Замовлення' tab and find order mentioned in preconditions
5. Open the order found in step 4

**Actual result**
The message is: "Вітання! Сьогодні УБС Кур’єр забрав у вас пакетів: 0. А оплачували ви: 3. Тож фіксуємо для вас депозит для наступного вивозу на суму 0 грн. Гарного дня!" (See the attachment)

**Expected result**
The message consists of: ""Переплата у розмірі 1000 грн зарахована на Ваш бонусний рахунок" is displayed below the "Сума до оплати: ХХХ,ХХ грн" label"

**User story and test case links**
User story #3633 
Test case (https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)
![bonus_message](https://user-images.githubusercontent.com/97729291/154333857-c3ac8d70-108a-437b-a5f2-5488460f53e7.png)

**Comment by mikhaylovamarina** [comment]
There is no ability to find the order mentioned in preconditions on 'Замовлення' tab

**Comment by TaniaIvashkiv** [comment]
There isn`t any notifications about recieved bonuses when order`s status is changed on 'Скасовано'
