### ISSUE TITLE
[UBS-User. Bonus] The bonuses are not accrued in "Рахунок" tab

### ISSUE THREAD

**Issue by hsushko** [ita-social-projects/GreenCity#3892]
**Environment:** OS, browser, it's version, device (for mobile devices).
**Reproducible:** always, rarely, sometimes etc.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
1. Create a user and make an order that is paid for bonuses (e.g. 'Безпечні відходи' in quantity of 4 packages (each package is per 250UAH), total amount - 1000UAH).
2. User is Logged in to GreenCity as an Administrator: https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Steps to reproduce**
1. Open 'Замовлення' tab and find order mentioned in preconditions
2. Open the order found in step 1, change the order status on the "Скасовано" and click on the "Зберегти" button
3. Log in to GreenCity as a User (https://ita-social-projects.github.io/GreenCityClient/#/ubs Use credentials as for Client mentioned in preconditions)
4. Open 'Замовлення' tab and find order mentioned in preconditions
5. Open the order found in step 4
6. Open the 'Рахунок' tab

**Actual result**
The message is "Вам ще не нараховано бонусів." 

**Expected result**
The amount of bonuses in value of 1000 UAH is displayed on the page.

**User story and test case links**
User story #3633 
Test case (https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)

**Comment by Petryulya** [comment]
1. 'Сума до оплати' in the 'Замовлення' tab after using bonuses does not remove them.
2. After canceling the order, bonuses are not returned back to the user.
3. Full amount not shown in step 'Підтвердження'.

![28](https://user-images.githubusercontent.com/102656931/164753843-75976f7e-6b40-4c49-aac4-97fef8422865.jpg)
![30](https://user-images.githubusercontent.com/102656931/164753862-1686e547-468c-4ba4-b726-547bfb67ecd4.jpg)
![31](https://user-images.githubusercontent.com/102656931/164753863-f13ee397-1dbf-410b-b97e-8fbd3cc1d3d9.jpg)
![29](https://user-images.githubusercontent.com/102656931/164753858-0958d327-9d02-4157-a7c5-0a2bd24d777a.jpg)
