### ISSUE TITLE
[UBS-User. Bonuses] The amount of bonuses in 'Рахунок' tab and order tab differs

### ISSUE THREAD

**Issue by hsushko** [ita-social-projects/GreenCity#3903]
**Environment:** OS Windows 11 PRO Version 21H2, Browser Google Chrome Version 98.0.4758.102
**Reproducible:** always
**Build found:** 17.02.2022

**Preconditions**
1. Create a user and make an order

**Steps to reproduce**
1. Pay for the order by: money - 250UAH, bonuses - 250UAH and certificate - 500UAH (e.g. 'Безпечні відходи' in quantity of 4 packages, each package is per 250UAH), total amount - 1000UAH.

**Actual result**
500 uah bonuses are used for payment instead of 250 uah

**Expected result**
The user has got 250 uah bonuses and can use the accurate amount of them (250 uah)

**User story and test case links**
User story #3633 
Test case (https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)
![bonus_is](https://user-images.githubusercontent.com/97729291/154476453-778775e6-1346-427a-9221-823303b7df1b.png)
![bonus_is2](https://user-images.githubusercontent.com/97729291/154476461-d8594758-68e5-49c2-a0b7-5a2a003bbcb1.png)
![bug_is3](https://user-images.githubusercontent.com/97729291/154476463-018928a8-96ed-49e4-9464-06afe863d284.png)

**Comment by voronkooleksandr** [comment]
All works correctly! Everything was tested!
