### ISSUE TITLE
[UBS User | Orders Page] Incorrect message in Order Cancellation pop-up in English

### ISSUE THREAD

**Issue by ivan-hrabarskyi** [ita-social-projects/GreenCity#3906]
**Environment:** All environments
**Reproducible:** always
**Build found:** 17.02.2022

**Preconditions**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'
2. Log into GreenCity UBS with user that has orders with order status 'Formed' and payment status 'Unpaid' in Orders Page
3. Click on Username dropdown in upper right corner
4. Click on 'UBS-user' button
5. Click on 'Orders' button on the left panel

**Steps to reproduce**
1. Click on language switcher on the top of the page
2. Click on 'En' button
3. Click on 'Cancel' button in any order

**Actual result**
Appears pop-up with following message: "If you cancel, the changes will be lost. Do you really want to cancel the changes?".
![image](https://user-images.githubusercontent.com/92604984/154548163-979ab6ea-21f5-4ac2-ac74-fe26764219de.png)

**Expected result**
Appears pop-up with following message: "If canceled, this order will be deleted. Do you really want to cancel the order?";

**User story and test case links**
E.g.: "User story #3488

**Comment by yarkokuzyk** [comment]
Blocked
When a user makes an order and tries to check it in the cabinet(UBS-user), he cannot find it there, but when the admin tries, it displays correctly.

**Comment by TaniaIvashkiv** [comment]
The first sentence in the message is grammatically constructed incorrectly. Must be "If canceled, this order will be deleted. Do you really want to cancel the order?";
![Знімок екрана 2022-06-23 125848](https://user-images.githubusercontent.com/105448699/175272990-fefc3b45-e182-47ff-b74f-f58928858a0c.png)
