### ISSUE TITLE
[UBS User | Orders Page] Order with payment status 'Half paid' can be cancelled

### ISSUE THREAD

**Issue by ivan-hrabarskyi** [ita-social-projects/GreenCity#3907]
**Environment:** All environments
**Reproducible:** always
**Build found:** 18.02.2022

**Preconditions**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'
2. Log into GreenCity UBS with user that has orders with order status 'Formed' and payment status 'Half paid' in Orders Page
3. Click on Username dropdown in upper right corner
4. Click on 'UBS-user' button
5. Click on 'Orders' button on the left panel

**Steps to reproduce**
1. Find order with order status 'Formed' and payment status 'Half paid'

**Actual result**
Order with order status 'Formed' and payment status 'Half paid' has 'Cancel' button
![image](https://user-images.githubusercontent.com/92604984/154650516-1986ea7a-a3a4-4ea7-9637-9ad360ad22e6.png)

**Expected result**
Order with order status 'Formed' and payment status 'Half paid' doesn't have 'Cancel' button

**User story and test case links**
[Test case](https://jira.softserve.academy/browse/GC-2186)"

**Comment by OliaFed** [comment]
BLOCKED because of the state HALFPAID

**Comment by Trololololololololololololo** [comment]
Blocked by impossibility to create order with payment status 'Half paid'
