### ISSUE TITLE
[UBS courier/Personal data] More than 4 addresses are saved

### ISSUE THREAD

**Issue by zubachihor** [ita-social-projects/GreenCity#3909]
**Environment:** All environments
**Reproducible:** always
**Build found:** 18.02.2022
E.g. "commit 147fa44"

**Preconditions**
Preconditions:
1. Login to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
2. UBS Order form is opened
3. All required fields on the tab “Деталі замовлення” are filled

**Steps to reproduce**
1. Go to 'Personal Data' page
2. Scroll down to 'Garbage collection address'

**Actual result**
More than 4 addresses are saved
Attached bug screenshots
![image](https://user-images.githubusercontent.com/84742125/154661488-a0e29532-aacf-4cd8-b90e-801af42858cc.png)

**Expected result**
The limit on the page - 4 addresses

**User story and test case links**
#2533 
[Test case](https://jira.softserve.academy/browse/GC-2069)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by NewArtMask** [comment]
No longer up to date
