### ISSUE TITLE
[UBS User | Orders Page] Orders are not loaded

### ISSUE THREAD

**Issue by ivan-hrabarskyi** [ita-social-projects/GreenCity#3913]
**Environment:** All environments
**Reproducible:** always
**Build found:** 20.02.2022

**Preconditions**
1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'
2. Log into GreenCity UBS with user that has orders in Orders Page

**Steps to reproduce**
1. Click on Username dropdown in upper right corner
2. Click on 'UBS-user' button
3. Click on 'Orders' button on the left panel

**Actual result**
Orders are not loaded, following error message appears "Oops, something went wrong. Please reaload page or try again later"
![Screenshot 2022-02-20 202520](https://user-images.githubusercontent.com/92604984/154858162-c5af402c-fb20-4203-8f37-c99ee1987cd2.png)
![Screenshot 2022-02-20 202413](https://user-images.githubusercontent.com/92604984/154858168-f4a6755f-eff9-47f6-a4b7-3028bd0bac17.png)

**Expected result**
All orders are loaded and shown on the page

**User story and test case links**
E.g.: "User story #3477

**Comment by Horokh** [comment]
Bud  is  fixed
