### ISSUE TITLE
[USB-User. Замовлення] The order does not consist of 'Частково оплачено' in user's 'Замовлення' tab notwithstanding the fact that in admin tab the status is changed on 'Частково оплачено'

### ISSUE THREAD

**Issue by hsushko** [ita-social-projects/GreenCity#3916]
**Environment:** OS Windows 11 PRO Version 21H2, Browser Google Chrome Version 98.0.4758.102
**Reproducible:** always
**Build found:** 21.02.2022

**Preconditions**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#]
2. The tab "Замовлення" in the personal cabinet is opened
3. Opened orders page - "Поточні замовлення" tab
4. Client has orders with status ‘Сформовано’ payment 
5. Log out from User's page

**Steps to reproduce**
1. Login as admin
2. Click on the last paid order
3. Chanhe the order details (add some additional packeges so that the price is higher than it was before)
4. Click on 'Зберегти'
5. Check if the order status is 'Сформовано' and 'Частково оплачено'
6. Log out from admin page
7. Log in as a User
8. Click on 'Замовлення'
9. Check if the order status has been changed

**Actual result**
The order status of the user is without changes (See the attachment 1)

**Expected result**
The order status of the user is changed both in Admin tab and User tab (See the attachment 2)

**User story and test case links**
User story #3488 
Test case (https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)
![cancel_1](https://user-images.githubusercontent.com/97729291/155025835-c23c1f49-3f49-41bc-bb6a-281d8b6a624b.png)
![cancel_2](https://user-images.githubusercontent.com/97729291/155025839-090a88de-5c1a-40ba-94e7-7579602c594a.png)

**Comment by Petryulya** [comment]
**Actual result**
1. The payment status 'Частково оплачено' changes temporarily until the 'Зберегти' button is pressed.
2. On the user page, the status 'Оплачено' also does not change.

https://user-images.githubusercontent.com/102656931/167251113-fb029d31-0e71-407a-a485-ae62ebeb71f3.mp4

![image](https://user-images.githubusercontent.com/102656931/167251343-407f074a-d38e-4e79-953f-8875aeb75624.png)

**Expected result**
User order status 'Частково оплачено 'changes in both Admin tab and User tab after changing the number of waste bags.
