### ISSUE TITLE
[UBS-Admin.Customers] Admin cannot filter users by 'Registration date' in the system

### ISSUE THREAD

**Issue by annachopyk** [ita-social-projects/GreenCity#3918]
**Environment:** Version 98.0.4758.102 (Official Build) (64-bit)
**Reproducible:** always

**Prerequisites:**
Apply 'USE greencity_ubs' in the Database tool
Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
Log in as admin with valid credentials
Go to 'Customers'
The table with clients contains at least 2 records

"Check expected result of users quantity:
" SELECT count(distinct users.id)\n" +
            " FROM users\n" +
            " INNER JOIN orders\n" +
            " ON orders.users_id = users.id\n" +
            " where date_of_registration between '%s' and '%s'"

**Steps to reproduce**
1.Click on the 'Filter' button
2. Input in 'Registration date' field  date. The date should be in the 'DD/MM/YYYY' format.
3. Click on the 'Filter' button

**Actual result**
The page is constantly loaded, the data is not filtered

**Expected result**
Total customers show number of users with spesific date. Use the query to find the right number of users.

[Test case][GC-2455](https://jira.softserve.academy/browse/GC-2455)
![image](https://user-images.githubusercontent.com/95702407/155101669-b3437112-1d20-4068-9927-070684e7a61e.png)

**Comment by Andrii-Yezenitskyi** [comment]
Dates are being sent in the wrong format. The right one is `YYYY-MM-DD`
![](https://user-images.githubusercontent.com/98427395/168070098-f66abb56-f572-42f4-a0d4-b36cf3534189.png)

**Comment by TaniaQC** [comment]
Done
