### ISSUE TITLE
[API | Order Controller] Incorrect responce of getFondyStatus with status code 200

### ISSUE THREAD

**Issue by ivan-hrabarskyi** [ita-social-projects/GreenCity#3947]
**Environment:** All environments
**Reproducible:** always
**Build found:** 30.02.2022

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Authorize as a user with any orders

**Steps to reproduce**
1. Click on 'order-controller'
2. Click on request GET/ubs/getFondyStatus/{orderId}
3. Click on 'Try it out' button
4. Enter the ID of authorized user order
5. Click on 'Execute' button

**Actual result**
Response with 'null' value of 'paymentStatus' recieved every time
![image](https://user-images.githubusercontent.com/92604984/160899605-b5761a6a-750e-4ecf-a8af-91c4605c0bcc.png)

**Expected result**
Response with certain value of current order 'paymentStatus' recieved ('PAID'; 'UNPAID'; HALF_PAID; PAYMENT_REFUNDED)

**Comment by NewArtMask** [comment]
Not a bug.
