### ISSUE TITLE
[Sign Up UBS] The mockup doesn't match with the actual page

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#3948]
**Environment:** Windows 10, Google Chrome 99
**Reproducible:** always
**Build found:** 31.03.2022

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Click the 'Sign Up' button
3. Compare the page with the mockup
4. Take a look at the color and the type of the bag in the image, font, the size of fields, spelling mistake in the word'Акаунт', 'Увійти' button, color of placeholder, the enter button, 'Ім`я користувача', the text below 'Вітаємо!' 

**Actual result**
The mockup is totally different from the actual page
![2022-03-31_11-28-06](https://user-images.githubusercontent.com/102300943/161011963-514806fb-f98d-4058-ba65-abde3a1d260f.jpg)

**Expected result**
Page meets it's mockup
![2022-03-31_11-27-45](https://user-images.githubusercontent.com/102300943/161011919-504d20e2-4f80-45bb-976c-fd1bba28837b.jpg)

**Mockup link**
[https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=13193%3A7414](url)

**Comment by valeriia2301** [comment]
Following issues were fixed: color and the type of the bag in the image, font, the size of fields, 'Увійти' button, color of placeholder,  'Ім`я користувача'.
Following issues are not issues: spelling mistake in the word'Акаунт', the enter button, cos we have issue in mockup, so these 2 items work as expected.
This issue wasn't fixed: the text below 'Вітаємо!' (mistake in word 'внеси', it should be 'внесiть')

**Comment by Horokh** [comment]
Акаунт  пишуть  з  1 літерою 'k'  зараз  вірно  відображено
