### ISSUE TITLE
[Sign Up UBS] The error message text is "Пароль повинен містити принаймі 8 символів" instead of "Пароль повинен містити принаймі 8 символів без пробілів"

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#3951]
**Environment:** Windows 10, Google Chrome 99
**Reproducible:** always
**Build found:** 01.04.2022

**Preconditions**
Open the link https://ita-social-projects.github.io/GreenCityClient/#/ubs
Choose the Ukrainian language as the main language

**Steps to reproduce**
1. Click the 'Зареєструватись' button
2. Enter 7 valid signs into the 'Пароль' field (e.g. '12Oh@as')
3. Take a look at the error message text
4. Do the same steps with the English chosen language

**Actual result**
The error message text is 'Пароль повинен містити принаймі 8 символів'
The error message text is 'Password must be at least 8 characters long'

**Expected result**
The error message text is 'Пароль повинен містити принаймі 8 символів без пробілів'
The error message text is 'Password must be at least 8 characters long without spaces'

**User story and test case links**
E.g.: "User story #619 

**Labels to be added**
"Bug"

**Comment by voronkooleksandr** [comment]
Everything works)
![image](https://user-images.githubusercontent.com/61209463/170733147-3682a138-5dc8-4f14-9b26-fd02c7517370.png)
