### ISSUE TITLE
[Sign up. USB] Incorrect popup notification message appears during registration

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#3955]
**Environment:** Windows 10, Chrome (версія: 97.0.4692.99)
**Reproducible:** always
**Build found:** 02.04.22

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Click on 'Sign up' button
3. Enter valid values in all fields
4. Click on 'Sign up' button
5. Pay attention to the popup message at the top of the page

**Actual result**
The popup with text "snack-bar.success.sign.up" is shown on the screen (see attached file)

**Expected result**
The popup with text "You successfully registered on this site. Please verify your email address in mailbox" is shown on the screen

**User story and test case links**
#29

![10](https://user-images.githubusercontent.com/102656931/161345591-849981d6-5849-48f4-8992-be54d4d0d7a5.jpg)

**Comment by NewArtMask** [comment]
No longer up to date
