### ISSUE TITLE
[UBS. Home page] Link for Sorting rules wastes are absent

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#3957]
**Environment:** all
**Reproducible:** always
**Build found:** 03.04.22

**Preconditions** Choose to display the page in English (top right)

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Scroll down to 'How to prepare?'
2. Pay attention to the inscription 'check out our Rules of sorting wastes (link)'

**Actual result**
1. Check out our **Rules of sorting** wastes
2. The word 'link' inactive

**Expected result**
1. Check out our **Sorting rules** wastes
2. The link redirects the user to the page for Rules of sorting wastes

**User story and test case links**
...
![13](https://user-images.githubusercontent.com/102656931/161426098-b0d765e6-0e07-4b02-ac1a-2fb4df8a0e99.jpg)

**Comment by TaniaQC** [comment]
Done
