### ISSUE TITLE
[UBS. Home page] Shape and color 'Subscribe' button does not match the mockup

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#3960]
**Environment:** all browsers
**Reproducible:** always
**Build found:** 03.04.22

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Scroll down to 'Subscribe to useful newsletter'
3. Pay attention to the 'Subscribe' button

**Actual result**
The shape and color of the 'Subscribe' button are different from the 'Call-up the courier' button (see attached file)

**Expected result**
The shape and color of the 'Subscribe' button are the same as the 'Call-up the courier' button

**User story and test case links**
...

![16](https://user-images.githubusercontent.com/102656931/161448656-5ce282fe-0c73-4d6e-8425-a1244e0f1383.jpg)

**Comment by Petryulya** [comment]
Expected result
The first letter is capital, the rest are lowercase :)

![image](https://user-images.githubusercontent.com/102656931/167177161-1b1bc0ff-4d07-4317-9100-3f87975fc3b2.png)

**Comment by OlehPetryshynTester** [comment]
**Actual result**
The button "ПІДПИСАТИСЯ" has all letter in the upper case
**Expected result**
The "Підписатися" button has the first letter in upper case, the rest - in lower case
