### ISSUE TITLE
[Sign up. USB] The inactive scroll bar is present after the registration popup appears

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#3961]
**Environment:** Windows 10, Chrome (Версія 97.0.4692.99) & Microsoft Edge (Версія 100.0.1185.29)
**Reproducible:** always
**Build found:** 04.04.22

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Click on 'Sign up' button
3. Pay attention to the background on the right, where there is a scroll bar (see attached file)

**Actual result**
An inactive scroll bar is present on the page

**Expected result**
The scroll bar should be active if the registration pop-up does not fit on the screen. There should be no scroll bar if the registration pop-up is placed on the screen.

**User story and test case links**
#2929

![17](https://user-images.githubusercontent.com/102656931/161554990-ded782d6-4c22-41e0-860a-a9130691b6b8.jpg)

**Comment by voronkooleksandr** [comment]
Checked! Everything works on 3 different browsers!

![image](https://user-images.githubusercontent.com/61209463/166218114-c92b4dab-dda0-4a29-b320-edf2d67e7cea.png)

![image](https://user-images.githubusercontent.com/61209463/166218186-9047fa8f-2a25-43ca-8f9e-2abdb2cc404a.png)
