### ISSUE TITLE
[UBS.Order] Address is duplicated when creating new order with comment to existing address

### ISSUE THREAD

**Issue by Mukola1983** [ita-social-projects/GreenCity#3963]
**Environment:** All browsers
**Reproducible:** always.
**Build found:** 07.04.2022
E.g. "commit 147fa44"

**Preconditions**
User has registered address

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Login as user
3. Click on Call-up the courier button
4. Fill-in step 0 and 1 with correct data
5. Choose existing address 
6. Add coment to the address
7. Click next button
8. Click cancel button
9. Click   'yes save'  button
10. Repeat step 3-5 

**Actual result**
There are two the same addreses

**Expected result**
There is only unique address

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Petryulya** [comment]
If the user adds a comment to his address, the address is completely duplicated on the ordering page ('Personаl data' step) and in the 'User date' tab (see attached files)


![20](https://user-images.githubusercontent.com/102656931/163674013-ecf0b388-b7bd-4ee4-9865-b56088c17ede.jpg)
![19](https://user-images.githubusercontent.com/102656931/163674007-dac8f784-d34b-40dd-9fd5-bcd6a91bee32.jpg)

**Comment by Andrii-Yezenitskyi** [comment]
@Petryulya Server started receiving new updates just a few hours ago. Please, check again.
