### ISSUE TITLE
[UBS Admin Orders] Column with 'select' is disappear

### ISSUE THREAD

**Issue by olga210500** [ita-social-projects/GreenCity#3969]
**Steps to reproduce**
1. Log in as Admid
2.  Go to Orders table
3. Click on 'Вид таблиці'
4. Check "Відображати всі колонки"
5. Uncheck  "Відображати всі колонки"
6. Select  columns to display
7. Click on 'Вид таблиці'

**Actual result**
When all columns unselected:
![image](https://user-images.githubusercontent.com/47634207/163238450-cbb6ebdf-7f78-4eec-b432-3fa6cde35dcb.png)

**Expected result**
Column with selectors appears when one or more colums are selected:
![image](https://user-images.githubusercontent.com/47634207/163992488-5ca29d17-cc31-493c-a828-933592b82b11.png)

But when all colums usnelected table is empty
![image](https://user-images.githubusercontent.com/47634207/163229186-fd05bff5-46ca-4330-a4b9-c864cedbe71a.png)

**Comment by Petryulya** [comment]
The requirements for the UI interface are being clarified
