### ISSUE TITLE
[UBS-User. Orders] Address popup overlaps text field so can't change street name

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#3979]
**Environment:** Windows 10, Chrome (Версія 97.0.4692.99) & Microsoft Edge (Версія 100.0.1185.29)
**Reproducible:** sometimes
**Build found:** 16.04.22

**Preconditions**
The registered user is logged in (https://ita-social-projects.github.io/GreenCityClient/#/)

**Steps to reproduce**
1. Click on 'Замовити Кур’єра'
2. Fill in the fields 'Послуги' (e.g. 'Текстильні відходи' -> 'Кількість пакетів' = 5 pieces)
3. Click on 'Далі' button
4. Click on 'Додати адресу' button
5. Pay attantion to the 'Додати адресу' button
6. Enter the first letter of the street name in the 'Вулиця' textfield
7. Select a street name from the popup
8. Try changing the name of the street

**Actual result**
1. Button title 'Додати адресу' is not centered
2. Popup field with street name overlaps input field
(see attachment)

**Expected result**
1. Button title 'Додати адресу' is centered
2. Popup field with street name does not overlaps input field

![22](https://user-images.githubusercontent.com/102656931/163681023-c07b522a-20aa-4aad-8ac4-fd48a2d22c1d.jpg)
![23](https://user-images.githubusercontent.com/102656931/163681274-ef8716ee-5561-4fab-9361-8ce5ab572c58.jpg)

https://user-images.githubusercontent.com/102656931/163681027-6b15f1ab-bdf2-4e1b-a66b-83a36b0369e9.mp4

**Comment by NewArtMask** [comment]
![image](https://user-images.githubusercontent.com/34275837/164200569-d91af6f0-0c27-486f-9944-067ae8aaaf3d.png)

Figma: https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=13758%3A54283
