### ISSUE TITLE
[UBS-User. Orders] After changing languages, the user returns to the first step of the order

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#3988]
**Environment:**  Windows 10, Chrome (Версія 97.0.4692.99) 
**Reproducible:** always
**Build found:** 19.04.22

**Preconditions**
1. The registered user is logged in (https://ita-social-projects.github.io/GreenCityClient/#/ubs)
2. Page display language - Ukrainian

**Steps to reproduce**
1. Click on 'Замовити Кур’єра'
3. Fill in the fields 'Послуги' (e.g. 'Текстильні відходи' -> 'Кількість пакетів' = 5 pieces)
4. Click on 'Далі' button
5. Pay attention, user has moved to the second step registration "Особисті дані"
6. Сhange the page display language to English (in the upper right corner)
7. Pay attention to which step of registration user is
 

**Actual result**
User has moved to the first step "Order details"

**Expected result**
The user stays on the actual orders page 'Personal data' and does not return to the first step

**Comment by IrynaKhyliuk** [comment]
Video of a bug

https://user-images.githubusercontent.com/104845656/167295888-ec7ae86d-6859-42a5-9f69-24fbbede9c40.mov
