### ISSUE TITLE
[UBS, Orders] The incorect warning message appears in the 'Your orders' page

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#3998]
**Environment:** Windows 10, Google Chrome 100
**Reproducible:** always
**Build found:** 21.04.2022

**Preconditions**
Steps to reproduce
1.Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'
2.Log into GreenCity UBS with user that has orders in Orders Page
3.Click on Username dropdown in upper right corner
4.Click on 'UBS-user' button
5.Click on 'Orders' button on the left panel
6.Click on 'Cancel' button in any order
7.Take a look at the warning message text

Actual result: Warning message appears with the 'If you cancel, the changes will be lost. Do you really want to cancel the changes?' text
Expected result: The message should be the next 'If you will cancel this order it will be deleted. Do you really want to cancel this order?'

![123](https://user-images.githubusercontent.com/102300943/164515364-21ab990e-0014-4ec0-ac4b-57fc2672e659.jpg)

**Labels to be added**

**Comment by anastasiialutsiv** [comment]
Not changed warning message

Actual result: Warning message appears with the 'If you cancel, the changes will be lost. Do you really want to cancel the changes?' text

Expected result: The message should be the next 'If you will cancel this order it will be deleted. Do you really want to cancel this order?'

**Comment by SavchuckNadia** [comment]
<img width="1440" alt="Знімок екрана 2022-05-15 о 23 59 36" src="https://user-images.githubusercontent.com/84589119/168493594-8fbde678-68d6-4331-9e77-23f806c4069b.png">

The bug was fixed. Review this issue again.

**Comment by anastasiialutsiv** [comment]
Yes, you are right. If log in as a user - the bug is fixed, but I found this defect in admin cabinet. You should log in as admin, make the same steps. Please, check it
