### ISSUE TITLE
[UBS Orders Admin] The UI defect in the 'Export time' field

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4007]
**Environment:** Windows 10, Google Chrome 100
**Reproducible:** always
**Build found:** 23.04.2022

**Preconditions**
1.Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2.Log in as admin

**Steps to reproduce**
1. Click the 'UBS-admin' button in the dropdownmenu
2. Click 'Orders' button
3. Click any 'Order's number' (e.g.57)
4. Go to 'Export details'
5. Take a look at the field
6. Choose the 'Export time' (e.g. 12:30-13:00)
7. Click 'Ok'
8. Take a look at the field

**Actual result**
The chosen 'Export time' does not fit in the field and the blank field is not aligned

**Expected result**
The field is aligned and the chosen time is clearly seen and placed in the field
![2022-04-23_8-04-08](https://user-images.githubusercontent.com/102300943/164878700-f125f0da-a810-4448-add1-6d6beaec57f3.jpg)
![2022-04-23_8-17-37](https://user-images.githubusercontent.com/102300943/164878924-09a5f105-e27e-4195-a62e-a2d9e59476c6.jpg)

**Comment by Horokh** [comment]
Bug  is  fixed

**Comment by annavoroshchuk** [comment]
Bug is fixed
