### ISSUE TITLE
[UBS Orders Admin] Size coursor doesn't work for 'Order's number' and 'Order's status' fields

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4010]
**Environment:** Windows 10, Google Chrome 100
**Reproducible:** always
**Build found:** 23.04.2022

**Preconditions**
1.Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2.Log in as admin

**Steps to reproduce**
1. Go to 'UBS-admin'
2. Open 'Orders' table
3. Hover the mouse on the 'Order's number' and 'Order's status' borders of tables and try to change the size of the columns

**Actual result**
The column size is not changed

**Expected result**
The size of the colums are changed

**Comment by Mukola1983** [comment]
First four columns should be sticky.
