### ISSUE TITLE
[API][Eco News Comment Controller] Received status code 500 but there isn't a description in Swagger

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4012]
Environment: All environment
Reproducible: always
Build found: 23.04.2022

Preconditions
1.Go to Postman
2.Sign In POST greencity-user.testgreencity.ga/ownSecurity/signIn
3.Body {
"email": "XXXX",
"password": "XXXX"
}
Steps to reproduce
1.POST greencity-user.testgreencity.ga/econews/comments/like?id=21

Actual result
Got a 500 Code

Expected result
The 500 Code is described in Swagger

**Comment by danylohlynsky** [comment]
Now if you do that request you will receive Bad Request response
