### ISSUE TITLE
[Sign Up] UI of 'Forgot password' form and 'Sign up' form does not match the mockup

### ISSUE THREAD

**Issue by melnychenkoas** [ita-social-projects/GreenCity#4018]
**Steps to reproduce**

1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'
2. Click on 'Sign in' button
3. Click on 'Forgot password' link
4. Pay attention on UI of the 'Forgot password' form

**Actual result**
Do not match the mockup:

1. The bag and its color
2. The lettering fonts, their colors, size
3. The color of inscription of 'Submit a login link' button and the color of button 'Submit a login link' by default on UBS page
4. The paragraph 'Remember your password ' is not displayed at the bottom of the page
5. The input's height

**Expected result**
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=12201%3A4
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=12206%3A349

**Steps to reproduce**

1. Go to 'https://ita-social-projects.github.io/GreenCityClient/#/ubs'
2. Click on 'Sign up' button
**Actual result**
Do not match the mockup:

1. The input's height
2. The lettering fonts, their colors, size
3. The color of inscription of 'Sign Up' button on UBS page
4. The color of inscription of 'Sign up' button when the button disabled on ubs page
5. The color of 'Sign in' link on ubs page and underlining 'Sign in' link on green city page
6. The typo in 'Please enter your details to sign up' paragraph in ukrainian language

**Comment by Olenazenchenkoo** [comment]
The page 'Sign up' is different than mock up. Look at attachement.
![image](https://user-images.githubusercontent.com/105363982/168486214-4048ea2b-c1a4-4b64-9018-eebf54fbaff5.png)
