### ISSUE TITLE
[UBS-User. Orders] Paid orders show up in the 'Current Orders' tab instead of 'Order History'.

### ISSUE THREAD

**Issue by NewArtMask** [ita-social-projects/GreenCity#4021]
**Preconditions**
1. The User has some orders with 'Виконано' order status.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click 'Замовлення' tab.
2. Click 'Історія замовлень' tab.
3. Take a look at the orders table.

**Actual result**
- Orders with status “Виконано” show up on the "Поточні замовлення" tab instead of “Історія замовлень”.
- Orders with status “Скасовано” are deleted.

**Expected result**
- On the tab “Історія замовлень” only orders with order statuses “Виконано”, “Скасовано” should be shown on it.

**User story:** [#3477](https://github.com/ita-social-projects/GreenCity/issues/3477)

**Comment by OlhaHubarieva** [comment]
Orders with status 'Виконано' don't show up on the 'Історія замовлень' tab.
