### ISSUE TITLE
[API][Eco News Comment Controller] Status code 200 OK is received after changing the parameter name in 'Get all active comments' controller

### ISSUE THREAD

**Issue by MiaSereda** [ita-social-projects/GreenCity#4024]
**Environment:** macOS BigSur, Chrome 100.0.4896.88
**Reproducible:** always
**Build found:**29.04.2022

**Preconditions**
1.Go to Postman
2.Sign In POST greencity-user.azurewebsites.net/ownSecurity/signIn
3.Login as admin
4.Body
{
"email": "string",
"password": "string"
}

**Steps to reproduce**
1.GET greencity.azurewebsites.net//econews/comments/active
2. Parameters:
- ecoNewsId = 1
- page = 1
- size = 5
3. Change parameter name (e.g pagefrtg, sizefgbfb)
4. Run the test

**Actual result**
Status code 200 is received after changing the parameter name 

**Expected result**
Status code 400 Bas Request is received after changing the parameter name

<img width="754" alt="Знімок екрана 2022-04-29 о 11 47 13" src="https://user-images.githubusercontent.com/102227195/165912839-74160f7a-22e9-43bd-bb9f-bdf90844385b.png">
e

**Comment by danylohlynsky** [comment]
If page or size parameters are not present or incorrect values are passed to them, default values will be substituted (page = 0, size = 20). It's not a bug, it's a feature)
