### ISSUE TITLE
[API] Counting of likes on comments always show 1 result, even if its not

### ISSUE THREAD

**Issue by mmyarich** [ita-social-projects/GreenCity#4025]
**Reproducible**: always
**Build found:** 22.04.2022
**Preconditions**
1.Go to Postman
2.Sign In through POST greencity-user.azurewebsites.net/ownSecurity/signIn
Body
{
"email": "string",
"password": "string"
}

**Steps to reproduce**
1. POST greencity.azurewebsites.net/econews/comments/like?id={your value}

**Actual result**
1 (attachment)
Code 200 Ok

**Expected result**
Real number of likes

<img width="571" alt="image" src="https://user-images.githubusercontent.com/102761755/165911142-7c00b40f-b3a7-498a-b69f-eb19560bedcf.png">

**Comment by Andrii-Yezenitskyi** [comment]
`greencity.azurewebsites.net/econews/comments/like` doesn't return the number of likes at all. '1' in your attachment is the row number.
