### ISSUE TITLE
[Admin.Orders] The 'Деталі замовлення' section name includes columns that are not in the requirements and the name of the 'Замовлення оплачено в розмірі' column should be 'Оплата'

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4031]
**Environment**: Windows 10, Google Chrome 101
**Reproducible**: always
**Build found**: 30.04.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/
Log in as an administrator

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Замовлення' button
3.Click the 'Вид таблиці' button
4.Scroll down to the 'Деталі замовлення' section name
5.Take a look at the columns

**Actual result**
The columns 'Коментарі до замовлення' and 'Ким заблоковано' are presented in the 'Деталі замовлення' section name and the name of the 'Замовлення оплачено в розмірі' appears

**Expected result**
The columns 'Коментарі до замовлення' and 'Ким заблоковано' are not presented in the 'Деталі замовлення' section name and the name of the 'Замовлення оплачено в розмірі' column is 'Оплата'

**User story and test case links**
E.g.: "User story #3334

**Comment by TaniaQC** [comment]
The columns 'Коментар до замовлення клієнта' and 'Ким заблоковано' are still present in the 'Деталі замовлення'
not presented in the 'Деталі замовлення'

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/180984762-6283ea77-ba94-436a-96fb-52124cf55760.png)
