### ISSUE TITLE
[Eco-News] BugFix_Incorrect_routing

### ISSUE THREAD

**Issue by Mukola1983** [ita-social-projects/GreenCity#4040]
**Preconditions**

**Steps to reproduce**
1. You should be authorized
2. Go to 'My space'  and choose 'My News'
3. Click on the one news and you will be on the detail news page
4. Click on the 'back' button  and you will appear in the general Eco-News list

**Actual result**
Routing does not work correct

**Expected result**
If you opened news from 'My Spase' you should back on this page after click on the 'back' button

**Comment by YBielik** [comment]
After clicking the 'Back' button, the authorized user does not return to the 'My news' page. Goes to the 'My habits' page. Routing does not work correct
