### ISSUE TITLE
[Orders.Admin]All columns in the 'Table view' are not displayed by defolt

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4046]
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 02.05.2022

**Preconditions**
1.Go to https://ita-social-projects.github.io/GreenCityClient/#
2.Sign in as administrator

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Click the 'Table view' button
4.Take a look if all colimns are chosen by defolt

**Actual result**
Not all columns are displayed by defolt

https://user-images.githubusercontent.com/102300943/166212921-61601cc2-2bca-4e70-93de-b6445cc60218.mp4

**Expected result**
All columns of the orders table are displayed by defolt

**User story and test case links**
E.g.: "User story #3334

**Comment by anastasiialutsiv** [comment]
No changes in defect. All columns of the orders table are not displayed by defolt
