### ISSUE TITLE
[Admin.Orders] The information is not presented in the : date of export, time of export, id order from shop, receiving station, responsible caller, driver, logistician, navigator colums

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4069]
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 05.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/
Sign in as admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Scroll the side slidebar and take a look if all columns are filled with information

**Actual result**
The information in the : date of export, time of export, id order from shop, receiving station, responsible caller, driver, logistician, navigator columns is not presented

**Expected result**
All required information is present

**Comment by voronkooleksandr** [comment]
Can you record the video or write more detail about this task?
