### ISSUE TITLE
[Admin.Orders] The checkboxes are not checked in the 'Статус замовлення' menu

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4072]
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 05.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/
Sign in as admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Замовлення' button
3.Click the menu in 'Статус замовлення' field
4.Take a look if the boxes are checked

**Actual result**
The check
![2022-05-05_13-46-29](https://user-images.githubusercontent.com/102300943/166908765-b883c33d-597e-41db-b54a-69781829363a.jpg)
boxes are not checked in the 'Статус замовлення' menu

**Expected result**
All checkboxes should be checked

**Comment by krayevska** [comment]
issue is closed due to story below:
https://github.com/ita-social-projects/GreenCity/issues/3300
