### ISSUE TITLE
[Admin.Orders] The text of the fields in 'Order date' and 'Payment date' is not aligned

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4073]
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 05.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/
Sign in as admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Click the 'Order date' menu
4.Click the 'Payment date' menu

**Actual result**
The text of the fields in 'Order date' and 'Payment date' is not aligned
![2022-05-05_13-52-14](https://user-images.githubusercontent.com/102300943/166910336-9b0364c3-0efc-485f-b243-ebac5230c42e.jpg)

**Expected result**
The text is aligned in the center of the fields and the fields are align with each other

**Comment by TaniaQC** [comment]
There is still improper alignment of text 
![image](https://user-images.githubusercontent.com/105351490/180958094-cc06b802-7db8-4585-a907-262568917b38.png)

**Comment by ghost** [comment]
This bug is not reproducible
