### ISSUE TITLE
[Admin.Orders] There is no possibility to expand the table on whole screen

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4079]
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 06.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/
Sign in as admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Click the 'Table view' button
4.Choose 5 or less columns to be shown
5.Try to expand the table 

**Actual result**
The table doesn't expand with the 5 or less columns shown
![2022-05-06_10-04-12](https://user-images.githubusercontent.com/102300943/167083769-aa63062e-8e1b-4b1f-91c4-dd603b9bb56f.jpg)

**Expected result**
The table can be expanded

**Comment by voronkooleksandr** [comment]
Are there so conditionals in the user story?
