### ISSUE TITLE
[UBS. Sign up] The verification email does not match the mockup UA/EN

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#4084]
**Environment:** all
**Reproducible:** always
**Build found:** 06.05.22

**Steps to reproduce**
1.Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2.Click on 'Sign up' button
4. Enter valid values in all fields
5. Click on 'Sign up' button
6. Go to your mailbox and open the letter to complete the registration
7. Pay attention to the content of the letter

**Actual result**
After registering on the UBS page, the user receives an e-mail from Green City.

**Expected result**
After registering on the UBS page, the user receives an e-mail from UBS (see attached files).
The changes apply to the Ukrainian and English versions of the site.

**User story and test case links**
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=12201%3A2

![image](https://user-images.githubusercontent.com/102656931/167202543-bf6280d0-6673-42cd-afd5-e377db503d18.png)
![image](https://user-images.githubusercontent.com/102656931/167197676-8e850460-ff20-4c92-99e8-ed45377f2cd2.png)
![image](https://user-images.githubusercontent.com/102656931/167203557-1f82d9b1-3780-485f-b610-724748c145a5.png)

**Comment by TaniaIvashkiv** [comment]
The verification email still does not match the mockup UA/EN
Below is the real verification email has got 03.06.22
![image](https://user-images.githubusercontent.com/105448699/175287878-f5a4cbcb-ee49-406b-9f3e-d1b4f292b63e.png)

**Comment by OlegVat** [comment]
The verification email's title has been reviewed and is now accurately displayed.
