### ISSUE TITLE
[Forgot password] A reset password link can be used for the second time after it was already successfully used

### ISSUE THREAD

**Issue by IrynaKhyliuk** [ita-social-projects/GreenCity#4085]
**Environment:** Windows 10 Pro, Chrome 101
**Reproducible:** always
**Build found:** May 6, 2022

**Preconditions**
A user has a registered account in UBS/Greencity.

**Steps to reproduce**
1. Go to GreenCity URL https://ita-social-projects.github.io/GreenCityClient/#/
2. Click on 'Sign in' button.
3. Click on 'Forgot password' link
4. Enter a registered email address in the field and click 'Submit a login link'
5. In the 'Confirm restoring password' letter from the email Inbox, click on 'Change password' button or copy/paste a link into your browser provided below the button.
6. Enter a valid new password (requirements specified here #385) in the 'Password' field, retype it into the 'Confirm password' field and click 'Change password'
7.  In the same 'Confirm restoring password' letter from the email Inbox, click on 'Change password' button again or copy/paste a link into your browser provided below the button.

**Actual result**
A reset password form is opened. User is able to enter a new password again. 

**Expected result**
A page with the following text is opened: "This link is no longer active". To leave the page the user needs to click the ‘Next’ button.

**User story and test case links**
User story #472, #4097
[GC-2626](https://jira.softserve.academy/browse/GC-2626) 

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity:High"), Type ("Functional").

**Comment by voronkooleksandr** [comment]
BA change conditionals
There is a new task 4390

**Comment by TaniaQC** [comment]
The link for restoring the password can not be used more than one time but the notification about the impossibility of the using the link for the second time is different from the one described in the Expected result
![image](https://user-images.githubusercontent.com/105351490/181879863-e8d6f9e6-1058-434c-9468-028fbc36e489.png)

**Comment by NataliaHlazova** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/87066582/189707309-b0ddd433-e8ae-4cf2-875a-6f524a3045f1.png">

**Comment by Olena-Kharkova** [comment]
User can use the link for recovery password more than 1 time which is prohibited by requirements

**Comment by ghost** [comment]
![image](https://github.com/ita-social-projects/GreenCity/assets/130749567/53fad1af-dff2-4040-b8a0-4d67c7a145d6)

Actual result
The notification "This link is no longer active" is not displayed on the password restoring  page after clicking on 'Change password' button again in the  'Confirm restoring password' letter

Expected result
A page with the following text is opened: "This link is no longer active". To leave the page the user needs to click the ‘Next’ button.
