### ISSUE TITLE
[USB-User. Orders] Only the 20 positions are displayed in the orders table and other orders are not available for viewing.

### ISSUE THREAD

**Issue by Petryulya** [ita-social-projects/GreenCity#4089]
**Environment:** all
**Reproducible:** always
**Build found:** 07.05.22

**Preconditions**
1. Logged in to UBS as a User https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Generate 20 orders (the status of orders can be any: paid / unpaid)
3. Pay attention to the contents of the table in the tab "Orders" 

**Steps to reproduce**
1. Create the 21st order on the user page 
2. Pay attention to the contents of the table in the tab "Orders"

**Actual result**
The contents of the table have not changed, the user can see only the previous 20 orders (however, on the admin page, new orders of this user are displayed)

**Expected result**
The user should be able to see all their orders in the "Current orders" table

![image](https://user-images.githubusercontent.com/102656931/167257751-f45700ec-67b5-466e-8cfe-e67a44afdd09.png)

**Comment by Petryulya** [comment]
Pay attention, when you make changes to the order on the Admin page, this order disappears on the User page (see the attached video), but the list still shows 20 positions.

https://user-images.githubusercontent.com/102656931/167263859-73a0ab5d-7599-45aa-9dfe-91240d7e7bf9.mp4

In this video you can see how the data on the Admin page is reset after making changes to the number of order items:

https://user-images.githubusercontent.com/102656931/167264260-6c0304ed-fbe3-4592-82cc-a5ac6fca1289.mp4

**Comment by TaniaQC** [comment]
There are only 10 orders of the user that are available on the first page.

**Comment by marianaharnyk** [comment]
This bug cannot be reproduced.
