### ISSUE TITLE
[UBS-User. Orders] 'Service' entries of the table on the 'Confirmation' page are not translated into English on EN locale   

### ISSUE THREAD

**Issue by IrynaKhyliuk** [ita-social-projects/GreenCity#4096]
**Environment:** Windows 10 Pro, Chrome 101
**Reproducible:** always
**Build found:** May 8, 2022

**Preconditions**
1. A user should be logged in.
2. EN locale should be set on the webpage

**Steps to reproduce**
1. Go to UBS URL https://ita-social-projects.github.io/GreenCityClient/#/ubs
3. Click on 'Call the Courier'
4. Select the city in the opened window (e.g. Kyiv) and click 'Continue'
5. In the table, set valid values in the 'Number of packages' column for each available entry - "Textile waste" 120l, "Safe waste" 120l, "Textile waste" 20l (e.g. 10; 10; 10).
6. Scroll down the page and click 'Next'
7. Fill in obligatory fields in Personal Data tab if needed and click 'Next'
8. Pay attention to the 'Service' entries in the table now. 

**Actual result**
There are "Текстильні відходи", "Безпечні відходи", "Текстильні відходи" entries in the 'Services' column now. 

![screen-capture-_2_](https://user-images.githubusercontent.com/104845656/167297102-ba2c1a0c-415a-434f-b354-0e0193bb7034.gif)

**Expected result**
There are "Textile waste", "Safe waste", "Textile waste" entries in the 'Services' column now. 

**User story and test case links**
#2200 
https://jira.softserve.academy/browse/GC-2081

**Comment by melnychenkoas** [comment]
@IrynaKhyliuk can you check it again? Because it work just fine on my profile.

**Comment by melnychenkoas** [comment]
![image](https://user-images.githubusercontent.com/51752239/167456770-adfad8f1-6f08-4f9d-a1f0-09c75e1932ea.png)

**Comment by IrynaKhyliuk** [comment]
@melnychenkoas It is fine indeed on my side too now.
