### ISSUE TITLE
[UBS courier. Orders. Admin cabinet] The receiver's data in the created order do not match the data that were entered by User in selected option 'The recipient is another person' 

### ISSUE THREAD

**Issue by MiaSereda** [ita-social-projects/GreenCity#4106]
**Environment:** macOS Big Sur 11.6.5, Chrome 100.0.4896.88, Safari 14.1.2
**Reproducible:** always
**Build found:** 09.04.2022

**Preconditions**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Sign in as a User
3. Create order and choose option 'The recipient is another person' 
4. Enter data that differs from User's personal data
5. Sign out 
6. Sign in as Admin

**Steps to reproduce**
1. Open 'UBS-admin'
2. Click on 'Orders'
3. Select the created order

**Actual result**
The receiver's data are not depicted in 'Information about client' according to data that were entered by User in option 'The recipient is another person'. The client’s data are depicted in these fields.

**Expected result**
The receiver's data are depicted in 'Information about client' according to data that were entered by User in option 'The recipient is another person'.

**User story and test case links**
User story #2787 #3453

**Comment by Andrii-Yezenitskyi** [comment]
Values in `anotherClient...` fields should be instead in `sender...` fields in the `/ubs/processOrder` request.
![1](https://user-images.githubusercontent.com/98427395/168271162-43904c67-14e6-4d81-9f97-48bdca3c3e90.png)

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/180983342-997026e1-d834-4a78-a8a3-a8f391a84996.png)
