### ISSUE TITLE
[UBS-User. Orders tab view] The tab "Замовлення" is second and not first in list as in Figma mock-up

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4109]
Environment: Chrome (latest)
Reproducible: always
Build found: 03.05.2022

Steps to reproduce
1. Logged in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
2. Choose UBS-user 
3. Pay attention to the right list

Actual result
tab "Замовлення" is second in the right list
![image](https://user-images.githubusercontent.com/105280048/167618287-8173a125-6f94-4f96-92fc-890b923fdd2c.png)

Expected result
tab "Замовлення" is first in the right list
Mock-up: [ITA UBS styles – Figma](https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17749%3A36515)

**User story and test case links**
 "User story #3477
[Test case] (https://jira.softserve.academy/browse/GC-2164)

**Labels to be added**
"Bug", "Priority: High", "Severity: Low", "UI"

**Comment by voronkooleksandr** [comment]
Can you explain in detail! Everything is as on mock now!
