### ISSUE TITLE
[UBS-User. Orders tab view] UBS left panel doesn't have the arrow to collapse the menu

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4111]
**Environment:** Chrome (latest).
**Reproducible:** always

**Steps to reproduce**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The tab "Замовлення" in the personal cabinet is opened
3. Pay attention to the left menu panel

**Actual result**
There is the arrow before 4 tabs
![image](https://user-images.githubusercontent.com/105280048/167618566-e77d6e0d-6d28-4d00-9b0f-20a5ab7e183b.png)

**Expected result**
List includes 4 tabs
Mock-up: [ITA UBS styles – Figma](https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17749%3A36515)

**User story and test case links**
E.g.: "User story #3477
[Test case](https://jira.softserve.academy/browse/GC-2164)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trial"), Type ("UI")

**Comment by Tvido** [comment]
Not a bug.
We are waiting for changing requirement.
