### ISSUE TITLE
[UBS-User. Orders tab view] Order status should be "Узгоджено" not "Узгодження"

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4114]
**Environment:** Chrome (latest)
**Reproducible:** always

**Steps to reproduce**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The tab "Замовлення" in the personal cabinet is opened
3. The client has a few orders
4. Go to DB greencity-ubs
5. Change Order status "Сформовано" to "Узгоджено" for the record № 1

**Actual result**
Order status became  "Узгодження"
![image](https://user-images.githubusercontent.com/105280048/167620789-8cf69901-d0b8-4f9f-b5f2-88f24d478231.png)

**Expected result**
Order status became  "Узгоджено"

**User story and test case links**
E.g.: "User story #3477 
[Test case](https://jira.softserve.academy/browse/GC-2170)

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: trial"), Type ("UI")

**Comment by TaniaIvashkiv** [comment]
Order status is still 'Узгодження'

![Знімок екрана 2022-06-21 163802](https://user-images.githubusercontent.com/105448699/174813250-49c1eb3e-14d0-40bf-a487-eb1ffce4fb63.png)

**Comment by NataliaHlazova** [comment]
Should it really be "Узгоджено"? In the [user story](https://github.com/ita-social-projects/GreenCity/issues/3477) the status is stated as "Узгодження".

![image](https://user-images.githubusercontent.com/87066582/175234779-73357bd5-dbe6-455c-9564-8134d9b5d538.png)

**Comment by TaniaIvashkiv** [comment]
Hi. Yes 'Узгодження'. Sorry, my mistake. Thank you)

чт, 23 черв. 2022 р. о 09:55 NataliaHlazova ***@***.***> пише:
