### ISSUE TITLE
[UBS-User. Orders tab view] In the collapsed table with order details, the colour of the text does not match the mock-up

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4117]
**Environment:** Chrome, Firefox (latest)
**Reproducible:** always

**Steps to reproduce**

1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. Open Orders page - "Поточні замовлення" tab with order
3. Verify text colour in the collapsed table with order details

**Actual result**
text colour is grey
![image](https://user-images.githubusercontent.com/105280048/167623172-3475dd6b-0efe-4407-995c-a1f1edaea3cd.png)

**Expected result**
text colour is black
mock-up https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=18597%3A52061

**User story and test case links**
E.g.: "User story #3477 
[Test case](https://jira.softserve.academy/browse/GC-2172)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trivial"), Type ("UI")

**Comment by Horokh** [comment]
Text  color  is updated
