### ISSUE TITLE
[Admin.Orders]There is no possibility to side-scroll the table

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4124]
**Environment:** mobile device
**Reproducible:** always
**Build found:** 11.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#
Log in as Admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Try to side-scroll the table

**Actual result**
There is no possibility to side-scroll the table

https://user-images.githubusercontent.com/102300943/167830012-c05e4eb9-80e3-4573-a368-8f609a255a9d.mp4

**Expected result**
There is possibility to side-scroll the table

**Comment by krayevska** [comment]
issue is closed because we are not implementing mobile version of Admin at the moment
