### ISSUE TITLE
[Admin.Orders] There is no possibility to use the 'Search' button

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4127]
**Environment:** mobile device
**Reproducible:** always
**Build found:** 11.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#
Log in as Admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Use the 'Search' button

**Actual result**
There is no possibility to use the 'Search' button
![2022-05-11_14-01-30](https://user-images.githubusercontent.com/102300943/167834679-30b7737c-2e37-47c4-a013-33c305567f27.jpg)

**Expected result**
The search button is usable

**Comment by krayevska** [comment]
issue is closed because we are not implementing Admin table for mobile devices at the moment
