### ISSUE TITLE
[Order form.Step 3] Discrepancy of UI оn 'Підтвердження' step

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4137]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:** 13.05.2022

**Preconditions**

1. Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/
2. Click on 'Увійти'.
3. Log in as a registered user .

**Steps to reproduce**

1. Click on 'UBS кур'єр' and choose location 'Київ'.
2.  Click 'Продовжити' and select the amount of packages (e.g. 'Текстильні відходи' - 1, 'Безпечні відходи' - 2), use bonuses, input numbers of orders in 'Доставка з Еко магазину' section (e.g. 1111111111, 2222222222) and leave comment.
3. Сlick 'Далі' to the 'Особисті дані' step and fill in 'Ім'я', 'Прізвище', 'Мобільний телефон', 'Електронну скриньку, 'Адресу' , 'Comment'.
4. Click on the button 'Далі'  and go on 'Підтвердження' step.
5. Verify UI controls' alighment, fonts, tabulation, size, colour.

**Actual result**
The UI doesn't correspond to the mock-up in Figma. 

1. Incorrect alignment of the step number (e.g '3')
2. The 'Сума' section is not properly aligned with subtitles below.
3. The 'Замовити', 'Відмінити' buttons do not have an equal distance. ( 88*44px and 136*44px)
4. The  'Коментар до замовлення' and 'Коментар до адреси' blocks are not divided in seperate blocks,  headline is not highligted and title 'Коментар до замовлення' is inappropriate.
5. Wrong order of the address' components (e.g. м. Київ, район Деснянський, Столичне шосе, 25, під'їзд 5, Київська область).
6.  The  'Сума оплати' title is not bolded.
7. The 'Назад' button is not pointed.

![Actual result ](https://user-images.githubusercontent.com/105351490/168338298-486c0467-70d5-45c1-b776-77fb8e0a6005.png)

**Expected result**
The UI in the website and mock-up should be identical.

1. The number '3' is in the middle of the round.
2. The 'Сума' section is in the middle position and subtitles are below it.
3. The 'Замовити'and'Відмінити' buttons  are 132*44 px.
4. Instead of  'Коментар до замовлення' block , there should be 'Коментар користувача' one; the two blocks are seperated and headlines are highlighted.
5. The order of the address components is as follows м. Київ, Столичне шосе, 25, під'їзд 5, район Деснянський, Київська область).
6. The 'Сума оплати' title is taken in bold. 
7. The 'Назад' button is pointed.
8. ![Expected result ](https://user-images.githubusercontent.com/105351490/168338459-2d780381-fc51-4683-afa1-b6ea9d0470db.png)

**User story and test case links**
E.g.: "User story #2200,#2541
[Test case](https://jira.softserve.academy/browse/GC-2066
https://jira.softserve.academy/browse/GC-2085"

**Comment by TaniaIvashkiv** [comment]
The 'Сума' section is still not properly aligned with subtitles below.
The 'Коментар до замовлення'headline is not highligted
The 'Назад' button is not pointed
![Знімок екрана 2022-06-23 121530](https://user-images.githubusercontent.com/105448699/175265971-9e23fe52-c493-41ad-aea4-32ccf0602ee4.png).

**Comment by TaniaIvashkiv** [comment]
The 'Сума' section is still not properly aligned with subtitles below.
The 'Коментар користувача' headline is not highligted in bold
![Знімок екрана 2022-06-23 123122](https://user-images.githubusercontent.com/105448699/175267065-9124be3b-7052-49c8-8ed5-ebf218b1b521.png)
.
