### ISSUE TITLE
[Order form. Step 1] The system allows user to add invalid certificate to the order.

### ISSUE THREAD

**Issue by OlhaHubarieva** [ita-social-projects/GreenCity#4139]
**Environment:** OS Windows 10 PRO. Firefox 100.0 (64 bit).
**Reproducible:** sometimes.
**Build found:** 10.05.2022

**Preconditions**
There is the valid certificate with total discount amount greater than 500.00 UAH.
There is the invalid certificate.

**Steps to reproduce**
1.     Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
2.     Log in as a user.
3.     Click on 'Замовити Кур'єра' button.
4.     Select 'Київ' city and click on 'Продовжити' button.
5.     Select services so that the amount of the order is greater than the total discount amount of the valid certificate.
6.     Enter the valid certificate number in 'Certificate section' input field and click 'Активувати' button.
7.     Enter the invalid certificate number in 'Certificate section' input field and click 'Активувати' button.

**Actual result**
'Сертифiкат на cуму XXX грн активовано. Строк дії сертифікату - до YY.YY.YYYY' message is shown, 'Додати ще сертифікат' link is shown.
![зображення](https://user-images.githubusercontent.com/105358315/168419716-38b61a96-e360-4444-a8eb-61a473868436.png)

**Expected result**
'Сертифiкат вже було використано YY.YY.YYYY' error message is shown, 'Додати ще сертифікат' link isn't shown.
![зображення](https://user-images.githubusercontent.com/105358315/168419725-3c1aeead-b56b-49b1-b7f8-c915d1ea8a28.png)

**User story and test case links**
User story #2329 #2481 
[Test case](https://jira.softserve.academy/browse/GC-1980)

**Comment by VadymMakitra** [comment]
Not reproducible
