### ISSUE TITLE
[Order. Step3] In block "Отримувач" phone number has doubled the country code.

### ISSUE THREAD

**Issue by Olenazenchenkoo** [ita-social-projects/GreenCity#4142]
**Environment:** OS Windows 10 21H1
Browser Chrome 100.0.4896.127
**Reproducible:** always.
**Build found:** 7.05.2022

**Steps to reproduce**

1. Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/;
2. Click on 'Увійти';
3. Log in as a registered user;
4. Click on 'UBS кур'єр' tab;
5. Click on "Замовити кур'єра";
6. Choose the city and click buttom "Продовжити";
7. User has filled the "Деталі замовлення" than click "Далі";
8. User go to "Особисті дані"  click field "Відправник інша людина" and fill field "Ім'я","Прізвище","Номер телефону" eg. +380 (67) 696 53 41 than cklick "Далі";
9. User go to "Підтверження" and in the field "Отримувач" the  phone number has doubled the country code.

**Actual result**
In field "Отримувач" phone number has doubled the country code eg. __+380 38 067 69 65341.__

**Expected result**
In field "Отримувач" phone number must be without doubled the country code eg. **+380 (67) 696 53 41.**

**User story and test case links**
E.g.: "User story #2541 
[Test case]https://jira.softserve.academy/browse/GC-2588

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![image](https://user-images.githubusercontent.com/105363982/168442466-e8a761f0-2d01-404a-8956-c045b20ad3f4.png)

**Comment by anastasiialutsiv** [comment]
Defect also reproduces in desktop version.

**Comment by Olenazenchenkoo** [comment]
Not fixed, this bug reproduse again.
![image](https://user-images.githubusercontent.com/105363982/174081632-1131af30-61b8-4c2e-b149-8a5ea074b0f2.png)
