### ISSUE TITLE
[Order form. Step 2] Validation in Email field accepts invalid special characters

### ISSUE THREAD

**Issue by anastasiialutsiv** [ita-social-projects/GreenCity#4143]
**Environment:** macOS Monterey 12.3.1; Safari 15.4
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev

**Steps to reproduce:**
1. Go to GreenCity 
https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Log in as a user 
3. Click on the "Замовити кур'єра" and make order 
4. Go to page "Особисті дані", put in all required fields 

**Steps to reproduce**
1. Click on the field "Email" and fill in "Email" field with invalid email: missing "@” sign
( e.g. howiv47374nenekbetcom)
2. Mark the checkbox “Отримувач інша людина” under the section “Особисті дані”
3. Click on the field "Email" and fill in "Email" field with invalid email: missing "@” sign
( e.g. howiv47374nenekbetcom)

Actual result: System allows to put in invalid email special characters
Expected result: Warning message "Введіть коректний email." near "Email" field should appear. The system shall check for “@”sign as must-haves for this field.

**User story and test case links**
E.g.: "User story #2531

**Comment by mikhaylovamarina** [comment]
Actual result: We can enter e-mail without must-have signs
Expected result: Warning message "Введіть коректний email" near "Email" field should appear
