### ISSUE TITLE
[Personal Cabinet - Order details] 'Оплачено' field is not changed to the 'Часткова оплата' field after admin made changes to existing order in "Послуга" column

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4148]
**Environment:** Chrome (latest)
**Reproducible:** always

**Preconditions**
The registered user has made and paid order №

**Steps to reproduce**
1. Log in under admin and click on "Замовлення" tab and select order №
2. Check "Статус оплати" in field is "Оплачено" (picture 2)
3. In "Деталі замовлення" change quantity (more than in order) in "Підтверджена к-ть" column and Save (picture 1)
4. Check "Статус оплати" field in the admin account and in the user account for order № (picture 2 and 3)

**Actual result**
"Статус оплати" in the field for order №  is "Оплачено" and doesn't change (picture 2 and 3)
<img width="828" alt="bug1" src="https://user-images.githubusercontent.com/105280048/168482651-6631f43e-41f3-4d52-bb55-37808dac8a0b.PNG">
<img width="868" alt="bug1 2" src="https://user-images.githubusercontent.com/105280048/168482662-035abf87-fa71-48f6-9f0b-ad105ea99d14.PNG">
<img width="927" alt="bug1 3" src="https://user-images.githubusercontent.com/105280048/168482669-13ec0d07-fcbf-491b-8614-2d9ec6b68df3.PNG">

**Expected result**
"Статус оплати" in the field changed to "Часткова оплата"  in the admin account and in the user account for order №

**User story and test case links**
E.g.: "User story #3478
[Test case](https://jira.softserve.academy/browse/GC-2660)

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: minor"), Type ("Functional")

**Comment by Olenazenchenkoo** [comment]
This bug not fixed. We can see change status only in inside order, but on the page "Замовлення" in admin page it is not correct.
![image](https://user-images.githubusercontent.com/105363982/173100967-6c4d7463-7d57-449f-9575-9f8d91c8369a.png)
![image](https://user-images.githubusercontent.com/105363982/173101640-9c5da711-8c14-4001-b72f-908d14c68279.png)

**Comment by VadymMakitra** [comment]
@Olenazenchenkoo Basicling on bug description: this bug was related to the personal cabinet and it was fixed. Please create new ticket. I think this ticket could be closed.
