### ISSUE TITLE
[Order form. Step 2] The title of the 'Редагувати адресу' pop-up is a 'Нова адреса' instead of 'Змінити адресу'

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4150]
**Environment:** OS Windows 11 Pro, Microsoft Edge Version 101.0.1210.39
**Reproducible:** always.
**Build found:** 15.05.22

**Preconditions**
1. User is registered and logged in (https://ita-social-projects.github.io/GreenCityClient/#/)
2. User has the address in the Personal Cabinet

**Steps to reproduce**
1. Select 'УБС кур'єр' and click the 'Замовити кур'єра' button.
2. Select location ('Київ'). 
3. Fill correct data in the 'Деталі замовлення' tab.
4. Fill correct data in the 'Особисті дані' tab.
5. In the 'Адреса вивозу сміття' section chose an address
6. Click on the 'Pencil' icon - edit address

**Actual result**
The title of the pop-up is a 'Нова адреса'.
![_thumb_413144](https://user-images.githubusercontent.com/105448699/168483480-b0c42af2-6e58-4608-8a6c-c85e493ea051.png)

**Expected result**
The title of the pop-up is a "Змінити адресу" according to the mock-up.
![_thumb_413145](https://user-images.githubusercontent.com/105448699/168483491-421a8b55-c27e-42d8-92ca-eace12f4995d.png)

**User story and test case links**
E.g.: "User story #2533

**Comment by valeriia2301** [comment]
Now the title of the pop-up is 'Редагувати адресу'. The title should be 'Змінити адресу' according to the mock-up
![adress](https://user-images.githubusercontent.com/105349761/175368839-1d470463-d09a-43e6-a773-49d8c92cf634.png)
