### ISSUE TITLE
[Personal Cabinet - Order details] There isn't amount in the field “Сертифікат:” when we see details in expand view of paid order

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4151]
**Environment:** Chrome (latest)
**Reproducible:** always

**Preconditions**
1.The registered user is logged in (https://ita-social-projects.github.io/GreenCityClient/#/)
2. The user navigated to the tab "Замовлення" in the personal cabinet
3. the user have an paid order with three ordered services (Послуга), used certificate, bonuses in order. User  used next fields in order : Доставка з Еко магазину, Номер замовлення, Коментар до замовлення, Коментар.
4.User clicked on expanding icon of order

**Steps to reproduce**
1. Verify field “Сертифікат:” 

**Actual result**
In the field “Сертифікат:” there is empty amount
<img width="850" alt="bug3" src="https://user-images.githubusercontent.com/105280048/168484421-c25815d0-5549-489f-90ff-9c3a0c9ed04d.PNG">

**Expected result**
Total amount of certificates used to pay for the order. 

**User story and test case links**
E.g.: "User story #3478
[Test case](https://jira.softserve.academy/browse/GC-2188)

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("UI, "Functional")

**Comment by TaniaQC** [comment]
Done
