### ISSUE TITLE
[Personal Cabinet - Order details] there isn't field “Оплачено:” in details in expand view of paid order

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4152]
**Environment:** Chrome (latest)
**Reproducible:** always

**Preconditions**
1.The registered user is logged in (https://ita-social-projects.github.io/GreenCityClient/#/)
2. The user navigated to the tab "Замовлення" in the personal cabinet
3. the user have an paid order with three ordered services (Послуга), used certificate, bonuses in order. User used next fields in order : Доставка з Еко магазину, Номер замовлення, Коментар до замовлення, Коментар.
4.User clicked on expanding icon of order

**Steps to reproduce**
1. Verify field “Оплачено:”

**Actual result**
Field “Оплачено:” isn't here
<img width="646" alt="bug4" src="https://user-images.githubusercontent.com/105280048/168484639-829c44a0-1c18-4958-9a93-29aaa96013df.PNG">

**Expected result**
Total amount that client has paid.
[Attached screenshots or mock-ups if available.](https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17780%3A37380)

**User story and test case links**
E.g.: "User story #3478
[Test case](https://jira.softserve.academy/browse/GC-2188)

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("UI, "Functional")

**Comment by voronkooleksandr** [comment]
double

**Comment by TaniaQC** [comment]
Done
