### ISSUE TITLE
[Order Form. Step 1] In 'Кількість пакетів' input field the user can enter the characters '+', '-'

### ISSUE THREAD

**Issue by valeriia2301** [ita-social-projects/GreenCity#4153]
**Environment:** Windows 10 Pro 21H2 19044.1415, Chrome 100.0.4896.127 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 08.05.22

In 'Кількість пакетів' input field the user can enter the characters '+', '-' and when these symbols are in the middle of a number (e.g. 2-3), the user can enter more than 3 numeric characters (e.g. 2+36365296)

**Steps to reproduce**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in to Green City
3. Click on the 'UBS кур'єр' tab
4. Click on the 'Замовити кур'єра' button
5. Select "Київ" city and click on "Продовжити" button.
6. Enter in 'Кількість пакетів' input field  2+-3

**Actual result**
The user can enter the characters '+' and '-' in 'Кількість пакетів' input field

**Expected result**
The system should not allow the user to enter the characters '+' and '-' in 'Кількість пакетів' input field

**User story and test case links**
User story #2379 
Test case https://jira.softserve.academy/browse/GC-1968

![Screenshot_1](https://user-images.githubusercontent.com/105349761/168484980-6ef60a63-c49c-4a7d-8dde-c96259293006.png)
![Screenshot_2](https://user-images.githubusercontent.com/105349761/168484984-36cb0331-9061-4bc4-8e2a-00df0d3c0c56.png)

**Comment by Olenazenchenkoo** [comment]
Defect also reproduces in desktop version.
