### ISSUE TITLE
[Order Form. Step 1] UI inconsistencies between mockups and website

### ISSUE THREAD

**Issue by valeriia2301** [ita-social-projects/GreenCity#4154]
**Environment:** Windows 10 Pro 21H2 19044.1415, Chrome 100.0.4896.127 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 08.05.22

UI inconsistencies between mockups and website
Link to mockups: https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=15777%3A37659

**Steps to reproduce**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in to Green City
3. Click on the 'UBS кур'єр' tab
4. Click on the 'Замовити кур'єра' button
5. Select "Київ" city and click on "Продовжити" button.

**Actual result**

1. Certificate section includes 'Чи бажаєте Ви скористатись сертифікатом?' header, input field under header and "Активувати" button near input field.
2. 'Номер сертифiката' isn`t colored green (#AFD85A) when the cursor focuses it.
3.  Tab`s counters have size of number 11x22 px, size of round field 24x24 px (this problem is reproducible on the all tabs - 'Деталі замовлення', 'Особисті дані', 'Підтвердження')
4.  'Кількість пакетів' input field has spinner on the right side, placeholder '0' is left aligned.
5. 'Еко-магазин' section includes input field with placeholder and  'Номер замовлення' label and **radiobuttons above these elements**.

**Expected result**

1. Certificate section includes **'Якщо бажаєте скористатися сертифікатом, введіть номер сертифіката' header**, input field under header **with "Номер сертифiката" label** and "Активувати" button near input field.
2. 'Номер сертифiката' **input field should be colored green (#AFD85A)** when the cursor focuses it.
3. Tab`s counters have **size of number 12x28 px, size of round field 30x30 px.**
4. 'Кількість пакетів' **input field has '+' and '-' buttons, placeholder '0' is central aligned**.
5. 'Еко-магазин' section includes input field with placeholder and  'Номер замовлення' label.

**User story and test case links**
Test case https://jira.softserve.academy/browse/GC-1935

1.
![actual 1](https://user-images.githubusercontent.com/105349761/168485640-f4a31ec8-1211-44a0-9800-71c159345bc8.png)
![expected 1](https://user-images.githubusercontent.com/105349761/168485642-f86eec96-8726-4548-bee2-dd72ad1c0b49.png)

2.
![actual 2](https://user-images.githubusercontent.com/105349761/168485678-4a0164dd-1b10-45bf-b583-b6d2cee577c0.png)
![expected 2](https://user-images.githubusercontent.com/105349761/168485685-3f0b815c-2445-48aa-a170-ebbc956c3ef9.png)

3.
![actual 3 1](https://user-images.githubusercontent.com/105349761/168485729-c33eb221-3d9e-4f47-bbcc-8ded60fa442f.png)
![expected 3 1](https://user-images.githubusercontent.com/105349761/168485733-a0dd7fdd-c7de-4770-8f49-17735a55270e.png)
![actual 3 2](https://user-images.githubusercontent.com/105349761/168485740-47ef7763-f0aa-4269-aa34-2b23441057b1.png)
![expected 3 2](https://user-images.githubusercontent.com/105349761/168485742-5cc6f032-990d-4351-a044-e11979fdafb0.png)

4.
![actual 4](https://user-images.githubusercontent.com/105349761/168485749-eff29706-e280-49b6-a7c1-6a1d2f138679.png)
![expected 4](https://user-images.githubusercontent.com/105349761/168485751-4660e7c9-66a9-48f8-897d-d3ccbe97fcfa.png)

5.
![actual 5](https://user-images.githubusercontent.com/105349761/168485761-f4ec0e44-56b0-419d-bacd-a49125414bbc.png)
![expected 5](https://user-images.githubusercontent.com/105349761/168485764-8effe6b0-2638-4ade-8670-0c436161eae9.png)

**Comment by Olenazenchenkoo** [comment]
Defect also reproduces in desktop version.
