### ISSUE TITLE
[Order. Step 2] In the field "Адреса вивозу сміття" radio button and "Додати адресу" button do not meet the requirements.

### ISSUE THREAD

**Issue by IrynaVdovyniuk** [ita-social-projects/GreenCity#4155]
**Environment:** Windows 10 Pro, Google Chrome.
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs

2. log in as a user.

3. Click on the "Замовити кур'єра" button.

4. Choose the location of the "Київ".

5. Click on the "Продовжити" button.

6. On the page "Деталі замовлення" fill in all required fields.

7. Click on the "Далі" button.

8. Choose the field "Адреса вивозу сміття".

**Actual result**
In the field "Адреса вивозу сміття" radio button and "Додати адресу" button do not meet the requirements.

**Expected result**
In the field "Адреса вивозу сміття" radio button and "Додати адресу" button meet the requirements.

**User story and test case links**
E.g.: "User story #3596

**Comment by mikhaylovamarina** [comment]
Actual result: "Додати адресу"
Expected result: "Додати іншу адресу"

**Comment by voronkooleksandr** [comment]
Oo! Thanks!)
