### ISSUE TITLE
[Personal Cabinet - Order details] The field "Адреса вивезення замовлених послуг" is on wrong place in form

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4157]
**Environment:** Chrome (latest)
**Reproducible:** always

**Preconditions**
1.The registered user is logged in (https://ita-social-projects.github.io/GreenCityClient/#/)
2. The user navigated to the tab "Замовлення" in the personal cabinet
3. the user have an paid order with three ordered services (Послуга), used certificate, bonuses in order. User used next fields in order : Доставка з Еко магазину, Номер замовлення, Коментар до замовлення, Коментар.
4.User clicked on expanding icon of order

**Steps to reproduce**
1. Verify  "Адреса вивезення замовлених послуг" 

**Actual result**
The field is in the left side of the form end
<img width="915" alt="bug4" src="https://user-images.githubusercontent.com/105280048/168531691-6bc6357e-6a58-4c8b-b98a-b61e4c7e3474.PNG">

**Expected result**
"Адреса вивезення замовлених послуг" is on the right side "Доставка"
[Attached screenshots or mock-ups if available.](https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=17780%3A37380)

**User story and test case links**
E.g.: "User story #3478
[Test case](https://jira.softserve.academy/browse/GC-2189)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: low"), Type ("UI, "Functional")

**Comment by krayevska** [comment]
duplicate https://github.com/ita-social-projects/GreenCity/issues/4122
