### ISSUE TITLE
[Personal Cabinet - Order details] When user fills in number block or entrance number in "Адреса вивезення замовлених послуг", the system displays "unreceived"

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4159]
**Environment:** Chrome (latest)
**Reproducible:** always

**Preconditions**
1.The registered user is logged in (https://ita-social-projects.github.io/GreenCityClient/#/)
2. The user navigated to the tab "Замовлення" in the personal cabinet
3. the user have an paid order with three ordered services (Послуга), used certificate, bonuses in order. User used next fields in order : Доставка з Еко магазину, Номер замовлення, Коментар до замовлення, Коментар.
4.User clicked on expanding icon of order

**Steps to reproduce**
1. Verify "Адреса вивезення замовлених послуг" when all details filled in

**Actual result**
The system displays "unreceived" in places of number block and entrance number
<img width="502" alt="bug 5" src="https://user-images.githubusercontent.com/105280048/168534276-f076c022-d745-419b-a08b-ba747655cd62.PNG">

**Expected result**
Address of waste pickup : City, Street, District, Region
E.g. Личаківська 5, корп. 3, п.2

**User story and test case links**
E.g.: "User story #3478
[Test case](https://jira.softserve.academy/browse/GC-2600)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:low"), Type ("UI, "Functional")

**Comment by TaniaQC** [comment]
Done
