### ISSUE TITLE
[Admin.Orders] The invalid export time can be selected 

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4174]
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 17.05.2022

Preconditions
Go to https://ita-social-projects.github.io/GreenCityClient/#
Log in as admin

Steps to reproduce
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Change the 'Order status' in some order to 'Узгодження'
4.In the 'Export date' choose current day
5.In the 'Export time' choose invalid time
6.Fill in all required fields
7.Click the 'Save' button

**Actual result**
The invalid export time can be selected 
![2022-05-17_15-30-16](https://user-images.githubusercontent.com/102300943/168812410-5cdaa5ff-6d21-4a00-b740-59e4a04533ca.jpg)

**Expected result**
Only the future time can be selected

**Comment by BelakorGit** [comment]
When choosing an "Adjustment" order status and setting current date, Admin is able to choose invalid time ,as the field "From" activates after Admin chose time for field "To".
<img width="1280" alt="Admin_time_invalid" src="https://user-images.githubusercontent.com/108956780/216137940-0b29b102-a796-4e68-b6c7-40f37d539749.png">

**Comment by SokhaTaras** [comment]
@Horokhov Hi, I've thought that this bug was caused due to your time format(you have USA format).Thus, when i try to reproduce it having setted USA format beforehands, format of time does not change on our pop-up.So, you have to add steps to reproduce
![image](https://user-images.githubusercontent.com/86615598/216954655-b176a3be-1484-4076-abfa-f4989b0bbfc2.png)

**Comment by BelakorGit** [comment]
Preconditions
1.Go to https://ita-social-projects.github.io/GreenCityClient/#
2.Log in as admin
3.User should have Kyiv time zone on PC, 24 hour clock format.

Steps to reproduce
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Change the 'Order status' in some order to 'Adjustment'
4.In the 'Export date' choose "To" past time.
5.In the 'Export time' "From" choose any time.
6.Fill in all required fields
7.Click the 'Save' button

https://user-images.githubusercontent.com/108956780/217029243-4f4226fc-e6fd-4e5a-b0cb-200efbf80cc3.mp4

**Comment by Tadei-Mykola** [comment]
cannot reproduce

**Comment by DanaIuich** [comment]
Bug is fixed
