### ISSUE TITLE
[Admin.Orders] The 'Export details' and 'Responsible persons' information is required even after filling it in

### ISSUE THREAD

**Issue by OliaFed** [ita-social-projects/GreenCity#4175]
**Environment:** Windows 10, Google Chrome 101
**Reproducible:** always
**Build found:** 17.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#
Log in as admin

**Steps to reproduce**
1.Click the 'UBS-admin' button in pop-up window
2.Click the 'Orders' button
3.Change the 'Order status' in some order to 'Узгодження'
4.Fill in all required fields
5.Click the 'Save' button
6.Open the order and make sure that all information is saved
7.Go to the 'Orders' table
8.Change the 'Order status' in the same order to 'Підтверджено'

**Actual result**
The 'Export details' and 'Responsible persons' information is not saved

https://user-images.githubusercontent.com/102300943/168814157-d6348682-5d59-40c1-a206-e99cb1445ff9.mp4

**Expected result**
The 'Export details' and 'Responsible persons' information is saved

**Comment by marianaharnyk** [comment]
This bug cannot be reproduced
https://www.loom.com/share/a28c33c19cbc4672b008a8a762fd1e04
