### ISSUE TITLE
[UBS Courier - Start Page] The text in the "Увійти" button is not aligned to the center

### ISSUE THREAD

**Issue by yarkokuzyk** [ita-social-projects/GreenCity#4176]
**Environment:**  Windows 10, Opera
**Reproducible:** Always
**Build found:** last commit (77ff7c4639beea65ce4c0f2d71af58c79855c4de)

**Preconditions**
1. Open the UBS Courier start page - https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Steps to reproduce**
1. Switch to the Ukrainian language
2. Check the alignment of the text in the "Увійти" button

**Actual result**
The text in the button is aligned to the left

**Expected result**
The text in the button is aligned to the center

**User story and test case links**
User Story #2924

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: minor"), Type ("UI").
![image](https://user-images.githubusercontent.com/104302356/168877075-002f265e-7aec-48ab-a86d-0f2ac8fada65.png)

**Comment by Horokh** [comment]
Text alignment in the "Login" button should be changed to "center"

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/181722946-4355a09a-50b9-4334-988b-e81dbdb064ab.png)
