### ISSUE TITLE
[Order step 1] The "Ви не можете ввести більше 255 символів." validation error message is shown below the 'Коментар' field after adding the text with line break special character

### ISSUE THREAD

**Issue by olabell** [ita-social-projects/GreenCity#4187]
Environment: Windows 11, Opera 85.0.4341.75
Reproducible: always
Build found: 18.05.2022

**Preconditions**
1. Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/
2. Click on 'Увійти' button.
3. Log in as a registered user .

**Steps to reproduce:**
1. Click on the 'UBS кур'єр" tab.
2. Click on the 'Замовити кур'єра' button, choose location 'Київ' and click 'Продовжити'
3. Enter the text with the line break special character (e.g. гофрокартон
алюмінієві бляшанки) into the 'Коментар' input field
5. Pay attention to the 'Ви не можете ввести більше 255 символів.' validation error massage.

**Actualt result:**
The "Ви не можете ввести більше 255 символів." validation error message is shown below the 'Коментар' field after adding the the text with line break special character.
![image](https://user-images.githubusercontent.com/39055716/169119347-e9531d07-1ca3-4f89-8fa0-052af594e50d.png)

**Expected result:**
The line break special character is available for entering by user into the 'Коментар' field.

User story and test case links
E.g.: "User story #2379 
[Test case](https://jira.softserve.academy/browse/GC-1842, 
https://jira.softserve.academy/browse/GC-2038"

**Comment by OlhaHubarieva** [comment]
The "Ви не можете ввести більше 255 символів." validation error message is shown below the 'Коментар' field after adding the the text with line break special character.
