### ISSUE TITLE
[UBS-Admin. Pricing page] Cross button is present in the Region ('Область') dropdown

### ISSUE THREAD

**Issue by IrynaKhyliuk** [ita-social-projects/GreenCity#4188]
**Environment:** Windows 10 Pro, Chrome 101
**Reproducible:** always.
**Build found:** May 18, 2022

**Preconditions**
User should be logged in as Admin.

**Steps to reproduce**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs
2. Click on 'Region' ('Область') dropdown and select any entry from the dropdown window (e.g. Київська область).
3. Click on the dropdown arrow.

**Actual result**
A cross button with dropdown arrow is present in the 'Region' ('Область') dropdown. There are two entries available in the dropdown list: the selected one (e.g. 'Київська область') and 'Усі' option. 
![bug1](https://user-images.githubusercontent.com/104845656/169136781-24e22173-19c1-45b8-b9ac-0dba6c689d4e.PNG)

**Expected result**
Only a dropdown arrow is present in the 'Region' ('Область') dropdown. All available entries of the 'Region' dropdown are present in the dropdown list (just like when you click on the field initially: 
![bugbug](https://user-images.githubusercontent.com/104845656/169136992-d56f93f4-a2b1-4259-90eb-db8ea239249f.png)

**User story and test case links**
User story #3835 
[Test case](https://jira.softserve.academy/browse/100)

**Comment by melnychenkoas** [comment]
The actual result is correct. We need to change story and mock-up according how it works now.
