### ISSUE TITLE
[UBS-Admin. Pricing page] Dropdown lists of the menu on the Pricing page ('Tariffs') is not localized for EN

### ISSUE THREAD

**Issue by IrynaKhyliuk** [ita-social-projects/GreenCity#4189]
**Environment:** Windows 10 Pro, Chrome 101
**Reproducible:** always
**Build found:** May 18, 2022

**Preconditions**
User is logged in as Admin. EN locale is set for the page. 

**Steps to reproduce**
1. Go to UBS Admin Tariffs page: https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs
2. Click on the 'Region' dropdown. Pay attention to the items in the dropdown list.
3. Select any entry in the 'Region' dropdown menu.
4. Click on the 'City' dropdown. Pay attention to the items in the dropdown list.
5. Click on the 'Courier' dropdown. Pay attention to the items in the dropdown list.
6. Click on the 'Receiving station' dropdown. Pay attention to the items in the dropdown list. 
7. Click on the 'State' dropdown. Pay attention to the items in the dropdown list. 

**Actual result**
Items in the dropdown lists are not localized according to EN locale.

**Expected result**
Items in the dropdown lists are localized according to EN locale. 

**User story and test case links**
User story #3835 
[Test case](https://jira.softserve.academy/browse/100)"

**Comment by melnychenkoas** [comment]
We don't localized for EN admin part of project
