### ISSUE TITLE
[UBS-User. Order tab] The column names aren`t aligned left in the orders table on the 'Поточні замовлення' and 'Історія замовлень' tabs

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4193]
**Environment:** OS Windows 11 Pro, Microsoft Edge Version 101.0.1210.39
**Reproducible:** always.
**Build found:**19.05.22

**Preconditions**

1. The User has some orders with 'Виконано' and/or 'Скасовано' order statuses.
2. Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3. Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**
1. Click 'Замовлення' tab.
2. Click 'Поточні замовлення' tab.
3. Take a look at the column names in the orders table.
4. Click 'Історії замовлення' tab.
5. Take a look at the column names in the orders table.

**Actual result**
The column names aren`t aligned left
![history orders](https://user-images.githubusercontent.com/105448699/169385573-e70b3c70-ebc9-4ad6-8219-e0b039d7e0b8.png)

**Expected result**
The column names are aligned left
![image](https://user-images.githubusercontent.com/105448699/169385778-0d24a0b9-5aab-4b20-9af5-522921a358db.png)

**User story and test case links**
E.g.: "User story #3477

**Comment by krayevska** [comment]
issue has been fix before
