### ISSUE TITLE
[Personal cabinet] Only 20 last orders are shown in 'Ваші замовлення' tub

### ISSUE THREAD

**Issue by OlhaHubarieva** [ita-social-projects/GreenCity#4195]
**Environment:** OS Windows 10 PRO. Firefox 100.0 (64 bit).
**Reproducible:** always.
**Build found:**19.05.2022

**Preconditions**

1. The User has more than 20 orders with different order statuses.
2.  Log in to GreenCity as a User https://ita-social-projects.github.io/GreenCityClient/#/
3.  Go to the user's personal cabinet (UBS-user).

**Steps to reproduce**

 1. Click 'Замовлення' tab.
 2. Take a look at the orders table.

**Actual result**
Only 20 last orders are shown in 'Ваші замовлення' tab.

**Expected result**
All user orders are shown in 'Ваші замовлення' tab.

**User story and test case links**
User story #3477

**Comment by Mukola1983** [comment]
Dublicated #4089
