### ISSUE TITLE
[Order form. Step 1] System doesn’t allow user with bonuses to choose ‘Ні’ radio-button in the Bonus section and go further to 'Далі' button using tab navigation

### ISSUE THREAD

**Issue by OlhaHubarieva** [ita-social-projects/GreenCity#4197]
**Environment:** OS Windows 10 PRO. Firefox 100.0 (64 bit).
Desktop version.
**Reproducible:** always.
**Build found:** 20.05.2022

**Preconditions**
The user has bonuses on his account.

**Steps to reproduce**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs

2. Log in as a user.

3. Click on 'Замовити Кур'єра' button.

4. Select 'Київ' city and click on 'Продовжити' button.

5. Select services so that the amount of the order is equal or greater than the 500.00 UAH.

6. Choose ‘Ні’ radio-button in the Bonus section and go further to 'Далі' button using tub navigation .

**Actual result**
System doesn’t allow to choose ‘Ні’ radio-button in the Bonus section and go further to 'Далі' button using tub navigation.

**Expected result**
User can choose ‘Ні’ radio-button in the Bonus section and go further to 'Далі' button using tab navigation.

**User story and test case links**
"User story #2379 
[Test case] (https://jira.softserve.academy/browse/GC-1935)

**Comment by VadymMakitra** [comment]
Not reproducible.
