### ISSUE TITLE
[Admin. Orders] The alignment of filtering pop-up window is wrong, text "Фільтри" instead of "Фільтрувати" and "Скасувати все" instead of "Скасувати"

### ISSUE THREAD

**Issue by Olya-Kashchin** [ita-social-projects/GreenCity#4212]
**Environment:** macOS Monterey Version 12.3.1, Chrome 101.0.4951.54
**Reproducible:** always
**Build found:** 27.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
Sign in as admin

**Steps to reproduce**
1. Click the 'UBS-admin' button in pop-up window
2. Click the button "Замовлення"
3. Click on the button "Фільтри"
4.  Set any filtering condition

**Actual result**
See attachment and pay attention on the alignment and text "Фільтри", label on the button "Скасувати все" and order of the buttons "Застосувати" and "Скасувати все"
<img width="377" alt="Screenshot 2022-05-27 at 15 38 44" src="https://user-images.githubusercontent.com/103331829/170702023-b39530a7-7e7b-4049-b276-29124b575ab9.png">

**Expected result**
See mock-up attached:
<img width="190" alt="Screenshot 2022-05-27 at 15 51 07" src="https://user-images.githubusercontent.com/103331829/170702814-05d56ea0-446d-4304-ba3c-e118fc7028ae.png">

**User story and test case links**
Mock-up: https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=18576%3A44599

**Comment by TaniaQC** [comment]
The label of the button 'Фільтрувати' should be 'Фільтри';
The label of
![image](https://user-images.githubusercontent.com/105351490/180977052-bf7b82a4-a3f3-4935-87a1-500ab7480dd1.png)
 the button 'Скасувати все' should be 'Скасувати'

**Comment by lubomir1509** [comment]
1. Link in Precondition https://ita-social-projects.github.io/GreenCityClient/#/ubs not relevant.
2. The buttons  "Застосувати" and "Скасувати" are not the right size for the pop-up  window

**Comment by atsa21** [comment]
Not reproduce
