### ISSUE TITLE
[Personal Cabinet] Orders tab - payment step 2. “Упс, щось пішло не так…” page doesn't displayed order number

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4226]
**Environment:** FireFox (lstest)
**Reproducible:** always

**Steps to reproduce**
1. The user is logged in as a client and navigated to a personal cabinet, tab “Замовлення”.
2. User made unsuccessful paid for the order and “Упс, щось пішло не так…” page is opened
3. Check that the order number in massage corresponds to the number in the customer's cabinet

**Actual result**
Order number isn't displayed in massage
![image](https://user-images.githubusercontent.com/105280048/170480011-b9f67665-cef0-4008-a398-9f14ff0e6252.png)

**Expected result**
Order number is displayed on the page and  corresponds to the number in the customer's cabinet
![image](https://user-images.githubusercontent.com/105280048/170480056-6d57ce67-2460-4f2c-b398-d4ce76d3190d.png)

**User story and test case links**
E.g.: "User story #3491 
[Test case](https://jira.softserve.academy/browse/GC-2247)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI, "Functional")

**Comment by YelyzavetaSheptytska** [comment]
Page doesn't display order number. The order number is 1694 (it has to be present on the current page). 
<img width="1127" alt="Screen Shot 2022-12-10 at 4 32 10 PM" src="https://user-images.githubusercontent.com/112197311/206862937-0ce6deb4-d539-4fc0-bc7f-45722f1bf8d0.png">
