### ISSUE TITLE
[Admin. Orders] Missing of the option "Без менеджера/логіста/штурмана/водія" in the relevant filters

### ISSUE THREAD

**Issue by Olya-Kashchin** [ita-social-projects/GreenCity#4239]
**Environment:** macOS Monterey Version 12.3.1, Chrome 101.0.4951.54
**Reproducible:** always
**Build found:** 27.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
Sign in as admin

**Steps to reproduce**
1. Click the 'UBS-admin' button in pop-up window
2. Click the button "Замовлення"
3. Click on the button "Фільтри"
4. Expand the next filters: 
- Менеджер обдзвону 
- Логіст
- Водій
- Штурман

**Actual result**
There is no option "Без менеджера/логіста/штурмана/водія" in the appropriate filters available.
<img width="385" alt="Screenshot 2022-05-27 at 16 21 05" src="https://user-images.githubusercontent.com/103331829/170707452-f0c2d66e-1202-4cdb-b237-cece42b58b5b.png">

**Expected result**
The option "Без менеджера/логіста/штурмана/водія" in the appropriate filters should be present.
<img width="239" alt="Screenshot 2022-05-27 at 16 23 35" src="https://user-images.githubusercontent.com/103331829/170707953-7cf893fa-1af5-48bf-9b03-eddda1e2f7f2.png">

**User story and test case links**
User story #3300 
Mock-up: https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=18582%3A52286

**Comment by zaitsev-oleksii** [comment]
To implement on back-end: 
Endpoint: https://greencity-ubs.testgreencity.ga/ubs/management/bigOrderTable
Add an option to match all the records without **caller/driver/logistician/navigator** to query params: 
`responsibleCallerId`, `responsibleDriverId`, `responsibleLogicManId`, `responsibleNavigatorId`.
I suggest using `-1`, e.g.  GET on https://greencity-ubs.testgreencity.ga/ubs/management/bigOrderTable?responsibleDriverId=-1 should return records with no **driver** assigned.
