### ISSUE TITLE
[Home page] "Start forming a habbit!" button doesn't work after user log out	

### ISSUE THREAD

**Issue by TomekPaluch** [ita-social-projects/GreenCity#4252]
**Environment:** OS, browser, it's version, device (for mobile devices).
**Reproducible:** always, rarely, sometimes etc.

**Step to reproduce:**

1). Go to [GreenCity (ita-social-projects.github.io)](https://ita-social-projects.github.io/GreenCityClient/#/)
2). Log in as a user
3). Log out
4). Click on every "Start forming a habit!" Button

**Actual result:**
Logged in User is  on "Home" Page after clicking on every button "Start forming a habit!"

**Expected result:**
Logged in User should be navigated to "Sign In" pop up

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: major"), Type (""Functional")

**Comment by voronkooleksandr** [comment]
double
