### ISSUE TITLE
[Personal Cabinet] Orders tab. Confirmed amount couldn't be increased by admin than user order was made and saved for payment status "Частково оплачено"

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4258]
**Environment:** Firefox, Chrome (latest)
**Reproducible:** always

**Steps to reproduce**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. Open The 'Замовлення' in the personal cabinet.
3. Create new order and pay it
4. Go in UBS-admin and increase Confirmed amount for this order
5. Click on Save button

**Actual result**
Erron message is displayed "User with current id does not exist."
![image](https://user-images.githubusercontent.com/105280048/171423764-631211c8-7be8-4681-ad6d-7fcf50536839.png)

**Expected result**
Changes saved and in UBS-user the payment status for this order is "Частково оплачено"

**User story and test case links**
E.g.: "User story #3491

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity:Major"), Type ("Functional")

**Comment by NataliaHlazova** [comment]
https://user-images.githubusercontent.com/87066582/175260172-5cddb6ca-3067-47d5-9a5d-add6e7a1de82.mp4
