### ISSUE TITLE
Change password in personal cabinet

### ISSUE THREAD

**Issue by Yuliia-Fliorko** [ita-social-projects/GreenCity#4276]
As a user, I want to change my password in my UBS-client profile page so that** I can have a new password for security reasons.

**Mock-ups:**  
1.https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=20703%3A62598
2.

**Pre-conditions:**
1. User is registered
2. User has clicked on **_“Дані користувача/User Data”_** tab.
3. User has clicked on **_“Змінити пароль/Change password”_** button.

**Acceptance criteria:**
1. **If** a user clicks on **_old password_** text field, **and** leaves it empty, **then** error message appears:
      _En:_ “Old password is required.”.
      _Ua:_ “Будь ласка введіть свій попередній пароль.”.

2. **If** a user clicks on **_new password_** text field, **and** leaves it empty, **then** error message appears:
      _En:_ “New password is required.”.
      _Ua:_ “Будь ласка введіть свій новий пароль.”.

3. **If** a user clicks on **_confirm new password_** text field, **and** leaves it empty, **then** error message appears:
      _En:_ “Please retype your new password.”.
      _Ua:_ “Будь ласка введіть свій новий пароль ще раз .”.

 4. **If** the user entered less than 8 characters in **_confirm password_** text field, **then** an informational message appears:
      _En:_ “Password must be at least 8 characters long without spaces.”.
      _Ua:_ “Пароль повинен містити принаймні 8 символів без пробілів.”.

5. **If** the user entered more than 20 characters in **_confirm password_** text field, **then** an informational message appears:
      _En:_ “Password must be less than 20 characters long without spaces.”.
      _Ua:_ “Пароль повинен бути меншим ніж 20 символів без пробілів.”.

6. **If** the user entered a password that does **not match a criteria** in **_new password_** or/and **_confirm new password_**, **then** error message appears:
      _En:_ “Password should be at least one character of Uppercase letter (A-Z), Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.). ”.
      _Ua:_ “Пароль повинен містити хоча б один символ латинського алфавіту верхнього (A-Z) та нижнього регістру (a-z), число (0-9) та спеціальний символ (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.).”.

7. ***If* **_new password_** and **_confirm new password_** does not match, **then** error message appears:
      _En:_ “Passwords do not match.”.
      _Ua:_ “Паролі не співпадають.”.

**Scenarios:**
1. **Given** user registered with _Google_.
    **When** user has clicked on**Change password** button.
    **Then** the pop-up window is showed with 2 fields: **New password** and **Confirm new password** (The second mock-up is used.).

2. **Given** user registered with _credentials_.
    **When** user has clicked on **Change password** button.
    **Then** the pop-up window is showed with 3 fields: **Old password**,**New password** , and **Confirm new password** (The first mock-up is used.).

3. **Given** user registered with credentials .
    **When ** user has entered wrong **old password**,
    **And** clicked on **Change password ** button.
    **Then** all fields are cleared,
    **And** error message under **old password** field:
      _En:_ “Wrong password.”.
      _Ua:_ “Пароль не правильний.”

4.  **Given** user registered with _credentials_.
    **When ** entered in **old password**, **new password** and **confirm new password**  meet requirements.
    **Then** the**Change password ** button is activated.

5. **Given** registered user,
    **When ** user has clicked on **Change password ** button 3 times in a row,
    **And **  error message _“Wrong password.”_ appeared all 3 times.
    **Then**  error message:
      _En:_ “Wrong password.You have made too many attempts, please try again in 30 minutes”.
      _Ua:_ “Пароль не правильний. Ви зробили занадто багато спроб, спробуйте ще раз через 30 хв”

For password requirements: #4277 section 4

**Comment by OlhaKyrylenko** [comment]
1. If a user clicks on old password text field, and leaves it empty, there is no error message appears
2. If a user clicks on new password text field, and leaves it empty, there is no error message appears
3. If a user clicks on confirm new password text field, and leaves it empty, there is no error message appears
4. If the user entered less than 8 characters in confirm password text field, there is no error message appears
5. If the user entered more than 20 characters in confirm password text field, there is no error message appears
6. If the user entered a password that does not match a criteria in new password or/and confirm new password  there is no error message appears
