### ISSUE TITLE
[USB-User cabinet. Bonuses] The message about absence of bonuses in the personal cabinet is not correct 

### ISSUE THREAD

**Issue by anastasiialutsiv** [ita-social-projects/GreenCity#4279]
**Environment:** Mac OS Monterey 12.4;  Safari 15.5 
**Reproducible:** always
**Build found:**  08/06/2022

**Preconditions**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The UBS-user page is opened

**Steps to reproduce**
1. Click on the button 'Рахунок' on the left menu panel
2. Open a window about bonuses information for user
3. Look at the message text

**Actual result**
The message text is "Вам ще не нараховано бонусів." 

**Expected result**
The message text should be “У вас ще немає бонусів”

**User story and test case links**
E.g.: "User story #3670 
[Test case](https://jira.softserve.academy/browse/GC-2719)"

**Labels to be added**
"Bug"

**Comment by NataliaVirt** [comment]
Fixed
![image](https://user-images.githubusercontent.com/112310945/193573379-40627231-a444-497a-b97d-c255421236e5.png)
