### ISSUE TITLE
[USB-User. Order page] Incorrect error message when user enter invalid certificate ('Споробуйте' instead of 'Спробуйте')

### ISSUE THREAD

**Issue by valeriia2301** [ita-social-projects/GreenCity#4281]
**Environment:** Windows 10 Pro 21H2 19044.1415, Chrome 102.0.5005.62 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 08.06.2022

**Preconditions**

1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/) (timka690ISTQB).
2. Go to 'UBS-user' - 'Замовлення' - 'Поточні замовлення'
4. Client has order with the amount in field 'Сума до оплати' is greater than null and payment status is 'Частково оплачено';

**Steps to reproduce**
1. Click on the "Оплатити" button next to order with payment status "Частково оплачено"
2. Enter invalid certificate, which does not match with the database and click 'Активувати' button

**Actual result**
Message appears "Сертифiкат не прийнято, споробуйте ще раз"
![споробуйте](https://user-images.githubusercontent.com/105349761/172707064-a14c4c9f-bb74-4090-8ec0-078fa8eea6fe.png)

**Expected result**
Message appears "Сертифiкат не прийнято, спробуйте ще раз"

**User story and test case links**
"User story #3489 
Test case https://jira.softserve.academy/browse/GC-2439

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/181724178-737ff62b-d5fe-48b6-8586-1929c37227f7.png)
