### ISSUE TITLE
[USB-User. Order page] Incorrect error message when user enter expired certificate

### ISSUE THREAD

**Issue by valeriia2301** [ita-social-projects/GreenCity#4283]
**Environment:** Windows 10 Pro 21H2 19044.1415, Chrome 102.0.5005.62 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 08.06.2022

**Preconditions**

1. Logged in to GreenCity as a User [https://www.testgreencity.ga/GreenCityClient/#](https://www.testgreencity.ga/GreenCityClient/) (timka690ISTQB).
2. Go to 'UBS-user' - 'Замовлення' - 'Поточні замовлення'
3. Client has order with the amount in field 'Сума до оплати' is greater than null and payment status is 'Частково оплачено';
4. The user has expired certificate 

**Steps to reproduce**
1. Click on the "Оплатити" button next to order with payment status "Частково оплачено"
2. Enter expired certificate (e.g. 2222-2222) and click 'Активувати' button

**Actual result**
Message appears "Сертифiкат не прийнято, спoробуйте ще раз"
![expired](https://user-images.githubusercontent.com/105349761/172708939-4c795866-ad0f-4cad-b912-7d7f09aa76db.png)

**Expected result**
Message appears "Сертифікат не є дійсним. Строк дії сертифікату - до YY.YY.YYYY"

**User story and test case links**
User story #3489 
[Test case](https://jira.softserve.academy/browse/GC-2439)"

**Comment by AntonHusiev** [comment]
**25.07.2022**

The date format is "YY-YY-YYYY" instead of "YY.YY.YYYY" in the error message.
