### ISSUE TITLE
[USB-User. Order page] Incorrect error message when user enter certificate with a discount that is greater than the order amount

### ISSUE THREAD

**Issue by valeriia2301** [ita-social-projects/GreenCity#4285]
**Environment:** Windows 10 Pro 21H2 19044.1415, Chrome 102.0.5005.62 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 08.06.2022

**Preconditions**

1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/) (timka690ISTQB).
2. Go to 'UBS-user' - 'Замовлення' - 'Поточні замовлення'
3. Client has order with the amount in field 'Сума до оплати' is greater than null and payment status is 'Частково оплачено';
4. The user has active certificate with a discount that is greater than the order amount

**Steps to reproduce**
1. Click on the "Оплатити" button next to order with payment status "Частково оплачено"
2. Enter active certificate with a discount that is greater than the order amount (e.g. 6666-6666) and click 'Активувати' button

**Actual result**
Message appears "Сертифiкат на cуму XXX грн активовано. Строк дії сертифікату - до YYYY-YY-YY"
![greater](https://user-images.githubusercontent.com/105349761/172713561-1899ebe5-9453-4e04-8d71-9bc774004cab.png)

**Expected result**
Message appears "Сертифікат на суму XXX.XX грн активовано, що перевищує суму Вашого замовлення. Залишок у розмірі ZZZ.ZZ грн не повертається. Строк дії сертифікату - до YY.YY.YYYY"

**User story and test case links**
User story #3489
[Test case](https://jira.softserve.academy/browse/GC-2440)

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/181228826-abe09595-06e7-4250-9d00-3581439c5214.png)
