### ISSUE TITLE
[USB-User. Order page] 'Додати сертифікат' button is not displayed when user deletes second certificate

### ISSUE THREAD

**Issue by valeriia2301** [ita-social-projects/GreenCity#4286]
**Environment:** Windows 10 Pro 21H2 19044.1415, Chrome 102.0.5005.62 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 08.06.2022

**Preconditions**

1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/) (timka690ISTQB).
2. Go to 'UBS-user' - 'Замовлення' - 'Поточні замовлення'
3. Client has order with the amount in field 'Сума до оплати' is greater than null and payment status is 'Частково оплачено';
4. The user has 2 certificates (at least 1 is active)

**Steps to reproduce**
1. Click on the "Оплатити" button next to order with payment status "Частково оплачено"
2. Enter active certificate (e.g. 1111-1111), and click 'Активувати' button 
3. Click 'Додати сертифікат' button
4. Enter second certificate (e.g. 5555-5555) and click 'Активувати' button
5. Click "Відмінити" button only next to second certificate

**Actual result**
'Додати сертифікат' button is not displayed. The user is unable to add 1 more certificate
![add](https://user-images.githubusercontent.com/105349761/172715750-fadaaf2f-7df0-44cc-bb28-5453a0f57edf.png)

**Expected result**
'Додати сертифікат' button is displayed. The user is able to add 1 more certificate

**User story and test case links**
User story #3489
[Test case](https://jira.softserve.academy/browse/GC-2440)

**Comment by voronkooleksandr** [comment]
Everything works! You can add a lot certificates
![image](https://user-images.githubusercontent.com/61209463/173051282-43104007-2ddf-449f-bbdd-ade7de22189b.png)

**Comment by valeriia2301** [comment]
https://user-images.githubusercontent.com/105349761/173119980-ebc3f24f-1dd8-4512-96e2-36a7c725ad0a.mp4

Yes, adding certificates works, the button is not displayed after deleting the certificate. If I made a mistake in the number of the second certificate, I click the 'Відмінити' button. After that I can't click again 'Додати сертифікат' button and I have to delete the first certificate and re-enter both
