### ISSUE TITLE
[USB-User cabinet. Bonuses] The user can't use sorting for bonuses by spending or replenishing in personal cabinet

### ISSUE THREAD

**Issue by anastasiialutsiv** [ita-social-projects/GreenCity#4291]
**Environment:** Mac OS Monterey 12.4;  Safari 15.5 
**Reproducible:** always
**Build found:**  09/06/2022

**Preconditions**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The UBS-user page is opened
Use test user (timka690ISTQB@gmail.com) with available bonuses in the cabinet

**Steps to reproduce**
1. Click on the button 'Рахунок' on the left menu panel
2. Open a window about bonuses information for user
3. Look at the available bonuses
![photo_2022-06-09 09 34 50](https://user-images.githubusercontent.com/105366154/172780539-4944e93e-0262-40b2-b7a4-9f5a70a5e7c1.jpeg)

4. Click on the button 'Кількість' for sorting by spending or replenishing 

**Actual result**
The client can not sort available bonuses by spending or replenishment. 

**Expected result**
The client can sort available bonuses by spending or replenishing. Sorting by number asc and desc.

**User story and test case links**
E.g.: "User story #3670 
[Test case](https://jira.softserve.academy/browse/GC-2719)"

**Labels to be added**
"Bug"

**Comment by NataliaVirt** [comment]
Fixed
