### ISSUE TITLE
[USB-User cabinet. Bonuses] The bonus accrual date is shown in wrong format

### ISSUE THREAD

**Issue by anastasiialutsiv** [ita-social-projects/GreenCity#4293]
**Environment:** Mac OS Monterey 12.4;  Safari 15.5
**Reproducible:** always
**Build found:** 09/06/2022

**Preconditions**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The UBS-user page is opened

**Steps to reproduce:**
1. Click on the button 'Рахунок' on the left menu panel
2. Open a window about bonuses information for the user
3. Look at the sorting by date 
4. Pay attention to the format of date 

**Actual result**
The format of the date is D.MM.YYYY (e.g: 8.06.2022)

**Expected result**
The format of the date should be DD/MM/YYYY (e.g: 08/06/2022)

**User story and test case links**
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/3670
[Test case](https://jira.softserve.academy/browse/GC-2719)"

Labels to be added
"Bug"

**Comment by YelyzavetaSheptytska** [comment]
Need to clarify the date status (after the 01.10.2022)
