### ISSUE TITLE
[USB-User cabinet. Bonuses] The column 'Кількість' has integers format instead of a float number

### ISSUE THREAD

**Issue by anastasiialutsiv** [ita-social-projects/GreenCity#4294]
**Environment:** Mac OS Monterey 12.4;  Safari 15.5 
**Reproducible:** always
**Build found:**  09/06/2022

**Preconditions**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The UBS-user page is opened
Use test user with available bonuses in the cabinet

**Steps to reproduce**
1. Click on the button 'Рахунок' on the left menu panel
2. Open a window about bonuses information for a user
3. Look at the available bonuses
4. Look at the button 'Кількість' for sorting by spending or replenishing and pay attention to the format of the column

**Actual result**
The column 'Кількість' has an integers format instead of a float number (e.g: 255)

**Expected result**
The column 'Кількість' should have a float number with 2 digits (e.g: in format 255.00 bonuses when replenished, and 255.00 bonuses when spending); 

**User story and test case links**
E.g.: "User story #3670 
[Test case](https://jira.softserve.academy/browse/GC-2719)"

**Labels to be added**
"Bug"

**Comment by NataliaVirt** [comment]
Fixed
![image](https://user-images.githubusercontent.com/112310945/196670143-4f9ddaf6-f9e3-4be7-872c-aadae9ca12ee.png)
