### ISSUE TITLE
[UBS-user. Orders] The cost of the services is not displayed properly in the order details

### ISSUE THREAD

**Issue by yarkokuzyk** [ita-social-projects/GreenCity#4296]
**Environment:** Windows 10, Opera browser
**Reproducible:** always
**Build found:** 09.06.2022

**Preconditions**
The user is logged in and made an order (e.g. 'Безпечні відходи' in the quantity of 4 packages, each package is per 250UAH), total amount - 1000UAH.

**Steps to reproduce**
1. Go to the UBS-user cabinet
2. Find your order just been made and expand it
3. Check the correctness of the "cost" column

**Actual result**
The user cannot see the information about the cost, only the currency.

**Expected result**
The user sees all the information about the cost that is being displayed in XXX.xx format

![image](https://user-images.githubusercontent.com/104302356/172855190-25a1fb1b-cae9-4cac-a81f-1c274db72e61.png)

**User story and test case links**
User story #3478 

**Labels to be added**
"Bug", Priority ("pri:medium "), Severity ("medium:"), Type ("Functional")

**Comment by NataliaHlazova** [comment]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/87066582/175262436-79f67697-c7d5-43ec-b524-676305f37e1a.png">
