### ISSUE TITLE
[Personal cabinet] - Order tab: message about bonuses return. The user does not get bonunes after paid for money when the order is "Скасовано" 

### ISSUE THREAD

**Issue by Olenazenchenkoo** [ita-social-projects/GreenCity#4299]
**Environment:** OS Windows 10 21H1
Browser Chrome 100.0.4896.127
**Reproducible:** always
**Build:** 09.06.2022

**Preconditions**
1. Create a user and make an order that is paid for money (e.g. 'Безпечні відходи' in quantity of 4 packages (each package is per 250UAH), total amount - 1000UAH).

 2. User is Logged in to GreenCity as an Administrator: https://ita-social-projects.github.io/GreenCityClient/#/ubs 

**Steps to reproduce**
1. Open 'Замовлення' tab and find order mentioned in preconditions
2. Open the order found in step 1, change the order status on the "Скасовано" and click on the "Зберегти" button
3. Log in to GreenCity as a User
4. Open 'Замовлення' tab and find order mentioned in preconditions
5. Open the order found in step 4
6. Open the 'Рахунок' tab

**Actual result**
The User does not get any bonuses after the order status is changed to 'Скасовано'

**Expected result**
The amount of bonuses in value of 1000 UAH has to displayed on the page 

**User story and test case links**
E.g.: "User story #3633 
[Test case](https://jira.softserve.academy/browse/GC-2379)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Andrii-Yezenitskyi** [comment]
Not a bug. Duplicate (see #3884).
