### ISSUE TITLE
[USB-User cabinet. Bonuses] Text field what consist information about reason for accrual of bonuses is not correct

### ISSUE THREAD

**Issue by anastasiialutsiv** [ita-social-projects/GreenCity#4302]
**Environment:** Mac OS Monterey 12.4;  Safari 15.5
**Reproducible:** always
**Build found:** 09/06/2022

**Preconditions**
1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The UBS-user page is opened

**Steps to reproduce:**
1. Click on the button 'Рахунок' on the left menu panel
2. Open a window about bonuses information for the user
3. Look at the available bonuses
4. Pay attention to the column 'Причина'

**Actual result**
1. The text field doesn't consist of full  information about the reason for the accrual of bonuses (e.g: Замовлення №216)

**Expected result**
1. Text field should consist information about reason for accrual of bonuses (e.g: “Повернення за замовлення №12345” or “Зарахування за замовлення №12345)

<img width="551" alt="Screenshot at Jun 09 23-19-33" src="https://user-images.githubusercontent.com/105366154/172937160-2dfa5bf2-b4d6-41f1-8ee8-c26fdcb3a9f1.png">

**User story and test case links**
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/3670
[Test case](https://jira.softserve.academy/browse/GC-2719)"

Labels to be added
"Bug"

**Comment by NataliaVirt** [comment]
Fixed
![image](https://user-images.githubusercontent.com/112310945/193572678-70cd54a5-b608-45ca-8ee2-3049b00532a7.png)
![image](https://user-images.githubusercontent.com/112310945/193572807-9f761fce-5830-4048-a058-ef7ea2c7cbda.png)
