### ISSUE TITLE
[UBS-user delete profile] UI inconsistency in pop-up with the warning message when user try to delete his/her profile

### ISSUE THREAD

**Issue by mikhaylovamarina** [ita-social-projects/GreenCity#4304]
**Environment:** macOS version 11.5.2, Safari; Chrome, Windows 10, 11; Mozilla Firefox, Windows 10, 11
**Reproducible:** always
**Build found:** 08.06.22

**Preconditions**
1. User is logged in [GreenCity (ita-social-projects.github.io)](https://ita-social-projects.github.io/GreenCityClient/#/)
2. 'UBS-user' - user`s personal cabinet is opened.
3. 'Дані користувача' tab is opened in the personal cabinet
4. "Видалити профіль" button is clicked on 
5. Pop-up window "Якщо Ви видалите свій профіль, ваші бонуси згорять, а інформацію про ваші замовлення буде видалено без можливості відновлення" is appearred

**Steps to reproduce**
1. Verify that shade of green colour of button is appropriate 
2. Verify that words on button "Видалити", "Скасувати" corresponds to mock-up  
3. Verify that all text has font - Lato 
4. Verify that all required elements are present on the page (corresponds to mock-up)
5. Verify UI control's alignment, spelling

**Actual result**
1. The shade of green colour of button "Видалити" differs from mock-up from figma 
2. The colour of word "Видалити" is white, the colour of word "Скасувати" is green
3. The font of text differs from mock-up from figma 
4. The buttons are on the right side
6. All required elements are not corresponds to mock-up
<img width="508" alt="actual result" src="https://user-images.githubusercontent.com/105449847/172945263-2dce9fb5-8767-486d-941e-df42b56c912e.png">

**Expected result**
1. Green colour of button "Видалити" : primary/02. Green UBS #AFD85A
2. The colour of this words "Видалити", "Скасувати" :Greyscale/08. Black #1D2830;
Font: Lato;
styleName:  Subtitle-2;
font-size : 14px;
font-weight: 700;
line-height: 20px;
letter-spacing: 0.10000000149011612px;
text-align: center
3. Lato font
4. The buttons are on the left side
5.  All required elements are present on the page (corresponds to mock-up)

<img width="524" alt="pop-up from figma" src="https://user-images.githubusercontent.com/105449847/172945325-9683ad60-8239-4c03-8562-46b15f6c4c22.png">

**User story and test case links**
E.g.: "User story #3807 
[Test case](https://jira.softserve.academy/browse/GC-2782)"

**Labels to be added**
"Bug", Priority ("medium"), Severity ("major"), Type ("UI")

**Comment by NataliaVirt** [comment]
Fixed
![image](https://user-images.githubusercontent.com/112310945/198145319-4bfe5555-d7f9-43d6-b37e-8e7a896d1d77.png)
