### ISSUE TITLE
[Personal cabinet] The amount in the 'Сума' field in the 'Оплата' pop up does not correspond to the 'Сума до оплати' field in the 'Деталі замовлення' tub for orders with 'Частково оплачено' payment status 

### ISSUE THREAD

**Issue by OlhaHubarieva** [ita-social-projects/GreenCity#4307]
**Environment:** Windows 10 PRO. Google Chrome 102.0.5005.115.
**Reproducible:** always.
**Build found:** 12.06.2022
**Preconditions**

1. The user is logged in GreenCity https://ita-social-projects.github.io/GreenCityClient/#/
2. The 'Замовлення' tab in the 'UBS-user' tab is opened.
3. The order with 'Частково оплачено' payment status is selected.

**Steps to reproduce**
1. Click on the 'Оплатити' button related to the order with the 'Частково оплачено' payment status.

**Actual result**
The amount in the 'Сума' field in the 'Оплата' pop up does not correspond to the 'Сума до оплати' field in the 'Деталі замовлення' tub.

![Actual result Оплата pop up](https://user-images.githubusercontent.com/105358315/173222684-1b1310f2-11e0-4669-bf5a-9d827e2c55f6.png)

![Order 234 User tab](https://user-images.githubusercontent.com/105358315/173222693-05391ae0-b8c9-41df-89ee-6f63d71eb198.png)

**Expected result**
The amount in the 'Сума' field in the 'Оплата' pop up corresponds to the 'Сума до оплати' field in the 'Деталі замовлення' tub.

**User story and test case links**
User story (https://github.com/ita-social-projects/GreenCity/issues/3491)
[Test case] (https://jira.softserve.academy/browse/GC-2832)

**Comment by Horokh** [comment]
Bug  is fixed
