### ISSUE TITLE
[DateBase] Order_status. Order_status can't be changed for orders

### ISSUE THREAD

**Issue by YuliiaFrankova** [ita-social-projects/GreenCity#4312]
**Environment:** DB
**Reproducible:** always

**Preconditions**
User has formed Order №

**Steps to reproduce**
1. Go to DB
2. Open table Orders
3. Find Order №
4. Change order_status column from Formed to Adjustment/Brought by himself/Confirmed/Оn the route/Not taken out/Done/Canceled
5. Click on Submit

**Actual result**
Error massage is displayed
![image](https://user-images.githubusercontent.com/105280048/173349690-1fdf8705-a947-45a1-a04f-5013c1c98caf.png)

**Expected result**
Changes saved 

**User story and test case links**
E.g.: "User story #3477

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: High"), Type ("UI, "Functional")

**Comment by VadymMakitra** [comment]
@YuliiaFrankova Hi, it is not a bug, everything is ok. Your work is to test API, and UI, for this changes in DB are not needed.
