### ISSUE TITLE
[UBS-User. Personal Cabinet] Validation in the 'Будинок' field allows only 4 characters instead of 8

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4313]
**Environment:** Microsoft 11, Chrome Version 102.0.5005.115
**Reproducible:** always.
**Build found:**13.06.22

**Preconditions**
1. Log in to the GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. Open 'UBS-user'
2. Click on 'User Data'
3. Click on 'Edit data'
4. Enter 8 numeric and alphabetic characters in the 'Будинок' field (e.g. "1254ABCD")

**Actual result**
1. The 'Будинок' field is highlighted in red color when the user enters more than 4 characters. 
![image](https://user-images.githubusercontent.com/105448699/173422848-e913ee6e-1cb7-4d94-a789-4d9b72349fdd.png)

**Expected result**
1. In the 'Будинок' field from a minimum of 1 to a maximum of 8 characters are allowed.

**User story and test case links**
E.g.: "User story #3811
[Test case](https://jira.softserve.academy/browse/GC-2737)"

**Comment by Horokh** [comment]
https://user-images.githubusercontent.com/102593506/180768312-593248bc-e02d-4063-a367-00406ad6da97.mp4

**Comment by marianaharnyk** [comment]
This bug cannot be reproduced

https://www.loom.com/share/f2ac5042719147729dd05513837c063e

**Comment by marianaharnyk** [comment]
Requirements of user story https://github.com/ita-social-projects/GreenCity/issues/3811 were changed. The system should allow the user to type from minimum 1 to maximum 5 characters.
