### ISSUE TITLE
[UBS-User. Personal Cabinet] Validation in the 'Корпус' field allows the only 4 characters instead of 8

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4315]
**Environment:** all
**Reproducible:** always.
**Build found:**13.06.22

**Preconditions**
1. Log in to the GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. Open the 'UBS-user' page
2. Click on the 'User Data' tab
3. Click on 'Edit data' button
4. Enter 8 characters in the 'Корпус' field (e.g. "1234ABCD")

**Actual result**
1. The 'Корпус' field is highlighted in red color when the user enters more than 4 characters
![image](https://user-images.githubusercontent.com/105448699/173426541-5c34e7c0-4886-4200-834e-2313b381da50.png)

**Expected result**
1. In the 'Корпус' field a minimum 1 to maximum 8 characters are allowed.

**User story and test case links**
E.g.: "User story #3811
[Test case](https://jira.softserve.academy/browse/GC-2740)"

**Comment by Horokh** [comment]
https://user-images.githubusercontent.com/102593506/180762447-63dc91bb-79dd-4152-8b8b-9e94dea5d7e1.mp4

**Comment by marianaharnyk** [comment]
This bug cannot be reproduced

https://www.loom.com/share/52d71f88274041cd9f60fa314b23e4bd

**Comment by marianaharnyk** [comment]
This bug can be reproduced only in pop-up add address. 
https://www.loom.com/share/65af852c67da48529f3cebe94088179f

**Comment by marianaharnyk** [comment]
Requirements of user story #3811 were changed. The system should allow the user to type from minimum 1 to maximum 5 characters.
