### ISSUE TITLE
[UBS-User. Personal Cabinet] The system does not show drop-down list with the street suggestions based on the Places API (Place Autocomplete) after entering the first 3 characters in the 'Вулиця' field 

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4316]
**Environment:** all.
**Reproducible:** always.
**Build found:** 13.06.22

**Preconditions**
1. Log in to the GreenCity as User https://www.testgreencity.ga/GreenCityClient/#/

**Steps to reproduce**

1. Open the 'UBS-user' page
2. Click on the 'User Data' tab
3. Click on 'Edit data' button
4. Enter the first 3 characters of the name of the street in the 'Вулиця' field (e.g. "Хре ")

**Actual result**
1. The system doesn`t show a drop-down list with the street suggestions based on the Places API (Place Autocomplete) after typing 3 characters in the 'Вулиця' field 
![image](https://user-images.githubusercontent.com/105448699/173430240-e7920273-c48e-40f6-b6af-ea8ff45d1c0e.png)

2. The form is filled only in ukrainian language.

**Expected result**
1. After typing 3 characters, the system shall show the street suggestions based on the Places API (Place Autocomplete). Suggestions are displayed by a drop-down list. 
2. The form should be filled both in ukrainian and english language.

**User story and test case links**
E.g.: "User story #3811
[Test case](https://jira.softserve.academy/browse/GC-2750)"

**Comment by irynakoch** [comment]
When editing existing address, the system doesn't show a drop-down list with suggested streets. 
The drop-down list is shown only when adding new address.
