### ISSUE TITLE
[UBS-User. Personal Cabinet] The "Додати адресу" button is shown below the 'Адреса 4' block after user has added the max available 4 adresses

### ISSUE THREAD

**Issue by olabell** [ita-social-projects/GreenCity#4323]
Environment: all.
Reproducible: always.
Build found: 14.06.22

Preconditions
1. Log in to the GreenCity as User [https://ita-social-projects.github.io/GreenCityClient/#/](https://ita-social-projects.github.io/GreenCityClient/#/)
2. Four address is added.

Steps to reproduce
1. Open the 'UBS-user' page
2. Click on the 'User Data' tab
3. Click on the "Редагувати дані" button.

Actual result
The "Додати адресу" button is shown below the 'Адреса 4' block after user has added the max available 4 adresses
![image](https://user-images.githubusercontent.com/39055716/173597895-cfa14f5f-2e5a-45a3-9534-d1fdf5d00a14.png)

Expected result
The "Додати адресу" button is not shown below the 'Адреса 4' block after user has added the max available 4 adresses.
Max 4 adresses can be added.

E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/3811
[Test case](https://jira.softserve.academy/browse/GC-2775)

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/181229157-76eeb595-1ba1-47a1-a344-7bbe090b973b.png)
