### ISSUE TITLE
[UBS-User. Personal Cabinet] The address can't be deleted by user by clicking on delete icon on 'Редагувати дані' page

### ISSUE THREAD

**Issue by olabell** [ita-social-projects/GreenCity#4326]
Environment: all.
Reproducible: always.
Build found: 14.06.22

Preconditions
1. Log in to the GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/
2. User's personal account 'UBS-user' is opened.
3. Address is added.
4. Figma`s mockup is opened - https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=24950%3A84649

Steps to reproduce
1. Click on the "Редагувати дані" button.
2. Pay attention on the adresses section.

Actual result
The address can't be deleted by user by clicking on delete icon on 'Редагувати дані' page
![image](https://user-images.githubusercontent.com/39055716/173663920-94ab9f43-7b86-4bd9-99ae-195b15e60a0f.png)

Expected result
The address can deleted by user by clicking on delete icon on 'Редагувати дані' page
![image](https://user-images.githubusercontent.com/39055716/173664034-d27bc99d-a508-41c9-a632-c2e8f71d1a62.png)

E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/3811
[Test case](https://jira.softserve.academy/browse/GC-2797)

**Comment by Olena-Kharkova** [comment]
A bug is not fixed
![12](https://user-images.githubusercontent.com/110603507/211373923-2817e95f-ca81-4b94-afe4-40c24d8d7c0c.png)
