### ISSUE TITLE
[USB-User. Order page]Step 3. Not displayed data of order on confirmation page, english localization

### ISSUE THREAD

**Issue by Olenazenchenkoo** [ita-social-projects/GreenCity#4328]
**Environment:** OS Windows 10 21H1
Browser Chrome 100.0.4896.127
**Reproducible:** always
**Build found:**  14.06.2022

**Preconditions**
Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/;
Choose English language;
Click on 'Sing in';
Log in as a new registered user.

**Steps to reproduce**
1. Click on 'UBS кур'єр' tab;
2. Click on 'Call the courier';
2. Fill in 'Order details' and 'Personal data';
3. Go to 'Confirmation page'.

**Actual result**
The order is not displayed on the page. Look on the attachement.
![image](https://user-images.githubusercontent.com/105363982/173679325-1a19d563-dae6-4f31-8c5b-58091001f1a3.png)

**Expected result**
The user can see his order with all the data.

**Comment by vplvua** [comment]
Not reproduce.
I tried in different order configurations. My orders were always displayed correctly. 
![Screenshot 2022-09-28 074720](https://user-images.githubusercontent.com/95560409/192690474-2143b9ed-0c61-4714-9311-b1b96b0788ad.png)
