### ISSUE TITLE
[USB-User. Order page]UI localization inconsistencies. The address field is not translated into English.

### ISSUE THREAD

**Issue by Olenazenchenkoo** [ita-social-projects/GreenCity#4329]
**Environment:** OS Windows 10 21H1
Browser Chrome 100.0.4896.127
**Reproducible:** always
**Build found:** 14.06.2022

**Preconditions**
Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/;
Choose English language;
Click on 'Sing in';
Log in as a registered user.

**Steps to reproduce**
1. Click on 'UBS кур'єр' tab;
2. Click on 'Call the courier';
3. Fill in 'Order details';
4. Fill in 'Personal data'.

**Actual result**
The field with 'Garbage collection address' doesn't translate into English.

**Expected result**
All field have to be translated into English.
![image](https://user-images.githubusercontent.com/105363982/173681588-28c0d933-1286-430e-97f1-d34f102a1e38.png)

**Comment by vplvua** [comment]
Not Reproduce.
I do not see this problem. 
![Screenshot 2022-09-28 192705](https://user-images.githubusercontent.com/95560409/192834777-a42f48bb-4471-4ca0-a574-69d2654dd39f.png)
