### ISSUE TITLE
[UBS-User. Order form] The address which was edited in the user`s personal cabinet is not displayed correctly on the Order form and in the pop-up for edit of this address

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4344]
**Environment:** all.
**Reproducible:** always.
**Build found:**16.06.22

**Preconditions**
1. Log in to the GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/
2. User has at least 1 address in the personal cabinet

**Steps to reproduce**
1. Open the 'UBS-user' page
2. Click on the 'User Data' tab
3. Click on 'Edit data' button
4. Edit fields of the first address
5. Click on the 'Save changes' button
6. Click the 'Orders' tab 
7. Click on the 'New order' button
8. Fill location and 'Orders details' with correct data
9. Click on the 'Personal data' tab :

- Move to the address section
- Click on the 'Pencil' icon to edit the first address

**Actual result**
1. The not all data of the edited address is displayed in the address section
![image](https://user-images.githubusercontent.com/105448699/174149531-733129a5-175f-441c-ad14-96d4d7ff0cbf.png)
2. The pop-up is shown with all empty fields of the address and not all fields are displayed
![image](https://user-images.githubusercontent.com/105448699/174149231-fc09c584-c4f4-40f1-aa9b-4bf2e6ef2b3e.png)

**Expected result**
1. Edited address is displayed with all fields
![image](https://user-images.githubusercontent.com/105448699/174150762-095544fa-7e95-4507-9503-492dd282481c.png)
2. Pop-up is shown with filled fields of the address
![image](https://user-images.githubusercontent.com/105448699/174150917-ce008534-92bc-4072-9da3-ff96e2cb25c7.png)

**User story and test case links**
E.g.: "User story #2531

**Comment by vplvua** [comment]
Not reproduce.

This problem has already been solved.

Address is displayed in full
![image](https://user-images.githubusercontent.com/95560409/197683877-1ceee99c-9b3e-4437-828a-afe5a2e9efd9.png)

All fields in the editing form are filled
![image](https://user-images.githubusercontent.com/95560409/197684074-e5d19b2d-8e1b-42cf-a97c-e79438f07f0e.png)
