### ISSUE TITLE
[USB-User. Order page] Infinity scroll is not implemented on 'Поточні замовлення' and 'Історія замовлень' tabs

### ISSUE THREAD

**Issue by valeriia2301** [ita-social-projects/GreenCity#4345]
**Environment:** Windows 10 Pro 21H2 19044.1415, Chrome 102.0.5005.63 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 17.06.2022

**Preconditions**

1. Logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/) 
2. User has at least 20 orders per tabs ('Поточні замовлення' and 'Історія замовлень')

**Steps to reproduce**
1. Go to 'UBS-user' - 'Замовлення' - 'Поточні замовлення'
2. Scroll down the page with the list of orders
3. Click on 'Історія замовлень' tab
4. Scroll down the page with the list of orders

**Actual result**
Infinity scroll is not implemented on 'Поточні замовлення' and 'Історія замовлень' tabs. User can see only last 10 orders

![scroll](https://user-images.githubusercontent.com/105349761/174167296-522ab230-23c0-407b-ab42-a2ae82b2e3e5.png)

**Expected result**
Infinity scroll is implemented on both tabs

**User story and test case links**
User story #3477 
[Test case](https://jira.softserve.academy/browse/GC-2617)

**Comment by krayevska** [comment]
duplicate https://github.com/ita-social-projects/GreenCity/issues/4306
