### ISSUE TITLE
[Orders From. Step 2,3] The improper naming of the fields on the 'Особисті дані' and 'Підтвердження' tabs.

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4357]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:** 20.06.2022

**Preconditions**

1. The user is logged in as a User in the GreenCity: https://www.testgreencity.ga/GreenCityClient/#/ubs

**Steps to reproduce**
1. Click the 'Замовити кур'єра' button, select the 'Київ' option and click the 'Продовжити' button.
2. Select the required amount of packages and click the 'Далі' button. 
4. Verify the naming of the fields regarding another recipient's personal information and address details the user should enter on the 'Особисті дані' tab.
5. Click the 'Далі' button and verify if the corresponding fields are correctly named on the 'Підтвердження' tab.

**Actual result**
There are such naming for the fields regarding another recipient's personal information and address details as 'Отримувач інша людина' and 'Адреса вивозу сміття' on 'Особисті дані' tab. On the 'Підтвердження' tab they are named as 'Отримувач' and 'Адреса вивезення замовлених послуг.
![image](https://user-images.githubusercontent.com/105351490/174666293-a28e4d50-fe68-4dfc-9676-8f8d36e421e3.png)
![image](https://user-images.githubusercontent.com/105351490/174732761-632d5cbc-2cef-445e-bde4-ad5b6dd8d505.png)

**Expected result**
The fields regarding another recipient's personal information and address details should be 'Відправник інша людина' and 'Адреса вивезення відходів' on the 'Особисті дані' tab and  'Відправник' and 'Адреса вивезення відходів' on the 'Підтвердження' tab.
![image](https://user-images.githubusercontent.com/105351490/174730947-63f97ac8-bde0-42bc-9fa9-ba82277aa9ca.png)
![image](https://user-images.githubusercontent.com/105351490/174733395-5f49500c-1de3-42f9-baf1-78d861e6284f.png)

**User story and test case links**
E.g.: "User story #3592

**Labels to be added**
"Bug", Priority ("High"), Severity ("Minor"), Type ("UI").

**Comment by AntonHusiev** [comment]
**25.07.2022**

Fields are not renamed on the 'Особисті дані' and 'Підтвердження' tabs.
