### ISSUE TITLE
[Orders Form. Step 3] The 'Коментар до замовлення' field is not seperated from other fields on the 'ПІдтвердження' step and its label in not in bold 

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4358]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:**21.06.2022

**Preconditions**

1. The user has logged as a registered user in GreenCity: https://ita-social-projects.github.io/GreenCityClient/#/
2. The use has made a new order in which he made a comment in the 'Коментар до замовлення' field and input all the required fields on the 'Деталі замовлення' and 'Особисті дані' steps till the 'Підтвердження' step.

**Steps to reproduce**
1. On the 'Підтвердження' tab, verify that the 'Коментар до замовлення' field is separated from the other fields that are located on the page and are in a proper place and of accepted design that corresponds to the mock-up.

**Actual result**
The  comment in the 'Коментар до замовлення' field placed below the 'Коментар до адреси' field.  It is not separated from other fields and its label is not in bold.  Its location and design don't correspond to the mock-up.
![Screenshot_78](https://user-images.githubusercontent.com/105351490/174827143-ccfe549c-d6e2-47c9-af78-cebe657f66ac.png)

**Expected result**
The  comment in the 'Коментар до замовлення' field is placed between 'Отримувач' and 'Адреса вивезення замовлених послуг' fields. It is separated and its label is in bold. Its location and design correspond to the mock-up.
![Screenshot_79](https://user-images.githubusercontent.com/105351490/174828596-9d131d33-9f96-45fc-92fa-a8aa99be3a52.png)

**User story and test case links**
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/2200,https://github.com/ita-social-projects/GreenCity/issues/2541
[Test case](https://jira.softserve.academy/browse/GC-2066

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Trivial"), Type ("UI")

**Comment by voronkooleksandr** [comment]
![image](https://user-images.githubusercontent.com/61209463/179418627-5a428910-f04b-4894-9ea7-dacbf47db11c.png)

Actual  mock-up

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/181229896-8c9c3f35-c7c3-443b-8efd-bb9dda6898e9.png)
The bug has not been fixed yet

**Comment by OlhaKyrylenko** [comment]
The comment in the 'Коментар до замовлення' field is placed between 'Отримувач' and 'Адреса вивезення замовлених послуг' fields. It is separated and its label is in bold. Its location and design correspond to the mock-up.

![1](https://user-images.githubusercontent.com/112948983/190859098-f6c304f7-855e-48a2-b999-8b4e0cffafdc.PNG)
