### ISSUE TITLE
[UBS-User. Bonus notification] The notification about received bonuses is sent 4 times

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4359]
**Environment:** all.
**Reproducible:** always.
**Build found:** 21.06.22

**Preconditions**
Create a user and make an order that is paid via Fondy (e.g. 'Безпечні відходи' in quantity of 4 packages (each package is per 250UAH), total amount - 1000UAH).
User is Logged in to GreenCity as an Administrator: https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Steps to reproduce**

1. Open 'Замовлення' tab and find order mentioned in preconditions
2. Open the order found in step 1 and change order`s status to the 'Привезе сам'
3. Update the page
4. Change order`s status to the 'Виконано'
5. Make the amount of bags less, so that the paid sum is higher than it became as the result 
6. Transfer the rest money to bonuses
7. Click on the 'Зберегти' button
8. Log in to GreenCity as a User (https://ita-social-projects.github.io/GreenCityClient/#/ubs Use credentials as for Client mentioned in preconditions)
9. Open 'Повідомлення' tab and find order mentioned in preconditions

**Actual result**
1. The notification about received bonuses is sent 4 times
![Знімок екрана 2022-06-23 164648](https://user-images.githubusercontent.com/105448699/175314679-4e19142b-bcd5-4766-a07e-4fd748ac63dd.png)

**Expected result**
1. The notification about recieved bonuses should be one time

**User story and test case links**
E.g.: "User story #2796
[Test case](https://jira.softserve.academy/browse/GC-2386)"

**Comment by TaniaQC** [comment]
Notificatiion is sent only one time
