### ISSUE TITLE
[UBS-User. Bonus notification] The notification about recieved bonuses is not displayed the payment sum received from the order form

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4361]
**Environment:** all.
**Reproducible:** always.
**Build found:**21.06.22

**Preconditions**

1. Create a user and make an order that is paid via Fondy (e.g. 'Безпечні відходи' in quantity of 4 packages (each package is per 250UAH), total amount - 1000UAH).
2. User is Logged in to GreenCity as an Administrator: https://ita-social-projects.github.io/GreenCityClient/#/ubs

**Steps to reproduce**

1. Open 'Замовлення' tab and find order mentioned in preconditions
2. Open the order found in step 1 and change order`s status to the 'Привезе сам'
3. Update the page
4. Change order`s status to the 'Виконано'
5. Make the amount of bags less, so that the paid sum is higher than it became as the result
6. Transfer the rest money to bonuses
7. Click on the 'Зберегти' button
8. Log in to GreenCity as a User (https://ita-social-projects.github.io/GreenCityClient/#/ubs Use credentials as for Client mentioned in preconditions)
9. Open 'Повідомлення' tab and find order mentioned in preconditions
10. Open the order found in step 9

**Actual result**
1. The payment sum is not  received from the order form
![Знімок екрана 2022-06-21 180605](https://user-images.githubusercontent.com/105448699/174833588-3d3ba9ea-ba55-45b2-b69a-2de997dbad86.png)

**Expected result**
1. The payment sum is received from the order form

**User story and test case links**
E.g.: "User story #2796 
[Test case](https://jira.softserve.academy/browse/GC-2386)"

**Comment by TaniaQC** [comment]
![image](https://user-images.githubusercontent.com/105351490/181189558-b06276c5-51c7-46f7-8215-162957054bd9.png)
