### ISSUE TITLE
[UBS-User. Notifications] UI inconsistencies with mock-up in the 'Messages' tab in the personal cabinet

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4363]
**Environment:** all.
**Reproducible:** always.
**Build found:** 22.03.22

**Preconditions**
1. User is Logged in to GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/
2. UBS-User is opened

**Steps to reproduce**
1. Click on the 'Messages' tab

**Actual result**
1. The titles and time of the messages aren`t aligned
2. The font of the message text is Roboro, Helvetica
3. The content of messages and time aren`t separate with place. 
4. The placement of the buttons for expand\ collapse to show message content is near 'Time' column
![Знімок екрана 2022-06-23 071520](https://user-images.githubusercontent.com/105448699/175209218-646efec7-01cd-4a10-9ec9-51435c93f9af.png)
![Знімок екрана 2022-06-21 221412](https://user-images.githubusercontent.com/105448699/175209236-48470ac9-d52d-48e9-bceb-61d212b441f1.png)

**Expected result**
1. The titles and time of the messages is aligned
2. The font of the message text is Leto
3. The text of messages and time should be separate with place. 
4. The placement of the buttons for expand\ collapse to show message content should be near '№ order'
![Знімок екрана 2022-06-21 221324](https://user-images.githubusercontent.com/105448699/175209259-f4bbfae1-f668-47bd-8668-9ed15a73747f.png)

**User story and test case links**
E.g.: "User story #2796
[Test case](https://jira.softserve.academy/browse/GC-2924)"

**Comment by AngelinaRudnitska** [comment]
Can not access "Повідомлення" as User. 
![403 error](https://user-images.githubusercontent.com/64897885/192575323-70c947d4-b067-488c-bb62-430fa6ea8dad.png)
