### ISSUE TITLE
[Order Page. Step 1] Pointer position when user click up or down for adding item for order doesn't work correct 

### ISSUE THREAD

**Issue by anastasiialutsiv** [ita-social-projects/GreenCity#4367]
**Environment:** macOS Monterey 12.3.1; Safari 15.4
**Reproducible:** always
**Build found:** 23/06/2022

**Preconditions**
1. Go to GreenCity web site 
https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. Log in as a user. As the user goes to the "Деталі замовлення" step in the order form

**Steps to reproduce:**
1. Go to "Послуги" 
2. Choose "Текстильні відходи" and add 1 or more numbers in the "Кількість пакетів" field by clicking on the slider
3. Click outside the field 
4. Repeat the same action of adding numbers of the packet by clicking on the slider

**Actual result**
The number of packets is added not correct. Pointer position go to the first position instead of changing number one by one (e.g: 1 - 21 - 321)

**Expected result**
The number of packets is added correct one by one after clicking outside the field. Ordinal addition is present (e.g: 1 - 2- 3)

https://user-images.githubusercontent.com/105366154/175331158-73120266-93ae-4a11-90f0-e0b62a2da9b9.mov

**User story and test case links**
E.g.: "User story #2379 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by AngelinaRudnitska** [comment]
Bug is not reproducible
