### ISSUE TITLE
[UBS-User. User Data page] Add an alternative email to the UBS User Data page

### ISSUE THREAD

**Issue by Myh45** [ita-social-projects/GreenCity#4368]
As a User, I shall be able to add an alternative email

Preconditions
1. Go to the UBS User Data page
2. Click on in Edit Data button
3. Click on Add alternative email button
4. Input for the alternative email should appear below

Issue link
#3805

**Comment by YBielik** [comment]
After entering an alternative email, the data is not displayed on the User Data page. Edited user data cannot be saved after clicking the 'Save changes' button

**Comment by atsa21** [comment]
User Date don't save changes if house number with "/" like "1/3". 
https://greencity-ubs.testgreencity.ga/ubs/userProfile/user/update
Need to add validation to "addressDto[0].houseNumber"  that accept "/" in back-end
