### ISSUE TITLE
[UBS-user Messages] The system doesn`t resend a message every 7 days (once a week) for a month when user made unpaid order

### ISSUE THREAD

**Issue by mikhaylovamarina** [ita-social-projects/GreenCity#4369]
**Environment:** macOS version 11.5.2, Safari; Chrome, Windows 10, 11; Mozilla Firefox, Windows 10, 11
**Reproducible:** sometimes 
**Build found:** 23.06.22

**Preconditions**
1. User 1 is logged in as client  https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. User 2 is logged in as client  https://ita-social-projects.github.io/GreenCityClient/#/ubs
3. User 3 is logged in as client  https://ita-social-projects.github.io/GreenCityClient/#/ubs
4. User 4 is logged in as client  https://ita-social-projects.github.io/GreenCityClient/#/ubs
5. User 1, 2, 3, 4 are on the UBS Courier page

**Steps to reproduce**

1. User 1,2,3,4 click on 'Замовити кур'єра' button
2. User 1,2,3,4 fill pages 'Деталі замовлення', 'Особисті дані',  'Підтвердження' 
3. User 1,2,3,4 click the 'Відмінити' button
4. User 1,2,3,4 click on 'Так, зберегти' button
5. User 1,2,3,4 go to UBS-user Page 
6. User 1,2,3,4 click on 'Повідомлення'
7. . Check if the system resends a message  in 3 days for User 1
8.  Check if the system resends a message  in 10 days for User 2
9.  Check if the system resends a message  in 17 days for User 3
10.  Check if the system resends a message  in 24 days for User 4

**Actual result**
1. The system sometimes resends a message  in 3 days for User 1
2. The system sometimes resends a message  in 10 days for User 2
3. The system doesn`t resend a message  in 17 days for User 3
4. The system doesn`t resend a message  in 24 days for User 4

**Expected result**
1. The system always resends a message  in 3 days for User 1
2.  The system always resends a message  in 10 days for User 2
3.  The system always resends a message  in 17 days for User 3
4. The system always resends a message  in 24 days for User 4

**User story and test case links**
E.g.: "User story #2796 
[Test case](https://jira.softserve.academy/browse/GC-2900)"

**Labels to be added**
"Bug", Priority ("law"), Severity ("minor"), Type ("Functional")

**Comment by DanaIuich** [comment]
Bug is fixed
