### ISSUE TITLE
[UBS-user Messages] The system doesn`t send the notifications about unpaid orders at 18 p.m

### ISSUE THREAD

**Issue by mikhaylovamarina** [ita-social-projects/GreenCity#4370]
**Environment:** macOS version 11.5.2, Safari; Chrome, Windows 10, 11; Mozilla Firefox, Windows 10, 11
**Reproducible:** sometimes 
**Build found:** 23.06.22

**Preconditions**
1. User is logged in as client  https://ita-social-projects.github.io/GreenCityClient/#/ubs
2. User is on the UBS Courier page
3. 'Замовити кур'єра' button is clicked
4. Pages 'Деталі замовлення', 'Особисті дані',  'Підтвердження' (4444 5555 6666 1111, 02/19 555) are filled
5. The 'Відмінити' button is clicked
6. The 'Так, зберегти' button is clicked
7. User made this unpaid order 3, 10, 17 or 24 days ago 
8. User is on UBS-user page 

**Steps to reproduce**
1. Click on 'Повідомлення'
2. Expand the message
3. Examine if the system checks BD at 18.00 daily and sends messages in case the order was formed 3, 10, 17, 24 days ago and wasn’t paid by client.

**Actual result**
The system doesn`t send the notifications about unpaid orders at 18 p.m
<img width="1340" alt="actual result" src="https://user-images.githubusercontent.com/105449847/175328309-db76d4f6-2203-4576-84fc-ae15c9cf9255.png">

**Expected result**
The system sends the notifications about unpaid orders at 18 p.m

**User story and test case links**
E.g.: "User story #2796 
[Test case](https://jira.softserve.academy/browse/GC-2377)"

**Labels to be added**
"Bug", Priority ("law "), Severity ("minor"), Type ("Functional")

**Comment by Olena-Kharkova** [comment]
The notifications were not sent to the user into the User profile, it's available only by e-mail
https://user-images.githubusercontent.com/110603507/224495210-2ec9cbc6-a0f4-412e-8f2f-6e89c0bffcae.mp4

**Comment by DanaIuich** [comment]
Bug is fixed
