### ISSUE TITLE
[UBS-User. Bonus notification] The system sends an incorrect amount of surcharge in the message after changing the payment status to “Частково оплачено”

### ISSUE THREAD

**Issue by IrynaVdovyniuk** [ita-social-projects/GreenCity#4374]
**Environment:** all
**Reproducible:** always
**Build found:** 23.06.22

**Preconditions**
1. User is logged out
2. Admin is logged in 
3. Admin goes to UBS-admin
4. Admin goes to 'Замовлення'
5. Admin chooses the last paid order of his user
6. Admin opens an appropriate order and goes to 'Деталі замовлення'
7. Admin adds some amount of bags, for example, and gets the changes in total sum which should be covered by a client
8. Admin is logged out
9. User is logged in as client
10. User navigates to Client's cabinet
11. User is on UBS-user page

**Steps to reproduce**
1. Click on 'Повідомлення' tab
2. Expand an unread message
3. Сheck the amount of surcharge in the message

**Actual result**
The system sends an incorrect amount of surcharge in the message after changing the payment status to “Частково оплачено”
![1](https://user-images.githubusercontent.com/105349993/175392660-ec1b85ae-e186-4a91-8eb3-ce55f2525eb5.png)
![2](https://user-images.githubusercontent.com/105349993/175392692-4e6b223a-af0e-4fc4-8845-90a65391e78a.png)

**Expected result**
The system sends the correct amount of surcharge in the message after changing the payment status to “Частково оплачено”

**User story and test case links**
E.g.: "User story #2796 
[Test case](https://jira.softserve.academy/browse/GC-2384)"

**Comment by vplvua** [comment]
These messages are generated on the back-end. Therefore, this problem should be solved by back-end developers.
