### ISSUE TITLE
[Order form. Step 2] The user cannot make an order if his registration email has special characters

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4375]
**Environment:** all.
**Reproducible:** always.
**Build found:**23.06.22

**Steps to reproduce**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/
2. Log in as a registered user with email that have special symbols (e.g. ivashkiv_t@itstep.org)
3. Select 'Київ' and click 'Продовжити'.
4. Fill 'Деталі замовлення' tab with correct data
5. Move to the 'Особисті дані' tab

**Actual result**
There is error message near email field
![image](https://user-images.githubusercontent.com/105448699/175394914-32c9b953-9467-4a29-8afa-9ffc67eab0ad.png)

**Expected result**
The special symbols are allowed in the email

**User story and test case links**
E.g.: "User story #2531

**Comment by mikhaylovamarina** [comment]
Actual result : When we enter special symbols there is error message near email field
Expected result: The special symbols are allowed in the email

**Comment by voronkooleksandr** [comment]
Wait little bit) We only will do pull request on Monday
