### ISSUE TITLE
[Change request to #2197, #2329] The notification about impossibility of paying for the order

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4380]
**Description of a Change request:**
As a user, I want to be informed about the impossibility of paying for the order if there are reasons for it so that I can proceed with an order by taking other steps to complete it.

**Reason for Change:**
The user is not informed about the reason for the impossibility of payment. There is neither notification about the problem nor redirection to the appropriate page.  The 'Оплатити' button is active but the user can not click on it.
 
**Acceptance Criteria**

**SCENARIO 1**
**GIVEN** the user wants to pay simultaneously for 2 orders
**AND** he enters one number of certificate in both cases
**WHEN** the client clicks on the 'Оплатити' button
**THEN** the user shall be redirected to the confirmation page.

1. If the payment is accepted, the user is redirected to the confirmation page with the successful status 'Ваше замовлення оплачено (№ [[Order ID]])'
2. If the payment of the order is rejected by the system the user shall be redirected to the confirmation page about failed payment status 'Упс, щось пішло не так'.
3. The confirmation page with failed payment status contains the information about the reason for the impossibility of the payment '**Сертифікат, яким Ви плануєте розрахуватись, вже був використаний/ The certificate you have entered, has already been used'** and a link 'Повернутися по оплати' that returns the user to the 'Замовлення' tab in the User's Cabinet.

**Scenario 2**
**GIVEN** the user wants to pay simultaneously for 2 orders
**AND** he wants to pay for the order by using bonuses
**WHEN** the client clicks on the 'Оплатити' button
**THEN** the user shall be redirected to the confirmation page

1.  If the payment is accepted and the user has enough bonuses on his account, he is redirected to the confirmation page with the successful status 'Ваше замовлення оплачено (№ [[Order ID]])'
2. If the payment of the order is rejected by the system the user shall be redirected to the confirmation page about failed payment status 'Упс, щось пішло не так'.
3. The confirmation page with failed payment status contains the information about the reason for the impossibility of the payment **'На Вашому бонусному рахунку недостатньо коштів для розрахунку/There aren't enough points on your bonus account' to pay for the order** and a link 'Повернутися по оплати' that returns the user to the 'Замовлення' tab in the User's Cabinet.

**Impact of Change**
#2197, #2329
**Labels to be added**
[change request: UI improvement]

Epic: [UBS Courier#2195]

**Comment by darinadobrukha** [comment]
not relevant

**Comment by darinadobrukha** [comment]
not relevant
