### ISSUE TITLE
Admin Cabinet

### ISSUE THREAD

**Issue by AnatoliiIvantsov** [ita-social-projects/GreenCity#4402]
As an admin, I want to see the list of bookmarks on my sidebar according to the priority of use, so that I can have convenient navigation.

Acceptance criterion:

1.	Tab “Orders” must be the first at the very top.
2.	Tab “Schedule” must be absent.
3.	By default, when an admin enters his cabinet, the tab “Orders” should be opened.
![image](https://user-images.githubusercontent.com/77727618/177109507-400fdd4e-7b4a-4662-965c-612e322e2e41.png)

Epic: https://github.com/ita-social-projects/GreenCity/issues/2195

**Comment by karinayakovenko** [comment]
Complete list of  bookmarks on the Admin sidebar in next order:

- "Orders"
- "Customers"
- "Certificates"
- "Employees"
- "Tariffs"
- "Notifications"
- "Settings"
- "Chat"
