### ISSUE TITLE
[API][Edit profile] The system returns 201 instead of 400 when  invalid data is entered in the 'district' and 'street' field of json

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4408]
**Environment:** all.
**Reproducible:** always.
**Build found:** 01.07.22

**Preconditions**
1.Postman is opened
2.POST greencity-user.testgreencity.ga/ownSecurity/signIn
Body:
{
"email": "хххххх",
"password": "ххххх"
}
3. User personal data is filled in

**Steps to reproduce**
1. Make method PUT greencity-ubs.testgreencity.ga/ubs/userProfile/user/update
{
"addressDto": [
{
"actual": true,
"addressComment": "string",
"city": "string",
"cityEn": "string",
"coordinates": {
"latitude": 0,
"longitude": 0
},
"district": "string",
"districtEn": "string",
"entranceNumber": "string",
"houseCorpus": "string",
"houseNumber": "string",
"id": 0,
"region": "string",
"regionEn": "string",
"street": "string",
"streetEn": "string"
}
],
"alternateEmail": "string",
"recipientName": "string",
"recipientPhone": "string",
"recipientSurname": "string"
}
2. Enter invalid data in the 'district' and 'street' (e.g. "street": "Святошинська%%@!&kjhhhhhhhhhhkk"", "district": Шевченківський$@%jjjjjjjj)

**Actual result**
System returns respons 201 (Created)
![image](https://user-images.githubusercontent.com/105448699/177209980-13e7c8b7-db5a-4203-8b35-04f20e9a29b2.png)

**Expected result**
The system should return 400 (Bad request)

**User story and test case links**
E.g.: "User story #3811

**Comment by OlegVat** [comment]
The issue can not be reproduced, probably description is incorrect.
I checked that request localy and on the live instance, validation works fine.
Please check the screenshots below:

![Screenshot 2022-08-29 130011](https://user-images.githubusercontent.com/73220885/187290982-f9569f74-c8d6-4c69-a3bb-7befc5e39581.png)

![Screenshot 2022-08-29 174054](https://user-images.githubusercontent.com/73220885/187290985-2219eaea-bb81-4f54-b798-520ac87367fc.png)
