### ISSUE TITLE
[UBS Courier. Personal Cabinet] The newly created orders are not shown in the User's Cabinet

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4412]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:** 06.07.2022

**Preconditions**

1. The user has logged as a registered user in GreenCity: https://ita-social-projects.github.io/GreenCityClient/#/
2. The user has clicked on the 'Замовити Кур'єра' button.

**Steps to reproduce**

1. Click on 'UBS кур'єр' and choose location 'Київ'.
2. Click 'Продовжити' and select the amount of packages (e.g. 'Текстильні відходи' - 1, 'Безпечні відходи' - 2) that is equaled to the minimum amount of order.
3. Сlick 'Далі' to the 'Особисті дані' step and fill in 'Ім'я', 'Прізвище', 'Мобільний телефон', 'Електронну скриньку, 'Адресу' , 'Comment'.
4. Click on the button 'Далі' and go on the 'Підтвердження' step.
5. On the 'Підтвердження' step, click on the 'Відмінити' button.
6. Click on the 'Так, зберегти' button on the pop-up 'У разі закриття Ваше замовлення буде збережене у Вашому особистому кабінеті. Чи бажаєте Ви зберегти це замовлення?'
7. On the confirmation page, click on the 'До особистого кабінету' button.

**Actual result**
The order is not available in the User's cabinet despite the fact that there was a notification about successful completion of the order in the confirmation page. Also, it is also shown on the 'Замовлення' table in the Admin's Cabinet.
https://user-images.githubusercontent.com/105351490/177490675-0400709a-5fcd-447c-b6ca-5cfa2c21cb42.mp4

**Expected result**
The order should be available in the User's Cabinet  with the 'Неоплачено' payment status for later proceedings with it.

**Postconditions**

**User story and test case links**
E.g.: "User story #3477 

**Labels to be added**
"Bug", Priority ("Blocker"), Severity ("Major"), Type ("Functional")

**Comment by AngelinaRudnitska** [comment]
Bug is not reproducible
