### ISSUE TITLE
[Change password] Wrong error message in the 'Change password' pop-up when the user try to change the password with invalid data

### ISSUE THREAD

**Issue by Trololololololololololololo** [ita-social-projects/GreenCity#4417]
Environment: All
Reproducible: always
Build found: 7.7.22

Preconditions

1. User is registered and logined in with Google.
2. Tab “Дані користувача” is opened.
3. Click the “Змінити пароль” button

Steps to reproduce
Fill in 'Введіть новий пароль' field with:
- password without char of Uppercase letter (A-Z) (e.g. "ololol_123")
- password without char of lowercase letter (a-z) (e.g. "OLOLOL_123")

Actual result
Wrong error message appears
![Image 4](https://user-images.githubusercontent.com/105349565/177774808-97027026-51be-4add-9946-35a5e587f03b.png)

Expected result
Error message appears:
“Пароль повинен містити хоча б один символ латинського алфавіту верхнього (A-Z) та нижнього регістру (a-z), число (0-9) та спеціальний символ (~!@#$%^&*()+=_-{}[]|:;”’?/<>,.).”

User story and test case links
User story https://github.com/ita-social-projects/GreenCity/issues/4276
Test case (https://jira.softserve.academy/browse/GC-2795)

Labels to be added
"Bug", Priority (high), Severity (major), Type (Functional)

**Comment by katia9261** [comment]
Fixed form change-password in task #4393

Now it works correctly
![image](https://user-images.githubusercontent.com/101433204/194905661-c85d5eb4-763d-4976-81a7-ed272f304f65.png)
