### ISSUE TITLE
[API][Edit profile] User can add more than 4 addresses and the system returns 201 created

### ISSUE THREAD

**Issue by IrynaVdovyniuk** [ita-social-projects/GreenCity#4419]
**Environment:** All
**Reproducible:** always
**Build found:** 05.07.22

**Preconditions**
1. The user is authorised.
4. Four addresses added.

**Steps to reproduce**
1. Apply the POST method by using request URL https://greencity-ubs.testgreencity.ga/ubs/save-order-address
2. Fill the request  'Body' e.g. 
{
    "addressComment": "",
    "districtEn": "Dniprovs'kyi",
    "district": "Дніпровський",
    "entranceNumber": "347",
    "houseCorpus": "4",
    "houseNumber": "24a",
    "regionEn": "Kyivs'ka oblast'",
    "region": "Київська область",
    "searchAddress": "Prospekt Lesya Kurbasa, 1, Kyiv, Ukraine"
}
3. Perform the request.

**Actual result**
Status code 201 Create and address added.

**Expected result**
Address not added.

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**

**Comment by YelyzavetaSheptytska** [comment]
When you put house number "24a" (like on the sample body) Postman returns 
    {
        "name": "houseNumber",
        "message": "must be greater than or equal to 1"
    }

When you put another house number, e.g. 2 or 5
The answer is correct (400 bad request):
{
    "message": "Number of addresses reached maximum"
}
