### ISSUE TITLE
[Sign Up page]'Last Name' field wrong validation

### ISSUE THREAD

**Issue by yariks228** [ita-social-projects/GreenCity#442]
**Steps to reproduse:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Enter more than 20 valid values in 'Last Name' field(e.g 'usajsdfdkdfsfjksnfdjklbvdo'). see #385 

**Actual result:**
'Last Name' field can containe more than 20 characters

**Expected result:**
'Last Name' field can containe maximum 20 characters

**Environment:**
Google Chrome 72.0.3626.81(64-bit), Windows 10 Pro(64-bit) 

![Снимок](https://user-images.githubusercontent.com/42251308/73574532-a1d6d300-447e-11ea-8d3c-54c88abcae64.PNG)

https://jira.softserve.academy/browse/GC-213

**Comment by lenadgit** [comment]
Some surnames contain more than 20 symbols. https://uk.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BA%D0%BE%D0%BB%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B8%D0%B9-%D0%94%D1%80%D1%83%D1%86%D1%8C%D0%BA%D0%B8%D0%B9
 Is it mandatory to set limitation for this field?

**Comment by ViktoriyaRyazhska** [comment]
see #385

**Comment by RomanDeveloperAcc** [comment]
Because of new mock-up, this bug is marked as 'done'
