### ISSUE TITLE
[API][Edit profile] Status code 201 is the wrong response got when data is updated in the personal cabinet

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4420]
**Environment:** all.
**Reproducible:** always.
**Build found:** 01.07.22

**Preconditions**
1.Postman is opened

2.POST greencity-user.testgreencity.ga/ownSecurity/signIn
Body:
{
"email": "хххххх",
"password": "ххххх"
}
3. User has data in the personal cabinet

**Steps to reproduce**
1. Make method PUT greencity-ubs.testgreencity.ga/ubs/userProfile/user/update
{
"addressDto": [
{
"actual": true,
"addressComment": "string",
"city": "string",
"cityEn": "string",
"coordinates": {
"latitude": 0,
"longitude": 0
},
"district": "string",
"districtEn": "string",
"entranceNumber": "string",
"houseCorpus": "string",
"houseNumber": "string",
"id": 0,
"region": "string",
"regionEn": "string",
"street": "string",
"streetEn": "string"
}
],
"alternateEmail": "string",
"recipientName": "string",
"recipientPhone": "string",
"recipientSurname": "string"
}
2. Edit data with valid data and send request

**Actual result**
1. Response 201 (Created) status code

**Expected result**
1. Response 204 (No Content) status code

**User story and test case links**
E.g.: "User story #3811 
[Test case](https://jira.softserve.academy/browse/100)"

**Comment by innayashna** [comment]
I am afraid, that it is not a relevant task. In this controller we return status code 200 OK (not 201 Created) that signifies that data is successfully updated. We also return not only response but updated user data. If we change response to 204 (No Content) status code then the controller should not to return anything.
