### ISSUE TITLE
[UBS. Order form] It is not possible to choose a default address

### ISSUE THREAD

**Issue by IrynaVdovyniuk** [ita-social-projects/GreenCity#4421]
**Environment:** all
**Reproducible:** always
**Build found:** 06.07.22

**Preconditions**
1. log in as a user.
2. The user is on the 'Замовити кур'єра' page.
3. All fields are filled in on the 'Деталі замовлення' page.
4. The user is on the 'Особисті дані' page.
5. The user has more than one registered address.

**Steps to reproduce**
1. Go to 'Адреса вивозу сміття'.
6. Сlick on the radio button of the required address.
**Actual result**
It is not possible to choose a default address
![def](https://user-images.githubusercontent.com/105349993/178106938-473c04de-d3f7-4168-a46d-c69fc1b88a70.png)

**Expected result**
It is possible to choose a default address

**User story and test case links**
[User story](https://jira.softserve.academy/browse/GC-2106)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by voronkooleksandr** [comment]
![image](https://user-images.githubusercontent.com/61209463/180601404-2f3f4eda-5c75-43f3-99a0-4068b2602d17.png)
![image](https://user-images.githubusercontent.com/61209463/180601406-0817ff16-8787-4258-aae2-e517363feae3.png)

Everything works! Can you record a video or write more details about how you reproducible this bug? (What location do you choose ?)

**Comment by stkh22** [comment]
Bug is reproduced

**Comment by ghost** [comment]
Bug is reproduced on Windows 10 x64, Google Chrome 113.0.5672.93

https://github.com/ita-social-projects/GreenCity/assets/130749567/8d1200c0-3581-42e6-9a41-1c77ecf31919

**Comment by katia9261** [comment]
the default address is set in the user profile cabinet, during order we just choose the needed address
