### ISSUE TITLE
[API][Notifications] Redundant status code 403 in the documentation of Swagger

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4423]
**Environment:** all.
**Reproducible:** always.
**Build found:** 08.07.22

**Preconditions**
1.Postman is opened
2.User is logged in using request POST greencity-user.testgreencity.ga/ownSecurity/signIn
Body:
{
"email": "хххххх",
"password": "ххххх"
}

**Steps to reproduce**
1. Make method GET greencity-ubs.testgreencity.ga/notifications

**Actual result**
Can get only 200 and 401 status codes performing request GET greencity-ubs.testgreencity.ga/notifications

**Expected result**
Status code 403 is described in the Swagger, but it is impossible to get

**User story and test case links**
E.g.: "User story #2796

**Comment by TaniaQC** [comment]
![Uploading image.png…]()
