### ISSUE TITLE
[UBS. Admin. Violation] The file with invalid format is displayed in the 3x2 photo matrix after uploading using the "Завантажити фото з пристрою" button. 

### ISSUE THREAD

**Issue by AntonHusiev** [ita-social-projects/GreenCity#4450]
**Environment:** Windows 7 x64, Chrome 103.0.5060.114
**Reproducible:** always
**Build found:** 20.07.2022

**Preconditions**
1. The user is logged in as an administrator - https://www.testgreencity.ga/GreenCityClient/#/ubs
2. The order page is opened - https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders

**Steps to reproduce**
1. Click the order number from the order table.
2. Click the "Додати порушення" button.
3. Click the "Завантажити фото з пристрою" button and select the file with an invalid format and valid size (<10MB).

**Actual result**
The file with an invalid format is displayed in the 3x2 photo matrix.
[actual result - screen](http://joxi.ru/1A5KEwPc4NV68m)
[actual result - video](https://user-images.githubusercontent.com/109277724/179996649-07ad9c4b-3241-43e7-bdc3-ff98c891ea32.mp4)

**Expected result**
The warning message is displayed: “Неправильний формат файлу. Будь ласка, виберіть інший файл”.
[mock-up - error message](http://joxi.ru/bmoEyN4UOKDnkA)

**User story and test case links**
E.g.: "User story #2863
[Test case](https://jira.softserve.academy/browse/GC-3111)

**Comment by ViktoriyaRyazhska** [comment]
not a bug according to the latest mockups
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=15642%3A92142
