### ISSUE TITLE
[UBS Admin Violation] The system extracts the current date from the device but not from the server

### ISSUE THREAD

**Issue by NataliaHarasym** [ita-social-projects/GreenCity#4458]
**Environment:** MacOS Version 12.4 Google Chrome 103.0.5060.114
**Reproducible:** always
**Build found:** 21.07.2022

**Preconditions**

1. User is logged in as administrator https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Administrator has opened an order from current orders view table

**Steps to reproduce**
1. Click the button "Додати порушення" and  check the date in the "Дата" field
3. Click on the button “Скасувати” on the pop-up
4. Change the date on the device (ex. 15.07.2022)
5. Click the button "Додати порушення" and check the date in the "Дата" field agin

**Actual result**
The non-current date is displayed in the pop-up if the administrator has changed the date on the device

**Expected result**
Administrator cannot change data on the pop-up

**User story and test case links**
E.g.: "User story #2861 
[Test case](https://jira.softserve.academy/browse/GC-3187#)"

**Comment by vplvua** [comment]
@NataliaHarasym We discussed this situation with PM and technical expert. This is the correct behavior of displaying the date. The consequences of changing the date are the responsibility of the administrator who does it. The correct date of the violation will be  assigned on the backend, after the violation is saved.
