### ISSUE TITLE
[User] User isn't registered after filling all required fields for registration

### ISSUE THREAD

**Issue by nseniuk** [ita-social-projects/GreenCity#446]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on Sign up link.
3. Leave unrequired Last Name field empty.
4. Fill all other fields with valid data.
5. Click on Sign up button.

**Actual result:**
User not created; Sign up button displays loading circle that keep spinning.

**Expected result:**
New user successfully registered in the system.

**_Environment:_** Google Chrome 79.0.3945.79 (64-bit) + Windows 10 Home (64 bit)
https://jira.softserve.academy/browse/GC-203
https://jira.softserve.academy/browse/GC-184
https://github.com/ita-social-projects/GreenCity/issues/385

**Comment by lenadgit** [comment]
it was fixed earliest 
Result after creating the new user is provided by link below
http://i.piccy.info/i9/5720fc740ea8a500495c871414741f4a/1582057722/115683/1362948/ready_auth.jpg
