### ISSUE TITLE
[Event] Unauthorized user is redirected to create event page by clicking on URL.

### ISSUE THREAD

**Issue by Sofiia-Sharun** [ita-social-projects/GreenCity#4466]
**Environment:** macOS Monterey 12.4
Safari 15.5
**Reproducible:** always.
**Build found:** 22.07.22

**Preconditions**
The user is not logged in as a registered user
**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/events/create-event

**Actual result**
Edit\Create page is open

**Expected result**
 "You need to be authorized to edit an event" error message is displayed.

**User story and test case links**
E.g.: "User story #3195, #3193
[Test case1](https://jira.softserve.academy/browse/GC-3194)
[Test case2](https://jira.softserve.academy/browse/GC-3133)"

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: major"), Type ("Functional").

**Comment by YelyzavetaSheptytska** [comment]
Edit\Create page is still opened for not logged in user. MacOs 10.10.5 Chrome Version 87.0.4280.141

**Comment by katia9261** [comment]
@YelyzavetaSheptytska task required to display an error-message, it not required to close the page and navigate somewhere else
