### ISSUE TITLE
[Home page] The unregistered user sees popup with "Log in" form instead of "Registration form" after clicking on the “My cabinet” button

### ISSUE THREAD

**Issue by ingakuh** [ita-social-projects/GreenCity#447]
**Pre-condition:**
Open a new private window in your browser. 
Steps to reproduce:
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'My cabinet' button 

**Actual result:** The unregistered user sees the popup with "Log in" form

**Expected result**: The unregistered user sees the popup with "Registration form" after clicking on the “My cabinet” button
**Environment**: Firefox Brower 72.0.2 (64-bit), Windows Server 2012 R2 Standard
https://jira.softserve.academy/browse/GC-200
https://github.com/ita-social-projects/GreenCity/issues/385
https://jira.softserve.academy/browse/GC-184

**Comment by lenadgit** [comment]
Must be Login instead of Registration form. This decision was approved by Viktoriya Ryazhska
