### ISSUE TITLE
[Eco news] The 'Eco news' tab is not highlighted in the header when the user navigates to the 'Eco news' page from the footer or clicking 'Read all news' button

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4475]
**Environment:** all).
**Reproducible:** always.
**Build found:** 26.07.22

**Preconditions**
1. The GreenCity: https://www.testgreencity.ga/GreenCityClient/#/ is opened.

**Steps to reproduce**
Scenarion#1:
1. Scroll down to the footer of the page
2. Click on the "Eco-news" link in the footer
Scenarion#2
1. Scroll down to the 'Eco news' section
2. Click on the "Read all news" button

**Actual result**
The 'Eco news' tab is not highlighted in green in the header
![Знімок екрана 2022-07-26 183747](https://user-images.githubusercontent.com/105448699/181049400-d7181efd-5e2f-4c5f-86ae-ecb41ae449a3.png)

**Expected result**
The 'Eco news' tab is highlighted in green #13AA57 in the header

**User story and test case links**
"User story #461

**Comment by OlhaKyrylenko** [comment]
Actual result is steal:
The 'Eco news' tab is not highlighted in green in the header
