### ISSUE TITLE
[Eco news. Home page] Date is translated only after updating the Home page of the Green City

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4478]
**Environment:** all.
**Reproducible:** always.
**Build found:** 26.07.22

**Preconditions**
1. The Green City: https://www.testgreencity.ga/GreenCityClient/#/ is opened

**Steps to reproduce**
1. Scroll down to the 'Еко новини' informational section
3. Change the language of the page (e.g. En) 

**Actual result**
The date is not translated. Only after updating the page.
[Translate.webm](https://user-images.githubusercontent.com/105448699/181088842-4cc4ffab-5606-46dd-95db-a57351a12404.webm)

**Expected result**
The date is translated into the selected language.

**User story and test case links**
E.g.: "User story #351
[Test case](https://jira.softserve.academy/browse/GC-690)"

**Comment by vplvua** [comment]
Not reproduce.

It seems that the problem has already been solved. Now when changing the language, the date translation changes without reloading the page.
