### ISSUE TITLE
[Eco news] The 'Read more' button does not redirect to the Single view of the particular news from the Home page, only after visiting the 'Eco news' page

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4479]
**Environment:** all.
**Reproducible:** always.
**Build found:** 26.07.22

**Preconditions**
1. The Green City: https://www.testgreencity.ga/GreenCityClient/#/ is opened

**Steps to reproduce**
1. Scroll down to the 'Еко новини' informational section
2. Click on the 'Read more' button

**Actual result**
The user is not redirected to a single view of the news. The page is empty
[read more .webm](https://user-images.githubusercontent.com/105448699/181095629-493dfbde-9419-439f-a26e-571c3781478e.webm)
Only after visiting the 'Eco news' page, the user is redirected to the single view of the particular news using the 'Read more' button 

**Expected result**
The user is redirected to a single view of the particular news

**User story and test case links**
E.g.: "User story #351
[Test case](https://jira.softserve.academy/browse/GC-712)"

**Comment by atsa21** [comment]
Duplicate #4638
