### ISSUE TITLE
[Event dashboard] 'Join Event' button is shown for unauthorized user. 

### ISSUE THREAD

**Issue by MariaSko** [ita-social-projects/GreenCity#4482]
**Environment:** Windows v. 10 Pro 21H2; Google Chrome v. 103.0.5060.114).
**Reproducible:** always.
**Build found:** 20.07.2022

**Steps to reproduce**
Open https://ita-social-projects.github.io/GreenCityClient/#/events as an unauthorized User.

**Actual result**
'Join Event' button is shown

**Expected result**
'Join Event' button is not shown

**User story and test case links**
 "User story #3197 
[Test case](https://jira.softserve.academy/browse/GC-3120)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by dmytro-kryvyi** [comment]
According to the fifth point of User story #3197 join event button should be visible for unauthorized users
