### ISSUE TITLE
[UBS. Admin. History] The "Статус замовлення - Скасовано" event is not shown in the "Історія замовлення" order work log after changing the status from "Сформовано" to "Скасовано"

### ISSUE THREAD

**Issue by AntonHusiev** [ita-social-projects/GreenCity#4491]
**Environment:** Windows 7 x64, Chrome 103.0.5060.134
**Reproducible:** always
**Build found:** 28.07.2022

**Preconditions**
1. The user is logged in as an administrator - https://www.testgreencity.ga/GreenCityClient/#/ubs
2. The order is created in the system
3. The current order is assigned the "Сформовано" order status
4. The page with details of the current order is opened

**Steps to reproduce**
1. Click the "Статус замовлення" dropdown list and select the "Скасовано" order status
2. Select the cancel reason in the "Додати причину скасування замовлення" radio button
3. Click the "Додати" button
4. Click the "Зберегти" button and refresh the page
5. Scroll down to the "Історія замовлення" section and expand it

**Actual result**
The "Статус замовлення - Скасовано" event is not shown.
[screenshot](http://joxi.ru/Q2KzkXNHOYLYNm)

**Expected result**
The "Статус замовлення - Скасовано" event is displayed.

**Additional information**
This defect is reproduced also when changing the status from "Не вивезли " to "Скасовано" [test case GC-3345](https://jira.softserve.academy/browse/GC-3345)

**User story and test case links**
User story #3217
[Test case GC-3351](https://jira.softserve.academy/browse/GC-3351)

**Comment by Olena-Kharkova** [comment]
https://user-images.githubusercontent.com/110603507/210074121-b58be7ce-8b52-497e-bf01-d2994dd636ca.mp4

After changing status from "Сформовано" to  "Скасовано" result of changing is not logged
