### ISSUE TITLE
[UBS Admin History]When the order which was paid using bonuses is canceled than the valid event title is not displayed.

### ISSUE THREAD

**Issue by YakymetsHub** [ita-social-projects/GreenCity#4495]
**Environment:** Chrome 103.0.5060.134 (64-розрядна версія)Windows 11 Home
**Reproducible:** always.
**Build found:** 28.07.2022

**Preconditions**
The user is logged in as the administrator.
The order is created in the system.
The order is paid using bonuses only.
The order details page for the current order is opened.

**Steps to reproduce**
1. Click the "Статус замовлення" dropdown list and select the "Скасовано" item.
2. Select the cancel reason and click the "Додати" button.
3. Scroll down and click the "Зберегти" button.
4. Click the "refresh page" button in the browser.
5. Scroll down and open the "Історія замовлення" section.

**Actual result**
The "Використані бонуси повернено на бонусний рахунок клієнта" message is not shown in the order work log "Історія замовлення.

**Expected result**
The "Використані бонуси повернено на бонусний рахунок клієнта" message is shown  in the order work log "Історія замовлення.

**User story and test case links**
E.g.: "User story #3217
[Test case GC-3292](https://jira.softserve.academy/browse/GC-3292)"

**Comment by Olena-Kharkova** [comment]
Please, consider this issue again. No logging about bonuses returning in the Order history logs
Example: Order 1041 
![yXqeyBvuSb](https://user-images.githubusercontent.com/110603507/222971379-c22d1dd3-a7ad-42a3-84aa-717c4fdd79b4.png)

https://user-images.githubusercontent.com/110603507/222971409-fa3baf7c-3500-4814-bcdb-01da7eb60e8e.mp4

According to the US #2900 AC 3 "When the administrator clicks “Зберегти”, the system should check the amount of confirmed bonuses “Використані бонуси” (column Підтверджена к-сть) and if it is greater than 0, add this amount to the client’s bonus account"

**Comment by jpgcz** [comment]
> 

I made new changes fixing this, thank you
