### ISSUE TITLE
[My habits] Error message "You don't have authorities." is displayed when you open habit page as autorized user.

### ISSUE THREAD

**Issue by OnzaRain** [ita-social-projects/GreenCity#4497]
**Environment:** macOS Monterey 12.4
Safari 15.5
**Reproducible:** always.
**Build found:** 28.07.2022

**Preconditions**

1. Sign in as an authorized user on Green City Project.
2. At least one habit was added to the "My habits" list.
3. The "My space" page is open. 

**Steps to reproduce**
1. Click on the edit link on the habit card.

**Actual result**
The "You don't have authorities." error message is displayed.

**Expected result**
No error messages are displayed.

**User story and test case links**
User story #[990](https://github.com/ita-social-projects/GreenCity/issues/990)
[Test case](https://jira.softserve.academy/browse/GC-3246)

**Labels to be added**
"Bug", "pri: low", "severity: trivial", "UI".

**Comment by atsa21** [comment]
Not reproduce
