### ISSUE TITLE
[My habit] User unable to mark habit as done from "My space" page, "My habits" tab.

### ISSUE THREAD

**Issue by OnzaRain** [ita-social-projects/GreenCity#4498]
**Environment:** macOS Monterey 12.4
Safari 15.5
**Reproducible:** always.
**Build found:** 28.07.2022

**Preconditions**
1. Be an Authorized User.
2. Open the "My space" page
3. Open the "My Habits" tab.

**Steps to reproduce**
1. Click on the "Mark as done" button.

**Actual result**
The "Wrong date. Should be 'LocalDate'" error message is displayed and the "Mark as done" button isn't clickable anymore.

**Expected result**
The system marks the habit as done on the current day only and it is replaced by a green button “Done”.

**User story and test case links**
E.g.: "User story #[990](https://github.com/ita-social-projects/GreenCity/issues/990)
Test cases #[3247](https://jira.softserve.academy/browse/GC-3247), #[3248](https://jira.softserve.academy/browse/GC-3248), #[3249](https://jira.softserve.academy/browse/GC-3249), #[3250](https://jira.softserve.academy/browse/GC-3250).

**Labels to be added**
"Bug", "My habits", "pri: medium ", "severity:major", "Functional".

**Comment by atsa21** [comment]
Duplication #4499
