### ISSUE TITLE
[UBS Admin Violation] UI inconsistency in the pop-up with details of related violation record

### ISSUE THREAD

**Issue by NataliaHarasym** [ita-social-projects/GreenCity#4505]
**Environment:** MacOS Version 12.4 Google Chrome 103.0.5060.114
**Reproducible:** always
**Build found:** 31.07.2022

**Preconditions**

1. User is logged in as administrator https://www.testgreencity.ga/GreenCityClient/#/ubs
2. There is at least one order created in the system
3. Administrator has opened an order from current orders view table
4. The violation has already been added to the current order
5. Figma`s mockup is opened - https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=18992%3A96252

**Steps to reproduce**

1. Clicks on “1” in the field “Поточне замовлення”
2. Verify UI control's alignment, spelling, font, size, color
3. Verify that all required elements are present on the page (corresponds to mock-up)

**Actual result**

1. The writing on the "Редагувати" button is purple (#5539BB)

<img width="118" alt="Screenshot 2022-07-31 at 18 59 33" src="https://user-images.githubusercontent.com/109278030/182034921-8c99098d-4354-447a-b276-23a4950411cf.png">

2. The writing on the "Завантажити фото з пристрою" button is purple (#5539BB)

<img width="221" alt="Screenshot 2022-08-01 at 00 15 47" src="https://user-images.githubusercontent.com/109278030/182045641-28dbbb51-8eae-4953-8de7-0c3fcc68566b.png">

3. The labels of the following fields differ from the mockup: "Оберіть ступінь порушення", "Фото порушення"

4. White color of the button with a black writing "Cкасувати".  
    Black button border
    Font: Lato;
    font-style: normal;
    height: 18px;
    width: 97px;
    left: 4px;
    top: 8px;

5. Gray color (#E3E6E8) of the button with a gray (#CACFD3) writing "Зберегти".  
    Font: Lato;
    font-style: normal;
    height: 18px;
    width: 159px;
    left: 4px;
    top: 8px;

<img width="306" alt="Screenshot 2022-08-01 at 01 23 18" src="https://user-images.githubusercontent.com/109278030/182047646-4d3cb5b9-7ca2-40b4-9738-57eaeb2efe5d.png">
6. Checkbox that is not selected has a colored background and a black writing

<img width="132" alt="Screenshot 2022-08-01 at 01 28 07" src="https://user-images.githubusercontent.com/109278030/182047777-5ae9dd79-d022-46d3-8a13-1febc1dae083.png">
7. The selected checkbox is gray
 
<img width="20" alt="Screenshot 2022-08-01 at 09 03 18" src="https://user-images.githubusercontent.com/109278030/182082420-4cd0bf0a-795c-43f7-a80d-bc824e56822b.png">
8. Incorrect alignment of elements: "Легке", "Серйозне" checkboxes and "Завантажити фото з пристрою" field

<img width="310" alt="Screenshot 2022-08-01" src="https://user-images.githubusercontent.com/109278030/182083789-6e033b78-6288-49ac-88a8-096ed261f41a.jpg">

**Expected result**
1. The writing on the "Редагувати" button is green (#13AA57)

<img width="126" alt="Screenshot 2022-08-01 at 09 28 53" src="https://user-images.githubusercontent.com/109278030/182085844-1c876e54-ebf7-46d9-b14e-b193a0ce64e9.png">
2. The writing on the "Завантажити фото з пристрою" button is light green (#B3E6C9) 

<img width="271" alt="Screenshot 2022-08-01 at 09 30 46" src="https://user-images.githubusercontent.com/109278030/182086114-97a08e4d-a413-4979-82dc-5723e8c52dea.png">
3. All labels of the fields are as in the Mock-up

<img width="359" alt="Screenshot 2022-08-01 at 09 41 03" src="https://user-images.githubusercontent.com/109278030/182088295-fe720c37-7e1c-4f53-b251-bd008cb52636.png">
4. White (#FFFFFF) color of the button with a green (#13AA57) writing "Cкасувати".  
    Green button border (#13AA57)
    Font: Lato;
    font-style: normal;
    height: 24px;
    width: 78px;
    left: 24px;
    top: 8px;

<img width="107" alt="Screenshot 2022-08-01 at 10 00 41" src="https://user-images.githubusercontent.com/109278030/182090976-f8c7b247-564b-4cee-bc3f-e7100df30bf9.png">
5. Light-Green color (#B3E6C9) of the button with a white (#FFFFFF) writing "Зберегти".  
    Font: Lato;
    font-style: normal;
    height: 24px;
    width: 78px;
    left: 24px;
    top: 8px;

<img width="103" alt="Screenshot 2022-08-01 at 10 00 32" src="https://user-images.githubusercontent.com/109278030/182091025-c6eaf6f0-ae5d-4bc0-b84e-a34ced052857.png">
6. Checkbox that is not selected has no background and the label is gray (#9CA7B0)

<img width="184" alt="Screenshot 2022-08-01 at 10 07 41" src="https://user-images.githubusercontent.com/109278030/182092111-700b8245-17b7-4dc1-9611-ef4e8847fe1b.png">
7. The selected checkbox is green (#13AA57)
 
<img width="28" alt="Screenshot 2022-08-01 at 10 10 16" src="https://user-images.githubusercontent.com/109278030/182092537-9989f55a-b475-4f02-8494-7e0e9466a897.png">
8. Fields "Порушення", "Ступінь порушення", "Деталі порушення", "Фотографії  порушення", "Завантажити фото з пристрою" have the same alignment

<img width="494" alt="Screenshot 2022-08-01 at 10 12 34" src="https://user-images.githubusercontent.com/109278030/182094174-0ce7bc70-5eec-4f4d-adf8-e8b93327542f.png">

**User story and test case links**
E.g.: "User story #2862
[Test case](https://jira.softserve.academy/browse/GC-3117)"

**Comment by NewArtMask** [comment]
The highlighting is correct and corresponds to the existing mockups:
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=15642%3A92142

Give a link to new mockups, please, if there are any, or close this issue.
