### ISSUE TITLE
[Eco news. List view] The List view of echo news for extension 576 is not according mock-up of Figma

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4511]
**Environment:**  for mobile devices.
**Reproducible:** always.
**Build found:** 02.08.22

**Preconditions**
1. The https://www.testgreencity.ga/GreenCityClient/#/ is opened on the device with extension 576
1. User is logged in in the GreenCity
2. Eco news page is opened  
3. Figma is opened https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12671%3A10190

**Steps to reproduce**
1. Click on the View as a List option on the right side of the page

**Actual result**
The eco news has images and Text 
![image](https://user-images.githubusercontent.com/105448699/182465870-096ebce8-47e6-47b5-a49a-85f1b1b6a908.png)

**Expected result**
The eco news has only Title without image and Text
![image](https://user-images.githubusercontent.com/105448699/182466133-10f601b3-dab4-4328-9bc5-6d8d305e0bef.png)

**User story and test case links**
E.g.: "User story #595
https://jira.softserve.academy/browse/GC-720

**Comment by atsa21** [comment]
Not a bug
