### ISSUE TITLE
[Personal cabinet. Orders view table] The orders aren't displayed in the ascending way after turning the page on the 'Orders' tab'

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4519]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:** 04.08.2022

**Preconditions**

1. The user is logged in to GreenCity as a User [https://ita-social-projects.github.io/GreenCityClient/#](https://ita-social-projects.github.io/GreenCityClient/)
2. The 'Замовлення' tab is opened in the personal cabinet.
3. The 'Поточні замовлення' tab is opened on the 'Замовлення' page.

**Steps to reproduce**
1. Verify that the orders are displayed in an ascending way from the newest one to the oldest after turning the page.

**Actual result**
When the 'Замовлення' tab is opened for the first time, the orders are displayed in an ascending way. But, after turning the page forward and back again, the orders have been mixed.

https://user-images.githubusercontent.com/105351490/182822105-406bd11c-6da4-44cf-8ea1-44db0d374942.mp4

**Expected result**
The orders should be displayed in an ascending way, from the newest to the oldest one regardless of turning the page

**User story and test case links**
E.g.: "User story #3477 

**Labels to be added**
"Bug", Priority ("High"), Severity ("Minor"), Type ("Functional")

**Comment by zaitsev-oleksii** [comment]
Not reproducible, pagination has been changed to infinite scroll, everything is displayed correctly.
Related issue: https://github.com/ita-social-projects/GreenCity/issues/4306

**Comment by JoseCaste** [comment]
Hi, with edge and chrome is working fine, Could you test it again, please?
![image](https://user-images.githubusercontent.com/70968629/217314677-8a1c10e6-0555-49fe-b7f0-bb7b9ba51f33.png)

**Comment by JoseCaste** [comment]
![image](https://user-images.githubusercontent.com/70968629/217314801-b14d0ead-ee13-4eae-adbb-8ce982ad5851.png)
