### ISSUE TITLE
Change request to US #2796 “Send notifications to users” 

### ISSUE THREAD

**Issue by schIRIS** [ita-social-projects/GreenCity#4520]
**Description of a Change request:**
Adding new notifications about violations status of the orders.

**Reason for Change:**
Clarification of business rules.

**Acceptance Criteria**
1. All auto notifications from the US #2796 should be duplicated in English if the User sets English as a language for communication.

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-e0e82f8f-7fff-2a3a-c89f-7705cfd48477"><div dir="ltr" style="margin-left:-23.25pt;" align="left">

Message | Content
-- | --
Unpaid order | Title: “Unpaid order”<br> Body: “Hello! You recently submitted a request to order our "UBS Courier" service, but we have not received confirmation of payment. Maybe you have some difficulties? If you have any questions, I will be happy to answer them! Chat with the manager t.me/nowaste_service_bot or e-mail hello@nowaste.org.ua”
Order is paid | Title: The payment was successful<br> Body: ”Congratulations! You have successfully ordered and paid for the "UBS Courier" service! UBS Courier will pick up your packages within 2-9 days from the date of payment for the service. When the route is formed, we will definitely contact you to agree on the details. If you have any questions, I will be happy to answer them! Chat with the manager t.me/nowaste_service_bot or e-mail hello@nowaste.org.ua”
Courier itinerary formed | Title: The courier's route is formed<br> Body: “Hello! We created the UBS Courier route. Our Courier will be with you tomorrow, XX Month. Working hours of the Courier: from XX:XX to XX:XX. Please stay connected and put your phone on loud during this time. The courier will call you in advance and when he arrives. If you will not be able to be there at the agreed time, you can leave your packages at the concierge, but be sure to notify the Courier or the managers! The Courier's number is +380638175035 or +380931038987. If you have any questions, I will be happy to answer them! Chat with the manager t.me/nowaste_service_bot or  e-mail hello@nowaste.org.ua
Unpaid package | Title: Pay for the change to the ordered<br> Body: “ Congratulations! You have made changes to order No. XXXXX. We ask you to pay XXX UAH. Pay: ("Pay" button). If you have any questions, I will be happy to answer them! Chat with the manager t.me/nowaste_service_bot or e-mail”
Accrued bonuses to account | Title: Bonuses have been accrued.<br> Body: “Hello! Today UBS Courier picked up packages from you: XXX. And you paid: XXX. Therefore, we fix a deposit for you for the next export in the amount of UAH XXX. Have a good day!”
Violation the rules | Title: Violation the rules<br> Body: Hello! Sorry, but in your packages were found: xxxxxx. This is waste that we do not accept. Please review our sorting rules again: https://bit.ly/2Q2esLB We do NOT accept: - batteries, accumulators, mercury-containing (fluorescent) lamps and thermometers; - medicines and pharmaceutical waste (masks, gloves, syringes), as well as everything that came into contact with body fluids (blood, urine, saliva, secretions); - used means of personal hygiene and contraception (diapers, pads, tampons, condoms, etc.); - printer cartridges; - construction waste, varnishes, paints, plasticine; - cigarette butts/sticks from electronic smoking accessories; - gas cylinders, lighters, explosive objects (shells, shells, etc.); - ceramics; - sharp and cutting objects. Thank you for understanding!
Let's stay connected | Title: Let's stay connected<br> Body: We noticed that you have not used the "UBS Courier" service for [month amount] months. Maybe you went on a long trip, or maybe something went wrong with the collection of plastics. Please share this with us so we can understand if and how we can help.

</div></b>
</body>
</html>

2. Adding the list of auto notification  - sent by the system automatically in response to violation
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-641ba24f-7fff-1c49-c450-d2de3fd8de00"><div dir="ltr" style="margin-left:-24.75pt;" align="left">

Message | Requirements | Content | Comment
-- | -- | -- | --
Canceled  violation the rules by the manager | Trigger: Manager canceled the violation order status<br> The System sends message after the manager canceled violation to order “Виявлено порушення”. <br> List of the violations deleted from the order form<br> Photos of the violations deleted from the order form | to communicate in Ukrainian:Title: “Відміна порушення правил сортування”<br>  Body: “Вітаю <User name>! У вашому замовленні було відмінено порушення правил сортування після спілкування з менеджером. Дякуємо, що сортуєте з нами. Гарного дня.<br> <br> to communicate in English:<br> Title: "Cancellation of violation of sorting rules"<br>  Body: “Hello <User name>! Your order has had a sorting violation canceled after speaking with a manager. Thank you for your cooperation with us. Have a good day. |  
Changed rule violation status | Trigger: Manager changed the violation order statusThe System sends message after the manager edited violation to order “Виявлено порушення”.List of the violations edited in the order formPhotos of the violations edited in the order form | to communicate in Ukrainian: <br> Title: “Зміни в порушеннях правил сортування”<br>  Body: Вітаю \<User name\>! У вашому замовленні \<Order number\> було внесено зміни в інформацію про порушення правил сортування після спілкування з менеджером. Передивіться, будь ласка, зміни в замовленні   \<link order\>.Дякуємо, що сортуєте разом з нами. Гарного дня.”<br> <br> to communicate in English: <br> Title:"Changes in violations of sorting rules"<br> Body:  “‘Hello \<User name\>. Your order \<Order number\> has had its sorting violation information changed after speaking with the manager. Please see the changes in the order \<link order\>.Thank you for sorting with us. Have a good day.” |  

</div></b>
</body>
</html>

Impact of Change
This change request affects 1 existing user story:
[#](https://github.com/ita-social-projects/GreenCity/issues/2199)2796

Epic: #2195

**Comment by ToriForH** [comment]
Notifications listed in issue have been implemented already.
