### ISSUE TITLE
[Pricing page. Tariffs] The suggestions  for the dropdowns on the 'Tariffs' panel are not localized into English

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4525]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:**10.08.2021

**Preconditions**

1. The user is logged in as Admin.
2. Tariffs panel is opened: https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
3. EN locale is set for the page

**Steps to reproduce**

1. Verify that the suggestions for the dropdowns on the 'Tariffs' panel are localized into English the way it is with labels and placeholders of the dropdowns.

**Actual result**
When the EN locale is set for the page the labels of the dropdowns and their palceholders are translated into English but the suggestions for the dropdowns are in Ukrainian.

https://user-images.githubusercontent.com/105351490/183845979-023f914a-be0c-443b-814b-a83da1493bbc.mp4

**Expected result**
When the EN locale is set for the page the labels of the dropdowns , their placeholders and suggestions for the dropdowns should be translated into English.

**User story and test case links**
E.g.: "User story #3835 

**Labels to be added**
"Bug", Priority ("High"), Severity ("Major), Type ("Functional")

**Comment by YelyzavetaSheptytska** [comment]
Receiving station dropdown list and the table below are still not localized into English

**Comment by atsa21** [comment]
Not reproduce
