### ISSUE TITLE
[Eco news. Create news] Tags are not translated by Russian localization

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4533]
**Environment:** all.
**Reproducible:** always.
**Build found:** 14.08.22

**Preconditions**
1. User is registered on the Green City https://www.testgreencity.ga/GreenCityClient/#/
2. The Eco news page is opened
3. 'Create news' page is opened

**Steps to reproduce**
1. Select the Russian language for the Interface.

**Actual result**
The tags are not translated into the Russian language
![locallization ru 2022-08-10 202717](https://user-images.githubusercontent.com/105448699/184551491-0037bd16-3d17-4268-81a7-2a71581abfaf.png)

**Expected result**
The tags should be translated into the Russian language

**User story and test case links**
E.g.: "User story #505
[Test case](https://jira.softserve.academy/browse/GC-586)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by atsa21** [comment]
It is not relevant
