### ISSUE TITLE
[Eco news. Create news] The tags are displayed incorrect when user clicks 'Preview' button on the Edit news page with Ukrainian and Russian localization

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4535]
**Environment:** all.
**Reproducible:** sometimes.
**Build found:** 14.08.22

**Preconditions**
1. User is registered on the Green City https://www.testgreencity.ga/GreenCityClient/#/
2. The Eco news page is opened
3. User has created at least one news

**Steps to reproduce**
1. Click on the earlier created user`s news
2. Click 'Edit news' button
3. Change language of the Interface on the Ukrainian or Russian
4. Click 'Preview' button
5. Pay attantion on the tags

**Actual result**
![tag ru 2022-08-10 203202](https://user-images.githubusercontent.com/105448699/184553205-7fe03ad1-3901-4931-a389-6a42c57e6f68.png)

![image](https://user-images.githubusercontent.com/105448699/184552920-612bc6d9-38a5-4931-b778-512a53f00cd0.png)

**Expected result**
Tags should be translated into Ukrainian or Russian

**User story and test case links**
E.g.: "User story #660
[Test case](https://jira.softserve.academy/browse/100)"

**Comment by atsa21** [comment]
not reproduce
