### ISSUE TITLE
[Eco news. Create news] The image is cropped and compressed during news creation

### ISSUE THREAD

**Issue by TaniaIvashkiv** [ita-social-projects/GreenCity#4536]
**Environment:** all.
**Reproducible:**  sometimes.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
1. User is registered on the Green City https://www.testgreencity.ga/GreenCityClient/#/
2. The Eco news page is opened
3. 'Create news' page is opened

**Steps to reproduce**
1. Enter valid data in the 'Title' field (e.g. "Hello world")
2. Select tag (e.g. "News")
3. Enter the valid data in the 'Content' field
4. Download the image (e.g. size  529*550)

**Actual result**
The image is cropped and compressed
![cropped](https://user-images.githubusercontent.com/105448699/184554073-5b6312df-8cf6-491b-a3c0-2405dcb1ee9a.png)

![image](https://user-images.githubusercontent.com/105448699/184554065-51faca30-6ca4-4098-9efb-33af9852c4d3.png)

**Expected result**
Image is displayed without changes in it's size. The image is not cropped and compressed

**User story and test case links**
E.g.: "User story #525

**Comment by vplvua** [comment]
@TaniaIvashkiv Could you please check again. Either the problem is already solved or I don't understand what the problem is.
