### ISSUE TITLE
[Pricing page. Tariffs]  The error message 'Not found' is absent when the Admin types in a non-existent region

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4537]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:** 15.08.2022

**Preconditions**

1. The user is logged in as Admin.
2.  Tariffs panel is opened: https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs

**Steps to reproduce**
1. Verify that the region is non-existent with the following query: 
SELECT * FROM [table] 
WHERE region LIKE ‘Римська’
2. Click on the 'Область' dropdown.
3. Type  the non- existent region from step 1 into the 'Область' field.

**Actual result**
The error message 'Не знайдено' is absent when the Admin enters the non-existent name of the region.
 
![зображення](https://user-images.githubusercontent.com/105351490/184614726-053b41f3-0e81-468c-8eaf-e1668c638182.png)

**Expected result** 
 The error message ' Не знайдено' should appear when the Admin enter the non-existent name of the region

**User story and test case links**
E.g.: "User story #3835 
[GC-3379](https://jira.softserve.academy/browse/GC-3379)

**Labels to be added**
"Bug", Priority ("High"), Severity ("Major"), Type ("Functional")

**Comment by ViktoriyaRyazhska** [comment]
According to story #3835 this bug is not relevant
