### ISSUE TITLE
[Pricing page. Tariffs] The 'Область' dropdown suggestions are not cleared after pressing the cross button

### ISSUE THREAD

**Issue by TaniaQC** [ita-social-projects/GreenCity#4538]
**Environment:** Windows 10 Enterprise 21H2, Microsoft Edge 101.0.1210.39
**Reproducible:** always
**Build found:** 15.08.2022

**Preconditions**

1. The user is logged in as Admin.
2. Tariffs panel is opened: https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs

**Steps to reproduce**
1. Click on the 'Область' dropdown
2. Select the 'Київська область' from the dropdown list.
3. Verify that all search results with this region appear
4. Press the cross button in the 'Область' field

**Actual result**
After pressing the cross button in the 'Область' field, the search results with this region don't disappear

https://user-images.githubusercontent.com/105351490/184616474-8e0f56bf-d7c0-4bc9-8fee-d7d2ddaf7c29.mp4

**Expected result**
The search results should disappear after pressing the cross button

**User story and test case links**
E.g.: "User story #3835 
[GC-3381](https://jira.softserve.academy/browse/GC-3381)"

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Minor"), Type ("Functional")

**Comment by atsa21** [comment]
not reproduce
