### ISSUE TITLE
[API] [Client-controller] if send Get https://greencity-ubs.testgreencity.ga/ubs/client/get-data-for-order-surcharge/{id} it return response 500 status code

### ISSUE THREAD

**Issue by YakymetsHub** [ita-social-projects/GreenCity#4539]
**Environment:**Chrome 103.0.5060.134 (64-розрядна версія)Windows 11 Home
**Reproducible:** always.
**Build found:** 15.08.2022

**Preconditions**
User is authorized.
User has at least one order.

**Steps to reproduce**
Send Get by using request
https://greencity-ubs.testgreencity.ga/ubs/client/get-data-for-order-surcharge/{id}

**Actual result**
<html><body><h2>Error Page</h2><div>Status code: <b>500</b></div><div>Exception Message: <b>Request processing failed; nested exception is javax.persistence.EntityNotFoundException: Employee with current id doesn't exist: </b></div><body></html>

**Expected result**
1. Status Code 200 Ok
2. Body responce:
{
  "addressComment": "string",
  "addressExportDetailsDto": {
    "addressCity": "string",
    "addressDistrict": "string",
    "addressEntranceNumber": "string",
    "addressHouseCorpus": "string",
    "addressHouseNumber": "string",
    "addressId": 0,
    "addressRegion": "string",
    "addressStreet": "string"
  },
  "amountOfBagsConfirmed": {
    "additionalProp1": 0,
    "additionalProp2": 0,
    "additionalProp3": 0
  },
  "amountOfBagsExported": {
    "additionalProp1": 0,
    "additionalProp2": 0,
    "additionalProp3": 0
  },
  "amountOfBagsOrdered": {
    "additionalProp1": 0,
    "additionalProp2": 0,
    "additionalProp3": 0
  },
  "bags": [
    {
      "capacity": 0,
      "id": 0,
      "name": "string",
      "nameEng": "string",
      "price": 0
    }
  ],
  "certificates": [
    "string"
  ],
  "comment": "string",
  "courierInfo": {
    "courierLimit": "LIMIT_BY_SUM_OF_ORDER",
    "maxAmountOfBigBags": 0,
    "maxPriceOfOrder": 0,
    "minAmountOfBigBags": 0,
    "minPriceOfOrder": 0
  },
  "courierPricePerPackage": 0,
  "employeePositionDtoRequest": {
    "allPositionsEmployees": {
      "additionalProp1": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "additionalProp2": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "additionalProp3": [
        {
          "id": 0,
          "name": "string"
        }
      ]
    },
    "currentPositionEmployees": {
      "additionalProp1": "string",
      "additionalProp2": "string",
      "additionalProp3": "string"
    },
    "orderId": 0
  },
  "exportDetailsDto": {
    "allReceivingStations": [
      {
        "createDate": "string",
        "createdBy": "string",
        "id": 0,
        "name": "string"
      }
    ],
    "dateExport": "string",
    "receivingStationId": 0,
    "timeDeliveryFrom": "string",
    "timeDeliveryTo": "string"
  },
  "generalOrderInfo": {
    "adminComment": "string",
    "dateFormed": "2022-08-10T15:53:28.861Z",
    "id": 0,
    "orderPaymentStatus": "PAID",
    "orderPaymentStatusName": "string",
    "orderPaymentStatusNameEng": "string",
    "orderPaymentStatusesDto": [
      {
        "eng": "string",
        "key": "string",
        "ua": "string"
      }
    ],
    "orderStatus": "FORMED",
    "orderStatusName": "string",
    "orderStatusNameEng": "string",
    "orderStatusesDtos": [
      {
        "ableActualChange": true,
        "eng": "string",
        "key": "string",
        "ua": "string"
      }
    ]
  },
  "numbersFromShop": [
    "string"
  ],
  "orderBonusDiscount": 0,
  "orderCertificateTotalDiscount": 0,
  "orderDiscountedPrice": 0,
  "orderExportedDiscountedPrice": 0,
  "orderExportedPrice": 0,
  "orderFullPrice": 0,
  "paymentTableInfoDto": {
    "overpayment": 0,
    "paidAmount": 0,
    "paymentInfoDtos": [
      {
        "amount": 0,
        "comment": "string",
        "id": 0,
        "imagePath": "string",
        "paymentId": "string",
        "receiptLink": "string",
        "settlementdate": "string"
      }
    ],
    "unPaidAmount": 0
  },
  "userInfoDto": {
    "customerEmail": "string",
    "customerName": "string",
    "customerPhoneNumber": "string",
    "customerSurName": "string",
    "recipientEmail": "string",
    "recipientId": 0,
    "recipientName": "string",
    "recipientPhoneNumber": "string",
    "recipientSurName": "string",
    "totalUserViolations": 0,
    "userViolationForCurrentOrder": 0
  }
}

**User story and test case links**

[Test case GC-2650](https://jira.softserve.academy/browse/GC-2650)"

**Comment by OlegVat** [comment]
The bug is already fixed, the method has NotFoundException for an employee in it.
