### ISSUE TITLE
[Create news] There is no highlighted warning message on the bottom of the text box when user tries to enter more than 170 symbols

### ISSUE THREAD

**Issue by mikhaylovamarina** [ita-social-projects/GreenCity#4544]
Environment: Chrome Version 103.0.5060.134, Windows 10
Reproducible: always.
Build found: 16.08.2022

Preconditions
1.Greencity is opened https://www.testgreencity.ga/GreenCityClient/#/news/create-news
2.User is registered

Steps to reproduce

1.Go to Eco news tab
2.Click on 'Create news' button
3.Enter valid data in 'Content' field
4.Select one or more tags (only 3 tags can be added)
5.Try to enter more than 170 symbols in 'Title' field

**Actual result**
Warning message  "Should contain maximum 170 symbols"  in red color is NOT displayed below the 'Title' field

**Expected result**
Warning message  "Should contain maximum 170 symbols"  in red color is displayed below the 'Title' field
![Снимок экрана (62)](https://user-images.githubusercontent.com/105449847/184890020-0263b5ef-1c16-4c72-949e-c3c957fb6c1f.png)

**User story and test case links**
E.g.: [User story](https://github.com/ita-social-projects/GreenCity/issues/537) (https://github.com/ita-social-projects/GreenCity/issues/505)
[Test case](https://jira.softserve.academy/browse/GC-644)

**Labels to be added**
"Bug", Priority ("low: "), Severity ("trivial:"), Type ( "UI").

**Comment by YelyzavetaSheptytska** [comment]
<img width="1244" alt="Screen Shot 2022-11-17 at 12 05 29 PM" src="https://user-images.githubusercontent.com/112197311/202430446-420e44d1-ddef-4df2-9001-37e50d69ee2f.png">

There is no warning message under the title

**Comment by atsa21** [comment]
Warning message for Title - 170/170 according Figma mockup
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=13193%3A15&t=eSPhsJ85zbY2V31C-0
![image](https://user-images.githubusercontent.com/104850911/203014702-dbb52cc0-a958-4f8e-bc60-227dc71d6267.png)
