### ISSUE TITLE
[UBS courier. User's personal cabinet] It is  impossible to input alternative user`s address due  the corrupted input form for alternative address while editing existing personal data in user's personal cabinet

### ISSUE THREAD

**Issue by Horokh** [ita-social-projects/GreenCity#4551]
**Environment:** Windows 10 pro, Opera 89.0.4447.91
**Reproducible:** always
**Build found:** 19.08.2022

**Scenario 1**
**Preconditions**
1.Go to  https://www.testgreencity.ga/GreenCityClient/#/
2.The user exists and has 1  paid order.
3.The user is authorized.
**Steps to reproduce**
1. Go to 'user data' section
2. Scroll down page and click on 'edit data.'
4. Click on 'Add address'

**Actual result**
It is impossible to input alternative user`s address due the corrupted input form for alternative address
https://user-images.githubusercontent.com/102593506/185521679-057219b8-7d8b-4c50-9f5c-9177c8052a25.mp4

**Expected result**
Form  for alternative address is fully visible and editable and input user`s  data

**Scenario 2**
**Preconditions**
1. Log in to the GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. Open 'UBS-user'
3. Click on 'New order'
4. You should not choose location in popup-window (close it)
5. Add services and move next (personal data)
6. Scroll down page and click on add another address 

**Actual result**
1. The client can`t fill the fields
<img width="1413" alt="Снимок экрана 2022-09-23 в 17 33 20" src="https://user-images.githubusercontent.com/108685196/191985547-afe96ff5-b9a2-4079-a86b-09e60912b9a4.png">

**Expected result**
1. The client can  fill the fields

**Labels to be added**
"Bug", Priority ("high"), Severity ("low"), Type ("UI")

**Comment by YelyzavetaSheptytska** [comment]
Actual result for the Scenario 2 still looks the same "The client can`t fill the fields"

**Comment by marianaharnyk** [comment]
Everything is working correctly. The bug described in scenario 2 cannot be reproduced
https://www.loom.com/share/172bcef08b95439d8a319d7d2a7e6bd6

**Comment by YelyzavetaSheptytska** [comment]
Double checked it. Yes it works correctly already.
