### ISSUE TITLE
[Mobile App][Personal Cabinet][AT]  An orders status is not  not displayed  in  the  'Current orders table'  

### ISSUE THREAD

**Issue by Horokh** [ita-social-projects/GreenCity#4561]
**Environment:**  OS Android 8.0 ,  device (Samsung A7 (2017) ).
**Reproducible:** always
**Build found:** 05.09.2022 GreenCity версія 1
**Preconditions**

1. User  downloaded  a mobile phone application   from [https://www.testgreencity.ga/GreenCityClient/#](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
2. The app. 'Greencity'  is opened
3. User is logged in as user  on  [https://www.testgreencity.ga/GreenCityClient/#](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
4. User  has  at  least  one  order  with  different  order  statuses

**Steps to reproduce**
<html>
<body>

  |   | Test Step | Test Data | Expected Result | Attachment | Columns
-- | -- | -- | -- | -- | -- | --
  | 1 | Clic on "UBS courier" |   |   |   |  
  | 2 | Click on the "UBS user" |   |   |   |  
  | 3 | Open an order from current orders view table | Formed, Done, Adjustment | The order with the corresponding status is displayed in the order table

</body>
</html>

**Actual result**
An orders status is not not displayed in the 'Current orders table'

**Expected result**
 The order with the corresponding status is displayed in the order table

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:

**Labels to be added**
"Bug", Priority ("high "), Severity ("low"), Type ("Functional"),

**Comment by vplvua** [comment]
Current mockup does not contain the display of order status and payment status.
First we will make changes to the mockup, then we will redesign the mobile application.

**Comment by HalynaChornevych** [comment]
The error cannot be reproduced. It is impossible to place a new order (the number in the "house" field in the order address is not accepted)

**Comment by Vadym840217** [comment]
![M_order_status](https://github.com/ita-social-projects/GreenCity/assets/130633728/af774e94-906d-461b-9f92-f392def92536)
