### ISSUE TITLE
[Mobile App][Personal Cabinet][AT] A UI defect was detected on the page for choosing payment methods for an order with the status "unpaid"

### ISSUE THREAD

**Issue by Horokh** [ita-social-projects/GreenCity#4563]
![Screenshot_20220905-143515_Chrome](https://user-images.githubusercontent.com/102593506/188856162-b576cea0-1344-4e47-b51a-7010c00b0202.jpg)
**Environment:** OS Android 8.0 , device (Samsung A7 (2017) ).
**Reproducible:** always
**Build found:** 05.09.2022 GreenCity версія 1

**Preconditions**

1. User  downloaded  a mobile phone application   from [https://www.testgreencity.ga/GreenCityClient/#](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
2. The app. 'Greencity'  is opened
3. User is logged in as user  on  [https://www.testgreencity.ga/GreenCityClient/#](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
4. User  has  at  least  one  order  with   statuses 'unpaid'

**Steps to reproduce**

1. Click on "UBS courier"  
2. Click on the "UBS user" 
3. Click on an order with status 'не оплачено' from current orders  
4. Click on the 'Pay' button   
5. Click on the 'Next' button   
6. Click on the 'Next' button

</body>
</html>

**Actual result**
A UI defect was detected on the page for choosing payment methods

**Expected result**
The "cancel" and "order" buttons are centered and do not contain extraneous elements

**Postconditions**

**Labels to be added**
"Bug", Priority ("high"), Severity ("minor"), Type ("UI, )

**Comment by atsa21** [comment]
Not reproduce
