### ISSUE TITLE
[Mobile App][ UBS Courier] The text of the fields in 'Деталі замовлення' tab and 'Підтвердження' tab is overlap and not aligned

### ISSUE THREAD

**Issue by YakymetsHub** [ita-social-projects/GreenCity#4567]
**Environment:** Android 11, Chrome 105.05195.77, device (Realme 6).
**Reproducible:** always.
**Build found:** 07.09.2022 GreenCity версія 1

**Preconditions**
The user is logged in as a client and navigated to a UBS Courier.

**Steps to reproduce**
Go to 'Деталі замовлення' tab.
Go to 'Підтвердження' tab.

**Actual result**
The text of the fields in 'Деталі замовлення' tab and 'Підтвердження' tab is overlap and not aligned

![photo_2022-09-07_12-54-11](https://user-images.githubusercontent.com/107051540/188876232-f89a1af1-312b-4af2-a2c7-8e7638b6b4fa.jpg)
![photo_2022-09-07_12-54-20](https://user-images.githubusercontent.com/107051540/188876235-75700252-f3cb-46eb-875f-8e1687894f71.jpg)
![photo_2022-09-07_12-54-24](https://user-images.githubusercontent.com/107051540/188876236-5be35746-9f94-450f-bc02-1b199fa3a584.jpg)
![photo_2022-09-07_12-54-30](https://user-images.githubusercontent.com/107051540/188876237-48599979-4d79-478a-88f4-68d3e93db08a.jpg)

**Expected result**
The text of the fields in 'Деталі замовлення' tab and 'Підтвердження' tab is aligned

**Comment by RoksolanaKolomiyets** [comment]
На роздільній здатності 360х740 , 260х653 (IPhone).  елементи накладаються одне на одне .
