### ISSUE TITLE
News page: display number of items

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#457]
As a User I want to have an option to chose number of items displayed per page, so I can have a View, which is most convenient for me. 

Mock up:
<img width="124" alt="Screenshot_32" src="https://user-images.githubusercontent.com/60645819/74139278-c3ad2400-4bfb-11ea-984a-a2b5f6d52a76.png">

Acceptance Criteria. 
1. WHEN a User clicks on the View drop down - he/she has following options: 12, 24, 36.
2. WHEN a User selects one of the View options available - N number or less of selected items is displayed. For example if user selects View of 24 items:
  a. If 24 items are available - 24 items displayed, pagination shows only 1 page
  b. If less than 24 items are available - this number of items is displayed, pagination shows only 1 page
  c. If more than 24 items available - 24 items displayed on the 1st page, and the rest of the items split to the next pages for 24 items respectively, or for N items if View N items is selected by User. Pagination is described in Story #458

**Comment by rsyvulko** [comment]
Not relevant.
