### ISSUE TITLE
[Change request #4575 ] UBS home page, changes in "How to prepare" block

### ISSUE THREAD

**Issue by KhristinaVasko** [ita-social-projects/GreenCity#4575]
**Description of a Change request:**
Updated text and view of the "How to prepare" block in UBS Home page

**Reason for Change:**
Make changes according to the client's request in UBS Home page:
1. Completely change the existed text to the next, which are shown below, unite all text in the first block:
        " Як підготуватися?
                Ознайомтеся зі списком того, що ми приймаємо.
                Зберіть мікс чистих і сухих відходів в пакети.
                Текстильні відходи зберіть в окремий пакет.
                Замовте та сплатіть послугу.
                Чекайте на зустріч із нами.
          Умови:
                Мінімальне замовлення в межах Києва — 240 л.
                Мінімальне замовлення в радіусі 20 км від Києва (2400 л). Лайфхак: об’єднуйтеся з сусідами 😉
                Один пакет не повинен бути важче 30 кг." 
2.  Remove block on screenshot №2, and the image of the black package can be combined with the image of the green package.

**Acceptance Criteria**
1.
![image](https://user-images.githubusercontent.com/55766529/190347386-f2852b2d-2651-48f5-877f-c6763fe81e9f.png)

2.
![image](https://user-images.githubusercontent.com/55766529/190347489-087e64a7-a0c6-4b8c-9e06-b9a792fb2729.png)

**Labels to be added**
[change request: UI improvement]
[change request: adjustment]
[change request: new functionality]

Epic: [Epic title with its link]

**Comment by NataliaFushtei** [comment]
Text is not updated  in UBS Home page
