### ISSUE TITLE
News page: Pagination

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#458]
As a User I want to have pagination on the page, so that I can navigate between the pages within shorter time. 

Mock up:
<img width="200" alt="Screenshot_26" src="https://user-images.githubusercontent.com/60645819/74132335-04527080-4bef-11ea-9b6d-77767d74354e.png">
Acceptance criteria:
1. WHEN a User clicks on the page number THEN he/she is navigated to the relevant page.
   a. Pagination is displayed as sequence of numbers - 1, 2,3 ..... N (N is the last page number in the sequence) - limit 5 numbers, including "...".
   b. If there are just 5 pages - pagination will be 1,2,3,4,5.
   c. If there are less than 5 pages - the relevant number of pages is displayed - 1,2 as example
   b. Alongside with numbers, Pagination should have an arrows to navigate from page to page. 
      - If User is on the 1st page - the left arrow should be disabled (not clickable) 
      - If User is on the last page - the right arrow should be disabled (not clickable)
      - If there is only 1 page, left and right arrows should be disabled (not clickable)

**Comment by rsyvulko** [comment]
Not relevant.
