### ISSUE TITLE
[Events. View event preview card] List of Attendees is not displayed on the Event preview card

### ISSUE THREAD

**Issue by Githubenko** [ita-social-projects/GreenCity#4582]
Environment: Mac OS High Sierra: Version 10.13.6, Google Chrome: Version 105.0.5195.102
Reproducible: always
Build found: 11.09.2022

Description:
This test case verifies that information about who attends the event is displayed on the "Event preview card"

Preconditions:
Go to "Events page" https://www.testgreencity.ga/GreenCityClient/#/events

Steps to reproduce:
1. View "Event preview card"

Actual result:
Information about who attends the event is not displayed on the "Event preview card"

Expected result:
Information about who attends the event is displayed on the "Event preview card"

User story and test case links
[User story] https://github.com/ita-social-projects/GreenCity/issues/3374
[Test case] https://jira.softserve.academy/browse/GC-3557

**Comment by AngelinaRudnitska** [comment]
@Githubenko Could you please send a screenshot/mockup how it should look like?
