### ISSUE TITLE
[Events. Event preview card] Authorized User is unable to Join the event by clicking Join Event button

### ISSUE THREAD

**Issue by Githubenko** [ita-social-projects/GreenCity#4584]
Environment: Mac OS High Sierra: Version 10.13.6, Google Chrome: Version 105.0.5195.102
Reproducible: always
Build found: 11.09.2022
 
Steps to reproduce:
1. Go to https://www.testgreencity.ga/GreenCityClient/#/  and sign in
2. Go to "Events" page
3. View events preview cards and find the "Event" that is not created by current user 
4. Click "Join Event" button on the "Event preview card"

Actual result:
User can not join the event:
"Join Event" button is not replaced with "Cancel Request" button
"Event" is not aded to "My Events" page

Expected result:
User joined the event:
"Join Event" button is replaced with "Cancel Request" button
"Event" is aded to "My Events" page

User story and test case links
[User story] https://github.com/ita-social-projects/GreenCity/issues/3374
[Test case] https://jira.softserve.academy/browse/GC-3568

**Comment by AngelinaRudnitska** [comment]
not reproducible
