### ISSUE TITLE
[Events] Join Event button is displayed for passed event on the Event preview card

### ISSUE THREAD

**Issue by Githubenko** [ita-social-projects/GreenCity#4586]
Environment: Mac OS High Sierra: Version 10.13.6, Google Chrome: Version 105.0.5195.102
Reproducible: always
Build found: 14.09.2022

Description:
This test case verifies that "Join Event" button is not displayed on the "Event preview card" when event is passed

Steps to reproduce:
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ and sign in
2. Go to "Events" page
3. View through the Evens preview cards and find the one that is passed

Actual result:
"Join Event" button is displayed on the "Event preview card"

Expected result:
"Join Event" button is not displayed on the "Event preview card"

User story and test case links
[User story] https://github.com/ita-social-projects/GreenCity/issues/3374
[Test case] https://jira.softserve.academy/browse/GC-3575

**Comment by ghost** [comment]
This bug is not reproducible.
