### ISSUE TITLE
[Event] A notification about successfully joining the event does not appear

### ISSUE THREAD

**Issue by GitVladyslav** [ita-social-projects/GreenCity#4588]
**Environment:** 
Windows 10 Домашняя 21H2
Google Chrome Version 104.0.5112.82 (64-bit)
**Reproducible:** always
**Build found:** 9.09.2022

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/events
2. Log in
3. Select an open-type event from the list
4. Click the "Join event" button on the event card

**Actual result**
The notification "You have successfully joined the event" does not appear

**Expected result**
The notification "You have successfully joined the event" should appear

**User story and test case links**
"User story #3193 
[Test case](https://jira.softserve.academy/browse/GC-3118)"

**Comment by DanaIuich** [comment]
The notification "You have successfully joined the event" does not appear

**Comment by darinadobrukha** [comment]
duplicate of [[Events] There is no message after joining event #5775
