### ISSUE TITLE
[Create Event] Alphabetic characters in house numbers are not localised after publishing event

### ISSUE THREAD

**Issue by irynakoch** [ita-social-projects/GreenCity#4589]
**Environment:** macOS Monterey 12.6, Safari 16.0.
**Reproducible:** sometimes.
**Build found:** 15/09/2022

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/
2. Log in
3. Choose English language
4. Click on the "Events" tab
5. Click "Create" button
6. Choose event duration in the "Duration" dropdown (e.g. 1 day)
7. Tick the "Place" checkbox
8. Enter address with alphabetic character after house number (e.g. Ivana Mazepy St, 6**b**, Kyiv, Ukraine) 
9. Fill all the other fields with valid data
10. Click on the "Publish" button
11. Click on the "More" button of the event you just created once the event details page is opened

**Actual result**
Alphabetic character in house number is not localised  (e.g. Ivana Mazepy St, 6**Б**, Kyiv, Ukraine).

When creating event:
![Event location address when creating event](https://user-images.githubusercontent.com/112730845/190478016-e0b0e5ab-6bae-449a-be6f-010967abc608.png)

When event is published:
![Event location address when event is published](https://user-images.githubusercontent.com/112730845/190478041-d90e7e15-844f-43f8-8d90-c8ae393f0599.png)

**Expected result**
Alphabetic character in house number is localised  (e.g. Ivana Mazepy St, 6**b**, Kyiv, Ukraine).

**User story and test case links**
User story https://github.com/ita-social-projects/GreenCity/issues/3193

**Labels to be added**
"Bug", Pri: Low, Sev: Minor, L10n, Events

**Comment by OlegVat** [comment]
That's not a backend bug, we are using google Translate API on the front end for this translation. So it's impossible to fix this bug as we get already translated data from that API.
