### ISSUE TITLE
[Create Event] Datepicker is not highlighted in red when focus is moved off from calendar

### ISSUE THREAD

**Issue by irynakoch** [ita-social-projects/GreenCity#4591]
**Environment:** macOS Monterey 12.6, Safari 16.0.
**Reproducible:** always.
**Build found:** 15/09/2022

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/
2. Log in
3. Click on the "Events" tab
4. Click "Create" button
5. Choose event duration in the "Duration" dropdown (e.g. 1 day)
6. Click on the date picker so that the calendar with dates is displayed
7. Take off focus from the calendar

**Actual result**
Datepicker is not highlighted in red.

![Actual result after focus is taken off from the datepicker](https://user-images.githubusercontent.com/112730845/190486914-b4942382-58d9-4553-a551-f49ba65882a4.png)

**Expected result**
Datepicker is highlighted in red.

![Expected result after focus is moved off from the datepicker](https://user-images.githubusercontent.com/112730845/190486400-7eda274b-2e20-447f-8e6e-43d598a2643a.png)

**User story and test case links**
User story https://github.com/ita-social-projects/GreenCity/issues/3193
Test case https://jira.softserve.academy/browse/GC-3155)

**Labels to be added**
"Bug", Pri: Medium, Sev: Minor, UI, Events

**Comment by atsa21** [comment]
not reproduce
