### ISSUE TITLE
[Create news] The uploaded image is stayed in the 'Picture' field after returning to the closed 'Create news' page.

### ISSUE THREAD

**Issue by RBCDwyane** [ita-social-projects/GreenCity#4594]
**Environment:** 
Windows 10 x64
Google Chrome v.103.0.5060.114
FireFox v.102.0.1
Opera v.89.0.4447.48
**Reproducible:** 
always
**Build found:** 
11.09.2022

**Preconditions**
user is authorized 

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. Click "Eco news" tab in the navigation menu
3. Click "Create news" button
4. Fill all required fields with valid data
5. Click "Preview" button
6. Click "Back to editing' button
7. Click "Eco news" tab in the navigation menu
8. Click the "Create news" button
9. Pay attention to the 'Picture' field

**Actual result**
The uploaded image is stayed in the adding field.

**Expected result**
The fields of 'Create news' page becomed empty.

https://user-images.githubusercontent.com/113509087/190488741-ea1b275a-74d2-463d-93d4-9076068a16b1.mp4

**User story and test case links**
"User story #526
[Test case](https://jira.softserve.academy/browse/GC-403)

**Comment by Maxv1z** [comment]
Fixed or not reproducible
