### ISSUE TITLE
[Create event] 'Duration' drop-down is out of the main container

### ISSUE THREAD

**Issue by julialytsus** [ita-social-projects/GreenCity#4595]
**Environment:** macOS Monterey 12.5  Safari version 15.6 (17613.3.9.1.5)
**Reproducible:** always
**Build found:** 16.09.2022
**Priority:** Medium
**Severity:** Minor

**Preconditions**
1. User should be authorized
2. Go to https://www.testgreencity.ga/GreenCityClient/#/events

**Steps to reproduce**
1. Click on 'Create' button
2. Observe the 'Duration' drop-down

**Actual result**
'Duration' drop-down is out of the main container.
<img width="722" alt="Знімок екрана 2022-09-09 о 00 01 11" src="https://user-images.githubusercontent.com/112894449/190492358-1e58cb71-288e-49a6-bca3-e86b90964736.png">

**Expected result**
'Duration' drop-down is in the  main container
<img width="698" alt="Знімок екрана 2022-09-08 о 11 07 47" src="https://user-images.githubusercontent.com/112894449/190492342-8da3621d-f9e7-4236-bf2c-849a03359b13.png">

**User story and test case links**
E.g.: "User story #3193

**Comment by vitaliitrehubov** [comment]
This bug is not reproducible.

**Comment by atsa21** [comment]
Not reproduced

**Comment by julialytsus** [comment]
It is reproduced only on the Safari web browser on Mac OS.
And it is reproduced till now.

<img width="175" alt="Знімок екрана 2022-10-31 о 17 36 03" src="https://user-images.githubusercontent.com/112894449/199047579-b5984285-308b-4499-a4a4-3c44b254644c.png">

**Comment by atsa21** [comment]
Not reproduced on the Safari web browser
