### ISSUE TITLE
[Create event] The date is changed to the next month's date if user enters 31, for the month which has less than 31 days

### ISSUE THREAD

**Issue by julialytsus** [ita-social-projects/GreenCity#4596]
**Environment:** macOS Monterey 12.5  Safari version 15.6 (17613.3.9.1.5)
**Reproducible:** always
**Build found:** 16.09.2022
**Priority:** Medium
**Severity:** Minor

**Preconditions**
1. User should be authorized
2. Go to https://www.testgreencity.ga/GreenCityClient/#/events

**Steps to reproduce**
1. Click on 'Create' button
2. Choose duration of event
3. Click on date field 
4. Enter date 31 to the month with 30 days, and 29,30,31 to February (e.g. '02/29/2023', 02/31/2023' 09/31/2022')

**Actual result**
The date is changed to the next month's date

**Expected result**
Field is highlighted in red #EB180D

**User story and test case links**
E.g.: "User story #3193 
[Test case] (https://jira.softserve.academy/browse/100)"](https://jira.softserve.academy/browse/GC-3576)

https://user-images.githubusercontent.com/112894449/190493758-939d6cf0-279a-4d1c-bf1d-ba27afa2c9b8.mov

https://user-images.githubusercontent.com/112894449/190493774-b1c0f333-5cdc-4a43-abb9-e07038197d10.mov

https://user-images.githubusercontent.com/112894449/190493780-39f05af4-1cb5-4128-9c93-3af2d92ca8c9.mov

**Comment by AngelinaRudnitska** [comment]
Expected result. Not a bug

**Comment by julialytsus** [comment]
Then what is it if not a bug?

**Comment by AngelinaRudnitska** [comment]
This datepicker was made the same as it is on Angular materials (which means it is an expected result). The date changes to the next month only if the chosen number exists in months. For example, if you choose 32-33 the field will show an error.

**Comment by RoksolanaKolomiyets** [comment]
If user enter a valid data in the field Date the field highlited

**Comment by AngelinaRudnitska** [comment]
What do you mean by "the field highlighted"?
