### ISSUE TITLE
[Create news] The containers of message is overlaped on each other on the page after clicking to publish the news.

### ISSUE THREAD

**Issue by RBCDwyane** [ita-social-projects/GreenCity#4597]
**Environment:** 
Windows 10 x64
Google Chrome v.103.0.5060.114
FireFox v.102.0.1
Opera v.89.0.4447.48
**Reproducible:** 
always
**Build found:** 
11.09.2022

**Preconditions**
1. User is authorized 
2. English/Russian localization is chosen

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. Click  "Eco news" tab in the navigation menu
3. Click "Create news" button
4. Fill all required fields with valid data
5. Click "Publish" button
6. Pay attention to the message displayed on the page

**Actual result**
The "Please wait while loading..."/"Подождите, пожалуйста..." message is overlapped the "Your news is loading to website. Please wait until page refreshes."/"Ваши новости загружаются на веб-сайт. Дождитесь обновления страницы." message on the loadin page.

**Expected result**
The "Please wait while loading..."/"Подождите, пожалуйста..." message must be located under the "Your news is loading to website. Please wait until page refreshes."/"Ваши новости загружаются на веб-сайт. Дождитесь обновления страницы." message on the loadin page.

![En Text overlaps each other](https://user-images.githubusercontent.com/113509087/190495825-97389e40-27c8-454a-bc0a-eadc2a4b01ea.png)
![Ru Text overlaps each other](https://user-images.githubusercontent.com/113509087/190495827-eb3f6a81-4705-4336-a3a6-fe4a461a7a7c.png)

**User story and test case links**
User story #527
[Test case GC-597](https://jira.softserve.academy/browse/GC-597)
[Test case GC-602](https://jira.softserve.academy/browse/GC-602)

**Comment by atsa21** [comment]
Duplicate #4532
