### ISSUE TITLE
[Eco news]The news are not filtered by the selected tag  after clicking on the tag

### ISSUE THREAD

**Issue by nata000** [ita-social-projects/GreenCity#4598]
Environment:Windows 10 ,Google Chrome 105.0.5195.102
Reproducible: always
Build found: 08.09.2022

Steps to reproduse:

1.Go to https://www.testgreencity.ga/GreenCityClient/#/news
2.Choose any tag(e.g. `News`)
3.Pay attention on the news  tag

Actual result:
The news are not filtered by tag

Expected result:
The news are filtered by tag

**Labels to be added**
"Bug", Priority ("High"), Severity ("severity: "Major"), Type ("Functional,"Tags","Display news","Eco news","Filter
![News_are_not_fitered_by_tags](https://user-images.githubusercontent.com/112875002/190504411-23190f8d-1156-4280-b5c9-06fe4e653769.png)
").

**Comment by atsa21** [comment]
not reproduce
