### ISSUE TITLE
News page: List view option

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#460]
As a User I want to be able to see News as a List, so that I have more structured overview of Content items. 

Mock up:
<img width="511" alt="Screenshot_38" src="https://user-images.githubusercontent.com/60645819/74149827-573d1f80-4c11-11ea-81a5-6256894c6776.png">
Guidelines for a mock up:
<img width="561" alt="Screenshot_43" src="https://user-images.githubusercontent.com/60645819/74435211-9e731c80-4e6c-11ea-8f92-2a72040675aa.png">
Acceptance criteria:
1. WHEN a User clicks on the View as a List option on the right side of the page, THEN Content items get displayed as a List.  
 a. List view icon should be highlighted.  
 b. User should see first 6 Content items by default, the rest news will be loaded as user scrolls down - Infinite scrolling
c. Content items should be displayed in chronological order starting from the most recent. 
d. Content items should have the following elements:
   - Image - either added by user or a placeholder (will be updated by designer)
   - Relevant tag #456 (mandatory)
   - Title (mandatory)
   - Content text (not mandatory)- Title and text can be not higher than 136 px. Title should be displayed fully, and the text can be cut). There can be cases, when only one Title is displayed, because there is no text, or title occupies the whole 136 px in height if it is too long. 
   - Author (mandatory) - [FIRST NAME, LAST NAME] - Ex. John Smith
   - Date (mandatory) - [MMM DD, YYYY]. Ex. - Jan 28, 2019
   - Possibility to Share content to Facebook, Twitter, LinkedIn

Related to #461 #595
Change request #469 #539 #753 

Defects #784

**Comment by BohdanPrysiazhnyi** [comment]
The placement of the elements differs on the mockups in Figma and GitHub. Where is  @right?
 @![Responce](https://user-images.githubusercontent.com/68583636/88563898-3770ab00-d03b-11ea-8fd6-aa866c43fd32.jpg)
![74149827-573d1f80-4c11-11ea-81a5-6256894c6776](https://user-images.githubusercontent.com/68583636/88564075-730b7500-d03b-11ea-88c4-6632c3700f33.png)

**Comment by VasylynaYaremkiv** [comment]
there is an mistake on the mockup, becausethe height of the container changes not in proportion to the change in the width of the container, there will be changes in the mockup, it is agreed with the designers, so when expanding 1024 the height of the container should not be 166 but 194-195 pixels
