### ISSUE TITLE
[Eco news] The filtered news is not displayed  after clicking on the 'Back' button

### ISSUE THREAD

**Issue by nata000** [ita-social-projects/GreenCity#4600]
Environment:Windows 10,Google Chrome 105.0.5195.102
Reproducible: always
Build found:08.09.2022

Steps to reproduse:

1.Go to https://www.testgreencity.ga/GreenCityClient/#/
2.Click on the 'Eco news' page
3.Choose any (e.g. `News`)
4.Click on the 'Back' button
4.Pay attention on the filter

Actual result:
All news displayed and are not filtered by tag 

Expected result:
Only news with selected tags are displayed

**Labels to be added**
"Bug", Priority ("pri:  "high"), Severity ("severity: major"), Type ("UI, "Functional"), "Filter","Tags","Display news", "Eco news"

**Comment by zaitsev-oleksii** [comment]
Duplicates https://github.com/ita-social-projects/GreenCity/issues/4501
