### ISSUE TITLE
[Create event] If the event location is not filled, warning appears not near corresponding field

### ISSUE THREAD

**Issue by OlhaKyrylenko** [ita-social-projects/GreenCity#4604]
**Defect Type:** UI
**Severity:** Minor
**Priority:** Low
**Environment:** Windows 10 Home, Google Chrome 104.0.5112.102
**Reproducible:** always.
**Build found:** 1.09.2022

**Staps to reproduce:**
1. Go to: https://www.testgreencity.ga/GreenCityClient/#/
2. Sign in as authorized user
3. Click on the 'Event' button
4. Сlick on the 'Create' button
5. Fill in all fields except the event location
6. Click on the 'Create' button

**Actual result:**
Warning appears not near corresponding field
![1](https://user-images.githubusercontent.com/112948983/190857072-97d720e6-1087-4856-9e6f-62efd5d7fab4.PNG)

**Expected result:**
Warning appears under fields 'Place' and 'Online' 
![2](https://user-images.githubusercontent.com/112948983/190857144-08775281-34c5-47fd-ba1e-95b29a6d0381.PNG)

**Comment by kovalchuk-vita** [comment]
Warning appears not under fields 'Place' and 'Online'
