### ISSUE TITLE
[Create news] The system allows to add PNG image more than 10 Mb in "Picture" field

### ISSUE THREAD

**Issue by MaximLiutyi** [ita-social-projects/GreenCity#4608]
**Environment:** Windows 10; Google Chrome - v.104.0.5112.102
**Reproducible:** always.
**Build found:** 17.09.2022

**Steps to reproduce**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. Sing in as a user
3. Go to "Eco news" page
4. Click on "Create news" button
5. Click on "browse" link in "Picture" field
6. Add image PNG format, more than 10 Mb

**Actual result**
We can add PNG image more than 10 Mb

**Expected result**
System doesn’t allow to add PNG image more than 10 Mb

**User story and test case links**
E.g.: "User story #537
[Test case](https://jira.softserve.academy/browse/GC-584)"
![Mock up](https://user-images.githubusercontent.com/112893321/190875573-e18203e3-7026-4bcc-8cba-936b0cc7ab50.png)

**Comment by atsa21** [comment]
Duplicate #4609
