### ISSUE TITLE
[Eco news] The placing `Back` button does not meet the mock-up at all screen resolutions

### ISSUE THREAD

**Issue by nata000** [ita-social-projects/GreenCity#4613]
Environment:  Windows 10,Google Chrome 105.0.5195.102
Reproducible: always
Build found: 14.09.2022

Steps to reproduse:
1.Go to https://www.testgreencity.ga/GreenCityClient/#/news
2.Set 1440, 1024, 768, 576, 320 of screen resolutions
3.Choose any news
4.Pay attention on the `Back` button
 
Actual result:
The `Back` button is not aligned according to the mockup

Expected result:
The `Back` button  is aligned according to the mockup https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=13187%3A52528

![Theback_Button_InThe_576Resolution](https://user-images.githubusercontent.com/112875002/190973587-e72169d5-5dc6-4386-83b9-e5b7b930637b.png)

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: minor"), Type ("UI")

**Comment by atsa21** [comment]
Not reproduce
