### ISSUE TITLE
[All habits] Gallery view is displayed instead of list view if user go back to all habits

### ISSUE THREAD

**Issue by julialytsus** [ita-social-projects/GreenCity#4620]
**Environment:** macOS Monterey 12.5, Safari 16.0
**Reproducible:** always
**Build found:** 20.09.2022
**Priority:** Low
**Severity:** Trivial

**Preconditions**
1. User should be authorized
2. Go to https://www.testgreencity.ga/GreenCityClient/#/profile/347/allhabits

**Steps to reproduce**
1. Change view of habits to a list view
3. Click on 'More' in any habit
4. Go back to 'All habits'

**Actual result**
All habits are displayed on a gallery view 

https://user-images.githubusercontent.com/112894449/191308080-beb3e573-8e0c-4723-8e66-3981fc0801eb.mov

**Expected result**
All habits are displayed on a list view

**Comment by vplvua** [comment]
Not reproduce.

It seems that the problem has already been solved. The way of displaying habits is saved when switching to other pages.
