### ISSUE TITLE
[Display news:List view] The title of the article is partially displayed

### ISSUE THREAD

**Issue by YBielik** [ita-social-projects/GreenCity#4625]
**Environment:** Fedora Linux 36, Firefox 104.0 (64-bit).
**Reproducible:** always.
**Build found:** 12/Sep/22.

**Preconditions**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/news 
2. 'Eco news' page is opened
3. Create a new article with a headline of at least 60 characters (e.g. ''XVI International specialized exhibition of ecologic products for the daily life")

**Steps to reproduce**
1. Click on 'Eco news' link in the header
2. Set size of page to 1440px, 1024px, 768px, 576px, 360px in turn
3. Click on the View as a List option
4. Pay attention created news UI - title should displayed fully

**Actual result**
The title of the article is partially displayed
https://jira.softserve.academy/secure/attachment/415118/Titles1440px.png
https://jira.softserve.academy/secure/attachment/415122/Titles1024px.png
https://jira.softserve.academy/secure/attachment/415119/Titles768px.png
https://jira.softserve.academy/secure/attachment/415120/Titles576px.png
https://jira.softserve.academy/secure/attachment/415121/Titles360px.png

**Expected result**
Title should displayed fully  https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12671%3A6371

https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12671%3A6429

https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12671%3A6458

**User story and test case links**
User story #460, #595

**Comment by atsa21** [comment]
Duplicate https://github.com/ita-social-projects/GreenCity/issues/4509
