### ISSUE TITLE
[UBS courier. User's personal cabinet] The client can see "You region {{currentLocation}}"

### ISSUE THREAD

**Issue by marianaharnyk** [ita-social-projects/GreenCity#4628]
**Environment:** macOS Mojave 10.14.6, Chrome Version 105.0.5195.102
**Reproducible:** sometimes
**Build found:** 23.09.2022 

**Preconditions**
1. Log in to the GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. Open 'UBS-user'
2. Click on 'New order'
3. You should not choose location in popup-window (close it)

**Actual result**
1. The client sees "You region {{currentLocation}}"
<img width="1237" alt="Снимок экрана 2022-09-23 в 18 50 22" src="https://user-images.githubusercontent.com/108685196/192002857-2cddb80d-48ae-48de-bda7-c955b569d678.png">

**Expected result**
1. The client should see an another text

**Comment by BelakorGit** [comment]
When the User is not choosing the location in pop-up window and pressing "Back" button, location is "Your location: {{currentLocation}}"
![image](https://user-images.githubusercontent.com/108956780/216129239-e65a9f21-da44-40e9-a0f8-a954884fe77f.png)
