### ISSUE TITLE
[UBS-User. Personal Cabinet] The message about wrong house number/ corp number/ entrance number is incorrect

### ISSUE THREAD

**Issue by marianaharnyk** [ita-social-projects/GreenCity#4633]
**Environment:** macOS Mojave 10.14.6, Chrome Version 105.0.5195.102
**Reproducible:** always
**Build found:** 29.09.2022 

**Preconditions**
1. Log in to the GreenCity as User https://ita-social-projects.github.io/GreenCityClient/#/

**Steps to reproduce**
1. Open 'UBS-user'
2. Click on 'User Data'
3. Click on 'Edit data'
4. Click on 'Add address'
5. Enter more than 8 numeric and alphabetic characters in the 'House' field/  'Corp' field/ 'Entrance' field (e.g. "1254ABCD")
6. Enter more than 255 numeric and alphabetic characters in the field 'Comment to the address' 

**Actual result**
The message about wtong number is 'The field should contain 1-30 characters.'
<img width="925" alt="Знімок екрана  о 09 38 25" src="https://user-images.githubusercontent.com/108685196/193208219-16c3b1ac-8d4e-4d0b-a6e8-51054e7f1f28.png">

**Expected result**
The message about wtong number in the 'House' field/  'Corp' field is 'The field should contain 1-8 characters.'
The message about wtong number in the 'Entrance' field is 'The field should contain 1-2 characters.'
The message about wtong maxLength in the field 'Comment to the address' is 'The field should contain 1-255 characters.'

**User story and test case links**
E.g.: "User story #3811

**Comment by NataliaVirt** [comment]
Fixed
![image](https://user-images.githubusercontent.com/112310945/198139280-ed018a67-c341-46ac-9e9b-9013a40cda1b.png)
![image](https://user-images.githubusercontent.com/112310945/198138848-df780402-d0e9-46fe-b8e1-6e0c9aaeff87.png)
