### ISSUE TITLE
[UBS User. Profile page] Error message in edit-mode is not responsive

### ISSUE THREAD

**Issue by vplvua** [ita-social-projects/GreenCity#4646]
**Environment:** Win 10, Chrome.
**Reproducible:** always
**Build found:** commit a772256

**Preconditions**
Go to the GreenCity : https://ita-social-projects.github.io/GreenCityClient/#/;
Log in as a registered user.

**Steps to reproduce**
1. Go to User data page
2. Click on Edit data button
3. Choose screen size smaller 770px width
4. Enter invalid symbol in field Name and Surname

**Actual result**
Error message does not behave responsive
![image](https://user-images.githubusercontent.com/95560409/195252118-dfd48508-0896-49e4-8be1-318b97894e4e.png)

**Expected result**
The error message should be displayed according to the screen size

**Postconditions**
It is necessary to make changes in the css style

**Comment by dmytro-kryvyi** [comment]
Does not reproduce
