### ISSUE TITLE
[UBS Admin Cabinet ] Admin can not change order status from “Не вивезли” to “Привезе сам”

### ISSUE THREAD

**Issue by NataliaVirt** [ita-social-projects/GreenCity#4654]
**Environment:** Windows 10, Google Chrome 106.0
**Reproducible:** always
**Build found:** 19.10.2022

**Preconditions**

1.User is signed in to  [Greencity](https://www.testgreencity.ga/GreenCityClient/#/) as admin
2. [Order history page](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders) is opened
3. Order with status "Не вивезли" is present in table 

**Steps to reproduce**
1. Find order with "Не вивезли" as "Статус замовлення"
2. Click on pencil near word "Не вивезли"
3. Click on arrow that trigger dropdown list

**Actual result**
Admin see  statuses  “Не вивезли”,  ”Узгодження”,  ”Привезе сам”, ”Скасовано” in dropdown list
Admin can not change order status from “Не вивезли” to “Привезе сам”
![image](https://user-images.githubusercontent.com/112310945/196633984-075009e2-fa81-42b8-a4b6-1c4a35abc783.png)

**Expected result**
Admin should see statuses “Не вивезли”,  ”Узгодження”,  ”Привезе сам”, ”Скасовано”  in dropdown list
Admin should be able to change order status from “Не вивезли” to “Привезе сам”
![image](https://user-images.githubusercontent.com/112310945/196635747-d9ae5526-d327-4609-8b45-cb9eced8d852.png)

**Additional information**
In Order details page the same. 
Admin can not change order status from “Не вивезли” to “Привезе сам”
 
**User story and test case links**
User story [#2901 ](https://github.com/ita-social-projects/GreenCity/issues/2901)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (" "Functional")

**Comment by zaitsev-oleksii** [comment]
Options added to UI part. Need to fix back-end as status will not change upon request.

**Comment by zaitsev-oleksii** [comment]
Need to fix on back-end as status will not change upon request. 
Endpoint: https://greencity-ubs.testgreencity.ga/ubs/management/changingOrder

**Comment by zaitsev-oleksii** [comment]
Required options added to UI.
