### ISSUE TITLE
[UBS Admin  Cabinet ][Orders] Admin can not change order status from “Підтверджено” to “Привезе сам”

### ISSUE THREAD

**Issue by NataliaVirt** [ita-social-projects/GreenCity#4655]
**Environment:** Windows 10, Google Chrome 106.0
**Reproducible:** always
**Build found:** 19.10.2022

**Preconditions**

1.User is signed in to  [Greencity](https://www.testgreencity.ga/GreenCityClient/#/) as admin
2. [Order history page](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders) is opened
3. Order with status “Підтверджено” is present in table 

**Steps to reproduce**
1. Find order with “Підтверджено” as "Статус замовлення"
2. Click on pencil near word “Підтверджено”
3. Click on arrow that trigger dropdown list

**Actual result**
Admin see  statuses  “Сформавано”,  ”Підтверджено”, ”На маршруті”,   ”Скасовано” in dropdown list.
Admin can not change order status from “Підтверджено” to “Привезе сам”.
![image](https://user-images.githubusercontent.com/112310945/196637969-e07fe00c-14e5-4706-8ffa-c4b897d4c2c4.png)

**Expected result**
Admin should see statuses “Сформавано”,  ”Підтверджено”, ”На маршруті”,  ”Привезе сам”, ”Скасовано”  in dropdown list.
Admin should be able to change order status from “Підтверджено” to “Привезе сам”.
![image](https://user-images.githubusercontent.com/112310945/196635747-d9ae5526-d327-4609-8b45-cb9eced8d852.png)

**Additional information**
In Order details page the same.  Admin can not change order status from “Підтверджено” to “Привезе сам”

 
**User story and test case links**
User story [#2901 ](https://github.com/ita-social-projects/GreenCity/issues/2901)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (" "Functional")

**Comment by zaitsev-oleksii** [comment]
Options added to UI part. Need to fix back-end as status will not change upon request.

**Comment by zaitsev-oleksii** [comment]
Need to fix on back-end as status will not change upon request. 
Endpoint: https://greencity-ubs.testgreencity.ga/ubs/management/changingOrder

**Comment by zaitsev-oleksii** [comment]
Required options added to UI.

**Comment by JJJazl** [comment]
This is not a backend bug. Each status has a list of statuses to which it can be changed.
For example, the CONFIRMED status can be replaced by the CANCELED, FORMED, and ON_THE_ROUTE statuses, but not by BROUGHT_IT_HIMSELF.
In case of an incorrect status change, we return a list of order IDs that were not processed and their change is irrelevant

**Comment by Olena-Kharkova** [comment]
![image](https://user-images.githubusercontent.com/110603507/210221492-277c061f-41d8-42fc-8e01-7a7007d9b3bf.png)
