### ISSUE TITLE
[UBS Admin Cabinet][Order details] List of order status is not updated after user change status and click "Зберегти" button

### ISSUE THREAD

**Issue by NataliaVirt** [ita-social-projects/GreenCity#4657]
**Environment:** Windows 10, Google Chrome 106.0
**Reproducible:** always
**Build found:** 19.10.2022

**Preconditions**

1.User is signed in to  [Greencity](https://www.testgreencity.ga/GreenCityClient/#/) as admin
2.  In [Order history page](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders) Order with status “Сформовано” is present in table 
3. Order details page is opened in order with status “Сформовано”

**Steps to reproduce**

1.Change status from  “Сформовано” to "Узгодження"
2. Add "Деталі вивезення" and "Відповідальні особи" information 
3. Click on "Зберегти" button
4. Go to order status and click on arrow to see dropdown list

**Actual result**
List of status is not updated.
Admin don't see status "Підтверджено" in list.
He should reload page to see updated order statuses list.

**Expected result**
List of status should be changed.
Admin should  see status "Підтверджено" in list.

**Additional information**
Same for all order status changing. 
 
**User story and test case links**
User story [#2901 ](https://github.com/ita-social-projects/GreenCity/issues/2901)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (" "Functional")

Video

https://user-images.githubusercontent.com/112310945/197550893-a78652e3-5914-4505-a2eb-d5531883c8d1.mp4

**Comment by BelakorGit** [comment]
Steps to reproduce, expected result and actual result are the same, as stated in the bug report.

**Comment by katia9261** [comment]
Not reproduced

https://user-images.githubusercontent.com/101433204/217463139-66f9f5cb-9a12-4032-a270-f3b29ead20cf.mp4
