### ISSUE TITLE
[UBS-Admin. Orders] System doesn't return to the Orders tab and hangs

### ISSUE THREAD

**Issue by YelyzavetaSheptytska** [ita-social-projects/GreenCity#4666]
**Environment:** macOS 10.10.5, Google Chrome 87.0.4280.141.
**Reproducible:** always.
**Build found:** 21.10.22

**Preconditions**
1. User is Logged in to UBS as an Admin: https://www.testgreencity.ga/GreenCityClient/#/ubs
2. "Замовлення" page is opened
3. Any order number from the table selected

**Steps to reproduce**
1. Go to 'Деталі замовлення'
2. Make any changes to the "Order Details"
3. Click on 'Назад' button
4. Click on "Так"button

**Actual result**
The system shows "У разі повернення назад внесені зміни будуть втрачені. Чи дійсно Ви бажаєте повернутись до таблиці?" message and doesn't return to the Orders tab, the page is hangs.
<img width="1146" alt="Screen Shot 2022-10-22 at 1 07 45 PM" src="https://user-images.githubusercontent.com/112197311/197336900-7c4402f5-5fa3-47be-85a3-c04465e06f28.png">

**Expected result**
The system should undo all the changes and return to the Orders tab.

User Story: https://github.com/ita-social-projects/GreenCity/issues/2795
[Test case](https://jira.softserve.academy/browse/GC-2407)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by katia9261** [comment]
The bug is not reproduced now
