### ISSUE TITLE
Create News: delete news

### ISSUE THREAD

**Issue by uliaso** [ita-social-projects/GreenCity#4671]
**As a** Registered User **I want to** delete my news **so that** news information is no longer stored

**Preconditions**
1. “Eco News” tab is opened
2. At least one eco news has been created

### Acceptance Criteria

1. User should be able to delete news posting WHEN using the delete button
2. After the User clicks on the ‘Delete’ button, the system shows the popup notification: "News will be deleted. Are you sure?’ Buttons ‘Yes’ and ‘No’ are displayed in red
3. If the User clicks on the ‘No’ button, the popup notification disappears, and the News is not deleted
4. If the User clicks on the ‘Yes’ button, the system deletes the News from the database and notifies the User of it

**Create news**
E.g.: Epic #912 [Epic]

**Comment by DanaIuich** [comment]
If the User clicks on the ‘Yes’ button, the system deletes the News from the database but doesn't notify the user of it

https://github.com/ita-social-projects/GreenCity/assets/128155213/a9602a9d-0795-4e0b-9826-4e903dbd765a
