### ISSUE TITLE
Insert.sql file is empty

### ISSUE THREAD

**Issue by lipiridi** [ita-social-projects/GreenCity#4672]
I tried to start the project locally according to the instructions, but point 7 is wrong.
![image](https://user-images.githubusercontent.com/60580660/197530826-78a9e63c-f395-4456-8d5b-7f32c757041f.png)
1. insert.sql file is not in dao package, it's here [src/test/resources/sqlFiles/ecoNewsRepo/insert.sql](src/test/resources/sqlFiles/ecoNewsRepo/insert.sql)
2. insert.sql file is empty

Please check it.

**Comment by kmpol** [comment]
Documentation needs to be updated - you do not need insert.sql, you have liquidbase instead

**Comment by lipiridi** [comment]
Thanks!
