### ISSUE TITLE
[UBS Admin Cabinet][Orders] Admin can not change order status from “Узгодження” to "Сформовано"

### ISSUE THREAD

**Issue by NataliaVirt** [ita-social-projects/GreenCity#4673]
**Environment:** Windows 10, Google Chrome 106.0
**Reproducible:** always
**Build found:** 24.10.2022

**Preconditions**

1.User is signed in to  [Greencity](https://www.testgreencity.ga/GreenCityClient/#/) as admin
2.  In [Order page](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders) Order with status  “Узгодження”
 is present in table 

**Steps to reproduce**
1. Click on pencil icon
2. Change status from “Узгодження” to "Сформовано"
3. Click on "Зберегти" icon
4. Go to DB to check order status / reload page 

**Actual result**
Status look changed. 
After page reload/in DB status is not changed.
**Expected result**
Status should be changed.

**Additional information**
Not reproducible on order details page 

 
**User story and test case links**
User story [#2901 ](https://github.com/ita-social-projects/GreenCity/issues/2901)
[Test case](https://jira.softserve.academy/browse/GC-2300)
**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (" "Functional")

Video

https://user-images.githubusercontent.com/112310945/197553508-46edf648-7925-4622-a3b6-b08fbf413ddf.mp4

**Comment by zaitsev-oleksii** [comment]
Need to fix on back-end as status will not change upon request. 
Endpoint: https://greencity-ubs.testgreencity.ga/ubs/management/changingOrder

**Comment by JJJazl** [comment]
This is not a backend bug. Each status has a list of statuses to which it can be changed. 
For example, the ADJUSTMENT status can be replaced by the BROUGHT_IT_HIMSELF, CONFIRMED, and CANCELED statuses, but not FORMED.
In case of an incorrect status change, we return a list of order IDs that were not processed and their change is irrelevant
