### ISSUE TITLE
[UBS Admin Cabinet][Orders] Admin can not change order status from “Не вивезли”/"На маршруті"/"Привезе сам" to "Скасовано"

### ISSUE THREAD

**Issue by NataliaVirt** [ita-social-projects/GreenCity#4674]
**Environment:** Windows 10, Google Chrome 106.0
**Reproducible:** always
**Build found:** 24.10.2022

**Preconditions**

1.User is signed in to  [Greencity](https://www.testgreencity.ga/GreenCityClient/#/) as admin
2.  In [Order page](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders) Order with status “Не вивезли”/"На маршруті"/"Привезе сам" is present in table 

**Steps to reproduce**
1. Click on pencil icon
2. Change status from “Не вивезли”/"На маршруті"/"Привезе сам" to "Скасовано"
3. Choose any reason radiobutton
4. Click on "Додати" button
5. Go to DB to check order status / refresh page /open orders details page

**Actual result**
Status is not updated.

**Expected result**
Status should be changed.

**Additional information**
Not reproducible on order details page 

 
**User story and test case links**
User story [#2901 ](https://github.com/ita-social-projects/GreenCity/issues/2901)
Test case [2338](https://jira.softserve.academy/browse/GC-2338)  [2339](https://jira.softserve.academy/browse/GC-2339)  [2340](https://jira.softserve.academy/browse/GC-2340)
**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (" "Functional")

Video

https://user-images.githubusercontent.com/112310945/197626711-52ac5529-478c-4aee-bb11-391cc7f832b3.mp4

**Comment by zaitsev-oleksii** [comment]
Need to fix on back-end as status will not change upon request. 
Endpoint: https://greencity-ubs.testgreencity.ga/ubs/management/changingOrder

**Comment by JJJazl** [comment]
This is not a backend bug. Each status has a list of statuses to which it can be changed.
For example, the NOT_TAKEN_OUT status can be replaced only by the ADJUSTMENT, and NOT_TAKEN_OUT statuses.
ON_THE_ROUTE status can be replaced only by DONE and NOT_TAKEN_OUT statuses, but not by others.
In case of an incorrect status change, we return a list of order IDs that were not processed and their change is irrelevant.
