### ISSUE TITLE
[UBS Admin Cabinet][Order details page] Order is not auto-assigned in the delivery day at 00:00 from status “Підтверджено” to status “На маршруті”

### ISSUE THREAD

**Issue by NataliaVirt** [ita-social-projects/GreenCity#4675]
**Environment:** Windows 10, Google Chrome 106.0
**Reproducible:** always
**Build found:** 24.10.2022

**Preconditions**

1.User is signed in to  [Greencity](https://www.greencity.social/#/ubs) as admin
2.  In [Order page](https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders) Order with status “Узгодження" is present in table 

**Steps to reproduce**
1. Go to orders details page of order with status "Узгодження"
2. Change status from “Узгодження" to "Підтверджено"
3. Change delivery date  to next day
4. Save changes
5. Wait to next day

**Actual result**
Order is not auto-assigned in the delivery day at 00:00 from status “Підтверджено” to status “На маршруті”

**Expected result**
Order is auto-assigned in the delivery day at 00:00 from status “Підтверджено” to status “На маршруті”

**Additional information**
You also can see that status is not updated for order 1513
https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/order/1513
 
**User story and test case links**
User story [#2901 ](https://github.com/ita-social-projects/GreenCity/issues/2901)
Test case [2304](https://jira.softserve.academy/browse/GC-2304)
**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (" "Functional")

**Comment by nina279** [comment]
Order is not auto-assigned in the delivery day at 00:00 from status “Підтверджено” to status “На маршруті”
<img width="1487" alt="Screenshot 2023-09-27 at 8 07 41" src="https://github.com/ita-social-projects/GreenCity/assets/111231614/8bcfe4e8-11d7-435a-94e4-d5f0f0bd1d01">
