### ISSUE TITLE
[UBS admin, Orders] The table scroll line doesn`t appear

### ISSUE THREAD

**Issue by KruVik** [ita-social-projects/GreenCity#4694]
**Environment:** Windows 10 (display resolution is 1366x768);  Google Chrome version 106.0.5249.119 (32-bit).
**Reproducible:** always
**Build found:** 19/10/22

**Preconditions**
User is logged in as administrator.

**Steps to reproduce**
1. Go to ubs-admin 
2. Go to Orders page
3. Pay attention to scroll line of the order table on the screen

**Actual result**
When the screen scale is 100% or more (depends on the screen size), the table scroll line disappears.
You need to scale the page down to 90% or less for the table scroll line to appear.
 
https://user-images.githubusercontent.com/112331608/198260800-98622ddb-8976-477e-9f86-b19fb31e5732.MP4

**Expected result**
The scroll line of the order table is available at any page scale.

**Comment by SokhaTaras** [comment]
Cannot be reproduced. Everything works correctly
![image](https://user-images.githubusercontent.com/86615598/206439506-f569cf40-3590-4aab-b9bd-f537d5e5043b.png)

**Comment by Olena-Kharkova** [comment]
https://user-images.githubusercontent.com/110603507/210220166-4cedbd91-c1cb-4b23-855d-08a465620ede.mp4

It's work correcty
