### ISSUE TITLE
[UBS-Admin. Orders] Pop-up manually added payment window doesn't close after clicking outside the window

### ISSUE THREAD

**Issue by YelyzavetaSheptytska** [ita-social-projects/GreenCity#4695]
**Environment:** macOS 10.10.5, Google Chrome 87.0.4280.141.
**Reproducible:** always.
**Build found:** 26.10.22

**Preconditions**
1. User is Logged in to UBS as an Admin.
2. Administrator has opened an order from current order view table.
3. Administrator has already manually added payment for current order.

**Steps to reproduce**
1. Administrator clicks on manually added payment id.
2. Administrator clicks outside the pop-up window.

**Actual result**
Pop-up window doesn't close.

**Expected result**
Pop-up window is closed and previous page Order Payment is shown.

User story: [#2999](https://github.com/ita-social-projects/GreenCity/issues/2999)
[Test case](https://jira.softserve.academy/browse/GC-3764)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Vadym840217** [comment]
https://github.com/ita-social-projects/GreenCity/assets/130633728/8d1282b6-3dc0-4dbe-b9db-088fd4b46d78
