### ISSUE TITLE
[UBS] - tariff status

### ISSUE THREAD

**Issue by innayashna** [ita-social-projects/GreenCity#4703]
You should create a new field that will display tariff status. It should be "Активно" if all the fields are filled correctly. "Незаповнено" if some information is missing. Or "Девктивовано" if tariff was deactivated. Currently we have status column in tariffs table but it represents location status that is not correct.

<img width="1435" alt="Screenshot 2022-10-30 at 12 34 42" src="https://user-images.githubusercontent.com/98092315/198874371-da437eb1-56f2-4615-9230-cfebd10d4be5.png">

**Comment by OlegVat** [comment]
Functionality already exists and works as expected. Couriers are not showing correctly on the front-end side.
