### ISSUE TITLE
[Pricing page. Tariffs] A list of items appears under the dropdowns' menu when select "all" in "City" and "Receiving station" on the tariffs panel

### ISSUE THREAD

**Issue by kovalchuk-vita** [ita-social-projects/GreenCity#4709]
**Environment:** Windows 10 Pro, browsers: Google Chrome version 106.0.5249.119, Microsoft Edge version 107.0.1418.26
**Reproducible:** always
**Build found:** 01.11.2022

**Preconditions**
1. The user is logged in as Admin.
2. Tariffs tab is opened: https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs

**Steps to reproduce**
1. Select 'All' on the dropdowns 'City' and 'Receiving station' on the tariffs' panel 

**Actual result**
A list of items appears under the dropdowns' menu
![image](https://user-images.githubusercontent.com/105010608/199209388-1053947a-dfef-4e16-97c3-c7eb0cb4d9d6.png)

**Expected result**
The selected items are hidden and are showed into the results table

**User story and test case links**
User story [#3835 ](https://github.com/ita-social-projects/GreenCity/issues/3835)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by marianaharnyk** [comment]
Expected result is not described in user story #3835.
