### ISSUE TITLE
BUG [USER] Popup with registration form is not shown after clicking on the “My cabinet” button

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#473]
Steps to reproduce:
1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the "My cabinet" button on the header
3. Pay attention to the page is opened 

[**Expected](url) Result:**
Popup with registration form is shown after clicking on the "My cabinet" button

**Actual Result:**
The "My cabinet" button is not highlighted and the login page is shown after the unregistered user clicks on the "My cabinet" button  

Environment: Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultimate
[https://github.com/ita-social-projects/GreenCity/labels/Bug]
#385

**Comment by Talichka** [comment]
![Mycabinet](https://user-images.githubusercontent.com/40841118/75815467-224d6400-5d9c-11ea-909a-5984f93988eb.png)

**Comment by nabermi2020** [comment]
Not relevant
