### ISSUE TITLE
[My habits] It is impossible to "Give up" the habit, button "Give up" ("Здатися") does not work

### ISSUE THREAD

**Issue by YelyzavetaSheptytska** [ita-social-projects/GreenCity#4735]
**Environment:** macOS 10.10.5, Google Chrome 87.0.4280.141, Safari 10.1.2 
**Reproducible:** always
**Build found:** 12.10.2022

**Preconditions**
1. Login into the Green City https://www.testgreencity.ga/GreenCityClient/#/
2. "My habits" page is opened

**Steps to reproduce**
1. Click on "Edit" habit button
2. Scroll down and click on "Give up" ("Здатися") button

**Actual result**
"Give up" button does not work. System doesn't return to the previous "My habits" page.

**Expected result**
When user clicks on the button "Give up" a pop-up notification "Are you sure you want to give up the habit? All your progress of habit's tracking will be lost." and buttons "No" and "Yes" appear. System returns to the previous "My habits" page. Appropriate edited habit is deleted.

Epic My habits https://github.com/ita-social-projects/GreenCity/issues/938
User story https://github.com/ita-social-projects/GreenCity/issues/2167

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by atsa21** [comment]
Duplicate #4833
