### ISSUE TITLE
BUG [USER] More than 20 characters are allowed in 'Last name' field of 'Sign up' page

### ISSUE THREAD

**Issue by Marie1360** [ita-social-projects/GreenCity#474]
**Steps to reproduce:**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on "Sign up" link on the right upper corner of the site
3. Enter more than 20 characters in 'Last name' field (e.g. 'Denussenkooooooooooooo')

**Actual result:**
More than 20 characters are allowed in 'Last name' field of 'Sign up' page
**Expected result:**
'Last name' field can contain up to 20 characters

**Environment:** 
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
Google Chrome Version 80.0.3987.132 (64-bit)

![Screenshot_5](https://user-images.githubusercontent.com/61519117/75810698-8116db80-5da4-11ea-9699-369961c63d2c.png)
#385

**Comment by nabermi2020** [comment]
Not relevant
