### ISSUE TITLE
BUG[USER]The verification email is not sent to user email box after clicking 'Sign up' button

### ISSUE THREAD

**Issue by KaterynaIlkiv** [ita-social-projects/GreenCity#476]
The verification email is not sent to user email box after entering valid data in the all mandatory fields and clicking 'Sign up' button in registration form.
Environment:
OS: Windows 10Pro, V.1909
Browser: Chrome 80.0.3987.122 / 64-bit

Bug is also reproduced on:
OS: Windows 10
Browser: Mozilla 73.0.1 / 64-bit

Steps to reproduce:

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Sign up' button in the right upper corner
3. Enter valid data into 'First name','Last name','Email','Password','Confirm password' fields
4. Click on the 'Sign up' button
5. Verify existing of verification email in the email box

Actual results: The verification email is not sent to user email box after clicking 'Sign up' button
Expected results: User should receive a verification email about registration in the application to email address to complete the registration

#386

**Comment by fil2002** [comment]
Bug is reproduced in the environment:
OS: Windows 10
Browser: Mozilla 73.0.1 / 64-bit
