### ISSUE TITLE
 BUG [USER] Endless progress is shown on 'Sign Up' button after leaving 'Last name' field empty

### ISSUE THREAD

**Issue by Marie1360** [ita-social-projects/GreenCity#477]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Enter valid value in 'First name' field (e.g. 'Nadya')
3. Leave 'Last name' field empty
4. Enter valid email adress (e.g. nadya@gmail.com)
5. Enter valid values in 'Password' and 'Confirm password' fields (e.g. Nadya*13)
6. Click on 'Sign Up' button

**Actual result:**
Endless progress is shown on 'Sign Up' button after leaving 'Last name' field empty
**Expected result:** 
'You have successfully registered on the site. Please confirm your email address in the email box' confirmation message is shown after clicking on 'Sign Up' button
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
Google Chrome Version 80.0.3987.132 (64-bit)
#385 
![Screenshot_1](https://user-images.githubusercontent.com/61519117/75886649-ff758b00-5e41-11ea-9c08-764b27091648.png)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
