### ISSUE TITLE
Feature/Implement notification in user profile cabinet

### ISSUE THREAD

**Issue by SokhaTaras** [ita-social-projects/GreenCity#4770]
It this user story you have to make possible to get notifications in Viber or (and) Telegram ( to choose).You have to put tick and then be redirected to chat bots which will help you
![image](https://user-images.githubusercontent.com/86615598/205052724-fa966d21-90a5-48dd-8139-c8327767e7ec.png)

**Comment by NeonilaH** [comment]
Retested ✅
[Jira Test case WR50QC-580](https://jira.softserve.academy/browse/WR50QC-580)
