### ISSUE TITLE
[UBS Tariffs Courier] Title of placeholder and field title of pop-up window "Додати кур'єра" do not correspond to the mock - up 

### ISSUE THREAD

**Issue by Lidiiaduzhych** [ita-social-projects/GreenCity#4779]
**Environment:** 
Windows 10 Home (Version 22H2) 
Chrome version 108.0.5359.71 
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 07.12.2022

**Preconditions**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super admin.
3. Go to page "Тарифи" and click on "gear" pictogram
4. Click on the additional pictogram "Додати" and choose point "Кур'єр"

**Steps to reproduce**
1. Check UI controls and elements are according to mock-ups (https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=19820%3A59978&t=iqpKdrw7BLhbj5nW-0)
2. Pay attention to the title of placeholder and field title of pop-up window "Додати кур'єра".

**Actual result**
Title of placeholder and field title of pop-up window "Додати кур'єра" do not correspond to the mock - up 

**Expected result**
All controls and elements of pop-up window are correct according mock-up. (https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=19820%3A59978&t=iqpKdrw7BLhbj5nW-0)

**User story and test case links**
E.g.: "User story #3849 
[Test case](https://jira.softserve.academy/browse/GC-4075)
![mock up](https://user-images.githubusercontent.com/116264137/206274135-86a997e0-5ec5-4d7b-8f22-8bf2c97d03ca.jpg)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: trivial"), Type ("UI")

**Comment by Olena-Kharkova** [comment]
not a bug
