### ISSUE TITLE
BUG [UI] Eye icons are placed outside the 'Password' and 'Password confirm' fields on 'Sign Up' popup

### ISSUE THREAD

**Issue by Marie1360** [ita-social-projects/GreenCity#478]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Verify eye icons placement of the 'Password' and 'Password confirm' fields

**Actual result:**
Eye icons are placed outside the 'Password' and 'Password confirm' fields on 'Sign Up' popup
**Expected result:** 
Eye icons are placed in the 'Password' and 'Password confirm' fields according to mockup
**Note:** The bug is also reproducible on 'Sign In' popup
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
Google Chrome Version 80.0.3987.132 (64-bit)
#385 
![Actual res (eye icon)](https://user-images.githubusercontent.com/61519117/75887925-fd143080-5e43-11ea-8330-f8ddbc8f2adc.png)
![mockup (eye icon)](https://user-images.githubusercontent.com/61519117/75887937-00a7b780-5e44-11ea-9949-93ee7baaf0bf.png)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
