### ISSUE TITLE
Field label is 'Password confirm' instead of 'Confirm password' field on 'Sign Up' popup

### ISSUE THREAD

**Issue by Marie1360** [ita-social-projects/GreenCity#479]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Look at label of 'Confirm password' field

**Actual result:**
Field label is 'Password confirm' instead of 'Confirm password' field on 'Sign Up' popup
**Expected result:**
Field label should be 'Confirm password' instead of 'Password confirm' on 'Sign Up' popup according to mockup
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
#385

**Comment by RomanDeveloperAcc** [comment]
Because of new mock-up this page is going to be deleted. That is why this bug seems to be irrelevant.
