### ISSUE TITLE
[Starting view]   Sidebar menu with `Замовлення`, `Клієнти`, `Сертифікати`, `Працівники`, `Документи`, `Тарифи`, `Повідомлення` is not displayed on the 'Про нас' page after authorization with Administrators credentials

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4793]
**Environment:** Windows 11, Google Chrome, Version 108.0.5359.96 (Official Build) (64-bit).
**Reproducible:** sometimes.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
1. log in as a Admin

**Steps to reproduce**
1. Go to '[(https://www.testgreencity.ga/GreenCityClient/#/ubs)]'
2. Log in the system
3. Click on the `Про нас' tab

**Actual result**
 Sidebar menu is not displayed on the 'Про нас' page after authorization with Administrators credentials

**Expected result**
When the Admin log in to the system he/she will see a Sidebar menu with the following fields: 
`Замовлення`, `Клієнти, `Сертифікати`, `Працівники`, `Документи`, `Тарифи`, `Повідомлення`.

**Create new cards of the location for the pricing page**
E.g.: "User story #3859 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: high"), Type ( "Functional")
![1](https://user-images.githubusercontent.com/116261833/206571825-801c119c-863c-4165-94ce-4d2f02e057da.png)
![2](https://user-images.githubusercontent.com/116261833/206571830-390f5185-dee6-44bf-840b-049770949571.png)
).

**Comment by OlegVat** [comment]
The bug is not related to the backend, and it seems this issue is not a bug. After discussing the situation with the team, the sidebar should be displayed only in the user cabinet section of the website but not on the "Про нас" page.
