### ISSUE TITLE
BUG [UI] Arrow is not aligned with 'Sign-in with Google' text button on 'Sign Up' popup

### ISSUE THREAD

**Issue by Marie1360** [ita-social-projects/GreenCity#480]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Look at elements alignment on 'Sign-in with Google' button
**Actual result:**
Arrow is not aligned with 'Sign-in with Google' text button on 'Sign Up' popup
**Expected result:**
All elements on 'Sign-in with Google' button are aligned with each other according to mockup
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
#385
![misalignment](https://user-images.githubusercontent.com/61519117/75889620-a3613580-5e46-11ea-9402-d9a5c4b5f497.png)
![mockup alignmentpng](https://user-images.githubusercontent.com/61519117/75889786-dd323c00-5e46-11ea-9d98-8f830e24ad83.png)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
