### ISSUE TITLE
[UBS Admin] Admin can make an order 

### ISSUE THREAD

**Issue by katia9261** [ita-social-projects/GreenCity#4800]
**Environment**: Windows 10, Google Chrome 108.0.5359.98
**Reproducible**: always
**Build found**: 09.12.2022

**Preconditions**
Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
Sign in as Admin.

**Steps to reproduce**
1. Go to the page and click on the "Order" button
2. Admin can make an order

**Actual result**
Admin can make an order

**Expected result**
1. Logged Admin can't make an order
2. When logged Admin clicks on the UBS logo he should get to his UBS-Admin cabinet
3.  The "Order" button should not be displayed on the main page of UBS (https://www.testgreencity.ga/GreenCityClient/#/ubs)
![image](https://user-images.githubusercontent.com/110603507/211556846-632fa47d-4ec8-442e-8056-f7200f271727.png)

**Comment by Olena-Kharkova** [comment]
point 3 was added to the Expected result as improvement
