### ISSUE TITLE
[API] [Pricing page. Admin cabinet] Super Admin can't create a new receiving station with valid data

### ISSUE THREAD

**Issue by DavidPolishchuk** [ita-social-projects/GreenCity#4802]
**Environment:** Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
**Reproducible:** always
**Build found:** 10.12.2022

**Preconditions**
1. Swagger is opened
2. The user has been registered as Super Admin
3. Go "Тарифи” -> tools “Gear”
4. Tap on “Додати”, and then choose point “Станція приймання”.

**Steps to reproduce**
1. Make method POST greencity-ubs.testgreencity.ga/ubs/superAdmin/create-receiving-station
2. Input greencity-ubs.testgreencity.ga/ubs/superAdmin/create-receiving-station?name=DavidDavid
3. Click the 'Execute' button

https://user-images.githubusercontent.com/116380555/206935421-032ef4d9-e8b0-4b6d-94f8-92e168bd1244.mp4

**Actual result**
The system outputs 500 status code

**Expected result**
The system should output the 201 status code. A new receiving station with valid data exists in DB.

**User story and test case links**
E.g.: "User story #3850
[Test case](https://jira.softserve.academy/browse/GC-4179)"

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: critical"), Type ("Functional").

**Comment by JoseCaste** [comment]
Current result
![image](https://user-images.githubusercontent.com/70968629/218487702-4d2901d9-9025-4bf5-88f6-d851fb621c24.png)
