### ISSUE TITLE
[Starting view. Courier field] The ‘Select courier’ placeholder is not displayed in the `Courier` drop-down list after changing the language to English

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4805]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Preconditions:

    User is logged in as Admin.
    Side bar menu :[https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders] is oppened 

**Steps to reproduce**
1. Click on the 'Uk' drop-down menu (upper right side) and choose the `En` item 
2. Click on 'Tariffs' bttn in the side bar menu

**Actual result**
The ‘Select courier’ placeholder is not displayed in the `Courier` drop-down list after changing the language to English
Attached bug screenshots recorded.

**Expected result**
All drop-down menus are displayed with a placeholders after clicking on `Tariffs` bttn

**User story and test case links**
E.g.: "Starting view for the pricing page ("Тарифи") #3835"
[Test case](https://jira.softserve.academy/browse/GC-3392)"

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI, "Functional")
![d1](https://user-images.githubusercontent.com/116261833/207054972-35dfd1a0-4083-48f7-b337-673548dd4390.png)
")

**Comment by atsa21** [comment]
Not reproduce
