### ISSUE TITLE
[Pricing Page. Admin cabinet. Gear. Add location] Sometimes it is possible to add invalid city in the filed 'Місто'

### ISSUE THREAD

**Issue by SapegaYulia** [ita-social-projects/GreenCity#4806]
**Environment:** Windows 10, Opera.
**Reproducible:** sometimes.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
1. The user should be authorized as admin
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
3. Main UBS menu - page 'Тарифи' should be opened.

**Steps to reproduce**
1. Click on 'Gear' - "Додати" - "Локація"
2. Fill out the field 'Область' by valid data
3. Start typing the city that is not related to the region, chosen in the field 'Місто'
4. Tab on the link 'Додати місто'
**Actual result**
Actual result: The city is added.

**Expected result**
The city is not added, the error message appears 'На жаль, місто не знайдено. Введіть ще раз'

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
