### ISSUE TITLE
[Starting view. Region field] Duplicate values are displayed in the 'Region' drop-down menu after changing the language to English

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4807]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

Preconditions:

    User is logged in as Admin.
    Tariffs panel is opened:[ https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs|https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs]
EN locale is set for the page.

**Steps to reproduce**
1. Click on the  'Region' field
2. Click on the 'All' bttn

**Actual result**
The same names of the regions are displayed in the 'Region' drop-down menu after changing the language to English
Attached bug screenshots recorded.

**Expected result**
An unique values are displayed  in the 'Region' drop down menu after changing the language to English

**User story and test case links**
E.g.: "Starting view for the pricing page ("Тарифи") #3835 "
[Test case](https://jira.softserve.academy/browse/GC-4154#)"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: medium"), Type ("Functional")
![dd](https://user-images.githubusercontent.com/116261833/207085228-8a6cd0c8-caa4-4cd0-8176-ce90c6c7501c.png)
![dd2](https://user-images.githubusercontent.com/116261833/207085232-13f8eedc-e970-40f8-8c7e-9926934f1f18.png)

**Comment by atsa21** [comment]
Need to remove unused regions - Controller GET  https://greencity-ubs.testgreencity.ga/ubs/superAdmin/getLocations
KEEP region with id 1 - 'Київ, Київська область'

**Comment by OlegVat** [comment]
After investigating, there seems to be a bug in the frontend component. The data duplication issue does not occur in the backend request. Instead, it occurs following a localization change, where the data is repeatedly appended to the dropdown.

**Comment by Olena-Kharkova** [comment]
Colleagues, please, consider this issue. I return it to the Bugs column because it has not been resolved yet 

![aq9HhjtFms](https://user-images.githubusercontent.com/110603507/222968678-326248fa-a461-46f7-a694-fc3d917f56c9.png)

**Comment by DanaIuich** [comment]
Bug is fixed
