### ISSUE TITLE
[Starting view. Region field] Names of the cities are displayed in the 'Region' drop-down menu of `Tariffs` field

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4808]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**

    User is logged in as Admin.
    Tariffs panel is opened:[ https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs|https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs]

**Steps to reproduce**
1. Tap the 'Region' field 
2. Click on 'All' bttn

**Actual result**
Names of the cities are displayed in the 'Region' drop down menu of `Tariffs` page

**Expected result**
Only regions names are displayed in the 'Region' drop down menu of `Tariffs` page

**User story and test case links**
E.g.: Starting view for the pricing page ("Тарифи") #3835
[Test case](https://jira.softserve.academy/browse/GC-4154#)"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:"medium), Type ("Functional")
![d3](https://user-images.githubusercontent.com/116261833/207064860-b15625ca-45c1-49cd-96cb-085e6122819f.png)

**Comment by atsa21** [comment]
Not reproduce
