### ISSUE TITLE
[Starting view. City field] Duplicate values are displayed in the 'City' drop-down menu after changing the language to English

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4809]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
 User is logged in as Admin.
    Tariffs panel is opened:[ https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs|https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs]
EN locale is set for the page.

**Steps to reproduce**
1. Click on the  'City' field
scenario 1
2. Type `Lv` data
![d7](https://user-images.githubusercontent.com/116261833/207071154-57bef988-8f13-4b52-93bd-c5d565deb229.png)

scenario 2
2. Type `Dr` data
![dro](https://user-images.githubusercontent.com/116261833/207072990-42de0e36-6417-4917-8854-b56b41b72bb1.png)

**Actual result**
The same names of the cities are displayed in the 'City' drop-down menu after changing the language to English 

Attached bug screenshots recorded.

**Expected result**
An unique values are displayed in the 'City' drop-down menu after changing the language to English

**User story and test case links**
E.g.: "Starting view for the pricing page ("Тарифи") #3835
[Test case](https://jira.softserve.academy/browse/GC-4155)"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: medium"), Type ("Functional", "Localization")

**Comment by OlegVat** [comment]
I checked, and most likely, it is a bug in the frontend part. The request to the backend does not duplicate the data. It is sent after the localization change and repeatedly adds the data to the dropdown.

**Comment by katia9261** [comment]
Bug is not reproduced 
![image](https://user-images.githubusercontent.com/101433204/231387377-6087f463-8569-4743-a64a-a1f7b32815b8.png)
