### ISSUE TITLE
BUG [UI] 'Password' and 'Confirm password' textboxes and 'Sign-in with Google' button size is not matched with the size of 'First name, Last name','Email' textboxes

### ISSUE THREAD

**Issue by Marie1360** [ita-social-projects/GreenCity#481]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Verify the size of text boxes on the 'Sign Up' page
**Actual result:**
'Password' and 'Confirm password' textboxes and 'Sign-in with Google' button size is not matched with the size of 'First name, Last name','Email' textboxes
**Expected result:**
'Password' and 'Confirm password' textboxes and 'Sign-in with Google' button size is matched with the size of 'First name, Last name','Email' textboxes according to mockup
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
Google Chrome Version 80.0.3987.132(64-bit)
#385
![text box size](https://user-images.githubusercontent.com/61519117/75891093-ba088c00-5e48-11ea-819d-979107f7798d.png)
![textbox mockup](https://user-images.githubusercontent.com/61519117/75891138-ca206b80-5e48-11ea-86ea-ac69cb399610.png)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
