### ISSUE TITLE
[Starting view. City field] The wrong spelled `Drohobych` city is displayed in the 'City' drop-down menu after changing the language to English

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4810]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
User is logged in as Admin.
Tariffs panel is opened:[ https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs|https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs]
EN locale is set for the page.

**Steps to reproduce**
1. Click on the 'City' field
2. Type `Dr` data

**Actual result**
The `Drogobichh` city is displayed instead of `Drohobych` in the 'City' drop-down menu after changing the language to English

**Expected result**
The right spelled `Drohobych` city is displayed in the 'City' drop-down menu after changing the language to English

**User story and test case links**
E.g.: "Starting view for the pricing page ("Тарифи") #3835
[Test case](https://jira.softserve.academy/browse/GC-4154#)"

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI")
![d6](https://user-images.githubusercontent.com/116261833/207079575-648d2ab0-dccd-47ce-995b-a1c8b937f80d.png)

**Comment by atsa21** [comment]
Not reproduce
