### ISSUE TITLE
[Starting view. City field] English titles of the cities are displayed in the 'City' drop-down menu after changing the language to Ukrainian

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4811]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
User is logged in as Admin.
Tariffs panel is opened:[ https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs|https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs]
UK locale is set for the page.

**Steps to reproduce**
1. Click on the 'City' field
2. Scroll down the list

**Actual result**
English titles of the cities are displayed in the 'City' drop-down menu after changing the language to Ukrainian

**Expected result**
All titles are displayed in Ukrainian in the 'City' drop-down menu after changing the language to Ukrainian

**User story and test case links**
E.g.: "Starting view for the pricing page ("Тарифи") #3835
[Test case](https://jira.softserve.academy/browse/GC-4156"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: medium"), Type ("Localization, "Functional")
![loca](https://user-images.githubusercontent.com/116261833/207081857-da97ddfb-2393-474e-91d1-90b2f405263d.png)

**Comment by atsa21** [comment]
Not reproduce
