### ISSUE TITLE
[Pricing page. Admin. Gear. Add location.] The new city doesn't appear in the list of cities if not to reload the page.

### ISSUE THREAD

**Issue by SapegaYulia** [ita-social-projects/GreenCity#4812]
**Environment:** Windows 10, Opera
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**

1. The user should be authorized as admin
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
3. Main UBS menu - page 'Тарифи' should be opened.

**Steps to reproduce**
1. Click on 'Gear' - "Додати" - "Локація"
2. Fill out the field 'Область' by valid data
3. Start typing the city that is related to the region, chosen in the field 'Місто'
4. Tab on the link 'Додати місто'
5. Press button 'Додати'

**Actual result**
Actual result: The popup is closed. The city is not added to the list of cities untill reloading the page.

**Expected result**
The popup is closed. The city is added to the list of cities without reloading the page.

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**User story and test case links**
E.g.: "User story #3859
[Test case](https://jira.softserve.academy/browse/GC-4173)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by atsa21** [comment]
Duplicate #4821
