### ISSUE TITLE
/[Starting view. City field] Ukrainian titles of the Receiving stations are displayed in the 'Receiving station` drop-down menu after changing the language to English

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4816]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
User is logged in as Admin.
Tariffs panel is opened:[ https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs|https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs]
En locale is set for the page.

**Steps to reproduce**
1. Tap the  'Receiving station' field
2. Verify the 'All' field 

**Actual result**
Ukrainian titles instead of English titles of the Receiving stations are displayed in the 'Receiving station` drop-down menu after changing the language to English

**Expected result**
English titles of the Receiving stations are displayed in the 'Receiving station` drop-down menu after changing the language to English
Attached screenshots  if available.

**Starting view for the pricing page ("Тарифи") #3835**

[Test case](https://jira.softserve.academy/browse/GC-4157)"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: medium"), Type ("Functional", "Localization")
![Uploading d8.png…]()

**Comment by atsa21** [comment]
Not a bug
