### ISSUE TITLE
[BUG] 'Sign Up' button is disabled on 'Sign Up' popup after leaving the fields empty

### ISSUE THREAD

**Issue by Marie1360** [ita-social-projects/GreenCity#482]
**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Leave the fields empty
3. Look at 'Sign Up' button display
**Actual result:**
'Sign Up' button is disabled on 'Sign Up' popup after leaving the fields empty
**Expected result:**
'Sign Up' button should be always enabled on 'Sign Up' popup according to mockup
Note: Button is also disabled when invalid valuea are entered in the fields
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
#385 
![Sign up disabled](https://user-images.githubusercontent.com/61519117/75895759-8a10b700-5e4f-11ea-8e34-6d13ead3cb09.png)
![sign up mockup](https://user-images.githubusercontent.com/61519117/75895823-9ac12d00-5e4f-11ea-9137-a7e7caeb3dbf.png)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
