### ISSUE TITLE
[Pricing Page. Admin cabinet. Gear. Add location] New city doesn't appear on the drop-down list of the specified field 'Місто' on the page 'Тарифи' after creating new location

### ISSUE THREAD

**Issue by Oryshchakb** [ita-social-projects/GreenCity#4821]
**Environment:** Google Chrome Версія 107.0.5304.88 (64-розрядна версія); Windows 10 Pro.
**Reproducible:** always.

**Preconditions**
1. The user should be authorized as SuperAdmin
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
3. Main UBS menu - page 'Тарифи' should be opened.

**Steps to reproduce**
1. Click on 'Gear' - "Додати" - "Локація"
2. Fill out the field 'Область' by valid data
3. Start typing and choose the city in drop down list that is related to the region, chosen in the field 'Місто'
4. Tab on the link 'Додати місто'
5. Press the bttn 'Додати'
6. Check if the new city added to  the drop-down list of the specified field 'Місто' on the page 'Тарифи'

**Actual result**
New city doesn't appear on the drop-down list of the specified field 'Місто' on the page 'Тарифи'

**Expected result**
New city should appear on the drop-down list of the specified field 'Місто' on the page 'Тарифи'

**User story and test case links**
E.g.: "User story #3859
[Test case](https://jira.softserve.academy/browse/GC-4120)"
[Test case](https://jira.softserve.academy/browse/GC-4113)"
**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: minor"), Type ("UI, "Functional").
![_thumb_416039](https://user-images.githubusercontent.com/116262018/207163713-cc685cee-9beb-4c71-9910-f0028d1abe53.png)

![_thumb_416040](https://user-images.githubusercontent.com/116262018/207163641-95fbecfa-4e6c-4105-af0a-b98a01e2bff9.png)

**Comment by atsa21** [comment]
Not reproduce

**Comment by DanaIuich** [comment]
Bug is fixed
