### ISSUE TITLE
[Starting view. Region field] The `Cross` redundant element is displayed in the `Region` field not according with mockup

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4822]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
User is logged in as Admin.

**Steps to reproduce**
1. Click on the 'Taрифи' bttn of side menu  bar
2. Pay attention on the `Region` field

**Actual result**
The `Cross` redundant element is displayed in the `Region` field not according with the mockup
Attached bug screenshots recorded.
![mmmm](https://user-images.githubusercontent.com/116261833/207180972-06f47e94-4ddf-4fbb-a06d-3eb85b16eb64.png)

**Expected result**
All fields are displayed according with the mockup
![mmm](https://user-images.githubusercontent.com/116261833/207180827-8ed5940b-84a8-47b6-932c-ecca6a61b15b.png)

**Starting view for the pricing page ("Тарифи") #3835**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/GC-4154#"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: low"), Type ("UI, "Functional")

**Comment by marianaharnyk** [comment]
It's feature. We can easily clear this field with this cross
