### ISSUE TITLE
[Starting view. Tariffs] Overlapping elements are displayed in the all drop-down menus of the `Tariffs` page after zooming window change by 175%

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4823]
**Environment:** Windows 11
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** 12.12.2022

**Preconditions**
User is logged in as Admin.

**Steps to reproduce**
1. Click on the 'Taрифи' bttn of side menu bar
2. Zoom to 175%

**Actual result**
Overlapping elements are displayed in the all drop-down menus of the `Tariffs` page after zooming window change by 175%
![si](https://user-images.githubusercontent.com/116261833/207184300-34abc36f-ea09-457d-8a47-b3c7a4bb5b8d.png)

**Expected result**
All elements are displayed according to the mockup
![mmm](https://user-images.githubusercontent.com/116261833/207184330-b6d0914c-36a4-4cb5-b8f1-8b69379b7806.png)

**Starting view for the pricing page ("Тарифи") #3835**

[Test case](https://jira.softserve.academy/browse/GC-3392"

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI,)

**Comment by marianaharnyk** [comment]
Duplication of #4814 
This bug was fixed
