### ISSUE TITLE
[Tariffs_Deactivate cards] The dropdown list of regions has alignment above the regions field instead of under alignment on the pop-up window  "Деактивувати" 

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#4835]
**Environment:** 
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 15/12/2022

**Preconditions**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. The user is logged in as Super Admin.
3. Go to Main UBS menu -> Choose "Тарифи”
4. Click on tools “Gear”-> item “Деактивувати”.

**Steps to reproduce**

1. Choose item "Регіон" 
2. Click on the dropdown pictogram 
3. Pay attention to the alignment of the dropdown list of regions  

**Actual result**
The dropdown list of regions has alignment above the regions field instead of under alignment on the pop-up window  "Деактивувати" 

**Expected result**
The dropdown list of regions has alignment under the regions field  on the pop-up window  "Деактивувати" 

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri:low"), Severity ("severity:minor"), Type ("UI, "Functional"), "API" (for back-end bugs).

![gJdLmOGJ09](https://user-images.githubusercontent.com/110603507/207873475-b74c7fe9-8cd4-4a70-acc2-3024416a11f4.png)

**Comment by katia9261** [comment]
The bug is not reproduced
![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/8a776918-2257-4fed-a3a7-eedee9f9e000)
