### ISSUE TITLE
[My habits] On the habit's card missing the "Mark as done" button

### ISSUE THREAD

**Issue by OlenaPorosiuk** [ita-social-projects/GreenCity#4841]
Environment: Windows 11, Google Chrome Версія 108.0.5359.99:
Mac OS 13.0.1; Google Chrome 108.0.5359.99
Reproducible: sometimes 
On Google Chrome 108.0.5359.125 - the bug does not show

Pre-conditions: 
• User should have at least one habit in progress
• The habit is not marked as done for a current day

Steps to reproduce:
1. Go to - https://www.testgreencity.ga/GreenCityClient/
2. Login with an existing user account
3. Open the My habits page
4. Click on the "Mark as done" button on the habit's in progress card

Actual Result: There is no "Mark as done" button. The "Great! You've got a habit!" reproduced instead.

Expected Result: There is enable "Mark as done" button. After clicking the button is changed to the "Done" button.

User story: 
- [My Habits] View list of habits on My habits page [#988 ](https://jira.softserve.academy/browse/GC-1805)
- [My habits] Edit / "mark as done" my own habits in progress[ #990 ](https://jira.softserve.academy/browse/GC-1806)

Test case: 
- [My habits] Verify contents of the card Habit in progress when habit is collective (https://jira.softserve.academy/browse/GC-4248)
- [My habits] Verify that the user can mark the habit as done on 'My habits' page (https://jira.softserve.academy/browse/GC-4193)

Defects:
- [My habits] On the habit's card missing the "Mark as done" button (https://jira.softserve.academy/browse/GC-4253)
- [My Habits] The "Mark as done" button on the habit's card is missed (https://jira.softserve.academy/browse/GC-4378)

![bug mark as done](https://user-images.githubusercontent.com/120177384/208106463-0ce7c860-6734-4fb6-8abc-43e2e6283b94.png)
![Mark as done](https://user-images.githubusercontent.com/120177384/208106497-da8a7546-a48e-4ca8-a0f5-93d9ce4cf0c8.png)

https://user-images.githubusercontent.com/120177384/208106529-88913225-70e9-4dc1-9d59-9fdebdc3fd28.mp4

<img width="1183" alt="_thumb_416059" src="https://user-images.githubusercontent.com/120177384/208107687-4f754da4-85ff-4da8-9929-983936d8aeb5.png">

**Comment by atsa21** [comment]
Duplication #4499
