### ISSUE TITLE
[BUG] #66 Title and arrow are not aligned on 'Sign in with Google' button on 'Sign in' pop-up

### ISSUE THREAD

**Issue by nuclearyana** [ita-social-projects/GreenCity#485]
**Steps to reproduce:**

1. Go to Green City application
2. Click 'Sign in!' link
3. Verify arrow and 'Sign in with Google' title alignment of 'Sign in with Google' button
**Actual result:**
'Sign in with Google' title is shifted up.
Arrow is shifted down
**Expected result:**
All elements of 'Sign in with Google' button are aligned according to mockup

Environment:
OS: Windows 10
Browser: Mozilla Firefox 73.0.1 (64-bit)
![Untitled](https://user-images.githubusercontent.com/61509126/75901419-22566e00-5e47-11ea-940d-a4a029ff913c.png)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
