### ISSUE TITLE
[Create pricing card] Date is not translated into EN language in the pop-up window "Create  card"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#4850]
**Environment:** Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always, .
**Build found:** 17/12/22

**Preconditions**

1. Go to: https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
2. Logged in as Admin
3. Go to page "Тарифи" and click on "gear" pictogram

**Steps to reproduce**
Choose EN language and check translations of all elements and UI controls
**Actual result**
Date is not translated into EN language in the pop-up window "Create  card"
**Expected result**
All elements in the pop up window is translated.

**User story and test case links**
E.g.: "User story #4202

**Labels to be added**
"Bug", Priority ("pri: Low), Severity ("severity:minor), Type ("Localization)
<img width="534" alt="Знімок екрана 2022-12-17 о 17 37 11" src="https://user-images.githubusercontent.com/116280846/208249584-58a477b4-1082-40eb-9036-e424f8dc1de8.png">

**Comment by atsa21** [comment]
Not reproduce
