### ISSUE TITLE
[All Habits] Tooltip doesnt appear and cursor isnt visual clickable when user moves mouse over 'List view' and 'Gallery view' button[Affected functionality] Clear and concise summary, e.g. "[Create news] 'Publish' button is not displayed on the 'Preview' page"

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#4853]
Environment: Windows 10 Home, 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Reproducible: always
Build found: Ver1.0

**Precondition:**

1.Goto https://www.testgreencity.ga

2.Login as a registered user

3.Goto page 'My Space'

4.Click on 'Add habit' button

5.Move Mouse over View as a List button on the right side of the page

**Actual result:**

Nothing happened 

**Expected result:**

Tool tip is expected to appear and cursor is changed to clickable

**User story and test case links**
User story #1231 , #1232

**Comment by darinadobrukha** [comment]
A tool tip is not appearing for 'list view' and 'gallery view', and cursor is changing only for 'list view'.

**Comment by atsa21** [comment]
@darinadobrukha 
User story #1231  , #1232   don't have any description about tooltip on hover. Cursor is changed on hover when it view is currently not selected

**Comment by darinadobrukha** [comment]
@atsa21 so I thought. in this case bug report is irrelevant, but it was in 'bugs retesting'. should it be moved to 'done' or..?

**Comment by darinadobrukha** [comment]
@atsa21 currently cursor is chenging for both when 'list view' is selected, and only for 'list' icon when 'gallery view' is celected.

**Comment by atsa21** [comment]
@darinadobrukha Oh, I see now what you mean. I will fix it to cursor hover only for not selected view
