### ISSUE TITLE
[Add a service "Послуга"] The  “Скасувати“ word is missing in the validation message after the User clicking on the “Скасувати” bttn 

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4856]
**Environment:** Windows 11
Google Chrome 108.0.5359.9
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**

Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
Sign in as SuperAdmin
Click on the “Tарифи" bttn

**Steps to reproduce**
1. Type the valid data in the "Область" drop-down
2. Type the valid data in the "Місто" drop-down
3. Click by the pricing card
4. Click on the "Додати послугу" bttn
5. Click on the "Скасувати" bttn

**Actual result**
The  pop-up window with the “Ви дійсно хочете скасувати внесені зміни? ” validation message is displayed after User clicks on the “Скасувати” bttn
![skas](https://user-images.githubusercontent.com/116261833/208405184-9f290109-5120-4747-93da-11884e5758ae.png)

**Expected result**
The  pop-up window with the “Скасувати. Ви дійсно хочете скасувати внесені зміни? ” validation message is displayed after User clicks on the “Скасувати” bttn
![sk](https://user-images.githubusercontent.com/116261833/208405202-22918026-35f0-46e9-abbe-0de468e9277a.png)

**User story and test case links**
E.g.: "User story #4366 
[Add a service "Послуга"] Verify that the validation message is occurs after the User clicking on the “Скасувати” bttn"

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: trivial"), Type ("UI, "Functional")

**Comment by katia9261** [comment]
The bug is not up to date
![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/d2a8a114-58b3-493f-8fff-f81656aacbc3)
