### ISSUE TITLE
[Add a service "Сервіс"] The “Скасувати“ word is missing in the validation message after the User clicking on the “Скасувати” bttn

### ISSUE THREAD

**Issue by HannaKedys** [ita-social-projects/GreenCity#4857]
**Environment:** Windows 11
Google Chrome 108.0.5359.9
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
Sign in as SuperAdmin
Click on the “Tарифи" bttn

**Steps to reproduce**
Type the valid data in the "Область" drop-down
Type the valid data in the "Місто" drop-down
Click by the pricing card
Click on the "Додати Сервіс" bttn
Click on the "Скасувати" bttn

**Actual result**
The pop-up window with the “Ви дійсно хочете скасувати внесені зміни? ” validation message is displayed after User clicks on the “Скасувати” bttn 
![skas](https://user-images.githubusercontent.com/116261833/208405698-d5b47291-e0df-4f3f-830f-c34b35911830.png)

Pay attention that the same word is absent in the En translation

**Expected result**
The pop-up window with the “Скасувати. Ви дійсно хочете скасувати внесені зміни? ” validation message is displayed after User clicks on the “Скасувати” bttn
![sk](https://user-images.githubusercontent.com/116261833/208405751-9a4fd025-a215-43c5-be07-415123c32a45.png)

**User story and test case links**
E.g.: "[Add a service "Сервіс" ] Verify that the “Скасувати” pop-up window is correctly displayed in English"

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trivial"), Type ("UI, "Functional")

**Comment by katia9261** [comment]
The bug is not up to date
![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/9b2efa78-db88-4b17-a611-5b597f5b9aec)
