### ISSUE TITLE
[BUG] #66 'View/hide password' icon is outside the 'Password' field on 'Sign in' pop-up

### ISSUE THREAD

**Issue by nuclearyana** [ita-social-projects/GreenCity#486]
**Steps to reproduce:**

1. Go to Green City application
2. Click 'Sign in!' link
3. Verify 'View/hide password' icon placement
**Actual result:**
'View/hide password' icon is placed outside the 'Password field
**Expected result:**
'View/hide password' icon should be placed inside the 'Password field
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 73.0.1 (64-bit)
![sergthyjukilo;p](https://user-images.githubusercontent.com/61509126/75902725-2aafa880-5e49-11ea-9c30-6649e1ac7e82.png)

**Comment by rsyvulko** [comment]
Verified
