### ISSUE TITLE
[Pricing card. Add a service] User can't type decimal number in fields "Об'єм", "Комісія", "Базова вартість" in "Додати сервіс" 

### ISSUE THREAD

**Issue by Oryshchakb** [ita-social-projects/GreenCity#4863]
**Environment:** Google Chrome Версія 107.0.5304.88 (64-розрядна версія); Windows 10 Pro.
**Reproducible:**  often.

Preconditions
The user should be logged in as a Super Admin
Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
Main UBS menu - page 'Тарифи' should be opened.
Go to any existing card

Steps to reproduce

Click on "Додати сервіс"
In fields "Об'єм" type decimal number "5.4"
In fields "Комісія" type decimal number "2,28"
In fields "Базова вартість" type decimal number "14.48"

**Actual result**
User can't type decimal number in fields "Об'єм", "Комісія", "Базова вартість" in "Додати сервіс" 

**Expected result**
User can type decimal number in fields "Об'єм", "Комісія", "Базова вартість" in "Додати сервіс" 

![image](https://user-images.githubusercontent.com/116262018/208513638-aec98c86-a1d0-4550-8c29-f39ed6b02999.png)

**User story and test case links**
E.g.: "User story #4428

**Comment by Olena-Kharkova** [comment]
The bug is not completely fixed 
![Wldra3pbhQ](https://user-images.githubusercontent.com/110603507/218131784-38efa1a6-1c1a-4e18-a704-d72078977606.png)

**Comment by Olena-Kharkova** [comment]
fixed 
![image](https://user-images.githubusercontent.com/110603507/218315300-8967ce8b-6164-4a98-b28f-3535a7d4749a.png)
