### ISSUE TITLE
BUG[USER]Validation of the 'First name' field does not occur on the 'Sign up' pop-up window after clicking on the "Sign up" button

### ISSUE THREAD

**Issue by KaterynaIlkiv** [ita-social-projects/GreenCity#487]
Step to reproduce:
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Leave the 'First name' field empty
3. Enter valid data to 'Last name','Email','Password','Confirm password' fields
4. Click on the 'Sign up' button
5. Look at the 'First name' field

Actual results: Validation of the 'First name' field does not occur on the 'Sign up' pop-up window after clicking on the "Sign up" button
Expected results: Validation of the 'First name' field should occur automatically. The 'First name' should highlight in red and the error message appears on the 'Sign up' pop-up window after leaving field empty.

#385

**Comment by nabermi2020** [comment]
Not relevant
