### ISSUE TITLE
[Pricing page. Admin. Limits] It is possible to type in the second filed lower number than in the first field.

### ISSUE THREAD

**Issue by SapegaYulia** [ita-social-projects/GreenCity#4870]
**Environment:** Windows 10, Opera
**Reproducible:** always
**Build found:** 23.12.2022 https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
1. User should be logged in as an admin
2. User should have at least one pricing card.
3. E.g.:
"Create an item in the database using SQL query:
INSERT INTO table1 (column1, column2)
VALUES (value1, value2);"

**Steps to reproduce**
1. Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs/location/1)
2. Click on radio buttons limits 'Сума замовлення' or 'Кількість пакетів'
3. Type number 10 in the first related filed.
4. Type number 8 in the second related field.
5. Repeat with another limit.
**Actual result**
It is possible to type in the second field lower number than in the first field.
Attached bug screenshots or video recorded.
![image](https://user-images.githubusercontent.com/116288875/209324267-54c9901c-e753-4810-9cd4-a8bf20b3d879.png)
![image](https://user-images.githubusercontent.com/116288875/209324336-1aa734ce-7dcb-48af-bd99-dd5143cb75c3.png)

**Expected result**
It is impossible to type in the second field lower number than in the first field.
Attached screenshots or mock-ups if available.

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:

**User story and test case links**
E.g.: "User story #4429 
[Test case][(https://jira.softserve.academy/browse/100)](https://jira.softserve.academy/browse/GC-4471)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by DanaIuich** [comment]
After typing in the second field lower number than in the first field there is no error message about the impossibility of entering a lower value
<img width="312" alt="No_error_message" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/bff19454-5248-449b-b50a-1e055ddab262">
