### ISSUE TITLE
[Habit's page] There is no progress value in the progress bar

### ISSUE THREAD

**Issue by TanchynIryna** [ita-social-projects/GreenCity#4871]
Environment: Mac OS 13.0.1, Google Chrome 108.0.5359.98
Reproducible: always 
Build found: 21.12.22

Preconditions:
- The user has habit in progress

Steps to reproduce:
1. Go to https://www.testgreencity.ga/GreenCityClient/
2. Login with user account
3. Open the My habits page
4. Click on the edit sign on the habit's card (mock-up below)
<img width="587" alt="editsign" src="https://user-images.githubusercontent.com/119937824/209483125-6b6809ab-e36e-481f-85b7-e32c1e7fc976.png">
5. To the right of the calendar is a progress bar (mock-up below)
<img width="581" alt="actualprogbar" src="https://user-images.githubusercontent.com/119937824/209483124-8d960a07-dda8-4305-a0eb-a1460cbf3985.png">

Actual result: Label: The progress bar does not show the progress value in %

Expected result: The progress bar shows the progress value in % (mock-up below) 
<img width="408" alt="expprogbar" src="https://user-images.githubusercontent.com/119937824/209483123-5f491d2c-e7e4-4126-bc80-b4063ef95087.png">

User story: [My habits] Edit / "mark as done" my own habits in progress #990 
Test case:  [My habits] Verify that the user can see his tracking progress on the progress bar https://jira.softserve.academy/browse/GC-4476

**Comment by BelakorGit** [comment]
Bug is reopened as the progress bar percent's are displayed when user point the cursor of the mouse on it and according to the req. #990 acceptance criteria 10 it should be already displayed.

**Comment by katia9261** [comment]
This issue is not actual because of the Change request https://github.com/ita-social-projects/GreenCity/issues/5175
