### ISSUE TITLE
BUG [USER] 'About' button on the menu block is dissabled on the registration page when the Tabulation is used

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#488]
**Steps to reproduce:**

1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the "Sign up" link in the upper corner
3. Verify the tabulation on the 'About' button
**Expected Result:**
Buttons and links are selected while tabulation is used
**Actual Result:**
The 'About' button is not tabulated on the registration page

**Environment**: Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultimate
#352

**Comment by KimAT25** [comment]
Not relevant
