### ISSUE TITLE
BUG: User is redirected to the 'Sign in' page after clicking on the home app link

### ISSUE THREAD

**Issue by fil2002** [ita-social-projects/GreenCity#489]
Steps to reproduce:

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Look at the page opened

Actual result:
User is redirected to the 'Sign in' page instead of home page after clicking on the home app link
Expected result:
The home page is shown after clicking on the home app link

Environment:
OS: Windows 10
Browser: Mozilla Firefox 73.0.1 /64 біт

**Comment by nabermi2020** [comment]
Not relevant
