### ISSUE TITLE
[UBS. Order form] User cannot edit the data in fields "Вулиця" or "Район" on the pop up window "Змінити адресу" in Step 2 "Personal data"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#4896]
Environment:.MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

Reproducible: always,
**Build found:** 4/01/2023
**Preconditions**
The user should be authorized
Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
The page 'UBS-Курє'р' is opened
Click on bttn " Замовити"
Select a location from the drop-down menu and click bttn"Продовжити"

**Steps to reproduce**

1. fill in all fields with valid data in Step 1 "Order details"
2. Click on bttn "Далі"
3. Find the address that the user left previously
4. Click on the " item Pencil " on the side next to the address text
5. Select another street  or area the fields "Вулиця"  or "Район"
6. Click bttn "Зберегти зміни"  
 **Actual result**
user cannot edit the data in field "Вулиця" on the pop up window "Змінити адресу" in Step 2 "Personal data"
**Expected result**
user can edit the data in field "Вулиця" on the pop up window "Змінити адресу" in Step 2 "Personal data"

E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("pri: medium), Severity ("severity:"major," )Type (" "Functional"), 

https://user-images.githubusercontent.com/116280846/210521987-274de462-2a23-4bb3-919f-ecf9a8c6863a.mov

**Comment by marianaharnyk** [comment]
Cannot be reproduce
