### ISSUE TITLE
[UBS. Order form] The system does not display the correct "Район" when user select "Район"  in Step 2 "Personal data" 

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#4898]
**Environment:.MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

Reproducible: always,
Build found: 4/01/2023
**Preconditions**
The user should be authorized
Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
The page 'UBS-Курє'р' is opened
Click on bttn " Замовити"
Select a location from the drop-down menu and click bttn"Продовжити"
**Steps to reproduce**

1. . Fill in all fields with valid data in Step 1 "Order details"
2.   Click on bttn "Далі" 
3.   Click on the link " Додати іншу адресу"
4. . Fill in all fields: Вулиця,Будинок ,Корпус ,Під'їзд 
5. . Select "Район" (For  example : Голосіївський )
6.  Click on bttn "Додати адресу"
7. . Check add address Pay attention "Район"on the  Step 2 "Personal data" 

**Actual result**
The system does not display the correct "Район" when user select "Район"  in Step 2 "Personal data" 
**Expected result**
The system does  display the correct "Район" when user select "Район"  in Step 2 "Personal data" 

**User story and test case links**
E.g.: "User story #2199

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:major"), Type ( "Functional"), .

https://user-images.githubusercontent.com/116280846/210544296-f9dee8ec-b28f-4c60-9b9c-8b8f14afd9e6.mov

**Comment by HalynaChornevych** [comment]
The error cannot be reproduced. It is impossible to place a new order (the number in the "house" field in the order address is not accepted)
