### ISSUE TITLE
Save places to Favorites

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#49]
As a registered user I want to be able to add available places to Favorites, so that I can easily find them in one convenient place.

**Acceptance Criteria:**

1. Provided a registered user opens a Detail View pop-up of a place on the map (by clicking on a place on the map), system shall display a Star (i.e. Favorites) icon (white, unfilled with color) at the top right corner of the pop-up.
2. GIVEN the Star icon is unfilled with color, WHEN user clicks on it, THEN system shall fill the Star icon with color (yellow) AND save the place to the user's Favorites list.
3. GIVEN the Star icon is filled with color (yellow), WHEN user clicks on it, THEN system shall make it unfilled with color (blank) AND remove the place from the Favorites list.
4. Provided a registered user has at least one saved favorite place, system shall display "Favorites" button near the map.
5. Provided user clicks on "Favorites" button, system shall open the Favorites modal pop-up (over the map) which shall include:
a. header "Favorite places"
b. list of all user's saved favorite places.
6. Provided user clicks on a place from the Favorites list, system shall
a. close the modal pop-up
b. display this place as selected on the map

7. Only on place can be selected at a time.

8. Available actions for user within the Favorites screen shall include:
a. edit name of saved place, by clicking on "Edit" button next to a place. Max number of characters for a name = 30
b. delete saved place, by clicking on "Delete" button next to a place

**Assumptions and Constraints:**
1. related to #26 
2. TBD - provided user has a list of saved favorite places - they shall be displayed on a map by a star icon (instead of default icon) - **separate story #167**

**Comment by rsyvulko** [comment]
Not relevant.
