### ISSUE TITLE
Not all special characters are accepted as valid in the 'Password' field on the registration page

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#491]
**Steps to reproduce:**

1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Fill 'First Name', 'Last Name', 'Email' fields with valid data
3. Fill 'Password' with valid value using at least one character of Uppercase letter (A-Z), Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.).  
4. Pay attention to the password with special character '-'  _e.g.789-456-Aa_
**Expected Result:**
All special characters are accepted as valid value of the password
**Actual Result:**
The special character '-' is an invalid value of the password on the registration page
The 'Password has contained at least one character of Uppercase letter (A-Z), Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.).' warning message is shown
**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultimate
#385

**Comment by Talichka** [comment]
![password](https://user-images.githubusercontent.com/40841118/75920818-c7357300-5e68-11ea-8af4-50dd254c940f.png)

**Comment by rsyvulko** [comment]
Verified
