### ISSUE TITLE
[UBS user.Order. Step 1] Bonuses calculation provides incorrect after changing the number of services and clicking the "Так"/ "Ні" radio button of bonuses choosing 

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#4913]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 05/01/2023

**Preconditions**
1. The registered user is logged in
2. The user has filled all needed fields in 1 step
3. The user used bonuses and certificates for full covering payment of the order 

**Steps to reproduce**
1. The user changes a number of services by pickers (adding more services in the order)
2.  The user chooses "Ні" in adding bonuses and chooses "Так"
3. Pay attention to the calculation of bonuses. 

**Actual result**
Bonuses calculation provides incorrect after changing the number of services and clicking the "Так"/ "Ні" radio button of bonuses choosing 

**Expected result**
Bonuses calculation provides correctly after changing the number of services and clicking the "Так"/ "Ні" radio button of bonuses choosing 

**User story and test case links**
E.g.: "User story #3478

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:minor"), Type ("Functional")

https://user-images.githubusercontent.com/110603507/210769984-90f7bb11-9fef-479b-aa5a-d524dd81a65a.mp4

**Comment by Tadei-Mykola** [comment]
Can not reproduce
