### ISSUE TITLE
Warning message is not displayed when password and confirmation password don't match on the registration page

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#492]
**Steps to reproduce:**

1.  Go to the https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Fill 'First Name', 'Last Name', 'Email' fields with valid data
3. Fill 'Password' with valid value using at least one character of Uppercase letter (A-Z), Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.). e.g.789-456-Aa
4. Fill the 'Password Confirm' field with a differing value, e.g. 789-456Aa
**Expected Result:**
Warning message 'Passwords don't match' is shown when password and confirmation password is different on the registration page
**Actual Result:**
The warning message is not shown and invalid data of password is confirmed
**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultimat
#385

**Comment by Talichka** [comment]
![password](https://user-images.githubusercontent.com/40841118/75922670-23e65d00-5e6c-11ea-98db-f693769e15e7.png)

**Comment by KimAT25** [comment]
Not relevant
