### ISSUE TITLE
Inconsistency in the description of the command in the plural / singular second person form is shown on the login page

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#494]
**Steps to reproduce:**

1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/auth
2. Change language into Ukrainian
3. Pay attention to the commands: внеси, забули, зареєструватись, заходь
**Expected Result:**
All commands are described in one form - singular or plural
**Actual Result:**
The mixed form of the person is used while describing actions on the login page  
**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultimat
#66

**Comment by Talichka** [comment]
![login page](https://user-images.githubusercontent.com/40841118/75928076-4a10fa80-5e76-11ea-9e8c-0d56e6d9aac6.png)

**Comment by KimAT25** [comment]
Not relevant
