### ISSUE TITLE
BUG [UI] Grammar mistake in text 'Have not an account yet?'  on 'Sign-in' page

### ISSUE THREAD

**Issue by yanaklyuchnyk** [ita-social-projects/GreenCity#495]
**Steps to reproduce:**

Go to https://ita-social-projects.github.io/GreenCityClient/#/auth 
Check the text for spelling and grammar mistakes 
**Actual result:**
Text under 'Sign-in' button :'Have not an account yet?' has grammatical mistake
**Expected result:**
Text under 'Sign-in' button should be: 'Don't have an account?'
Note: The same bug is present on 'Sign In' popup
**Environment:**
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)
Google Chrome Version 80.0.3987.132 (64-bit)
#385

**Comment by lenadgit** [comment]
All texts we got from experts
In English in expression the verb "have" can be used without do\does  
For example  http://joxi.ru/E2pBvPEI7yv10r
https://learnenglish.britishcouncil.org/english-grammar-reference/questions-and-negatives

You can check the expression to be sure
https://www.grammarcheck.net/editor/

**Comment by yanaklyuchnyk** [comment]
'Have not an account yet?'- This question form has a grammar mistake. 
There are 2 possible ways of forming this question:
1. 'Don't have an account yet?' - with the verb 'to have'
In order to negate the verb 'have' it is obligatory to use the auxiliary verb 'do'.
2. 'Haven't got an account yet?' - with the expression 'have got'
Online grammar checking tools are not reliable. You can only check spelling errors this way.

**Comment by traviscolt** [comment]
https://ita-social-projects.github.io/GreenCityClient/#/auth - must be deleted, instead when we click the "My cabinet" in the header "Sign In" pop up must appear.

Bug not fixed on "Sign In" pop up
![Screenshot_17](https://user-images.githubusercontent.com/35031131/82118976-44436980-9783-11ea-8f01-1a4f9d603525.jpg)
