### ISSUE TITLE
[Edit Profile] Valid Input in Field 'Name' returns Error Massage

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#4951]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Reproducible: always
Build found: Build found: 13/01/23

**Preconditions**
Logged User GreenCity to https://www.testgreencity.ga/GreenCityClient/#/profile/577/edit
Goto: My Space
Click: Edit Profile

**Steps to reproduce**
1. Enter in Name Field:  'RostT11' 
2. Click on 'Save' Button

**Actual result**
Error Massage Appears: ''Oops something went wrong. Please reload page and try again later'

**Expected result**
Profile Name 'RostT11' should be saved
#1005
![Clip_3](https://user-images.githubusercontent.com/119998851/212486227-baf85a32-6a6e-4042-b218-00f54ff338a5.jpg)

**Comment by atsa21** [comment]
Not reproduce
