### ISSUE TITLE
[Edit profile] User can enter the 5 forbidden characters  in the Name field on User profile

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#4954]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 109.0.5414.74 (64-bit).
**Reproducible:** always.
**Build found:** 14/01/23

**Preconditions**

1. The registered user is logged in. 
2. 'My habits' page is opened.

**Steps to reproduce**
1. Click the 'Edit' icon on the Profile block.
2. Enter 5 characters in the Name field.
e.g: Пwert

**Actual result**
An error message in red isn’t displayed when 5 characters are entered in the Name field.

![Снимок экрана 2023-01-14 103912](https://user-images.githubusercontent.com/119864646/212473945-8727e7f3-dfa1-4d7d-80a3-0f2115251f0d.png)

**Expected result**
An error message in red is displayed when 5 characters are entered in the Name field.

**Postconditions**

**User story and test case links**
E.g.: "User story #1010 
[Test case](https://jira.softserve.academy/browse/GC-4616)

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Minor"), Type ("Functional")

**Comment by atsa21** [comment]
Replace name min length as required. 
Need to change error message
