### ISSUE TITLE
[Edit profile] User can not enter special characters ()!,-’ in the City field on User profile

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#4956]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 109.0.5414.74 (64-bit).
**Reproducible:** always.
**Build found:** 14/01/23

**Preconditions**
1. The registered user is logged in.
2. 'My habits' page is opened.

**Steps to reproduce**
1. Click the 'Edit' icon on the Profile block.
2. Enter special characters in the City field 
e.g. Lviv!  
e.g. Lviv 'Lviv'

**Actual result**
An error message in red is displayed when user enters special characters: '()!,-’ in the City field.

![image](https://user-images.githubusercontent.com/119864646/214158265-ca9cf4c1-592b-4ab5-9aad-43624f4a4961.png)
![image](https://user-images.githubusercontent.com/119864646/214158289-7d0b2239-e045-4ad3-a398-965eccf098e2.png)
![image](https://user-images.githubusercontent.com/119864646/214158331-eb5cbf78-ffad-465d-aa79-cc6504bb5986.png)

**Expected result**
An error message in red isn’t displayed when user enters special characters: '()!,-’ in the City field.

**Postconditions**

**User story and test case links**
E.g.: "User story #1010 
[Test case](https://jira.softserve.academy/browse/GC-4625)

**Labels to be added**
"Bug", Priority ("Medium "), Severity ("Minor"), Type ("Functional").

**Comment by atsa21** [comment]
City can't be started with special characters
Add missing special characters '!''
