### ISSUE TITLE
[Edit Profile] User Can't save profile after adding 2 same social networks and press 'Cancel' button

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#4958]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Reproducible: always
Build found: Build found: 14/01/23

**Preconditions**
Log into Greencity https://www.testgreencity.ga/GreenCityClient/# as registered user
'My habits' page is opened.

**Steps to reproduce**
1.Go to 'Edit Profile' Page, 'Linked social networks' Block
2.Click on 'Add social network' button
3.Type a link to a social network with a valid format (e.g. https://www.facebook.com/romein3d)
4.Click on 'Add social network' button
5.Type one more the same link to a social network with a valid format (e.g. https://www.facebook.com/romein3d)
6. Error message in red appears below the field: "This link has been already added'. ‘Social network’ field is highlighted in red.
7. Click 'Cancel' Button
8. Click 'Save' Button

**Actual result**
1. User Cannot save one social network. User is not redirected to 'Habbit Page'
**Expected result**
2. User can save one social network. User is redirected to 'Habit Page'

![Clip_4](https://user-images.githubusercontent.com/119998851/212488950-64316d1e-655d-4b29-8104-981259d031c2.jpg)

**User story and test case links:**
User story #1007

**Comment by ABbondar** [comment]
Retest please
