### ISSUE TITLE
[Edit Profile] User can't save profile after changing social network

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#4959]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Reproducible: always
Build found: Build found: 14/01/23

**Preconditions**
Log into Greencity https://www.testgreencity.ga/GreenCityClient/# as registered user
'My habits' page is opened.
User has at least 1 social network link e.g."https://www.instagram.com/patron_dsns/".

**Steps to reproduce**
1.Click the 'Edit' icon on the Profile block
2.Click on the 'Edit' icon near the social network link
3.Change the link in the field e.g. "https://www.linkedin.com/company/softserve/"
4.Click 'Add' button
5.Click on the 'Save' button

**Actual result**
User Cannot save one social network. User is not redirected to 'Habbit Page'

**Expected result**
User can save one social network. User is redirected to 'Habit Page'
![Clip_6](https://user-images.githubusercontent.com/119998851/212491773-82c5c36c-7b48-45bc-bcf0-de1ace97284a.jpg)

**User story and test case links:**
User story #1007

**Comment by ABbondar** [comment]
This functional works correctly, retest please.
