### ISSUE TITLE
[My Profile] When the to-do list checkbox is unchecked in 'Profile Privacy' , the to-do list is still displayed on the page 

### ISSUE THREAD

**Issue by lili2005prus** [ita-social-projects/GreenCity#4962]
**Environment:** Windows 10 Pro, Chrome 109.0.5414.74 (Офіційне складання) (64-розрядна версія).
**Reproducible:** always
**Build found:** 14/01/2022

**Preconditions**
Uuser should sign up and log in to Green City https://ita-social-projects.github.io/GreenCityClient/#/welcome
'Edit profile' should be opened.

**Steps to reproduce**
1. Verify that shopping list checkbox is unselected.
2. Go to My Profile page.
3. Verify that To-do list is absent on the page.

**Actual result**
There is to-do list despite the shopping list checkbox being unselected.

**Expected result**
The to-do list isn't shown on the page.

**User story and test case links**
E.g.: "User story #1008
[Test case](https://jira.softserve.academy/browse/GC-1532)"

**Comment by BelakorGit** [comment]
The checkbox "user.edit-profile.to-do-list" is functioning like a "Show my shopping list" , showing and hiding "Shopping list" on User's profile page when checked or unchecked and saved on the "Edit profile" page. So, the name of the checkbox is wrong.
<img width="1280" alt="UI_defect" src="https://user-images.githubusercontent.com/108956780/217376004-eb9038bd-32ae-47a8-a82a-3a7bbfe9ab41.png">
