### ISSUE TITLE
[Edit Profile] The elements of the 'Edit photo' popup are not fully displayed after minimizing the browser window on the ENG localization

### ISSUE THREAD

**Issue by OlenaPorosiuk** [ita-social-projects/GreenCity#4972]
**Environment:** Windows 11, Google Chrome Version 108.0.5359.126 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 15.01.23

**Preconditions**
User should be logged in GreenCity https://www.testgreencity.ga/GreenCityClient/#/             
The En localization should be chosen

**Steps to reproduce**
1. Go to 'https://www.testgreencity.ga/GreenCityClient/#/'
2. Open the 'My habits' page
3. Click on the 'Edit profile' button
4. Click on the 'Edit picture' button
5. Resize the browser window to the 320x310 size

**Actual result**
The scrollbar appeared. The profile photo is partly displayed. The 'Upload new photo' button is displayed on a different background.

**Expected result**
The scrollbar appeared. All elements of the pop-up are displayed completely and on a white background.

![Pop-up is not completely displayed1](https://user-images.githubusercontent.com/120177384/212558219-2f2adb93-a24b-487c-b0c0-18d4575e7117.png)
![Pop-up is not completely displayed2](https://user-images.githubusercontent.com/120177384/212558220-4bab32ff-e1fc-454c-9d9e-cd59ccb3839f.png)
![mock-up320](https://user-images.githubusercontent.com/120177384/212558142-0d9cbf62-b889-4807-beae-fc87ad5a96bb.png)

**User story and test case links**
E.g.: "User story #1006 
[Test case] https://jira.softserve.academy/browse/GC-4678

**Comment by DanaIuich** [comment]
There are no buttons "Change photo", "Save photo"
<img width="436" alt="No_buttons_EN" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/0f8ae67c-a0c0-4085-b5a8-7d56a3bca0cc">

**Comment by Viktoriia0106** [comment]
Not all elements are shown fully, alignment is broken

![retesting_edit_photo](https://github.com/ita-social-projects/GreenCity/assets/109147739/f1550c91-b1d7-4df5-94dd-bbd90ff24674)
![retesting_edit_photo2](https://github.com/ita-social-projects/GreenCity/assets/109147739/e57d5608-bf12-480f-a16e-e8dabc70b490)

**Comment by Viktoriia0106** [comment]
not reproduced
