### ISSUE TITLE
[Edit profile] The elements of the 'Edit photo' popup are not fully displayed after minimizing the browser window on the UA localization

### ISSUE THREAD

**Issue by OlenaPorosiuk** [ita-social-projects/GreenCity#4975]
**Environment:** Windows 11, Google Chrome Version 108.0.5359.126 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 15.01.23

**Preconditions**
The user should be logged in GreenCity https://www.testgreencity.ga/GreenCityClient/#/
The UA localization should be chosen

**Steps to reproduce**

1. Go to 'https://www.testgreencity.ga/GreenCityClient/#/'
2. Open the 'Мої звички' page
3. Click on the 'Edit profile' button
4. Click on the 'Змінити фотографію' button
5. Resize the browser window to the 320x310 size

**Actual result**
The scrollbar appeared. The profile photo is partly displayed. The 'Завантажити нове фото' button is displayed on a different background.

**Expected result**
The scrollbar appeared. All elements of the pop-up are displayed completely and on a white background.

![Pop-up is not completely displayedUAEDIT2](https://user-images.githubusercontent.com/120177384/212561493-6bd8a67d-6e23-42cb-9a4d-b622e78b647b.png)
![Pop-up is not completely displayedUAEDIT](https://user-images.githubusercontent.com/120177384/212561495-ea2c62ae-dd98-4780-b1cf-0dd57be9b8b1.png)
![mock-up320](https://user-images.githubusercontent.com/120177384/212561501-64086b93-ade1-4337-825c-d9980954d4ea.png)

**User story and test case links**
E.g.: "User story #1006 
[Test case]https://jira.softserve.academy/browse/GC-4678

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by DanaIuich** [comment]
Actual result
There are no buttons "Змінити фотографію", "Зберегти фото"
<img width="400" alt="No_button" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/1af2675f-9d46-4501-8842-880efc13b86a">
