### ISSUE TITLE
[Order details. Admin cabinet] The system  is not  displays "Район" which the user selected previously If "City" Kyiv in the block "Адреса вивезення відходів"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#4987]
**Environment:** Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
**Reproducible:** always, .
**Build found:** 18/01/2023

**Preconditions**

1. User is logged in as administrator.
2. Co to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
3. An administrator navigates to the Orders tab.
4. An administrator has opened an order from current orders view table

**Steps to reproduce**

1. Click on any number in the column Номер замовлення"
2. Click on the text "Адреса вивезення відходів"
3. Check  The system  is  displays Район in the field "Район" 

**Actual result**
The system  is not  displays "Район" which the user selected previously If "City" Kyiv in the block "Адреса вивезення відходів"
**Expected result**
The system  is   displays "Район" which the user selected previously If "City" Kyiv in the block "Адреса вивезення відходів"

**User story and test case links**
E.g.: "User story #2787
](https://github.com/ita-social-projects/GreenCity/issues/2787)
(https://jira.softserve.academy/browse/GC-4693)
**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: major"), Type ( "Functional"), 
<img width="1280" alt="Знімок екрана 2023-01-18 о 12 49 37" src="https://user-images.githubusercontent.com/116280846/213152646-3404b58e-d487-4042-a934-482907c9d978.png">
.

**Comment by atsa21** [comment]
Not reproduce
