### ISSUE TITLE
[Order details. Admin cabinet]The changes are not saved in the field ""Будинок"when super admin enter alphabetic and numeric characters in the block "Адреса вивезення відходів"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#4995]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,
**Build found:**18/01/2023
**Preconditions**

1. User is logged in as administrator.
2. Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
3. An administrator navigates to the Orders tab.
4. An administrator has opened an order from current orders view table

**Steps to reproduce**

1. Click on any number in the column Номер замовлення"
2. Click on the text "Адреса вивезення відходів"
3. Enter alphabetic and numeric characters on field "Будинок" From minimum 1 to maximum 4 character (for example: 123)

**Actual result**
The changes are not saved in the field ""Будинок"when super admin enter alphabetic and numeric characters in the block "Адреса вивезення відходів"
**Expected result**
The changes are not saved in the field ""Будинок"when super admin enter alphabetic and numeric characters in the block "Адреса вивезення відходів"

**User story and test case links**
E.g.: "User story #2787
(https://jira.softserve.academy/browse/GC-4702)
**Labels to be added**"Bug", Priority ("pri: medium"), Severity ("severity: major")
Type (""Functional"),

https://user-images.githubusercontent.com/116280846/213209093-cf38ff33-5eb8-4daf-b52f-f126748d33e2.mov

**Comment by atsa21** [comment]
Not reproduce
