### ISSUE TITLE
[API] [Edit Profile] User gets code '500 Response' when he/she tries to send GET request to the non-existing Profile id 

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5008]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 19.01.2023

**Preconditions**
Register token 
ENDPOINT: /user/{userId}/profile/ 
METHOD: GET

**Steps to reproduce**
Server: https://greencity-user.testgreencity.ga/user/{userid}/profile/ (where userid for example '574)
Send GET request to Endpoint '/user/profile' (E.g using Postman) using valid registered token

**Actual result**
User gets '500 Internal Server' 

**Expected result**
'404 Not Found'

**User story and test case links**
Userstory #1008
Test case [GC-4779](https://jira.softserve.academy/browse/GC-4779)
![Screenshot 2023-01-19 115723](https://user-images.githubusercontent.com/119998851/213412970-6223b153-7842-4bee-a3e5-2739403cffe5.png)

**Comment by juseti** [comment]
Please clarify the Expected result:
'404 Not Found' or '400 Bad Request' ?

**Comment by RostyslavTomkiv** [comment]
> Please clarify the Expected result: '404 Not Found' or '400 Bad Request' ?

404 Not Found

**Comment by Olena-Kharkova** [comment]
![image](https://user-images.githubusercontent.com/110603507/216304586-aa77372e-021f-4aab-839a-8288a5de4f8f.png)

Status code 200 - OK
