### ISSUE TITLE
[UBS_admin. Orders] The message about limits is not displayed when in the column 'Підтверджена кількість'  set amount of big packages less than 20 packages 120l for Kiev region on the page 'Orders'

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5010]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 19.01.23

**Preconditions**
1. User is logged in as an administrator.
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/
3. Navigate to UBS > Orders
4. The order for Kyiv region location and status "Cформовано" should be created

**Steps to reproduce**
1. Choose the order for Kyiv region location and with status 'Сформовано' from the table "Orders"
2. Scroll down to 'Деталі замовлення' section
3.  Set the amount of big packages (Мікс відходів 120l) less that 20 packages 120l for Kyiv region location on 'Підтверджена кількість' column

**Actual result**
The system doesn't validate amount of packages with set limit and message is not displayed when amount of packages less than 20 packages 120l for Kiev region on the page 'Orders'
![Kiev region](https://user-images.githubusercontent.com/116512982/213430787-86e0a733-70aa-4c93-a49e-dfc4b3aeca16.jpg)
![acs](https://user-images.githubusercontent.com/116512982/213430837-6acb0387-d1a7-467c-a5f2-a032c32f6fa9.jpg)

**Expected result**
If the package quantity doesn’t meet the requirements of the minimum order rule  (20 big packages Мікс відходів 120l ) on the column 'Підтверджена кількість' the error message is shown:  for Kyiv region: “Замовлення не може бути змінене. Мінімальне замовлення має містити не менше двадцяти пакетів по 120 л” and bttn should "Зберегти" should be disabled

**User story and test case links**
[Change request to #2866] Order sum validation #3706

**Comment by katia9261** [comment]
This bug is not reproduced now
![image](https://user-images.githubusercontent.com/101433204/231453598-7ed77acd-4bb3-4a85-abff-cf9eda181663.png)
