### ISSUE TITLE
[API] [Edit profile] User can't edit 'Name' field with valid data (response 400)

### ISSUE THREAD

**Issue by GalyaKryviak** [ita-social-projects/GreenCity#5015]
Environment: Windows 10,Google Chrome Версія  102.0.5005.63 (Розробка) (64-розрядна версія)
Reproducible: always
Build found: 19.01.2023

Preconditions
User need to be logged in https://www.greencity.social/#/greenCity
 

**Steps to reproduce**
1. Register token
2. Send 'PUT request /user/profile
{
  "city": "string",
  "name": "Тест.GreenCity09",
  "showEcoPlace": true,
  "showLocation": true,
  "showShoppingList": true,
  "socialNetworks": [
    "string"
  ],
  "userCredo": "string"
}

**Actual result**
Response 400 Bad request

**Expected result**
Response 200 OK

**User story and test case links**
E.g.: "User story #1010 #4942 
[Test case](https://jira.softserve.academy/browse/GC-4757)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for 
![edit name ex](https://user-images.githubusercontent.com/120183212/213451357-fcd1f588-4a6c-43ee-9c19-9ef6d92576c3.png)

**Comment by Phobos13bdrive** [comment]
Actual result
Response 400 Bad request

![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/4c8ab7c8-c204-4acd-8372-dc02270b88b3)
