### ISSUE TITLE
News page: items calculator function

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#502]
Calculator should display number of filtered News items. 
If no News items are filtered, number of all News items available should be displayed.

**Comment by rsyvulko** [comment]
Not fixed. Max number for found news is 20. Number of found news is never displayed more than 20, even if in database there are more than 20 news with selected tag. 
Windows 10 x64, Mozilla Firefox 76.0 (64-bit)

**Comment by rsyvulko** [comment]
Not fixed. Max number for found news is still 20. Number of found news is never displayed more than 20, even if in database there are more than 20 news with selected tag.
Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
![news tag count](https://user-images.githubusercontent.com/64583544/83066739-2a046800-a06e-11ea-86d5-0fdd3e955760.jpg)

**Comment by Yulia-H** [comment]
Duplicate bug  #768 https://github.com/ita-social-projects/GreenCity/issues/768
