### ISSUE TITLE
[Edit profile] User can not save allowed name in the Name field on User profile

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5023]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 109.0.5414.75 (64-bit).
**Reproducible:** always.
**Build found:** 19/01/23

**Preconditions**
1. The registered user is logged in.
2. 'My habits' page is opened.

**Steps to reproduce**
1. Click the 'Edit' icon on the Profile block.
2. Enter allowed characters in the Name field.
e.g: Terter2023
3. Click on the 'Save' button.

**Actual result**
The name isn't saved on User profile. A pop-up"Oops, something went wrong. Please reload page or try again later." is shown.

![image](https://user-images.githubusercontent.com/119864646/213493579-6805b60a-78c0-435b-818c-faaccd77ad70.png)

**Expected result**
The name is saved on User profile.

**Postconditions**

**User story and test case links**
E.g.: "User story #1010 
[Test case](https://jira.softserve.academy/browse/GC-1551)

**Labels to be added**
"Bug", Priority ("High "), Severity ("Minor"), Type ("Functional").

**Comment by atsa21** [comment]
Need to change back-end validator for profile name

**Comment by MaksymGolik** [comment]
@atsa21 
Back-end validator for profile name will be changed. But I also found an incorrectness in the front-end. The hint for filling the field "Name" says that the dot can only be in the middle of the name and without repetition, for example Tester.123, but in this case the button "Save" is still disabled.
![image](https://user-images.githubusercontent.com/99403738/213777159-1468b0cb-cbe6-4901-b1a0-bfec010ead8f.png)

The following pattern replacement is planned for the backend:
^(?=.{6,30}$)([ЁёІіЇїҐґЄєА-Яа-яA-Za-z-'\d\s]+[.]?[ЁёІіЇїҐґЄєА-Яа-яA-Za-z-'\d\s]+)+$

For example these name variants will be allowed:
- Tester
- Tester123
- Tester.123
- Tester Testerov
- tester.testerov 123

**Comment by atsa21** [comment]
@MaksymGolik 
In fronted it will be fixed after we merge this branch https://github.com/ita-social-projects/GreenCityClient/pull/2091
Check backend pattern that it allow to enter one letter name

**Comment by MaksymGolik** [comment]
@atsa21 
Yes, I heard yesterday's discussion. Backend pattern allows to set the name from one character.
