### ISSUE TITLE
[Edit profile] Window at 1024x1584px resolution looks different from the mockup

### ISSUE THREAD

**Issue by lili2005prus** [ita-social-projects/GreenCity#5024]
Environment: Windows 10 Pro, Chrome 109.0.5414.74 (Офіційне складання) (64-розрядна версія).
Reproducible: always.
Build found:  19/01/2022

**Preconditions**
User should be logged in
'Edit Profile' is opened (Go to 'My habits' > Edit Profile)
The language of the website is English

**Steps to reproduce**
Click on "Edit profile"icon
Verify UI control's alignment
Verify Label alignment
Verify spelling
Verify tabulation

**Actual result**
"Edit profile" page differs from mock-up,UI control's alignment differs,spelling differs(mock-up-Title/actual result-Credo,mock-up-Edit profile/actual result-Edit Profile), label alignment differs
![image](https://user-images.githubusercontent.com/108429806/213556602-c7d93b4c-b6c5-4360-a1d9-796fe6bf9d32.png)

**Expected result**
"Edit profile" page design should correspond to mockup design
![image](https://user-images.githubusercontent.com/108429806/213556523-0d1d2916-fdad-4f35-8700-1c7c1bcaace2.png)

**User story and test case links**
E.g.: "User story #1011 
[Test case](https://jira.softserve.academy/browse/GC-4669)"

**Comment by Vadym840217** [comment]
The appearance of the "Edit Profile" page was discussed and accepted with the designer, in accordance with the requirements
