### ISSUE TITLE
[Edit Profile] Button text placement in the 'Edit Picture' window in ENG localization doesn't correspond to mocap

### ISSUE THREAD

**Issue by lili2005prus** [ita-social-projects/GreenCity#5025]
Environment: Windows 10 Pro, Chrome 109.0.5414.74 (Офіційне складання) (64-розрядна версія).
Reproducible: always.
Build found:  19/01/2022

**Preconditions**
User should be logged in 
'Edit Profile' is opened (Go to 'My habits' > Edit Profile)
The language of the website is English

**Steps to reproduce**
Click on 'Edit Picture' button
Verify that labels alignment look according to the mocap

**Actual result** 
The text of the 'Delete Photo' and 'Upload New Photo' buttons is located in two line (look at the attached screenshot image_2023-01-12_195916368.png)
![image](https://user-images.githubusercontent.com/108429806/213557756-453ca5db-fe12-415f-81d9-5505ff375e46.png)

**Expected result**
The text of 'Delete Photo' and 'Upload New Photo' buttons is located in one line according to attached mockups
![image](https://user-images.githubusercontent.com/108429806/213557536-87555d47-1240-4f5c-b440-17b16e732368.png)
![image](https://user-images.githubusercontent.com/108429806/213557545-c2446d2e-5410-4782-b23e-8b60dc7d89f4.png)
![image](https://user-images.githubusercontent.com/108429806/213557558-2f6c294b-744b-467f-9b01-77f886b631b7.png)
![image](https://user-images.githubusercontent.com/108429806/213557567-7bf5b291-1c87-4a06-ac07-83e323cded50.png)
![image](https://user-images.githubusercontent.com/108429806/213557584-1c81aae2-f8ad-484b-b945-3ba61e000f0b.png)

**User story and test case links**
E.g.: "User story #1011 
[Test case](https://jira.softserve.academy/browse/100)"

**Comment by katia9261** [comment]
Issue was already fixed 

![image](https://user-images.githubusercontent.com/101433204/213727565-3a54de5c-2335-461a-9fd1-4e51c0d84507.png)
