### ISSUE TITLE
[Edit Profile] When the Edit Picture window is enlarged to 300% percent buttons go protrude beyond the window on ENG Localisation

### ISSUE THREAD

**Issue by lili2005prus** [ita-social-projects/GreenCity#5026]
Environment: Windows 10 Pro, Chrome 109.0.5414.74 (Офіційне складання) (64-розрядна версія).
Reproducible: always.
Build found:  19/01/2022

**Preconditions**
User should be logged in 
'Edit Profile' is opened (Go to 'My habits' > Edit Profile)
The language of the website is English

**Steps to reproduce**

1. Click on 'Edit Picture' button
2. Increase the window size by 300% '

**Actual result**
Buttons Delete Photo and Upload new photo protrude beyond the window. Delete Photo button is transparent (look at the attached mocap)
![image](https://user-images.githubusercontent.com/108429806/213558415-8dbcf6ad-481d-477a-ad2b-b38b42f5e6b6.png)

**Expected result**
All buttons and labels are located according to the mocap
![image](https://user-images.githubusercontent.com/108429806/213558382-f93d8f29-fc7f-49bf-82d7-88c1ea3b2781.png)

**User story and test case links**
E.g.: "User story #1011
[Test case](https://jira.softserve.academy/browse/GC-1411)"

**Comment by atsa21** [comment]
Not reproduce
