### ISSUE TITLE
[UBS.Admin.Tariffs ]The 403 (Forbidden) occurs when Admin chooses items and is redirected to the pricing card of the tariff

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5035]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 20/01/2023

**Preconditions**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super admin
3. Go to page "Тарифи" and choose 'Неактивно' in the filter item 'Стан' 

**Steps to reproduce**
1. Click on the item in the column 'Область' and choose pricing card (e.g. Київ, Київська область)
2. Pay attention to the error message which is displayed after redirection to the pricing card page (Http failure response for https://greencity-ubs.testgreencity.ga/ubs/superAdmin/getService: 403 OK)

**Actual result**
The 403 (Forbidden) occurs when Admin chooses items and is redirected to the pricing card of the tariff

**Expected result**
The content of the pricing card details is displayed and Admin can provide any necessary actions.

**User story and test case links**
E.g.: "User story #4948 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![image](https://user-images.githubusercontent.com/110603507/213711863-a250ff11-2506-4ca9-9750-121e91c5b174.png)

**Comment by MaksymGolik** [comment]
Not back-end part bug. Its small bug on the front-end. Path for receive services by the tariff should be corrected from "/ubs/superAdmin/getService" to "/ubs/superAdmin/{tariffId}/getService".
