### ISSUE TITLE
[API] [Edit Profile] User gets '500 Response' when he/she adds to Profile more than one accounts from the same social network

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5043]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 01/21/2023
ENDPOINT: /user/profile

**Preconditions**
The registered user is logged in greencity-user.testgreencity.ga

**Steps to reproduce**
1.Register token
2. Send 'PUT request to ENDPOINT /user/profile
For Example:
{
  "city": "string",
  "name": "string",
  "showEcoPlace": true,
  "showLocation": true,
  "showShoppingList": true,
  "socialNetworks": [  
"https://www.facebook.com/romein3d",  "https://www.facebook.com/SoftServeCompany/"
],
  "userCredo": "string"
}

**Actual result**
Response 500
'Internal Server Error'

**Expected result**
Response 200
'User updated successfully.'

**User story and test case links**
User story #1007
[Test case GC-1522](https://jira.softserve.academy/browse/GC-1522)"
![Screenshot 2023-01-22 181725](https://user-images.githubusercontent.com/119998851/213926634-e197116e-3e1b-4095-9722-658e7a41338b.png)

**Comment by ABbondar** [comment]
This functional works correctly, actual result - Response 200 'User updated successfully.'
Retest, please
