### ISSUE TITLE
[API] [Edit Profile] User gets '500 Response' after adding up to five different social network links to Profile

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5044]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 2023/01/21
ENDPOINT: /user/profile

**Preconditions**
User need to be logged in [greencity.testgreencity.ga/](http://greencity.testgreencity.ga/)

**Steps to reproduce**
1. Register Token
2. Send 'PUT request /user/profile
For example:
1.{
  "city": "string",
  "name": "string",
  "showEcoPlace": true,
  "showLocation": true,
  "showShoppingList": true,
  "socialNetworks": [  
"https://www.facebook.com/romein3d"
],
  "userCredo": "string"
}
2.  {
  "city": "string",
  "name": "string",
  "showEcoPlace": true,
  "showLocation": true,
  "showShoppingList": true,
  "socialNetworks": [  
"https://www.facebook.com/romein3d",  
"http://91.218.212.172/school/lessons_summary/",
"https://www.linkedin.com/company/softserve/"],
  "userCredo": "string"
}
3. {
  "city": "string",
  "name": "string",
  "showEcoPlace": true,
  "showLocation": true,
  "showShoppingList": true,
  "socialNetworks": [    
"https://www.facebook.com/romein3d",
"https://www.instagram.com/patron_dsns/",
"http://91.218.212.172/school/lessons_summary/",
"https://www.linkedin.com/company/softserve/",
"https://www.youtube.
com/@SoftServeCareer"],
  "userCredo": "string"
}

**Actual result**
Response 500
'Internal Server Error'

**Expected result**
Response 200 OK
'User updated successfully.'

**User story and test case links**
E.g.: "User story #1007
[Test case GC-1523](https://jira.softserve.academy/browse/GC-1523")
![Screenshot 2023-01-22 181157](https://user-images.githubusercontent.com/119998851/213926388-19f0f5db-63a9-42f3-b892-e01ac084175c.png)

**Comment by ABbondar** [comment]
this functional works correctly, additional tests for the saveUserProfile method on the backend part will be added, retest this please
