### ISSUE TITLE
[Order detail.Admin Cabinet] The 'From' field in the 'Export Time' popup is empty after changing the  order status

### ISSUE THREAD

**Issue by nata000** [ita-social-projects/GreenCity#5046]
Environment: macOS Big Sur 11.3,Google Chrome 105.0.5195.125
Reproducible:always
Build found: 18.01.2023

Preconditions

1. User is logged in as administrator.
2. User navigated to the Orders tab
3. There is at least one order on the 'Order' table  with 'Formed' status

Steps to reproduce
1. Go to 'Order' page
2. Change the order status from 'Formed' to any (e.g. 'Adjustment')
3. Click on the 'Export time' field
4. Pay attention on the 'From ' field on the  'Export time' popup 

Actual result
The 'For' field is empty.Admin can not choose the time of export

Expected result
Admin can choose any  time on the 'From' field on the  'Export time' popup 

Labels to be added
"Bug", Priority ("pri: medium"), Severity ("severity: low"), Type ("Functional")
<img width="791" alt="Знімок екрана 2023-01-22 о 23 23 02" src="https://user-images.githubusercontent.com/112875002/213941217-5aba7eae-dd33-4c0e-95cf-4638ff886fa9.png">

**Comment by AlexW8719** [comment]
Test it, everything is working now.

**Comment by DanaIuich** [comment]
Bug is fixed
