### ISSUE TITLE
News page: Create News functionality

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#505]
As a Registered User, I want to be able to publish news, so I can contribute to Eco community. 
Mock up:
TBD 

Acceptance criteria:
News submission form should have following fields/buttons in sequential order:
1. **Title** 
    a. status - mandatory field
    b. type - auto-resizing text area
    c. Max characters - 170
2. **Tag**
    a. Predefined list of tags available for selection:
      News, Events, Courses, Initiatives, Ads - User should select at least one tag
2. **Add image**
    a. possibility to add image from computer
    b. Not mandatory
3. **Main text**
    a. status - mandatory field
    b. type - auto-resizing text area + User can resize it manually (by dragging the corner of the window)
    c. Min characters - 20
    d. Max characters - 63 206
4. **Author**
    a. Auto-filled based on Name of registered User
5. **Date**
    a. Auto-filled
6. **Source**
    a. status - not mandatory field
    b. type - fixed size field - no auto-resizing, no truncation - User sees just part of URL.
7. **Cancel** button
8. **Preview** button
9. **Publish** button

Mock-up available in #525 
#661 #671
Defect: #698, #699, #700, #701

**Comment by Elina-Lapka** [comment]
Updated Story - we've dropped "Short description" field. Mock-up available at Figma. More details in #525

**Comment by TetiShel** [comment]
Add restriction  to the Title field:
d) Text format - alphanumeric without special characters except <;>, <:>, <->, <">, <'>, <%>, <?>, <!>, <,>, <.>
