### ISSUE TITLE
[Admin_cabinet. Orders] The names of services are duplicated in the column 'Послуга' of 'Деталі замовлення' table on the page 'Order'

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5052]
**Environment:**  Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 23.01.23

**Preconditions**
1. User is logged in as an administrator.
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/
3. Navigate to UBS > Orders
4. The order should be created

**Steps to reproduce**
1. Choose the order from the table "Orders"
2. Scroll down to section "Деталі замовлення" and pay attention to the column 'Послуга'

**Actual result**
The names of services are duplicated in the column 'Послуга'
![duplicate](https://user-images.githubusercontent.com/116512982/214277692-7d9dd4f4-e36b-43d3-af3b-a5023966b6a5.jpg)

**Expected result**
The column 'Послуга' should contain fields: Мікс відходів 120л Текстильні відходи 60 л Текстильні відходи 20л
![right](https://user-images.githubusercontent.com/116512982/214039530-468d46fe-2fed-4c01-a88d-0d7748f08a95.jpg)

**User story and test case links**
[[UBS Admin Cabinet ] Packages quantity and order cost](https://github.com/ita-social-projects/GreenCity/issues/2865#top)
#2865
**Labels to be added**

**Comment by ViktoriyaRyazhska** [comment]
Dublicated #4938

**Comment by ViktoriyaRyazhska** [comment]
Dublicated https://github.com/ita-social-projects/GreenCity/issues/4938
