### ISSUE TITLE
[Order details. Admin cabinet] the duplicate  Last + First Name in Drop-down list in field  " "Менеджер обдзвону" on the Section “Відповідальні особи”

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5053]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,
**Build found:**23/01/2023 
**Preconditions**

1. User is logged in as administrator.
2. Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
3. An administrator navigates to the Orders tab.
4. An administrator has opened an order from current orders view table

**Steps to reproduce**
Click on number in the column "Номер замовлення"which have  Order status "Сформовано"
 in the column Order status
Click on the text “Відповідальні особи”
Click on Drop-down list " "Менеджер обдзвону"
**Actual result**
 the duplicate  Last + First Name in field  " "Менеджер обдзвону" in Drop-down list in field "Менеджер обдзвону" the Section “Відповідальні особи”
**Expected result**
  Last + First Name in field  " "Менеджер обдзвону" is not the duplicate on the Section “Відповідальні особи”

**User story and test case links**
E.g.: "User story #2287
(https://jira.softserve.academy/browse/GC-4753)
**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:"major), Type ("UI, "Functional"), .
<img width="1280" alt="Знімок екрана 2023-01-23 о 17 20 19" src="https://user-images.githubusercontent.com/116280846/214077652-b2e05c2a-a08a-4b20-8af4-2a1375564314.png">

**Comment by katia9261** [comment]
This bug doesn't reproduce now
![image](https://user-images.githubusercontent.com/101433204/231414620-40040165-0c88-4a5f-b02f-233e1497fe9d.png)
