### ISSUE TITLE
[Order details. Admin cabinet] the duplicate Last + First Name in field ""Логіст"on the Section “Відповідальні особи

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5054]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,
**Build found:**23/01/2023
**Preconditions**

1. User is logged in as administrator.
2. Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
3. An administrator navigates to the Orders tab.
4. An administrator has opened an order from current orders view table

**Steps to reproduce**
Click on number in the column "Номер замовлення"which have Order status "Сформовано"
in the column Order status
Click on the text “Відповідальні особи”
Click on Drop-down list  "Логіст"
**Actual result**
the duplicate Last + First Name in field  "Логіст" on the Section ““Відповідальні особи
**Expected result**
Last + First Name in field "Логіст is not the duplicate on the Section “Відповідальні особи”
**User story and test case links**
E.g.: "User story #2287
(https://jira.softserve.academy/browse/GC-4754)
**Labels to be added**"Bug", Priority ("pri: medium"), Severity ("severity:"major), Type ("UI, "Functional"), .
<img width="1145" alt="Знімок екрана 2023-01-23 о 17 38 44" src="https://user-images.githubusercontent.com/116280846/214081968-4c7a74d6-9ca4-4f81-af71-045f6464094e.png">

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed
