### ISSUE TITLE
[Order details. Admin cabinet] the duplicate Last + First Name  in the drop down list  in field  "Штурман" on the Section “Відповідальні особи”

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5055]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,
**Build found:**23/01/2023
**Preconditions**

1. User is logged in as administrator.
2. Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
3. An administrator navigates to the Orders tab.
4. An administrator has opened an order from current orders view table

**Steps to reproduce**
Click on number in the column "Номер замовлення"which have Order status "Сформовано"
in the column Order status
Click on the text “Відповідальні особи”
Click on Drop-down list " Штурман"
**Actual result**
the duplicate Last + First Name  on the drop down list  in field  "Штурман" on the Section “Відповідальні особи”
**Expected result**
Last + First Name in field "Штурман"" is not the duplicate on the Section “Відповідальні особи”

**User story and test case links**
E.g.: "User story #2287
(https://jira.softserve.academy/browse/GC-4755)
**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:"major), Type ("UI, "Functional"), .
<img width="1102" alt="Знімок екрана 2023-01-23 о 17 51 33" src="https://user-images.githubusercontent.com/116280846/214085026-fce824d6-adda-4e96-9a3e-877f99dce63c.png">

**Comment by katia9261** [comment]
The bug is not reproduced
