### ISSUE TITLE
[Order details. Admin cabinet] the duplicate Last + First Name in the drop down list in field "Водій" on the Section “Відповідальні особи”

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5056]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,
**Build found:**23/01/2023
**Preconditions**
User is logged in as administrator.
Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
An administrator navigates to the Orders tab.
An administrator has opened an order from current orders view table

**Steps to reproduce**

1. Click on number in the column "Номер замовлення"which have Order status "Сформовано"
2. in the column Order status
3. Click on the text “Відповідальні особи”
4. Click on Drop-down list "Водій"

**Actual result**
the duplicate Last + First Name in the drop down list in field "Водій" on the Section “Відповідальні особи”
**Expected result**
Last + First Name in field "Водій" is not the duplicate on the Section “Відповідальні особи”

**User story and test case links**
E.g.: "User story #2287
(https://jira.softserve.academy/browse/GC-4756)
**Labels to be added**"Bug", Priority ("pri: medium"), Severity ("severity:"major), Type ("UI, "Functional"), .
<img width="1155" alt="Знімок екрана 2023-01-23 о 18 03 59" src="https://user-images.githubusercontent.com/116280846/214088189-4a99dbdf-d764-4c89-a799-1e00c3ceab34.png">

**Comment by katia9261** [comment]
The bug is not reproduced
