### ISSUE TITLE
[Admin Cabinet] The 'Filters' popup window don't closes after clicking on outside in the  Admin cabinet on the 'Order' page

### ISSUE THREAD

**Issue by nata000** [ita-social-projects/GreenCity#5067]
Environment: macOS Big Sur 11.3,Google Chrome 105.0.5195.125
Reproducible:always
Build found: 24.01.2023

Preconditions

1. User is logged in as administrator.
2. User navigated to the 'Orders' tab

**Steps to reproduce**

1. Click on 'Filters' button
2. Click outside the window

Actual result
The 'Filters' popup window don't closing after clicking outside the window

Expected result
The 'Filters' popup window  closing after clicking outside the window

**User story and test case links**
E.g.: "User story #2600

Labels to be added
"Bug", Priority ("pri: low"), Severity ("severity:minor"), Type ("UI)

**Comment by DanaIuich** [comment]
Bug is fixed
