### ISSUE TITLE
BUG[NAVIGATION PANEL] The 'Eco-news' page is shown in landing page after clicking on the 'Eco-advices' page

### ISSUE THREAD

**Issue by KaterynaIlkiv** [ita-social-projects/GreenCity#507]
BUG[NAVIGATION PANEL] The 'Eco-news' page is shown in landing page after clicking on the 'Eco-advices' page
Environment:
OS: Windows 10Pro, V.1909
Browser: Chrome 80.0.3987.122 / 64-bit

Steps to reproduce:
1. Go to the site https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Eco-advices' page
3. Verify the opened page

Actual result:The 'Eco-news' page is shown in landing page after clicking on the 'Eco-advices' page
Expected result:The 'Eco-advices' page is shown in landing page after clicking on the 'Eco-advices' page

#354

**Comment by lenadgit** [comment]
Can you to reproduce this bug?  Because after clicking on a link "Eco-Advices" I see scrolling to the Eco-Advices section
https://nimbusweb.me/s/share/3965993/mdqhgp8e9nvirgzu3tck

**Comment by KaterynaIlkiv** [comment]
I always have random presence of this page:scrolling, displaying another page. Link for video
https://drive.google.com/open?id=1iDujX1y_aHWC5JexsSR2qhO0jwmXvJKn

**Comment by KimAT25** [comment]
Not reproducible
