### ISSUE TITLE
[Order details. Admin cabinet] The error massage doesn't  appear When super admin download  Invalid file format the image if file is other than PNG or JPG format and size more then 10MБ” .on pop-up window “Додати порушення” In block "Інформація про клієнта"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5070]
**Environment:**Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,
**Build found:**25/01/2023
**Preconditions**

1. User is logged in as administrator.
2. Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders)
3. An administrator navigates to the Orders tab.
4. An administrator has opened an order from current orders view table

**Steps to reproduce**
Click on any number in the column Номер замовлення"
Click on the text "Інформація про клієнта
Click on button “Додати порушення”
download the image Invalid  for example file format TIFF on the  photo matrix  and download the image size more then 10MБ”
**Actual result**
The error massage doesn't  appear When super admin download  Invalid file format the image if file is other than PNG or JPG format and size more then 10MБ” .on pop-up window “Додати порушення” In block "Інформація про клієнта"
**Expected result**
The error massage does appear When super admin download  Invalid file format the image if file is other than PNG or JPG format and size more then 10MБ” .
<img width="995" alt="Знімок екрана 2023-01-25 о 12 20 55" src="https://user-images.githubusercontent.com/116280846/214538515-612cf828-02c3-4999-b947-d4868fc71869.png">

**User story and test case links**
E.g.: "User story #2287
(https://jira.softserve.academy/browse/GC-4726)
**Labels to be added**
"Bug", Priority ("pri:low "), Severity ("severity:minor"), Type ("UI, ).

**Comment by katia9261** [comment]
The bug doesn't reproduce
![image](https://user-images.githubusercontent.com/101433204/231415688-08022abb-de53-43e0-b7ca-aaefd7939822.png)
