### ISSUE TITLE
BUG[FOOTER]: Navigation to the 'Home' page is not occur after clicking on 'Home' page in the footer of application

### ISSUE THREAD

**Issue by KaterynaIlkiv** [ita-social-projects/GreenCity#508]
Environment:
OS: Windows 10Pro, V.1909
Browser: Chrome 80.0.3987.122 / 64-bit

Steps to reproduce:
1. Go to the site https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Scroll down to the footer of app
3. Click on the 'Home' page
4. Verify navigation to the 'Home' page

Actual result:Navigation to the 'Home' page is not occur after clicking on 'Home' page in the footer of application
Expected result: The 'Home' page is displayed after clicking on 'Home' page in the footer of application

#384

**Comment by Marie1360** [comment]
Bug is also reproducible on:
OS: Windows 10
Browser: Mozilla Firefox 72.0.2 (64-біт)

**Comment by KimAT25** [comment]
Not relevant
