### ISSUE TITLE
[UBS Admin.Orders. Orders detailes] The 'Назад' bttn is hidden after zooming on the order details page on 110%,125%,150%

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5080]
**Environment:**
 Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
**Reproducible:** always
**Build found:** 25/01/2023

**Preconditions**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super Admin
3. Go to the Super Admin profile and choose the UBS-Admin item
4. Choose the 'Orders' item
5. Click on the Order's number in the Order table (except orders with 'Виконано'/ 'Скасовано' statuses)

**Steps to reproduce**
1. Provide zooming of page from 75% to 175%
2. Pay attention to the 'Назад' bttn which is situated near the title 'Замовлення №...'

**Actual result**
The 'Назад' bttn is hidden after zooming on the order details page on 110%,125%,150%

**Expected result**
All UI controls and elements of the order details page are displayed and adopted according to zoom (responsiveness)

**User story and test case links**
E.g.: "User story #(https://github.com/ita-social-projects/GreenCity/issues/2787)
"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

https://user-images.githubusercontent.com/110603507/214665816-5bc0ba34-016a-48c1-9746-c9667762cbc2.mp4

**Comment by katia9261** [comment]
The position of the button must match the new mockup
![image](https://user-images.githubusercontent.com/101433204/216988231-1e54e7b8-a8e8-4145-aca6-bd9100cc0a03.png)
