### ISSUE TITLE
[Pricing Page. Create card] Auto-translation of region is incorrect

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5083]
**Environment:**  Windows 10 Pro, Google Chrome 109.0.5414.119 
**Reproducible:** always
**Build found:** 26.01.2023

**Preconditions**
The user should be authorized as UBS Admin
Select 'UA' language

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
2. Click on 'Gear'
3. Click on Tab 'Create card'

**Actual result**
Ukrainian region ('Харківська область') is auto-translated as 'Kharkiv region, Kharkiv Oblast'
![image](https://user-images.githubusercontent.com/104850911/214812476-e049a444-acfd-4351-88d7-5c3412e6fb3f.png)

**Expected result**
Ukrainian region ('Харківська область') is auto-translated as 'Kharkiv Oblast'

**Comment by atsa21** [comment]
Will be fixed by removing region duplication from database

**Comment by ABbondar** [comment]
not reproduce
