### ISSUE TITLE
[Pricing page. Create card] Courier, region and city inputs lists translation for EN language

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5085]
**Environment:** Windows 10 Pro, Google Chrome 109.0.5414.119
**Reproducible:** always
**Build found:** 26.01.2023

**Preconditions**
The user should be authorized as UBS Admin
Select 'EN' language

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
2. Click on 'Gear'
3. Click on Tab 'Create card'

**Actual result**
User see list of Ukrainian couriers instead of English. Screenshot attached ↓
![image](https://user-images.githubusercontent.com/104850911/214815563-2923581a-9b31-4ff9-ad86-f84254a49105.png)

Same wrong list for regions and cities. Screenshots attached ↓
![image](https://user-images.githubusercontent.com/104850911/214816023-64af3f02-be26-4091-bdb6-e28ba49d1913.png)
![image](https://user-images.githubusercontent.com/104850911/214816186-39af5467-93e0-4dba-9a18-ad2c8c0158e7.png)

**Expected result**
In courier, region and city inputs user see lists of couriers in English

**Comment by BohdanaYuzkiv** [comment]
![image](https://github.com/ita-social-projects/GreenCity/assets/109086383/fe38431f-faa8-496a-a493-0fa13595202c)
City is still displayed only in Ukrainian

**Comment by Maksym8Kravchenko** [comment]
This bug was fixed partly. The column 'Receiving station' still displayed Ukrenian titles.
![image](https://github.com/ita-social-projects/GreenCity/assets/127987815/9f9ed17a-0075-4ffa-a865-188f768f7cb1)

**Comment by katia9261** [comment]
We don't have translation for receiving stations

**Comment by Maksym8Kravchenko** [comment]
Thank you for clarifying the requirements, I'm closing the bug.
