### ISSUE TITLE
[Change request to #1010] Edit Profile on the ‘My habits’ page on the notification form for 'Name' field.

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5087]
**Acceptance Criteria**
Name field:
Criteria to validate a 'Name' field on the 'Edit profile' page should be the following:

- Valid letters are (a-z; а-я)
- ‘Name’ field is mandatory.
- The name must contain 1-30 characters.
- Numbers (0-9) are valid.
- Dot(.) can be used, but dot at the start, at the end and consecutive dot is forbidden.

Name field: (error message)
ENG - The field is required. The name must contain 1-30 characters and can contain letters(a-z; а-я), numbers(0-9) and a dot(.), dot at the start, at the end and consecutive dot is forbidden
UA - Поле обов’язкове для заповнення. Ім'я повинно містити 1-30 символів і може складатись з літер(a-z; а-я), цифр(0-9) та крапки(.), крапка на початку імені, в кінці та послідовність крапок заборонена

Related to:
User story [#1010] [#4942 ] 
Epic: [#938 ]

**Comment by mdashko** [comment]
this bug is already fixed
