### ISSUE TITLE
BUG [HEADER] The 'sign up' hyperlink instead of 'register' is displayed in header

### ISSUE THREAD

**Issue by fil2002** [ita-social-projects/GreenCity#509]
Environment:
OS: Windows 10 Home
Browser: Firefox Mozilla 73.0.1 / 64-bit

Steps to reproduce:

1. Go to the site https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Look at the hyperlinks in header

Actual result: The 'sign up' hyperlink instead of 'register' is displayed in header

Expected result: The 'register' hyperlink is shown in header

#352

![2020-03-13_23-59-11](https://user-images.githubusercontent.com/61517113/76663196-f9418600-6588-11ea-8a27-55e0ca72d1e5.jpg)

**Comment by nabermi2020** [comment]
Not relevant
