### ISSUE TITLE
[Starting view] The existing list of tariffs is updated with the same values each time when one of the field "Region", "City", "Courier", "Receiving station", "State" are selected  

### ISSUE THREAD

**Issue by LiliaMokhnatska** [ita-social-projects/GreenCity#5094]
**Environment:** Windows 10
Chrome 107.0.5304.63
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
User is logged in as Admin.
Tariffs panel is opened:[ https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs|https://ita-social-projects.github.io/GreenCityClient/#/ubs-admin/tariffs]

"Create an item in the database using SQL query:
INSERT INTO table1 (column1, column2)
VALUES (value1, value2);"

**Steps to reproduce**

1.Click on the 'Region' field
2. Click on the 'All' bttn or choose one region 
3. Click on on the cross button

1.Click on the 'City' field
2. Click on the 'All' bttn or choose one city

1.Click on the 'Courier' field
2. Click on the 'All' bttn or choose one courier

1.Click on the 'Receiving station' field
2. Click on the 'All' bttn or choose one receiving station

1.Click on the 'State' field
2. Click on the 'All' bttn or choose one state

**Actual result**
The existing list of tariffs is updated with the same values each time when one of the field "Region", "City", "Courier", "Receiving station", "State" are selected.
When updating the page, a non-duplicated list of tariffs remains.

**Expected result**
By selecting the values in the fields: "Region", "City", "Courier", "Receiving station", "State", the corresponding list of tariffs remains

https://user-images.githubusercontent.com/113025377/214968459-06b902cb-d2c5-4231-a261-94ffc4623a0d.mp4

https://www.youtube.com/watch?v=3fjGrjd9u-k

**User story and test case links**
E.g.: "Starting view for the pricing page ("Тарифи") https://github.com/ita-social-projects/GreenCity/issues/3835 "

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional")

**Comment by marianaharnyk** [comment]
It is duplication of #5049
