### ISSUE TITLE
BUG [HOME PAGE]: The Home page is shifted up and the 'Advertising' title is partially cut after clicking the site logo

### ISSUE THREAD

**Issue by fil2002** [ita-social-projects/GreenCity#510]
Environment:
OS: Windows 10 Home
Browser: Firefox Mozilla 73.0.1 / 64-bit
Google Chrome
Version 80.0.3987.132 (64-bit)

Steps to reproduce:

1. Go to the site https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the site logo
3. Look at the Advertising title

Actual result: The Home page is shifted up and the 'Advertising' title is partially cut after clicking the site logo

Expected result: The Home page is displayed fully with all elements presented on it after clicking the site logo

The defect is reproduced on every page of the application

#280

![2020-03-14_0-14-18](https://user-images.githubusercontent.com/61517113/76665150-68ba7400-658f-11ea-8daa-711cc4e315cf.jpg)

**Comment by rsyvulko** [comment]
Verified
