### ISSUE TITLE
[Admin Cabinet] The data on the 'Ім'я клієнта' column are not sorted on the “А”-”Я” / “Я”-”A” order after clicking on the arrow icon 

### ISSUE THREAD

**Issue by nata000** [ita-social-projects/GreenCity#5103]
Environment: macOS Big Sur 11.3,Google Chrome 105.0.5195.125
Reproducible:always
Build found: 29.01.2023

Preconditions

User is logged in as administrator.
User navigated to the Orders tab
There is at least two order on the 'Order' table with different statuses

Steps to reproduce

1. Click once on the arrow icon in the 'Ім'я клієнта' column on admin cabinet
2. Pay attention on the sorting data
3. Click twice on the arrow icon in the 'Ім'я клієнта' column on admin cabinet
4.  Pay attention on the sorting data

Actual result
The data are NOT sorted on the sorted in alphabetical order “А”-”Я”  after one clicking
The data are NOT sorted on the sorted in ”Я”-"A" order  after second clicking

Expected result
Actual result
The data are sorted on the sorted in alphabetical order “А”-”Я”  after one clicking
The data are sorted on the sorted in ”Я”-"A" order  after second clicking

**User story and test case links**
E.g.: "User story #2537
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by atsa21** [comment]
Not reproduce

**Comment by DanaIuich** [comment]
Bug is fixed

**Comment by yulianagoncharenko** [comment]
Bus is not reproduced on prod environment
