### ISSUE TITLE
[UBS] Set order status from "CONFIRMED" to "ON_THE_ROUTE" automatically on the day of order fulfillment

### ISSUE THREAD

**Issue by Markiro1** [ita-social-projects/GreenCity#5113]
**Link to issue**: https://github.com/ita-social-projects/GreenCity/issues/5034

**Actual result**
The order status from "Підтверджено" to "На маршруті" is not changed and is not set automatically at 00:00 on the day of order fulfillment

**Expected result**
The order status from "Підтверджено" to "На маршруті" is changed and is set automatically at 00:00 on the day of order fulfillment

**Comment by Olena-Kharkova** [comment]
The bug is still can be reproduced


https://user-images.githubusercontent.com/110603507/224540023-27f69e91-64c8-4fef-831d-591c16039b74.mp4

**Comment by Maksym8Kravchenko** [comment]
This  buf is not a fixed
![image](https://github.com/ita-social-projects/GreenCity/assets/127987815/86b8941e-244e-40ef-810d-bcfb66763f47)

**Comment by lagysha** [comment]
Everything seems to be working as expected
