### ISSUE TITLE
[UBS Admin.Orders. Orders details] Admin can not save changes in the field 'Order number from store' of block 'Order details' after deleting the number of Eco-store order

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5116]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 30/01/2023

**Preconditions**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super Admin
3. Go to the Super Admin profile and choose the UBS-Admin item
4. Choose the 'Orders' item
5. Click on the Order's number in the Order table (except orders with 'Виконано'/ 'Скасовано' statuses) which hasn't filled the field 'Order number from store'

**Steps to reproduce**
1. Go to the block 'Order details' 
2. Click on 'v' control for content expansion of the block 'Order details' 
3. Scroll down to the item 'Order number from store' and set the order number of Eco-store in the block 'Order details'. 
4. Save changes by 'Зберегти' bttn clicking
5. Go back to the block 'Order details' 
6. Click 'x' for deleting the content in the field 'Order number from store'
7. Scroll down to the 'Зберегти' bttn and pay attention to the bttn - there is no ability to save these changes

**Actual result**
Admin can not save changes in the field 'Order number from store' of block 'Order details' after deleting the number of Eco-store order

**Expected result**
When Super Admin deletes the item 'Order number from store', and saves this information in the Order, it should be displayed as a change event with the title "Видалено номер замовлення з магазину: ......" (e.g. "Видалено номер замовлення з магазину: 1234567890")

**User story and test case links**
E.g.: "User story #3217 #5111 
[Test case](https://jira.softserve.academy/browse/GC-4727)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional")

https://user-images.githubusercontent.com/110603507/215522474-3e321fb7-639d-4ba6-b0e3-0e4490cd5c90.mp4

**Comment by DanaIuich** [comment]
Admin can not save changes after entering the number of Eco-store order in formed and paid/unpaid order. The error message "Bag does not exist by id:2" appears. Response 400 in dev-tools.

https://github.com/ita-social-projects/GreenCity/assets/128155213/ba855958-bb44-43a2-a4a1-627f532c6c74

**Comment by Tadei-Mykola** [comment]
Can not reproduce
