### ISSUE TITLE
BUG[FOOTER] The scrolling page is displayed in landing page after clicking on the 'My cabinet' link

### ISSUE THREAD

**Issue by KaterynaIlkiv** [ita-social-projects/GreenCity#512]
Environment:
OS: Windows 10Pro, V.1909
Browser: Chrome 80.0.3987.122 / 64-bit

Steps to reproduce:
1. Go to 'Green city' application https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Scroll down to the bottom of the page
3. Click on 'My cabinet' link
4. Verify the displayed page

Actual result:The scrolling page is displayed in landing page after clicking on the 'My cabinet' link
Expected result: The 'Log in' form is displayed for unlogged user in landing page after clicking on the 'My cabinet' link

#384 

Video link:
https://drive.google.com/open?id=1dA_KE_pdkCOs5p9kzK-jgL6uFTPoNBmb

**Comment by traviscolt** [comment]
Bug not fixed. 
Appears page instead 'Sign In' pop up
In the footer "My habits" instead "My cabinet"
![Screenshot_18](https://user-images.githubusercontent.com/35031131/82119117-9769ec00-9784-11ea-9f5c-8b0c1042b388.jpg)

**Comment by KimAT25** [comment]
Old functional of Authorization will be deleted and after will be add link for button to open Auth modal window instead of old Auth page
