### ISSUE TITLE
[Change request to #3193] <Create event>

### ISSUE THREAD

**Issue by DimaKarma** [ita-social-projects/GreenCity#5123]
**Description of a Change request:**
Minor changes in functionality
Event type "Offline" transformed to an Event type "Place" 

**Reason for Change:**
To clarify some misunderstanding moments

**Mockups**
1 день 
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=50699-47722&mode=design
2 дня 
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=50699-55581&mode=design

**Acceptance Criteria**
_According to the original order_
**6.** _Add:_ By default the System sets up a current date.

**7**. Event time. By default the System sets up current time +1 hour.
7.1. The User should be able to choose: "Start Time", "End Time" or choose an option "All day". If the User choose "All day" then the System makes time dropdown lists as inactive, and sets up time by default: "Start Time" - 00:00, "End Time" - 23:59.
The time input format must be 24 hours.
7.1.1. If the User selected "All day" and Event date is current the System sets up the beginning time by default: "Start Time" - 00:00 , "End Time" - 23:59.
7.2. The User shouldn’t be able to choose the past time in the case if a current date is chosen in AC#6.

7.3. In case user want to enter specific time he should do it manually with step in 30 min in "Set Start Time" and "Set End Time" boxes. If the user enter specific time in not define format the System show red error message “Incorrect Time format. Use format 00:00 +30min”.

**9, 11.** _Add_ See US #4232

**13.** _Add:_When the User is typing then the System should calculate and display in real time how many characters was typed by the User. If the User exceeds the max. quantity of entered symbols (>63206) then the System changes this informational text into the red color.
![image](https://user-images.githubusercontent.com/118194848/222972438-44a5a717-2655-4c80-9486-eaec69d5e98a.png)

**20.** _Add:_ Checkboxes "Place"/"Online", Quick filters markers "Initiative type"/"Event type" are mandatory to choose by the User.

**Impact of Change**
#3193 #4234 #4232

Epic: #3194

**Comment by Mykola365** [comment]
Reproduces again, does not highlight in red if there are to many characters.
