### ISSUE TITLE
[UBS Admin Cabinet ] Admin doesn't see the borders of City field and Street field in 'Waste export address' section after he/she moves from User account to Admin account

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5125]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 109.0.5414.120 (64-bit).
**Reproducible:** always.
**Build found:** 30/01/23

**Preconditions**

1. User is registered as admin.
2. User is registered as user.
3. The registered user is logged in.
4. Orders tab is opened. 
5. User has at least 1 order.

**Steps to reproduce**

1. Click on the 'New order' button.
2. Click on the 'Back' button.
3. Click on the name in the top right.
4. Click Sign out.
5. Click Sign in.
6. Log in as admin.
7. Click on the name in the top right 
8. Click UBS-admin.
9. Click on particular order
10. Click on 'Waste export address'
11. Pay attention to the City field.
12. Pay attention to the Street field.

**Actual result**

 Admin doesn't see the borders of the City field and Street field in the 'Waste export address' section.
![image](https://user-images.githubusercontent.com/119864646/215579877-c2e93091-c914-4aa0-a9e4-d64d9bfea2e9.png)

https://user-images.githubusercontent.com/119864646/215581615-83d3413b-4d96-493d-8435-7d7b03d37fc6.mp4

**Expected result**

 Admin sees the borders of the City field and Street field in the 'Waste export address' section.

![image](https://user-images.githubusercontent.com/119864646/215582427-ae2a252f-43a4-42a5-8022-786c774365be.png)

**Postconditions**

**User story and test case links**
E.g.: "User story #5101 

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity:Trivial"), Type ("UI").

**Comment by marianaharnyk** [comment]
Cannot be reproduce
