### ISSUE TITLE
BUG[FOOTER]:The elements presented in the footer differ from elements in mock up 

### ISSUE THREAD

**Issue by KaterynaIlkiv** [ita-social-projects/GreenCity#513]
The elements presented in the footer differs from elements in mock up and have different positions

Environment:
OS: Windows 10Pro, V.1909
Browser: Chrome 80.0.3987.122 / 64-bit

Steps to reproduce:
1. Go to the Green city web-site https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Scroll down to the footer
3. Verify presence and elements position

Actual results:The elements presented in the footer differ from elements in mock up 
Expected result: All required elements are displayed corresponding to mock up and have the same position

#384 
![Footer](https://user-images.githubusercontent.com/61518233/76678739-f8d5d900-65e2-11ea-85a8-78a727225ef1.jpg)

![MOCKUP](https://user-images.githubusercontent.com/61518233/76678689-89f88000-65e2-11ea-9749-2ef8b82e5e9d.png)

**Comment by KimAT25** [comment]
Not relevant
