### ISSUE TITLE
[Manage event location] The event location is not indicated by the map 

### ISSUE THREAD

**Issue by BelakorGit** [ita-social-projects/GreenCity#5130]
**Environment:** Windows 10 x64, Chrome Version 109.0.5414.119 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 31.01.2023

**Preconditions**
1. Site https://www.testgreencity.ga/GreenCityClient/#/ should be opened.
2. User should be authorized. 

**Steps to reproduce**
1. Click on the "Events" tab in the header
2. Click on the "Create" button below the header in the right upper corner.
3. Choose 1 day in the "Duration" dropdown.
4. Click on the "Place" radio button.
5. Fill in the "Location" field with the valid address.

**Actual result**
The Location is chosen , but map is not displayed.

**Expected result**
The location is chosen and map with pin and +,- zooms is displayed.

**User story and test case links**
E.g.: "User story #3373 
[Test case](https://jira.softserve.academy/browse/GC-4003)"

**Comment by atsa21** [comment]
Not reproduce
