### ISSUE TITLE
[Edit Event] An authorized user can go to "Edit event" page , when the event is past

### ISSUE THREAD

**Issue by BelakorGit** [ita-social-projects/GreenCity#5134]
**Environment:** Windows 10 x64, Chrome Version 109.0.5414.119 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 31.01.2023

**Preconditions**
1. Site https://www.greencity.social/#/greenCity should be opened.
2. User should be logged in as an authorized.
3. User of this account should be an organizer of past event.

**Steps to reproduce**
1. Open past event created by logged in user.
2. Click on "Edit" button.

**Actual result**
The "Edit" button on the past event page exists. However, button "Publish" on the "Edit event" screen is disabled.

**Expected result**
There should be no "Edit" button on the past event page.

**User story and test case links**
E.g.: "User story #3195 
[Test case](https://jira.softserve.academy/browse/GC-3198)"

**Comment by Phobos13bdrive** [comment]
There "Edit" button not disabled on the past event page.

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. tnx
