### ISSUE TITLE
[Edit Event] Users can enter the title of the event with spaces when using copy-paste

### ISSUE THREAD

**Issue by BelakorGit** [ita-social-projects/GreenCity#5135]
**Environment:** Windows 10 x64, Chrome Version 109.0.5414.119 (Official Build) (64-bit)
**Reproducible:** sometimes
**Build found:** 31.01.2023

**Preconditions**
1. Sign in to "Greencity" project as an authorized user.
2. Event should created by this account.
3. The "Events" page is opened.

**Steps to reproduce**
1. Find a created by this account event from the events list.
2. Click on "More" link on event card.
3. Click on "Edit" button.
4. Edit the event's "Title" using copy-paste to the name "THIS IS SPACE".

**Actual result**
When copy-pasting no error messages appear and the event can be edited with an invalid title.

**Expected result**
The event "Title" field is highlighted in red and an error message appears "You should have no whitespaces".

**User story and test case links**
E.g.: "User story #3195 
[Test case](https://jira.softserve.academy/browse/GC-3196)"
![SPACE](https://user-images.githubusercontent.com/108956780/215782332-6cb2ab8f-ce40-41d6-b791-6da78bc61560.jpg)

**Comment by ViktoriyaRyazhska** [comment]
not relevant
