### ISSUE TITLE
[Edit Event] An authorized user can not change the order of pictures in the created event

### ISSUE THREAD

**Issue by BelakorGit** [ita-social-projects/GreenCity#5136]
**Environment:** Windows 10 x64, Chrome Version 109.0.5414.119 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 31.01.2023

**Preconditions**
1. Site https://www.testgreencity.ga/GreenCityClient/#/ should be opened.
2. User should be authorized.
3. Event should be created and saved.

**Steps to reproduce**
1. Click on "Events" tab in the header.
2. Find the created Event and Click on "More" button.
3. Click on "Edit" button at the right upper corner.
4. Drag and drop the images to a different position in order to change their order.

**Actual result**
The initial order of images has not been changed.

**Expected result**
The order of the pictures has been changed according to transfer.

**User story and test case links**
E.g.: "User story #3195 
[Test case](https://jira.softserve.academy/browse/GC-3207)"

**Comment by Olena-Kharkova** [comment]
Check this issue one more time. The bug is not completely fixed, the user should provide the page refreshing in addition that to see the changes which are made with the event Image. 



https://user-images.githubusercontent.com/110603507/228564513-8f02c576-c16f-4044-865a-046595450099.mp4

**Comment by ghost** [comment]
The bug is reproduced on  Windows 10 x64, Chrome Version 113.0.5672.93 (Official Build) (64-bit) The image is not displayed in different position on the 'Edit Event' page after drag and drop it in other place
