### ISSUE TITLE
[Sign up] User can`t sign up when clicks 'sign up with Google' button

### ISSUE THREAD

**Issue by patselyuk** [ita-social-projects/GreenCity#5139]
**Environment:** macOS 12.6.1,12.4 Chrome109.0.5414.87,108.0.5359.124
**Reproducible:** always
**Build found:** 27.01.2023

**Steps to reproduce**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. Click on 'Sign-up' button
3. Click to  'Sign up with Google' button

**Actual result**
The button 'Sign up with Google' is not clickable 

**Expected result**
New window 'Google sign in'  is opened, button 'Google sign in'  is enabled

**User story and test case links**
E.g.: "User story #50
[Test case](https://jira.softserve.academy/browse/GC-218)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by atsa21** [comment]
Not reproduce
