### ISSUE TITLE
BUG[Header] Wrong welcome text is shown in a header 

### ISSUE THREAD

**Issue by nuclearyana** [ita-social-projects/GreenCity#514]
**Steps to reproduce:**

1. Go to Green City [https://ita-social-projects.github.io/GreenCityClient/#/welcome]
2. Verify Welcome text of the header

**Actual result:**
Welcome text 'Hi there! It's an eco-habit tracker. Sign-up to create your own or sign-in, if you are already with us' is shown
**Expected result:**
Welcome text 'Hello! It is tracker of eco habits. Please register to create your own tracker or sign in if you are already with us' sould be shown

**Environment:**
OS: Windows 10 
Browser: Firefox Mozilla 73.0.1 / 64-bit
Google Chrome 80.0.3987.132 / 64-bit
![image](https://user-images.githubusercontent.com/61509126/76682869-208b6800-6608-11ea-9b00-83f50e7bdce0.png)
![Wrong header_Chrome](https://user-images.githubusercontent.com/61537703/76683521-5aab3880-660d-11ea-9dda-7afcc6164866.JPG)

**Comment by nabermi2020** [comment]
Not relevant, the current header will be replaced with the new one in a while
