### ISSUE TITLE
[Delete Event] The administrator can delete not all past events

### ISSUE THREAD

**Issue by ZubachV1990** [ita-social-projects/GreenCity#5143]
**Environment:** 
Windows 10 Pro, Chrome. Версия 109.0.5414.120 (64 бит)

**Reproducible:**
 sometimes

**Build found:** 
31.01.2023

**Steps to reproduce**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. The Admin is logged (Login: admin.greencity@starmaker.email; Password: GreenCityAdmin-1[adminubs@starmaker.email](mailto:adminubs@starmaker.email)
3. Go to 'Events'
4. Find the past event.
5. Click  'More' button, which is placed on your event. 
6. Click 'Delete'button
7. Click on 'Yes' button in pop-up

**Actual result**
The "Delete" button is not in every past event

**Expected result**
All data about the past event are delete

**User story and test case links**
E.g.: "User story #3196
[Test case] https://jira.softserve.academy/secure/enav/#/49224

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Tadei-Mykola** [comment]
cannot reproduce
