### ISSUE TITLE
[Change request to #3211] <Reply on comment>

### ISSUE THREAD

**Issue by DimaKarma** [ita-social-projects/GreenCity#5145]
**Description of a Change request:**
Minor changes in AC #8

**Acceptance Criteria**
**8.** Allowed special characters !"#$%&'()*+,-./:;<=>?@[]^_`{|}~". Quantity of characters from 1 to 8000.

**Impact of Change**
#3211 

Epic: #3194

**Comment by VlasenkoYuliia** [comment]
Minor changes in AC #6
