### ISSUE TITLE
[View my events] The upcoming events are displayed in random order on My events page

### ISSUE THREAD

**Issue by babaeva84** [ita-social-projects/GreenCity#5148]
**Environment:** MacOS 12.0.1, GoogleChrom 109.0.5414.87
**Reproducible:** always, rarely, sometimes etc.
**Build found:** 31.01.2023
E.g. "commit 147fa44"

**Preconditions**

**Steps to reproduce**
1. Go to https://www.greencity.social/#/greenCity and log in
2. Go to Events page and join 2 online and 2 offline events
3. Go to My Events and view added events

**Actual result**
The online and offline events are displayed  in random order

**Expected result**
1. The online events are filtered by date, so that later event has higher position in list
2. The offline events are filtered by place closer to the User's IP location, so that closer events have higher position in the list

**Postconditions**

DELETE FROM table1
WHERE id=<item1_id>;"

**User story and test case links**
E.g.: "User story #3375 
[Test case](https://jira.softserve.academy/browse/GC-5018)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Priadkohrystyna** [comment]
Need to fix, the online and offline events are still displayed in random order
