### ISSUE TITLE
[UBS. Admin Cabinet. Orders]  Wrong amount of bonuses adds to the user account when order has overpayment and status 'Виконано' on the page 'Order'

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5149]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 31.01.23

**Preconditions**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super Admin
3. Navigate to UBS menu > Orders
4. The order should be created and displayed on the table 'Orders'

**Steps to reproduce**
1. Open the order with the status 'Сформовано'
2. Change status Cформовано> Узгодження> Підтверджено> На маршруті > Виконано
3. Scroll down to the section 'Деталі замовлення' and reduce the amount of packages in column 'Actual amount' 
4. Pay attention on the message “Переплата <overpayment грн>” under the table 'Деталі замовлення'
5. Open the next section 'Oплата замовлення'
6. Press the bttn 'Зберегти'
7. Pay attention on record with overpayment sum and comment "Зарахування на бонусний рахунок" that added on section 'Oплата замовлення'
8. Pay attention on sum of the field "Замовлення oплачено у розмірі" on the section 'Oплата замовлення'

**Actual result**
Wrong amount of bonuses adds to the user account after admin reduces number of packages in column 'Actual amount 'in section 'Деталі замовлення' when order has overpayment and status 'Виконано'. 
At the same time in section "Оплата замовлення" wrong amount of bonuses is displayed as a record and the sum of the field "Замовлення оплачено у розмірі" is not recalculated correctly.

https://user-images.githubusercontent.com/116512982/216012487-13898874-ee01-4991-b4f5-3244657a3e49.mp4

![bug calculation](https://user-images.githubusercontent.com/116512982/216012947-cfcdfe5d-1de4-4d80-bcf6-2781dec7d618.jpg)

**Expected result**
If there is some overpayment amount, after admin reduce the number of packages in column 'Actual amount' (order status 'Виконано' ) and press the bttn "Зберегти" , the system should add the record in the table 'Оплата замовлення ' with the overpayment sum and comment 'Зарахування на бонусний рахунок'. 
Each time when a new payment amount is added on the table 'Оплата замовлення', the system should dynamically recalculate the total payment “Замовлення оплачено в розмірі”.
In this case, the total payment “Замовлення оплачено в розмірі” should be calculated by formula :
total payment = payment amount 1 - payment amount 2 with the comment “Зарахування на бонусний рахунок” 

![return overpayment](https://user-images.githubusercontent.com/116512982/216010861-bd3d051d-738e-45fe-8b3c-fcfd95ae7a15.jpg)

**The total payment “Замовлення оплачено в розмірі formula”**

![AC](https://user-images.githubusercontent.com/116512982/216015796-b0d08b68-37b1-4005-959a-1ee95d900ecf.jpg)

**User story and test case links**
User story [UBS Admin Cabinet] Return overpayment as bonuses to the client's bonuses account](https://github.com/ita-social-projects/GreenCity/issues/2900#top)#2900
[[UBS Admin Cabinet ] Order payment details](https://github.com/ita-social-projects/GreenCity/issues/2898#top)
#2898
Test case](https://jira.softserve.academy/browse/GC-5011

**Comment by BranetE** [comment]
Fixed with other task https://github.com/ita-social-projects/GreenCity/issues/5520
