### ISSUE TITLE
BUG[UI] Inconsistency in text labels: sign in(sign-in) and sign up(sign-up) 

### ISSUE THREAD

**Issue by yanaklyuchnyk** [ita-social-projects/GreenCity#515]
**Steps to reproduce:**
1. Go to:
https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'sign-up' hyperlink
3. Verify that all text labels are written in the same way:
sign-in/sign-up or sign in/sign up
**Actual result:**
Text labels for sign in/sign up option are inconsistent and written in different ways: sign in, sign-in, sign up, sign-up
**Expected result:**
Text labels should be written in the same way everywhere: with or without hyphen '-', with the same capitalization of first letters
Environment:
OS: Windows 10
Browser: Firefox Mozilla 73.0.1 / 64-bit
Google Chrome 80.0.3987.132 / 64-bit
![Text labels inconsistency](https://user-images.githubusercontent.com/61537703/76684239-dcea2b80-6612-11ea-8f36-b1712d347d12.JPG)

**Comment by nabermi2020** [comment]
Not relevant
