### ISSUE TITLE
[UBS. Admin Cabinet. Orders] The amount of ordered packages isn't displayed in section 'Деталі замовлення' of 'Order' page when user made order for location '20 кілометрів, Київ, Київська область' 

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5152]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 02.01.23

**Preconditions**
1. The order for location  '20 кілометрів, Київ, Київська область' should be created by user
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/orders
3. Sign in as Super Admin
4. Navigate to UBS menu > Orders

**Steps to reproduce**
1. Choose the created order for location  '20 кілометрів, Київ, Київська область' from table 'Orders'
2. Scroll down to section 'Деталі замовлення'
3. Pay attention on the amount of packages on the table 'Деталі замовлення'

**Actual result**
The amount of ordered packages isn't displayed in section 'Деталі замовлення' of 'Order' page when user made order for location '20 кілометрів, Київ, Київська область' 

![photo_2023-02-01_15-36-15](https://user-images.githubusercontent.com/116512982/216073340-31586ed9-454f-4a1d-9560-2f2ea4b0399b.jpg)

**Expected result**
The amount of ordered packages should be displayed in section 'Деталі замовлення' of 'Order' page when user made order for location '20 кілометрів, Київ, Київська область' 

**User story and test case links**
[UBS Admin Cabinet ] Packages quantity and order cost #2865

[Test case]https://jira.softserve.academy/projects/GC?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab

**Comment by katia9261** [comment]
It is not a bug now
![image](https://user-images.githubusercontent.com/101433204/231453926-1f27ed9d-9fec-4407-9fc9-dd8459600021.png)
