### ISSUE TITLE
The language icon is not aligned with other icons in the header for logged in user

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#516]
**Steps to reproduce:**

1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/welcome as logged in user
2. Pay attention to the language icon

**Expected Result:**
All icons are aligned to each other in the header for logged in user
**Actual Result:**
The language icon is upper than other icons in the header for logged in user
**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultima
#352

**Comment by Talichka** [comment]
![mock up](https://user-images.githubusercontent.com/40841118/76684524-4a975700-6615-11ea-9259-983fc7ccb165.png)
![language icon](https://user-images.githubusercontent.com/40841118/76684533-56831900-6615-11ea-90f2-f0a494e30ed6.png)

**Comment by KimAT25** [comment]
not relevant
