### ISSUE TITLE
[Event attendance] An authorized user can`t join to the ''Closed'' event.

### ISSUE THREAD

**Issue by LiliiaKhoroz** [ita-social-projects/GreenCity#5163]
**Environment:**
Windows 10 Pro 21H2
Google Chrome 109.0.5414.75

**Reproducible:** always
**Build found:** 01/02/2023

**Preconditions:**
1. The website https://www.testgreencity.ga/GreenCityClient/#/ is opened.
2. The user is signed in. (E.g. login: greencitycustomer@gmail.com password:Green@333)
3. Closed-type event is created by an Organizer, who is a friend of the user.
4. An authorized user has an event Organizer in his friend list.

**Steps to reproduce**
1. Click the ''Events'' link.
2. Observe the closed future event`s preview card.

**Actual result:** The ''See rating' button is displayed on the closed future event preview card.
**Expected result:** The ''Join event'' button is displayed on the closed future event preview card, an authorized user can join to the event.

**User story and test case links**
User story #3270 
[Test case]https://jira.softserve.academy/browse/GC-4899
![Screenshot_13](https://user-images.githubusercontent.com/123656862/216133706-02ec4f9f-1fea-4b9f-8775-29dc132c46bc.png)

**Comment by mdashko** [comment]
this bug is already fixed
