### ISSUE TITLE
[Create Event] This date is not highlighted in red color after selecting a past date.

### ISSUE THREAD

**Issue by OlenaSpivak** [ita-social-projects/GreenCity#5167]
**Environment:** Platform: 
Google Chrome 104.0.5112.79
Operating System: MacOS Monterey
OS Version: 12.5

**Reproducible:** always
**Build found:** 02.02.2023

**Steps to reproduce**

1. Go to https://www.testgreencity.ga/
3. Sign in as an Authorized user.
4. Click on the 'Event' page.
5. Click on the field 'Duration' and choose 1 day.
6. Click on the calendar icon.
7. Choose a past date.

**Actual result**
This date is not highlighted in red color after selecting a past date.

**Expected result**
This date is highlighted in red color after selecting a past date.

**User story and test case links**
Create Event #3193
[Test case]([GC-3071](https://jira.softserve.academy/browse/GC-3071))"

**Labels to be added**
"Bug", Priority ("Low: "), Severity ("Minor"), Type ("Functional")
<img width="662" alt="Знімок екрана 2023-01-26 о 10 56 12" src="https://user-images.githubusercontent.com/123725975/216314592-b7a62fb7-dc15-444b-9295-4f3b4d3643fb.png">

**Comment by ruslan-teh** [comment]
not relevant, the user cannot select a date in the past
