### ISSUE TITLE
[API UBS / Management Order Controller] The amount of bonuses is added twice when using the  method POST Return overpayment to user

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5169]
**Environment:** 
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110 
**Reproducible:** always, 
**Build found:** 02/02/2023

**Preconditions**

1. Open API documentation for UBS Courier
2. Go to block 'Management Order Controller'

**Steps to reproduce**
1. Choose method POST Return overpayment to user
2. Authorize with bearer  token 
3. fill in orderId and body{
  "bonuses": 0,
  "comment": "string",
  "overpayment": 0
}  (e.g {
  "bonuses": 60,
  "comment": "Зарахування на бонусний рахунок",
  "overpayment": 60
}
)
4. Pay attention   to the added  bonuses to user  
**Actual result**
The amount of bonuses is added twice when using the  method POST Return overpayment to user
**Expected result**
The   bonuses returned to the user, the amount level is assigned in the body of the request method and is not duplicated

**User story and test case links**
E.g.: "User story #2900

![image](https://user-images.githubusercontent.com/116280846/216320792-8154cfd4-aa69-4a15-afdb-80b7d85dcb85.png)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by JoseCaste** [comment]
Hi, I'd like to know how many orders and how many Bonuses do you have.
Because I have reproduce your step but I can't see the same results.
AS you can see, the list is correctly
![step](https://user-images.githubusercontent.com/70968629/216398065-7659cc75-c2f5-456c-b251-130083043801.png)

**Comment by RoksolanaKolomiyets** [comment]
Hello ! first can you say  What do you have  operating system ?

Windows or Mac OS .

Because this bug reproduce only Mac OS.


чт, 2 лют. 2023, 19:29 користувач José Castellanos ***@***.***>
пише:

**Comment by JoseCaste** [comment]
Windows 10. 
But, I'd like to know if Did you test it on windows machine?

**Comment by RoksolanaKolomiyets** [comment]
this bug does not reproduce on  windows machine only Mac.we
investigated this when testing with colleagues.

you will not be able to reproduce this bug on  windows machine


чт, 2 лют. 2023 р. о 19:49 José Castellanos ***@***.***> пише:

**Comment by JoseCaste** [comment]
Very strange, the following image was made with Mac machine, please, Could you send greencity url?

![photo_2023-02-02_11-59-36](https://user-images.githubusercontent.com/70968629/216423633-ea2fffc4-db82-4e89-8093-0954e317840a.jpg)

**Comment by JoseCaste** [comment]
It was not reproducible neither mac or windows machine

**Comment by Olena-Kharkova** [comment]
Hello! It's reproduced on Windows OS too
1. User has a paid order
2. As Admin you should cancel this User's order 
3. By using Swagger you should use the POST method to add bonuses to the User (please, use this endpoint [/ubs/management/return-overpayment](management-order-controller/returnOverpaymentUsingPOST)
and check the sum of added bonuses.
I have ordered an Order (Id1142) and added 1 000 UAH to User (myself) successfully with 2 attempts, and the User get twice 1 000 UAH in each case. So, now I have 4 000 UAH

![image](https://user-images.githubusercontent.com/110603507/218824939-56f12e74-4e0e-4a97-88a3-1823d6987187.png)

**Comment by Olena-Kharkova** [comment]
> Very strange, the following image was made with Mac machine, please, Could you send greencity url?
> 
> ![photo_2023-02-02_11-59-36](https://user-images.githubusercontent.com/70968629/216423633-ea2fffc4-db82-4e89-8093-0954e317840a.jpg)

https://www.testgreencity.ga/GreenCityClient/#/

**Comment by MaksymGolik** [comment]
At the moment this endpoint is not used, instead it is overpaid for the order and if you cancel the order the endpoint /add-bonuses-user/{id} is used for a refund. Endpoint /ubs/management/return-overpayment was not cut at the moment, because it still can be necessary when implementing the payback NOT on the bonus account, this moment is being clarified.

**Comment by JoseCaste** [comment]
Please, could you share with us a video with the steps using the Return overpayment method?
Also, when you are having duplicate data @Olena-Kharkova

**Comment by Olena-Kharkova** [comment]
> Please, could you share with us a video with the steps using the Return overpayment method? Also, when you are having duplicate data @Olena-Kharkova

Yes, here is the video 

https://user-images.githubusercontent.com/110603507/220565930-ede4add6-4103-48af-a25b-b8424a9a48a3.mp4

**Comment by Olena-Kharkova** [comment]
> Please, could you share with us a video with the steps using the Return overpayment method? Also, when you are having duplicate data @Olena-Kharkova

I guess that if we fill up both keys: 'bonuses' and 'overpayment' it causes such adding.
{
  "bonuses": 560,
  "comment": "Зарахування на бонусний рахунок",
  "overpayment": 560
}

https://user-images.githubusercontent.com/110603507/220566733-45006e9e-1f41-4864-a54c-b57823287b99.mp4

If we set some changes to the JSON: fill up, for example, 'bonuses' with '0' it returns 0 and 560 UAH  we have the next result, but it is also incorrect, I suppose
{
  "bonuses": 0,
  "comment": "Зарахування на бонусний рахунок",
  "overpayment": 560
} 
![QEKLIdGOJL](https://user-images.githubusercontent.com/110603507/220568456-49682db4-4ef0-4eaa-908a-f9ae032b7feb.png)

**Comment by JoseCaste** [comment]
We deleted that endpoint because is not used for anything
