### ISSUE TITLE
Localizational mistakes on the Home page for unregistered user

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#517]
**Steps to reproduce:**
1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/welcome 
2. Pay attention to the mistakes, shown in the attachments

**Expected Result:**
All content, titles and buttons should be appropriately translated in the chosen language
**Actual Result:**
'localization1' file - 'Введіть ваш email' is not translated into Eng
'localization2' file - Content in 'Eco-advices' block is not translated into Eng and Рус
'localization3' file -  'Введіть ваш email' is not translated into Рус. A grammar mistake in the phrase 'интересные новости' and there is a mistake in the word 'чтобы'
**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultima
![localization1](https://user-images.githubusercontent.com/40841118/76686331-483bf980-6623-11ea-93af-674689b41675.png)
![localization2](https://user-images.githubusercontent.com/40841118/76686335-4eca7100-6623-11ea-8046-2e38a159e84c.png)
![localization3]
![localization3](https://user-images.githubusercontent.com/40841118/76686784-ac13f180-6626-11ea-8193-e0517ed62772.png)
#352

**Comment by rsyvulko** [comment]
Not fixed in full
'localization1' and 'localization3' files - **fixed**
'localization2' file - Content in 'Eco-advices' block is not translated into Eng and Рус - **not fixed.**
Windows 10 x64, Mozilla Firefox 76.0 (64-bit)

**Comment by yuriizhurakovskyi** [comment]
Eco-advises changed to Tips & Tricks and still not added, grammar mistakes and translations fixed

**Comment by Volodymyr-Danyliv** [comment]
'localization2' file - Content in 'Eco-advices' block is not translated into Eng and Рус
