### ISSUE TITLE
The Home page is not scrolled using scrollbar after resizing the page to 250%

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#518]
**Steps to reproduce:**

1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Resize the page to 250%
3. Expand the Menu icon
4. Pay attention to the scroll
**Expected Result:**
The page is scrolled using the scrollbar
**Actual Result:**
The page is frozen and no action is done after scrolling
**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultima
![resize](https://user-images.githubusercontent.com/40841118/76687416-593d3880-662c-11ea-8506-11213eed404a.png)
#352

**Comment by rsyvulko** [comment]
Not fixed
Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
