### ISSUE TITLE
The Menu block is not aligned relative to the Logo after resizing the Home page while changing the languages

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#519]
**Steps to reproduce:**
1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Resize the page to 125%
3. Pay attention to the Menu block alignment relative to the Logo after changing the languages
**Expected Result:**
The Menu block is aligned relative to the Logo
**Actual Result:**
The Menu block is not aligned relative to the Logo after resizing the Home page while changing the languages

**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultim
#354

**Comment by Talichka** [comment]
https://drive.google.com/file/d/1-5_Ot0a8A4Oa9CY3dmIabmOo6Yzraynd/view?usp=sharing

**Comment by KimAT25** [comment]
not relevant
