### ISSUE TITLE
[UBS Admin. Orders. Order details. Canceled order] The change event 'Зараховано кошти на бонусний рахунок клієнта' and "Скасовано" status are not logged and not displayed in the block 'Історія замовлення'  

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5195]
**Environment:**
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71, Firefox version 109.0
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 04/02/2023

**Preconditions**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super Admin
3. Go to the Super Admin profile and choose the UBS-Admin item
4. Choose the 'Orders' item
5. Click on the Order's number in the Order table (except orders with 'Виконано'/ 'Скасовано' statuses)

**Steps to reproduce**
1. Go to the block 'Оплата замовлення' and check the overpayment presence 
2. Click on the " Зарахувати на бонусний рахунок" bttn
3. Scroll to the block 'Історія замовлення' on the order details page and check the info about changing. There is no logging of the change event 'Зараховано кошти на бонусний рахунок клієнта'

**Actual result**
The change event 'Зараховано кошти на бонусний рахунок клієнта' and "Скасовано" status are not logged and not displayed in the block 'Історія замовлення'  

**Expected result**
The change event 'Зараховано кошти на бонусний рахунок клієнта' is logged and displayed in the block 'Історія замовлення' when the record with comment “Зарахування на бонусний рахунок” was added to the table with order payment details (story https://github.com/ita-social-projects/GreenCity/issues/2900, scenario 1 and 3, acceptance criteria 2)

**User story and test case links**
E.g.: "User story #5111 ](https://github.com/ita-social-projects/GreenCity/issues/3217)
[Test case](https://jira.softserve.academy/browse/GC-4727)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

https://user-images.githubusercontent.com/110603507/216769299-cafb5bb3-c255-4b92-8b78-134573e97b2d.mp4

**Comment by MaksymGolik** [comment]
Hi @KharchenkoV . Part of this issi: "change event 'Зараховано кошти на бонусний рахунок клієнта'" already fixed in PR related to previous issue #5062.
