### ISSUE TITLE
[UBS Admin. Orders. Order details] The change event 'Зараховано кошти на бонусний рахунок клієнта' is not logged and not displayed in the block 'Історія замовлення' when the record with the comment “Зарахування на бонусний рахунок” was added to the table with order payment details in case of order status  'Виконано' 

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5196]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71, Firefox version 109.0
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
**Reproducible:** always
**Build found:** 04/02/2023

**Preconditions**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super Admin
3. Go to the Super Admin profile and choose the UBS-Admin item
4. Choose the 'Orders' item
5. Click on the Order's number in the Order table with 'Виконано' status

**Steps to reproduce**
1. Go to the block 'Оплата замовлення' and add payment in order to make an overpayment
2. Scroll down and click on the 'Зберегти' bttn 
3. Go to the block 'Історія замовлення' on the order details page and check the info about changing

**Actual result**
The change event 'Зараховано кошти на бонусний рахунок клієнта' is not logged and not displayed in the block 'Історія замовлення' when the record with the comment “Зарахування на бонусний рахунок” was added to the table with order payment details in case of order status  'Виконано' 

**Expected result**
The change event 'Зараховано кошти на бонусний рахунок клієнта' is logged and displayed in the block 'Історія замовлення' when the record with comment “Зарахування на бонусний рахунок” was added to the table with order payment details (story https://github.com/ita-social-projects/GreenCity/issues/2900, scenario 1 and 3, acceptance criteria 2)

**User story and test case links**
E.g.: "User story #[100](https://github.com/ita-social-projects/GreenCity/issues/3217)
[Test case](https://jira.softserve.academy/browse/GC-4727)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

https://user-images.githubusercontent.com/110603507/216770478-bfa68dad-ac3c-4b31-9411-17152cde2cc7.mp4

**Comment by MaksymGolik** [comment]
The issue is the same as in [#5062](https://github.com/ita-social-projects/GreenCity/issues/5062). Already fixed.
