### ISSUE TITLE
[UBS Admin. Orders. Order details. API] The bonuses could be added to the Client without checking the overpayment presence by method POST

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5197]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71, Firefox version 109.0
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 04/02/2023

**Preconditions**
1. Go to the Swagger 
2. Authorize with JWT(API key - bearer)

**Steps to reproduce**
1. Go to 'Management Order Controller'
2. Click on the 'POST'- method with path [/ubs/management/return-overpayment](https://greencity-ubs.testgreencity.ga/swagger-ui.html#/operations/management-order-controller/returnOverpaymentUsingPOST)
3. Fill up all needed items in JSON for order with  Cancel status and overpayment presence 
4. Execute POST method one time - response code 200 OK
5. Execute it again - response code 200 OK too

**Actual result**
The bonuses could be added to the Client without checking the overpayment presence by method POST

**Expected result**
The bonuses could be added to the Client by checking the overpayment presence by method POST. In case when Client has already gotten his/her bonuses and overpayment was returned to his/her account response on the POST method might be 400 Bad Request

**User story and test case links**
E.g.: "User story #2900"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![image](https://user-images.githubusercontent.com/110603507/216771345-4343470c-7c26-413e-a7e9-c77b302e6759.png)

**Comment by MaksymGolik** [comment]
This endpoint was removed in the [pull request](https://github.com/ita-social-projects/GreenCityUBS/pull/1027).
