### ISSUE TITLE
[ita-social-projects/GreenCity][UBS User orders] UI Fonts of the Popup window do not correspond to mockup

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5198]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 02/04/2023
**Mockup:**
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12201%3A2&t=71xJ77BZ5Gfezk9q-0

**Preconditions**
1. Logg as a User to https://www.testgreencity.ga/GreenCityClient/
2. Goto Profile-->Ubs User

**Steps to reproduce**
1. Click on 'New Order' bttn
2. On next window by '+' and '-' choose waste amount in order to make 'Next' bttn active
3. Choose 'Next' bttn, click on 'Add address' bttn

**Actual result**
1.A popup window is opened with incorrect font familty 'Roboto'
2.The font size of the 'Delete' button is 14 px
3. The colour of the 'Delete'button is Red '#eb180d' 

**Expected result**
1.A popup window is opened with font -family 'Lato' according to mockup
2. The font size of the 'Delete' button is 16 px
3. The colour of the 'Delete'button is black according to the mockup

**User story and test case links**
E.g.: "User story #3811 
[Test case](https://jira.softserve.academy/browse/GC-5045)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![Clip_14](https://user-images.githubusercontent.com/119998851/216811281-13233841-2646-4149-a82b-b4bd936751b9.jpg)
![Screenshot 2023-02-05 102952](https://user-images.githubusercontent.com/119998851/216811105-b9ef4daf-0783-4284-9f7d-a0ee86789f01.png)

**Comment by BohdanaYuzkiv** [comment]
![delete_button_incorrect_color_style](https://github.com/ita-social-projects/GreenCity/assets/109086383/48ff7ed6-b06b-4799-9e7a-0e6864bf310d)
"Delete" button isn't fixed

**Comment by Vadym840217** [comment]
Bug is fixed
