### ISSUE TITLE
[UBS_admin. Orders] The frame of the added field 'Номер замовлення з магазину' is colored red after admin presses  'Додати ще номер замовлення' in section 'Деталі замовлення' of 'Order' page"

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5208]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 08.02.23

**Preconditions**
1. User is logged in as an administrator.
2. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/
3. Navigate to UBS > Orders
4. The new order should be created

**Steps to reproduce**
1. Press on the number of created order on table 'Orders'
2. Scroll down to section 'Деталі замовлення' of the page 'Order'
3. Click on the bttn 'Додати ще номер замовлення' and pay attention on the frame of added field 

**Actual result**
The frame of added field 'Номер замовлення з магазину' is colored red after admin presses  'Додати ще номер замовлення' in section 'Деталі замовлення' of 'Order' page
![номер замовлення](https://user-images.githubusercontent.com/116512982/217515585-059f87cc-81e3-4f8f-941c-fe7458ede9be.jpg)

**Expected result**
The frame of the added field should not be colored red after admin presses  'Додати ще номер замовлення' in section 'Деталі замовлення' of 'Order' page.

**Comment by DanaIuich** [comment]
Bug is fixed
