### ISSUE TITLE
[UBS User] User cannot delete addresses from 'User Data' Page in his/her UBS Profile

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5210]
**Environment:** Windows 11 Home 64 bit, Chrome Version 108.0.5359.125 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 02/09/2023

**Preconditions**
1.User Logged to https://www.testgreencity.ga
2.Goto Profile-->UBS User
3.Goto User data
4.User have at least 2 addresses filled in 'User Data'Page

**Steps to reproduce**
1. Click on 'Edit data' button

**Actual result**
List of addresses displayed without 'Delete' button
![Screenshot 2023-02-09 102435](https://user-images.githubusercontent.com/119998851/217756993-39e27517-e8f7-4545-be1f-2b0b62c003bd.png)

**Expected result**
List of addresses displayed with 'Delete' button near each address according to mockup
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=20703%3A62409&t=22YTY9kfcKYydR0e-0
![Screenshot 2023-02-09 101206](https://user-images.githubusercontent.com/119998851/217754425-2a95c541-217d-4822-900e-00f6c59ee540.png)

**User story and test case links**
User Story:  #3811

**Comment by atsa21** [comment]
Not reproduce. On screenshot is wrong link that include GreenCityClient
