### ISSUE TITLE
[ Pickup city UBS.Registration form] The Error message incorrect in field Email when the user presses the spacebar on the keyboard on the Registration page

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5219]
**Environment:**MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always .
Build found: 10/01/2023
**Preconditions**
Go to https://www.pick-up.city/GreenCityClient/#/ubs

**Steps to reproduce**

1. Click on button "Зареєструватись""
2. Presses the spacebar on the keyboard in field Email

**Actual result**
the error message incorrect "Введіть пошту"
**Expected result**
the error message correct  "Перевірте, чи правильно вказано вашу адресу електронної пошти"

**User story and test case links**
E.g.: "User story #4099

**Labels to be added**
"Bug", Priority ("pri: "Low), Severity ("severity:minor"), Type ("UI, "Functional"),

**Comment by atsa21** [comment]
Not a bug
![image](https://user-images.githubusercontent.com/104850911/226949465-72ea6c85-bb65-4757-8161-f717c3c58101.png)
