### ISSUE TITLE
#3333[UBS admin] The 'Certificate' button on the Admin tab doesn't exist 

### ISSUE THREAD

**Issue by maru0909** [ita-social-projects/GreenCity#5222]
**Issues:** #3333 

**Environment:** MacOS Ventura 13.2 (22D49), Safari 16.3 (18614.4.6.1.5), Chrome, Windows 10, 11; Mozilla Firefox.
**Reproducible:** Always.

**Preconditions**
1) Go to page: https://www.testgreencity.ga/#/ubs
2) log in to the admin profile with the valid date: 
Login: *****
Password: *****

**Steps to reproduce**
1. Click on the GreenCityAdmin button in the upper right corner of the page
2. Select the UBS-user tab from the drop-down list
3. Click on the certificate tab on Admin bar on left side of the page (_the defect appears here_)

**Actual result**
The 'Certificate' button on the Admin tab doesn't exist 

**Expected result**
The 'Certificate' button exist on the Admin tab 

**User story:** #4884 
[Test case](https://jira.softserve.academy/browse/WR50QC-559)

<img width="1404" alt="bug_certificate" src="https://user-images.githubusercontent.com/64164676/218271329-8626e988-0604-4975-b54f-9dafe15d7baf.png">

**Comment by SWalaszek** [comment]
Wrong admin account used.
