### ISSUE TITLE
#2198 [Order form] Missing error message after entering invalid data.

### ISSUE THREAD

**Issue by NataliaRyczek** [ita-social-projects/GreenCity#5228]
Environment: Chrome 108, Windows 10
Reproducible: always

**Preconditions**
1. Go to: https://www.testgreencity.ga/#/ubs
2. Log in with ADMIN credentials.
3. Go to "Order" tab.

**Scenario 1**

**Steps to reproduce**
1. Go to: "Personal data" tab.
2. In"Name" field enter: "Alina90".
3. Check the results

**Actual result**
No Error message appear

**Expected result**
Error message appear: **"Only letters and hyphen, space, apostrophe are allowed**".

**Scenario 2**
1. Go to: "Personal data" tab.
2. In"Surname" field enter:"Kropka21".
3. Check the results

**Actual result**
No Error message appear

**Expected result**
Error message appear: **"Only letters and hyphen, space, apostrophe are allowed**".

**User story and test case links**
E.g.: "User story #2198 
[Test case](https://jira.softserve.academy/browse/WR50QC-563)"

**Attachment:**
![2023-02-12 19 47 07](https://user-images.githubusercontent.com/51031973/218330891-b25ca0d8-ad80-428c-8bde-217b0287a1aa.png)

**Comment by Vadym840217** [comment]
According to #5719, the user can fill in numeric characters after the first and last name
The administrator is not able to create an order like usual user
