### ISSUE TITLE
[UBS Admin Cabinet ] Admin can save changes to the waste disposal address when the system doesn’t display auto-filled district in the 'District' field in the En localization 

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5229]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 110.0.5481.78 (64-bit).
**Reproducible:** sometimes. It reproduces only when the district is auto-filled, but not for all districts.
**Build found:** 12/02/23

**Preconditions**

1. User is logged in as administrator.
2. Orders tab is opened.
3. At least 1 order is in the orders table with 'Kyiv' city.
4. En localization.

**Steps to reproduce**
1. Click on the particular order.
2. Click on the 'Waste export address' menu.
3. Select the street from the dropdown list in the 'Street' field 
e.g. 'Obolonskyi Avenue' 
5. Pay attention to the 'District' field.
6. Click on the 'Save' buttons.

**Actual result**

Admin can save the waste disposal address when the 'District' field is empty.

![Снимок экрана 2023-02-08 110359](https://user-images.githubusercontent.com/119864646/218329184-1f1bd409-2e6c-4739-93ef-8b85e73d63f2.png)

![photo_2023-02-10_16-33-31](https://user-images.githubusercontent.com/119864646/218331558-281c0af3-53ec-4b55-8b78-d29cf51f6662.jpg)

**Expected result**

'District' field is highlighted in red and an error message in red appears below the field: "This field is required". 'Cancel' and 'Save' buttons are disabled.

**User story and test case links**
E.g.: "User story #5101 

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Minor"), Type ("Functional").

**Comment by atsa21** [comment]
Can't reproduse
