### ISSUE TITLE
[UBS.Order form] The user can't add a new address after typing the full name of city and street in the 'Місто' and 'Вулиця' fields when the system doesn't have any suggestion based on API in the 'Нова адреса' pop-up

### ISSUE THREAD

**Issue by olyatyshchenko** [ita-social-projects/GreenCity#5230]
**Environment:** Windows 10, Google Chrome Version 110.0.5481.78 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** 13/02/2023

**Preconditions**

1. Login to GreenCity as a User [https://www.testgreencity.ga/GreenCityClient/#](https://www.testgreencity.ga/GreenCityClient/)
2. UBS Order form is opened.
3. All required fields on the tab "Деталі замовлення" are filled in and the tab "Особисті дані" is active .
4. User can add only 4 addresses.

**Steps to reproduce**
1. Click on the "Додати адресу" button.
2. Type the full name of the city in the 'Місто' field
3. Type the full name of the street in the 'Вулиця' field
4. Fill in the  'Будинок' and 'Район' fields as required.
5. Pay attention to the 'Додати адресу' button.

**Actual result**
The 'Додати адресу' button is disabled when user type the full name of city and street in the 'Місто' and 'Вулиця' fields on the 'Нова адреса' pop-up

https://user-images.githubusercontent.com/120178274/230457050-2b163da7-b21b-4928-8fff-d3ee5ee959e8.mp4

**Expected result**
The 'Додати адресу' button is enabled.

**Additional info**
Bug is also reproduced in the Admin Cabinet

**User story and test case links**
"User story" #5101, #2199

**Comment by atsa21** [comment]
It is impossible to select the street that not exist from google map search (Ростиславська)
