### ISSUE TITLE
[UBS_Prod. Client. Sign up] Incorrect messages are displayed under the field 'Email' on EN/UA localization when the user typed e-mail that doesn't meet criteria on pop-up 'Sign up'

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5232]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 13.02.23

**Preconditions**
Go to the https://www.pick-up.city/

**Steps to reproduce**
1. Set UA localization of the main page 'Pick-up'
1. Click Sign up button
2. Fill out on the field 'Email' (e.g. example_mail)
4. Pay attention on the message that appears after typing wrong email on UA localization
5.  Set EN localization of the main page 'Pick-up'
6. Click Sign up button
2. Fill out on the field 'Email' (e.g. ubs_mail)
4. Pay attention on the message that appears after typing wrong email on EN localization

**Actual result**
 Incorrect messages are displayed  when user typed something in email text field, and written doesn't meet criteria:
En: "Please check that your e-mail address is indicated correctly"
UA: "Перевірте, чи правильно вказано вашу адресу електронної пошти"
![pick up](https://user-images.githubusercontent.com/116512982/218404837-5ae42119-e3f9-4f2a-9ec2-f09b1cbffa16.jpg)

![pick-up 2](https://user-images.githubusercontent.com/116512982/218404848-aabdd3d6-c2fc-42d9-874a-48335c10f87f.jpg)

**Expected result**
If a user typed something in email text field, and written doesn't meet criteria, then error message should be displayed:
En: “Please check if the email is written correctly.”.
Ua: ”Перевірте коректність введеної електронної адреси”
![pick-up 3](https://user-images.githubusercontent.com/116512982/218404872-4768dcdd-f4b5-467b-b617-147ef90fb766.jpg)
![pick-up 4](https://user-images.githubusercontent.com/116512982/218404879-75c21acb-92a6-44ec-9132-184898c45cd0.jpg)

**User story and test case links**
https://github.com/ita-social-projects/GreenCity/issues/4277
https://github.com/ita-social-projects/GreenCity/issues/4099

**Comment by BohdanaYuzkiv** [comment]
Incorrect messages are displayed:
![incorrect_mess_mail](https://github.com/ita-social-projects/GreenCity/assets/109086383/8223e76d-f262-435d-8e04-ba5871427ddb)
![mail_incorrect_message](https://github.com/ita-social-projects/GreenCity/assets/109086383/d915cda5-817c-4a81-8e7a-8692da20d74d)

**Comment by atsa21** [comment]
Fixed on prod
