### ISSUE TITLE
[UBS-User. Edit profile] The new address isn't displayed after its adding on the 'Дані користувача' page

### ISSUE THREAD

**Issue by olyatyshchenko** [ita-social-projects/GreenCity#5237]
**Environment:**  Windows 10, Google Chrome Version 110.0.5481.78 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** 13/02/2023
**Preconditions**
Preconditions
1. Log in to the GreenCity as User [https://www.testgreencity.ga/GreenCityClient/#](https://www.testgreencity.ga/GreenCityClient/)
2. User's personal account 'UBS-user' is opened.
3. The user is in the personal account on the 'Редагувати дані' page.
4. User can add only 4 addresses.

**Steps to reproduce**
1. Click on the "Додати адресу" button.
2. Fill in all required address fields.
3. Click on the "Зберегти зміни" button.

**Actual result**
The created address isn't displayed on the 'Дані користувача' page. The created address is displayed after refreshing the page. 

**Attachments**
https://www.loom.com/share/5348c90bcc89446f9878943669221e06

**Expected result**
The created address is displayed on the 'Дані користувача' page. 

**User story and test case links**
E.g.: "User story #3811

**Comment by katia9261** [comment]
The bug is not reproduced now
