### ISSUE TITLE
News page: language of news display

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#524]
As a User, I want to be able to select one or more languages for the News to be displayed, so I can see content in all available languages if needed. 
Mock-up:
<img width="627" alt="Screenshot_78" src="https://user-images.githubusercontent.com/60645819/77057557-cd852c80-69dc-11ea-8502-c6f5b2a691d7.png">
Acceptance criteria:
1. The language of the interface (selected in the header), should be selected for News display by default. So if User, sees page in Ukrainian, the Ukrainian language should be selected for News display as well. 
2. User should be able to select one or more languages for News display. 
3. User should be able to uncheck the box if only one language is selected, in this case News in all available languages will be displayed. So the behavior of all unchecked boxes = behavior of all checked boxes.  
4. User should be able to uncheck the box by clicking on the checked box.

**Comment by rsyvulko** [comment]
Not relevant.
