### ISSUE TITLE
[App] Unification of scroll bar styles all over the page

### ISSUE THREAD

**Issue by SokhaTaras** [ita-social-projects/GreenCity#5241]
Environment:
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

Reproducible: always
Build found: 13/02/2023

Preconditions

Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
Sign in as Super Admin/User (does not matter)

Pay attention we have different scroll bar styles in our app

Actual result: We have different scroll bar styles in our app
![image](https://user-images.githubusercontent.com/86615598/218455095-d7a33f50-32cb-49a6-9f8f-4c6e45b5083b.png)
![image](https://user-images.githubusercontent.com/86615598/218455176-59a37c4d-339d-40b6-a8e4-f1b32628b1a4.png)
![image](https://user-images.githubusercontent.com/86615598/218455317-32beb2ef-f53c-4719-b8b6-0fd5f9924338.png)

Expected result: scroll bar style are unified all over the app
![image](https://user-images.githubusercontent.com/86615598/218454917-d128b101-4d4d-490c-acfd-601efa98de53.png)
![image](https://user-images.githubusercontent.com/86615598/218454619-93a7dddc-5987-4cad-a01e-011116d953c3.png)
![image](https://user-images.githubusercontent.com/86615598/218455004-1c95c429-cbea-419a-8ddb-835a54a127d6.png)

**Comment by Olena-Kharkova** [comment]
The bug is still reproduced on Mozilla Firefox
![image](https://user-images.githubusercontent.com/110603507/222217483-003a2679-0631-467a-a503-7dca5b4fd017.png)

**Comment by ShyraiDan** [comment]
Can't reproduce

**Comment by snezhanapravdyuk** [comment]
Scroll bar is missing

![изображение](https://github.com/ita-social-projects/GreenCity/assets/165433958/483e8aa3-ff74-4097-a1ff-10957126ab11)
