### ISSUE TITLE
[UBS_Prod. Client. Sign up] Incorrect message is displayed on EN/UA localization when user typed password more than 20 symbols on the pop-up 'Sign up''

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5242]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 13.02.23

**Preconditions**
Go to the https://www.pick-up.city/

**Steps to reproduce**
1. Set UA localization of the main page 'Pick-up'
2. Click 'Sign up' button
3. Type a password in the field 'Password', that contains more than 20 symbols (e.g. aaaaaBBBBBccccc!12345)
4. Pay attention to the message under the field 'Password'
5. Set EN localization of the main page 'Pick-up'
6. Click 'Sign up' button
7. Type a password in the field 'Password', that contains more than 20 symbols (e.g. aaaaaBBBBBccccc!12345)
8. Pay attention to the message under the field 'Password'

**Actual result**
An incorrect message is displayed on EN/UA localization when user enters the password more than 20 symbols on the pop-up 'Sign up'':
Ua: "Пароль задовгий, дозволено не більше 20 символів"
En: ''Password is too long, a maximum of 20 characters allowed"

![password 1](https://user-images.githubusercontent.com/116512982/218475874-6a55f5b9-91b6-4c58-83b3-5a81467e766d.jpg)

![password 3](https://user-images.githubusercontent.com/116512982/218475887-0859a1f4-a736-412d-b845-ed2a9ae205e3.jpg)

**Expected result**
If a user clicked on password text field, and typed more than 20 symbols, then the error message appears:
En: “Password must be less than 20 characters long without spaces.”
Ua: “Пароль повинен містити менше 20 символів без пробілів.”.

**User story links**
https://github.com/ita-social-projects/GreenCity/issues/4277
https://github.com/ita-social-projects/GreenCity/issues/4099

**Comment by BohdanaYuzkiv** [comment]
Incorrect message with UA localization. Should be: 
Ua: “Пароль повинен містити менше 20 символів без пробілів.”
En: “Password must be less than 20 characters long without spaces.”
![password_incor_ms](https://github.com/ita-social-projects/GreenCity/assets/109086383/8215784e-abbf-4990-b539-55ccf682f66f)

**Comment by AlexW8719** [comment]
In the task, the changes concern the "Sign Up" form, but you sent "Sign In" instead. If similar changes are also needed there, I will make them quickly.

**Comment by BohdanaYuzkiv** [comment]
yup, you are right. my fault, this is for 'sign in'. i will make a new bug then

**Comment by AlexW8719** [comment]
Okay, and subscribe me, I've already completed it with another task.
