### ISSUE TITLE
[ Pick up city UBS.Restore password] User sees incorrect the link name in the email when he/she receives the "Password reset" and "Successful change password" emails 

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5253]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 110.0.5481.97 (64-bit).
**Reproducible:** always (prod)
**Build found:** 15/02/23

**Preconditions**

1. User is registered as user. 
2. "Pick up city UBS' home page is opened.

**Steps to reproduce**
1. Click on the "Sign in" button.
3. Enter the email address in the "Email" field.
4. Click the "Forgot password?" link.
5. Enter the same email address in the "Email" field.
6. Click on the "Submit a login link".
7. Go to the email address.
8. Open a particular email.
9. Pay attention to the link name in the email.
10. Click on the "Change password" button.
11. Enter a new password in the "Password" field.
12. Repeat entering the new password in the "Confirm password" field.
13. Click on the "Change password" button.
14. Repeat steps 7-8.
15. Pay attention to the link name in the email.

**Actual result**

User sees the incorrect "Green City UBS' link name in the "Password reset' and "Successful change password" emails. 

![image](https://user-images.githubusercontent.com/119864646/220463913-08012312-312f-481a-be25-54f18de8f32f.png)
![image](https://user-images.githubusercontent.com/119864646/220466561-543a3282-b660-4e68-9d02-d4dc8e9e5250.png)

**Expected result**
User should see the "Pick up city UBS " link name in the "Password reset' and "Successful change password" emails. 

**User story and test case links**
E.g.: "User story #4103, #4104, #5282

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity:Minor"), Type ("UI").

**Comment by MaksymGolik** [comment]
Already fixed by this PR https://github.com/ita-social-projects/GreenCityUser/pull/218
