### ISSUE TITLE
#4392 [UBS-admin. Employees] Bookmark 'Employees' view on the Admin bar doesn't exist

### ISSUE THREAD

**Issue by maru0909** [ita-social-projects/GreenCity#5270]
Issues: #4392 
**Environment:** MacOS Ventura 13.2 (22D49), Safari 16.3 (18614.4.6.1.5), Chrome, Windows 10, 11; Mozilla Firefox.
**Reproducible:** Always.

**Preconditions**
Go to page: https://www.testgreencity.ga/#/ubs
log in to the admin profile with the valid date:
Login: *****
Password: *****

**Steps to reproduce**
1. Click on the GreenCityAdmin button in the upper right corner of the page
2. Select the UBS-user tab from the drop-down list
3. Click on the 'Employees' tab on the Admin bar on the left side of the page (the defect appears here)

**Actual result**
The 'Employees' button on the Admin tab doesn't exist

**Expected result**
The 'Employees' button on the Admin tab exists

[Test case](https://jira.softserve.academy/browse/WR50QC-573)"
<img width="1421" alt="2023-02-19_17-02-38" src="https://user-images.githubusercontent.com/64164676/219959748-379e4455-c2e9-4a2b-8dcd-15c11cc0a64d.png">

**Comment by atsa21** [comment]
Not reproduce
