### ISSUE TITLE
[UBS order form] Incorrect section name for payment(2200)

### ISSUE THREAD

**Issue by IrusiaVI** [ita-social-projects/GreenCity#5271]
**Environment:** 
macOS Mojave 10.14.6 , browser Chrome Version 110.0.5481.77 
**Reproducible:** 
always
**Build found:** 
last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev

**Preconditions**
The registered user is available 

**Steps to reproduce**
1. Login as registered user
2. Click "Замовити" button
3. Fill the “Деталі замовлення” tab and click "Далі" button (Select 2 for "Мікс відходів", select 1 for "Текстильні відходи 60л")
4. Fill the “Особисті дані” tab and click "Далі" button (Ім'я: Ala
Прізвище: Bart Номер телефону: +380 (48) 787 55 67 Email: alabart@gmail.com)

**Actual result**
1. Section is called "Оплата" instead of "Спосіб оплати"
2. Default value for drop-down “Спосіб оплати” is "Карткою через Fondy"

**Expected result**
1. Section is called “Спосіб оплати”
2. The user can see drop-down “Спосіб оплати”:
system displays "Карткою через LiqPay" by default.

**User story and test case links** 
Issue on GitHub: [UBS] Review order summary and submit order #2200

[Test execution in JIRA](https://jira.softserve.academy/secure/enav/#/50096)

<img width="561" alt="Zrzut ekranu 2023-02-17 o 16 52 36" src="https://user-images.githubusercontent.com/124627333/219960261-361f9a12-adb0-46e4-aa05-1375b14bdfbb.png">

**Comment by katia9261** [comment]
According to the change request it's not a bug
https://github.com/ita-social-projects/GreenCity/issues/2541

**Comment by IrusiaVI** [comment]
Superseded #2541
