### ISSUE TITLE
[Sign in] No error message appears in case of entering a password longer than 20 characters.

### ISSUE THREAD

**Issue by SWalaszek** [ita-social-projects/GreenCity#5274]
**Environment:** Windows 10, Opera GX, 94.0.4606.107
**Reproducible:** Always
**Build found:** Commit: ff7ec6b

**Preconditions**
1. Go to https://www.pick-up.city/#/ubs

**Steps to reproduce**
1. Click on 'Sign in'
2. Enter a password longer than 20 characters e.g. 'Testpasswordlongerthan20characters'

**Actual result**
No error message

**Expected result**
An error message below 'Password' field:
ENG "Password cannot exceed 20 characters."
UA "Пароль не може містити більше 20 символів."

**User story and test case links**
User story #4100 
[Test case](https://jira.softserve.academy/browse/WR50QC-575)
[Test case](https://jira.softserve.academy/browse/WR50QC-576)

**Labels to be added**
"Bug"

![Bug2](https://user-images.githubusercontent.com/105596557/220039475-83c94eef-561a-44e5-9ad9-13a90488493e.JPG)
![Bug4](https://user-images.githubusercontent.com/105596557/220046749-9f884eff-9f78-4ae4-a884-5422de567841.JPG)

**Comment by NadiiaStoiko** [comment]
Change text and password field according to this requirements (user story https://github.com/ita-social-projects/GreenCity/issues/4099)
![photo_2023-02-27_14-28-05](https://user-images.githubusercontent.com/60553157/221564086-d2c944a8-e393-47fc-bfc3-87402f009e58.jpg)
