### ISSUE TITLE
[Events/Organizer Rating] The buttons"Join event/Share event"  are not replaced to the"Rate Organizer"  button , to the user who attended event on the Events page

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5286]
Environment:: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,
Build found: 20/02/2023
**Preconditions**
tested user should have at list one tested event attended
Go to https://www.testgreencity.ga/GreenCityClient/#/events
Sign in with a user who attended event
**Steps to reproduce**
Click on "Events "tab
Find "Event" which user attended previously.
**Actual result**
The buttons"Join event/Share event"  are not replaced to  the "Rate Organizer"  button ,the user who attended event on the Events page
**Expected result**
"Join event/Share event" buttons   are replaced with "Rate Organizer" button
<img width="752" alt="Знімок екрана 2023-02-21 о 12 49 02" src="https://user-images.githubusercontent.com/116280846/220325197-7f9b5656-220c-4722-8853-c4ce505bf8c9.png">

**User story and test case links**
E.g.: "User story #3268
(https://jira.softserve.academy/browse/GC-3940)
**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:critical"), Type ("UI, "Functional"),

**Comment by DanaIuich** [comment]
The buttons"Join event/Share event" are not replaced to the "Rate Organizer" button ,the user who attended event on the Events page

**Comment by ruslan-teh** [comment]
can not reproduce
