### ISSUE TITLE
[Pick up city UBS.Restore password] User can request a password reset when he/she doesn't verify email during registration on the Pick up city UBS 

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5297]
Environment: Windows 10 Pro v.21H2, Google Chrome 110.0.5481.104 (64-bit).
Reproducible: always.
Build found: 21/02/23

**Preconditions**
"Pick up city UBS' home page is opened.

**Steps to reproduce**
1. Click on the "Sign up" button.
2. Enter the email address in the "Email" field.
3. Enter the name in the "User name" field.
4. Enter a password in the "Password" field.
5. Repeat entering the password in the "Confirm password" field.
6. Click on the "Sign up" button.
7. Go to the email address.
8. Check the verification email.
9. Go to the "Pick up city UBS' home page.
10. Click on the "Sign in" button.
11. Enter the email address in the "Email" field.
12. Click the "Forgot password?" link.
13. Enter the same email address in the "Email" field.
14. Click on the "Submit a login link" button.
15. Go to the email address.
16. Open a Password reset email.
17. Click on the "Change password" button.
19. Enter a new password in the "Password" field.
20. Repeat entering the new password in the "Confirm password" field.
21. Click on the "Change password" button.
22. Go to the email address.

**Actual result**

User receives Restore password emails. Password has been changed .

https://user-images.githubusercontent.com/119864646/223699199-4b39568d-3967-4123-b806-2576d6fa3711.mp4

**Expected result**
User can not request a password reset when he/she doesn't verify email during registration. 

**User story and test case links**
E.g.: "User story #4103, #5282 

**Labels to be added**
"Bug", Priority ("pri: High "), Severity ("severity: Blocked"), Type ("Functional").

**Comment by AlexW8719** [comment]
Hi, could you please check if the bug is still relevant?
