### ISSUE TITLE
[Pick up city UBS.Restore password] User see incorrect username in the text of email when he/she receives Password reset email.

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5298]
Environment: Windows 10 Pro v.21H2, Google Chrome 110.0.5481.104 (64-bit).
Reproducible: always. User registered with a Google account. (test and prod)
Build found: 21/02/23

**Preconditions**
1. User is registered as user in the application with a Google account.
2. User has received a password reset email. 

**Steps to reproduce**
1. Go to the email address.
2. Open the password reset email.
3. Pay attention to the username in the text of the email.

**Actual result**
User sees a "null" username in the text of the email.

![image](https://user-images.githubusercontent.com/119864646/220463131-536c6e51-809a-4c02-970d-766235426280.png)

**Expected result**
User should see the username that was entered during registration.

**Additional information**
User see the correct username in the "Successful change password" email.

**User story and test case links**
E.g.: "User story #4103, #5282

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: Minor"), Type ("UI").

**Comment by OlegVat** [comment]
After some investigation, I can confirm that the functionality works properly on newly created accounts. I have tested this on multiple accounts and did not encounter any issues. However, older accounts may have problems because their names were incorrectly set.
