### ISSUE TITLE
[Pick up City UBS. Restore password] User receives an email about successful resetting password in English with Ukrainian localization

### ISSUE THREAD

**Issue by olyatyshchenko** [ita-social-projects/GreenCity#5299]
**Environment:** Windows 10, Google Chrome Version 110.0.5481.97 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** 22/02/2023

**Preconditions**

- User is registered at https://www.testgreencity.ga/GreenCityClient/#/ubs
- User has received a Confirm restoring password  email.
- Ukrainian localization is chosen.

**Steps to reproduce**
1. Open a Confirm restoring password email.
2. Click on the 'Змінити пароль' button.
3.  Fill in 'Пароль' and 'Змінити пароль' fields with valid data.
4. Click on the 'Змінити пароль' button.
5. Open a Restore password email.

**Actual result**
The Restore password email is displayed in English:
Restore password 
Hi /username/, Your password has been successfully changed!  
If that doesn't work, copy and paste the following link in your browser: https://www.testgreencity.ga/#
![image](https://user-images.githubusercontent.com/120178274/220479790-ddb51fd4-3acf-4797-b79c-4eb1d983b16a.png)

**Expected result**
The Restore password email is displayed in Ukrainian:
Відновлення паролю
Привіт /username/, Ваш пароль було успішно змінено!
Якщо це не працює, скопіюйте та вставте наступне посилання у свій браузер: https://www.testgreencity.ga/#

**User story and test case links**
E.g.: "User story #4104, #5272

**Comment by MaksymGolik** [comment]
This bug is no longer reproducible.
https://user-images.githubusercontent.com/99403738/236211015-d2c673ad-05db-4eb1-a4e5-c26f97ce6d01.mp4

**Comment by BohdanaYuzkiv** [comment]
Subject with UA localization should be: Відновлення паролю
![restore](https://github.com/ita-social-projects/GreenCity/assets/109086383/97c63ec4-4a85-442e-9cb6-3663db91a9aa)
