### ISSUE TITLE
[Habits view]The 'Acquire habit' button doesn't appear when habit has reached 80% of successful tracking

### ISSUE THREAD

**Issue by YakymetsHub** [ita-social-projects/GreenCity#5308]
**Environment:** Windows 11 Home, Google Chrome.
**Reproducible:** always.
**Build found:**28.02.2023

**Preconditions**

- Registered User is logged in
- User has at least one habit in progress
- It is the last day of habit’s primary duration (duration which was established by a user when he/she added a habit to track)

**Steps to reproduce**
1. Click on the habit card on My habits page.
2. Mark chosen habit as done.

**Actual result**
The 'Acquire habit' button doesn't appear when habit has reached 80% of successful tracking

**Expected result**
The 'Acquire habit' button appears when habit has reached 80% of successful tracking

**User story and test case links**
E.g.: "User story #993

https://user-images.githubusercontent.com/107051540/220955010-3aeb639d-9f07-4ade-b5ff-9839f46b214e.mp4

**Comment by atsa21** [comment]
Need to check on back-end change status on ACQUIRED for habit if progress if 80% and more
![image](https://user-images.githubusercontent.com/104850911/221156204-62e12b66-a595-49cb-a26f-a964a48e9cdc.png)
