### ISSUE TITLE
[Pickup city UBS_Order form]The error massage doesn't appear and the frame is not highlighted in red .When user enter with not valid data in field "Номер телефону"in section "Відправник інша людина" in step 2 "Personal details"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5316]
**Environment:** Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
**Reproducible:** always,

**Build found:** 21/02/2023

**Preconditions*

1. The user should be authorized
2. Go To (https://www.pick-up.city/#/ubs)
3. Sign in as authorized user
4. Click on the profile and choose the item 'UBS-user'
5. Click on button 'Нове Замовлення'
6. Fill up all necessary items on Step 1.  

**Steps to reproduce**

1. Click check box "Відправник інша людина""
2. Enter in field  "Номер телефону digits (e.g  +380 (00) 000 00 00 , +380 (11) 111 11 11 , enter  to  this field the  same  in such format  with  using digits from 0 to 9. )

**Actual result**
The error massage doesn't appear and the frame is not highlighted in red
<img width="1207" alt="Знімок екрана 2023-02-23 о 15 56 46" src="https://user-images.githubusercontent.com/116280846/220930405-73e10e0e-f192-4c6a-9309-116bca5912b9.png">

**Expected result**
The error massage does appear and the frame is highlighted in red.

**User story and test case links**
E.g.: "User story #2198 

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:major"), Type ("UI, "Functional"),

**Comment by RoksolanaKolomiyets** [comment]
The bug isn't fixed on the prod environment
<img width="1235" alt="Знімок екрана 2023-04-04 о 11 33 21" src="https://user-images.githubusercontent.com/116280846/229735611-76240e02-e8e7-465e-bcd7-2f13d5ee9896.png">

**Comment by NadiiaStoiko** [comment]
changes added to prod  environment

вт, 4 апр. 2023 г. в 11:35, RoksolanaKolomiyets ***@***.***>:

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS.Admin Cabinet.
