### ISSUE TITLE
[Habits view] Percent of habit tracking displayed in a progress bar over 100%

### ISSUE THREAD

**Issue by YakymetsHub** [ita-social-projects/GreenCity#5320]
**Environment:** 11 Home, Google Chrome.
**Reproducible:** always.
**Build found:** 23.02.2023

**Preconditions**

- Registered User is logged in
- User has at least one habit in progress
- It is the day after the last day of the habit’s primary duration 
- User hasn't marked the habit as done on the current day and the day before

**Steps to reproduce**
1. Click on the habit card on My habits page.
2. Mark chosen habit as done on the current day and the day before.

**Actual result**
Percent of habit tracking displayed in a progress bar over 100%

**Expected result**
Percent of habit tracking shouldn't be calculated and displayed in a progress bar over 100%

https://user-images.githubusercontent.com/107051540/220971221-9b8cf347-c669-4f20-a615-aea2a7fe8b36.mp4

**Postconditions**

**User story and test case links**
E.g.: "User story #993
[Test case GC-5172]https://jira.softserve.academy/browse/GC-5172"

**Comment by atsa21** [comment]
Need to change GET controller on backend
Controller - https://greencity.testgreencity.ga/habit/assign/activity/{from}/to/{to} - GET just habits with status INPROGRESS
![image](https://user-images.githubusercontent.com/104850911/222114593-63b9ee98-b5f0-4e14-a5bc-6c3671d7c013.png)

**Comment by atsa21** [comment]
Removed back end label because found way to fix in UI
