### ISSUE TITLE
[My habit] 403 Error - on GET/habit/tags/search

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5321]
**Environment:** Windows 10 Pro, Google Chrome 109.0.5414.119
**Reproducible:** always
**Build found:** 23.02.2023

**Preconditions**
Authorize in Swagger UI

**Steps to reproduce**
1. Go to https://greencity.testgreencity.ga/swagger-ui.html
2. Click on 'habit-controller'
3. Click on GET/habit/tags/search controller
![image](https://user-images.githubusercontent.com/104850911/221019957-2da0a8d9-57f2-46bd-bd3a-e7df453782d0.png)

**Actual result**
When I GET by tags: 'Reusable' I receive 403 response
![image](https://user-images.githubusercontent.com/104850911/221020464-6e6a03e8-74fc-4256-b152-21205298246f.png)

**Expected result**
Receive 200 response with habits
![image](https://user-images.githubusercontent.com/104850911/221020736-4bd8802d-f42a-4216-bf30-55ff8b739355.png)

**Comment by BranetE** [comment]
It works fine if you logged in using this credentials :
admin.greencity@starmaker.email
GreenCityAdmin-1
