### ISSUE TITLE
[Pickup city UBS_Order form]The error "Упс, щось пішло не так..." is displayed after making an order which fully covered with  certificate and the order is not formed

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5328]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71, Firefox version 109.0
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always, 

**Build found:** 25/02/2023

**Preconditions**
The user should be authorized

1. Go To (https://www.pick-up.city/#/ubs)
2. Sign in as authorized user
3. Click on the profile and choose the item 'UBS-user'
4. Click on button 'Нове Замовлення'
5. Choose the location "Київ, Київська область" or '20 кілометрів, Київ, Київська область' on the pop-up "Вітаємо в УБС! Спочатку оберіть локацію вивезення відходів. Наразі ми працюємо в Києві та передмісті." and click "Продовжити" bttn

**Steps to reproduce**

1.  Choose the number of packages for services in the block 'Послуги' and:
2.   in the block 'Якщо бажаєте скористатися сертифікатом, введіть номер сертифікату' input certificate number and click on the "Активувати" bttn
3.  Fill up the necessary information on Step 2 ( if you need it) and click on "Далі" bttn
4. Check the info on Step 3 and click 'Замовити' bttn
5. Pay attention to the failed payment and error displaying

**Actual result**
The error "Упс, щось пішло не так..." is displayed after making an order which fully covered with  certificate and the order is not formed
**Expected result**
Users can order the order fully covered with certificate  and certificate  the order is formed

**User story and test case links**
E.g.: "User story #2197
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity:Critical"), Type ("Functional"), 

https://user-images.githubusercontent.com/116280846/221362040-89c4a992-91cc-43ab-ab01-58996a23e7ac.mov

**Comment by katia9261** [comment]
The bug doesn't reproduce now

https://user-images.githubusercontent.com/101433204/221543549-1ffb3e13-aef7-4ac4-b1f3-fc664a7f27d9.mp4
