### ISSUE TITLE
[Pick-up. City Order form. Payment by card Fondy] The sum of expired certificate is subtracted from the 'Payment amount' when the user does payment by card via Fondy

### ISSUE THREAD

**Issue by sorokhteym** [ita-social-projects/GreenCity#5341]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 27.02.23

**Preconditions**
1. The user should be authorized
2. Go to https://www.pick-up.city/#/ubs
3. User should have expired certificate

**Steps to reproduce**
1. Open the page 'UBS-courier'
2. Click on bttn 'Order'
3. Set the big packages according to a minimum rule (Kyiv  - 2 big packages )
4. Scroll down and fill the number of an expired certificate
5. Press the bttn 'Асtivate'
6. Press 'Next'
7. Fill out the personal details and address on step 2 and press 'Next'
8.  Confirm your order on step 3 by pressing 'Order' 
9.  Go to the next step to do payment by card Fondy and pay attention on the Payment amount
10.  Go to ubs.admin cabinet and check the status of certificate

**Actual result**
The sum of expired certificate is subtracted from the 'Payment amount' when the user does payment by card via Fondy. The status of expired certificate changes on 'Used' after using it for creating order.

https://user-images.githubusercontent.com/116512982/221571415-57cb801d-267d-4d42-9825-22453ce5ac8f.mp4

**Expected result**
The sum of the expired certificate should not be subtracted from the Payment amount when the user does payment by card via Fondy

**User story and test case links**
https://github.com/ita-social-projects/GreenCity/issues/2481

**Comment by Phobos13bdrive** [comment]
We no longer have access to Pick-up
