### ISSUE TITLE
[Pickup city UBS_Order form] The error massage doesn't appear and the frame is not highlighted in red in the fields name and surname when user enter not valid date  in section "Personal date and "The recipient is another person " in step 2 Personal data

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5350]
**Environment:**
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always,

**Build found:**27/02/2023

**Preconditions**
The user should be authorized
1. Co To (https://www.pick-up.city/#/ubs)
2. Sign in as authorized user
3. Click on the profile and choose the item 'UBS-user'
4. Click on button ' Нове Замовлення'
5. Fill up all necessary items on Step 1

**Steps to reproduce**

1. Enter in fields  "Name" and "Surname" in section  "Personal date and "The recipient is another person 2. not valid date (e.g  Окс.ана Мель.ниченко)

**Actual result**
The error massage doesn't appear and the frame is not highlighted in red in the fields name and surname when user enter not valid date  in section "Personal date and "The recipient is another person " in step 2 Personal data
<img width="655" alt="Знімок екрана 2023-02-27 о 22 55 53" src="https://user-images.githubusercontent.com/116280846/221683978-f8ff411f-ea68-448b-8590-6d74090a6b00.png">

**Expected result**
The error massage does appear: "Only letters and hyphen, space, apostrophe are allowed"  and the frame is highlighted in red 

**User story and test case links**
E.g.: "User story #2531(https://github.com/ita-social-projects/GreenCity/issues/2531)

**Labels to be added**
"Bug", Priority ("pri: Low "), Severity ("severity:Trivial "), Type ("UI, "Functional"),

**Comment by RoksolanaKolomiyets** [comment]
The bug isn't fixed on the prod  environment
<img width="1278" alt="Знімок екрана 2023-04-04 о 11 29 28" src="https://user-images.githubusercontent.com/116280846/229734269-8d506917-5043-49af-bd8c-6bd2da4c7621.png">

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
