### ISSUE TITLE
[UBS_Prod. Admin. Order table] The 500 status code occurs when Admin tries to save changes in the order status in the Order table

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5353]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71, Firefox version 109.0
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always (**prod and test**)
**Build found:** 28/02/2023

**Preconditions**
1. Go to https://www.pick-up.city/#/ubs
2. Sign in as Super Admin
3. Click on the Admin profile and choose 'UBS-admin'

**Steps to reproduce**
1. Go to the 'Order status' column and choose the order with any (except 'Canceled' and 'Done') status and open  dev tools with the 'Network' tab
2. Click on the 'pencil' icon in order to change another order status
3. Choose any status in the drop-down list of order statuses and click on the '✔' to confirm the choice 
4. Pay attention to the error in the dev tools with the 'Network' tab

**Actual result**
The 500 status code occurs when Admin tries to save changes in the order status in the Order table

**Expected result**
Admin can change and save chosen order status in the Order table

**User story and test case links**
E.g.: "User story #[2536](https://github.com/ita-social-projects/GreenCity/issues/2536)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

https://user-images.githubusercontent.com/110603507/221927665-da5ecb2d-170a-45e3-8e69-087c5673eba5.mp4

**Comment by BranetE** [comment]
I tested it several times and it works fine
