### ISSUE TITLE
[Change request] Remove changing status of habit on ACQUIRED controller POST /habit/assign/{habitId}/enroll/{date}

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5364]
**Description of a Change request:**
 Remove changing status of habit on ACQUIRED
 controller POST /habit/assign/{habitId}/enroll/{date}
![image](https://user-images.githubusercontent.com/104850911/222143417-1d4dd266-5f11-4dfe-a15c-47d71bb71c9b.png)

**Reason for Change:**
User will send status with another controller

**Acceptance Criteria**
When user use controller POST /habit/assign/{habitId}/enroll/{date} status will remain INPROGRESS

Epic: https://github.com/ita-social-projects/GreenCity/issues/993

**Comment by LiliaMokhnatska** [comment]
Not a bug
