### ISSUE TITLE
[Edit habit] User see buttons  'Give up' and 'Save' on Acquired habits

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5366]
**Environment:** Windows 10 Pro, Google Chrome 109.0.5414.119
**Reproducible:** always
**Build found:** 01.03.2023

**Preconditions**
User is authorized
User has at least one acquired habit

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/greenCity
2. Click on 'My space'
3. Click on Acquired habit card 'pencil'

**Actual result**
User see buttons 'Give up' and 'Save' on Acquired habits
https://www.loom.com/share/bcf213c25f40439ca0ca6e25e6bd71fc

**Expected result**
User don't see buttons 'Give up' and 'Save' on Acquired habits
![image](https://user-images.githubusercontent.com/104850911/225972305-32b1b78c-1ca0-4271-8db4-c42242888de4.png)

**Comment by RudnevaOlena** [comment]
Bugs retesting for this fix is DONE.
