### ISSUE TITLE
[Admin cabinet] The employee card cannot be saved if the "Email" field is empty

### ISSUE THREAD

**Issue by ZubachV1990** [ita-social-projects/GreenCity#5379]
Environment:
Windows 10 Pro (Version 22H2) / Chrome version110.0.5481.177

Reproducible:
always,

Build found:
03/03/2023

Preconditions:
1. Site https://www.testgreencity.ga/GreenCityClient/#/ubs should be opened

2. User should be logged in as an UBS Admin

3. Employee should be created.

4. "Employees" page should be opened.

Steps to reproduce:

Click on 3 dots in the right side of employee
Click  on "Edit employee data" tab
Clear data from the "Email" field
Press the save data button
Actual result:

The error message "This field is required" appears

Expected result:

"Save" button is active and "Email" is not shown in the Employee card

**Comment by BohdanaYuzkiv** [comment]
the issue is still reproducible
![edit_employee_save_without_email](https://github.com/ita-social-projects/GreenCity/assets/109086383/50c7992e-abc6-4365-9c69-d74a62b68044)

**Comment by katia9261** [comment]
The employee email is required, so it is not a bug now.
