### ISSUE TITLE
[Admin cabinet] It is possible to save a combination of letters and numbers in the "name" and "surname" fields

### ISSUE THREAD

**Issue by ZubachV1990** [ita-social-projects/GreenCity#5381]
Environment:
Windows 10 Pro (Version 22H2) / Chrome version110.0.5481.177

Reproducible:
always,

Build found:
03/03/2023

Preconditions:
1. Site https://www.testgreencity.ga/GreenCityClient/#/ubs should be opened

2. User should be logged in as an UBS Admin

3. Employee should be created.

4. "Employees" page should be opened.

Steps to reproduce:
Click on 3 dots in the right side of employee
Click  on "Edit employee data" tab
Alternately enter a combination of letters and numbers in the "First name" and "Surname" fields (letters first)

Actual result:
The "Save" button is active and changes can be saved

Expected result:
The fields are highlighted in red and there is an error message ""Numeric characters and special characters (%$#@&*?!+=:”></) are not allowed". The save button is not active

**Comment by atsa21** [comment]
Not reproduce
Site link is https://www.testgreencity.ga/#/ubs
