### ISSUE TITLE
[Admin cabinet] Inappropriate name of the employee name field in "Edit employee data"

### ISSUE THREAD

**Issue by ZubachV1990** [ita-social-projects/GreenCity#5383]
Environment:
Windows 10 Pro (Version 22H2) / Chrome version110.0.5481.177

Reproducible:
always,

Build found:
03/03/2023

Preconditions:
1. Site https://www.testgreencity.ga/GreenCityClient/#/ubs should be opened

2. User should be logged in as an UBS Admin

3. Employee should be created.

4. "Employees" page should be opened.

Steps to reproduce:
Click on 3 dots in the right side of employee
Click  on "Edit employee data" tab

Actual result:
Field name is “Name”

Expected result:
The name of the field should be “First name”

**Comment by Olena-Kharkova** [comment]
Please fix it on PROD also

![ewDuFciwqp](https://user-images.githubusercontent.com/110603507/229280442-6c2d44ac-e8ae-4b8c-b39e-cf0064eef231.png)
