### ISSUE TITLE
[Admin cabinet] Inappropriate name of the employee's last name field in "Edit employee data"

### ISSUE THREAD

**Issue by ZubachV1990** [ita-social-projects/GreenCity#5384]
Environment:
Windows 10 Pro (Version 22H2) / Chrome version110.0.5481.177

Reproducible:
always,

Build found:
03/03/2023

Preconditions:
1. Site https://www.testgreencity.ga/GreenCityClient/#/ubs should be opened

2. User should be logged in as an UBS Admin

3. Employee should be created.

4. "Employees" page should be opened.

Steps to reproduce:

Click on 3 dots in the right side of employee
Click  on "Edit employee data" tab

Actual result:
Field name is “Surname”

Expected result:
The name of the field should be "Last name"

**Comment by Olena-Kharkova** [comment]
Please fix this issue on PROD also

![ewDuFciwqp](https://user-images.githubusercontent.com/110603507/229280558-ba73a6e7-c2a0-40e0-83ac-23d3e5a7280c.png)
