### ISSUE TITLE
[UBS.Personal cabinet] The expanded order details table isn`t displayed after clicking on arrow at the beggining of the order line.

### ISSUE THREAD

**Issue by LiliiaKhoroz** [ita-social-projects/GreenCity#5386]
Environment: Windows 10
Google Chrome 109.0.5414.75
Reproducible: always
Build found: 03/03/2023

Preconditions
1. Logged in to GreenCity as a User https://www.testgreencity.ga/#/ubs
2. The tab "Order history"  is opened.
3. The client has at least one order with 'Done' or 'Cancel' order statuses.

Steps to reproduce

1. Click on the arrow at the beginning of the order line (before the order number).
2. Pay attention to the order.

Actual result:  The expanded order details table is displayed after clicking on the order number at the beginning of the order line.

Expected result: The expanded order details table is displayed after clicking on the arrow at the beginning of the order line.
User story and test case links
User story #3477
[Test case] https://jira.softserve.academy/projects/GC/issues/GC-5311?filter=reportedbyme
![bug](https://user-images.githubusercontent.com/123656862/222696290-514e35ce-8996-4de8-b6e1-68979443dff7.png)

**Comment by Olena-Kharkova** [comment]
Duplicate 
https://github.com/ita-social-projects/GreenCity/issues/4893
