### ISSUE TITLE
[UBS.Orders]The order is displayed as 'Unpaid' in the 'Current orders' table after payment.	

### ISSUE THREAD

**Issue by LiliiaKhoroz** [ita-social-projects/GreenCity#5388]
Environment: Windows 10
Google Chrome 109.0.5414.75
Reproducible: always
Build found: 03/03/2023

Preconditions:
1. Logged in to GreenCity as a User https://www.testgreencity.ga/#/ubs
2. The tab "Orders" in the personal cabinet is opened.

Steps to reproduce:
1. Click the 'New order' button.
2. Accept your location.
3. Choose some services and click the 'Next button'.
4. Enter your personal data, choose your address and click the 'Next' button.
5. Choose the payment method 'By card via LiqPay' and click the 'Order' button.
6. Enter your card number, expiry date, CVV code and click the 'Pay' button.
7. Observe the 'Your order is paid' message.
8. Open the 'Current orders' table.
9. Pay attention to the order status.

Actual result: The order is displayed as 'Unpaid' in the 'Current orders' table after payment.
Expected result: The order is displayed as 'Paid' in the 'Current orders' table after payment.

User story #3477

![Screenshot_55](https://user-images.githubusercontent.com/123656862/222700433-e1a177f0-d3b8-4d4c-92ee-f5b2a2056ccd.png)
![Screenshot_56](https://user-images.githubusercontent.com/123656862/222700537-dc708479-2d2c-4c5b-a16c-f098aa02e0dc.png)

**Comment by MaksymGolik** [comment]
Payment system Liqpay was removed, with payment system Fondy this problem does not arise. If the problem still occurs, please detail the conditions of its occurrence. I am attaching a video of the absence of the problem.

https://user-images.githubusercontent.com/99403738/234295096-8b30cbd3-8d9e-4669-aa74-f9fae14731d6.mp4
