### ISSUE TITLE
[UBS_Prod. UBS User. Orders] The 500 status code occurs when User clicks on 'Cancel' in case of order cancellation

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5391]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71, Firefox version 109.0
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always (**prod**)
**Build found:** 03/03/2023

**Preconditions**
1. Go to https://www.pick-up.city/#/ubs
2. Sign in as a User
3. Click on the User profile and choose 'UBS-user'
4. The User has formed an order without payment

**Steps to reproduce**
1. Go to the 'Orders' tab and open 'Dev tools' on the 'Network tab'
2. Choose an order without payment in the 'Current orders' tab of the 'Your orders' table
3. Click on the 'Cancel' bttn near the order
4. On the appeared message  “У разі скасування дане замовлення буде видалено. Чи дійсно Ви бажаєте скасувати замовлення?” press “Так”
5. Pay attention to the error 500 in the Dev tools

**Actual result**
The 500 status code occurs when User clicks on 'Cancel' in case of order cancellation

**Expected result**
When the User chooses “Так” on the pop-up window the warning message “У разі скасування дане замовлення буде видалено. Чи дійсно Ви бажаєте скасувати замовлення?” in case of order cancelation, the message should be closed and the order should be deleted.

**User story and test case links**
E.g.: "User story #(https://github.com/ita-social-projects/GreenCity/issues/3488)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

https://user-images.githubusercontent.com/110603507/222738145-c8816ccf-ffe3-43d0-9068-b9478c3075f7.mp4

**Comment by MaksymGolik** [comment]
The situation could not be reproduced, if the problem is still present, please provide details, such as the error message from Response in Network
![image](https://user-images.githubusercontent.com/99403738/222751197-a1211b81-218f-4a08-8a79-40e3bd3aff7d.png)

**Comment by Olena-Kharkova** [comment]
> The situation could not be reproduced, if the problem is still present, please provide details, such as the error message from Response in Network ![image](https://user-images.githubusercontent.com/99403738/222751197-a1211b81-218f-4a08-8a79-40e3bd3aff7d.png)


Maksym, I see that you tried to reproduce the bug in the testing environment. But it's can be reproduced only on the prod space

https://user-images.githubusercontent.com/110603507/222762302-ab8a2965-7755-4a3c-b31b-6dba87b0bbe5.mp4

**Comment by MaksymGolik** [comment]
> > The situation could not be reproduced, if the problem is still present, please provide details, such as the error message from Response in Network ![image](https://user-images.githubusercontent.com/99403738/222751197-a1211b81-218f-4a08-8a79-40e3bd3aff7d.png)
> 
> Maksym, I see that you tried to reproduce the bug in the testing environment. But it's can be reproduced only on the prod space

![image](https://user-images.githubusercontent.com/99403738/222763579-18ebc913-05ba-49b2-9d00-92202a8af3b5.png)

**Comment by MaksymGolik** [comment]
> > > The situation could not be reproduced, if the problem is still present, please provide details, such as the error message from Response in Network ![image](https://user-images.githubusercontent.com/99403738/222751197-a1211b81-218f-4a08-8a79-40e3bd3aff7d.png)
> > 
> > 
> > Maksym, I see that you tried to reproduce the bug in the testing environment. But it's can be reproduced only on the prod space
> 
> ![image](https://user-images.githubusercontent.com/99403738/222763579-18ebc913-05ba-49b2-9d00-92202a8af3b5.png)

https://user-images.githubusercontent.com/99403738/222765622-203427d6-4f85-4b7b-9636-8329bcb151bb.mp4

**Comment by Olena-Kharkova** [comment]
![image](https://user-images.githubusercontent.com/110603507/222768085-c945adc4-e05b-4aa6-85b3-e0cd7a2546f0.png)
