### ISSUE TITLE
[UBS_Prod. Orders] System timeout after change of field 'Date of Export' in Orders Page

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5392]
**Environment:** Windows 11 Home 64 bit, Chrome Version 110.0.5481.97 (Official Build)
**Reproducible:** always
**Build found:** 3/3/2023"

**Preconditions**
1.Login as admin to https://www.pick-up.city/#/ubs-admin/orders
2. Goto UBS Admin, Orders

**Steps to reproduce**
1. Choose an order in the orders table
2. Goto the column 'Date of Export', (Ukr - 'Дата вивезення')
3. Click on pencil and in the calendar window try to change 'Date of Export' (Ukr - 'Дата вивезення') to any future date

**Actual result**
System timeout 

**Expected result**
The field 'Date of Export' (Ukr-'Дата вивезення') has been changed and displayed in the table 

**User story and test case links**
E.g.: "User story #3184
Video:
https://www.loom.com/share/d88d6254809845a6babaf00c299a461b

![Screenshot 2023-03-03 181009](https://user-images.githubusercontent.com/119998851/222769977-f284565c-db1c-428f-b8f4-431e71540aff.png)

**Comment by JoseCaste** [comment]
If you have a chance, please, try again. It was already fixed.
