### ISSUE TITLE
[UBS_Prod. Orders] User cant change 'time of export' from the order table

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5393]
Environment: Windows 11 Home 64 bit, Chrome Version 110.0.5481.97 (Official Build)
Reproducible: always
Build found: 3/3/2023

Preconditions
1.Login as admin to https://www.pick-up.city/#/ubs-admin/orders 
2. Goto UBS Admin, Orders Page

Steps to reproduce
1. Choose an order in the orders table
2. Goto the column 'Time of Export', (Ukr - 'Час вивезення')
3. Click on pencil and in the popup window try to change 'Time of Export' (Ukr - 'Час вивезення') 

**Actual result**
1.The dropdowns of the popup window are inactive
2.User cannot set time of export manually

**Expected result**
1.The dropdowns of the popup window are active
2.User is able to set time of export manually

**User story and test case links**
E.g.: "User story #3184
![Screenshot 2023-03-03 191324](https://user-images.githubusercontent.com/119998851/222786041-c9607188-6bc8-433e-b170-acf1f1f7ac17.png)
https://www.loom.com/share/aae3982af0cc4bb79f0b5171c6270af7

**Comment by OlegVat** [comment]
The bug probably is not from the back end since there is a function to set the export time. It might be from the front end, like a problem with the user interface or input.

**Comment by BohdanaYuzkiv** [comment]
the issue is still present


https://github.com/ita-social-projects/GreenCity/assets/109086383/81f632c6-44d9-4f27-b2e1-368b6c379b25
