### ISSUE TITLE
[Change request to #3373] <Manage event location>

### ISSUE THREAD

**Issue by DimaKarma** [ita-social-projects/GreenCity#5394]
**Description of a Change request:**
Story is not actual more

**Reason for Change:**
Due to the updated requirements an User ability to chose events addresses on the Google map is refused. Furthermore, a map ability was described in the US #3193 and deleted in the change request #5123

**Acceptance Criteria**

**Impact of Change**
#3373  #3193 

Epic: #3194

**Comment by nina279** [comment]
Not relevant
