### ISSUE TITLE
[Pick up city UBS.UBS Admin Cabinet] Admin sees empty fields 'Ім’я відправника', 'Телефон відправника' and 'Email відправника' in the orders table on the Order tab when user hasn’t chosen option “Відправник інша людина” in the order form in the user's cabinet

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5412]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 110.0.5481.178 (64-bit).
**Reproducible:** always.(test and prod)
**Build found:** 06/03/23

**Preconditions**
1. User is logged in as administrator.
2. Orders tab is opened.
3. At least 1 order in which user hasn’t chosen option 'Відправник інша людина' is in the orders table.

**Steps to reproduce**
1. Click on the particular order.
2. Click on 'Інформація про клієнта'.
3. Pay attention to Client information “Клієнт” and Sender information 'Відправник'.
4. Click on the button 'Back'.
5. Pay attention  to the fields 'Ім’я відправника', 'Телефон відправника' and 'Email відправника' in this order.

**Actual result**

Admin sees empty fields 'Ім’я відправника', 'Телефон відправника' and 'Email відправника' in the orders table.
![Снимок экрана 2023-03-05 202943](https://user-images.githubusercontent.com/119864646/223245608-2e7b35c1-f5ac-4725-b871-fda913e622b6.png)
![image](https://user-images.githubusercontent.com/119864646/223257924-50face43-dd3b-488d-a824-9f16335f8ebf.png)

**Expected result**
'Ім'я клієнта' should be shown in the 'Ім’я відправника' field, 'Телефон клієнта' should be shown in the 'Телефон відправника' field and 'Email клієнта' should be shown in the 'Email відправника' field in the orders table if user hasn’t chosen option 'Відправник інша людина' in the order form.

**User story and test case links**
E.g.: "User story #2536, #3184

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("Minor:"), Type ("UI").

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS.Admin Cabinet.
