### ISSUE TITLE
[UBS_Prod. Orders] Wrong sum in the field 'Amount due' of the table orders

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5431]
Environment: Windows 11 Home 64 bit, Chrome Version 110.0.5481.97 (Official Build)
Reproducible: always
Build found: 3/5/2023

Preconditions
1. Log in as admin to https://www.pick-up.city/#/ubs-admin/orders
2. Goto UBS Admin, Orders Page
3. At least one order is present in the system

Steps to reproduce
1. Goto order and check the amount due
2. Check the column 'Amount due' if the same sum is displayed

**Actual result**
1. The sum in the column 'Amount due' (Сума до оплати) of the table is not equal to the amount to be paid in the order 

**Expected result**
1. The sum in column 'Amount due' (Сума до оплати) of the table should be equal to that one in the order

E.g.: "User story #3184
[Test case](https://jira.softserve.academy/browse/3184)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![Screenshot 2023-03-08 125318](https://user-images.githubusercontent.com/119998851/223694942-87c1b48e-ba03-4b7b-a124-6879b66701cb.png)
![Screenshot 2023-03-08 125447](https://user-images.githubusercontent.com/119998851/223694957-0029a5a1-33ab-42a4-9057-7602aeeeb4cc.png)

**Comment by MaksymGolik** [comment]
Has it been fixed at https://www.testgreencity.ga/#/ubs. There will soon be a merge at pick-up.city

**Comment by MaksymGolik** [comment]
Merged into prod.
