### ISSUE TITLE
[Pickup city UBS _Order details. Admin cabinet] The error massage doesn't appear When super admin download Invalid file format the image if file is other than PNG or JPG format and size more then 10MБ” .on pop-up window “Додати порушення” In block "Інформація про клієнта"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5434]
**Environment:** OS, browser, it's version, device (for mobile devices).
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible: **always,( Prod and Test )

**Build found:**08/03/2023

**Preconditions**
User is logged in as administrator.
Go to (https://www.pick-up.city/#/ubs-admin/orders)
An administrator navigates to the Orders tab.
An administrator has opened an order from current orders view table

**Steps to reproduce**
Click on any number in the column Номер замовлення"
Click on the text "Інформація про клієнта
Click on button “Додати порушення”
download the image Invalid for example file format TIFF on the photo matrix and download the image size more then 10MБ”
**Actual result**
The error massage doesn't appear When super admin download Invalid file format the image if file is other than PNG or JPG format and size more then 10MБ” .on pop-up window “Додати порушення” In block "Інформація про клієнта"
**Expected result**
The error massage does appear When super admin download Invalid file format the image if file is other than PNG or JPG format and size more then 10MБ” .

![image](https://user-images.githubusercontent.com/116280846/223714951-bc14a29a-0d9d-4415-9781-df0bee852f98.png)

**User story and test case links**
E.g.: "User story #2861 
(https://jira.softserve.academy/browse/GC-4726)**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: major"), Type ("UI, "Functional")

**Comment by KKatiaa** [comment]
I have verified that everything is working correctly.
