### ISSUE TITLE
[Pickup city UBS _Order details. Admin cabinet] When super admin editing, the frames "Ім'я", "Прізвище","Телефон ","Email "  changes color in block "Відправник"  in section  "Інформація про клієнта"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5440]
Environment: OS, browser, it's version, device (for mobile devices).
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible: **always,( Prod and Test )

**Build found:**09/03/2023

**Preconditions**

1. User is logged in as administrator.
2. Go to (https://www.pick-up.city/#/ubs-admin/orders)
3. An administrator navigates to the Orders tab.
4. An administrator has opened an order from current orders view table

**Steps to reproduce**
Click on number in the column "Номер замовлення"
Click on the text "Інформація про клієнта
Enter in fields."Ім'я", "Прізвище","Телефон ,"Email " a valid date  in section Sender information "Відправник"
**Actual result**
The frames "Ім'я", "Прізвище","Телефон "Email " changes color when super admin editing
<img width="1049" alt="Знімок екрана 2023-03-09 о 12 24 25" src="https://user-images.githubusercontent.com/116280846/223996174-2746eda8-da31-4ea2-9dab-5b74eed5e6ec.png">

**Expected result**
The frame  "Email "doesn't change color when super admin editing
<img width="878" alt="Знімок екрана 2023-03-09 о 12 27 35" src="https://user-images.githubusercontent.com/116280846/223996865-a673e9bb-3d4a-482d-818d-430d445c5283.png">

**User story and test case links**
E.g.: "User story #2787 

**Labels to be added**
"Bug", Priority ("pri:Low "), Severity ("severity:minor "), Type ("UI, "Functional")

**Comment by mdashko** [comment]
this bug is already fixed

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
