### ISSUE TITLE
[UBS_Prod. Orders] Administrator's comment arent displayed in the table

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5441]
Environment: Windows 11 Home 64 bit, Chrome Version 110.0.5481.97 (Official Build)
Reproducible: always
Build found: 3/8/2023

**Preconditions**
1.Log in as admin to https://www.pick-up.city/#/ubs-admin/orders
2.Goto UBS Admin, Orders Page
3.At least one order is present in the system

**Steps to reproduce**
1. Goto order and check if there is an administrator's comment, if not - add any comment
2. Click in 'Save' button.
3. Check the Orders table whether the comment is displayed in column 'Administrator comment'.

**Actual result**
The comment is not displayed in the orders table column 'Admninstator comment'.
**Expected result**
The comment should be displayed in the orders table column 'Admninstator comment'.

**User story and test case links**
E.g.: "User story #3184
[Test case](https://jira.softserve.academy/browse/GC-5714)"
![Screenshot 2023-03-09 120145](https://user-images.githubusercontent.com/119998851/223987887-ecc9ccbe-c16e-4b36-bcac-45e9b3a36454.png)
![Screenshot 2023-03-09 120106](https://user-images.githubusercontent.com/119998851/223987906-962e04dd-a6cd-4db1-80c4-b603c76134bc.png)

**Comment by MaksymGolik** [comment]
Has it been fixed at https://www.testgreencity.ga/#/ubs. There will soon be a merge at pick-up.city

**Comment by MaksymGolik** [comment]
Merged into prod.
