### ISSUE TITLE
[UBS.Order Form.API] Incorrect API response status code for unauthorized user

### ISSUE THREAD

**Issue by patselyuk** [ita-social-projects/GreenCity#5448]
**Environment:** macOS 12.6.2 (21G320), browser Chrome 110.0.5481.177 (Official Build).
**Reproducible:** always
**Build found:** 10.03.2023

**Preconditions**
1. Postman is opened.
2. Without token to authorize in Postman .

**Steps to reproduce**
1. Choose POST method
2. Set up 'https://greencity-ubs.testgreencity.ga/ubs/processLiqPayOrder/'
3. Set up body '{"additionalOrders":null,"addressId":4,"bags":[{"amount":"2","id":1}],"certificates":[],"orderComment":"","personalData":{"email":"catherina.pat@gmail.com","firstName":"kkkkkk","id":11,"lastName":"pppp","phoneNumber":"+380635956512","senderFirstName":null,"senderLastName":null,"senderEmail":null,"senderPhoneNumber":null,"addressComment":null,"ubsUserId":8,"city":"Київ","cityEn":"Kyiv","district":"Голосіївський район","districtEn":"Holosiivs'kyi district","region":"місто Київ","regionEn":"Kyiv","street":"Стратегічне шосе","streetEn":"Stratehichne Highway","houseNumber":"1","houseCorpus":null,"entranceNumber":null,"latitude":50.4005722,"longitude":30.5246249},"pointsToUse":0,"shouldBePaid":true,"locationId":1}'

**Actual result**
Status code 500 Internal Server Error

**Expected result**
Status code 401 Unauthorized

**User story and test case links**
E.g.: "User story #2200 
[Test case](https://jira.softserve.academy/browse/GC-5775)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by DenuwanLiyanage** [comment]
Hi,
If nobody looking into this issue I can work on this. Please assign me.
