### ISSUE TITLE
[API] 500 Response after adding double slash in link

### ISSUE THREAD

**Issue by Yegor-Klimenko** [ita-social-projects/GreenCity#5456]
Environment: Postman
Reproducible: always

**Preconditions**
Postman is installed on PC.

**Steps to reproduce**
1. Go to Postman
2. Click on Add a request
3. Select GET request.
4. Fill in a link with double slash: greencity-ubs.testgreencity.ga/admin/ubs-employee//getAll-active-employees
5. Send request.

**Actual result**
Status code 500 Internal Server Error

<html><body><h2>Error Page</h2><div>Status code: <b>500</b></div><div>Exception Message: <b>The request was rejected because the URL was not normalized.</b></div><body></html>.

**Expected result**
Status code 200 OK.

**Comment by OlegVat** [comment]
There should not be duplication in the URL to send a request (use the proper URL):
greencity-ubs.testgreencity.ga/admin/ubs-employee/getAll-active-employees

Check this article: https://en.wikipedia.org/wiki/URI_normalization
