### ISSUE TITLE
[Pick up city UBS.UBS Admin Cabinet] Wrong presentation of bags amount in the ‘Orders’ table when admin has changed the Confirmed amount to ‘0’ in the ‘Order details’ section 

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5458]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 111.0.5563.65 (64-bit).
**Reproducible:** always.
**Build found:** 13/03/23

**Preconditions**

1.	User is logged in as administrator.
2.	Orders tab is opened.
3.	At least 1 order is in the orders table.

**Steps to reproduce**

1. Pay attention to the string with the number of packages ‘0’ in the column ‘Bags amount’. 
2. Click on the particular order
e.g. Bags amount: 20L - 0p; 60L - 0p; 120L - 2p.
3. Click on the ‘Order details’.
5. Pay attention to the Planned amount and Confirmed amount.

**Actual result**

Admin sees the number of packages ‘0’ in the string when Planned amount does not match  Confirmed amount.
![Снимок экрана 2023-03-13 005905](https://user-images.githubusercontent.com/119864646/224648059-27624f58-0566-49f9-8887-e8586026ea54.png)
![image](https://user-images.githubusercontent.com/119864646/224649894-9abdea28-ef99-4300-a605-1925eccb2cb9.png)

**Expected result**

Only ordered packages should be shown in the ‘Bags amount’ column in the ‘Orders’ table.
![Снимок экрана 2023-03-13 005959](https://user-images.githubusercontent.com/119864646/224648193-e889cd95-b10d-428e-ac08-43be3aaf2d1e.png)

**Addition information**

Admin sees the wrong presentation of bags amount when Planned amount and Confirmed amount  does not match Actual amount.
![Снимок экрана 2023-03-13 005827](https://user-images.githubusercontent.com/119864646/224648224-c2ca63fe-b144-4279-9d25-10e026ba49e6.png)
![image](https://user-images.githubusercontent.com/119864646/224649451-f9bdade0-f1f2-4db4-86b3-99a047315c06.png)

**User story and test case links**
User story #3184
[Test case](https://jira.softserve.academy/browse/GC-2165)

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity:  Minor"), Type ("UI").

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS.Admin Cabinet.
