### ISSUE TITLE
[API.UBS.Save address] The 500 status code is displayed when unauthorized user save the address.

### ISSUE THREAD

**Issue by LiliiaKhoroz** [ita-social-projects/GreenCity#5460]
Environment:
Windows 10 Pro 21H2
Google Chrome 109.0.5414.75

Reproducible: always
Build found: 13/03/2023

Preconditions:
1. The Postman is opened.
2. The token isn`t added.

Steps to reproduce
1. Apply the POST method by using request url https://greencity-ubs.testgreencity.ga/ubs/findAll-order-address
2. Fill in the request ''Body'' 
{
"addressComment": "string",
"district": "string",
"districtEn": "string",
"entranceNumber": "string",
"houseCorpus": "string",
"houseNumber": "string",
"region": "string",
"regionEn": "string",
"searchAddress": "string"
}

3.Click 'Send' button to send request
4. Observe the 500 status code.

Actual result
 The system returns the 500 status code if the unauthorized User saves order addresses.
Expected result
 The system returns the 401 status code if the unauthorized User saves order addresses.

User story and test case links
E.g.: "User story #2199 
[Test case] https://jira.softserve.academy/browse/GC-5642
![postman](https://user-images.githubusercontent.com/123656862/224667413-f541364b-c1d4-420f-ac36-5993576ddf67.png)

**Comment by ghost** [comment]
![image](https://github.com/ita-social-projects/GreenCity/assets/130749567/cdebfb04-4c7f-445b-b67a-16b02f7bf0b9)
Actual result
The system returns the 405 status code if the unauthorized User saves order addresses. (Method is not allowed)
