### ISSUE TITLE
[All Habits] On click filter by user don't see all habits with selected tag category

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5462]
**Environment:** Windows 10 Pro, Google Chrome 111.0.5563.65
**Reproducible:** always
**Build found:** 07.03.2023

**Preconditions**
User is authorized

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/greenCity
2. Click on 'My space'
3. Click on 'Add new habit'
4. Click on Filter by - 'Reusable'

**Actual result**
User see just first 2 habit with 'Reusable' tag
![image](https://user-images.githubusercontent.com/104850911/224679833-4e45fa72-0d62-47ae-8299-662cf35b37c3.png)

**Expected result**
User see all habits with 'Reusable' tag

**Comment by RudnevaOlena** [comment]
This bug is fixed.
