### ISSUE TITLE
[API. Employee]  When the administrator creates a new employee position, response 200 is not reproduced

### ISSUE THREAD

**Issue by ZubachV1990** [ita-social-projects/GreenCity#5465]
**Environment**:
Windows 10 Pro (22H2)/Google Chrome Версія 110.0.5481.180

**Reproducible**:
always,

**Build found:**
12/03/2023

 **Steps to reproduse:**
1. Choose method POST
2. Set up https://greencity-ubs.testgreencity.ga/admin/ubs-employee/create-position ( Authorized by bearer token )
3. Set up name parameter 'any data'
4. Send request

**Actual result**
Response 201. Created

**Expected result** 
Respone 200.OK

**Test case link:**
https://jira.softserve.academy/browse/GC-5635

**Comment by ABbondar** [comment]
temporary we deleted this endpoint from our project, so i'll close this task
