### ISSUE TITLE
[API] Admin can update/save employee information with empty required fields

### ISSUE THREAD

**Issue by Yegor-Klimenko** [ita-social-projects/GreenCity#5469]
**Environment:** Postman
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Postman is installed.

**Steps to reproduce**
1. Open Postman.
2. Choose method PUT.
3. Set up endpoint: https://greencity-ubs.testgreencity.ga/admin/ubs-employee/update-employee 
4. Set up parameter (firstName/lastName/phoneNumber/email/id/employeePositions/tariffs) 
5. Enter invalid information in one of the fields (leave the "LastName" field empty).
6. Send request.

**Actual result**
Admin could save request with empty required (*) fields. Status 200

**Expected result**
Recording to the requirements Admin can't save Employee without all  required (*) fields. Response 400 Bad Request. 

**User story and test case links**
Edit employee permissions #4617
[Test case](https://jira.softserve.academy/browse/GC-5722)"

**Labels to be added**
"Bug", "severity:high ", "Functional", "API"

![BUG API](https://user-images.githubusercontent.com/49099832/225015619-40915572-4727-472d-9f3a-ef088aa3228e.png)

**Comment by ABbondar** [comment]
retest, please
