### ISSUE TITLE
News display: issue with tags

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#547]
When tags are displayed in two lines, the distance between them should be 8 px. 
_No screenshot available, since could not find a content example with all tags selected._

**Comment by rsyvulko** [comment]
Defect is fixed for unselected tags, but for selected tags no.
Distance between two selected tags is 0 px.

Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
![selected unselected tags](https://user-images.githubusercontent.com/64583544/82617495-eaa2cb00-9bd8-11ea-8490-0d379c693780.png)
