### ISSUE TITLE
[API] Admin can create employee with invalid phone number

### ISSUE THREAD

**Issue by Yegor-Klimenko** [ita-social-projects/GreenCity#5471]
**Environment:** Postman
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Postman is installed.

**Steps to reproduce**
1. Open Postman.
2. Choose method POST.
3. Set up endpoint: https://greencity-ubs.greencity.social/admin/ubs-employee/save-employee
4. Set up parameter (firstName/lastName/phoneNumber/email/id/employeePositions/tariffs) 
5. Set up parameter Authorizetion.
6. Enter invalid information in phone number field (+380222).
7. Send request.

**Actual result**
Admin could create and save employee with invalid phone number less than 7 digits. Status 201.

**Expected result**
Recording to the requirements Admin can't create and save employee with invalid phone number less than 7 digits. Response 400 Bad Request. 

**User story and test case links**
Edit employee data #4616

**Labels to be added**
"Bug", "severity:high ", "Functional", "API"

![BUG API](https://user-images.githubusercontent.com/49099832/225033001-8746dfed-e826-4845-af82-bc847fcff721.png)

**Comment by ABbondar** [comment]
fixed, retest please
