### ISSUE TITLE
[API] Admin can create employee with empty required fields

### ISSUE THREAD

**Issue by Yegor-Klimenko** [ita-social-projects/GreenCity#5472]
**Environment:** Postman
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Postman is installed.

**Steps to reproduce**
1. Open Postman.
2. Choose method POST.
3. Set up endpoint: https://greencity-ubs.testgreencity.ga/admin/ubs-employee/save-employee
4. Set up parameter (firstName/lastName/phoneNumber/email/id/employeePositions/tariffs) 
5. Set up parameter Authorizetion.
6. Leave the "LastName" field empty.
7. Send request.

**Actual result**
Admin could create emloyee with empty required (*) fields. Status 201

**Expected result**
Recording to the requirements Admin can't create Employee without all required (*) fields. Response 400 Bad Request. 

**User story and test case links**
Edit employee permissions #4617
[Test case](https://jira.softserve.academy/browse/GC-5722)"

**Labels to be added**
"Bug", "severity:high ", "Functional", "API"

![BUG API](https://user-images.githubusercontent.com/49099832/225035064-0bc15e07-484b-4c8f-ac51-e2e5ff09ddd9.png)

**Comment by Phobos13bdrive** [comment]
500 Internal Server Error
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/5a0dfbb7-f23a-45ce-8f57-95fd544f7ea0)

**Comment by ospodaryk** [comment]
The response is correct. If the data is empty, the result provided is accurate.
<img width="942" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/82940222/71ca174a-52e3-4cb1-a6ea-2d698508a4fa">
