### ISSUE TITLE
News page: gallery view display issue

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#549]
Content items in the Gallery view should be aligned horizontally only in the first row, the next rows should have random horizontal alignment depending on the container height. 
Expected:
![Screenshot_98](https://user-images.githubusercontent.com/60645819/78551568-9bfac680-780e-11ea-8f53-a42a3a2119e0.png)
Not expected:
<img width="507" alt="Screenshot_99" src="https://user-images.githubusercontent.com/60645819/78551585-a2893e00-780e-11ea-8174-01d986e4cd87.png">

**Comment by KimAT25** [comment]
not relevant according change request to new mockup
