### ISSUE TITLE
[Pick up city UBS.UBS Admin Cabinet]  Admin sees sorting of packages of each size in ascending order on one line in Orders table

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5492]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 111.0.5563.65 (64-bit).
**Reproducible:** always.
**Build found:** 19/03/23

**Preconditions**

1.	User is logged in as administrator.
2.	Orders tab is opened.
3.	At least 1 order is in the orders table.

**Steps to reproduce**

1. Pay attention to the order of sorting of packages of each size ’ in the column ‘Bags amount’. 
e.g. order 1157

**Actual result**

Packages of each size are sorted in ascending order on one line.
20л - 1шт; 60л - 1шт; 120л - 2шт
![image](https://user-images.githubusercontent.com/119864646/226166950-babb4984-9426-47a1-a360-29cb03af70db.png)

**Expected result**

Packages of each size should be sorted in descending order on one line.
120л - 2шт; 60л - 1шт; 20л - 1шт

**User story test case links**
User story #3184
[Test case](https://jira.softserve.academy/browse/GC-2165)"

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity:  Minor"), Type ("UI").

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS.Admin Cabinet.
