### ISSUE TITLE
[Pick up city UBS.UBS Admin Cabinet] Admin sees  wrong title of the Sender section in En localization in the 'Information about client' section of the order form

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5494]
**Environment**: Windows 10 Pro v.21H2, Google Chrome 111.0.5563.65 (64-bit).
**Reproducible**: always.
**Build found**: 19/03/23

**Preconditions**

User is logged in as administrator.
Orders tab is opened.
At least 1 order is in the orders table.

**Steps to reproduce**

1. Choose En localization.
2. Click on any order.
3. Click on the 'Information about client' menu.
4. Pay attention to the title of the Sender section.

**Actual result**
Admin sees Recipient title of the Sender section in En localization.
![image](https://user-images.githubusercontent.com/119864646/226172443-0942f993-774b-4dbd-8086-309a2d5ec8d6.png)

**Expected result**
Admin should see Sender title of the Sender section in En localization.

**Addition information** :
'Recipient'isn't changed to 'sender' in step 2 when user creates a new order.
![image](https://user-images.githubusercontent.com/119864646/226205260-ddbbd851-03fa-4ee9-9c0b-b8dd150960ab.png)

**User story and test case links**
User story #3184

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("Minor:"), Type ("UI").

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS.Admin Cabinet.
