### ISSUE TITLE
[Pick up city UBS.UBS Admin Cabinet] Sender email isn't updated in the 'Email' field on the order form when admin edits Sender email for orders with chosen option 'The sender is another person'

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5499]
**Environment**: Windows 10 Pro v.21H2, Google Chrome 111.0.5563.65 (64-bit).
**Reproducible**: always.
**Build found**: 19/03/23

**Preconditions**

User is logged in as administrator.
The orders tab is opened.
At least 1 order is in the orders table. User chooses the 'The sender is another person' option.

**Steps to reproduce**
1. Click on the particular order.
2. Click on the 'Information about client' menu.
3. Clear 'Sender Email' field.
4. Click on the 'Save' button.
5. Pay attention to  Sender email.

**Actual result**
Sender email isn't updated in the 'Email' field when admin edits Sender email for orders with chosen option 'The sender is another person'

https://user-images.githubusercontent.com/119864646/226203547-14c607ef-b7ca-439c-9621-83c3b6a22ab4.mp4

**Expected result**

Sender email should be updated in the 'Email' field when admin edits Sender email for orders with chosen option 'The sender is another person'

**User story and test case links**
User story #2787

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: Minor"), Type ("Functional").

**Comment by MaksymGolik** [comment]
This bug is no longer reproducible
https://user-images.githubusercontent.com/99403738/235916378-29ce749b-5ed3-4369-bf0f-17537681ce75.mp4

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
