### ISSUE TITLE
News display: alinment

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#550]
Tags and Create News should be aligned, as well as Number of items found and gallery/list view
<img width="413" alt="Screenshot_101" src="https://user-images.githubusercontent.com/60645819/78555081-f26b0380-7814-11ea-8b65-ac4ac7562f78.png">

**Comment by rsyvulko** [comment]
'Create news' button's allignment is fixed.

'Gallery/list' icons' alignment is not fixed.
Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
![signs alignment](https://user-images.githubusercontent.com/64583544/82618368-92b99380-9bdb-11ea-9896-5273da995b32.png)

**Comment by rsyvulko** [comment]
'Gallery/list' icons' alignment is not fixed.
Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
![Eco news calc alignment](https://user-images.githubusercontent.com/64583544/84146552-8733ec80-aa64-11ea-90d2-1c8112f24cfc.png)

**Comment by KimAT25** [comment]
![123](https://user-images.githubusercontent.com/56609118/84173680-4b118380-aa86-11ea-84fc-e970366890ed.JPG)

I checked all, and everything works fine. About using Mozila, we have to discuss it with all prject members, as it was not a task.
