### ISSUE TITLE
[Pick up city UBS.UBS Admin Cabinet] Email in the 'Sender email' column in orders table isn't changed when admin edits Sender email in the ' Information about client' section of order form

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5500]
**Environment**: Windows 10 Pro v.21H2, Google Chrome 111.0.5563.65 (64-bit).
**Reproducible**: always.
**Build found**: 19/03/23

**Preconditions**

User is logged in as administrator.
The orders tab is opened.
At least 1 order is in the orders table. 

**Steps to reproduce**
1. Click on the particular order.
2. Click on the 'Information about client' menu.
3. Change the sender email in the 'Email' field.
 midmia1@ukr.net
5. Click on the 'Save' button.
6. Click on the 'Back" button.
7. Pay attention to the email in the 'Sender email' column.
8. Pay attention to the email in the 'Client email' column.

**Actual result**

Sender email is changed in the 'Client email' column.

https://user-images.githubusercontent.com/119864646/226208170-72aed0fa-818e-4f89-a7e5-cbb908b88b25.mp4

**Expected result**

Sender email is changed in the 'Sender email' column in the orders table.

**Addition information**
The same behavior of the system for the Sender name and Sender phone.

**User story and test case links**
User story #2787 

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: Minor"), Type ("Functional").

**Comment by BohdanaYuzkiv** [comment]
the issue is still present, same result as on previous video
