### ISSUE TITLE
[Pickup city UBS Admin cabinet]  The message "Underpayment" doesn't appear in section "Оплата замовлення" when super admin editing date in section "Деталі замовлення" and click button "Зберегти"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5508]
Environment: OS, browser, it's version, device (for mobile devices).
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible: **always,( Prod and Test )

**Build found:**20/03/2023

**Preconditions**

- User is logged in as administrator.
- Go to (https://www.pick-up.city/#/ubs-admin/orders)
- An administrator navigates to the Orders tab.
- An administrator has opened an order from current orders view table

**Steps to reproduce**

1. Click on number in the column Номер замовлення" which have statuses "Сформовано""
2. Changes statues "Сформовано" to "Узгодження""
3. Fill in sections  "Деталі вивезення" and "Відповідальні особи"
4. Click on section "Деталі замовлення"and editing date increase the number in the column "Підтверджена к-ть"
5. Click button ""Зберегти"

**Actual result**
The message "Underpayment" doesn't appear in section "Оплата замовлення" when super admin changes  date in section "Деталі замовлення" and click button "Зберегти"

https://user-images.githubusercontent.com/116280846/226473498-daa7f2dc-38c6-4e44-8393-ff9d356d8f6b.mov

**Expected result**
The message "Underpayment" does appear in section "Оплата замовлення" when super admin changes  date in section "Деталі замовлення" and click button "Зберегти"

**User story and test case links**
E.g.: "User story #2899 

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:major"), Type ("UI, "Functional"),

**Comment by KKatiaa** [comment]
it is already done

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
