### ISSUE TITLE
[Admin Cabinet. Orders tab. Orders payment] HTTP (POST) sends incorrect request

### ISSUE THREAD

**Issue by DavidPolishchuk** [ita-social-projects/GreenCity#5509]
**Environment:** Windows 10. Google Chrome Version 109.0.5414.120
**Reproducible:** always
**Build found:** 21.03.2023

**Preconditions**
1.The User is logged into GreenCity as an admin.
2.The 'Замовлення' tab is opened in the admin cabinet.
3.Administrator has opened an separate order from current orders view table.

**Steps to reproduce**

1.Click on the orders and the expanded view of the orders appears.
2.Click on the order number and open order.
3.Find 'Оплата заказа' link and click on it.
4.Open "DevTools" and clear logs.
5.Fill in all fields required for payment.
6.Use button "+Додати оплату".
7.Chek in "DevTools" log with (POST) and open (Payload).

**Actual result**
We have payment with a couple of zeros after real price   _**(like: "amount":200000")**_

https://user-images.githubusercontent.com/116380555/226484091-af08abfc-f2d9-4d0e-a8b6-5b537ac22a26.mp4

**Expected result**
We have payment with a real price **_(like: "amount":2000")_**

**User story and test case links**
User story  #2996

**Comment by MaksymGolik** [comment]
Not a bug, two extra zeros indicate pennies, that is, for 2000.00 hryvnia is sent the value 20000 pennies
