### ISSUE TITLE
[Pick up City. Admin cabinet. Orders] The phone number is displayed without  '+' sign in the 'Phone number' column after its editing

### ISSUE THREAD

**Issue by olyatyshchenko** [ita-social-projects/GreenCity#5518]
**Environment:** Windows 10, Google Chrome Version 111.0.5563.65 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** 21/03/2023.

**Preconditions**
Log in as Admin https://www.pick-up.city/#/ubs-admin/orders
Go to the Orders tab.
The order from the current orders view table should be opened.

**Steps to reproduce**
1. Edit the 'Phone number' field.
2. Click on the 'Save' button.
3. Back to the current orders view table.
4. Pay attention to the 'Phone number' column of edited order.

**Actual result**
The '+' sign is missed in the phone number.

https://user-images.githubusercontent.com/120178274/226741774-9ef00fdd-2cf1-4706-baeb-79ee4c9e2317.mp4

**Expected result**
9 digits starting with:+380 Received from order form.

**User story and test case links**
E.g.: "User story #3184, #2536

**Comment by MaksymGolik** [comment]
UI bug, because the phone number value is sent without a "+", at the same moment, when creating an order, the phone number is sent with a "+"
![image](https://user-images.githubusercontent.com/99403738/236208201-528be7e0-6684-4f54-b36f-418f52b24c7c.png)

**Comment by Phobos13bdrive** [comment]
This bug reproduce again

**Comment by Maxv1z** [comment]
Cannot reproduce

https://github.com/ita-social-projects/GreenCity/assets/122612827/c35e38fb-0a4e-4eeb-b3b9-3a22058a7bc5
