### ISSUE TITLE
News display: gallery view change request to #459 #538

### ISSUE THREAD

**Issue by ViraPryshlyak** [ita-social-projects/GreenCity#552]
![538](https://user-images.githubusercontent.com/63067658/78602740-9e394100-785f-11ea-9407-0c022da30082.png)
****

**Actual result:**
1.Author goes 1st
2.Date goes after the Author
3,Share button is not deleted

**Expected result:**
1.Date goes 1st
2.Author goes after the Date
3,Share button is deleted

**Comment by KimAT25** [comment]
This bug was fixed in change request #459
