### ISSUE TITLE
[Change request to #2865,#2866,#3706,#4977,#2898,#2899,#2900, #2901,#3707,#5420,#5417#3492 ] Clarification Order validation and Order details

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5520]
**Description of a Change request:**
the clarification for the order validation with overpayment/underpayment cases 

 **Reason for Change:**
Improvements after the PO review

**Preconditions**

1. The user is logged in as an administrator.
2. The administrator navigates to the Orders tab.
3. The administrator has opened an order from the current orders view table
4. Section “Деталі замовлення” should contain a table with the following field and their attributes.
5. The column Actual amount should be displayed only on order stages  Не вивезли; Виконано; 
6. The sequence of displaying should be according to the sequence of the table

**Acceptance Criteria**

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-389f68dc-7fff-cf58-3da2-f134702a2342"><ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:decimal;font-size:10.5pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.542857142857143;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;padding:-9pt 0pt 0pt 0pt;" role="presentation"></p></li></ol><div dir="ltr" style="margin-left:0pt;" align="left">

“Послуга”Service name | “Об’єм” Package size | “Вартість за одиницю” Price per package | “Планована к-сть” Planned amount | “Підтверджена к-сть” Confirmed amount | “Вивезена к-ть” Actual amount
-- | -- | -- | -- | -- | --
“Мікс відходів”. Text. Disabled. | “120 л” Text. Disabled. | “280.00 грн” Text. Disabled. | Planned quantity of packages. Values from 0-999 only. Received from the order form. Disabled | Confirmed quantity of packages. Values from 0-999 only. Received from the order form. Enabled on the stages: Сформовано; Узгодження; Підтверджено; Не вивезли | Actual quantity of packages. Values from 0-999 only. “0” on stage “Скасованo”.On other stages - received from the previous related field. Enabled on the stages: Не вивезли; Виконано; 
“Текстильні відходи”. Text. Disabled. | “60 л” Text. Disabled. | “220.00 грн” Text. Disabled. | Planned quantity of packages. Values from 0-999 only. Received from the order form. Disabled | Confirmed quantity of packages. Values from 0-999 only. Received from the order form. Enabled on the stages: Сформовано; Узгодження; Підтверджено; Не вивезли | Actual quantity of packages. Values from 0-999 only. “0” on stage “Скасованo”.On other stages - received from the previous related field. Enabled on the stages: Не вивезли; Виконано; 
“Текстильні відходи”. Text. Disabled. | “20 л” Text. Disabled. | “110.00 грн” Text. Disabled. | Planned quantity of packages. Values from 0-999 only. Received from the order form. Disabled | Confirmed quantity of packages. Values from 0-999 only. Received from the order form. Enabled on the stages: Сформовано; Узгодження; Підтверджено; Не вивезли | Actual quantity  of packages. Values from 0-999 only. “0” on stage “Скасованo”.On other stages - received from the previous related field. Enabled on the stages: Не вивезли; Виконано; 
“Загальна к-сть пакетів” Text. Disabled. |   |   | Values from 0-999 only.Calculated by the formula:  Total quantity of packages = planned quantity of packages “Мікс відходів” 120L + planned quantity of packages  “Текстильні відходи” 120L + planned quantity of packages “Текстильні відходи” 20L.(e.g.: 2+0+1=3)Didisabled | Values from 0-999 only.Calculated by the formula:  Confirmed quantity of packages “Мікс відходів” 120L + confirmed quantity of packages  “Текстильні відходи” 120L + confirmed quantity of packages “Текстильні відходи” 20L = Total quantity of confirmed packages (e.g.: 2+0+1=3)Disabled | Values from 0-999 only.Calculated by the formula:  Total quantity of actual packages  = actual quantity of packages “Мікс відходів ” 120L + actual quantity of packages  “Текстильні відходи” 120L + actual quantity of packages “Текстильні відходи” 20L.(e.g.: 2+1+0=3)Disabled
“Сума замовлення” Text. Disabled. |   |   | Order sum without discount. Float number with 2 digits. e.g (255.00 грн). Should be greater than 0. No upper limit is set. Received from the order form.  Disabled | Confirmed order sum without discount. Float number with 2 digits. e.g (255.00 грн). Should be greater than 0. No upper limit is set. Calculated by the formula: Confirmed quantity of packages “Мікс відходів” 120L x price per 1 relative package + confirmed quantity of packages  “Текстильні відходи” 120L x price per 1 relative package + confirmed quantity of packages “Текстильні відходи” 20L x price per 1 relative package = Order sum (e.g.: 2300+050+1*250=850.00 грн) Disabled | Actual order sum without discount. Float number with 2 digits. e.g (255.00 грн). May be equal to or greater than 0. No upper limit is set. Calculated by the formula: Actual quantity of packages “Мікс відходів” 120L x  price per 1 relative package + actual quantity of packages  “Текстильні відходи” 120L x price per 1 relative package + actual quantity of packages “Текстильні відходи” 20L x price per 1 relative package = Order sum (e.g.: 2300+150+0*250=650.00 грн) Disabled
“Сертифікат” Text. Disabled. |   |   | Integer 0-999. Received from the order form. Displayed in the format “-50 грн” Disabled | Integer 0-999. Received from the order form. Displayed in the format “-50 грн” Disabled | Integer 0-999. “0” on stage “Скасованo”. On other stages - received from the order form. Displayed in the format “-50 грн” Disabled
“Використані бонуси” Text. Disabled. |   |   | Float number 0.00-999.00 with 2 digits. Received from the order form. Displayed in the format “-50.00 грн” Disabled | Float number 0.00-999.00 with 2 digits. Received from the order form. Displayed in the format “-50.00 грн” Disabled | Float number 0.00-999.00 with 2 digits.  “0.00” on stage “Скасованo”. On other stages - received from the order form. Displayed in the format “- 50.00 грн” Disabled
“УБС кур’єр” Text. Enabled in the scenario are written below |   |   |   |   | Described in Scenario are written below
“Сума до оплати” Text. Disabled. |   |   | Order total. May be equal to or greater than 0. Float number with 2 digits. e.g (150.00 грн) No upper limitReceived from order formDisabled | Confirmed order total.  May be equal to or greater than 0. Float number with 2 digits. e.g 150.00 грн) No upper limit calculated by the formula: Confirmed order sum “Сума замовлення” - “Сертифікат” - “Використані бонуси” = Confirmed order total “Сума до оплати”(e.g.: 850-150-0=700.00 грн)Disabled | Actual order total.  May be equal to or greater than 0. Float number with 2 digits. e.g (150.00 грн) No upper limit calculated by the formula: Actual order sum “Сума замовлення” - “Сертифікат” - “Використані бонуси”  = Actual order total “Сума до оплати” Disabled

</div></b>

2.  For simplification, there are scenarios with user flow during the ordering 

**The primary Rule for debiting: the sequence of debiting UBS courier and to the sorting station: first, the face value of the certificate is debited -> bonuses -> money paid by the client.**

**Scenario 1**

**User flow of changes statuses: "Formed " - "Brought by himself" when the order is unpaid**

The client pays all necessary payments himself by cash at the Receiving station.
The system sends messages by e-mail/notification to the personal cabinet about this case:
EN localization: “Dear client! You are confirmed the order will be brought by yourself to the Receiving station. We draw your attention to the necessity of making payment at the Receiving station. Thank you!”.
UA localization: “Шановний клієнте! Ви підтвердили, що замовлення буде привезено Вами на Станцію приймання самостійно. Звертаємо Вашу увагу на необхідність здійснення розрахунків безпосередньо на Станції приймання. Дякуємо! ”

**Scenario 2**

**User flow of changes statuses: "Formed " - "Brought by himself"**

**Conditions:**

- The field “Списання на станцію сортування”  is displayed
- Admin manually sets the sum in the field “Списання на станцію сортування” 
- The “Списання на станцію сортування” is added to “Сума до сплати”’ in the column "Вивезена кількість"

**1)the order is paid with money / bonuses / money + bonuses:**

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and in the section “Деталі замовлення”.
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
add the following record  (“Зарахування на бонусний рахунок”) in the table with order payment details in the section ‘Оплата замовлення’
add the overpayment amount to the client’s bonuses account (the  button display “Зарахування на бонусний рахунок” in the section ‘Оплата замовлення’ ).
if order payd bonuses  and we have an overpayment, they bonuses automatically be returned to the bonus account

**Case Underpayment**
If “Сума до сплати” is greater than “Замовлення оплачено у розмірі”:

Underpayment = “Сума до сплати” - “Замовлення оплачено у розмірі” 

Underpayment must be paid in cash by the client at the Receiving station
The system sends messages by e-mail/notification to the personal cabinet about this case:
EN localization: “Dear client! We inform you about the necessity of paying for services at the Receiving station. The sum is …. UAH”
UA localization: “Шановний Клієнте! Інформуємо Вас про необхідність оплати за послуги на Станції приймання. Сума до сплати …. грн.”
The client pays the sum that the Underpayment message contains

 **2)the order is paid with certificates + money / certificates + bonuses / certificates + bonuses + money:**

**The rule: The remaining funds from the value of the used certificate are NOT RETURNABLE**

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and in the section “Деталі замовлення”.
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
add the following record  (“Зарахування на бонусний рахунок”) in the table with order payment details in the section ‘Оплата замовлення’
add the overpayment amount to the client’s bonuses account (“Зарахування на бонусний рахунок”).

 **3)the order is paid with certificates**

If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’: 
Money from the certificate covered the sum of “Сума до сплати”
The remaining funds from the face value of the used certificate are NOT RETURNABLE
There is NO OVERPAYMENT in this case.

After all, payments are calculated by the system the Administrator can save the changes  (press the “Зберегти” button).

**Case Underpayment**
If “Сума до сплати” (the paid money with certificate usage)  is greater than “Замовлення оплачено у розмірі”:

Underpayment =“Сума до сплати” - “Замовлення оплачено у розмірі” 

Underpayment must be paid in cash by the client at the Receiving station
The system sends messages by e-mail/notification to the personal cabinet about this case:
EN localization: “Dear client! We inform you about the necessity of paying for services at the Receiving station. The sum is …. UAH”
UA localization: “Шановний Клієнте! Інформуємо Вас про необхідність оплати за послуги на Станції приймання. Сума до сплати …. грн.”
The client pays the sum that the Underpayment message contains

**Scenario 3**

**User flow of changes statuses: “Formed”  - “Adjustment”  - “Confirmed” - “On the route” - “Done”**

**Conditions**
-  Admin sets manually the number of packages on the column “Вивезена к-сть”
- The system should display the field “УБС кур’єр” in the column “Вивезена к-сть” of “Деталі замовлення” section (by default it is set 50 грн)
 - The sections of the order details should be available for editing

**1) the order is unpaid**

**Case Underpayment**
If “Сума до сплати” is greater than “Замовлення оплачено у розмірі”:

Underpayment = “Сума до сплати” - “Замовлення оплачено у розмірі” 

Underpayment must be paid by the client later via cash or non-cash payment with a bank money transfer
The system sends messages by e-mail/notification to the personal cabinet about this case:
EN localization: “Dear client! We inform you about the necessity of paying for services. The sum is …. UAH”
UA localization: “Шановний Клієнте! Інформуємо Вас про необхідність оплати за послуги. Сума до сплати …. грн.”
The client pays the sum that the Underpayment message contains

**2) the order is paid with money / bonuses / money + bonuses:**

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and in the section “Деталі замовлення”.
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
add the following record  (“Зарахування на бонусний рахунок”) in the table with order payment details in the section ‘Оплата замовлення’
add the overpayment amount to the client’s bonuses account (“Зарахування на бонусний рахунок”).

**Case Underpayment**
If “Сума до сплати” is greater than “Замовлення оплачено у розмірі”:

Underpayment = “Сума до сплати” - “Замовлення оплачено у розмірі” 

Underpayment must be paid by the client later via cash or non-cash payment with a bank money transfer
The system sends messages by e-mail/notification to the personal cabinet about this case:
EN localization: “Dear client! We inform you about the necessity of paying for services. The sum is …. UAH”
UA localization: “Шановний Клієнте! Інформуємо Вас про необхідність оплати за послуги. Сума до сплати …. грн.”
The client pays the sum that the Underpayment message contains

**3) the order is paid with certificates + money / certificates + bonuses / certificates + bonuses + money:**

The rule: The remaining funds from the value of the used certificate are NOT RETURNABLE

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and in the section “Деталі замовлення”.
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
add the following record  (“Зарахування на бонусний рахунок”) in the table with order payment details in the section ‘Оплата замовлення’
add the overpayment amount to the client’s bonuses account (“Зарахування на бонусний рахунок”).

**4)the order is paid with certificates** 

If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’: 
Money from the certificate covered the sum of “Сума до сплати”
The remaining funds from the face value of the used certificate are NOT RETURNABLE
There is NO OVERPAYMENT in this case.

After all, payments are calculated by the system the Administrator can save the changes  (press the “Зберегти” button).

**Case Underpayment**
If “Сума до сплати” (the paid money with certificate usage)  is greater than “Замовлення оплачено у розмірі”:

Underpayment = “Сума до сплати” - “Замовлення оплачено у розмірі” 

Underpayment must be paid in cash by the client cash or non-cash payment with a bank money transfer
The system sends messages by e-mail/notification to the personal cabinet about this case:
EN localization: “Dear client! We inform you about the necessity of paying for services. The sum is …. UAH”
UA localization: “Шановний Клієнте! Інформуємо Вас про необхідність оплати за послуги. Сума до сплати …. грн.”
The client pays the sum that the Underpayment message contains

**Scenario 4**

**User flow of changes statuses: “Formed”  - “Adjustment”  - “Confirmed”  - “On the route” / “Not picked up” - ‘Canceled’** 

**Conditions**
- The actual amount of packages of any service (column “Вивезена к-сть”) is '0' 
- The number of packages in the column Actual amount’ is “0”
- The system should display the field “УБС кур’єр” in the column “Вивезена к-сть” of “Деталі замовлення” section (by default it is set 50 грн)
- The field “УБС кур’єр” should be available for editing
- The sections of the order details should NOT be available for editing (except in cases when the order is unpaid / partly paid)
- The sum of  the field “УБС кур’єр” can’t be greater than the field “Сума до сплати”

**1)Order is Unpaid**  

**Case Underpayment**
Underpayment = “Сума до сплати” - “Замовлення оплачено у розмірі” 

Underpayment must be paid in cash by the client cash or non-cash payment with a bank money transfer
The system sends messages by e-mail/notification to the personal cabinet about this case:
EN localization: “Dear client! We inform you about the necessity of paying for services. The sum is …. UAH”
UA localization: “Шановний Клієнте! Інформуємо Вас про необхідність оплати за послуги. Сума до сплати …. грн.”
The client pays the sum that the Underpayment message contains

**2)the order is paid with money / money + cretificate/es**

The rule: The remaining funds from the value of the used certificate are NOT RETURNABLE

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and  in the section “Деталі замовлення”
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
in the case of paid money then add the 2 buttons   (“Зарахування на бонусний рахунок” and “Повернення коштів”) in the table with order payment details in the section ‘Оплата замовлення’.

**3)the order is paid with money + bonuses / money + bonuses + certificate/s**

The remaining funds from the face value of the used certificate are NOT RETURNABLE

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and  in the section “Деталі замовлення”
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
in the case of paid money then add the 2 buttons   (“Зарахування на бонусний рахунок” and “Повернення коштів”) in the table with order payment details in the section ‘Оплата замовлення’.
BONUSES - automatically transferred to the client's bonus account

**4)the order is paid with bonuses / bonuses + certificates**

The remaining funds from the face value of the used certificate are NOT RETURNABLE

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and  in the section “Деталі замовлення”
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
BONUSES - automatically transferred to the client's bonus account

5)the order is paid with a certificate/s 

The remaining funds from the face value of the used certificate are NOT RETURNABLE
There are NO cases of overpayment

**Scenario 5**

**User flow changes statuses: “Formed” - “Canceled” when the order is unpaid**

**Conditions**
- Total number of packages in the column "Підтверджена кількість" is= 0
- The number of packages in the column Actual amount’ is “0
- The admin deletes the order from the system

**There are no cases of overpayment / underpayment**

**Scenario 6**

**User flow changes statuses: “Formed” - “Canceled”** 

**Conditions** 
- The total number of packages in the column "Підтверджена кількість" is = 0
- The number of packages in the column Actual amount’ is “0
- The sections of the order details should NOT be available for editing (and actual amount ) is  disabled.

**1)the order is paid with money / money + cretificate/es**

The rule: The remaining funds from the value of the used certificate are NOT RETURNABLE

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and  in the section “Деталі замовлення”
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
in the case of paid money then add the 2 buttons   (“Зарахування на бонусний рахунок” and “Повернення коштів”) in the table with order payment details in the section ‘Оплата замовлення’.

**2)the order is paid with money + bonuses / money + bonuses + certificate/s**

The remaining funds from the face value of the used certificate are NOT RETURNABLE

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and  in the section “Деталі замовлення”
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
in the case of paid money then add the 2 buttons   (“Зарахування на бонусний рахунок” and “Повернення коштів”) in the table with order payment details in the section ‘Оплата замовлення’.
BONUSES - automatically transferred to the client's bonus account

**3)the order is paid with bonuses / bonuses + certificates**

The remaining funds from the face value of the used certificate are NOT RETURNABLE

**Case Overpayment**
If “Сума до сплати” is less than “Замовлення оплачено у розмірі”’:

Overpayment = “Замовлення оплачено у розмірі” - “Сума до сплати”

After the overpayment is calculated the system:
add the following record “Переплата …. грн”  in the table with order payment details in the section “Оплата замовлення” and  in the section “Деталі замовлення”
After the overpayment is calculated the system and the Administrator saves the changes  (press the “Зберегти” button):
BONUSES - automatically transferred to the client's bonus account

**4)the order is paid with a certificate/s** 

The remaining funds from the face value of the used certificate are NOT RETURNABLE
There are NO cases of overpayment

3. For simplification, there are table that explains the availability of columns in the Order details section

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-bd7a445e-7fff-8764-b25c-b55e69de711c"><p dir="ltr" style="line-height:1.542857142857143;margin-left: 36pt;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;padding:-9pt 0pt 0pt 0pt;"></p><div dir="ltr" style="margin-left:0pt;" align="left">

“Статус замовлення” Order status | “Планована к-сть” Planned amount | “Підтверджена к-сть” Confirmed amount | “Вивезена к-ть” Actual amount | “УБС Кур'єр”UBS Courier | “Списання на Сортувальну станцію”
-- | -- | -- | -- | -- | --
“Сформовано” (fresh order) | Disabled | Enabled and  Admin can edit | Absent | Absent | Absent
“Узгодження” | Disabled | Enabled and Admin can edit | Absent | Absent | Absent
“Підтверджено” | Disabled | Enabled and Admin can edit | Absent | Absent | Absent
“На маршруті” | Disabled | Enabled and Admin can edit | Absent | Absent | Absent
“Сформовано” (“Узгодження”) | Disabled | Enabled and  Admin can edit | Absent | Absent | Absent
“Сформовано” (після Підтверджено) | Disabled | Enabled and Admin can edit | Absent | Absent | Absent
“Не вивезли” | Disabled | Disabled | 0 is set, enabled and Admin can edit | Enabled and Admin can edit | Absent
“Привезе сам” | Disabled | 0 is set. Disabled | Absent | Absent | Enabled and can edit
“Виконано” | Disabled | Disabled | Enabled and Admin can edit | Absent | Enabled and Admin can edit
“Скасовано” | Disabled | 0 is set. Disabled |Disabled | Absent (except the case when Admin sets “Скасовано” after “На маршруті”) | Absent

</div><p dir="ltr" style="line-height:1.542857142857143;background-color:#ffffff;margin-top:-1pt;margin-bottom:-1pt;"><br /></p></b><br class="Apple-interchange-newline">
</body>
</html>

Impact of Change:
#2865, #2866, #3706, #4977, #2898, #2899, #2900, #2901, #3707, #5420, #5417, #3492

Epic: [UBS courier#2195]  https://github.com/ita-social-projects/GreenCity/issues/2195
5. Feature: Orders [Admin cabinet]

**Comment by Olena-Kharkova** [comment]
a table with simplification was added

**Comment by SofiiaHavsot7** [comment]
Postman collection for API testing
[Overpayment Copy.postman_collection.json](https://github.com/ita-social-projects/GreenCity/files/15375501/Overpayment.Copy.postman_collection.json)
