### ISSUE TITLE
[Pick up City. Admin cabinet. Orders] The 'Статус оплати' column isn't sorted in alphabetical order after first clicking on the  in the Order table 

### ISSUE THREAD

**Issue by olyatyshchenko** [ita-social-projects/GreenCity#5528]
**Environment:** Windows 10, Google Chrome Version 111.0.5563.6 (Official Build) (64-bit)..
**Reproducible:** always (Test and Prod).
**Build found:** 23/03/2023.

**Preconditions**

- Log in as Admin https://www.testgreencity.ga/GreenCityClient/#/
- The Orders tab should be opened.
- At least 2 orders should be on the Orders table.

**Steps to reproduce**
1. Click on the arrow icon near the column headline in the 'Статус оплати' column.
2. Pay attention to the sorting in the column.
3. Click on the arrow icon near the column headline in the 'Статус оплати' column.
4. Pay attention to the sorting in the column.

**Actual result**
The items are displayed in alphabetical order  “Я”-”A” after first clicking on the arrow icon, and after second clicking on the arrow icon they are sorted in alphabetical  order  “А”-”Я”.

https://user-images.githubusercontent.com/120178274/227272533-b7afcfba-2eac-4ccd-869e-5da7bf4631c1.mp4

**Expected result**
The items in the 'Статус оплати' column are displayed in alphabetical order  “А”-”Я” after first clicking on the arrow icon, and after second clicking on the arrow icon the items are sorted in order  “Я”-”A”.

**User story and test case links**
E.g.: "User story #3336

**Comment by MaksymGolik** [comment]
On the backend side, these columns are sorted by enum value, which is the English name with underscores, for both locales (ua, en), as this table does not store the Ukrainian translation.

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
