### ISSUE TITLE
[Pick up City. Admin cabinet. Orders]  The 'Iм'я клієнта' column is displayed empty after clicking on the arrow icon near the column headline  in the Order table

### ISSUE THREAD

**Issue by olyatyshchenko** [ita-social-projects/GreenCity#5529]
**Environment:** Windows 10, Google Chrome Version 111.0.5563.6 (Official Build) (64-bit)..
**Reproducible:** always (Test and Prod).
**Build found:** 23/03/2023.

**Preconditions**

- Log in as Admin https://www.testgreencity.ga/GreenCityClient/#/
- The Orders tab should be opened.
- At least 2 orders should be on the Orders table.

**Steps to reproduce**
1. Click on the arrow icon near the column headline in the 'Статус замовлення' column.
2. Pay attention to the sorting in the column.
3. Click on the arrow icon near the column headline in the 'Статус замовлення' column.
4. Pay attention to the sorting in the column.

**Actual result**
The  The 'Iм'я клієнта' column is displayed empty.

https://user-images.githubusercontent.com/120178274/227273412-fc944b27-9499-4910-bbb3-26da72db697c.mp4

**Expected result**
The items in the 'Ім'я клієнта' column are displayed in alphabetical order  “А”-”Я” after first clicking on the arrow icon, and after second clicking on the arrow icon they are sorted in order  “Я”-”A”.

*Additional information **
The bug is also reproduced in the 'Дата оплати' column after second clicking on the arrow icon near the column headline.
( The payment date should be displayed in descending order - from the oldest dates to the newest ones after the first clicking and in ascending order - from the newest dates to the oldest ones after the second clicking).

**User story and test case links**
E.g.: "User story #3336

**Comment by MaksymGolik** [comment]
Not a bug. The sorting process works so that orders without a payment date or the name of the sender, when sorting in descending or ascending order are displayed at the top or bottom, respectively. And after or before, depending on the sorting order, the orders with null values of the column by which sorting is performed the rest of the orders sorted alphabetically go.
