### ISSUE TITLE
[My habits] The tabulation doesn't achieve tabs "My news", "My events",the pencil icon on the habit card, the calendar and there is no visual marker when the system focuses on the avatar icon.

### ISSUE THREAD

**Issue by OksanaObukhovska** [ita-social-projects/GreenCity#5537]
Environment: OS Windows 10 x 64, Br Google Chrome ver. 110.0.5481.178.
Reproducible: always
Build found: 13/03/2023

Preconditions
Have at least one habit in progress.
https://www.greencity.social/#/greenCity opens.
Sign in as a user.
The "My habits" page opens.

Steps to reproduce

Press the Tab key on the keyboard.

Actual result

1. Tabs "My news", and "My events" can't be achieved by tabulation.
2. The system does not focus on the pencil icon on the habit card while using the "Tab".
3. The system does not focus on any element of the calendar on the right side of the page while using the "Tab".
4. There is no visual marker when the system focuses on the avatar icon on the left side of the page 

Expected result

1. Tabs "My news", and "My events" can be reached after the tab "My habits" and before the button "Add new habit" by tabulating.
2. The pencil icon on the habit card can be reached after the button "Add new habit" and before the icon "+ Mark as done" by tabulating.
3. The calendar on the right side of the page can be reached after all controls on all habits cards and before the footer by tabulating.
4. The avatar icon stands out in a square frame after we achieve it by tabulating.

User story and test case links
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/988

[Test case] https://jira.softserve.academy/browse/GC-5535".

Labels to be added
"Bug", Priority ("pri:high"), Severity ("severity: major"), Type ("UI, "Accessibility"), "My habits", "Calendar".

**Comment by sobkiv** [comment]
Tabs "My news", and "My events" can be reached by an arrow right navigation when you reach "My habits"
