### ISSUE TITLE
[My habits] There are grammar mistakes in the text of the "Факт дня" cards.

### ISSUE THREAD

**Issue by OksanaObukhovska** [ita-social-projects/GreenCity#5547]
Environment: OS Windows 10 x 64, Br Google Chrome ver. 110.0.5481.178.
Reproducible: always
Build found: 19/03/2023

Steps to reproduce:

1. Go to https://www.testgreencity.ga/#/greenCity
2. Sign in as a user.
3. Choose Ua localization
4. Open the "My habits" page.

Actual result

There are grammar mistakes in the text of the "Факт дня" cards as shown in the attachments.

Expected result

There are no grammar mistakes in the text of the "Факт дня" cards. 

User story and test case links
E.g.: "User story https://jira.softserve.academy/browse/GC-1803

[Test case] https://jira.softserve.academy/browse/GC-1819".

Labels to be added
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("UI"), "Fact of the day", "localization", and "My habits".

![Ua 2](https://user-images.githubusercontent.com/127955359/227983607-08fe41a9-4bce-465b-8a13-6173ed3af8cd.png)
![Ua](https://user-images.githubusercontent.com/127955359/227983611-14502204-f5bf-4ddc-8dcf-fd959b82a287.png)

**Comment by BohdanaYuzkiv** [comment]
incorrect translation is still present on the page:
![fact_of_the_day](https://github.com/ita-social-projects/GreenCity/assets/109086383/5e24745b-d26a-4054-95d6-e2cf412a72b3)
