### ISSUE TITLE
[UBS User. Orders. Notification] The word 'Pay' (Оплатити) instead of the clickable button 'Pay' (Оплатити) in the content of the email

### ISSUE THREAD

**Issue by Olena-Kharkova** [ita-social-projects/GreenCity#5549]
**Environment:** 
Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71, Firefox version 109.0
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110

**Reproducible:** always
**Build found:** 27/03/2023

**Preconditions**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs or https://www.pick-up.city/#/ubs
2. Sign in as Super Admin
3. Go to the Super Admin profile and choose the UBS-Admin item
4. Choose the 'Замовлення' item
5. Click on the Order's number in the Order table (except 'Виконано' and 'Скасовано' statuses)

**Steps to reproduce**
1. Go to 'Деталі замовлення' section
2. Change the quantity of packages
3. As a client go to the email box and check the content of the incoming message with the title 'Pay for the change to the ordered' ('Оплатіть зміну у замовлені')
4. Pay attention to the word 'Pay' (Оплатити) instead of the clickable button 'Pay' (Оплатити) in the content 

**Actual result**
The word 'Pay' (Оплатити) instead of the clickable button 'Pay' (Оплатити) in the content of the email
The same problem in the Notification tab of the UBS-User cabinet

**Expected result**
The 'Pay' bttn is displayed after the phrase 'Pay:' in the content of the email. It's clickable and provides redirection to the site for payment

**User story and test case links**
E.g.: "User story #(https://github.com/ita-social-projects/GreenCity/issues/4520)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

Attachments:
Email:
![qrOANc38VX](https://user-images.githubusercontent.com/110603507/227999307-67c83511-a0a3-465e-8319-9885a6a94e87.png)

The same problem in the Notification tab of the UBS-User cabinet

![yWvYCzhTMp](https://user-images.githubusercontent.com/110603507/228185117-b8f1da87-c440-4697-aadb-26d8eb80305e.png)

**Comment by OlegVat** [comment]
It seems that a similar problem was solved in ticket #4377. Before opening a new ticket, please check if your issue has already been reported to avoid duplication.
