### ISSUE TITLE
[Footer] There is no icon for TikTok and Patreon

### ISSUE THREAD

**Issue by katia9261** [ita-social-projects/GreenCity#5550]
**Environment**: OS Windows 10, Google Chrome ver. 110.0.5481.178.
**Reproducible:** always
**Build found**: 26/03/2023

**Steps to reproduce**
1. Go to [GreenCity](https://www.testgreencity.ga/#/ubs)
2. Scroll down to 'Footer'

**Actual result**
There aren't any icons for TikTok and Patreon according to the mock-up 

**Expected result**
There are icons for TikTok and Patreon according to the mock-up 
https://www.figma.com/file/KmaTQl8I31fnA3leNd9CoX/UBS-(%D0%A3%D0%91%D0%A1)?node-id=245%3A548&t=ViWfNhThN3Q8luko-0

**Comment by BohdanaYuzkiv** [comment]
TikTok and Patreon icons aren't displayed, the default social network icon is used
![social_net_display](https://github.com/ita-social-projects/GreenCity/assets/109086383/d88aad1e-f1ad-4d2e-99bc-53e6726f3a59)
![soc_net](https://github.com/ita-social-projects/GreenCity/assets/109086383/f2a220e6-8251-452e-ad54-de42dbc13f3a)

**Comment by katia9261** [comment]
It should be for UBS (Pick Up) part
![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/63b6041d-6c71-454e-80be-979d241253e4)
