### ISSUE TITLE
News page: List view option issue #460 #553

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/GreenCity#556]
Actual result: The text is too close to the title.
Expected result: Text should be placed on the required distance to the title.

![2NewsListBug](https://user-images.githubusercontent.com/62544149/78749972-fbc0b100-7977-11ea-84ac-23c1717ddf0b.png)

![2NewsListBugSizes](https://user-images.githubusercontent.com/62544149/78780608-8cfb4c00-79a7-11ea-84b1-fcd0cec5dca9.png)

**Comment by rsyvulko** [comment]
Verified
