### ISSUE TITLE
[Habits view] UI of the 'To-do list' section doesn't correspond to mockup.

### ISSUE THREAD

**Issue by YakymetsHub** [ita-social-projects/GreenCity#5560]
**Environment: 11 Home, Google Chrome.
**Reproducible:** always.
29.03.23

**Preconditions**

1. Registered User is logged in
2. User has at least one habit in progress

**Steps to reproduce**

1. Click on the habit card on My habits page.
2. Verify If the UI of the 'To-do list' section corresponds to the mockup.

**Actual result**
 UI of the 'To-do list' section doesn't correspond to the mockup.

**Expected result**
UI of the 'To-do list' section corresponds to the mockup.

![habits To-do list edit](https://user-images.githubusercontent.com/107051540/228541694-0e70983a-e101-41c0-a439-332672ce3128.jpg)
![habits To-do list](https://user-images.githubusercontent.com/107051540/228541704-1acb0a85-ab5d-4a1e-981c-1e2ad9ea2b6f.jpg)

**Comment by DanaIuich** [comment]
UI of the 'To-do list' section doesn't correspond to the mockup.
<img width="217" alt="to_do_list" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/4ccc2e82-e28a-4984-ba36-e497006cf330">

**Comment by atsa21** [comment]
It is mockup bug - the design was agreed with Viktoriya Ryazhska
