### ISSUE TITLE
Home page : List issue, eco-news section

### ISSUE THREAD

**Issue by Nataliia2903** [ita-social-projects/GreenCity#557]
Current state : The text consist  "Read more" labels and dates. 
Desired state : Text should be placed separately from "Read more" labels and dates.

<img width="797" alt="Capture" src="https://user-images.githubusercontent.com/63233271/78755522-fc5e4500-7981-11ea-9aa9-c90dc463084d.PNG">

**Comment by rsyvulko** [comment]
Verified. Not relevant.
