### ISSUE TITLE
[Pickup city UBS User data] Checkmark"Зробити адресою за замовчуванням" is missing on the page "User data" when user edited the data

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5571]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,( Prod )

Build found: 30/02/2023

**Preconditions**

1.  The user should be authorized
2.  Go To (https://www.pick-up.city/#/ubs)
3.  Sign in as authorized user
4.  Click on the profile and choose the item 'UBS-user'
5.  The user should be have 2 Address

**Steps to reproduce**
1. Click on section "User data"
2. Click on the button "Edit date"

**Actual result**
Checkmark"Зробити адресою за замовчуванням"is missing on the page "User data"
**Expected result**
Checkmark"Зробити адресою за замовчуванням"is added  on the page "User data"
<img width="744" alt="Знімок екрана 2023-03-30 о 11 47 04" src="https://user-images.githubusercontent.com/116280846/228782144-8e40f228-0fe8-4256-b7b7-88d50dd7dd3b.png">

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("pri: "medium), Severity ("severity:major"), Type ("UI, "Functional"),

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
