### ISSUE TITLE
[Admin cabinet.Pricing page] Button "UP" in field 'Basic cost' should correctly increase volume of basic cost in 'Service'

### ISSUE THREAD

**Issue by BobrovK** [ita-social-projects/GreenCity#5576]
Environment: macOS Monterey 12.6.3 (21G419)
Safari 16.3 (17614.4.6.11.6, 17614)
Google Chrome 111.0.5563.64.
Reproducible: always.
Build found: last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev

Preconditions:
The website is opened https://www.testgreencity.ga/#/ubs .
The User is registrated as SuperAdmin.
The Tariffs link is opened.
The pricing card is created.
Find the necessary card on the main page "Тарифи" (tariffs), click on it to see the tariffs card
Click to button "Додати сервіс" (Add the service)on the tariffs card
The pop-up window "Додати сервіс" (Add the service) should be opened
Other fields are filled in correctly

Steps to reproduce

1. In field "Basic cost" write 5,00
2. Click button "UP"
3. Click one more time button "UP"

Actual result
After first click 5,00 changes to 5,01. After the second click 5,01 changes to 6,01

Expected result
After first click 5,00 should change to 6,00. After the second click to 7,00.

User story and test case links
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/4428, https://github.com/ita-social-projects/GreenCity/issues/4427

**Comment by NadiiaStoiko** [comment]
Requirements was changed, now arrows is removed from field "Basic cost"
