### ISSUE TITLE
[Pickup city UBS User data]  The delete icon does not respond as in the mockup on the page "User data"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5577]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,( Prod )

Build found: 30/02/2023

**Preconditions**

1. The user should be authorized
2. Go To (https://www.pick-up.city/#/ubs)
3. Sign in as authorized user
4. Click on the profile and choose the item 'UBS-user'
5. The user should be have 2 Address

**Steps to reproduce**
Click on section "User data"
Click on the button "Edit date"
**Actual result**
The delete icon does not respond as in the mockup 
<img width="1073" alt="Знімок екрана 2023-03-30 о 12 19 04" src="https://user-images.githubusercontent.com/116280846/228792729-87c33bf5-1fa9-4b40-9225-850d565f1297.png">

**Expected result**
The delete icon does not respond as in the mockup
<img width="683" alt="Знімок екрана 2023-03-30 о 12 20 30" src="https://user-images.githubusercontent.com/116280846/228792847-7d9774b5-18f0-4ec8-bad7-99c59fe6c7e0.png">

[
](https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=20703-62409&t=ahJvOXJhB8VyIXuP-0)

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity:minor"), Type ("UI, ),

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
