### ISSUE TITLE
[UBS Admin Cabinet] User can`t save "Найменування послуги"(name of the service in UA) in "Сервіси" with 255 characters

### ISSUE THREAD

**Issue by patselyuk** [ita-social-projects/GreenCity#5579]
**Environment:** macOS Monterey 12.6.3 (21F79), Google Chrome 111.0.5563.64
**Reproducible:** always
**Build found:** 30.03.2023

**Preconditions**

1. The website is opened https://www.testgreencity.ga/#/ubs
2. Login as super admin user
3. Page "Tariffs" is opened
4. Click on the string with a tariff

**Steps to reproduce**

1. Click on the 'pencil' in "Сервіси"
2. Write "впоравпрлаврпвролпрворполвраполвролпрволвпоравпрлаврпвролпрворполвраполвролпрволвпоравпрлаврпвролпрвon" the field “Найменування послуги” 
3. Click button 'Зберегти'

**Actual result**
Service don`t save.

**Expected result**
Service saved

**User story and test case links**
E.g.: "User story #4428, #4427
[Test case](https://jira.softserve.academy/browse/GC-6031)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by sobkiv** [comment]
Could I move this issue to "Done"?
