### ISSUE TITLE
Header: Menu appearance

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/GreenCity#558]
As an end User I want to see a menu list, so I can navigate to the section interesting for me, by clicking on the relevant tab. 

Mock up:
![3HeaderRegistedUser](https://user-images.githubusercontent.com/62544149/78752236-6247ce00-797c-11ea-9282-2ae3b97983d4.png)
![4HeaderUnregistedUser](https://user-images.githubusercontent.com/62544149/78753750-0af72d00-797f-11ea-8fe0-de439abc75ca.png)

Acceptance criteria:
1. For registered end User for screen extensions:
-  1200, 992: all section names should be placed horizontally and include: GreenCity logo, Section names - Eco news (in green color), Tips & Tricks, Places, About us, My habits; Search, Language, User Name/Profile  sections.
- 768, 576: all section names should be placed horizontally and include: GreenCity logo and Search, Language, Profile sections. Other sections should be replaced by the drop-up Burger menu in the right corner of horizontal line.
- 576 (additional option): all section names should be placed horizontally and include: GreenCity logo, Search, Language sections. Other sections should be replaced by the drop-up Burger menu in the right corner of horizontal line.
- 320: menu should be vertical and include sections : GreenCity logo (top left corner), Section names - Eco news (in green color), Tips & Tricks, Places, About us, My habits; User Name (in green color), Profile, Settings, Sign out sections.

2. For unregistered end User, criteria are the same as mention above except for Profile section. It should be replaced by two sections:
- Sigh in (in green color).
- Sigh up (as a button, in green color).

3. For unregistered end User for screen extension 320:
- menu should be vertical;
- menu should include sections : GreenCity logo (top left corner), Section names - Eco news (in green color), Tips & Tricks, Places, About us, My habits; Sigh in (in green color), Sigh up (as a button, in green color).
![7HeaderVertical3](https://user-images.githubusercontent.com/62544149/78760863-71357d00-798a-11ea-8f7b-cf03e6867dba.png)

4. For Sections Profile and Language for screen extensions 768, drop-up menu should be opened by clicking on the Section name. Menu list should be places vertically and include such text:
- for Language: En (shown in the main horizontal menu), Ua, Ru.
- for Profile: User Name (shown in the main horizontal menu), Profile, Settings, Sign out.

![5HeaderVertical1](https://user-images.githubusercontent.com/62544149/78755992-b9e93800-7982-11ea-8efb-9ea175960670.png)

5. For other Sections included into Burger menu (Eco news, Tips & Tricks, Places, About us, My habits) for screen extensions 768 and lower, menu should be opened by clicking on the Burger menu. Menu list should be places vertically and include section names.

![6HeaderVertical2](https://user-images.githubusercontent.com/62544149/78759531-6f6aba00-7988-11ea-8064-9c476a5ac035.png)

6. For sections with drop-up menu:
- menu opens from the top;
- when one menu is open and end User opens other drop-up menu, then the first open menu hides;
- for screen extensions 768, 320 menu could be closed with a criss-cross on the top right corner of the screen.

7. Link requirements are described in #352.

8. Translation of header into other languages:

- EN: Eco news, Tips & Tricks, Places, About us, My habits, Sign in, Sign up

- UA: Еко новини, Поради, Місця, Про нас, Мої звички, Увійти, Зареєструватись.

- RU: Эко-новости, Советы, Места, О нас, Мои привычки, Войти, Зарегистрироваться.

Assumptions and constraints:
Header should be always visible on any page of the site.

#352 #558 #670

**Comment by MariiaShtraisel** [comment]
New mockup : https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=12201-5&mode=design
