### ISSUE TITLE
[Pickup city UBS User data] The  UI  controls are not aligned and are not respond as in the mockup on the page "User data" 

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5581]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,( Prod and Test )

Build found: 30/02/2023

**Preconditions**

1. The user should be authorized
2. Go To (https://www.pick-up.city/#/ubs)
3. Sign in as authorized user
4. Click on the profile and choose the item 'UBS-user'
5. The user should be have 2 Address

**Steps to reproduce**
1. Click on section "User data"
Pay attention to the UI controls and the spaces between the name of the frame and the text.

**Actual result**
The UI controls are not aligned and are not respond as in the mockup 
<img width="1280" alt="Знімок екрана 2023-03-30 о 13 52 31" src="https://user-images.githubusercontent.com/116280846/228815431-8a138538-1337-4dea-8552-7ab2a0e13c7f.png">

**Expected result**
The UI controls are  aligned and respond as in the mockup 

<img width="763" alt="Знімок екрана 2023-03-30 о 13 57 02" src="https://user-images.githubusercontent.com/116280846/228815628-d796c7a5-efa5-44d3-b33e-c0f43fce9066.png">

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("pri: Low), Severity ("severity:minor"), Type ("UI,), "

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
