### ISSUE TITLE
[UBS Admin Cabinet] User don`t have error message when write 256 characters in field "Name of the service EN" in "Services"

### ISSUE THREAD

**Issue by patselyuk** [ita-social-projects/GreenCity#5589]
**Environment:** macOS Monterey 12.6.3 (21F79), Google Chrome 111.0.5563.64
**Reproducible:** always
**Build found:** 30.03.2023

**Preconditions**

1. The website is opened https://www.testgreencity.ga/#/ubs
2. Login as super admin user
3. Page "Tariffs" is opened
4. Click on the string with a tariff

**Steps to reproduce**

1. Click on the 'pencil' in "Сервіси"
2. Write "jjgkjfgjfkjgfjgjfjgkjfjkfjgkjfkjjfkjkfjkgjkfjgkjgfkjgkjfkjgkjfkmcvmbfjdrkdnfkdsdsdsdss vdfdfrfdffd fdfjdsfhdhfkhdkjghjkdfhjjgkjfgjfkjgfjgjfjgkjfjkfjgkjfkjjfkjkfjkgjkfjgkjgfkjgkjfkjgkjfkmcvmbfjdrkdnfkdsdsdsdss vdfdfrfdffd fdfjdsfhdhfkhdkjghjkdffdfjdsfhdhfkh" the field “Name of the service”
3. Click button 'Save'

**Actual result**
No error message. Service don`t save

**Expected result**
Error message "Error message"The field must contain between 1 and 255 characters".Service don`t save

**User story and test case links**
E.g.: "User story #4427, #4428
[Test case](https://jira.softserve.academy/browse/GC-6056)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by NadiiaStoiko** [comment]
Requarments changed, now the field “Name of the service” must contain before 30 characters. Added error message 'The field must contain between 1 and 30 characters'.
