### ISSUE TITLE
[Friends] User isn't able to reject friend request by clicking 'Decline' button

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5594]
Environment: Windows 10 Pro, Chrome 111.0.5563.65
Reproducible: always.
**Build found:**17.03.2023

**Preconditions**
The registered user is logged in
Request tab on My Friends page is opened
User has received at least 1 friends' request

**Steps to reproduce**
1. Click on “Decline” button on the friend’s card

**Actual result**
'Decline' button doesn't react on clicking, the friend's card is shown

**Expected result**
Friend’s card disappears from “Requests” tab; user card isn't displayed in all friends list

**User story and test case links**
E.g.: "User story #2084
[Test case](https://jira.softserve.academy/browse/GC-4231), (https://jira.softserve.academy/browse/GC-4235)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by BohdanaYuzkiv** [comment]
friend request can not be declined. there is an issue:
![image](https://github.com/ita-social-projects/GreenCity/assets/109086383/50097b85-9e62-4f65-954e-71f021fd1fc2)

**Comment by Maxv1z** [comment]
Not reproducible
