### ISSUE TITLE
[Events]Add possibility to choose filters

### ISSUE THREAD

**Issue by SokhaTaras** [ita-social-projects/GreenCity#5597]
Environment:
Windows 10 Pro, Chrome. Версия 109.0.5414.120 (64 бит)

Reproducible:
sometimes

Build found:
01.04.2023

Steps to reproduce

Go to https://www.greencity.social/#/greenCity
The Admin is logged 
Go to 'Events'
Find the event.
Choose on some filters.
Actual result
None of the selected filters are displayed

Expected result
All data about the filters should be displayed

**Comment by darinadobrukha** [comment]
The functionality is still not applicable
