### ISSUE TITLE
[Event Dashboard] No message displayed at the end of the 'Event' page

### ISSUE THREAD

**Issue by LiliaZakharko** [ita-social-projects/GreenCity#5601]
Environment: Windows 10 Pro, Chrome 111.0.5563.65
Reproducible: always
Build found: 12.03.2023

**Steps to reproduce**

1. Go to the  https://www.testgreencity.ga/#/greenCity
2. 1st scenario - user is logged in. 2d scenario - user is not logged in
3. Go to the 'Event' dashboard
4. Scroll down to the end of the 'Event' page

**Actual result**
At the end of the 'Event' page, there is no message displayed. 

**Expected result**
The message is displayed: "Unfortunately, there are no events found"

**User story and test case links**
E.g.: "User story #3197 #3266 
[Test case](https://jira.softserve.academy/browse/GC-3868)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Roksana77** [comment]
There is loader instead of this message. Bug is still exist on Chrome 127.0.6533.100 (64-bit)

**Comment by K4sik** [comment]
This bug doesn't reproduce anymore. I've tested 4 days in a row on Chrome 129.0.6668.59 (64-bit).
