### ISSUE TITLE
[Pickup city UBS User data]when editing the  error message doesn't appear and frames:"Name ,"Surname " are not highlighted in red when user enter not valid date on the page "User Data"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5610]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,( Prod and Test )

Build found: 30/02/2023

**Preconditions**

1. The user should be authorized
2. Go To (https://www.pick-up.city/#/ubs)
3. Sign in as authorized user
4. Click on the profile and choose the item 'UBS-user'

**Steps to reproduce**

1. Click on section "User data"
2. Click on button "Edit data"
3. Enter in the felds  Name ,"Surname  date  with  character +

**Actual result**
the  error message doesn't appear and frames:"Name ,"Surname "frames are not highlighted in red when user enter not valid date
<img width="1275" alt="Знімок екрана 2023-04-03 о 12 43 06" src="https://user-images.githubusercontent.com/116280846/229477380-3b6b1d47-c457-4a98-862f-6a0f7c0bd181.png">

**Expected result**
the  error message does appear and frames:"Name ,"Surname "frames are highlighted in red .
"EN Only letters, numbers and hyphen, space, apostrophe are allowed"
" UA Дозволені лише букви,цифри,дефіс, пробіл, апостроф"

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity:minor"), Type ("UI, "Functional"),

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
