### ISSUE TITLE
[UBS_Prod. User_Data] Wrong popup window design after pressing 'Change Password' for users registered with credentials

### ISSUE THREAD

**Issue by RostyslavTomkiv** [ita-social-projects/GreenCity#5613]
**Environment:**  Windows 11 Home 64 bit, Chrome Version 110.0.5481.97 (Official Build)
**Reproducible:** always
**Build found:** 04/03/2023

**Preconditions**
1. Logged in as an User to https://www.pick-up.city/#/ubs (with credentials, not with google account)
2. Click on the user profile and choose 'UBS-user'
3. Choose 'User data' tab

**Steps to reproduce**
1. Click on the 'Change Password' button

**Actual result**
1. A popup with 2 fields 'Enter the new password' and 'Repeat the new password' for changing passwords for users registered with google account has appeared.
![Screenshot 2023-04-03 140903](https://user-images.githubusercontent.com/119998851/229493808-a8e091de-98cc-4abf-803f-c2d7762d825f.png)

**Expected result**
1. A popup with 3 fields 'Enter the current password', 'Enter the new password, 'Repeat the new password' should appear.
2. Mockup: https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=12201%3A2&t=Im6PrCmycgCOGaC4-1

**User story and test case links**
E.g.: "User story #4276 Scenario 2
[Test case](https://jira.softserve.academy/browse/GC-6184)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
