### ISSUE TITLE
[Pickup city UBS User data]when the user editing the remover item "X"missing in field "Альтернативна скринька"on the page "Дані користувача"

### ISSUE THREAD

**Issue by RoksolanaKolomiyets** [ita-social-projects/GreenCity#5617]
Environment: Windows 10 Home (Version 22H2)
Chrome version 108.0.5359.71
MacOS version 12.6.1 (21G217)
Chromе version 107.0.5304.110
Reproducible: always,( Prod and Test )

Build found: 30/02/2023
**Preconditions**

1. The user should be authorized
2. Go To (https://www.pick-up.city/#/ubs)
3. Sign in as authorized user
4. Click on the profile and choose the item 'UBS-user'

**Steps to reproduce**

1. Click on section "User data"
2. Click on button "Edit data"
3. Fill in fields "Name and "Surname"
4. Click on link "Додати альтернативний email"
5. Enter in field "Альтернативна скринька" date ( e.g  pickupubs@city.com )

**Actual result**
when the user editing the remover item "X"missing in field "Альтернативна скринька"on the page "Дані користувача"
<img width="1280" alt="Знімок екрана 2023-04-04 о 10 36 43" src="https://user-images.githubusercontent.com/116280846/229721587-64040a9d-eeb9-40e3-9f31-162291166884.png">

**Expected result**
the remover item "X" should be added in field "Альтернативна скринька"
<img width="687" alt="Знімок екрана 2023-04-04 о 10 38 59" src="https://user-images.githubusercontent.com/116280846/229722189-dda28bd0-c417-40e9-86f6-e90004538869.png">

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("pri: Low "), Severity ("severity: Minor"), Type ("UI, "Functional"),

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
