### ISSUE TITLE
[Events]Incorrect date of creation

### ISSUE THREAD

**Issue by SokhaTaras** [ita-social-projects/GreenCity#5629]
Environment:
Windows 10 Pro, Chrome. Версия 109.0.5414.120 (64 бит)

Reproducible:
sometimes

Build found:
01.04.2023

Steps to reproduce

Go to https://www.testgreencity.ga/GreenCityClient/#/
The Admin is logged (Login: [admin.greencity@starmaker.email](mailto:admin.greencity@starmaker.email); Password: GreenCityAdmin-1[adminubs@starmaker.email](mailto:adminubs@starmaker.email)
Go to 'Events'
Find the event.

Look at creation date
Actual result
it's equal to current date
Expected result
The date should be correct

**Comment by morholha** [comment]
The event can be created only from tomorrow
