### ISSUE TITLE
My cabinet: Manage goals

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/GreenCity#563]
As a registered User I want to have a possibility to update goals created by me in My cabinet, so I can correct mistakes or delete the goal.

![8ManageGoals2](https://user-images.githubusercontent.com/62544149/78906684-547f6f00-7a88-11ea-8f90-c58c42db4cdf.png)
![8ManageGoals1](https://user-images.githubusercontent.com/62544149/78906697-59dcb980-7a88-11ea-931c-db1de9573f93.png)

Acceptance criteria
1. Add buttons Edit and Delete on the right side of the window (same as for Write your goal here).

Assumptions and dependencies:
1. Should be valid only for positions created by this User.
2. Should be valid for all languages.

**Comment by rsyvulko** [comment]
Not relevant.
