### ISSUE TITLE
[UBS Admin. Tarrifs] The Tarrif`s name and description are displayed in Ukrainian for the EN site language.

### ISSUE THREAD

**Issue by LiliiaKhoroz** [ita-social-projects/GreenCity#5649]
Environment: Windows 10
Google Chrome 109.0.5414.75
Reproducible: always
Build found: 06/04/2023

Preconditions:
1. Logged in to GreenCity as an Admin https://www.testgreencity.ga/#/ubs
2. The 'Tariffs' section is opened
3. The site language is EN
4. The card is created

Steps to reproduce
1. Click on the card.
2. Click on 'Add Service' button for Tariffs for services.
3. Fill in All required fields.
4. Click the 'Add' button.
5. Pay attention to the service name and description.

Actual result
The Tarrif`s name and description are displayed in Ukrainian for the EN site language.

Expected result
The Tarrif`s name and description are displayed in English for the EN site language. 

User story and test case links
User story #4948
![Eng1](https://user-images.githubusercontent.com/123656862/230573372-a7c1049b-f5fc-4c56-8881-e096db67e1d3.png)
![Eng 3](https://user-images.githubusercontent.com/123656862/230573368-e6b0fd5c-0cbc-4424-ac2a-09e12cfe4a12.png)
![Eng2](https://user-images.githubusercontent.com/123656862/230573375-9771fca9-18f6-42a5-b2d0-307752a4b1ab.png)

[Test case]https://jira.softserve.academy/browse/GC-6194

**Comment by MaksymGolik** [comment]
Bug front-end, in the payload values for Ukrainian and English locales are sent mixed up.
![image](https://user-images.githubusercontent.com/99403738/233978378-e6421e69-3ba9-4a41-9ccf-6fc8b1108278.png)
