### ISSUE TITLE
[UBS-User.Edit Profile] User cannot save the default address when he/she selects it on the editable 'User data' page

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5656]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 111.0.5563.147 (64-bit).
**Reproducible:** always.
**Build found:** 07/04/23

**Preconditions**

1. User is logged in as user.
2. User data tab is opened.
3. More than 1 address is added.

**Steps to reproduce**
1. Click on the 'Edit Data' button.
2. Click on the unchecked 'Make the address by default' checkbox for any address except the first one.
e.g. Address 3.
4. Click on the 'Save changes' button.
5. Click on the 'Edit Data' button.
6. Pay attention to the 'Make it the default address' checkbox for this address.
7. Click on the 'Orders' tab in the navigation menu.
8. Click on the 'New order' button''.
9. Go to the 'Personal data' tab.
10. Pay attention to the default address in the 'Garbage collection address' section.

**Actual result**
'Make the address by default' checkbox is unchecked for the selected address on the editable 'User data' page. The default address isn't changed in the Order form.

https://user-images.githubusercontent.com/119864646/230674959-b1ba0796-46e1-4d1b-9ca0-2fc997c8825b.mp4

**Expected result**
'Make the address by default' checkbox should be checked for the selected address on the editable 'User data' page. The default address in the Order form should be matched with the address by default in the editable 'User data' page.

**User story and test case links**
User story #3811 
[Test case](https://jira.softserve.academy/browse/GC-2828)

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: Major"), Type "Functional").

**Comment by MaksymGolik** [comment]
This functional not implemented yet

**Comment by sergoliarnik** [comment]
Backend part is ready. Use PATCH/ubs/makeAddressActual/{addressId} to make address actual
