### ISSUE TITLE
[Pick up city UBS-UBS Admin Cabinet ] Wrong title of the 'Будинок'and 'Корпус'  fields  in En localization in the 'Waste export address' section of the order form

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5657]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 112.0.5615.50 (64-bit).
**Reproducible:** always.
**Build found:** 08/04/23

**Preconditions**
1. User is logged in as administrator.
2. Orders tab is opened.
3. At least 1 order is in the orders table.

**Steps to reproduce**

1. Click on any order.
2. Click on the "Waste export address" menu.
3. Pay attention to the title of the 'Будинок'  field in En localization.
4. Pay attention to the title of the 'Корпус'  field in En localization.

**Actual result**
The fields title are 'Building'/'Будинок' and 'Corp'/'Корпус'.
![image](https://user-images.githubusercontent.com/119864646/230716534-8e0cfa86-6fa8-4faf-9a6f-b1a5b3260e48.png)

**Expected result**
The fields title should be 'House'/'Будинок' and 'Building'/'Корпус'.

**Addition information**

It's the same for the 'Корпус' field on the 'User data' page and the order form in the User cabinet in En localization.
![image](https://user-images.githubusercontent.com/119864646/230716838-bf7f395c-35bb-4756-b882-b0836bc6b6ce.png)

**User story and test case links**
User story #5101 

**Labels to be added**
"Bug", Priority ("pri: Low "), Severity ("severity: Trivial"), Type ("UI").

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
