### ISSUE TITLE
[UBS] Blank "unpaid amount" in scheduled notification

### ISSUE THREAD

**Issue by Maksym-Lenets** [ita-social-projects/GreenCity#5685]
**Steps to reproduce**
1. Create new order
2. Do not pay for this order
3. Receive notification

**Actual result**
![img](https://user-images.githubusercontent.com/20425724/232679454-609daf92-e004-4074-8b08-95770c8dcb1a.JPG)

**Expected result**
${amountToPay} should be filled with the unpaid amount

**Comment by DanaIuich** [comment]
https://github.com/ita-social-projects/GreenCity/assets/128155213/d3f92506-f6ec-4945-b040-08d84be9a3e0
