### ISSUE TITLE
[UBS Admin Notifications] Infinite scroll absence

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5691]
Environment: Windows 10 Pro, Chrome 111.0.5563.65
Reproducible: always.
**Build found:**19.04.2023

**Preconditions**

1. The registered user is logged in as Admin
2. Notifications page is opened

**Steps to reproduce**
1. Verify if infinite scroll is present on the page

**Actual result**
Pagination for switching between pages is present.

**Expected result**
All the Notifications can be viewed by the infinite scroll. 

![paging](https://user-images.githubusercontent.com/109086383/233161200-1aa5b20c-7b4c-4d87-b0b8-b2f97830af4c.png)

**User story and test case links**
User story #4510

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by nina279** [comment]
resolved
