### ISSUE TITLE
Creation of new place as Admin

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#57]
As Admin I want to create new place so that it will be shown on the list of Places and map.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/63800988-fbf3cb00-c917-11e9-8f5f-6f11b9a1aef6.png)

Acceptance criteria:

1. "Create new place" button is available on the "Places" tab.

2. WHEN Admin see "Places" tab, THEN he can click on "Create new place" button.

3. WHEN Admin clicks "Create new place" button THEN he can see popup with next fields:
a. input field "Type/Category"
b. input field "Name"
c. input field "Address"
d. input field "Working times"
e. "Save" button

4. WHEN Admin fill in all required fields for new place and clicks "Save" button THEN he/she can see newly created place on the top of the list on Places tab.

**Comment by Mari1ana** [comment]
Bug #289 
Bug #290 
Bug #291 done
Bug #292 done
Bug #308

**Comment by rsyvulko** [comment]
Not relevant.
