### ISSUE TITLE
[View my events] 'Cancel join event' button is not replaced with 'Join event' button after clicking on the 'Cancel join event' button

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#5708]
Environment: Windows 10 Pro x64 21H2, Google Chrome 110.0.5481.178.
Reproducible: always.
Build found: 23.04.2023

**Preconditions**

1. https://www.testgreencity.ga/#/greenCity is opened
2. The user is authorized
3. There is at least one future event joined by this user

**Steps to reproduce**

1. Go to 'My space' tab
2. Go to 'My Events' tab
3. Scroll down to joined event
4. Click on the 'Cancel join event' button

**Actual result**
Frame of the button 'Cancel join event' changes the color. 
![GreenCity - Google Chrome 23 04 2023 20_50_29 (2)](https://user-images.githubusercontent.com/128295227/233859175-1b26598f-946d-4292-8183-ceb6eeddbb15.png)

**Expected result**
 'Cancel join event' button is replaced with 'Join event' button.

**User story and test case links**
E.g.: "User story #3375 

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Minor"), Type ("UI, "Functional").

**Comment by DanaIuich** [comment]
the button 'Cancel join event' changed on button "Cancel Request"
