### ISSUE TITLE
[Pick up city UBS.User's personal cabinet] User cannot enter numeric characters in the 'Name' and 'Surname' fields on the 'User date' page

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5713]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 112.0.5615.13 (64-bit).
**Reproducible:** always. 
**Build found:** 24/04/23

**Preconditions**

1. User is logged in as user.
2. User data tab is opened.
3. 'Name' and 'Surname' fields are filled and contain alphabetic characters 
e.g. Iryna 
e.g. Mikhalska 

**Steps to reproduce**
1. Click on the 'Edit Data' button.
2. Add numeric characters in the 'Name' field
e.g. Iryna1.
3. Add numeric characters in the  'Surname' field
e.g. Mikhalska2.

**Actual result**

Error messages in red are displayed when numeric characters are entered in the 'Name' and 'Surname' fields. 

![image](https://user-images.githubusercontent.com/119864646/234063328-abf880dd-e245-4b3c-93f2-b42b9b3c638d.png)

**Expected result**

User can enter numeric characters in the 'Name' and 'Surname' fields.

**User story and test case links**
User story #3811 

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity:Trivial"), Type ("Functional").

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
