### ISSUE TITLE
[Pick up city UBS.Order form] User cannot save the order when the "Name" and 'Surname" fields contain  numeric or apostrophe characters

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5716]
**Environment**: Windows 10 Pro v.21H2, Google Chrome 112.0.5615.138 (64-bit).
**Reproducible**: always.
**Build found**: 25/04/23

**Preconditions**

User is logged in as user.
Orders tab is opened.
User data is filled.

**Steps to reproduce**

1. Click on the 'New order' button.
2. Choose the localization of waste disposal.
e.g Kyiv
3. Click on the 'Continue' button.
4. Select the number of the packages
e.g. 2 packages of 120L.
5. Click on the 'Next' button.
6. Add the numerics or apostrophe characters in the "Name" field.
7. Add the numerics or apostrophe characters in the "Surname " field.
8. Click on the 'Next' button.
9. Click on the 'Pay' button.
10. Click on the name in the top right.
11. Click on the UBS-user.
12. Pay attention to the current orders.

**Actual result**

User sees 'Oops, something went wrong' message after clicking on the 'Pay' button. The order isn't saved.  

https://user-images.githubusercontent.com/119864646/234205915-712b1109-5465-4df7-9e25-08cc6583d35a.mp4

**Expected result**

User can save the order when the "Name" and 'Surname" fields contain  numeric or apostrophe characters

**User story and test case links**
User story #5719 

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: Blocker"), Type ("Functional").

**Comment by Maksym8Kravchenko** [comment]
This bug is not fixed. The user still cannot input the numeric characters into the Name/Surname fields.

**Comment by DanaIuich** [comment]
Bug is fixed
