### ISSUE TITLE
[UBS Tariffs Page] Error message appears when Admin activates Tariff card

### ISSUE THREAD

**Issue by LiliaZakharko** [ita-social-projects/GreenCity#5729]
**Environment:** Windows 10 Pro, Chrome 111.0.5563.65.
**Reproducible:** always.
**Build found:** 01.05.2023

**Preconditions**
1. https://www.testgreencity.ga/ is opened.
2. User is logged in as a Super Admin
3. There is at least one inactive 'Tariff card'.

**Steps to reproduce**
1. Go to the 'Тарифи' page.
2. Choose 'Inactive' state.
3. Select necessary card from the sorting list on the page.
4. Select the point of menu on this card - 'Підтвердження відновлення' (in form of round arrow). 

**Actual result**
Error message appeared: 'Tariff has not been activated. Please add service to tariff'.

**Expected result**
Tariff card was saved, the window “Підтвердження відновлення” was closed and the user will see the main page "Тарифи” view.

**User story and test case links**
E.g.: "User story #4425 
[Test case](https://jira.softserve.academy/browse/GC-7033)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by LiliaZakharko** [comment]
<img width="840" alt="Tariff activation Error message" src="https://user-images.githubusercontent.com/128394400/235458891-8fd2c0df-1d1b-46fa-9b66-37d0d7d55327.png">

**Comment by MaksymGolik** [comment]
The error message says that you need to add a service for the tariff, and then you can activate it.

**Comment by LiliaZakharko** [comment]
> The error message says that you need to add a service for the tariff, and then you can activate it.

'Service' is not mandatory. So I should be able to activate the 'Tariff card' without adding 'Service'.

**Comment by LiliaZakharko** [comment]
![Сервіси - опціональні](https://user-images.githubusercontent.com/128394400/235668747-c87c0b3b-6d1a-49a5-8758-68821a6c9298.png)
Green marked - mandatory;
Red marked - optional
