### ISSUE TITLE
[Create habit] System doesn't create new habit with image file

### ISSUE THREAD

**Issue by LiliaMokhnatska** [ita-social-projects/GreenCity#5732]
**Environment:** 11 Home, Google Chrome.
**Reproducible:** always.
**Build found:** 15.04.23

**Preconditions**

1. Registered User is logged in
2. 'Create habit' page is opened.

**Steps to reproduce**

1. Fill in all required fields.
2. Go to 'Picture' section and add new image
3. Click on 'Add habit' button.

**Actual result**
System doesn't create new habit after clicking on enabled 'Add habit' button on 'Create habit' page.

**Expected result**
System should disable 'Add habit' button.

**Comment by DanaIuich** [comment]
System doesn't create new habit after clicking on enabled 'Add habit' button on 'Create habit' page.

**Comment by Vadym840217** [comment]
Expected result sould be (for my opinion) : System creates new custom habit
