### ISSUE TITLE
[UBS Tariffs Page] The pop-up window doesn't contain the necessary UI controls when editing a service in the "Services" section

### ISSUE THREAD

**Issue by SolomiiaPryshliak** [ita-social-projects/GreenCity#5738]
**Environment:** Windows 11, Google Chrome 64
**Reproducible:** always

**Preconditions**
1. https://www.testgreencity.ga/ is opened
2. User is logged in as a Super Admin (email:[adminubs@starmaker.email](mailto:adminubs@starmaker.email); password: Test-User123).

**Steps to reproduce**
1. Go to the 'Тарифи' page.
2. Click on the pricing card on the main page “Тарифи”
3. Click on the “pencil” in the certain line of the editing service in “Сервіси” section

**Actual result**
The pop-up window "Редагувати послугу" is opened with fields: "Найменування послуги*" (name of the service in UA), "Найменування послуги*" (name of the service in EN), "Базова вартість*", "Опис послуги*" (service description in UA), "Опис послуги*" (service description in EN), "Скасувати" (cancel) Button, "Зберегти" (save) Button, "Дата", "Додано"

**Expected result**
The pop-up window “Редагувати сервіс” (Edit the service) is opened with fields: 
<html>
<body>

Field title | Field type | Condition | Prefilled text | Validation
-- | -- | -- | -- | --
“Найменування сервісу” (name of the service in UA) | Input field | Mandatory | The data from the tariff card | From minimum 1 to maximum 30 characters are allowed.
“Name of the service” | Input field | Mandatory | The data from the tariff card | From minimum 1 to maximum 30 characters are allowed.
“Об’єм, л” (volume, l) | Input field | Mandatory | The data from the tariff card | min.1 max 3 numeric characters
“Кур’єр, грн.” (courier, uah) | Input field | Mandatory | The data from the tariff card | min.3 max 8 numeric characters with decimal values
“Базова вартість” (base cost) | Input field | Mandatory | The data from the tariff card | min.3 max 8 numeric characters with decimal values
“Опис сервісу” (service description in UA) | Input field | Mandatory | The data from the tariff card | From minimum 1 to maximum 255 characters are allowed.
“Service description”’ | Input field | Mandatory | The data from the tariff card | From minimum 1 to maximum 255 characters are allowed.
“Скасувати” (cancel) | Button |   |   | Active by default.
“Зберегти” (save) | Button |   |   | Inactive by default. When the user change any of fields - the button becomes active
“Дата” (date) | Text | Mandatory |   | Current data in the format mmm_dd,yyy
“Додано:” (added) | Text | Mandatory |   | Name of logged Super Admin

</body>
</html>
**Test case link**
User story #4427

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:medium"), Type ("UI")

![Edit_servis](https://user-images.githubusercontent.com/128297635/236002740-a4818d47-2c8f-4dca-b2c9-828735d0db9f.jpg)

**Comment by katia9261** [comment]
It's not a bug
