### ISSUE TITLE
[Events] User can't get to "Create event" button using a TAB

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5744]
**Environment:** ALL
**Reproducible:** always
**Build found:** 27.04.2023

**Preconditions**

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/events
 2. Swith to 'Create event' button with 'TAB' button on keyboard

**Actual result**
"Create event" button can't be selected by TAB

**Expected result**
"Create Event" bttn  is selected 

**Postconditions**

**User story and test case links**
E.g.: "User story #3193 

**Labels to be added**

**Comment by DanaIuich** [comment]
pressing the space bar or enter button "Create event" does not respond and the "Create event" page does not appear

**Comment by NadiiaStoiko** [comment]
Hi!
This task was only about  using TAB for crete event.

*Actual result*
"Create event" button can't be selected by TAB

*Expected result*

"Create Event" bttn is selected.

Requirements for using the space bar or the enter button in the task were
not specified.

Maybe you need to add it to this task card.




пн, 29 мая 2023 г. в 13:23, DanaIuich ***@***.***>:
