### ISSUE TITLE
[UBS Tariffs page_Create pricing card] The field "Місто" is available for city selection only after filling the field "Область" 

### ISSUE THREAD

**Issue by RudnevaOlena** [ita-social-projects/GreenCity#5751]
**Environment:** Mac OS Ventura 13.2.1, browser Version 112.0.5615.137, it's version 06.05.2023.
**Reproducible:** always
**Build found:** 06.05.2023

**Preconditions**
1. The database must contain at least one region and city from the region existing in the database.
2. The User should be logged in as a Super Admin.

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/ubs;
2. Click on the "Тарифи" icon on the left sidebar;
3. Click on the tools "Gear" in the right corner;
4. Tap on the "Створити картку";
5.  Try to type 1 character in the field "Місто".
6. Click on the drop-down menu icon of the "Місто" field. 

**Actual result**
The field "Місто" is inactive for input. The "Місто" field cannot be accessed for typing or selecting the city from the drop-down list until the "Область" field has been completed.

**Expected result**
User can type a character in the field "Місто" or select a city from the drop-down list when any other fields of "Створити картку" are not filled.

**User story and test case links**
E.g.: "User story #4202

Attachment:
https://user-images.githubusercontent.com/128076020/236631086-40f2bdb2-315d-488d-9e5c-fc56bbb86fec.mp4

**Comment by katia9261** [comment]
It's not a bug
