### ISSUE TITLE
[Create event] "Log in" page is not opened and Unauthorized user can fill in all fields for create event

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5760]
**Environment:** All
**Reproducible:** always
**Build found:** 05/05/2023

**Preconditions**
User shouldn't be authorized

**Steps to reproduce**

1. Go to https://www.testgreencity.ga/#/events/create-event
2. Fill in all mandatory fields and click on "Publish" button

**Actual result**
After navigating to a URL the page " Create event" is opened and unauthorized user can fill in all fields.  

**Expected result**
"Log in" page is opened

**Postconditions**

**User story and test case links**
E.g.: "User story #3193 
[Test case]https://jira.softserve.academy/browse/GC-3133

**Labels to be added**

**Comment by NadiiaStoiko** [comment]
After push button " Create event" unauthorized user redirects to "Log in" page
