### ISSUE TITLE
[Events] The message after clicking "Join event" button doesn't appear

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5761]
**Environment:** All
**Reproducible:** always
**Build found:** 05/05/2023

**Preconditions**
The User should be logged in as an Authorized User.

**Steps to reproduce**

1. Go to https://www.testgreencity.ga/#/events
2. Click on the "Join event" button on the card of the open type event created by another User.

**Actual result**
There is no message after clicking on "Join event" button

**Expected result**
"You have successfully joined the event" message is displayed.

**User story and test case links**
E.g.: "User story #3193 
[Test case]https://jira.softserve.academy/browse/GC-3118

**Labels to be added**

**Comment by NadiiaStoiko** [comment]
"You have successfully joined the event" message is displayed.
