### ISSUE TITLE
[[Pricing page] In filed "область" No opportunity select other region

### ISSUE THREAD

**Issue by AndriiRadchenko** [ita-social-projects/GreenCity#5764]
**Environment:** Windows 10 Pro, Google Chrome
**Reproducible:** always
**Build found:** 07.05.2023

**Preconditions**
Log in as Super User.
Open https://www.testgreencity.ga/#/ubs-admin/tariffs

**Steps to reproduce**
1. In filed "область" select "Волиньська область"
2. Click on the drop-down list
3. Select "Житомирська область"

**Actual result**
In the drop-down list not displed other regions

**Expected result**
In the drop-down displed all regions

**User story and test case links**
E.g.: ["User story #100
](https://github.com/ita-social-projects/GreenCity/issues/4256)
[Test case][(https://jira.softserve.academy/browse/100](https://jira.softserve.academy/browse/GC-6461))"

[Video](https://monosnap.com/file/PC2yfRT1Y8AwNlZ2DMNPQPskDSuI8e)

**Comment by Vadym840217** [comment]
All regions are displayed
