### ISSUE TITLE
[UBS Tariffs page] Сlicking on the tariff card does not work on all parts of the tariff card

### ISSUE THREAD

**Issue by OksanaObukhovska** [ita-social-projects/GreenCity#5771]
Environment: OS Windows 10 x 64, Br Google Chrome ver. 110.0.5481.178. 
Reproducible: always
Build found: 06.05.2023
Preconditions
1.	User should be authorized as Admin
2.	Page 'Тарифи' opened
Steps to reproduce
1.	Click on any tariff card after “Кур’єр” field.
2.	Click on any tariff card before “Кур’єр” field.
Actual result
1. After clicking on the tariff card in the field after the courier value, the tariff page does not open. 
2. After clicking on the tariff card in the field after the courier value, the tariff page opens.
Expected result
After clicking on any part of the tariff card the tariff page opens.
User story and test case links
E.g.: "User story #4430

**Labels to be added**
Bug, Functional, Pri: medium, Sev: major, tariffs, UBS. Pricing

**Comment by DanaIuich** [comment]
Bug is fixed
