### ISSUE TITLE
[UBS Tariffs Page] The "редагувати послугу" inscriptions are instead of "редагувати сервіс" on the pop-up window when editing a service.

### ISSUE THREAD

**Issue by SolomiiaPryshliak** [ita-social-projects/GreenCity#5772]
**Environment:** Windows 11, Google Chrome 64
**Reproducible:** always

**Preconditions**
1. https://www.testgreencity.ga/ is opened
2. User is logged in as a Super Admin (email:[adminubs@starmaker.email](mailto:adminubs@starmaker.email); password: Test-User123).

**Steps to reproduce**
1. Go to the 'Тарифи' page.
2. Click on the pricing card on the main page “Тарифи”
3. Click on the “pencil” in the certain line of the editing service in “Сервіси” section

**Actual result**
The pop-up window "Редагувати послугу" is opened with fields: "Найменування послуги*" (name of the service in UA), "Найменування послуги*" (name of the service in EN), "Опис послуги*" (service description in UA), "Опис послуги*" (service description in EN)

**Expected result**
The pop-up window "Редагувати сервіс" is opened with fields: "Найменування сервісу*" (name of the service in UA), "Найменування сервісу*" (name of the service in EN), "Опис сервісу*" (service description in UA), "Опис сервісу*" (service description in EN)

**User story and test case links**
E.g.: "User story #4427

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:trival"), Type ("UI")
![GreenCity_service](https://user-images.githubusercontent.com/128297635/236951878-fe0131e2-41e1-4b63-a435-4ea5c239b801.png)

**Comment by DanaIuich** [comment]
Bug is fixed
