### ISSUE TITLE
[UBS Tariffs Page] The user can enter more than 8 numeric characters in the "Базова вартість" field.

### ISSUE THREAD

**Issue by SolomiiaPryshliak** [ita-social-projects/GreenCity#5773]
**Environment:** Windows 11, Google Chrome 64
**Reproducible:** always

**Preconditions**
1. https://www.testgreencity.ga/ is opened
2. User is logged in as a Super Admin (email:[adminubs@starmaker.email](mailto:adminubs@starmaker.email); password: Test-User123).

**Steps to reproduce**
1. Go to the 'Тарифи' page.
2. Click on the pricing card on the main page “Тарифи”
3. Click on the “pencil” in the certain line of the editing service in “Сервіси” section
4. Enter more than 8 numeric characters with decimal values

**Actual result**
The input field is highlighted in red only after entering 22 characters

**Expected result**
The input field is highlighted in red after entering more than 8 characters

**Postconditions**

**User story and test case links**
E.g.: "User story #4427

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:major"), Type ("Functional
![GreenCity_numbers](https://user-images.githubusercontent.com/128297635/236955476-ea311aeb-b8e8-4b04-9cd8-80de65c3c83c.png)
")

**Comment by Vadym840217** [comment]
Actual result
The input field is highlighted in red only after entering 22 characters - still actual
letter 'e' possible to enter in 'basic cost' field
