### ISSUE TITLE
[Preview news page] Incorrect displaying of long title and content

### ISSUE THREAD

**Issue by Nata-test** [ita-social-projects/GreenCity#578]
**Environment:**
Google Chrome Version 80.0.3987.163 (32-bit)
Windows 10 Pro (64 bit)

**Steps to reproduce:**
1. Sign in to the 'Green City' application as a registered user
2. Go to 'Create news' page
3. Enter more than 50 characters in a 'Title' field (e. g.: "qwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiop")
4. Enter more than 150 characters in a 'Content' field (e. g.: "qwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiop")
5. Click on 'Preview' button

**Actual result:**
Title and content are displayed each as a single-line text that extend beyond the viewing area
![Actual_result](https://user-images.githubusercontent.com/63057560/79383318-adaa3f80-7f6d-11ea-9ad2-b6b6bfd0f517.png)

**Expected result:**
Title and content should be displayed each as a multi-line text within the viewing area according to mock-up
![Expected_result](https://user-images.githubusercontent.com/63057560/79384542-bef44b80-7f6f-11ea-975a-660aec7a19f0.png)

**Reproducible:**
Always

**Comment by rsyvulko** [comment]
Verified.
