### ISSUE TITLE
[UBS Tariffs Page] Alignments between input fields and labels 'Сума замовлення' / 'Кількість пакетів' are not even

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#5784]
**Environment:** Windows 10 Pro x64 21H2, Google Chrome 113.0.5672.93.
**Reproducible:** always.
**Build found:** 13.05.2023

**Preconditions**

1. https://www.testgreencity.ga/#/ubs-admin/tariffs is opened
2. The User is signed in as a Super Admin
3. 'Tariffs' page is opened
4. There should be at least one pricing card in the list

**Steps to reproduce**
1. Click on any pricing card from the list
2. Scroll down to 'Ліміти замовлення'
3. Check alignments between input fields and labels 'Сума замовлення' / 'Кількість пакетів'

**Actual result**
Alignments between input fields and labels 'Сума замовлення' / 'Кількість пакетів' are not even.
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/c0662164-d0c3-4cb6-a1ee-08e9e09b533b)

**Expected result**
Alignments between input fields and labels 'Сума замовлення' / 'Кількість пакетів' are according to the mockup
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=19776%3A59280&t=eaaTkhSXk9j8vRVr-0
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/7ce2b6e7-5914-4e16-a05a-06d7be59b715)

**User story and test case links**
E.g.: "User story #4948 

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("UI").

**Comment by DanaIuich** [comment]
Bug is fixed
