### ISSUE TITLE
[Pricing cards] White screen when try go to page tariffs

### ISSUE THREAD

**Issue by AndriiRadchenko** [ita-social-projects/GreenCity#5785]
**Environment:** Windows 10 PRO, Google Chrome
**Reproducible:** always
**Build found:** 14.05.2023

**Preconditions**
Not Log in as super admin

**Steps to reproduce**
1. Go to (https://www.testgreencity.ga/#/ubs-admin/tariffs)

**Actual result**
White screen and no message error 

**Expected result**
Redirect to Log in form and error message "forbidden"

**User story and test case links**
E.g.: "[User story #4256](https://github.com/ita-social-projects/GreenCity/issues/4256)
[Test case](https://jira.softserve.academy/browse/GC-6450)"

[Video ](https://monosnap.com/file/EW9CRq8UtfEt8CqDfvCATML2QPWFnL)

**Comment by katia9261** [comment]
It is not a bug
_Credentials_: 
adminubs@starmaker.email
Test-User123
![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/39ef06d6-0c56-46af-8b1a-98926e76ec92)

**Comment by AndriiRadchenko** [comment]
If I not log in , not anything error message, or redirect to login form. It's okey ?
