### ISSUE TITLE
[Pricing cards] Not displayed cross in fields filters

### ISSUE THREAD

**Issue by AndriiRadchenko** [ita-social-projects/GreenCity#5786]
**Environment:** Windows 10 Pro Google Chrome
**Reproducible:** always
**Build found:** 14.05.2023

**Preconditions**
The user is authorized as a Super Admin.
https://www.testgreencity.ga/#/ubs-admin/tariffs is opened.
UA location is selected.

**Steps to reproduce**
1. Check filters fields

**Actual result**
Only filter "Область" have cross 

**Expected result**
All filters have cross

![image](https://github.com/ita-social-projects/GreenCity/assets/107478119/e69c59c3-4a2e-4923-b840-f64a40958e17)

**Comment by Vadym840217** [comment]
All needed crosses were added
