### ISSUE TITLE
[Pricing Cards Filters]  The color of the selected filter is similar to the color of the tooltip

### ISSUE THREAD

**Issue by AndriiRadchenko** [ita-social-projects/GreenCity#5789]
**Environment:** Windows 10 Pro Google Chrome
**Reproducible:** Always
**Build found:** 14.05.2023

**Preconditions**
The user is authorized as a Super Admin.
https://www.testgreencity.ga/#/ubs-admin/tariffs is opened.
UA location is selected.
There is at least one pricing card on the list.

**Steps to reproduce**
1. Select "Київська область" in the field "Область"

**Actual result**
The colour of the selected filter is similar to the colour of the tooltip

**Expected result**
The colour of the selected filter must be according to the layout #1D2830 

![image](https://github.com/ita-social-projects/GreenCity/assets/107478119/3144abfd-c5f2-46d1-9ed1-14e352f82f87)

Mocap - https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?type=design&node-id=20043-60493&t=V8X2cMpzWNAYXVkW-0

**Comment by DanaIuich** [comment]
Bug is fixed
