### ISSUE TITLE
['Eco News' page]Create News: Publish functionality #526

### ISSUE THREAD

**Issue by OksanaFedor** [ita-social-projects/GreenCity#579]
Steps to reproduce:
1.Go to https://ita-social-projects.github.io/GreenCityClient/#/news
2.Go to Eco News page
3.Click "Create news" button
4.Enter news
5.Click "Publish" button
Actual result:
"Publish" button does not work
Expected result:
User is able to post news using "Publish" button
Environment:
Windows 10 Enterprise LTSC, Chrome 80.0.3987.132
![10](https://user-images.githubusercontent.com/63067646/79437380-c735a080-7fda-11ea-96da-cf819c109c53.png)

**Comment by nabermi2020** [comment]
Not relevant
