### ISSUE TITLE
[Events/Organizer Rating] The UI of "Rate Organizer" dialog window does not correspond to the mockup

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#5794]
**Environment:** Windows 10 Pro x64 21H2, Google Chrome 113.0.5672.93.
**Reproducible:** always.
**Build found:** 16.05.2023

**Preconditions**

1. https://www.testgreencity.ga/#/greenCity is opened
2. The user is authorized
3. There is at least one attended event

**Steps to reproduce**

1. Go to 'My space' tab
2. Go to 'My Events' tab
3. Find attended event
4. Click on 'Rate Organizer' button

**Actual result**
The color of the inactive 'Save' button is #839c94, the distance between stars and buttons is wider. 
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/b65a4a58-3397-4de7-8157-c24b5db7921d)

**Expected result**
The color of inactive 'Save' button is Primary/04. Light-Green #B3E5C9; the distance between stars and buttons is according to the mockup.
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/33d8b93d-e06c-400f-9c0d-ae0e0f337705)

**User story and test case links**
E.g.: "User story #3268 
Test Case [GC-8767](https://jira.softserve.academy/browse/GC-8767)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type ("UI").

**Comment by DanaIuich** [comment]
Bug is fixed

**Comment by OliaProtyniak** [comment]
> Bug is fixed

The distance between stars and buttons is wider.

![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/907c6df2-62c4-4aea-9745-600e0b9878d0)
