### ISSUE TITLE
[UBS Tariffs Page] Input field 'Інформація про ліміти замовлення' does not display allowed 255 characters for input

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#5795]
**Environment:** Windows 10 Pro x64 21H2, Google Chrome 113.0.5672.93.
**Reproducible:** always.
**Build found:** 16.05.2023

**Preconditions**

1. https://www.testgreencity.ga/#/ubs-admin/tariffs is opened
2. The User is signed in as a Super Admin
3. 'Tariffs' page is opened
4. Any pricing card is opened

**Steps to reproduce**
1. Type 255 characters in the 'Інформація про ліміти замовлення' input field 
Test data: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisis velit quis mi tristique, vitae lacinia tortor feugiat. Nunc iaculis dui eget nulla efficitur fringilla. Sed ac finibus arcu. Integer malesuada urna atmale 12334567,!"§$%&&/()=?`"tell

**Actual result**
Only 170 characters are displayed and allowed by input field.
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/6904d427-01f9-4a50-83b0-7c474378d3bc)

**Expected result**
255 characters are displayed in the input field.

**User story and test case links**
E.g.: "User story #4948 

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("UI, "Functional").

**Comment by Vadym840217** [comment]
255 ok
