### ISSUE TITLE
[UBS Tariffs Page] Names of fields in 'Сервіси' do not match mockup

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#5799]
**Environment:** Windows 10 Pro x64 21H2, Google Chrome 113.0.5672.93.
**Reproducible:** always.
**Build found:** 16.05.2023

**Preconditions**

1. https://www.testgreencity.ga/#/ubs-admin/tariffs is opened
2. The User is signed in as a Super Admin
3. 'Tariffs' page is opened
4. Any pricing card is opened

**Steps to reproduce**
Pay attendion to names of the fields in 'Сервіси'.

**Actual result**
'Найменування послуги', 'Опис послуги', 'Базова вартість' are displayed.
![Screenshot 2023-05-16 170733](https://github.com/ita-social-projects/GreenCity/assets/128295227/9ede8038-bd99-47a2-b5ae-e7166eea6603)

**Expected result**
'Найменування сервісу', 'Опис сервісу', 'Базова вартість' are displayed.

**User story and test case links**
E.g.: "User story #4948 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: minor"), Type ("UI").

**Comment by Vadym840217** [comment]
according to mockup
