### ISSUE TITLE
[UBS Tariffs Page] 

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#5800]
**Environment:** Windows 10 Pro x64 21H2, Google Chrome 113.0.5672.93.
**Reproducible:** always.
**Build found:** 16.05.2023

**Preconditions**

1. https://www.testgreencity.ga/#/ubs-admin/tariffs is opened
2. The User is signed in as a Super Admin
3. 'Tariffs' page is opened
4. There should be at least one pricing card in the list

**Steps to reproduce**
1. Click on any pricing card from the list
2. Make changes in any active input field (e.g. in 'Інформація про ліміти замовлення')
3. Press 'Зберегти зміни' button

**Actual result**
User stays on this pricing card, the changes entered by user are erased.

https://github.com/ita-social-projects/GreenCity/assets/128295227/695743d5-1083-4db0-b1f2-39f695bdc15a

**Expected result**
The tariffs card is saved and the user sees the previous page "Тарифи” view.

**User story and test case links**
E.g.: "User story #4948 
**Labels to be added**
"Bug", Priority ("pri: hign"), Severity ("severity: major"), Type ("UI, "Functional").

**Comment by DanaIuich** [comment]
Bug is fixed
