### ISSUE TITLE
'Title' field is not changed automatically by switching languages

### ISSUE THREAD

**Issue by ViraPryshlyak** [ita-social-projects/GreenCity#581]
'Title' field is not changed automatically after creating and previewing created news by switching different languages.
![505-2](https://user-images.githubusercontent.com/63067658/79448350-f1428f00-7fe9-11ea-9b3e-4fa9133276df.png)

**Expected result:** 'Title' field is changed automatically after creating and previewing created news by switching different languages.

**Comment by nabermi2020** [comment]
Not relevant
