### ISSUE TITLE
[Events.Organizer Rating] The modal window with message ‘Rating sent’ is not shown on the 'Events' page after clicking on the rating mark

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#5814]
**Environment:** Windows 10 x64, Google Chrome 111.0.5563.147
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
1. The user must be registered in the WEB-site: https://www.greencity.social/#/ubs
2. The user joined at least one event. 
3. Go to https://www.greencity.social/#/greenCity

**Steps to reproduce**
1. Click on the "Events" tab.
2. Find "Event" which user attended previously.
3. Click on the "Rate Organizer" button.

**Actual result**
The modal window with message ‘Rating sent’ is not shown on the 'Events' page after clicking on the rating mark

**Expected result**
The modal window with message ‘Rating sent’ is displayed on the 'Events' page after clicking on the rating mark

**User story and test case links**
E.g.: "User story #3268 
[Test case](https://jira.softserve.academy/browse/GC-3940)"

![bug report 6](https://github.com/ita-social-projects/GreenCity/assets/130749567/77f4f657-eefb-4803-8f39-634586e30502)

https://github.com/ita-social-projects/GreenCity/assets/130749567/24dbcc0d-e868-4e8e-a2ec-7e96a966e781

**Comment by KKatiaa** [comment]
It is done already

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
