### ISSUE TITLE
[Pricing page] Not displayed message when the card is not found

### ISSUE THREAD

**Issue by AndriiRadchenko** [ita-social-projects/GreenCity#5822]
**Environment:** Windows 10 Pro, Google Chrome 
**Reproducible:** always
**Build found:** 20.05.2023

**Preconditions**
Log in as Super User.
Open https://www.testgreencity.ga/#/ubs-admin/tariffs
Sorting by status "Всі"

**Steps to reproduce**
1. Select the filter "Київ" in the field "Місто"
2. Select the filter "ЛЗ Тест1" in the field "Кур'єр" 

**Actual result**

The results field is empty, there is no message that there is no card
![image](https://github.com/ita-social-projects/GreenCity/assets/107478119/81e9ad61-4797-4b73-93bf-5ec9ab0273a9)

**Expected result**
A message that there is no card and a button to create a new card is displayed.
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?type=design&node-id=25206-85874&t=2QaYJtrS5sc3IKt8-0

**User story and test case links**
E.g.: [User story 4256](https://github.com/ita-social-projects/GreenCity/issues/4256)

**Comment by DanaIuich** [comment]
The results field is empty, there is no message that there is no card
