### ISSUE TITLE
[Pick up city UBS.Admin Cabinet] Admin doesn't see used bonuses in the "Planned amount" and "Confirmed amount" columns of the "Order details" section when he/she cancels the order in the order form

### ISSUE THREAD

**Issue by Iryna1972** [ita-social-projects/GreenCity#5823]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 113.0.5672.127 (64-bit).
**Reproducible:** always
**Build found:** 21/05/23

**Preconditions**
1. User is logged in as administrator.
2. Orders tab is opened.
3. At least 1 order with the status “Formed” and paid with bonuses is in the orders table.

**Steps to reproduce**

1. Click on particular order with the status “Formed”.
2. Click on the "Order detals" menu.
3. Pay attention to the "Used bonuses" field in the "Planned amount" column.
4. Pay attention to the "Used bonuses" field in the "Confirmed amount" column.
5. Click on the dropdown "Order status".
6. Click on the status "Canceled".
7. Click on any radio button
e.g. Moving
8. Click on the button "Add".
9. Click on the "Save" button.
10. Pay attention to the "Used bonuses" field in the "Planned amount" column.
11. Pay attention to the "Used bonuses" field in the "Confirmed amount" column.

**Actual result**

Admin sees the “0.00” in the "Used bonuses" field in the "Planned amount" and "Confirmed amount" columns of the "Order details" on stage “Скасованo”. 

https://github.com/ita-social-projects/GreenCity/assets/119864646/9293259a-5731-477a-ae93-e4a13a6fb8bf

**Expected result**
Admin should see the used bonuses in the "Used bonuses" field in the "Planned amount" and "Confirmed amount" columns of the "Order details" on stage “Скасованo”. 

**User story and test case links**
User story #5520 

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Trivial"), Type ("Functional").

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS.Admin Cabinet.
