### ISSUE TITLE
[Friends] - Find friends - user see already friend on find friends page

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5828]
**Environment:** Windows 10 Pro, Google Chrome 111.0.5563.65
**Reproducible:** always
**Build found:** 22.05.2023

**Preconditions**
User is authorized
User has at least one friend

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/
2. Click on "My space"
3. My friends column - Click on "See all"
4. Click on "Find friends"

**Actual result**
User see users that is already his/her friends
Method **GET/user/{userId}/findAll/friendsWithoutExist/**
![image](https://github.com/ita-social-projects/GreenCity/assets/104850911/e3fc182d-1384-4987-ad26-e4dcc849c99d)
![image](https://github.com/ita-social-projects/GreenCity/assets/104850911/2ff6745e-d493-44f1-80c8-c6367df3c301)

**Expected result**
User see users that are not his/her friends and user that he/she doesn't send friend request

**Comment by DanaIuich** [comment]
Bug is fixed
