### ISSUE TITLE
[Create news page] 'Publish' button is enabled when no tag is selected while creating a news item #505

### ISSUE THREAD

**Issue by OlenaBachynska** [ita-social-projects/GreenCity#583]
#505 
 **Steps to reproduce:**

1. Go to 'Eco news' page ( https://ita-social-projects.github.io/GreenCityClient/#/news).
2. Click on 'Create news' button.
3. Enter valid data into the 'Title' field (no more than 170 characters: capital and lower case letters/ numbers/ special characters) (e. g.: "Be eco! Be cool!").
4. Enter valid data into the 'Content' field (no less than 20 characters: capital and lower case letters/ numbers/ special characters) (e. g.: "It's so healthy, fun and cool to bring eco habits in everyday life").

**Actual result:**

'Publish' button is enabled.

**Expected result:**

'Publish' button should be disabled.

!['Publish' button is enabled when no tag is selected](https://user-images.githubusercontent.com/63067689/79452808-69f91980-7ff1-11ea-9407-fe70ed0c6e9a.png)

**Comment by rsyvulko** [comment]
Verified
