### ISSUE TITLE
[Friends] MyFriends section, friends are not shown properly

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5832]
Environment: Windows 10, Chroome Version 111.0.5563.65
Reproducible: always
Build found: 22.05.2023

**Preconditions**

1. The registered user is logged in
2. My profile page is open
3. User has at least 2 friends

**Steps to reproduce**
1. Pay attention to MyFriends section

**Actual result**
Friends are displayed vertically
![friends_incorrect_display](https://github.com/ita-social-projects/GreenCity/assets/109086383/2dceb36b-2a13-4066-af52-fb1faad0bb2a)

**Expected result**
Friends are displayed according to mockup 
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=12201-3&t=Z5yFf6Bk5fSetiBZ-0
![image](https://github.com/ita-social-projects/GreenCity/assets/109086383/8b993e22-5c54-49a0-8f31-4e8e253e2590)

**User story and test case links**
User story #1002

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Vadym840217** [comment]
Fixed
