### ISSUE TITLE
[Friends] - Requests tab - friend's card don't match mockup

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5833]
**Environment:** Windows 10 Pro, Google Chrome 111.0.5563.65
**Reproducible:** always
**Build found:** 22.05.2023

**Preconditions**
User is authorized
User has at least 2 friends

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/
2. Click on "My space"
3. My friend's column - Click on "See all"
4. Click on "Requests"

**Actual result**
Friend's card don't match mockup
![image](https://github.com/ita-social-projects/GreenCity/assets/104850911/36f35b80-70b2-4482-97a6-e332d6526c71)

**Expected result**
Friend's card match mockup
![image](https://github.com/ita-social-projects/GreenCity/assets/104850911/f4e16aa3-be97-4404-8a85-c696c78cb464)

**Comment by Vadym840217** [comment]
"Requests" is accepted like feature
