### ISSUE TITLE
[UBS Tariffs page_Create pricing card] A pricing card doesn't create after changing the "Станція приймання" field when before the validation message about the necessity to do changing to save the card was displayed

### ISSUE THREAD

**Issue by RudnevaOlena** [ita-social-projects/GreenCity#5834]
**Environment:** Mac OS Ventura 13.3.1, browser Version 113.0.5672.63 (Official Build) (arm64), it's version 22.05.2023.
**Reproducible:** always.
**Build found:** 22.05.2023.

**Preconditions**
1. The User should be logged in as a Super Admin.
2. At least one blank pricing card must be in DB (i.e. pricing card with the next fields: the "Область" field ="Харківська область", the "Місто" field ="Харків", the "Кур'єр" field ="Швидкий", the "Станція приймання" field ="Ринок").
3. The pop-up window "Створити картку" is opened (Go to https://www.testgreencity.ga/#/ubs. - > Main UBS menu - > Choose "Тарифи" - > tools pictogram "Gear" - >Choose the option "Створити картку").

**Steps to reproduce**

1. Select from the drop-down list of the field "Кур'єр" the same value as an existing card (i.e. the value "Швидкий");
2. Select from the drop-down list of the field "Станція приймання" the same value as an existing card (i.e. the value "Ринок");
3. Select from the drop-down list of the field "Область" the same value as an existing card (i.e. the value "Харківська область");
4. Select from the drop-down list of the field "Місто" the same value as an existing card (i.e. the value "Харків");
5. Click on the "Створити" button;
6. Click on the delete icon near the text selected receiving station (i.e. "Ринок");
7.  Select from the drop-down list of the field "Станція приймання" the other value (i.e. "Деміївська");
8. Click on the "Створити" button.

**Actual result**
The validation message is displayed when creating a pricing card after selecting another value of receiving station to make the card different from the existing one. So it's not possible to create a new card with changes. (For changes with fields "Кур'єр" or "Місто" - the creation function of a new pricing card works as expected).

https://github.com/ita-social-projects/GreenCity/assets/128076020/a34f3b10-cb31-42e3-a0a7-69dca413c427

**Expected result**
The window that duplicates all selected fields appears without any message, so a card with changes is available for creation as a new pricing card.

**User story and test case links**
E.g.: "User story #4202

**Comment by juseti** [comment]
To create a tariff, the courier and the location are unique, not the receiving station.
