### ISSUE TITLE
[Pick up city UBS.Pricing page.Admin cabinet] Filtering for tariffs does not work after deactivation

### ISSUE THREAD

**Issue by katia9261** [ita-social-projects/GreenCity#5836]
**Environment:** Windows 10 Pro v.21H2, Google Chrome 113.0.5672.127 (64-bit).
**Reproducible:** always
**Build found:** 22/05/23

**Preconditions**
1. User is logged in as an administrator.
2. Tariffs tab is opened.

**Steps to reproduce**
1. Click on Deactivate tariff
2. Try to change filtration conditions (e.g. to state `INACTIVE`)

**Actual result**
The tariffs aren't changed and filters were not applied

https://github.com/ita-social-projects/GreenCity/assets/101433204/0f36abcb-0b9f-460a-b06c-a9208bd7c913

**Expected result**
Tariffs that match these filters are displayed

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick up city UBS
