### ISSUE TITLE
[Pick up city UBS-User.Edit Profile] User can not add address: City, Street no dropdowns; House number is not saved

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5837]
Environment: Windows 10, Chroome Version 111.0.5563.65
Reproducible: always
Build found: 23.05.2023

**Preconditions**

1. Go to https://www.pick-up.city/#/ubs
2. Sign in as a User
3. Click on the User profile and choose 'UBS-user'
4. There is no address added

**Steps to reproduce**

1. Go to 'Дані користувача' menu
2. Click on 'Редагувати дані'
3. Scroll down to 'Адреса' block
5. Click on 'Додати нову адресу' bttn

**Actual result**
1. City field: there is no dropdown with cities available
2. Street field: there is no suggested streets dropdown
3. House field: house number can not be saved, the field stays empty and is highlighted in red

https://github.com/ita-social-projects/GreenCity/assets/109086383/65a6031a-076b-45f0-9fee-353aa0091950

**Expected result**
1. City field: there is a dropdown with cities available
2. Street field: there is suggested streets dropdown
3. House field: house number is saved after entering

![street_drop](https://github.com/ita-social-projects/GreenCity/assets/109086383/ccd6eebc-d0f4-44f3-b296-7ec551c5dc5d)
![city_dropd](https://github.com/ita-social-projects/GreenCity/assets/109086383/675f24c7-3cff-4e49-876b-dec03a41c00b)

**User story and test case links**
User story #3811

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by atsa21** [comment]
That is a problem on Google console, so it can't be fixed from UI or backend - need to wait that client will fix it

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed
