### ISSUE TITLE
[Create news page] 'Publish' button is enabled when space is entered into 'Title' field while creating a news item #505

### ISSUE THREAD

**Issue by OlenaBachynska** [ita-social-projects/GreenCity#584]
#505 
**Steps to reproduce:**

1. Go to 'Eco news' page ( https://ita-social-projects.github.io/GreenCityClient/#/news).
2. Click on 'Create news' button.
3. Choose one or more of the proposed tags (e. g.: "Events").
4. Enter valid data into the 'Content' field (no less than 20 characters: capital and lower case letters/ numbers/ special characters) (e. g.: "It's so healthy, fun and cool to bring eco habits in everyday life").
5. Enter a space into a 'Title' field.

**Actual result:**

'Publish' button is enabled.

**Expected result:**

'Publish' button should be disabled.

!['Publish' button is enabled when space is entered into 'Title' field](https://user-images.githubusercontent.com/63067689/79456353-0a057180-7ff7-11ea-83f4-649214f54f98.png)

**Comment by rsyvulko** [comment]
Verified
