### ISSUE TITLE
[All habits] Filters are not clickable via enter.

### ISSUE THREAD

**Issue by OksanaObukhovska** [ita-social-projects/GreenCity#5849]
**Environment:** OS Windows 10 x 64, Br Google Chrome ver. 110.0.5481.178.
**Reproducible:** always.

**Preconditions:**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. Log in as an authorized user.
3. The "All habits"' page is open.

**Steps to reproduce:**

Go through the elements of the page using the tab.
Press enter after achieving the "Filter by", "Testing", "Reusable", "Resource Saving", "Smart Consuming", "Transportation", and "Recycling/Waste Sorting" buttons.

**Actual result:** 

After achieving the buttons "Filter by", "Testing", "Reusable", "Resource Saving", "Smart Consuming", "Transportation", and "Recycling/Waste Sorting" by tab, they are not clickable by enter.

**Expected result:**

After achieving the buttons "Filter by", "Testing", "Reusable", "Resource Saving", "Smart Consuming", "Transportation", and "Recycling/Waste Sorting" by tab, they are clickable by enter.

**E.g.**: "User story #1000
[Test case](https://jira.softserve.academy/browse/GC-6313)"

**Labels to be added**
Accessibility, All habits. Gallery view, All Habits. List view, All habits, Bug, Functional, Pri: high, Sev: major.

**Comment by atsa21** [comment]
Not reproduce -  check link https://www.testgreencity.ga/#/profile/12/allhabits

**Comment by ghost** [comment]
Bug is still reproduced: The filter by selected item is not shown on the 'All habits' page after clicking the Enter button on keyboard
