### ISSUE TITLE
[UBS Tariffs Page] Tariff details page wrong buttons and field alignment

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5851]
Environment: Windows 10, Chroome Version 111.0.5563.65
Reproducible: always
Build found: 25.05.2023

**Preconditions**
The user should be authorized as Admin
Main UBS menu -> page 'Тарифи' should be opened

**Steps to reproduce**
1. Click on any tariff available
2. Pay attension to the Add service and Add tariff buttons
3. Pay attention to the Services and Tariffs for services tables

**Actual result**
1. UA localization: - different '' and '' buttons' size
                             - different 'Базова вартість' and 'Повна вартість' fields size
2. EN localization: - different 'Add service' and 'Add tariff' buttons' size
           
![add_add_button](https://github.com/ita-social-projects/GreenCity/assets/109086383/1a4893f5-ee97-4f70-9ecd-36d167c6bc58)

 
           
![add_button_cost_UA](https://github.com/ita-social-projects/GreenCity/assets/109086383/b9bb38e9-92d2-4ce4-94d6-7d74d916644a)

**Expected result**
1. UA localization: - the same buttons size
                             - the same fields size
2. EN localization: - the same buttons size
                             

**User story and test case links**
User story #4429

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by katia9261** [comment]
The buttons appearance are Ok according to mock-up
