### ISSUE TITLE
[All habits] The picture on the habit card disappears when expanding the screen 576p and below and zooming 200% on the list view.

### ISSUE THREAD

**Issue by OksanaObukhovska** [ita-social-projects/GreenCity#5852]
**Environment:** OS Windows 10 x 64, Br Google Chrome ver. 110.0.5481.178.
**Reproducible**: always.

**Preconditions:**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. Log in as an authorized user.
3. The "All habits"' page is open.

**Steps to reproduce:**

1. Choose the list view.
2. Choose to expand the screen to 576p.
3. Choose to expand the screen to 320p.
4. Zooming the page to 200%.

**Actual result:** 

There is no image on the habit card when the screen is expanded to 576p, 320p, and zooming 200%.

**Expected result:**

There is an image on the habit card when the screen is expanded to 576p, 320p, and zooming 200%.

**E.g.:** "User story https://github.com/ita-social-projects/GreenCity/issues/1000
[Test case] (https://jira.softserve.academy/browse/GC-6313)"

**Labels to be added**
 All Habits. List view, All habits, Bug, Pri: medium, Sev: minor, UI.
![576](https://github.com/ita-social-projects/GreenCity/assets/127955359/cb55fbd7-0447-41e9-b4cc-3ff68a5ae8bd)
![320](https://github.com/ita-social-projects/GreenCity/assets/127955359/db3a19a2-c4bc-4e25-b906-7a7881831fd8)
![200%](https://github.com/ita-social-projects/GreenCity/assets/127955359/fb57dd2c-20c1-471d-9bbe-300199946c8c)

**Comment by atsa21** [comment]
There is no image on the habit card when the screen is expanded to 576p - not a bug, it is the same as on Eco news 576 view
![image](https://github.com/ita-social-projects/GreenCity/assets/104850911/da25c579-b070-468f-b83a-e72fd2adba7a)
On screen 320p and zooming 200% - not reproduce
