### ISSUE TITLE
[Habit's page] "Add habit" button doesn't work.

### ISSUE THREAD

**Issue by OksanaObukhovska** [ita-social-projects/GreenCity#5853]
**Environment:** OS Windows 10 x 64, Br Google Chrome ver. 110.0.5481.178.
**Reproducible:** always.

**Preconditions:**

1. Go to https://www.testgreencity.ga/GreenCityClient/#/
2. Log in as an authorized user.
3. The "All habits"' page is open.

**Steps to reproduce:**

1. Click on the button "More" on the habit's card which hasn't been added to the habits in progress.
2. Click on the button "Add habit".

**Actual result:** 

The button "Add habit" doesn't work. The page remains "Habit's page". A new habit doesn't add.

**Expected result:**

1. 'My habits' page is opened
2. Chosen habit is displayed as the first item on the progress habit list
3. The notification with the information: 'You have successfully added a new habit to your list' appears.

**E.g.:** "User story https://github.com/ita-social-projects/GreenCity/issues/1000
[Test case] (https://jira.softserve.academy/browse/GC-6330)"

**Labels to be added**
Add new habit, Bug, Functional, Habit's page, Pri: medium, Sev: major].
![Add Habit](https://github.com/ita-social-projects/GreenCity/assets/127955359/e0afb1ab-5d34-47c6-a209-7a220024eaf0)

**Comment by atsa21** [comment]
Not reproduce - check url - https://www.testgreencity.ga/#/profile/12/allhabits/addhabit/2

**Comment by ghost** [comment]
Bug is reproduced. Actual result: The new habit is not added on the 'Habit info' page after clicking the 'Add habit' button
