### ISSUE TITLE
[Order form] The system notification message is appeared on the UBS Courier page after adding the new garbage collection address

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#5858]
**Environment:** Windows 10 x64, Google Chrome 113.0.5672.93
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
1. Login to GreenCity as a User https://www.testgreencity.ga/#/ubs
2. UBS Courier form is opened.
3. All required fields on the tab "Деталі замовлення" are filled in and the tab "Особисті дані" is active .

**Steps to reproduce**

1. Click on the “Add address” button.
2. Fill in all required address fields.
3. Click on the 'Add address' button.

**Actual result**
The system notification message is appeared on the UBS Courier page after adding the new garbage collection address

**Expected result**
The 'Address is successfully added' notification message is appeared on the UBS Courier page after adding the new garbage collection address

**User story and test case links**
E.g.: "User story #2199 
![bug retest](https://github.com/ita-social-projects/GreenCity/assets/130749567/2549f171-362a-4ff1-81be-5f182617d0b4)

**Comment by ShyraiDan** [comment]
Can't reproduce

**Comment by snezhanapravdyuk** [comment]
Address is not added
![изображение](https://github.com/ita-social-projects/GreenCity/assets/165433958/cde1354c-d75f-47a1-ad6f-727fa037d486)

**Comment by bzhn** [comment]
Can't reproduce.

![image](https://github.com/user-attachments/assets/624bce39-cfdf-4c9b-b676-75b770764a70)
