### ISSUE TITLE
[UBS User] User data - it is possible to add not existing house number

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5859]
**Environment:** Windows 10 Pro, Google Chrome 111.0.5563.65
**Reproducible:** always
**Build found:** 29.05.2023

**Preconditions**
User is authorized

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/ubs
2. Click on "user icon"
3. Click on "UBS-USER"
4. Click on "User data"
5. Click on "Edit data"

**Actual result**
After entering and select City: "Kyiv", Street:"Kyivska Street", House: 1 and click outside - user can save this data

**Expected result**
User will select houseNumber and after it is possible to click "Add Address"

**Comment by DanaIuich** [comment]
Bug is fixed
