### ISSUE TITLE
[Event Dashboard] The header elements are not matched to Events page mockup

### ISSUE THREAD

**Issue by ghost** [ita-social-projects/GreenCity#5860]
**Environment:** Windows 10 x64, Google Chrome 113.0.5672.127
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Steps to reproduce**
1. Go to https://www.greencity.social/#/greenCity
2. Open the 'Event' dashboard
3. Open the mockup: https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=30511-114493
4. Check that the header is matched to header in mockup

**Actual result**
The header elements are not matched to Events page mockup

**Expected result**
The header elements are displayed according to Events page mockup

![header of Events page is not matched to mockup](https://github.com/ita-social-projects/GreenCity/assets/130749567/0cd34aa5-5b13-4224-bf53-2cac90800c55)

**Comment by sobkiv** [comment]
cannot reproduce
