### ISSUE TITLE
[UBS Admin] Order table - order - it is possible to add not existing house number

### ISSUE THREAD

**Issue by atsa21** [ita-social-projects/GreenCity#5862]
**Environment:** Windows 10 Pro, Google Chrome 111.0.5563.65
**Reproducible:** always
**Build found:** 29.05.2023

**Preconditions**
User is authorized as admin

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/ubs
2. Click on "UBS-ADMIN"
3. Click on "orders"
4. Click on any NOT Canceled order card number
5. Click on "Waste export address"

**Actual result**
After entering and select City: "Kyiv", Street:"Kyivska Street", House: 1 admin can see that "Save" button is not disabled

**Expected result**
Admin will select houseNumber and after it is possible to click "Save"

**Comment by DanaIuich** [comment]
Bug is fixed
