### ISSUE TITLE
[UBS Admin.Orders tab.Table.] Admin can set one of three values: 'Time of export,' 'Date of export,' or 'Receiving station,' even if the other two values are empty

### ISSUE THREAD

**Issue by AlexW8719** [ita-social-projects/GreenCity#5866]
**Environment:** Windows 10
**Reproducible:** always
**Build found:** 29.05.2023

**Preconditions**
Admin is logged in.
Go to https://www.testgreencity.ga/#/ubs-admin/orders

**Steps to reproduce**
1. Go to 'ubs-admin' tab 
2. Click on the filter and select 'Order status' with the value 'Formed'
3. Find in the table orders with empty values in three columns: 'Time of export,' 'Date of export,' and 'Receiving station'.
4. Set any value in one of the three cells.

**Actual result**
You can set a value in any of the three columns: 'Time of export,' 'Date of export,' or 'Receiving station,' while leaving the other two empty.

**Expected result**
You can set a value in any of the three columns: 'Time of export,' 'Date of export,' and 'Receiving station,' while leaving the other two empty.

**Comment by Maksym8Kravchenko** [comment]
According to the Change request
https://github.com/ita-social-projects/GreenCity/issues/3300
The functionality of filtering has no option to filter by 'Time of export'

**Comment by Maksym8Kravchenko** [comment]
You can set a value in 'Date of export while leaving the other two fields of the 'Data range empty.

https://github.com/ita-social-projects/GreenCity/assets/127987815/d78428bb-f04d-4fbb-9e5a-4e0d9e6b7ae9
