### ISSUE TITLE
[UBS Tariffs Page] Courier can NOT be changed when Editing pricing card 

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5867]
**Environment:** Windows 10, Chroome Version 111.0.5563.65
**Reproducible:** always
**Build found:** 30.05.2023

**Preconditions**

1. The user should be authorized as Admin
2. Main UBS menu -> page 'Тарифи' should be opened

**Steps to reproduce**
1. Click on any tariff card available
2. Click on three dots sign and choose edit
4. Edit card pop-up window is opened
5. Select courier from the dropdown list
6. Click on 'Edit' button

**Actual result**
Courier can not be selected and saved from the dropdown options

**Expected result**
Courier can be changed; should be selected and saved from the dropdown options

![image](https://github.com/ita-social-projects/GreenCity/assets/109086383/2037aa19-de4b-4fee-b5b2-357b0a237d41)

**User story and test case links**
User story #3860

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by DanaIuich** [comment]
Bug is fixed
