### ISSUE TITLE
[Edit event] After clicking on "Preview" button "Preview" page does not open

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5873]
**Environment:** All
**Reproducible:** always
**Build found:** 31/05/2023

**Preconditions**

1. Website: https://www.greencity.social/#/events is opened
2. User is authorized
3. Event shoud be created

**Steps to reproduce**

1. Click on 'Edit event'
2. Change information in mandatory fields
3. Click on "Preview" button

**Actual result**
The 'Preview" button is not active

**Expected result**
"Preview" page with all entered Event information appeared

**Postconditions**

**User story and test case links**
E.g.: "User story #3195 
[Test case]https://jira.softserve.academy/browse/GC-3132

**Labels to be added**

**Comment by sobkiv** [comment]
cannot reproduce
