### ISSUE TITLE
[UBS_Prod. Client. Sign in] Incorrect message is displayed on EN/UA localization when user typed password more than 20 symbols on the pop-up 'Sign in''

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5882]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 06.01.23

**Preconditions**
Go to the https://www.pick-up.city/

**Steps to reproduce**

1. Set UA localization of the main page 'Pick-up'
2. Click 'Sign in' button
3. Type a password in the field 'Password', that contains more than 20 symbols (e.g. aaaaaBBBBBccccc!12345)
4. Pay attention to the message under the field 'Password'
5. Set EN localization of the main page 'Pick-up'
6. Click 'Sign in' button
7. Type a password in the field 'Password', that contains more than 20 symbols (e.g. aaaaaBBBBBccccc!12345)
8. Pay attention to the message under the field 'Password'

**Actual result**
An incorrect message is displayed on EN/UA localization when user enters the password more than 20 symbols on the pop-up 'Sign in'':
Ua: "user.auth.sign-in.too-long-password"
En: ''user.auth.sign-in.too-long-password"

![password_incor_ms](https://github.com/ita-social-projects/GreenCity/assets/109086383/c9d21712-4dd0-4534-b356-e776652a9f85)

**Expected result**
If a user clicked on password text field, and typed more than 20 symbols, then the error message appears:
En: “Password cannot exceed 20 characters.”
Ua: “Пароль не може містити більше 20 символів”.

**User story and test case links**
"User story #4100"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
