### ISSUE TITLE
[UBS_Prod. Tariffs] Translation issue in the fields when Editing tariff with EN Localization

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5883]
**Environment:** Windows 10, Chrome Version 108.0.5359.99
**Reproducible:** always
**Build found:** 01.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. Tariffs page is opened
3. There is a tariff card with at least one service is added
4. EN language is chosen

**Steps to reproduce**
1. Click on the tariff card with service added
2. Click on 'pencil' to edit tariff
3. Pay attention to the Edit tariff pop-up window

**Actual result**
With EN localization information in the fields Name of the tariff and Найменування послуги, Tariff description and Опис послуги 
is confused: Ukrainian in the English language field and vice versa

![edit_tariff](https://github.com/ita-social-projects/GreenCity/assets/109086383/7cf86bd4-b893-4c8a-9de9-c74e9218e69c)

**Expected result**
Name of the tariff and Найменування послуги, Tariff description and Опис послуги fields information should be displayed correctly 

**User story and test case links**
E.g.: "User story #4430"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
