### ISSUE TITLE
[UBS_Prod. Notifications User] 'Your messages' page header view is cut

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5884]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 01.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized 

**Steps to reproduce**
1. Go to the Notifications page
2. Pay attention to the page view

**Actual result**
The page header is cut (overlapped by header)

![notific_ui](https://github.com/ita-social-projects/GreenCity/assets/109086383/0cd49c84-e097-4879-b68d-33c929989035)

**Expected result**
The page header is fully visible

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
