### ISSUE TITLE
[UBS_Prod. Tariffs] Order limits section, selected radiobutton is of different color

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5885]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 01.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized as Admin

**Steps to reproduce**
1. Go to Tariffs page
2. Click on any tariff card available
3. Pay attention to the order limits radiobutton section

**Actual result**
Selected radiobutton color is pink: #ff4081

![image](https://github.com/ita-social-projects/GreenCity/assets/109086383/65534efb-d63c-4053-af34-7219c19230c8)

**Expected result**
Selected radiobutton color should be: #1d2830

**User story and test case links**
E.g.: "User story #4948"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
