### ISSUE TITLE
[UBS_Prod. User Notifications] Missing information in the 'formed route' notification

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5886]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 01.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized as User
3. At least one order should be made with status 'adjustment'

**Steps to reproduce**
1. Go to Notifications page
2. Click on 'The courier route formed' message
3. Pay attention to the text 

**Actual result**
Date and time are absent in the notification

![route_is_formed](https://github.com/ita-social-projects/GreenCity/assets/109086383/69ccb562-84e6-4093-abf9-b6afad260c12)

**Expected result**
Date and time should be present in the notification

**User story and test case links**
E.g.: "User story #4635"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
