### ISSUE TITLE
[Create Event #3193] There is no tag “closed” added to the close type event details or preview card

### ISSUE THREAD

**Issue by darinadobrukha** [ita-social-projects/GreenCity#5888]
**Environment:** 
Windows 11 Pro, 21H2
Chrome Version 112.0.5615.138 (Official Build) (64-bit)

**Reproducible:** always

**Build found:** 02/06/2023

**Preconditions**
1. Go to https://www.greencity.social/#/events as a authorized user.
2. Closed type event was created by another authorized user.

**Steps to reproduce**
1. Find a 'Close' type of event in the events list.

**Actual result**
No tag “closed” is added to the event details or event preview card.

**Expected result**
Tag “closed” must be added to the event details and event preview card.

**User story and test case links**
E.g.: "User story #3193 
[Test case] [https://jira.softserve.academy/browse/GC-3114] [https://jira.softserve.academy/browse/GC-3113]

**Labels to be added** Bug, Events, Event Preview, Events Dashboard, UI

Priority: Medium 
Severity: Minor
Type: UI

![Знімок екрана 2023-05-31 165831](https://github.com/ita-social-projects/GreenCity/assets/110566105/d9e90a4d-301a-4d0b-abd6-ebe91c832986)

**Comment by DanaIuich** [comment]
Bug is fixed
