### ISSUE TITLE
[UBS_Prod. Tariffs User] Incorrect message about limits when creating new Order

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5889]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 01.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized as User

**Steps to reproduce**
1. Go to main page and click on 'order' button
2. Select 'Mykolaiv' (or any other except Kyiv) from location dropdown
3. Fill in correct number of packages
4. Pay attention to the message shown

**Actual result**
incorrect limitc are shown. the minimum packages set in the tariff card differs

![message](https://github.com/ita-social-projects/GreenCity/assets/109086383/a3c834fe-4626-4b5e-bd51-dd1843319a9b)

![image](https://github.com/ita-social-projects/GreenCity/assets/109086383/1cf79d26-19c4-4d6c-a4a4-ef512941bb98)

**Expected result**
The message corresponds to the limits set in the tariff card

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
