### ISSUE TITLE
[UBS_Prod. Tariffs User] the 'Next' button is inactive after correct number of packages is entered when making new order

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5890]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 01.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized as User

**Steps to reproduce**

1. Go to the main page and click on 'order' button
2. Select 'Mykolaiv' (or any other except Kyiv) from location dropdown
3. Fill in correct number of packages
4. Pay attention to the 'Next' button

**Actual result**
the 'Next' button is inactive regardless the number of packages selected

**Expected result**
the 'Next' button is active when the correct number of packages is selected

p.s. I believe there is connection with this issue: https://github.com/ita-social-projects/GreenCity/issues/5889

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by BohdanaYuzkiv** [comment]
after some research made I found that if the maximum number of packages is filled in (when creating a new tariff card) than the order can be made. but this field should NOT be mandatory and should not affect the order. in case more info needed I will provide it

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
