### ISSUE TITLE
[UBS_Prod. Tariffs] Scroll is absent on the Add tariff pop-up window

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5891]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 01.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized as Admin
3. Tariffs page is opened

**Steps to reproduce**
1. Click on the 'Add tariff' button
2. Pay attention to the pop-up window view

**Actual result**
Scroll is absent, buttons are hidden

![scrol_abs](https://github.com/ita-social-projects/GreenCity/assets/109086383/9bbd65c8-0424-44a0-905f-002cc2760e7a)

**Expected result**
Scroll is present, user can see the whole pop-up window

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
