### ISSUE TITLE
[UBS.Notifications (Admin`s cabinet)] The list of notifications is not infinitely scroll

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#5894]
**Environment:** Google Chrome 113.0.5672.93,Windows 10 Pro 20H2
**Reproducible:** always
**Build found:** 03.01.23

**Preconditions**
1. Website https://www.greencity.social/#/greenCity is opened
2. The user should be logged in as a Super Admin
3. The system consists of more than ten notifications

**Steps to reproduce**
1. In the main UBS menu click on 'Notifications'

**Actual result**
Pagination is implemented at the bottom of the Notifications page

**Expected result**
The list of notifications infinitely scroll

**User story and test case links**
"User story #4635 
![Screenshot_1](https://github.com/ita-social-projects/GreenCity/assets/131760121/0492a1e5-a470-42bc-9a12-3423297bdae6)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:minor"), Type ("UI, "Functional")

**Comment by Maksym8Kravchenko** [comment]
This big is not fixed.

**Comment by DanaIuich** [comment]
Bug is fixed
