### ISSUE TITLE
[Create Event #3193 Change request #5123] The "All Day" option does not display default time values

### ISSUE THREAD

**Issue by darinadobrukha** [ita-social-projects/GreenCity#5897]
**Environment:** 
OS: MacOS 13.1
Browser: Google Chrome 113.0.5672.126

**Reproducible:** always

**Build found:** 04.06.2023

**Preconditions**
1. Go to https://www.greencity.social/#/events
2. The user should be authorized
3. The 'Create event' page is opened

**Steps to reproduce**
1. Select a valid date in the date field
2. Select "All day" event

**Actual result**
After selecting the "All day" option no default time values are displayed. 

**Expected result**
The default beginning time is displayed as 9 AM.
The default end time is displayed as 9 PM.

**User story and test case links**
E.g.: "User story [Create Event] #3193, [Change Request] #5123 

**Labels to be added**
Bug, Events, Events dashboard, Create event

Priority: Medium
Severity: Minor
Type: Functional

Attachments:
<img width="497" alt="Screenshot 2023-06-01 at 16 45 45" src="https://github.com/ita-social-projects/GreenCity/assets/110566105/7c61fbe4-789a-4a88-b8ea-92be65653881">

**Comment by DanaIuich** [comment]
Bug is fixed
