### ISSUE TITLE
Search for entry by name

### ISSUE THREAD

**Issue by yartymys** [ita-social-projects/GreenCity#59]
As an admin I want to be able to search for particular items within the Admin page, so that I can easily find needed items.

**Mockups:** 
![image](https://user-images.githubusercontent.com/53868652/63422574-473b4480-c413-11e9-9052-5e43d3ffc8ba.png)
*TBD for field width and location

**Acceptance Criteria:**

1. System shall display a search input field in the Admin page.
2. After entering search criteria, Admin can initiate the search action by:
a. pressing "Enter" 
b. clicking on the magnifying icon in the search field
3. Provided admin entered search criteria into the search field and initiated the search, system shall do search within the active tab in the Admin page. (e.g. if admin is in "Approved places" tab - system shall search only within this tab. To search within other tabs, admin needs to navigate to other tabs)
4. Search shall be available without any restrictions as to input criteria (letters, digits, symbols), EXCEPT for blank search criteria (i.e. provided admin clicks the magnifying icon when there is no search criteria, system shall not initiate search).
5. Search action shall do search by means of "contains" parameter AND within all columns (i.e. given there is "Intempo" entry and admin searches for "int" - system shall display the result + any other possible results which include "int")
6. Provided there is(are) items that are identified by the search criteria after admin initiates search, system shall display them within the tab in alphabetical order (A-Z). System shall display the whole entry row.
7. Provided there is no item identified by search criteria after admin initiates search, system shall display message "No matches found" within the tab.

**Assumptions and Constraints:**

**TBD:**

**Comment by rsyvulko** [comment]
Not relevant.
