### ISSUE TITLE
[Edit event] After changing language on UA the text on the button does not fit

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5902]
**Environment:** all
**Reproducible:** always
**Build found:** 05/06/2023

**Preconditions**

1. Go to https://www.greencity.social/#/events
2. An authorized user shoud be logged
3. The event shoud be created and found

**Steps to reproduce**
1. Click on "Edit event" button on created event
2. Change the language on UA

**Actual result**
The text on  "Попередній перегляд" button  does not fit

**Expected result**
All texts on buttons are according mockup

**Postconditions**

**User story and test case links**
E.g.: "User story #5146 

<img width="361" alt="wrong_buttons" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/fbc9da26-c020-4579-8dc7-53281d89364e">

**Comment by katia9261** [comment]
Mock-up is only in EN version
![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/52f298f0-4d4f-4232-ae18-654fcc1a3370)
