### ISSUE TITLE
[Edit event] The added image is not displayed in edited event

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5904]
**Environment:** All
**Reproducible:** always
**Build found:**05/06/2023

**Preconditions**

1. Go to https://www.greencity.social/#/events
2. An authorized user shoud be logged
3. Event shoud be created and found

**Steps to reproduce**

1. Click on "Edit event" button
2. Upload 2 images to event
3. Click "Publish"
4. Find edited event and click "More" button
5. Verify that all images are displayed

**Actual result**
Only 1 image ia displayed

**Expected result**
All apploaded images are displayed

**User story and test case links**
E.g.: "User story #3195 
[Test case]https://jira.softserve.academy/browse/GC-3202

https://github.com/ita-social-projects/GreenCity/assets/128155213/79869531-2723-422a-89e5-8c824cfdc979

**Comment by KKatiaa** [comment]
I checked and 3 img were displayed in my event

**Comment by DanaIuich** [comment]
I can't see 2 images when I click on "More" button of created event

https://github.com/ita-social-projects/GreenCity/assets/128155213/8741bf6e-ee08-4c9d-b3f5-626e4fa5772e

**Comment by KKatiaa** [comment]
can we discuss it discod KaterynaKravchuk#0525

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
