### ISSUE TITLE
[UBS_Prod Create new card of couirer] The system allows to create new courier with already existing name

### ISSUE THREAD

**Issue by ViktoriyaDatsyshyn** [ita-social-projects/GreenCity#5907]
Environment: Microsoft Windows 10 Pro, Сhrome 111.0.5563.65.
Reproducible: always.
Build found: 05/06/2023.

Preconditions:
1. The web-page https://www.pick-up.city/#/ubs-admin/tariffs is opened.
2. The User is logged in as a Super Admin.
3. Courier with title "УБС" already exists.

Steps to reproduce:
1. Go to the page 'Тарифи' in the UBS-Admin menu.
2. Tap on the “gear” pictogram in upper right corner.
3. Tap on “Додати”.
4. Choose point “Кур’єр”.
5. Input the name of existing courier with 3 spaces.
6. Click on "Додати".

Actual result:
New courier with existing name is created.

Expected result:
The system doesn't allow to create courier with already existing name. 
The validation message appears : “Кур’єр вже існує в системі”.

User story #3849

Labels to be added
![Add existing courier_good](https://github.com/ita-social-projects/GreenCity/assets/128295039/53f59309-c891-4812-ae12-a468efd0bb5c)
![Add existing courier_defect](https://github.com/ita-social-projects/GreenCity/assets/128295039/48e6a96e-ff77-4790-9a7b-d1bf3505564c)
Bug, pri: medium, severity: minor, Type: Functional

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
