### ISSUE TITLE
[UBS_Prod. Orders_Admin] The orders table doesn't support the width change of every column

### ISSUE THREAD

**Issue by RudnevaOlena** [ita-social-projects/GreenCity#5915]
**Environment:** Mac OS Ventura 13.3.1 (a), browser Safari Version 16.4 (18615.1.26.110.1)..
**Reproducible:** always.
**Build found:** 06.06.2023

**Preconditions**

1. The User should be logged in as a Super Admin.
2. Orders page is opened.

**Steps to reproduce**
1. Go to https://www.pick-up.city/#/ubs-admin/orders;
2. Click the mouse on the border of any column and try to move it left/right

**Actual result**
The order table column is dragged to another position.

https://github.com/ita-social-projects/GreenCity/assets/128076020/4842db39-a7bb-4ef1-acef-e29004b806d8

**Expected result**
The width of the order table column changes, while the column itself does not change its position.

**User story and test case links**
E.g.: "User story #2536

**Comment by katia9261** [comment]
We change the width with the column's borders, not the headers. The header swapping changes the position as on the video
https://github.com/ita-social-projects/GreenCity/assets/101433204/e314c976-14eb-4caf-91cc-c992b6be7409
