### ISSUE TITLE
[UBS_Prod User Cabinet] Impossible to add a city when editing a location       

### ISSUE THREAD

**Issue by ViktoriyaDatsyshyn** [ita-social-projects/GreenCity#5916]
Environment: Microsoft Windows 10 Pro, Сhrome 111.0.5563.65.
Reproducible: always.
Build found: 06/06/2023.

Preconditions:

1. The web-page https://www.pick-up.city/#/ubs-admin/tariffs is opened.
2. The User is logged in as a Super Admin.
3. English localization is selected.

Steps to reproduce:

1. Go to the page 'Тарифи' in the UBS-Admin menu.
2. Tap on the “gear” pictogram in upper right corner.
4. Tap on “Редагувати”.
5. Choose point “Локація”
6. Select the region from drop-down list.
7. Type the city name in the field “Місто”.
8. Press “Enter” or tap on the link “Додати місто”.

Actual result:
Autocomplete doesn't work.
The message “The city already exists in the system. Change it” appears.

Expected result:
Edited city will appear as a text with Ukrainian equivalent.

Actual result:
Autocomplete doesn't work.
The message “The city already exists in the system. Change it” appears.
![edit location_auto](https://github.com/ita-social-projects/GreenCity/assets/128295039/335fa5be-e37c-4608-b5f0-02d4e56aa9aa)
![edit location_bug](https://github.com/ita-social-projects/GreenCity/assets/128295039/68510588-2bd0-4522-b746-6f377cd564b9)
![edit location_error message](https://github.com/ita-social-projects/GreenCity/assets/128295039/929f1238-8a2b-4297-9dfd-550411458ae8)

User story #3902

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
