### ISSUE TITLE
[UBS_Prod. Tariffs User page] Order detailes dissapears if tariff is changed or deleted

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5917]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 06.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized as User
3. The order is made and is shown on the Orders page

**Steps to reproduce**
1. Log in as Admin 
2. Go to the tariffs page
3. Delete tariffs for services in the previously made order
4. Log in as User
5. Check info about that Order in order details

**Actual result**
The info about services is absent. It is cleared not only in the tariff card but also in the user cabinet

![image](https://github.com/ita-social-projects/GreenCity/assets/109086383/9bd75288-eee5-4b51-8250-920502b0e66a)

**Expected result**
In case order is paid, Order detailes are shown to the user even if the tariff card is changed/deleted

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by nina279** [comment]
The issue is not relevant - the product was handed over to the client
