### ISSUE TITLE
[Sign-up]Does not have a pop-up window confirming the registration

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#5924]
**Environment:** Windows 10 home, Firefox 113.0.2 (64-bit).
**Reproducible:** always.

**Preconditions**
Go to https://www.greencity.social/#/ubs

**Steps to reproduce**
1. Go to 'https://www.greencity.social/#/ubs'
2. Click on 'Sign-up'
3. Enter data for registration

**Actual result**
Does not have a pop-up window confirming the registration.

**Expected result**
When Unregistered user fills in all necessary fields AND clicks "Sign Up" button, THEN he/she see popup with text "You successfully registered on this site. Please verify your email address in mailbox". 

**User story and test case links**
E.g.: "User story #4099 
https://github.com/ita-social-projects/GreenCity/issues/29

**Comment by KKatiaa** [comment]
it is already completed
