### ISSUE TITLE
[Admin cabinet.Pricing page] Not all regions can be deactivated when selected more than 1 item

### ISSUE THREAD

**Issue by katia9261** [ita-social-projects/GreenCity#5928]
**Environment**: Microsoft Windows 10 Pro, Сhrome 111.0.5563.65.
**Reproducible**: always.
**Build found**: 08/06/2023.

**Preconditions:**
1. The web page https://www.pick-up.city/#/ubs-admin/tariffs is opened.
2. The User is logged in as a Super Admin.
3. English localization is selected.

**Steps to reproduce:**
1. Go to the page 'Тарифи' in the UBS-Admin menu.
2. Tap on the “gear” pictogram in the upper right corner.
4. Tap on “Деактивувати”.
5. Choose point “Регіон”
6. Choose more than 1 region to deactivate 

**Actual result**
Only the first selected region is deactivated

https://github.com/ita-social-projects/GreenCity/assets/101433204/d0ae71ce-6fe6-4d46-98a2-ccd2ce64bc20

**Expected result**
All selected regions are deactivated

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
