### ISSUE TITLE
[ GreenCity Registration ] The system redirects the User on UBS homepage instead of GreenCity home page when cancel registration

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/GreenCity#5945]
**Environment:** OS: Windows 11
**Reproducible:** always
**Build found:** 14.06.2023

**Discription**
The system redirects the User on UBS homepage instead of GreenCity home page when cancel registration

**Steps to reproduce**
1. Open the application  https://www.greencity.social/#/greenCity 
2. Click on Sign Up
3. Click on "Cancel" button ( the cross in the right corner of these window )

**Actual result**
The User redirects to UBS page 

**Expected result**
The User returns to the main page of the GreenCity site

**User story and test case links**
E.g.: "User story

https://github.com/ita-social-projects/GreenCity/assets/109734235/647d668e-bfcb-4777-88d2-01203e377571

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:trivial"), Type ( "Functional"),

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
