### ISSUE TITLE
[Create news] The tags are selected automatically when user creats the second news

### ISSUE THREAD

**Issue by ChuikoJulia** [ita-social-projects/GreenCity#5947]
**Environment:** OS: Windows 10 Pro
                            Browser: Google Chrome Version 111.0.5563.112.
**Reproducible:** always.
**Build found:** 15.06.2023

**Preconditions**
1. User should be registered on Green City site (https://www.greencity.social/#/greenCity)
2. User is Sign in on Green City

**Steps to reproduce**

1. Click on the "Eco news" button.
2. Click on the "Create news" button.
3. Fill in all mandatory fields with valid data and select tags (from 1 to 3).
4. Click the "Publish" button.
5. Click on the "Create news" button.
6. Fill in all mandatory fields with valid data and select tags.
7. Click the "Publish" button.

**Actual result**
Step 5: The tags from step 3 are selected automatically on the "Create news" page.
Step 7: The "Publish" button is disabled.

**Expected result**
Step 5: All tags must be unselected on the new "Create news" page.
Step 7: The "Publish" button is enabled.

**User story and test case links**
"User story #505 

**Labels to be added**
"Bug", Priority ("High"), Severity ("Major"), Type ("Functional").

**Comment by DanaIuich** [comment]
Step 5: The tags from step 3 are selected automatically on the "Create news" page.

**Comment by dmytro-kryvyi** [comment]
Does not reproduce. Propably fixed with #6670
