### ISSUE TITLE
[Edit profile] A confirmation pop-up appears when the user clicks on the 'Cancel' button without making any changes.

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/GreenCity#5951]
**Environment:** Windows 11,
Google Chrome Version 111.0.5563.147 (64-bit)
Mozilla Firefox Version 114.0 (64-bit)
Microsoft Edge Version 114.0.1823.41 (Official build) (64-bit)
**Reproducible:** Always
**Build found:** 13.06.2023

**Steps to reproduce:**

1. Open the application in a browser (https://www.greencity.social/#/greenCity)
2. Sign in as a registered user.
3. Open 'Edit Profile' page.
4. Click on the 'Cancel' button.

_**Actual result:**_
The system shows the confirmation pop-up with "All created content will be lost. Do you still want to cancel profile editing?" message and two options: "Continue editing", "Yes, cancel".

_**Expected result:**_
The system doesn't show the confirmation pop-up.

**User story and test case links:**
"User story #1009

https://github.com/ita-social-projects/GreenCity/assets/135108144/3911e01a-8056-4d66-a706-68bc14cd0a1e

https://github.com/ita-social-projects/GreenCity/assets/135108144/5bec40a5-40da-4fa4-a3fc-f592ec619aac

**Comment by Vadym840217** [comment]
1. The pop-up window appears as in the 1st video, when you have not made any changes and click on any tab at the top
2. The pop-up window appears in accordance with paragraph 6 of the user story #1009
* If a user has made some changes but then reverted them to what they were before editing, and tries to navigate away from the "Edit Profile" page, the cancellation prompt should not appear.
