### ISSUE TITLE
[All habits] The user can see all custom habits instead of only their own

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/GreenCity#5955]
**Environment:** Windows 11,
Google Chrome Version 111.0.5563.147 (64-bit)
Mozilla Firefox Version 114.0 (64-bit)
Microsoft Edge Version 114.0.1823.41 (Official build) (64-bit)
**Reproducible:** Always
**Build found:** 15.06.2023

**Preconditions:**
A minimum of three custom habits are created: 1 belonging to a user, 1 belonging to a user's friend, and 1 belonging to a user who is not among friends.

**Steps to reproduce**

1. Open Green City https://www.greencity.social/#/greenCity 
2. Log in.
3. Click on "My habits" tab.
4. Scroll to the end of the habits list.

_**Actual result:**_
The user can see both standard habits and all custom habits created on the 'All habits' page.

_**Expected result:**_
The user can see only standard habits,  habits of user's friends, and their own created habits on the 'All habits' page.

**User story and test case links:**
"User story #1000

**Comment by Vadym840217** [comment]
Fixed
