### ISSUE TITLE
[UBS_Prod. User Cabinet] 'Змінити локацію' doesnt allow to choose necessary location

### ISSUE THREAD

**Issue by LiliaZakharko** [ita-social-projects/GreenCity#5958]
Environment: Windows 10 Pro, Chrome 111.0.5563.65.
Reproducible: sometimes.
Build found: 16.06.2023

**Preconditions**
1. Go to the https://www.pick-up.city/
2. User should be authorized as User
3. 'Ваші замовлення' page is opened.

**Steps to reproduce**
1. Click on 'Нове замовлення'
2. Choose the location of waste disposal (e.g. Малин, Киівська область)
3. Click on 'Змінити локацію'
4. Select another location from drop-down list (e.g. Лісники, Київська область)

**Actual result**
The previous location is shown on the 'Деталі замовлення' page.

**Expected result**
New location is shown on the 'Деталі замовлення' page.

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

https://github.com/ita-social-projects/GreenCity/assets/128394400/cf362c45-3776-447d-8046-3cccfe6dc0f6

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
