### ISSUE TITLE
[UBS_Prod. Tariff page] Deactivated cities are visible in Tariff card

### ISSUE THREAD

**Issue by LiliaZakharko** [ita-social-projects/GreenCity#5959]
Environment: Windows 10 Pro, Chrome 111.0.5563.65.
Reproducible: always.
Build found: 16.06.2023

**Preconditions**

1. https://www.pick-up.city/ is opened.
2. User is logged in as a Super Admin
3. Tariff page is opened.
4. There is at least one active Tariff card
5. There are several active cities in one Tariff card
6. There was an order made by User for at least one city

**Steps to reproduce**

1. Click on the 'Gear' section.
2. Select 'Деактивувати' option
3. Choose any active region (e.g.Київська область)
4. Select several active cities (e.g.Київ, Малин, Лісники)
5. Click on the 'Деактивувати' button.
7. Click on the 'Деактивувати' button' in new pop up window 'Підтвердити деактивацію'.

**Actual result**
All deactivated cities are visible in the active Tariff card on the main Tariff page.

**Expected result**

1. Cities with no orders are not visible in the active Tariff card on the main Tariff page.
2. Cities for which there were orders are colored in grey. 

**User story and test case links**
E.g.: "User story #3851 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
<img width="607" alt="PROD_deactivated cities are visible" src="https://github.com/ita-social-projects/GreenCity/assets/128394400/a725e294-040e-4bd3-844a-4e8d2e4c4cd9">

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
