### ISSUE TITLE
[UBS_Prod. Tariff page] Recently activated regions became deactivated if another region is deactivating

### ISSUE THREAD

**Issue by LiliaZakharko** [ita-social-projects/GreenCity#5960]
Environment: Windows 10 Pro, Chrome 111.0.5563.65.
Reproducible: always.
Build found: 16.06.2023

**Preconditions**

1. https://www.pick-up.city/ is opened.
2. User is logged in as a Super Admin
3. Tariff page is opened.
4. There are several active Tariff cards

**Steps to reproduce**

1. Click on the 'Gear' section.
2. Select 'Деактивувати' option
3. Choose any active region (e.g.Київська область)
4. Click on the 'Деактивувати' button
5. Click on the 'Деактивувати' button on the new pop-up window 'Підтвердити деактивацію'
6. Select 'Неактивно' status
7. Activate the recently deactivated region by clicking on the round arrow on the appropriate Tariff card
8. Select 'Aктивно' status
9. Click on the 'Gear' section.
10. Select 'Деактивувати' option
11. Choose any active region (e.g.Львівська область)
12. Click on the 'Деактивувати' button
13. Click on the 'Деактивувати' button on the new pop-up window 'Підтвердити деактивацію'. 

**Actual result**

1. The Tariff card with the last deactivated region and recently activated regions became deactivated and are not visible on the main Tariff page with only active cards.
2. Deactivated regions are not available for Activation via 'Gear'-'Activation' 

**Expected result**

1. The Tariff card with the last deactivated region became deactivated and is not visible on the main Tariff page with only active cards. 
2. Tariff cards with recently activated regions are active and are visible on the main Tariff page with only active cards.
3. Deactivated regions are available for Activation via 'Gear'-'Activation' 

**User story and test case links**
E.g.: "User story #3851 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
We have no access to the Pick-up.
