### ISSUE TITLE
[Create news] User can't publish the news after drag & drop inappropriate file in 'Image' field and filling in all mandatory field

### ISSUE THREAD

**Issue by YuliaValkovets** [ita-social-projects/GreenCity#5961]
**Environment:** OS: Windows 11 Pro; Browser: Google Chrome 113.0.5672.127.
**Reproducible:** always
**Build found:** 12.06.2023

**Preconditions**
1. The user must be authorized on the Green City (https://www.greencity.social/#/greenCity);
2. The 'Eco news' page is opened.

**Steps to reproduce**
1. Click on 'Create news' button;
2. Drag & drop any inappropriate file in 'Image' field (e.g. PPT);
3. Fill in all mandatory fields with valid data and select tags (from 1 to 3);
4. Press the 'Publish' button.

**Actual result**
The 'Publish' button is disabled.

**Expected result**
The 'Publish' button is enable and news is published with default image on 'Eco news' page.

**User story and test case links**
"User story #537 

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Minor"), Type ("Functional")

**Comment by DanaIuich** [comment]
After trying to upload picture more than 10MB (32MB) and clicking the button "Опублікувати" The new page with message "Please wait while loading...

Your news is loading to website. Please wait until page refreshes." is openning.  The wait is very long. The page must be reloaded. The news is not published. In devtools response 413.

https://github.com/ita-social-projects/GreenCity/assets/128155213/62c77d32-f37b-41af-944e-133b0e765830

**Comment by dimoybiyca** [comment]
Bug does not reproduce.
