### ISSUE TITLE
[Create News] The word "download" should be replaced with "upload" in the warning above the "Image" field

### ISSUE THREAD

**Issue by YuliaValkovets** [ita-social-projects/GreenCity#5964]
**Environment:** OS: Windows 11 Pro; Browser: Google Chrome 113.0.5672.127
**Reproducible:** always
**Build found:**  13.06.2023

**Preconditions**
1. The user must be authorized on the Green City (https://www.greencity.social/#/greenCity).
2. The 'Eco news' page is opened.

**Steps to reproduce**
1. Click on 'Create news' button;
2. On 'Create news' page look at warning above the 'Image' field.

**Actual result**
The warning 'Download PNG or JPG only. File size should be less than 10MB'.

**Expected result**
The warning 'Upload PNG or JPG only. File size should be less than 10MB'

**User story and test case links**
User story #537 
Change request #5995 

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Minor"), Type ("UI")

**Comment by AlexW8719** [comment]
Please review the task. The word "Download" is used in both the "User story https://github.com/ita-social-projects/GreenCity/issues/537 and the project. Thank you.

**Comment by YuliaValkovets** [comment]
I created a change request and linked to this issue, see please
