### ISSUE TITLE
[Create news] The warning is highlighted in red after entering valid data of 170 characters in the 'Title' field.

### ISSUE THREAD

**Issue by YuliaValkovets** [ita-social-projects/GreenCity#5965]
**Environment:** OS: Windows 11 Pro; Browser: Google Chrome 113.0.5672.127
**Reproducible:** always
**Build found:** 11.06.2023

**Preconditions**
1. User is logged in on https://www.greencity.social/#/greenCity
2. 'Eco news' page is opened.

**Steps to reproduce**
1. Click on 'Create news' button;
2. Enter 170 characters(e.g. ghghgjKKOJIJIJGGFDsesesdcgvbnKJHUUYTYTftreswedtvhbjnjnjnjnkjnJHUYTYRTerefgvFTRRThjhjnGTThjnkjkjijijijihuGYFTFRDESESESfghgbhjhnjhuhuYGTRTRERERERDTGVHBUJhuhytytytrtrtfrftgk) in 'Title' input field.

**Actual result**
The warning is highlighted in red color after entering valid data of 170 characters in the 'Title' field.

**Expected result**
The warning is displayed in gray color(#64727D) after entering valid data of 170 characters in 'Title' field.

**User story and test case links**
 "User story #537 

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Minor"), Type ("Functional")

**Comment by DanaIuich** [comment]
Bug is fixed
