### ISSUE TITLE
[To do list] Grammatically incorrect text of the items counter in the “My To-do list” block on the “My habits” page

### ISSUE THREAD

**Issue by khrystenko-qa** [ita-social-projects/GreenCity#5968]
**Environment:** Windows 10x64,
Google Chrome 114.0.5735.134
Microsoft Edge 114.0.1823.51
Mozilla Firefox 114.0.1
**Reproducible:** always
**Build found:** 20.06.2023

**Preconditions**

1. The user is logged in on https://www.greencity.social/
2. The user has one added to the to-do list item.
3. The "My habits" page is open.

**Steps to reproduce**
1. Scroll down to the bottom of the page.
2. Pay attention to the items counter text in the “My To-do list” block on the left sidebar of the page.

**Actual result**
The text of the items counter is grammatically incorrect in the “My To-do list” block on the left sidebar of the “My habits” page when having 1 item added to the to-do list.

**Expected result**
The "1 item" counter text is shown in the “My To-do list” block on the left sidebar of the “My habits” page when having 1 item added to the to-do list.

**User story and test case links**
User story [#2252](https://github.com/ita-social-projects/GreenCity/issues/2252)

**Labels to be added**
"Bug",  "Shopping list", Priority ("pri: low"), Severity ("severity: trivial"), Type ("UI").

**Attachments:**

![grammar_error_items_counter](https://github.com/ita-social-projects/GreenCity/assets/129203930/b9724016-7ecc-480e-acc1-963ae5b8b772)

**Comment by RudnevaOlena** [comment]
The bug has not been fixed yet, when you add something to the "To-do list", we see on DevTools the counter of  <"customShoppingListItems": null>. So, It seems, that the server doesn't consist of the data about customers' items in the   "To-do list".
![Uploading Screenshot 2023-07-13 at 17.22.42.png…]()

**Comment by RudnevaOlena** [comment]
The bug is fixed, and grammatically correct text is displayed for one and more items. Retesting was on the Chrome Version 115.0.5790.98 (Official Build) (arm64), MacOS Ventura 13.4.1 (c)
