### ISSUE TITLE
[To do list] Title of custom item consist are blanks

### ISSUE THREAD

**Issue by sobkiv** [ita-social-projects/GreenCity#5979]
**Date Time**
19-06-2023 14:40

**Severity**
Major

**Priority**
Medium

**Environment:**
OS: Windows 11 Pro, version 22H2
Browsers: Opera (99.0.4788.65), Mozilla Fiferox (114.0.1 64-bit), Chrome (114.0.5735.134 64-bit)
Reproducible: always
Build found: 18.06.2023

**Pre-conditions**

    1. The registered user is logged in.
    2. User has at least 1 habit in progress
    3. "Habits" page (edit mode) is open.

**Steps to Reproduce**

    1. Type blank 3 times in the input field "add custom item"
    2. Click a "+" button near field "add custom item"
    3. Check item " " is visible in a to-do list
    4. Сlick "+" button near item " "
    5. Click "Save" button.

**Expected result**
The title of the custom item can't consist are blanks

**Actual result**
The title of the custom item consists are blanks

**User story and test case links E.g.:** "User story #191
![247936904-6525ec02-2855-4ea6-beb3-e2c89e8d851c](https://github.com/ita-social-projects/GreenCity/assets/112779214/ef86c751-00fa-469d-9b54-1557fbe5dd9f)

**Comment by Vadym840217** [comment]
Now the user won't be able to add an item using 'space 3 times' - fixed
