### ISSUE TITLE
[Change request to #2379] "Екомагазин" section

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5981]
**Description of a Change request:**
Clarification for 'Eco-shop' section.

**Reason for Change:**
 Improvements of the Order Form after customer reviews.

**Acceptance Criteria**
1. When the user wants an order(s) from the Eco-shop to be delivered with the next garbage disposal by UBS Courier, the user shall be able to enter the shop order(s) in the section “Екомагазин”.
Under the bonus section, the user shall see the section "Екомагазин" and the statement ”Якщо Ви чекаєте замовлення з нашого Екомагазину, будь ласка, введіть номер замовлення" and the field "Номер замовлення" with message near by “Якщо Ви не змогли знайти номер замовлення, вкажіть в коментарі прізвище та ім’я, на яке було оформлене замовлення.”
The input field contains a placeholder with a grey-colored text: “XXXXXXXX”. The placeholder shall disappear once the user starts typing.

![ecoshop-02](https://github.com/user-attachments/assets/8b1c2373-5936-480d-8b49-e2b245131e55)

2. Validation of the shop order number – the format  from 1 to 8 symbols.  When the user enters more than 8 symbols  the system displayed the error message: "Номер введено невірно. Спробуйте ще раз" (Eng. "The number was entered incorrectly. Please try again."), the "Next" button is disabled and user can not go to the next page.

![ecoshop-05](https://github.com/user-attachments/assets/063f1072-e737-402b-a88b-483f63495106)

3. After user entered valid order number, link ‘Додати ще номер замовлення’ is appeared. And user able to enter one more order.

![ecoshop-01](https://github.com/user-attachments/assets/26d5aff4-4627-4a53-b14c-904c428edcbe)

4. If user enter similar order numbers in the fields ‘Order number’ red error message under each similar fields is appeared: “Замовлення <ХХХХХХХХ> вже було додано”

![ecoshop-03](https://github.com/user-attachments/assets/b02f496f-cd7d-4c68-99d9-4c2723c913f4)

5. User can enter maximum 5 orders. After entering 5th order link ‘Додати ще номер замовлення’ is disabled.

![ecoshop-04](https://github.com/user-attachments/assets/f3bdde09-bec5-4848-b045-90ad8ad196b9)

Impact of Change
This change request affects 1 change request:
[Change request to #2196] Order form – step 1 [#2379.](https://github.com/ita-social-projects/GreenCity/issues/2379)

Epic: [EPIC: UBS courier #2195](https://github.com/ita-social-projects/GreenCity/issues/2195)

**Comment by Daria811** [comment]
Duplicate to https://github.com/ita-social-projects/GreenCity/issues/6006
