### ISSUE TITLE
( Calendar )not clickability of the entire icon area of the current day (with a display resolution of 1024 * 907 and more)

### ISSUE THREAD

**Issue by gavrtv** [ita-social-projects/GreenCity#5989]
**Date Time**
23-06-2023 21:55

**Severity**
Major

**Priority**
Medium

**Environment:**
OS: Windows 10 Home
Browser: Google Chrome version 114.0.5735.134
Reproducible: always
 
**Pre-conditions**
-Registered user is logged in
-"My space" page is open
-User already has at least 1 habit
-Display resolution of 1024 * 907 and more
-Display resolution of 1023 * 907 to 474 * 907
-click not in the central area of the icon

**Steps to Reproduce**
1. Click on the border of the current day button in the calendar.

**Expected result**
The page displays a pop-up window with a list of habits

**Actual result**
 The pop-up window with the list of habits is not displayed on the page: with a display resolution of 1024 * 907 and more, the active area of the calendar icon is configured so that only when hovering over its central part, the action takes place. When expanding 1023 * 907 to 474 * 907, the entire icon area is active, and a popup with a list of habits is displayed. The format of the icon changes from a round shape to a rectangular one.

**Video**
https://github.com/nromanen/pratical_testing_2022/assets/130498642/f0a68122-b988-442a-a2a5-d0673eba8927

**User story and test case link**
User story [Mark / Unmark habits in progress on a Calendar on My habits page #1431](https://github.com/ita-social-projects/GreenCity/issues/1431#issue-704914207)

**Comment by katia9261** [comment]
The bug doesn't reproduce now
https://github.com/ita-social-projects/GreenCity/assets/101433204/21ff4c08-90bf-4cf4-93e8-eeaca55a7ead
