### ISSUE TITLE
[UBS Courier] The system does not allow entering 5 order numbers in the section "Eco-shop"

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#5991]
**Reproducible:** always
**Build found:** 25/06/2023

**Preconditions**
Login to GreenCity as a User
Go to https://www.greencity.social/#/ubs/order

**Steps to reproduce**
1. Go to the section "Eco-shop"
2. Enter from 1 to 8 numeric characters in the field "Order number".
3. Click on "Add another number" under the field.
4. Try to repeat steps 2 -3 several times.

**Actual result**
After entering characters in the 2 fields "Order number" the link ""Add another number" becomes inactive and an error message "The number was entered incorrectly. Please try again" appears when the cursor is clicked on an empty space

**Expected result**
There is a posibility to enter 5 order numbers in the 5 similar fields

**User story and test case links**
E.g.: https://github.com/ita-social-projects/GreenCity/issues/2379

https://github.com/ita-social-projects/GreenCity/assets/128155213/1011ad5c-3a55-41ad-80bd-6ee00bce1e39

**Comment by DanaIuich** [comment]
There is no possible to enter even 1 order number in the field. The error message appears.
<img width="517" alt="No_possible_to_enter_even_one_order_number" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/e582eca4-d1fa-4392-8e46-8ece49e69bc1">

**Comment by Tadei-Mykola** [comment]
Now, the Eco-Shop number can be from 4 to 10.

**Comment by snezhanapravdyuk** [comment]
This bug is not relevant, it is now link Eco-shop redirect on the page https://shop.nowaste.com.ua/
