### ISSUE TITLE
['Create habit' page edit mode ] 'The field should contain minimum of 20 symbols' error message is not appeared

### ISSUE THREAD

**Issue by machechka** [ita-social-projects/GreenCity#5993]
**Environment:**
 OS: macOS Monterey
 Version: 12.6.5
 Browser: Safari
 Version: 16.4.1
 Reproducible: always
 Build found: 20.06.2023

**Pre-conditions**

1. Registered user is logged in https://www.greencity.social/
2. 'Create habit' page is open

**Steps to Reproduce**

1. Type one symbol into the 'Habit description' input filed
2. Click anywhere in the interface
3. Pay attention to the error message 
4. Type 13 symbols into the 'Habit description' input field
5. Observe the error message

**Actual result**
The error message is not appeared

**Expected result**
The error message 'The field should contain a minimum of 20 symbols' highlighted in red is shown under the input field

**Screenshot**

![Error message (20 symbols)](https://github.com/nromanen/pratical_testing_2022/assets/130856733/a22993e2-8f8c-46e7-b96d-f34dc9877642)

**User story** 
"Change request to #1001 . Add new custom habit https://github.com/nromanen/pratical_testing_2022/issues/192"

**Comment by Vadym840217** [comment]
Error message is appeared 'The field contains insufficient characters', shoud be 'The field should contain a minimum of 20 symbols'.
![incorrect_message_1](https://github.com/ita-social-projects/GreenCity/assets/130633728/194c0806-797d-4cec-8aa7-f377d016b279)
