### ISSUE TITLE
[To do list]The link-item in To-Do list not clickable

### ISSUE THREAD

**Issue by Neolla7** [ita-social-projects/GreenCity#5996]
**Environment:**
OS: Windows 11 Pro, version 22H2
Browsers: Opera (99.0.4788.65), Mozilla Fiferox (114.0.1 64-bit), Chrome (114.0.5735.134 64-bit)
Reproducible: always
Build found: 18.06.2023

**Pre-conditions**
1. The registered user is logged in.
2. User has at least 1 habit in progress.
3. "Habits" page (edit mode) is open.

**Steps to Reproduce**
1. Insert a link in the input field  "add custom item".
2. Click a "+" button near field "add custom item" .
3. Choose the item link: click the "+" button near the item-link.
4. Click the "Save" button.
5. Click on the item-link list of items on "My page".

**Actual result**
Nothing happens, whole the link is shown in a tooltip.

**Expected result**
Will happen to redirect to the address of the link.

**User story and test case links** E.g.: "User story #191 

**Screenshots**![Screenshot 2023-06-22 160219](https://github.com/nromanen/pratical_testing_2022/assets/130867290/4ceaed64-ea52-483c-b518-ab8999ceef75)

**Comment by Vadym840217** [comment]
Link item in to-do list is clickable (must be shorter than 50 characters)
