### ISSUE TITLE
[UBS courier #2195] An error while entering 'UBS-user' cabinet

### ISSUE THREAD

**Issue by darinadobrukha** [ita-social-projects/GreenCity#5998]
**Environment:** 
Windows 11 Pro, 21H2
Версія 114.0.5735.134 (Official Build) (64-bit)

**Reproducible:** always

**Build found:** 26.06.2023

**Preconditions**
1. Page https://www.greencity.social/#/ubs is opened
2. Entered with a parcitular user (name: Dara Dara, email: 1994nika@gmail.com) 

**Steps to reproduce**
1. Go to 'UBS-User' page
3. Click on any icon 'Orders/Bonuses/User data/Messeges'

**Actual result**
1. Error messeges 'Oops, something went wrong. Please reload page or try again later.' and 'ubs-client-profile.error-message' appears.
2. None of the pages is loading.

**Expected result**
1. A page of 'Orders/Bonuses/User data/Messeges' must be opened showing a corresponding data.

**User story and test case links**
Epic #2195  
User story #4351 #3477 
Related bug report #5999 

**Labels to be added**
Bug, Functional, UBS Personal Cabinet, UBS, ubs-user 

Priority: Medium 
Severity: Minor 
Type: Functional

Attached files:

https://github.com/ita-social-projects/GreenCity/assets/110566105/417da8e6-6768-496a-a9a1-9a5349354845

**Comment by DanaIuich** [comment]
Bug is fixed
