### ISSUE TITLE
[Create news] The news is duplicated in the "My Space" tab after creation.

### ISSUE THREAD

**Issue by AlexW8719** [ita-social-projects/GreenCity#6002]
**Environment:** OS: Windows 10 Pro.
Browser: Google Chrome Version 114.0.5735.134
**Reproducible:** always.
**Build found:**27.06.2023

**Preconditions**

1. User should be registered on Green City site (https://www.greencity.social/#/greenCity)
2. User is Sign in on Green City

**Steps to reproduce**

1. Click on the "Eco news" button.
2. Click on the "Create news" button.
3. Fill in all mandatory fields with valid data and select tags (from 2 to 3).
4. Click the "Publish" button.

**Actual result**
On the "My Space" page, in the "My News" tab, sometimes the news articles that we created are duplicated.

**Expected result**
On the "My Space" page, in the "My News" tab, the exact number of created news articles should be displayed.

**Comment by DanaIuich** [comment]
The news articles that we created are duplicated.


https://github.com/ita-social-projects/GreenCity/assets/128155213/3605db00-e772-4a47-a357-1872beaf2633
