### ISSUE TITLE
[Order form] Not correct notification after changing the conditions for the order

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6003]
**Environment:** Firefox 114.0.2 (64-bit)
Windows 11 IoT Enterprise, version 22H2 
**Reproducible:** always

**Preconditions**
Through the admin account, change the minimum number of packages to the minimum amount of payment (500 UAH) for Kharkiv and Kharkiv region.

**Steps to reproduce**
1. Go to https://www.greencity.social/#/ubs
2. Click to order
3. Choose Kharkiv and Kharkiv region.

**Actual result**
Not correct notification -  "The minimum order amount must be 500 UAH
Please note that the minimum order must contain at least 500 packages of 120l"

**Expected result**
Correct notification - "The minimum order amount must be 500 UAH"

![Screenshot_1](https://github.com/ita-social-projects/GreenCity/assets/128135241/090edbd3-35e0-4f6f-8330-0c584acce7f0)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by BranetE** [comment]
I checked on test and local databases and everything works fine.
![Screenshot 2023-06-30 140253](https://github.com/ita-social-projects/GreenCity/assets/47332977/1c73490c-f8da-4abb-b2c3-9ab427ea9594)
![image](https://github.com/ita-social-projects/GreenCity/assets/47332977/73c827f3-d600-4128-a773-7df606da983f)
