### ISSUE TITLE
[UBS Courier] The error message appears after entering different order numbers in the section "Eco-shop"

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6006]
**Reproducible:** always
**Build found:**28/06/2023

**Preconditions**

1. User should be logged
2. Go to https://www.greencity.social/#/ubs/order

**Steps to reproduce**
1. In the section "Eco-shop" in the field "Order number" enter from 1 to 8 symbols (e.g. 12345)
2. Click on link "Add another order number" under the field "Order number" and enter from 1 to 8 symbols which are not similar with symbols from the first field (e.g. 65)
3. Сlick the mouse on an empty place on the page

**Actual result**
The error message "The number was entered incorrectly. Please try again." appears under the field "Order number"

**Expected result**
The link  "Add another order number" becomes active. There is no error message

**User story and test case links**
[Change request to #2196] Order form – step 1 #2379
[Change request to #2379] "Екомагазин" section #5981

https://github.com/ita-social-projects/GreenCity/assets/128155213/1e6f26ec-70b4-4ea8-8646-8ff3dc482af5

**Comment by DanaIuich** [comment]
According to [[Change request to #2379] "Екомагазин" section #5981](https://github.com/ita-social-projects/GreenCity/issues/5981) user can enter  from 1 to 8 symbols in the field of section Еко-шоп".  But now he can't do this
<img width="480" alt="user_can't_fill_eco-shop" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/a9a60a4a-e302-42d4-b816-2a3f6602e16d">

**Comment by liliaruda** [comment]
The page doesn`t load

![Знімок екрана (1175)](https://github.com/ita-social-projects/GreenCity/assets/163115255/104ed5e3-1f60-4324-8bdc-de96f3b57554)
