### ISSUE TITLE
[UBS courier/Order details] An error message appears when user clicks the mouse outside the field "Order number"

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6007]
**Environment:** All
**Reproducible:** always
**Build found:** 28/06/2023

**Preconditions**

1. User should be logged
2. Go to https://www.greencity.social/#/ubs/order

**Steps to reproduce**

1. In the section "Eco-shop" click the mouse on the field "Order numbers" but does not enter data there
2. Click the mouse outside the field "Order number"
3. In the section "Eco-shop" in the field "Order number" enter more than 8 symbols
4. Click the mouse outside the field "Order number"

**Actual result**
Steps 1-2.
After clicking the mouse outside the field "Order number" an error message "The number was entered incorrectly. Please try again." appears under the field "Order number"
Steps 3-4
An error message "The number was entered incorrectly. Please try again."  appears only after clicking the mouse outside the field "Order number"

**Expected result**
Steps 1-2. There are no changes on the page. User can do next steps
Steps 3-4. After entering 9 symbols an error message "The number was entered incorrectly. Please try again." appears under the field "Order number"

**User story and test case links**
https://github.com/ita-social-projects/GreenCity/issues/2379
https://github.com/ita-social-projects/GreenCity/issues/5981
[Test case]https://jira.softserve.academy/browse/GC-7183
https://jira.softserve.academy/browse/GC-7182

https://github.com/ita-social-projects/GreenCity/assets/128155213/4cb369f1-60d4-4eab-a997-74e109f1919d

https://github.com/ita-social-projects/GreenCity/assets/128155213/4cfaf6c0-019d-4645-b460-6a49775d00c2

**Comment by DanaIuich** [comment]
An error message "The number was entered incorrectly. Please try again." appears under the field "Order number" when user enters less than 9 symbols.

https://github.com/ita-social-projects/GreenCity/assets/128155213/62ea8b22-c559-4d81-89d4-189a6fc53f8e

**Comment by Tadei-Mykola** [comment]
Now, the Eco-Shop number can be from 4 to 10.
