### ISSUE TITLE
[Order form] The wrong name's link “Додати іншу адресу" below section “Адреса вивозу відходів”

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6015]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 30.06.2023
Preconditions

1. User is logged in https://www.greencity.social/#/greenCity
2. The user has not yet specified any garbage collection address in their profile
3. The user makes an order
4. The user filled in the tab 'Деталі замовлення' 

Steps to reproduce

1. Click on the 'Далі'  button
2. Pay attention to the name of the link in the 'Адреса вивезення відходів' section аt the tab 'Персональні дані'

Actual result
The name link is “Додати іншу адресу"
Expected result
The name link is “Додати адресу"

"User story #2199 

**Labels to be added**
"Bug", Priority ("low "), Severity ("minor"), Type ("UI")

**Comment by Maksym8Kravchenko** [comment]
This bug is not fixed

**Comment by sobkiv** [comment]
Because it's not merged yet, sorry! When it is merged I'll put it in Bugs retesting again.

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
