### ISSUE TITLE
[Order form] The house number is not fully saved in section “Адреса вивозу відходів”

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6016]
![Number house in Garbage collection address](https://github.com/ita-social-projects/GreenCity/assets/131760121/39e2cfcb-4ab6-4a74-8329-457b5f6247f7)
![Number house in New address](https://github.com/ita-social-projects/GreenCity/assets/131760121/587ea66d-1053-4979-8ecb-86840dd1e6d9)
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 30.06.2023
Preconditions

1. User is logged in https://www.greencity.social/#/greenCity
2. The user makes an order
3. The user filled in the tab 'Деталі замовлення'

Steps to reproduce

1. Click on the 'Далі' button
2. Click on the link 'Додати іншу адресу'
3. The field 'Область' displays 'Kyiv oblast'
4. Select in the field 'Місто' 'Bucha'
5. Select in the field 'Вулиця' 'Energetykiv Street'
6. The field 'Район' displays 'Brovars'kyi district'
7. Type and select in the field 'Будинок' '7-0'
8. Click on the 'Додати адресу' button

Actual result
Section "Адреса вивозу відходів" contains the Address 'City Bucha Brovars'kyi district Energetykiv Street house 7 Kyivs'ka oblast
Expected result
Section "Адреса вивозу відходів" contains the Address 'City Bucha Brovars'kyi district Energetykiv Street house 7-0 Kyivs'ka oblast
 "User story #2199
**Labels to be added**
"Bug", Priority ("high"), Severity ("major"), Type ("Functional")

**Comment by dmytro-kryvyi** [comment]
The address is sent in full, but the house number is truncated in the reply from back-end
![image](https://github.com/ita-social-projects/GreenCity/assets/94367438/56173a42-b37d-4ddf-8966-02b4a130c0f9)
