### ISSUE TITLE
['Create habit' page edit mode] Inability to Invite Friends by Email or Username 

### ISSUE THREAD

**Issue by yanakhoma** [ita-social-projects/GreenCity#6022]
**Environment:**
OS: macOS Ventura 13.4
Browser: Google Chrome Version 114.0.5735.133
Reproducible: always

**Pre-conditions**
1. Registered user is logged in https://www.greencity.social/.
2. “My space” page is open.

**Steps to Reproduce**
1. Click on the 'Add New Habit' button.
2. Click on the 'Create habit' button.
3. Locate the ‘Invite friends' field.
4. Click on the '+' badge

**Expected result**
There should be options or input fields available to invite friends by entering their email address or username.

**Actual result**
There are no options or input fields provided to invite friends using their email or username. The user is not able to add friends through these methods.

**Screenshots**
<img width="1440" alt="3" src="https://github.com/ita-social-projects/GreenCity/assets/134542525/42586a70-c62f-43f3-9008-93f234af94eb">

**User story and test case links**
"Change request to #1001 . Add new custom habit https://github.com/nromanen/pratical_testing_2022/issues/192"

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed
