### ISSUE TITLE
['Create habit' page edit mode] Inconsistency in the information message after Picture Upload 

### ISSUE THREAD

**Issue by yanakhoma** [ita-social-projects/GreenCity#6023]
**Environment:**
OS: macOS Ventura 13.4
Browser: Google Chrome Version 114.0.5735.133
Reproducible: always

**Pre-conditions**
1. Registered user is logged in https://www.greencity.social/.
2. “My space” page is open.

**Steps to Reproduce**
1. Click on the 'Add New Habit' button.
2. Click on the 'Create habit' button.
3. Locate the ‘Picture (optional)’ field.
4. Upload file with 'webp' format.

**Expected result**
The information message should be displayed as "Upload PNG or JPG only. File size should be less than 10MB" and highlighted in red to indicate the importance of the message.

**Actual result**
The information message is displayed as "Download PNG or JPG only. File size should be less than 10MB" instead of "Upload PNG or JPG only. File size should be less than 10MB".

**Screenshots**
<img width="1440" alt="4" src="https://github.com/ita-social-projects/GreenCity/assets/134542525/57c0c5e0-d251-4b59-8627-b26f852c57c2">

**User story and test case links**
"Change request to #1001 . Add new custom habit https://github.com/nromanen/pratical_testing_2022/issues/192"

**Comment by Vadym840217** [comment]
![grey_to_red](https://github.com/ita-social-projects/GreenCity/assets/130633728/72366b1e-6153-418f-a41d-ef30f23f1ce6)
The information message is changed correctly, but highligted in grey color, must be in RED.

**Comment by mdashko** [comment]
I will fix itSent from my iPhoneOn 10 Aug 2023, at 12:03 PM, Vadym ***@***.***> wrote:﻿
The information message is changed correctly, but highligted in grey color, must be in RED.
