### ISSUE TITLE
[API] [Eco-news-comment-controller] Status 200OK is displayed when entered the wrong {parentCommentId}

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/GreenCity#6041]
**Environment:** Windows 11,
Google Chrome Version 111.0.5563.147 (64-bit)

**Reproducible:** Always

**Preconditions**
Website https://greencity.greencity.social/swagger-ui.html#/ is opened.

**Steps to reproduce**

1. Chose to GET /econews/comments/replies/active/513?page=0&size=5&sort=desc
2. Click the 'Send' button.
3. Check a response.

**Actual result**
Status code 200

**Expected result**
Status code 404

**Comment by Vadym840217** [comment]
This bug is fixed.
