### ISSUE TITLE
[API] [Event-comment-controller] 401 code is returned in requests where authorization is not required.

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/GreenCity#6043]
**Environment:** Windows 11,
Google Chrome Version 111.0.5563.147 (64-bit)

**Reproducible:** Always

**Preconditions**
Website https://greencity.greencity.social/swagger-ui.html#/ is opened.

**Steps to reproduce**

1. Chose to GET /econews/comments/actives?ecoNewsId=151 AND /econews/comments/countreplies/0?page=0&size=5&sort=desc
2. Click the 'Send' button.
3. Check responses.

**Actual result**
Status code 401 Unauthorized

**Expected result**
Status code 404

**Comment by ABbondar** [comment]
retest please
