### ISSUE TITLE
Infinity loop after logout

### ISSUE THREAD

**Issue by Vadym840217** [ita-social-projects/GreenCity#6046]
**Environment:**
OS: Windows 10 Pro, OS build : 19045.2965
Browser Google Chrome, Version: 114.0.5735.199 (Official Build) (64-bit)

**Reproducible:** 
always

**Preconditions:**
* Registered User is logged in
* 'My habits' tab in user's 'My space' page is opened

**Steps to reproduce**
1. Click on 'Add New Habit' button
2. Click on 'More' button on unadded standard habit
3. Click on 'Cancel' button
4. Logout

**Actual result**
* User redirects to [greencity main page](https://www.greencity.social/#/greenCity)
* User is logout
* Infinity loop of login window

**Expected result**
* User redirects to [greencity main page](https://www.greencity.social/#/greenCity)
* User is logout

https://github.com/nromanen/pratical_testing_2022/assets/130633728/224e477f-5c2a-4382-870e-b95809a167a8

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. tnx
