### ISSUE TITLE
[UBS courier] On the order form page of the "Деталі замовлення" step, the application allows the user to go to the next step "Особисті дані" by use the "Далі" buttonwhen the user does not select any item

### ISSUE THREAD

**Issue by Maksym8Kravchenko** [ita-social-projects/GreenCity#6052]
**Environment:**Windows 11 Home, Chrome 114.0.5735.199
Reproducible: always.
**Build found:**10.07.2023

Preconditions

1. Be able to log in as an administrator
2. Have a user to log in to the system
3. Page https://www.greencity.social/#/ubs is opened

Steps to reproduce
1. Log in as administrator
2. Go to the "Тарифи" tab
3. Click on any location (for example, " Харківська область, Харків")
4. In the "Ліміти" block, under the "Ліміти замовлення" title, select the radio button for "Сума замовлення"
5. In the two fields for input enter the limits of the order (for example, 3 and 300)
6. Click on the "Зберігти зміни" button.
7. Log out of the application
8. Log in to the application as a user
9. Click on the "Замовити" button
10. Make sure that the location "Харківська область, Харків" is selected
11. If another location is selected then:
- Click on the "Змінити локацію" button
- In the pop-up window that opens, click on the input field and click on "Київська область 20 кілометрів"
- Click on the "Продовжити" button
12. Scroll down the page and click on the "Далі" button

**Actual result**
The "Next" button is active. The application allows the user to go to the next page "Особисті дані"

**Expected result**
The 'Далі' button should be disabled, the application should not allow the user to go to the next page 'Особисті дані'

**Postconditions**
Log in as an administrator and return the tariff that has been changed to the previous values (for example, for Харківська область, Харків" - select the "Number of packages" radio button, the number of packages is at a minimum of 2)

**User story and test case links**
Pay atteintion on the Aceptance critetia nubmer 5

https://github.com/ita-social-projects/GreenCity/assets/127987815/435b1cc1-c820-4c75-8494-e250b350e139

 
[Change request to #2196](https://github.com/ita-social-projects/GreenCity/issues/2379)

**Labels to be added**
"Bug", Priority ("medium "), Severity ("minor:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by RudnevaOlena** [comment]
Retesting was on the MacOs 13.3.1 (a), Chrome Version 114.0.5735.198 (Official Build) (arm64) - works as expected
