### ISSUE TITLE
[UBS Admin.Orders] Admin cannot save changes in the 'Information about client(Sender)' block after modifying the information.

### ISSUE THREAD

**Issue by Tadei-Mykola** [ita-social-projects/GreenCity#6055]
Environment:
Windows 11 Pro (Version 22H2)
Chrome version 114.0.5735.199

Reproducible: always, 
Build found: 11/07/2023

Preconditions
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs
2. Sign in as Super Admin
3. Go to the Super Admin profile and choose the UBS-Admin item
4. Choose the 'Orders' item
5. Click on the Order's number in the Order table (except orders with 'Done'/ 'Canceled' statuses)

Steps to reproduce
1. Go to the block 'Information about client of Sender'
2. Change Name, Surname, Phone or Email 
3. Scroll down to the save button and click on

Actual result
The block 'Information about client(Sender)' is not changed

Expected result
The block 'Information about client(Sender)' must contain modified information

https://github.com/ita-social-projects/GreenCity/assets/117460264/51da6eb5-02a6-44b9-a26b-e4002e48de28

**Comment by Maksym8Kravchenko** [comment]
The admin has no permission to edit the data of the sender.
This is already not a bug. This functionality work is correct.
Tnx.
