### ISSUE TITLE
[API] Not correct end-point GET /ubs/management/{userId}/ordersAll

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6064]
**Environment:** Windows 11 IoT Enterprise, Firefox 115.0.2 (64-bit).
**Reproducible:** always.

**Preconditions**
Must be opened https://greencity-ubs.greencity.social/swagger-ui.html#/
Must be opened Postman
Opened [admin-ubs-controller]
Must be created Sign-In request to use this end-point

**Steps to reproduce**
1. (Postman) Choose method GET
2. (Postman) Enter link - https://greencity-ubs.greencity.social/ubs/management/ordersAll
3. (Postman) Enter the data as described in Swagger - GET /ubs/management/{userId}/ordersAll
4. (Postman) Save and send requiest.

**Actual result**
Response - 404 Not found

**Expected result**
Response - 200 OK

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/27d1053a-db8a-4573-85f8-1f9354cb4098)

**Comment by HelenSotnik** [comment]
Bug Retesting needed.
Endpoint GET /ubs/management/{userId}/ordersAll works both in Swagger and Postman.

**Steps to reproduce**

1)(Postman) Choose method GET
2)(Postman) Enter link - https://greencity-ubs.greencity.social/ubs/management/1/ordersAll 
(1 or other existing  userId)
3)(Postman) Enter the data as described in Swagger - GET /ubs/management/{userId}/ordersAll 
It is neccessary to insert 2 params "column" and "sortingType". Column (any column name in table order, or use "id" as value). And the last  - path variable is userId, it should not be in Params( userId should be a part of URL). 
4)(Postman) Save and send requiest.  

**Expected result** 
Response - 200 [OK]

**Actual result** 
Response - 200 [OK]

![Postman-ordersAll](https://github.com/ita-social-projects/GreenCity/assets/63450632/a79f4a4f-054e-45ba-ad17-78ca1a07c15c)
![Swagger-ordersAll](https://github.com/ita-social-projects/GreenCity/assets/63450632/57dd021e-f7ff-4127-8fdf-b60bd5b31098)
