### ISSUE TITLE
[API] Not correct  end-point PUT ubs/management/blockOrders

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6065]
**Environment:** Windows 11 IoT Enterprise, Firefox 115.0.2 (64-bit)..
**Reproducible:** always.

**Preconditions**
Must be opened https://greencity-ubs.greencity.social/swagger-ui.html#/
Must be opened Postman
Opened [admin-ubs-controller]
Must be created Sign-In request to use this end-point

**Steps to reproduce**
1. (Postman) Choose method PUT
2. (Postman) Enter link - https://greencity-ubs.greencity.social/ubs/management/blockOrders
3. (Postman) Enter the data as described in Swagger - /ubs/management/blockOrders
4. (Postman) Save and send requiest.

**Actual result**
Response - 500 Internal Server Error

**Expected result**
Response - 200 OK

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/62d7c070-5a5b-4a4d-bce3-8663ed08f4bb)

**Comment by HelenSotnik** [comment]
**Bug retesting needed.**
End-point /ubs/management/blockOrders works correctly.

**Preconditions**
Must be opened https://greencity-ubs.greencity.social/swagger-ui.html#/
Must be opened Postman
Opened [admin-ubs-controller]
Must be created Sign-In request to use this end-point

**Steps to succeed during testing:**
1)(Postman) Choose method PUT
2)(Postman) Enter link - https://greencity-ubs.greencity.social/ubs/management/blockOrders
3)(Postman) Enter the data as described in Swagger - /ubs/management/blockOrders
    3.1) listOfOrdersId NOT recommeded to add as Params in Postman. As it is not a parameter, but a requested Body. (if will be added as a param - URL looks like  : 
https://greencity-ubs.greencity.social/ubs/management/blockOrders?listOfOrdersId= 
It will lead to Error Status Code:500.
   3.2)Add to Body in Postman listOfOrdersId in form of:
[
  26
]
(inside of brackets should be one ore more orderId, in database you may choose any from (11,12,13,14,23,24,25,26,30,31)
If there will be not existing orderId or empty body added - Error with Status Code:500.
4)(Postman) Save and send requiest.

**Expected result**
Response - 200 [OK]

**Actual result**
Response - 200 [OK]

**Postconditions**
If any order is blocked, you may unblock them in swagger by end-point the same way
/ubs/management/unblockOrders

Photo with execution of end-poin work is added below. Please mention, I have worked with local database and my parameters are those that are present in my database. 

![blockOrder](https://github.com/ita-social-projects/GreenCity/assets/63450632/1826439d-6842-42b0-b618-a34e69f0b6f0)
![blockOrder2](https://github.com/ita-social-projects/GreenCity/assets/63450632/ed717202-b575-4f5d-9511-79379b357652)
![blockOrder3](https://github.com/ita-social-projects/GreenCity/assets/63450632/b4f4eb86-b22d-46ad-aedf-8ea93aad1e17)
