### ISSUE TITLE
[API] Not correct end-point GET users for the table

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6068]
**Environment:** Windows 11 IoT Enterprise, Firefox 115.0.2 (64-bit).
**Reproducible:** always.

**Preconditions**
Must be opened https://greencity-ubs.greencity.social/swagger-ui.html#/
Must be opened Postman
Opened [admin-ubs-controller]
Must be created Sign-In request to use this end-point

**Steps to reproduce**
1. (Postman) Choose method GET
2. (Postman) Enter link - https://greencity-ubs.greencity.social/ubs/management/usersAll
3. (Postman) Enter the data as described in Swagger - GET /ubs/management/usersAll
4. (Postman) Save and send requiest.

**Actual result**
Response - 400 Bad Request

**Expected result**
Response - 200 OK

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/d2ae5929-a837-4a62-9f79-4e2281391a84)

**Comment by ospodaryk** [comment]
Bug Retesting needed.
Endpoint GET /ubs/management/{userId}/ordersAll works both in Swagger and Postman.

Steps to reproduce

1)(Swagger) Choose method GET : /ubs/management/usersAll
2)(Swagger) Don't enter any values, just execute
<img width="754" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/82940222/95cf5684-55ac-4515-8258-7b0ae9cd2133">

Expected result
Response - 200 [OK]

Actual result
Response - 200 [OK]

<img width="399" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/82940222/5f8198fa-cc0f-4238-926f-683739daadfb">
