### ISSUE TITLE
[UBS-User.Edit Profile] The 'Дані користувача' page isn't opened and error notification is appeared

### ISSUE THREAD

**Issue by YuliaValkovets** [ita-social-projects/GreenCity#6069]
**Environment:** OS: Windows 11 Pro; Browser: Google Chrome 114.0.5735.199 
**Reproducible:** sometimes 
**Build found:** 14.07.2023

**Preconditions**
1. The User is authorized on the site https://www.greencity.social/#/ubs;
2. 'Дані користувача' page is opened.

**Steps to reproduce**
1. Click on "Редагувати дані" button;
2. Click on 'Додати адресу' button;
3. Fill in all mandatory fields (Region - 'Київська область', City - 'Зазим'є', Street - 'Лісова', House - '12', District - 'Броварський');
4. Click on 'Додати адресу' button;
5. Click on tab 'Дані користувача'.

**Actual result**
The 'Дані користувача' page isn't opened and error notification is appeared.

**Expected result**
Address is added and 'Дані користувача' page is opened.

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Major"), Type ("Functional")
![errorprofile](https://github.com/ita-social-projects/GreenCity/assets/135055962/1fb2a216-eb92-4ff6-aee3-ce1dd4835f9f)
![errorprofile2](https://github.com/ita-social-projects/GreenCity/assets/135055962/524df371-bc72-4773-aae5-666d3d446a3a)

**Comment by DanaIuich** [comment]
Bug is fixed
