### ISSUE TITLE
[Orders] Logistician can edit an order card

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6073]
https://github.com/ita-social-projects/GreenCity/assets/128155213/5d185934-b821-4223-8f76-7b91a425258c

https://github.com/ita-social-projects/GreenCity/assets/128155213/276971ef-6511-46a4-a25d-315bc184dfc1

**Environment:** All
**Reproducible:** always
**Build found:**17/07/2023

**Preconditions**

1. User shoud be on the position logistician
2. User shoud be logged
3. Go to https://www.greencity.social/#/ubs-admin/orders

**Steps to reproduce**

1. In tab "Orders" choose an order number
2. In section "Order payment" click on "Add payment" button
3. Fill all fields in  pop-up window "Add a payment document" (choose Payment date, enter Payment amount (UAH) and Payment ID, select radio button "Link to electronic bill" and add there any link)
4. Click on "Confirm payment" button
5. Click on "Save" button in the bottom of the page "Orders".

**Actual result**
Information in the section "Order payment" is changed accroding to to the changes made. 

**Expected result**
Logistician can not edit an order card and add payment

**User story and test case links**
E.g.: https://github.com/ita-social-projects/GreenCity/issues/5538

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
