### ISSUE TITLE
[Orders] Logistician can see the main page “Notifications ”

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6074]
**Environment:** All
**Reproducible:** always
**Build found:** 17/07/2023

**Preconditions**

1. User shoud be on the position logistician
2. User shoud be logged
3. Go to https://www.greencity.social/#/ubs-admin/notifications

**Steps to reproduce**

1. Go to tab "Notofication"

**Actual result**
The main page of the tab "Notification" is opened with information about notifications.

**Expected result**
Logistician can not see the main page “Notifications ”

**User story and test case links**
E.g.: https://github.com/ita-social-projects/GreenCity/issues/5538

<img width="889" alt="main_page_notifications" src="https://github.com/ita-social-projects/GreenCity/assets/128155213/5568aea3-c20e-4c2a-bedd-c822d940b64c">

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
