### ISSUE TITLE
[Orders] Logistician can edit a notification card 

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6075]
**Environment:** All
**Reproducible:** always
**Build found:** 17/07/2023

**Preconditions**

1. User shoud be on the position logistician
2. User shoud be logged
3. Go to https://www.greencity.social/#/ubs-admin/notifications

**Steps to reproduce**
1. On the page "Notification" click on notification card
2. Try to activate/inactivate notifiction topic
3. Change the name of notification topic
4. Change the text of "Site", "Email", "Mobile"
5. Click on "Save changes" button

**Actual result**
Logistician can edit a notification card. 

**Expected result**
Logistician can not edit a notification card. 

**User story and test case links**
E.g.: https://github.com/ita-social-projects/GreenCity/issues/5538

https://github.com/ita-social-projects/GreenCity/assets/128155213/72b34482-4efb-4ce5-8503-8a59ae7210f9

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
