### ISSUE TITLE
[Orders] Navigator can edit an order card

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6076]
**Environment:** All
**Reproducible:** always
**Build found:** 18/07/2023

**Preconditions**

1. User shoud be on the position navigator
2. User shoud be logged
3. Go to https://www.greencity.social/#/ubs-admin/orders

**Steps to reproduce**

1. In tab "Orders" choose an order number
2. In section "Order payment" click on "Add payment" button
3. Fill all fields in pop-up window "Add a payment document" (choose Payment date, enter Payment amount (UAH) and Payment ID, select radio button "Link to electronic bill" and add there any link)
4. Click on "Confirm payment" button
5. Click on "Save" button in the bottom of the page "Orders".
6. Find an order card and verify if the changes are saved

**Actual result**
Information in the section "Order payment" is changed accroding to to the changes made.

**Expected result**
Navigator can not edit an order card and add payment

**User story and test case links**
E.g.: https://github.com/ita-social-projects/GreenCity/issues/5538

https://github.com/ita-social-projects/GreenCity/assets/128155213/9c48c427-6909-4896-9fe5-0b8050e203b8

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
