### ISSUE TITLE
[Orders] Navigator can see the main page “Notifications ”

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6077]
**Environment:** All
**Reproducible:** always
**Build found:**18/07/2023

**Preconditions**

1. User shoud be on the position navigator
2. User shoud be logged
3. Go to https://www.greencity.social/#/ubs-admin/notifications

**Steps to reproduce**

1. Go to tab "Notofication"

**Actual result**
The main page of the tab "Notification" is opened with information about notifications.

**Expected result**
Navigator can not see the main page “Notifications ”

**User story and test case links**
E.g.: https://github.com/ita-social-projects/GreenCity/issues/5538

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
