### ISSUE TITLE
[UBS-User.Edit Profile] The name of the radio button in the address part has incorrect text.

### ISSUE THREAD

**Issue by oksanakushnir** [ita-social-projects/GreenCity#6095]
**Environment:** all
**Reproducible:** always
**Build found:** 24/07/2023

**Preconditions**
1. The registered user is logged in https://www.greencity.social/#/ubs
2. User data tab is opened

**Steps to reproduce**
1.	Click on “Edit data” button
2.	Check the name of the radio button in the address section

**Actual result**
The name of the radio button in the address part has incorrect text "за умовчуванням".
![incorrect text](https://github.com/ita-social-projects/GreenCity/assets/130609090/bbca06a2-25e6-4ae1-9d65-9ffc357739d8)

**Expected result**
The name of the radio button in the address part should be "за замовчуванням".

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Low"), Type ("UI").

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed
