### ISSUE TITLE
[UBS-User.Edit Profile] 'User data', In the address the radio button icon is corrupted.

### ISSUE THREAD

**Issue by oksanakushnir** [ita-social-projects/GreenCity#6098]
**Environment:** MacOS Monterey 12.6.7,  Safari 16.5.1
**Reproducible:** always
**Build found:** 24/07/2023

**Preconditions**
1. The registered user is logged in https://www.greencity.social/#/ubs
2. User data tab is opened

**Steps to reproduce**
1. Click on “Edit data” button.
2. Scroll down to 'Address' section
3. Check radio button

**Actual result**
Right side of radio button icon is cut.

![radio button](https://github.com/ita-social-projects/GreenCity/assets/130609090/61213348-7111-4c3b-a8c4-ac8ffdc4c2b3)

**Expected result**
The radio button icon should be fully displayed.

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Minor"), Type ("UI")

**Comment by DanaIuich** [comment]
Bug is fixed
