### ISSUE TITLE
[Employee (Admin cabinet)] The 'Cancel' button should be enabled by default in 'Set employee permissions'

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6100]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 25.07.2023
Preconditions

1. Website https://www.greencity.social/#/greenCity is opened
2. The user should be logged in as a Super Admin

Steps to reproduce

1. Click on the 'Employee' tab
2. In the tab 'Employee' choose the Employee
3. In pop-up window click on 'Set Employee permissions'
4. Pay attention to the 'Cancel' button

Actual result
The 'Cancel' button is disabled by default

Expected result
The 'Cancel' button should be enabled by default
 User story #4617 

"Bug", Priority ("low"), Severity ("minor"), Type ("UI")
![Cancel button](https://github.com/ita-social-projects/GreenCity/assets/131760121/e774b2b4-fddc-43f4-b036-18c7bd37d4ae)

**Comment by Maksym8Kravchenko** [comment]
This bug is not fixed
