### ISSUE TITLE
[User's personal cabinet]The first name and last name of the employee are displayed in one word in 'Edit Profile'

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6105]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 25.07.2023
Preconditions

1. The user should be logged in  https://www.greencity.social/#/greenCity as a Super Admin 

Steps to reproduce

1. Click on the 'Employee' tab
2. Click on the 'Add an employee'
3. Fill in all required fields (e.g. First name: Yarema Last name: Lira)
4. Select 'Position' and 'Tariffs'
5. Click on the 'Add'
6. New adding employee logs in to their profile
7. Click on the icon in the upper right corner
8. In pop-up window  click on "Settings"
9. Pay attention to the 'Name field'

Actual result
The 'Name field' displays the 'First name' and 'Last name' data employee  

Expected result
The 'Name field' should display the data 'First name' employee  
User story https://github.com/ita-social-projects/GreenCity/issues/4617, https://github.com/ita-social-projects/GreenCity/issues/3811

"Bug", Priority ("Medium"), Severity ("Major"), Type ("UI"), "API" (for back-end bugs)
![first name and last name admin](https://github.com/ita-social-projects/GreenCity/assets/131760121/bd8c1018-31b9-433b-83b1-3b6f20a8268e)
![Name employee](https://github.com/ita-social-projects/GreenCity/assets/131760121/1af287cb-ed0b-47c7-b418-ba1e05868af2)

**Comment by ospodaryk** [comment]
Bug Retesting needed.
If the user enters such a value as his name during registration, it will be displayed exactly like this. 
This is a nickname chosen by the user during registration or editing.
