### ISSUE TITLE
[Employee (Admin cabinet)] The Super Admin cannot check  the checkbox 'Deactivate the pricing card' for employees

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6107]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 25.07.2023
Preconditions

1. Website https://www.greencity.social/#/greenCity is opened
2. The user should be logged in as a Super Admin
3. Super Admin should add an employee with a Driver position

Steps to reproduce

1. Click on the 'Employee' tab
2. In the tab 'Employee' choose the Employee with a Driver position
3. In pop-up window click on 'Set Employee permissions'
4. Click on 'Tarrifs' drop-down
5. Check on the checkbox "Deactivate the pricing card"
6. Click on the 'Save' button
7. Click on 'Set Employee permissions' again
8. Click on 'Tarrifs' drop-down
9. Verify that check on the checkbox "Deactivate the pricing card"

Actual result
The checkbox "Deactivate the pricing card" is unchecked

Expected result
The checkbox "Deactivate the pricing card" should be checked 

User story https://github.com/ita-social-projects/GreenCity/issues/4617

Labels to be added
"Bug", Priority ("high"), Severity ("major"), Type ("Functional")

Uploading Super Admin cannot check  the checkbox 'Deactivate the pricing card'.mp4…

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed. Tnx
