### ISSUE TITLE
[UBS-User. Edit Profile] The 'Save changes' button is enabled when the User entered data manually

### ISSUE THREAD

**Issue by KaterinaUrizko** [ita-social-projects/GreenCity#6120]
**Environment:** Windows 11 Home Chrome 114.0.5735.91 (Official buid) (64-bit).
**Reproducible:** always.
**Build found:** 

When User changes the existing address data in the fields: Region, City, Street it is possible to enter the data manually and the “Save changes” button becomes enabled. If you click on the “Save changes” button, the notification that changes are saved appears. The last changed data is displayed on the ‘User Data’ page. After the page refreshing the old data, which was before editing, is displayed.

**Preconditions**
1. The User is authorized  and logged in the site https://www.greencity.social/#/ubs;
2. 'User Data' page is opened.
3. User has at least one saved Address in profile 

**Steps to reproduce**
1. Click on 'Edit data' button
2. Earase the data of the 'Street' text field of Address 1
4. Enter manually new data (e.g. TestTest)

**Actual result**
The 'Save changes' button is enabled. When you click on it, the notification 'Your changes have been saved' appeares, and User is redirected to the 'User Data' page. The new street name is displayed in the 'Street' textfield (e.g. TestTest). After refreshing of the page the previous name of the street is displayed in the 'Street' textfield.

**Expected result**
The ‘Save changes’ button is enabled only if User selects data from the drop-down list. Applies to data pulled via API (Region, city, street, house numbers, district) The field with manually entered data is highlighted in red, the label "Select from list" appears

**User story and test case links**
 "User story #3811 
[Test case](https://jira.softserve.academy/browse)"

![StreetTest](https://github.com/ita-social-projects/GreenCity/assets/93221162/d2af47da-4a7a-4996-8820-e68b71014e3d)
![StreetTest1](https://github.com/ita-social-projects/GreenCity/assets/93221162/f4dce1b2-cf53-4af6-b866-0a74a2073541)

**_After refreshing_previously saved data is displayed**

![StreetTest2](https://github.com/ita-social-projects/GreenCity/assets/93221162/6e735b24-5b0d-495a-b503-5d6bbb6f261b)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maksym8Kravchenko** [comment]
This bug is fixed
