### ISSUE TITLE
[UBS-User. Edit Profile] Numeric data entered in the Name and Surname text fields is not saved

### ISSUE THREAD

**Issue by KaterinaUrizko** [ita-social-projects/GreenCity#6125]
**Environment:** Windows 11 Home Chrome 114.0.5735.91 (Official buid) (64-bit)
**Reproducible:** always,
**Build found:** 28.07.2023

When the User enters numeric data in the Name and Surname text fields, the data is not saved.

**Preconditions**

1.The User is authorized and logged in the site https://www.greencity.social/#/ubs;
2.'User Data' page is opened.
3. User profile is filled in.

**Steps to reproduce**
1. Click on 'Edit data' button
2. Add numeric data to existed Name and Surname (eg. 95)
3. Click on "Save changes" button

**Actual result**
Appears notification "Your changes is saved", the User is redirected to User Profile page, appearce notification 

https://github.com/ita-social-projects/GreenCity/assets/93221162/e8b660c2-8260-497b-9ca0-72692c3a1d1e

**Expected result**
Appears notification "Your changes is saved", the User is redirected to User Profile page, the changed data is displayed in Profile.

**User story and test case links**
E.g.: "User story #3811 

**Labels to be added**

**Comment by DanaIuich** [comment]
Bug is fixed
