### ISSUE TITLE
[Admin cabinet (Employees tab)] Can't to unmark item in drop-down menu 'Position' in English website version 

### ISSUE THREAD

**Issue by Vadym840217** [ita-social-projects/GreenCity#6141]
**Environment:** Google Chrome, Version: 114.0.5735.199 (Official Build) (64-bit)
Windows 10 Pro, OS build : 19045.2965

**Reproducible:** always

**Preconditions**
1. Website https://www.greencity.social/#/greenCity is opened
2. User logged in as Admin
3. User is in Admin cabinet
4. Tab 'Employees' is opened
5. Page is switched to English

**Steps to reproduce**
1. Click on 'Position' drop-down menu
2. Click on choosen item (any)
3. Click on the same item again (to unmark it)

**Actual result**
Chosen item is added again, user can't unmark it.

**Expected result**
Chosen item  is unmarked.

"Bug", Priority ("Medium"), Severity ("Major"), Type ("Functional").

https://github.com/ita-social-projects/GreenCity/assets/130633728/29748ee9-1fdb-4e65-b07f-bb2958ebf3b9

**Comment by dmytro-kryvyi** [comment]
Does not reproduce
