### ISSUE TITLE
[UBS-User. Edit Profile] The mouse cursor is changing to hand  when hovering over the Telegram and Viber togglers. 

### ISSUE THREAD

**Issue by KaterinaUrizko** [ita-social-projects/GreenCity#6145]
**Environment:** Windows 11 Home Firefox 114.0.2 (64-біт)
**Reproducible:** always
**Build found:**  08.08.2023

**Preconditions**

1.The User is authorized and logged in the site https://www.greencity.social/#/ubs;
2.'User Data' page is opened.
3. User profile is filled in.

**Steps to reproduce**
1. Move the mouse cursor to the Telegram or Viber toggler

**Actual result**
The mouse cursor changes to hand when hovers over the Telegram or Viber toggler.

**Expected result**
The mouse cursor does not change its shape

**User story and test case links**
E.g.: "User story #3811

**Labels to be added**

https://github.com/ita-social-projects/GreenCity/assets/93221162/7e52dfd0-e5dd-4466-8072-6efae26bdd4b

**Comment by Vadym840217** [comment]
Not a bug, haven't found any restrictions in both mockups and requirements
