### ISSUE TITLE
[UBS Address] District value is not visible when editing an address in EN mode

### ISSUE THREAD

**Issue by katia9261** [ita-social-projects/GreenCity#6154]
**Environment:** Windows 10 Google Chrome 113.0.5672.93
**Reproducible:** always
**Build found:** 10.08.2023

**Preconditions**
1.  The user should be logged in https://www.greencity.social/#/ubs as a user
2. User has at least 1 address (for example like on the screenshot)
3. There is 'EN' mode

**Steps to reproduce**
1. Go to UBS main page
2. Click on 'Order' btn
3. Go to the second step of the order
4. Click on the 'Edit address icon'

**Actual result**
The user doesn't see the district value due to using different services for handling address and district information, leading to inconsistency in the English language spelling.![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/79438e32-a3d7-4f02-81fa-8b0641c7a609)

**Expected result**
The user should see the district value when editing the address
![image](https://github.com/ita-social-projects/GreenCity/assets/101433204/fe683320-49cb-4ab7-8cca-23500aa6f7b6)

**Comment by Mariia232** [comment]
Windows 10, Chrome 123.0.6312.86
