### ISSUE TITLE
[Edit Event #3195] Incorrect localization of 'Preview' button in Ukranian language

### ISSUE THREAD

**Issue by OleksandrOrlov2** [ita-social-projects/GreenCity#6161]
**Environment:** Windows 10 Pro 22Р2, Opera One V.100.0.4815.76.
**Reproducible:** always.
**Build found:** 5/8/23

**Steps to reproduce**
1. Open [GreenCity](https://www.greencity.social/#/greenCity)
2. Log in (as an Admin or Event Organizer).
3. Choose English language.
4. Click on 'Events'.
5. Click on 'More' button on Event Card.
6. Click on 'Edit" button.
7. Change language to Ukranian.
8. Look at 'Preview / Попередній перегляд' button.

**Actual result**
The text is overflowing the button.
![Screenshot_1](https://github.com/ita-social-projects/GreenCity/assets/140503680/a9d0433e-f851-4f9e-841f-624a8f0b20dc)

**Expected result**
The text does not overflow the button.

**User story and test case links**
E.g.: "User story #3195 #5146 #3193
[Test case](https://jira.softserve.academy/browse/GC-7365)

**Comment by Tadei-Mykola** [comment]
cannot reproduce
