### ISSUE TITLE
[Create event] The Menu Bar disappears and there is no horizontal scroll to display all the elements of the page when the user zooms the page to 200%

### ISSUE THREAD

**Issue by K-Denysyk** [ita-social-projects/GreenCity#6168]
[**Environment:**](url) OS: Ubuntu 22.04.2 LTS
Google Chrome
Version 114.0.5735.133 (Official Build) (64-bit)

**Reproducible:** always
**Build found:** 10.08.23
**Preconditions**

**Steps to reproduce**

1. Go to https://www.greencity.social/#/greenCity
2. Log in as User
3. Open the "Events" page
4. Press to "Create Event" button
5. Zoom page to 200%

**Actual result**
The Menu Bar disappears and there is no horizontal scroll

**Expected result**
All page elements are present, and horizontal/ vertical scrolling is available.

**Postconditions**

![Create Event 6](https://github.com/ita-social-projects/GreenCity/assets/130599672/191c5ddf-3999-4401-a8ba-baec157e3a9e)
![Create Event 8](https://github.com/ita-social-projects/GreenCity/assets/130599672/1c948f7f-c1ee-40e5-8c20-6528f7d55171)
![create event 1](https://github.com/ita-social-projects/GreenCity/assets/130599672/9dfe6d06-8853-4de8-890d-ec403f78bf4a)

**User story and test case links**
E.g.: "User story #3193 
[Test case](https://jira.softserve.academy/browse/GC-5612)"

**Labels to be added**

**Comment by sobkiv** [comment]
Is it a problem? Every page on the site main menu turns to burger menu when you zoom in to 150%

**Comment by K-Denysyk** [comment]
Hello, all information on the page should be available at 200% zoom. The "Eco News" button is hard to see when the menu is changed to a burger menu (I added a new attachment). Also, horizontal scrolling is required to access all buttons at 200% zoom.
![create event 1](https://github.com/ita-social-projects/GreenCity/assets/130599672/4f0d9c23-8c8e-4a7f-9e4e-7586e571b4a9)

**Comment by Mariia232** [comment]
![Monosnap GreenCity - Google Chrome 2024-04-15 20 1](https://github.com/ita-social-projects/GreenCity/assets/99343288/63fc4137-795c-414f-a55a-cb9b54748cb8)
![Monosnaps GreenCity - Google Chrome 2024-04-15 20 1](https://github.com/ita-social-projects/GreenCity/assets/99343288/de09c646-0901-432e-a4b2-20691ad19cd0)
The Menu Bar disappears and there is no horizontal scroll to display all the elements of the page when the user zooms the page to 200%
'Eco News', 'Events' buttons not showing when menu changed to hamburger menu at 200 zoom
