### ISSUE TITLE
[Edit Event #3195] When the Description text style is changed, the minimum number of characters decreases.

### ISSUE THREAD

**Issue by OleksandrOrlov2** [ita-social-projects/GreenCity#6176]
**Environment:** Windows 10 Pro 22Р2, Opera One V.100.0.4815.76.
**Reproducible:** always.
**Build found:** 05/08/23.

**Steps to reproduce**
1. Open https://www.greencity.social/#/greenCity
2. Log in as Admin or Event Organizer.
3. Click 'More' button on Event Card.
4. Click 'Edit' button.
5. Change text style in Description to bold.
6. Type in Description field.

**Actual result**
The minimum number of characters in Description is 4.
![Screenshot_1](https://github.com/ita-social-projects/GreenCity/assets/140503680/1b386b54-d16e-4f69-8630-1f16df6bd96a)
![Screenshot_2](https://github.com/ita-social-projects/GreenCity/assets/140503680/f29f342c-fc87-491a-88cd-2ce53d66a442)

**Expected result**
The minimum number of characters in Description is 20.

**User story and test case links**
E.g.: "User story #3193 #3195
[Test case](https://jira.softserve.academy/browse/GC-7374)

**Comment by Oleksandra-Kobets** [comment]
Still reproducible... if we  apply two styles to the text. In this case I tried "bold" with "italic" and event was successfully  published. 
**Env:**
Windows 11 Home, 64 bit Version22H2
Chrome  117.0.5938.132 64bit

Build found: 28.09.23

![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/fc8187ef-99be-4f9d-9cc8-5b3e1dc5031f)

**Comment by sobkiv** [comment]
cannot reproduce

**Comment by Oleksandra-Kobets** [comment]
Still reproducible 
**Steps to reproduce** 

1. Go to "Events" page 
2. Click on "Create Event" button
3. Fill in all required fields
4. Type text "1234" in description field 
5. Click on "Publish" button 
6. Apply to text "1234" in description - bold style and italic style 
7. Click on "Publish" button again 

![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/7a464958-a14b-4212-b9d2-40d9c5999210)
