### ISSUE TITLE
[Create Event #3193] Incorrect display of Event Type 'Close' on Event Preview Card

### ISSUE THREAD

**Issue by OleksandrOrlov2** [ita-social-projects/GreenCity#6179]
**Environment:** Windows 10 Pro 22Р2, Opera One V.100.0.4815.76.
**Reproducible:** always.
**Build found:** 06/08/23.

**Steps to reproduce**
1. Open https://www.greencity.social/#/greenCity
2. Log in as Admin or Event Organizer.
3. Open an Event with Event Type 'Close'.

**Actual result**
Type 'Event completed' is displayed.
![Screenshot_1](https://github.com/ita-social-projects/GreenCity/assets/140503680/dd014bf0-6d1b-4d4d-9351-ee397884872f)
![Screenshot_2](https://github.com/ita-social-projects/GreenCity/assets/140503680/b42763b1-5a0e-4c88-a718-a9326041527c)
![Screenshot_3](https://github.com/ita-social-projects/GreenCity/assets/140503680/d0826d66-d781-4a2f-be06-e360d763387a)

**Expected result**
Type 'Close' is displayed.

**User story and test case links**
E.g.: "User story #3193 #3195
[Test case](https://jira.softserve.academy/browse/GC-3116)

**Comment by OlenaPodkovyrova** [comment]
Re-tested. Working as expected
![image](https://github.com/ita-social-projects/GreenCity/assets/140602524/5728a4ad-15c7-40fe-bdec-51c4bc780c71)
