### ISSUE TITLE
[Footer/Event dashboard] User name of registered User not depicteded on event dashdoard after signing up

### ISSUE THREAD

**Issue by Priadkohrystyna** [ita-social-projects/GreenCity#6184]
**Environment:** Windows 11 Home, Microsoft Edge Version 115.0.1901.188 (Official) (64-bit)
**Reproducible:** always
**Build found:** 12.08.2023

**Preconditions**

**Steps to reproduce**

1. Go to https://www.greencity.social/#/greenCity
2. Go to Events page
3. log in as User (e.g. magnolia123@gmail.com, password-magnolia1!)

**Actual result**
The Controls of event dashdoard not match mockup, user name of logged in user is not depicted.

**Expected result**
The Controls of event dashdoard match mockup, user name of logged in user is depicted.

**Postconditions**

**User story and test case links**
E.g.: "User story #3197 
[Test case](https://jira.softserve.academy/browse/GC-5166)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![_thumb_418139](https://github.com/ita-social-projects/GreenCity/assets/106020174/a6f41c3a-544c-40a6-ab37-010cc29793a7)
![_thumb_418138](https://github.com/ita-social-projects/GreenCity/assets/106020174/24ea37ba-cfd3-4531-b948-cfe1f7b46aa3)

**Comment by dmytro-kryvyi** [comment]
Does not reproduce. Username is visible at header for registered user.
