### ISSUE TITLE
[Event dashboard] Quantity of "items found" after filter out "upcoming" events does not match quantity events depicted

### ISSUE THREAD

**Issue by Priadkohrystyna** [ita-social-projects/GreenCity#6189]
**Environment:**Windows 11 Home, Microsoft Edge Version 115.0.1901.188 (Official) (64-bit)
**Reproducible:** alway
**Build found:**12.08.2023

**Preconditions**

**Steps to reproduce**

1. Go to https://www.greencity.social/#/greenCity
2. Go to Event page
3. Apply "upcoming" filter

**Actual result**
Quantity of "items found" after filter out "upcoming" events does not match quantity events depicted on event dashboard.All existing events upcoming and past are depicted on event dashboard, sorted in order of  the last changes made in events.

**Expected result**
Quantity of "items found" after filter out "upcoming" are match quantity events depicted on event dashboard.

 

**User story and test case links**
E.g.: "User story #3197 #4907
[Test case](https://jira.softserve.academy/browse/GC-5738)"

**Labels to be added**
"Bug", 
![_thumb_418134](https://github.com/ita-social-projects/GreenCity/assets/106020174/54ed8116-7faf-4caa-9998-276adee5b13c)

**Comment by OlenaPodkovyrova** [comment]
Re-tested. Working as expected
