### ISSUE TITLE
[Create Event] User cannot create the event with such text formatting as:font color, highlight, size, alignment in the description

### ISSUE THREAD

**Issue by Oleksandra-Kobets** [ita-social-projects/GreenCity#6195]
**Environment:** Browser Chrome 115.0.5790.111, Windows 11 Version22H2
**Reproducible:** always 
**Build found:** 07.08.2023 

**Steps to reproduce**
1. Go to https://www.greencity.social/#/greenCity 
2. Log in 
3. Open Event page 
4. Click on "Create event" button
5. In "Description" type four lines of any text and apply to it:
     a) font color,
     b) text highlight color,
     c) text alignment,
     d) text size 
6. Publish event 

**Actual result**
Event was created. 
a-d) The text has not changed. The chosen text formatting is not displaying in the description of event.  

**Expected result**
Event was created. Text is changed according to the chosen:  
a) font color
b) text highlight color
c) text alignment
d) text size 

**User story and test case links**
E.g.: "User story #3193 
[Test case](https://jira.softserve.academy/browse/GC-3175)

**Attachments**
actual result 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/cb0e4197-1dd6-4091-bcf2-426902254a6b)

expected result 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/e0b14cca-a91c-463a-8ee1-050d6f110296)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Oleksandra-Kobets** [comment]
Env: Windows 11 Home, 64 bit Version22H2, Chrome 117.0.5938.132 64bit
Build found: 28.09.23

Сontinues to reproduce with such text formating as alignment, size 

**Actual result:** 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/621ceb74-3091-4fad-a9d7-d1671e4f870c)

**Expected result**
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/d91ce0ee-e4da-41c9-8500-1f2d92a38477)

**Comment by sobkiv** [comment]
cannot reproduce

**Comment by Oleksandra-Kobets** [comment]
Still reproducible 

**Steps to reproduce:** 
1. Type few lines of any text in "Description" field 
2. Apply to this text such style as: 

- [ ] alignment  (for example - right alignment) 
- [ ] font-size (for example - large) 

3. Click on "Publish" button
