### ISSUE TITLE
[View my events] "Cancel request" button is not replaced with "View details" button when the event is passed

### ISSUE THREAD

**Issue by Andrii1999** [ita-social-projects/GreenCity#6200]
**Environment:** Browser Microsoft Edge 115.0.1901.200 Windows 10 Enterprise LTSC
**Reproducible:** Always
**Build found:** 10.08.23

**Steps to reproduce**

  1. Go to https://www.greencity.social/#/greenCity
  2. Log in
  3. Click on "My space" tab in header
  4. Click on "My events" tab in profile
  5. Find an attended event in the list 
  6. Verify that "Cancel request" button is replaced with "View details" button

**Actual result**
"Cancel request" button is not replaced with "View details" button

**Expected result**
"Cancel request" button is not replaced with "View details" button

**User story and test case links**
E.g.: "User story #3375 
[Test case](https://jira.softserve.academy/browse/GC-5023)"

**Comment by dmytro-kryvyi** [comment]
Probably not actual anymore. There are no buttons "Cancel request" or "View details" anymore
![image](https://github.com/ita-social-projects/GreenCity/assets/94367438/0d39adb6-8234-4a58-9936-f21fb7e6a72b)
