### ISSUE TITLE
[UBS Admin cabinet] When the user tries to filter the orders by the fill-in 'Date export' field the 'Apply' button is not able 

### ISSUE THREAD

**Issue by Maksym8Kravchenko** [ita-social-projects/GreenCity#6203]
**Environment:**  Windows 11 Home, Chrome, Version 115.0.5790.171 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 15.08.2023

**Preconditions**

  - Log in as Admin https://www.greencity.social/#/ubs
  - Go to the 'Orders' tab

**Steps to reproduce**
1. Click on the 'Filters' button
2. Check the 'Date export' mark
3. Fill in the 'Date export' field
4. Click on the 'Apply' button

**Actual result**
The 'Apply' button is not able

**Expected result**
The user shall be able to click on the 'Apply' button to use the filter

https://github.com/ita-social-projects/GreenCity/assets/127987815/f283257b-ecaa-424a-9b46-0a8ba9135a50

**User story and test case links**
 User story(https://github.com/ita-social-projects/GreenCity/issues/3300)

**Labels to be added**
Priority ("medium"), Severity ("minor"), Type ( Functional)

**Comment by DanaIuich** [comment]
Incorrect work of "Apply" button:
1. After choosing date the system is looking for an order for the selected date without clicking "Apply" button.
2. After entering date "Apply" button is disabled until user  clicks the mouse on the page

https://github.com/ita-social-projects/GreenCity/assets/128155213/5cea2931-0dc2-4fdc-b100-9adb39249a94


https://github.com/ita-social-projects/GreenCity/assets/128155213/8c915b2d-fa26-4b27-b1f2-bba7d18f8515
