### ISSUE TITLE
Sign up. Error message is not updated after entering an incorrect password

### ISSUE THREAD

**Issue by bartrom653** [ita-social-projects/GreenCity#6220]
Environment:
Windows 11 Pro version 22H2
Google Chrome version 116.0.5845.97 (Official Build) (64-bit)

Reproducible: 
Always

Build found: 
last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev "2bc5ed4"

Preconditions:
Go to the page https://www.greencity.social/#/ubs and click the button 'Sing up'

Steps to reproduce:
1. Click on the field to enter the password
2. Click on any other field (User name, email, etc.)
3. Enter an incorrect password

Actual result
<img width="1004" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/63873130/9052b898-d72f-4b2d-9f5d-7f3dc28e0985">

Expected result:
<img width="375" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/63873130/6da95bdf-0de3-4c91-977d-0781fa9f6836">

Epic link
Epic #908

**Comment by Mariia232** [comment]
Not relevant
