### ISSUE TITLE
[UBS Admin Cabinet]Super admin can't save changes in the order

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6225]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 22.08.2023
Preconditions

The user should be logged in https://www.greencity.social/#/greenCity as a Super Admin

Steps to reproduce

1. Click on the 'Orders' tab
2. In the tab 'Orders' choose the order with 'Payment status' 'Paid'
3. Change Order status from 'Formed' to 'Canceled'
4. Chose the radio button 'Moving' and click 'Add'
5. Click on 'Save' button

Actual result
The order status does not change

Expected result
Order status has changed to 'Canceled'

User story  https://github.com/ita-social-projects/GreenCity/issues/2538

"Bug", Priority ("High"), Severity ("Major"), Type ("Functional"), "API" (for back-end bugs)

**Comment by DanaIuich** [comment]
Bug is fixed
