### ISSUE TITLE
[Events/Organizer Rating] After opening "Rate Organizer" dialog window from the event review card number of displayed stars does not correspond to the mockup

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#6228]
**Environment:**  Windows 10 Pro x64 21H2, Google Chrome 115.0.5790.173.
**Reproducible:** always.
**Build found:** 22.08.2023

**Preconditions**

1. https://www.greencity.social/#/greenCity is opened
2. The user is authorized
3. There is at least one attended event

**Steps to reproduce**

1. Go to 'My space' tab
2. Go to 'My Events' tab
3. Find attended event
4. Click on 'More' button
5. Click on 'Rate Organizer' button

**Actual result**
5 stars are displayed for choice.
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/f87484de-fbc9-4096-8234-88c5ba964c1f)

**Expected result**
There are only 3 stars available for choice.
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/e86b6e08-f5fc-4833-a558-53be5e635cf7)

**User story and test case links**
E.g.: "User story #3268 

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type ("UI").

**Comment by KKatiaa** [comment]
can you send me a link for this mockup?

**Comment by OliaProtyniak** [comment]
> can you send me a link for this mockup?

https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=31341-147821&mode=design&t=3aUflhUWp10sdAOR-0

**Comment by KKatiaa** [comment]
there are already only 3 stars not 5

**Comment by OliaProtyniak** [comment]
> there are already only 3 stars not 5


https://github.com/ita-social-projects/GreenCity/assets/128295227/bf9176dc-ceb5-485e-bd52-abac9f84f3d7
