### ISSUE TITLE
[My habits] Wrong name of the 'Back to My habits' button

### ISSUE THREAD

**Issue by OlenaBudnyk** [ita-social-projects/GreenCity#6232]
**Environment:** Windows 10 Version 21H2, Chrome Version 116.0.5845.97.
**Reproducible:** always.
**Build found:** 23.08.2023

**Preconditions**

**Steps to reproduce**
1. Go to: https://www.greencity.social.
2. Sign in.
3. Click the 'Add New Habit' button.
4. Choose the localization 'UA'.
5. Pay attention at the 'Назад до моїх звичок' button in the upper left corner.

**Actual result**
There is 'Назад.до Моїх звичок' button (see attachment 1).

**Expected result**
There is 'Back to My habits' button (see attachment 2).

**Postconditions**

**User story and test case links**
#5407

**Labels to be added**
![1](https://github.com/ita-social-projects/GreenCity/assets/130562966/0e04b581-9bf1-4a04-85a7-b48fd7bc138c)
![2](https://github.com/ita-social-projects/GreenCity/assets/130562966/903fd0b1-4432-43ea-9715-599c4d937bf1)

**Comment by KKatiaa** [comment]
this is not a dot but short underline between letters
