### ISSUE TITLE
[Order form] A pop-up 'Welcome to UBS...' appears twice at the zero step of the 'Order form'

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6239]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: sometimes
Build found: 23.08.2023
Preconditions

1. User is logged as Admin (admin.greencity@starmaker.email, GreenCityAdmin-1) 
     in https://www.greencity.social/#/greenCity

Steps to reproduce

1. Click on the icon in the upper right corner
3. Click on the 'UBS-USER'
4. Click on the 'New order' button 
5. Chose your location (e.g. Kyiv, Kyiv Oblast)
6. Click on the 'Continue' button 

Actual result
A pop-up 'Welcome to UBS...' with a drop-down to select a location appears

Expected result
The system redirects the user to the first step of the 'Order form'

User story https://github.com/ita-social-projects/GreenCity/issues/3033
Labels to be added
"Bug", Priority ("Medium"), Severity ("Minor"), Type ("UI")

https://github.com/ita-social-projects/GreenCity/assets/131760121/a6a9f0a9-8445-4c68-90e3-14c08eb39cdc

**Comment by Priadkohrystyna** [comment]
Need to fix, actual result after fixing- the same as before fixing.
