### ISSUE TITLE
[Sign-up]Incorrect error message for 'Password' field.

### ISSUE THREAD

**Issue by Vitaliipuchak** [ita-social-projects/GreenCity#624]
**Environment:** Windows 10 Pro/ Google Chrome 81.0.4044.129
**Reproducible:** always
**Build found:** commit 7439e88
**Steps to reproduce:**
1)Go to GreenCity (https://ita-social-projects.github.io/GreenCityClient/#/welcome);
2)Click on "Sign up" button;
3)Enter less than 8 characters into 'Password' field;
**Actual result:** Error-message 'Password must be at least 8 characters _long_' appear.
**Expected result:** Error-message 'Password must be at least 8 characters _in length_' should appear.
**User story:** #385 
**Test case:** https://jira.softserve.academy/browse/GC-198

**Comment by RomanDeveloperAcc** [comment]
Fixed
