### ISSUE TITLE
[Order form] By clicking on the arrow, the drop-down does not open in the pop-up 'Welcome to UBS...' with a drop-down to select a location

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6240]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 23.08.2023
Preconditions

1. User is logged in https://www.greencity.social/#/greenCity

Steps to reproduce

1. Click on the icon in the upper right corner
2. Click on the 'UBS-USER'
3. Click on the 'New order' button
4. Click on the arrow in the drop-down

Actual result
The list with locations does not open

Expected result
A list with locations opens

User story https://github.com/ita-social-projects/GreenCity/issues/3033
Labels to be added
"Bug", Priority ("Medium"), Severity ("Minor"), Type ("UI")

https://github.com/ita-social-projects/GreenCity/assets/131760121/428a1b80-3d44-41bd-9540-bd5c45370d8d

**Comment by Priadkohrystyna** [comment]
Window with message "Welcome to UBS, choose the location..." is abcent.  User can not choose location in order.
[Video_2023_09_27-1.webm](https://github.com/ita-social-projects/GreenCity/assets/106020174/d0dbf036-ad03-4a25-98b9-16fc815a7dd3)
