### ISSUE TITLE
[My space] The color of 'Facebook', 'Linkedin' and unknown social network icons is #878787 instead  #64727D

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6241]
**Environment:** Windows 10 Pro, Google Chrome (116.0.5845.96)
**Reproducible:** always
**Build found:** 23.08.2023

**Precondition**
The user has 5 added social networks (facebook, instagram, linkedin, twitter, tiktok) in his profile.

**Steps to reproduce**

1. Go to https://www.greencity.social/#/greenCity
2. Sign in as user
3. Open 'My space' page
4. Take a look at the "Profile" form

**Actual result**
The color of 'Facebook', 'Linkedin' and unknown social network icons is background: #878787.
![2023-08-23 20 18 56220](https://github.com/ita-social-projects/GreenCity/assets/138515375/5b638f97-09db-4631-97af-cbd3b0f622ab)

**Expected result**
The color of 'Facebook', 'Linkedin' and unknown social network icons is background: #64727D.
![2023-08-23 20 02 551120](https://github.com/ita-social-projects/GreenCity/assets/138515375/c3d2a829-20f1-4b50-8087-591d0c2cc306)

**User story and test case links**
User story #1102

**Comment by KKatiaa** [comment]
we are dispalying only available social media so only one color will be used
