### ISSUE TITLE
[My habits] User doesn't get points for each day of habits in progress

### ISSUE THREAD

**Issue by OlenaBudnyk** [ita-social-projects/GreenCity#6246]
**Environment:** Windows 10 Version 21H2, Chrome Version 116.0.5845.97.
**Reproducible:** always.
**Build found:** 24.08.2023

**Preconditions**
Registered user has at least one habit in progress

**Steps to reproduce**
1. Go to: https://www.greencity.social/.
2. Sign in.
3. Go to the 'My habits' page.
4. Pay attention to the 'Rate' on the left.

**Actual result**
'Rate' is 0 (see attachment).

**Expected result**
User gets 1 point for each day of habits in progress

**Postconditions**

**User story and test case links**
User story #997
[Test case](https://jira.softserve.academy/browse/GC-7748)"

**Labels to be added**
![rate 1](https://github.com/ita-social-projects/GreenCity/assets/130562966/508ec950-ccd4-468b-a851-193062a1f29f)

**Comment by Maxv1z** [comment]
Not reproducible

https://github.com/ita-social-projects/GreenCity/assets/122612827/c3b07927-ab38-4535-9345-f6a4ee15c178
