### ISSUE TITLE
[Edit Profile] The User can not add a city and country just from the drop-down list

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6248]
**Environment:** Windows 10 Pro, Google Chrome (116.0.5845.96)
**Reproducible:** always
**Build found:** 23.08.2023

**Steps to reproduce**

1. Go to https://www.greencity.social/#/profile
2. Sing in as user
3. Open 'My space' page
4. Click on the 'Edit profile icon near the photo
5. Enter the 'Lviv' value into the 'City' text field.

**Actual result**
The drop-down list is not shown. The 'Lviv' value was entered in the 'City' text field. 

**Expected result**
The drop-down list is shown, where the user can choose the 'Lviv, Ukraine' value.

**User story and test case links**
User story #1102 
[GC-7827](https://jira.softserve.academy/browse/GC-7827)

**Comment by Priadkohrystyna** [comment]
Bug is not resolved, the drop-down list is not shown
![Знімок екрана 2023-09-26 105726](https://github.com/ita-social-projects/GreenCity/assets/106020174/63a8f726-56fb-49f6-840d-9e1a4c9a8a3e)
