### ISSUE TITLE
[Sign In] 'Email' and 'Password' fields are not highlighted after trying to sign in with registered email and incorrect password

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#625]
**Environment:** Windows Server 2012 R2 Standard x64, Google Chrome 81.0.4044.129, 
Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 7439e88

**Preconditions**
There is at least 1 registered user.

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign-in' link.
3. Set valid registered email address into 'Email' field.
4. Set incorrect password into 'Password' field (e.g. "Qw123456.\").
5. Click on Sign-in button.

**Actual result**
'Password' and 'Email' fields are not highlighted in red color and error message is displayed under 'Password' field: "Bad email or password".
![Sign in2 actual](https://user-images.githubusercontent.com/64583544/81180043-27ed4300-8fb3-11ea-8fbb-ccb73ff76700.png)

**Expected result**
'Password' and 'Email' fields are highlighted in red color and error message appears under 'Password' field: "Bad email or password".
![Sign in expected](https://user-images.githubusercontent.com/64583544/81180047-291e7000-8fb3-11ea-950a-b97fd4f31ba0.png)

User story #471
Test case https://jira.softserve.academy/browse/GC-30

**Comment by KimAT25** [comment]
Fixed

**Comment by rsyvulko** [comment]
Verified.
