### ISSUE TITLE
[Edit Profile] The 'Save' button is not clickable when the 'City' text field is empty

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6256]
**Environment:** Windows 10 Pro, Google Chrome (116.0.5845.96)
**Reproducible:** when the text field has already been edited once
**Build found:** 24.08.2023

**Preconditions**
There should already be some value in the 'City' text field

**Steps to reproduce**

1. Go to https://www.greencity.social/#/profile
2. Sing in as user
3. Open 'My space' page
4. Click on the 'Edit profile icon near the photo
5. Erase a value in 'City' text field
6. Click on 'Save' button

**Actual result**
The 'Save' button is not clickable and the empty 'City' text field is not saved

https://github.com/ita-social-projects/GreenCity/assets/138515375/df04b620-18e6-4830-af10-f53723211e5c

**Expected result**
The 'Save' button is clickable and the empty 'City' text field is saved

**User story and test case links**
User story #1010 
[GC-7826](https://jira.softserve.academy/browse/GC-7826)

**Comment by nina279** [comment]
resolved
