### ISSUE TITLE
[My Friends Page] Placeholder "Search" in the search field instead of "Search a friend"

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6257]
**Environment:** Windows 10, Chrome 116.0.5845.97 (64 bit)
**Reproducible:** always
**Build found:** 24/08/23

**Preconditions**
The rigestered user is loged in

**Steps to reproduce**
1. Go to [GreenCity](https://www.greencity.social/#/)
2. Click on 'My Friends Page'
3. Open 'All Friends' Tab

**Actual result**
Placeholder "Search" in the search field instead of "Search a friend".

**Expected result**
Placeholder 'Search a friend' in a search field.

**User story and test case links**
User story #2122 

**Labels to be added**
"Bug", Priority (pri: "Low"), Severity (sev: "Minor"), Type (type: "UI")

**Comment by Yavorovskayuliia** [comment]
The search field has an incorrect name.  Placeholder "Search" in the search field instead of "Search a friend".
![6257](https://github.com/ita-social-projects/GreenCity/assets/135861356/39c07b4d-bbe4-42f9-b6d9-c9e7d18b52b7)

**Comment by OksanaFilipchuk** [comment]
https://github.com/ita-social-projects/GreenCity/issues/6423

https://github.com/ita-social-projects/GreenCity/issues/6465

This bug is no more an actual

**Comment by OksanaFilipchuk** [comment]
https://github.com/ita-social-projects/GreenCity/issues/6423

https://github.com/ita-social-projects/GreenCity/issues/6465
There are other requirements in the change request
