### ISSUE TITLE
[My habits] [Calendar] Pop up with a list of all habits "In Progress" appears in English in UA localization

### ISSUE THREAD

**Issue by OlenaBudnyk** [ita-social-projects/GreenCity#6260]
**Environment:** Windows 10 Version 21H2, Chrome Version 116.0.5845.97.
**Reproducible:** always.
**Build found:** 25.08.2023

**Preconditions**
Registered user has at least 2 habits "in progress"

**Steps to reproduce**
1. Go to: https://www.greencity.social/.
2. Sign in.
3. Choose the localization 'UA'.
4. Click a mouse on current or one of 7 previous days on a Calendar.
5. Pay attention at the pop up with a list of all habits "in progress".

**Actual result**
Pop up with a list of all habits "In Progress" appears in English (see attachment).
![localization 1](https://github.com/ita-social-projects/GreenCity/assets/130562966/9ce6bdc4-30a5-457f-8edd-d9f60c7acec5)

**Expected result**
Pop up with a list of all habits "In Progress" appears in Ukrainian.

**Postconditions**

**User story and test case links**
User story #1431

**Labels to be added**

**Comment by sobkiv** [comment]
Cannot reproduce
