### ISSUE TITLE
[Events/Organizer Rating] Buttons 'Закрити' and 'Зберегти' are shifted to the left in the 'Rate Organizer' dialog window UA localization

### ISSUE THREAD

**Issue by OliaProtyniak** [ita-social-projects/GreenCity#6262]
**Environment:** Windows 10 Pro x64 21H2, Google Chrome 115.0.5790.173.
**Reproducible:** always.
**Build found:** 25.08.2023

**Preconditions**

1. https://www.greencity.social/#/greenCity is opened
2. The user is authorized
3. There is at least one attended event
4. Localization is switched to UA

**Steps to reproduce**

1. Go to 'My space' tab
2. Go to 'My Events' tab
3. Find attended event
4. Click on 'Rate Organizer' button

**Actual result**
Buttons 'Закрити' and 'Зберегти' are shifted to the right.
![image](https://github.com/ita-social-projects/GreenCity/assets/128295227/1c581b50-006e-4eba-ade4-d825b2b48e8c)

**Expected result**
The 'Закрити' and 'Зберегти' buttons have equal distances from the left and right edges of the dialog window.

**User story and test case links**
E.g.: "User story #3268 
Test case [GC-8975](https://jira.softserve.academy/browse/GC-8975)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type ("UI").

**Comment by IrynaFedun** [comment]
![Rate_Expect  Закрити_Зберегти](https://github.com/ita-social-projects/GreenCity/assets/142750671/4dc57d36-a95d-46a9-8102-52215fe359b5)

**Comment by IrynaFedun** [comment]
The button "Закрити" must be shifted to the left according to the button "Зберегти"

**Comment by IrynaFedun** [comment]
Actual result: There is a button "Close"
![Actual modal window 1](https://github.com/ita-social-projects/GreenCity/assets/142750671/2a502c97-7df3-4844-9532-28dccf75473b)


Expect result: There is a button "Cancel"
![Espected modal window 1](https://github.com/ita-social-projects/GreenCity/assets/142750671/63f493ba-d036-46d4-bab7-a0e2a4c230fd)
