### ISSUE TITLE
[Log In Page] 'Sign In' is disabled for Registered User while using 'Sign in with Google' 

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6271]
**Environment:** Windows 10, Chrome 116.0.5845.97 (64bit)
**Reproducible:** always
**Build found:** 25.08.23

**Preconditions**
User is registered.
Data for signing in is saved for autofill.

**Steps to reproduce**
1. Go to [GreenCity](https://www.greencity.social/#/greenCity)
2. Click on 'User Icon' in upper right corner. 

**Actual result**
Email and password is filled automatically, button is dissabled. After clicking in random free space button is active.

**Expected result**
Email and password is filled automatically, button is active.

**User story and test case links**
E.g.: "User story #50
[Test case](https://jira.softserve.academy/browse/GC-2562)"

![1](https://github.com/ita-social-projects/GreenCity/assets/138124542/286c1bf0-c98a-46a8-8e8e-82fff4223ae1)
![2](https://github.com/ita-social-projects/GreenCity/assets/138124542/6a78ca70-5131-4836-9a52-5511efac4c0e)

**Comment by Tadei-Mykola** [comment]
cannot reproduce
