### ISSUE TITLE
[My friends][My Space] User is not redirected to the the friend's page after clicking the friend's avatar

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6273]
**Environment:** Windows 10, Chrome 116.0.5845.97 (64bit)
**Reproducible:** always
**Build found:** 25.08.23

**Preconditions**
The user is logged in to the 'https://www.greencity.social/#/greenCity' website
User has at least 1 friend (friend downloaded photo for his avatar, which means that avatar photo is not standard)

**Steps to reproduce**
1. Click the friend's avatar in the "My friends" block
3. Pay attention to the result

**Actual result**
The user is not redirected to the friend's page after clicking the friend's avatar. Instead, that system opens [UBS](https://www.greencity.social/#/ubs).

**Expected result**
The user is redirected to the friend's page after clicking the friend's avatar in the 'My friends' block of the 'My Space' page

**User story and test case links**
E.g.: "User story #1002 
[Test case](https://jira.softserve.academy/browse/GC-2215)

**Comment by Priadkohrystyna** [comment]
System do not redirects to User's Friend page. Instead of that system opens [UBS](https://www.greencity.social/#/ubs).
[Uploading Video_2023_12_04-1.webm…]()
