### ISSUE TITLE
[Friends Page] Placeholder 'Search' in text field instead of 'Search for a new friend'

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6278]
**Environment:** Windows 10, Chrome 114.0.5735.110 (64 bit)
**Reproducible:** always
**Build found:** 23.08.23

**Steps to reproduce**
1. Go to [GreenCity](https://www.greencity.social/#/ubs).
2. Sign in as a User.
3. Open 'My Space' page.
4. Open 'My Friends' page.
5. Click on 'Find Friends' button.
6. Check the placeholder in text field.

**Actual result**
In text field placeholder 'Search'.

**Expected result**
There is a placeholder "Search for a new friend" in the search field.

**User story and test case links**
E.g.: "User story #1003
[Test case](https://jira.softserve.academy/browse/4509)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by yurikhrunyk** [comment]
According to the attached user story text in the placeholder should be "Search"
