### ISSUE TITLE
[Sign-up]Error message is not displayed for 'First name' field.

### ISSUE THREAD

**Issue by Vitaliipuchak** [ita-social-projects/GreenCity#628]
**Environment:** Windows 10 Pro/ Google Chrome 81.0.4044.129
**Reproducible:** always
**Build found:** commit 7439e88
**Steps to reproduce:**
1)Go to GreenCity (https://ita-social-projects.github.io/GreenCityClient/#/welcome);
2)Click on "Sign up" button;
3)Leave the 'First name' field empty;
4)Enter valid email, Password and Confirm Password (field requirements in #385)
5)Click on 'Sing-up' button
**Actual result:** Error message 'First name is required' is not displayed for 'First name' field.
**Expected result:** Error-message 'First name is required' is displayed.
**User story:** #385 
**Test case:** https://jira.softserve.academy/browse/GC-210

**Comment by RomanDeveloperAcc** [comment]
Fixed
