### ISSUE TITLE
[Request Page] Message on Request page do not responds to requirements

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6284]
**Environment:** Windows 10, Chrome 114.0.5735.110 (64 bit)
**Reproducible:** always
**Build found:** 22.08.23

**Preconditions**
User has 0 friends requests.

**Steps to reproduce**
1. Go to [GreenCity](https://www.greencity.social/#/greenCity).
2. Sign in as a User.
3. Open 'My Space' page.
4. Open 'My Friends' page.
5. Open 'Requests' page.
**Actual result**
System shows a message 'Unfortunately, there are no new requests.' 

**Expected result**
System shows a message 'Unfortunately you don’t have new friends requests' on Friends requests tab as mentioned in requirements.

**User story and test case links**
E.g.: "User story #2084
[Test case](https://jira.softserve.academy/browse/4236)

**Comment by Oleksandra-Kobets** [comment]
Need to fix. User should able to see only this part of text:
"Unfortunately you don’t have new friends requests" 

This part of the text needs to be removed   " ' on Friends requests tab as mentioned in requirements." 

![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/afc46b57-b8c8-49f7-86d7-9f9c41840e31)
