### ISSUE TITLE
[Request Page] Button 'Unfriend' does not replaced by a button "Add friend". Number of friends do not decreases by 1

### ISSUE THREAD

**Issue by lerakhmullaeva** [ita-social-projects/GreenCity#6285]
**Environment:** Windows 10, Chrome 114.0.5735.110 (64 bit)
**Reproducible:** always
**Build found:** 23.08.23

**Preconditions**
User has at least one friend

**Steps to reproduce**
1. Go to [GreenCity](https://www.greencity.social/#/ubs).
2. Sign in as a User.
3. Open 'My Space' page.
4. Open 'My Friends' page.
5. Click on 'Unfriend' button below User's friend.

**Actual result**
System hides part of friends, **number of friends do no decrease by 1. (Look Atachments)
![1](https://github.com/ita-social-projects/GreenCity/assets/138124542/8656484a-4161-4388-85ef-cd76af82354a)

**Expected result**
Button "Unfriend" automatically replaced by a button "Add friend".
Number of friends decreases by 1.

**User story and test case links**
E.g.: "User story #1004
[Test case](https://jira.softserve.academy/browse/4242)

**Comment by KKatiaa** [comment]
but it is not supposed to be replased. Friend disappeared from "all friends" and you can find him again in "find friends"
