### ISSUE TITLE
[Sign-up]Spelling error on 'Sign up' page.

### ISSUE THREAD

**Issue by Vitaliipuchak** [ita-social-projects/GreenCity#629]
**Environment:** Windows 10 Pro/ Google Chrome 81.0.4044.129
**Reproducible:** always
**Build found:** commit 7439e88
**Steps to reproduce:**
1)Go to GreenCity (https://ita-social-projects.github.io/GreenCityClient/#/welcome);
2)Click on "Sign up" button;
3)Verify spelling, labels font, size, and colors according to the mock-up
**Actual result:** 'Вже маєете акаунт' 
**Expected result:** 'Вже маєте акаунт' 
**User story:** #385
**Test case:** https://jira.softserve.academy/browse/GC-216
![image](https://user-images.githubusercontent.com/44547708/81193441-12344980-8fc4-11ea-9121-62a906b8dda0.png)

**Comment by Sergio2209** [comment]
Verified
