### ISSUE TITLE
[Edite profile] User can't click on the"Save" button when added five links from social network 

### ISSUE THREAD

**Issue by OksanaPyrozhok** [ita-social-projects/GreenCity#6290]
**Environment:** Windows 10, 64-bit
Opera One(версія: 101.0.4843.43)
**Reproducible:** always
**Build found:** 27.08.2023

**Preconditions**
The user is logged in to Green City https://www.greencity.social/#/profile
The EN localization is chosen.
'My habits' page is opened.

**Steps to reproduce**
1.Go to [GreenCity](https://www.greencity.social/#/ubs).
2.Sing in as a user
3.Open the "My habits"page
4. Click the 'Edit' icon on the Profile block
5. Click on 'Add social network' button
6. Add five links from social network e.g. "https://www.facebook.com/romein3d"
                                                  "https://www.facebook.com/SoftServeCompany/"
                                                  "https://www.facebook.com/ukrposhta"
                                                  "https://www.linkedin.com/company/softserve/"
                                                  "https://www.youtube.com/@SoftServeCareer"
 

**Actual result**
The system does not save five links from added social networks
![photo_2023-08-27_17-28-12](https://github.com/ita-social-projects/GreenCity/assets/138609814/13483277-6296-4258-80e8-503af71da22f)

**Expected result**
Five links from social networks are saved

**User story and test case links**
E.g.: "User story #1007
[GC-1510](https://jira.softserve.academy/browse/GC-1510)
[GC-4571](https://jira.softserve.academy/browse/GC-4571)

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity:minor"), Type ("Functional")

**Comment by KKatiaa** [comment]
everithing works correctly
