### ISSUE TITLE
[Edit Profile] Users can't save edits when only the Name field is filled

### ISSUE THREAD

**Issue by KaterynaSimonchyk** [ita-social-projects/GreenCity#6299]
Environment: MacBook Air 12.6.6  12.6.6 Google Chrome
Preconditions: always
Build found: 29.08.2023

Precondition 
The field city and credo should be empty

Steps to reproduce
1. Go to https://www.greencity.social/#/profile
2. Sing in as users
3. Open the 'My space' page
4. Click on the "Edit profile"
5. Set correct value in required 'Name' field e.g Kate
6. Click button "Save"

Actual result
The 'Save' button isn't disabled, but the click action has no effect
Expected result
The Save button is active. Error message isn’t highlighted in the red. The user is redirected to the My Space page

User story and test case links
User story #1010 
![баг!!](https://github.com/ita-social-projects/GreenCity/assets/138121097/735a8ff5-69c2-4212-bbb4-1119a88e7fa4)
https://jira.softserve.academy/browse/GC-1550

**Comment by OlenaPodkovyrova** [comment]
Re-tested. Working as expected
![image](https://github.com/ita-social-projects/GreenCity/assets/140602524/5b5ec566-048c-4617-8346-a323da0484ba)
![image](https://github.com/ita-social-projects/GreenCity/assets/140602524/cb4c0946-ea62-4342-8a75-74139a4223c0)
