### ISSUE TITLE
[Edit Profile] The error message is not displayed when we leave the city field empty

### ISSUE THREAD

**Issue by KaterynaSimonchyk** [ita-social-projects/GreenCity#6300]
Environment: MacBook Air 12.6.6 Google Chrome
Reproducible: always
Build found: 29.08.2023

Precondition:
The Name field is valid.

Steps to reproduce:
1. The user is logged in to Green City https://www.greencity.social/#/profile
2. Go to "Edit Profile"
3. Leave the field 'City' empty
4. Click 'Save"

Actual result
The Save button is inactive. Does not have Error message
Expected result
The Save button is inactive. Error message must be present on the bottom of the text box and should be highlighted in red.

![bag2](https://github.com/ita-social-projects/GreenCity/assets/138121097/68e3ea96-88d7-4ce1-ad9b-781a58c4af6c)

**User story and test case links**
E.g.: "User story #1010 
https://jira.softserve.academy/browse/GC-1552

**Comment by OksanaFilipchuk** [comment]
The city field can be empty. It is not a required field.
