### ISSUE TITLE
[Edit Profile 'City' field ] The system does not shown the list of cities in 'City' field on the 'Edit Page'

### ISSUE THREAD

**Issue by BerezovychRomana** [ita-social-projects/GreenCity#6301]
**Environment:** Mac OS, browser: version 116.0.5845.110
**Reproducible:** always
**Build found:** 28/08.2023

**Steps to reproduce**
Steps to reproduce:

1. Go to https://www.greencity.social/#/greenCity
2. 'Edit Profile' is opened
3. Enter the first symbol of valid data in 'City' (e.g. K )

**Precondition**

**Actual result**
The system doesn't show a list of cities whose names begin with the symbol 'K'
<img width="627" alt="Знімок екрана 2023-08-28 о 13 19 48" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/18ad885e-2ba0-4f51-983e-7f2fbe9665ce">

**Expected result**
The system shows a list of cities whose names begin with the symbol 'K'

**Postconditions**

**User story and test case links**
E.g.: "User story - #1102  Change request - #5938 
[Test case](https://jira.softserve.academy/browse/GC-6840)"

**Labels to be added**
"Bug", Priority ("high: "), Severity ("major:"), Type ("UI, "Functional")

**Comment by nina279** [comment]
resolved
