### ISSUE TITLE
[My habits] On the "My habits" page the inscriptions "Мої звички"and "Мої новини" are found on top of each other, 320p screen resolutions UA localization

### ISSUE THREAD

**Issue by OksanaPyrozhok** [ita-social-projects/GreenCity#6305]
**Environment:** Windows 10, 64-bit
Opera One(версія: 101.0.4843.43)
**Reproducible:** always
**Build found:**29.08.2023
**Preconditions**
1. The registered user is logged in https://www.greencity.social/#/greenCity with valid data 
2. "My habits" page is opened

**Steps to reproduce**
1. UA localization for "My habits" page on 320p screen resolution.

**Actual result**
The inscription "Мої звички" and "Мої новини" do not fit
![image](https://github.com/ita-social-projects/GreenCity/assets/138609814/d6255c49-ef3e-4338-8138-d5c39ad78312)

**Expected result**
The inscription "Мої звички" and "Мої новини" should be fully displayed

**User story and test case links**
E.g.: "User story #1000
test case [GC-1794](https://jira.softserve.academy/browse/GC-1794)

**Labels to be added**
"Bug", Priority (" Low "), Severity ("Minor"), Type ("UI"),

**Comment by Priadkohrystyna** [comment]
In UA localization in sigyature "Moї новини"- the last letter "и" - not fully displayed.

**Comment by sobkiv** [comment]
This task was in Bugs in Progress, so it was not supposed to take on the
retesting stage yet

вт, 19 вер. 2023 р. о 15:15 Priadkohrystyna ***@***.***> пише:

**Comment by Priadkohrystyna** [comment]
Ok, sorry) Have a nice day)

вт, 19 вер. 2023 р., 16:20 користувач Pavlo Sobkiv ***@***.***>
пише:
