### ISSUE TITLE
[My habits] Unable to edit and save additional details about the habit #1002

### ISSUE THREAD

**Issue by BohdanKalytynskyi** [ita-social-projects/GreenCity#6319]
**Environment:** Windows 10, Google Chrome
Версія 114.0.5735.134
**Reproducible:** always.
**Build found:** 

**Preconditions**

1. The user is logged in
2. Site localisation = UA
3. 'My habits' page opened [https://www.greencity.social/#/profile] 
4. Habbit_1 does not have a translation to UA

**Steps to reproduce**

1. Click 'Додати Нову Звичку' button
2. Find  habit _1 and click the 'Детальніше' button
3. Change the duration of habit formation 
4. Click the 'Додати Звичку' button

**Actual result**

1. Тривалість" field  changes were NOT saved,
2. “Список Завдань" field  changes were NOT saved

**Expected result**

1. 'Тривалість' field  changes were saved,
2. 'Список Завдань' field  changes were saved

**Comment** This defect is displayed only on those habits in which the name of the habit was not translated when changing the language (from English to Ukrainian)

**Attachments**
![BR№0_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/d1c58d8e-8d3f-44c4-ac17-9caec04336ca)
![BR№1_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/96d41109-a45c-4010-8ea7-9d766b8cd412)
![BR№2_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/9f692a65-1a3f-41f1-8069-230264af719d)
![BR№3_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/29fab98e-1618-42ad-b0a1-b23d14d4b156)
![BR№4_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/c5611f31-74bd-495d-97dd-5bb528f41c4a)
![BR№5_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/c95e938e-fcb8-4c13-bccc-60b7d7053abe)
![BR№6_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/7b518cd6-3618-4567-9eb0-bfb9d1806193)
![BR№7_St5407_CR1785_TC5938](https://github.com/ita-social-projects/GreenCity/assets/138378347/f423df47-876f-4481-9547-cb9c17813a53)

**Postconditions**

**User story and test case links**
E.g.: "User story #1002
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: major"), Type ("Functional").

**Comment by Rusiaieva** [comment]
The bug remains relevant. The "Тривалість" and "Список завдань" fields are not saved after you make changes to the habit, even the "Тривалість" field does not change. This field is displayed as if it has changed, it appears to reflect the change when you close the habit, but in fact it does not when you reopen the habit. When you re-open it, the data in the "Тривалість" field is displayed without changes. This bug exists when using the English and Ukrainian versions of the page.

**Comment by AnastasiiaIvko** [comment]
The To-do list is not saved after making changes or adding custom items
