### ISSUE TITLE
[Sign In] 'Email' and 'Password' fields are not highlighted and no error-messages are displayed after trying to sign in with empty email and password

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#632]
**Environment:** Windows Server 2012 R2 Standard x64, Google Chrome 81.0.4044.129, 
Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 7439e88

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign-in' link.
3. Leave 'Email' and 'Password' fields empty.
5. Click on 'Sign-in' button.

**Actual result**
'Password' and 'Email' fields are not highlighted in red color and error messages are not displayed under 'Password' and 'Email' fields.
![Sign in empty actual](https://user-images.githubusercontent.com/64583544/81197931-90dfb580-8fc9-11ea-947c-23a6ea6e01d5.png)

**Expected result**
'Password' and 'Email' fields are highlighted in red color and error messages are displayed under 'Password' and 'Email' fields: **_"Email is required" and "Password is required"._**
![Sign in empty expected](https://user-images.githubusercontent.com/64583544/81197961-963d0000-8fc9-11ea-8050-2d5e183f4dbf.png)

User story #471
Test case https://jira.softserve.academy/browse/GC-229

**Comment by rsyvulko** [comment]
**Additional info.**
Bug is reproducable only if user doesn't try to type any symbols in fields or even click on fields and clicks on 'Sign-in' button. If user clicks on fields or type something and delete it, validation starts working.

**Comment by KimAT25** [comment]
As we have to input data in all fields, this bug isn`t relevant, as sign-in button are disabled according story #471.

**Comment by rsyvulko** [comment]
Verified
