### ISSUE TITLE
[Create Event/Edit Event] Creating of Event does not have the possibility of choosing and sending to back-end only the location or link of an event's specific day

### ISSUE THREAD

**Issue by sobkiv** [ita-social-projects/GreenCity#6326]
Environment: Google Chrome Version 115.0.5790.110 (Official build), (64 bit) Windows 11
Reproducible: always
Build found: 03-09-2023

**Steps to reproduce**
Steps to reproduce
Go to https://www.greencity.social/#/greenCity
Log in as a User
Open the "Events" page
Press to "Create Event" or "Edit Event" buttons
Type Event name
Set Duration 2 days
Set dates and time for two days
Choose only location on the first day
Choose only link on the second day
Type Event description
Choose Initiative type
Choose images
Press to "Submit" button
After redirecting to Events page press "Edit Event" button of the Created Event

**Actual result**
We have different values on editing stage

**Expected result**
Possibility to have the same values on the editing stage that the user puts on the creating stage. Also from the front-end and back-end sides to have the possibility of choosing only the location, only the link, or both for the specific days and sending them to the back-end 

**User story and test case links**
E.g.: "User story #https://github.com/ita-social-projects/GreenCity/issues/3193

https://github.com/ita-social-projects/GreenCity/assets/112779214/f9ecb311-abcc-4dfe-8e4a-56d597a0c17d

On creating stage before Submit
![image](https://github.com/ita-social-projects/GreenCity/assets/112779214/e511e91f-2034-45ac-a697-2814a3e5fb28)

On editing stage we have different values
![image](https://github.com/ita-social-projects/GreenCity/assets/112779214/54490c1a-3b23-440e-b6f6-b91092815e07)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Priadkohrystyna** [comment]
Need to fix once more, actual result the same after fixing.

**Comment by sobkiv** [comment]
Please try to test it again, today's merge solved this misunderstanding :)
