### ISSUE TITLE
[Sign In] 'Email' field is not highlighted and no error-message is displayed after trying to sign in with empty email

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#634]
**Environment:** Windows Server 2012 R2 Standard x64, Google Chrome 81.0.4044.129,
Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 7439e88

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign-in' link.
3. Leave 'Email' field empty.
4. Enter valid value into the 'Password' field (8 and more symbols, at least 1 symbol from each group: Uppercase letter (A-Z), Lowercase letter (a-z). Digit (0-9), Special character (~`!@#$%^&*()+=_-{}[]|:;”’?/<>,.)).
5. Click on 'Sign-in' button.

**Actual result**
'Email' field is not highlighted in red color and error message is not displayed under 'Email' field.
![Sign in empty mail act](https://user-images.githubusercontent.com/64583544/81200992-668ff700-8fcd-11ea-85a9-c93ddce2b3a8.png)

**Expected result**
'Email' field is highlighted in red color and error message is displayed under 'Email' field: **_"Email is required"_**.
![Sign in empty mail exp](https://user-images.githubusercontent.com/64583544/81201019-70195f00-8fcd-11ea-9009-c5134f869610.png)

User story #471
Test case https://jira.softserve.academy/browse/GC-522

**Comment by rsyvulko** [comment]
**Additional info.**
Bug is reproducable only if user doesn't try to type any symbols in field or even click on field and clicks on 'Sign-in' button. If user click on field or type something and delete it, validation starts working.

**Comment by KimAT25** [comment]
As we have to input data in all fields, this bug isn`t relevant, as sign-in button are disabled according story #471.

**Comment by rsyvulko** [comment]
Verified.
