### ISSUE TITLE
[Orders] Horizontal scrollbar appears only when user reachs to the bottom of the page

### ISSUE THREAD

**Issue by DanaIuich** [ita-social-projects/GreenCity#6348]
**Environment:** all
**Reproducible:** always
**Build found:** 13/09/2023

**Preconditions**

1. User should be logged as super admin or an employee with the appropriate permission to view the page "Orders" (all employees exept driver).
2. Go to https://www.greencity.social/#/ubs-admin/orders

**Steps to reproduce**
1. On the page scroll down the page.
2. Verify location of Horizontal scrollbar.

**Actual result**
Horizontal scrollbar appears only when user reachs to the bottom of the page and only after that the user can scroll the page to the rightю 

**Expected result**
Horizontal scrollbar is always present on the page. User shouldn't scroll the page to use Horizontal scrollbar .

**User story and test case links**
https://github.com/ita-social-projects/GreenCity/issues/5538

https://github.com/ita-social-projects/GreenCity/assets/128155213/aebeb024-c260-4226-8c61-e2b622b423f3

**Comment by Mariia232** [comment]
Environment: all

**Comment by Mariia232** [comment]
Environment: all
Reproducible: always
Build found: 22,06,2024    
Preconditions
1. Go to  ](https://www.pick-up.city/#/ubs-admin/orders)   

https://github.com/ita-social-projects/GreenCity/assets/99343288/7dafba26-d640-45be-b5ab-23e7feb23b4c

**Comment by kovalsofiia1** [comment]
Scrolbar is present now

https://github.com/user-attachments/assets/394c7132-42e2-4363-8340-56aa4716fed9
