### ISSUE TITLE
[Sign in] There is no Scroll-bar on the “Sign-in” modal window after page resizing 

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#635]
**Environment:** macOS High Sierra 10.13.16, Google Chrome 81.0.4044.129 (64-bit), Firefox 76.0
**Reproducable:** always
**Build found:** commit 7439e88

**Preconditions:**
Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome;

**Steps to reproduce**
1. Click on 'Sign in' link;
2. Press F12;
3. Verify that scroll-bar is present on the “Sign-in” modal window after page resizing. (e.g. set 50 %, 150%)

**Actual result**
There is no Scroll-bar on the “Sign-in” modal window on the browser Chrome 81.0.4044.129.

**Expected result**
Scroll-bar is present on the “Sign-in” modal window.

**User story:** #551

Attached files: modal window on browser Chrome 81.0.4044.129

![Sign in Chrome 50%](https://user-images.githubusercontent.com/64582769/81227838-bc789500-8ff5-11ea-9dd1-469273010f97.png)
![Sign in Chrome 150%](https://user-images.githubusercontent.com/64582769/81227851-c0a4b280-8ff5-11ea-80d4-39e2bb2bb713.png)

**Comment by KimAT25** [comment]
will be made mock-up of visual look of scroll bar by designer. Scroll should be present, but hidden.
