### ISSUE TITLE
[Events] Default image is not displayed correctly

### ISSUE THREAD

**Issue by sobkiv** [ita-social-projects/GreenCity#6350]
Environment: Google Chrome Version 115.0.5790.110 (Official build), (64 bit) Windows 11
Reproducible: always
Build found: 13-09-2023

**Steps to reproduce**
1:
Go to https://www.greencity.social/#/greenCity
Log in as a User
Open the "Events" page
2:
Go to https://www.greencity.social/#/greenCity
Log in as a User
Open the "Events" page
Press "Edit Event" button
3:
Go to https://www.greencity.social/#/greenCity
Log in as a User
Open the "Events" page
Press "More" button

**Actual result**
Default image is not displayed

**Expected result**
Default image is displayed

![image](https://github.com/ita-social-projects/GreenCity/assets/112779214/e4189dfa-054c-4445-adc2-67b034f03b12)
![image](https://github.com/ita-social-projects/GreenCity/assets/112779214/00b3fee0-ead3-4e82-b0ec-c1d80f118149)
![image](https://github.com/ita-social-projects/GreenCity/assets/112779214/f48cc8f4-f1c4-4491-9b34-e7633f0491e8)

User story and test case links
E.g.: "User story #https://github.com/ita-social-projects/GreenCity/issues/3193

Test case https://jira.softserve.academy/browse/GC-9027

**Comment by Oleksandra-Kobets** [comment]
The bug is still reproducible. On the ["events dashboard page"](https://www.greencity.social/#/events) default images are not displayed 

![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/6be58000-0bf3-4de4-9035-6a829f74db97)

**Comment by sobkiv** [comment]
Hi! Please, check again if it works now
https://github.com/ita-social-projects/GreenCity/assets/112779214/e65a797c-868f-4b7b-8944-f541e2e8d71c

**Comment by ViraM2301** [comment]
![image](https://github.com/ita-social-projects/GreenCity/assets/151033706/6ddfebf8-b8b9-4808-b58a-053c0a363c2a)

**Comment by ViraM2301** [comment]
![image](https://github.com/ita-social-projects/GreenCity/assets/151033706/2ec52956-0344-437f-a5b7-f0ccb6b0f657)

**Comment by ViraM2301** [comment]
![image](https://github.com/ita-social-projects/GreenCity/assets/151033706/0c07bb00-3136-46a0-8d80-4d3c033d1f2b)

**Comment by ViraM2301** [comment]
Привіт, баг був закритий, але знову з'явилась проблема з відображенням дефолтних картинок

**Comment by sobkiv** [comment]
Привіт. Тепер проблема на back-end, передав Olena Sotnik що саме потрібно зробити

**Comment by ViraM2301** [comment]
Привіт , добре , дякую

Пн, 19 февр. 2024 г. в 16:20, Pavlo Sobkiv ***@***.***>:

**Comment by KizerovDmitriy** [comment]
Already fixed
![image](https://github.com/ita-social-projects/GreenCity/assets/113462277/40e25e86-440a-4a9b-8e35-075cbca8a2f8)
![image](https://github.com/ita-social-projects/GreenCity/assets/113462277/9c9ce390-5f9d-4edf-9216-85166f321821)
![image](https://github.com/ita-social-projects/GreenCity/assets/113462277/405686b5-6d44-461a-9b65-80170423f64f)
