### ISSUE TITLE
[Sign In] 'Password' field is not highlighted and no error-message is displayed after trying to sign in with empty password

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#636]
**Environment:** Windows Server 2012 R2 Standard x64, Google Chrome 81.0.4044.129,
Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 7439e88

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Sign-in' link.
3. Enter valid data into 'Email' field (using "@" symbol).
4. Leave 'Password' field empty.
5. Click on 'Sign-in' button.

**Actual result**
'Password' field is not highlighted in red color and error message is not displayed under 'Password' field.
![Sign in empty pass act](https://user-images.githubusercontent.com/64583544/81207888-f6866e80-8fd6-11ea-8d61-922bcb5ab469.png)

**Expected result**
''Password' field is highlighted in red color and error message is displayed under 'Password' field: **_"Password is required"_**.
![Sign in empty pass exp](https://user-images.githubusercontent.com/64583544/81207909-fe461300-8fd6-11ea-8976-e76287df425d.png)

User story #471
Test case https://jira.softserve.academy/browse/GC-523

**Comment by rsyvulko** [comment]
**Additional info.**
Bug is reproducable only if user doesn't try to type any symbols in field or even click on field and clicks on 'Sign-in' button. If user click on field or type something and delete it, validation starts working.

**Comment by KimAT25** [comment]
As we have to input data in all fields, this bug isn`t relevant, as sign-in button are disabled according story #471. 
Fixed only error message part.

**Comment by rsyvulko** [comment]
Verified.
