### ISSUE TITLE
[Sign in] There is no Scroll-bar on the “Sign-in” modal window after clicking on “My cabinet” button

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#637]
**Environment:** macOS High Sierra 10.13.16, Google Chrome 81.0.4044.129 (64-bit), Firefox 76.0
**Reproducable:** always
**Build found:** commit 7439e88

**Preconditions:**
Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome;

**Steps to reproduce**
1. Click on 'My cabinet' button;
2. Press F12;
2. Verify that scroll-bar is present on the “Sign-in” modal window after page resizing (e.g. set 50 %, 150%).

**Actual result**
There is no Scroll-bar on the “Sign-in” modal window on browser Chrome 81.0.4044.129 and Firefox 76.0.

**Expected result**
Scroll-bar is present on the “Sign-in” modal window.

**User story:** #551

Attached files: modal window on Google Chrome 81.0.4044.129 (64-bit) and Firefox 76.0

![My cabinet Chrome 50%](https://user-images.githubusercontent.com/64582769/81228102-26913a00-8ff6-11ea-89d8-002686dd17a8.png)
![My cabinet Chrome 150%](https://user-images.githubusercontent.com/64582769/81228116-2abd5780-8ff6-11ea-8747-a06efb655903.png)

![My cabinet Firefox](https://user-images.githubusercontent.com/64582769/81228341-9c95a100-8ff6-11ea-8e16-b6dbd91dfc73.png)

**Comment by KimAT25** [comment]
not relevant
