### ISSUE TITLE
[UBS Admin Cabinet] When adding 'Add service', the number in the 'Basic cost' column is not displayed correctly

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6370]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 19.09.2023
Preconditions

1. The user should be logged in https://www.greencity.social/#/greenCity as a Super Admin

Steps to reproduce

1. Click on the 'Tariffs' tab
2. Choose the pricing card without 'Services'
3. Click on the  'Add service' button
4. Fill in all required fields
5. In the 'Basic cost' field, write the number '100'
6. Click on the  'Add' button
7. Pay attention to the number in the 'Basic cost' column

Actual result
The number '1.00' is displayed 

Expected result
The number '100.00' should be displayed

User story https://github.com/ita-social-projects/GreenCity/issues/4428

"Bug", Priority ("Medium"), Severity ("Major"), Type ("Functional")
![Screenshot_1](https://github.com/ita-social-projects/GreenCity/assets/131760121/5b88b069-41c6-40f5-94a2-e9783d77c1e1)
![Screenshot_2](https://github.com/ita-social-projects/GreenCity/assets/131760121/0e074c8d-2462-4480-af60-fb2c7fe2267c)

**Comment by Daria811** [comment]
The price '1.00' is displayed when the Admin enters the '100'. But after editing the basic price for '100', the number '100.00' is displayed. 
This problem reproduces only when the Admin adds the new tariff.
