### ISSUE TITLE
Event was commented notification

### ISSUE THREAD

**Issue by KateHorb** [ita-social-projects/GreenCity#6376]
**As a** user **I want to** be notified when an event I posted was commented **so that** I can reply people's questions soon

**Preconditions**
1. User created an event and another user left a comment

### Acceptance Criteria
- When a new comment is left under the user's event, the user must get a new notification about it
   - A notification counter value is increased by one
- User should see a corresponding notification record when he views the most recent notifications popup or All notifications page: 
  - [Username] commented on your event [Event name]. [Date and Time] 
     - (ex. "Maria commented on your event Eco Day. Today 10:00 a.m")
     - [Username] - user who left a message
        - If more than one user left a comment by the moment the user sees this notification, then the usernames of 2 last commentators and "other users" should be instead (ex, "Maria, Olha and other users commented on your event Eco Day. Today 10:00 a.m")
        - If the same user left more than one comment on the same event by the moment the user sees this notification, then user should see only the latest one in the notification record 
     - [Event name] - name of the event. Should be a link, should be cut if too long (?)
     - [Date and time] - Date and time when the comment was left. 
        - Date format is DD.MM.YYYY
        - Time format is  HH:MM XM 
           - If the day = Today, then use "Today" word instead of calendar date 
           - If the day = Today - 1, then use "Yesterday" word instead of calendar date

**Epic link**
E.g.: Epic #6332 

**Labels to be added**
"User story"

**Comment by IliaWithHat** [comment]
Already done in EventCommentServiceImpl 123 line.
