### ISSUE TITLE
Event was liked notification

### ISSUE THREAD

**Issue by KateHorb** [ita-social-projects/GreenCity#6377]
**As a** user **I want to** be notified when somebody likes the event I created **so that** I am always aware that people are interested in my events

**Preconditions**
1. User created an event and another user liked it

### Acceptance Criteria

- When another user likes the event, the author of this event should be notified about it
   - A notification counter value is increased by one
- User can see a corresponding notification record when he views the most recent notifications popup or All notifications page:
   - [Username] likes your event [Event name]. [Date and Time] 
      - (ex. "Maria likes your event Eco Day. Today 10:00 a.m")
   - [Username] - user who likes the event
      - If more than one user liked the event by the moment the author sees this notification, then the usernames of 2 last users and "other users" should be instead (ex, "Maria, Olha and other users like your event Eco Day. Today 10:00 a.m")
         - A notification counter value is increased by one
      - If the same user liked more than one event by the moment the user sees this notification, then user should see all corresponding notifications in order from the latest notification to the earliest one
         - A notification counter value is increased by one each time a new event is liked
   - [Event name] - name of the event. Should be a link, should be cut if too long (?)
   - [Date and time] - Date and time when the comment was left.
       - Date format is DD.MM.YYYY
       - Time format is HH:MM XM
       - If the day = Today, then use "Today" word instead of calendar date
       - If the day = Today - 1, then use "Yesterday" word instead of calendar date

**Epic link**
E.g.: Epic #6332 

**Labels to be added**
"User story"

**Comment by VinuVicho** [comment]
Are you sure event is likeble?
Cannot find this on backend\
