### ISSUE TITLE
Event was canceled notification

### ISSUE THREAD

**Issue by KateHorb** [ita-social-projects/GreenCity#6378]
**As a** гиук **I want to** get notified when the event I joined is cancelled **so that** I won't be surprised on the day of the event

**Preconditions**
1. User has joined an upcoming event but it was cancelled 

### Acceptance Criteria
- When the event user has joined is cancelled, the user must get a notification about it 
- User should see a corresponding notification record when he views the most recent notifications popup or All notifications page:
  - Unfortunately, event [Event name] was cancelled. [Date and Time]
     - (ex. "Unfortunately, event Eco Day was cancelled. Today 10:00 a.m")
     - [Event name] - name of the event. Should be a link, should be cut if too long (?)
     - [Date and time] - Date and time when the comment was left.
        - Date format is DD.MM.YYYY
        - Time format is HH:MM XM
        - If the day = Today, then use "Today" word instead of calendar date
        - If the day = Today - 1, then use "Yesterday" word instead of calendar date

**Epic link**
E.g.: Epic #6332 

**Labels to be added**
"User story"

**Comment by IliaWithHat** [comment]
Already done in EventServiceImpl 212 line.
