### ISSUE TITLE
Event was updated notification

### ISSUE THREAD

**Issue by KateHorb** [ita-social-projects/GreenCity#6379]
**As a** user **I want to** be notified if the event I joined was updated **so that** I can adjust my plans early

**Preconditions**
1. User has joined the event, but it was updated 

### Acceptance Criteria
- User must always be notified when one of the following updates of the event he joined were made:
   -  Event name
       - Show message: "Event [Previous event name] was updated. New name is [New event name]. [Date and time]"
       - eg. "Event Eco Day was updated. New name is Eco Life. Today 10:00 am" 
   - Event date and time
       - Show message: "Date and time for event [Event name] was updated. New date and time is [Event date and time]. [Date and time]"
       - eg. "Date and time for event Eco Day was updated. New date and time is Sep 23, 2023 10:00 am. Today 10:00 am" 
    - Event location
       - Show message: "Location for event [Event name] was updated. New location is [Event location]. [Date and time]"
       - eg. "Location for event Eco Day was updated. New location is Lviv, Svobody avenue 28. Today 10:00 am" 

**Epic link**
E.g.: Epic #6332 

**Labels to be added**
"User story"

**Comment by VinuVicho** [comment]
What if updated wasnt the name?
Result of this notification will be: `Event Eco Day was updated. New name is Eco Day.`
Is this ok?
