### ISSUE TITLE
[Sign up] There is no Scroll-bar on the “Sign-up” modal window after page resizing

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#638]
**Environment:** macOS High Sierra 10.13.16, Google Chrome 81.0.4044.129 (64-bit), Firefox 76.0
**Reproducable:** always
**Build found:** commit 7439e88

**Preconditions:**
Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome;

**Steps to reproduce**
1. Click on 'Sign up' button;
2. Press F12;
3. Verify that scroll-bar is present on the “Sign-up” modal window after page resizing (e.g. set 50 %, 150%).

**Actual result**
There is no Scroll-bar on the “Sign-up” modal window on browser Chrome 81.0.4044.129.

**Expected result**
Scroll-bar is present on the “Sign-up” modal window.

**User story:** #551

Attached files: modal window 'Sign up' on browser Chrome 81.0.4044.129.

![Sign up Ghrome 50%](https://user-images.githubusercontent.com/64582769/81228666-1af24300-8ff7-11ea-8fc1-b9ab70ed0e4e.png)
![Sign up Ghrome 150%](https://user-images.githubusercontent.com/64582769/81228675-1ded3380-8ff7-11ea-8b81-597e5956675c.png)

**Comment by KimAT25** [comment]
will be made mock-up of visual look of scroll bar by designer. Scroll should be present, but hidden.
