### ISSUE TITLE
[API] [Friend list] [/friends/not-friends-yet] The response contains users that do not have a "+" in the search name portion

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6383]
**Environment:** Windows 10 Pro, Postman
**Reproducible:** always
**Build found:** 21.09.23

**Preconditions**
1. The user is logged in, and the token is gotten.
2. At least one user, who is not a friend yet, exists (e.g. name: 'Nataliia-Hrusha+Наталія_Груша')

**Steps to reproduce**
1. Send the request: GET greencity.greencity.social/friends/not-friends-yet?name={parameter} 
(e.g. {parameter}: '+')
3. Check a response.

**Actual result**
The status code is 200 OK. There are users without {parameter} in the part of the name in the response.
![image](https://github.com/ita-social-projects/GreenCity/assets/138515375/38ea9424-939f-4fb4-8865-51d1663e728f)

**Expected result**
The status code is 200 OK. There is the user with {parameter} in the part of the name in the response.

**User story and test case links**
User story #1003

**Comment by ABbondar** [comment]
This endpoint works correctly.
Retest, please, via swagger or send such request (http://localhost:8080/friends/not-friends-yet?name=%2B&page=0&size=5) from postman
