### ISSUE TITLE
[API] [Friend list], [Get Friends/not-friends-yet] There is response code 500 Internal Server Error instead 400 Bad Request when user send invalid value

### ISSUE THREAD

**Issue by OksanaPyrozhok** [ita-social-projects/GreenCity#6384]
**Environment** Windows,10, Postman
**Reproducible:** always
**Build found:** 21.09.2023

**Preconditions**
1.Sign in as User, used Token
2.Open API test tool (e.g. Swagger , Postman).

**Steps to reproduce**
1. Choose GET [/friends/not-friends-yet], https://greencity.greencity.social/swagger-ui.html#/friend-controller/findAllUsersExceptMainUserAndUsersFriendUsingGET
2. Input invalid Params Name and Sort (/friends/not-friends-yet?name=sfddf&sort=113)

**Actual result**
The status code is 500 Internal Server Error

![image](https://github.com/ita-social-projects/GreenCity/assets/138609814/05aca76d-4a7b-432c-9b56-869f935eb188)

**Expected result**
The status code must be 400 Bad Request

**User story and test case links**
E.g.: "User story #1003

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:major"), Type ("Functional"), "API" (for back-end bugs).

**Comment by LiliaMokhnatska** [comment]
duplicate https://github.com/ita-social-projects/GreenCity/issues/6382

**Comment by LiliaMokhnatska** [comment]
duplicate https://github.com/ita-social-projects/GreenCity/issues/6382
