### ISSUE TITLE
[API] [Friend list] GET friends/not-friends-yet There is an unnecessary response 404 Not Found

### ISSUE THREAD

**Issue by OksanaPyrozhok** [ita-social-projects/GreenCity#6387]
**Environment:** Windows 10, Postman
**Reproducible:** always
**Build found:** 22.09.2023

 Open GET/friends/not-friends-yet in your documentation

**Actual result**
There is code 404 Not Found

**Expected result**
There should be no 404 code Not Found. 
When User enters invalid name always should be code 200 Ok and empty array.

**User story and test case links**
E.g.: "User story #1003

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:major"), Type ("Functional"), "API" (for back-end bugs)

**Comment by ABbondar** [comment]
This endpoint can throw "Not found exception" when current user does not exists in db by user id.
