### ISSUE TITLE
[Forgot password] There is no Scroll-bar on the “Forgot password” modal window after page resizing

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#639]
**Environment:** macOS High Sierra 10.13.16, Google Chrome 81.0.4044.129 (64-bit), Firefox 76.0
**Reproducable**: always
**Build found:** commit 7439e88

**Preconditions:**
Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome;

**Steps to reproduce**
1. Click on 'Sign in' button;
2. Click on "Forgot password" link;
3. Press F12;
5. Verify that scroll-bar is present on the “Forgot password” modal window after page resizing (e.g. set 50 %, 150%).

**Actual result**
There is no Scroll-bar on the “Forgot password” modal window on browser Chrome 81.0.4044.129.

**Expected result**
Scroll-bar is present on the “Forgot password” modal window.

**User story:** #551

Attached files: modal window on browser Chrome 81.0.4044.129.

![Forgot password Chrome 150%](https://user-images.githubusercontent.com/64582769/81228811-6a387380-8ff7-11ea-8026-7b7a38b39ce0.png)
![Forgot password Chrome50%](https://user-images.githubusercontent.com/64582769/81228817-6dcbfa80-8ff7-11ea-8f50-7dd4839f99dc.png)

**Comment by KimAT25** [comment]
will be made mock-up of visual look of scroll bar by designer. Scroll should be present, but hidden.
