### ISSUE TITLE
[API] [Friend list] [/friends/not-friends-yet] The response has a status 400 instead of 200 when entering ']', '{', '^', '`' symbols in the search field

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6399]
**Environment:** Windows 10 Pro, Postman
**Reproducible:** always
**Build found:** 23.09.2023

**Preconditions**
The user is logged in, and the token is gotten.

**Steps to reproduce**
1. Send the request: GET greencity.greencity.social/friends/not-friends-yet?name={parameter}
(1 e.g. {parameter}: ']'
2 e.g. {parameter}: '['
3 e.g. {parameter}: '^'
4 e.g. {parameter}: '`'
5 e.g. {parameter}: '{'
6 e.g. {parameter}: '}'
7 e.g. {parameter}: '|')
2. Check a response.

**Actual result**
The status code is 400 Bad Request. 
![image](https://github.com/ita-social-projects/GreenCity/assets/138515375/b47a7372-6013-4f9a-8432-41c85b88cf20)

**Expected result**
The status code is 200 OK. The response has an empty array.

**User story and test case links**
User story #1003

**Comment by VadimasikKPI** [comment]
Tomcat Server version 8.5+ can`t decode special characters, we can`t solve this problem until Tomcat in newer version solve it!

**Comment by ryhaldenys** [comment]
This bug is not reproduced

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/3cd9e4f6-d23d-4a8f-aeb8-c666feff3255)

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/ca25bc4a-f40d-47d7-b4eb-21df4e91b83a)
