### ISSUE TITLE
[API] [Friend list] [/friends/not-friends-yet] The response has users instead of empty array when entering '#', '%', '&', '_' symbols in the search field

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6400]
**Environment:** Windows 10 Pro, Postman.
**Reproducible:** always
**Build found:** 23.09.2023

**Preconditions**
The user is logged in, and the token is gotten.

**Steps to reproduce**
1. Send the request: GET greencity.greencity.social/friends/not-friends-yet?name={parameter}
(1 e.g. {parameter}: '#'
2 e.g. {parameter}: '%'
3 e.g. {parameter}: '&'
4 e.g. {parameter}: '_' )
2. Check a response.

**Actual result**
The status code is 200 OK. There are users in the response.
![image](https://github.com/ita-social-projects/GreenCity/assets/138515375/83bf637b-3a22-4a79-984b-e416abef3222)

**Expected result**
The status code is 200 OK. The response has an empty array.

**User story and test case links**
User story #1003

**Comment by HrushaNataliia** [comment]
Сontinues to reproduce with '%' and '&'.

**Comment by LiliaMokhnatska** [comment]
on backend side everything is ok

**Comment by HelenSotnik** [comment]
Issue is not reproducible. As I tried all mentioned symbols, returned only for '-', as some of users names contain this symbol. For other, always returns empty array. 
<img width="1470" alt="Screenshot 2024-05-31 at 12 08 32" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/4bff2b09-9d72-4717-8b1a-3abf8364c2cb">
<img width="1470" alt="Screenshot 2024-05-31 at 12 08 26" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/5690eff2-41d6-49de-9607-041bbe2bde3a">
<img width="1470" alt="Screenshot 2024-05-31 at 12 09 59" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/d91eacfc-7e3b-44cf-bede-13dbcc89d43a">
<img width="1470" alt="Screenshot 2024-05-31 at 12 13 10" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/3131ac60-712b-4bcf-9731-813782ace64b">
