### ISSUE TITLE
[API] System allow register user with name, more than 20 characters

### ISSUE THREAD

**Issue by traviscolt** [ita-social-projects/GreenCity#641]
**Reproducable:** always

**Steps to reproduce:**
1. Click 'own-security-controller' drop-down page
2. Click '/ownSecurity/signUp' request
3. Click "Try out" button
4. Edit request {
  "email": "string",
  "name": "string",
  "password": "string"
   }
 - Enter valid email
 - Enter name that contains more than 20 characters
 - Enter valid password
5. Click 'Execute' button

**Actual result:**
The user was created. The user receives response 201 {
 access-control-allow-credentials: true 
}
![Screenshot_13](https://user-images.githubusercontent.com/35031131/81213519-233e8400-8fdf-11ea-9730-bb96af248211.jpg)
**Expected result:**
The user is not created. The user receives response 400. 
  {
    "name": "name",
    "message": "User name must be from 1 to 20 characters"
  }

User story #385 
Test case https://jira.softserve.academy/browse/GC-540

**Comment by rsyvulko** [comment]
Not fixed. It is still possible to create user with username with more than 20 characters via API call.
![long username](https://user-images.githubusercontent.com/64583544/83276162-e37f4c80-a1d8-11ea-9eb6-6384e9f141b5.png)
