### ISSUE TITLE
[My space] UI The User’s avatar doesn't match User's changed name

### ISSUE THREAD

**Issue by VlasenkoYuliia** [ita-social-projects/GreenCity#6426]
**Environment:** 
macOS  Version 13.4.1
Google Chrome 
Version 117.0.5938.88 (Official Build) (arm64)

**Reproducible:** always
**Build found:** 
21/09/23
**Preconditions**
User Logged-in with Google
continue as User's Name

**Steps to reproduce**
1. Go to 'Edit Profile';
2. Change 'Name' the First letter needs to be different from User's name;
3. Click 'Save' button;

**Actual result**
the User’s avatar doesn't match User's changed name
<img width="193" alt="Screenshot 2023-09-27 at 09 35 32" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/8734203c-bcba-49f0-afd6-f3ade5fefb71">

**Expected result**
The first letter of User's changed name need to match with the letter displayed in the Avatar

**Postconditions**

**User story and test case links**
https://jira.softserve.academy/browse/GC-8004
**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by ShyraiDan** [comment]
Can't reproduce

**Comment by VlasenkoYuliia** [comment]
User Logged-in with Google

**Comment by nina279** [comment]
Can't save any changes to the user profile: 
name, city (message "This page can't load Google Maps correctly." appears), credo.
Server returns 500
The same mistake for the regular login and for logging via Google.

**Comment by nina279** [comment]
resolved

**Comment by VlasenkoYuliia** [comment]
the User’s avatar doesn't match User's changed name

https://github.com/ita-social-projects/GreenCity/assets/138223368/a615e097-9000-44b7-8e02-f69241bc2c85

**Comment by nina279** [comment]
Can't reproduce the bug on different OS using different accounts:
macOS Ventura Version 13.4 (22F66)
Windows 10 Education 22H2
two user accounts sign-in via Google

**Comment by ShyraiDan** [comment]
This bug reproduces only for old user, try create a new one and your avatar will be default

**Comment by VlasenkoYuliia** [comment]
resolved
