### ISSUE TITLE
[News] The 'Edit date' format change for UA language

### ISSUE THREAD

**Issue by VlasenkoYuliia** [ita-social-projects/GreenCity#6435]
**Environment:** 
macOS  Version 13.4.1
Google Chrome 
Version 117.0.5938.88 (Official Build) (arm64).
**Reproducible:** always.
**Build found:** 
25/09/23

**Preconditions**
At least a News is added;
a News includes a User's edited comment.

**Steps to reproduce**

1. Open the site https://www.greencity.social/#/greenCity;
2. Logged-in as User;
3. Choose UA language;
4. Click on the 'Eco news' tab;
5. Click on the News that includes an edited comment;
6. Verify the 'Edit date' is after the label 'Edited'.

**Actual result**
the 'Edit date' format
(25 вер. 2023 р.
dd/mmm./yyyy p.)
doesn't match mock-up and AC#5-6 in the Change request to #3210 <Edit comment> #6413
where c) the system displays the date of the edit 'Edit date' as mmm/dd,/yyyy (eg. Sep 12, 2023) after the label 'Edited';
<img width="886" alt="Screenshot 2023-09-25 at 10 26 37" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/02cfc044-9d8a-44cc-a776-90e698ace8c0">

**Expected result**
The system displays the date of the edit 'Edit date' as mmm/dd,/yyyy (eg. Sep 12, 2023) after the label 'Edited'.

<img width="664" alt="Screenshot 2023-09-25 at 10 30 00" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/7c56446a-2353-4202-96bf-8868747dd137">

**Postconditions**

**User story and test case links**
E.g.: "User story #6413
[Test case](https://jira.softserve.academy/browse/GC-8041)"

**Labels to be added**
"Bug", Priority ("low "), Severity ("trivial"), Type ("UI"), "API" (for back-end bugs).

**Comment by OksanaFilipchuk** [comment]
The mock-up has only English version and date format mmm/dd,/yyyy (eg. Sep 12, 2023) is used in the USA. But in Ukraine dates are usually written in "day month year" (DMY) order.

**Comment by VlasenkoYuliia** [comment]
thank you, I will close the bug for the reason Not a bug

**Comment by VlasenkoYuliia** [comment]
close for the reason Not a bug
