### ISSUE TITLE
[Forgot password]: Incorrect ''Submit a login link' button size

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#645]
**Environment:** macOS Catalina 10.15.4, Safari 13.1
**Reproducible:** always
**Build found:** commit 7439e88

**Preconditions:**
Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome;

**Steps to reproduce:**
1. Click on the 'Sign in' button in the top right part of the window.
2. Click on 'Forgot password?' link.

**Actual result:**
Incorrect 'Submit a login link' button size at Ukrainian and Russian localization

<img width="1015" alt="Incorrect ''Submit a login link' button size - ukr" src="https://user-images.githubusercontent.com/64583209/81221870-170cf380-8fec-11ea-9409-4ae89fc2528f.png">

<img width="997" alt="Incorrect ''Submit a login link' button size - rus" src="https://user-images.githubusercontent.com/64583209/81221886-1e340180-8fec-11ea-91a5-5ac5230a8460.png">

**Expected result:**
'Submit a login link' button should be at on mock-up

<img width="676" alt="Correct ''Submit a login link' button size" src="https://user-images.githubusercontent.com/64583209/81221901-2429e280-8fec-11ea-909f-cb4b92abb0d6.png">

User story: #472

**Comment by greatpanda1603** [comment]
Already fixed:

![image](https://user-images.githubusercontent.com/52715377/85552931-2a236380-b62c-11ea-8dbc-cb5f4406d60a.png)
![image](https://user-images.githubusercontent.com/52715377/85553030-41625100-b62c-11ea-80e1-0381f87f34d7.png)

**Comment by MariaKorniavka** [comment]
Not Fixed



<img width="984" alt="Screenshot 2020-06-30 at 21 41 50" src="https://user-images.githubusercontent.com/64583209/86164804-07f18000-bb1b-11ea-8d8a-55e0e61a45ea.png">
<img width="989" alt="Screenshot 2020-06-30 at 21 43 07" src="https://user-images.githubusercontent.com/64583209/86164812-0b850700-bb1b-11ea-98ee-f5fea3399b7c.png">

**Comment by MariaKorniavka** [comment]
Not Fixed

**Comment by NazariyPylypchuk** [comment]
not fixed

**Comment by sofiiamatsyhin** [comment]
[
<img width="950" alt="Screen Shot 2020-07-22 at 15 16 20" src="https://user-images.githubusercontent.com/55846203/88175392-78795180-cc2e-11ea-9087-5b4554bdcecf.png">
<img width="1001" alt="Screen Shot 2020-07-22 at 15 16 43" src="https://user-images.githubusercontent.com/55846203/88175403-7d3e0580-cc2e-11ea-8d1b-52498d7367b8.png">

](url)
