### ISSUE TITLE
[Friends list] [My friends] tab/ EN and UA localisation for screen resolution 1024x1584px  does not match the mock-up

### ISSUE THREAD

**Issue by BerezovychRomana** [ita-social-projects/GreenCity#6455]
**Environment:** Mac OS, browser Chrome, version: 117.0.5938.92
**Reproducible:** always
**Build found:** 29/09/2023

**Preconditions**
1. The user is logged in https://www.greencity.social/#/greenCity
2. [My friends] page is opened

**Steps to reproduce**
1. EN localization is chosen
2. The screen resolution of the window is 1024x1584px 
3. Zoom is 100%
4. UA localization is chosen
5. Repeat steps 2-3

**Actual result**
[My friends] tab does not match the mock-up on screen resolution 1024x1584px 
EN localization: <img width="445" alt="Знімок екрана 2023-09-29 о 11 26 49" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/67febb49-7e83-459f-899e-92a8f130eef1">
UA localization:
<img width="1040" alt="Знімок екрана 2023-09-29 о 11 57 10" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/b041edd5-81c2-47fe-b5e3-01796e27f6ce">

**Expected result**
[My friends] match the mock-up on screen resolution 1024x1584px 
<img width="794" alt="Знімок екрана 2023-09-29 о 11 27 17" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/75ec85c6-b04d-486b-96bd-21f74f5b3d10">

**User story and test case links**
E.g.: "User story #2122 
[GC-8165](https://jira.softserve.academy/browse/GC-8165)

**Comment by OksanaFilipchuk** [comment]
Styles was fixed. 
But there are 
3 buttons according to the change request  [#6423](https://github.com/ita-social-projects/GreenCity/issues/6423) 
and 2 buttons according to design
