### ISSUE TITLE
 [Friends list] [My friends] EN and UA localization alignment of elements are incorrect for tab and field on screen resolution is 1024x1584px

### ISSUE THREAD

**Issue by BerezovychRomana** [ita-social-projects/GreenCity#6456]
Environment: Mac OS, browser Chrome, version: 117.0.5938.92
Reproducible: always
Build found: 29/09/2023

Preconditions

1. The user is logged in https://www.greencity.social/#/greenCity
2. [My friends] page is opened

Steps to reproduce
1. EN localization is chosen
2. The screen resolution of the window is 1024x1584px
3. Zoom is 100%
4. Ua localization is chosen 
5. Repeat steps 2-3

**Actual result**
The alignment of elements  tab and field are incorrect
EN localization: <img width="410" alt="Знімок екрана 2023-09-29 о 11 49 04" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/ed6abdf9-4c24-4596-997a-a6b450f8696b">
UA localization:
<img width="1040" alt="Знімок екрана 2023-09-29 о 11 57 10" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/3f860663-dc12-474f-a24c-7e4a368c3a91">

**Expected result**
UI controls have alignment according to mock-up design

User story and test case links
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/2122
[GC-8165](https://jira.softserve.academy/browse/GC-8165)
[GC-8170](https://jira.softserve.academy/browse/GC-8170)

**Comment by OksanaFilipchuk** [comment]
Styles was fixed. 
But there are 
3 buttons according to the change request  [#6423](https://github.com/ita-social-projects/GreenCity/issues/6423) 
and 2 buttons according to design
