### ISSUE TITLE
[Friends list] [My friends] EN  and Ua localization alignment of elements  tab and field are incorrect for screen resolution 768x1664px

### ISSUE THREAD

**Issue by BerezovychRomana** [ita-social-projects/GreenCity#6457]
Environment: Mac OS, browser Chrome, version: 117.0.5938.92
Reproducible: always
Build found: 29/09/2023

Preconditions

1. The user is logged in https://www.greencity.social/#/greenCity
2. [My friends] page is opened

 Steps to reproduce

1. EN localization is chosen
2. The screen resolution of the window is 768x1664px
3. UA localization is chosen 
4. The screen resolution of the window is 768x1664px

**Actual result**
The alignment of elements  tab and field are incorrect
EN localization:
<img width="993" alt="Знімок екрана 2023-09-29 о 12 30 40" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/9aae6db5-8a5d-4028-8342-d8034e317f1e">
UA localization:
<img width="870" alt="Знімок екрана 2023-09-29 о 12 25 53" src="https://github.com/ita-social-projects/GreenCity/assets/107962063/74a049e0-d4aa-46cd-855e-b63554fdbccd">

**Expected result**
The alignment of elements are correct and match mock-up

User story and test case links
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/2122
[GC-8180](https://jira.softserve.academy/browse/GC-8180)
[GC-8181](https://jira.softserve.academy/browse/GC-8181)

**Comment by OksanaFilipchuk** [comment]
Styles was fixed. 
But there are 
3 buttons according to the change request  [#6423](https://github.com/ita-social-projects/GreenCity/issues/6423) 
and 2 buttons according to design
