### ISSUE TITLE
[Forgot password]: English Label text differs from Ukrainian and Russian Labels texts

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#646]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit), Safari 13.1, Firefox 75.0 (64-bit)
**Reproducible:** always
**Build found:** commit 7439e88

**Preconditions:**'
Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome;

**Steps to reproduce:**
1. Click on the 'Sign in' button in the top right part of the window.
2. Click on 'Forgot password?' link.

**Actual result:**
Label at English localization is - 'Enter your email address and we'll send you a link to regain access to your account'

<img width="1108" alt="engl" src="https://user-images.githubusercontent.com/64583209/81226064-ebd9d280-8ff2-11ea-879d-31a04f2eb47a.png">

Label at Ukrainian localization is - 'Введіть ім'я користувача або електронну адресу, і ми надішлемо вам посилання для відновлення доступу до облікового запису.'

<img width="1017" alt="ukr" src="https://user-images.githubusercontent.com/64583209/81226077-f1371d00-8ff2-11ea-9197-f254521e48d6.png">

Label at Russion localization is - 'Введите имя пользователя или электронный адрес, и мы вышлем вам ссылку для восстановления доступа к аккаунту'

<img width="998" alt="rus" src="https://user-images.githubusercontent.com/64583209/81226097-f85e2b00-8ff2-11ea-9cfa-77ab699c1ff7.png">

At English localization user can enter **only email address**, but
at Ukrainian and Russian user can enter **name OR email address.**

**Expected result:**
Labels should have the same text at different localization.

User story: #472

**Comment by nvolodymyr** [comment]
fixed

**Comment by MariaKorniavka** [comment]
Verified
