### ISSUE TITLE
[Friend list] The name of the first tab is "All friends” instead of "My friends” and the default text in the search field is "Find a friend” instead of "Search”

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6465]
**Environment:** Windows 10 Pro, Google Chrome (117.0.5938.132)
**Reproducible:** always
**Build found:** 29.09.2023

**Preconditions**
The user is logged in to Green City https://www.greencity.social/#/profile
The EN localization is chosen.

**Steps to reproduce**
1. Go to the 'My Eco Friends' page https://www.greencity.social/#/profile/372/friends
2. Take a look at the text in the search field by default.
3. Take a look at the name of the first tab

**Actual result**
1. The default text in the search field is "Find a friend”.
2. The first tab is named "All friends”.
![2023-09-29 19 03 19](https://github.com/ita-social-projects/GreenCity/assets/138515375/b1e8f080-8c98-405e-b93a-85ed9b8f1291)

**Expected result**
1. The default text in the search field is "Search”.
2. The first tab is named "My friends”.
This is a sketch, the mockup is still in progress
![2023-09-30 11 26 59](https://github.com/ita-social-projects/GreenCity/assets/138515375/541f1606-caec-4d0a-b86b-9909112d2a40)

**User story and test case links**
User story #6423

**Comment by nina279** [comment]
resolved
