### ISSUE TITLE
[Friends List] Friend cards appear randomly to the right of the friend's profile form after scrolling down to the bottom and then scrolling up to the top

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6467]
**Environment:** Windows 10 Pro, Google Chrome (117.0.5938.132)
**Reproducible:** sometimes 
**Build found:** 29.09.2023

**Preconditions**
The user is logged in to Green City https://www.greencity.social/#/profile
The 'My Eco Friends' page is opened.

**Steps to reproduce**
1. Go to the 'Find a friend' tab
2. Click on the friend's card (e.g.1: Юлія Вальковець, e.g.2: Secaj, e.g.3: Antonenko Daria,  e.g.4: UBSADMIN2 )
3. Scroll down to the bottom and then scroll up to the top

**Actual result**
Friend cards appear randomly to the right of the friend's profile form. (Reproduced only with the first four users in the 'Find a friend' tab).
https://github.com/ita-social-projects/GreenCity/assets/138515375/c0d4a07a-c14b-41c5-87dc-fa27bfe62a4e

**Expected result**
There is an empty field to the right of the friend's profile form.
![2023-09-29 21 18 42](https://github.com/ita-social-projects/GreenCity/assets/138515375/9556f0bb-7f45-4bfe-98e4-d50ba019cdfd)

**User story and test case links**
User story #1003

**Comment by ShyraiDan** [comment]
Can't reproduce
