### ISSUE TITLE
[Friend list] The system finds users without the special character in the name when entering a special symbol instead of not finding users

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6473]
**Environment:** Windows 10 Pro, Google Chrome (117.0.5938.132)
**Reproducible:** always
**Build found:** 30.09.23

**Preconditions**
The user is logged in to Green City https://www.greencity.social/#/profile
The EN localization is chosen.
The 'My Eco Friends' page is opened.

**Steps to reproduce**
1. Go to the 'Find a friend' tab
2. Enter into the 'Search' field special characters (e.g. one of these symbols: # % & )

**Actual result**
Users without the special character in the name are found.
![2023-09-30 21 11 24](https://github.com/ita-social-projects/GreenCity/assets/138515375/99d82f0e-2b13-4278-a531-712b45134ed8)

**Expected result**
No users were found. The 'We didn't find any results matching this search' message is shown below the 'Search' field.
This is a sketch, the mockup is still in progress
![2023-09-30 20 45 46](https://github.com/ita-social-projects/GreenCity/assets/138515375/b6bb2baa-2764-493a-aab4-0250ac43da1a)

**User story and test case links**
User story #1003
[GC-8193](https://jira.softserve.academy/browse/GC-8193)

**Comment by nina279** [comment]
https://github.com/ita-social-projects/GreenCity/issues/6472 duplicate
