### ISSUE TITLE
[Friend list] The system doesn't find a user who has '+' character in the name when searching

### ISSUE THREAD

**Issue by HrushaNataliia** [ita-social-projects/GreenCity#6475]
**Environment:** Windows 10 Pro, Google Chrome (117.0.5938.132)
**Reproducible:** always
**Build found:** 30.09.23

**Preconditions**
The user is logged in to Green City https://www.greencity.social/#/profile
The EN localization is chosen.
The 'My Eco Friends' page is opened.
At least one user with '+' in the name exists.

**Steps to reproduce**
1. Go to the 'Find a friend' tab
2. Enter into the 'Search' field '+' special character.

**Actual result**
Users without the '+' special character in the name are found.
![2023-09-30 21 38 59](https://github.com/ita-social-projects/GreenCity/assets/138515375/be470029-1b10-4f8c-b9c4-36b353158784)

**Expected result**
Users with the '+' special character in the name are found.

**User story and test case links**
User story #1003
[GC-8192](https://jira.softserve.academy/browse/GC-8192)

**Comment by nina279** [comment]
resolved
