### ISSUE TITLE
[Event Description] Event's attendees are not notified of the event's deletion by email

### ISSUE THREAD

**Issue by Bezrodna1988** [ita-social-projects/GreenCity#6476]
**Environment:** Windows 10x64, Google Chrome 116.0.5845.189.
**Reproducible:** always.
**Build found:** 30.09.2023

**Preconditions**
1. The https://www.greencity.social/#/greenCity is opened
2. Admin is logged in.
3. The Events page is opened.
4. There is a saved active offline event (with attendees) created by the admin (or organizer).

**Steps to reproduce**
1. Click the 'More' button on the card of the active offline event (see preconditions) at the Event dashboard.
2. Click the 'Delete' button on the Event description page.
3. Click the 'Yes' button. 

**Actual result**
Event's attendees are not notified of the event's deletion by email

**Expected result**
Attendees are notified of the event's deletion by email.

**User story and test case links**
E.g.: "User story #3196 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("Functional")

**Comment by ABbondar** [comment]
retest please
