### ISSUE TITLE
[API] Incorrect error message when sign in with unregistered email

### ISSUE THREAD

**Issue by nadiiakuzmin** [ita-social-projects/GreenCity#648]
**Environment:** Swagger

**Reproducible**: always

**Preconditions**
User is registered with correct credentials: email and password.
**Steps to reproduce**
1. Go to GreenCity swagger  https://greencity.azurewebsites.net/swagger-ui.html#/
2. Open 'Sign-in by own security logic' request via /ownSecurity/signIn api call.
3. Click "Try out" button.
4. Edit request: {
  "email": "unregistered email",
  "password": "password"
}
5. Click "Execute" button.

**Actual result**
Error message "No message available" is in Response body.
**Expected result**
Error message "Bad email or password" is in Response body.
User story: #471
Test case: https://jira.softserve.academy/browse/GC-493
![Screenshot 2020-05-06 at 16 37 46](https://user-images.githubusercontent.com/64583442/81228575-f6966680-8ff6-11ea-85ee-5ba0938d370b.png)

**Comment by zendermean** [comment]
Fixed.
https://github.com/ita-social-projects/GreenCity/pull/664
