### ISSUE TITLE
[API] In GET /user - Get User dto by principal (email) from access token response 200 OK - need 403 Forbidden

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6481]
**Environment:** Firefox 116.0.3 (64-bit).
**Reproducible:** always.

**Preconditions**
Moved to Swagger https://greencity-user.greencity.social/swagger-ui.html
Sign in us User.

**Steps to reproduce**
1. Click on User controller.
2. Click on GET /user.
3. Click on 'Try out'.

**Actual result**
Response 200 OK

**Expected result**
Response 403 Forbidden 

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by 111natalies** [comment]
[API] In GET /user - Getting the User dto by principal (email) from the access token results in a 401 response, but a 403 Forbidden response is needed.

**Comment by holotsvan** [comment]
couldn't reproduce
