### ISSUE TITLE
[API] In POST /user Save User response 500 Undocumented - should be 403 Forbidden.

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6484]
**Environment:** Firefox 116.0.3 (64-bit).
**Reproducible:** always.

**Preconditions**
Moved to Swagger https://greencity-user.greencity.social/swagger-ui.html
Sign in us User.

**Steps to reproduce**
1. Click on User controller.
2. Click on POST /user Save User.
3. Click on 'Try out'.
4. Click on 'Execute'.

**Actual result**
Response 500 Undocumented 
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/dcbf7a18-638a-4dbb-a3ef-7c398faa9deb)

**Expected result**
Response 403 Forbidden.

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by SvitlanaRadkevych** [comment]
<html>
<body>

Error: response status is 401
--



</body>
</html>
![github_bug_API](https://github.com/ita-social-projects/GreenCity/assets/165490180/67abac00-c93f-45e7-8796-daa3322c6295)

**Comment by SvitlanaRadkevych** [comment]
Error: response status is 401
![github_bug_API](https://github.com/ita-social-projects/GreenCity/assets/165490180/1355fb63-8398-414e-afa4-fb2086cfb61c)

**Comment by Dima-Vas** [comment]
POST /user endpoint not used in current version of API

**Comment by holotsvan** [comment]
Endpoint was deleted
