### ISSUE TITLE
Event was joined notification

### ISSUE THREAD

**Issue by hbenesh** [ita-social-projects/GreenCity#6497]
**As a** user **I want to** be notified **so that** I can see people joining my events sooner

**Preconditions**
1. User created an event and another user joined it.

### Acceptance Criteria

-  When any user joins the user's event, the user must get a new notification about it
A notification counter value is increased by one

- User should see a corresponding notification record when he views the most recent notifications popup or All notifications page:

     - [Username] joined your event [Event name]. [Date and Time]
       (ex. "Maria joined your event Eco Day. Today 10:00 a.m")
     - [Username] - user who joined an event
     - If more than one user joined by the moment the user sees this notification, then the usernames of 2 last users and "other users" should be instead (ex, "Maria, Olha and other users joined your event Eco Day. Today 10:00 a.m")
     - [Event name] - name of the event. Should be a link, should be cut if too long (?)
     - [Date and time] - Date and time when the event  was joined.

     Date format is DD.MM.YYYY
     Time format is HH:MM XM
     If the day = Today, then use "Today" word instead of calendar date
     If the day = Today - 1, then use "Yesterday" word instead of calendar date

**Epic link**
E.g.: Epic https://github.com/ita-social-projects/GreenCity/issues/6332

**Labels to be added**
"User story"

**Comment by IliaWithHat** [comment]
Already done in EventServiceImpl 449 line.
