### ISSUE TITLE
[Event Description] The 'Delete' button doesn't appear for active online event

### ISSUE THREAD

**Issue by Bezrodna1988** [ita-social-projects/GreenCity#6500]
**Environment:** Windows 10x64, Google Chrome 116.0.5845.189
**Reproducible:** always
**Build found:** 04.10.2023

**Preconditions**
1.https://www.greencity.social/#/profile is opened.
2. User (admin or event organizer) is logged in.
3.User has at least one online active (current or future) event.
4.The Event page is opened.

**Steps to reproduce**
1. Click the 'More' button on the online active Event card (see preconditions) at the Event dashboard.

**Actual result**
The 'Delete' button doesn't appear for the active online event at the Event Description page
![_thumb_418307](https://github.com/ita-social-projects/GreenCity/assets/139672725/4a1b0ed8-f7d4-471a-a8aa-7b689634c803)

**Expected result**
The 'Delete' button is located in the right top corner. 
![_thumb_418306](https://github.com/ita-social-projects/GreenCity/assets/139672725/0d4cc8b0-ab4e-4fc1-bfb0-dc6e97ba009e)

**User story and test case links**
E.g.: "User story #3196 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI")

**Comment by sobkiv** [comment]
which login do you use?

**Comment by Bezrodna1988** [comment]
Bug was reproduced for the event organizer and admin roles.
