### ISSUE TITLE
[API] In GET /user/{userId}/profileStatistics/ response 200 OK- need 403 Forbidden.

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6509]
**Environment:** Firefox 116.0.3 (64-bit).
**Reproducible:** always.

**Preconditions**
Moved to Swagger https://greencity-user.greencity.social/swagger-ui.html#/
Sign-in us Admin.

**Steps to reproduce**
1. Click on User controller.
2. GET /user/{userId}/profileStatistics/.
3. Enter valid data.
4. Click on 'Try out'.

**Actual result**
Response 200 OK.
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/f9f459e8-91f2-40a5-864a-cdf303ae3609)

**Expected result**
Response 403 Forbidden.

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by lukovskyj** [comment]
Users with ADMIN role should have permission to access this endpoint
