### ISSUE TITLE
[API] In PUT /user/deactivate response 403 Forbidden - need 404 Undocumented.

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6512]
**Environment:** Firefox 116.0.3 (64-bit).
**Reproducible:** always.

**Preconditions**
Moved to Swagger https://greencity-user.greencity.social/swagger-ui.html#/
Sign-in us Admin.

**Steps to reproduce**
1. Click on User controller.
2. Click on PUT /user/deactivate.
3. Enter invalid data.
4. Click on 'Try out'.

**Actual result**
Response 403 Forbidden.
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/f5e17151-64cf-43b0-8433-00336b47770f)

**Expected result**
Response 404 undocumented.
Add to Swagger documentation this response.

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by lukovskyj** [comment]
Bug was fixed. The endpoint now correctly returns the following status codes:
    200 OK
    400 Bad Request
    401 Unauthorized
    403 Forbidden
    404 Not Found

The Swagger documentation has been updated to reflect these status codes.
