### ISSUE TITLE
[Create Event] All previous settings are not saved after selecting "back to editing" in the event preview window 

### ISSUE THREAD

**Issue by Oleksandra-Kobets** [ita-social-projects/GreenCity#6518]
**Environment:** Google Chrome  117.0.5938.150 64 bit, Windows 11 home 22H2 build 22621.2283 
**Reproducible:** always 
**Build found:** 05.10.23

**Preconditions**
Website https://www.greencity.social/#/greenCity is opened in browser 
User is logged in 

**Steps to reproduce**
1. Go to 'Events'
2. Click on 'Create Event' button 
3. Enter name for an Event 
4. Enter any text in "Description" field 
5. Click on "Preview"  button 
6. Select "Back to editing" from the top left 

**Actual result**
Name of event and text in description were lost. All fields are empty 

**Expected result**
User can see previous typed name of event and text in description 

**User story and test case links**
E.g.: User story #3193 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Oleksandra-Kobets** [comment]
Needs to fix 

1. After click on "back to editing" incorrect name of address appears; 
2. User is not able to publish event after viewing the preview window; 

Please look at the attached video


https://github.com/ita-social-projects/GreenCity/assets/140553661/ee545718-0fcb-4e49-a768-8e4e68d73419

**Comment by sobkiv** [comment]
Cannot reproduce yet
