### ISSUE TITLE
[API] Incorrect params order in  /ownSecurity/changePassword controller

### ISSUE THREAD

**Issue by OlesiaSolovii** [ita-social-projects/GreenCity#652]
Steps to reproduce: 
1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#/
2. Click on 'own-security-controller' 
3. Click on '/ownSecurity/changePassword'
**Actual result:**
{
  "confirmPassword": "string",
  "password": "string",
  "token": "string"
}
**Expected result:**
{
  "password": "string",
  "confirmPassword": "string",
  "token": "string"
}

User story #465 
Test case: https://jira.softserve.academy/browse/GC-548

**Comment by zendermean** [comment]
Features of the swagger
