### ISSUE TITLE
[Order] Super Admin  can not scroll list of  orders on orders page

### ISSUE THREAD

**Issue by Priadkohrystyna** [ita-social-projects/GreenCity#6532]
Windows 11 Home
Microsoft Edge Version 115.0.1901.188 (Official) (64-bit)
Build found: 08.10.2023
Preconditions

- User is logged in https://www.greencity.social/#/ubs as Super Admin

Steps to reproduce

1. Go to https://www.greencity.social/#/ubs-admin/orders
2. Scroll down to see all orders with help of touchpad 

Actual result:
User can not  scroll down to  see orders that are on other pages 

Expected result
User can  scroll down to  see orders that are on other pages 

Attachments:
[Video_2023_10_08-1.webm](https://github.com/ita-social-projects/GreenCity/assets/106020174/7c99d53c-bd74-434e-9c8b-bf12df09b375)

**Comment by RomanVintoniak** [comment]
Can not reproduce
