### ISSUE TITLE
[Sign Up] User can sign up with different values in 'Password' and 'Confirm password' fields

### ISSUE THREAD

**Issue by Sergio2209** [ita-social-projects/GreenCity#654]
**Environment:** Windows 7 Maximum, Google Chrome 81.0.4044.129
**Reproducible:** always
**Build found:** commit 7439e88

**Steps to reproduce:**

1. Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on Sign-up button
3. Set correct value in 'First name' field
4. Set correct value in 'Email' field  
5. Set correct value in the 'Password' field
6. Set incorrect value in the 'Confirm Password' field
7. Click 'Sing-up' button

**Actual result:** 
User can sign up with different values in 'Password' and 'Confirm password' fields. Message "You have successfully registered on the site. Please confirm your email address in the email box" is displayed. Email to confrim registration has been sent

![Screenshot_13](https://user-images.githubusercontent.com/64583079/81344082-ca461d00-90be-11ea-9b5e-c160e5900b89.png)

**Expected result:**
User can not sign up with different values in 'Password' and 'Confirm password' fields. An apropriate error messages   are displayed:
"Passwords do not match", 
"Password has contain at least one character of Uppercase letter (A-Z), 
Lowercase letter (a-z), Digit (0-9), Special character (~`!@#$%^&*()+=_-{}" 

User story: #455

**Comment by RomanDeveloperAcc** [comment]
Fixed
