### ISSUE TITLE
[Habits] When user tries to edit habit the current image disappears on the edit stage. There are lots of errors in the console.log

### ISSUE THREAD

**Issue by sobkiv** [ita-social-projects/GreenCity#6547]
**Environment:**
OS: Windows 11 Pro, version 22H2
Browsers: Opera (99.0.4788.65), Mozilla Firefox (114.0.1 64-bit), Chrome (114.0.5735.134 64-bit)
Reproducible: always
Build found: 09.10.2023

**Pre-conditions**

The registered user is logged in.
Page "My space" is open.

**Steps to Reproduce**

Click "More" button
Click "Edit habit" button

**Actual result**
User doesn't see the image of the habit and must choose it again

**Expected result**
User should see the image of the habit that was set when the habit was created

https://github.com/ita-social-projects/GreenCity/assets/112779214/18d48120-ab3e-4c5e-b276-89be49ab8847

![Screenshot_2023_10_11-1](https://github.com/ita-social-projects/GreenCity/assets/112779214/c51d6c37-c896-403f-a19f-138f43b9dbe9)

**User story and test case links E.g.:** 
https://github.com/ita-social-projects/GreenCity/issues/938

**Comment by AnnaMalibu** [comment]
Users cannot upload images and choose from the default images

**Comment by sobkiv** [comment]
Maybe it is not a perfect approach, but it works. Let's look at a mockup design or do you have any idea?
https://github.com/ita-social-projects/GreenCity/assets/112779214/10179853-6db8-4d03-8729-aac5f01532b6
