### ISSUE TITLE
[Habit] Very slowly scrolling if User used display 1360x720.

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6555]
**Environment:** Chrome 117.0.5938.150 (Official) 64bit.
**Reproducible:** always.

**Preconditions**
Sign-in as User.
Moved to "My Space".

**Steps to reproduce**
1. Click on 'Add New Habit'.
3. Scroll down.

**Actual result**
Very slowly scrolling down.

**Expected result**
Scrolling should be faster.

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**User story and test case links**
E.g.: "User story #1785

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by dmytro-kryvyi** [comment]
Bug reproduces  only in Google Chrome devtools. After i changed smoot scrolling param on chrome://flags to disabled, restarted launcher and then changed to enabled bug didn't occur anymore in devtools. On laptop with screen 1360*768 it does'nt appear.

**Comment by CactusNP21** [comment]
not replicate
