### ISSUE TITLE
[Habit] Incorect displayed "Back to my Habits" in "Habit Page".

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6556]
**Environment:** Chrome 117.0.5938.150 (Official) 64bit.
**Reproducible:** always.

**Preconditions**
Sign-in as User.
Moved to "My Space".

**Steps to reproduce**
1. Click on 'Add New Habit'.
2. Choose any one habit.
3. Click on 'More'.

**Actual result**
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/d0f9ce35-ab8b-44e8-b569-c958645c8e19)

**Expected result**
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/c1613d7b-4d6e-4d16-a6e9-732739f3952e)

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Yavorovskayuliia** [comment]
the error not fixed, Incorect displayed "Back to my Habits" in "Habit Page".

**Comment by sobkiv** [comment]
Can you provide more specifics, please? Maybe "Back to my Habits" should be green as before. I am not sure

**Comment by Phobos13bdrive** [comment]
Not actual.
