### ISSUE TITLE
[My habits] Done items are disappeared from “My To-do list” after refreshing a page

### ISSUE THREAD

**Issue by Oleksandra-Kobets** [ita-social-projects/GreenCity#6564]
**Environment:** Microsoft Edge 117.0.2045.60 64 bit, Windows 11 home 22H2 build 22621.2283 
**Reproducible:** always 
**Build found:** 13.10.23

**Preconditions**
Website https://www.greencity.social/#/greenCity is opened in browser 
User is logged in as admin 

**Steps to reproduce**

1. Go to 'My space' page 
2. Click on “Add new habit” button 
3. Select any habit from the list “All habits”  and click on “add habit” button 
4. Click on “Edit habit” button 
5. Add few new custom items in “To-do list” 
6. Click on circle “Plus” button opposite to the items 
7. Click on “Save changes” button 
8. Checked off the checklist items in “To-do list” on “My space” page 
9. Refresh the browser page (for example, press F5) 

**Actual result**
Done items in “To-do list”  are disappeared 

**Expected result**
All done items are visible in “To-do list” 

**Attachments** 

https://github.com/ita-social-projects/GreenCity/assets/140553661/65d0d51c-536c-43f3-9d91-928e031e397b

**User story and test case links**
E.g.: User story #988

**Comment by ViktoriyaRyazhska** [comment]
not relevant
