### ISSUE TITLE
[API] There is no response code when leave 'Email' field empty

### ISSUE THREAD

**Issue by OlesiaSolovii** [ita-social-projects/GreenCity#657]
**Steps to reproduce:**

1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#/
2. Click on 'own-security-controller'
3. Click on '/ownSecurity/restorePassword'
4. Click on 'Try it out' button
5. Leave 'Email' field empty
6. Click on 'Execute' button

**Actual result**
'Email' field is highlighted in red color, there is no response code.

**Expected result**
Code 400
Response body:
{"message": "The user does not exist by this email: "}

User story #465 
Test case: [https://jira.softserve.academy/browse/GC-546]

**Comment by zendermean** [comment]
This is feature of Swagger.
Try using Postman.
