### ISSUE TITLE
[Create Event] User is not able to fill in the address in Ukrainian language if browser language is English 

### ISSUE THREAD

**Issue by Oleksandra-Kobets** [ita-social-projects/GreenCity#6573]
**Environment:** Chrome 118.0.5993.71, 64 bit, Windows 11 home 22H2 build 22621.2428
**Reproducible:** always 
**Build found:** 17.10.23

**Preconditions**

- The English  language is used to display the browser (for example Google Chrome UI)
- Website https://www.greencity.social/#/greenCity is opened in browser 
- The language of greencity website is UA 
- User is logged in 

**Steps to reproduce**

1. Go to 'Events' page 
2. Click on 'Create Event' button
3. Click on the checkbox "місце"
4. Enter any address in the location field in Ukrainian language. For example: “вулиця Городоцька” 

**Actual result**
The address is displayed in English language in the location field 

**Expected result**
The address is displayed in Ukrainian language in the location field 

**Attachments** 
Actual result 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/4920980c-4687-4e44-9f21-39a181ac59eb)

Expected result 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/41bb58aa-5170-47bd-9ff2-ea8aa25c1ece)

Description: 
Exactly the same situation in reverse. If the browser language is Ukrainian, all locations are displayed in Ukrainian, regardless of the greencity website localization

**User story and test case links**
E.g.:  User story #3193

**Comment by yulianagoncharenko** [comment]
The problem persists: street name is displayed in selected language (eg Ukrainian) but city name and oblast  is displayed in English
if the user selects 'Apply to all days of the event' checkbox then for Day 1 the address is shown partially in Ukrainian, partially in English, but for the second day it is displayed in English only.
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/254cf68c-a693-4d0e-b008-929abaa272a9)
