### ISSUE TITLE
Habit was commented notification

### ISSUE THREAD

**Issue by hbenesh** [ita-social-projects/GreenCity#6574]
**As a** user **I want to** be notified when my habits are commented **so that** I can reply to a comment sooner

**Preconditions**
1. User 1 adds  a habit and User 2 leaves a comment for the added habit

### Acceptance Criteria

- When a new comment is left under the user's new habit, the user must get a new notification about it
- A notification counter value is increased by one
- User should see a corresponding notification record when he views the most recent notifications popup or All notifications page:
       - [Username] commented on your habbit [Habit name]. [Date and Time]
         (ex. "Maria commented on your habit Do not use disposable packages. Today 10:00 a.m")
       - [Username] - user who left a message
       - If more than one user left a comment by the moment the user sees this notification, then the usernames of 2 last 
       commentators and "other users" should be instead (ex, "Maria, Olha and other users commented on your habit Do not 
       use disposable packages. Today 10:00 a.m")
      - If the same user left more than one comment on the same habit by the moment the user sees this notification, then user 
         should see only the latest one in the notification record
      - [Habit name] - name of the event. Should be a link, should be cut if too long (?)
      - [Date and time] - Date and time when the comment was left.
         Date format is DD.MM.YYYY
        Time format is HH:MM XM
        If the day = Today, then use "Today" word instead of calendar date
        If the day = Today - 1, then use "Yesterday" word instead of calendar date

**Epic link**
E.g.: Epic #6332

**Labels to be added**
"User story"

**Comment by tellmant** [comment]
At the moment, there is no functionality for commenting on habits.

**Comment by K4sik** [comment]
Back-end - DONE
