### ISSUE TITLE
My cabinet tab: rename to My habbits

### ISSUE THREAD

**Issue by Elina-Lapka** [ita-social-projects/GreenCity#658]
As a User I want to have My cabinet tab renamed to My habits, so that I know that I can form useful habits there. 
Mock-up:
<img width="483" alt="Screenshot_19" src="https://user-images.githubusercontent.com/60645819/81389982-60ac2a00-9123-11ea-909b-245fc0d9cfcf.png">

Acceptance criteria:
1. My cabinet tab is renamed to:
ENG - My habbits
RUS - Мои привычки
UKR - Мої звички

**Comment by rsyvulko** [comment]
Not relevant.
