### ISSUE TITLE
[News] The last reply in the ‘View [number] replies’ list isn't disappeared after deleting

### ISSUE THREAD

**Issue by VlasenkoYuliia** [ita-social-projects/GreenCity#6583]
Environment:
macOS Sonoma Version 14.0
Google Chrome
Version 118.0.5993.70 (Official Build) (arm64)

Reproducible: 
**The bug is reproducible just for the last reply in the ‘View [number] replies’ list.**

Build found:
19.10.23

Preconditions
At least a News is added;
A News includes a User's comment;
The replies are added to the comment.

Steps to reproduce

1. Open the site https://www.greencity.social/#/greenCity;
2. Logged-in as User;
3. Click on the 'Eco news' tab;
4. Click on the News that includes a comment;
5. Click on the ‘View [number] replies’ list for the comment;
8. Click on the 'Delete' icon under User's reply;
9. Click on 'Yes, delete' button;

**Actual result**
The reply is still present in the ‘View [number] replies’ list until the page is refreshed.

https://github.com/ita-social-projects/GreenCity/assets/138223368/8afa67b5-b43e-431b-99f4-a5b969dc819f

**Expected result**
The reply is deleted from the ‘View [number] replies’ list and from the total number of replies.

**Postconditions**

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/GC-3817)"

**Labels to be added**
"Bug", Priority ("high"), Severity ("minor"), Type ("Functional").

**Comment by igorv404** [comment]
Can not reproduce

**Comment by VlasenkoYuliia** [comment]
You need to have one reply in the ‘View [number] replies’ 
The reply is still present in the ‘View [number] replies’ list until the page is refreshed.

https://github.com/ita-social-projects/GreenCity/assets/138223368/579a663d-84dd-4a88-a414-4fe28f61941a

**Comment by igorv404** [comment]
Okey, I will fix it
