### ISSUE TITLE
[DELETE/Events delete] There is error 500 instead of 403 FORBIDDEN when Organizer deletes non-existent Event

### ISSUE THREAD

**Issue by IrynaFedun** [ita-social-projects/GreenCity#6590]
Environment:Windows 10x64, Google Chrome 116.0.5845.189
Reproducible: always
Build found: 25.10.2023

Preconditions
User is logged in

Steps to reproduce

1. Send DEL https://greencity.greencity.social/events/delete/464

Actual result
![EventDeleteAdmin464 неіснуюча](https://github.com/ita-social-projects/GreenCity/assets/142750671/6298345a-5741-4c6e-9cc6-b664274e7b96)

There is error 500

Expected result
There is error 403

User story #3196

Labels to be added
"Bug", Priority ("pri: "), Severity ("severity:"), "API" (for back-end bugs), events-controller

**Comment by ABbondar** [comment]
retest, please

**Comment by IrynaFedun** [comment]
It's OK, I retested and closed this as completed
