### ISSUE TITLE
[API] [POST/email controller/send User Violation]Response status is 500 instead 400 when language parameter is empty

### ISSUE THREAD

**Issue by Bezrodna1988** [ita-social-projects/GreenCity#6594]
**Environment:** Windows 10, Postman
**Reproducible:** always
**Build found:**21.10.2023

**Preconditions**
The admin is logged in, and the token is gotten.

**Steps to reproduce**
1.Go to the https://greencity-user.greencity.social/swagger-ui.html#/email-controller/sendUserViolationUsingPOST
2.Send the request POST https://greencity-user.greencity.social/email/sendUserViolation. In the body of the request "email": " " (i.e. email is empty). All other parameters are valid.
3. Pay attention to the status code.

**Actual result**
The status code is 500.
<img width="642" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/139672725/dee7d37e-98b3-4b8b-9367-388d80f409d6">

**Expected result** 
The status code is 400.
**User story and test case links**
E.g.: "User story #2567 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), "API" (for back-end bugs).

**Comment by Bezrodna1988** [comment]
The bug is reproduced again. It was fixed?

**Comment by VinuVicho** [comment]
> The bug is reproduced again. It was fixed?

Yes
