### ISSUE TITLE
[API] [DELETE/Events delete] There is error 500 instead of 200 OK when ADMIN deletes past event

### ISSUE THREAD

**Issue by IrynaFedun** [ita-social-projects/GreenCity#6598]
Environment: Windows 10, Postman
Reproducible: always
Build found: 21.10.2023

Preconditions:
The admin is logged in
The token is gotten
Open Postman

Steps to reproduce

   1. Send the request DELETE https://greencity.greencity.social/events/delete/425
    425 is past event ID

Actual result
The status code is 500.
![EventDelete425 існуюча](https://github.com/ita-social-projects/GreenCity/assets/142750671/14400560-73a0-4285-bec3-e7b36fafc40e)

Expected result
The status code is 200.

User story and test case links
E.g.: "User story #3196

Labels to be added
"Bug", Priority ("pri: "), Severity ("severity:"), "API" (for back-end bugs) "Events controller"

**Comment by ABbondar** [comment]
Can not reproduce, retest please. The past events are successfully deleted.

**Comment by IrynaFedun** [comment]
> Can not reproduce, retest please. The past events are successfully deleted.

The following events are not deleted: 33, 40, 127, 128, 129, 193, 425, 438, 448, 449

**Comment by IrynaFedun** [comment]
The following events are not deleted: ID33, 40, 127, 128, 129, 193, 425, 438, 448, 449
