### ISSUE TITLE
[UBS Order page] User cannot input data on 'Entrance' field

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6599]
**Environment:** Firefox 118.0.2 (64-bit).
**Reproducible:** always.

**Preconditions**
Moved to https://www.greencity.social/#/ubs-admin/
Sign-in as Admin.

**Steps to reproduce**
1. Go to 'Orders' page.
2. Click on anyone order.
3. Moved to 'Waste export address'.
4. Enter '0' to 'Entrance' field.

**Actual result**
User have error message - Only numbers are allowed.
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/0fbcace8-d142-4eae-a990-aab62b2dd58b)

**Expected result**
User can enter - '0'.

**User story and test case links**
E.g.: "User story  #2199
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by NadiiaStoiko** [comment]
It's not a bug, number of Entrance can be from 1 to 99(max 2 numeric characters) and can't be 0
