### ISSUE TITLE
[UI/News] the Width of 'Reply' button doesn't match the Width of 'Reply' text box

### ISSUE THREAD

**Issue by VlasenkoYuliia** [ita-social-projects/GreenCity#6624]
Environment:
macOS Sonoma Version 14.0
Google Chrome
Version 118.0.5993.70 (Official Build) (arm64).

Reproducible: always.
Build found:
26.10.23

Preconditions
At least a News is added;
A News includes a User's comment;
Display Resolution Sizes 320 is chosen.

Steps to reproduce
1. Open the site https://www.greencity.social/#/greenCity;
2. Logged-in as User;
3. Click on the 'Eco news' tab;
4. Click on the News that includes a comment;
5. Compare Comment's controls with the mock-up

**Actual result**
Size ‘Comment’ button 284x48;
Size ‘Comment’ text box 284x72.
Size ‘Reply’ button 129x48;
Size ‘Reply’ text box 214x72.
<img width="240" alt="Screenshot 2023-10-26 at 11 32 21" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/234fc0a4-e080-4246-88d7-30edcda3a407">

**Expected result**
Size ‘Comment’ button 288x48;
Size ‘Comment’ text box 288x72.
Size ‘Reply’ button 256x48;
Size ‘Reply’ text box 256x72.
<img width="323" alt="Screenshot 2023-10-26 at 11 31 30" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/93acf15c-8a81-45f3-b94a-ecb8f6840a52">

Postconditions

User story and test case links
E.g.: mock-up
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=35760-150581&mode=design&t=fB6aCbsRzLPaxi4s-0
"

Labels to be added
"Bug", Priority ("medium "), Severity ("trivial"), Type ("UI").

**Comment by nuttaa0** [comment]
Wrong distance between input field and 'Reply' button.
![Image](https://github.com/user-attachments/assets/1b69a701-ac69-40c8-880b-44fa0cebd49f)


Should be according to [Mockup](https://www.figma.com/design/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=12649-1279&t=Oooi4A7CdzXCfYT1-1)

**Comment by kryzanivska-nastya** [comment]
![Image](https://github.com/user-attachments/assets/6ad8b561-0359-4809-a482-74a1242a26fd)
Now, there is 'image' button.
