### ISSUE TITLE
[UI/News] Comment's controls for Display Resolution Sizes less than 575 don't match the mock-up

### ISSUE THREAD

**Issue by VlasenkoYuliia** [ita-social-projects/GreenCity#6626]
Environment:
macOS Sonoma Version 14.0
Google Chrome
Version 118.0.5993.70 (Official Build) (arm64).

Reproducible: always.
Build found:
26.10.23

Preconditions
At least a News is added;
A News includes a User's comment;
Display Resolution Sizes **575** is chosen.

Steps to reproduce

1. Open the site https://www.greencity.social/#/greenCity;
2. Logged-in as User;
3. Click on the 'Eco news' tab;
4. Click on the News that includes a comment;
5. Compare Comment's controls with the mock-up

**Actual result**
<img width="483" alt="Screenshot 2023-10-26 at 14 45 52" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/10135e65-251e-4fac-af79-a0f24413473b">
<img width="302" alt="Screenshot 2023-10-26 at 15 03 53" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/9503fbe8-32e5-4cd1-ab0b-9bffba9c2acc">

For Display Resolution Size less than 576:
1. ‘Comment’ and ‘Reply’ buttons  are after the text boxes;
2. The User’s Avatar is before the User’s Name;
3. The word “View” is omitted from the ‘View [number] replies’ list;
4. The  User’s Avatars for the ‘Comment’ and ‘Reply’ text boxes are present.
5. Size ‘Comment’ button 312x48;
    Size ‘Comment’ text box 129x72.
    Size ‘Reply’ button 269,93x48;
    Size ‘Reply’ text box 103,07x72.
6.  The distance is absent between the Footer “Follow us” and the footer-top-box;
7.   Icon size of social media is 15x12.19

**Expected result**
<img width="347" alt="Screenshot 2023-10-26 at 14 28 39" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/54c39eee-f2d2-4802-9ab9-1c364ae6fdfb"><img width="261" alt="Screenshot 2023-10-26 at 09 49 33" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/32fd75dc-7c99-49c2-9817-20f91d008df9"><img width="473" alt="Screenshot 2023-10-26 at 13 03 02" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/16673bb3-fe10-4610-b1be-12f657f0d687">
For Display Resolution Size less than 576

1. ‘Comment’ and ‘Reply’ buttons are below the text boxes;
2. The User’s Avatar is above the User’s Name.
3.  The  User’s Avatars for the ‘Comment’ and ‘Reply’ text boxes are absent.
4. Size ‘Comment’ button 543x48;
    Size ‘Comment’ text box 543x72.
    Size ‘Reply’ button 511x48;
    Size ‘Reply’ text box 511x72.
5. The distance is 60 between the Footer “Follow us” and the footer-top-box;
6.  Icon size of social media is 16x16
**Postconditions**

**User story and test case links**
E.g.: mock-up
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=30606-115496&mode=design&t=R1nDYzwx1bBHoGKF-0

**Labels to be added**
"Bug", Priority ("High"), Severity ("minor"), Type ("UI").

**Comment by VlasenkoYuliia** [comment]
The User’s Avatar is above the User’s Name.
<img width="504" alt="Screenshot 2023-11-06 at 16 22 38" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/97616379-33f4-48c2-a1f2-63c0d44a1aa3">
Size ‘Comment’ button 543x48;
Size ‘Comment’ text box 543x72.
Size ‘Reply’ button 511x48;
Size ‘Reply’ text box 511x72.

**Comment by ShyraiDan** [comment]
Due to in the whole project we have got paddings and margins on the side equaled 18px not 16px like in mockup in containers size of the ‘Comment’ text box will be 539x72 and size of the ‘Comment’ button will be 539x48
