### ISSUE TITLE
[UI/News] Comment's controls for Display Resolution Sizes 576 don't match the mock-up

### ISSUE THREAD

**Issue by VlasenkoYuliia** [ita-social-projects/GreenCity#6631]
Environment:
macOS Sonoma Version 14.0
Google Chrome
Version 118.0.5993.70 (Official Build) (arm64).

Reproducible: always.
Build found:
27.10.23

Preconditions
At least a News is added;
A News includes a User's comment;
Display Resolution Sizes **576** is chosen.

Steps to reproduce

1. Open the site https://www.greencity.social/#/greenCity;
2. Logged-in as User;
3. Click on the 'Eco news' tab;
4. Click on the News that includes a comment;
5. Compare Comment's controls with the mock-up

**Actual result**
Comment’ and ‘Reply’ buttons are after the text boxes;
Comment’ and ‘Reply’ controls aren't aligned;
Size ‘Comment’ button 129x48;
Size ‘Comment’ text box 315x72.
Size ‘Reply’ button 103.13x48;
Size ‘Reply’ text box 270.88x72.
<img width="498" alt="Screenshot 2023-10-27 at 09 06 54" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/f50f67d5-18fb-4f79-807d-a7e6ae555d78">

**Expected result**
Comment’ and ‘Reply’ buttons are below the text boxes;
Comment’ and ‘Reply’ controls are aligned;
Size ‘Comment’ button 157x48;
Size ‘Comment’ text box 476x72.
Size ‘Reply’ button 123x48;
Size ‘Reply’ text box 404x72.
<img width="637" alt="Screenshot 2023-10-27 at 09 07 04" src="https://github.com/ita-social-projects/GreenCity/assets/138223368/f60066e7-4775-41fb-9fa5-cd076a4501e1">

**Postconditions**

**User story and test case links**
E.g.: mock-up
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=12649-1279&mode=design&t=sAgZAao7wX1bfggx-0

**Labels to be added**
"Bug", Priority ("high"), Severity ("trivial"), Type ("UI).

**Comment by VlasenkoYuliia** [comment]
Size ‘Comment’ text box 476x72.
Size ‘Reply’ button 123x48;
Size ‘Reply’ text box 404x72.

**Comment by ShyraiDan** [comment]
Due to in the whole project we have got paddings and margins on the side equaled 18px not 16px like in mockup in containers   size of the ‘Comment’ text box will be 468x72

**Comment by zahar777** [comment]
<img width="529" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/70384616/ddc57165-a66e-4ae7-8196-e77f3883f8be">

Size ‘Comment’ text box should be 476x72.

**Comment by zahar777** [comment]
> <img alt="image" width="529" src="https://private-user-images.githubusercontent.com/70384616/290153673-ddc57165-a66e-4ae7-8196-e77f3883f8be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjI4MzksIm5iZiI6MTcwMjQ2MjUzOSwicGF0aCI6Ii83MDM4NDYxNi8yOTAxNTM2NzMtZGRjNTcxNjUtYTY2ZS00YWU3LTgxOTYtZTc3ZjM4ODNmOGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEwMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNTY0NGM0YmMzZmZkYTM3MjRhNDM2ZDE3ODJiNzQzNjk0NThjYTRhMDRkMDlhYzczYTc5ODgzZWZkMjdlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wBH6mXIdpx7nlbQNCi-ma5iqaosTBhvn4SG0u4zIAQs">
> Size


 ‘Comment’ text box should be 476x72.

**Comment by VlasenkoYuliia** [comment]
The size of ‘Comment’ text box 468x72 are acceptable.
