### ISSUE TITLE
[API] [Swagger/events controller/Get all events] Response status is 500 instead of 400 when an invalid parameter is entered in the values.

### ISSUE THREAD

**Issue by dklakovych** [ita-social-projects/GreenCity#6634]
**Environment:** macOs 13.0.1 ; Safari 16.1, Postman
**Reproducible:** always
**Build found:** 25.10.2023

**Preconditions**
Postman is opened. The user is logged in https://www.greencity.cx.ua/#/events , and the actual token is entered.

**Steps to reproduce**
1. Send the request GET with URL: https://www.greencity.cx.ua/#/events . In Query Params set 2 keys: page and size. Add invalid Values to these keys, so that total amount of elements is bigger than actual. (e.g. We have 286 total elements, 58 pages. Add page: 189, size: 5)
3. Pay attention to the status code.

**Actual result**
The status code is 500 Internal Server Error.
<img width="1017" alt="Знімок екрана 2023-10-25 о 19 15 12" src="https://github.com/ita-social-projects/GreenCity/assets/128260857/f45c7802-ca6e-47b9-987d-7ea035a69aab">

**Expected result**
The status code is 400 (Bad request). 

**Labels to be added**
"Bug", "API", "Events", "back-end", "GET".

**Comment by ABbondar** [comment]
retest please

**Comment by Viktoriia0106** [comment]
The specified page does not exist, if we put invalid data, but the error message: "fromIndex(945) > toIndex(662)" in response is not understandable.

![image](https://github.com/ita-social-projects/GreenCity/assets/109147739/988ae27c-6785-4f93-a0e2-e5bc07282c55)

**Comment by YarkaRyvak** [comment]
Response status is 200 instead of 400.
![bug for git hub](https://github.com/ita-social-projects/GreenCity/assets/72704813/6dcb97ce-e4e3-414b-b36c-c0affae92c3a)

**Comment by HelenSotnik** [comment]
As far as number of events in database is equal to 1734 elements by 11.06.2024 and you are trying to get page 189 with 5 elements(which exists as 189 x 5= 945, it is less than total amount of events). So 200 status is correct here.

Even when the limit of events is exceeded by request page and size parameters, we have 200 status code any way, as we do not return events simply. In our case we return PageableAdvancedDto<EventPreviewDto> that have following structure:page,  totalElements, currentPage, totalPages, number, hasPrevious, hasNext, first, last; So this result will be returned anyway if url request is correctly formed by client.

<img width="1470" alt="Screenshot 2024-06-11 at 14 48 31" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/70ad4cc3-0cfa-4c4d-964a-e135b344cc5e">
<img width="1470" alt="Screenshot 2024-06-11 at 14 19 40" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/d57df061-77d5-4db5-8109-15e716e02523">
