### ISSUE TITLE
[Edit Profile] Users are not able to add any social network link to their profiles 

### ISSUE THREAD

**Issue by Oleksandra-Kobets** [ita-social-projects/GreenCity#6645]
**Environment:** Chrome 118.0.5993.118, Windows 11 22H2 build 22621.2428 
**Reproducible:** always 
**Build found:** 31.10.23

**Preconditions**
Website https://www.greencity.social/#/greenCity is opened in browser 
User is logged in 

**Steps to reproduce**
1. Go to 'My space' page 
2. Click on 'Edit Profile' button 
3. Scroll down to 'Linked social networks' section 
4. Click on 'Add social network' button 
5. Enter any link  e.g."https://www.instagram.com/patron_dsns/" 
6. Click on 'Add' button 
7. Click on 'Save' button 

**Actual result**
The user remains on the "edit profile" page. The "save" button does not work. The link to the social network was not added to the profile. 

**Expected result**
"My space page" has opened. The user sees the added link in the profile information. 

**User story and test case links**
E.g.: "User story #3811 
[Test case GC-4565](https://jira.softserve.academy/browse/GC-4565)

**Comment by dmytro-kryvyi** [comment]
The reason for this bug is the transition from a city to a location with coordinates. After this was implemented everything works

**Comment by Oleksandra-Kobets** [comment]
> The reason for this bug is the transition from a city to a location with coordinates. After this was implemented everything works

The bug is still reproducible and the button "save" doesn't work 
Please look at the attached video 

https://github.com/ita-social-projects/GreenCity/assets/140553661/584d9571-b333-4bf3-974e-ec5f9e6bf1e4
