### ISSUE TITLE
[All Habits] All Habits page shows all custom habits created by user's friends. Only custom habits REQUESTED to assign by friends should be shown instead of all.

### ISSUE THREAD

**Issue by HelenSotnik** [ita-social-projects/GreenCity#6666]
**Preconditions**

1. The user is logged in.
2. Goes to My space page and pushes 'Add New Habit' button.
3. 'All habits' page opened [https://www.greencity.social/#/profile] 

**Actual result**
1. All default, custom habit created by user and all created by his friends are represented in 'All habits' page.

**Expected result**
1. All default, custom habit created by user and ONLY requested to assign by friends custom habits should be represented.

**Example attached** 
There are 31 default habits, but now I can see 104 habits, some of them my friends might not want to share with everyone,  instead  I can assign to them.
<img width="1241" alt="Screenshot 2023-11-05 at 11 28 36" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/25f74f46-e5f0-4815-afe8-45a4c2442866">

**Comment by MariiaShtraisel** [comment]
Reopen. Habits double
