### ISSUE TITLE
[All habits] A user doesn't have possibility to delete a created and not-assigned by anyone habit 

### ISSUE THREAD

**Issue by Oleksandra-Kobets** [ita-social-projects/GreenCity#6683]
**Environment:** 
Chrome 119.0.6045.123, 
Windows 11 home 22H2  build 22621.2428

**Reproducible:** always 
**Build found:**  08.11.2023

**Preconditions**
Website is opened https://www.greencity.social/#/greenCity
User is logged
User created one habit and this habit is not assigned to anyone 

**Steps to reproduce**
1. Go to 'My space' page 
2. Click on 'Add New Habit' button 
3. Scroll down and find a habit created by the user 
4. Click on "More" button 
5. Scroll down and find "Delete" button to click on it 

**Actual result**
A button "Delete" is absent. Instead of it user sees a "Cancel" button. 

**Expected result**
A button "Delete" is displayed. After clicking on it, the habit is removed from the greencity website.

**Attachments** 
The button "Delete" sould be placed here 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/7686a9ad-0792-4b1d-98b8-14b5313c7dc4)

**User story and test case links**
E.g.: User story #1643

**Comment by sobkiv** [comment]
As I know the possibility to delete created habits is not required

**Comment by Oleksandra-Kobets** [comment]
> As I know the possibility to delete created habits is not required

Due to new requirements a user can delete created habit but if this habit wasn't assigned (wasn't added ) by anyone. So I updated the card

**Comment by HelenSotnik** [comment]
From backend side, endpoint to delete custom habit is implemented, required to apply it on all custom habits that user has created.

![Image](https://github.com/user-attachments/assets/11ee5c00-d168-4fa7-9c67-d86adebe9244)
