### ISSUE TITLE
[API] [Friend list] [UserFriendDTO] When User does not have a location in UserFriendDTO all UserLocationDTO fields are set to null

### ISSUE THREAD

**Issue by LiliaMokhnatska** [ita-social-projects/GreenCity#6694]
**Reproducible:** always
**Build found:** 11.11.2023

**Preconditions**
User is logged in, token is got.

**Steps to reproduce**
1. Open [Swagger friend-controller](https://greencity.greencity.social/swagger-ui.html#/friend-controller).
2. Choose [get /friends](https://greencity.greencity.social/swagger-ui.html#/operations/friend-controller/findAllFriendsOfUserUsingGET)
 (Find all friends).
3. Check a response 

**Actual result**
in UserFriendDTO all UserLocationDTO fields are set to null when User does not have a location

**Expected result**
  when User does not have a location just UserLocationDTO is set null

**User story and test case links**
E.g.: "User story #2122 
[Test case](https://jira.softserve.academy/browse/4184)"

**Comment by KizerovDmitriy** [comment]
already fixed

![image](https://github.com/ita-social-projects/GreenCity/assets/113462277/6e53e3b9-1710-41a5-aea4-f243c3d5d394)
