### ISSUE TITLE
[Create habit] A user cannot crop the uploaded picture 

### ISSUE THREAD

**Issue by Oleksandra-Kobets** [ita-social-projects/GreenCity#6703]
**Environment:** Chrome  119.0.6045.125, Windows 11 home 22H2 build 22621.2428 
**Reproducible:** always 
**Build found:** 15.11.23

**Preconditions**
The website https://www.greencity.social/#/greenCity is opened in the browser
User is loged in 

**Steps to reproduce**
1. Go to 'My space', click on "My Habits" tab 
2. Click on 'Add new habit' button
3. Click on 'Create habit' button
4. Fill in all mandatory fields with any data
5. Upload any picture from your computer 
6. Crop image as you like with 'crop borders'
For example, like this: 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/cd65b2da-3b66-4989-bb8d-69c361f4e006)

7. Click on 'Submit' button 
8. Click on "Add habit" button 

**Actual result**
Habit was created and published on the "all habit" page. The image was cropped differently than the user cropped it. 
![image](https://github.com/ita-social-projects/GreenCity/assets/140553661/f28375f7-d46a-409f-a811-7b8c6b3fdbb9)

**Expected result**
Habit was created and published on the "all habit" page. The image was cropped the same way as the user cropped it. 

**User story and test case links**
E.g.: "User story #938

**Comment by Maxv1z** [comment]
already fixed by @Tadei-Mykola
