### ISSUE TITLE
[All Habits] "Add habit" button does not change the name to "Added habit" on an already added habit

### ISSUE THREAD

**Issue by AnnaMalibu** [ita-social-projects/GreenCity#6725]
**Environment:**  Linux Mint
Chrome 118.0.5993.88 (64bit)
**Reproducible:** always
**Build found:** 3/11/2023

**Preconditions**

**Steps to reproduce**
1. Go to https://www.greencity.social/#/greenCity

2. Login with valid credentials

3. Open 'All Habits' page

4. Chose the habit which haven't been added yet and click the 'Add habit' button

5. Use the left (back) arrow of the navigation bar to return to the previous (All Habits) page.

7. Find just an added habit, pay attention to the 'Add habit'  button

**Actual result**
The button's name has not changed from 'Add habit' to 'Added habit'

**Expected result**
The button's name was changed from 'Add habit' to 'Added habit'

**User story and test case links**
E.g.: "User story #6045 
https://jira.softserve.academy/browse/GC-8490?filter=-1"

**Labels to be added** "Bug", 
Priority ("Low "), 
Severity ("Minor"), 
Type ("UI").

![_thumb_418655](https://github.com/ita-social-projects/GreenCity/assets/145026698/2eedcfee-ea67-4db8-966e-7ffa8320f4d7)

**Comment by Priadkohrystyna** [comment]
"Add habit" button still does not change the name to "Added habit" on already added habit
![Uploading Знімок екрана 2023-12-20 132827.png…]()
