### ISSUE TITLE
[Edit Profile] The boolean fields : "showEcoPlace", "showEcoPlace", "showShoppingList" can contain invalid data

### ISSUE THREAD

**Issue by zahar777** [ita-social-projects/GreenCity#6745]
**Reproducible:** always.

**Preconditions**
The user is logged in, and the token is gotten.

The Edit profile page is opened
**Steps to reproduce**
1. Go to 'https://greencity-user.greencity.social/user/profile'
2. Send the request PUT with invalid data as an example where : (showLocation": "",  "showEcoPlace": 1,"  showShoppingList": null) :
 "{
  "coordinates": {
    "latitude": 48.45664825511967,
    "longitude":  34.98029487730522
  },
  "name": "User",
  "showEcoPlace": 1,
  "showLocation": "",
  "showShoppingList": null,
  "socialNetworks": [
    "https://www.instagram.com/mostlycamomile/"

  ],
  "userCredo": "string"
}"

4. Send request
5. Pay attention to the status code.

**Actual result**
The request status is 200, all data were saved
<img width="1161" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/70384616/e9ac2dc4-10b8-4ea9-b37d-98a5bf3f7370">

**Expected result**
Status code 400

**User story and test case links**
E.g.: "User story #1008

**Labels to be added**
"Bug", Priority ("pri:minor "), Severity ("severity:minor")

**Comment by ABbondar** [comment]
"When we pass 0, it is equivalent to false; any other number is equivalent to true. In the case of passing a String, for example, "not valid," we will receive a 400 status code."

**Comment by AnnaMalibu** [comment]
And if we pass "" ? we received 200 OK.
