### ISSUE TITLE
[Profile] The photo from the Google account is not displayed after logging in via Google

### ISSUE THREAD

**Issue by Viktoriia0106** [ita-social-projects/GreenCity#6749]
**Environment:**
Windows 10 x64
Google Chrome 119.0.6045.105

**Reproducible:** always
**Build found:** 10.12.2023_16:25

**Preconditions**
The user is registered on the https://www.greencity.social/#/greenCity website
The user has the Google account
No photo or the current profile's photo should be not as in the Google account

**Steps to reproduce**
1. Log in via Google
2. Pay attention to the profile photo

**Actual result**
The photo from the Google account is not displayed in the profile after logging in via Google

**Expected result**
The photo from the Google account is shown in the user's profile after logging in via Google

**User story and test case links**
E.g.: "User story #1303 
[Test case GC-8642](https://jira.softserve.academy/browse/GC-8642)"

**Labels to be added**
"Bug", Priority ("pri: Medium "), Severity ("severity: Major"), Type ("Functional"), 
![bug_photo_via_google](https://github.com/ita-social-projects/GreenCity/assets/109147739/2c55657b-dcaa-42e7-b89d-78c9ebbbedbe)

https://github.com/ita-social-projects/GreenCity/assets/109147739/82416180-6b98-43b0-89b1-f5d48806b080

**Comment by vladmorozov2** [comment]
Can't reproduce this bug

**Comment by vladmorozov2** [comment]
Missclick but can't reproduce

**Comment by Viktoriia0106** [comment]
https://github.com/ita-social-projects/GreenCity/assets/109147739/0dd1cf57-5055-4e67-9905-44d98317e180

Photo from Google account is not shown as avatar after log in via Google

**Comment by Roman-Loboda** [comment]
not reproduse
