### ISSUE TITLE
[Tech Story 674] Develop Personal information & Personal Activity Analytics block on the Personal Profile Page

### ISSUE THREAD

**Issue by TetiShel** [ita-social-projects/GreenCity#675]
Related to the Tech story #674 

Design the Personal information & Personal Activity Analytics block based on mockup:
![image](https://user-images.githubusercontent.com/64966652/81940317-239ed680-9600-11ea-85fa-f76e2ab10701.png)

**Comment by sofiiamatsyhin** [comment]
Design in this tech story isn't correct
We have correct resolution on a mockup
![Uploading Screen Shot 2020-08-21 at 19.26.57.png…]()
