### ISSUE TITLE
[Habit info][To-do list] Add an error message if user input more than 2048 characters to input field

### ISSUE THREAD

**Issue by zahar777** [ita-social-projects/GreenCity#6759]
**Description of a Change request:**
Add error message if user inputs more than 2048 characters to input field 
**Reason for Change:**
As a user, I want to see what mistake I have made to the input field

**Acceptance Criteria**
If the user input more than 2048 characters to the input field the system displays "The field can contain  maximum 2048 characters"

**Impact of Change**
#6750 

Epic: My habits #938

**Comment by HelenSotnik** [comment]
There is implemented error message in case when To-Do List is bigger that 2048 chars during new habit creation. 
Photo demonstration error is attached below. [
<img width="1470" alt="Screenshot 2024-05-13 at 15 39 28" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/e6592106-7e3b-47da-a5ee-ba080b84845d">
](url)

**Comment by ElenaSH98** [comment]
Повідомлення не приходить при введенні більше 2048 символів .

**Comment by ElenaSH98** [comment]
Повідомлення не приходить при введенні більше 2048 символів .

**Comment by ElenaSH98** [comment]
Повідомлення не приходить при введенні більше 2048 символів .

**Comment by ElenaSH98** [comment]
Повідомлення не приходить при введенні більше 2048 символів.

**Comment by Dima-Vas** [comment]
![Image](https://github.com/user-attachments/assets/89394ae6-4dce-4d5f-a6f2-c04ebe60d36b)
Always receiving the message and unable to press "+" button when providing more than 2048 characters on Windows 11, Chrome 126.0.6478.183

**Comment by Mikusja** [comment]
Works fine. Notification appears.
![Image](https://github.com/user-attachments/assets/c9fd1c03-bbb1-4e93-9a49-7aec3cc9ad44)
