### ISSUE TITLE
[My habits] [Calendar] Pop-up with a list of habits "In Progress" does not appear when clicking on the current or 7 previous days

### ISSUE THREAD

**Issue by NadiiaBedrii** [ita-social-projects/GreenCity#6763]
**Environment:** OS Windows 10 Pro - Firefox 120.0.1
**Reproducible:** always
**Build found:** 12.12.2023

**Preconditions**
1. Registered User is logged in https://www.greencity.social/#/greenCity
2. User is on "My habits" page.
3. User has at least 1 habit in progress for the last 7 days.

**Steps to reproduce**
1. Click on the current day on the Calendar
2. Click on each day 7 days prior the currant date on the calendar.

**Actual result**
By clicking on the currant day or 7 days prior on the Calendar nothing happens, 
the pop-up with a list of habits "In Progress" does not appear.
![photo_5461139191783084504_y](https://github.com/ita-social-projects/GreenCity/assets/148986015/5121ff7c-88d4-4b54-ac8e-6629dfeaa073)

**Expected result**
By clicking the first time on the currant day or 7 days prior on the Calendar the pop-up window with habits 'In Progress' appears open.
By clicking again on the currant day or 7 days prior on the Calendar the pop-up window closes and disappears.

**User story and test case links**
E.g.: "User story #https://github.com/ita-social-projects/GreenCity/issues/1429 
[Test case](https://jira.softserve.academy/browse/GC-1865)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maxv1z** [comment]
Already fixed
