### ISSUE TITLE
[Chat] Incorrect displayed 'Chat' window in 'My space' tab.

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6777]
**Environment:** Chrome 120.0.6099.72(Official version)(64 bit).
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Open Chrome browser.
Moved to https://www.greencity.social/#/greenCity
Sign-in as user/admin.

**Steps to reproduce**
1. Go to 'My Space' tab.
2. Click on 'Chat' window.
3. Click on any one dialog.

**Actual result**
Chat is overlaid on 'My Space' enviroment.
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/d1eeb9d8-d046-4c02-b799-db3dccb49d43)

**Expected result**
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/d879b6f4-d170-4700-9ff1-cf967db78866)

**Comment by MariiaShtraisel** [comment]
Not relevant. The mockup and requirements have changed #6914 https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=12201-4&mode=design
