### ISSUE TITLE
[Chat] Design of the chat window should match the mocap.

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6779]
**Environment:** Chrome 120.0.6099.72(Official version)(64 bit)..
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Open Chrome browser.
Moved to https://www.greencity.social/#/greenCity
Sign-in as user/admin.

**Steps to reproduce**
1. Go to 'My Space' tab.
2. Click on 'Chat' window.
3. Click on any one dialog.

**Actual result**
Chat window design does not match the documentation.
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/0efa8e9e-3dea-468e-bda1-5d2094c0b432)

**Expected result**
Design of the chat window should match the mocap.
![image](https://github.com/ita-social-projects/GreenCity/assets/128135241/465bb324-bbdd-4163-923f-afe5637c98b6)

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by barchikamila** [comment]
[https://github.com/ita-social-projects/GreenCityClient/pull/2843](url)

**Comment by MariiaShtraisel** [comment]
Not relevant. The mockup and requirements have changed #6914 https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=12201-4&mode=design
