### ISSUE TITLE
[Events]Events are not sorted by date in descending order by default on the events page

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#6816]
**Environment:**Windows 10 Pro Version 21H1 OS 19043.928 Google Chrome Version 120.0.6099.130 (Official Build) (64-bit)
**Reproducible:**always
**Build found:**11/01/24

**Preconditions**
1.The site https://www.greencity.social/#/events is opened.
2.Three events created by another user are present.
3.The user is not authorized.

**Steps to reproduce**
Click the 'Events' tab. 

**Actual result**
Events are sorted in random order.

**Expected result**
Events are sorted by future date in descending order by default on the events page.

**User story and test case links**
E.g.: "User story #3197 
[Test case](https://jira.softserve.academy/browse/GC-8088)"
<img width="295" alt="Screenshot 2024-01-04 193727" src="https://github.com/ita-social-projects/GreenCity/assets/150814204/a8865e54-e63e-4dc2-bdb3-6fe50ac6c16d">

**Labels to be added**

**Comment by KizerovDmitriy** [comment]
already fixed
