### ISSUE TITLE
[Create Event] When the user changes focus from 'Location', the floor is not displayed in red

### ISSUE THREAD

**Issue by Tetiana1202** [ita-social-projects/GreenCity#6818]
Environment: MacOS 13.5.1, Google Chrome (120.0.6099.129) 
Reproducible: always
Build found: 08.01.2024

Preconditions: 
1. Go to https://www.greencity.social/#/greenCity
2. User is Authorized
3. Open "Events" page

Steps to reproduce: 
1 .Click on 'Create event' button
2. Click on checkbox 'Place'
3. Click on the 'Location' field
4. Change cursor focus (click on page)

Actual result: 
1. The 'Location' field is grayed out

Expected result:
1. The 'Location' field is displayed in red and the message 'You should fill at least one address or link' is displayed under the field'

User story #4232

**Comment by kulaira** [comment]
The defect is reproduced. Environment: Windows 10, Google Chrome 123.0.6312.86 (64-bit).

**Comment by barchikamila** [comment]
Doesn't reproduce
