### ISSUE TITLE
[Events/Create event]The map for creating the event is not localized.

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#6820]
**Environment:** Windows 10 Pro Version 22H2 OS 19045.3803 Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 11/01/24

**Preconditions**
1.The site https://www.greencity.social/#/events is opened.
2.The user is authorized.
3.'Events' tab is clicked.
4.'Create event' button is clicked.
5.The UA language is selected.

**Steps to reproduce**
1.Click 'Місце' checkbox.
2.Сheck the names of cities on the map.
3.Select English language.
4.Сheck the names of cities on the map.

**Actual result**
The names of the cities are written in two languages: Ukrainian and English. Outside Ukraine, city names are written in the language of the country marked on the map.

**Expected result**
The names of cities (in Ukraine and abroad) are written in only one language, the one that was chosen.

**User story and test case links**
E.g.: "User story #3197 
[Test case](https://jira.softserve.academy/browse/GC-8959)"
<img width="299" alt="L2 1" src="https://github.com/ita-social-projects/GreenCity/assets/150814204/e3fa32ea-d4b5-404f-9f29-5f1caae730b4">
<img width="307" alt="L2 2" src="https://github.com/ita-social-projects/GreenCity/assets/150814204/ba19d526-4baa-4c4f-a004-0bc52f460383">
<img width="301" alt="L2" src="https://github.com/ita-social-projects/GreenCity/assets/150814204/47c920c7-1ebd-4eba-a676-0dfd551fc4a4">

**Labels to be added**

**Comment by CactusNP21** [comment]
may never be fixed. Map is displayed according to browser settings
