### ISSUE TITLE
[Events/Event filters]The "Upcoming" filter is called 'Future'

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#6824]
**Environment:** Windows 10 Pro Version 22H2 OS 19045.3803 Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:**11/01/24

**Preconditions**
1.The site https://www.greencity.social/#/events is opened.
2.The user is authorized.
3.The 'Events' tab is clicked.

**Steps to reproduce**
1.Click on the dropdown 'Event time' on the filters panel.
2.Select checkbox 'Upcoming'.

**Actual result**
There is no 'Upcoming' checkbox on the event card,it called 'Future'.

**Expected result**
 The ''Upcoming' checkbox is present.

**User story and test case links**
E.g.: "User story #3375 
[Test case](https://jira.softserve.academy/browse/GC-3894)"
<img width="218" alt="Screenshot 2024-01-11 203206" src="https://github.com/ita-social-projects/GreenCity/assets/150814204/2dc81c21-ba2f-4091-a91a-1088fec25485">

**Labels to be added**

**Comment by Roksana77** [comment]
It's still a bug on Chrome

![image](https://github.com/user-attachments/assets/16f7e458-b088-428c-8c3e-04545c4599c4)

**Comment by nuttaa0** [comment]
Its still 'Future''
![Image](https://github.com/user-attachments/assets/1449d622-6fd9-4cf2-ba8b-5aa64c2e5c0c)

**Comment by MilaKomisarenko** [comment]
![image](https://github.com/user-attachments/assets/9c6ccef3-0bcd-47fa-9121-2912821d100b)
