### ISSUE TITLE
[Create Event] When the page is in Ukrainian, the calendar is displayed in English

### ISSUE THREAD

**Issue by Tetiana1202** [ita-social-projects/GreenCity#6828]
Environment: MacOS 13.5.1, Google Chrome (120.0.6099.129) .
Reproducible: always
Build found: 08.01.2024

Preconditions:
1. Go to https://www.greencity.social/#/greenCity (UA)
2. User is Authorized
3. Open "Події" page
 
Steps to reproduce:
1. Click on 'Створити подію' button
2. Click on the calendar icon in ''Обрати дату"

Actual result:
1. A calendar is displayed in which months and days are displayed in English

Expected result:
1. A calendar is displayed, in which the months are displayed in Ukrainian

User story #3193

**Comment by Tetiana1202** [comment]
<img width="692" alt="Знімок екрана 2024-01-09 о 22 51 01" src="https://github.com/ita-social-projects/GreenCity/assets/127137747/75b0575d-dec5-47cd-8b32-15e96ac8a8c2">

**Comment by vladmorozov2** [comment]
https://github.com/ita-social-projects/GreenCityClient/pull/2908
