### ISSUE TITLE
[Create news] Source and Image content  is not displayed in Single view after user click on 'Preview' button

### ISSUE THREAD

**Issue by OlesiaSolovii** [ita-social-projects/GreenCity#683]
Environment: macOS Catalina, Version 10.15.4 (19E287),
Google Chrome, Version 81.0.4044.129
Build found: commit 7439e88

**Steps to reproduce:**
1. Sign in on Green City [https://ita-social-projects.github.io/GreenCityClient/#/news]
2. Click on 'Eco News' link
3. Click on 'Create news' button
4. Fill in 'Title' field (e.g. '‘Plastic’ bags")
5. Select one tag (e.g. "News")
6. Fill in 'Content' field (e.g. "Ukrainian scientist invents eco-friendly ‘plastic’ bags")
7. Fill in 'Source' field (e.g. 'https://www.kyivpost.com/lifestyle/ukrainian-scientist-invents-eco-friendly-plastic-bags.html?cn-reloaded=1')
8. Download picture (JPG or PNG) into 'Picture' box 
9. Click on 'Preview' button

**Actual result**
Source and Image content is not displayed in Single view after user click on 'Preview' button.
<img width="1181" alt="Single_view_Preview_btn" src="https://user-images.githubusercontent.com/64583001/81950540-b9406300-960c-11ea-9cfb-1ec62110671d.png">

**Expected result**
Preview news window appears filled in with  data from 4-8 steps.

User story #526 
Test case: [https://jira.softserve.academy/secure/enav/#/7889?query=issue%3DGC-633&offset=1]

**Comment by RomanDeveloperAcc** [comment]
Fixed
