### ISSUE TITLE
[My Events] Created events are not displayed

### ISSUE THREAD

**Issue by ViraM2301** [ita-social-projects/GreenCity#6831]
**Environment:**
11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz   3.19 GHz, 
Windows 11 Pro release , 22H2  
Chrome 120.0.6099.199 (Official Build), (64 bit)
**Reproducible:** always.
**Build found:** 11.01.2024

**Preconditions**
1. Go to https://www.greencity.social/#/greenCity
2. Organizer and/or Admin is loged in.
3. Two events are created by Organizer and/or Admin.
4. The 'My events' tab is opened

**Steps to reproduce**
1. Find the event created by Organizator and/or Admin  in all event list

 **Actual result**
Events from precondition doesn't displayed, only joined and saved events displayed

**Expected result**
Created events are displayed on the 'My events' page

**User story and test case links**
E.g.: "User story #3375 
[Test case](https://jira.softserve.academy/browse/GC-3891)"

**Labels to be added**

[Bug](https://github.com/ita-social-projects/GreenCity/labels/Bug)
[event](https://github.com/ita-social-projects/GreenCity/labels/event)
[Events](https://github.com/ita-social-projects/GreenCity/labels/Events)
[Functional](https://github.com/ita-social-projects/GreenCity/labels/Functional)
[GreenCityEvent](https://github.com/ita-social-projects/GreenCity/labels/GreenCityEvent)
[My Events](https://github.com/ita-social-projects/GreenCity/labels/My%20Events)

**Comment by Maxv1z** [comment]
Already fixed. When User/Admin creates an event, it is shown in "My Events" tab.
![image](https://github.com/ita-social-projects/GreenCity/assets/122612827/85ae9729-41ad-412b-a1fd-be3cd2ac2379)
