### ISSUE TITLE
[My Events] The filter for offline events joined by IP address does not work 

### ISSUE THREAD

**Issue by ViraM2301** [ita-social-projects/GreenCity#6832]
**Environment:** 
11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz   3.19 GHz, 
Windows 11 Pro release , 22H2  
Chrome 120.0.6099.199 (Official Build), (64 bit)

**Reproducible:** always.

**Build found:** 11/01/2024

**Preconditions**
1. The site [https://www.greencity.social/](https://www.greencity.social/#/events) is opened.
2. The User is logged-in.
3. User should be joined to 2 online and 2 offline events.

**Steps to reproduce**
1. Click on "My space" tab in a header
2. Click on "My events" tab in profile
3. Select the checkbox 'Offline'

**Actual result**
Offline events are displayed regardless of the venue and date

**Expected result**
All upcoming offline events is filtered by place closer to the User's IP location, so that closer events have higher position in the list

**User story and test case links**
E.g.: "User story #3375 
[Test case](https://jira.softserve.academy/browse/GC-3893)"

**Labels to be added**
[Bug](https://github.com/ita-social-projects/GreenCity/labels/Bug)
[event](https://github.com/ita-social-projects/GreenCity/labels/event)
[Events](https://github.com/ita-social-projects/GreenCity/labels/Events)
[Functional](https://github.com/ita-social-projects/GreenCity/labels/Functional)
[GreenCityEvent](https://github.com/ita-social-projects/GreenCity/labels/GreenCityEvent)
[My Events](https://github.com/ita-social-projects/GreenCity/labels/My%20Events)
[Pri: medium](https://github.com/ita-social-projects/GreenCity/labels/Pri%3A%20medium)
[Sev: minor](https://github.com/ita-social-projects/GreenCity/labels/Sev%3A%20minor)

**Comment by Maxv1z** [comment]
Bug is reproducible when user didn't allow an access to geodata. When user gives a permission - everything works

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/4dcc72cb-66aa-4d78-ac53-908380bd4882)

Everything is according location. It's not a bug on Chrome 127.0.6533.100  (64-bit)
