### ISSUE TITLE
[Events.Comment] If user enter special characters when editing a comment, they are not saved

### ISSUE THREAD

**Issue by ViraM2301** [ita-social-projects/GreenCity#6833]
**Environment:** 
11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz 3.19 GHz,
Windows 11 Pro release , 22H2
Chrome 120.0.6099.199 (Official Build), (64 bit)

**Reproducible:** always.
**Build found:** 11.01.2024
**Preconditions**
1.The site https://www.greencity.social/#/events is opened.
2.The User is logged-in.
3.An event is opened and a comment is written

**Steps to reproduce**
1.'Edit' button is clicked on.
2.Type special characters in 'Edit' text field.
3.Click "Save changes" button.

**Actual result**
The data was saved and the message 'Oops, something went wrong. Please reload page or try again later'. After reloading the page, the special characters in the edited comment disappeared.

**Expected result**
Special characters are in the edit comment

**User story and test case links**
E.g.: "User story #3210 
[Test case](https://jira.softserve.academy/browse/GC-3861)"

**Labels to be added**
[Bug](https://github.com/ita-social-projects/GreenCity/labels/Bug)
[Event Description](https://github.com/ita-social-projects/GreenCity/labels/Event%20Description)
[event](https://github.com/ita-social-projects/GreenCity/labels/event)
[Events](https://github.com/ita-social-projects/GreenCity/labels/Events)
[Functional](https://github.com/ita-social-projects/GreenCity/labels/Functional)
[GreenCityEvent](https://github.com/ita-social-projects/GreenCity/labels/GreenCityEvent)
[Pri: medium](https://github.com/ita-social-projects/GreenCity/labels/Pri%3A%20medium)
[Sev: major](https://github.com/ita-social-projects/GreenCity/labels/Sev%3A%20major)

**Comment by Roksana77** [comment]
![comment](https://github.com/user-attachments/assets/5ab16682-6832-420e-ae38-39281bd4daa0)
Special characters are in the edit comment on Chrome 127.0.6533.100 (64-bit)
