### ISSUE TITLE
[Events] There is no 'Rate Organizer' button on the cards 

### ISSUE THREAD

**Issue by ViraM2301** [ita-social-projects/GreenCity#6835]
**Environment:** 
11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz   3.19 GHz, 
Windows 11 Pro release , 22H2  
Chrome 120.0.6099.199 (Official Build), (64 bit)

**Reproducible:** always.
**Build found:** 11/01/2024

**Preconditions**
1.The site [https://www.greencity.social/](https://www.greencity.social/#/events) is opened.
2.The User is logged-in.
3.The 'Events' tab is opened.
4.The user must be a participant of one completed event.

**Steps to reproduce**
1. Сlick on the dropdown 'Status' and select the checkbox 'Joined'
2. Click on the dropdown 'Event time' and select the checkbox 'Past'
3. Click the ‘Rate Organizer’ button  on the event card 

**Actual result**
Cards with events that cannot be rated are displayed

**Expected result**
Cards with the 'Rate Organizer' button displayed

**User story and test case links**
E.g.: "User story #3268 
[Test case](https://jira.softserve.academy/browse/GC-8767)"

**Labels to be added**

[Bug](https://github.com/ita-social-projects/GreenCity/labels/Bug)
[event](https://github.com/ita-social-projects/GreenCity/labels/event)
[Events dashboard](https://github.com/ita-social-projects/GreenCity/labels/Events%20dashboard)
[Events Organizer Rating](https://github.com/ita-social-projects/GreenCity/labels/Events%20Organizer%20Rating)
[Events](https://github.com/ita-social-projects/GreenCity/labels/Events)
[GreenCityEvent](https://github.com/ita-social-projects/GreenCity/labels/GreenCityEvent)
[Pri: medium](https://github.com/ita-social-projects/GreenCity/labels/Pri%3A%20medium)
[Sev: minor](https://github.com/ita-social-projects/GreenCity/labels/Sev%3A%20minor)
[UI](https://github.com/ita-social-projects/GreenCity/labels/UI)

**Comment by ViraM2301** [comment]
![Uploading 8767 events.png…]()

**Comment by Maxv1z** [comment]
Rate organizer is missing on event cards, because endpoint `https://greencity.greencity.social/events?` returns property `isRelevant` set to false, when actually it should be true (based on an event and current date). 
It also can be seen on another endpoint `https://greencity.greencity.social/events/event`, that returns `isRelevant` set to true for the same event id (see video below).


https://github.com/ita-social-projects/GreenCity/assets/122612827/22ce2ed2-d55e-4938-b5ba-69ea0a8ccf62

**Comment by KizerovDmitriy** [comment]
not actual
