### ISSUE TITLE
[Events] When the 'Past' event filter is set, 'Past' and 'Current' events are displayed

### ISSUE THREAD

**Issue by ViraM2301** [ita-social-projects/GreenCity#6836]
**Environment:**
11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz   3.19 GHz, 
Windows 11 Pro release , 22H2  
Chrome 120.0.6099.199 (Official Build), (64 bit)

Build found: 11.01.2024

**Preconditions**
The site https://www.greencity.social/#/events is opened.
The 'Events' page is opened.

**Steps to reproduce**
1. Click on the dropdown 'Event time' and select the checkbox 'Past'

 **Actual result**
All completed and current events are displayed

**Expected result**
All completed events are displayed

**User story and test case links**
E.g.: "User story #3268
[Test case](https://jira.softserve.academy/browse/GC-8767)"

**Labels to be added**
[Bug](https://github.com/ita-social-projects/GreenCity/labels/Bug)
[event](https://github.com/ita-social-projects/GreenCity/labels/event)
[Events dashboard](https://github.com/ita-social-projects/GreenCity/labels/Events%20dashboard)
[Events](https://github.com/ita-social-projects/GreenCity/labels/Events)
[Functional](https://github.com/ita-social-projects/GreenCity/labels/Functional)
[GreenCityEvent](https://github.com/ita-social-projects/GreenCity/labels/GreenCityEvent)
[Pri: medium](https://github.com/ita-social-projects/GreenCity/labels/Pri%3A%20medium)
[Sev: minor](https://github.com/ita-social-projects/GreenCity/labels/Sev%3A%20minor)

**Comment by Maxv1z** [comment]
Not reproducible. See only past events
