### ISSUE TITLE
[My Events]  The 'Rate Organiser' button is missing on event cards 

### ISSUE THREAD

**Issue by ViraM2301** [ita-social-projects/GreenCity#6839]
**Environment:** 
11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz   3.19 GHz, 
Windows 11 Pro release , 22H2  
Chrome 120.0.6099.199 (Official Build), (64 bit)

**Reproducible:** always.

**Build found:** 11.01.2024

**Preconditions**
1.The site https://www.greencity.social/#/events is opened.
2.The User is logged-in.
3.User should be an Attendee of the two event that are passed.
4.'My events' page is opened.

**Steps to reproduce**
1. Find an attended event in the list 
2. Click the‘Rate Organizer’ button 

**Actual result**
Cards are displayed without the ability to rate the event
![image](https://github.com/ita-social-projects/GreenCity/assets/122612827/779a959d-524e-4824-a024-e74f1e9008ee)

**Expected result**
The cards should have a 'Rate Organizer' button to rate the event

**User story and test case links**
E.g.: "User story #3268
[Test case](https://jira.softserve.academy/browse/GC-8767)"

**Comment by ViraM2301** [comment]
![8767](https://github.com/ita-social-projects/GreenCity/assets/151033706/6a148d90-c341-414f-9e58-1ca270db9801)

**Comment by dmytro-kryvyi** [comment]
It was decided to remove the functionality for evaluating the organizer from the application. You can evaluate only the event itself

**Comment by ViktoriyaRyazhska** [comment]
not relevant
