### ISSUE TITLE
[Event. Reply on comment] Gray 'Replay' bttn remains grey when user is writing a replay under a comment

### ISSUE THREAD

**Issue by OlenaKhita** [ita-social-projects/GreenCity#6854]
**Environment:**
Chrome Version 120.0.6099.200 (Official Build) (64-bit)
Windows 10 Pro Version 21H2

**Reproducible:** always
**Build found:** 11/01/2024

**Preconditions**
1.User1 is exist
2. Logged-in User1 user is authorized
3. Event 1 card is opened
4. The comment to the Event 1 is written by User1 or someone else  

**Steps to reproduce**
1. Scroll to comment's block
2. Go to existing comment
3. Click on grey 'Reply' bttn under the comment

**Actual result**
Gray 'Replay' bttn doesn't change color to green when is writing a replay 
![bttn](https://github.com/ita-social-projects/GreenCity/assets/150794535/ab107534-e81c-4069-b4d9-23e06803a72c)

**Expected result**
Gray 'Replay' bttn turned green when writing a replay 

![reply (1)](https://github.com/ita-social-projects/GreenCity/assets/150794535/e7dccb12-87eb-4cd8-8d44-db57d7a974e0)

**User story and test case links**
User story #3211

**Comment by Roksana77** [comment]
Gray 'Replay' button turned green when writing a replay on Chrome 127.0.6533.100 (64-bit)

![image](https://github.com/user-attachments/assets/5bd8111e-23df-43ec-b55e-944f4ddd92ee)
