### ISSUE TITLE
[Events. Create event] User can create an event in case if the 'Location' checkboxes was not selected

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6855]
**Environment:** OS: Windows 11 Pro, version 22H2, build 22621.2861
Browser: Firefox version 121.0
**Reproducible:** always
**Build found:** 07.01.2024

*Preconditions:*
1. The site [GreenCity|https://www.greencity.social/#/greenCity] is opened
2. User is logged in
3. The 'Events' page is opened

*Steps to reproduce:*
1. Click on the 'Create event' button
2. Fill in mandatory fields 'Title', 'Events Description', pick 'Initiative type', 'Date', 'Start Time', 'End Time'
3. Click on the 'Publish' button

*Actual result:*
The event is created. Offline location "Міні-аеродром, dsadsa, Kyiv, Ukraine, 02000" is added.

*Expected result:*
Error message in red color 'You should fill at least one address or link' appears below the 'Location' checkboxes.

Attachments: 
<img width="721" alt="create event no location1" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/6ec9f1ad-b715-4016-a3e5-2b610faf5df6">
<img width="725" alt="create event no location2" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/6e224a73-0b57-44e6-9b84-c7b1978c924c">

**User story and test case links**
User story #4232
[Test case GC-5445](https://jira.softserve.academy/browse/GC-5445)

**Comment by Maxv1z** [comment]
Fixed
