### ISSUE TITLE
[Events. Create event] Incorrect error message appears when the user uploads picture in forbidden format

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6863]
**Environment:**OS: Windows 11 Pro, version 22H2, build 22621.2861
Browser: Firefox version 121.0
**Reproducible:** always
**Build found:** 08.01.2024

**Preconditions**
1. The site [GreenCity](https://www.greencity.social/#/greenCity) is opened
2. The user is logged in
3. The 'Events' page is opened

**Steps to reproduce**
1. Click on the 'Create event' button
2. Click on the '+' button in the 'Picture' section to upload the file
3. Upload the file not in PNG and JPG format. e.g. in TIF or GIF format 
![picture_GIF](https://github.com/ita-social-projects/GreenCity/assets/95030828/cfb3ca1c-bc7e-4182-9c9f-e71b1fa7c1db)

**Actual result**
Red error message appears "Incorrect image type. Use file format JPG or PNG"
<img width="762" alt="create event incorrect image type" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/36b31e2a-99c5-4cdb-8486-30088a1a1898">

**Expected result**
Red error message appears "Incorrect picture format. Use files in JPG or PNG format instead"

**User story and test case links**
User story #6359 
[Test case GC-8880](https://jira.softserve.academy/browse/GC-8880)

**Comment by OlenaKhita** [comment]
An error message "Incorrect picture format. Use files in JPG or PNG format insteadshould be displayed instead of a message "Incorrect image type. Use files in JPG or PNG format instead".

**Comment by yulianagoncharenko** [comment]
when a file is uploaded file in the format other than JPG, PNG "errorMessage" highlighted is shown and then disappears without any user action. 
![image-2024-04-02-23-18-21-945](https://github.com/ita-social-projects/GreenCity/assets/24385480/8eadd019-80e0-4392-895d-022647fa57c8)
