### ISSUE TITLE
[Events. Create Event] Text formatting (text font, size, alignment) is not applied in the event card description after publishing the event

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6864]
**Environment:** OS: Windows 11 Pro, version 22H2, build 22621.2861
Browser: Firefox version 121.0
**Reproducible:** always
**Build found:** 09.01.2024

**Preconditions**
1. The site [GreenCity](https://www.greencity.social/#/greenCity) is opened
2. User is logged in
3. The 'Events' page is opened

**Steps to reproduce**

1. Click on the 'Create event' button
2. Fill in fields 'Title', 'Initiative type', 'Date', 'Start Time', 'End Time'
3. In the 'Description' field type random text and apply to it different fonts: Sans Serif, Serif, Monospace
4. On the next 4 different lines in the 'Description field' type random text and apply to it right, left, center alignment and by width
5. On the next line in the 'Description' field type random text and apply to it different sizes
6. Click on the 'Publish' button
7. On the 'Events' page open created even by clicking on the 'More' button
8. Observe description of the event.

**Actual result**
All text in the description is displayed in Sans Serif font, normal size, aligned to the right.
<img width="677" alt="create event formatting description1" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/fb5f3734-4ef5-4cf4-8ec8-3ff4579fdb16">
<img width="666" alt="create event formatting description2" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/c1385d39-1051-4c25-875f-7902a08907aa">

**Expected result**
Text in the description is displayed in different fonts, sizes, with different aligning according to the formatting during creating the event

**User story and test case links**
User story #3193 
[Test case GC-3175](https://jira.softserve.academy/browse/GC-3175)

**Comment by OksanaFilipchuk** [comment]
The same issue : https://github.com/ita-social-projects/GreenCity/issues/6195
