### ISSUE TITLE
[Events. Create event] Time in the 'Start Time' and 'End Time' fields are displayed in incorrect format if the 'All day' checkbox is selected

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6867]
**Environment:** OS: Windows 11 Pro, version 22H2, build 22621.2861
Browser: Firefox version 121.0
**Reproducible:** always
**Build found:** 09.01.2024

**Preconditions**

1. The site [GreenCity](https://www.greencity.social/#/greenCity) is opened
2. The user is logged in
3. The 'Events' page is opened

**Steps to reproduce**

1. Click on the 'Create event' button
2. Fill in mandatory fields 'Title', 'Initiative type', 'Events description'.
3. Pick any date in future in the 'Date field'
4. Check off the 'All day' checkbox

**Actual result**
The 'Start Time' dropdown list is disabled, "0:00" time is set by default. The 'End Time' dropdown list is disabled, "00:00" time is set by default
<img width="660" alt="create event all day time" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/30d2b199-cc74-4a04-a818-9b6f3c091487">

**Expected result**
The 'Start Time' dropdown list is disabled, "00:00" time is set by default. The 'End Time' dropdown list is disabled, "23:59" time is set by default

**User story and test case links**
User story #4232 
[Test case GC-5445](https://jira.softserve.academy/browse/GC-5445)

**Comment by OlenaKhita** [comment]
The disabled dropdown list "Start Time" should display "00:00" (no 0:00) by default when 'All day' checkbox is selected.  [https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=50699-55581&mode=design](url)

**Comment by OlenaKhita** [comment]
The disabled dropdown list "Start Time" should display "00:00" (no 0:00) by default when 'All day' checkbox is selected. [https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=50699-55581&mode=design](https://github.com/ita-social-projects/GreenCity/issues/url)
