### ISSUE TITLE
[Events. Create event] Address for the offline event location was changed after publishing/ after applying to all days

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6869]
**Environment:** OS: Windows 11 Pro, version 22H2, build 22621.2861
Browser: Firefox version 121.0
**Reproducible:** sometimes 
**Build found:** 11.01.2024

**Preconditions**

1. The site [GreenCity](https://www.greencity.social/#/greenCity) is opened
2. User is logged in
3. Localization UA is chosen
4. The 'Events' page is opened

**Steps to reproduce**
**Case1:**

1. Click on the 'Create event' button
2. Fill in mandatory fields 'Title', 'Events Description', pick 'Initiative type', 'Date', 'Start Time', 'End Time'
3. Select the 'Place' checkbox
4. In the 'Location' field enter the address "вулиця Квітки-Основ'яненка, 15, Львів, Львівська область, Україна" and pick the address from the dropdown list
5. Click the 'Publish' button

**Actual result**
In the preview event card, on the 'Events' page, the address is changed to "Україна, Львів, вулиця Квітки-Основ'яненка, 16"
<img width="191" alt="create event address" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/6439cd5d-8a34-4bd7-821b-1d1d30c8571b">

**Expected result**
In the preview event card, on the 'Events' page, the address, that was specified during creating the event, is shown.

**Case 2:**

1. Steps 1-3 from Case 1
2. In the 'Location' field enter the address "вулиця Сковороди, 16, Хмельницький, Хмельницька область, Україна" and pick the address from the dropdown list
3. Select 'Apply to all days of the event' checkbox
4. Observe addresses in the 'Location ' fields for all days

**Actual result:** Addresses for for 2nd and next days are displayed with different number of the building
<img width="610" alt="create event apply to all 2" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/163cddb2-b0fa-4f45-82df-414ad17e040c">

**Expected result:** Addresses for all days are the same.

**User story and test case links**
User story #4232
[Test case GC-5445](https://jira.softserve.academy/browse/GC-5445)

**Comment by CactusNP21** [comment]
There are no buildings in Ukraine under numbers mentioned above, so it is working correctly
