### ISSUE TITLE
[Events. Create event] Uploaded images diplayed cropped on the preview event card and Event card after publishing the event

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6873]
**Environment:** OS: Windows 11 Pro, version 22H2, build 22621.2861
Browser: Firefox version 121.0
**Reproducible:** always
**Build found:** 11.01.2024

**Preconditions**

1. The site [GreenCity](https://www.greencity.social/#/greenCity) is opened
2. The user is logged in
3. The 'Events' page is opened

**Steps to reproduce**

1. Click on the 'Create event' button
2. Fill in mandatory fields 'Title', 'Initiative type', 'Events description', 'Date', 'Start time', 'End time'
3. Upload 5 images with different resolutions
4. Click on the 'Publish' button
5. Observe the poster of the event on the preview event card
6. Open event details by clicking on the 'More' button on the preview event card
7. Observe all uploaded images

**Actual result**
Pictures are cropped
<img width="613" alt="create event image crop1" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/637ef54c-173f-4fe8-82e9-1c4526321932">
<img width="614" alt="create event image crop2" src="https://github.com/ita-social-projects/GreenCity/assets/95030828/ccffdab0-1287-4fe8-b65f-32c8ce9e7c71">
[Test data.zip](https://github.com/ita-social-projects/GreenCity/files/13920621/Test.data.zip)

**Expected result**
The size of the pictures is adapted to the size of the Poster box. Pictures are not cropped

**User story and test case links**
User story #3193 
[Test case GC-3125](https://jira.softserve.academy/browse/GC-3125)

**Comment by dmytro-kryvyi** [comment]
It is impossible to always fit images without cropping or distortions. Instead I have added an opportunity to crop images by clicking on 'pencil' icon to crop as user wishes
