### ISSUE TITLE
[Event. Reply comment] The reply message is not displayed after pressing 'Reply' button.

### ISSUE THREAD

**Issue by Rusiaieva** [ita-social-projects/GreenCity#6875]
**Environment:** Windows 11 Pro, Version 22H2
OS build 22621.2861
Experience Windows Feature Experience Pack 1000.22681.1000.0
Chrome: Version 120.0.6099.200 (Official Build) (64-bit)

**Reproducible:** always
**Build found:** 09.01.2024

**Preconditions**
1. The site [Green City](https://www.greencity.social/#/greenCity) is opened 
2. User_1, User_2 exists
3. User_1 is logged in
4. Click on the 'Events' tab in the header
5. Event_1 exists
6. Open an Event_1 with at least one Comment_1 from User_2

**Steps to reproduce**
1. Enter the text to the Text box click on 'Replay' button

**Actual result**
The reply is not displayed. Only after page refresh.
![Screenshot 2024-01-14 205643](https://github.com/ita-social-projects/GreenCity/assets/138620529/ae9fc47d-8e6d-43bc-8b00-27106c2550a2)

**Expected result**
1. The reply is displayed under the reply Text box 'Add a reply'.
2. The reply is displayed on the top of replies list.

**User story and test case links**
E.g.: "User story #3211
[Test case](https://jira.softserve.academy/browse/GC-8800)"

**Comment by dmytro-kryvyi** [comment]
fixed in this pr [#2871](https://github.com/ita-social-projects/GreenCityClient/pull/2871)
