### ISSUE TITLE
[Event. Reply comment] User could not create a reply with 8000 characters

### ISSUE THREAD

**Issue by Rusiaieva** [ita-social-projects/GreenCity#6877]
Environment: Chrome: Version 120.0.6099.199 (Official Build) (64-bit)
Windows 11 Pro,
Version 22H2
**Reproducible:** always
**Build found:** 07.01.2024

**Preconditions**
1. The site [Green City](https://www.greencity.social/#/greenCity) is opened
2. User_1, User_2 exists
3. User_1 is logged in
4. The 'Events' tab is chosen
5. Event_1 exists and opened
6. Event_1 has Comment_1 from User_2

**Steps to reproduce**
1. Click the "Reply" icon under the Comment_1

2. Enter a text containing 8000 characters in the reply field 
[8000.docx](https://github.com/ita-social-projects/GreenCity/files/13933052/8000.docx)

3. Click the "Reply" button

**Actual result**
Could not save reply on 8000 characters after the click to the 'Reply' button 
'Reply' button  is enabled  
![Screenshot 2024-01-14 213732](https://github.com/ita-social-projects/GreenCity/assets/138620529/a28eadda-dbeb-452d-9331-3a95c885ce6e)

**Expected result**
Reply is saved and displayed in ‘View [number] replies’ list.

**User story and test case links**
E.g.: "User story #3211
[Test case](https://jira.softserve.academy/browse/GC-8806)"

**Comment by dmytro-kryvyi** [comment]
You should understand that 8000 is limitation for API. The amount of characters is calculated by their code representation. 

Let's take the ampersand (&) symbol as an example. In the user interface (UI), this symbol may occupy five spaces, but for the user, only one symbol is apparent. Similarly, when users tag someone, it's not just the name itself that contributes to the character count. Behind the scenes, additional code is necessary to represent the user tag, resulting in a higher character count than what's immediately visible.

In essence, our character count validation ensures that users stay within the 8000-character limit imposed by our API
