### ISSUE TITLE
[Events. Reply comment] UI elements 'Reply' button of the reply on the comment are not according to the mock-up

### ISSUE THREAD

**Issue by Rusiaieva** [ita-social-projects/GreenCity#6879]
Environment: Chrome: Version 120.0.6099.200 (Official Build) (64-bit)
Windows 11 Pro, Version 22H2
OS build 22621.2861
Experience Windows Feature Experience Pack 1000.22681.1000.0

**Reproducible:** always
**Build found:** 09.01.2024

**Preconditions**
1. The site [Green City](https://www.greencity.social/#/greenCity) is opened
2. Sign in (e.g. using a Google account)
3. Click on the 'Events' tab
4. Choose the Event preview card with a comment

**Steps to reproduce**
1. Open 'Reply' field under 'Comments'
2. Find existing comment

**Actual result**
'Reply' button is not present on a mock up. 
![Screenshot 2024-01-14 221022](https://github.com/ita-social-projects/GreenCity/assets/138620529/359033b8-8dbf-49b5-83a8-5b3a60c11237)

Real button in site 
![Screenshot 2024-01-14 220120](https://github.com/ita-social-projects/GreenCity/assets/138620529/76ad11e5-4d40-48a4-9d01-34ae4e3035c6)

**Expected result**
Probably mock-up is outdated and should be validated.
[https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=13787-55543&mode=design](url)

**User story and test case links**
E.g.: "User story #3211
[Test case](https://jira.softserve.academy/browse/GC-5145)"

**Comment by dmytro-kryvyi** [comment]
Not a bug, mock-up is deprecated. There should be reply button anyway
