### ISSUE TITLE
[Edit photo, save changes] Buttons are located vertically under each other, deviating from the mockup - near each other when the extension is 576

### ISSUE THREAD

**Issue by Viktoriia0106** [ita-social-projects/GreenCity#6881]
**Environment:**
Windows 10 x64
Google Chrome 120.0.6099.217 

**Reproducible:** always

**Build found:** 16.01.2024_11:30

**Preconditions**
The user registered and logged in to the 'https://www.greencity.social/#/greenCity' website.
The 'My Space' page is opened.
The English language is chosen.
The ‘Edit photo’ mock-up link [edit photo](https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=13449-1769&mode=design&t=D7HgH7U47MGznwlE-4)

**Steps to reproduce**
1. Click the 'Edit Profile' icon
2. Click the 'Edit photo' icon
3. Click the 'Upload new photo' button
4. Add new photo
5. Open Devtools and choose the "576" extension 
6. Pay attention to the buttons' location

**Actual result**
Buttons are located vertically under each other, deviating from the mockup - near each other, when the extension is 576

**Expected result**
Buttons are located horizontally near each other, according to the mockup when the extension of the screen is 576

The bug is reproduced in the Ua localization as well.

**User story and test case links**
[Test case GC-4681](https://jira.softserve.academy/browse/GC-4681)"

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity: Trivial"), Type ("UI)

![576_mock-up_WYL_to_save_changes](https://github.com/ita-social-projects/GreenCity/assets/109147739/c73c9a07-4666-4aab-ac40-67079c376fc4)
![576_act_WYL_to_save_changes](https://github.com/ita-social-projects/GreenCity/assets/109147739/fad2169a-4c4f-4eb7-98a2-aca93295fc29)

**Comment by dmytro-kryvyi** [comment]
Not a bug. Mocup is deprecated because in Ukrainian localization it is impossible to align elements in line due to their width.

**Comment by Viktoriia0106** [comment]
"Not a bug" or "Not reproduced"? I've just checked and the buttons are located as on the mock-up. 
![image](https://github.com/ita-social-projects/GreenCity/assets/109147739/56706499-b2ad-49d5-94cd-83cc73573427).
