### ISSUE TITLE
[Edit photo, save changes] The  "Would you like to save changes?" text's alignment is not matched to the mockup when the screen's extension is 576

### ISSUE THREAD

**Issue by Viktoriia0106** [ita-social-projects/GreenCity#6882]
**Environment:**
Windows 10 x64
Google Chrome 120.0.6099.217

**Reproducible:** always

**Build found:** 16.01.2024_11:40

**Preconditions**
The user registered and logged in to the 'https://www.greencity.cx.ua/#/greenCity' website.
The 'My Space' page is opened.
The English language is chosen.
The ‘Edit photo’ mock-up link [edit photo](https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=13449-1769&mode=design&t=D7HgH7U47MGznwlE-4)

**Steps to reproduce**
1. Click the 'Edit Profile' icon
2. Click the 'Edit photo' icon
3. Click the 'Upload new photo' button
4. Add a new photo
5. Open Devtools and choose the "576" extension
6. Pay attention to the text's alignment

**Actual result**
The text's alignment is not matched to the mockup when the screen's extension is 576

**Expected result**
The "Would you like to save changes?" text is placed in one line according to the mockup when the screen's extension is 576

User story and test case links
[Test case GC-4681](https://jira.softserve.academy/browse/GC-4681)"

"Bug", Priority ("pri: Low"), Severity ("severity: Trivial"), Type ("UI)

![576_act_WYL_to_save_changes_text](https://github.com/ita-social-projects/GreenCity/assets/109147739/61fe5963-e4b1-4250-ae03-d6ed5378ace2)
![576_mock-up_WYL_to_save_changes](https://github.com/ita-social-projects/GreenCity/assets/109147739/7410fe1f-3ac4-4738-8806-7ea676865171)

**Comment by Maxv1z** [comment]
Not reproducable:
![image](https://github.com/ita-social-projects/GreenCity/assets/122612827/68572f85-3d2c-4742-919f-85155ca61e5a)

![image](https://github.com/ita-social-projects/GreenCity/assets/122612827/2042ad7f-44cc-4830-9b0f-fb3230d800ee)
