### ISSUE TITLE
[Edit photo, save changes] The 'Edit Profile' page is not shown on the background  during changing the profile photo when expanding the screen is 576

### ISSUE THREAD

**Issue by Viktoriia0106** [ita-social-projects/GreenCity#6883]
**Environment:**
Windows 10 x64
Google Chrome 120.0.6099.217

**Reproducible:** always

**Build found:** 16.01.2024_13:30

**Preconditions**
The user registered and logged in to the 'https://www.greencity.social/#/greenCity' website.
The 'My Space' page is opened.
The English language is chosen.
The ‘Edit photo’ mock-up link [edit photo](https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=13449-1769&mode=design&t=D7HgH7U47MGznwlE-4)

**Steps to reproduce**
1. Click the 'Edit Profile' icon
2. Click the 'Edit photo' icon
3. Click the 'Upload new photo' button
4. Add a new photo
5. Open Devtools and choose the "576" extension
6. Pay attention to the 'Edit Profile' page view

**Actual result**
The 'Edit Profile' page is not shown on the background  during changing the profile photo when expanding the screen is 576

**Expected result**
The 'Edit Profile' page background is visible according to the mockup for a clear and seamless user experience

The bug is reproduced in the Ua localization as well.

**User story and test case links**
[Test case GC-4681](https://jira.softserve.academy/browse/GC-4681)"

"Bug", Priority ("pri: Medium"), Severity ("severity: Trivial"), Type ("UI)
![576_mock-up_WYL_to_save_changes](https://github.com/ita-social-projects/GreenCity/assets/109147739/be28dbc0-5cb1-4d63-a7c1-22eeb9a8f4ee)
![Edit profile page](https://github.com/ita-social-projects/GreenCity/assets/109147739/d169d97b-4308-47c8-bb35-79eeffa68e53)

**Comment by ShyraiDan** [comment]
Can't reproduce
