### ISSUE TITLE
Tag "News" is not displayed in tag selection in edit news function

### ISSUE THREAD

**Issue by Radi0activeBaby** [ita-social-projects/GreenCity#6888]
**Environment:**    OS, Win 10 GoogleChrome 120.0.6099.217
**Reproducible**: After user is loged in ,and located in creating or changing information, and user refreshing page 
**Preconditions** User Loged as a User

**Steps to reproduce**
1. Go to https://www.greencity.social/#/news/create-news?id=1257
2. In function "Pick tags for news" no tag News

**Actual result**
When choosing tags to create a new news, display 2 Ads tags and no  News tag

**Expected result**
When choosing tags should be news, events, courses(changed to education), initiatives and advertising tags

**User story and test case links**
E.g.: "User story #660

**Comment by Radi0activeBaby** [comment]
![image](https://github.com/ita-social-projects/GreenCity/assets/137924994/d56feaa4-f455-4a39-a236-9041a8cd6fc2) **Must be**

![image](https://github.com/ita-social-projects/GreenCity/assets/137924994/5e7148dd-1a7c-4fe3-aaab-487be1b7f58e) **Is**

**Comment by ShyraiDan** [comment]
Can't reproduce
