### ISSUE TITLE
[API]System allow create news with empty ‘title’ field.

### ISSUE THREAD

**Issue by Vitaliipuchak** [ita-social-projects/GreenCity#689]
**Reproducible**: always
**Preconditions:**
1. Swagger https://greencity.azurewebsites.net/swagger-ui.html#/ is opened.
2. Log in as a registered user
3. Get token
4. Authorize
**Steps to reproduce:**
1. Click on 'eco-news-controller' drop down page;
2. Click on '/econews Add new eco news.' request;
3. Click "Try it out" button;
4. Edit request:
{
"tags": ["ads"],
"title": "",
"text": "TC_GC-572",
"source": ""
}
5. Click "Execute" button.
**Actual result:** News with empty ‘title’ field was created and added to DB.
**Expected result:**  News with empty ‘title’ field shouldn`t be created and added to DB. User should get an appropriative error message.
**User story:** #537 
**Test case:** https://jira.softserve.academy/browse/GC-572

**Comment by rsyvulko** [comment]
Verified.

**Comment by marjana07** [comment]
**The defect is reproducible with Json:**
{
"tags": ["ads"],
"text": "123456789101112131415",
![empty title](https://user-images.githubusercontent.com/57389132/83632328-be5b5700-a5a7-11ea-86fb-dc6415c834c3.png)

"source": ""
}

**If we don't set a key in Json this field has a null value, and the news is created.**

{
  "id": 740,
  "title": null,
  "text": "123456789101112131415",
  "ecoNewsAuthorDto": {
    "id": 154,
    "name": "MarJana"
  },
  "creationDate": "2020-06-03T11:35:07.11Z",
  "imagePath": "https://storage.cloud.google.com/staging.greencity-c5a3a.appspot.com/eb0f5932-ac88-45e5-b7d0-bb9d6c495117",
  "source": "",
  "tags": [
    "ads"
  ]
}
