### ISSUE TITLE
[Edit photo, pop-up] Buttons are located vertically under each other, deviating from the mockup - near each other when the extension is 576

### ISSUE THREAD

**Issue by Viktoriia0106** [ita-social-projects/GreenCity#6890]
**Environment:**
Windows 10 x64
Google Chrome 120.0.6099.217

**Reproducible:** always

**Build found:** 16.01.2024_20:00

**Preconditions**
The user is registered and logged in to the 'https://www.greencity.social/#/greenCity' website.
The 'My Space' page is opened.
The English language is chosen.
The ‘Edit photo’ mock-up link [edit photo](https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=13449-1612&mode=design&t=fvv6EDIe09WJTncW-4)

**Steps to reproduce**
1. Click the 'Edit Profile' icon
2. Click the 'Edit photo' icon
3. Open Devtools and choose the "576" extension
4. Pay attention to the buttons' location in the 'Do you want to change your profile picture?' pop-up

**Actual result**
Buttons are located vertically under each other, deviating from the mockup - near each other, when the extension is 576

**Expected result**
Buttons are located horizontally near each other, according to the mockup when the extension of the screen is 576

The bug is reproduced in the Ua localization as well.

**User story and test case links**
[Test case GC-4678](https://jira.softserve.academy/browse/GC-4678)"

![576_act_do you want to change your profile picture](https://github.com/ita-social-projects/GreenCity/assets/109147739/f8979566-bcbe-48ff-866d-458449ba17ea)

![576_mock-up_do you want to change your profile picture](https://github.com/ita-social-projects/GreenCity/assets/109147739/9ff2c742-49c0-4188-be9a-0a0f04e651f8)

**Comment by dmytro-kryvyi** [comment]
Not a bug. Mocup is deprecated because in Ukrainian localization it is impossible to align elements in line due to their width.

**Comment by Viktoriia0106** [comment]
"Not a bug" or "Not reproduced"? I've just checked and the buttons are located as on the mock-up.
![image](https://github.com/ita-social-projects/GreenCity/assets/109147739/288d3ffd-ce7d-41e1-9ffd-8120850dcd3f)

**Comment by dijulya** [comment]
Verified on Windows 11 Pro, Chrome 122.0.6261.131
