### ISSUE TITLE
[Edit photo, pop-up] The "Do you want to change your profile picture?" text's alignment is not matched to the mockup when the screen's extension is 576

### ISSUE THREAD

**Issue by Viktoriia0106** [ita-social-projects/GreenCity#6891]
**Environment:**
Windows 10 x64
Google Chrome 120.0.6099.217

**Reproducible:** always

**Build found:** 16.01.2024_20:25

**Preconditions**
The user is registered and logged in to the 'https://www.greencity.social/#/greenCity' website.
The 'My Space' page is opened.
The English language is chosen.
The ‘Edit photo’ mock-up link [edit photo](https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=13449-1612&mode=design&t=fvv6EDIe09WJTncW-4)

**Steps to reproduce**
1. Click the 'Edit Profile' icon
2. Click the 'Edit photo' icon
3. Open Devtools and choose the "576" extension
4. Pay attention to the text's alignment in the 'Do you want to change your profile picture?' pop-up

**Actual result**
The text's alignment is not matched to the mockup when the screen's extension is 576

**Expected result**
The "Would you like to save changes?" text is placed in one line according to the mockup when the screen's extension is 576

**User story and test case links**
[Test case GC-4678](https://jira.softserve.academy/browse/GC-4678)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

![576_act_do you want to change your profile picture_TEXT](https://github.com/ita-social-projects/GreenCity/assets/109147739/b05fb4ad-db1a-4f0b-bca4-20096af32071)
![576_mock-up_do you want to change your profile picture](https://github.com/ita-social-projects/GreenCity/assets/109147739/c29d0dac-6bc8-41df-b232-1ce0adb2ddc1)

**Comment by dijulya** [comment]
Verified on Windows 11 Pro, Chrome 122.0.6261.131
