### ISSUE TITLE
The View drop down for selecting the number of articles to display on 1 page is missing in the "Eco news" site section

### ISSUE THREAD

**Issue by TetianaShchupko** [ita-social-projects/GreenCity#6894]
**Environment:** Widows 10, Google chrome 109.0.5414.74 
**Reproducible:** always

**Steps to reproduce**

1. Go to 'https://www.greencity.social/#/news'
2. Pay attention to the right part of the body of the page

**Actual result**
The View drop down for selecting the number of articles on 1 page is missing in the "Eco news" section of the site
![2024-01-17_01-19-46](https://github.com/ita-social-projects/GreenCity/assets/153717519/0418574f-7646-4822-bfa1-95bfe601c47e)

**Expected result**
The View drop down for selecting the number of articles on 1 page is in the "Eco news" section of the site
<img width="124" alt="74139278-c3ad2400-4bfb-11ea-984a-a2b5f6d52a76" src="https://github.com/ita-social-projects/GreenCity/assets/153717519/58871c15-c6b4-4c89-9179-3668f34a3123">

**User story and test case links**
E.g.: "User story #457

**Comment by ViktoriyaRyazhska** [comment]
not a bug because infinity scroll is realized on this page
