### ISSUE TITLE
[Add Event Comment] The comment is displayed only after the event page is reloaded

### ISSUE THREAD

**Issue by KristinaKozyar** [ita-social-projects/GreenCity#6896]
**Environment:** Windows 11 Home version 22H2. Google Chrome Версія 120.0.6099.131
**Reproducible:** sometimes 
**Build found:**09.01.24

**Preconditions**
Precondition:

1.User1 is registered and authorized 
2. Event1 is exist
3. Comment for Event 1 is added by User1 or any another user
4. Event 1 card is opened

**Steps to reproduce**
1. Scroll to the 'Comments' block.
2.Enter the text in the "Add a comment" field

https://github.com/ita-social-projects/GreenCity/assets/151456775/3f93cb3b-ec9b-4acd-8615-cd21e010a5b9

![Знімок екрана 2024-01-11 173555](https://github.com/ita-social-projects/GreenCity/assets/151456775/3be0fa32-f4a3-4799-9140-8ec8a7f668c2)

3.Click on "Comment" button

**Actual result**
A comment isn't shown and the loader appears after adding it i on the Add comment block

**Expected result**
The comment is displayed on the screen. 

**User story and test case links**
"User story #4701

**Comment by snezhanapravdyuk** [comment]
User selection does not work when writing comments.

https://github.com/ita-social-projects/GreenCity/assets/165433958/ec6d3352-b5dd-4768-bb4e-e447267c201f
