### ISSUE TITLE
[Tagging in comment] Tagging appears when both "@" are entered simultaneously

### ISSUE THREAD

**Issue by KristinaKozyar** [ita-social-projects/GreenCity#6897]
![Знімок екрана 2024-01-07 134610](https://github.com/ita-social-projects/GreenCity/assets/151456775/8a85499f-272c-4779-b373-4f64dacfd14f)
![Знімок екрана 2024-01-07 134628](https://github.com/ita-social-projects/GreenCity/assets/151456775/3c19b4a1-aa09-45fd-986a-5d40db6c5383)
**Environment:** Windows 11 Home version 22H2. Google Chrome Версія 120.0.6099.131
**Reproducible:** always
**Build found:** 09.01.24

**Preconditions**
1. User 1 is logged in.
2. User 2 is authorized.
3. The Event with the ability to add a comment is open.

 

**Steps to reproduce**
User 1 click on the "Add a comment" field
User 1 types two the special character  @@
User 1 starts to type user 2 nickname

**Actual result**
The system displays  the input text as tagging

**Expected result**
The system does not recognize the input text as tagging

**User story and test case links**
"User story #4701

**Comment by OksanaFilipchuk** [comment]
if you choose user 2 from the dropdown the system displays his/her name as a tag. If you type text with the @ sign before the system proposes to choose a user from the dropdown. But if you don't click on the proposed user, the system doesn't add this user as a tag.

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/8d091e5d-a26f-47e8-899b-4848249cb2a7)
It's still the input text as tagging. + I can't press 'comment' until I renew the page by Enter
