### ISSUE TITLE
[Habit] Changes to the habit duration are not displayed after saving

### ISSUE THREAD

**Issue by NadiiaBedrii** [ita-social-projects/GreenCity#6898]
**Environment:** Windows 10, Opera 106, Chrome 120
**Reproducible:** always
**Build found:** 19.01.2024

**Preconditions**
The user is logged in [at https://www.greencity.social/;](https://www.greencity.social/#/greenCity)
The user has at least 1 habit in progress

**Steps to reproduce**
1. Go to 'My Space' page, my habits tab;
2. Click on a habit in progress;
3. Change duration of habit (e.g. from 14 days to 20 days);
4. Click the 'Save changes' button;
5. Click on the habit where modification of the duration was changed in steps 3-4;
6. Pay attention to the habit duration.

**Actual result**
The value of the duration is displayed as initial/standard (14 days) 

**Expected result**
The duration value of the habit is updated as modified to the new value (20 days).

**User story and test case links**
E.g.: "User story https://github.com/ita-social-projects/GreenCity/issues/1952 
[Test case][GC-8443](https://jira.softserve.academy/browse/GC-8443)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by kryzanivska-nastya** [comment]
Does not reproduce
