### ISSUE TITLE
[API]System allows creating news with empty ‘text’ field.

### ISSUE THREAD

**Issue by Vitaliipuchak** [ita-social-projects/GreenCity#690]
**Reproducible**: always
**Preconditions:**
1. Swagger https://greencity.azurewebsites.net/swagger-ui.html#/ is opened.
2. Log in as a registered user
3. Get token
4. Authorize
**Steps to reproduce:**
1. Click on 'eco-news-controller' drop down page;
2. Click on '/econews Add new eco news.' request;
3. Click "Try it out" button;
4. Edit request:
{
"tags": ["ads"],
"title": "TC_GC-600",
"text": "",
"source": "https://eco-lavca.ua/"
}
5. Click "Execute" button.
**Actual result:** News with empty ‘text’ field was created and added to DB.
**Expected result:**  News with empty ‘text’ field shouldn`t be created and added to DB. User should get an appropriative error message.
**User story:** #537 
**Test case:** https://jira.softserve.academy/browse/GC-600

**Comment by rsyvulko** [comment]
Verified.

**Comment by marjana07** [comment]
![news with empty title and text](https://user-images.githubusercontent.com/57389132/83630916-4be97780-a5a5-11ea-8677-1786848b6a94.png)

The defect is reproducible with Json: {
"tags": ["ads"],
"title": "TC_GC-600",
"source": "https://eco-lavca.ua/"
}
**If we don't set a key in Json this field has a null value, and the news is created.**
    {
      "creationDate": "2020-06-03T09:34:33.264Z",
      "imagePath": "https://storage.cloud.google.com/staging.greencity-c5a3a.appspot.com/caf60527-7a4f-4649-8650-ced4cea97822",
      "id": 726,
      "title": "TC_GC-600",
      "text": null,
      "source": null,
      "author": {
        "id": 154,
        "name": "MarJana"
      },
      "tags": [
        "ads",
        "events"
      ]
    }
