### ISSUE TITLE
The total number of comments does not match the number of displayed comments under the news

### ISSUE THREAD

**Issue by PohorielovaAnastasiia** [ita-social-projects/GreenCity#6902]
**Environment:** Windows 11 , Google Chrome 120.0.6099.217
**Reproducible:** always

**Steps to reproduce**
1. Go to https://www.greencity.social/#/news/1248
2. Scroll down to comments
3. Match the number of displayed comments under the news with the total number of comments
4. 
![b](https://github.com/ita-social-projects/GreenCity/assets/153717561/4f323472-5040-44ad-a813-3ad0cd53b9d0)

**Actual result**
The total number of comments does not match the number of displayed comments under the news.

**Expected result**
The total number of comments should match the number of displayed comments under the news.

**User story and test case links**
User story #461
Bug also reproduse at another news page https://www.greencity.social/#/news/1249
![u](https://github.com/ita-social-projects/GreenCity/assets/153717561/13f6a3c2-799e-48d9-a713-182e93a4a389)

**Labels to be added**
"Bug", Priority Low, Severity Medium, Type Functional

**Comment by Daria811** [comment]
The total number of comments doesn't match the number of displayed comments under the news.

![image](https://github.com/ita-social-projects/GreenCity/assets/165039674/795066ed-8bab-4d9d-9063-65d9233c973a)

**Comment by nuttaa0** [comment]
Still reproduced. 
Like here [https://www.greencity.cx.ua/#/news/1857](https://www.greencity.cx.ua/#/news/1857)
