### ISSUE TITLE
[API] System allow create news with less than 20 characters in ‘text’ field.

### ISSUE THREAD

**Issue by Vitaliipuchak** [ita-social-projects/GreenCity#691]
**Reproducible**: always
**Preconditions:**
1. Swagger https://greencity.azurewebsites.net/swagger-ui.html#/ is opened.
2. Log in as a registered user
3. Get token
4. Authorize
**Steps to reproduce:**
1. Click on 'eco-news-controller' drop down page;
2. Click on '/econews Add new eco news.' request;
3. Click "Try it out" button;
4. Edit request:
{
"tags": ["ads"],
"title": "TC_GC-600",
"text": "Магазин",
"source": "https://eco-lavca.ua/"
}
5. Click "Execute" button.
**Actual result:** News with less than 20 characters in 'text' field was created and added to DB.
**Expected result:**  News with less than 20 characters in 'text' field shouldn`t be created and added to DB. User should get an appropriative error message.
**User story:** #537 
**Test case:** https://jira.softserve.academy/browse/GC-601

**Comment by rsyvulko** [comment]
Verified.
