### ISSUE TITLE
[Header/Сhat]An unauthorized user can open a chat

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#6917]
**Environment:** Windows 10 Pro Version 22H2 OS 19045.3803 Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 03/02/2024

**Preconditions**
1.The site https://www.greencity.social/#/greenCity is opened.
2.The user is not authorized.

**Steps to reproduce**
1.Click on the 'Сhat' icon in the right corner on the header.

**Actual result**
The 'Chat' pop-up appears.

**Expected result**
The 'Sign In' pop-up appears.

**User story and test case links**
E.g.: "User story #558 
https://jira.softserve.academy/browse/GC-9025

**Comment by snezhanapravdyuk** [comment]
This bug is not relevant, in the upper right corner in the footer there is no chat icon for unauthorized users

**Comment by snezhanapravdyuk** [comment]
![изображение](https://github.com/ita-social-projects/GreenCity/assets/165433958/277e14fd-5fdb-425a-9898-dc7976928055)
