### ISSUE TITLE
[UBS client /New order] Inconsistent certificate rejection message

### ISSUE THREAD

**Issue by nina279** [ita-social-projects/GreenCity#6920]
**Environment:** 
macOS Sonoma 14.2.1 (23C71)
Chrome Version 121.0.6167.139 (Official Build) (arm64)

**Reproducible:** always
**Build found:** 31/12/2024

**Preconditions**
1. https://www.greencity.social/#/ubs is opened
2. User is signed in
3. Valid certificate is available

**Steps to reproduce**
1. Click on 'Замовити'
2. Add at least 2 packages of 120l
3. Add a valid certificate and push "Активувати".
4. Click on "Додати ще сертифікат"
5. Add a not-valid certificate (e.g. expired one or with a non-existent id number) and push "Активувати".

**Actual result**
A message, "Сертифікат не прийнято. Спробуйте ще раз" appears on all certificates, whether they are valid and already activated or invalid.

**Expected result**
A message, "Сертифікат не прийнято. Спробуйте ще раз" appears on non-valid certificates only

<img width="816" alt="Screenshot 2024-02-05 at 15 13 21" src="https://github.com/ita-social-projects/GreenCity/assets/111231614/3c70c539-697a-4412-8ff3-25ebc0a595be">
.

**Comment by snezhanapravdyuk** [comment]
![изображение](https://github.com/ita-social-projects/GreenCity/assets/165433958/5e069b1d-2b5d-4537-b525-14f2ec4a04d6)
