### ISSUE TITLE
[Comment. Reply] Original comment/reply is displayed together with edited comment/reply after user saves changes in the text 

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6930]
**Environment:** OS Windows 11Pro Version 22H2
Browser: Chrome Version 121.0.6167.86
**Reproducible:** always
**Build found:** 07.02.2024

**Preconditions**
1. The site GreenCity https://www.greencity.social/#/greenCity is opened
2. User is logged in
3. Event_1 is created 

**Steps to reproduce**
1. Click on "Events" tab
2. Click on 'More' button on the Event preview card
3. Add a comment
4. Click on the 'Edit' button below the comment
5. Edit the comment 
6. Click on the 'Save changes' button
7. Observe edited comment

Notes: The same behavior was observed during adding a reply. Also, this bug can be reproduced when adding a comment to news.

**Actual result**
Original comment displayed together with edited comment. If click on the 'Edit' button again and click the 'Save changes' button, the edited comment will be added to the already existing text of the comment.

https://github.com/ita-social-projects/GreenCity/assets/95030828/fa2541e4-b77e-43f8-ba58-614582da7602

**Expected result**
User can see only the edited text of the comment.

**User story and test case links**
E.g.: "User story #3208 #3211

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/068e63f5-05e3-4823-82d2-4b74ba3d9a5d)
  I see only edited comment. It's not a bug anymore.
