### ISSUE TITLE
[API]An event is created using only spaces in the title and description

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#6935]
**Environment:**Windows 10 Pro Version 22H2 OS 19045.3803 Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)
Postman Version 10.22.13
**Reproducible:** always
**Build found:** 08.02.24

**Preconditions**
1.The user is logged in  https://www.greencity.social/#/greenCity
2.Postman is opened 
3.Post request https://greencity-user.greencity.social/ownSecurity/signIn created
4.The token is gotten.

**Steps to reproduce**
1.Create a POST request  https://greencity.greencity.social/events/create
2. In authorization, select 'Bearer Token' and add a token.
3.Click the 'Body':
4. Select the radio button 'form-data'
5.Add the 'Key': addEventDtoRequest
6. Enter the 'Value': 
   {
    "title":"          ",
    "description":"                         ",
    "open":true,
    "datesLocations":[
        {
            "startDate":"2024-03-27T16:00:00Z",
            "finishDate":"2024-03-27T17:00:00Z",
            "onlineLink":"https://www.greencity.social/#/profile/1243"
        }
    ],
    "tags":["Economic"] }   
7. Сlick 'Save' button.
8. Click 'Send' button.

**Actual result**
Status : 201Created. 

**Expected result**
Status : 400 Bad Request

<img width="750" alt="Bug(only space)" src="https://github.com/ita-social-projects/GreenCity/assets/150814204/07ff1609-c089-4190-b2d4-d236894e1b44">
<img width="656" alt="Screenshot 2024-02-10 130230" src="https://github.com/ita-social-projects/GreenCity/assets/150814204/20a5992d-d9fa-4286-b5e0-f577133843f4">

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/60ad78eb-1e0f-421d-83cd-2c1e492da4ae)

**Comment by Roksana77** [comment]
It's OK now for Chrome 127.0.6533.100 (64-bit)

![image](https://github.com/user-attachments/assets/ae2af5c0-296f-4864-b550-02d314d0cefa)
