### ISSUE TITLE
API [Edit event] When we upload 5 images in 'Picture' it shows status 500

### ISSUE THREAD

**Issue by Tetiana1202** [ita-social-projects/GreenCity#6942]
Environment: 
MacOS 13.5.1
 Safari 
Postman (web application)

Reproducible: always

Build found: 11.02.2024

Preconditions: 
The user is logged in at https://www.greencity.social/;
The user has one created event 
Postman is opened and the token is gotten.
Steps to reproduce:

1. Create a PUT request to https://greencity.greencity.social/events/update
 Body:
{
"id": 2355,
"title": "Event with Pictures",
"titleImage": "https://csb10032000a548f571.blob.core.windows.net/allfiles/13c4752f-4928-4429-ab26-38cb5c3ab2c8%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202023-10-13%20%D0%BE%2018.23.07.png",
"additionalImages": [
"https://csb10032000a548f571.blob.core.windows.net/allfiles/7c313518-5c0e-4057-92e5-eda9338c542d%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202023-10-11%20%D0%BE%2016.40.36.png",
"https://csb10032000a548f571.blob.core.windows.net/allfiles/f3301eb6-8234-493c-850d-9e08a49a6b80%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202023-10-13%20%D0%BE%2012.25.37.png",
"https://csb10032000a548f571.blob.core.windows.net/allfiles/7c313518-5c0e-4057-92e5-eda9338c542d%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202023-10-11%20%D0%BE%2016.42.37.png",
"https://csb10032000a548f571.blob.core.windows.net/allfiles/f3301eb6-8234-493c-850d-9e08a49a6b80%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202023-10-13%20%D0%BE%2012.66.99.png"
],
"description": "<p>Some description</p>",
"dates": [
{
"id": null,
"event": null,
"startDate": "2024-02-09T19:00:21Z",
"finishDate": "2024-02-09T21:59:21Z",
"onlineLink": null,
"coordinates": {
"latitude": 49.89030393229213,
"longitude": 23.970619046029633,
"streetEn": null,
"streetUa": null,
"houseNumber": null,
"cityEn": "Bryukhovychi",
"cityUa": "Брюховичі",
"regionEn": "Lviv Oblast",
"regionUa": "Львівська область",
"countryEn": "Ukraine",
"countryUa": "Україна",
"formattedAddressEn": "VXRC+46 Bryukhovychi, Lviv Oblast, Ukraine",
"formattedAddressUa": "VXRC+46 Брюховичі, Львівська область, Україна"
}
}
]
}

2. Click on 'Send' button

Actual result: 
Status: 500. The 'Picture' has no image

Expected result: 
Status: 200. 5 Image is in 'Picture'

**Comment by Maryna-511750** [comment]
This bug is gone.
