### ISSUE TITLE
[Create Edit Event] The picture displayed on the Event is cropped

### ISSUE THREAD

**Issue by ViraM2301** [ita-social-projects/GreenCity#6955]
**Environment**:
11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz 3.19 GHz,
Windows 11 Pro release , 22H2
Chrome 120.0.6099.199 (Official Build), (64 bit)

**Reproducible**: always
**Build found**: 11.02.2024

**Preconditions**
1.The site https://www.greencity.social/#/greenCity is opened.
2.The User is logged-in.
3.The 'Events' tab is opened.
4.An event has been created

**Steps to reproduce**
1.Click 'Edit event' bttn on the 'Event'  card
2. Download pictures
3. Click 'Save event' bttn
4. Check how the image looks like in the card on the 'Events' page

**Actual result**
The picture displayed on the Event is cropped

**Expected result**
The picture is displayed in the 'Event' card correctly

**User story and test case links**
E.g.: "User story #3193 
[Test case](https://jira.softserve.academy/browse/GC-9034)"

**Labels to be added**
[Bug](https://github.com/ita-social-projects/GreenCity/labels/Bug)
[Create event](https://github.com/ita-social-projects/GreenCity/labels/Create%20event)
[Edit Event](https://github.com/ita-social-projects/GreenCity/labels/Edit%20Event)
[Event Preview](https://github.com/ita-social-projects/GreenCity/labels/Event%20Preview)
[event](https://github.com/ita-social-projects/GreenCity/labels/event)
[Events dashboard](https://github.com/ita-social-projects/GreenCity/labels/Events%20dashboard)
[Events](https://github.com/ita-social-projects/GreenCity/labels/Events)
[GreenCity](https://github.com/ita-social-projects/GreenCity/labels/GreenCity)
[GreenCityEvent](https://github.com/ita-social-projects/GreenCity/labels/GreenCityEvent)
[Pri: medium](https://github.com/ita-social-projects/GreenCity/labels/Pri%3A%20medium)
[Sev: trivial](https://github.com/ita-social-projects/GreenCity/labels/Sev%3A%20trivial)
[UI](https://github.com/ita-social-projects/GreenCity/labels/UI)

**Comment by ViraM2301** [comment]
![9034](https://github.com/ita-social-projects/GreenCity/assets/151033706/64863afb-64ea-461d-85e2-a1149c0777b6)

![ukr-16-serce](https://github.com/ita-social-projects/GreenCity/assets/151033706/0a206dff-47d8-417a-9a62-24f2191ab35e)

**Comment by dmytro-kryvyi** [comment]
It is impossible to always fit images without cropping or distortions. Instead I have added an opportunity to crop images by clicking on 'pencil' icon to crop as user wishes
