### ISSUE TITLE
[My space. Edit profile] Default icon for unknown social network appears when user adds links with "x.com" domain 

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/GreenCity#6977]
**Environment:** OS: Windows 11 Pro Version 22H2, Browser: Chrome Version 121.0.6167.185
**Reproducible:** always
**Build found:** 21.02.2024

**Preconditions**
1. The site GreenCity https://www.greencity.social/#/greenCity is opened
2. The User is logged in
3. The 'My Space" tab is opened

**Steps to reproduce**
1. Click on the 'Edit' button near the user`s avatar
2. In the 'Linked social networks' module click on the 'Add social network' button
3. Insert the link with the "x.com" domain, e.g. "https://x.com/narik_aliev?t=qwkm0GBVJMMgunjLMQLUKg&s=35" in the text field
4. Click the 'Add' button
5. Observe the icon of the added social network
6. Click on the 'Save' button to finish editing 
7. Observe the icon of the added social network that is indicated below the user`s avatar

**Actual result**
The default icon is displayed for "x.com" links
![image](https://github.com/ita-social-projects/GreenCity/assets/95030828/18e4d965-ffd6-4dae-b46a-2704fe59605f)

**Expected result**
The official icon of the "X" social network is displayed according to the mock-up
![image](https://github.com/ita-social-projects/GreenCity/assets/95030828/f66bbee5-bbb7-4b8e-9602-fb6d1d896538)

**User story and test case links**
 User story #4937

**Comment by Ihor21Vor** [comment]
The button "Save" is not clickable and it is impossible to finish editing and verify test case.
