### ISSUE TITLE
[Affected functionality] Clear and concise summary, e.g. "[Create news] 'Publish' button is not displayed on the 'Preview' page"

### ISSUE THREAD

**Issue by vladmorozov2** [ita-social-projects/GreenCity#6990]
**Environment:** Google Chrome
**Reproducible:** always

Frontend don`t show right data, according swagger what data sends backend

**Preconditions**
User should be logged 

**Steps to reproduce**
1. Go to event page
2. Click on "Status  ==> CREATED"

**Actual result**
![image](https://github.com/ita-social-projects/GreenCity/assets/130310750/99c08f26-aaaf-4e5c-9743-38966445015b)

**Expected result**
[response_1708923535356.json](https://github.com/ita-social-projects/GreenCity/files/14399857/response_1708923535356.json)

**Comment by bzhn** [comment]
Can't reproduce the bug.

![Image](https://github.com/user-attachments/assets/2942e0bc-6be8-4cfb-ba90-be9c2ca25d97)
