### ISSUE TITLE
[Create news]: Incorrect alignment at phone screen resolution

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#700]
**Environment:** iPhone 8, iOS  13.3.1, Google Chrome 81.0.4044.124 
**Reproducible:** always
**Build found:** commit b517ccb

**Preconditions:**
1. User is signed in
2. https://ita-social-projects.github.io/GreenCityClient/#/create-news is opened

**Steps to reproduce:**
1. Click on hamburger menu
2. Click on the 'Eco news' link.
3. Click on the 'Create news' button.

**Actual result:**
Incorrect alignment at phone screen resolution

![mob alignment 1](https://user-images.githubusercontent.com/64583209/82158359-097b2780-9890-11ea-9cb5-41f919929c60.jpg)
![mob alignment 2](https://user-images.githubusercontent.com/64583209/82126527-03187d00-97b6-11ea-8c46-3ecc2b7c3b24.jpg)
![iphone 3  ](https://user-images.githubusercontent.com/64583209/82126570-4d99f980-97b6-11ea-80b0-72c6d5df3159.jpg)

**Expected result:**
The alignment should be as on mock-up.

<img width="142" alt="320" src="https://user-images.githubusercontent.com/64583209/82126603-6bfff500-97b6-11ea-9c0b-975d1003fe63.png">

User story: #505

**Comment by MariaKorniavka** [comment]
not fixed 


![2](https://user-images.githubusercontent.com/64583209/83130550-282abb00-a0e7-11ea-8944-839de8527b45.jpg) 


![1](https://user-images.githubusercontent.com/64583209/83130545-2660f780-a0e7-11ea-829d-997e433c94e3.jpg)

**Comment by MariaKorniavka** [comment]
Not Fixed

**Comment by JustinCooper43** [comment]
Bug was not fixed.
![Create news](https://user-images.githubusercontent.com/64972476/91214968-7cf8c480-e71c-11ea-8ea3-2194e4d28bcd.jpg)
