### ISSUE TITLE
[UBS/order] The number of packages is reset to zero after a change of location

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#7004]
**Environment:** Windows 10 Pro Version 22H2 OS 19045.3803 Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 03/03/2024

**Preconditions**
1.The site https://www.greencity.social/#/ubs is opened.
2.The user is authorized.
3. The 'order' button is clicked.

**Steps to reproduce**
1. Set the number of packages.
2. Click on the 'Change your location'
3.Click on the dropdown and change location.
4.Click 'Continue' button.

**Actual result**
The set number of packets has changed to 0.

**Expected result**
The set number of packets does not change.

**User story and test case links**
E.g.: "User story #3033 #2379

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by dmytro-kryvyi** [comment]
Not a bug.  After a change of location, all bags are changed. They can have the same name, but this is not necessary, they have different id, validation and cost. I also don't see such a requirement in the user stories.
