### ISSUE TITLE
[UBS/order]The user can enter more than 255 characters in the 'Comment to the address' field.

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#7005]
**Environment:** Windows 10 Pro Version 22H2 OS 19045.3803 Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)
Reproducible: always
Build found: 03/03/2024

**Preconditions:**
1.The site https://www.greencity.social/#/ubs is opened.
2.The user is authorized.
3. The 'order' button is clicked.
4. The number of packages entered.
5. The 'Next' button is clicked.

**Steps to reproduce:**
1.Write or paste more than 255 characters in the 'Comment to the address' field.

**Actual result**
The field is highlighted in blue, and the user can continue entering characters.

**Expected result**
The field is highlighted in red, and the user cannot continue entering characters.

Labels to be added
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![photo_2024-03-03_12-06-13 (2)](https://github.com/ita-social-projects/GreenCity/assets/150814204/d3d4c876-e26c-41b6-960e-df78c44601b7)
![photo_2024-03-03_12-06-13](https://github.com/ita-social-projects/GreenCity/assets/150814204/19f58250-8818-44ab-8c10-f21cbf86e20c)

**Comment by dmytro-kryvyi** [comment]
Same as #7006 but also add an red border if textarea is invalid.
