### ISSUE TITLE
[UBS/order]The user can enter more than 255 characters in the 'Comment to the address' field on the 'New address' popup.

### ISSUE THREAD

**Issue by MariiaShtraisel** [ita-social-projects/GreenCity#7006]
**Environment:** Windows 10 Pro Version 22H2 OS 19045.3803 Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)
Reproducible: always
Build found: 03/03/2024

**Preconditions:**
1.The site https://www.greencity.social/#/ubs is opened.
2.The user is authorized.
3. The 'order' button is clicked.
4. The number of packages entered.
5. The 'Next' button is clicked.
6. 'Add another address' button is clicked.

**Steps to reproduce:**
1.Type address.
2.Write or paste more than 255 characters in the 'Comment to the address' field.

**Actual result**
The field is highlighted in blue-red, and the user can continue entering characters.

**Expected result**
The field is highlighted in red, and the user cannot continue entering characters.

Labels to be added
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
![photo_2024-03-03_12-06-13 (3)](https://github.com/ita-social-projects/GreenCity/assets/150814204/c28eecb7-eb70-4dcd-a68b-c0f665dc9942)
![photo_2024-03-03_12-06-13 (4)](https://github.com/ita-social-projects/GreenCity/assets/150814204/2b89a6c9-0c3b-4940-87b2-51150ee35d21)

**Comment by dmytro-kryvyi** [comment]
I will remove the blue highlight in case of an error, but there is no need to limit the input. The user can enter more than 255 characters and then a message will appear that the comment is not valid. If you limit the input to 255 characters, the user will never see a validation message.
