### ISSUE TITLE
[UBS] An authorized user who entered the Certificate number cannot erase it using the 'Backspace' key

### ISSUE THREAD

**Issue by Tetiana1202** [ita-social-projects/GreenCity#7007]
Environment: MacOS 13.5.1 (22G90), Google Chrome  122.0.6261.94
Reproducible: always
Build found: 04.03.2024

Preconditions:
1. Open https://www.greencity.social/#/ubs
2. The user is authorized
3. the 'UBS Courier' page is open

Steps to reproduce:
1. Enter 'Mix waste 120l ' in the field e.g. '2'
2. Enter 'Textile waste 20l ' in the field e.g. '1'
3. Enter 'Textile waste 60l  ' in the field e.g. '1'
4. fill in the 'Certificate number' field e.g. '1234-5678'
5. Click on 'Activate' 
6. Click on the field 'Certificate number' and press the key 'Backspace'

Actual result:
1. The symbols remain in the field 'Certificate number'

Expected result:
1. Symbols are erased in the field 'Certificate number'

**Comment by vladmorozov2** [comment]
It looks okay to me,user can click on "Cancel" button

**Comment by vladmorozov2** [comment]
Close issue or clarify a little bit more what you want

**Comment by Tetiana1202** [comment]
> Close issue or clarify a little bit more what you want

The user cannot erase a character that he entered incorrectly.
