### ISSUE TITLE
[UBS] [Order form] Adding addresses located further than 20 kilometers from Kyiv is allowed in the “Garbage collection address ” block

### ISSUE THREAD

**Issue by OlenaKhita** [ita-social-projects/GreenCity#7008]
**Environment:** Windows 10 Pro Google Chrome 109.0.5414.168.
**Reproducible:** always
**Build found:** 04/03/2024
**Preconditions**
1. User_1 is logged in
2. "UBS Courier" page is opened 

**Steps to reproduce**
1. Scroll to "Garbage collection address" block
2. Click on 'Add address'/'Add add another address' bttn
3. Fill in the "City" field with any city of the Kyiv region located further than 20 km from Kyiv (e.g Irpin)
4. Fill in all mandatory fields with valid data
5. Click on 'Add address' bttn

**Actual result**
The entered address is accepted. The address with the disabled radiobutton is displayed in the "Garbage collection address" block

**Expected result**
The entered address is not accepted. The error message that user have to select another city is displayed

**User story and test case links**
"User story #2199

**Comment by dmytro-kryvyi** [comment]
Not a bug. The user can add any address anywhere in the world, but this address cannot be selected for placing an order if it is not included in the selected tariff. Validation for 20 km for the region is currently under development and has not been implemented yet.
