### ISSUE TITLE
[UBS/Order form] User is not redirected to the payment page when trying to pay for a saved order

### ISSUE THREAD

**Issue by OlenaKhita** [ita-social-projects/GreenCity#7010]
**Environment:** Windows 10 Pro Google Chrome 109.0.5414.168.
**Reproducible:** always
**Build found:** 05/03/2024

**Preconditions**
1. User_1 is logged in
2. User_1 data is registered, according to UBS Courier requirements 
3. User_1's order is created and saved

**Steps to reproduce**
1. Go to UBS-USER cabinet
2. Go to your order
3. Click on 'Pay' bttn
4. Confirm Order details clicking on 'Next' bttn
5. Confirm Personal data clicking on 'Next' bttn
6. Click on 'Pay' bttn
**Actual result**
The message "Oops, something went wrong" is shown. User is not redirected to the payment page 

**Expected result**
User is redirected to the payment page when after clicking on 'Pay' bttn for on a saved order

https://github.com/ita-social-projects/GreenCity/assets/150794535/09f472c4-1290-4745-b2ee-0522ef15a02b

**User story and test case links**
E.g.: "User story #3491 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by dmytro-kryvyi** [comment]
Does not reproduce. Propably fixed with #6992.
