### ISSUE TITLE
[UBS] Authorized user in 'Personal data' can specify 'Name' and 'Surname' only one letter

### ISSUE THREAD

**Issue by Tetiana1202** [ita-social-projects/GreenCity#7013]
Environment: MacOS 13.5.1 (22G90), Google Chrome 122.0.6261.94
Reproducible: always
Build found: 06.03.2024

Preconditions:
1. Open https://www.greencity.social/#/ubs
2. The user is authorized
3. The 'Order details' page is filled out correctly

Steps to reproduce:
1. Go to 'Personal data'
2. Specify in the 'Name' field e.g. 'A'
3. In the 'Surname' field, specify e.g. 'F'

Actual result:
1. The 'Name' and 'Surname' fields are not highlighted in red.

Expected result:
1. The 'Name' and 'Surname' fields are highlighted in red

**Comment by dmytro-kryvyi** [comment]
Not a bug. According to change request #2198 to user story #2195 the minimal length of name and surname should be 1 and maximal - 30.
