### ISSUE TITLE
The user cannot 'Sign in with Google' account

### ISSUE THREAD

**Issue by Tetiana1202** [ita-social-projects/GreenCity#7016]
Environment: MacOS 13.5.1, Google Chrome 122.0.6261.94
Reproducible: always
Build found: 08.03.2024

Preconditions:
1. Open: https://www.greencity.social/#/greenCity
2. The user is not authorized

Steps to reproduce:
1. Click on 'SIGN IN' button
2. Click on 'Sign in with Google' button

Actual result:
1. The button 'Sign in with Google'  is not active

Expected result:
1. A Google authorization window will appear

**Comment by Maxv1z** [comment]
Duplicate of this one https://github.com/ita-social-projects/GreenCity/issues/6708
