### ISSUE TITLE
[Create news] Text content flows outside the modal window if user enter text without any spaces

### ISSUE THREAD

**Issue by OlesiaSolovii** [ita-social-projects/GreenCity#702]
Environment: macOS Catalina, Version 10.15.4 (19E287),
Google Chrome, Version 81.0.4044.129
Build found: commit 7439e88
Reproducible: always

**Steps to reproduce:**

1. Sign in on Green City [https://ita-social-projects.github.io/GreenCityClient/#/news].
2. Click on 'Eco News' link.
3. Click on 'Create news' button.
4. Fill in 'Title' field (e.g. 100 symbols **without any spaces**).
5. Fill in 'Content' field (e.g. 300 symbols **without any spaces**).
6. Click on "Preview" button.

**Actual result** 
Text content flows outside the modal window.
<img width="1679" alt="Screen Shot 2020-05-17 at 1 21 31 PM" src="https://user-images.githubusercontent.com/64583001/82142229-774d3200-9843-11ea-9387-0906b2a0c2a1.png">

**Expected result**
Text content in "Title" and "Content" fields  should not flow outside the modal window.

User story #526
Test case https://jira.softserve.academy/browse/GC-633

**Comment by rsyvulko** [comment]
Duplicate
https://github.com/ita-social-projects/GreenCity/issues/578
