### ISSUE TITLE
[UBS] [Order] An error message is shown on the "New address" page if letters are entered in the "Entrance" field

### ISSUE THREAD

**Issue by OlenaKhita** [ita-social-projects/GreenCity#7023]
**Environment:** Windows 10 Pro Google Chrome 109.0.5414.168.
**Reproducible:** always
**Build found:** 15/03/2024

**Preconditions**
1. User_1 is logged in
2. "UBS Courier" page is opened
3. User_1's order details are filled with valid data

**Steps to reproduce**
1. Go to the "Personal data" block on the "UBS Courier" page
2. Scroll to the "Garbage collection address" block
3. Click on "Add another address"/"Add address" bttn
4. Fill the field in "New address" window with valid data
5.  Enter any letter in the "Entrance" field

**Actual result**
An error message "Only numbers are allowed" is shown under "Entrance" field. However, the "Add address" button becomes active. The user is allowed to create this address
![Screenshot_45](https://github.com/ita-social-projects/GreenCity/assets/150794535/0af5a8e7-ef04-4601-97da-11a520d58807)

**Expected result**
An error message "Only numbers are allowed" isn't shown under "Entrance" field if user add letters in the field.

**User story and test case links**
E.g.: "User story #2199

**Comment by snezhanapravdyuk** [comment]
An error message "Only numbers are allowed" is shown under "Entrance" field if user add letters in the field.

**Comment by snezhanapravdyuk** [comment]
![изображение](https://github.com/ita-social-projects/GreenCity/assets/165433958/99c0e217-2ba2-469e-82d6-123b58aff512)
