### ISSUE TITLE
[UBS] Ukrainian and English languages in street names are switched when user adding Garbage collection address on the English version of the site

### ISSUE THREAD

**Issue by OlenaKhita** [ita-social-projects/GreenCity#7028]
**Environment:** Windows 10 Pro Google Chrome 109.0.5414.168.
**Reproducible:** always
**Build found:**18/03/2024

**Preconditions**
1. User_1 is logged in
2. "UBS Courier" page is opened
3. User_1's order details are filled with valid data
4. The English language page version is choosen

**Steps to reproduce**
1. Go to the "Personal data" block on the "UBS Courier" page
2. Scroll to the "Garbage collection address" block
3. Click on "Add another address"/"Add address" bttn
4. Fill the field in "New address" window with valid data 
(e.g. city Kyiv  
Pecherskyi district   
Vasylia Tiutiunnyka Street, house 7,
Kyiv Oblast)
5. Click on "Add address" bttn

**Actual result**
The name of the street is displayed in Ukrainian. When changing the language to Ukrainian, the street name is translated to English
![Screenshot_50](https://github.com/ita-social-projects/GreenCity/assets/150794535/42b1c486-b069-477a-a261-4afe06518a1a)

**Expected result**
The name of the street is displayed in English on the English version of the site

**User story and test case links**
E.g.: "User story #2199

**Comment by dmytro-kryvyi** [comment]
Fixed [#2947](https://github.com/ita-social-projects/GreenCityClient/pull/2947)

**Comment by Daria811** [comment]
The name of the street is displayed in Ukrainian on the English localization. 
![image](https://github.com/ita-social-projects/GreenCity/assets/165039674/9a8f0f14-8684-47aa-9512-d2aa6e4d562e)
The name of the street is displayed in English on the Ukrainian localization. 
![image](https://github.com/ita-social-projects/GreenCity/assets/165039674/47bff5b8-2ad5-42d8-baef-83e72f7aeb8e)
