### ISSUE TITLE
[Create Event] The error message is not appeared under the ''Date" field after entering the past date.

### ISSUE THREAD

**Issue by kulaira** [ita-social-projects/GreenCity#7039]
**Environment:** Windows 10, Google Chrome 123.0.6312.86 (64-bit).
**Reproducible:** always.
**Build found:** 04.04.2024.

**Preconditions**
1. GreenCity site is opened https://www.greencity.cx.ua/#/greenCity.
2. Authorized user is logged in.
3. "Events" page is opened.

**Steps to reproduce**
1. Click on the ''Create event" button.
2. Enter the past date 12/31/2023 manually in the "Date" field.

**Actual result**
The error message is not appeared under the ''Date" field, the "Date" field is highlighted in red.
![image](https://github.com/ita-social-projects/GreenCity/assets/157893084/177cffc8-ac8b-4290-bbb4-951b3f3ad2ac)

**Expected result**
The error message "Past date can't be chosen" is displayed under the "Date" field and the "Date" field is highlighted in red.

**User story and test case links**
E.g.: "User story #3193, #4231
[Test case](https://jira.softserve.academy/browse/GC-3166)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by yuliiakaras** [comment]
It seems like this bug have been resolved


![Image](https://github.com/user-attachments/assets/057b0262-1808-465f-bb4e-c7a9214863c0)
