### ISSUE TITLE
[View event preview card] System doesn’t redirect to Event details page, when user clicks on the button “Join event”

### ISSUE THREAD

**Issue by Ihor21Vor** [ita-social-projects/GreenCity#7040]
**Environment:** Windows 11 Home 22H2, Opera One(version: 108.0.5067.29
**Reproducible:** always.
**Build found:** 02.04.2024

**Steps to reproduce**
1. Go to the Website  https://www.greencity.social/#/greenCity .
2. Sign in as a user 
3. Click on the button "Events".
4. Click on the "Join Event" button

**Actual result**
System doesn’t redirect user to the  Event details page and shows the same page.

**Expected result**
System redirects User to  Event details page.

**User story and test case links**
E.g.: "User story #3374,  #5006
[Test case] https://jira.softserve.academy/browse/GC-9096

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by ViktoriyaRyazhska** [comment]
not a bug
