### ISSUE TITLE
[View Event Preview Card] System doesn't show a popup with the message text "Are you sure that you don't want to join this event?" when attendee wants to unjoin

### ISSUE THREAD

**Issue by Ihor21Vor** [ita-social-projects/GreenCity#7041]
**Environment:** Windows 11 Home, Opera One(version: 109.0.5097.38)
**Reproducible:** always.
**Build found:** 02/04/2024

**Preconditions**
User is signed in.
User should be member to one of the event. 

**Steps to reproduce**
1. Go to the Website  https://www.greencity.social/#/greenCity.
2. Scroll to the event of which the user is a member.
3. Click on the Cancel Request button on the Event Preview Card.

**Actual result**
Page doesn't reload when user clicks on Cancel request button.

**Expected result**
System show a popup with the message text "Are you sure that you don't want to join this event?"

**User story and test case links**
E.g.: "User story #3374, #5006
[Test case] https://jira.softserve.academy/browse/GC-9096
**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Roksana77** [comment]
I can't even join the event. (Chrome 127.0.6533.100 (64-bit)

![image](https://github.com/user-attachments/assets/45b2e924-3ce1-47a7-ae07-267a70fe107a)

In 1 mn it's ok. It's not a bug. The message text "Are you sure that you don't want to join this event?" is displayed when attendee wants to unjoin.

![image](https://github.com/user-attachments/assets/8b1e6347-0187-4e03-9660-e4d159e72386)
