### ISSUE TITLE
[Create Event] Incorrect Start time displayed when 'All day' checkbox is activated

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7043]
**Environment:** Windows 10 Pro for Workstations, Google Chrome 123.0.6312.86 (64-bit)
**Reproducible:** always
**Build found:** 02/Apr/24

**Preconditions**

1. Go to https://www.greencity.social/#/greenCity 
2. Log in as an authorized user.
3. The 'Events' page is opened.

**Steps to reproduce**

1. Go to https://www.greencity.social/#/events/create-event
2. Check the checkbox "All day"

**Actual result**
Start time default value is current time + 1 hour

**Expected result**
 "Start Time" default value is 00:00

**User story and test case links**
E.g.: "User story #5123 
[Test case](https://jira.softserve.academy/browse/GC-8879)"
![StartDate_Actual](https://github.com/ita-social-projects/GreenCity/assets/24385480/f9d26568-6298-4f86-89c0-22f36f8a9c11)
![StartDate_Expected](https://github.com/ita-social-projects/GreenCity/assets/24385480/580bdcb4-5d09-4f6c-aecf-a2c1f0f1faea)

**Comment by Maxv1z** [comment]
https://github.com/ita-social-projects/GreenCity/assets/122612827/b0f86c77-0e31-452b-a4e0-4909a007f664

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/e71e4835-7307-492d-a32d-5c0c9e641c4e)

It's 00:00 on Chrome 127.0.6533.100 (64-bit)
