### ISSUE TITLE
[Tagging in comment] User does not receive a notification about tagging on E-mail.

### ISSUE THREAD

**Issue by Nastya1403** [ita-social-projects/GreenCity#7045]
**Environment:** Windows 11 Home, Google Chrome 123.0.6312.86 (Official Build) (64-bit).
**Reproducible:** sometimes.
**Created:** 07.04.2024

**Preconditions**
1. Go to https://www.greencity.social/#/events.
2. User 1 is logged in.
3. User 2 is authorized.
4. The Event is created.

**Steps to reproduce**
1. Tab on the button "More" under the Event.
2. Tag User 2 using special character @ in comments.
3. Click "Comment" button.

**Actual result**
User 2 did not receive the notification about tagging on E-mail.
https://github.com/ita-social-projects/GreenCity/assets/61518116/4d5313dd-c19f-4785-b42a-9f6dda72904b

**Expected result**
User 2 received the notification about tagging on E-mail.

**User story and test case links**
User story #4701 
[Test case](https://jira.softserve.academy/browse/GC-6380)

**Comment by nuttaa0** [comment]
Issue still reproduces. Some users received notifications, but some don't.

**Comment by holotsvan** [comment]
Emails are send. 
![Image](https://github.com/user-attachments/assets/31467b22-04e8-4598-8103-42831042dbbe)

Make sure that
 ![Image](https://github.com/user-attachments/assets/f289153c-e0be-41dd-9b58-06e3745b48bf)

**Comment by OlegDemkiv10** [comment]
there is no way to tag another user 

https://github.com/user-attachments/assets/caeb5b80-286c-4e07-a318-71cae3df4970
