### ISSUE TITLE
[API] PUT/user/profile Error 401 pops up when requesting with invalid params

### ISSUE THREAD

**Issue by lukovskyj** [ita-social-projects/GreenCity#7080]
During the resolution of task [#4966](https://github.com/ita-social-projects/GreenCity/issues/4966), a bug was discovered.

**Preconditions**

Authorize according to [Swagger_istruction](https://github.com/ita-social-projects/GreenCity/wiki/Swagger-Configuration).

Steps to reproduce

try **PUT/user/profile**

Enter value  - {
  "showLocation": true,
  "showEcoPlace": true,
  "showShoppingList": true,
  "coordinates": {
    "latitude": 0,
    "longitude": 0
  }
}
   
Actual result
401 Unauthorized

![pict5](https://github.com/ita-social-projects/GreenCity/assets/73854494/77768f31-9ced-4dad-804c-f1fe565f093f)

Expected result

Code 404appears in response.

**Comment by SvitlanaRadkevych** [comment]
The bug is reproduced with code 400.
Expected result
Code 404appears in response.
![user_profile](https://github.com/ita-social-projects/GreenCity/assets/165490180/087f6de9-f510-49ad-b2f2-2de15f33ba4f)

**Comment by lukovskyj** [comment]
Sorry, I made a mistake in the task description. Requesting endpoints with invalid parameters should return a `400 Bad Request` status, not a `404 Not Found` as I described in the "Expected result" section. Therefore, if the bug was resolved correctly, the response should be `400 Bad Request` for invalid parameters, as @SvitlanaRadkevych mentioned in her comment.

> The bug is reproduced with code 400. Expected result Code 404appears in response. ![user_profile](https://private-user-images.githubusercontent.com/165490180/346271809-087f6de9-f510-49ad-b2f2-2de15f33ba4f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTcwOTEsIm5iZiI6MTcyNjY1Njc5MSwicGF0aCI6Ii8xNjU0OTAxODAvMzQ2MjcxODA5LTA4N2Y2ZGU5LWY1MTAtNDlhZC1iMmYyLTJkZTE1ZjMzYmE0Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMDUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTE0ZWNlMDIzN2FkNWIwNmNlYmVjMWYxMzRhNjVkYTNiMjE1NDJiNTA3OGNkODViYzhkN2VmODRkMTk5MGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mLEYyV8_95MAtWFfEsUuA5U2CHak5nPO0XEnyuyzGTs)
