### ISSUE TITLE
GrencityUBS endpoint GET /ubs/superAdmin/tariffs returns 401 status code

### ISSUE THREAD

**Issue by ryhaldenys** [ita-social-projects/GreenCity#7088]
When a user logged in as a superAdmin tries to filter tariffs by region, location, receiving station, or courier, using GET /ubs/superAdmin/tariffs,  they receive a 401 response status.

**Comment by snezhanapravdyuk** [comment]
![изображение](https://github.com/user-attachments/assets/426c6513-35ea-4310-96a1-195a541222b2)
