### ISSUE TITLE
[Create news] Current user's name is not displayed on the 'Preview' page

### ISSUE THREAD

**Issue by traviscolt** [ita-social-projects/GreenCity#710]
**Environment:** Windows 8.1 x64, Mozilla Firefox 76.0 (64-bit),  Google Chrome
Версія 81.0 (64-bit)
**Reproducible:** always
**Build found:** commit b517ccb

**Steps to reproduce:**

1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click on 'Create news' button.
5. Enter valid values in 'Title' text field and 'Content' text field
6. Click the 'Preview' button

**Actual result:**
Current user's name is not displayed on the 'Preview' page
![Screenshot_9](https://user-images.githubusercontent.com/35031131/82154950-fcebd480-9879-11ea-932d-a5e9cdf6abb3.jpg)

**Expected result:**
Current user's name is displayed on the 'Preview' page

User story #505

**Comment by rsyvulko** [comment]
Verified.
