### ISSUE TITLE
[UBS Admin table] After select 'Скасовано' status in admin table pop-up apear out of monitor

### ISSUE THREAD

**Issue by korbantyk** [ita-social-projects/GreenCity#7103]
**Environment:**  ОС Windows 10 Version 22H2 для систем на базі x64-процесорів (KB5036979),Chrome Версія 124.0.6367.119
**Reproducible:** always
**Build found:** Prod

**Preconditions**
1.User is logged in as administrator https://www.pick-up.city/#/ubs

**Steps to reproduce**
1. Go to https://www.pick-up.city/#/ubs admin table
2. Click on 'Замовлення'
3. Select  'Скасовано' status in any order 

**Actual result**

https://github.com/ita-social-projects/GreenCity/assets/51170284/bba03ad4-74ac-48b2-bed7-0e25e37c0138

Pop-up apear out of monitor

**Expected result**
Pop-up “Додати причину скасування замовлення” apear.

**User story and test case links**
E.g.: "User story #3190 #3192

**Comment by 111natalies** [comment]
Pop-up “Додати причину скасування замовлення”  doesn't apear after selecting  'Скасовано' status in any order.
