### ISSUE TITLE
[Test environment. Admin cabinet. Orders] The 'Статус замовлення' column isn't sorted in alphabetical order “А”-”Я” / “Я”-”A” in the Order table with Ukrainian localization #7095

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7104]
**Environment:** Windows 10 Pro for Workstations, Google Chrome 124.0.6367.93
**Reproducible:** always
**Build found:** 06 May 2024 (test)

**Preconditions**

1. Log in as Admin https://www.greencity.social/#/ubs-admin/orders
2. Ukrainian localization is chosen.
3. Filter by payment status 'Оплачено' in the column 'Статус оплати' is applied.

**Steps to reproduce**

1. Click on the arrow icon near the column heading 'Статус замовлення' to sort in "А-Я" оrder. Pay attention to the sorting in the column.
2. Click on the arrow icon near the column heading in the 'Статус замовлення' to sort it in "Я-А" оrder. Pay attention to the sorting in the column.

**Actual result**
After the first click on arrow icon the items in the column are sorted in reverse alphabetical order ”Я”-“А” and arrow icon points upward. After the second click on arrow icon the items are sorted in alphabetical order ”А”-“Я” and arrow icon points downward.

![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/264845eb-4b74-454d-9026-eb1b89909e7c)
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/f87acac3-12ab-4858-a8cb-4f578c8abbef)

**Expected result**
After the first click on arrow icon the items in the column should be sorted in alphabetical order “А”-”Я” and arrow icon should point downward, status 'Виконано' is shown first, 'Узгодження' is shown last. After the second click on arrow icon the items should be sorted in reverse alphabetical order ”Я”-“А” and arrow icon points upwards, status 'Узгодження' is shown first, 'Виконано' is shown last. 

**User story and test case links**
#3336 
[Test case]https://jira.softserve.academy/secure/enav/#/59671

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by ViktoriyaRyazhska** [comment]
Dublicate #5527

**Comment by lukovskyj** [comment]
https://github.com/ita-social-projects/GreenCity/issues/5527 -> PickUp City, https://github.com/ita-social-projects/GreenCity/issues/7104 -> dev
