### ISSUE TITLE
[Pick up City. Admin cabinet. Orders] The 'Час вивезення' column isn't sorted in asc. order based on first HH\MM in range

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7107]
**Environment:** Windows 10 Pro for Workstations, Firefox 126.0b8 (32-bit)
**Reproducible:** always
**Build found:** 06 May 2024 (test)

**Preconditions**

1. Log in as Admin https://www.greencity.social/#/ubs-admin/orders
2. Ukrainian localisation selected.
3. Filter by 'half-paid' Payment status is appllied.

**Steps to reproduce**
1. Click on the arrow icon near the column heading 'Час вивезення' to sort in desc. order based on first HH\MM in range. Pay attention to the sorting in the column.
Click again on the arrow icon near the column heading 'Час вивезення' to sort in asc. order based on first HH\MM in range. Pay attention to the sorting in the column.

**Actual result**
After the first click on arrow icon the items in the column are sorted asc. order based on first HH\MM in range.
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/daa8a183-55c3-42b2-ba9a-8fd5aee41e19)
After the second click the items in this column are sorted in descending order  based on first HH\MM in range.
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/a6ee65b2-69ea-4af6-afb6-2e990f3a3cdb)

**Expected result**
 After the first click on arrow icon the items to be sorted in desc. order based on first HH\MM in range. After the second click on arrow icon the items to be sorted in asc. order based on first HH\MM in range. 

**User story and test case links**
#3336 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by lukovskyj** [comment]
I tried to reproduce the bug. Here's what I found:

1. Logged in as admin, ua  language, filtering by payment status.
![зображення](https://github.com/user-attachments/assets/78c5c1d3-bbc8-445f-95a3-4b3c47ef9ff6)

2. First click on the sorting arrow for the "Час вивезення" column:
![зображення](https://github.com/user-attachments/assets/45ed30fa-272b-4c9a-9daa-a62f1ca5172d)
       Column sorted in descending order based on first HH\MM in range.

3. Second click on the sorting arrow:
![зображення](https://github.com/user-attachments/assets/35d6db1c-1d26-43cd-9047-804165830e22)

**Bug did not reproduce.**


_P.S. Ascending sorting first shows all results with an empty "Час вивезення" column value, and it's normal behavior for the table and database._

**Comment by lukovskyj** [comment]
Update.
This  [PR 1529](https://github.com/ita-social-projects/GreenCityUBS/pull/1529) places null value elements at the end of the sorted list.
