### ISSUE TITLE
[Pick up City. Admin cabinet. Orders]  Missing filter for column 'Область'

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7111]
**Environment:** Windows 10 Pro for Workstations, Google Chrome 124.0.6367.93
**Reproducible**: always
**Build found**: 08 May 2024 (prod and test)

**Preconditions**

1. Log in as Admin https://www.pick-up.city/#/ubs-admin/orders 
2. Log in as Admin https://www.greencity.social/#/ubs-admin/orders

**Steps to reproduce**
1. Go to column 'Область'
2. Pay attention to missing filter

**Actual result**
No filter icon for column 'Область' is displayed
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/6547aef9-a83a-4b63-959c-730de86274c4)

**Expected result**
Admin can click filter icon in 'Область' column, after that pop-up window is shown with the selection of checkboxes based on information entered in existing orders

**User story and test case links**
#3300 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by dmytro-kryvyi** [comment]
No data from back-end (field checked) to sort by

GET https://greencity-ubs.greencity.social/ubs/management/tableParams

![image](https://github.com/ita-social-projects/GreenCity/assets/94367438/d409626a-d5d8-44a6-afe6-2a6616dc28e5)

**Comment by lukovskyj** [comment]
Currently, the column's been added for dev. It'll be added for prod soon.
