### ISSUE TITLE
[Pick up City. Admin cabinet. Orders] Equals option is missing for 'Дата замовлення', 'Дата оплати', 'Дата вивезення'

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7112]
**Environment:** Windows 10 Pro for Workstations, Firefox 126.0b9 (32-bit)
**Reproducible:** always
**Build found**: 08 May 2024 (prod and test)

**Preconditions**

1. Log in as Admin https://www.pick-up.city/#/ubs-admin/orders
2. Log in as Admin https://www.greencity.social/#/ubs-admin/orders

**Steps to reproduce**
1. Go to column 'Дата замовлення'.
2. Pay attention to missing option Equals to select specific date 
3. Select 'Date range' checkbox. Pay attention to filtering is done without any date range selected.
4. Go to column 'Дата оплати'.
5. Pay attention to missing option Equals to select specific date.
6. Select 'Date range' checkbox. Pay attention to filtering is done without any date range selected.
7. Go to column 'Дата вивезення'.
8. Pay attention to missing option Equals to select specific date.

**Actual result**
No option is displayed to select specific order date or payment date
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/491813e0-4d16-42b0-b7f1-c940ea280fb1)
When 'Date range' checkbox is activated filtering is done without any date selected
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/5aab613f-b4af-41d7-a2fb-719f9da3fde8)

**Expected result**
In filter pop-up window the option Equals is shown. When this option is chosen the user should be able to select a specific date

**User story and test case links**
#3300 
[Test case](https://jira.softserve.academy/browse/GC-9160)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Daria811** [comment]
The filter doesn't work when the Admin selects the date range. 

https://github.com/ita-social-projects/GreenCity/assets/165039674/62a7cc0b-dc7e-4de7-a687-dc209e8ec2ba
