### ISSUE TITLE
[Admin cabinet. Orders] Buttons 'Застосувати' and 'Скасувати' are displayed when no filter items selected

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7115]
**Environment:** Windows 10 Pro for Workstations, Firefox 126.0b9 (32-bit)
**Reproducible:** always
**Build found:** 02 May 2024 (prod)

**Preconditions**
Log in as Admin https://www.pick-up.city/#/ubs-admin/orders

**Steps to reproduce**
1. Click on filter icon in column 'Order status'
2. Do not select any filter items
3. Pay attention that both  'Застосувати' and 'Скасувати' buttons are shown

**Actual result**
Buttons “Застосувати” and “Скасувати все” are displayed in column filter
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/6a9bba62-2fff-49a7-9211-55d6a59f59ba)

**Expected result**
Buttons “Застосувати” and “Скасувати все” are displayed when at least one item from filtering list is selected.

**User story and test case links**
#3300 
[Test case](https://jira.softserve.academy/browse/GC-9160)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by bstarchuk** [comment]
Added a fix for displaying the "Apply" and "Cancel" buttons when selecting filters on the orders page of the admin panel.
Pull Request: https://github.com/ita-social-projects/GreenCityClient/pull/3271

### Result:
No selected case:
![Image](https://github.com/user-attachments/assets/de2f9e84-9e89-4a06-bef7-581df1bd07b5)
Selected case:
![Image](https://github.com/user-attachments/assets/a65bbf3d-97cc-4bcb-9918-8cfb44bd98e7)
