### ISSUE TITLE
[Admin cabinet. Orders] Column name is not highlighted when the filter is set.

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7119]
**Environment:** Windows 10 Pro for Workstations, Google Chrome 124.0.6367.93
**Reproducible:** always
**Build found:** 08 May 2024 (prod)

**Preconditions**
Log in as Admin https://www.pick-up.city/#/ubs-admin/orders

**Steps to reproduce**
1. Go to column 'Order status'.
2. Click on filter icon to enable filter by order status
3. Pay attention to column being highlighted and column name not highlighted

**Actual result**
Column rows are highlighted, column heading not highlighted
![image](https://github.com/ita-social-projects/GreenCity/assets/24385480/8248d8a3-61b5-4ee9-8fee-e863b843ae5b)

**Expected result**
Column is highlighted in the same colour as column values.

**User story and test case links**
#3300 
[Test case](https://jira.softserve.academy/browse/GC-9160)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by ViktoriyaRyazhska** [comment]
requirements were changed
