### ISSUE TITLE
[Pick up city UBS Address] The mandatory field 'Район' is not active in the pop-up window 'Нова адреса' when entering the cities: Зазим’є, Петропавлівська Борщагівка, Софіївська Борщагівка.

### ISSUE THREAD

**Issue by Mariia232** [ita-social-projects/GreenCity#7121]
**Environment:** Windows 10, Chrome 123.0.6312.86
**Reproducible:** always,
**Build found:** 09.05.2024

**Preconditions**

1. The registered user is logged in
2. The page 'UBS Courier' is opened
3. User have chosen services from the 'Деталі замовлення' page
4. The second page 'Особисті дані' is opened

**Steps to reproduce**
1. Go to 'Адреса вивезення відходів'.
2. Click on link 'Додати адресу'.
3. Enter city; Зазим'є, Петропавлівська Борщагівка, Софіївська Борщагівка.
4. Enter valid data in the 'Вулиця' field.
5. Select a district from the 'Район' drop-down field.

**Actual result**
The mandatory 'Район' field is not active when entering; 'Зазим’є, Петропавлівська Борщагівка, Софіївська Борщагівка' in the 'Місто' field.
![Monosnap Pick Up City - Google Chrome 2024-05-09 2](https://github.com/ita-social-projects/GreenCity/assets/99343288/310d79e6-c2ab-4bd3-a3a8-806c9e4c1a01)

**Expected result**
The mandatory field 'Район' is active, district options are displayed in the drop-down list when selecting a city: 'Зазим’є, Петропавлівська Борщагівка, Софіївська Борщагівка'.

**User story and test case links**
[Change request to Change request to #2533] <Order form #2199> #3596

**Comment by Maxv1z** [comment]
It was a backend issue. Already fixed.
