### ISSUE TITLE
[Pick up City. Admin cabinet. Orders] Only 20.03.2024 payment date is displayed after selecting the data range from 20.03.2024 to 01.05.2024.

### ISSUE THREAD

**Issue by kulaira** [ita-social-projects/GreenCity#7123]
**Environment:** Windows 10, Google Chrome 123.0.6312.86 (64-bit).
**Reproducible:** always.
**Build found:** 09.05.2024 (prod)

**Preconditions**
1. Pick-up.city site is opened https://www.pick-up.city/#/ubs-admin/orders.
2. Log in as Admin.

**Steps to reproduce**
1. Click on the "Фільтри" button.
2. Click on the ''Дата оплати".
3. Select "Відрізок часу".
4. Choose a date  from 20.03.2024 to 01.05.2024.
5. Click on the "Застосувати" button.

**Actual result**
Only 20.03.2024 payment date is displayed after selecting the data range from 20.03.2024 to 01.05.2024.
![Screenshot_1](https://github.com/ita-social-projects/GreenCity/assets/157893084/974b5cbe-3d27-44c7-8268-714198a1fb4a)

**Expected result**
The payment date from 20.03.2024 to 01.05.2024 is displayed after selecting the data range from 20.03.2024 to 01.05.2024.

**User story and test case links**
E.g.: "User story #3300"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Daria811** [comment]
There are other payment dates in the period from 20.03.2024 to 01.05.2024.
![image](https://github.com/ita-social-projects/GreenCity/assets/165039674/dc5abc8a-8e2e-4430-94ed-3e4fdf9716ca)
But when the Admin uses the filter, only the 20.03.2024 payment date is displayed after selecting the data range from 20.03.2024 to 01.05.2024.
![image](https://github.com/ita-social-projects/GreenCity/assets/165039674/599985a5-e8e9-40b2-be33-d3e55743aaa4)
The filter works only with the first date 20.05.2024.
