### ISSUE TITLE
[Admin cabinet. Orders] Filter deselection not applied within 'Штурман', Логіст', 'Водій', 'Менеджер'

### ISSUE THREAD

**Issue by yulianagoncharenko** [ita-social-projects/GreenCity#7128]
**Environment:** Windows 10 Pro for Workstations, Google Chrome  124.0.6367.119
**Reproducible:** always
**Build found**: 09 May 2024 (prod)

**Preconditions**
Log in as Admin https://www.pick-up.city/#/ubs-admin/orders

**Steps to reproduce**
1. Apply filter within 'Менеджер' column by value 'Nadiia Stoiko'
2. Click on filter again to deselect filer by 'Nadiia Stoiko' and select filter by 'Валерія Ніколайчук'
3. Pay attention that filer button is done by previous selection instead of current selection.
4. Repeat these steps for filter within colums by other employee roles 'Штурман', Логіст', 'Водій'

**Actual result**
Filter applied by previosly selected checkbox instead of current selection
https://www.awesomescreenshot.com/video/27523261?key=727b4102ae6dde01fb9372d3d6101bbc

**Expected result**
Filter checkbox deselection is reflected in popup and filter is applied by currently selected value.

**User story and test case links**
#3300 
[Test case](https://jira.softserve.academy/browse/GC-9160)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maxv1z** [comment]
https://github.com/ita-social-projects/GreenCity/assets/122612827/6d3298ee-0420-4ec7-8516-36569c76080a
