### ISSUE TITLE
[UBS. User. Order form] Different bonus amount in the user's personal account and on the order page

### ISSUE THREAD

**Issue by dijulya** [ita-social-projects/GreenCity#7130]
**Environment:** Windows 11 Pro, Chrome 122.0.6261.131
**Reproducible:** always
**Build found:** 10 May 2024 (prod)

**Preconditions**
Login as User [https://www.pick-up.city/#/ubs](https://www.pick-up.city/#/ubs)
Ukrainian localization is chosen
Bonuses from 'Повернення за замовлення №..' have been added to the User's profile

**Steps to reproduce**
1. Go to User profile
2. Click on tab 'Бонуси'
3. Pay attention to the number of bonuses after returning for the order and on the total amount of bonuses (Screen 1)
4. Go to the 'УБС' page
5. Click on the 'замовити' button
6. Scroll down to point 'Чи бажаєте ви скористатися бонусами?'
7. Pay attention to the number of bonuses 'На Вашому бонусному рахунку: .. грн' (Screen 2)

**Actual result**
Different values of bonuses in the user's personal account and on the order page 

![Screen 1](https://github.com/ita-social-projects/GreenCity/assets/61908979/43e00267-3b22-41bf-95d0-0b0041798f53)
![Screen 2](https://github.com/ita-social-projects/GreenCity/assets/61908979/429e198a-fa65-449f-a83b-3008133ac151)

https://github.com/ita-social-projects/GreenCity/assets/61908979/78d4c52d-0cde-4e7b-8b5f-4f27fe71fbe9

**Expected result**
Bonus amount should be the same in the user personal account and on the order page

**User story and test case links**
E.g.: "User story [#2197](https://github.com/ita-social-projects/GreenCity/issues/2197)

**Comment by dmytro-kryvyi** [comment]
Please add more information why this issue is reopened. Also you should take into account that if you are asking backend team to add bonuses they may not appear in history

**Comment by AnastasiiaIvko** [comment]
Sorry, it must have come out by mistake.
