### ISSUE TITLE
[Pick-up City. UBS Order. API Client Controller] The amount of order with partial payment after GET request 'getAll-users-orders' doesn't match order amount in User's account

### ISSUE THREAD

**Issue by dijulya** [ita-social-projects/GreenCity#7140]
**Environment:** Windows 11 Pro, Chrome 122.0.6261.131
**Reproducible:** always
**Build found:** 13 May 2024 (prod)

**Preconditions**
1. Login as User https://www.pick-up.city/#/ubs
2. The order with partial payment created by the User is displayed in the User's profile

**Steps to reproduce**
1. Create a request with method GET to URL https://greencity-ubs.pick-up.city/ubs/client/getAll-users-orders
2. Send the request

**Actual result**
Status 200 OK is received in the response. The order 'amount' value in the response doesn't match the order amount value in the User's profile

![Actual result Postman](https://github.com/ita-social-projects/GreenCity/assets/61908979/91315e57-f716-420d-bdf8-f39119d677db)

![Actual result User's profile](https://github.com/ita-social-projects/GreenCity/assets/61908979/d4621a89-a392-4642-b967-5cbf59f9ae7a)

**Expected result**
Status 200 OK is received in the response. The order 'amount' value in the response match the order amount value in the User's profile

**User story and test case links**
[Swagger](https://greencity-ubs.pick-up.city/swagger-ui.html#/client-controller/getAllOrdersDoneByUserUsingGET)

**Comment by HelenSotnik** [comment]
Endpoint indeed calculated wrong amount for user to pay, and as it is not used, it was decided to delete it from project. 
The other endpoint from 'Your orders' page shows correct  amount left  to pay and initial payment sum.

**Comment by SvitlanaRadkevych** [comment]
[> [Commit with deleted getAll-users-orders endpoint ita-social-projects/GreenCityUBS#1361 ](/ita-social-projects/GreenCityUBS/pull/1361)
>  Merged
> [ Deleted getAll-users-orders endpoint as not used ita-social-projects/GreenCityUBS#1362](/ita-social-projects/GreenCityUBS/pull/1362)](https://github.com/ita-social-projects/GreenCityUBS/pull/1361)

The endpoint has deleted
