### ISSUE TITLE
[GreenCity] Habits are not displayed in calendar in "My Space" section

### ISSUE THREAD

**Issue by ABbondar** [ita-social-projects/GreenCity#7167]
Habits are not displayed in calendar in "My Space" section.

Actual result
<img width="1250" alt="Снимок экрана 2024-05-27 в 22 57 32" src="https://github.com/ita-social-projects/GreenCity/assets/53192419/026ffccd-e3be-4bf9-a21a-be29c1284d96">

Expected result
<img width="545" alt="2024-05-27_14 40 36" src="https://github.com/ita-social-projects/GreenCity/assets/53192419/a8fdcdc0-114d-4919-9b49-cdaf4d919292">

**Comment by snezhanapravdyuk** [comment]
![изображение](https://github.com/ita-social-projects/GreenCity/assets/165433958/a8a5eaec-dc4c-4e72-9218-4c30c904c684)
