### ISSUE TITLE
[UBS Tariffs Page] The tariff is not deactivated after clicking the ''Deactivate'' button.

### ISSUE THREAD

**Issue by kulaira** [ita-social-projects/GreenCity#7179]
**Environment:** Windows 10, Google Chrome 123.0.6312.86 (64-bit).
**Reproducible:** always.
**Build found:** 02.06.2024.

**Preconditions**
1. GreenCity site is opened https://www.greencity.social/#/ubs-admin/tariffs.
2. User is authorized as Admin.
3. "Tariffs" page is opened.

**Steps to reproduce**
1. Click on any available tariff card.
2. Click to the “trash” in the tariff line in “Tariffs for services” section.
3. The "Deactivate tariff for service" pop-up window is opened.
4. Click on the ''Deactivate'' button.

**Actual result**
The tariff is not deactivated, the "Deactivate tariff for service" pop-up window is opened and the ''Deactivate'' button is highlighted in blue.
![Screenshot_5](https://github.com/ita-social-projects/GreenCity/assets/157893084/a9b8f261-4a11-44fc-8d32-536169f4781f)
**Expected result**
The "Deactivate tariff for service" pop-up window is closed and the tariff is deactivated.

**User story and test case links**
E.g.: "User story #4431"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Maxv1z** [comment]
Not reproducible:

https://github.com/ita-social-projects/GreenCity/assets/122612827/814f2d2f-93d4-429c-93d9-ce177bc5404c

**Comment by Daria811** [comment]
The "Deactivate tariff for service" pop-up window is opened and the ''Deactivate'' button isn't clickable. The tariff is not deactivated. 
https://drive.google.com/file/d/1CzM6feKZXMM8xTEeNFPsP1RSKKyPWK7g/view?usp=sharing
