### ISSUE TITLE
[Create news][Display news] Image's size is changed after selecting it in the 'Picture' field and news publishing

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#719]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit b517ccb

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Log into the system.
3. Click on 'Eco news' link in the header.
4. Click on 'Create news' button.
5. Enter valid data in 'Title' and 'Content' fields (e.g. "NASA photo showing the Earth's atmosphere").
6. Select 1 tag (e.g. "News").
7. Drag & drop image that has size that is smaller than the field size into 'Picture' field (JPEG or PNG only less than 10 MB, e.g. image from attachment).
8. Click on 'Publish' button.
![index](https://user-images.githubusercontent.com/64583544/81990501-f37b2600-9647-11ea-9d30-37c69f54e958.png)

**Actual result**
Image in the 'Picture' field on the 'Create news' page changed it's size according to the field boundaries. Image in the created news also changed it's size according to the container boundaries.
![Image resizing](https://user-images.githubusercontent.com/64583544/82158074-19920780-988e-11ea-94a4-d7f3f3ae4cbc.png)
![Display image resizing](https://user-images.githubusercontent.com/64583544/82158075-1dbe2500-988e-11ea-9e84-985f3fa4c0e4.png)

**Expected result**
Image in the 'Picture' field on the 'Create news' page didn't change it's size. Image in the created news also didn't change it's size. 

User story #505 #459 #460 
[Test case1](https://jira.softserve.academy/browse/GC-656) [Test case2](https://jira.softserve.academy/browse/GC-679)

**Comment by KimAT25** [comment]
This is not a bug, as it wasn`t agree with BA and Designers, should be discussed this logic.
