### ISSUE TITLE
API [Edit event] Status code 200 is shown when user enters the same time in "Start time" and "End time" fields in 1 day duration event

### ISSUE THREAD

**Issue by Maryna-511750** [ita-social-projects/GreenCity#7219]
**Environment:** 
Windows 11 Pro,
Google Chrome (126.0.6478.56),
Postman
**Reproducible:** always.
**Build found:** 14.06.2024

**Preconditions**
The user is authorized
The user has one created event 
Postman is opened and the token is gotten.

**Steps to reproduce**
Create a PUT request to https://greencity.greencity.social/events/update
 Body:
{
  "id": "2",
  "title": "Some title",
  "description": "<p>Some description. A very long description of the event.</p>",
  "open": true,
  "tags": [
    "Economic"
  ],
  "datesLocations": [
    {
      "startDate": "2024-06-25T13:00:00.000Z",
      "finishDate": "2024-06-25T13:00:00.000Z",
      "onlineLink": "https://github.com/ita-social-projects/GreenCity/projects/3"
    }
  ],
  "imagesToDelete": [],
  "additionalImages": [],
  "titleImage": "img/habits/default-habit-image.png"
}

**Actual result**
Status: 200 OK

**Expected result**
Status: 400 Bad Request

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/3d99b743-659c-4ddf-be4e-29b6e2391d45)

**Comment by Roksana77** [comment]
The bug is not reproducible for Chrome 127.0.6533.100 (64-bit).

![image](https://github.com/user-attachments/assets/c4bf17ab-9431-420c-b146-9f8f2d1e4fe5)

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/81d8a1ab-d563-46fb-98e1-acf1f54c1e86)
