### ISSUE TITLE
[Create news] Default image size doesn't  full displayed on the screen after resizing 

### ISSUE THREAD

**Issue by OlesiaSolovii** [ita-social-projects/GreenCity#722]
Environment: macOS Catalina, Version 10.15.4 (19E287),
Google Chrome, Version 81.0.4044.129
Build found: commit b517ccb

**Steps to reproduce:**

1. Sign in on Green City [https://ita-social-projects.github.io/GreenCityClient/#/news].
2. Click on 'Eco News' link.
3. Click on 'Create news' bttn.
4. Fill in 'Title' field (e.g. '‘Plastic’ bags").
5. Select one tag (e.g. "News").
6. Fill in 'Content' field (e.g. "Ukrainian scientist invents eco-friendly ‘plastic’ bags").
7. Click on "Preview" bttn.
8. Resize window to 576  resolution.

**Actual result** 
Default image size doesn't full displayed on the screen after resizing.
<img width="468" alt="Screen Shot 2020-05-17 at 10 54 24 PM" src="https://user-images.githubusercontent.com/64583001/82158727-4ba56880-9892-11ea-8c6c-97b0c300a1bc.png">

**Expected result** 
Default image size should be full displayed on the screen after resizing(see mock up).
<img width="215" alt="Screen Shot 2020-05-17 at 10 58 55 PM" src="https://user-images.githubusercontent.com/64583001/82158849-1f3e1c00-9893-11ea-96fc-9dcdc864f1fc.png">

User story #526
Test case [https://jira.softserve.academy/browse/GC-405]

**Comment by BohdanPrysiazhnyi** [comment]
This bug didn't fixed
