### ISSUE TITLE
[UBS AutoNotification] Links in autonotifications are not clickable in 'Messages' tab

### ISSUE THREAD

**Issue by liliaruda** [ita-social-projects/GreenCity#7238]
***Environment***: Chrome 126.0.6478.127 (64-bit)
***Reproducible***: always
***Build found**:* 29.06.24

***Preconditions***
1. Go to  https://www.pick-up.city/ as client
2. Open 'My profile'
3. Click on 'Messages' tab
4. Client has notifications with links (such as The courier route formed, Violation of the rules, Pay for the change in the order, Unpaid Order) in 'Messages' tab 

***Steps to reproduce***
1. Expand notification (by clicking on the up arrow)
2. Pay attention to the links in the message

***Actual result***
Links in notifications are ***not clickable*** in 'Messages' tab
![Знімок екрана (1222)](https://github.com/ita-social-projects/GreenCity/assets/163115255/7dfee7fe-e4a6-4788-9880-4faa4241eddd)
![Знімок екрана (1223)](https://github.com/ita-social-projects/GreenCity/assets/163115255/e8bc29e4-a752-487e-9c47-170c4182cbd1)

***Expected result***
Links in notifications are clickable and active in 'Messages' tab

**User story** #2796

**Comment by OlhaNechaieva** [comment]
The link to the messenger is not clickable

**Comment by OlhaNechaieva** [comment]
https://github.com/user-attachments/assets/8a6697be-8a1a-4e7e-b229-074c2ff75d0c
