### ISSUE TITLE
[UBS Client cabinet] The Telegram toggle button isn`t automatically disabled after deleting chat with bot

### ISSUE THREAD

**Issue by liliaruda** [ita-social-projects/GreenCity#7241]
**Environment:** Chrome 126.0.6478.127 (64-bit)
**Reproducible:** always
**Build found:**  29.06.24

**Preconditions**
Telegram must be installed on a PC

**Steps to reproduce**
1. Go to https://www.pick-up.city/#/ubs as client
2. Open 'My profile'
3. Click on 'User data' tab 
4. Click on 'Edit data' button
5. Scroll down to 'Get notification in'
6. Switch on toggle button 'Telegram'
7. Click on the 'Send message'
8. Press ‘Start’ in the chat-bot in Telegram
9. Delete chat with the bot in messenger Telegram

**Actual result**
Toggle button 'Telegram' **isn`t** automatically disabled
![image](https://github.com/ita-social-projects/GreenCity/assets/163115255/1d8cf8b9-9f1a-4685-b47b-f009cf1beb20)

**Expected result**
Toggle button 'Telegram' is automatically disabled after deleting chat with bot on Telegram

**User story and test case links**
User story #5423

**Comment by Dima-Vas** [comment]
Implemented in [#1473](https://github.com/ita-social-projects/GreenCityUBS/pull/1473)
