### ISSUE TITLE
 [UBS Notifications] Notification 'Let's stay connected' isn`t sent every 2 months after last order in 'Messages' tab

### ISSUE THREAD

**Issue by liliaruda** [ita-social-projects/GreenCity#7244]
**Environment:** Chrome 126.0.6478.127 64-bit
**Reproducible:** always
**Build found:** 01.07.24

**Preconditions**
User has the last order that was made 2 months ago

**Steps to reproduce**
1. Go to https://www.pick-up.city/#/ubs
3. Click on 'My profile'
4. Open 'Message' tab
5. Pay attention to the notification 'Let's stay connected' that came after 2 months from the date of the last order

**Actual result**
The notification 'Let's stay connected' **wasn`t** received

**Expected result**
1. Notification 'Let's stay connected' received after 2 months from the date of the last order
2. The system must re-send a message every 2 months, throughout the year. The letter should have a built-in counter that will indicate how long ago the last order was 2 months, 4 months, 6 months, etc. up to 1 year.
3. Text of the notification: 
Title: Давайте залишатися на зв'язку Body: Привіт! Ми помітили, що ви не користувалися послугою «УБС Кур‘єр» уже [month amount] місяці. Можливо, ви вирушили в тривалу подорож, а можливо, щось пішло не так зі збиранням пластиків. Поділіться, будь ласка, цим із нами, щоб ми зрозуміли, чи можемо допомогти і як саме.

**User story and test case links**
User story #2796

**Comment by HelenSotnik** [comment]
Close issue due to duplication in [issue 7245.](https://github.com/orgs/ita-social-projects/projects/43/views/1?pane=issue&itemId=69506156)
