### ISSUE TITLE
[API Employees] The '/admin/ubs-employee/get-employee-login-positions' Endpoint has 400 code by a valid employee's email

### ISSUE THREAD

**Issue by Daria811** [ita-social-projects/GreenCity#7265]
**Environment:**  OS Windows 10 Home, browser Chrome, Version 126.0.6478.127 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** 09.07.2024.

**Preconditions**
The Admin is logged in, and the token is gotten.

**Steps to reproduce**
1. Create a request:

- method - GET
- URL - https://greencity-ubs.greencity.cx.ua
- Endpoint - /admin/ubs-employee/get-employee-login-positions?email=testerdaria7@gmail.com
- Authorization by gotten token Admin. 

2. Send the request.
3. Observe the response.

**Actual result**
The '/admin/ubs-employee/get-employee-login-positions' Endpoint has 400 'Bad Request' code by a valid employee's email (this employee has been authorized).
The response has the message: "User has not login in the system by this email".

**Expected result**
The response should have 200 OK code. 
This Endpoint should show the information about employee's positions by the login.

Notes:
This Endpoint shows the information only about the Admin login with his gotten token.
That is, the request is performed under the authorization of the admin and according to his login so that the admin can see his position as the admin.
This feature doesn't work on the test web app, the Admin can not search the employee's positions by login.

**User story and test case links**
E.g.: "User story #[2782](https://github.com/ita-social-projects/GreenCity/issues/2782)

**Comment by ToriForH** [comment]
Bug doesn't reproduce

**Comment by ToriForH** [comment]
endpoint was deleted since it doesn`t use
