### ISSUE TITLE
[GreenCity/ User data/ Delete profile] The user profile is not deleted

### ISSUE THREAD

**Issue by snezhanapravdyuk** [ita-social-projects/GreenCity#7266]
**Environment**: Windows 11 Pro, 123.0.1 (64-bit)
**Reproducible:** always
**Build found:** 09.07.2024

**Preconditions**

    Go to ​ https://www.greencity.cx.ua/#/ubs-user/profile

    User logged in

Steps to reproduce

    Go to 'UBS-user'

    Open 'User data' tab

    Сlick on the 'Delete profile'
    
    Click on 'Delete' in the pop-up

**Actual result**

The user profile is not deleted

https://github.com/ita-social-projects/GreenCity/assets/165433958/68f8e899-8a61-408e-947c-2131bfba7cb9

**Expected result**

The user profile is deleted

Postconditions

Labels to be added
"Bug", Priority ("pri: high"), Severity ("severity: minor"), Type ("Functional").

**Comment by dmytro-kryvyi** [comment]
Duplication of #5606
