### ISSUE TITLE
[GreenCity Admin pofile] Not all registered users are displayed in the Customers table

### ISSUE THREAD

**Issue by snezhanapravdyuk** [ita-social-projects/GreenCity#7267]
**Environment:** Windows 11 Pro, 123.0.1 (64-bit)
**Reproducible:** always
**Build found:** 10.07.2024

**Preconditions**

Go to  https://www.greencity.cx.ua/#/ubs-admin/customers

Login as an admin

**Steps to reproduce**

Go to 'UBS-admin'

Open 'Customers' tab

Pay attention to the number of registered users

![Image](https://github.com/ita-social-projects/GreenCity/assets/165433958/72a1b841-a485-412f-8126-5bdb38dd87fd)

Verify the number of registered users in the database

https://github.com/ita-social-projects/GreenCity/assets/165433958/b333cff1-73b0-4e08-89d5-e9ee945283ef

**Actual result**
The number of users on the site does not correspond to the number of users in the database

**Expected result**

The number of users on the site corresponds to the number of users in the database

**Postconditions**

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("Functional").

**Comment by KizerovDmitriy** [comment]
On this page, we display only those customers who have at least one order, for those who have no orders - they are not included in the list.
