### ISSUE TITLE
[API]GET /admin/ubs-employee/get-all-positions Get all employee positions  - return 200 status instead of 403.

### ISSUE THREAD

**Issue by 111natalies** [ita-social-projects/GreenCity#7271]
**Environment:** Windows 10 , browser Chrome, Version 125.0.6422.142 
**Reproducible:** always
**Build found:**10.07.24

**Preconditions**
1.Swagger:    https://greencity-ubs.greencity.cx.ua/swagger-ui/index.html#/management-employee-controller/getTariffInfoForEmployee
2. An employee without 'Employees' permissions is authorized

**Steps to reproduce**
1.Create a GET  request to :  admin/ubs-employee/get-all-positions
 

**Actual result**
200 Status code is shown
**Expected result**
403 Status code is shown

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by IliaWithHat** [comment]
No bug found.
