### ISSUE TITLE
[Events page] Events duplication during filtering

### ISSUE THREAD

**Issue by DmytroDmytruk** [ita-social-projects/GreenCity#7295]
**Environment:** Windows 11 x64, Google Chrome 127.0.6533.73
**Reproducible:** always
**Build found:** 30.07.2024

**Preconditions**

1. Go to events page

**Steps to reproduce**

1. Write title of event. For example "TEST TEST TEST TEST"

![Image](https://github.com/user-attachments/assets/33786b41-8fb2-4a9b-afee-bd75004ccba5)

2.Quickly click on the 2 or more checkboxes before previous change load

![Image](https://github.com/user-attachments/assets/b1b352e0-2ff9-439e-8374-efb198c1a887)

Actual result 
There are 2 copies of Event "TEST TEST TEST TEST"

Expected result
There is 1 copy of Event "TEST TEST TEST TEST"

**Comment by Lokankara** [comment]
Unable to reproduce
![Screenshot (1081)](https://github.com/user-attachments/assets/59d41307-7574-4072-b67b-f50ecd2e04b7)

**Comment by DmytroDmytruk** [comment]
> Unable to reproduce ![Screenshot (1081)](https://private-user-images.githubusercontent.com/78595276/354547982-59d41307-7574-4072-b67b-f50ecd2e04b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTIxNjIsIm5iZiI6MTcyMjU5MTg2MiwicGF0aCI6Ii83ODU5NTI3Ni8zNTQ1NDc5ODItNTlkNDEzMDctNzU3NC00MDcyLWI2N2ItZjUwZWNkMmUwNGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA5NDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODU2Y2Y0MzQ0OThkZGNhYWNlZTBkMDMyMzliZGI1NzExYjAxNzU1MzI2Njg2ODJkMjQwMTg3ZmU0YTExN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iZ6fLSe2BHpBOszOQJ2S9PaNMGMY30gOouR1ikBrMaI)

You need quickly apply filters before previous changes loaded
