### ISSUE TITLE
[Cabinet view] [User data] The switch in the User Profile doesn't disable automatically if a user deletes a chat with a bot in the messenger

### ISSUE THREAD

**Issue by SvitlanaRadkevych** [ita-social-projects/GreenCity#7299]
**Environment:** IPhone 13, IOS 17.5.1, Google Chrome 110.0.5481.83
**Reproducible:** always
**Build found:** 01/08/2024

**Preconditions**
1. The mobile application "Green city" is installed on the phone
2. The user is logged in.

**Steps to reproduce**
1. Go to 'MY PROFILE'
2. Click on 'User' icon 
3. Click on 'Telegram' toggle button
4. Start a chat with PICKUPcity_bot
5. Delete the chat
6.  Go back to the mobile application "Green city"
7. Pay attention to 'Telegram' toggle button.

**Actual result**
The toggle button in the User Profile is activated 
![toggle_button](https://github.com/user-attachments/assets/626e1e22-a651-4eb4-9947-9f7009a3f3d5)

**Expected result**
 The toggle button in the User Profile should be switched off automatically without user participation in the profile editing

**User story and test case links**
[https://github.com/ita-social-projects/GreenCity/issues/5423](url)

**Comment by Maryna-511750** [comment]
Such task already exists: https://github.com/ita-social-projects/GreenCity/issues/7241
