### ISSUE TITLE
[Comment Reply] The reply is displayed with delay near 1 mn and with repetition of the same reply 

### ISSUE THREAD

**Issue by Roksana77** [ita-social-projects/GreenCity#7343]
**Environment:** Windows 10, Chrome  127.0.6533.89, 64-bit;  iOS 17.5.1 (21F90)
**Reproducible:** always.
**Build found:** last commit from https://www.greencity.cx.ua/#/events/3009

**Preconditions**
The Event's page https://www.greencity.cx.ua/#/events is opened.
The user is logged in.

**Steps to reproduce**
1.Choose event and click 'More' button.
2.Choose comment and click 'Reply' button.
3.Type the reply and click 'Reply' button.
4.Pay attention to publishing time of reply.

**Actual result**
1.The system adds the reply with delay (near 1mn).
2. It repeats the same reply for a lot of times (near 25).
3. The reply is visible only after reloading the page or finding the event with this reply in the search.

https://github.com/user-attachments/assets/4e514192-9cd5-4ec2-b228-51e23eec80b9

![reply repeat](https://github.com/user-attachments/assets/467f2889-eaa7-4192-a4e3-368b2db36a32)

**Expected result**
1. Systems adds the reply immediately.
2.The reply is displayed under the reply text box 'Add a reply' with the User’s name and avatar, the date of the reply over the reply text box.
3. The system saves the reply in the ‘View [number] replies’ list;
5. The system recalculates the number of the total replies and updates it in the ‘View [number] replies’ list.

**Postconditions**
Close the Even'ts card.

**User story and test case links**

https://github.com/ita-social-projects/GreenCity/issues/6411

**Labels to be added**

"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by HelenSotnik** [comment]
I have tried to reproduce your steps and even opened the same event to reply your comment. It seems to work fine. Reply is sent momentally and no necessity to reload page, clicked once and created once. Maybe you had poor internet connection and clicked too many times?, but for me this bug is not reproducible. 
 I use MacBook Air, Safari and iPhone. 

![Image](https://github.com/user-attachments/assets/95c29694-7149-4275-b029-52d771e259ba)

**Comment by Roksana77** [comment]
Hello! I have a good internet and this problem occurs also if we want to
add, edit comments or reply or delete replies as well. Maybe this site is
only for MacBook, Safari). But it is a bug on  Windows 10, Chrome
127.0.6533.89, 64-bit.
 Home - Google Chrome 2024-08-14 22-46-12.mp4
<https://drive.google.com/file/d/1jhMWRZhsOE2_rrGexl0sS-IyUomwDfLs/view?usp=drive_web>


чт, 15 серп. 2024 р. о 15:55 HelenSotnik ***@***.***> пише:

**Comment by Roksana77** [comment]
[image: image.png]

чт, 15 серп. 2024 р. о 17:46 Oksana Buchko ***@***.***> пише:

**Comment by AnastasiiaIvko** [comment]
Although a reply to a comment is saved quickly and without repetition, it cannot be deleted.

**Comment by kryzanivska-nastya** [comment]
> Although a reply to a comment is saved quickly and without repetition, it cannot be deleted.

Doesn't reproduce
https://github.com/user-attachments/assets/e5e3b515-4209-475b-a94b-5d6118e8b90c

**Comment by AnastasiiaIvko** [comment]
https://github.com/user-attachments/assets/cd7b7575-4fc4-468b-9c38-35b0cb8ac2c0

**Comment by AnastasiiaIvko** [comment]
A reply to a comment is deleted only after the page is reloaded.

**Comment by kryzanivska-nastya** [comment]
> A reply to a comment is deleted only after the page is reloaded.

Fixed, now works like this
https://github.com/user-attachments/assets/adef509d-0470-45ff-b33c-aaa23a260e35
