### ISSUE TITLE
[Comment Reply] The text with more than 8000 characters can be added into reply to the comment (8001 and much more)

### ISSUE THREAD

**Issue by Roksana77** [ita-social-projects/GreenCity#7346]
**Environment:** Windows 10, Chrome 127.0.6533.89, 64-bit.
**Reproducible:** often
**Build found:** 14.08.2024

**Preconditions**

The Event's page https://www.greencity.cx.ua/#/events is opened.
The user is logged in.

**Steps to reproduce**

1.Choose event with comments and reply to one.
2.Type 8001 characters. Click 'Reply' button.
3. Type much more that 8001 characters. Click 'Reply' button.

**Actual result**

The text with more than 8000 characters can be added (8001 and much more).

**Expected result**

1.System doesn't save reply with more that 8000 characters.
2.The reply text field is highlighted in red color starting from 8001 characters.
3.'Reply' button is disabled
4. Error message ''This reply text field shouldn't be more than 8000 characters' under the reply text field is displayed.

**Postconditions**

Close the Event's card.

**User story and test case links**

https://github.com/ita-social-projects/GreenCity/issues/6411

**Labels to be added**

**Comment by HelenSotnik** [comment]
I have generated 8002 characters text and added it to reply. The message that it is more than 8000 chars text is shown, and button is not able to push. Once I removed 2 chars and it became ok to save. Maybe you wrongly generated less than 8000 chars, that is why it was saved. Retest bug please.

![Image](https://github.com/user-attachments/assets/20e62112-db5e-40dc-b22a-c317b8b0d0c9)


![Image](https://github.com/user-attachments/assets/56fb002d-e49c-4abc-8b66-270f81d94059)

**Comment by Roksana77** [comment]
https://www.greencity.cx.ua/#/events/3009
But I typed over 8002 somehow))) You can count characters to ensure)

чт, 15 серп. 2024 р. о 15:40 HelenSotnik ***@***.***> пише:

**Comment by HelenSotnik** [comment]
I have counted and number of chars you typed does not equal 8001 as mentioned. You can check it here. https://hyperhost.ua/tools/uk/character-counter#:~:text=✏%20Як%20порахувати%20кількість%20символів,обсяг%20тексту%20в%20порожнє%20поле.



![Image](https://github.com/user-attachments/assets/ca15b38f-6a2e-490b-b176-e800763ed9dd)

Here is you text counted by number of chars
