### ISSUE TITLE
[Comment Delete] The comments cannot be deleted by owners if they are authorized users

### ISSUE THREAD

**Issue by Roksana77** [ita-social-projects/GreenCity#7348]
**Environment:** Windows 10, Chrome  127.0.6533.89, 64-bit.
**Reproducible:** often
**Build found:** last commit from 14.08.2024

**Preconditions**

1. The Event's page https://www.greencity.cx.ua/#/events is opened.
2. The user if logged in.

**Steps to reproduce**
1. Choose event and click 'More' button.
2. Choose your own comments and click 'Delete' label.
3. Click 'Yes, delete' button.

**Actual result**

System doesn't delete comments if action is performed by authorized user.

https://github.com/user-attachments/assets/73a69dd5-9e30-4226-bc9f-333d5b97f637

![delete](https://github.com/user-attachments/assets/45b2af65-5fab-4408-ad3c-30fe7006639c)

![deleteeee](https://github.com/user-attachments/assets/bd129230-6289-43f6-8f61-5b92d96194b5)

**Expected result**

System deletes the comment immediately.

**Postconditions**

Close Event's card.

**User story and test case links**

https://github.com/ita-social-projects/GreenCity/issues/3209

**Labels to be added**

**Comment by Lokankara** [comment]
Cannot be reproduced

https://github.com/user-attachments/assets/8b969143-b37f-47e5-8016-37dc1733c6e1

**Comment by Roksana77** [comment]
As a user or admin?

śr., 14 sie 2024, 22:18 użytkownik Pasha ***@***.***> napisał:

**Comment by Roksana77** [comment]
Only as admin I can, as authorized user I cannot


śr., 14 sie 2024, 22:24 użytkownik Oksana Buchko ***@***.***>
napisał:

**Comment by Roksana77** [comment]
Uploading Home - Google Chrome 2024-08-14 22-34-56.mp4…

**Comment by Roksana77** [comment]
https://github.com/user-attachments/assets/0c3d818c-dbc7-4513-988d-2cdcfe595e21

**Comment by Roksana77** [comment]
DeleteComment2.mp4…

**Comment by Roksana77** [comment]
Video2.mp4…

**Comment by Roksana77** [comment]
https://github.com/user-attachments/assets/23bb240b-7094-49c3-aa0c-6429563becef

**Comment by HelenSotnik** [comment]
This bug is not reproduced, I have been logged in as user. Added new comment to event, and then deleted it. 

![Image](https://github.com/user-attachments/assets/76c72bee-cf14-47f3-a3e1-ec6ca23a0466)
![Image](https://github.com/user-attachments/assets/a9fbe1ec-f280-4de8-966c-cbd6280a9e4c)

**Comment by Roksana77** [comment]
Using Windows 10, Chrome 127.0.6533.89, 64-bit Environment and being logged in I can't delete any comments.
