### ISSUE TITLE
[Edit Event] Uploaded image for the event cannot be edited

### ISSUE THREAD

**Issue by Roksana77** [ita-social-projects/GreenCity#7357]
**Environment:** Windows 10, Chrome  127.0.6533.89, 64-bit.
**Reproducible:** always
**Build found:**  10.08.2024

**Preconditions**
1.The page https://www.greencity.cx.ua/#/ is opened.
2.The user is logged in.

**Steps to reproduce**
1.Create event on page 'Events'.
2.Click on 'Edit' button.
3.Upload the image with the size less than 10MB.
4.Check if it's possible to chose area to display and edit it.

**Actual result**
Photo is partly visible with the button  'Edit image', which is disable.
https://drive.google.com/file/d/18nrcjxvaa6OG4of6TRIhRhc-j3736YDH/view?usp=sharing

**Expected result**
Photo is visible just with the chosen area. during editing.

**Postconditions**
Close Event's card.

**User story and test case links**
https://github.com/ita-social-projects/GreenCity/issues/3193

**Labels to be added**

**Comment by bzhn** [comment]
@Roksana77 
Can't reproduce the bug. Toast message shows as expected after following all steps from issue description.


![Image](https://github.com/user-attachments/assets/5bd38f7a-0ad2-4217-ab5f-2ad07dfc626a)


I used the image from this site

https://svs.gsfc.nasa.gov/vis/a030000/a030800/a030877/frames/5760x3240_16x9_01p/

**Comment by Roksana77** [comment]
Yes, but still we have problem with editing pictures with correct size. It's impossible to edit. And in general it's difficult to edit event and it's impossible to see it edited without reloading the page.

https://drive.google.com/file/d/18nrcjxvaa6OG4of6TRIhRhc-j3736YDH/view?usp=sharing

**Comment by Maryna-511750** [comment]
This error is not reproduced. Editing a loaded image when editing an event works correctly.
![Image](https://github.com/user-attachments/assets/0206274d-070c-4418-aae7-2599ad1e0578)
![Image](https://github.com/user-attachments/assets/dead61b3-b7d1-4f86-8537-7406cb87eaef)
![Image](https://github.com/user-attachments/assets/eed2b1f3-6f39-4f81-97ba-05de0b4825cd)
![Image](https://github.com/user-attachments/assets/038651c2-a4be-4af0-ae90-b70a03fb031f)
