### ISSUE TITLE
[Places] "More options" button is not displayed according to mockup

### ISSUE THREAD

**Issue by kryzanivska-nastya** [ita-social-projects/GreenCity#7388]
**Environment**: Windows, Chrome 128.0.6613.86
**Reproducible**: always

**Steps to reproduce**

Go to [GreenCity](https://www.greencity.cx.ua/#/greenCity)
The user must be logged in to the system
Go to Places page

**Actual result** 
active and non active state of button are higher than other buttons
![Image](https://github.com/user-attachments/assets/988c0bf4-61d8-4503-adc0-71bf2b00a42e)

**Expected result** 
active and non active state of button are in correct position
![Image](https://github.com/user-attachments/assets/f363e824-9ea6-496c-b1db-b5a8c75a6936)

![Image](https://github.com/user-attachments/assets/ce466936-ca2d-497d-9211-438fbf2753cb)

Mockup: [link](https://www.figma.com/design/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=13787-55543&node-type=CANVAS&t=OzwO51bQNmLZXnS2-0)

Labels 
"Bug", Priority ("pri:low "), Severity ("severity:trivial"), Type ("UI), Places

**Comment by nuttaa0** [comment]
'More option' button is still different from mockup.
![Image](https://github.com/user-attachments/assets/0bef20b8-f4bf-4bfe-b8a9-86e2ffde2192)

**Comment by kryzanivska-nastya** [comment]
> 'More option' button is still different from mockup. ![Image](https://github.com/user-attachments/assets/0bef20b8-f4bf-4bfe-b8a9-86e2ffde2192)

Sorry for confusion, didn't mention the active state and non active(updated the issue), when active it's green(choosed sth), it's all as it should be, the button just was moved a little below (the active and non active state too)

**Comment by AnastasiiaIvko** [comment]
The font of the 'More Options' button is still different from the mockup and the fonts on the other buttons 
![Image](https://github.com/user-attachments/assets/fcff93e4-2677-4ac8-99df-b6e823b5ef9b)

**Comment by kryzanivska-nastya** [comment]
> The font of the 'More Options' button is still different from the mockup and the fonts on the other buttons ![Image](https://github.com/user-attachments/assets/fcff93e4-2677-4ac8-99df-b6e823b5ef9b)

Fixed, now looks like that ![Image](https://github.com/user-attachments/assets/1657c49c-715b-4ac9-b141-84064c20bb4f)
