### ISSUE TITLE
[UBS GreenCity events] Incorrect pagination UI according to mock-up

### ISSUE THREAD

**Issue by DenysLeontiev** [ita-social-projects/GreenCity#7409]
**Environment:** Windows 11, Chrome
**Reproducible:** always
**Build found:** 03.09.2024

**Preconditions**
Go to event comments under it

**Steps to reproduce**
1. Go to [https://www.greencity.cx.ua/#/events/96](https://www.greencity.cx.ua/#/events)
2. Choose any event with comments under it
3. Scroll down to pagination

**Actual result**
![_actual](https://github.com/user-attachments/assets/456ab55f-aafb-4531-954d-e5cc0f0a9fa3)

**Expected result**
![_expected](https://github.com/user-attachments/assets/f960427d-2e93-4541-8ca6-d8a868f7ee0b)

**Comment by nuttaa0** [comment]
Pagination still doesn't correspond the mockup
![Image](https://github.com/user-attachments/assets/8f591da7-8d55-4d65-877a-e6c3a8641e5d)

**Comment by Nodarianec** [comment]
pagination fixed
![image](https://github.com/user-attachments/assets/02ccf4c3-1c7d-4168-b0f6-5d4c7237c510)
