### ISSUE TITLE
[My Space] Incorrect pop-up message when trying to add a seventh habit

### ISSUE THREAD

**Issue by AnastasiiaIvko** [ita-social-projects/GreenCity#7416]
**Environment:** Windows 10 Pro  (64 bit)
Chrome 128.0.6613.113

**Reproducible:** always.

**Preconditions**
1.	User must be logged in.
2.	The user must have 6 habits in progress.
3.	The «My Habits» page must be open. 

**Steps to reproduce**
1.	Click on the button "Add New Habit"
2.	Choose any new habit from the list and click "Add habit"

**Actual result**
A pop-up appears with the message: " You already have assigned this habit”

**Expected result**
A pop-up should appear with the message: " You can only have 6 habits in progress”

**User story and test case links**
E.g.: "User story #1001

**Labels to be added**
Priority: medium Severity: low Type: UI

![Image](https://github.com/user-attachments/assets/0ba59d7b-56dc-43da-bef3-f36da8b9dc09)

**Comment by AnastasiiaSmolianska** [comment]
When user tries to add a sixth habit pop-up message " You can only have 6 habits in progress” appears and user can have only 5 habits in progress. This message should appears when user attempts to add seventh habit. User should be able to add 6 habits in progress, according to the user story #1001.
https://github.com/user-attachments/assets/49e5cd68-f493-4aad-9e84-5319e56f6013

**Comment by kryzanivska-nastya** [comment]
https://github.com/user-attachments/assets/458fb5ba-27d7-4dc5-b2ca-3b1c969a741b
Doesn't reproduce in my case
