### ISSUE TITLE
[Comment] Dropdown list stability during tagging user

### ISSUE THREAD

**Issue by kryzanivska-nastya** [ita-social-projects/GreenCity#7417]
**Environment**: Windows, Chrome 128.0.6613.86
**Reproducible**: always

**Steps to reproduce**
Go to [GreenCity](https://www.greencity.cx.ua/#/greenCity)
The user must be logged in to the system
Go to Eco news page
Click on news
Go to the comments
Tag a user @

**Actual result**
Everytime a user types new letter, the list closes and opens again

![Image](https://github.com/user-attachments/assets/41f894cc-4481-4da8-ba3c-114ca3211c0e)

**Expected result**
Everytime a user types new letter the list doesn't close

Labels 
"Bug", Priority ("pri:medium"), Severity ("severity:medium"), Type ("UI"), Eco news

**Comment by nuttaa0** [comment]
Drop down with suggested users isn't appeared. It is impossible to tag user. Reproduce in Google Chrome. In Firefox works properly.
https://github.com/user-attachments/assets/0f9605a1-9823-4726-832c-e1f11cfbec65

**Comment by kryzanivska-nastya** [comment]
> Drop down with suggested users isn't appeared. It is impossible to tag user. Reproduce in Google Chrome. In Firefox works properly. https://github.com/user-attachments/assets/0f9605a1-9823-4726-832c-e1f11cfbec65

Works fine for me in Google
https://github.com/user-attachments/assets/26ad4e98-b466-43a7-b465-23b9fc301f8b

**Comment by nuttaa0** [comment]
> > Drop down with suggested users isn't appeared. It is impossible to tag user. Reproduce in Google Chrome. In Firefox works properly. https://github.com/user-attachments/assets/0f9605a1-9823-4726-832c-e1f11cfbec65
> 
> Works fine for me in Google https://github.com/user-attachments/assets/26ad4e98-b466-43a7-b465-23b9fc301f8b

Still doesn't work on MacOs Sonoma 14.6 (23G80). Browser: Google Chrome Версія 129.0.6668.91 (Офіційне складання) (x86_64)

https://github.com/user-attachments/assets/6f2c5b9c-1e52-49e8-a613-dd0cbb04d178

**Comment by kryzanivska-nastya** [comment]
Still works fine for me in Google Chrome Версія 130.0.6723.70 (Офіційне складання) (x86_64),  MacOs Sequoia
Версія 15.0.1 (24A348)
https://github.com/user-attachments/assets/c7302bc7-96ae-43ec-9700-503b11c7c480
Could you please try again? maybe reloading could help

**Comment by nuttaa0** [comment]
Already working. Thank you.
