### ISSUE TITLE
[Add friend] Error message appears when confirming a friend request

### ISSUE THREAD

**Issue by AnastasiiaIvko** [ita-social-projects/GreenCity#7418]
**Environment:** Windows 10 Pro 
Chrome - 128.0.6613.113 (64 bit)

**Reproducible:** always

**Preconditions**
1.	User must be logged in.
2. 	Have another user send a friend request to the logged-in user

**Steps to reproduce**
1. Click on the notification icon in the upper right corner of the page and select "All messages"
2. Under the field "(Username) sent you a friend request" click "Accept"

**Actual result**
An error message is displayed 

**Expected result**
The counter of friends on My Profile page increases by 1:
a. friend’s card appears in the friends list at “All friends” tab on My Eco Friends page;
b. friend’s card disappears from “Friends requests” tab;
c. buttons “Accept request” and “Decline request” on Friend’s profile page are replaced by a button “Unfriend”.

User Story: #2084 

![Image](https://github.com/user-attachments/assets/9ea7da3e-26f7-4e49-b2e5-da2d9198cb7d)

**Comment by Lokankara** [comment]
Can you specify what message should appear when a friendship request has been successfully accepted?
possibly share a link User Story, Figma?

**Comment by AnastasiiaIvko** [comment]
I made some changes and added a user story.  According to the user story, it looks like there shouldn't be any message.

**Comment by Lokankara** [comment]
@AnastasiiaIvko  You are trying to add a friend who has already been added
Can I use the “Friend with this id has already been added ” message from the response to handle this error?

**Comment by AnastasiiaIvko** [comment]
Yes, that would be nice.
