### ISSUE TITLE
[Log in] Page not rendering in full size, scrollbar appears by default

### ISSUE THREAD

**Issue by Roksana77** [ita-social-projects/GreenCity#7424]
**Environment:** Chrome 127.0.6533.100 (64-bit).
**Reproducible:** always
**Build found:** 05.09.2024

**Preconditions**
The page GreenCity is open. 

**Steps to reproduce**
1. Check the page
2. Observe that the page loads in a smaller view by default
3. Pay attention if a vertical  scrollbar appears even when there is sufficient space to display the entire page content without scrolling
4. Pay attention for emplty space below and above the text fields that can be used for text fields and for avoiding scrollbar

**Actual result**
The page renders smaller than expected, causing a scrollbar to appear by default, making the user scroll to view the content.

![image](https://github.com/user-attachments/assets/615770a1-999d-49ac-8b9e-eec71f011bc8)

**Expected result**

The page should render in full size by default without the need for a scrollbar, fitting the visible area of the screen appropriately. If the size is smaller because of user's wish, 

**User story and test case links**

https://github.com/ita-social-projects/GreenCity/issues/6793

**Comment by kovalsofiia1** [comment]
@Roksana77 Is this an expected behaviour?

I made space on top smaller according to figma.

![Image](https://github.com/user-attachments/assets/35de905b-f995-42d1-93d9-667abdf6e64d)


If screen is too small:

![Image](https://github.com/user-attachments/assets/cfc1b233-5567-4b30-bbad-95791a9fbcc6)

**Comment by Roksana77** [comment]
@kovalsofiia1  Yes, it looks perfect.
