### ISSUE TITLE
[Header]: Incorrect dropdown menus

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#743]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit)
**Reproducible:** always
**Build found:** commit 0bf7e46

**Steps to reproduce:**
1. Go to  https://ita-social-projects.github.io/GreenCityClient/#/welcome

**Actual result:**
Dropdown menus looks incorrectly

<img width="246" alt="wrong en dropdown" src="https://user-images.githubusercontent.com/64583209/82726873-a81fe200-9cef-11ea-9e6a-212776e736b5.png">

<img width="298" alt="wrong name dropdown" src="https://user-images.githubusercontent.com/64583209/82726876-ace49600-9cef-11ea-8e1c-f00ade934cf5.png">

**Expected result:**
Dropdown menus should look like on mockup.

<img width="177" alt="correct en dopdown" src="https://user-images.githubusercontent.com/64583209/82726887-b837c180-9cef-11ea-83de-af9137457427.png">

<img width="222" alt="correct name dropdown" src="https://user-images.githubusercontent.com/64583209/82726893-bcfc7580-9cef-11ea-9fe8-9564c06fce17.png">

User story: #558

**Comment by NazariyPylypchuk** [comment]
a bug is not fixed yet
for Profile - fixed 
for Language - not fixed 
screen attached 
<img width="210" alt="Screenshot 2020-07-21 at 17 15 26" src="https://user-images.githubusercontent.com/34487672/88066260-3ab8f200-cb76-11ea-9b68-f7605b5c1fcc.png">

**Comment by Gusvarov** [comment]
It must be En-Ua-Ru, here mockup screenshot
![image](https://user-images.githubusercontent.com/54152415/88081045-8c6a7800-cb88-11ea-8989-865216a77cf7.png)

**Comment by NazariyPylypchuk** [comment]
not fixed yet
EN 
<img width="288" alt="Screenshot 2020-07-22 at 14 19 19" src="https://user-images.githubusercontent.com/34487672/88170601-a064b700-cc26-11ea-8bc0-e7bf04ce3708.png">
UA 
<img width="323" alt="Screenshot 2020-07-22 at 14 19 33" src="https://user-images.githubusercontent.com/34487672/88170669-c25e3980-cc26-11ea-8c8b-e6845f0b8be5.png">
RU
<img width="323" alt="Screenshot 2020-07-22 at 14 19 45" src="https://user-images.githubusercontent.com/34487672/88170744-db66ea80-cc26-11ea-8f32-e84d403178d1.png">

**Comment by Volodymyr-Danyliv** [comment]
At Windows 8.1 Pro is displayed correctly.

**Comment by JustinCooper43** [comment]
Drop down  has spel mistake. Instead '**Uk**' should  stand '**Ua**'

**Comment by JustinCooper43** [comment]
Drop down has spel mistake. Instead 'Uk' should stand 'Ua'

![uk](https://user-images.githubusercontent.com/64972476/91770196-6d302300-ebe9-11ea-8b9e-63aac99027e7.jpg)
