### ISSUE TITLE
[GreenCityUser, EmailNotifications] User cannot see email notification types that he/she is already using

### ISSUE THREAD

**Issue by K4sik** [ita-social-projects/GreenCity#7491]
Environment: Windows 10 Pro, Chrome 128.0.6613.139, 64-bit
Reproducible: always
Build found: 23.09.2024

Preconditions

Preconditions

Page https://www.greencity.cx.ua/#/ is opened.
The user is logged in.
Steps to reproduce

Go to "My Space";
Press "Edit Profile";
Scroll down to the section "Email Notifications".
Actual Result:
User cannot see types of email notification that he/she is already using.
![Image](https://github.com/user-attachments/assets/62fedf32-6dad-4577-9a5e-efdcff7e64ac)

Expected Result:
User see types of email notification that he/she is already using.
![Image](https://github.com/user-attachments/assets/9738e86f-9384-4053-9753-e597d6f33624)

Labels to be added
"Bug", "GreenCityUser", "Notification", "email", Priority ("pri: low"), Severity ("severity: minor"), "Functional", "API", "UI improvement".

**Comment by K4sik** [comment]
Back-end - DONE

**Comment by kryzanivska-nastya** [comment]
Front-end DONE
