### ISSUE TITLE
[Habit info] 'Progress' section on 'Habit info' page does not correspond to the mock up

### ISSUE THREAD

**Issue by AnastasiiaSmolianska** [ita-social-projects/GreenCity#7503]
**Environment:** Windows 10 Home v. 22H2, Chrome 128.0.6613.115 .
**Reproducible:** always.
**Build found:** 25.09.2024

**Preconditions**
1. User is signed in
2. User has at least one habit
3. 'My Habits' tab is opened

**Steps to reproduce**
1. Click on the pencil icon on any habit card in progress
2. Scroll down to the 'Progress' section

**Actual result**
The calendar displays days as square-shaped icons. The progress bar not on the same horizontal level with the calendar.
![image](https://github.com/user-attachments/assets/fd27fef7-9ba2-4173-9d81-335ea12076c4)

**Expected result**
According to the mockup, the calendar should display days as circlular icons.  The progress bar needs to be aligned on the same horizontal level with the calendar.
Mockup: https://www.figma.com/proto/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=37844-154515&node-type=frame&t=Cdu9uBULw8qe91h7-1&scaling=min-zoom&content-scaling=fixed&page-id=12201%3A8

**User story and test case links**

**Comment by yuliiakaras** [comment]
It was decided to unify the date icons on the habit page according to 'my space' on this mockup: https://www.figma.com/design/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=49255-18557&node-type=frame&t=iLzGsL9bodTwfeUg-0
