### ISSUE TITLE
[Habit'sPage_give up button] 'When choose "No" on give up button a notification with grammatical errors appears'

### ISSUE THREAD

**Issue by KharytonovaYuliya** [ita-social-projects/GreenCity#7512]
**Environment:** Google Chrome Version 129.0.6668.70 (Official Build) (64-bit).
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev

**Preconditions**
1. Https://www.greencity.cx.ua/#/greenCity is opened.
2. The user is logged in.
3. 'My habits' tab is active on the 'My Space' page.
4. User has at least 1 habit in progress.

**Steps to reproduce**
1. Click pencil icon on the habit's card in 'In progress' section.
2. Click 'Give up' button. 
3. Click 'No' button on the pop-up window
4. Pop-up window with the text “We glad that you change your mind” appears.
5. User is returned on 'My habits' page.

**Actual result**
A pop-up window with the following text appears: “We glad that you change your mind”. There are grammatical errors in it.

**Expected result**
The text of this message according to the user story must be the following: “We are glad that you changed your mind”

**Postconditions**

**User story and test case links**
User story https://github.com/ita-social-projects/GreenCity/issues/2167
Test case  https://jira.softserve.academy/browse/100)"](https://1242.atlassian.net/projects/SCRUM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCase/SCRUM-T10

**Labels to be added**
"Bug", Priority ("priority: low"), Severity ("severity: minor"), Type ("UI").

**Comment by nuttaa0** [comment]
@kovalsofiia1 Hello, message shoud be: “We are glad that you changed your mind”
