### ISSUE TITLE
[Delete eco news comment] wrong id comes to backend

### ISSUE THREAD

**Issue by DmytroDmytruk** [ita-social-projects/GreenCity#7517]
Environment: Google Chrome Version 129.0.6668.60 (Official Build) (64-bit).
Reproducible: always
Build found: last commit from https://github.com/ita-social-projects/GreenCity

Preconditions

https://www.greencity.cx.ua/#/greenCity is opened.
The user is logged in.
User writes some comment to eco-news
User tries to delete comment

Actual result

![Image](https://github.com/user-attachments/assets/70e32edb-ed7a-41c4-8fcd-633f673d4e7b)

![Image](https://github.com/user-attachments/assets/dc987802-d271-484d-9e75-85afcfa596cb)

Id of eco-news comes to endpoint:

![Image](https://github.com/user-attachments/assets/3a01d916-5133-45d7-b9ea-190338de8717)

Expected result
Id of comment that user wants to delete comes to backend

**Comment by MilaKomisarenko** [comment]
Fixed
![image](https://github.com/user-attachments/assets/23ba85f1-5c37-4c40-a631-6109408dcdc6)

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/8d66608a-51e9-4122-a7b9-0c0244f5a67e)

![Uploading image.png…]()

**Comment by Roksana77** [comment]
![image](https://github.com/user-attachments/assets/d295b8d9-4973-46e0-9a08-3bf9a0b7c152)

![image](https://github.com/user-attachments/assets/d1eff180-8866-4baa-b609-9929c7238496)
