### ISSUE TITLE
[Affected functionality] Clear and concise summary, e.g. "[Create news] 'Publish' button is not displayed on the 'Preview' page"

### ISSUE THREAD

**Issue by KharytonovaYuliya** [ita-social-projects/GreenCity#7522]
**Environment:** Version 129.0.6668.71 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev

**Preconditions**

1. https://www.greencity.cx.ua/#/greenCity is opened.
2. 'My habits' page is opened.
3. User clicked 'Add New habit' button on 'My habits' page.
4. 'All habits' page is opened.
5. Any habit is chosen and 'More' button is clicked.
6. 'Invite friends' button on Habit's description page is clicked.

**Steps to reproduce**
1. Enter to the text field 'Search friend'  a part of the correct name of a friend which contains special characters, e.g. "" (quotes).

**Actual result**
Search by special characters (e.g. quotes) in the name doesn`t produce result.

**Expected result**
According to the user story user can add 3 – 15 symbols ( letters, numbers, special characters) to the field.

**User story and test case links**
User story https://github.com/ita-social-projects/GreenCity/issues/4772 
Test case https://1242.atlassian.net/projects/SCRUM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCase/SCRUM-T95

**Labels to be added**
"Bug", Priority ("priority: medium"), Severity ("severity: medium"), Type ("Functional")

**Comment by kovalsofiia1** [comment]
@KharytonovaYuliya while i`m searchilg with special characters ( - ; ' ) i get the result
![Image](https://github.com/user-attachments/assets/cf7af651-3142-459d-b327-6ab1859013b3)
![Image](https://github.com/user-attachments/assets/fbaa561f-84a3-4f4a-a2e5-bc81a58d5548)

in this issue allowed special characters are described
[https://github.com/ita-social-projects/GreenCity/issues/4277](https://github.com/ita-social-projects/GreenCity/issues/4277)

**Comment by Mikusja** [comment]
![Image](https://github.com/user-attachments/assets/7e8ccd1f-b921-45d0-a73f-5ca2a1acc9d9)

Works fine
