### ISSUE TITLE
[Friends page] The text does not fit in the button when the Ukrainian language is selected

### ISSUE THREAD

**Issue by AnastasiiaIvko** [ita-social-projects/GreenCity#7526]
**Environment:** 
Windows 10 Pro (64 bit)
Chrome 129.0.6668.60 
Firefox 130.0.1

**Preconditions**
1. The user is logged into the system.
2. The Ukrainian language is selected.
3. The "Друзі" page is open.

**Steps to reproduce**
1. Go to "Знайти друга" tab
2. Click the "Додати" button on the card of any recommended friend

**Actual result**
The "Додати" button changed to a "Скасувати запит" button, the text of which extends beyond the button.

**Expected result**
The "Додати" button changed to a "Відхилити" button, the text of which should fit within the button.

![Image](https://github.com/user-attachments/assets/6efeadf0-91ad-4e85-9bba-8e33718b3f42)

**Comment by kovalsofiia1** [comment]
@AnastasiiaIvko should this button be just longer than others or all btns on the page should become the same?
![Image](https://github.com/user-attachments/assets/19ebe3f9-dfe6-4fbb-9691-0d34e2d59498)

**Comment by AnastasiiaIvko** [comment]
@kovalsofiia1 Sorry, changes have been made. 
"Скасувати запит" should be replaced with "Відхилити"
