### ISSUE TITLE
[Add address] User can not add a new address on 'Order form' page on 'Personal data' tab

### ISSUE THREAD

**Issue by Mikusja** [ita-social-projects/GreenCity#7537]
**Environment:** Windows 10 Home 

1. Microsoft Edge Version 128.0.2739.67
2. Google Chrome Version 129.0.6668.60
3. Mozilla Firefox  130.0.1

**Reproducible:** always

**Build found:** 01/10/2024

**Preconditions**
1. User is signed in, https://www.greencity.cx.ua/#/ubs
2. The Order form is opened

**Steps to reproduce**
1. On the 'Order details' tab choose required packages 
2. Click on 'Next'
3. On the 'Personal data' tab fill in all required fields
4. Click on 'Add new address'
5. Fill in all required fields
6. Click on 'Add address'

**Actual result**
1. Appears message ' New address added'
2. Appears error message
3. Appears loader
4. New address is NOT added

**Expected result**
1. Appears message ' New address added'
2. New address is added

**Postconditions**

**User story and test case links**
"User story " https://github.com/ita-social-projects/GreenCity/issues/2199
"Change request" https://github.com/ita-social-projects/GreenCity/issues/2533

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Mikusja** [comment]
![Image](https://github.com/user-attachments/assets/39ecd7f6-9f4e-48e4-ad9b-30e8c35b0966)

Firefox

**Comment by Mikusja** [comment]
![Image](https://github.com/user-attachments/assets/375afd56-a93a-411c-8be7-58d3acfa99bd)

MS Edge

**Comment by Mikusja** [comment]
https://drive.google.com/file/d/1SPkJqt7gC7PNmWajR5RNaEbDpgOnsYYZ/view?usp=drive_link

Chrome variation

**Comment by kovalsofiia1** [comment]
It must have been fixed

**Comment by Mikusja** [comment]
Hi Sofiia,

Sorry for the bad news on Monday, but it still don`t work as needed. I retested it through the weekend, and it had 400 bad requests, or just not added address. So, I transferred it back to bugs.

Best regards,
Solomija

________________________________

**Comment by KizerovDmitriy** [comment]
what address you enter to reproduce this bug?

**Comment by Mikusja** [comment]
Hi, Dmytro

I tried to add different addresses but it didn`t work. (I put the video in the comments) I can try it again and record the new screen video while trying. If you need it, just let me know.
Also, I need some clarification about the district field. It is one of mandatory data, but it is blocked for input, may you unblock it?

Best regards,
Solomija

________________________________
