### ISSUE TITLE
[Notifications popup] A notifications popup doesn`t correspond to mockup in Figma

### ISSUE THREAD

**Issue by KharytonovaYuliya** [ita-social-projects/GreenCity#7555]
**Environment:** Version 129.0.6668.71 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev

**Preconditions**

1. User is logged in https://www.greencity.cx.ua/#/profile.
2. 'My Space' page is opened.

**Steps to reproduce**
1. Click 'Bell' icon on 'My Space' page.

**Actual result**
After clicking 'Bell' icon a notification popup appears but it doesn`t correspond to the mockup. There is no any additional information about notification.

**Expected result**
After clicking a 'Bell' icon a notification popup appears which must correspond to the following mockup: https://www.figma.com/proto/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?node-id=43072-82695&node-type=frame&t=emftLoasxApeF5mf-1&scaling=min-zoom&content-scaling=fixed&page-id=12201%3A2

**User story and test case links**
User story https://github.com/ita-social-projects/GreenCity/issues/6336)
[Test case] https://jira.softserve.academy/browse/100)"](https://1242.atlassian.net/projects/C2?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCase/C2-T4

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("UI")

**Comment by kovalsofiia1** [comment]
Hi! Additional information appears on clicking on notification. Notifications were made expandable so that they would be of the same size. I added toggle button so that user could understand that he should click the notification.


https://github.com/user-attachments/assets/2892d397-dee6-4a0e-b7de-6e80b630a4fd
