### ISSUE TITLE
User can choose email notification periodicity

### ISSUE THREAD

**Issue by ToriForH** [ita-social-projects/GreenCity#7560]
As User I want to choose how often I get notifications via email for each notification **type**(SYSTEM, LIKES, COMMENTS, INVITES)

**Acceptance Criteria**

When User navigates to edit profile page through 'My Space'.
User can see their email preferences with one value of **periodicity** for each **type**.
User can change **periodicity** for each **type** individually.
Acceptance **periodicities**: **IMMEDIATELY, TWICE_A_DAY, DAILY, WEEKLY, MONTHLY**.
**IMMEDIATELY**: email notification send to user email as soon as notification was created.
**TWICE_A_DAY**: email notification send to user twice a day(in the morning and in the evening) with a summary of new updates.
**DAILY**: email notification send to user once a day(in the morning) with a summary of new updates.
**WEEKLY**: email notification send to user once a week(on Monday) with a summary of new updates.
**MONTHLY**: email notification send to user once a month(on 1st day of month) with a summary of new updates.

**Comment by Mikusja** [comment]
![Image](https://github.com/user-attachments/assets/a95b7d25-5e38-4f0b-9958-6dfd71d649ff)
Works fine
