### ISSUE TITLE
[UBS Confirmation page] The confirmation page does not match the mocap

### ISSUE THREAD

**Issue by OlhaNechaieva** [ita-social-projects/GreenCity#7565]
Environment:
Windows 11 Pro Version 23H2, x64
Google Chrome Version 128.0.6613.137 (Official Build) (64-bit)
Microsoft Edge Version 129.0.2792.52 (Official build) (64-bit)

Reproducible: always

Preconditions

Go to the https://www.greencity.cx.ua/#/ubs website
Log in
Location selected
The 'Order details' tab and 'Personal data' are filled in
The 'Confirmation' tab is active

Steps to reproduce:

Click the 'Cancel' button
Click 'Yes, save' in the pop-up window

Actual result:

The 'Сonfirmation' tab closes with all filled tabs
Redirect to the confirmation page.
![Image](https://github.com/user-attachments/assets/ea93ea9c-b39b-4f21-93a0-2687d01ab2a4)

Expected result:
![Image](https://github.com/user-attachments/assets/50fcb398-9ae7-4ccf-b52e-637a27b97622)

Mockup:
https://www.figma.com/design/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=13760-122&t=BdjYOl13pcFojh9a-1

**Comment by yuliiakaras** [comment]
Please, note that according to the customer's new requirements, we need to use a green bag instead of a black one

**Comment by AnastasiiaIvko** [comment]
The page still doesn't match the mockup. No message "Тепер ви можете знайти своє замовлення №... у Вашому особистому кабінеті та продовжити його оформлення в будь-який час" , no button "До особистого кабінету" either.

**Comment by nuttaa0** [comment]
The message "Тепер ви можете знайти своє замовлення №... у Вашому особистому кабінеті та продовжити його оформлення в будь-який час". Appeared only for 3 seconds and Dissapeared very fast so user can't finish to read it. Could you add 3 seconds more for showing it, please. Also the place where message appeared doesn't match to mockup.
https://github.com/user-attachments/assets/c9ed6332-467d-4abe-b4fa-56c1d5c9f8ba

**Comment by OlegDemkiv10** [comment]
The confirmation page matches with the mocap
