### ISSUE TITLE
[UBS Certificate field] The certificate number cannot be edited

### ISSUE THREAD

**Issue by OlhaNechaieva** [ita-social-projects/GreenCity#7568]
Environment:
Windows 11 Pro Version 23H2, x64
Google Chrome Version 128.0.6613.137 (Official Build) (64-bit)
Microsoft Edge Version 129.0.2792.52 (Official build) (64-bit)

Reproducible: always

Preconditions

1. Go to the https://www.greencity.cx.ua/#/ubs website
2. Log in
3. Location selected
4. The 'Order details' tab is active

Steps to reproduce:

1. Click on the input field below the 'Certificate number' text
2. Input the certificate number
3. Click the Activate button
4. Click on the filled input field again

Actual result:
1. The field frame has turned green
2. Editing is not possible

https://github.com/user-attachments/assets/145afac8-94f9-4ee4-90df-72179539bdaf

Expected result:

Can edit the number of the entered certificate

**Comment by kovalsofiia1** [comment]
@borntoshine1 You should clear the field by pressing 'Cancel' and then input another certificate number
as is deccribed in user story [#2329 ](https://github.com/ita-social-projects/GreenCity/issues/2329)

https://github.com/user-attachments/assets/491cf478-c304-4891-81eb-5a8795d8342c
