### ISSUE TITLE
BUG [API] Missing checkbox labels in 'My goals' section in My cabinet and pop up window

### ISSUE THREAD

**Issue by greatpanda1603** [ita-social-projects/GreenCity#759]
![image](https://user-images.githubusercontent.com/52715377/83018234-9ad76000-a02d-11ea-90eb-d233f9cb5925.png)
![image](https://user-images.githubusercontent.com/52715377/83018282-b0e52080-a02d-11ea-8ec4-c4870ff9439b.png)

**Comment by MariaKorniavka** [comment]
Not relevant
