### ISSUE TITLE
500 on add friend

### ISSUE THREAD

**Issue by holotsvan** [ita-social-projects/GreenCity#7600]
**Environment:** OS: Ubuntu 22.04.4 LTS x86_64, Chrome
**Reproducible:** always

**Preconditions**
User is loged in

**Steps to reproduce**
1. Go to "My Space"
2. Click on '+' at My Friedns section
3. Go to "Find a friend"
4. Click on "Add friend" at any user

**Actual result**
500 status code
![Image](https://github.com/user-attachments/assets/bdb1d24b-0c00-4c8e-bcca-e22065979af4)

**Expected result**
friend is added, notification about adding to friends is send

**Comment by MilaKomisarenko** [comment]
Fixed
![image](https://github.com/user-attachments/assets/65b631ef-1aad-4d32-99a0-76f2c406dff0)
