### ISSUE TITLE
[Achievements] Server response 500 on GET /achievements?achievementCategoryId=5

### ISSUE THREAD

**Issue by ToriForH** [ita-social-projects/GreenCity#7608]
**Preconditions**
Log in to the system as an user. User must have 2 and more habits assigned.

**Steps to reproduce**
On the My Space page, near Achievements click the "See All" button.
On the pop-up window with list of achievements category click on "Acquire Habit" section.

**Actual result**
No achievements displayed. Network response code 500 Internal Server Error(see screeshot image).

**Expected result**
The user achievements by habit succesfully displayed for each tracked habit or 3 default achievements displayed if user has no tracked habits.
![Image](https://github.com/user-attachments/assets/56d263a9-ac58-435a-80d9-a8aa6bc8a052)

**Comment by Mikusja** [comment]
Works fine 
![Image](https://github.com/user-attachments/assets/8b3df3db-8e50-4896-b4a1-4b5b90278c0a)
