### ISSUE TITLE
[API Swagger] Certain notification types can`t perform in GET/notifications endpoint

### ISSUE THREAD

**Issue by AnastasiiaSmolianska** [ita-social-projects/GreenCity#7609]
**Environment:** Windows 10 Home v. 22H2, Chrome 128.0.6613.115.
**Reproducible:** always.
**Build found:** 11.10.2024

**Steps to reproduce**
1. Go to https://greencity.greencity.cx.ua/swagger-ui/index.html#/notification-controller/getNotificationsFiltered
2. Click on 'Try it out'
3. Scroll the 'Notification-types' listbox to the 'Habit' section

**Actual result**
The notification-types such as 'HABBIT_LIKE', 'HABBIT_COMMENT', 'HABBIT_COMMENT_LIKE', 'HABBIT_COMMENT_REPLY','HABBIT_COMMENT_USER_TAG' is available for execution, but this functions does not exist on the 'GreenCity' site.
![Image](https://github.com/user-attachments/assets/451e58f2-5d55-45bb-83fc-30c466c1afa0)

**Expected result**
The notification-types such as 'HABBIT_LIKE', 'HABBIT_COMMENT', 'HABBIT_COMMENT_LIKE', 'HABBIT_COMMENT_REPLY','HABBIT_COMMENT_USER_TAG' should not be visible and available for execution in case of related functions does not exist on the 'GreenCity' site.

**Comment by ToriForH** [comment]
![Image](https://github.com/user-attachments/assets/18d99fd5-d285-40b7-b127-052a861340fa)
There are functional for commenting habits in habit comment controller. This feature will be implemented by front-end in future.
