### ISSUE TITLE
[API] (Check if certificate is available) Wrong 200 OK status code instead of 400 when enter invalid userUuid

### ISSUE THREAD

**Issue by nuttaa0** [ita-social-projects/GreenCity#7610]
**Environment:** OS: MacOS Sonoma version 14.6, browser: Google Chrome Version 128.0.6613.138 (x86_64)
**Reproducible:** always

**Preconditions**
1. [https://greencity-ubs.greencity.cx.ua/swagger-ui/index.html#/order-controller/checkIfCertificateAvailable](https://greencity-ubs.greencity.cx.ua/swagger-ui/index.html#/order-controller/checkIfCertificateAvailable) is opened
2. User is logged in

**Steps to reproduce**
1. Click 'Try it out' button
2. Enter valid responseCode (e.g. 9876-9876)
3. Enter invalid userUuid (e.g. kjkh_89??)
4. Click 'Execute' button

**Actual result**
The status code is 200 OK.

**Expected result**
Status code is 400 Bad Request

**Labels to be added**
"Bug", "API"

**Comment by holotsvan** [comment]
Fixed and could not be reproduce.

We could not  "Enter invalid userUuid (e.g. kjkh_89??)" anymore
