### ISSUE TITLE
[My Space] Fact of the day updates on every page reloading

### ISSUE THREAD

**Issue by yuliiakaras** [ita-social-projects/GreenCity#7616]
Environment: Windows 10, Chrome 128.0.6613.114, 64-bit.
Reproducible: always
Build found: 14.10.2024

**Steps to reproduce:**
1. Login as user
2. Go to 'My space'
3. Pay attention to the 'Fact of the day' card
4. Reload page or change language

**Actual result:**
Fact of the day has different content
https://github.com/user-attachments/assets/d85028bf-7178-4ee5-9c71-8324a4468f00

**Expected result:**
Content of 'Fact of the day' changes every day (every 24 hours), not every reload

**Comment by Mikusja** [comment]
There is no content now 
1. MS Edge 
![Image](https://github.com/user-attachments/assets/71bdbc60-7a07-4e00-a4e0-e414e9c02efd)

2. Google Chrome
![Image](https://github.com/user-attachments/assets/8f5c8f00-b211-420c-a254-7ffb62259dfe)

3. Mozilla Firefox
![Image](https://github.com/user-attachments/assets/f7f6f129-83f2-4812-b26d-aa7976a20356)

4. Mozilla Firefox incognito
also here is only green box with fact of the day
![Image](https://github.com/user-attachments/assets/87459453-1ca4-4623-af13-2c47be8dd6b2)

**Comment by yuliiakaras** [comment]
Adding 2 languages to the fact of the day was implemented and merged on the backend side, but it is still under review on the front end

**Comment by Mikusja** [comment]
Hi,
Ok.
I will check it in the end of the week again.
If you know some news earlier, please share with me.

Have a nice day
Solomija

________________________________
