### ISSUE TITLE
[Display news: Gallery view] Gallery view of News page has 1 column in 576px screen resolution, instead of 2 columns

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#762]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Preconditions:**

1. https://ita-social-projects.github.io/GreenCityClient/#/news is opened.
2. Eco news page is opened, Gallery view is selected.

**Steps to reproduce:**
1. Change screen resolution to 576px.

**Actual result:**
1 column is displayed with 576px screen resolution.

**Expected result:**
2 columns are displayed with 576px screen resolution.

User story: #459 
![Screen resolution 576px](https://user-images.githubusercontent.com/64582769/83153380-8f586780-a107-11ea-9ebf-5dd02e6a4bf8.png)
![Mockup screen resolution 576px 2columns](https://user-images.githubusercontent.com/64582769/83153700-eeb67780-a107-11ea-85d2-ecfc29986d08.png)

**Comment by BohdanPrysiazhnyi** [comment]
https://github.com/ita-social-projects/GreenCity/issues/999
Only list view is present.
