### ISSUE TITLE
[Create/Edit event] Text editor looses focus on each character input

### ISSUE THREAD

**Issue by kovalsofiia1** [ita-social-projects/GreenCity#7620]
Environment: Windows 11 Home, 64-bit
Reproducible: always
Build found: 14.10.2024

**_Preconditions_**

Page https://www.greencity.cx.ua/#/events/create-event is opened.
The user is logged in.

_**Steps to reproduce**_
1. Try to inpur event description 

**_Actual result :_**
Text editor looses focus after user inpurs one character
https://github.com/user-attachments/assets/86dce686-74e4-4e6b-b000-0f5f144e4b6a

**_Expected result:_**
User can input text without need to focus on editor each time

**Comment by Mikusja** [comment]
1. Space is trimmed 
![Image](https://github.com/user-attachments/assets/74defd1a-f51c-4fba-8d27-db4d8e341261)

**Comment by Mikusja** [comment]
Hi Yuliia,
Great news!
Thank you,
Solomija
________________________________
