### ISSUE TITLE
[API] [Swagger] The body in some POST, PUT requests can be created only using form-data

### ISSUE THREAD

**Issue by RadchenkoVlada** [ita-social-projects/GreenCity#7621]
**Environment:** macOS Sonoma 14.5, Swagger, Postman
**Reproducible:** always
**Build found:** 14.10.2024

**Preconditions**
1) Make an authorization in Swagger(bearerAuth).

**Steps to reproduce**
1. Go to [swagger/event-controller](https://greencity.greencity.cx.ua/swagger-ui/index.html#/event-controller)
2. Click on dropdown sign ![Image](https://github.com/user-attachments/assets/50027d14-a76d-4449-bf85-895f17004be8)  POST /events Create new event 
3. Choose the request body ![Image](https://github.com/user-attachments/assets/603b3b65-c413-4728-a20a-6bbfd129d01c) (application/json)
4. Click on "Execute" button
5. Repeat steps 2-4 for :

-  event-controller: editEvent
- EcoNewsCommentsService: addComment
- EventsCommentsService: addComment
- changeCustomHabit

**Actual result**
The response status code is 413 Request Entity Too Large. This result is expected because application/json content type is not supported. The problem is only in documentation.
![Image](https://github.com/user-attachments/assets/8a0700fe-ee8e-4572-ae99-abb0447d9b01)

**Expected result**
Dropdown for the request body(content type) contains ONLY -  multipart/form-data
![Image](https://github.com/user-attachments/assets/fc2dade8-0845-4801-bb1b-cc10512ed969)

**Labels to be added**

**Comment by K4sik** [comment]
I've also made the same changes in EcoNewsController for saving and updating News and in HabitController for saving custom habits.
