### ISSUE TITLE
Add a comment to the piece of news or tips&tricks

### ISSUE THREAD

**Issue by TetiShel** [ita-social-projects/GreenCity#763]
**As a** Logged User **I want** to add a comment to the piece of News or to the Tips & Tricks **so that** I can share my thoughts with other users. 

_Tab.1 'Add Comment' Attributes_

|# | Name | Type | Condition | Value/Restriction|
-- | -- | -- | -- | --
1 | Add a comment | Input Text, alphanumeric and Special characters| Mandatory,Enable | max characters number - 8000min characters number - 1, except ‘space character’.
2 | Added comment | Text, alphanumeric and Special characters| Disable | max characters number - 8000min characters number - 1, except ‘space character’.
3 | Comment | Button | Enable/ Disable | When Attribute 1 isn’t valid, the button is disabled.When Attribute 1 is valid, the button is enabled.
4 | Avatar | Picture | Disable | The avatar of the user who added the comment
5 | User name | Text | Disable | The name of the user who added the comment
6 | Date | Text, date format[Mont Day, Year] | Disable | The date when the user added the comment

_Mockup_: News_page_registered_my

**Acceptance Criteria:**

1. Only registered and logged user can add a comment to the piece of news.
2. Only registered and logged user can add a comment to the Tips & Tricks.
3. Logged User can add a comment on the  ‘News’ page (News Single View). 
4. Logged User can add a comment on the ‘Tips $ Tricks’ page (Tips & Tricks Single View).
5. Logged User can publish some text pressing the ‘Comment’.
6. When Logged User presses the ‘Comment’ button:
a) the system saves the comment and displays below,
b) the system displays the date of the comment publishing,
c) the system recalculates the number of the total comments and updates it on the News Single Page or Tips & Tricks Single Page.
d) the system displays the author-name and avatar related to the comment 
7. All users (registered and not registered) can review all related to the piece of news or o the Tips $ Tricks comments. 
8. All Tab.1 Attributes are valid.
9. Breakpoints 1140, 1024, 768, 576, 320 are done due to provided mockups.

**Comment by ViktoriyaRyazhska** [comment]
Done without Tips&Tricks functionality
