### ISSUE TITLE
[Display news: Gallery view] Image is not aligned to Content according to mockup in screen resolution 320px.

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#764]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Preconditions:**
1. https://ita-social-projects.github.io/GreenCityClient/#/news is opened.
2. Eco news page is opened, Gallery view is selected.

**Steps to reproduce**
1. Change screen resolution on News page in Gallery view on  320px.

**Actual result:**
Image is not aligned to Content according to mockup in screen resolution 320px

**Expected result:**
Image is aligned to Content according to mockup in screen resolution 320px

User story: #459

![320px image](https://user-images.githubusercontent.com/64582769/83426418-c2686700-a437-11ea-813c-e093039105e2.png)
![mockup 320px](https://user-images.githubusercontent.com/64582769/83426426-c6948480-a437-11ea-8c65-1174773b04c1.png)

**Comment by JustinCooper43** [comment]
**Bug was not fixed**

1. Image and header stay without changing.
2. Location of date and name not centralized.
3. 'Edit news' button is adsent.

**P. S.** 
Related bugs[ #1045](https://github.com/ita-social-projects/GreenCity/issues/1045)

**Actual result**
![Single View 320](https://user-images.githubusercontent.com/64972476/89100869-78820a00-d403-11ea-982a-fb870e486982.jpg)


**Expected result**

![Single View 320 correct](https://user-images.githubusercontent.com/64972476/89100870-7e77eb00-d403-11ea-9ce0-9f0da75e7be1.jpg)

**Comment by RomanDeveloperAcc** [comment]
Not relevant
