### ISSUE TITLE
Like a Comment/Reply

### ISSUE THREAD

**Issue by TetiShel** [ita-social-projects/GreenCity#766]
**As** a Logged User **I want** to like the comment or reply on the News Single Page or on the  Tips & Tricks Single Page **so that** I can specify the comments I like. 

_Mockup: News_page_registered_my_

**Acceptance Criteria:**
1. Only registered and logged user can like the comment/ reply on the News Single Page.
2. Only registered and logged user can like the comment/reply on the Tips & Tricks Single Page.
3. Logged User can like a comment/ reply just one time.
4. When Logged User likes the comment/reply a second time the system identifies it as dislike. 
5. The system displays the total likes number bellow the comment/reply.
6. User can like just the other user’s comments/replies.
7. When Logged User likes the comment/reply the system recalculates the total likes number.
8. When Logged User likes the comment/reply the 'like' button is highlighted in green.
9. When Logged User likes the comment/reply a second time the system recalculates the total likes number excluding the like. 
10. When Logged User likes the comment/reply a second time the 'like' button shouldn't  highlighted in green.
11. All users can see the total likes number related to the comments and/or replies.

**Comment by ViktoriyaRyazhska** [comment]
Done without Tips&Tricks functionality
