### ISSUE TITLE
[GreenCityUBS] Implement Notification Management Features

### ISSUE THREAD

**Issue by K4sik** [ita-social-projects/GreenCity#7669]
### Controller Updates:
1. Add new endpoints in NotificationController.java to handle user notifications:
 - viewNotification(): Mark a notification as viewed.
 - unreadNotification(): Mark a notification as unread.
 - deleteNotification(): Delete a notification for a user.

### Service Layer Implementation:
2. In NotificationService.java and NotificationServiceImpl.java, add methods to manage notification statuses:
 - viewNotification(): Logic will mark notifications as viewed.
 - unreadNotification(): Logic will mark notifications as unread.
 - deleteNotification(): Logic will delete notifications for users by marking them as deleted.

### Repository Updates:
3. In UserNotificationRepository.java, add methods:
 - markNotificationAsViewed(): Update notification to be marked as viewed.
 - markNotificationAsNotViewed(): Update notification to be marked as unread.
 - deleteUserNotificationByIdAndUserId(): Delete a notification by notification ID and user ID by marking it as deleted.
 - existsByIdAndUserId(): Check if a notification exists by notification ID and user ID.
 
### Testing:

4. Write unit tests to cover the new methods in the service and repository layers.
 - Ensure all endpoints in NotificationController.java are thoroughly tested for correctness.

**Comment by holotsvan** [comment]
All methods outlined in the task have been implemented and merged into the codebase. Therefore, I am considering this task as 'Done' and "Ready for testing".
