### ISSUE TITLE
[Display news: Gallery view] Content items in a server response are displayed in the not same order as in a Data Base

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#769]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Steps to reproduce**
1. Go to DB (DataGrip) and run the script: "SELECT * FROM eco_news ORDER BY creation_date DESC;";
2. Go to Swagger: https://greencity.azurewebsites.net/swagger-ui.html?fbclid=IwAR0H_eRDHYKBdTAr8WeoAk2TCdczN3TPXUc-8S4Wxnzw6enlkMgXVGEVFxs#/eco-news-controller/findAllUsingGET;
3. Click on eco-news-controller;
4. Set '1' value into 'page' field;
5. Set number of records for viewing in 'size' field (e. g.: 12);
6. Set 'desc' value in a 'sort' field;
7. Click on 'Execute' button.
8. Compare content items in DB and in the Swagger.

**Actual result:**
Content items in a server response are displayed in the not same order as those displayed in a Data Base.

**Expected result:**
Content items in a server response are displayed in the same order as those displayed in a Data Base.
![Swagger ](https://user-images.githubusercontent.com/64582769/83169415-ad2fc780-a11b-11ea-84f2-eeceef7db236.png)
![DB](https://user-images.githubusercontent.com/64582769/83169925-6b535100-a11c-11ea-8c04-e865844438de.png)

User story: #459

**Comment by Yulia-H** [comment]
Not a bug

**Comment by natalinapr** [comment]
**Environment**: OS: Windows 10 Pro, Version 2004
**Browser:** Mozilla Firefox, Version: 82.0.3
**Reproducible:** always
**Build found:** last commit from 21.11.2020

**Steps to reproduce**

1. Go to DB (DataGrip) and run the script: "SELECT * FROM eco_news ORDER BY creation_date DESC;";
2. Go to Swagger: https://greencity.azurewebsites.net/swagger-ui.html?fbclid=IwAR0H_eRDHYKBdTAr8WeoAk2TCdczN3TPXUc-8S4Wxnzw6enlkMgXVGEVFxs#/eco-news-controller/findAllUsingGET;
3. Click on eco-news-controller;
4. Set '1' value into 'page' field;
5. Set number of records for viewing in 'size' field (e. g.: 12);
6. Set 'desc' value in a 'sort' field;
7. Click on 'Execute' button.
8. Compare content items in DB and in the Swagger.

**Actual result:**
Content items in a server response are NOT displayed in the same order as those displayed in a Data Base.
![DB](https://user-images.githubusercontent.com/62031226/99878769-4db8fd00-2c10-11eb-9e76-ec68e604fbe7.png)
![image](https://user-images.githubusercontent.com/62031226/99878777-5dd0dc80-2c10-11eb-8743-28c678f7c4c5.png)


**Expected result:**
Content items in a server response are displayed in the same order as those displayed in a Data Base.

[Verify that Content items are displayed in a chronological order starting from the most recent] (https://jira.softserve.academy/browse/GC-337)
