### ISSUE TITLE
[Comment,  email Notifications] User doesn't receive notifications in case of chosen option 'daily', 'twice a day' for it 

### ISSUE THREAD

**Issue by Roksana77** [ita-social-projects/GreenCity#7699]
**Environment:** Windows 10, Chrome 127.0.6533.89, 64-bit.
**Reproducible:** always.
**Build found:** 25.10.2024

**Preconditions**
The page https://www.greencity.cx.ua/#/events is opened.
The user is logged in.

Steps to reproduce

**Steps to reproduce**
1.User 1 chooses 'daily' for notification in the setting of the profile and create own event.
2. User 2 comments the event of User 1. 
3.User 1 checks the notifications on email next day.
4. User 1 chooses 'twice a day' for notification in the setting of the profile.
5.User 2 comments the  event of User 1 again. 
6.User 1 checks the notifications on email till the end of the day.

**Actual result**
The user doesn't receive notifications on email about comments next day, when he/she has status 'daily'. The user doesn't receive notifications on email about comments till the end of the day, but he/she has status 'twice a day'. These statuses work as status 'never'.

**Expected result**
With 'daily' status for getting notifications user gets notifications on email about new comments at least next day. With 'twice a day' status user gets notification on email about new comments at least till the end of the day.

User story and test case links
https://github.com/ita-social-projects/GreenCity/issues/4665

**Comment by ToriForH** [comment]
Bug ready for retesting
