### ISSUE TITLE
[Display news, Gallery view] Size of icons near Date and Author are not aligned and not correct size.

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#772]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Preconditions:**
1. https://ita-social-projects.github.io/GreenCityClient/#/news is opened.

**Steps to reproduce**
1. Click F12 to verify UI of Date and Author format.

**Actual result:**
1. Size of Icon near Date is 12-14, icon near Author is 12-13.
2. Icons near Date and Author are not aligned, according to mockup.
3. Color of Date and Author format is #666666

**Expected result:**
1. Size of Icon near Date is 11-12, icon near Author is 12-12.
2. Icons near Date and Author are not aligned, according to mockup. 
3. Color of Date and Author format is #878787

User story: #459, #538 

![icon1](https://user-images.githubusercontent.com/64582769/83194002-994a8c80-a140-11ea-8bf2-f13867c5c64e.png)
![icon2](https://user-images.githubusercontent.com/64582769/83194366-39a0b100-a141-11ea-9701-afd0b3fea92d.png)
![mockup icon1](https://user-images.githubusercontent.com/64582769/83194378-3d343800-a141-11ea-94be-3086be6d8448.png)
![mockupicon2](https://user-images.githubusercontent.com/64582769/83194396-42918280-a141-11ea-914a-f7a9ec7a8ada.png)
![Alignment](https://user-images.githubusercontent.com/64582769/83194413-4ae9bd80-a141-11ea-807f-c80c91850cbc.png)
![mockup2](https://user-images.githubusercontent.com/64582769/83194430-4fae7180-a141-11ea-9435-ea2e623c4d22.png)
![color](https://user-images.githubusercontent.com/64582769/83266646-ca23d380-a1cb-11ea-9e57-409c26b3e973.png)
![color mockup](https://user-images.githubusercontent.com/64582769/83266668-d0b24b00-a1cb-11ea-9b0c-a0d0b532ef66.png)

**Comment by JustinCooper43** [comment]
Bug was not fixed

**Date**
![1214](https://user-images.githubusercontent.com/64972476/91770831-9309f780-ebea-11ea-91da-b8970a160f72.jpg)

 **Author**
![1213](https://user-images.githubusercontent.com/64972476/91770833-943b2480-ebea-11ea-99ff-2dd900c47364.jpg)

**Comment by krivondulia** [comment]
Not fixed size and color.
Mozilla Firefox 82.0, Windows 10 Home/Pro

**Comment by bohdana1** [comment]
Not fixed
Actual result: size of Icon near Date is 11-14, icon near Author is 12-14.
