### ISSUE TITLE
[Display news, Gallery view] Size of tag 'News' and distance between Content and Date  are not correct according to mockup.

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#773]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Preconditions:**
1. https://ita-social-projects.github.io/GreenCityClient/#/news is opened.

**Steps to reproduce**
1. Click F12 to verify UI of Content elements

**Actual result:**
1. Size of tag 'News' is 69.02-32.
2. Distance between Content and Date is 8px.

**Expected result:**
1. Size of tag 'News' is 68-30.
2. Distance between Content and Date is 16px.

User story: #459

![tag News](https://user-images.githubusercontent.com/64582769/83195324-ba13e180-a142-11ea-8e37-d385c3816b9f.png)
![mockup](https://user-images.githubusercontent.com/64582769/83195335-bda76880-a142-11ea-9441-0381c9bf23e7.png)
![8px](https://user-images.githubusercontent.com/64582769/83195704-53db8e80-a143-11ea-990b-f193aa625e4e.png)
![distance 16px](https://user-images.githubusercontent.com/64582769/83195732-5dfd8d00-a143-11ea-8f26-7b5bdc926315.png)

**Comment by KimAT25** [comment]
About issue #1: first of all width of tag will be dynamic, according to the text inside, on mockup it`s only sample. Height of tag don`t include on mockup border size of line. That`s why tag has height 32px;
Second part of these bugs in progress.

**Comment by Yulia-H** [comment]
Second point fixed
