### ISSUE TITLE
[Edit profile] When we have an unchecked checkbox of notification but change from never to another periodicity it doesn't save periodicity

### ISSUE THREAD

**Issue by kryzanivska-nastya** [ita-social-projects/GreenCity#7733]
**Environment:**
Windows 11 Pro Version 23H2, x64
Google Chrome Version 128.0.6613.137 (Official Build) (64-bit)

**Preconditions**

Go to the https://www.greencity.cx.ua
Log in
Go to the page 'My space'
Click on edit profile
While having unchecked checkbox in the email notifications, change from never to another periodicity, click save

**Actual result:**
The checkbox is unchecked and the periodicity is never

**Expected result:**
The checkbox is checked and the periodicity which has been chosen is there

**Comment by Roksana77** [comment]
![Image](https://github.com/user-attachments/assets/656fdc10-2a8f-4939-b60e-ff14562e8eee)
