### ISSUE TITLE
[Events] Error on selecting favorite events when not signed in

### ISSUE THREAD

**Issue by kovalsofiia1** [ita-social-projects/GreenCity#7739]
**_Preconditions:_**
Open https://www.greencity.cx.ua/events
User is not signed in

**_Steps to reproduce:_**
Click on favorite events

**_Actual result:_**
User gets an error and infinite loading
https://github.com/user-attachments/assets/8c7871f1-0257-4ffc-bbac-2ab9b2a20ae6

**_Expected result:_**
User is asked to log in

**Comment by Roksana77** [comment]
It asks to log in
![Image](https://github.com/user-attachments/assets/d49a41ef-1331-404a-94dd-e8d32c7e3ddf)
