### ISSUE TITLE
[Search] Implement search endpoint for places

### ISSUE THREAD

**Issue by bzhn** [ita-social-projects/GreenCity#7746]
Create endpoint that will accept the same search parameters as `events` and `econews` ([Swagger](https://greencity.greencity.cx.ua/swagger-ui/index.html#/search-controller/searchEvents)) and will return JSON with the similar structure.

**Comment by IliaWithHat** [comment]
Done. Note that I changed endpoint "/search/econews" to "/search/eco-news" and some DTO. See Swagger documentation for more details.
