### ISSUE TITLE
[Display news, Gallery view] Title can displays more than 170 characters and Content can't displays 200 characters.

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#775]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Preconditions:**
1. https://ita-social-projects.github.io/GreenCityClient/#/news is opened.

**Postconditions:**
1. Delete News from step 2. 
(DELETE FROM eco_news_tags
WHERE eco_news_id=600;
DELETE FROM eco_news
WHERE id=600;)

**Steps to reproduce**
1. Go to DB (DataGrip);
2. Create News with Title more that 170 characters and Content more than 200 characters. 
(e.g. Title  - 186 characters, Content- 241 characters)
 (INSERT INTO eco_news
(ID, title, text, author_id, creation_date)
VALUES (600, 'Doctors and medical professionals from around the globe have called on world leaders in the Group of 20 (G20) to “recover better” from the economic decline caused by the COVID-19 crisis.', 'While greenhouse gas emissions are set to fall this year in the wake of the crisis, any positive impact on the climate could be short-lived and quickly outweighed by increased emissions if the economic recovery resumes on a high-carbon path.', 50 , '"2020-05-29 22:00:00.000000');
INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (600, 6);)

**Actual result:**
1. Title displays 186 characters.
2. Content displays 199 characters.

**Expected result:**
1. Title displays 170 characters.
2. Content displays 200 characters.

User story: #459 

![Title and Content](https://user-images.githubusercontent.com/64582769/83197012-7ec6e200-a145-11ea-95d7-cd370724a653.png)

**Comment by KimAT25** [comment]
text have cutting for 197 symbols + 3 symbol dots what give us in summary 200 symbols.
Title don`t have any validation as we can create in the page 'create news' title with more than 170 symbols.
As you did it manually in DB it`snot a bug
