### ISSUE TITLE
[Event] User isn't redirected to Event page from notification about the comment in which he/she is tagged.

### ISSUE THREAD

**Issue by volo-amare** [ita-social-projects/GreenCity#7754]
**Environment:** OS: Windows 10 Pro 64-bit, Chrome Version 130.0.6723.92
**Reproducible:** always
**Build found:** last commit 08.11.2024

**Preconditions**
1. User is logged in on https://www.greencity.cx.ua/#/greenCity
2. There is a comment to the event where the user is tagged
3. The notifications page is opened

**Steps to reproduce**
1. Choose a notification about the comment in which the User is tagged.
2. Click on the link of the notification about the comment in which you are tagged.

**Actual result**
The Notifications page is opened. There is no link; only the Event title in text format.

**Expected result**
The Event page with a comment where the User was tagged is opened.

**User story and test case links**
"User story #4701

**Labels to be added**

![Notification](https://github.com/user-attachments/assets/a43f0c58-a136-41e5-8f22-9f3a2b9abff4)

**Comment by kryzanivska-nastya** [comment]
Now, the event title has a link 

https://github.com/user-attachments/assets/4ca81d3d-c2c2-43d4-9f3d-7b9db902e86c
