### ISSUE TITLE
[Edit profile] All labels are displayed as JS code after deleting a photo.

### ISSUE THREAD

**Issue by MilaKomisarenko** [ita-social-projects/GreenCity#7772]
**Environment:** Windows 10 Pro, Google Chrome Version 130.0.6723.92 (Official Build) (64-bit).
**Reproducible:** sometimes.
**Build found:** 07.11.2024

**Preconditions**
1. The user is logged in https://www.greencity.cx.ua/#/greenCity.
2. The profile picture is uploaded.
3. The edit profile page is opened.

**Steps to reproduce**
1. Click on the icon "Edit photo".
2. Click on the button “Delete photo“.
3. Click on the button “Yes, delete“.
4. Refresh the page.

**Actual result**
All label texts on the Edit profile page appear as JavaScript code rather than the intended text.
https://github.com/user-attachments/assets/637d0440-590b-49ef-83d6-9a80eb8ba3d6

**Expected result**
The label texts throughout the interface appear as the intended text.

**User story and test case links**
E.g.: "User story #1006.

**Comment by kovalsofiia1** [comment]
Can`t reproduce
https://github.com/user-attachments/assets/4fd04bf3-c354-4340-afdd-128bbaa342ee
