### ISSUE TITLE
[Comments] When we upload one image and/or choose one emoji and click 'comment' the comment appears 'Add commente[emoji]' or with photo

### ISSUE THREAD

**Issue by kryzanivska-nastya** [ita-social-projects/GreenCity#7776]
**Environment**: Windows 10 Pro, Google Chrome Version 130.0.6723.92 (Official Build) (64-bit).
**Reproducible**: always.

**Preconditions**

The user is logged in https://www.greencity.cx.ua/#/greenCity.
The habits/event/news page is opened.

**Steps to reproduce**
Scroll to the comments
Choose 1 image and 1 emoji without text
Click 'Comment'

**Actual result**
Comment with 'Add comment' text appears and image/emoji
![Image](https://github.com/user-attachments/assets/5a13e485-74e5-467e-a9fd-8a9ccf169430)
![Image](https://github.com/user-attachments/assets/389666fe-2b28-47a4-a761-f32a594bcc0d)

**Expected result**
Comment without text appears as it was intended and image/emoji also there
![Image](https://github.com/user-attachments/assets/68bc856c-fe49-4aa4-966b-b47896b8d7d0)
![Image](https://github.com/user-attachments/assets/111df235-d58e-4517-b9cd-9acf79d53914)

**Comment by KhatamovaDaria** [comment]
![image](https://github.com/user-attachments/assets/c20e75a1-6fb5-4827-9c1d-712d40230f88)
