### ISSUE TITLE
[Eco news] Status 403 instead of 200 when try to get information about comment by id.

### ISSUE THREAD

**Issue by volo-amare** [ita-social-projects/GreenCity#7805]
**Environment:** OS: Windows 10 Pro 64-bit, Chrome Version 131.0.6778.71
**Reproducible:** always
**Build found:** commit be310e97bf1078850130b5d08f1e7d9927466f2a

**Preconditions**
1. You should be authorized as a User on https://www.greencity.cx.ua/.

**Steps to reproduce**
1. Do endpoint: https://greencity.greencity.cx.ua/eco-news/comments/8180

**Actual result**
The system returns status 403 and doesn't give information about comment.
{
    "timestamp": "2024-11-22T15:29:09.985+00:00",
    "status": 403,
    "error": "Forbidden",
    "path": "/eco-news/comments/8180"
}

**Expected result**
The system returns status 200 and gives information about comment.

**Postconditions**
_

**User story and test case links**
User story #1723

**Comment by ToriForH** [comment]
Fixed with:
https://github.com/ita-social-projects/GreenCity/pull/7813
