### ISSUE TITLE
[Display news, Gallery view] Image is not aligned to Content according to mockup in screen resolution 768px.

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#782]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Preconditions:**
1. https://ita-social-projects.github.io/GreenCityClient/#/news is opened.

**Steps to reproduce**
1. Change screen resolution on News page in Gallery view to 768 px

**Actual result:**
1. Image is not aligned to Content according to mockup in screen resolution 768px

**Expected result:**
1.  Image is aligned to Content according to mockup in screen resolution 768px

User story: #459

![Alighment](https://user-images.githubusercontent.com/64582769/83265229-dc9d0d80-a1c9-11ea-8d72-108b237f394d.png)

**Comment by rsyvulko** [comment]
Fixed and verified:
https://github.com/ita-social-projects/GreenCity/issues/793
