### ISSUE TITLE
API [Create event] Status code 201 is shown instead of 400 when the user enters start time of the event 2 minutes earlier current time in "Start time" field in the body of the request 

### ISSUE THREAD

**Issue by Yuliia85** [ita-social-projects/GreenCity#7824]
**Environment:** OS: Windows 10 Pro, Browser Chrome version 130.6723.92
**Reproducible:** always
**Build found:** b74eb43

**Preconditions**
The user is logged in, and the token is gotten.

**Steps to reproduce**
1. Enter into the URL field https://greencity.greencity.cx.ua/events
2. Select the POST method from dropdown list
3. In the request body tab select form-data checkbox
4. Enter key parameter: addEventDtoRequest (text format) and value:{
"title":"Eco",
"description":"Our city is our house, clearness is the useful approach",
"open":true,
"datesLocations":[
{
"startDate":"YYYY-MM-DDTHH:mm:ss" (specify current date and start time 2 minutes earlier current),
"finishDate":"YYYY-MM-DDTHH:mm:ss"(specify the current date and any end time, later the start time) ,
"coordinates":{
"latitude":49.166565,
"longitude": 26.576463
},
"onlineLink":"http://google.com"
}
],
"tags":["Social"]
}
5. Click send button
6. Pay attention to the status code

**Actual result**
Status code 201 is shown instead of 400 when the user enters start time of the event 2 minutes earlier current time in "Start time"  field in the body of the request 

![2 MIN](https://github.com/user-attachments/assets/cedd4422-a49a-4668-873c-48bc6c8e8db5)

**Expected result**
400 Status code (Bad request) is shown after sending the request

**User story and test case links**
E.g.: "User story #3193 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by KostashchukIryna** [comment]
![Image](https://github.com/user-attachments/assets/c00a3daf-8c88-4a24-a054-64f7c0a1b4de)
This was probably tested using Kyiv time, but specifying UTC in request body.
![Image](https://github.com/user-attachments/assets/90aadd3c-b0e2-434f-aaa8-7c05bf0b9a63)
