### ISSUE TITLE
[Display news: Single view]: Incorrect alignment at 1140px screen resolution

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#783]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit)
**Reproducible:** always
**Build found:** commit 07bfeb2

**Preconditions:**
1. https://ita-social-projects.github.io/GreenCityClient/#/welcome  is opened.

**Steps to reproduce:**
1. Click 'Eco-news' from Header
2. Choose on any news from available on the page and open it in a 'Single view'

**Actual result:**
The alignment is incorrect.

<img width="1075" alt="incorect alignment" src="https://user-images.githubusercontent.com/64583209/83267858-7ca86600-a1cd-11ea-8320-c8c0f714a81b.png">

**Expected result:**
Alignment should be as on mock-up.

<img width="1084" alt="corect alignment" src="https://user-images.githubusercontent.com/64583209/83267890-8500a100-a1cd-11ea-8c89-d03a233fb7bf.png">

User story: #498

**Comment by Volodymyr-Danyliv** [comment]
The bug fixed not fully correctly:
![image](https://user-images.githubusercontent.com/29017153/90191122-f9101580-ddc8-11ea-8f00-185aad99a571.png)
