### ISSUE TITLE
[Display news] Incorrect title and content rows height in the List view

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#784]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 378caca

**Preconditions**
News item is displayed first in the list on the 'Eco news' page. Create news item in the DB using querries:
```
INSERT INTO eco_news
(ID, title, text, author_id, creation_date)
VALUES (723, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim ven',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure d',
857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (723, 1), (723, 2);
```
**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Eco news' link in the header.
3. Set browser window width to 1440px. 
4. Click on the View as a List option on the right side of the page. 
5. Pay attention to created news Title and Description display.

**Actual result**
- Title is displayed and consists of 3 rows and have 76px in height.
- Description is displayed and consists of 1 row and  16px in height.
![3 rows height title](https://user-images.githubusercontent.com/64583544/83278746-bc2a7e80-a1dc-11ea-85d1-5b7b5c2b2ddc.png)
![1 row content](https://user-images.githubusercontent.com/64583544/83278780-c64c7d00-a1dc-11ea-92e5-a79be672e8d4.png)

**Expected result**
- Title is displayed and consists of 3 rows and have 96px in height.
- Description is displayed and consists of 1 row and  32px in height.
![list view block](https://user-images.githubusercontent.com/64583544/83278942-07dd2800-a1dd-11ea-8c2d-9c3fc9bd6b14.png)
**Postconditions**
Delete created news from DB using queries:
```
DELETE FROM eco_news_tags
WHERE eco_news_id = 723;

DELETE FROM eco_news
WHERE id = 723;
```

User story #460 
[Test case](https://jira.softserve.academy/browse/GC-723)

**Comment by rsyvulko** [comment]
This defect is present not only in 3 rows title and 1 row description news display. Incorrect rows height is present also in 2-1 rows title and 2-3 rows description.

**Comment by KimAT25** [comment]
First of all it`s not a bug, there was incorrect title height, but it was fixed.
Technically, it`s impossible to made the same height as in mock-up, so it will be discussed and changed in mock-up guide.
Main task was to make dynamic tittle and text height and made mandatory tittle.
