### ISSUE TITLE
[Event] Can't create the Event without a place but with link.

### ISSUE THREAD

**Issue by volo-amare** [ita-social-projects/GreenCity#7847]
**Environment:** Windows 10 Pro 64-bit, Chrome Version 131.0.6778.71
**Reproducible:** always
**Build found:** commit 8cf331a092431c128c000419f91066a8c4b3f047

**Preconditions**
1. You should be authorized as a User on https://www.greencity.cx.ua/.
2. Go to the Event dashboard or to the "My events" in the profile page.

**Steps to reproduce**
1. Click on the button "Add Event"
2. Choose 1 day in the "Duration".
3. Enter the valid values to the mandatory fields: "Title", "Event description", "Initiative type", "Date/time", "Link".
4. Click on the button "Publish" to create the event.

**Actual result**
The event isn't created. Error message appears: "errorMessage".

**Expected result**
The event is created.

**Postconditions**
Delete created event.

**User story and test case links**
User story #3193

**Video:** https://app.screencast.com/Oe61NINwSAUTH

**Comment by volo-amare** [comment]
Bug still reproducing 
Here  is my requests with error from Devtools. Import it to the Devtools.
https://dropmefiles.com.ua/ua/k8NLA6G5cX

**Comment by ChernenkoVitaliy** [comment]
> Bug still reproducing Here is my requests with error from Devtools. Import it to the Devtools. https://dropmefiles.com.ua/ua/k8NLA6G5cX
It closed automatically after merging pull request.
The bug has been fixed but there is a problem with the project deploy that is why the ticket is in column "Bugs".
When problem with deploy will be fixed the ticket will be mowed to "Bugs Retesting".
