### ISSUE TITLE
[Display news: Single view] 'Source' field appears under the "main text" field in case User has NOT filled in "Source" field in "Create news" form.

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#785]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit)
**Reproducible:** always
**Build found:** commit 07bfeb2

**Preconditions:**

1. New item is created in DB

Use queries:

INSERT INTO eco_news
(ID, title, text, image_path, author_id, creation_date)
VALUES (1, 'Еко лавка',
'Мережа магазинів спеціалізованих на реалізації натуральної та екологічно чистої продукції, яка вирощується і виробляється на фермерських господарствах.',
'https://storage.cloud.google.com/staging.greencity-c5a3a.appspot.com/51d59384-c6d0-46b9-b64c-42800dbfd701',
302, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (1, 4);

**Postconditions:**

1. Created news are deleted from DB using queries:

DELETE FROM eco_news_tags
 WHERE eco_news_id = 1;

DELETE FROM eco_news
 WHERE id = 1;

**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/news
2. Choose just created news and open it in a 'Single view'

**Actual result:**
"Source" field appears under the "main text" field in case the User has **NOT** filled in the "Source" field in "Create news" form.

<img width="1189" alt="Screenshot 2020-05-29 at 22 28 07" src="https://user-images.githubusercontent.com/64583209/83299470-e4c37000-a1fe-11ea-94a9-a789b3ec1425.png">

**Expected result:**
"Source" field should appear under the "main text" field in case User has filled in "Source" field in "Create news" form.

User story: #498

**Comment by RomanDeveloperAcc** [comment]
Fixed

**Comment by MariaKorniavka** [comment]
Verified
