### ISSUE TITLE
[UBS] Wrong text on the pop-up for choosing the address.

### ISSUE THREAD

**Issue by volo-amare** [ita-social-projects/GreenCity#7868]
**Environment:** 
- Lenovo YOGA Slim 7, Windows 10 Pro, екран 1920 x 1080 пікселей,
Chrome Версія 128.0.6613.120;
- Redmi Note 13 Pro 5G, Android 13TKQ1.221114.001, екран 2712 x 1220 пікселей, Chrome Версія 128.0.6613.100

**Reproducible:** always
**Build found:** commit 1b0a935da50883f70eac5f975674e5de1ba5790d

**Preconditions**
Login as a User on the https://www.pick-up.city/#/ubs

**Steps to reproduce**
1. Go to the Main page
2. Click on the button "Замовити".

**Actual result**
Text on the pop-up: "Вітаємо в УБС! Спочатку оберіть локацію вивезення відходів. Наразі ми працюємо тільки по м. Київ та обраних містах."
![Скриншот_2024_12_05_12_46_13_887](https://github.com/user-attachments/assets/0e5a2045-7e81-4003-84dc-ed2bc53bf1fa)

**Expected result**
Text on the pop-up: "Вітаємо в УБС! Оберіть локацію вивезення відходів. Наразі ми працюємо тільки в м. Києві та передмістті столиці в радіусі 20 км."

**Postconditions**
_

**User story and test case links**
User story #5192, #2924

**Comment by kryzanivska-nastya** [comment]
Fixed
<img width="1437" alt="Image" src="https://github.com/user-attachments/assets/a46f2887-3106-49ee-b54d-b65e26b85a6c" />

**Comment by volo-amare** [comment]
@kryzanivska-nastya Sorry, i didn't correct the customer's mistake in the word “передмісті” - there should be 1 letter “т”
Please fix it

**Comment by kryzanivska-nastya** [comment]
It was updated: 
<img width="118" alt="Image" src="https://github.com/user-attachments/assets/745ba430-845e-43c5-90d6-4e844046d465" />
<img width="736" alt="Image" src="https://github.com/user-attachments/assets/89f211d4-4c14-4148-b430-e99309f13edc" />
