### ISSUE TITLE
[UBS] Wrong text on the pop-up "Перелік екстрапозицій та умови здачі" on the Order form.

### ISSUE THREAD

**Issue by volo-amare** [ita-social-projects/GreenCity#7870]
**Environment:** 
- Lenovo YOGA Slim 7, Windows 10 Pro, екран 1920 x 1080 пікселей,
Chrome Версія 128.0.6613.120;
- Redmi Note 13 Pro 5G, Android 13TKQ1.221114.001, екран 2712 x 1220 пікселей, Chrome Версія 128.0.6613.100
**Reproducible:** always
**Build found:** commit 1b0a935da50883f70eac5f975674e5de1ba5790d

**Preconditions**
Login as a User on the https://www.pick-up.city/#/ubs

**Steps to reproduce**
1. Go to the Main page.
2. Click on the button "Замовити".
3. Choose any variant of the address and click on the button "Продовжити".
4. Click on the button "Перелік екстрапозицій та умови здачі" over the comment field.

**Actual result**
1. Text on the bottom of the pop-up is: "Ви можете додати безлімітну кількість екстрапозицій УБС Кур'єру, обов'язково виконавши прості умови:".
2. Text on the bottom of the pop-up is: "Вкажіть у коментарі, що плануєте віддати Кур'єру безкоштовні позиції, а також зазначте їх об'єм і кількість.".
3. Text on the bottom of the pop-up is: "Кожен вид упаковки спакуєте окремо. Мікс цих відходів в одному пакеті/коробці УБС Кур'єр не вибирається.  Зав'яжіть пакети перед здачею.".

**Expected result**
1. The text on the bottom of the pop-up is: "Ви можете здати БЕЗОПЛАТНІ позиції вторсировини на переробку, обовʼязково виконавши прості умови:".
2. The text on the bottom of the pop-up is: "Вкажіть, що саме ви хочете здати і в якій кількості. Наприклад: 20-літровий пакет з алюмінієвими бляшанками та коробка гофрокартону 70х40 см.".
3. Text on the bottom of the pop-up is: "Кожен вид упаковки спакуєте окремо. Мікс цих відходів в одному пакеті/коробці УБС Курʼєр не приймає. Завʼяжіть пакети перед здачею.".

**Postconditions**
_

**User story and test case links**
User story #3598

**Comment by volo-amare** [comment]
@kryzanivska-nastya You changed "упаковки" to "паковань" on the 3 point.
Did the customer tell you about this?
![image](https://github.com/user-attachments/assets/d16baf24-71c8-4d09-b14c-439279464551)

**Comment by kryzanivska-nastya** [comment]
Maybe someone changed it by accident. I will change it back to 'упаковки'. Thanks!

Upd: fixed
