### ISSUE TITLE
[Display news: Single view]: Not proper size and place of 'Edit' button at 320px screen resolution.

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#789]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit)
**Reproducible:** always
**Build found:** commit 07bfeb2

**Preconditions:**
1. User is registered.
2. https://ita-social-projects.github.io/GreenCityClient/#/welcome  is opened.

**Steps to reproduce:**
1. Click 'Eco-news' from Header
2. Choose on any news from available on the page and open it in a 'Single view'

**Actual result:**
Not proper size and place of 'Edit' button at 320px screen resolution.

<img width="324" alt="Edit' button 320 " src="https://user-images.githubusercontent.com/64583209/83307399-4db1e480-a20d-11ea-9493-e0e604389fed.png">

**Expected result:**
'Edit' button should be as on mock-up

<img width="587" alt="'Edit' button 320 figma" src="https://user-images.githubusercontent.com/64583209/83307411-51de0200-a20d-11ea-80d5-732e96517c4a.png">

User story: #498

**Comment by JustinCooper43** [comment]
'Edit news' button is absent. I can not mesure size button.

**Actual result**

![Eddit button is absent](https://user-images.githubusercontent.com/64972476/89080689-41bfdb80-d392-11ea-852a-e444e516f0e1.jpg)

**Expected result**

![Eddit button present](https://user-images.githubusercontent.com/64972476/89080728-6320c780-d392-11ea-883f-21f2480a7e32.jpg)

**Comment by Volodymyr-Danyliv** [comment]
The 'Edit News' button is not displayed (Environment: Chrome, Firefox).

**Comment by RomanDeveloperAcc** [comment]
> The 'Edit News' button is not displayed (Environment: Chrome, Firefox).

The 'Edit News' button is only visible to the author. As it is shown on your screenshot, the name of the author is 'John Smith' and the name of the user is 'Jane Doe'. That is why it works correctly. Try to create one news item and then check the visibility of the button.

**Comment by JustinCooper43** [comment]
'Edit news' button size is incorrect.

**Actual result**
![Single view](https://user-images.githubusercontent.com/64972476/90987715-b7842500-e595-11ea-9a40-730858f10ec4.jpg)

**Expected result**
![Single view correct](https://user-images.githubusercontent.com/64972476/90987750-ec907780-e595-11ea-856b-77f8bbf804b4.jpg)

**Comment by JustinCooper43** [comment]
'Edit news' button size is incorrect and located on two line instead one.

![122](https://user-images.githubusercontent.com/64972476/91774204-f860e700-ebf0-11ea-92b0-4425da98a2e1.png)
