### ISSUE TITLE
[UBS] The system does not round a number to 2 digits after the dot when calculating the sum 

### ISSUE THREAD

**Issue by volo-amare** [ita-social-projects/GreenCity#7890]
**Environment:** 
- Windows 10 Pro 64-bit, iPhone Xs (IOS version 16.6.1)
- Browser Chrome Version 131.0.6778.109

**Reproducible:** always
**Build found:** commit 88644d6821c978261b2e9f1fdeecb01144f5f9ff

**Preconditions**
1. Login as a User on the https://www.greencity.cx.ua/#/ubs
2. A price variant should be added to the services: 10.1 UAH

**Steps to reproduce**
1. Go to the Main page.
3. Click on the button "Замовити".
4. Choose any variant of the address and click on the button "Продовжити".
5. Choose 9 pieces of "рпп".

**Actual result**
Total: 90.89999999999999 UAH
Order amount: 90.89999999999999 UAH
Amount due: 90.89999999999999 UAH

**Expected result**
Total: 90.90 UAH
Order amount: 90.90 UAH
Amount due: 90.90 UAH

**Postconditions**
_

**User story and test case links**
User story #2196, #3027

**Comment by KhatamovaDaria** [comment]
![image](https://github.com/user-attachments/assets/188bb6ca-414c-4c22-ba4f-c36cf01356c3)
