### ISSUE TITLE
[Display new] Gallery view, incorrect alignment of UI elements on 768 px screen resolution width

### ISSUE THREAD

**Issue by traviscolt** [ita-social-projects/GreenCity#801]
**Environment:** Windows 8.1 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducible:** always
**Build found:** 8629873

**Steps to reproduce:**

1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/news
2. Using dev tools change screen resolution width for the current page to 768px

**Actual result:**
![Screenshot_3](https://user-images.githubusercontent.com/35031131/83353053-7c88a180-a358-11ea-89ec-d0ba23c25711.jpg)

**Expected result:**
Alignment of UI elements like on mock-up
<img width="181" alt="768" src="https://user-images.githubusercontent.com/35031131/83353038-667ae100-a358-11ea-86c9-50c0a5fb67f2.png">

User story #459 
Test case on JIRA [674](https://jira.softserve.academy/browse/GC-674)

**Comment by RomanDeveloperAcc** [comment]
Not relevant because of new mock-up
