### ISSUE TITLE
[Display news] 2d and 3d news block is moved down in the 'Eco news' section on the Home page on 1053-1025px resolutions

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#803]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 8629873

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Set browser window width to 1054px.
3. Scroll down to 'Eco news' section.
4. Pay attention to second and third news block.
5. Set browser window width to 1053px.
6. Pay attention to second and third news block.
7. Set browser window width to 1024px.
8. Pay attention to second and third news block.

**Actual result**
Second and third news block is moved down in the 'Eco news' section on the Home page on 1053-1025px window width while first news block remains in the same place.
![Eco news home 1053](https://user-images.githubusercontent.com/64583544/83353462-6b8d5f80-a35b-11ea-9e9e-9f11406e1459.png)

**Expected result**
Second, third and first news block remains in the same place on 1440-1024px display resolutions or window width.
![Eco news home 1054](https://user-images.githubusercontent.com/64583544/83353464-6cbe8c80-a35b-11ea-9630-d6471469d900.png)

User story #351 
[Test case](https://jira.softserve.academy/browse/GC-689)

**Comment by yuriizhurakovskyi** [comment]
Can't recreate the bug. Please, check it again.

**Comment by rsyvulko** [comment]
Bug is not reproducible now after last merged commits.
