### ISSUE TITLE
Wrong alignment on 'Forgot password with Google' page button's label is not centred in (UA, RU, EN)

### ISSUE THREAD

**Issue by MartaLytvynovuch** [ita-social-projects/GreenCity#814]
**Environment:** macOS 10.15.4 Google Chrome Версія 83.0.4103.61 (Розробка) (64-розрядна версія)
**Reproducible:** always
**Build found:** 

**Steps to reproduce**

- Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
- Click on the 'Sign in' link
- Click on the 'Forgot password' link
- Verify if labels alignment 

**Actual result**
![Знімок екрана 2020-06-01 о 12 45 41](https://user-images.githubusercontent.com/65448781/83397236-f165e500-a405-11ea-808a-8587813dd703.png)

**Expected result**
'Forgot password' page Google button's label alignment is centered.
![Знімок екрана 2020-06-01 о 12 43 35](https://user-images.githubusercontent.com/65448781/83397017-9d5b0080-a405-11ea-9a6b-c54c81107bc3.png)

User story #471
Test case https://jira.softserve.academy/browse/GC-228

**Comment by JustinCooper43** [comment]
The bug was not fixed.

**Comment by JustinCooper43** [comment]
The bug was not fixed.

**Actual result** 

![Bug](https://user-images.githubusercontent.com/64972476/88460412-cb5c3e80-cea4-11ea-95db-ed4002671b52.jpg)

**Expected result**

![Correct](https://user-images.githubusercontent.com/64972476/88460428-db741e00-cea4-11ea-8e76-3448afc4b371.jpg)

**P.S.**
Maybe fixing this bug [#644](https://github.com/ita-social-projects/GreenCity/issues/644) will solve this problem.

**Comment by marinasmarsa** [comment]
The size of 'Sign in with Google' button shorter than 'Sign in' button (UA, RU)

**Comment by marinasmarsa** [comment]
![ec6ad63711](https://user-images.githubusercontent.com/69673592/92129923-cb891b80-ee0c-11ea-9e61-7575a5e19ce7.jpg)
![f5aabdae2d](https://user-images.githubusercontent.com/69673592/92129930-ccba4880-ee0c-11ea-9b29-eea8ff4f37d1.jpg)

**Comment by Volodymyr-Danyliv** [comment]
The bug was not fixed at login form in Uk, Ru localization:
![image](https://user-images.githubusercontent.com/29017153/92564976-ad933f00-f282-11ea-9ef3-435bb3d7af45.png)
