### ISSUE TITLE
[Display news, Home page] Picture of the latest article in home page is not the same with picture of the latest article in eco news.

### ISSUE THREAD

**Issue by Vitaliipuchak** [ita-social-projects/GreenCity#818]
**Environment:** Windows 10, Google Chrome 83.0.4103.61
**Reproducable:** always
**Build found:** commit b517ccb

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Scroll down  landing page  to the 'Eco news' informational section. 
3. Look at the title and picture of the article that is displayed in the 1st column of 'Eco news' section.
4. Switch to the 'Eco news' page
5. Verify picture of the latest article (top article in first column)
**Actual result**
Picture from step 3 is not the same as the picture from step 5.
**Expected result**
Picture from step 3 should be the same as the picture from step 5.
**User story**: #351 
**Test case**:https://jira.softserve.academy/browse/GC-702

**Comment by RomanDeveloperAcc** [comment]
Fixed
