### ISSUE TITLE
[Display news: Gallery view] Correct news displaying in right order 

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#834]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit 07bfeb2

**Steps to reproduce**
1. Open Eco news page https://ita-social-projects.github.io/GreenCityClient/#/news.

**Actual result:**
News displaying in order from top to bottom and from left to right. 

**Expected result:**
News displaying in order from left to right and from top to bottom. 

User story: #459 

![Screen Shot 2020-06-02 at 5 22 13 PM](https://user-images.githubusercontent.com/64582769/83531771-0b7ef080-a4f6-11ea-941c-adca2c5a9ef4.png)

**Comment by KimAT25** [comment]
As we had issues with masonry layout, we agreed with designers and BA to change style of grid for econews. It will be fix after designers will create new design for grid.

**Comment by KimAT25** [comment]
Will be new mockup for these view, so it blocked by Designers
