### ISSUE TITLE
[API] User is created after entering invalid data into 'Email' field

### ISSUE THREAD

**Issue by krechkivskyi** [ita-social-projects/GreenCity#841]
**Steps to reproduce:**

1. Go to https://greencitysoftserve.herokuapp.com/swagger-ui.html?...#/
2. Click 'own-security-controller' drop down page
3. Click '/ownSecurity/signUp' request
4. Click on 'Try it out' button
5. Enter invalid data into 'email' field (e.g. '111@333')
6. Enter valid data into 'name' and 'password' fields (e.g. 'Noname' and 'Qw@rt111')
7. Click on 'Execute' button

**Actual result:**
Code 201:
{
  "userId": 1014,
  "username": "Bohdan",
  "email": "111@111",
  "ownRegistrations": true
}
![2020-06-05_205450](https://user-images.githubusercontent.com/65503141/83908600-10e76f80-a770-11ea-891d-5f86c33cd7dd.jpg)

**Expected result:**
User receive response 400.
{ "name": "email", "message": "The email is invalid" }

User story #465
Test case: [https://jira.softserve.academy/browse/GC-536]

**Comment by krechkivskyi** [comment]
Not a bug

**Comment by yuriizhurakovskyi** [comment]
Added pattern annotation with regex: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$" to email field

**Comment by Volodymyr-Danyliv** [comment]
Incorrect response message.
**Actual result:**
"User with this email is already registered"
**Expected result:**
"The email is invalid"

**Comment by iraflorens** [comment]
[API] User is not created after entering invalid data into 'Email' field
