### ISSUE TITLE
View replies 

### ISSUE THREAD

**Issue by TetiShel** [ita-social-projects/GreenCity#843]
**As** a Logged or Unlogged User, **I want** to see all replies to the comment on the News Single Page or on the Tips & Tricks Single Page **so that** I can review that.

Tab.1 ‘View Replies’ Attributes

|# | Name | Type | Condition | Value/Restriction|
-- | -- | -- | -- | --
1 | View [number] replies | Text | Enable | Hidden by default. When at least 1 reply is saved, the attribute is shown.
2 | Added reply | Text, alphanumeric and Special characters | Disable | max characters number - 8000 min characters number - 1, except ‘space character’.
2 | Avatar | Picture | Disable | The avatar of the user who added the reply.
3 | User name | Text | Disable | The name of the user who added the reply.
4 | Date | Text, date format [Month, Day, Year] | Disable | The date when the user added the reply.

**Mockup: News_page_registered_my**

**Acceptance Criteria:**
1. All users (logged and unlogged) can see the replies to the comment on the News Single Page.
2. To review the replies to the comment user should click on the link ‘View [number] replies’ (Attribute 1).
3. To hide the replies to the comment user should click a second time on the link ‘View [number] replies’ (Attribute 1).
4. By default replies are hidden.
5. When user presses ‘View [number] replies’ button, the system display 10 first replies (or less).
6. If user want to see the next 10 replies, he/she shall presses 'View more 10 replies' link.
7. When user presses 'View more 10 replies' link, the system displays the next 10 replies and scrolls the page down. 

Change Request: #1170

**Comment by ViktoriyaRyazhska** [comment]
Done without Tips&Tricks functionality
