### ISSUE TITLE
Edit comment on the piece of news or tips&tricks

### ISSUE THREAD

**Issue by TetiShel** [ita-social-projects/GreenCity#845]
**As** a Logged User **I want** to edit my comment on the Tips & Tricks **so that** I can change the comment content. 

**As** a Logged User **I want** to edit my comment on the piece of News  **so that** I can change the comment content. 

_Tab.1 Edit comment attributes_

|# | Name | Type | Condition | Value/Restriction|
-- | -- | -- | -- | --
1 | Edit | Icon & link | Enable | Enable only for the user’s own comments
2 | Added comment | Text, alphanumeric and Special characters | Disable/ Enable | max characters number - 8000, min characters number - 1, except ‘space character’. The field is enabled, when user press the ‘Edit’ link (Attribute 1)
  | Comment | Button | Enable/ Disable | When Attribute 2 isn’t valid, the button is disabled. When Attribute 2 is valid, the button is enabled.
4 | Avatar | Picture | Disable | The avatar of the user who added the comment
5 | User name | Text | Disable | The name of the user who added the comment
6 | Date | Text, date format[Month, Day, Year] | Disable | The date when the user edited the comment

_Mockup: News_page_registered_my_

**Acceptance Criteria:**
1. User can edit only its own comment.
2. Logged User can edit its own comment on the ‘News’ page (News Single View). 
3. Logged User can edit its own comment on the ‘Tips $ Tricks’ page (Tips & Tricks Single View).
4. Logged User can publish its edited comment pressing the ‘Save changes’ button.
5. When Logged User presses the ‘Save changes’ button:
 - the system saves the changes,
 - the system displays the date of the comment editing.
6. If the user leaves/updates the page without pressing the ‘Save changes’ button, the changes are not saved. 
7. All Tab.1 Attributes are valid.
8. Breakpoints 1140, 1024, 768, 576, 320 are done due to provided mockups.

**Comment by ViktoriyaRyazhska** [comment]
Done without Tips&Tricks functionality
