### ISSUE TITLE
Delete comment/reply  on the piece of news or tips&tricks

### ISSUE THREAD

**Issue by TetiShel** [ita-social-projects/GreenCity#846]
**As** a Logged User **I want** to delete my comment/reply on the piece of News or on the Tips & Tricks **so that** nobody can see it.

_Tab.1 Delete comment/reply attributes_

|# | Name | Type | Condition | Value/Restriction|
-- | -- | -- | -- | --
1 | Delete | Icon & link | Enable | Enable only for the user’s own comments/replies
2 | Added comment/ Added reply | Text, alphanumeric and Special characters| Disable | max characters number - 8000min characters number - 1, except ‘space character’.
3 | Yes | Button | Enable | ‘Are you sure’  notification
4 | No | Button | Enable | ‘Are you sure’  notification

_Mockup: News_page_registered_my_

**Acceptance Criteria:**
1. User can delete only its own comment.
2. User can delete only its own reply.
3. Logged User can delete its own comment/reply on the  ‘News’ page (News Single View). 
4. Logged User can delete its own comment/reply on the ‘Tips $ Tricks’ page (Tips & Tricks Single View).
5. When Logged User presses the ‘Delete’ button:
 - the system display notification ‘ Are you sure you want to delete the comment?’ - if user wants to delete its comment,
 - the system display notification ‘ Are you sure you want to delete the reply?’ - if user wants to delete its reply,
 - user has 2 option to answer: yes, no,
 - if user presses the ‘no’ button, the system doesn’t delete the comment,
 - if user presses the ‘yes’ button, the system deletes the comment.
6. When the user deletes the comment, all related comments are deleted by the system.  
7. All Tab.1 Attributes are valid.
8. Breakpoints 1140, 1024, 768, 576, 320 are done due to provided mockups.

**Comment by ViktoriyaRyazhska** [comment]
Done without Tips&Tricks functionality
