### ISSUE TITLE
Edit reply on the piece of news or tips&tricks

### ISSUE THREAD

**Issue by TetiShel** [ita-social-projects/GreenCity#847]
**As** a Logged User **I want** to edit my reply on the piece of News or on the Tips & Tricks **so that** I can change the reply content. 

_Tab.1 'Edit Reply' Attributes_

|# | Name | Type | Condition | Value/Restriction|
-- | -- | -- | -- | --
1 | Edit | Icon & link | Enable | Enable only for the user’s own replies.
2 | Added reply | Text, alphanumeric and Special characters | Disable/ Enable | max characters number - 8000, min characters number - 1, except ‘space character’. The field is enabled, when user press the ‘Edit’ link (Attribute 1)
3 | Reply | Button | Enable/ Disable | When Attribute 2 isn’t valid, the button is disabled. When Attribute 2 is valid, the button is enabled.
4 | Avatar | Picture | Disable | The avatar of the user who added the reply.
5 | User name | Text | Disable | The name of the user who added the reply.
6 | Date | Text, date format [Month, Day, Year] | Disable | The date when the user edited the reply.

_Mockup: News_page_registered_my_

**Acceptance Criteria:**
1. User can edit only its own replies.
2. Logged User can edit its own replies on the ‘News’ page (News Single View). 
3. Logged User can edit its own replies on the ‘Tips & Tricks’ page (Tips & Tricks Single View).
4. Logged User can publish its edited reply pressing the ‘Reply’ button.
5. When Logged User presses the ‘Reply’ button:
 - the system saves the changes,
 - the system displays the date of the reply editing.
6. If the user leaves/updates the page without pressing the 'Reply’ button, the changes are not saved. 
7. All Tab.1 Attributes are valid.
8. Breakpoints 1140, 1024, 768, 576, 320 are done due to provided mockups.

**Comment by ViktoriyaRyazhska** [comment]
Done without Tips&Tricks functionality
