### ISSUE TITLE
[Search] Search functionality doesn't work with Tips & Tricks

### ISSUE THREAD

**Issue by traviscolt** [ita-social-projects/GreenCity#851]
**Environment:** Windows 8.1 x64, Google Chrome 83.0.4103.97 (64-bit)
**Reproducible:** always
**Build found:** commit 147fa44

**Steps to reproduce:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Search' button
3. Enter "Посадіть дерево" in the search field

**Actual result:**
Displays content that contains "Посадіть дерево" without Tips & Tricks with "Посадіть дерево"
![Screenshot_3](https://user-images.githubusercontent.com/35031131/84174016-b6f3ec00-aa86-11ea-9c7b-3eb6e9b81846.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/35031131/84174021-b9564600-aa86-11ea-9437-6636de1c85f4.jpg)

**Expected result:**
Displays content that contains "Посадіть дерево" including Tips & Tricks with "Посадіть дерево"

User Story #545

**Comment by greatpanda1603** [comment]
Front-end functionality for the tips & tricks section has not been developed yet. To be checked once UI part of #561 is completed.

**Comment by greatpanda1603** [comment]
Tips & Tricks are now included in the search. If you want to test this functionality, please use search query that contains words or phrases from title / text / tag of tips & tricks that are currently in our database. Please do not use phrases from the tips & tricks section on the home page, this is content not related to tips & tricks and will be replaced if future.

**Comment by Volodymyr-Danyliv** [comment]
To execute an existing bug need to translate TIPs & Tricks into English.

**Comment by greatpanda1603** [comment]
No need to translate hardcoded text on the landing page, just try typing into the search field either Tips & Tricks tags (eg lifehacks, green thinking, zero waste, 3 r's, eco-city) or some phrases from the content in the database (table tips_and_tricks, columns title or text). Please see attached screenshot

![image](https://user-images.githubusercontent.com/52715377/88376644-805c0180-cda6-11ea-8597-bd6d4111614d.png)
