### ISSUE TITLE
[Search] After the search, tags in news start with lower case letter

### ISSUE THREAD

**Issue by traviscolt** [ita-social-projects/GreenCity#852]
**Environment:** Windows 8.1 x64, Google Chrome 83.0.4103.97 (64-bit)
**Reproducible:** always
**Build found:** commit 147fa44

**Steps to reproduce:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Search' button
3. Enter "New" in the search field

**Actual result:**
Tags start with lower case 
![Screenshot_5](https://user-images.githubusercontent.com/35031131/84176365-ed7f3600-aa89-11ea-8b27-c3b765d3f377.jpg)

**Expected result:**
Tags start with upper case 

User Story #545

**Comment by greatpanda1603** [comment]
Changed tags in deployed database to start with upper case letter.

**Comment by traviscolt** [comment]
Verified
