### ISSUE TITLE
[Search] Missing Ukrainian  and Russian localization

### ISSUE THREAD

**Issue by traviscolt** [ita-social-projects/GreenCity#857]
**Environment:** Windows 8.1 x64, Google Chrome 83.0.4103.97 (64-bit)
**Reproducible:** always
**Build found:** commit 147fa44

**Steps to reproduce:**

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Change language in the right upper corner from the drop-down list (UA/RU)
3. Click on the 'Search' button

**Actual result:**
Search functionality displays on the English
![Screenshot_9](https://user-images.githubusercontent.com/35031131/84182364-f3c5e000-aa92-11ea-8b30-dd0b16027f33.jpg)

**Expected result:**
Search functionality displays on the chosen language

User Story #545 
[Test case](https://jira.softserve.academy/browse/GC-773)

**Comment by Gusvarov** [comment]
That's not a bug, because we didn't make search localization. I did it today, so you can test it) 
#1094 - localization story
