### ISSUE TITLE
[Header] User Name is not fully displayed when it consists of 20 symbols

### ISSUE THREAD

**Issue by OlesiaSolovii** [ita-social-projects/GreenCity#860]
Environment: macOS Catalina, Version 10.15.4 (19E287),
Google Chrome, Version 81.0.4044.129
Build found: commit 147fa44

**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in with creds: 'Email'="zotrubigne@enayu.com", 'Password'="Qwerty123."
3. Verify User Name

**Actual result**
User Name is not fully displayed when it consists of 20 symbols.
<img width="366" alt="Screen Shot 2020-06-09 at 11 37 41 PM" src="https://user-images.githubusercontent.com/64583001/84197596-e1f03700-aaaa-11ea-90ee-1306e437bcd3.png">
 **Expected result**
User Name should be fully displayed.

User story #558

**Comment by JustinCooper43** [comment]
Location "Dropdown Button" does not meet mockup.

**Actual result**

![Drop down user name](https://user-images.githubusercontent.com/64972476/88420700-f5075e00-cdef-11ea-9940-5e440fbb025b.jpg)

![Drop down user name 1](https://user-images.githubusercontent.com/64972476/88420719-fc2e6c00-cdef-11ea-84dd-5ddcd9b43da2.jpg)


**Expected result**


![Drop down user correct](https://user-images.githubusercontent.com/64972476/88420775-15cfb380-cdf0-11ea-9158-b383153ba485.jpg)
