### ISSUE TITLE
[Search] Search label contains "User's search query" instead of text of user's query for 0 found items

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#865]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 147fa44

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Search' icon in the Header.
3. Enter text which could not be found, e.g. "sdf 6sf7868sf6sd8fsf6" in the 'Search' text field.

**Actual result**
**"We couldn't find results for 
"User's search query"
Please change the search."**  
label is displayed.
![0 search query](https://user-images.githubusercontent.com/64583544/84248275-e439ac00-ab11-11ea-8b5d-e8db565938cf.png)

**Expected result**
**"We couldn't find results for 
"<Text of user's search query>". 
Please change the search."** 
label is displayed, e.g.:
**"We couldn't find results for 
"sdf 6sf7868sf6sd8fsf6". 
Please change the search."**
![Search 0 items expected](https://user-images.githubusercontent.com/64583544/84249013-e3554a00-ab12-11ea-9a99-ca08f1e43663.png)

User story #569  
[Test case](https://jira.softserve.academy/browse/GC-760)

**Comment by HryshkoAnton** [comment]
This bug and bug#866 are the same. I have fix bug#866
