### ISSUE TITLE
[Search] Recommendation block is shifted to the left and overlaps Search label on >=1069 resolution

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#867]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 147fa44

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Search' icon in the Header.
3. Enter text which could not be found, e.g. "sdf 6sf7868sf6sd8fsf6" in the 'Search' text field.
4. Set browser window width to 1069, then 781px and less.

**Actual result**
'News' and 'Tips & Tricks' recommendation block is shifted to the left and overlaps Search label on >=1069px browser window width. At 781px and less width block is not fully displayed, part of it is hidden beyond the visible window.
![Search 0 res 1069](https://user-images.githubusercontent.com/64583544/84250845-3cbe7880-ab15-11ea-9412-44a476a286cd.png)
![Search 0 res 781](https://user-images.githubusercontent.com/64583544/84250852-3defa580-ab15-11ea-9d08-d31fad41433b.png)

**Expected result**
'News' and 'Tips & Tricks' recommendation block is allways displayed in the right or bottom part of the window. At all resolutions and any window width all labels and blocks are displayed fully and don't overlaps each other.

User story #569  
[Test case](https://jira.softserve.academy/browse/GC-760)

**Comment by JustinCooper43** [comment]
**Bug was not fixed**

At 781px and less width block is not fully displayed, part of it is hidden beyond the visible window.

![Search wrong](https://user-images.githubusercontent.com/64972476/89101551-85a1f780-d409-11ea-9445-deb1c9af435d.jpg)
