### ISSUE TITLE
[Search] Scroll bar is absent and 'See all results' link is not displayed for search results at >=575px resolutions

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#870]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 147fa44

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Search' icon in the Header.
3. Enter "a" in the 'Search' text field.
4. Set browser window width to 575px, then less.

**Actual result**
'See all results' link is not displayed. Verticall scroll bar is absent.
![Search 575 scroll](https://user-images.githubusercontent.com/64583544/84252982-ffa7b580-ab17-11ea-8e5d-7002f9bf0999.png)

**Expected result**
'See all results' link is displayed at the bottom of the page under the last found item. Verticall scroll bar is present to make all page visible for user.
![Screenshot_9](https://user-images.githubusercontent.com/64583544/84253287-6c22b480-ab18-11ea-9fbb-c9b6fd4a66ce.jpg)

User story #545 
[Test case](https://jira.softserve.academy/browse/GC-760)

**Comment by Volodymyr-Danyliv** [comment]
Search-filtered news is not displayed. But the counter shows the number of news items that fall under the search parameters:
![image](https://user-images.githubusercontent.com/29017153/91235249-d1f90280-e73d-11ea-9e42-01bd84ba62d2.png)

**Comment by Volodymyr-Danyliv** [comment]
The search result is overlapping with each other at the screen resolution 576 px.
![image](https://user-images.githubusercontent.com/29017153/92554533-35228300-f26e-11ea-8dc7-96742f5e4898.png)
