### ISSUE TITLE
[Header] There are 3 available options for the User Name drop-down list

### ISSUE THREAD

**Issue by OlesiaSolovii** [ita-social-projects/GreenCity#873]
Environment: macOS Catalina, Version 10.15.4 (19E287),
Google Chrome, Version 81.0.4044.129
Build found: commit 147fa44

**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in with creds: 'Email'="green.city.test2@gmail.com", 'Password'="Green.city#500"
3. Click on "User Name" link
4. Click on "User settings"
5. Scroll down to the page

**Actual result** 
There are drop-down list with 3 available options: Favorite places, User settings, Sign out.
When user selects "User settings", pop-up does not appear. Page blocked and does not scroll down to the page.
<img width="298" alt="Screen Shot 2020-06-10 at 3 02 40 PM" src="https://user-images.githubusercontent.com/64583001/84265798-12c48080-ab2c-11ea-9ceb-12a187609c67.png">
<img width="1613" alt="Screen Shot 2020-06-11 at 1 07 06 PM" src="https://user-images.githubusercontent.com/64583001/84373798-c0e03100-abe5-11ea-8c8d-af0bf415de0f.png">

**Expected result**
For the User Name drop-down list should be 2 available options: **Settings, Log Out.**
Favorite places option should be excluded. When User selects "Settings" option, the system opens Settings form as a pop-up.

User story #670

**Comment by KimAT25** [comment]
These buttons it`s old functionally what will be changed, so it`s no reason to test it right now.

**Comment by OlesiaSolovii** [comment]
Could you exclude option "Favorite places" option and change button "User settings" to "Settings".
