### ISSUE TITLE
[Header]: Tips & Tricks link is highlighted in green when Home page is open.

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#875]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit)
**Reproducible:** always
**Build found:** commit 147fa44

**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/news
2. Click on the Application logo and name.

**Actual result:**
Tips & Tricks link is highlighted in green when the Home page is open.

<img width="1678" alt="green link" src="https://user-images.githubusercontent.com/64583209/84272514-2e348900-ab36-11ea-8e9f-18b803593ce4.png">

**Expected result:**
Tips & Tricks link shouldn't be highlighted in green when the Home page is open.

User story: #354

**Comment by greatpanda1603** [comment]
Tips & Tricks link is highlighted due to the fact that currently both Home page and Tips & Tricks redirect to thr same "active-link" with path '/welcome'. Will be fixed once Tips & Tricks separate page is developed with it's own unique path.
