### ISSUE TITLE
[Search] Search results are not displayed for entered symbols " % , ^ , [ , ] , { , } , | , \ , ` "

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#876]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit 147fa44

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on the 'Search' icon in the Header.
3. Enter "%" in the 'Search' text field.
4. Clear text field and enter "^" in the text field. Repeat with "[", "]", "{", "}", "|", "\ ", "`".

**Actual result**
No results, labels, images or icons are displayed. Search area is empty and looks like before text for search was entered.
![Search %](https://user-images.githubusercontent.com/64583544/84273514-6dafa500-ab37-11ea-8c64-7699b89d3f49.png)

**Expected result**
Search results are displayed if they are found. "We couldn't find results" page is displayed if results are not found. Search area is not empty.

User story #545 
[Test case](https://jira.softserve.academy/browse/GC-763)

**Comment by Uliana-Bigun** [comment]
**This defect is still reproduced.**

****Actual result**
After search request with special characters we get 400 client error in console (see attachment)
![Screenshot_2](https://user-images.githubusercontent.com/82227122/116709371-47a62400-a9d9-11eb-8cf8-5e35e343ed89.png)

**Expected result****
Search results are displayed if they are found. "We couldn't find results" page is displayed if results are not found.
