### ISSUE TITLE
[Footer] Incorrect alignment and size of 'Eco news' link and Twitter icon on the footer 

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#877]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit a101c84

**Steps to reproduce**
1. Open Eco news page https://ita-social-projects.github.io/GreenCityClient/#/news;
2. Scroll to the footer of the page;

**Actual result:**
1. Size of link 'Eco news' on the footer is 60.7-22
2. Twitter icon on the footer is 16-14
3. Incorrect alignment "Follow us" and icons

**Expected result:**
1. Size of link 'Eco news' on the footer is 61-19
2. Twitter icon on the footer is 15-12,19
3. Alignment "Follow us" and icons according to mockup

User story: #384 

1.
![1- Eco news](https://user-images.githubusercontent.com/64582769/84277604-6b037e80-ab3c-11ea-910c-95060aa5844d.png)
![1-mockup eco news](https://user-images.githubusercontent.com/64582769/84277621-6f2f9c00-ab3c-11ea-8469-70f4c6f733ed.png)

2.
![3-twitter icon](https://user-images.githubusercontent.com/64582769/84277951-d3526000-ab3c-11ea-9622-3ad712410979.png)
![3-mockup twitter icon](https://user-images.githubusercontent.com/64582769/84277962-d77e7d80-ab3c-11ea-9a10-31df73fd911c.png)

3.
![4- alignment](https://user-images.githubusercontent.com/64582769/84278834-e7e32800-ab3d-11ea-9f96-7a2b4fca9b19.png)
![4-mockup aligntment](https://user-images.githubusercontent.com/64582769/84278846-eb76af00-ab3d-11ea-8d81-baececdeef57.png)

**Comment by JustinCooper43** [comment]
Bug was not fixed

**Eco news**
![Eco news](https://user-images.githubusercontent.com/64972476/91771374-8e920e80-ebeb-11ea-8a4e-959fb7324818.jpg)

**Twitter**
![Twitter](https://user-images.githubusercontent.com/64972476/91771395-9b166700-ebeb-11ea-9247-d880be3942a9.jpg)

**Comment by natalinapr** [comment]
Wrong size of "Follow us"
Environment: Windows 10 Pro, Google Chrome 87.0.4280.66 (64-bit)
Reproducable: always
Build found: 26.11.2020

Steps to reproduce

Open Eco news page https://ita-social-projects.github.io/GreenCityClient/#/news;
Scroll to the footer of the page;

Actual result:

Size of 'Follow us' is 156.03x24.
![DEFECT](https://user-images.githubusercontent.com/62031226/100391138-38423980-303b-11eb-96fc-606caae9df47.png)

Expected result:
Size of 'Follow us' is 158x20.
![84278846-eb76af00-ab3d-11ea-8d81-baececdeef57](https://user-images.githubusercontent.com/62031226/100391197-60ca3380-303b-11eb-8db7-610ad20132a5.png)

**Comment by IrynaShlyakhetko** [comment]
Defect is not fixed 
size Twitter icon on the footer is 16-16
Size of link 'Eco news' on the footer is 60,56 - 16
Size of 'Follow us' is 156.03x24. is 540 -17,25
<img width="277" alt="Screen Shot 2021-01-21 at 14 51 12" src="https://user-images.githubusercontent.com/77668307/105355668-1f00d800-5bfb-11eb-87e1-9a74be43f4b9.png">
<img width="283" alt="Screen Shot 2021-01-21 at 14 51 41" src="https://user-images.githubusercontent.com/77668307/105355686-27f1a980-5bfb-11eb-886d-3484fbefd62d.png">
<img width="614" alt="Screen Shot 2021-01-21 at 14 53 35" src="https://user-images.githubusercontent.com/77668307/105355702-2cb65d80-5bfb-11eb-8b84-2950c13722a1.png">
