### ISSUE TITLE
[Header] Page doesn't scroll up to it's top if user scrolls the page down and clicks on link of this page in the Header.

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#878]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit)
**Reproducible:** always
**Build found:** commit a101c84

**Steps to reproduce:**
1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on any link in Header (eg. 'Eco news')
3. Scroll down the opened page.
4. Click on the link of this page Header.

**Actual result:**
 Page doesn't scroll up to it's top if the user scrolls the page down and clicks on the link of this page in the Header.

**Expected result:**
 Page should scroll up to it's top if the user scrolls the page down and clicks on the link of this page in the Header.

User story: #354

**Comment by KimAT25** [comment]
When you click on different link you going to the top, when you click on the same link it`s not happen, as it was not a requirement from BA and Designers. Should be discussed with them(BA and Designers)

**Comment by MariaKorniavka** [comment]
Agreed with designers.
