### ISSUE TITLE
[Footer] User is not redirected to the previous page after clicking My habits link in the footer of the page.

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#881]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit a101c84

**Preconditions**
User is not logged in

**Steps to reproduce**
1. Open Eco news page https://ita-social-projects.github.io/GreenCityClient/#/news;
2. Scroll to the footer of the page;
3. Click on 'My habits' link in the footer of the page;
4. Click back button on the browser to return to the previous page.

**Actual result:**
 Page 'Tips & Tricks' is opened

**Expected result:**
User is returns to the previous page

User story: #384

**Comment by KimAT25** [comment]
it`s not reproducable bug, I tested few times all works fine.
