### ISSUE TITLE
[Footer] Incorrect alignment of footer on screen resolution 1024px, 768px, 576px, 320px.

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#882]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit a101c84

**Steps to reproduce**
1. Open Eco news page https://ita-social-projects.github.io/GreenCityClient/#/news;
2. Scroll to the footer of the page;
3. Click F12;
4. Change screen resolution on 1024px, 768px, 576px, 320px.

**Actual result:**
 1. Incorrect distance of elements and alignment of text "© Copyright 2020. Green City" on screen resolution 1024px
2. Incorrect distance of elements and alignment of text "© Copyright 2020. Green City" on screen resolution 768px
3. Incorrect alignment of text "© Copyright 2020. Green City" on screen resolution 576px
4. Incorrect distance between elements on screen resolution 320px

**Expected result:**
1. Distance and alignment on screen resolution 1024px is according to mockup
2. Distance and alignment on screen resolution 768px is according to mockup
3. Alignment on screen resolution 576px is according to mockup
4. Distance between elements on screen resolution 320px is according to mockup

User story: #384 

1.
![6-1024](https://user-images.githubusercontent.com/64582769/84377615-92fdeb00-abeb-11ea-84ad-a9ef8846e9a8.png)
![6-1024 mockup](https://user-images.githubusercontent.com/64582769/84377695-b6c13100-abeb-11ea-906d-dedbef8d75ca.png)

2. 
![768](https://user-images.githubusercontent.com/64582769/84377911-0c95d900-abec-11ea-8d5a-fcf1863bb8d6.png)
![768 mockup](https://user-images.githubusercontent.com/64582769/84377936-128bba00-abec-11ea-8e43-393c3b5ed5e4.png)

3. 
![576](https://user-images.githubusercontent.com/64582769/84378213-77471480-abec-11ea-9a80-3612a14479d7.png)
![576 mockup](https://user-images.githubusercontent.com/64582769/84378234-7dd58c00-abec-11ea-91c3-313670e98bda.png)

4. 
![320](https://user-images.githubusercontent.com/64582769/84378712-49160480-abed-11ea-985c-32d44d87cc92.png)
![320 mockup](https://user-images.githubusercontent.com/64582769/84378730-503d1280-abed-11ea-902a-755e877a23f8.png)

**Comment by JustinCooper43** [comment]
Menu links and Social network links don't stand on the one line.

**Actual result:**

![footer incorrect](https://user-images.githubusercontent.com/64972476/90989384-1d76a980-e5a2-11ea-9f20-37d3025d87b6.jpg)


**Expected result:**

![footer correct](https://user-images.githubusercontent.com/64972476/90989375-0afc7000-e5a2-11ea-9140-85d64f201627.jpg)
