### ISSUE TITLE
[Footer] Page is not updated after clicking twice same link on the footer of the page

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#883]
**Environment:** macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit)
**Reproducable:** always
**Build found:** commit a101c84

**Preconditions:**
1. Open GreenCity website https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in with valid credentials

**Steps to reproduce**
1. Scroll to the footer of the page;
2. Click 'Eco news' link in the footer. 
3. Scroll to the footer of the page
4. Click 'Eco news' link in the footer again.
5. Repeat step 1-4 with links in the footer: 'Places', 'About us', 'My habits' and the name "Greencity" or logo 

**Actual result:**
Page is not updated

**Expected result:**
Page is updated

User story: #384

**Comment by KimAT25** [comment]
It was not a requirement from BA and Designers, should be discussed

**Comment by Yulia-H** [comment]
Agreed with designers on the meeting
