### ISSUE TITLE
Editing existent place in the list as Admin 

### ISSUE THREAD

**Issue by nhrab** [ita-social-projects/GreenCity#91]
As Admin I want to edit existent place so that information in the list of Places is always actual.

Mockup:
![image](https://user-images.githubusercontent.com/53810790/63801911-19c22f80-c91a-11e9-9845-cfb9ca5eb8ad.png)

Acceptance criteria:

1. "Edit" icon button is available on the "Places" tab near each row on the right side. It is shown as icon of pencil.

2. WHEN Admin see "Places" tab, THEN he can click on one of "Edit" icon button near each row.

3. WHEN Admin clicks "Edit" icon button THEN popup with already filled information of chosen row is shown:
   a. input field "Name"
   b. input field "Address"
   c. input field "Working times"
   d. "Save" button

5. WHEN Admin updates information in required fields of current place and clicks "Save" button THEN he can see this place in the list with updated info.

**Comment by rsyvulko** [comment]
Not relevant.
