### ISSUE TITLE
[API] The field image has max permitted size of 1048576 bytes instead of 10 Mb

### ISSUE THREAD

**Issue by Yulia-H** [ita-social-projects/GreenCity#920]
Environment: macOS High Sierra 10.13, Google Chrome 81.0.4044.129 (64-bit).
Reproducable: always.
Build found: commit 1e33458.

**Preconditions**

1. Open Swagger: https://greencity.azurewebsites.net/swagger-ui.html#/ ;
2. Sign in with controller Post /ownSecurity/signIn;
3. Use token to authorize in Swagger;

**Steps to reproduce**

1. Open user-controller
2. Click on controller PATCH /user/profilePicture Update user profile picture
3. Click on "Try it out" button
4. Choose an image in png or jpeg format up to 10 MB. (e.g. enclosed image "Test5" with size 8,91MB)
5. Click on "Execute" button

**Actual result**
Code 400.
Response body
{
  "message": "Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException: The field image exceeds its maximum permitted size of 1048576 bytes."
}

**Expected result**
Code 200

**User story and test case links**
User story #537 
[Test case in JIRA] GC-1067

Test5
![Test5](https://user-images.githubusercontent.com/64582769/85880435-b2e4ff80-b7e4-11ea-89d9-34d4c4470093.png)

Actual result
![4- 1048576 bytes](https://user-images.githubusercontent.com/64582769/85880483-c5f7cf80-b7e4-11ea-9e47-35bb80d8c715.png)

**Comment by greatpanda1603** [comment]
Duplicated issue, bug #832 has already been opened to address problem with image size.

**Comment by Yulia-H** [comment]
Fixed
