### ISSUE TITLE
[API][Habits] Incorrect error-message is displayed after user entered other language except "uk", "ru" or "en" via /user/{userId}/habit-dictionary/available API GET call

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#951]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit d9696b1 

**Preconditions**
1. GreenCity Swagger page is opened: https://greencity.azurewebsites.net/swagger-ui.html#/
2. User is signed in and authorised in the GreenCity Swagger.

**Steps to reproduce**
1. Click on 'user-controller' item.
2. Click on 'GET /user/{userId}/habit-dictionary/available' item.
3. Click on 'Try it out' button.
4. Enter id of the current user into the 'Id of current user. Cannot be empty.' field.
5. Enter text into the 'Code of the needed language.' except "en", "uk" and "ru" (e.g. "pl").
6. Click on the 'Execute' button.

**Actual result**
400 response code is received. Response body message: "This user is tracking all available habit dictionary".
![Habitdictionary other language](https://user-images.githubusercontent.com/64583544/86945936-5a9dee00-c152-11ea-9f50-25901dcbc5c2.png)

**Expected result**
400 response code is received. Response body message contains information about wrong language selection (e.g. "Select correct language: "en", "uk" or "ru".").

[Test case](https://jira.softserve.academy/browse/GC-1115)

**Comment by Volodymyr-Danyliv** [comment]
Actual result: 500 response code is received...
Expected result: 400 response code is received...
