### ISSUE TITLE
[API, Goals] System allows to save custom goal with empty values.

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#964]
**Environment:** macOS Catalina 10.15.4, Google Chrome  83.0.4103.97 (64-bit)
**Reproducable:** always
**Build found:** commit 7384fdc

**Preconditions**

1. Swagger https://greencity.azurewebsites.net/swagger-ui.html#/ is opened.
2. Log in  (e.g. em: green.city.test2@gmail.com pwd: Green.city#500)
3. Get token
4. Authorize 

**Steps to reproduce**

1. Click on 'user-controller' drop down page
2. Click on '/user/{userId}/customGoals Save one or multiple custom goals' request
3. Click "Try it out" button
4. Edit request  
{
  "customGoalSaveRequestDtoList": [
    {
      "text": "<empty>"
    }
  ]
}
5. Fill in 'userId' field (eg. userId: '302')
6. Click the "Execute" button.

**Actual result**
System allows to save custom goal with empty values.

<img width="898" alt="Screenshot 2020-07-14 at 13 58 13" src="https://user-images.githubusercontent.com/64583209/87420136-64ee3b00-c5dd-11ea-9b54-bc02860ed2df.png">

Database

<img width="717" alt="Screenshot 2020-07-14 at 13 58 53" src="https://user-images.githubusercontent.com/64583209/87420156-6d467600-c5dd-11ea-8256-c78576e553cb.png">

**Expected result**
System should not allow to save custom goal with empty values

[Test case](https://jira.softserve.academy/browse/GC-1164)

**Comment by Volodymyr-Danyliv** [comment]
The system allows saving a custom goal with empty values.

**Comment by Volodymyr-Danyliv** [comment]
The bug didn't fix:
![image](https://user-images.githubusercontent.com/29017153/91653825-a616ad80-eaac-11ea-9ab7-74d964729c08.png)
DB:
![image](https://user-images.githubusercontent.com/29017153/91653841-ba5aaa80-eaac-11ea-8683-98fb4ae43103.png)

**Comment by Plilia** [comment]
The bug didn't fix
![123](https://user-images.githubusercontent.com/12970841/92129742-97adf600-ee0c-11ea-81a9-0e352a1a0a68.jpg)
