### ISSUE TITLE
[Header] There are 3 available options for the User Name drop-down list

### ISSUE THREAD

**Issue by BohdanPrysiazhnyi** [ita-social-projects/GreenCity#984]
Environment:
OS: Windows 10 Home
Browser: Google chrome 84.0.4147.89  64-bit

       Reproducable:  always

       Steps to reproduce:

1. Go to https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Sign in with creds: 'Email'="green.city.test2@gmail.com", 'Password'="Green.city#500"
3. Click on "User Name" link

       Actual result

There are drop-down list with 3 available options: Profille, Settings, Sign out.
![Без імені](https://user-images.githubusercontent.com/68583636/88300739-7eddfb00-cd0c-11ea-9a54-38d6dcb35800.png)
- 

      Expected result

For the User Name drop-down list should be 2 available options: Settings, Sign Out.

![Без імені1](https://user-images.githubusercontent.com/68583636/88300804-90bf9e00-cd0c-11ea-9e47-5b70edaed246.png)

User story #[670](https://github.com/ita-social-projects/GreenCity/issues/670)

**Comment by krivondulia** [comment]
There are 2 options, but it is extra space under the 'Sign out' button.
![extra space](https://user-images.githubusercontent.com/69672600/97724489-45681900-1acd-11eb-9c15-6e1dde966757.jpg)
