### ISSUE TITLE
 Freeze the habit

### ISSUE THREAD

**Issue by YuliyaTimosh** [ita-social-projects/GreenCity#992]
As a Logged User I want to pause the habit so I can frezze that.

**Acceptance criteria** 

1. User can freeze the habit on 5, 10, 15 or 20 days.
2. If user freeze the habit the counter decrease in one every 5 days. 
3. After  unfreeze the habit user should be able to continue track the habit.

**Comment by ViktoriyaRyazhska** [comment]
Not relevant
