### ISSUE TITLE
Manage acquired habits

### ISSUE THREAD

**Issue by YuliyaTimosh** [ita-social-projects/GreenCity#994]
As a Logged User I want to interact with my own acquired habits on the “My habits” page, so that I can manage that.

**Acceptance criteria:**

1. User should be able to see three and less acquired habits by default.
2. If user got more than three habits, the fourth and next habits are hidden.
3. User should be able to see the next three acquired habits after clicking on ‘View more’ button
4. When user have opened whole list of acquired habits the ‘View more’ button disappear.
5. Each acquired habit should have “Great! You got a habit!” label.

**Comment by NataliaRyczek** [comment]
User Story closed after testing.
