### ISSUE TITLE
'My Eco Friends' page view

### ISSUE THREAD

**Issue by irapetrovych** [ita-social-projects/GreenCity#995]
**As a** user, **I want to** have one place where I can see the list of all my friends, search for a new friend and accept friend requests **so that** all my actions related to friends were done in a common place.

**Preconditions:**
The registered user is logged in
My habits page is open

**Acceptance criteria:**

**1. When user has 1+ friends, the system displays a button “See all” on My habits page in the My Friends area
  a. “See all” button is always enabled.
2. When user has 0 friends, the button “See all” on My habits page in the My Friends area are not visible 
3. When user has 1+ friends and clicks on the button “See all” on My habits page in the My Friends area the system redirect her/him to All friends tab by default
4. When user has 0+ friends and clicks on the button “+” on My habits page in the My Friends area the system redirect her/him to Find friends tab by default**

5. On My Eco Friends page user is able to see and navigate around tabs:
     a. All friends
     b. Find friends
     c. Requests

**Out of scope:**
View my eco friends list
Search for new friends
Accept or decline friends requests

**Comment by NataliaRyczek** [comment]
Test works fine

**Comment by BohdanKalytynskyi** [comment]
[https://drive.google.com/file/d/1z4DnB2UOu_KI0nPqatRgJcKls9Qy0PNr/view?usp=sharing](url)
