### ISSUE TITLE
Rate calculation

### ISSUE THREAD

**Issue by krechkivskyi** [ita-social-projects/GreenCity#997]
As a user I want to see my ‘Rate’ on ‘My habits’ page.

_Mockup: Profile_

Activity | Points
-- | --
Acquired habit per 14 days | 20
Acquired habit per 21 days | 30
Acquired habit per 30+ days | 40
Days of habit in progress | 1 point per 1 day
Created news | 20
Added tips & tricks | 10
Comment or reply | 2
Like comment or reply | 1
Share news or tips & tricks | 10
First 5 achievements | 20
First 10 achievements | 30
First 15 achievements | 40
First 20 achievements | 50

**Acceptance Criteria:**

1. User can see ‘Rate’ based on his/her activities
2. When user acquired habit by himself, he/she gets the appropriate
points amount
3. When user acquired habit together with friends, he/she gets the
appropriate points amount multiplied by number of friends who
were involved
4. If the habit was NOT acquired user does not get any points from
acceptance criteria 2 or 3
5. User gets 1 point for each day of habits in progress
6. Points from acceptance criteria 5 saves even if habit was NOT
acquired
7. User gets 20 points for each created news
8. User gets 10 points for each created tips&amp;tricks
9. User gets 2 points for each comment or reply for a comment
10. User gets 1 point for each like of comment or reply for a
comment
11. User gets 10 points for share news or tips&amp;tricks on his/her
social networks
12. User gets appropriate points amount for number of
achievements he/she successfully passed

**Comment by TarasDovganyuk** [comment]
Need to add calculation for achievment and habits and sharing
